Repository ravendb/ravendb, pull requests merged in 2018-10, with the labels that each got.

#7666 RavenDB-11931 Exception when loading the view of auto map index
  src/Raven.Studio/typescript/viewmodels/database/indexes/editIndex.ts
Labels: v4.1

#7665 RavenDB_11891 Additional test case
  test/SlowTests/Server/Documents/ETL/RavenDB_11891.cs
Labels: v4.1

#7667 RavenDB-12005 fixed LastIndexOf and LastIndexOfAny implementation in LazyStringValue
  src/Sparrow/Json/LazyStringValue.cs
  test/SlowTests/Bugs/EntityWithStack.cs
  test/SlowTests/Issues/RavenDB_12005.cs
Labels: v4.0

#7668 RavenDB-12005 fixed LastIndexOf and LastIndexOfAny implementation in LazyStringValue
  src/Sparrow/Json/LazyStringValue.cs
  test/SlowTests/Bugs/EntityWithStack.cs
  test/SlowTests/Issues/RavenDB_12005.cs
Labels: v4.1

#7635 RavenDB-11975 don't store issuers from certificate chains
  src/Raven.Server/Web/Authentication/AdminCertificatesHandler.cs
Labels: v4.0

#7643 RavenDB-11975 don't store issuers from certificate chains
  src/Raven.Server/Web/Authentication/AdminCertificatesHandler.cs
Labels: v4.1

#7664 [4.1] RavenDB-12016 - No upload progress when importing a database
  src/Raven.Studio/typescript/commands/commandBase.ts
  src/Raven.Studio/typescript/commands/database/studio/importDatabaseCommand.ts
  src/Raven.Studio/typescript/commands/database/studio/importFromCsvCommand.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/importCollectionFromCsv.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/importDatabaseFromFile.ts
Labels: v4.1

#7663 [4.0] RavenDB-12016 - No upload progress when importing a database
  src/Raven.Studio/typescript/commands/commandBase.ts
Labels: v4.0

#7674 RavenDB-11827 session.Advanced.Increment should check for 'null'
  src/Raven.Client/Documents/Session/InMemoryDocumentSessionOperations.Patch.cs
  test/SlowTests/Issues/RavenDB_11827.cs
Labels: v4.0

#7673 RavenDB-11827 session.Advanced.Increment should check for 'null'
  src/Raven.Client/Documents/Session/InMemoryDocumentSessionOperations.Patch.cs
  test/SlowTests/Issues/RavenDB_11827.cs
Labels: v4.1

#7679 RavenDB-11692 flaky tests
  CommonAssemblyInfo.cs
  Raven.Tests.Bundles/LiveTest/StartupTaskTests.cs
  Raven.Tests.Issues/RavenDB_2129.cs
  Raven.Tests.Issues/RavenDB_2556.cs
  Raven.Tests.Issues/RavenDB_2699.cs
  Raven.Tests.Issues/RavenDB_3109.cs
  Raven.Tryouts/Program.cs
  Raven.Tryouts/Raven.Tryouts.csproj
Labels: v3.5

#7675 RavenDB-7836: Added system / db directory validation before using offline-operations
  tools/rvn/CommandLineApp.cs
Labels: v4.1

#7688 RavenDB-11917 Fix failing test DisableExternalReplication
  src/Raven.Server/Documents/Replication/OutgoingReplicationHandler.cs
  test/SlowTests/Server/Replication/ReplicationBasicTestsSlow.cs
Labels: v4.1

#7696 RavenDB-12033 Fixed NRE. We no longer needs files to be collection, w…
  src/Voron/Impl/PagerState.cs
Labels: v4.1

#7697 RavenDB-11815 support for nested group by values in multi-map indexes
  src/Raven.Server/Documents/Indexes/CompiledIndexField.cs
  src/Raven.Server/Documents/Indexes/Static/Roslyn/Rewriters/RewritersHelper.cs
  src/Raven.Server/Documents/Indexes/Static/StaticIndexBase.cs
  src/Raven.Server/Utils/TypeConverter.cs
  test/SlowTests/Issues/RavenDB_11815.cs
  test/SlowTests/Server/RecordingTransactionOperationsMergerTests.cs
Labels: v4.1

#7701 RavenDB-11692 sibling propagation timer should fire in interval, not once
  Raven.Database/Bundles/Replication/Tasks/ReplicationTask.cs
  Raven.Tryouts/Program.cs
Labels: v3.5

#7707 RavenDB-11988
  src/Raven.Client/Documents/Linq/RavenQueryProviderProcessor.cs
  test/SlowTests/Issues/RavenDB-11988.cs
Labels: v4.1

#7706 RavenDB-12030 support for Fuzzy and Proximity
  src/Raven.Client/Documents/Session/AbstractDocumentQuery.cs
  src/Raven.Server/Documents/Queries/MethodType.cs
  src/Raven.Server/Documents/Queries/QueryBuilder.cs
  src/Raven.Server/Documents/Queries/QueryMetadata.cs
  src/Raven.Server/Documents/Queries/QueryMethod.cs
  test/SlowTests/Issues/RavenDB_12030.cs
Labels: v4.1

#7711 RavenDB-12025 Reduce the deserialization costs in the cluster observer
  src/Raven.Server/Config/RavenConfiguration.cs
  src/Raven.Server/Json/JsonDeserializationServer.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterMaintenanceWorker.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterObserver.cs
  test/FastTests/Server/Documents/Indexing/Auto/BasicAutoMapIndexing.cs
Labels: v4.1

#7715 RavenDB-12025 Fix NRE and InvalidCast
  src/Raven.Server/ServerWide/Maintenance/ClusterObserver.cs
Labels: v4.1

#7716 RavenDB-12025 Improve low memory handler performance
  src/Raven.Server/Dashboard/MachineResourcesNotificationSender.cs
  src/Raven.Server/Utils/CpuUsage.cs
  src/Sparrow/LowMemory/LowMemoryNotification.cs
Labels: v4.1

#7717 RavenDB-12025 added safe checks in ReadDeletionInProgress
  src/Raven.Server/ServerWide/Maintenance/ClusterObserver.cs
Labels: v4.1

#7718 RavenDB-12046 Use GetNodeHttpServerUrl() instead of WebUrl
  src/Raven.Server/Utils/Cli/RavenCli.cs
  src/Raven.Server/Web/RequestHandler.cs
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
  test/SlowTests/Issues/RavenDB-11372.cs
Labels: v4.1

#7721 [4.0] RavenDB-12057 - Can't stop an import when documents are skipped
  src/Raven.Server/Smuggler/Documents/CsvStreamSource.cs
  src/Raven.Server/Smuggler/Documents/Data/ISmugglerSource.cs
  src/Raven.Server/Smuggler/Documents/DatabaseSmuggler.cs
  src/Raven.Server/Smuggler/Documents/DatabaseSource.cs
  src/Raven.Server/Smuggler/Documents/StreamSource.cs
Labels: v4.0

#7724 RavenDB-12056 support predicate for LINQ Count in projection
  src/Raven.Client/Util/JavascriptConversionExtensions.cs
  test/SlowTests/Issues/RavenDB_12056.cs
Labels: v4.0

#7723 RavenDB-12056 support predicate for LINQ Count in projection
  src/Raven.Client/Util/JavascriptConversionExtensions.cs
  test/SlowTests/Issues/RavenDB_12056.cs
Labels: v4.1

#7712 Fix for RavenDB-12041
  Raven.Database/Smuggler/DatabaseDataDumper.cs
  Raven.Database/Smuggler/SmugglerDatabaseApi.cs
  Raven.Database/Smuggler/SmugglerDatabaseBetweenOperation.cs
Labels: v3.5

#7720 RavenDB-12025 Reduce dashboard resource utilization in idle work
  src/Raven.Server/Dashboard/DatabasesInfoNotificationSender.cs
Labels: v4.1

#7729 RavenDB-12063 Fix the possibility of skipping documents for indexing …
  src/Raven.Server/Documents/Indexes/IndexStorage.cs
Labels: v4.0

#7728 RavenDB-12063 Fix the possibility of skipping documents for indexing …
  src/Raven.Server/Documents/Indexes/IndexStorage.cs
  test/Tryouts/Program.cs
Labels: v4.1

#7738 RavenDB-12068 ensure null coalescing is surrounded with parenthesis
  src/Raven.Client/Util/JavascriptConversionExtensions.cs
  test/SlowTests/Client/QueriesWithCustomFunctions.cs
  test/SlowTests/Issues/RavenDB-10625.cs
  test/SlowTests/Issues/RavenDB_12068.cs
Labels: v4.0

#7737 RavenDB-12068 ensure null coalescing is surrounded with parenthesis
  src/Raven.Client/Util/JavascriptConversionExtensions.cs
  test/SlowTests/Client/QueriesWithCustomFunctions.cs
  test/SlowTests/Issues/RavenDB-10625.cs
  test/SlowTests/Issues/RavenDB_12068.cs
Labels: v4.1

#7742 RavenDB-12070 NullReferenceException access to notifications before t…
  src/Raven.Server/RavenServerStartup.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Sparrow/AsyncManualResetEvent.cs
Labels: v4.1

#7743 RavenDB-12055 Could not reach any node of 'test' database
  src/Raven.Server/ServerWide/Maintenance/ClusterMaintenanceWorker.cs
Labels: v4.1

#7741 RavenDB-12023 - fix top threads usage display in linux
  src/Raven.Server/Program.cs
Labels: v4.1

#7750 RavenDB-11932 Search inside counters doesn't work
  src/Raven.Studio/typescript/viewmodels/database/documents/editDocumentConnectedDocuments.ts
Labels: v4.1

#7749 RavenDB-11976 [Dashboard] Storage pie on dashboard does not highlight…
  src/Raven.Studio/gulp/paths.js
  src/Raven.Studio/typescript/models/resources/serverDashboard/storagePieChart.ts
  src/Raven.Studio/typings/_studio/customTypings.d.ts
  src/Raven.Studio/wwwroot/index.html
  test/Studio/test.html
Labels: v4.1

#7751 RavenDB-12045 Allow to filter failed requests only in traffic watch
  src/Raven.Studio/typescript/viewmodels/manage/trafficWatch.ts
  src/Raven.Studio/wwwroot/App/views/manage/trafficWatch.html
Labels: v4.1

#7755 RavenDB-11643 Fixing tree rebalancing on compressed trees what result…
  src/Voron/Data/BTrees/Tree.cs
  src/Voron/Data/BTrees/TreeRebalancer.cs
  test/SlowTests/Voron/Issues/RavenDB_11643_Voron.cs
Labels: v4.1

#7754 RavenDB-11643 Fixing tree rebalancing on compressed trees what result…
  src/Voron/Data/BTrees/Tree.cs
  src/Voron/Data/BTrees/TreeRebalancer.cs
  test/SlowTests/Voron/Issues/RavenDB_11643_Voron.cs
Labels: v4.0

#7752 RavenDB-11953 Failed to get index entries in query page
  src/Raven.Studio/typescript/commands/database/index/getIndexEntriesFieldsCommand.ts
  src/Raven.Studio/typescript/common/queryCompleter.ts
  src/Raven.Studio/typescript/common/queryUtil.ts
Labels: v4.1

#7744 Fix memory leak (RavenDB-12058)
  src/Sparrow/Json/UnmanagedBuffersPool.cs
Labels: v4.1

#7757 RavenDB-11834 better error when defining an index
  src/Raven.Server/Documents/Indexes/Static/Roslyn/Rewriters/CaptureSelectNewFieldNamesVisitor.cs
Labels: v4.2

#7766 RavenDB-11963 Search in patch testing doesn't list all available docu…
  src/Raven.Studio/typescript/common/queryUtil.ts
  src/Raven.Studio/typescript/viewmodels/database/patch/docsIdsBasedOnQueryFetcher.ts
  src/Raven.Studio/typescript/viewmodels/database/patch/patch.ts
  src/Raven.Studio/typescript/viewmodels/database/patch/patchTester.ts
  src/Raven.Studio/typescript/viewmodels/database/query/query.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editRavenEtlTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editSqlEtlTask.ts
Labels: v4.1

#7768 RavenDB-7070 updated packages
  src/Raven.Client/Raven.Client.csproj
Labels: v4.0

#7769 RavenDB-7070 updated packages
  src/Raven.Client/Raven.Client.csproj
  test/FastTests/Server/Documents/Indexing/Auto/BasicAutoMapIndexing.cs
  test/SlowTests/Blittable/SerializeAndDeserializeMergedTransactionCommandTests.cs
  tools/Raven.Migrator/Raven.Migrator.csproj
Labels: v4.1

#7770 RavenDB-11650 add paging to RQL for better server-side metadata caching
  src/Raven.Client/Documents/Session/AbstractDocumentQuery.cs
  src/Raven.Server/Documents/Queries/IndexQueryServerSide.cs
  src/Raven.Server/Documents/Queries/QueryBuilder.cs
  test/SlowTests/Tests/Linq/RavenDB14.cs
Labels: v4.2

#7773 RavenDB-11863 In studio, in subscriptions view, we do not receive cli…
  src/Raven.Studio/typescript/commands/database/tasks/getSubscriptionConnectionDetailsCommand.ts
  src/Raven.Studio/typescript/models/database/tasks/ongoingTaskSubscriptionListModel.ts
Labels: v4.1

#7774 RavenDB-11583 Introduce object pooling to BlittableObjectReader
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/Fields/BlittableObjectReader.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/Fields/BlittableObjectReaderPool.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/Fields/CachedFieldItem.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/LuceneDocumentConverterBase.cs
Labels: v4.2

#7777 RavenDB-7070 updated packages
  src/Raven.Server/Raven.Server.csproj
Labels: v4.0

#7778 RavenDB-7070 updated packages
  src/Raven.Server/Raven.Server.csproj
Labels: v4.1

#7786 RavenDB-9995 added test
  test/SlowTests/Issues/RavenDB_9995.cs
Labels: v4.2

#7788 RavenDB-12098: Catch EarlyOOM too in TxMerger to prevent TxMerger fro…
  src/Raven.Server/Documents/TransactionOperationsMerger.cs
Labels: v4.1

#7791 RavenDB-12098: Catch EarlyOOM too in TxMerger to prevent TxMerger fro…
  src/Raven.Server/Documents/TransactionOperationsMerger.cs
Labels: v4.0

#7789 RavenDB-12099: Raise once LowMem event on Early OOM in order to run c…
  src/Sparrow/LowMemory/LowMemoryNotification.cs
  src/Sparrow/LowMemory/MemoryInformation.cs
Labels: v4.1

#7792 RavenDB-12099: Raise once LowMem event on Early OOM in order to run c…
  src/Sparrow/LowMemory/LowMemoryNotification.cs
  src/Sparrow/LowMemory/MemoryInformation.cs
Labels: v4.0

#7781 RavenDB-12072 - Allow to filter on graph edges
  src/Raven.Server/Documents/Queries/AST/QueryExpression.cs
  src/Raven.Server/Documents/Queries/GraphQueryRunner.cs
  src/Sparrow/Json/LazyNumberValue.cs
  src/Sparrow/StringSegment.cs
  test/FastTests/Graph/GraphQueries.cs
Labels: v4.2

#7801 RavenDB-12109 - Traffic watch doesn't display errors as errors in the studio
  src/Raven.Server/RavenServerStartup.cs
  src/Raven.Server/Routing/RequestRouter.cs
Labels: v4.0

#7800 RavenDB-12109 - Traffic watch doesn't display errors as errors in the studio
  src/Raven.Server/RavenServerStartup.cs
  src/Raven.Server/Routing/RequestRouter.cs
Labels: v4.1

#7806 RavenDB-12120 - Compact crashes the studio
  src/Voron/Impl/Compaction/StorageCompaction.cs
Labels: v4.1

#7807 RavenDB-12116 Verify if firefox supports line breaks in textarea
  src/Raven.Studio/typescript/common/placeholderUtils.ts
  src/Raven.Studio/typescript/viewmodels/shell/registration.ts
  src/Raven.Studio/typescript/viewmodels/wizard/license.ts
Labels: v4.1

#7811 RavenDB-12123 Fixing race condition in test - we need to bind to OnIn…
  test/SlowTests/Issues/RavenDB_10744.cs
Labels: v4.0

#7812 RavenDB-12123 Fixing race condition in test - we need to bind to OnIn…
  test/SlowTests/Issues/RavenDB_10744.cs
Labels: v4.1

#7815 RavenDB-11977 Consider saving custom columns order on documents view.
  src/Raven.Studio/typescript/common/storage/storageKeyProvider.ts
  src/Raven.Studio/typescript/models/resources/serverDashboard/driveUsage.ts
  src/Raven.Studio/typescript/viewmodels/database/documents/documents.ts
  src/Raven.Studio/typescript/viewmodels/database/query/query.ts
  src/Raven.Studio/typescript/viewmodels/manage/debugAdvancedMemoryMappedFiles.ts
  src/Raven.Studio/typescript/viewmodels/manage/debugAdvancedObserverLog.ts
  src/Raven.Studio/typescript/viewmodels/manage/debugAdvancedThreadsRuntime.ts
  src/Raven.Studio/typescript/viewmodels/partial/columnsSelector.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/columns/actionColumn.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/columns/checkedColumn.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/columns/customColumn.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/columns/flagsColumn.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/columns/hyperlinkColumn.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/columns/providers/documentBasedColumnsProvider.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/columns/textColumn.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/columns/virtualColumn.ts
  src/Raven.Studio/typings/_studio/dto.d.ts
  src/Raven.Studio/wwwroot/App/views/database/documents/documents.html
  src/Raven.Studio/wwwroot/App/views/partial/columnsSelector.html
Labels: v4.1

#7813 RavenDB-12128 Support for collection queries with StartsWith() and Co…
  src/Raven.Server/Documents/Queries/CollectionQueryEnumerable.cs
  test/SlowTests/Issues/RavenDB_12128.cs
Labels: v4.0

#7814 RavenDB-12128 Support for collection queries with StartsWith() and Co…
  src/Raven.Server/Documents/Queries/CollectionQueryEnumerable.cs
  test/SlowTests/Issues/RavenDB_12128.cs
Labels: v4.1

#7822 RavenDB-12126 QueryParser.Parse chokes when with single quote in comm…
  src/Raven.Server/Documents/Queries/Parser/QueryScanner.cs
  test/FastTests/Issues/RavenDB-12126.cs
Labels: v4.0

#7820 RavenDB-12126 QueryParser.Parse chokes when with single quote in comm…
  src/Raven.Server/Documents/Queries/Parser/QueryScanner.cs
  test/FastTests/Issues/RavenDB-12126.cs
Labels: v4.1

#7819 RavenDB-12101
  src/Raven.Client/Documents/Linq/RavenQueryProviderProcessor.cs
  test/SlowTests/Issues/RavenDB-12101.cs
Labels: v4.1

#7828 RavenDB-12024: v4.1 ported to v4.0.
  src/Raven.Client/Constants.cs
  src/Raven.Server/Documents/ETL/EtlProcess.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/MapReduce/MapReduceResultsStore.cs
  src/Raven.Server/Documents/Indexes/Static/DynamicBlittableJson.cs
  src/Raven.Server/Documents/Patch/ScriptRunner.cs
  src/Raven.Server/Documents/Queries/Dynamic/CollectionQueryRunner.cs
  src/Raven.Server/ServerWide/Memory/MemoryUsageGuard.cs
  src/Sparrow/Json/JsonContextPoolBase.cs
  src/Sparrow/Json/JsonOperationContext.cs
  src/Voron/Impl/Paging/Windows32BitsMemoryMapPager.cs
  test/FastTests/Server/Documents/Indexing/Auto/BasicAutoMapReduceIndexing.cs
  test/SlowTests/Issues/RavenDB_10382.cs
  test/SlowTests/Issues/RavenDB_10621.cs
  test/SlowTests/Issues/RavenDB_11904.cs
  test/SlowTests/Issues/RavenDB_11905.cs
  test/SlowTests/Server/Documents/Indexing/Debugging/RavenDB_5577.cs
  test/SlowTests/Server/Documents/Indexing/MapReduce/RavenDB_5383.cs
  test/SlowTests/SlowTests/Bugs/VeryBigResultSet.cs
  test/SlowTests/Voron/LargeValues.cs
  test/SlowTests/Voron/MemoryMapWithoutBackingPagerTest.cs
  test/SlowTests/Voron/RecoveryMultipleJournals.cs
  test/StressTests/Client/Attachments/AttachmentsHugeFiles.cs
  test/StressTests/Client/Attachments/AttachmentsSessionAsyncStress.cs
  test/StressTests/Client/Attachments/AttachmentsSessionStress.cs
  test/StressTests/Databases.cs
  test/StressTests/Voron/HugeTransactions.cs
  test/Tests.Infrastructure/Fact32BitAttribute.cs
  test/Tests.Infrastructure/Fact64BitAttribute.cs
  test/Tests.Infrastructure/NightlyBuildFact32BitAttribute.cs
  test/Tests.Infrastructure/NightlyBuildFact64BitAttribute.cs
  test/Tests.Infrastructure/NightlyBuildTheory32BitAttribute.cs
  test/Tests.Infrastructure/NightlyBuildTheory64BitAttribute.cs
  test/Tests.Infrastructure/Theory32BitAttribute.cs
  test/Tests.Infrastructure/Theory64BitAttribute.cs
  test/Tests.Infrastructure/TheoryAndSkipWhen32BitsEnvironment.cs
Labels: v4.0

#7836 RavenDB-12143 Recyclable journals should be counted as temporary files
  src/Voron/Debugging/StorageReportGenerator.cs
  src/Voron/StorageEnvironment.cs
Labels: v4.1

#7837 RavenDB-12143 Recyclable journals should be counted as temporary files
  src/Voron/Debugging/StorageReportGenerator.cs
  src/Voron/StorageEnvironment.cs
Labels: v4.0

#7832 RavenDB-12122 Don't use size of blittable when calculating the hash c…
  src/Sparrow/Json/BlittableJsonReaderObject.cs
  test/FastTests/Blittable/BlittableJsonEqualityTests.cs
Labels: v4.0

#7833 RavenDB-12122 Don't use size of blittable when calculating the hash c…
  src/Sparrow/Json/BlittableJsonReaderObject.cs
  test/FastTests/Blittable/BlittableJsonEqualityTests.cs
Labels: v4.1

#7835 Edge aliases projections and untyped document aliases
  src/Raven.Server/Documents/Document.cs
  src/Raven.Server/Documents/Queries/AST/GraphQuery.cs
  src/Raven.Server/Documents/Queries/AST/Query.cs
  src/Raven.Server/Documents/Queries/AST/QueryVisitor.cs
  src/Raven.Server/Documents/Queries/AST/StringQueryVisitor.cs
  src/Raven.Server/Documents/Queries/AST/WithEdgesExpression.cs
  src/Raven.Server/Documents/Queries/Dynamic/CollectionQueryRunner.cs
  src/Raven.Server/Documents/Queries/GraphQueryRunner.IntermediateResults.cs
  src/Raven.Server/Documents/Queries/GraphQueryRunner.Match.cs
  src/Raven.Server/Documents/Queries/GraphQueryRunner.cs
  src/Raven.Server/Documents/Queries/Parser/QueryParser.cs
  src/Raven.Server/Documents/Queries/QueryMetadata.cs
  src/Raven.Server/Documents/Queries/Results/GraphQueryResultRetriever.cs
  src/Raven.Server/Utils/IncludeUtil.cs
  src/Sparrow/StringSegment.cs
  test/FastTests/Graph/GraphQueries.cs
  test/FastTests/Graph/SimpleGraphQueries.cs
Labels: v4.2

#7844 RavenDB-12024-2_v4.1: Added single allocation size limit when running on 32 bits
  src/Sparrow/Json/ArenaMemoryAllocator.cs
  src/Sparrow/Utils/NativeMemory.cs
  test/SlowTests/Voron/Issues/RavenDB_11643_Voron.cs
Labels: v4.1

#7845 RavenDB-11666 enhance exception message cannot delete doc due to existing tombstone
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/ETL/EtlProcess.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/Documents/TombstoneCleaner.cs
  test/SlowTests/Issues/RavenDB_10656.cs
  test/SlowTests/Server/Documents/Indexing/MapReduce/OutputReduceToCollectionReplicationTests.cs
  test/SlowTests/Server/Documents/Revisions/RevisionsReplication.cs
Labels: v4.2

#7853 RavenDB-12077
  src/Raven.Client/Documents/Session/Operations/QueryOperation.cs
Labels: v4.1

#7862 RavenDB-11690 [UX] Documents view - Add ability to query displayed co…
  src/Raven.Studio/typescript/common/queryCompleter.ts
  src/Raven.Studio/typescript/common/queryUtil.ts
  src/Raven.Studio/typescript/models/database/documents/collection.ts
  src/Raven.Studio/typescript/viewmodels/database/documents/documents.ts
  src/Raven.Studio/wwwroot/App/views/database/documents/documents.html
Labels: v4.2

#7860 RavenDB-9388 Query page - different L&F for buttons before and after …
  src/Raven.Studio/wwwroot/App/views/database/query/query.html
Labels: v4.2

#7859 RavenDB-11252 Indexing progress set to 100% during index disable
  src/Raven.Studio/typescript/models/database/index/index.ts
  src/Raven.Studio/typescript/models/database/index/indexProgress.ts
  src/Raven.Studio/wwwroot/App/views/database/indexes/indexes.html
Labels: v4.2

#7858 RavenDB-7013 Indexing Performance Graph: Add 'Map' & 'Reduce' on the …
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexPerformance.ts
Labels: v4.2

#7857 RavenDB-12129 bump version in 4.2 studio
  src/Raven.Studio/mockups/src/license-modal.html
  src/Raven.Studio/mockups/src/partials/footer.html
  src/Raven.Studio/typescript/commands/commandBase.ts
  src/Raven.Studio/typescript/common/storage/storageKeyProvider.ts
  src/Raven.Studio/wwwroot/App/views/manage/certificates.html
  src/Raven.Studio/wwwroot/App/views/resources/createDatabase.html
  src/Raven.Studio/wwwroot/App/views/wizard/setupShell.html
Labels: v4.2

#7865 RavenDB-10261 Documents View - Add custom column - Missing validation…
  src/Raven.Studio/wwwroot/Content/css/styles.less
Labels: v4.2

#7864 RavenDB-12163 - Add IndexWriter allocated memory
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/MapReduce/ReduceMapResultsBase.cs
  src/Raven.Server/Documents/Indexes/Workers/CleanupDeletedDocuments.cs
  src/Raven.Server/Documents/Indexes/Workers/HandleReferences.cs
  src/Raven.Server/Documents/Indexes/Workers/IIndexingWork.cs
  src/Raven.Server/Documents/Indexes/Workers/MapDocuments.cs
Labels: v4.1

#7863 RavenDB-12163 - Add IndexWriter allocated memory
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/MapReduce/ReduceMapResultsBase.cs
  src/Raven.Server/Documents/Indexes/Workers/CleanupDeletedDocuments.cs
  src/Raven.Server/Documents/Indexes/Workers/HandleReferences.cs
  src/Raven.Server/Documents/Indexes/Workers/IIndexingWork.cs
  src/Raven.Server/Documents/Indexes/Workers/MapDocuments.cs
Labels: v4.0

#7870 RavenDB-11618 Show the identities in the studio
  src/Raven.Studio/typescript/commands/database/debug/getIdentitiesCommand.ts
  src/Raven.Studio/typescript/viewmodels/database/status/statistics.ts
  src/Raven.Studio/wwwroot/App/views/database/status/statistics.html
Labels: v4.2

#7871 RavenDB-10842 Add percentiles to traffic watch
  src/Raven.Studio/typescript/viewmodels/manage/trafficWatch.ts
  src/Raven.Studio/wwwroot/App/views/manage/trafficWatch.html
  src/Raven.Studio/wwwroot/Content/css/pages/traffic-watch.less
  src/Raven.Studio/wwwroot/Content/css/styles.less
Labels: v4.2

#7872 RavenDB-12182 Can't add node to cluster
  src/Raven.Server/Web/System/SetupHandler.cs
  src/Raven.Studio/typescript/models/wizard/nodeInfo.ts
  src/Raven.Studio/typescript/models/wizard/unsecureSetup.ts
  src/Raven.Studio/wwwroot/App/views/wizard/unsecured.html
Labels: v4.1

#7874 RavenDB-8493 Import database with Expired Documents
  src/Raven.Studio/wwwroot/App/views/database/tasks/importDatabaseFromFile.html
Labels: v4.2

#7875 RavenDB-12024-2_v4.0: Using buffer.copy for overlapped blocks
  src/Sparrow/Json/ArenaMemoryAllocator.cs
  src/Sparrow/Json/Parsing/JsonParserState.cs
  src/Sparrow/Memory.cs
  src/Sparrow/Utils/NativeMemory.cs
  test/SlowTests/SlowTests/Bugs/VeryBigResultSet.cs
  test/SlowTests/Voron/Issues/RavenDB_11643_Voron.cs
Labels: v4.0

#7876 RavenDB-12172 add import option to skip server certificate validation
  src/Raven.Server/Smuggler/Migration/AbstractLegacyMigrator.cs
  src/Raven.Server/Smuggler/Migration/AbstractMigrator.cs
  src/Raven.Server/Smuggler/Migration/ApiKey/Authenticator.cs
  src/Raven.Server/Smuggler/Migration/MigrationConfiguration.cs
  src/Raven.Server/Smuggler/Migration/Migrator.cs
  src/Raven.Server/Smuggler/Migration/MigratorOptions.cs
  src/Raven.Server/Web/System/DatabasesHandler.cs
  src/Raven.Studio/typescript/commands/database/studio/getRemoteServerVersionWithDatabasesCommand.ts
  src/Raven.Studio/typescript/models/database/tasks/migrateRavenDbDatabaseModel.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/migrateRavenDbDatabase.ts
  src/Raven.Studio/wwwroot/App/views/database/tasks/migrateRavenDbDatabase.html
Labels: v4.1

#7882 RavenDB-12151 Fixing counting the number of pages modified in a trans…
  src/Voron/Impl/LowLevelTransaction.cs
  test/SlowTests/Voron/Issues/RavenDB_12151.cs
Labels: v4.0

#7885 RavenDB-12194 Fixing JsonNetBlittableEntitySerializer - _customize fi…
  src/Raven.Client/Documents/Conventions/JsonNetBlittableEntitySerializer.cs
  test/SlowTests/Issues/RavenDB_12194.cs
Labels: v4.0

#7886 RavenDB-12194 Fixing JsonNetBlittableEntitySerializer - _customize fi…
  src/Raven.Client/Documents/Conventions/JsonNetBlittableEntitySerializer.cs
  test/SlowTests/Issues/RavenDB_12194.cs
Labels: v4.1

#7888 RavenDB-12194
  src/Raven.Client/Documents/Conventions/JsonNetBlittableEntitySerializer.cs
Labels: v4.0

#7889 RavenDB-12194
  src/Raven.Client/Documents/Conventions/JsonNetBlittableEntitySerializer.cs
Labels: v4.1

#7887 RavenDB-8487 Normalize help icons
  src/Raven.Studio/wwwroot/App/views/database/indexes/editIndex.html
  src/Raven.Studio/wwwroot/App/views/database/patch/patch.html
  src/Raven.Studio/wwwroot/App/views/database/query/query.html
  src/Raven.Studio/wwwroot/App/views/database/settings/conflictResolution.html
  src/Raven.Studio/wwwroot/App/views/database/status/statistics.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editPeriodicBackupTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editRavenEtlTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editSqlEtlTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editSubscriptionTask.html
  src/Raven.Studio/wwwroot/App/views/resources/serverDashboard.html
  src/Raven.Studio/wwwroot/Content/css/pages/stats.less
Labels: v4.2

#7892 RavenDB-12197 - Matching graph queries syntax to the rest of RQL
  src/Raven.Server/Documents/Queries/AST/GraphQuery.cs
  src/Raven.Server/Documents/Queries/AST/Query.cs
  src/Raven.Server/Documents/Queries/AST/QueryVisitor.cs
  src/Raven.Server/Documents/Queries/AST/StringQueryVisitor.cs
  src/Raven.Server/Documents/Queries/AST/WithEdgesExpression.cs
  src/Raven.Server/Documents/Queries/GraphQueryRunner.Match.cs
  src/Raven.Server/Documents/Queries/GraphQueryRunner.cs
  src/Raven.Server/Documents/Queries/Parser/QueryParser.cs
  src/Raven.Server/Documents/Queries/Parser/QueryScanner.cs
  test/FastTests/Graph/AdvancedGraphQueries.cs
  test/FastTests/Graph/BasicGraphQueries.cs
  test/FastTests/Graph/IntersectionTests.cs
  test/FastTests/Graph/Parsing.cs
  test/FastTests/Graph/VerticesFromIndexes.cs
Labels: v4.2

#7890 RavenDB-12143 The recyclable journals need to be counted as temporary…
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Voron/Debugging/DetailedStorageReport.cs
  src/Voron/Debugging/StorageReportGenerator.cs
Labels: v4.0

#7891 RavenDB-12143 The recyclable journals need to be counted as temporary…
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Voron/Debugging/DetailedStorageReport.cs
  src/Voron/Debugging/StorageReportGenerator.cs
Labels: v4.1

#7899 RavenDB-12207 fixed collection name detection when WhereEntityIs is used
  src/Raven.Server/Documents/Indexes/Static/Roslyn/Rewriters/CollectionNameRetriever.cs
  test/SlowTests/Issues/RavenDB_12207.cs
Labels: v4.1

#7903 RavenDB-12182 Can't add node to cluster - fix
  src/Raven.Studio/typescript/models/wizard/serverSetup.ts
Labels: v4.1

#7900 RavenDB-12171 Studio: Notification bar - convert new lines to <br/> w…
  src/Raven.Studio/typescript/common/notifications/models/abstractNotification.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/virtualGridUtils.ts
  src/Raven.Studio/wwwroot/App/views/notifications/notificationCenter.html
Labels: v4.2

#7898 RavenDB-12105 Studio should remember the last path of database creati…
  src/Raven.Studio/typescript/common/storage/lastUsedAutocomplete.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/migrateDatabase.ts
  src/Raven.Studio/typescript/viewmodels/resources/createDatabase.ts
  src/Raven.Studio/wwwroot/App/views/database/tasks/migrateDatabase.html
  src/Raven.Studio/wwwroot/App/views/resources/createDatabase.html
Labels: v4.2

#7905 RavenDB-12129 bump version in 4.2 studio
  src/Raven.Studio/typescript/viewmodels/resources/createDatabase.ts
  src/Raven.Studio/wwwroot/App/views/manage/certificates.html
  src/Raven.Studio/wwwroot/App/views/resources/createDatabase.html
  src/Raven.Studio/wwwroot/App/views/wizard/setupShell.html
  src/Raven.Studio/wwwroot/version.txt
Labels: v4.2

#7908 RavenDB-12143 Recyclable journals should be counted as temporary files
  src/Raven.Studio/typescript/models/database/status/storageReportItem.ts
  src/Raven.Studio/typescript/viewmodels/database/status/storageReport.ts
  src/Raven.Studio/wwwroot/App/views/database/status/storageReport.html
Labels: v4.0

#7906 Implementing recursive queries in graphs
  src/Raven.Server/Documents/Queries/AST/PatternMatchElementExpression.cs
  src/Raven.Server/Documents/Queries/GraphQueryRunner.Visitor.Intersection.cs
  src/Raven.Server/Documents/Queries/GraphQueryRunner.Visitor.cs
  src/Raven.Server/Documents/Queries/GraphQueryRunner.cs
  src/Raven.Server/Documents/Queries/Parser/QueryParser.cs
  src/Raven.Server/Documents/Queries/Parser/QueryScanner.cs
  test/FastTests/Graph/AdvancedGraphQueries.cs
  test/FastTests/Graph/BasicGraphQueries.cs
Labels: v4.2

#7910 Tests for RavenDB-12191 (WIP, some more tests are needed)
  test/FastTests/Graph/AdvancedGraphQueries.cs
Labels: v4.2

#7916 RavenDB-9479: Write EscapeCharacters ported from v4.0.
  src/Raven.Server/Documents/DocumentIdWorker.cs
  src/Sparrow/Json/BlittableJsonReaderObject.cs
  src/Sparrow/Json/BlittableJsonTextWriter.cs
  src/Sparrow/Json/BlittableWriter.cs
  src/Sparrow/Json/JsonOperationContext.cs
  src/Sparrow/Json/Parsing/JsonParserState.cs
  src/Sparrow/Json/Parsing/ObjectJsonParser.cs
  src/Sparrow/Json/Parsing/UnmanagedJsonParser.cs
  test/FastTests/Blittable/BlittableJsonWriterTests/ManualBuilderTests.cs
  test/FastTests/Server/Documents/Indexing/Lucene/LazyStringValueReaderTests.cs
  test/SlowTests/Issues/RavenDB-9479.cs
Labels: v4.1

#7915 RavenDB-12208 converting WhereEntityIs to a MultiMap index
  src/Raven.Server/Documents/Indexes/Static/IndexCompiler.cs
  src/Raven.Server/Documents/Indexes/Static/Roslyn/MapFunctionProcessor.cs
  src/Raven.Server/Documents/Indexes/Static/Roslyn/Rewriters/CollectionNameRetriever.cs
Labels: v4.2

#7914 RavenDB-9864 Map/reduce visualizer when reduce results are VERY large
  src/Raven.Studio/typescript/common/helpers/graph/graphHelper.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/visualizer/visualizerGraphDetails.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/visualizer/visualizerGraphGlobal.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/visualizer/visualizerTreeExplorer.ts
  src/Raven.Studio/wwwroot/App/views/database/indexes/visualizer/visualizerTreeExplorer.html
Labels: v4.2

#7918 RavenDB-7070 updated packages
  bench/Micro.Benchmark/Micro.Benchmark.csproj
  bench/Regression.Benchmark/Regression.Benchmark.csproj
  src/Raven.Server/Raven.Server.csproj
  test/BenchmarkTests/BenchmarkTests.csproj
  test/EmbeddedTests/EmbeddedTests.csproj
  test/FastTests/FastTests.csproj
  test/InterversionTests/InterversionTests.csproj
  test/RachisTests/RachisTests.csproj
  test/SlowTests/SlowTests.csproj
  test/StressTests/StressTests.csproj
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
Labels: v4.1

#7917 RavenDB-7070 updated packages
  bench/Micro.Benchmark/Micro.Benchmark.csproj
  bench/Regression.Benchmark/Regression.Benchmark.csproj
  src/Raven.Server/Raven.Server.csproj
  test/FastTests/FastTests.csproj
  test/InterversionTests/InterversionTests.csproj
  test/RachisTests/RachisTests.csproj
  test/SlowTests/SlowTests.csproj
  test/StressTests/StressTests.csproj
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
Labels: v4.0

#7924 RavenDB-11981 Let's use Fact instead of Theory so hopefully we'll be …
  test/StressTests/Databases.cs
Labels: v4.0

#7925 RavenDB-11981 Let's use Fact instead of Theory so hopefully we'll be …
  test/StressTests/Databases.cs
Labels: v4.1

#7923 RavenDB-12218 Notifications: Escape issue on exception details dialog
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/deleteDocumentsDetails.ts
  src/Raven.Studio/wwwroot/App/views/common/notificationCenter/detailViewer/alerts/etlTransformOrLoadErrorDetails.html
  src/Raven.Studio/wwwroot/App/views/common/notificationCenter/detailViewer/alerts/genericAlertDetails.html
  src/Raven.Studio/wwwroot/App/views/common/notificationCenter/detailViewer/alerts/newVersionAvailableDetails.html
  src/Raven.Studio/wwwroot/App/views/common/notificationCenter/detailViewer/licenseLimitDetails.html
  src/Raven.Studio/wwwroot/App/views/common/notificationCenter/detailViewer/operations/deleteDocumentsDetails.html
  src/Raven.Studio/wwwroot/App/views/common/notificationCenter/detailViewer/operations/patchDocumentsDetails.html
  src/Raven.Studio/wwwroot/App/views/common/notificationCenter/detailViewer/performanceHint/indexingDetails.html
  src/Raven.Studio/wwwroot/App/views/common/notificationCenter/detailViewer/performanceHint/pagingDetails.html
  src/Raven.Studio/wwwroot/App/views/common/notificationCenter/detailViewer/performanceHint/requestLatencyDetails.html
  src/Raven.Studio/wwwroot/App/views/common/notificationCenter/detailViewer/performanceHint/slowSqlDetails.html
  src/Raven.Studio/wwwroot/App/views/common/notificationCenter/detailViewer/performanceHint/slowWriteDetails.html
  src/Raven.Studio/wwwroot/App/views/common/notificationCenter/detailViewer/recentErrorDetails.html
  src/Raven.Studio/wwwroot/App/views/notifications/notificationCenter.html
Labels: v4.2

#7922 RavenDB-8912 Expose expiration data on edit document page (if any)
  src/Raven.Studio/typescript/models/database/documents/documentMetadata.ts
  src/Raven.Studio/typescript/models/resources/database.ts
  src/Raven.Studio/typescript/viewmodels/database/documents/editDocument.ts
  src/Raven.Studio/typescript/viewmodels/database/settings/expiration.ts
  src/Raven.Studio/typings/_studio/dto.d.ts
  src/Raven.Studio/wwwroot/App/views/database/documents/editDocument.html
Labels: v4.2

#7919 RavenDB-12144 Timer is null in the RequestExecutor
  src/Raven.Client/Http/RequestExecutor.cs
Labels: v4.0

#7920 RavenDB-12144 Timer is null in the RequestExecutor
  src/Raven.Client/Http/RequestExecutor.cs
Labels: v4.1

#7926 RavenDB-12079 Add low memory handler to ETL process
  src/Raven.Server/Documents/ETL/EtlProcess.cs
  test/SlowTests/Server/Documents/ETL/RavenDB_12079.cs
Labels: v4.2

#7931 RavenDB-12026: getNextOperationId now displays the thrown exception.
  src/Raven.Studio/typescript/viewmodels/database/tasks/exportDatabase.ts
Labels: v4.1

#7932 RavenDB-12224 - Unexpected error in indexing thread
  src/Raven.Server/Documents/Indexes/Index.cs
Labels: v4.0

#7933 RavenDB-12224 - Unexpected error in indexing thread
  src/Raven.Server/Documents/Indexes/Index.cs
Labels: v4.1

#7935 RavenDB-9479 fixed escape char handling
  src/Sparrow/Json/BlittableJsonReaderObject.cs
  src/Sparrow/Json/BlittableJsonTextWriter.cs
  src/Sparrow/Json/Parsing/JsonParserState.cs
  src/Sparrow/Json/Parsing/UnmanagedJsonParser.cs
  test/SlowTests/Issues/RavenDB-9479.cs
Labels: v4.0

#7936 RavenDB-9479 fixed escape char handling
  src/Sparrow/Json/BlittableJsonReaderObject.cs
  src/Sparrow/Json/BlittableJsonTextWriter.cs
  src/Sparrow/Json/Parsing/JsonParserState.cs
  src/Sparrow/Json/Parsing/UnmanagedJsonParser.cs
  test/SlowTests/Issues/RavenDB-9479.cs
Labels: v4.1
