Repository ravendb/ravendb, pull requests merged in 2018-09, with the labels that each got.

#7519 RavenDB-11498 Reset attachment temp file in MergedDocumentReplicationCommand
  src/Raven.Server/Documents/Replication/IncomingReplicationHandler.cs
Labels: v4.0

#7521 RavenDB-11686 In index, Additional Sources should allow downloading t…
  src/Raven.Studio/typescript/viewmodels/database/indexes/editIndex.ts
  src/Raven.Studio/wwwroot/App/views/database/indexes/editIndex.html
Labels: v4.1

#7524 RavenDB-11881 When importing/exporting we show "spinner" icon on conf…
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/smugglerDatabaseDetails.ts
Labels: v4.1

#7523 RavenDB-11862 Create better validation message for disallowed charact…
  src/Raven.Server/Web/System/ResourceNameValidator.cs
Labels: v4.1

#7522 RavenDB-11498 reverse fix
  src/Raven.Server/Documents/Replication/IncomingReplicationHandler.cs
Labels: v4.0

#7526 Raven db 11716
  src/Raven.Studio/typescript/models/resources/serverDashboard/driveUsage.ts
  src/Raven.Studio/typescript/models/resources/serverDashboard/storagePieChart.ts
  src/Raven.Studio/typescript/viewmodels/resources/serverDashboard.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/virtualGrid.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/virtualGridController.ts
  src/Raven.Studio/wwwroot/Content/css/pages/dashboard.less
  src/Raven.Studio/wwwroot/Content/css/virtual-grid.less
Labels: v4.1

#7525 RavenDB-11882 Can't load a document - race in canActivate method
  src/Raven.Studio/typescript/viewmodels/database/cmpXchg/editCmpXchg.ts
  src/Raven.Studio/typescript/viewmodels/database/documents/editDocument.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/editIndex.ts
  src/Raven.Studio/typescript/viewmodels/database/query/query.ts
  src/Raven.Studio/typescript/viewmodels/database/settings/databaseRecord.ts
  src/Raven.Studio/typescript/viewmodels/database/settings/expiration.ts
  src/Raven.Studio/typescript/viewmodels/database/settings/revisions.ts
Labels: v4.1

#7527 RavenDB-11875 Improve test patch
  src/Raven.Studio/typescript/viewmodels/database/patch/patchTester.ts
  src/Raven.Studio/wwwroot/App/views/database/patch/patch.html
  src/Raven.Studio/wwwroot/Content/css/pages/patch.less
Labels: v4.1

#7528 [v4.1]RavenDB-11889: Add "PrivateClean" smap memory type to available memor…
  src/Sparrow/LowMemory/LowMemoryNotification.cs
Labels: v4.1

#7529 RavenDB-11885
  src/Raven.Server/Documents/CountersStorage.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  test/SlowTests/Issues/RavenDB-11885.cs
Labels: v4.1

#7539 RavenDB-11893
  src/Raven.Server/Documents/Patch/PatchDocumentCommand.cs
  src/Raven.Server/Documents/Patch/ScriptRunner.cs
Labels: v4.1

#7540 RavenDB-11894 Embedded should not inherit ASPNETCORE environment variables from parent process
  src/Raven.Embedded/RavenServerRunner.cs
Labels: v4.1

#7542 RavenDB-11896: Add PrivateClean to total linux' AvailableMemory (whic…
  src/Raven.Server/Dashboard/MachineResources.cs
  src/Raven.Server/Dashboard/MachineResourcesNotificationSender.cs
  src/Raven.Server/Documents/Handlers/Debugging/MemoryDebugHandler.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/ServerWide/Memory/MemoryUsageGuard.cs
  src/Raven.Server/Utils/Cli/RavenCli.cs
  src/Sparrow/LowMemory/LowMemoryNotification.cs
  src/Sparrow/LowMemory/MemoryInformation.cs
Labels: v4.1

#7543 RavenDB-11879 fixing issues with optimized sort only queries and multiple (deleted) docs in the reader with same index, but different term
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/IndexReadOperation.cs
  test/SlowTests/Issues/RavenDB_11879.cs
Labels: v4.1

#7544 RavenDB-11890 Let's skip getting process memory usage if reduce phase…
  src/Raven.Server/Documents/Indexes/MapReduce/ReduceMapResultsBase.cs
Labels: v4.1

#7545 RavenDB-11794 added support for issuing dynamic queries with '@metadata.@last-modified' field
  src/Raven.Server/Json/BlittableJsonTraverserHelper.cs
  test/SlowTests/Issues/RavenDB_11794.cs
Labels: v4.1

#7552 RavenDB-11892 Memory leak in ByteStringContext
  src/Sparrow/ByteString.cs
Labels: v4.0

#7538 RavenDB-11892 Memory leak in ByteStringContext
  src/Sparrow/ByteString.cs
Labels: v4.1

#7553 RavenDB-11899 - High CPU usage when executing large transcations
  Raven.Database/DocumentDatabase.cs
  Raven.Database/Storage/Esent/StorageActions/Indexing.cs
  Raven.Database/Storage/IIndexingStorageActions.cs
  Raven.Database/Storage/Managed/IndexingStorageActions.cs
Labels: v2.5

#7554 RavenDB-11901 - OS name is in quotes after parsing: /etc/os-release
  src/Raven.Server/Commercial/OsInfoExtensions.cs
Labels: v4.1

#7561 RavenDB-7070 updated packages
  src/Raven.Server/Raven.Server.csproj
  test/SlowTests/Issues/RavenDB-11789.cs
  test/SlowTests/Server/Documents/Indexing/Static/RavenDB_11469.cs
Labels: v4.0

#7562 RavenDB-7070 updated packages
  src/Raven.Server/Raven.Server.csproj
  test/SlowTests/Issues/RavenDB-11789.cs
  test/SlowTests/Server/Documents/Indexing/Static/RavenDB_11469.cs
  tools/Raven.Migrator/MongoDB/MongoDBMigrator.cs
Labels: v4.1

#7560 RavenDB-10516 Studio omits hostname in Traffic Watch for lazy queries
  src/Raven.Server/Documents/Handlers/MultiGetHandler.cs
  src/Raven.Server/RavenServerStartup.cs
Labels: v4.1

#7565 RavenDB-11725 more debug info
  test/StressTests/Voron/HugeTransactions.cs
Labels: v4.1

#7567 RavenDB-11725 added tasks for cancellation
  test/StressTests/Voron/HugeTransactions.cs
Labels: v4.0

#7566 RavenDB-11725 added tasks for cancellation
  test/StressTests/Voron/HugeTransactions.cs
Labels: v4.1

#7569 RavenDB-11910 SQL ETL: Deletions should be sent to tables specific fo…
  src/Raven.Server/Documents/ETL/Providers/SQL/SqlDocumentTransformer.cs
  test/SlowTests/Server/Documents/ETL/SQL/SqlEtlTests.cs
Labels: v4.1

#7568 RavenDB-11910 SQL ETL: Deletions should be sent to tables specific fo…
  src/Raven.Server/Documents/ETL/Providers/SQL/SqlDocumentTransformer.cs
  test/SlowTests/Server/Documents/ETL/SQL/SqlEtlTests.cs
Labels: v4.0

#7571 RavenDB-11878 added AttachmentsFor and CounterNamesFor methods to static indexes
  src/Raven.Client/Documents/Indexes/AbstractIndexCreationTask.cs
  src/Raven.Server/Documents/Indexes/Static/StaticIndexBase.cs
  test/SlowTests/Issues/RavenDB_11878.cs
Labels: v4.1

#7576 [4.0] - RavenDB-11915 - add attachments metrics to the dashboard stats
  src/Raven.Server/Dashboard/DatabasesInfoNotificationSender.cs
  src/Raven.Server/Documents/Handlers/StatsHandler.cs
Labels: v4.0

#7578 RavenDB-11911 unclean close of changes api web socket
  src/Raven.Server/Documents/Handlers/ChangesHandler.cs
Labels: v4.1

#7579 RavenDB-11911 unclean close of changes api web socket
  src/Raven.Server/Documents/Handlers/ChangesHandler.cs
Labels: v4.0

#7585 RavenDB-7070 updated .NET Core to 2.1.4
  bench/BulkInsert.Benchmark/BulkInsert.Benchmark.csproj
  bench/Indexing.Benchmark/Indexing.Benchmark.csproj
  bench/Micro.Benchmark/Micro.Benchmark.csproj
  bench/Regression.Benchmark/Regression.Benchmark.csproj
  bench/SubscriptionFailover.Benchmark/SubscriptionFailover.Benchmark.csproj
  bench/Subscriptions.Benchmark/Subscriptions.Benchmark.csproj
  bench/Voron.Benchmark/Voron.Benchmark.csproj
  src/Raven.Embedded/ServerOptions.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Studio/Raven.Studio.csproj
  src/Sparrow/Sparrow.csproj
  test/BenchmarkTests/BenchmarkTests.csproj
  test/EmbeddedTests/EmbeddedTests.csproj
  test/FastTests/FastTests.csproj
  test/InterversionTests/InterversionTests.csproj
  test/RachisTests/RachisTests.csproj
  test/SlowTests/SlowTests.csproj
  test/StressTests/StressTests.csproj
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
  test/Tryouts/Tryouts.csproj
  tools/Raven.Migrator/Raven.Migrator.csproj
  tools/TypingsGenerator/TypingsGenerator.csproj
  tools/Voron.Recovery/Voron.Recovery.csproj
  tools/rvn/rvn.csproj
Labels: v4.1

#7586 RavenDB-7070 updated .NET Core to 2.1.4
  bench/BulkInsert.Benchmark/BulkInsert.Benchmark.csproj
  bench/Indexing.Benchmark/Indexing.Benchmark.csproj
  bench/Micro.Benchmark/Micro.Benchmark.csproj
  bench/Regression.Benchmark/Regression.Benchmark.csproj
  bench/SubscriptionFailover.Benchmark/SubscriptionFailover.Benchmark.csproj
  bench/Subscriptions.Benchmark/Subscriptions.Benchmark.csproj
  bench/Voron.Benchmark/Voron.Benchmark.csproj
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Studio/Raven.Studio.csproj
  src/Sparrow/Sparrow.csproj
  test/FastTests/FastTests.csproj
  test/InterversionTests/InterversionTests.csproj
  test/RachisTests/RachisTests.csproj
  test/SlowTests/SlowTests.csproj
  test/StressTests/StressTests.csproj
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
  test/Tryouts/Tryouts.csproj
  tools/TypingsGenerator/TypingsGenerator.csproj
  tools/Voron.Recovery/Voron.Recovery.csproj
  tools/rvn/rvn.csproj
Labels: v4.0

#7593 RavenDB-11943
  src/Raven.Studio/typescript/viewmodels/wizard/finish.ts
Labels: v4.1

#7592 RavenDB-11941 Studio is not loading on IE/Edge
  src/Raven.Studio/typescript/viewmodels/shell.ts
Labels: v4.1

#7590 RavenDB-11928 Auto assign backup task name when missing during update
  src/Raven.Client/ServerWide/DatabaseRecord.cs
  src/Raven.Server/ServerWide/Commands/PeriodicBackup/UpdatePeriodicBackupCommand.cs
Labels: v4.0

#7589 RavenDB-11928 Auto assign backup task name when missing during update
  src/Raven.Client/ServerWide/DatabaseRecord.cs
  src/Raven.Server/ServerWide/Commands/PeriodicBackup/UpdatePeriodicBackupCommand.cs
Labels: v4.1

#7595 [2.5] RavenDB-1111 - add debug logs to the bulk_docs endpoint
  Raven.Database/DocumentDatabase.cs
  Raven.Database/Server/Responders/DocumentBatch.cs
Labels: v2.5

#7600 RavenDB-11950 Don't fail for blittable in results for commands that e…
  src/Raven.Server/Rachis/Leader.cs
  src/Raven.Server/ServerWide/ServerStore.cs
Labels: v4.0

#7599 RavenDB-11950 Don't fail for blittable in results for commands that e…
  src/Raven.Server/Rachis/Leader.cs
  src/Raven.Server/ServerWide/ServerStore.cs
Labels: v4.1

#7602 RavenDB-11723 SlowTests.Server.Documents.CompactDatabaseTest.CanCompa…
  test/FastTests/Voron/Compaction/StorageCompactionTests.cs
Labels: v4.0

#7601 RavenDB-11723 SlowTests.Server.Documents.CompactDatabaseTest.CanCompa…
  test/FastTests/Voron/Compaction/StorageCompactionTests.cs
Labels: v4.1

#7603 RavenDB-11723 SlowTests.Server.Documents.CompactDatabaseTest.CanCompa…
  src/Raven.Server/Documents/CompactionResult.cs
Labels: v4.0

#7594 RavenDB-11945 - avoid opening a read tx if it's not necessary when running a backup
  src/Raven.Client/Documents/Smuggler/SmugglerResult.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/PeriodicBackup/BackupTask.cs
  src/Raven.Server/Smuggler/Documents/DatabaseSmuggler.cs
  src/Raven.Server/Smuggler/Documents/DatabaseSource.cs
  src/Raven.Server/Smuggler/Documents/Handlers/SmugglerHandler.cs
Labels: v4.1

#7606 RavenDB-11952 Unhandled exception in notification center timers can k…
  src/Raven.Server/NotificationCenter/Paging.cs
  src/Raven.Server/NotificationCenter/SlowWriteNotifications.cs
Labels: v4.1

#7605 RavenDB-11952 Unhandled exception in notification center timers can k…
  src/Raven.Server/NotificationCenter/Paging.cs
  src/Raven.Server/NotificationCenter/SlowWriteNotifications.cs
Labels: v4.0

#7607 RavenDB-7070 disabled RS1022 due to NRE that it throws
  RavenDB.ruleset
Labels: v4.1

#7611 RavenDB-11956 Avoid Console.WriteLine in Voron.Recovery tests
  test/SlowTests/Issues/RavenDB_11904.cs
  test/SlowTests/Issues/RavenDB_11905.cs
  tools/Voron.Recovery/CommandLineApp.cs
  tools/Voron.Recovery/Recovery.cs
Labels: v4.1

#7613 RavenDB-11956 Avoid Console.WriteLine in Voron.Recovery tests
  test/SlowTests/Issues/RavenDB_11904.cs
  test/SlowTests/Issues/RavenDB_11905.cs
  tools/Voron.Recovery/CommandLineApp.cs
  tools/Voron.Recovery/Recovery.cs
Labels: v4.0

#7618 prevent tests failing because of already used 8080 port (RavenDB-11961)
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
  test/RachisTests/DatabaseCluster/OngoingTasks.cs
  test/SlowTests/Authentication/AuthenticationBasicTests.cs
Labels: v4.1

#7616 RavenDB-11896
  src/Raven.Server/Dashboard/MachineResources.cs
  src/Raven.Server/Dashboard/MachineResourcesNotificationSender.cs
  src/Raven.Server/Documents/Handlers/Debugging/MemoryStatsHandler.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/ServerWide/Memory/MemoryUsageGuard.cs
  src/Raven.Server/Utils/Cli/RavenCli.cs
  src/Sparrow/LowMemory/LowMemoryNotification.cs
  src/Sparrow/LowMemory/MemoryInformation.cs
Labels: v4.0

#7617 RavenDB-11896: rename CalculatedAvailableMemory -> AvailableWithoutTo…
  src/Raven.Server/Dashboard/MachineResources.cs
  src/Raven.Server/Dashboard/MachineResourcesNotificationSender.cs
  src/Raven.Server/Documents/Handlers/Debugging/MemoryDebugHandler.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/ServerWide/Memory/MemoryUsageGuard.cs
  src/Raven.Server/Utils/Cli/RavenCli.cs
  src/Sparrow/LowMemory/LowMemoryNotification.cs
  src/Sparrow/LowMemory/MemoryInformation.cs
Labels: v4.1

#7615 RavenDB-11947 Fix NREs
  src/Raven.Server/Rachis/FollowerAmbassador.cs
  src/Raven.Server/RavenServer.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/ServerStore.cs
Labels: v4.1

#7614 RavenDB-11962 Test failure - SlowTests.MailingList.Vitaly.Test
  src/Raven.Client/Json/BlittableJsonReader.cs
Labels: v4.1

#7632 RavenDB-11979 Cluster wide transaction failed with NRE when the datab…
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/Handlers/BatchHandler.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/Commands/ClusterTransactionCommand.cs
Labels: v4.1

#7631 RavenDB-11948 Better message when reloading a db due to voron unrecov…
  src/Raven.Server/Documents/CatastrophicFailureHandler.cs
  src/Raven.Server/Documents/CompactDatabaseTask.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Voron/Exceptions/CatastrophicFailureNotification.cs
  src/Voron/StorageEnvironmentOptions.cs
  test/SlowTests/Issues/RavenDB_10744.cs
Labels: v4.1

#7627 RavenDB-11978 Can't edit backup task with Azure
  src/Raven.Studio/typescript/viewmodels/database/tasks/editPeriodicBackupTask.ts
Labels: v4.0

#7626 RavenDB-11978 Can't edit backup task with Azure
  src/Raven.Studio/typescript/viewmodels/database/tasks/editPeriodicBackupTask.ts
Labels: v4.1

#7633 RavenDB-11914 DeleteByQueryOperation<TEntity> throws when DocumentSto…
  src/Raven.Client/Documents/Operations/DeleteByQueryOperation.cs
  test/SlowTests/Issues/RavenDB_11914.cs
Labels: v4.1

#7634 RavenDB-11914 DeleteByQueryOperation<TEntity> throws when DocumentSto…
  src/Raven.Client/Documents/Operations/DeleteByQueryOperation.cs
  test/SlowTests/Issues/RavenDB_11914.cs
Labels: v4.0

#7646 RavenDB-11992 Fix Export and import in smuggler when no default database
  src/Raven.Client/Documents/Smuggler/DatabaseSmuggler.cs
  test/SlowTests/Smuggler/SmugglerApiTests.cs
Labels: v4.1

#7644 RavenDB-11998
  src/Raven.Server/RavenServer.cs
  src/Raven.Server/Routing/RequestRouter.cs
Labels: v4.1

#7628 RavenDB-11974 Error Sort Only Query
  libs/Lucene.Net.3.0.16.nupkg
  libs/Lucene.Net.3.0.17.nupkg
  libs/Lucene.Net.Contrib.Spatial.NTS.3.0.13.nupkg
  libs/Lucene.Net.Contrib.Spatial.NTS.3.0.17.nupkg
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/IndexReadOperation.cs
  src/Raven.Server/Raven.Server.csproj
  test/SlowTests/Issues/RavenDB_8956.cs
  test/SlowTests/MailingList/SjurIndexingTests.cs
Labels: v4.1

#7648 RavenDB-11992a Fix Export and import in smuggler when no default data…
  src/Raven.Client/Documents/Smuggler/DatabaseSmuggler.cs
  test/SlowTests/Smuggler/SmugglerApiTests.cs
Labels: v4.0

#7647 Avoid leaking log file handle in tests
  test/SlowTests/Issues/RavenDB_11904.cs
  test/SlowTests/Issues/RavenDB_11905.cs
  tools/Voron.Recovery/Recovery.cs
Labels: v4.1

#7655 RavenDB-11891 Tombstones might not have Collection set but they do ha…
  src/Raven.Server/Documents/ETL/Providers/Raven/RavenEtlDocumentTransformer.cs
  test/SlowTests/Server/Documents/ETL/RavenDB_11891.cs
Labels: v4.1

#7656 RavenDB-12009 SQL ETL: Open the connection to SQL db only if we have …
  src/Raven.Server/Documents/ETL/EtlProcess.cs
  src/Raven.Server/Documents/ETL/Providers/SQL/SqlDocumentTransformer.cs
Labels: v4.1
