Repository ravendb/ravendb, pull requests merged in 2018-12, with the labels that each got.

#8140 RavenDB-11650 Let's use the context of session instead of the one cre…
  test/SlowTests/Issues/RavenDB_11650.cs
Labels: v4.2

#8139 RavenDB-12364 If we are running in transaction scope and topology upd…
  Raven.Client.Lightweight/Connection/Async/AsyncServerClient.cs
Labels: v3.5

#8142 RavenDB-12249 Rendering studio when an index is "paused until restart…
  src/Raven.Studio/typescript/models/database/index/index.ts
Labels: v4.2

#8143 RavenDB-12418 null message in notification center
  src/Raven.Studio/typescript/common/notifications/models/abstractNotification.ts
Labels: v4.2

#8146 RavenDB-12389 Moving classes that implements IOperationProgress and I…
  src/Raven.Client/Documents/Operations/Backups/BackupProgress.cs
  src/Raven.Client/Documents/Operations/Backups/BackupResult.cs
  src/Raven.Client/ServerWide/Operations/Certificates/ClientCertificateGenerationResult.cs
  src/Raven.Client/ServerWide/Operations/CompactionProgress.cs
  src/Raven.Client/ServerWide/Operations/CompactionResult.cs
  src/Raven.Client/ServerWide/Operations/RestoreProgress.cs
  src/Raven.Client/ServerWide/Operations/RestoreResult.cs
  src/Raven.Server/Documents/CompactDatabaseTask.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreBackupTask.cs
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/compactDatabaseDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/generateClientCertificateDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/smugglerDatabaseDetails.ts
Labels: v4.0

#8145 RavenDB-12389 Moving classes that implements IOperationProgress and I…
  src/Raven.Client/Documents/Operations/Backups/BackupProgress.cs
  src/Raven.Client/Documents/Operations/Backups/BackupResult.cs
  src/Raven.Client/ServerWide/Operations/Certificates/ClientCertificateGenerationResult.cs
  src/Raven.Client/ServerWide/Operations/CompactionProgress.cs
  src/Raven.Client/ServerWide/Operations/CompactionResult.cs
  src/Raven.Client/ServerWide/Operations/RestoreProgress.cs
  src/Raven.Client/ServerWide/Operations/RestoreResult.cs
  src/Raven.Server/Documents/CompactDatabaseTask.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreBackupTask.cs
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/compactDatabaseDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/generateClientCertificateDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/replayTransactionCommandsDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/smugglerDatabaseDetails.ts
Labels: v4.1

#8147 RavenDB-12425 - Progress in FTP backup upload is not updated
  src/Raven.Server/Documents/PeriodicBackup/RavenFtpClient.cs
Labels: v4.1

#8150 RavenDB-12151 - take into account the work that needs to be done for a map-reduce index (during the reduce)
  src/Raven.Server/Documents/Indexes/Index.cs
Labels: v4.1

#8151 RavenDB-12427 Support Enumerable.Zip LINQ statement in indexing funct…
  src/Raven.Server/Documents/Indexes/Static/Roslyn/Rewriters/DynamicLambdaExpressionsRewriter.cs
  test/SlowTests/Issues/RavenDB_12427.cs
Labels: v4.1

#8154 RavenDB-12422 Animate "in progress" operations on replication stats view
  src/Raven.Studio/typescript/viewmodels/database/status/replicationStats.ts
  src/Raven.Studio/wwwroot/App/views/database/status/replicationStats.html
  src/Raven.Studio/wwwroot/Content/css/pages/metrics.less
Labels: v4.2

#8155 Raven db 10716
  src/Raven.Studio/typescript/common/helpers/database/genericProgress.ts
  src/Raven.Studio/typescript/common/helpers/database/progress.ts
  src/Raven.Studio/typescript/models/database/index/index.ts
  src/Raven.Studio/typescript/models/database/index/indexProgress.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/smugglerDatabaseDetails.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexes.ts
  src/Raven.Studio/wwwroot/App/views/common/notificationCenter/detailViewer/operations/smugglerDatabaseDetails.html
  src/Raven.Studio/wwwroot/App/views/database/indexes/indexes.html
  src/Raven.Studio/wwwroot/Content/css/basic-layout.less
Labels: v4.2

#8157 RavenDB-12359
  src/Raven.Client/Util/JavascriptConversionExtensions.cs
  test/SlowTests/Issues/RavenDB-12359.cs
Labels: v4.0

#8158 RavenDB-12359
  src/Raven.Client/Util/JavascriptConversionExtensions.cs
  test/SlowTests/Issues/RavenDB-12359.cs
Labels: v4.1

#8161 RavenDB-5154 Dim metadata section in document editor
  src/Raven.Studio/aceBuild/Makefile.dryice.js
  src/Raven.Studio/aceBuild/addons/lib/ace/mode/raven_document.js
  src/Raven.Studio/aceBuild/addons/lib/ace/mode/raven_document_highlight_rules.js
  src/Raven.Studio/aceBuild/addons/lib/ace/mode/raven_document_newline_friendly.js
  src/Raven.Studio/aceBuild/addons/lib/ace/mode/raven_document_newline_friendly_highlight_rules.js
  src/Raven.Studio/typescript/common/helpers/database/documentHelpers.ts
  src/Raven.Studio/typescript/viewmodels/database/documents/editDocument.ts
  src/Raven.Studio/wwwroot/App/views/database/conflicts/conflicts.html
  src/Raven.Studio/wwwroot/App/views/database/documents/editDocument.html
  src/Raven.Studio/wwwroot/App/views/database/patch/patch.html
  src/Raven.Studio/wwwroot/Content/ace/mode-raven_document.js
  src/Raven.Studio/wwwroot/Content/ace/mode-raven_document_newline_friendly.js
  src/Raven.Studio/wwwroot/Content/css/ace.less
Labels: v4.2

#8162 RavenDB-12431 - add order by double to the examples in the query page
  src/Raven.Studio/wwwroot/App/views/database/query/querySyntax.html
Labels: v4.1

#8163 RavenDB-9300 Dashboard - Storage UX
  src/Raven.Server/Dashboard/DatabasesInfoNotificationSender.cs
  src/Raven.Server/Dashboard/DrivesUsage.cs
  src/Raven.Server/Storage/StorageSpaceMonitor.cs
  src/Raven.Studio/typescript/common/generalUtils.ts
  src/Raven.Studio/typescript/models/resources/serverDashboard/driveUsage.ts
  src/Raven.Studio/typescript/viewmodels/resources/serverDashboard.ts
  src/Raven.Studio/wwwroot/App/views/resources/serverDashboard.html
  src/Raven.Studio/wwwroot/Content/css/pages/dashboard.less
Labels: v4.2

#8167 RavenDB-12436 - Change the default of MaxTimeToWaitForPreviousTxInMs
  src/Raven.Server/Config/Categories/TransactionMergerConfiguration.cs
Labels: v4.1

#8168 RavenDB-12436 - Change the default of MaxTimeToWaitForPreviousTxInMs.
  src/Raven.Server/Config/Categories/TransactionMergerConfiguration.cs
Labels: v4.0

#8169 RavenDB-12437 - Update metrics in an index can be single threaded
  src/Raven.Server/Documents/ETL/EtlProcess.cs
  src/Raven.Server/Documents/ETL/Providers/SQL/RelationalWriters/RelationalDatabaseWriter.cs
  src/Raven.Server/Documents/Indexes/MapIndexBase.cs
  src/Raven.Server/Documents/Indexes/MapReduce/ReduceMapResultsBase.cs
  src/Raven.Server/Documents/Indexes/Workers/HandleReferences.cs
  src/Raven.Server/Documents/Indexes/Workers/MapDocuments.cs
  src/Raven.Server/Utils/Metrics/MeterMetric.cs
Labels: v4.1

#8170 RavenDB-12410: BlittableJsonReaderObject.Equals works as expected with nested objects properties
  src/Sparrow/Json/BlittableJsonReaderObject.cs
  test/FastTests/Blittable/BlittableJsonEqualityTests.cs
  test/SlowTests/Issues/RavenDB_12410.cs
Labels: v4.1

#8127 RavenDB-12393 Fixing memory leak in BlittableMetadataModifier usage
  src/Raven.Server/Documents/BlittableMetadataModifier.cs
  src/Raven.Server/Smuggler/Documents/StreamSource.cs
Labels: v4.2

#8173 RavenDB-12401 Add features to query page when query setting are used
  src/Raven.Studio/typescript/viewmodels/database/query/query.ts
  src/Raven.Studio/wwwroot/App/views/database/query/query.html
Labels: v4.2

#8178 RavenDB-12447 Index perf view seems to be loading something, but actu…
  src/Raven.Studio/wwwroot/App/views/database/indexes/indexPerformance.html
  src/Raven.Studio/wwwroot/App/views/database/status/ioStats.html
  src/Raven.Studio/wwwroot/App/views/database/status/replicationStats.html
Labels: v4.1

#8176 RavenDB-12436
  src/Raven.Server/Smuggler/Documents/StreamSource.cs
Labels: v4.0

#8175 Ravendb-12393
  src/Raven.Server/Documents/BlittableMetadataModifier.cs
  src/Raven.Server/Smuggler/Documents/StreamSource.cs
Labels: v4.1

#8177 RavenDB-12413 Warn user when querying with offset on fan-out index
  src/Raven.Studio/typescript/commands/database/query/queryCommand.ts
  src/Raven.Studio/typescript/viewmodels/database/query/query.ts
  src/Raven.Studio/wwwroot/App/views/database/query/query.html
Labels: v4.2

#8180 RavenDB-8213
  src/Raven.Server/Documents/Queries/Parser/QueryParser.cs
  src/Raven.Server/Documents/Queries/QueryMetadata.cs
  test/SlowTests/Issues/RavenDB-8213.cs
Labels: v4.2

#8181 RavenDB-12448 throwing FeaturesAvailabilityException on stable
  src/Raven.Server/Documents/Queries/GraphQueryRunner.cs
Labels: v4.2

#8194 RavenDB-12318 Add includes to graph queries
  src/Raven.Server/Documents/Queries/GraphQueryRunner.cs
  test/FastTests/Graph/BasicGraphQueries.cs
Labels: v4.2

#8192 RavenDB-12449 Consider hiding RAFT connection error from notification…
  src/Raven.Server/ServerWide/ServerStore.cs
Labels: v4.1

#8187 RavenDB-12455 & RavenDB-12454
  src/Raven.Server/Documents/ConflictsStorage.cs
  test/SlowTests/Server/Replication/ReplicationConflictsTests.cs
Labels: v4.1

#8191 RavenDB-12455 & RavenDB-12454
  src/Raven.Server/Documents/ConflictsStorage.cs
  test/SlowTests/Server/Replication/ReplicationConflictsTests.cs
Labels: v4.0

#8190 RavenDB-12451 - Use a single context for the NotificationCenterWebSocketWriter
  src/Raven.Server/NotificationCenter/NotificationCenterWebsocketWriter.cs
Labels: v4.1

#8195 RavenDB-12450 Cannot project Id from map-reduce index
  src/Raven.Client/Documents/Linq/RavenQueryProviderProcessor.cs
  src/Raven.Client/Documents/Queries/QueryData.cs
  src/Raven.Client/Documents/Session/DocumentQuery.cs
  test/SlowTests/Issues/RavenDB_12450.cs
Labels: v4.1

#8197 RavenDB-12450
  src/Raven.Client/Documents/Linq/RavenQueryProviderProcessor.cs
  test/SlowTests/Issues/RavenDB_12450.cs
Labels: v4.1

#8198 RavenDB-12471 - DiskFullException doesn't result in client failover
  src/Raven.Server/RavenServerStartup.cs
Labels: v4.0

#8199 RavenDB-12471 - DiskFullException doesn't result in client failover
  src/Raven.Server/RavenServerStartup.cs
Labels: v4.1

#8196 RavenDB-12466 Raven.StorageExporter never finishes if tree stats show…
  Raven.StorageExporter/StorageExporter.cs
Labels: v3.5

#8200 RavenDB-12351 Fixing Fix issue when sync can be run with or without pre and pro sync tasks
  src/Voron/Impl/Journal/WriteAheadJournal.cs
Labels: v4.1

#8201 RavenDB-12474 update supported browser detection
  src/Raven.Studio/typescript/viewmodels/shell.ts
Labels: v4.1

#8202 RavenDB-12474 update supported browser detection
  src/Raven.Studio/typescript/viewmodels/shell.ts
Labels: v4.0

#8203 RavenDB-12457 Studio array serialization
  src/Raven.Studio/typescript/viewmodels/database/documents/editDocument.ts
Labels: v4.1

#8207 RavenDB-12318 fixing include from JS projection are not been respecte…
  src/Raven.Server/Documents/Queries/GraphQueryRunner.cs
  test/FastTests/Graph/BasicGraphQueries.cs
Labels: v4.2

#8186 RavenDB-10683 Backup of encrypted database
  src/Raven.Client/Documents/Operations/Backups/EncryptionSettings.cs
  src/Raven.Client/Documents/Operations/Backups/PeriodicBackupConfiguration.cs
  src/Raven.Client/Documents/Operations/Backups/RestoreBackupConfiguration.cs
  src/Raven.Client/Documents/Smuggler/DatabaseSmugglerOptions.cs
  src/Raven.Server/Documents/PeriodicBackup/BackupTask.cs
  src/Raven.Server/Documents/PeriodicBackup/EncryptedBackup.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreBackupTask.cs
  src/Raven.Server/Raven.Server.csproj
  src/Sparrow/Constants.cs
  src/Sparrow/Sodium.cs
  src/Sparrow/sodium-api.txt
  test/SlowTests/Server/Documents/PeriodicBackup/EncryptedBackupTest.cs
Labels: v4.2

#8193 RavenDB-12441: Remove LINQ from statements from ToBlittableSupportedType
  src/Raven.Client/Json/TypeConverter.cs
  src/Raven.Server/Utils/TypeConverter.cs
Labels: v4.1

#8204 RavenDB-12470 Allow CPU usage to be greater than 100%
  src/Raven.Server/Utils/Cpu/CpuUsageExtensionPoint.cs
  test/SlowTests/ExtensionPoints/RavenDB_12161.cs
Labels: v4.1

#8213 fix for RavenDB-12459
  src/Raven.Server/Documents/Queries/Graph/SingleEdgeMatcher.cs
  test/FastTests/Issues/RavenDB-12459.cs
Labels: v4.2

#8220 RavenDB-12473 Getting EarlyOutOfMemory when retrieving index stats sh…
  src/Raven.Server/Documents/Handlers/IndexHandler.cs
Labels: v4.1

#8222 RavenDB-12497
  src/Raven.Server/Documents/Patch/ScriptRunner.cs
Labels: v4.1

#8229 RavenDB-7070 updated packages
  src/Raven.Server/Raven.Server.csproj
  tools/Raven.Migrator/Raven.Migrator.csproj
Labels: v4.1

#8226 RavenDB-12483 fix dir name in build script
  build.ps1
Labels: v4.2

#8221 RavenDB-12473 Let's ignore write errors when updating index state to …
  src/Raven.Server/Documents/Indexes/Auto/AutoMapIndex.cs
  src/Raven.Server/Documents/Indexes/Errors/FaultyInMemoryIndex.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/MapReduce/Auto/AutoMapReduceIndex.cs
Labels: v4.1

#8231 RavenDB-12450 Making the implementation of DocumentQuery.CreateDocume…
  src/Raven.Client/Documents/Linq/RavenQueryProviderProcessor.cs
  src/Raven.Client/Documents/Queries/QueryData.cs
  src/Raven.Client/Documents/Session/DocumentQuery.cs
Labels: v4.1

#8235 RavenDB-12193 Skipping the test. Fixing `async Task` usage - there wa…
  test/SlowTests/Issues/RavenDB_12193.cs
Labels: v4.1

#8234 RavenDB-7548 Redirect to non existing page fails
  src/Raven.Studio/typescript/common/appUrl.ts
Labels: v4.2

#8212 fix for RavenDB-12263
  src/Raven.Server/Documents/Queries/Graph/RecursionQueryStep.cs
  test/FastTests/Issues/RavenDB-12263.cs
Labels: v4.2

#8224 adding regression unit test for an issue that appears to be already solved (RavenDB-12206)
  test/FastTests/Graph/AdvancedGraphQueries.cs
Labels: v4.2

#8223 fix for RavenDB-12468
  src/Raven.Server/Documents/Patch/ScriptRunner.cs
  src/Raven.Server/Documents/Queries/QueryMetadata.cs
  src/Raven.Server/Documents/Queries/Results/GraphQueryResultRetriever.cs
  src/Raven.Server/Documents/Queries/Results/QueryResultRetrieverBase.cs
  test/FastTests/Issues/RavenDB-12468.cs
Labels: v4.2

#8239 proper fix for RavenDB-12202
  src/Raven.Server/Documents/Queries/Results/GraphQueryResultRetriever.cs
  test/FastTests/Graph/AdvancedGraphQueries.cs
Labels: v4.2

#8243 RavenDB-12509: dispose Win32FileJournalWriter if we got an exception
  src/Voron/Platform/Win32/Win32JournalWriter.cs
Labels: v4.1

#8240 RavenDB-12015: Unable to start database because 'db.lock' file it is being used by another process
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
Labels: v4.1

#8244 RavenDB-12510: Reset _isQueryExpression flag between usages of Captur…
  src/Raven.Server/Documents/Indexes/Static/Roslyn/FieldNamesValidator.cs
  src/Raven.Server/Documents/Indexes/Static/Roslyn/Rewriters/CaptureSelectNewFieldNamesVisitor.cs
  test/SlowTests/Issues/RavenDB_12510.cs
Labels: v4.2

#8247 RavenDB-12506 PageLocator should throw on negative page numbers. In p…
  src/Voron/PageLocator.cs
  test/SlowTests/Voron/Issues/RavenDB_12506.cs
Labels: v4.0

#8246 RavenDB-12506 PageLocator should throw on negative page numbers. In p…
  src/Voron/PageLocator.cs
  test/SlowTests/Voron/Issues/RavenDB_12506.cs
Labels: v4.1

#8248 RavenDB-12492 Let's include duration of deleting records from PageNum…
  src/Raven.Server/Documents/Indexes/MapReduce/ReduceMapResultsBase.cs
Labels: v4.1

#8250 RavenDB-12517 The test modified to wait to 'worker' if it didn't finished and the 'throwWorker' finished
  test/SlowTests/Voron/Storage/SyncFlushTimingTest.cs
Labels: v4.1

#8236 RavenDB-12508 More detail about journals added to `StorageHandler`
  src/Voron/Debugging/DetailedStorageReport.cs
  src/Voron/Debugging/StorageReportGenerator.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/StorageEnvironment.cs
  test/SlowTests/Voron/Storage/StorageReportGenerationTests.cs
Labels: v4.1

#8249 RavenDB-12502 support staleness in graph queries
  src/Raven.Client/Documents/Queries/IndexQuery.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Queries/Graph/CollectionDestinationQueryStep.cs
  src/Raven.Server/Documents/Queries/Graph/EdgeQueryStep.cs
  src/Raven.Server/Documents/Queries/Graph/GraphQueryPlan.cs
  src/Raven.Server/Documents/Queries/Graph/IGraphQueryStep.cs
  src/Raven.Server/Documents/Queries/Graph/IntersectionQueryStep.cs
  src/Raven.Server/Documents/Queries/Graph/QueryQueryStep.cs
  src/Raven.Server/Documents/Queries/Graph/RecursionQueryStep.cs
  src/Raven.Server/Documents/Queries/GraphQueryRunner.cs
Labels: v4.2

#8252 RavenDB-12015 - fixing AVE
  src/Raven.Server/Documents/Indexes/MapReduce/MapReduceIndexingContext.cs
Labels: v4.0

#8251 RavenDB-12015 - fixing AVE
  src/Raven.Server/Documents/Indexes/MapReduce/MapReduceIndexingContext.cs
Labels: v4.1

#8254 RavenDB-12406 - display the Raven.Server full path for the setcap error
  src/Raven.Server/Commercial/SetupManager.cs
  src/Raven.Server/Program.cs
Labels: v4.1

#8256 RavenDB-12506
  src/Voron/PageLocator.cs
  test/SlowTests/Voron/Issues/RavenDB_12506.cs
Labels: v4.0

#8255 RavenDB-12506
  src/Voron/PageLocator.cs
  test/SlowTests/Voron/Issues/RavenDB_12506.cs
Labels: v4.1

#8259 RavenDB-12522 EnumerateArray in TypeConverter isn't passing context to ToBlittableSupportedType
  src/Raven.Server/Utils/TypeConverter.cs
Labels: v4.1

#8262 RavenDB-12534 Throw early on invalid size of a voron stream so we won…
  src/Voron/Data/BTrees/Tree.Stream.cs
Labels: v4.1

#8264 RavenDB-12538: Prefetch to avoid slowdowns.
  src/Voron/Impl/Journal/JournalReader.cs
  src/Voron/Impl/Paging/AbstractPager.cs
Labels: v4.1

#8265 RavenDB-12539: Increasing the read buffer to improve copy performance.
  src/Voron/Data/BTrees/Tree.Stream.cs
Labels: v4.1

#8267 fix for RavenDB-12187
  src/Raven.Server/Documents/Queries/AST/QueryExpression.cs
  src/Raven.Server/Documents/Queries/Parser/QueryParser.cs
  src/Sparrow/Json/BlittableJsonReaderObject.cs
  test/FastTests/Issues/RavenDB-12187.cs
  test/Tests.Infrastructure/RavenTestBase.cs
Labels: v4.2

#8268 RavenDB-12502 Graph query staleness
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Queries/Graph/GraphQueryIndexGatherer.cs
  src/Raven.Server/Documents/Queries/Graph/GraphQueryPlan.cs
  src/Raven.Server/Documents/Queries/Graph/QueryPlanRewriter.cs
  src/Raven.Server/Documents/Queries/Graph/QueryPlanVisitor.cs
  src/Raven.Server/Documents/Queries/Graph/QueryQueryStep.cs
  src/Raven.Server/Documents/Queries/GraphQueryRunner.cs
  test/FastTests/Graph/BasicGraphQueries.cs
Labels: v4.2

#8269 4.1 to 4.2 merge
  src/Raven.Client/Documents/Changes/DatabaseConnectionState.cs
  src/Raven.Client/Documents/Linq/RavenQueryProviderProcessor.cs
  src/Raven.Client/Documents/Linq/RavenQueryableExtensions.cs
  src/Raven.Client/Documents/Queries/QueryData.cs
  src/Raven.Client/Documents/Session/AsyncDocumentQuery.cs
  src/Raven.Client/Documents/Session/DocumentQuery.cs
  src/Raven.Client/Documents/Session/IDocumentQueryBase.cs
  src/Raven.Client/Json/TypeConverter.cs
  src/Raven.Server/Commercial/SetupManager.cs
  src/Raven.Server/Config/Categories/StorageConfiguration.cs
  src/Raven.Server/Documents/CompactDatabaseTask.cs
  src/Raven.Server/Documents/ConfigurationStorage.cs
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Handlers/IndexHandler.cs
  src/Raven.Server/Documents/Indexes/Auto/AutoMapIndex.cs
  src/Raven.Server/Documents/Indexes/Errors/FaultyInMemoryIndex.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/MapReduce/Auto/AutoMapReduceIndex.cs
  src/Raven.Server/Documents/Indexes/MapReduce/MapReduceIndexBase.cs
  src/Raven.Server/Documents/Indexes/MapReduce/MapReduceIndexingContext.cs
  src/Raven.Server/Documents/Indexes/MapReduce/MapReduceResultsStore.cs
  src/Raven.Server/Documents/Indexes/MapReduce/ReduceMapResultsBase.cs
  src/Raven.Server/Documents/Patch/PatchDocumentCommand.cs
  src/Raven.Server/Documents/Patch/ScriptRunner.cs
  src/Raven.Server/Program.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Utils/Cpu/CpuUsageExtensionPoint.cs
  src/Raven.Server/Utils/TypeConverter.cs
  src/Raven.Studio/typescript/viewmodels/database/documents/editDocument.ts
  src/Sparrow/Utils/DiskSpaceChecker.cs
  src/Voron/Data/BTrees/Tree.Stream.cs
  src/Voron/Data/Tables/Table.cs
  src/Voron/Debugging/DebugStuff.cs
  src/Voron/Debugging/DetailedStorageReport.cs
  src/Voron/Debugging/StorageReportGenerator.cs
  src/Voron/GlobalFlushingBehavior.cs
  src/Voron/Impl/FileHeaders/HeaderAccessor.cs
  src/Voron/Impl/Journal/JournalReader.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/Impl/Paging/AbstractPager.cs
  src/Voron/PageLocator.cs
  src/Voron/Platform/Win32/Win32JournalWriter.cs
  src/Voron/Platform/Win32/Win32NativeFileMethods.cs
  src/Voron/StorageEnvironment.cs
  src/Voron/StorageEnvironmentOptions.cs
  test/SlowTests/ExtensionPoints/RavenDB_12161.cs
  test/SlowTests/Issues/RavenDB_12193.cs
  test/SlowTests/Issues/RavenDB_12490.cs
  test/SlowTests/Issues/RavenDB_9553.cs
  test/SlowTests/Server/Documents/Indexing/MapReduce/RavenDB_11643.cs
  test/SlowTests/Voron/DeletionFromMultiTableWithGlobalIndex.cs
  test/SlowTests/Voron/Issues/RavenDB_12506.cs
  test/SlowTests/Voron/Storage/StorageReportGenerationTests.cs
  test/SlowTests/Voron/Storage/SyncFlushTimingTest.cs
Labels: v4.2

#8273 RavenDB-12509: dispose wind32 & posix journalWriter on exception.
  src/Voron/Platform/Posix/PosixJournalWriter.cs
  src/Voron/Platform/Win32/Win32JournalWriter.cs
Labels: v4.0

#8277 RavenDB-12524
  src/Voron/Impl/Backup/IncrementalBackup.cs
  src/Voron/Impl/Journal/JournalReader.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/Impl/Paging/AbstractPagerExtensions.cs
  src/Voron/Impl/Paging/CryptoPager.cs
  src/Voron/StorageEnvironment.cs
Labels: v4.0

#8274 RavenDB-12509_v4.1: dispose on exception in posix journal writer.
  src/Voron/Platform/Posix/PosixJournalWriter.cs
Labels: v4.1

#8276 RavenDB-12525 Failing test: SlowTests.Issues.RavenDB_5435.CanCompact
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/StorageEnvironment.cs
  test/SlowTests/Voron/Storage/SyncFlushTimingTest.cs
Labels: v4.1

#8278 RavenDB-12543 We must not update PTT of the journal file immediately …
  src/Voron/Impl/Journal/JournalFile.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/Impl/LowLevelTransaction.cs
  test/SlowTests/Voron/Issues/RavenDB_12543.cs
Labels: v4.1

#8279 RavenDB-12543 We must not update PTT of the journal file immediately …
  src/Voron/Impl/Journal/JournalFile.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/Impl/LowLevelTransaction.cs
  test/SlowTests/Voron/Issues/RavenDB_12543.cs
Labels: v4.0

#8280 RavenDB-12500 support cache for graph queries
  src/Raven.Server/Documents/Queries/Graph/GraphQueryPlan.cs
  src/Raven.Server/Documents/Queries/GraphQueryRunner.cs
  src/Raven.Server/Documents/Queries/QueryResultServerSide.cs
  test/FastTests/Graph/BasicGraphQueries.cs
Labels: v4.2

#8275 Code review changes for RavenDB-12187 fix
  src/Raven.Server/Documents/Queries/AST/QueryExpression.cs
Labels: v4.2

#8282 4.1 to 4.2 merge
  RavenDB.sln.DotSettings
  src/Raven.Client/Documents/Linq/RavenQueryableExtensions.cs
  src/Raven.Client/Documents/Session/AsyncDocumentQuery.cs
  src/Raven.Client/Documents/Session/DocumentQuery.cs
  src/Voron/Impl/Backup/IncrementalBackup.cs
  src/Voron/Impl/Journal/JournalFile.cs
  src/Voron/Impl/Journal/JournalReader.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/Impl/LowLevelTransaction.cs
  src/Voron/Impl/Paging/AbstractPagerExtensions.cs
  src/Voron/Impl/Paging/CryptoPager.cs
  src/Voron/Platform/Posix/PosixJournalWriter.cs
  src/Voron/StorageEnvironment.cs
  test/SlowTests/Issues/RavenDB-12359.cs
  test/SlowTests/Issues/RavenDB_12490.cs
  test/SlowTests/Voron/Issues/RavenDB_12543.cs
  test/SlowTests/Voron/Storage/SyncFlushTimingTest.cs
Labels: v4.2

#8284 RavenDB-12544 - Index stays in low memory state forever
  src/Raven.Server/Documents/Indexes/Index.cs
Labels: v4.1

#8283 RavenDB-12286 - Early out of memory during cleanup
  src/Voron/Impl/Scratch/ScratchBufferPool.cs
Labels: v4.1

#8285 RavenDB-12015 - remove StoreNextMapResultId from the dispose method
  src/Raven.Server/Documents/Indexes/MapReduce/MapReduceIndexingContext.cs
  src/Raven.Server/Documents/Indexes/MapReduce/ReduceMapResultsBase.cs
Labels: v4.1

#8287 RavenDB-12015 - remove StoreNextMapResultId from the dispose method
  src/Raven.Server/Documents/Indexes/MapReduce/MapReduceIndexingContext.cs
  src/Raven.Server/Documents/Indexes/MapReduce/ReduceMapResultsBase.cs
Labels: v4.0

#8261 RavenDB-12333 upgrade Jint
  libs/Jint.3.0.15-ravendb.nupkg
  libs/Jint.3.0.18-ravendb.nupkg
  src/Raven.Server/Config/Categories/PatchingConfiguration.cs
  src/Raven.Server/Documents/ETL/EtlTransformer.cs
  src/Raven.Server/Documents/ETL/Providers/Raven/RavenEtlDocumentTransformer.cs
  src/Raven.Server/Documents/ETL/Providers/SQL/SqlDocumentTransformer.cs
  src/Raven.Server/Documents/Indexes/Static/JavaScriptIndex.cs
  src/Raven.Server/Documents/Patch/JintNullPropagationReferenceResolver.cs
  src/Raven.Server/Documents/Patch/ScriptRunner.cs
  src/Raven.Server/Raven.Server.csproj
  test/FastTests/Graph/BasicGraphQueries.cs
  test/SlowTests/Issues/RavenDB-11824.cs
  test/SlowTests/Issues/RavenDB-11837.cs
  test/SlowTests/Issues/RavenDB_12333.cs
  test/SlowTests/Issues/RavenDB_2609.cs
Labels: v4.2

#8288 RavenDB-12444 - changed column names
  src/Raven.Studio/typescript/viewmodels/manage/debugAdvancedThreadsRuntime.ts
Labels: v4.1

#8289 RavenDB-12524
  src/Voron/Impl/LowLevelTransaction.cs
  src/Voron/StorageEnvironmentOptions.cs
Labels: v4.1

#8292 RavenDB-12524 Will also validate checksum of pages when copying from …
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/Impl/Scratch/ScratchBufferFile.cs
  src/Voron/Impl/Scratch/ScratchBufferPool.cs
Labels: v4.0

#8291 RavenDB-12524 Will also validate checksum of pages when copying from …
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/Impl/Scratch/ScratchBufferFile.cs
  src/Voron/Impl/Scratch/ScratchBufferPool.cs
Labels: v4.1

#8290 4.1 to 4.2 merge
  src/Raven.Server/Dashboard/ThreadsInfo.cs
  src/Raven.Server/Documents/Handlers/Debugging/ThreadsHandler.cs
  src/Raven.Server/Documents/Handlers/IndexHandler.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/IndexingRunStats.cs
  src/Raven.Server/Documents/Indexes/IndexingStatsAggregator.cs
  src/Raven.Server/Documents/Indexes/MapReduce/MapReduceIndexingContext.cs
  src/Raven.Server/Documents/Indexes/MapReduce/ReduceMapResultsBase.cs
  src/Raven.Server/Documents/Indexes/Workers/MapDocuments.cs
  src/Raven.Server/Indexing/IndexOutputFilesSummary.cs
  src/Raven.Server/Indexing/LuceneVoronDirectory.cs
  src/Raven.Server/Indexing/VoronIndexOutput.cs
  src/Raven.Server/Program.cs
  src/Raven.Server/Storage/StorageSpaceMonitor.cs
  src/Raven.Server/Utils/ExceptionHelper.cs
  src/Raven.Server/Utils/ThreadsUsage.cs
  src/Raven.Studio/typescript/commands/database/debug/getDebugThreadsRunawayCommand.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexErrors.ts
  src/Raven.Studio/typescript/viewmodels/manage/debugAdvancedThreadsRuntime.ts
  src/Raven.Studio/wwwroot/App/views/database/indexes/indexErrors.html
  src/Sparrow/ByteString.cs
  src/Voron/Data/BTrees/Tree.MultiTree.cs
  src/Voron/Data/BTrees/Tree.cs
  src/Voron/Data/RawData/ActiveRawDataSmallSection.cs
  src/Voron/Data/RawData/RawDataSection.cs
  src/Voron/Data/Tables/Table.cs
  src/Voron/Debugging/StorageReportGenerator.cs
  src/Voron/Exceptions/DiskFullException.cs
  src/Voron/Exceptions/VoronUnrecoverableErrorException.cs
  src/Voron/Impl/LowLevelTransaction.cs
  src/Voron/Impl/Scratch/ScratchBufferPool.cs
  src/Voron/Platform/Win32/Win32JournalWriter.cs
  src/Voron/StorageEnvironment.cs
  src/Voron/StorageEnvironmentOptions.cs
  test/SlowTests/Voron/Issues/RavenDB_10225_Voron.cs
  tools/TypingsGenerator/Program.cs
Labels: v4.2

#8302 RavenDB-12464 support distinct on graph queries
  src/Raven.Server/Documents/Queries/GraphQueryRunner.cs
  test/SlowTests/Graph/BasicGraphQueries.cs
Labels: v4.2

#8298 RavenDB-12096 support exact method in edge where clause
  src/Raven.Server/Documents/Queries/AST/QueryExpression.cs
Labels: v4.2

#8303 RavenDB-12524 Fixed validation during the recovery process. If a page…
  src/Voron/Impl/Journal/JournalReader.cs
  test/SlowTests/Voron/Issues/RavenDB_12524.cs
Labels: v4.1

#8307 RavenDB-12543
  src/Voron/Impl/Journal/JournalFile.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/Impl/LowLevelTransaction.cs
Labels: v4.0

#8306 RavenDB-12543
  src/Voron/Impl/Journal/JournalFile.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/Impl/LowLevelTransaction.cs
Labels: v4.1

#8310 4.1 to 4.2 merge
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/TcpHandlers/SubscriptionConnection.cs
  src/Raven.Server/Rachis/Exceptions.cs
  src/Raven.Server/Rachis/Leader.cs
  src/Raven.Server/RavenServerStartup.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/Commands/CommandBase.cs
  src/Raven.Server/ServerWide/Commands/CompareExchangeCommands.cs
  src/Raven.Server/ServerWide/Commands/ETL/UpdateEtlProcessStateCommand.cs
  src/Raven.Server/ServerWide/Commands/Subscriptions/UpdateSubscriptionClientConnectionTime.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterNodeStatusReport.cs
  src/Raven.Studio/typescript/models/resources/serverDashboard/driveUsage.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/alerts/etlTransformOrLoadErrorDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/performanceHint/pagingDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/performanceHint/requestLatencyDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/performanceHint/slowSqlDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/performanceHint/slowWriteDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/virtualOperations/virtualBulkInsertDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/virtualOperations/virtualDeleteByQueryDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/virtualOperations/virtualUpdateByQueryDetails.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexErrors.ts
  src/Raven.Studio/typescript/viewmodels/manage/debugAdvancedMemoryMappedFiles.ts
  src/Raven.Studio/typescript/viewmodels/manage/debugAdvancedObserverLog.ts
  src/Raven.Studio/typescript/viewmodels/manage/debugAdvancedThreadsRuntime.ts
  src/Raven.Studio/typescript/viewmodels/manage/trafficWatch.ts
  src/Raven.Studio/typescript/viewmodels/resources/serverDashboard.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/columns/actionColumn.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/columns/checkedColumn.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/columns/flagsColumn.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/columns/hyperlinkColumn.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/columns/sortableVirtualColumn.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/columns/textColumn.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/columns/virtualColumn.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/virtualGrid.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/virtualGridController.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/virtualRow.ts
  src/Raven.Studio/typings/_studio/dto.d.ts
  src/Raven.Studio/wwwroot/Content/css/virtual-grid.less
  src/Voron/Impl/Journal/JournalFile.cs
  src/Voron/Impl/Journal/JournalReader.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/Impl/LowLevelTransaction.cs
  test/SlowTests/Server/Documents/ETL/EtlLoaderTests.cs
  test/SlowTests/Voron/Issues/RavenDB_12524.cs
Labels: v4.2

#8312 RavenDB-12524 During the recovery let's validate the page checksum if…
  src/Voron/Impl/Journal/JournalReader.cs
Labels: v4.1

#8313 RavenDB-12524 Recovery needs to take into account that a modified pag…
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  test/SlowTests/Voron/Issues/RavenDB_12524.cs
Labels: v4.1

#8314 4.1 to 4.2 merge
  src/Voron/Impl/Journal/JournalReader.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  test/SlowTests/Voron/Issues/RavenDB_12524.cs
Labels: v4.2

#8315 RavenDB-12537
  src/Raven.Server/Documents/TcpHandlers/SubscriptionConnection.cs
  src/Raven.Server/Rachis/Exceptions.cs
  src/Raven.Server/Rachis/Leader.cs
  src/Raven.Server/RavenServerStartup.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/Commands/CommandBase.cs
  src/Raven.Server/ServerWide/Commands/CompareExchangeCommands.cs
  src/Raven.Server/ServerWide/Commands/ETL/UpdateEtlProcessStateCommand.cs
  src/Raven.Server/ServerWide/Commands/Subscriptions/UpdateSubscriptionClientConnectionTime.cs
  src/Voron/Impl/Journal/JournalFile.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/Impl/LowLevelTransaction.cs
  test/FastTests/Server/Documents/Indexing/Auto/BasicAutoMapIndexing.cs
  test/SlowTests/Issues/RavenDB_4110.cs
  test/SlowTests/Server/Documents/ETL/EtlLoaderTests.cs
Labels: v4.0

#8311 RavenDB-12505 use Set to calculate distinct array elements
  src/Raven.Client/Util/JavascriptConversionExtensions.cs
  src/Raven.Server/Documents/Queries/QueryMetadata.cs
  test/SlowTests/Client/QueriesWithCustomFunctions.cs
Labels: v4.2

#8317 RavenDB-12521 handling laod() calls outside of the map function scope
  src/Raven.Server/Documents/Indexes/Static/JavaScriptIndex.cs
  src/Raven.Server/Documents/Indexes/Static/JavaScriptMapOperation.cs
  test/FastTests/Client/Indexing/JavaScriptIndexTests.cs
Labels: v4.1

#8318 Un-skipping and fixing test for RavenDB-12187
  test/SlowTests/Graph/AdvancedGraphQueries.cs
Labels: v4.2

#8319 RavenDB-12528 NRE when trying to increment a counter for a conflicted…
  src/Raven.Server/Documents/ConflictsStorage.cs
  src/Raven.Server/Documents/Handlers/CountersHandler.cs
  src/Raven.Server/Documents/Replication/ConflictManager.cs
  src/Raven.Server/Documents/Replication/ResolveConflictOnReplicationConfigurationChange.cs
  test/SlowTests/Client/Counters/CountersReplication.cs
Labels: v4.1

#8322 RavenDB-12530 Revisions flag isn't cleared when there are no revisions
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  test/FastTests/Server/Documents/Revisions/RevisionsTests.cs
Labels: v4.1

#8325 RavenDB-12570 - Unexpected exception occurred during map index
  src/Raven.Server/Documents/Indexes/CollectionOfBloomFilters.cs
  src/Raven.Server/Documents/Indexes/Errors/FaultyInMemoryIndex.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/MapIndexBase.cs
  src/Raven.Server/Documents/Indexes/MapReduce/MapReduceIndexBase.cs
  src/Raven.Server/Documents/Indexes/Workers/MapDocuments.cs
  test/FastTests/Server/Documents/Indexing/BasicAnalyzers.cs
  test/FastTests/Server/Documents/Indexing/BloomFilterTests.cs
Labels: v4.1

#8324 RavenDB-12556 Assign to `_journalsToDelete` moved from the task that passed to write transaction
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  test/SlowTests/Voron/Storage/SyncFlushTimingTest.cs
Labels: v4.1

#8327 RavenDB-12571 making sure we don't optimize query steps with paging
  src/Raven.Server/Documents/Queries/Graph/EdgeCollectionDestinationRewriter.cs
  src/Raven.Server/Documents/Queries/Graph/QueryQueryStep.cs
Labels: v4.2

#8326 RavenDB-11871 Journal applicator keep applying journals even if the i…
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  test/SlowTests/Voron/RavenDB-11871.cs
Labels: v4.1

#8328 RavenDB-12575 - Fix document size formatting
  src/Raven.Studio/typescript/viewmodels/database/documents/editDocument.ts
  src/Raven.Studio/wwwroot/App/views/database/documents/editDocument.html
Labels: v4.1

#8329 RavenDB-12574 - fix stream size calculation overflow
  src/Voron/Data/BTrees/Tree.Stream.cs
Labels: v4.1

#8330 RavenDB-12573 - fix IndexOutOfRangeException : Index was outside the bounds of the array
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/IndexQueryingScope.cs
  test/SlowTests/Issues/RavenDB-12573.cs
Labels: v4.1

#8331 RavenDB-12576 fixing server not coming up
  src/Sparrow/Json/JsonOperationContext.cs
Labels: v4.2

#8334 RavenDB-12554 - low memory trigger calculation improvements
  src/Sparrow/LowMemory/MemoryInformation.cs
Labels: v4.1

#8338 4.1 to 4.2 merge
  src/Raven.Server/Config/Categories/MemoryConfiguration.cs
  src/Raven.Server/Dashboard/MachineResourcesNotificationSender.cs
  src/Raven.Server/Documents/ConflictsStorage.cs
  src/Raven.Server/Documents/Handlers/CountersHandler.cs
  src/Raven.Server/Documents/Indexes/CollectionOfBloomFilters.cs
  src/Raven.Server/Documents/Indexes/Errors/FaultyInMemoryIndex.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/MapIndexBase.cs
  src/Raven.Server/Documents/Indexes/MapReduce/MapReduceIndexBase.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/IndexQueryingScope.cs
  src/Raven.Server/Documents/Indexes/Static/JavaScriptIndex.cs
  src/Raven.Server/Documents/Indexes/Static/JavaScriptMapOperation.cs
  src/Raven.Server/Documents/Indexes/Workers/MapDocuments.cs
  src/Raven.Server/Documents/Replication/ConflictManager.cs
  src/Raven.Server/Documents/Replication/ResolveConflictOnReplicationConfigurationChange.cs
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Utils/PoolOfThreads.cs
  src/Raven.Studio/typescript/common/generalUtils.ts
  src/Raven.Studio/typescript/viewmodels/database/documents/editDocument.ts
  src/Raven.Studio/typescript/viewmodels/manage/debugAdvancedThreadsRuntime.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/columns/textColumn.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/virtualGrid.ts
  src/Raven.Studio/wwwroot/App/views/database/documents/editDocument.html
  src/Sparrow/LowMemory/LowMemoryNotification.cs
  src/Sparrow/LowMemory/MemoryInformation.cs
  src/Sparrow/Utils/NativeMemory.cs
  src/Voron/Data/BTrees/Tree.Stream.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  test/FastTests/Client/Indexing/JavaScriptIndexTests.cs
  test/FastTests/Server/Documents/Indexing/BasicAnalyzers.cs
  test/FastTests/Server/Documents/Indexing/BloomFilterTests.cs
  test/FastTests/Server/Documents/Revisions/RevisionsTests.cs
  test/SlowTests/Client/Counters/CountersReplication.cs
  test/SlowTests/Issues/RavenDB-12573.cs
  test/SlowTests/Voron/RavenDB-11871.cs
  test/SlowTests/Voron/Storage/SyncFlushTimingTest.cs
Labels: v4.2

#8337 RavenDB-12407:
  src/Raven.Client/Documents/Session/InMemoryDocumentSessionOperations.cs
  src/Raven.Client/Documents/Subscriptions/DocumentSubscriptions.cs
  src/Raven.Client/Http/HttpCache.cs
  src/Raven.Server/ServerWide/OperationCancelToken.cs
  src/Sparrow/ByteString.cs
  src/Sparrow/Json/ArenaMemoryAllocator.cs
  src/Sparrow/Json/BlittableJsonDocumentBuilder.cs
  src/Sparrow/Json/BlittableWriter.cs
  src/Sparrow/Json/JsonContextPoolBase.cs
  src/Sparrow/Json/JsonOperationContext.cs
  src/Sparrow/Json/Parsing/ObjectJsonParser.cs
  src/Sparrow/Json/UnmanagedBuffersPool.cs
  src/Sparrow/Json/UnmanagedWriteBuffer.cs
  src/Sparrow/Threading/DisposeOnce.cs
Labels: v4.2

#8342 RavenDB-12582 When the server returns PatchOperation results, certain fields are missing
  src/Raven.Server/Documents/Handlers/DocumentHandler.cs
  test/FastTests/Issues/RavenDB_12582.cs
Labels: v4.1

#8343 RavenDB-12407 Fixing finalization
  src/Sparrow/Json/JsonContextPoolBase.cs
  src/Sparrow/Threading/DisposeOnce.cs
Labels: v4.2

#8189 RavenDB-12012 Skipped index backup during incremental backup
  src/Raven.Client/Documents/Operations/Backups/BackupStatus.cs
  src/Raven.Client/Documents/Operations/Backups/PeriodicBackupStatus.cs
  src/Raven.Client/ServerWide/DatabaseRecord.cs
  src/Raven.Server/Documents/PeriodicBackup/BackupTask.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  test/SlowTests/Server/Documents/PeriodicBackup/RavenDB_12012.cs
Labels: v4.1

#8347 RavenDB-12259 added projection (true) to metadata when projection is used via subscriptions
  src/Raven.Server/Documents/Subscriptions/SubscriptionPatchDocument.cs
  src/Raven.Server/Documents/TcpHandlers/SubscriptionDocumentsFetcher.cs
  test/SlowTests/Issues/RavenDB_12259.cs
Labels: v4.1

#8346 RavenDB-12588: If we pass allowErrors=true. WaitForIndexing should wait for all indexes to become 'non-stale'.
  test/Tests.Infrastructure/RavenTestBase.cs
Labels: v4.2

#8351 fix for RavenDB-12591
  src/Raven.Server/Documents/Queries/Graph/QueryQueryStep.cs
  test/SlowTests/Graph/AdvancedGraphQueries.cs
  test/SlowTests/Graph/BasicGraphQueries.cs
  test/SlowTests/Graph/IntersectionTests.cs
Labels: v4.2

#8350 fix for RavenDB-12563
  src/Raven.Server/Documents/Queries/AST/GraphQuerySyntaxValidatorVisitor.cs
  src/Raven.Server/Documents/Queries/Parser/QueryParser.cs
  test/SlowTests/Issues/RavenDB-12563.cs
Labels: v4.2

#8345 RavenDB-12584: Add type conversions to DynamicArray when using Contains, IndexOf or LastIndexOf methods to get proper results.
  src/Raven.Server/Documents/Indexes/Static/DynamicArray.cs
  test/SlowTests/Issues/RavenDB_12584.cs
Labels: v4.2

#8355 RavenDB-12259 projections should not be registered in subscription session
  src/Raven.Client/Documents/Subscriptions/SubscriptionBatch.cs
  test/SlowTests/Issues/RavenDB_12259.cs
Labels: v4.1

#8354 RavenDB-12250 & RavenDB-12257
  src/Raven.Client/Documents/Session/AbstractDocumentQuery.cs
  src/Raven.Client/Documents/Session/IncludesUtil.cs
  src/Raven.Client/Documents/Session/Loaders/IncludeBuilder.cs
  src/Raven.Client/Documents/Subscriptions/DocumentSubscriptions.cs
  src/Raven.Client/Documents/Subscriptions/SubscriptionCriteria.cs
  src/Raven.Server/Documents/Indexes/Static/DynamicArray.cs
  src/Raven.Server/Documents/Indexes/Static/Roslyn/MapFunctionProcessor.cs
  src/Raven.Server/Documents/Indexes/Static/Roslyn/Rewriters/IsRewriter.cs
  src/Raven.Server/Documents/Indexes/Static/Roslyn/Rewriters/ReduceIndex/ReduceFunctionProcessor.cs
  test/FastTests/Server/Documents/Queries/Dynamic/MapReduce/BasicDynamicMapReduceQueries.cs
  test/FastTests/Server/Documents/Revisions/RevisionsTests.cs
  test/SlowTests/Core/Commands/Documents.cs
  test/SlowTests/Issues/RavenDB-11422.cs
  test/SlowTests/Issues/RavenDB_12250.cs
  test/SlowTests/Issues/RavenDB_12257.cs
  test/SlowTests/Server/Documents/Revisions/RevisionsReplication.cs
Labels: v4.2

#8360 RavenDB-11870: IOMetrics SetFileSize should receive long
  src/Voron/Platform/Win32/Win32JournalWriter.cs
Labels: v4.0

#8361 RavenDB-12526 fixed sorting when clicking on arrows
  src/Raven.Studio/typescript/widgets/virtualGrid/virtualGrid.ts
Labels: v4.1

#8364 4.1 to 4.2 merge
  src/Raven.Client/Documents/Operations/Backups/BackupStatus.cs
  src/Raven.Client/Documents/Operations/Backups/PeriodicBackupStatus.cs
  src/Raven.Client/Documents/Subscriptions/SubscriptionBatch.cs
  src/Raven.Client/ServerWide/DatabaseRecord.cs
  src/Raven.Server/Documents/Handlers/DocumentHandler.cs
  src/Raven.Server/Documents/PeriodicBackup/BackupTask.cs
  src/Raven.Server/Documents/Subscriptions/SubscriptionPatchDocument.cs
  src/Raven.Server/Documents/TcpHandlers/SubscriptionDocumentsFetcher.cs
  src/Raven.Server/Json/BlittableJsonTextWriterExtensions.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/Smuggler/Documents/Handlers/SmugglerHandler.cs
  src/Raven.Server/Utils/ProcessExtensions.cs
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
  src/Raven.Studio/typescript/models/resources/serverDashboard/storagePieChart.ts
  src/Raven.Studio/typescript/viewmodels/database/documents/documents.ts
  src/Raven.Studio/typescript/viewmodels/wizard/nodes.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/virtualGrid.ts
  src/Raven.Studio/wwwroot/App/views/wizard/nodes.html
  src/Raven.Studio/wwwroot/Content/css/styles-common.less
  src/Sparrow/Meters/IoMeterBuffer.cs
  src/Voron/Platform/Win32/Win32JournalWriter.cs
  test/FastTests/Issues/RavenDB_12582.cs
  test/SlowTests/Issues/RavenDB_12259.cs
  test/SlowTests/Server/Documents/PeriodicBackup/RavenDB_12012.cs
Labels: v4.2

#8366 RavenDB-12524 we need to dispose TempPagerTransaction resources
  src/Voron/Impl/Journal/WriteAheadJournal.cs
Labels: v4.0

#8367 RavenDB-12524 we need to dispose TempPagerTransaction resources
  src/Voron/Impl/Journal/WriteAheadJournal.cs
Labels: v4.1
