Repository ravendb/ravendb, pull requests merged in 2019-01, with the labels that each got.

#8369 RavenDB-12601 - Using cluster transactions doesn't properly update the database change vector
  src/Raven.Server/Documents/Handlers/BatchHandler.cs
  src/Raven.Server/ServerWide/Commands/ClusterTransactionCommand.cs
  test/FastTests/Server/Replication/ReplicationTestBase.cs
  test/SlowTests/Cluster/ClusterTransactionTests.cs
  test/SlowTests/Issues/RavenDB_12601.cs
Labels: v4.1

#8377 RavenDB-12214: Transform script example at Import Data doesn't work.
  src/Raven.Studio/typescript/models/database/tasks/migrateDatabaseModel.ts
  src/Raven.Studio/typescript/models/database/tasks/migrateRavenDbDatabaseModel.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/exportDatabase.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/importDatabaseFromFile.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/migrateDatabase.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/migrateRavenDbDatabase.ts
Labels: v4.2

#8378 4.1 to 4.2 merge
  src/Raven.Server/Documents/Handlers/BatchHandler.cs
  src/Raven.Server/ServerWide/Commands/ClusterTransactionCommand.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  test/FastTests/Server/Replication/ReplicationTestBase.cs
  test/SlowTests/Cluster/ClusterTransactionTests.cs
  test/SlowTests/Issues/RavenDB_12601.cs
Labels: v4.2

#8382 RavenDB-12616 we need to dispose request executor used in SubscriptionWorker
  src/Raven.Client/Documents/Subscriptions/SubscriptionWorker.cs
Labels: v4.0

#8381 RavenDB-12616 we need to dispose request executor used in SubscriptionWorker
  src/Raven.Client/Documents/Subscriptions/SubscriptionWorker.cs
Labels: v4.1

#8383 RavenDB-12556 Last flushed properties binned together to prevent using half updated values
  src/Voron/Impl/Journal/WriteAheadJournal.cs
Labels: v4.1

#8389 RavenDB-12601 - update only the database change vector and the document CV when we have a cluster tx
  src/Raven.Server/Documents/Handlers/BatchHandler.cs
  src/Raven.Server/ServerWide/Commands/ClusterTransactionCommand.cs
  test/SlowTests/Issues/RavenDB_12601.cs
Labels: v4.1

#8385 RavenDB-11698 allow configuring different max log file size
  src/Raven.Server/Config/Categories/LogsConfiguration.cs
  src/Raven.Server/Program.cs
  src/Sparrow/Logging/LoggingSource.cs
Labels: v4.2

#8390 RavenDB-12612: Fix failing SchemaUpgrade.Issues.RavenDB_12321
  test/SlowTests/SchemaUpgrade/Issues/RavenDB_12321.cs
Labels: v4.1

#8398 RavenDB-12618 install --dev natives@1.1.6 as a workaround for gulp 3 …
  src/Raven.Studio/package-lock.json
  src/Raven.Studio/package.json
Labels: v4.0

#8399 RavenDB-12618 install --dev natives@1.1.6 as a workaround for gulp 3 …
  src/Raven.Studio/package-lock.json
  src/Raven.Studio/package.json
Labels: v4.1

#8391 RavenDB-8799 added enable/disable methods to subscriptions API
  src/Raven.Client/Documents/Operations/OngoingTasks/ToggleOngoingTaskStateOperation.cs
  src/Raven.Client/Documents/Subscriptions/DocumentSubscriptions.cs
  src/Raven.Server/Documents/Subscriptions/SubscriptionStorage.cs
  test/SlowTests/Issues/RavenDB_8799.cs
Labels: v4.2

#8400 RavenDB-12615: Solved race in updating the single attempt DuringDispo…
  src/Sparrow/Threading/DisposeOnce.cs
Labels: v4.2

#8401 RavenDB-12606 fixing visitors to recursive step
  src/Raven.Server/Documents/Queries/Graph/EdgeCollectionDestinationRewriter.cs
  src/Raven.Server/Documents/Queries/Graph/EdgeQueryStep.cs
  src/Raven.Server/Documents/Queries/Graph/GraphQueryDetailedReporter.cs
  src/Raven.Server/Documents/Queries/Graph/QueryPlanRewriter.cs
  src/Raven.Server/Documents/Queries/Graph/QueryPlanVisitor.cs
  src/Raven.Server/Documents/Queries/Graph/QueryQueryStep.cs
  src/Raven.Server/Documents/Queries/Graph/RecursionQueryStep.cs
Labels: v4.2

#8407 4.1 to 4.2 merge
  src/Raven.Client/Exceptions/Documents/Subscriptions/SubscriptionDoesNotBelongToNodeException.cs
  src/Raven.Server/Documents/Patch/BlittableObjectInstance.cs
  src/Raven.Server/Documents/Patch/ScriptRunner.cs
  src/Raven.Server/Documents/Patch/ScriptRunnerResult.cs
  src/Raven.Server/Documents/Queries/Results/QueryResultRetrieverBase.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/Commands/ClusterTransactionCommand.cs
  src/Raven.Server/ServerWide/Commands/CommandBase.cs
  src/Raven.Server/ServerWide/Commands/DeleteCertificateCollectionFromClusterCommand.cs
  src/Raven.Server/ServerWide/Commands/DeleteCertificateFromClusterCommand.cs
  src/Raven.Server/ServerWide/Commands/DeleteMultipleValuesCommand.cs
  src/Raven.Server/ServerWide/Commands/DeleteValueCommand.cs
  src/Raven.Server/ServerWide/Commands/ETL/AddEtlCommand.cs
  src/Raven.Server/ServerWide/Commands/Indexes/PutAutoIndexCommand.cs
  src/Raven.Server/ServerWide/Commands/Indexes/PutIndexCommand.cs
  src/Raven.Server/ServerWide/Commands/Indexes/SetIndexLockCommand.cs
  src/Raven.Server/ServerWide/Commands/Indexes/SetIndexStateCommand.cs
  src/Raven.Server/ServerWide/Commands/PeriodicBackup/UpdatePeriodicBackupCommand.cs
  src/Raven.Server/ServerWide/Commands/Subscriptions/DeleteSubscriptionCommand.cs
  src/Raven.Server/ServerWide/Commands/Subscriptions/PutSubscriptionCommand.cs
  src/Raven.Server/ServerWide/Commands/Subscriptions/ToggleSubscriptionStateCommand.cs
  src/Raven.Server/ServerWide/Commands/UpdateClusterIdentityCommand.cs
  src/Raven.Server/ServerWide/Commands/UpdateDatabaseCommand.cs
  src/Raven.Server/ServerWide/Commands/UpdateExternalReplicationCommand.cs
  src/Raven.Studio/package-lock.json
  src/Raven.Studio/package.json
  src/Voron/Impl/Journal/JournalReader.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/StorageEnvironment.cs
  test/SlowTests/Issues/RavenDB-12442.cs
Labels: v4.2

#8408 RavenDB-11698 set minimum log file size value to 16 mb
  src/Raven.Server/Config/Categories/LogsConfiguration.cs
Labels: v4.2

#8409 4.1 to 4.2 merge
  src/Raven.Server/Documents/ConflictsStorage.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Sparrow/Json/BlittableJsonReaderArray.cs
  src/Sparrow/Json/BlittableJsonReaderBase.cs
  src/Sparrow/Json/BlittableJsonReaderObject.cs
  src/Sparrow/Json/JsonOperationContext.cs
  src/Voron/Impl/Transaction.cs
  test/BenchmarkTests/BenchmarkTests.csproj
  test/FastTests/FastTests.csproj
  tools/Raven.Migrator/Raven.Migrator.csproj
Labels: v4.2

#8414 4.1 to 4.2 merge
  src/Voron/Impl/Journal/JournalFile.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
Labels: v4.2

#8417 RavenDB-12611 when we are restoring a backup and it is relevant to the current node then we need to wait for the database record change to be actually applied to the database
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreBackupTask.cs
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
Labels: v4.1

#8420 tests for RavenDB-12059
  test/SlowTests/Issues/RavenDB-12059.cs
Labels: v4.2

#8421 RavenDB-7070 more reliable test
  test/SlowTests/Server/Documents/ETL/SQL/SqlEtlTests.cs
Labels: v4.0

#8428 RavenDB-12636
  src/Raven.Server/Rachis/Leader.cs
Labels: v4.1

#8429 RavenDB-12400 implement CappedMaxResults for graph queries
  src/Raven.Server/Documents/Queries/GraphQueryRunner.cs
Labels: v4.2

#8432 4.1 to 4.2 merge
  src/Raven.Server/Documents/Indexes/Static/EsprimaVisitor.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreBackupTask.cs
  src/Raven.Server/Rachis/Leader.cs
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
  src/Voron/GlobalFlushingBehavior.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/StorageEnvironmentOptions.cs
  test/FastTests/Client/Indexing/JavaScriptIndexTests.cs
  test/SlowTests/Server/Documents/ETL/SQL/SqlEtlTests.cs
  test/SlowTests/Voron/Storage/SyncFlushTimingTest.cs
Labels: v4.2

#8434 RavenDB-9913 [docker scripts] fix regex for patch version number > 9
  docker/build-nanoserver.ps1
  docker/build-ubuntu.ps1
  docker/common.ps1
  docker/publish-nanoserver.ps1
  docker/publish-ubuntu.ps1
Labels: v4.0

#8437 RavenDB-12561 Detect if running on cloud and suggest docs for deployment
  src/Raven.Server/Commercial/SetupParameters.cs
  src/Raven.Server/Web/System/SetupHandler.cs
  src/Raven.Studio/typescript/models/wizard/serverSetup.ts
  src/Raven.Studio/typescript/viewmodels/wizard/setupShell.ts
  src/Raven.Studio/wwwroot/App/views/wizard/setupShell.html
Labels: v4.2

#8441 RavenDB-9913 copy missing script to artifacts for docker build chain
  scripts/docker.ps1
Labels: v4.0

#8442 RavenDB-9913 copy missing script to artifacts for docker build chain
  scripts/docker.ps1
Labels: v4.1

#8440 RavenDB-12610
  src/Raven.Client/Exceptions/ExceptionDispatcher.cs
  src/Raven.Client/Extensions/ExceptionExtensions.cs
  src/Raven.Client/Http/RequestExecutor.cs
  src/Raven.Server/Documents/Replication/IncomingReplicationHandler.cs
  src/Raven.Server/Extensions/ExceptionExtensions.cs
  src/Raven.Server/Smuggler/Migration/ApiKey/TaskExtensions.cs
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
  src/Raven.Server/Web/System/DatabasesHandler.cs
Labels: v4.0

#8446 RavenDB-12650 JS projections on map reduce index should use IdentityP…
  src/Raven.Client/Documents/Linq/RavenQueryProviderProcessor.cs
  src/Raven.Client/Util/JavascriptConversionExtensions.cs
  test/SlowTests/Issues/RavenDB_12650.cs
Labels: v4.1

#8450 RavenDB-12654 Add ability to provide custom comparator in virtual grid
  src/Raven.Studio/typescript/common/generalUtils.ts
  src/Raven.Studio/typescript/models/resources/serverDashboard/driveUsage.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/alerts/etlTransformOrLoadErrorDetails.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexErrors.ts
  src/Raven.Studio/typescript/viewmodels/manage/debugAdvancedObserverLog.ts
  src/Raven.Studio/typescript/viewmodels/manage/trafficWatch.ts
  src/Raven.Studio/typescript/viewmodels/resources/serverDashboard.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/columns/textColumn.ts
  src/Raven.Studio/typings/_studio/dto.d.ts
Labels: v4.2

#8451 RavenDB-12384 Add an ability to select theme in setup wizard
  src/Raven.Studio/typescript/viewmodels/wizard/setupShell.ts
  src/Raven.Studio/wwwroot/App/views/wizard/setupShell.html
  src/Raven.Studio/wwwroot/Content/css/pages/setup.less
  src/Raven.Studio/wwwroot/Content/css/pages/themes.less
Labels: v4.2

#8454 RavenDB-12650 Simplifying the implementation - no need to return inne…
  src/Raven.Client/Util/JavascriptConversionExtensions.cs
Labels: v4.1

#8455 RavenDB-12610 we need to throw when self-checks are done
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
Labels: v4.0

#8456 4.1 to 4.2 merge
  src/Raven.Client/Documents/Linq/RavenQueryProviderProcessor.cs
  src/Raven.Client/Exceptions/ExceptionDispatcher.cs
  src/Raven.Client/Extensions/ExceptionExtensions.cs
  src/Raven.Client/Http/RequestExecutor.cs
  src/Raven.Client/Util/JavascriptConversionExtensions.cs
  src/Raven.Server/Extensions/ExceptionExtensions.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterMaintenanceWorker.cs
  src/Raven.Server/Smuggler/Migration/ApiKey/TaskExtensions.cs
  src/Raven.Server/Web/RequestHandler.cs
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
  src/Raven.Server/Web/System/DatabasesHandler.cs
  test/RachisTests/DatabaseCluster/ReplicationTests.cs
  test/SlowTests/Client/Subscriptions/CriteriaScript.cs
  test/SlowTests/Issues/RavenDB_12650.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
  test/Tests.Infrastructure/RavenTestBase.cs
Labels: v4.2

#8460 RavenDB-12661 Fixing the order of disposing blittables in ApplyMetada…
  src/Raven.Client/Documents/Session/Operations/BatchOperation.cs
  test/SlowTests/Issues/RavenDB_12661.cs
Labels: v4.1

#8464 Last change that needs to be done for RavenDB-12503
  test/SlowTests/Graph/AdvancedGraphQueries.cs
Labels: v4.2

#8462 Adding regression tests for an edge case of RavenDB-11676
  test/SlowTests/Issues/RavenDB-11676.cs
Labels: v4.2

#8469 RavenDB-12609 Setup wizard - Cant enter IPv6 at setup wizard
  src/Raven.Studio/typescript/common/extensions.ts
  src/Raven.Studio/typescript/common/generalUtils.ts
  src/Raven.Studio/typescript/models/wizard/ipEntry.ts
  src/Raven.Studio/typescript/models/wizard/nodeInfo.ts
  src/Raven.Studio/typescript/viewmodels/wizard/domain.ts
  src/Raven.Studio/typescript/viewmodels/wizard/nodes.ts
  src/Raven.Studio/typescript/viewmodels/wizard/unsecured.ts
  src/Raven.Studio/typings/_studio/dto.d.ts
Labels: v4.2

#8470 RavenDB-12671 Fixing error handling when import operation fails befor…
  src/Raven.Client/Documents/Smuggler/DatabaseSmuggler.cs
Labels: v4.1

#8472 4.1 to 4.2 merge
  src/Raven.Client/Documents/Indexes/ExpressionStringBuilder.cs
  src/Raven.Client/Documents/Session/Operations/BatchOperation.cs
  src/Raven.Client/Documents/Smuggler/DatabaseSmuggler.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  src/Raven.Server/Utils/IOExtensions.cs
  src/Raven.Server/Web/RequestHandler.cs
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
  test/RachisTests/DatabaseCluster/ReplicationTests.cs
  test/SlowTests/Issues/RavenDB_12649.cs
  test/SlowTests/Issues/RavenDB_12652.cs
  test/SlowTests/Issues/RavenDB_12661.cs
  test/SlowTests/MailingList/EnumAsInts.cs
Labels: v4.2

#8452 PrefetchingBehavior continuations can execute synchronously because they are short lived
  Raven.Database/Prefetching/PrefetchingBehavior.cs
Labels: v3.5

#8481 RavenDB-12689: Size might be taken from existing DataDir of old test,…
  test/SlowTests/Voron/Storage/InitialSize.cs
Labels: v4.1

#8482 RavenDB-12689: Size might be taken from existing DataDir of old test,…
  test/SlowTests/Voron/Storage/InitialSize.cs
Labels: v4.0

#8484 RavenDB-12687: Fix test exception type assertion
  test/SlowTests/Issues/RavenDB-11836.cs
Labels: v4.0

#8483 RavenDB-12687: Fix test exception type assertion
  test/SlowTests/Issues/RavenDB-11836.cs
Labels: v4.1

#8486 4.1 to 4.2 merge
  src/Raven.Client/Documents/Changes/ChangeNotification.cs
  src/Raven.Client/Documents/Changes/DatabaseChanges.cs
  src/Raven.Client/Http/RequestExecutor.cs
  src/Raven.Client/ServerWide/Commands/GetDatabaseTopologyCommand.cs
  src/Raven.Server/Documents/ChangesClientConnection.cs
  src/Raven.Server/Documents/DocumentsChanges.cs
  src/Raven.Server/Documents/Handlers/ChangesHandler.cs
  src/Raven.Server/RavenServer.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Utils/Cli/RavenCli.cs
  src/Raven.Server/Web/Authentication/AdminCertificatesHandler.cs
  src/Raven.Studio/wwwroot/App/views/manage/certificates.html
  test/SlowTests/Bugs/AggressiveCaching.cs
  test/SlowTests/Cluster/ClusterOperationTests.cs
  test/SlowTests/Issues/RavenDB-11836.cs
  test/SlowTests/Voron/Storage/InitialSize.cs
  test/StressTests/Voron/HugeTransactions.cs
Labels: v4.2

#8491 RavenDB-11637 fixing test
  test/RachisTests/DatabaseCluster/ReplicationTests.cs
Labels: v4.0

#8492 RavenDB-11637 fixing test
  test/RachisTests/DatabaseCluster/ReplicationTests.cs
Labels: v4.1

#8499 fix for RavenDB-12638
  src/Raven.Server/Documents/Queries/Graph/GraphQueryPlan.cs
  test/SlowTests/Issues/RavenDB-12638.cs
Labels: v4.2

#8463 RavenDB-12664 - cancel the token to let the task complete
  src/Raven.Server/ServerWide/ServerStore.cs
Labels: v4.1

#8500 RavenDB-12557 CopyOnWriteMode is currently not supported for 32 bits
  test/SlowTests/Issues/RavenDB_12557.cs
Labels: v4.1

#8501 RavenDB-12557 CopyOnWriteMode is currently not supported for 32 bits
  test/SlowTests/Issues/RavenDB_12557.cs
Labels: v4.0

#8503 RavenDB-12706 - wait for the tasks to complete before disposing the cancellation token
  src/Raven.Server/ServerWide/ServerStore.cs
Labels: v4.1

#8508 4.1 to 4.2 merge
  src/Raven.Server/Documents/CountersStorage.cs
  src/Raven.Server/RavenServer.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/SecretProtection.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Utils/CertificateUtils.cs
  src/Raven.Server/Web/System/SetupHandler.cs
  src/Raven.Studio/typescript/models/resources/creation/databaseCreationModel.ts
  src/Raven.Studio/wwwroot/App/views/database/query/query.html
  src/Sparrow/LowMemory/MemoryInformation.cs
  src/Voron/Exceptions/DiskFullException.cs
  src/Voron/Exceptions/IncreasingDataFileInCopyOnWriteModeException.cs
  src/Voron/Impl/Paging/AbstractPager.cs
  src/Voron/Platform/Win32/WindowsMemoryMapPager.cs
  test/RachisTests/DatabaseCluster/ReplicationTests.cs
  test/SlowTests/Authentication/AuthenticationClusterTests.cs
  test/SlowTests/Cluster/ClusterTransactionTests.cs
  test/SlowTests/Issues/RavenDB_12557.cs
  test/Tests.Infrastructure/TestBase.cs
  tools/Voron.Recovery/Recovery.cs
Labels: v4.2

#8509 RavenDB-12693
  src/Voron/GlobalFlushingBehavior.cs
  src/Voron/StorageEnvironmentOptions.cs
  test/SlowTests/Voron/RavenDB-11871.cs
  test/SlowTests/Voron/Storage/SyncFlushTimingTest.cs
Labels: v4.1

#8511 RavenDB-12714 Expose a way to gather managed allocation data at runtime
  src/Raven.Server/Web/System/AdminAllocationDebugHandler.cs
Labels: v4.2

#8513 RavenDB-12717 Let's use a dedicated server for test that deals with s…
  test/SlowTests/Issues/RavenDB_11440.cs
Labels: v4.1

#8512 Do not log TaskCanceledException with WARN
  Raven.Database/Prefetching/PrefetchingBehavior.cs
Labels: v3.5

#8514 RavenDB-12423 Improve error message in the reduce phase
  src/Raven.Server/Documents/Indexes/MapReduce/ReduceMapResultsBase.cs
Labels: v4.1

#8515 RavenDB-12333 upgraded jint
  libs/Jint.3.0.18-ravendb.nupkg
  libs/Jint.3.0.19-ravendb.nupkg
  src/Raven.Server/Documents/Indexes/Static/JavaScriptMapOperation.cs
  src/Raven.Server/Documents/Indexes/Static/JavaScriptReduceOperation.cs
  src/Raven.Server/Documents/Patch/JintDateTimeConverter.cs
  src/Raven.Server/Documents/Patch/JintEnumConverter.cs
  src/Raven.Server/Documents/Patch/JintGuidConverter.cs
  src/Raven.Server/Documents/Patch/JintStringConverter.cs
  src/Raven.Server/Documents/Patch/JintTimeSpanConverter.cs
  src/Raven.Server/Documents/Patch/ScriptRunner.cs
  src/Raven.Server/Extensions/JintExtensions.cs
  src/Raven.Server/Raven.Server.csproj
  test/FastTests/Client/Indexing/JavaScriptIndexTests.cs
Labels: v4.2

#8517 4.1 to 4.2 merge
  src/Raven.Server/Documents/DocumentPutAction.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Indexes/MapReduce/ReduceMapResultsBase.cs
  src/Raven.Server/Smuggler/Documents/DatabaseSmuggler.cs
  src/Voron/GlobalFlushingBehavior.cs
  src/Voron/StorageEnvironmentOptions.cs
  test/SlowTests/Issues/RavenDB_11440.cs
  test/SlowTests/Voron/RavenDB-11871.cs
  test/SlowTests/Voron/Storage/SyncFlushTimingTest.cs
Labels: v4.2

#8524 RavenDB-12627 Prepare icons for new 4.2 features
  src/Raven.Studio/typescript/viewmodels/manage/runningQueries.ts
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.eot
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.svg
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.ttf
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.woff
  src/Raven.Studio/wwwroot/Content/css/icons.less
Labels: v4.2

#8522 RavenDB-12646 Wrong number of revisions after backup and restore
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreBackupTask.cs
  test/SlowTests/Issues/RavenDB_12646.cs
Labels: v4.1

#8526 RavenDB-12526 femove cell coloring on sorted tables
  src/Raven.Studio/wwwroot/Content/css/virtual-grid.less
Labels: v4.1

#8527 RavenDB-12342 Issues with long database names when env is set
  src/Raven.Studio/wwwroot/App/views/shell.html
  src/Raven.Studio/wwwroot/Content/css/basic-layout.less
  src/Raven.Studio/wwwroot/Content/css/bootstrap/badges.less
Labels: v4.2

#8528 RavenDB-12716 give the subscription a little time to receive the doc
  test/SlowTests/Cluster/ClusterOperationTests.cs
Labels: v4.1

#8529 RavenDB-9812: removed unnecessary disposes since we are inside using.
  src/Raven.Server/Documents/Replication/ReplicationDocumentSender.cs
Labels: v4.2

#8534 4.1 to 4.2 merge
  src/Raven.Client/Documents/Queries/QueryResult.cs
  src/Raven.Client/Documents/Session/QueryStatistics.cs
  src/Raven.Server/Documents/Handlers/Debugging/ThreadsHandler.cs
  src/Raven.Server/Documents/Handlers/DocumentHandler.cs
  src/Raven.Server/Documents/Handlers/SubscriptionsHandler.cs
  src/Raven.Server/Documents/Includes/IncludeDocumentsCommand.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreBackupTask.cs
  src/Raven.Server/Documents/Queries/Dynamic/CollectionQueryRunner.cs
  src/Raven.Server/Documents/Queries/GraphQueryRunner.cs
  src/Raven.Server/Documents/Queries/Results/GraphQueryResultRetriever.cs
  src/Raven.Server/Documents/Queries/Results/QueryResultRetrieverBase.cs
  src/Raven.Server/Documents/Replication/IncomingReplicationHandler.cs
  src/Raven.Server/Documents/TcpHandlers/SubscriptionConnection.cs
  src/Raven.Server/Documents/TcpHandlers/SubscriptionDocumentsFetcher.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Server/Utils/ThreadsUsage.cs
  src/Raven.Studio/wwwroot/Content/css/virtual-grid.less
  test/SlowTests/Cluster/ClusterOperationTests.cs
  test/SlowTests/Issues/RavenDB_12383.cs
  test/SlowTests/Issues/RavenDB_12646.cs
  test/SlowTests/Server/Documents/PeriodicBackup/EncryptedBackupTest.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v4.2

#8535 RavenDB-12737 - expected exceptions handling
  src/Raven.Server/Rachis/CandidateAmbassador.cs
  src/Raven.Server/Rachis/Elector.cs
  src/Raven.Server/Rachis/Follower.cs
  src/Raven.Server/Rachis/FollowerAmbassador.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
Labels: v4.1

#8537 RavenDB-12729 can_backup_and_restore_encrypted - test fix
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
  test/SlowTests/Server/Documents/PeriodicBackup/EncryptedBackupTest.cs
Labels: v4.2

#8542 RavenDB-12745 - Environment variables aren't being loaded when running Xunit in Debug
  src/Raven.Server/Config/RavenConfiguration.cs
Labels: v4.1

#8544 RavenDB-12745 - Environment variables aren't being loaded when running Xunit in Debug
  src/Raven.Server/Config/RavenConfiguration.cs
Labels: v4.0

#8540 RavenDB-9120: added test for FullAndIncrementalBackupsInSameFolderShouldWork.
  test/SlowTests/Issues/RavenDB-9120.cs
Labels: v4.2

#8545 RavenDB-10842 Add percentiles to traffic watch
  src/Raven.Studio/wwwroot/App/views/manage/cluster.html
  src/Raven.Studio/wwwroot/App/views/manage/trafficWatch.html
  src/Raven.Studio/wwwroot/Content/css/basic-layout.less
  src/Raven.Studio/wwwroot/Content/css/icons.less
  src/Raven.Studio/wwwroot/Content/css/styles-common.less
Labels: v4.2

#8536 RavenDB-12299: Snapshot restore should fail before actual restore, if…
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
Labels: v4.2

#8547 RavenDB-12744 Fix attachment change vector on replication
  src/Raven.Server/Documents/AttachmentsStorage.cs
  src/Raven.Server/Documents/Replication/IncomingReplicationHandler.cs
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
  test/SlowTests/Client/Attachments/AttachmentsRevisions.cs
Labels: v4.1

#8556 RavenDB-12725 Check sum issue
  src/Voron/Constants.cs
  src/Voron/Exceptions/InvalidJournalException.cs
  src/Voron/Exceptions/VoronUnrecoverableErrorException.cs
  src/Voron/Impl/Backup/FullBackup.cs
  src/Voron/Impl/Backup/IncrementalBackup.cs
  src/Voron/Impl/FileHeaders/HeaderAccessor.cs
  src/Voron/Impl/Journal/JournalInfo.cs
  src/Voron/Impl/Journal/JournalReader.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/Schema/IVoronSchemaUpdate.cs
  src/Voron/Schema/Updates/From22.cs
  src/Voron/Schema/VoronSchemaUpdater.cs
  src/Voron/StorageEnvironmentOptions.cs
  test/FastTests/Voron/ValidHeaders.cs
  test/SlowTests/Voron/Issues/RavenDB_7099.cs
  test/SlowTests/Voron/RavenDB_12725.cs
  test/SlowTests/Voron/RavenDB_12725_2.cs
  test/SlowTests/Voron/RavenDB_12725_3.cs
  test/SlowTests/Voron/RavenDB_12725_4.cs
Labels: v4.1

#8555 RavenDB-12754: Prevent resize of compression pager when not needed
  src/Voron/Impl/Journal/WriteAheadJournal.cs
Labels: v4.1

#8557 RavenDB-12744 A resolved document must preserve the original change v…
  src/Raven.Server/Documents/AttachmentsStorage.cs
  src/Raven.Server/Documents/CountersStorage.cs
  src/Raven.Server/Documents/DocumentFlags.cs
  src/Raven.Server/Documents/DocumentPutAction.cs
  src/Raven.Server/Documents/Replication/ConflictManager.cs
  src/Raven.Server/Documents/Replication/ResolveConflictOnReplicationConfigurationChange.cs
  test/SlowTests/Server/Replication/ReplicationAutomaticConflictResolution.cs
Labels: v4.1

#8553 4.1 to 4.2 merge
  src/Raven.Client/Documents/Changes/DatabaseChanges.cs
  src/Raven.Client/Http/ClusterRequestExecutor.cs
  src/Raven.Client/Http/RequestExecutor.cs
  src/Raven.Client/ServerWide/Commands/GetClusterTopologyCommand.cs
  src/Raven.Client/ServerWide/Commands/GetDatabaseTopologyCommand.cs
  src/Raven.Server/Config/RavenConfiguration.cs
  src/Raven.Server/Documents/AttachmentsStorage.cs
  src/Raven.Server/Documents/ConflictsStorage.cs
  src/Raven.Server/Documents/CountersStorage.cs
  src/Raven.Server/Documents/DocumentPutAction.cs
  src/Raven.Server/Documents/Handlers/Admin/RachisAdminHandler.cs
  src/Raven.Server/Documents/Replication/IncomingReplicationHandler.cs
  src/Raven.Server/Rachis/CandidateAmbassador.cs
  src/Raven.Server/Rachis/Elector.cs
  src/Raven.Server/Rachis/Follower.cs
  src/Raven.Server/Rachis/FollowerAmbassador.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/ServerWide/SecretProtection.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
  src/Raven.Server/Utils/CertificateUtils.cs
  src/Raven.Server/Web/Authentication/AdminCertificatesHandler.cs
  src/Raven.Server/Web/RequestHandler.cs
  src/Sparrow/Json/LazyCompressedStringValue.cs
  test/FastTests/Server/Documents/Indexing/Lucene/LazyStringValueReaderTests.cs
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
  test/SlowTests/Client/Attachments/AttachmentsRevisions.cs
  test/SlowTests/Client/Counters/CountersCluster.cs
Labels: v4.2

#8559 4.1 to 4.2 merge
  src/Raven.Server/Documents/AttachmentsStorage.cs
  src/Raven.Server/Documents/CountersStorage.cs
  src/Raven.Server/Documents/DocumentFlags.cs
  src/Raven.Server/Documents/DocumentPutAction.cs
  src/Raven.Server/Documents/Replication/ConflictManager.cs
  src/Raven.Server/Documents/Replication/ResolveConflictOnReplicationConfigurationChange.cs
  src/Voron/Constants.cs
  src/Voron/Exceptions/InvalidJournalException.cs
  src/Voron/Exceptions/VoronUnrecoverableErrorException.cs
  src/Voron/Impl/Backup/FullBackup.cs
  src/Voron/Impl/Backup/IncrementalBackup.cs
  src/Voron/Impl/FileHeaders/HeaderAccessor.cs
  src/Voron/Impl/Journal/JournalInfo.cs
  src/Voron/Impl/Journal/JournalReader.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/Schema/IVoronSchemaUpdate.cs
  src/Voron/Schema/Updates/From22.cs
  src/Voron/Schema/VoronSchemaUpdater.cs
  src/Voron/StorageEnvironmentOptions.cs
  test/FastTests/Voron/ValidHeaders.cs
  test/SlowTests/Server/Replication/ReplicationAutomaticConflictResolution.cs
  test/SlowTests/Voron/Issues/RavenDB_7099.cs
  test/SlowTests/Voron/RavenDB_12725.cs
  test/SlowTests/Voron/RavenDB_12725_2.cs
  test/SlowTests/Voron/RavenDB_12725_3.cs
  test/SlowTests/Voron/RavenDB_12725_4.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v4.2

#8554 RavenDB-12540 Slow tests Server.Replication.ReplicationBasicTestsSlow…
  src/Raven.Server/Documents/Replication/OutgoingReplicationHandler.cs
  test/SlowTests/Server/Replication/ReplicationBasicTestsSlow.cs
Labels: v4.0

#8568 RavenDB-12750 Cannot save edited backup task
  src/Raven.Studio/typescript/viewmodels/database/tasks/editPeriodicBackupTask.ts
Labels: v4.2

#8565 RavenDB-12743 SNMP entry for total number of indexing errors in database
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.2.X/1/DatabaseIndexingErrors.cs
  src/Raven.Server/Monitoring/Snmp/SnmpDatabase.cs
  src/Raven.Server/Monitoring/Snmp/SnmpOids.cs
Labels: v4.1

#8566 RavenDB-12458 Graph queries syntax highlight inside with clause
  src/Raven.Studio/aceBuild/addons/lib/ace/mode/rql_highlight_rules.js
  src/Raven.Studio/wwwroot/Content/ace/mode-rql.js
Labels: v4.2

#8570 RavenDB-12035 Setup wizard fails in macOS Mojave 10.14
  src/Raven.Server/Commercial/SetupParameters.cs
  src/Raven.Server/Web/System/SetupHandler.cs
  src/Raven.Studio/typescript/viewmodels/wizard/welcome.ts
  src/Raven.Studio/wwwroot/App/views/wizard/welcome.html
Labels: v4.1

#8572 4.1 to 4.2 merge
  src/Raven.Server/Commercial/SetupParameters.cs
  src/Raven.Server/Documents/DocumentPutAction.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.2.X/1/DatabaseIndexingErrors.cs
  src/Raven.Server/Monitoring/Snmp/SnmpDatabase.cs
  src/Raven.Server/Monitoring/Snmp/SnmpOids.cs
  src/Raven.Server/Web/System/SetupHandler.cs
  src/Raven.Studio/typescript/viewmodels/database/query/query.ts
  src/Raven.Studio/typescript/viewmodels/wizard/welcome.ts
  src/Raven.Studio/wwwroot/App/views/wizard/welcome.html
Labels: v4.2

#8573 RavenDB-12722 making recovery journal apply failure less scary and re…
  tools/Voron.Recovery/Recovery.cs
Labels: v4.1

#8575 RavenDB-12665 we need to take into account escape positions size when allocation a buffer
  src/Raven.Server/Documents/DocumentIdWorker.cs
Labels: v4.2

#8578 RavenDB-12725 Checksum issue (port to 4.0)
  src/Voron/Constants.cs
  src/Voron/Exceptions/InvalidJournalException.cs
  src/Voron/Exceptions/VoronUnrecoverableErrorException.cs
  src/Voron/GlobalFlushingBehavior.cs
  src/Voron/Impl/Backup/FullBackup.cs
  src/Voron/Impl/Backup/IncrementalBackup.cs
  src/Voron/Impl/FileHeaders/HeaderAccessor.cs
  src/Voron/Impl/Journal/JournalInfo.cs
  src/Voron/Impl/Journal/JournalReader.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/Schema/IVoronSchemaUpdate.cs
  src/Voron/Schema/Updates/From22.cs
  src/Voron/Schema/VoronSchemaUpdater.cs
  src/Voron/StorageEnvironmentOptions.cs
  test/FastTests/Voron/ValidHeaders.cs
  test/SlowTests/SchemaUpgrade/Issues/DocumentsVersion/schema_9/Journals/0000000000000000000.journal
  test/SlowTests/SchemaUpgrade/Issues/DocumentsVersion/schema_9/Journals/0000000000000000001.journal
  test/SlowTests/SchemaUpgrade/Issues/DocumentsVersion/schema_9/Raven.voron
  test/SlowTests/SchemaUpgrade/Issues/DocumentsVersion/schema_9/headers.one
  test/SlowTests/SchemaUpgrade/Issues/DocumentsVersion/schema_9/headers.two
  test/SlowTests/SlowTests.csproj
  test/SlowTests/Voron/Issues/RavenDB_7099.cs
  test/SlowTests/Voron/RavenDB_12725.cs
  test/SlowTests/Voron/RavenDB_12725_2.cs
  test/SlowTests/Voron/RavenDB_12725_3.cs
  test/SlowTests/Voron/RavenDB_12725_4.cs
Labels: v4.0

#8579 RavenDB-12545 after PR merge
  src/Raven.Studio/typescript/viewmodels/database/query/query.ts
Labels: v4.2

#8576 RavenDB-12725 We need to use the value itself, not the constant, bec…
  src/Voron/Schema/Updates/From22.cs
Labels: v4.1

#8582 RavenDB-12724 will throw on license activation errors in tests and no…
  src/Raven.Client/Exceptions/Commercial/LicenseActivationException.cs
  src/Raven.Server/Commercial/LicenseManager.cs
  src/Raven.Server/RavenServer.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  test/Tests.Infrastructure/RachisConsensusTestBase.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v4.0

#8590 RavenDB-12758 Apply database configuration for replication tests
  test/Tests.Infrastructure/TestBase.cs
Labels: v4.0

#8593 RavenDB-12590 Failed to execute cluster transactions due to an argume…
  src/Raven.Server/Documents/Handlers/BatchHandler.cs
Labels: v4.1

#8596 RavenDB-12753 Check for uniqueness of connection string name
  src/Raven.Studio/typescript/models/database/settings/connectionStringModel.ts
  src/Raven.Studio/typescript/models/database/settings/connectionStringRavenEtlModel.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editExternalReplicationTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editPullReplicationSinkTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editRavenEtlTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editSqlEtlTask.ts
Labels: v4.2

#8604 RavenDB-12453 A query in the studio fails silently if the param eval …
  src/Raven.Studio/typescript/viewmodels/database/query/query.ts
Labels: v4.1

#8601 RavenDB-8351 One node, voting in progress when passive
  src/Raven.Server/NotificationCenter/Notifications/Server/ClusterTopologyChanged.cs
  src/Raven.Studio/typescript/common/shell/clusterTopologyManager.ts
  src/Raven.Studio/typescript/models/database/cluster/clusterGraph.ts
  src/Raven.Studio/typescript/models/database/cluster/clusterNode.ts
  src/Raven.Studio/typescript/models/database/cluster/clusterTopology.ts
  src/Raven.Studio/typescript/viewmodels/manage/cluster.ts
Labels: v4.0

#8602 RavenDB-8351 One node, voting in progress when passive
  src/Raven.Server/NotificationCenter/Notifications/Server/ClusterTopologyChanged.cs
  src/Raven.Studio/typescript/common/shell/clusterTopologyManager.ts
  src/Raven.Studio/typescript/models/database/cluster/clusterGraph.ts
  src/Raven.Studio/typescript/models/database/cluster/clusterNode.ts
  src/Raven.Studio/typescript/models/database/cluster/clusterTopology.ts
  src/Raven.Studio/typescript/viewmodels/manage/cluster.ts
Labels: v4.1

#8606 RavenDB-10554 - fix typo in traffic watch
  src/Raven.Studio/typescript/viewmodels/manage/trafficWatch.ts
Labels: v4.1

#8607 RavenDB-12774 handle topologychanged message in changes api
  src/Raven.Studio/typescript/common/changesApi.ts
Labels: v4.1

#8608 RavenDB-12726 update rainbow in menu
  src/Raven.Studio/typescript/common/shell/menu/items/manageServer.ts
  src/Raven.Studio/typescript/common/shell/menu/items/stats.ts
  src/Raven.Studio/wwwroot/Content/css/icons.less
Labels: v4.2

#8613 RavenDB-12756 add Delete hub/sink tests
  src/Raven.Server/ServerWide/Commands/DeleteOngoingTaskCommand.cs
  test/SlowTests/Server/Replication/PullReplicationTests.cs
Labels: v4.2

#8617 RavenDB-12790 Lazy query should throw IndexDoesNotExistException if i…
  src/Raven.Client/Documents/Session/Operations/Lazy/LazyQueryOperation.cs
  test/SlowTests/Issues/RavenDB_12790.cs
Labels: v4.0

#8616 RavenDB-12790 Lazy query should throw IndexDoesNotExistException if i…
  src/Raven.Client/Documents/Session/Operations/Lazy/LazyQueryOperation.cs
  test/SlowTests/Issues/RavenDB_12790.cs
Labels: v4.1

#8618 RavenDB-12746 Let's make sure that a reason of marking an index as er…
  src/Raven.Server/Documents/Indexes/Index.cs
Labels: v4.1

#8619 RavenDB-12764 fix failing test RevertResolvedConflictByRemoteToOriginal
  test/FastTests/Utils/RevisionsHelper.cs
  test/SlowTests/Server/Documents/Revisions/RevertRevisionsTests.cs
Labels: v4.2
