Repository ravendb/ravendb, pull requests merged in 2019-11, with the labels that each got.

#9847 RavenDB-14217 Projection uses wrong alias for result of function
  src/Raven.Server/Documents/Queries/Results/QueryResultRetrieverBase.cs
  test/SlowTests/Issues/RavenDB-14217.cs
Labels: v4.2

#9848 RavenDB-14221 Facet intersection algorithm calculation is incorrect
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/IndexFacetedReadOperation.cs
Labels: v4.2

#9843 RavenDB-14201: Add the ability to Export Storage from a backup
  Raven.StorageExporter/Raven.StorageExporter.csproj
  Raven.StorageExporter/StorageExporter.cs
Labels: v3.5

#9852 RavenDB-14220 - reduce the memory allocation during execution of OutputReduceToCollectionCommand
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/OutputReduceIndexWriteOperation.cs
Labels: v4.2

#9856 4.2 to 5.0 merge
  src/Raven.Client/Util/JavascriptConversionExtensions.cs
  src/Raven.Server/Config/Categories/MemoryConfiguration.cs
  src/Raven.Server/Config/Categories/TransactionMergerConfiguration.cs
  src/Raven.Server/Dashboard/MachineResourcesNotificationSender.cs
  src/Raven.Server/Documents/DatabaseMetricCacher.cs
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/Handlers/Admin/RachisAdminHandler.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/IndexFacetedReadOperation.cs
  src/Raven.Server/Documents/Queries/Results/QueryResultRetrieverBase.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.2.X/2/DatabaseStorageDiskRemainingSpace.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.10/ServerStorageDiskRemainingSpace.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.10/ServerStorageDiskRemainingSpacePercentage.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.5/MachineCpu.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.5/ProcessCpu.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.6/ServerTotalMemory.cs
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
  src/Raven.Server/NotificationCenter/Handlers/ServerDashboardHandler.cs
  src/Raven.Server/Rachis/FollowerAmbassador.cs
  src/Raven.Server/Rachis/Leader.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/Rachis/RemoteConnection.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Server/RavenServer.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/Commands/DeleteDatabaseCommand.cs
  src/Raven.Server/ServerWide/Commands/UpdateDatabaseCommand.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterMaintenanceSupervisor.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterObserver.cs
  src/Raven.Server/ServerWide/ServerMetricCacher.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Utils/Cli/WelcomeMessage.cs
  src/Raven.Server/Utils/ExceptionAggregator.cs
  src/Raven.Server/Utils/MetricCacher.cs
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
  src/Raven.Studio/typescript/models/database/index/index.ts
  src/Sparrow.Server/LowMemory/MemoryInformation.cs
  src/Sparrow.Server/Utils/DiskSpaceChecker.cs
  src/Voron/Impl/Paging/Windows32BitsMemoryMapPager.cs
  src/Voron/Impl/Scratch/ScratchBufferPool.cs
  src/Voron/Platform/Win32/Win32NativeFileMethods.cs
  src/Voron/Platform/Win32/WindowsMemoryMapPager.cs
  test/FastTests/Server/Basic/MaxSecondsForTaskToWaitForDatabaseToLoad.cs
  test/RachisTests/AddNodeToClusterTests.cs
  test/SlowTests/Client/Attachments/AttachmentsStreamTests.cs
  test/SlowTests/Issues/EncryptedDatabaseGroup.cs
  test/SlowTests/Issues/RavenDB-14200.cs
  test/SlowTests/Issues/RavenDB-14217.cs
  test/SlowTests/Issues/RavenDB_7589.cs
  test/StressTests/Client/Attachments/AttachmentsStreamStress.cs
  test/Tests.Infrastructure/Operations/GetClusterDebugInfoPackageOperation.cs
  test/Tests.Infrastructure/TestBase.cs
  test/Tests.Infrastructure/TestExtensions.cs
  test/Tests.Infrastructure/Utils/DebugPackageHandler.cs
  test/Tests.Infrastructure/Utils/TestOutcomeAnalyzer.cs
Labels: v5.0

#9858 RavenDB-14233 Get rid of typings registry
  src/Raven.Studio/typings.json
Labels: v4.1

#9857 RavenDB-14233 Get rid of typings registry
  src/Raven.Studio/typings.json
Labels: v4.2

#9849 RavenDB-14220 - Take into account the output collection for a map-reduce index budget
  src/Raven.Server/Documents/Indexes/Errors/FaultyInMemoryIndex.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/MapIndexBase.cs
  src/Raven.Server/Documents/Indexes/MapReduce/Auto/AutoMapReduceIndex.cs
  src/Raven.Server/Documents/Indexes/MapReduce/MapReduceIndexBase.cs
  src/Raven.Server/Documents/Indexes/MapReduce/Static/MapReduceIndex.cs
  test/FastTests/Server/Documents/Indexing/BasicAnalyzers.cs
Labels: v4.2

#9839 RavenDB-14093: add additional information to describe smaps reader error
  src/Sparrow.Server/Platform/Posix/SmapsReader.cs
Labels: v4.2

#9863 RDBCL-1007 We must not rely on TryAutorize result but the actual Auth…
  src/Raven.Server/Routing/RequestRouter.cs
Labels: v4.2

#9868 RavenDB-14220 - PR comments
  src/Raven.Server/Documents/Indexes/Errors/FaultyInMemoryIndex.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/MapIndexBase.cs
  src/Raven.Server/Documents/Indexes/MapReduce/Auto/AutoMapReduceIndex.cs
  src/Raven.Server/Documents/Indexes/MapReduce/MapReduceIndexBase.cs
  src/Raven.Server/Documents/Indexes/MapReduce/Static/MapReduceIndex.cs
  test/FastTests/Server/Documents/Indexing/BasicAnalyzers.cs
Labels: v4.2

#9866 RavenDB-14244 - Skip writing the last index etag after server restart
  src/Raven.Server/Documents/Indexes/Workers/MapDocuments.cs
Labels: v4.2

#9872 RavenDB-14257 & RavenDB-14186 Cluster observer fixes
  src/Raven.Server/ServerWide/Maintenance/ClusterObserver.cs
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
  test/RachisTests/SubscriptionFailoverWIthWaitingChains.cs
Labels: v4.2

#9873 RavenDB-14258 fixed a race condition between loading a database (and checking if it is deleted) and disposing a server store
  src/Raven.Server/Documents/DatabasesLandlord.cs
Labels: v4.2

#9876 4.2 to 5.0 merge
  libs/librvnpal/librvnpal.arm.32.so
  libs/librvnpal/librvnpal.arm.64.so
  libs/librvnpal/librvnpal.linux.x64.so
  libs/librvnpal/librvnpal.mac.x64.dylib
  libs/librvnpal/librvnpal.win.x64.dll
  libs/librvnpal/librvnpal.win.x86.dll
  libs/librvnpal/librvnpal.win7.x64.dll
  libs/librvnpal/librvnpal.win7.x86.dll
  src/Raven.Pal/pal.ver
  src/Raven.Pal/src/rvngetpalver.c
  src/Raven.Pal/src/win/fileutils.c
  src/Raven.Pal/src/win/getsysteminformation.c
  src/Raven.Pal/src/win/journal.c
  src/Raven.Pal/src/win/writefileheader.c
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/Indexes/Errors/FaultyInMemoryIndex.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/MapIndexBase.cs
  src/Raven.Server/Documents/Indexes/MapReduce/Auto/AutoMapReduceIndex.cs
  src/Raven.Server/Documents/Indexes/MapReduce/MapReduceIndexBase.cs
  src/Raven.Server/Documents/Indexes/MapReduce/Static/MapReduceIndex.cs
  src/Raven.Server/Documents/Indexes/Workers/MapDocuments.cs
  src/Raven.Server/Routing/RequestRouter.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterObserver.cs
  src/Sparrow.Server/Platform/Pal.cs
  src/Voron/Platform/Win32/Win32NativeFileMethods.cs
  test/FastTests/Server/Documents/Indexing/BasicAnalyzers.cs
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
  test/RachisTests/SubscriptionFailoverWIthWaitingChains.cs
Labels: v5.0

#9877 RavenDB-14263: timer should not restart when PerformHealthCheck fails
  src/Raven.Client/Http/RequestExecutor.cs
Labels: v4.2

#9879 RavenDB-8644 fix docker build scripts - commenting out a line with es…
  docker/build-nanoserver.ps1
  docker/build-ubuntu.ps1
Labels: v5.0

#9886 RavenDB-14242 fix failing tests
  src/Raven.Server/Documents/TimeSeries/TimeSeriesStorage.cs
  src/Voron/Data/Tables/Table.cs
Labels: v5.0

#9887 RavenDB-14098: Add more assets to failing test
  test/SlowTests/Server/Documents/PeriodicBackup/RavenDB-11139.cs
Labels: v4.2

#9891 RavenDB-14207 Don't kicked out node from the cluster if the we have e…
  src/Raven.Server/Rachis/RachisConsensus.cs
  test/RachisTests/DatabaseCluster/RemoveNodeFromCluster.cs
Labels: v4.2

#9889 RavenDB-14121: NoDisposalNeeded should inherit from LinuxRaceConditio…
  test/SlowTests/Client/BulkInserts.cs
  test/SlowTests/Issues/RavenDB_6285_2.cs
  test/SlowTests/Issues/SlowBasicAutoMapReduceIndexing.cs
  test/SlowTests/Server/Documents/Indexing/CollisionsOfReduceKeyHashes_StressTests.cs
  test/Tests.Infrastructure/NoDisposalNeeded.cs
  test/Tests.Infrastructure/NoDisposalNoOutputNeeded.cs
Labels: v4.2

#9895 RavenDB-14225 Fixing build
  src/Raven.Client/ServerWide/Operations/ConfigureRevisionsForConflictsOperation.cs
Labels: v4.2

#9896 RavenDB-14279 / RavenDB-14121 Tests runnig other tests should inhevit…
  test/StressTests/Client/Attachments/AttachmentsSessionStress.cs
  test/StressTests/Core/Expiration/ExpirationStressTest.cs
  test/StressTests/Issues/RavenDB-5763.cs
  test/StressTests/Server/Replication/ExternalReplicationStressTests_NoDispose.cs
  test/StressTests/Utils/ChunkedMmapStreamTests.cs
  test/StressTests/Voron/Bugs/DataInconsistencyReproStressTests.cs
  test/StressTests/Voron/LargeFixedSizeTreesStressCases.cs
  test/StressTests/Voron/Trees/FreeSpaceStressTests.cs
Labels: v4.2

#9897 RavenDB-14121: fix ITestOutputHelper in nightly build tests
  test/StressTests/Client/Attachments/AttachmentsHugeFiles.cs
  test/StressTests/Client/Attachments/AttachmentsSessionAsyncStress.cs
  test/StressTests/Server/Documents/PeriodicBackup/Retention.cs
Labels: v4.2

#9901 RavenDB-14287 Increasing a timeout of Databases.ConcurrentLoadTimeou…
  src/Raven.Server/Config/Categories/DatabaseConfiguration.cs
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/NotificationCenter/Notifications/AlertType.cs
Labels: v4.2

#9905 4.1 to 4.2 merge
  src/Raven.Server/Documents/Indexes/MapReduce/ReduceMapResultsBase.cs
  src/Raven.Server/Documents/Replication/IncomingReplicationHandler.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/RavenServer.cs
  src/Voron/Data/BTrees/Tree.Compressed.cs
  src/Voron/Data/Compression/CompressionResult.cs
  src/Voron/Data/Compression/LeafPageCompressor.cs
  src/Voron/Debugging/DebugStuff.cs
  test/RachisTests/DatabaseCluster/ReplicationTests.cs
  test/SlowTests/Voron/LeafsCompression/RDBS_52.cs
Labels: v4.2

#9908 RavenDB-14290 - support load, store and delete in OnBeforeStore and OnBeforeDelete
  src/Raven.Client/Documents/Session/AdvancedSessionExtensionBase.cs
  src/Raven.Client/Documents/Session/DocumentSessionAttachments.cs
  src/Raven.Client/Documents/Session/DocumentSessionAttachmentsAsync.cs
  src/Raven.Client/Documents/Session/DocumentSessionAttachmentsBase.cs
  src/Raven.Client/Documents/Session/DocumentSessionRevisions.cs
  src/Raven.Client/Documents/Session/InMemoryDocumentSessionOperations.cs
  test/FastTests/Client/Events.cs
Labels: v4.2

#9909 RavenDB-14276 - initialize the MetadataAsDictionary properly
  src/Raven.Client/Json/MetadataAsDictionary.cs
  test/SlowTests/Issues/RavenDB-14276.cs
Labels: v4.2

#9911 RavenDB-14298 Avoid throwing ObjectDisposed during audit logging if the socket was closed
  src/Raven.Server/RavenServer.cs
Labels: v4.2

#9912 RavenDB-14299 Update WRK scripts
  bench/Scripts/batch-writes.lua
  bench/Scripts/raven-wrk-test.sh
  bench/Scripts/reads.lua
  bench/Scripts/writes.lua
Labels: v4.2

#9918 RavenDB-14293 : Timeseries Removal granularity
  src/Raven.Server/Documents/TimeSeries/TimeSeriesStorage.cs
  test/SlowTests/Client/TimeSeries/RavenDB-14293.cs
Labels: v5.0
