Repository ravendb/ravendb, pull requests merged in 2019-06, with the labels that each got.

#9318 Fix for RavenDB-13499
  src/Raven.Server/Documents/Queries/Graph/SingleEdgeMatcher.cs
  test/FastTests/FastTests.csproj
  test/FastTests/Issues/RavenDB-13499.cs
  test/FastTests/Issues/RavenDB-13499.ravendbdump
Labels: v4.2

#9338 RavenDB-13556 CreateSampleDataCommand needs to implement IRaftCommand
  test/Tests.Infrastructure/CreateSampleDataOperation.cs
Labels: v4.2

#9339 RavenDB-13611 Error details have been corrected to be more understood
  test/SlowTests/SparrowTests/LoggingSourceTests.cs
Labels: v4.2

#9340 RavenDB-13640 If we fail during BeginAsyncCommitAndStartNewTransactio…
  src/Voron/Impl/LowLevelTransaction.cs
  test/SlowTests/Voron/Issues/RavenDB_13640.cs
Labels: v4.2

#9341 4.1 to 4.2 merge
  src/Voron/Impl/LowLevelTransaction.cs
  test/SlowTests/Voron/Issues/RavenDB_13640.cs
Labels: v4.2

#9343 RavenDB-13611 Tests of logging corrected to add all log file name in a case of failure
  test/SlowTests/SparrowTests/LoggingSourceTests.cs
Labels: v4.2

#9345 RavenDB-13656 : Projecting a property called "Limit" fails with parser exception
  src/Raven.Client/Documents/Linq/RavenQueryProviderProcessor.cs
  test/SlowTests/Issues/RavenDB-13656.cs
Labels: v4.1

#9314 RavenDB-13617 At GetLower function, missing cast added in optimization
  src/Raven.Server/Documents/DocumentIdWorker.cs
  test/FastTests/Server/Documents/DocumentIdWorkerTests.cs
Labels: v4.1

#9349 4.1 to 4.2 merge
  src/Raven.Client/Documents/Linq/RavenQueryProviderProcessor.cs
  src/Raven.Client/Http/ClusterTopologyResponse.cs
  src/Raven.Server/Commercial/SetupManager.cs
  src/Raven.Server/Documents/DocumentIdWorker.cs
  src/Raven.Server/NotificationCenter/Handlers/DatabaseNotificationCenterHandler.cs
  src/Raven.Server/NotificationCenter/Handlers/ServerNotificationCenterHandler.cs
  src/Raven.Server/NotificationCenter/NotificationCenterWebsocketWriter.cs
  src/Raven.Server/NotificationCenter/Notifications/Server/ClusterTopologyChanged.cs
  src/Raven.Server/Rachis/Candidate.cs
  src/Raven.Server/Rachis/CandidateAmbassador.cs
  src/Raven.Server/Rachis/FollowerAmbassador.cs
  src/Raven.Server/Rachis/Leader.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/RavenServer.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  test/FastTests/Server/Documents/DocumentIdWorkerTests.cs
  test/RachisTests/DatabaseCluster/RemoveNodeFromCluster.cs
  test/SlowTests/Issues/RavenDB-13656.cs
Labels: v4.2

#9352 RavenDB-13662 fix RachisTests.AddNodeToClusterTests.FailOnAddingNonPa…
  src/Raven.Server/Rachis/FollowerAmbassador.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
Labels: v4.1

#9353 RavenDB-13664 Race in `PutAsync` might throw `TimeoutException`
  src/Raven.Server/Rachis/Leader.cs
Labels: v4.1

#9342 RavenDB-13311 Cluster observer should be more informative for the rea…
  src/Raven.Server/ServerWide/Maintenance/ClusterObserver.cs
Labels: v4.1

#9355 4.1 to 4.2 merge
  src/Raven.Client/Documents/Operations/PatchResult.cs
  src/Raven.Server/Documents/Document.cs
  src/Raven.Server/Documents/ExecuteRateLimitedOperations.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/LuceneIndexWriter.cs
  src/Raven.Server/Documents/Patch/PatchDocumentCommand.cs
  src/Raven.Server/Documents/Queries/AbstractQueryRunner.cs
  src/Raven.Server/Rachis/FollowerAmbassador.cs
  src/Raven.Server/Rachis/Leader.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterObserver.cs
  test/SlowTests/Cluster/ClusterTransactionTests.cs
Labels: v4.2

#9356 RavenDB-13667 Failed to include on subscriptions test
  src/Raven.Server/Documents/Handlers/SubscriptionsHandler.cs
Labels: v4.2

#9360 RavenDB-13676 Export certificate should work for Operators
  src/Raven.Server/Web/Authentication/AdminCertificatesHandler.cs
Labels: v4.2

#9364 RavenDB-13679 UI for Server-wide Backup - disabled + marked server wi…
  src/Raven.Studio/typescript/models/database/tasks/ongoingTaskBackupListModel.ts
  src/Raven.Studio/wwwroot/App/views/database/tasks/editPeriodicBackupTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/ongoingTasks.html
Labels: v4.2

#9359 Raven db 13503 Integer addition in projection while using "store files" with indexes
  src/Raven.Server/Documents/Patch/BlittableObjectInstance.cs
  test/SlowTests/Issues/RavenDB-13503.cs
Labels: v4.1

#9369 4.1 to 4.2 merge
  src/Raven.Server/Documents/Patch/BlittableObjectInstance.cs
  src/Raven.Server/Documents/Patch/PatchDocumentCommand.cs
  src/Raven.Server/Https/AuthenticatingAdapter.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/Rachis/TimeoutEvent.cs
  src/Raven.Server/RavenServer.cs
  src/Sparrow.Server/ByteString.cs
  src/Sparrow/Json/BlittableJsonReaderObject.cs
  test/RachisTests/BasicTests.cs
  test/SlowTests/Issues/RavenDB-13503.cs
  test/SlowTests/Server/Documents/Patching/PatchByIndexTests.cs
Labels: v4.2

#9370 RavenDB-12800 Adding option to stop ETL batch if size limit is exceed…
  src/Raven.Server/Config/Categories/EtlConfiguration.cs
  src/Raven.Server/Documents/ETL/EtlProcess.cs
  src/Raven.Server/Documents/ETL/EtlTransformer.cs
  src/Raven.Server/Documents/ETL/Providers/Raven/RavenEtlDocumentTransformer.cs
  src/Raven.Server/Documents/ETL/Providers/Raven/RavenEtlScriptRun.cs
  src/Raven.Server/Documents/ETL/Providers/SQL/SqlDocumentTransformer.cs
  src/Raven.Server/Documents/ETL/Stats/EtlPerformanceStats.cs
  src/Raven.Server/Documents/ETL/Stats/EtlRunStats.cs
  src/Raven.Server/Documents/ETL/Stats/EtlStatsAggregator.cs
  src/Raven.Server/Documents/ETL/Stats/EtlStatsScope.cs
  test/SlowTests/Server/Documents/ETL/Raven/RavenDB_12800.cs
  test/SlowTests/Server/Documents/ETL/SQL/SqlEtlTests.cs
Labels: v4.2

#9371 RavenDB-7070 updated packages
  bench/Regression.Benchmark/Regression.Benchmark.csproj
  src/Raven.Server/Raven.Server.csproj
  test/BenchmarkTests/BenchmarkTests.csproj
  test/EmbeddedTests/EmbeddedTests.csproj
  test/FastTests/FastTests.csproj
  test/InterversionTests/InterversionTests.csproj
  test/RachisTests/RachisTests.csproj
  test/SlowTests/SlowTests.csproj
  test/StressTests/StressTests.csproj
Labels: v4.1

#9372 RavenDB-12800 Better configuration option description. Exposing curre…
  src/Raven.Server/Config/Categories/EtlConfiguration.cs
  src/Raven.Studio/typescript/viewmodels/database/status/ongoingTasksStats.ts
Labels: v4.2

#9375 RavenDB-13696 Patch should preserve the order of properties
  src/Raven.Server/Documents/Patch/JsBlittableBridge.cs
Labels: v4.2

#9376 RavenDB-13696 added test
  test/SlowTests/Issues/RavenDB_13696.cs
Labels: v4.2

#9380 RavenDB-13697 DatabaseDoesNotExistException on first operation after …
  src/Raven.Client/Http/RequestExecutor.cs
  test/SlowTests/Issues/RavenDB-13697.cs
Labels: v4.2

#9379 RavenDB-10520 IDocumentQuery and IRawDocumentQuery should not inherit from IEnumerable
  src/Raven.Client/Documents/DocumentQueryExtensions.cs
  src/Raven.Client/Documents/Linq/RavenQueryInspector.cs
  src/Raven.Client/Documents/Session/DocumentQuery.cs
  src/Raven.Client/Documents/Session/IDocumentQuery.cs
  test/FastTests/Graph/ClientGraphQueries.cs
  test/FastTests/Issues/RavenDB_10503.cs
  test/FastTests/Issues/RavenDB_10520.cs
  test/SlowTests/MailingList/StreamingTests.cs
  test/SlowTests/MailingList/chad.cs
  test/SlowTests/Server/Documents/Indexing/Auto/RavenDB_8761.cs
  test/SlowTests/Server/Documents/Indexing/Auto/RavenDB_9292.cs
  test/SlowTests/Tests/Bugs/Zhang/UseMaxForDateTimeTypeInReduce.cs
  test/SlowTests/Tests/Bugs/Zhang/UseMaxForLongTypeInReduce.cs
Labels: v5.0

#9382 RDBS-11 ExternalAlignedSize must be calculated at runtime because it is different between x86 and x64
  src/Sparrow/ByteString.cs
Labels: v4.1

#9381 RavenDB-13703 Allow disposing of EmbeddableDocumentStore even if it was not initialized
  Raven.Database/Client/EmbeddableDocumentStore.cs
Labels: v3.5

#9385 4.1 to 4.2 merge
  src/Sparrow.Server/ByteString.cs
Labels: v4.2

#9386 Support for StreamQueryStatistics in async client API
  src/Raven.Client/Documents/Session/AsyncDocumentSession.Stream.cs
  src/Raven.Client/Documents/Session/IAsyncAdvancedSessionOperations.Stream.cs
  src/Raven.Client/Documents/Session/Operations/StreamOperation.cs
  test/SlowTests/Core/Streaming/QueryStreaming.cs
Labels: v4.2

#9389 RavenDB-13688 adding test for encrypted indexing tx limit + minor ref…
  test/SlowTests/Authentication/AuthenticationEncryptionTests.cs
  test/SlowTests/Issues/RavenDB_12151.cs
  test/Tests.Infrastructure/RavenTestBase.cs
Labels: v4.2

#9391 RavenDB-13708 - Disable task toggle for server wide backups
  src/Raven.Server/ServerWide/Commands/ToggleTaskStateCommand.cs
  test/SlowTests/Server/Documents/PeriodicBackup/ServerWideBackup.cs
Labels: v4.2

#9390 RavenDB-11800 Restarting the server should preserve the cluster topology
  src/Raven.Server/Rachis/Candidate.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  test/RachisTests/AddNodeToClusterTests.cs
Labels: v4.1

#9393 4.1 to 4.2 merge
  src/Raven.Server/Rachis/Candidate.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  test/RachisTests/AddNodeToClusterTests.cs
Labels: v4.2

#9394 RavenDB-13710 - use the encryption key of the database for encrypted databases
  src/Raven.Server/ServerWide/Commands/PutServerWideBackupConfigurationCommand.cs
  test/SlowTests/Server/Documents/PeriodicBackup/ServerWideBackup.cs
Labels: v4.2

#9396 RavenDB-11800 : fix fixed port validation when building cluster via setup manager
  src/Raven.Server/Commercial/SetupManager.cs
  src/Raven.Server/ServerWide/ServerStore.cs
Labels: v4.1

#9397 4.1 to 4.2 merge
  src/Raven.Server/Commercial/SetupManager.cs
  src/Raven.Server/ServerWide/ServerStore.cs
Labels: v4.2

#9400 RavenDB-13721 Updating EULA
  LICENSE
Labels: v4.1, v4.2

#9402 RavenDB-13630: Fix NRE on hilo tombstone replication
  src/Raven.Server/Documents/Replication/ConflictManager.cs
  test/FastTests/Client/HiLo.cs
Labels: v4.2

#9399 RavenDB-13719 Recognize SMB2 shares as not valid for dir sync
  .gitignore
  libs/librvnpal/librvnpal.arm.32.so
  libs/librvnpal/librvnpal.arm.64.so
  libs/librvnpal/librvnpal.linux.x64.so
  libs/librvnpal/librvnpal.mac.x64.dylib
  libs/librvnpal/librvnpal.win.x64.dll
  libs/librvnpal/librvnpal.win.x86.dll
  libs/librvnpal/librvnpal.win7.x64.dll
  libs/librvnpal/librvnpal.win7.x86.dll
  src/Raven.Pal/pal.ver
  src/Raven.Pal/src/posix/linuxonly.c
  src/Raven.Pal/src/rvngetpalver.c
  src/Sparrow.Server/Platform/Pal.cs
Labels: v4.2

#9404 RDBCL-447 Monitoring cpu credits in a dedicated thread
  src/Raven.Server/RavenServer.cs
Labels: v4.2

#9403 RavenDB-13707 Backup task should try to stay on the original node
  src/Raven.Server/Commercial/LicenseManager.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
  src/Raven.Server/Web/System/OngoingTasksHandler.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
Labels: v4.1

#9407 RavenDB-13715 support for sorting id as a alphanumeric value
  src/Raven.Server/Documents/Queries/QueryMetadata.cs
  test/SlowTests/Issues/RavenDB_12345.cs
Labels: v4.2

#9411 RavenDB-13734: Fix NRE
  src/Raven.Server/ServerWide/Maintenance/ClusterMaintenanceSupervisor.cs
Labels: v4.2

#9419 4.1 to 4.2 merge
  src/Raven.Client/Documents/Conventions/DocumentConventions.cs
  src/Raven.Client/Documents/Operations/CompareExchange/CompareExchangeValueResultParser.cs
  src/Raven.Client/Documents/Operations/CompareExchange/GetCompareExchangeValueOperation.cs
  src/Raven.Client/Documents/Operations/CompareExchange/GetCompareExchangeValuesOperation.cs
  src/Raven.Client/Documents/Operations/CompareExchange/PutCompareExchangeValueOperation.cs
  src/Raven.Client/Documents/Session/EntityToBlittable.cs
  src/Raven.Client/Documents/Session/InMemoryDocumentSessionOperations.cs
  src/Raven.Client/Extensions/BlittableJsonTextWriterExtensions.cs
  src/Raven.Client/Json/Converters/ParametersConverter.cs
  src/Raven.Server/Documents/Handlers/Admin/AdminConfigurationHandler.cs
  src/Raven.Server/Documents/Handlers/ConfigurationHandler.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/Commands/PutClientConfigurationCommand.cs
  src/Raven.Server/ServerWide/Commands/PutValueCommand.cs
  src/Sparrow/Json/BlittableJsonReaderObject.cs
  test/SlowTests/Client/ClientConfigurationTests.cs
  test/SlowTests/Cluster/ClusterTransactionTests.cs
  test/SlowTests/Issues/RavenDB_13363.cs
  test/SlowTests/MailingList/markp.cs
Labels: v4.2

#9420 RavenDB-7070 removing warnings
  src/Raven.Client/Documents/Operations/CompareExchange/CompareExchangeValueResultParser.cs
  test/SlowTests/Issues/RavenDB-13503.cs
Labels: v4.1

#9414 RavenDB-13716 After server upgrade - version is not updated on Cluste…
  src/Raven.Studio/typescript/common/shell/clusterTopologyManager.ts
Labels: v4.1

#9424 RavenDB-13723 Fix Cluster View constantly shows Voting In Progress
  src/Raven.Server/NotificationCenter/Handlers/DatabaseNotificationCenterHandler.cs
  src/Raven.Server/NotificationCenter/Handlers/ServerNotificationCenterHandler.cs
  src/Raven.Server/NotificationCenter/Notifications/Server/ClusterTopologyChanged.cs
  src/Raven.Server/ServerWide/ServerStore.cs
Labels: v4.1

#9425 RavenDB-13359 Revisions flag isn't cleared after replication of expir…
  src/Raven.Server/Documents/DocumentPutAction.cs
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  test/SlowTests/Server/Documents/Revisions/RevisionsReplication.cs
Labels: v4.2

#9426 4.1 to 4.2 merge
  src/Raven.Client/Documents/Operations/CompareExchange/CompareExchangeValueResultParser.cs
  src/Raven.Server/NotificationCenter/Handlers/DatabaseNotificationCenterHandler.cs
  src/Raven.Server/NotificationCenter/Handlers/ServerNotificationCenterHandler.cs
  src/Raven.Server/NotificationCenter/Notifications/Server/ClusterTopologyChanged.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Studio/typescript/common/shell/clusterTopologyManager.ts
Labels: v4.2

#9427 RavenDB-13746 - add CanRenewLicense
  src/Raven.Server/Config/Categories/LicenseConfiguration.cs
  src/Raven.Server/Web/Studio/LicenseHandler.cs
Labels: v4.2

#9415 RavenDB-13739: Elaborate message
  tools/Raven.Debug/CommandLineApp.cs
Labels: v4.2

#9429 RavenDB-13738 pass the build version over the rachis hello message
  src/Raven.Server/Rachis/RachisHello.cs
  src/Raven.Server/Rachis/RemoteConnection.cs
Labels: v4.1

#9430 RavenDB-13539 MethodDynamicParametersRewriter should adjust the return type of the visited method to be dynamic
  src/Raven.Server/Documents/Indexes/Static/Roslyn/Rewriters/MethodDynamicParametersRewriter.cs
  test/FastTests/Client/Indexing/IndexExtensionFromClient.cs
Labels: v4.2

#9428 RavenDB-13744 prevent big memory streams to be held by the context ca…
  src/Sparrow/Json/JsonOperationContext.cs
Labels: v4.2

#9431 RavenDB-13749 Reverting configuration option rename introduced in htt…
  src/Raven.Server/Config/Categories/LogsConfiguration.cs
Labels: v4.2

#9410 RDBS-24: Fix available memory without shared clean calculation in con…
  src/Sparrow.Server/LowMemory/MemoryInformation.cs
Labels: v4.2

#9433 4.1 to 4.2 merge
  src/Raven.Server/Documents/Handlers/StreamCsvResultWriter.cs
  src/Raven.Server/Rachis/RachisHello.cs
  src/Raven.Server/Rachis/RemoteConnection.cs
  src/Raven.Server/Smuggler/Documents/CsvStreamSource.cs
Labels: v4.2

#9432 RavenDB-13746 Remove Replace License and Renew License when it's disa…
  src/Raven.Server/Config/Categories/LicenseConfiguration.cs
  src/Raven.Server/Web/Studio/LicenseHandler.cs
  src/Raven.Studio/typescript/commands/licensing/getLicenseConfigurationSettingsCommand.ts
  src/Raven.Studio/typescript/viewmodels/shell/about.ts
  src/Raven.Studio/wwwroot/App/views/shell/about.html
  tools/TypingsGenerator/Program.cs
Labels: v4.2

#9435 RavenDB-13738 Have a better error why 4.2 can't talk with 4.1.4
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/ServerWide/ServerVersion.cs
  src/Raven.Server/Smuggler/Documents/Processors/BuildVersion.cs
Labels: v4.2

#9436 RavenDB-13722: Fix the skipping of compare exchange values when resto…
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreBackupTask.cs
  src/Raven.Server/Smuggler/Documents/DatabaseSmuggler.cs
Labels: v4.2

#9438 RavenDB-13753 On server startup always copy the appropriate PAL and S…
  src/Sparrow.Server/Platform/Pal.cs
  src/Sparrow.Server/Sodium.cs
Labels: v4.2

#9439 RavenDB-13634 dropping named subscription should work
  src/Raven.Server/Documents/Subscriptions/SubscriptionStorage.cs
Labels: v4.2

#9441 RavenDB-13749 Reverting changed default value for Logs.RetentionTimeI…
  src/Raven.Server/Config/Categories/ConfigurationCategory.cs
  src/Raven.Server/Config/Categories/LogsConfiguration.cs
  test/SlowTests/Issues/RavenDB_13749.cs
Labels: v4.2

#9443 RavenDB-13739: Fix duplicate lines
  tools/Raven.Debug/CommandLineApp.cs
Labels: v4.2

#9450 4.2 to 5.0 merge
  src/Raven.Client/Documents/Commands/Batches/BatchCommand.cs
  src/Raven.Client/Documents/LinqExtensions.cs
  src/Raven.Client/Documents/Operations/CompareExchange/CompareExchangeValueResultParser.cs
  src/Raven.Server/Config/Categories/ConfigurationCategory.cs
  src/Raven.Server/Config/Categories/LicenseConfiguration.cs
  src/Raven.Server/Config/Categories/LogsConfiguration.cs
  src/Raven.Server/Documents/DocumentPutAction.cs
  src/Raven.Server/Documents/Handlers/StreamCsvResultWriter.cs
  src/Raven.Server/Documents/Indexes/Static/IndexCompiler.cs
  src/Raven.Server/Documents/Indexes/Static/Roslyn/Rewriters/MethodDynamicParametersRewriter.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreBackupTask.cs
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  src/Raven.Server/Documents/Subscriptions/SubscriptionStorage.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.5/CpuCreditsAlertRaised.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.5/CpuCreditsBackgroundTasksAlertRaised.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.5/CpuCreditsBase.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.5/CpuCreditsCurrentConsumption.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.5/CpuCreditsFailoverAlertRaised.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.5/CpuCreditsMax.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.5/CpuCreditsRemaining.cs
  src/Raven.Server/Monitoring/Snmp/SnmpOids.cs
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
  src/Raven.Server/NotificationCenter/Handlers/DatabaseNotificationCenterHandler.cs
  src/Raven.Server/NotificationCenter/Handlers/ServerNotificationCenterHandler.cs
  src/Raven.Server/NotificationCenter/Notifications/Server/ClusterTopologyChanged.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/Rachis/RachisHello.cs
  src/Raven.Server/Rachis/RemoteConnection.cs
  src/Raven.Server/RavenServer.cs
  src/Raven.Server/ServerWide/Commands/UpdatePullReplicationAsSinkCommand.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/ServerWide/ServerVersion.cs
  src/Raven.Server/Smuggler/Documents/CsvStreamSource.cs
  src/Raven.Server/Smuggler/Documents/DatabaseSmuggler.cs
  src/Raven.Server/Smuggler/Documents/Processors/BuildVersion.cs
  src/Raven.Server/Web/Studio/LicenseHandler.cs
  src/Raven.Studio/typescript/commands/licensing/getLicenseConfigurationSettingsCommand.ts
  src/Raven.Studio/typescript/common/shell/clusterTopologyManager.ts
  src/Raven.Studio/typescript/viewmodels/shell/about.ts
  src/Raven.Studio/wwwroot/App/views/shell/about.html
  src/Sparrow.Server/LowMemory/MemoryInformation.cs
  src/Sparrow.Server/Platform/Pal.cs
  src/Sparrow.Server/Sodium.cs
  src/Sparrow/Json/JsonOperationContext.cs
  test/FastTests/Client/Indexing/IndexExtensionFromClient.cs
  test/SlowTests/Client/Queries/FullTextSearch.cs
  test/SlowTests/Issues/RavenDB_10664.cs
  test/SlowTests/Issues/RavenDB_13636.cs
  test/SlowTests/Issues/RavenDB_13749.cs
  test/SlowTests/Server/Documents/Revisions/RevisionsReplication.cs
  test/SlowTests/Smuggler/BackupDatabaseRecordTests.cs
  tools/Raven.Debug/CommandLineApp.cs
  tools/TypingsGenerator/Program.cs
Labels: v5.0

#9449 RavenDB-7070 fixing dev build number
  src/Raven.Server/ServerWide/ServerVersion.cs
Labels: v4.2

#9448 RavenDB-13601 retry raft command if the term was changed during the p…
  src/Raven.Server/ServerWide/ServerStore.cs
Labels: v4.1

#9454 RavenDB-13767 when patching cluster transaction documents need to rem…
  src/Raven.Server/Documents/Patch/PatchDocumentCommand.cs
  src/Raven.Server/Documents/Patch/PatchFailedException.cs
Labels: v4.2
