Repository ravendb/ravendb, pull requests merged in 2019-02, with the labels that each got.

#8625 RavenDB-12423 Fixing error message - Page doesn't have ToString overl…
  src/Raven.Server/Documents/Indexes/MapReduce/ReduceMapResultsBase.cs
Labels: v4.1

#8621 RavenDB-12789 fixing 32 bit issues relating to the actual size of the…
  src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
Labels: v4.1

#8633 RavenDB-12623: Removing debug code
  src/Sparrow/Json/JsonContextPoolBase.cs
Labels: v4.2

#8634 RavenDB-12783 collecting logs for ExternalReplicationShouldWorkWithSm…
  test/StressTests/Server/Replication/ExternalReplicationStressTests.cs
  test/Tests.Infrastructure/InterversionTest/WebSocketUtil.cs
Labels: v4.0

#8641 RavenDB-12807 fixed tests
  test/SlowTests/Issues/RavenDB-12780.cs
Labels: v4.1

#8640 RavenDB-12826 added ToArrayAsync support to async queries
  src/Raven.Client/Documents/LinqExtensions.cs
  src/Raven.Client/Documents/Session/AsyncDocumentQuery.cs
  src/Raven.Client/Documents/Session/DocumentQuery.cs
  src/Raven.Client/Documents/Session/IAsyncDocumentQuery.cs
  src/Raven.Client/Documents/Session/Operations/QueryOperation.cs
Labels: v4.2

#8636 RavenDB-12823 Inconsistent documents number in the cluster when there…
  src/Raven.Server/Documents/ConflictsStorage.cs
  src/Raven.Server/Documents/DocumentPutAction.cs
  test/SlowTests/Server/Replication/ReplicationConflictsTests.cs
Labels: v4.1

#8632 RavenDB-12762 use current data dir when continuing cluster setup
  src/Raven.Server/Commercial/SetupManager.cs
Labels: v4.1

#8642 RavenDB-12826 added a test
  test/SlowTests/Issues/RavenDB_12826.cs
Labels: v4.2

#8629 RavenDB-12761 Fixing race condition in test - make sure that Index.Re…
  test/FastTests/Server/Documents/Indexing/Auto/BasicAutoMapIndexing.cs
Labels: v4.1

#8630 RavenDB-12761 Fixing race condition in test - make sure that Index.Re…
  test/FastTests/Server/Documents/Indexing/Auto/BasicAutoMapIndexing.cs
Labels: v4.0

#8644 RavenDB-12733 Fixing race condition in test. The issue was that index…
  test/SlowTests/Issues/RavenDB_7043.cs
Labels: v4.0

#8643 RavenDB-12733 Fixing race condition in test. The issue was that index…
  test/SlowTests/Issues/RavenDB_7043.cs
Labels: v4.1

#8647 4.1 to 4.2 merge
  src/Raven.Client/Documents/Operations/TransactionsRecording/ReplayTransactionsRecordingOperation.cs
  src/Raven.Client/Documents/Session/AsyncDocumentQuery.cs
  src/Raven.Client/Documents/Session/DocumentQuery.cs
  src/Raven.Client/Documents/Session/Operations/Lazy/LazyQueryOperation.cs
  src/Raven.Server/Commercial/SetupManager.cs
  src/Raven.Server/Config/Categories/EtlConfiguration.cs
  src/Raven.Server/Documents/ConflictsStorage.cs
  src/Raven.Server/Documents/DocumentPutAction.cs
  src/Raven.Server/Documents/ETL/EtlLoader.cs
  src/Raven.Server/Documents/Handlers/TransactionsRecordingHandler.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/MapReduce/ReduceMapResultsBase.cs
  src/Raven.Server/Documents/Operations/Operations.cs
  src/Raven.Server/Documents/TransactionOperationsMerger.cs
  src/Raven.Server/NotificationCenter/Handlers/ServerNotificationCenterHandler.cs
  src/Raven.Server/Rachis/FollowerAmbassador.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterObserver.cs
  src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
  src/Raven.Server/Storage/Layout/StorageLoader.cs
  src/Raven.Server/Utils/Cli/RavenCli.cs
  src/Raven.Studio/typescript/commands/database/debug/recordTransactionsCommand.ts
  src/Raven.Studio/typescript/commands/database/debug/replayTransactionsCommand.ts
  src/Raven.Studio/typescript/commands/database/debug/stopRecordingTransactionsCommand.ts
  src/Raven.Studio/typescript/commands/database/studio/importFromCsvCommand.ts
  src/Raven.Studio/typescript/common/appUrl.ts
  src/Raven.Studio/typescript/common/notifications/notificationCenter.ts
  src/Raven.Studio/typescript/common/shell/activeDatabaseTracker.ts
  src/Raven.Studio/typescript/common/shell/databasesManager.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/replayTransactionCommandsDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/transactionCommandsDetails.ts
  src/Raven.Studio/typescript/viewmodels/manage/debugAdvancedParent.ts
  src/Raven.Studio/typescript/viewmodels/manage/debugAdvancedRecordTransactionCommands.ts
  src/Raven.Studio/typescript/viewmodels/manage/debugAdvancedReplayTransactionCommands.ts
  src/Raven.Studio/wwwroot/App/views/manage/debugAdvancedParent.html
  src/Raven.Studio/wwwroot/App/views/manage/debugAdvancedRecordTransactionCommands.html
  src/Raven.Studio/wwwroot/App/views/manage/debugAdvancedReplayTransactionCommands.html
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.eot
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.svg
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.ttf
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.woff
  src/Raven.Studio/wwwroot/Content/css/icons.less
  src/Voron/Impl/Compaction/StorageCompaction.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/Impl/Paging/Windows32BitsMemoryMapPager.cs
  test/FastTests/Issues/RavenDB-6250.cs
  test/FastTests/Server/Documents/Indexing/Auto/BasicAutoMapIndexing.cs
  test/SlowTests/Issues/RavenDB-12780.cs
  test/SlowTests/Issues/RavenDB_12790.cs
  test/SlowTests/Issues/RavenDB_7043.cs
  test/SlowTests/Server/Documents/ETL/RavenDB_12809.cs
  test/SlowTests/Server/RecordingTransactionOperationsMergerTests.cs
  test/SlowTests/Server/Replication/ReplicationConflictsTests.cs
  tools/TypingsGenerator/Program.cs
Labels: v4.2

#8651 4.1 to 4.2 merge
  src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
Labels: v4.2

#8603 RavenDB-12320 When smuggler imports revisions w/o documents, it creat…
  src/Raven.Server/Documents/Handlers/CountersHandler.cs
  src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
  test/SlowTests/Smuggler/SmugglerApiTests.cs
Labels: v4.1

#8652 RavenDB-12828 ChangesApiReorderDatabaseNodes - test fix
  test/SlowTests/Cluster/ClusterOperationTests.cs
Labels: v4.1

#8655 Add missing WaitForNonStaleResults() for a test (related to RavenDB-12784)
  test/FastTests/Graph/ClientGraphQueries.cs
  test/Tryouts/Program.cs
Labels: v4.2

#8654 RavenDB-12740 Add new incremental backup type extension
  src/Raven.Client/Constants.cs
  src/Raven.Client/Documents/Smuggler/BackupUtils.cs
  src/Raven.Server/Documents/PeriodicBackup/BackupTask.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreUtils.cs
Labels: v4.2

#8653 4.1 to 4.2 merge
  src/Raven.Server/Documents/Handlers/CountersHandler.cs
  src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
  test/SlowTests/Cluster/ClusterOperationTests.cs
  test/SlowTests/Smuggler/SmugglerApiTests.cs
Labels: v4.2

#8656 RavenDB-12823 fix failing tests
  src/Raven.Server/Documents/ConflictsStorage.cs
  src/Raven.Server/Documents/DocumentPutAction.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Replication/ConflictManager.cs
Labels: v4.1

#8658 RavenDB-12320 we need to wait for cluster command to be applied when writing database record
  src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
Labels: v4.1

#8660 RavenDB-12812 Search in the studio should allow keyboard navigation
  src/Raven.Studio/typescript/common/shell/searchBox.ts
  src/Raven.Studio/wwwroot/App/views/shell.html
  src/Raven.Studio/wwwroot/Content/css/basic-layout.less
Labels: v4.2

#8662 RavenDB-12813 Stack traces in v3.5 should be reversed
  Raven.Studio.Html5/App/viewmodels/manage/infoPackage.ts
Labels: v3.5

#8661 4.1 to 4.2 merge
  src/Raven.Server/Documents/ConflictsStorage.cs
  src/Raven.Server/Documents/DocumentPutAction.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Replication/ConflictManager.cs
  src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
Labels: v4.2

#8663 RavenDB-11139: CompareExchange should be deleted on DB delete.
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  test/SlowTests/Client/UniqueValues.cs
Labels: v4.1

#8665 RavenDB-12835 / RavenDB-12725 Make sure we won't attempt to sync data…
  tools/Voron.Recovery/Recovery.cs
Labels: v4.1

#8668 RavenDB-12838 Reuse file import widget in studio
  src/Raven.Studio/typescript/common/fileImporter.ts
  src/Raven.Studio/typescript/models/database/tasks/periodicBackup/ftpSettings.ts
  src/Raven.Studio/typescript/models/wizard/continueSetup.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/editIndex.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexPerformance.ts
  src/Raven.Studio/typescript/viewmodels/database/settings/editCustomSorter.ts
  src/Raven.Studio/typescript/viewmodels/database/status/ioStats.ts
  src/Raven.Studio/typescript/viewmodels/database/status/ongoingTasksStats.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editPullReplicationHubTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editPullReplicationSinkTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/importDatabaseFromSql.ts
  src/Raven.Studio/typescript/viewmodels/manage/captureStackTraces.ts
  src/Raven.Studio/typescript/viewmodels/manage/certificates.ts
  src/Raven.Studio/typescript/viewmodels/wizard/certificate.ts
  src/Raven.Studio/wwwroot/App/views/database/indexes/indexPerformance.html
  src/Raven.Studio/wwwroot/App/views/database/settings/editCustomSorter.html
  src/Raven.Studio/wwwroot/App/views/database/status/ioStats.html
  src/Raven.Studio/wwwroot/App/views/database/status/ongoingTasksStats.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editPeriodicBackupTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editPullReplicationHubTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editPullReplicationSinkTask.html
  src/Raven.Studio/wwwroot/App/views/manage/captureStackTraces.html
Labels: v4.2

#8667 4.1 to 4.2 merge
  src/Raven.Server/Documents/ConflictsStorage.cs
  src/Raven.Server/Documents/Replication/ResolveConflictOnReplicationConfigurationChange.cs
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  test/SlowTests/Client/UniqueValues.cs
  test/SlowTests/Server/Replication/ReplicationWithRevisions.cs
  tools/Voron.Recovery/Recovery.cs
Labels: v4.2

#8669 RavenDB-12829 fix Smuggler.LegacySmugglerTests.CanImportRevisions test
  src/Raven.Server/Documents/BlittableMetadataModifier.cs
  src/Raven.Server/Smuggler/Documents/StreamSource.cs
Labels: v4.1

#8670 RavenDB-12412 increase test timeout
  test/SlowTests/Authentication/AuthenticationClusterTests.cs
Labels: v4.1

#8671 RavenDB-12412 increase test timeout
  test/SlowTests/Authentication/AuthenticationClusterTests.cs
Labels: v4.0

#8672 RavenDB-12700 Handling the case that we might not be able to compress…
  src/Voron/Data/BTrees/Tree.Compressed.cs
  src/Voron/Data/BTrees/TreePageSplitter.cs
  src/Voron/Data/Compression/DecompressedLeafPage.cs
  test/SlowTests/SlowTests.csproj
  test/SlowTests/Voron/LeafsCompression/Data/RavenDB-12700-page-1278-compressed
  test/SlowTests/Voron/LeafsCompression/RavenDB_12700_Voron.cs
Labels: v4.1

#8673 RavenDB-12832 keep conflicted revision with its original change vector
  src/Raven.Server/Documents/Replication/IncomingReplicationHandler.cs
  src/Raven.Server/Documents/Replication/ResolveConflictOnReplicationConfigurationChange.cs
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  test/SlowTests/Server/Replication/ReplicationConflictsTests.cs
Labels: v4.1

#8674 RavenDB-12672 - throw when we allocated less than the required
  src/Raven.Server/Documents/Replication/IncomingReplicationHandler.cs
  src/Sparrow/Json/UnmanagedWriteBuffer.cs
Labels: v4.1

#8676 RavenDB-12847 - Add support for Normalize in LazyStringValue
  src/Sparrow/Json/LazyStringValue.cs
  test/SlowTests/Issues/RavenDB-12847.cs
Labels: v4.1

#8677 RavenDB-12848 bump studio packages versions
  src/Raven.Studio/package-lock.json
  src/Raven.Studio/package.json
Labels: v4.1

#8679 RavenDB-12849 Making sure we'll delete temporary files created in tests
  test/SlowTests/Authentication/AuthenticationLetsEncryptTests.cs
  test/SlowTests/Client/Attachments/AttachmentsSmuggler.cs
  test/SlowTests/Client/UniqueValues.cs
  test/SlowTests/Issues/RDBQA_11.cs
  test/SlowTests/Smuggler/SmugglerApiTests.cs
  test/SlowTests/Smuggler/SmugglerConflicts.cs
  test/Tests.Infrastructure/RavenTestHelper.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v4.0

#8678 RavenDB-12849 Making sure we'll delete temporary files created in tests
  test/InterversionTests/SmugglerTests.cs
  test/SlowTests/Authentication/AuthenticationEncryptionTests.cs
  test/SlowTests/Authentication/AuthenticationLetsEncryptTests.cs
  test/SlowTests/Client/Attachments/AttachmentsSmuggler.cs
  test/SlowTests/Client/UniqueValues.cs
  test/SlowTests/Cluster/ClusterTransactionTests.cs
  test/SlowTests/Issues/RDBQA_11.cs
  test/SlowTests/Server/Documents/ETL/RavenDB_12809.cs
  test/SlowTests/Server/Replication/ReplicationWithRevisions.cs
  test/SlowTests/Smuggler/SmugglerApiTests.cs
  test/SlowTests/Smuggler/SmugglerConflicts.cs
  test/Tests.Infrastructure/RavenTestHelper.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v4.1

#8680 4.1 to 4.2 merge
  src/Raven.Server/Documents/BlittableMetadataModifier.cs
  src/Raven.Server/Documents/Replication/IncomingReplicationHandler.cs
  src/Raven.Server/Documents/Replication/ResolveConflictOnReplicationConfigurationChange.cs
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  src/Raven.Server/Smuggler/Documents/StreamSource.cs
  src/Raven.Studio/package-lock.json
  src/Raven.Studio/package.json
  src/Sparrow/Json/LazyStringValue.cs
  src/Sparrow/Json/UnmanagedWriteBuffer.cs
  src/Voron/Data/BTrees/Tree.Compressed.cs
  src/Voron/Data/BTrees/TreePageSplitter.cs
  src/Voron/Data/Compression/DecompressedLeafPage.cs
  test/InterversionTests/SmugglerTests.cs
  test/SlowTests/Authentication/AuthenticationClusterTests.cs
  test/SlowTests/Authentication/AuthenticationEncryptionTests.cs
  test/SlowTests/Authentication/AuthenticationLetsEncryptTests.cs
  test/SlowTests/Client/Attachments/AttachmentsSmuggler.cs
  test/SlowTests/Client/UniqueValues.cs
  test/SlowTests/Cluster/ClusterTransactionTests.cs
  test/SlowTests/Issues/RDBQA_11.cs
  test/SlowTests/Issues/RavenDB-12847.cs
  test/SlowTests/Server/Documents/ETL/RavenDB_12809.cs
  test/SlowTests/Server/Replication/ReplicationConflictsTests.cs
  test/SlowTests/Server/Replication/ReplicationWithRevisions.cs
  test/SlowTests/SlowTests.csproj
  test/SlowTests/Smuggler/SmugglerApiTests.cs
  test/SlowTests/Smuggler/SmugglerConflicts.cs
  test/SlowTests/Voron/LeafsCompression/Data/RavenDB-12700-page-1278-compressed
  test/SlowTests/Voron/LeafsCompression/RavenDB_12700_Voron.cs
  test/Tests.Infrastructure/RavenTestHelper.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v4.2

#8681 RavenDB-12849 Making sure we'll delete temporary files created in tes…
  test/SlowTests/Server/Documents/PeriodicBackup/EncryptedBackupTest.cs
  test/SlowTests/Smuggler/SmugglerApiTests.cs
Labels: v4.2

#8683 RavenDB-12853 giving better names to databases in tests
  test/Tests.Infrastructure/TestBase.cs
Labels: v4.1

#8689 4.1 to 4.2 merge
  test/Tests.Infrastructure/TestBase.cs
Labels: v4.2

#8684 RavenDB-12764 create a revision from incoming replication
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  test/SlowTests/Server/Documents/Revisions/RevertRevisionsTests.cs
Labels: v4.2

#8690 RavenDB-12630 support 8, 9, 10 and 11 in install build prerequisites …
  install_build_prerequisites.sh
Labels: v4.0

#8691 RavenDB-12630 support 8, 9, 10 and 11 in install build prerequisites …
  install_build_prerequisites.sh
Labels: v4.1

#8686 RavenDB-12850 / RavenDB-12700 Fixing map-reduce issue related to comp…
  src/Voron/Data/BTrees/Tree.Compressed.cs
  src/Voron/Data/Compression/DecompressedLeafPage.cs
Labels: v4.1

#8692 RavenDB-12870 Removing condition that made that tombstones of documen…
  src/Raven.Server/Documents/Indexes/Workers/CleanupDeletedDocuments.cs
  test/SlowTests/Issues/RavenDB_12870.cs
Labels: v4.1

#8695 4.1 to 4.2 merge
  install_build_prerequisites.sh
  src/Raven.Server/Documents/Indexes/Workers/CleanupDeletedDocuments.cs
  src/Voron/Data/BTrees/Tree.Compressed.cs
  src/Voron/Data/Compression/DecompressedLeafPage.cs
  test/FastTests/Server/Documents/DocumentsCrud.cs
  test/SlowTests/Issues/RavenDB_12870.cs
  test/SlowTests/Server/Documents/Queries/Dynamic/Map/MatchingAutoMapIndexesForDynamicQueries.cs
  test/SlowTests/Server/Documents/Queries/Dynamic/MapReduce/MatchingAutoMapReduceIndexesForDynamicQueries.cs
  test/SlowTests/Server/Documents/Queries/MatchingAutoMapReduceIndexesForDynamicQueriesSlow.cs
  test/SlowTests/Server/Documents/Revisions/RevisionsReplication.cs
  test/SlowTests/Smuggler/SmugglerConflicts.cs
  test/SlowTests/Tests/Spatial/Afif.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v4.2

#8698 RavenDB-7070 updated to .NET Core 2.2.2
  bench/BulkInsert.Benchmark/BulkInsert.Benchmark.csproj
  bench/Indexing.Benchmark/Indexing.Benchmark.csproj
  bench/Micro.Benchmark/Micro.Benchmark.csproj
  bench/Regression.Benchmark/Regression.Benchmark.csproj
  bench/SubscriptionFailover.Benchmark/SubscriptionFailover.Benchmark.csproj
  bench/Subscriptions.Benchmark/Subscriptions.Benchmark.csproj
  bench/Voron.Benchmark/Voron.Benchmark.csproj
  src/Raven.Embedded/ServerOptions.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Studio/Raven.Studio.csproj
  test/BenchmarkTests/BenchmarkTests.csproj
  test/EmbeddedTests/EmbeddedTests.csproj
  test/FastTests/FastTests.csproj
  test/InterversionTests/InterversionTests.csproj
  test/RachisTests/RachisTests.csproj
  test/SlowTests/SlowTests.csproj
  test/StressTests/StressTests.csproj
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
  test/Tryouts/Tryouts.csproj
  tools/Raven.Debug/Raven.Debug.csproj
  tools/Raven.Migrator/Raven.Migrator.csproj
  tools/TypingsGenerator/TypingsGenerator.csproj
  tools/Voron.Recovery/Voron.Recovery.csproj
  tools/rvn/rvn.csproj
Labels: v4.2

#8699 RavenDB-11876 clone encryption key for compaction
  src/Raven.Server/Documents/CompactDatabaseTask.cs
  test/SlowTests/Authentication/AuthenticationEncryptionTests.cs
Labels: v4.1

#8700 RavenDB-11876 clone encryption key for compaction + tests
  src/Raven.Server/Documents/CompactDatabaseTask.cs
  test/SlowTests/Authentication/AuthenticationEncryptionTests.cs
Labels: v4.0

#8701 RavenDB-7070 JIT in .NET Core 2.2.2 does not longer have the limitation
  test/SlowTests/Issues/RavenDB_10621.cs
Labels: v4.2

#8706 RavenDB-12861 Change Vector preview is broken
  src/Raven.Studio/typescript/viewmodels/database/documents/editDocument.ts
Labels: v4.2

#8705 RavenDB-12842 Capturing local stack traces throws sillently
  src/Raven.Server/Documents/Handlers/Debugging/ThreadsHandler.cs
  src/Raven.Studio/typescript/commands/maintenance/captureClusterStackTracesCommand.ts
Labels: v4.2

#8707 RavenDB-12229 Next Starting Batch value from subscriptions should be …
  src/Raven.Studio/typescript/models/database/tasks/ongoingTaskSubscriptionListModel.ts
  src/Raven.Studio/wwwroot/App/views/database/tasks/ongoingTasks.html
  src/Raven.Studio/wwwroot/Content/css/pages/ongoing-tasks.less
Labels: v4.2

#8703 RavenDB-12876 When running environment in memory we should not attemp…
  src/Voron/StorageEnvironmentOptions.cs
Labels: v4.1

#8638 RavenDB-12684: Reducing chance to have finalization order issues
  src/Raven.Client/Documents/Session/InMemoryDocumentSessionOperations.cs
  src/Raven.Client/Documents/Subscriptions/DocumentSubscriptions.cs
  src/Raven.Client/Http/HttpCache.cs
  src/Raven.Server/ServerWide/OperationCancelToken.cs
  src/Sparrow/ByteString.cs
  src/Sparrow/Json/ArenaMemoryAllocator.cs
  src/Sparrow/Json/JsonContextPoolBase.cs
  src/Sparrow/Json/JsonOperationContext.cs
Labels: v4.1

#8645 RavenDB-12684: Reducing chance to have finalization order issues
  src/Raven.Client/Documents/Session/InMemoryDocumentSessionOperations.cs
  src/Raven.Client/Documents/Subscriptions/DocumentSubscriptions.cs
  src/Raven.Client/Http/HttpCache.cs
  src/Raven.Server/ServerWide/OperationCancelToken.cs
  src/Sparrow/ByteString.cs
  src/Sparrow/Json/ArenaMemoryAllocator.cs
  src/Sparrow/Json/JsonContextPoolBase.cs
  src/Sparrow/Json/JsonOperationContext.cs
Labels: v4.0

#8709 RavenDB-12878 iterating resource cache should be done in case insensitive manner
  src/Raven.Server/Documents/ResourceCache.cs
  src/Raven.Server/Program.cs
Labels: v4.0

#8710 RavenDB-12878 iterating resource cache should be done in case insensitive manner
  src/Raven.Server/Documents/ResourceCache.cs
  src/Raven.Server/Program.cs
Labels: v4.1

#8711 RavenDB-12880 fixed calculation
  src/Sparrow/Platform/PlatformDetails.cs
Labels: v4.0

#8712 RavenDB-12880 fixed calculation
  src/Sparrow/Platform/PlatformDetails.cs
Labels: v4.1

#8713 4.1 to 4.2 merge
  src/Raven.Client/Documents/Subscriptions/DocumentSubscriptions.cs
  src/Raven.Server/Documents/CompactDatabaseTask.cs
  src/Raven.Server/Documents/ResourceCache.cs
  src/Raven.Server/Program.cs
  src/Sparrow/Platform/PlatformDetails.cs
  src/Voron/StorageEnvironmentOptions.cs
  test/SlowTests/Authentication/AuthenticationEncryptionTests.cs
Labels: v4.2

#8719 RavenDB-12869 Fixing disposal of IndexWriteOperation in test
  test/SlowTests/Server/Documents/Indexing/MapReduce/RavenDB_11643.cs
Labels: v4.1

#8720 RavenDB-12869 Fixing disposal of IndexWriteOperation in test
  test/SlowTests/Server/Documents/Indexing/MapReduce/RavenDB_11643.cs
Labels: v4.0

#8717 RavenDB-10862 Add a way to filter indexes by state
  src/Raven.Studio/typescript/common/appUrl.ts
  src/Raven.Studio/typescript/common/shell/footer.ts
  src/Raven.Studio/typescript/models/database/index/index.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexes.ts
  src/Raven.Studio/typings/_studio/dto.d.ts
  src/Raven.Studio/wwwroot/App/views/database/indexes/indexes.html
  src/Raven.Studio/wwwroot/App/views/shell.html
  src/Raven.Studio/wwwroot/Content/css/basic-layout.less
  src/Raven.Studio/wwwroot/Content/css/pages/indexes.less
Labels: v4.2

#8718 RavenDB-12593 Editor background and selected row colors should be exc…
  src/Raven.Studio/wwwroot/Content/css/ace.less
Labels: v4.2

#8715 RavenDB-12867 added support for deserialize of Dictionary<string, Bl…
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreSettings.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/Commands/AddDatabaseCommand.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Sparrow/Json/JsonDeserializationBase.cs
  test/SlowTests/Issues/RavenDB_12867.cs
Labels: v4.1

#8722 Raven db 10862
  src/Raven.Studio/typescript/common/generalUtils.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexes.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/virtualGridUtils.ts
  src/Raven.Studio/wwwroot/App/views/database/indexes/indexes.html
Labels: v4.2

#8708 RavenDB-12823 fix inconsistent revision count in the cluster when the…
  src/Raven.Server/Documents/ConflictsStorage.cs
  src/Raven.Server/Documents/DocumentPutAction.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Replication/ConflictManager.cs
  src/Raven.Server/Documents/Replication/IncomingReplicationHandler.cs
  src/Raven.Server/Documents/Replication/ReplicationDocumentSender.cs
  src/Raven.Server/Documents/Replication/ResolveConflictOnReplicationConfigurationChange.cs
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  test/SlowTests/Server/Documents/Revisions/RevisionsReplication.cs
  test/SlowTests/Server/Replication/ReplicationConflictsTests.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
Labels: v4.1

#8723 RavenDB-7070 CsvWriter should use same delimeter as CsvReader so cult…
  src/Raven.Server/Documents/Handlers/StreamCsvBlittableQueryResultWriter.cs
  src/Raven.Server/Documents/Handlers/StreamCsvDocumentQueryResultWriter.cs
  src/Raven.Server/Documents/Handlers/StreamCsvResultWriter.cs
  src/Raven.Server/Documents/Handlers/StreamingHandler.cs
  src/Raven.Server/Smuggler/Documents/CsvStreamSource.cs
  test/SlowTests/Issues/RavenDB_6596.cs
Labels: v4.1

#8724 RavenDB-7070 CsvWriter should use same delimeter as CsvReader so culture specific tests can pass
  src/Raven.Server/Documents/Handlers/StreamCsvDocumentQueryResultWriter.cs
  src/Raven.Server/Documents/Handlers/StreamingHandler.cs
  src/Raven.Server/Smuggler/Documents/CsvStreamSource.cs
  test/SlowTests/Issues/RavenDB_6596.cs
Labels: v4.0

#8725 4.1 to 4.2 merge
  src/Raven.Server/Documents/ConflictsStorage.cs
  src/Raven.Server/Documents/DocumentPutAction.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Handlers/StreamCsvBlittableQueryResultWriter.cs
  src/Raven.Server/Documents/Handlers/StreamCsvDocumentQueryResultWriter.cs
  src/Raven.Server/Documents/Handlers/StreamCsvResultWriter.cs
  src/Raven.Server/Documents/Handlers/StreamingHandler.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreSettings.cs
  src/Raven.Server/Documents/Replication/ConflictManager.cs
  src/Raven.Server/Documents/Replication/IncomingReplicationHandler.cs
  src/Raven.Server/Documents/Replication/ReplicationDocumentSender.cs
  src/Raven.Server/Documents/Replication/ResolveConflictOnReplicationConfigurationChange.cs
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/Commands/AddDatabaseCommand.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Smuggler/Documents/CsvStreamSource.cs
  src/Sparrow/Json/JsonDeserializationBase.cs
  test/SlowTests/Issues/RavenDB_12867.cs
  test/SlowTests/Issues/RavenDB_6596.cs
  test/SlowTests/Server/Documents/Indexing/MapReduce/RavenDB_11643.cs
  test/SlowTests/Server/Documents/Revisions/RevisionsReplication.cs
  test/SlowTests/Server/Replication/ReplicationConflictsTests.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
Labels: v4.2

#8728 RavenDB-12730: use already implemented rvn_get_current_thread_id thro…
  src/Raven.Server/Documents/Replication/OutgoingReplicationHandler.cs
  src/Raven.Server/Program.cs
  src/Raven.Server/Rachis/Candidate.cs
  src/Raven.Server/Rachis/Elector.cs
  src/Raven.Server/Rachis/Leader.cs
  src/Raven.Server/Utils/PoolOfThreads.cs
  src/Sparrow/Platform/Posix/PerPlatformValues.cs
  src/Sparrow/Utils/NativeMemory.cs
  src/Voron/Platform/Pal.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v4.2

#8721 RavenDB-10999 rich cron editor
  src/Raven.Server/Web/Studio/StudioTasksHandler.cs
  src/Raven.Server/Web/System/BackupDatabaseHandler.cs
  src/Raven.Studio/typescript/commands/database/tasks/getCronExpressionOccurrenceCommand.ts
  src/Raven.Studio/typescript/commands/database/tasks/getNextBackupOccurrenceCommand.ts
  src/Raven.Studio/typescript/models/database/tasks/periodicBackup/periodicBackupConfiguration.ts
  src/Raven.Studio/typescript/viewmodels/common/cronEditor.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editPeriodicBackupTask.ts
  src/Raven.Studio/wwwroot/App/views/common/cronEditor.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editPeriodicBackupTask.html
  src/Raven.Studio/wwwroot/Content/css/pages/edit-backup.less
  tools/TypingsGenerator/Program.cs
Labels: v4.2

#8730 RavenDB-12484
  src/Raven.Client/Documents/Conventions/JsonNetBlittableEntitySerializer.cs
  test/SlowTests/Issues/RavenDB-11907.cs
  test/SlowTests/Issues/RavenDB-12484.cs
Labels: v4.1

#8729 RDBC-267 in class Raven.Client.Documents.Session.DocumentsChanges som…
  src/Raven.Client/Documents/Session/DocumentsChanges.cs
Labels: v4.1

#8733 4.1 to 4.2 merge
  src/Raven.Client/Documents/Conventions/JsonNetBlittableEntitySerializer.cs
  src/Raven.Client/Documents/Session/DocumentsChanges.cs
  src/Raven.Server/Documents/CountersStorage.cs
  src/Raven.Server/Documents/Replication/ConflictManager.cs
  src/Raven.Server/Documents/Replication/IncomingReplicationHandler.cs
  src/Raven.Server/Documents/Replication/ReplicationDocumentSender.cs
  src/Raven.Server/Documents/Replication/ResolveConflictOnReplicationConfigurationChange.cs
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  src/Raven.Server/Documents/StreamsTempFile.cs
  src/Raven.Server/Smuggler/Documents/DatabaseSmuggler.cs
  src/Raven.Server/Smuggler/Documents/StreamSource.cs
  src/Raven.Server/Storage/Schema/Updates/Documents/From16.cs
  test/SlowTests/Issues/RavenDB-11907.cs
  test/SlowTests/Issues/RavenDB-12484.cs
  test/SlowTests/Issues/RavenDB_12601.cs
  test/SlowTests/Server/Replication/ReplicationWithRevisions.cs
Labels: v4.2

#8734 RavenDB-12906 fix studio compilation related to update of counter ref…
  src/Raven.Server/Documents/ETL/Providers/Raven/RavenEtlDocumentTransformer.cs
  src/Raven.Studio/typescript/models/database/tasks/abstractOngoingTaskEtlListModel.ts
  src/Raven.Studio/typescript/viewmodels/database/status/ongoingTasksStats.ts
Labels: v4.2

#8731 RavenDB-12793
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Voron/Impl/Scratch/ScratchBufferFile.cs
  src/Voron/Impl/Scratch/ScratchBufferPool.cs
  test/StressTests/Server/Replication/ExternalReplicationStressTests.cs
Labels: v4.1

#8748 RavenDB-12908 test replication connection shouldn't use bidirectional…
  src/Raven.Studio/typescript/commands/database/cluster/testClusterNodeConnectionCommand.ts
  src/Raven.Studio/typescript/models/database/settings/connectionStringRavenEtlModel.ts
Labels: v4.1

#8744 RavenDB-12854 We must not use current tx when dealing with compressio…
  src/Voron/Impl/Journal/WriteAheadJournal.cs
Labels: v4.1

#8745 RavenDB-12854 We must not use current tx when dealing with compressio…
  src/Voron/Impl/Journal/WriteAheadJournal.cs
Labels: v4.0

#8743 RavenDB-12248 : Typed patch API should respect $type for subclasses
  src/Raven.Client/Documents/Session/InMemoryDocumentSessionOperations.Patch.cs
  src/Raven.Client/Json/TypeConverter.cs
  test/SlowTests/Issues/RavenDB-12248.cs
Labels: v4.1

#8742 RavenDB-12911 Concurrency exception during spawning CandidateAmbassad…
  src/Raven.Server/Rachis/Candidate.cs
  src/Raven.Server/Rachis/CandidateAmbassador.cs
Labels: v4.1

#8739 RavenDB-12491: Minor - Fix error message
  src/Sparrow.Server/Sodium.cs
Labels: v4.2

#8753 4.1 to 4.2 merge
  src/Raven.Client/Documents/Session/InMemoryDocumentSessionOperations.Patch.cs
  src/Raven.Client/Json/TypeConverter.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Rachis/Candidate.cs
  src/Raven.Server/Rachis/CandidateAmbassador.cs
  src/Raven.Studio/typescript/commands/database/cluster/testClusterNodeConnectionCommand.ts
  src/Raven.Studio/typescript/models/database/settings/connectionStringRavenEtlModel.ts
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/Impl/Scratch/ScratchBufferFile.cs
  src/Voron/Impl/Scratch/ScratchBufferPool.cs
  test/SlowTests/Issues/RavenDB-12248.cs
  test/StressTests/Server/Replication/ExternalReplicationStressTests.cs
Labels: v4.2

#8756 RavenDB-12921 - Porting failing tests
  test/SlowTests/Issues/RavenDB-12921.cs
Labels: v4.0

#8754 fix for RavenDB-12494
  src/Raven.Server/Routing/RequestRouter.cs
  test/Tryouts/Program.cs
Labels: v4.1

#8757 RavenDB-12823 a resolved document will generate a new change vector t…
  src/Raven.Server/Documents/ConflictsStorage.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Replication/ConflictManager.cs
  src/Raven.Server/Documents/Replication/ResolveConflictOnReplicationConfigurationChange.cs
  src/Raven.Server/Utils/ChangeVectorUtils.cs
  test/SlowTests/Cluster/ClusterTransactionTests.cs
  test/SlowTests/Server/Replication/ReplicationConflictsTests.cs
  test/SlowTests/Server/Replication/ReplicationWithRevisions.cs
Labels: v4.1

#8759 RavenDB-12793 fixed cluster transaction task so it won't hang thus le…
  src/Raven.Server/Documents/DocumentDatabase.cs
Labels: v4.1

#8762 RavenDB-12926 AsyncManualResetEvent.WaitAsync(Cts) should work even i…
  src/Sparrow/AsyncManualResetEvent.cs
  test/FastTests/Issues/RavenDB-12926.cs
Labels: v4.1

#8763 RavenDB-8891
  test/SlowTests/Issues/RavenDB_8891.cs
Labels: v4.2

#8765 RavenDB-12854 Taking into account that we might be using 32 bits page…
  src/Voron/Impl/Journal/WriteAheadJournal.cs
Labels: v4.1

#8764 RavenDB-12904 Let's not include stats of current ETL batch to the ove…
  src/Raven.Server/Documents/ETL/EtlProcess.cs
Labels: v4.2

#8761 RavenDB-12891 When adding / deleting results of map-reduce index as a…
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/OutputReduceIndexWriteOperation.cs
  test/SlowTests/Issues/RavenDB_12891.cs
Labels: v4.0

#8760 RavenDB-12891 When adding / deleting results of map-reduce index as a…
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/OutputReduceIndexWriteOperation.cs
  test/SlowTests/Issues/RavenDB_12891.cs
Labels: v4.1

#8766 RavenDB-12854 Taking into account that we might be using 32 bits page…
  src/Voron/Impl/Journal/WriteAheadJournal.cs
Labels: v4.0

#8768 4.1 to 4.2 merge
  src/Raven.Client/Http/NodeSelector.cs
  src/Raven.Client/Http/RequestExecutor.cs
  src/Raven.Server/Documents/ConflictsStorage.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/OutputReduceIndexWriteOperation.cs
  src/Raven.Server/Documents/Replication/ConflictManager.cs
  src/Raven.Server/Documents/Replication/ResolveConflictOnReplicationConfigurationChange.cs
  src/Raven.Server/Routing/RequestRouter.cs
  src/Raven.Server/Utils/ChangeVectorUtils.cs
  src/Sparrow.Server/AsyncManualResetEvent.cs
  src/Sparrow/Json/ArenaMemoryAllocator.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  test/FastTests/Issues/RavenDB-12926.cs
  test/SlowTests/Cluster/ClusterTransactionTests.cs
  test/SlowTests/Issues/RavenDB-12921.cs
  test/SlowTests/Issues/RavenDB_12891.cs
  test/SlowTests/Server/Replication/ReplicationConflictsTests.cs
  test/SlowTests/Server/Replication/ReplicationWithRevisions.cs
Labels: v4.2

#8769 Fix database topology not cleared from local cache
  src/Raven.Client/Http/DatabaseTopologyLocalCache.cs
Labels: v4.2

#8771 RavenDB-12931 Releasing memory allocations while doing counter schema…
  src/Raven.Server/Storage/Schema/Updates/Documents/From16.cs
Labels: v4.2

#8773 RavenDB-12886 remove google+ links from studio
  src/Raven.Studio/wwwroot/App/views/shell/about.html
Labels: v4.1

#8776 RavenDB-12594 Documents List View - Fields don't show after refresh (…
  .gitignore
  src/Raven.Studio/typescript/models/database/documents/document.ts
  src/Raven.Studio/typescript/viewmodels/database/documents/documents.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/columns/providers/documentBasedColumnsProvider.ts
Labels: v4.1

#8772 RavenDB-10999 Proper editor for the cron syntax - PR fix
  src/Raven.Server/Web/Studio/StudioTasksHandler.cs
  src/Raven.Studio/typescript/commands/database/tasks/getCronExpressionOccurrenceCommand.ts
  src/Raven.Studio/typescript/viewmodels/common/cronEditor.ts
Labels: v4.2

#8775 RavenDB-12903 Add sample etl script with counters / document deletion
  src/Raven.Studio/typescript/viewmodels/database/tasks/transformationScriptSyntax.ts
  src/Raven.Studio/wwwroot/App/views/database/tasks/transformationScriptSyntax.html
Labels: v4.2

#8780 4.1 to 4.2 merge
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Routing/RequestRouter.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/Commands/ClusterTransactionCommand.cs
  src/Raven.Studio/typescript/models/database/documents/document.ts
  src/Raven.Studio/typescript/viewmodels/database/documents/documents.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/columns/providers/documentBasedColumnsProvider.ts
  src/Raven.Studio/wwwroot/App/views/shell/about.html
  test/SlowTests/Cluster/ClusterTransactionTests.cs
Labels: v4.2

#8781 RavenDB-12377 Backup database record - interversion test
  test/InterversionTests/SmugglerTests.cs
Labels: v4.1

#8783 RavenDB-12900 have a timeout for a cluster transaction request.
  src/Raven.Server/Documents/ClusterTransactionWaiter.cs
  src/Raven.Server/Documents/Handlers/BatchHandler.cs
Labels: v4.1

#8784 RavenDB-12934 fix `LockAlreadyDisposedException` exception in `Remove…
  test/Tests.Infrastructure/ClusterTestBase.cs
Labels: v4.1

#8785 RavenDB-12662 fixing JS indexes for cases where documents+indexes are…
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/PropertyAccessor.cs
  test/FastTests/Client/Indexing/JavaScriptIndexTests.cs
Labels: v4.2

#8786 RavenDB-12923 fixed double open read Tx in graph query runner code
  src/Raven.Server/Documents/Queries/Graph/GraphQueryPlan.cs
Labels: v4.2

#8788 4.1 to 4.2 merge
  src/Raven.Server/Documents/ClusterTransactionWaiter.cs
  src/Raven.Server/Documents/Handlers/BatchHandler.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
Labels: v4.2

#8787 RavenDB-12941
  src/Raven.Client/Http/RequestExecutor.cs
Labels: v4.1

#8792 RavenDB-12881 add ability to customize which portions of database rec…
  src/Raven.Studio/typescript/models/database/tasks/exportDatabaseModel.ts
  src/Raven.Studio/typescript/models/database/tasks/importDatabaseModel.ts
  src/Raven.Studio/typescript/models/database/tasks/smugglerDatabaseRecord.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/exportDatabase.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/importDatabaseFromFile.ts
  src/Raven.Studio/wwwroot/App/views/database/tasks/exportDatabase.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/importDatabaseFromFile.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/smugglerDatabaseRecord.html
Labels: v4.2

#8793 RavenDB-7291: Verified in dotnet 2.2.2 - https://github.com/dotnet/co…
  src/Raven.Client/Http/AttachmentStreamContent.cs
Labels: v4.2

#8795 RavenDB-11999 BlittableJsonReaderObject.Clone better handling when Mo…
  src/Sparrow/Json/BlittableJsonReaderObject.cs
Labels: v4.2

#8794 RDBC-285 Allow to define boost 0 from the client API
  src/Raven.Client/Documents/Session/AbstractDocumentQuery.cs
Labels: v4.1

#8796 RavenDB-12905 use counterGroups instead of Counters in studio. Added …
  src/Raven.Studio/typescript/models/database/tasks/exportDatabaseModel.ts
  src/Raven.Studio/typescript/models/database/tasks/importDatabaseModel.ts
  src/Raven.Studio/wwwroot/App/views/database/tasks/importDatabaseFromFile.html
Labels: v4.2

#8797 RavenDB-12806 Added cancellation token when waiting for index lock. W…
  src/Raven.Server/Documents/Handlers/IndexHandler.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
Labels: v4.1

#8798 RavenDB-12806 Added cancellation token when waiting for index lock. W…
  src/Raven.Server/Documents/Handlers/IndexHandler.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
Labels: v4.0

#8800 4.1 to 4.2 merge
  src/Raven.Client/Documents/Changes/DatabaseChanges.cs
  src/Raven.Client/Documents/Commands/Batches/BatchCommand.cs
  src/Raven.Client/Documents/Commands/Batches/PutAttachmentCommandHelper.cs
  src/Raven.Client/Documents/Session/AbstractDocumentQuery.cs
  src/Raven.Client/Http/RequestExecutor.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Handlers/IndexHandler.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  src/Raven.Server/Documents/Replication/IncomingReplicationHandler.cs
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
  test/FastTests/Utils/RevisionsHelper.cs
  test/InterversionTests/SmugglerTests.cs
  test/SlowTests/Issues/RavenDB-12477.cs
  test/SlowTests/Server/Replication/ReplicationSpecialCases.cs
  test/SlowTests/SlowTests.csproj
  test/SlowTests/Smuggler/Document_Without_Attachment_Stream.ravendbdump
  test/SlowTests/Smuggler/RavenDB-12890.cs
Labels: v4.2

#8804 RavenDB-12959: Pool collectors lists
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Collectors/CollectorsPool.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Collectors/GatherAllCollector.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Collectors/IntersectionCollector.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Collectors/NonSortingCollector.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/IndexReadOperation.cs
Labels: v4.1

#8801 RavenDB-12956 Fixing NREs in 4.2 tests
  src/Raven.Server/Commercial/LicenseManager.cs
  src/Raven.Server/Commercial/SetupManager.cs
Labels: v4.2

#8790 RavenDB-12912 Reduce Voron.Data.Tables.NewPageAllocator.Create() allo…
  src/Voron/Data/Tables/NewPageAllocator.cs
  test/FastTests/Voron/Tables/Allocations.cs
Labels: v4.1

#8802 RDBC-285 Add test for zero boosting
  test/SlowTests/Issues/RDBC-285.cs
Labels: v4.1

#8805 4.1 to 4.2 merge
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Collectors/CollectorsPool.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Collectors/GatherAllCollector.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Collectors/IntersectionCollector.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Collectors/NonSortingCollector.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/IndexReadOperation.cs
  src/Voron/Data/Tables/NewPageAllocator.cs
  test/FastTests/Voron/Tables/Allocations.cs
  test/SlowTests/Issues/RDBC-285.cs
Labels: v4.2

#8782 RavenDB-12924
  src/Raven.Server/Documents/CountersStorage.cs
  test/SlowTests/Client/Counters/CountersCluster.cs
Labels: v4.2

#8807 RavenDB-12961
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreBackupTask.cs
  src/Raven.Server/ServerWide/Commands/AddDatabaseCommand.cs
  test/Tryouts/Program.cs
Labels: v4.1

#8814 RavenDB-12890 - dispose the CounterValues
  src/Raven.Server/Documents/Replication/IncomingReplicationHandler.cs
Labels: v4.2

#8803 RavenDB-12598 adding test for changes-api with aggressive caching
  test/SlowTests/Issues/RavenDB-12598.cs
Labels: v4.1

#8815 RavenDB-12843: Fix race where we commit (and therefor staleness) but …
  test/SlowTests/Server/Documents/Indexing/MapReduce/OutputReduceToCollectionTests.cs
Labels: v4.1

#8808 RavenDB-12960 fixed possible SOE after receiving HttpStatus.Gone
  src/Raven.Client/Exceptions/UnsuccessfulRequestException.cs
  src/Raven.Client/Http/RequestExecutor.cs
  test/Tryouts/Program.cs
Labels: v4.1

#8811 RavenDB-12963 - Leader is stepping down when the snapshot is too large
  src/Raven.Server/Rachis/FollowerAmbassador.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
Labels: v4.1

#8817 RavenDB-12966 Select() in Include() causes ArgumentException when lis…
  src/Raven.Client/Json/BlittableExtensions.cs
  test/SlowTests/MailingList/Enzmann.cs
Labels: v4.1

#8816 RavenDB-12964 Raven Embedded should allow to point to a server directory
  src/Raven.Embedded/RavenServerRunner.cs
  src/Raven.Embedded/ServerOptions.cs
  src/Raven.TestDriver/TestServerOptions.cs
Labels: v4.1

#8822 RavenDB-12731 support for comparison between LCSV and LSV
  src/Sparrow/Json/LazyCompressedStringValue.cs
  src/Sparrow/Json/LazyStringValue.cs
  test/FastTests/Issues/RavenDB_12731.cs
Labels: v4.1
