Repository ravendb/ravendb, pull requests merged in 2019-08, with the labels that each got.

#9569 RavenDB-13895
  src/Raven.Server/Background/BackgroundWorkBase.cs
  src/Raven.Server/Documents/Expiration/ExpiredDocumentsCleaner.cs
Labels: v4.2

#9572 RavenDB-13879 Fix Info Text in Studio - regression after RavenDB-13571
  src/Raven.Studio/wwwroot/Content/css/bootstrap/variables-body.less
  src/Raven.Studio/wwwroot/Content/css/pages/edit-index.less
  src/Raven.Studio/wwwroot/Content/css/pages/etl.less
  src/Raven.Studio/wwwroot/Content/css/pages/metrics.less
  src/Raven.Studio/wwwroot/Content/css/pages/storage-report.less
  src/Raven.Studio/wwwroot/Content/css/styles-common.less
  src/Raven.Studio/wwwroot/Content/css/themes/blue-theme-variables-override.less
Labels: v4.2

#9571 RavenDB-13870 detecting artificial projection and avoid treating it as a projection, returning whole document in this case
  src/Raven.Server/Documents/Queries/FieldsToFetch.cs
  test/SlowTests/Issues/RavenDB_13870.cs
Labels: v4.1

#9574 RavenDB-13815 Can't see the properties of a document when the documen…
  src/Raven.Studio/wwwroot/App/views/database/documents/editDocument.html
  src/Raven.Studio/wwwroot/Content/css/pages/documents-edit.less
Labels: v4.2

#9575 4.1 to 4.2 merge
  src/Raven.Client/Documents/Session/EntityToBlittable.cs
  src/Raven.Client/Documents/Session/Operations/BatchOperation.cs
  src/Raven.Server/Documents/Queries/FieldsToFetch.cs
  src/Raven.Server/Documents/Queries/GraphQueryRunner.cs
  test/FastTests/Client/Documents/BasicDocuments.cs
  test/FastTests/Issues/RavenDB_13891.cs
  test/FastTests/Issues/RavenDB_9875.cs
  test/InterversionTests/MixedClusterTests.cs
  test/SlowTests/Issues/RavenDB-5686.cs
  test/SlowTests/Issues/RavenDB_13868.cs
  test/SlowTests/Issues/RavenDB_13870.cs
Labels: v4.2

#9577 RavenDB-13815 fix flex
  src/Raven.Studio/wwwroot/App/views/database/documents/editDocument.html
  src/Raven.Studio/wwwroot/Content/css/pages/documents-edit.less
Labels: v4.2

#9578 RavenDB-13898 - redundant string.Format
  src/Raven.Server/Documents/PeriodicBackup/BackupTask.cs
  src/Raven.Server/ServerWide/SecretProtection.cs
  src/Raven.Server/Utils/DirectoryExecUtils.cs
Labels: v4.2

#9582 RavenDB-13762 session in subscription should not track revisions
  src/Raven.Client/Documents/Subscriptions/SubscriptionBatch.cs
  test/SlowTests/Issues/RavenDB_13762.cs
Labels: v4.1

#9584 RavenDB-13673-2 bumping Lucene.Net.3.0.20.nupkg => Lucene.Net.3.0.21.…
  libs/Lucene.Net.3.0.20.nupkg
  libs/Lucene.Net.3.0.21.nupkg
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/IndexFacetedReadOperation.cs
  src/Raven.Server/Raven.Server.csproj
Labels: v4.2

#9562 RavenDB-13098 Replication sending / incoming refactoring
  src/Raven.Client/Documents/Replication/OutgoingReplicationPerformanceStats.cs
  src/Raven.Server/Documents/AttachmentsStorage.cs
  src/Raven.Server/Documents/CountersStorage.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Replication/IncomingReplicationHandler.cs
  src/Raven.Server/Documents/Replication/OutgoingReplicationStatsAggregator.cs
  src/Raven.Server/Documents/Replication/ReplicationBatchItem.cs
  src/Raven.Server/Documents/Replication/ReplicationDocumentSender.cs
  src/Raven.Server/Documents/Replication/ReplicationItems/AttachmentReplicationItem.cs
  src/Raven.Server/Documents/Replication/ReplicationItems/AttachmentTombstoneReplicationItem.cs
  src/Raven.Server/Documents/Replication/ReplicationItems/CounterReplicationItem.cs
  src/Raven.Server/Documents/Replication/ReplicationItems/DocumentReplicationItem.cs
  src/Raven.Server/Documents/Replication/ReplicationItems/ReplicationBatchItem.cs
  src/Raven.Server/Documents/Replication/ReplicationItems/RevisionTombstoneReplicationItem.cs
  src/Raven.Server/Documents/Replication/ReplicationItems/TimeSeriesReplicationItem.cs
  src/Raven.Server/Documents/Replication/ReplicationItems/TombstoneReplicationItem.cs
  src/Raven.Server/Documents/Replication/ReplicationOperation.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesStorage.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesValuesSegment.cs
  src/Sparrow/Json/JsonOperationContext.cs
  test/SlowTests/Server/Replication/TimeSeriesReplicationTests.cs
Labels: v5.0

#9586 RavenDB-13903: Prevent from query operations (delete and patch) from …
  src/Raven.Server/Documents/Handlers/QueriesHandler.cs
  src/Raven.Server/Documents/Operations/Operations.cs
Labels: v4.2

#9590 RavenDB-13917 RavenTestDriver.GetDocumentStore fails if called from ctor
  src/Raven.TestDriver/RavenTestDriver.cs
Labels: v4.2

#9593 4.1 to 4.2 merge
  src/Raven.Client/Documents/Subscriptions/SubscriptionBatch.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/IndexFacetedReadOperation.cs
  test/SlowTests/ExtensionPoints/ExtensionPointsTests.cs
  test/SlowTests/Issues/RavenDB_13762.cs
Labels: v4.2

#9594 RDBCL-727 fix test
  test/SlowTests/ExtensionPoints/ExtensionPointsTests.cs
Labels: v4.2

#9596 RavenDB-13926 Change the backup ownership to the non primary node of …
  src/Raven.Client/Documents/Operations/Backups/PeriodicBackupConfiguration.cs
  src/Raven.Client/Documents/Operations/ETL/EtlConfiguration.cs
  src/Raven.Client/Documents/Operations/Replication/ExternalReplicationBase.cs
  src/Raven.Client/Documents/Subscriptions/SubscriptionState.cs
  src/Raven.Client/ServerWide/DatabaseTopology.cs
  src/Raven.Server/Web/System/TcpConnectionInfoHandler.cs
Labels: v4.2

#9600 RDBC-326 added System.Text.RegularExpressions to known server-side assemblies
  src/Raven.Client/Documents/Indexes/ExpressionStringBuilder.cs
  test/SlowTests/Issues/RDBC_326.cs
Labels: v4.2

#9599 RavenDB-13906: OnAfterSaveChanges not firing after Patch
  src/Raven.Client/Documents/Session/Operations/BatchOperation.cs
  test/FastTests/Issues/RavenDB_13906.cs
Labels: v4.2

#9606 RavenDB-13889 Demote / Promote buttons should be shown only for clust…
  src/Raven.Studio/typescript/common/shell/accessManager.ts
  src/Raven.Studio/typescript/models/database/cluster/clusterNode.ts
Labels: v4.1

#9604 RavenDB-13935 Error when loading Ongoing Tasks View
  src/Raven.Studio/typescript/viewmodels/database/tasks/ongoingTasks.ts
Labels: v4.2

#9605 RavenDB-13936 Nodes can't agree on index/term when log divergence occur
  src/Raven.Server/Rachis/Follower.cs
  test/RachisTests/ElectionTests.cs
  test/Tests.Infrastructure/RachisConsensusTestBase.cs
Labels: v4.2

#9611 RavenDB-10598 removed obsoletes
  src/Raven.Client/Documents/Changes/ChangeNotification.cs
  src/Raven.Client/Documents/Changes/DatabaseChanges.cs
  src/Raven.Client/Documents/Changes/IDatabaseChanges.cs
  src/Raven.Client/Documents/Commands/Batches/BatchCommand.cs
  src/Raven.Client/Documents/Conventions/DocumentConventions.cs
  src/Raven.Client/Documents/Indexes/AbstractMultiMapIndexCreationTask.cs
  src/Raven.Client/Documents/Indexes/IndexDefinition.cs
  src/Raven.Client/Documents/Indexes/IndexDefinitionBuilder.cs
  src/Raven.Client/Documents/Indexes/IndexPrettyPrinter.cs
  src/Raven.Client/Documents/Indexes/IndexPrettyPrinterEqualityComparer.cs
  src/Raven.Client/Documents/Operations/Configuration/ClientConfiguration.cs
  src/Raven.Client/Documents/Operations/ConnectionStrings/PutConnectionStringOperation.cs
  src/Raven.Client/Documents/Operations/ConnectionStrings/RemoveConnectionStringOperation.cs
  src/Raven.Client/Documents/Operations/ETL/EtlConfiguration.cs
  src/Raven.Client/Documents/Queries/QueryResult.cs
  src/Raven.Client/Documents/Session/DocumentsChanges.cs
  src/Raven.Client/Documents/Session/EntityToBlittable.cs
  src/Raven.Client/Documents/Session/Operations/QueryOperation.cs
  src/Raven.Client/Documents/Session/Operations/SessionOperationExecutor.cs
  src/Raven.Client/Documents/Session/QueryStatistics.cs
  src/Raven.Client/Documents/Smuggler/DatabaseSmugglerImportOptions.cs
  src/Raven.Client/Documents/Smuggler/DatabaseSmugglerOptions.cs
  src/Raven.Client/Documents/Subscriptions/SubscriptionWorkerOptions.cs
  src/Raven.Client/Http/RequestExecutor.cs
  src/Raven.Client/ServerWide/Operations/Certificates/ReplaceClusterCertificateOperation.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  src/Raven.Server/Smuggler/Documents/CsvStreamSource.cs
  src/Raven.Server/Smuggler/Documents/Data/DatabaseSmugglerOptionsServerSide.cs
  src/Raven.Server/Smuggler/Documents/Data/ISmugglerSource.cs
  src/Raven.Server/Smuggler/Documents/DatabaseSource.cs
  src/Raven.Server/Smuggler/Documents/StreamSource.cs
  test/FastTests/Client/Documents/BasicDocuments.cs
  test/FastTests/Issues/RavenDB_9875.cs
  test/SlowTests/Bugs/MultiMap/SimpleMultiMap.cs
  test/SlowTests/Issues/RavenDB-5686.cs
  test/SlowTests/Issues/RavenDB_13457.cs
  test/SlowTests/Issues/RavenDB_3365.cs
  test/SlowTests/Issues/RavenDB_3864.cs
  test/SlowTests/Issues/RavenDB_483.cs
  test/SlowTests/MailingList/Andrew.cs
  test/SlowTests/MailingList/IndexWithWhere.cs
  test/SlowTests/MailingList/IndexesIgnoreNewtonsoftJsonPropertyAttributes.cs
  test/SlowTests/MailingList/Joel.cs
  test/SlowTests/Server/Documents/Notifications/ChangesTests.cs
  test/SlowTests/Tests/Indexes/CreateIndexesWithCasting.cs
  test/SlowTests/Tests/Indexes/LinqIndexesFromClient.cs
  test/SlowTests/Tests/Linq/CanCallLastOnArray.cs
Labels: v5.0

#9617 4.1 to 4.2 merge
  src/Voron/Data/BTrees/Tree.cs
  src/Voron/Data/BTrees/TreeCursorHandler.cs
  src/Voron/Data/Tables/Table.cs
  test/SlowTests/Data/RavenDB-13937.ravendbdump
  test/SlowTests/Issues/RavenDB-13937.cs
  test/SlowTests/SlowTests.csproj
Labels: v4.2

#9618 RavenDB-13957 "Backup Now" button for server wide backups should be v…
  src/Raven.Studio/typescript/models/database/tasks/ongoingTaskBackupListModel.ts
  src/Raven.Studio/wwwroot/App/views/database/tasks/ongoingTasks.html
Labels: v4.2

#9621 RavenDB-13789 Fix the Create Database View + Added Validation
  src/Raven.Studio/typescript/commands/resources/getCloudBackupCredentialsFromLinkCommand.ts
  src/Raven.Studio/typescript/models/resources/creation/databaseCreationModel.ts
  src/Raven.Studio/wwwroot/App/views/resources/createDatabase.html
Labels: v4.2

#9623 RavenDB-13077 removed SNMP warning after license activation
  src/Raven.Server/Commercial/LicenseManager.cs
  src/Raven.Server/Monitoring/Snmp/SnmpHandler.cs
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
  src/Raven.Server/NotificationCenter/Notifications/Details/LicenseLimitWarning.cs
Labels: v4.2

#9624 RavenDB-13954 End poing for encryption buffers usage added and in low memory free buffers
  src/Raven.Server/Documents/Handlers/Debugging/TransactionDebugHandler.cs
  src/Voron/Debugging/DetailedStorageReport.cs
  src/Voron/Debugging/StorageReportGenerator.cs
  src/Voron/Impl/EncryptionBuffersPool.cs
  src/Voron/StorageEnvironment.cs
Labels: v4.2

#9628 4.2 to 5.0 merge
  src/Raven.Server/Commercial/LicenseManager.cs
  src/Raven.Server/Documents/Handlers/Debugging/TransactionDebugHandler.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.10/ServerStorageDiskRemainingSpace.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.10/ServerStorageDiskRemainingSpacePercentage.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.10/ServerStorageTotalSize.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.10/ServerStorageUsedSize.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.6/ServerLowMemoryFlag.cs
  src/Raven.Server/Monitoring/Snmp/SnmpHandler.cs
  src/Raven.Server/Monitoring/Snmp/SnmpOids.cs
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
  src/Raven.Server/NotificationCenter/Notifications/Details/LicenseLimitWarning.cs
  src/Raven.Server/Rachis/CandidateAmbassador.cs
  src/Raven.Server/Rachis/Elector.cs
  src/Raven.Server/Rachis/Follower.cs
  src/Raven.Server/Rachis/FollowerAmbassador.cs
  src/Raven.Server/Rachis/Leader.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterObserver.cs
  src/Raven.Server/ServerWide/RawDatabaseRecord.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Web/System/BackupDatabaseHandler.cs
  src/Raven.Studio/typescript/commands/resources/getCloudBackupCredentialsFromLinkCommand.ts
  src/Raven.Studio/typescript/commands/resources/getCloudCredentialsFromLinkCommand.ts
  src/Raven.Studio/typescript/common/shell/accessManager.ts
  src/Raven.Studio/typescript/models/database/cluster/clusterNode.ts
  src/Raven.Studio/typescript/models/database/documents/documentMetadata.ts
  src/Raven.Studio/typescript/models/database/tasks/ongoingTaskBackupListModel.ts
  src/Raven.Studio/typescript/models/resources/creation/cloudBackupCredentials.ts
  src/Raven.Studio/typescript/models/resources/creation/databaseCreationModel.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/ongoingTasks.ts
  src/Raven.Studio/typescript/viewmodels/resources/createDatabase.ts
  src/Raven.Studio/typings/_studio/dto.d.ts
  src/Raven.Studio/wwwroot/App/views/database/tasks/ongoingTasks.html
  src/Raven.Studio/wwwroot/App/views/resources/createDatabase.html
  src/Voron/Data/BTrees/Tree.cs
  src/Voron/Data/BTrees/TreeCursorHandler.cs
  src/Voron/Data/Tables/NewPageAllocator.cs
  src/Voron/Data/Tables/Table.cs
  src/Voron/Debugging/DetailedStorageReport.cs
  src/Voron/Debugging/StorageReportGenerator.cs
  src/Voron/Impl/EncryptionBuffersPool.cs
  src/Voron/StorageEnvironment.cs
  test/RachisTests/ElectionTests.cs
  test/SlowTests/Data/RavenDB-13937.ravendbdump
  test/SlowTests/Issues/EncryptedDatabaseGroup.cs
  test/SlowTests/Issues/RavenDB-13937.cs
  test/SlowTests/SlowTests.csproj
  test/Tests.Infrastructure/RachisConsensusTestBase.cs
  tools/TypingsGenerator/Program.cs
Labels: v5.0

#9630 RavenDB-13968 Styling regression - unit for number of docs in collection
  src/Raven.Studio/wwwroot/App/views/resources/databases.html
  src/Raven.Studio/wwwroot/App/views/resources/deleteDatabaseConfirm.html
  src/Raven.Studio/wwwroot/Content/css/main-menu.less
Labels: v4.2

#9629 RavenDB-13966 RavenDB Setup Wizard missing scroll bar on last stable …
  src/Raven.Studio/wwwroot/Content/css/basic-layout.less
Labels: v4.2

#9615 RavenDB-12480 when encountering socket exception we want to get rid of the HttpClient so new one will be created next time
  src/Raven.Client/Http/RequestExecutor.cs
Labels: v4.2

#9631 RavenDB-13929 Create server-wide-backup icon for Database-Group-Topol…
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.eot
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.svg
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.ttf
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.woff
  src/Raven.Studio/wwwroot/Content/css/icons.less
Labels: v4.2

#9626 RavenDB-13963 Specific document with attachment insertion pattern cau…
  src/Raven.Server/Documents/Replication/ReplicationDocumentSender.cs
  test/SlowTests/Client/Attachments/AttachmentsReplication.cs
Labels: v4.2

#9634 RDBC-325 RequestExecutor.ExecuteAsync StopWatch created, but never …
  src/Raven.Client/Http/RequestExecutor.cs
Labels: v4.2

#9635 4.2 to 5.0 merge
  src/Raven.Client/Documents/Operations/Revisions/RevertResult.cs
  src/Raven.Client/Exceptions/Database/DatabaseIdleException.cs
  src/Raven.Client/Http/NodeSelector.cs
  src/Raven.Client/Http/RavenCommand.cs
  src/Raven.Client/Http/RequestExecutor.cs
  src/Raven.Client/ServerWide/Commands/GetTcpInfoCommand.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/DocumentFlags.cs
  src/Raven.Server/Documents/DocumentPutAction.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Handlers/RevisionsHandler.cs
  src/Raven.Server/Documents/Operations/Operations.cs
  src/Raven.Server/Documents/Replication/ReplicationDocumentSender.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  src/Raven.Server/Routing/RouteInformation.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Utils/ReplicationUtils.cs
  src/Raven.Studio/wwwroot/App/views/resources/databases.html
  src/Raven.Studio/wwwroot/App/views/resources/deleteDatabaseConfirm.html
  src/Raven.Studio/wwwroot/Content/css/basic-layout.less
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.eot
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.svg
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.ttf
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.woff
  src/Raven.Studio/wwwroot/Content/css/icons.less
  src/Raven.Studio/wwwroot/Content/css/main-menu.less
  test/FastTests/Issues/RavenDB-6250.cs
  test/FastTests/Server/Documents/Revisions/RevisionsTests.cs
  test/RachisTests/SubscriptionsFailover.cs
  test/SlowTests/Client/Attachments/AttachmentsReplication.cs
  test/SlowTests/Issues/RavenDB_13796.cs
  test/SlowTests/Server/Documents/Revisions/RevisionsReplication.cs
  test/SlowTests/Server/Replication/ExternalReplicationTests.cs
Labels: v5.0

#9636 RavenDB-13960 Passing the actual value to ArgumentOutOfRangeException…
  src/Sparrow/Json/ArenaMemoryAllocator.cs
  src/Sparrow/Json/BlittableJsonReaderObject.cs
  src/Sparrow/Json/BlittableJsonTextWriter.cs
  src/Sparrow/Json/JsonOperationContext.cs
  src/Sparrow/Json/LazyStringValue.cs
  src/Sparrow/StringSegment.cs
Labels: v4.2

#9637 RDBC-312 In abstractDocumentQuery.WhereLessThanOrEqual() and Abstract…
  src/Raven.Client/Documents/Session/AbstractDocumentQuery.cs
Labels: v4.2

#9638 RDBC-322 in RequestExecutor.FirstTopologyUpdate check for 'initialUrl…
  src/Raven.Client/Http/RequestExecutor.cs
Labels: v4.2

#9639 RavenDB-13979 Making sure we add type of Where clause to RootTypes if…
  src/Raven.Client/Documents/Linq/RavenQueryProviderProcessor.cs
  test/SlowTests/Issues/RavenDB_13979.cs
Labels: v4.2
