Repository ravendb/ravendb, pull requests merged in 2019-12, with the labels that each got.

#9924 4.2 to 5.0 merge
  bench/BulkInsert.Benchmark/BulkInsert.Benchmark.csproj
  bench/Indexing.Benchmark/Indexing.Benchmark.csproj
  bench/Micro.Benchmark/Benchmarks/Hardware/Compare.cs
  bench/Micro.Benchmark/Benchmarks/Hardware/Diff.cs
  bench/Micro.Benchmark/Benchmarks/Hardware/Prefetch.cs
  bench/Micro.Benchmark/Benchmarks/Hardware/Prefetch2.cs
  bench/Micro.Benchmark/Benchmarks/Hardware/Search.cs
  bench/Micro.Benchmark/Benchmarks/LZ4/LZ4Benchmark.cs
  bench/Micro.Benchmark/Benchmarks/PageLocator/PlRandomRead.cs
  bench/Micro.Benchmark/Benchmarks/PageLocator/PlRandomWrite.cs
  bench/Micro.Benchmark/Benchmarks/Sorting/Sorting.cs
  bench/Micro.Benchmark/Micro.Benchmark.csproj
  bench/Regression.Benchmark/Regression.Benchmark.csproj
  bench/SubscriptionFailover.Benchmark/SubscriptionFailover.Benchmark.csproj
  bench/Subscriptions.Benchmark/Subscriptions.Benchmark.csproj
  bench/Voron.Benchmark/StorageBenchmark.cs
  bench/Voron.Benchmark/Voron.Benchmark.csproj
  src/Raven.Client/Raven.Client.csproj
  src/Raven.Embedded/ServerOptions.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Studio/Raven.Studio.csproj
  test/BenchmarkTests/BenchmarkTests.csproj
  test/EmbeddedTests/EmbeddedTests.csproj
  test/FastTests/FastTests.csproj
  test/InterversionTests/InterversionTests.csproj
  test/RachisTests/RachisTests.csproj
  test/SlowTests/SlowTests.csproj
  test/StressTests/StressTests.csproj
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
  test/Tryouts/Tryouts.csproj
  tools/Raven.Debug/Raven.Debug.csproj
  tools/Raven.Migrator/Raven.Migrator.csproj
  tools/TypingsGenerator/TypingsGenerator.csproj
  tools/Voron.Recovery/Voron.Recovery.csproj
  tools/rvn/rvn.csproj
Labels: v5.0

#9917 RavenDB-14309 - Cannot start the server if the cluster is down
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
Labels: v4.2

#9926 Check inner exception for TaskCanceledException as well
  Raven.Database/Prefetching/PrefetchingBehavior.cs
Labels: v3.5

#9925 RavenDB-14286 - dispose the correct context of the request
  src/Raven.Client/Http/RequestExecutor.cs
Labels: v4.2

#9920 RavenDB-12648 - disable the MaxServicePointIdleTime
  src/Raven.Client/Http/RequestExecutor.cs
Labels: v4.2

#9919 RavenDB-14312 : TimeSeries : fix NRE when tag is null
  src/Raven.Server/Documents/TimeSeries/TimeSeriesStorage.cs
  test/SlowTests/Client/TimeSeries/RavenDB-14312.cs
Labels: v5.0

#9930 Revert of RavenDB-14094
  src/Raven.Server/ServerWide/Context/TransactionOperationContext.cs
  src/Sparrow/Json/JsonContextPoolBase.cs
  src/Sparrow/Json/JsonOperationContext.cs
  src/Sparrow/LowMemory/LowMemoryNotification.cs
  src/Sparrow/Utils/StrongReference.cs
  test/Tryouts/CodeReference.cs
Labels: v4.2

#9927 RavenDB-14319: Add timeout when there is compare exchange subscriptio…
  src/Raven.Server/Documents/Subscriptions/SubscriptionConnectionState.cs
  src/Raven.Server/Documents/TcpHandlers/SubscriptionConnection.cs
  src/Sparrow/Threading/DisposeOnce.cs
Labels: v4.2

#9931 4.2 to 5.0 merge
  RavenDB.sln.DotSettings
  src/Raven.Client/Http/RequestExecutor.cs
  src/Raven.Server/Documents/Indexes/Workers/HandleReferences.cs
  src/Raven.Server/ServerWide/Context/TransactionOperationContext.cs
  src/Sparrow/Json/JsonContextPoolBase.cs
  src/Sparrow/Json/JsonOperationContext.cs
  src/Sparrow/LowMemory/LowMemoryNotification.cs
  src/Sparrow/Utils/StrongReference.cs
  test/SlowTests/Issues/RavenDB-14323.cs
  test/Tryouts/CodeReference.cs
Labels: v5.0

#9916 RavenDB-14254 Handling a conflict should take into account the unused…
  src/Raven.Server/Documents/ConflictsStorage.cs
  src/Raven.Server/ServerWide/Context/DocumentsOperationContext.cs
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
Labels: v4.2

#9935 RavenDB-14326 / RavenDB-14220 We must not keep reduce outputs as obje…
  src/Raven.Server/Documents/Indexes/MapReduce/OutputToCollection/OutputReduceIndexWriteOperation.cs
  src/Raven.Server/Documents/Indexes/MapReduce/OutputToCollection/OutputReduceToCollectionCommand.cs
Labels: v4.2

#9938 RDBC-347 added xml docs to the NuGet
  src/Directory.Build.props
  src/Raven.Client/Raven.Client.csproj
  src/Sparrow/Sparrow.csproj
Labels: v4.2

#9937 4.2 to 5.0 merge
  bench/Micro.Benchmark/Micro.Benchmark.csproj
  bench/Voron.Benchmark/Voron.Benchmark.csproj
  build.ps1
  scripts/Copy-FileHash.ps1
  scripts/Get-DestinationFilePath.ps1
  scripts/package.ps1
  src/Raven.Client/Documents/Subscriptions/SubscriptionWorker.cs
  src/Raven.Client/Documents/Subscriptions/SubscriptionWorkerOptions.cs
  src/Raven.Client/Exceptions/Documents/Subscriptions/SubscriptionDoesNotBelongToNodeException.cs
  src/Raven.Client/Raven.Client.csproj
  src/Raven.Server/Documents/ConflictsStorage.cs
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/Indexes/MapReduce/OutputToCollection/OutputReduceIndexWriteOperation.cs
  src/Raven.Server/Documents/Indexes/MapReduce/OutputToCollection/OutputReduceToCollectionCommand.cs
  src/Raven.Server/Documents/Indexes/Static/StaticIndexBase.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
  src/Raven.Server/Documents/Replication/ReplicationItems/ReplicationBatchItem.cs
  src/Raven.Server/Documents/Subscriptions/SubscriptionConnectionState.cs
  src/Raven.Server/Documents/Subscriptions/SubscriptionStorage.cs
  src/Raven.Server/Documents/TcpHandlers/SubscriptionConnection.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Server/Routing/RouteInformation.cs
  src/Raven.Server/ServerWide/Context/DocumentsOperationContext.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Web/System/TcpConnectionInfoHandler.cs
  src/Sparrow/Sparrow.csproj
  src/Sparrow/Threading/DisposeOnce.cs
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
  test/RachisTests/SubscriptionFailoverWIthWaitingChains.cs
  test/SlowTests/Issues/RavenDB_14292.cs
  test/SlowTests/SlowTests.csproj
  test/StressTests/Client/Attachments/AttachmentsStreamStressFromSlow.cs
  test/StressTests/Server/Documents/PeriodicBackup/ServerWideBackupStress.cs
  test/Tryouts/Tryouts.csproj
  tools/Raven.Debug/Raven.Debug.csproj
  tools/Raven.Migrator/Raven.Migrator.csproj
  tools/Voron.Recovery/Voron.Recovery.csproj
  tools/rvn/rvn.csproj
Labels: v5.0

#9943 RavenDB-14331 Add the collections count in the documents page
  src/Raven.Studio/typescript/viewmodels/shell.ts
  src/Raven.Studio/wwwroot/App/views/shell.html
Labels: v4.2

#9940 RavenDB-14083 Copying Custom Info (the RQL) from traffic watch contai…
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/alerts/etlTransformOrLoadErrorDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/performanceHint/pagingDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/performanceHint/requestLatencyDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/performanceHint/slowSqlDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/performanceHint/slowWriteDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/virtualOperations/virtualBulkInsertDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/virtualOperations/virtualDeleteByQueryDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/virtualOperations/virtualUpdateByQueryDetails.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexErrors.ts
  src/Raven.Studio/typescript/viewmodels/manage/debugAdvancedMemoryMappedFiles.ts
  src/Raven.Studio/typescript/viewmodels/manage/debugAdvancedObserverLog.ts
  src/Raven.Studio/typescript/viewmodels/manage/debugAdvancedThreadsRuntime.ts
  src/Raven.Studio/typescript/viewmodels/manage/trafficWatch.ts
Labels: v4.2

#9944 RavenDB-14327 Avoid ignoring index write errors even if inner exception is SystemException
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/IndexStorage.cs
  test/SlowTests/Issues/RavenDB_14327.cs
Labels: v4.2

#9946 RavenDB-14136 Enforce revision button should be enabled even when the…
  src/Raven.Studio/typescript/viewmodels/database/settings/revisions.ts
  src/Raven.Studio/wwwroot/App/views/database/settings/revisions.html
Labels: v4.2

#9951 RavenDB-7070 added test resource analyzer
  test/Tests.Infrastructure/TestBase.cs
  test/Tests.Infrastructure/TestResourcesAnalyzer.cs
Labels: v4.2

#9952 4.2 to 5.0 merge
  src/Directory.Build.props
  src/Raven.Client/Raven.Client.csproj
  src/Raven.Server/Documents/Handlers/StreamCsvDocumentQueryResultWriter.cs
  src/Raven.Server/Documents/Handlers/Streaming/StreamingHandler.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/IndexStorage.cs
  src/Raven.Server/Documents/Queries/Results/QueryResultRetrieverBase.cs
  src/Raven.Server/Json/BlittableJsonTraverser.cs
  src/Raven.Server/Json/BlittableJsonTraverserHelper.cs
  src/Raven.Server/Utils/IncludeUtil.cs
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/alerts/etlTransformOrLoadErrorDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/performanceHint/pagingDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/performanceHint/requestLatencyDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/performanceHint/slowSqlDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/performanceHint/slowWriteDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/virtualOperations/virtualBulkInsertDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/virtualOperations/virtualDeleteByQueryDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/virtualOperations/virtualUpdateByQueryDetails.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexErrors.ts
  src/Raven.Studio/typescript/viewmodels/database/settings/revisions.ts
  src/Raven.Studio/typescript/viewmodels/manage/debugAdvancedMemoryMappedFiles.ts
  src/Raven.Studio/typescript/viewmodels/manage/debugAdvancedObserverLog.ts
  src/Raven.Studio/typescript/viewmodels/manage/debugAdvancedThreadsRuntime.ts
  src/Raven.Studio/typescript/viewmodels/manage/trafficWatch.ts
  src/Raven.Studio/typescript/viewmodels/shell.ts
  src/Raven.Studio/wwwroot/App/views/database/settings/revisions.html
  src/Raven.Studio/wwwroot/App/views/manage/adminLogs.html
  src/Raven.Studio/wwwroot/App/views/manage/trafficWatch.html
  src/Raven.Studio/wwwroot/App/views/shell.html
  src/Raven.Studio/wwwroot/Content/css/pages/traffic-watch.less
  src/Raven.Studio/wwwroot/Content/css/styles-common.less
  src/Sparrow/Json/LazyStringValue.cs
  src/Sparrow/Sparrow.csproj
  test/FastTests/Server/Documents/Indexing/Lucene/LazyStringValueReaderTests.cs
  test/SlowTests/Cluster/ClusterMaintenanceTest.cs
  test/SlowTests/Issues/RavenDB-14315.cs
  test/SlowTests/Issues/RavenDB_14327.cs
  test/Tests.Infrastructure/TestBase.cs
  test/Tests.Infrastructure/TestResourcesAnalyzer.cs
Labels: v5.0

#9942 RavenDB-14334 - start the indexes concurrently
  src/Raven.Server/Documents/Indexes/IndexStore.cs
Labels: v4.2

#9953 RavenDB-14351 - change the license ratio to double
  src/Raven.Server/Commercial/LicenseManager.cs
  src/Raven.Server/Commercial/LicenseStatus.cs
Labels: v4.2

#9957 RavenDB-14350 Create icons for Reduce-Results-Output
  src/Raven.Studio/wwwroot/App/views/database/indexes/editIndex.html
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.eot
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.svg
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.ttf
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.woff
  src/Raven.Studio/wwwroot/Content/css/icons.less
Labels: v4.2

#9956 RavenDB-14363 we also need to take into account the IOrderedQueryable when considering a root type
  src/Raven.Client/Documents/Linq/RavenQueryProviderProcessor.cs
  test/SlowTests/Issues/RavenDB_14363.cs
Labels: v4.2

#9958 RavenDB-14368 Fixing incorrect usage of table's PK index iterator. Le…
  src/Raven.Server/Commercial/LicenseManager.cs
  src/Raven.Server/Documents/Handlers/Debugging/ServerWideDebugInfoPackageHandler.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
Labels: v4.2

#9865 RavenDB-13902: vfork, re-PRing
  libs/librvnpal/librvnpal.arm.32.so
  libs/librvnpal/librvnpal.arm.64.so
  libs/librvnpal/librvnpal.linux.x64.so
  libs/librvnpal/librvnpal.mac.x64.dylib
  libs/librvnpal/librvnpal.win.x64.dll
  libs/librvnpal/librvnpal.win.x86.dll
  libs/librvnpal/librvnpal.win7.x64.dll
  libs/librvnpal/librvnpal.win7.x86.dll
  src/Raven.Pal/build-all-posix.sh
  src/Raven.Pal/inc/internal_posix.h
  src/Raven.Pal/inc/rvn.h
  src/Raven.Pal/inc/status_codes.h
  src/Raven.Pal/pal.ver
  src/Raven.Pal/src/posix/linuxonly.c
  src/Raven.Pal/src/posix/maconly.c
  src/Raven.Pal/src/posix/spawn.c
  src/Raven.Pal/src/rvngetpalver.c
  src/Raven.Pal/src/win/spawn.c
  src/Raven.Server/Program.cs
  src/Raven.Server/RavenServer.cs
  src/Raven.Server/Utils/Cli/BrowserHelper.cs
  src/Raven.Server/Utils/Cli/RavenCli.cs
  src/Raven.Server/Utils/Cpu/CpuHelper.cs
  src/Raven.Server/Utils/Cpu/CpuUsageCalculator.cs
  src/Raven.Server/Utils/Cpu/CpuUsageExtensionPoint.cs
  src/Sparrow.Server/Platform/Pal.cs
  src/Sparrow.Server/Platform/PalFlags.cs
  src/Sparrow.Server/Platform/RavenProcess.cs
  src/Voron/Debugging/DebugStuff.cs
  test/SlowTests/ExtensionPoints/RavenDB_12161.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v4.2

#9962 RavenDB-14317 Add NGram Analyzer & all indexing configuration options
  src/Raven.Studio/typescript/models/database/index/configurationItem.ts
  src/Raven.Studio/typescript/models/database/index/indexFieldOptions.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/editIndex.ts
  src/Raven.Studio/wwwroot/App/views/database/indexes/editIndex.html
Labels: v4.2

#9966 RavenDB-14235 Added missing Theory attribute so tests will be run
  test/SlowTests/Issues/RavenDB_14235.cs
Labels: v4.2

#9967 RavenDB-14350 Create icons for Reduce-Results-Output
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.eot
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.svg
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.ttf
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.woff
Labels: v4.2

#9960 RavenDB-14328 Loading a document including a reference nested in a di…
  src/Raven.Client/Extensions/ExpressionExtensions.cs
  test/SlowTests/Issues/RavenDB-14328.cs
Labels: v4.2

#9969 RavenDB-13078 / RavenDB-14322 Making sure when we parse a document id…
  src/Raven.Server/Documents/TimeSeries/TimeSeriesValuesSegment.cs
  src/Sparrow/Json/JsonOperationContext.cs
  src/Sparrow/Json/Parsing/JsonParserState.cs
  test/FastTests/Client/Indexing/TimeSeries/BasicTimeSeriesIndexes.cs
Labels: v5.0

#9939 RavenDB-14334 changed timeout
  src/Raven.Server/Documents/Indexes/IndexStore.cs
Labels: v4.2

#9970 4.2 to 5.0 merge
  src/Raven.Client/Documents/Commands/NextIdentityForCommand.cs
  src/Raven.Client/Documents/Conventions/DocumentConventions.cs
  src/Raven.Client/Documents/Linq/RavenQueryProviderProcessor.cs
  src/Raven.Client/Documents/Operations/Backups/PeriodicBackupStatus.cs
  src/Raven.Client/Extensions/ExpressionExtensions.cs
  src/Raven.Client/Http/RavenCommand.cs
  src/Raven.Client/Http/RequestExecutor.cs
  src/Raven.Server/Commercial/LicenseManager.cs
  src/Raven.Server/Commercial/LicenseStatus.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/ETL/EtlLoader.cs
  src/Raven.Server/Documents/ETL/EtlProcess.cs
  src/Raven.Server/Documents/ETL/Providers/Raven/RavenEtl.cs
  src/Raven.Server/Documents/Handlers/Debugging/ServerWideDebugInfoPackageHandler.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  src/Raven.Server/Documents/PeriodicBackup/Azure/RavenAzureClient.cs
  src/Raven.Server/Documents/PeriodicBackup/BackupTask.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
  src/Raven.Server/Documents/PeriodicBackup/RavenStorageClient.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/AzureRestorePoints.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreFromAzure.cs
  src/Raven.Server/Documents/PeriodicBackup/Retention/AzureRetentionPolicyRunner.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/Smuggler/Documents/DatabaseSource.cs
  src/Raven.Server/Web/Studio/StudioTasksHandler.cs
  src/Raven.Studio/typescript/models/database/index/configurationItem.ts
  src/Raven.Studio/typescript/models/database/index/indexFieldOptions.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/editIndex.ts
  src/Raven.Studio/wwwroot/App/views/database/indexes/editIndex.html
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.eot
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.svg
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.ttf
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.woff
  src/Raven.Studio/wwwroot/Content/css/icons.less
  test/SlowTests/Cluster/ClusterOperationTests.cs
  test/SlowTests/Issues/RavenDB-14328.cs
  test/SlowTests/Issues/RavenDB_14235.cs
  test/SlowTests/Issues/RavenDB_14363.cs
  test/SlowTests/Server/Documents/ETL/Raven/RavenDB_6257.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Azure.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Restore/RestoreFromAzure.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Retention.cs
  test/SlowTests/Server/Replication/PullReplicationTests.cs
  test/SlowTests/Server/Replication/ReplicationCleanTombstones.cs
  test/SlowTests/Server/Replication/ReplicationConflictsTests.cs
  test/SlowTests/Server/Replication/ReplicationResolveConflictsOnConfigurationChange.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
  test/Tests.Infrastructure/RavenTestBase.cs
  test/Tests.Infrastructure/TestBase.cs
  test/Tests.Infrastructure/TestResourcesAnalyzer.cs
Labels: v5.0

#9971 RDBCL-1125 we need to initialize SNMP Engine always with greater engine boots
  libs/Lextm.SharpSnmpLib.Engine.11.3.100.nupkg
  libs/Lextm.SharpSnmpLib.Engine.11.3.101.nupkg
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
  src/Raven.Server/Raven.Server.csproj
Labels: v4.2

#9968 RavenDB-14325 Tombstone cleaner should take into account external rep…
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  test/FastTests/Server/Replication/ReplicationTestBase.cs
  test/SlowTests/Server/Replication/ReplicationCleanTombstones.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
Labels: v4.2

#9973 RavenDB-14364 options and filterMetadataProperty should not be static
  src/Raven.Server/Smuggler/Documents/StreamDestination.cs
Labels: v4.2

#9974 4.2 to 5.0 merge
  libs/Lextm.SharpSnmpLib.Engine.11.3.100.nupkg
  libs/Lextm.SharpSnmpLib.Engine.11.3.101.nupkg
  src/Raven.Client/Documents/Indexes/IndexFailureInformation.cs
  src/Raven.Client/Documents/Indexes/IndexStats.cs
  src/Raven.Server/Commercial/LicenseManager.cs
  src/Raven.Server/Config/Categories/MemoryConfiguration.cs
  src/Raven.Server/Documents/Document.cs
  src/Raven.Server/Documents/Handlers/Debugging/MemoryDebugHandler.cs
  src/Raven.Server/Documents/IMetadataModifier.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/IndexStorage.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  src/Raven.Server/Documents/Indexes/IndexingRunStats.cs
  src/Raven.Server/Documents/Indexes/IndexingStatsAggregator.cs
  src/Raven.Server/Documents/Indexes/MapReduce/OutputToCollection/OutputReduceToCollectionActions.cs
  src/Raven.Server/Documents/Indexes/MapReduce/OutputToCollection/OutputReferencesPattern.cs
  src/Raven.Server/Documents/Indexes/Workers/HandleReferences.cs
  src/Raven.Server/Documents/Indexes/Workers/MapItems.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/Documents/TcpHandlers/SubscriptionConnection.cs
  src/Raven.Server/Documents/TransactionOperationsMerger.cs
  src/Raven.Server/Json/BlittableJsonTextWriterExtensions.cs
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
  src/Raven.Server/NotificationCenter/OutOfMemoryNotifications.cs
  src/Raven.Server/Program.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Server/RavenServerStartup.cs
  src/Raven.Server/ServerWide/Commands/UpdateLicenseLimitsCommand.cs
  src/Raven.Server/Smuggler/Documents/Data/SmugglerMetadataModifier.cs
  src/Raven.Server/Smuggler/Documents/StreamDestination.cs
  src/Raven.Server/Utils/Cli/RavenCli.cs
  src/Raven.Studio/typescript/models/database/index/index.ts
  src/Raven.Studio/typescript/models/database/index/indexDefinition.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/deleteIndexesConfirm.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/editIndex.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexes.ts
  src/Raven.Studio/wwwroot/App/views/database/indexes/deleteIndexesConfirm.html
  src/Raven.Studio/wwwroot/App/views/database/indexes/editIndex.html
  src/Raven.Studio/wwwroot/App/views/database/indexes/indexes.html
  src/Sparrow.Server/LowMemory/MemoryInformation.cs
  src/Sparrow.Server/Utils/StrongReference.cs
  src/Sparrow/Json/BlittableJsonReaderObject.cs
  src/Sparrow/LowMemory/HighDirtyMemoryException.cs
  src/Sparrow/LowMemory/LowMemoryException.cs
  src/Sparrow/LowMemory/LowMemoryNotification.cs
  src/Sparrow/LowMemory/MemoryInfoResult.cs
  src/Voron/Impl/Scratch/ScratchBufferFile.cs
  test/FastTests/Server/Documents/Indexing/Static/BasicStaticMapIndexing.cs
  test/FastTests/Server/Replication/ReplicationTestBase.cs
  test/SlowTests/Issues/RavenDB-14323.cs
  test/SlowTests/Issues/RavenDB_13951.cs
  test/SlowTests/Server/Replication/ReplicationCleanTombstones.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
Labels: v5.0

#9975 RavenDB-7070 updated packages
  src/Raven.Server/Raven.Server.csproj
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
  tools/Raven.Migrator/Raven.Migrator.csproj
Labels: v4.2

#9979 4.2 to 5.0 merge
  src/Raven.Server/Raven.Server.csproj
  test/SlowTests/Issues/RavenDB_13951.cs
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
  tools/Raven.Migrator/Raven.Migrator.csproj
Labels: v5.0

#9981 RavenDB-14329 MapBatchSize isn't respected when we have LoadDocument
  src/Raven.Studio/typescript/models/database/index/index.ts
  src/Raven.Studio/typescript/models/database/stats/indexStatistics.ts
  src/Raven.Studio/wwwroot/App/views/database/status/statistics.html
Labels: v4.2

#9982 RavenDB-14352 Add support to case sensitive collations in SQL databas…
  src/Raven.Server/SqlMigration/MsSQL/MsSqlDatabaseMigrator.Schema.cs
  src/Raven.Server/SqlMigration/MySQL/MySqlDatabaseMigrator.Schema.cs
  src/Raven.Server/SqlMigration/NpgSQL/NpgSqlDatabaseMigrator.Schema.cs
Labels: v4.2

#9984 RavenDB-14398 Database name missing for server wide backup dialog and…
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
  src/Raven.Studio/typescript/common/notifications/models/virtualBulkInsert.ts
Labels: v4.2

#9948 RavenDB-14400 added debug messages
  test/SlowTests/Server/Documents/ETL/EtlTestBase.cs
  test/SlowTests/Server/Documents/ETL/SQL/SqlEtlTests.cs
Labels: v4.2

#9988 RavenDB-14376 Adding the same attachment doesn't show the saving popup
  src/Raven.Studio/typescript/viewmodels/database/documents/editDocumentUploader.ts
Labels: v4.2

#9987 RavenDB-14381 Allow to modify the database record from the studio
  src/Raven.Studio/typescript/commands/resources/saveDatabaseSettingsCommand.ts
  src/Raven.Studio/typescript/viewmodels/database/settings/databaseRecord.ts
  src/Raven.Studio/wwwroot/App/views/database/settings/databaseRecord.html
Labels: v4.2

#9986 RavenDB-14401 add ITestOutputHelper to RachisTests
  test/RachisTests/BasicCluster.cs
  test/RachisTests/BasicTests.cs
  test/RachisTests/CommandsTests.cs
  test/RachisTests/ElectionTests.cs
  test/RachisTests/TopologyChangesTests.cs
  test/Tests.Infrastructure/RachisConsensusTestBase.cs
Labels: v4.2

#9990 RavenDB-14400 do not wait without end for tests to complete
  test/SlowTests/Server/RecordingTransactionOperationsMergerTests.cs
Labels: v4.2

#9985 4.2 to 5.0 merge
  libs/Lextm.SharpSnmpLib.Engine.11.3.101.nupkg
  libs/Lextm.SharpSnmpLib.Engine.11.3.102.nupkg
  src/Raven.Server/Config/Categories/MonitoringConfiguration.cs
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/SqlMigration/MsSQL/MsSqlDatabaseMigrator.Schema.cs
  src/Raven.Server/SqlMigration/MySQL/MySqlDatabaseMigrator.Schema.cs
  src/Raven.Server/SqlMigration/NpgSQL/NpgSqlDatabaseMigrator.Schema.cs
  src/Raven.Studio/typescript/commands/resources/saveDatabaseSettingsCommand.ts
  src/Raven.Studio/typescript/common/notifications/models/virtualBulkInsert.ts
  src/Raven.Studio/typescript/models/database/index/index.ts
  src/Raven.Studio/typescript/models/database/index/indexDefinition.ts
  src/Raven.Studio/typescript/models/database/stats/indexStatistics.ts
  src/Raven.Studio/typescript/viewmodels/database/documents/editDocumentUploader.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/editIndex.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexes.ts
  src/Raven.Studio/typescript/viewmodels/database/settings/databaseRecord.ts
  src/Raven.Studio/wwwroot/App/views/database/indexes/editIndex.html
  src/Raven.Studio/wwwroot/App/views/database/indexes/indexes.html
  src/Raven.Studio/wwwroot/App/views/database/settings/databaseRecord.html
  src/Raven.Studio/wwwroot/App/views/database/status/statistics.html
  src/Raven.Studio/wwwroot/Content/css/pages/edit-index.less
  src/Raven.Studio/wwwroot/Content/css/pages/indexes.less
  src/Raven.Studio/wwwroot/Content/css/styles-common.less
  test/FastTests/Client/Indexing/TimeSeries/BasicTimeSeriesIndexes.cs
  test/RachisTests/BasicCluster.cs
  test/RachisTests/BasicTests.cs
  test/RachisTests/CommandsTests.cs
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
  test/RachisTests/ElectionTests.cs
  test/RachisTests/TopologyChangesTests.cs
  test/SlowTests/Server/Documents/ETL/EtlTestBase.cs
  test/SlowTests/Server/Documents/ETL/SQL/SqlEtlTests.cs
  test/SlowTests/Server/RecordingTransactionOperationsMergerTests.cs
  test/Tests.Infrastructure/RachisConsensusTestBase.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v5.0

#9991 RavenDB-13078 fixing NRE
  src/Raven.Server/Documents/DocumentPutAction.cs
Labels: v5.0

#9992 RavenDB-14403 Fixing an issue with query.ToString() on negation gener…
  src/Raven.Server/Documents/Queries/AST/StringQueryVisitor.cs
Labels: v4.2

#9993 RavenDB-14397: Fix error message string (instead of "0.25%" - 25%)
  src/Sparrow.Server/LowMemory/MemoryInformation.cs
Labels: v4.2

#9994 RavenDB-14407 SelectFields should not mutate the original query
  src/Raven.Client/Documents/Session/DocumentQuery.cs
  test/SlowTests/MailingList/FacetsAndDocQuery.cs
Labels: v4.2

#9999 RavenDB-14410 - TransactionSizeLimit is evaluated on every document indexing
  src/Raven.Server/Documents/Indexes/Index.cs
Labels: v4.2

#9998 RavenDB-14390 - When restoring a backup, user can have a read only permission to the restore folder
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreFromLocal.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
Labels: v4.2

#10000 RavenDB-14411 - Reduce the number of Is32Bit checks
  src/Raven.Server/Config/Categories/TransactionMergerConfiguration.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/MapIndexBase.cs
  src/Raven.Server/Documents/Subscriptions/SubscriptionStorage.cs
  src/Raven.Server/Documents/TcpHandlers/SubscriptionDocumentsFetcher.cs
  src/Raven.Server/Documents/TransactionOperationsMerger.cs
  src/Raven.Server/ServerWide/Context/DocumentsContextPool.cs
  src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
  src/Raven.Server/Utils/Cli/RavenCli.cs
  src/Voron/Impl/Paging/AbstractPager.cs
  src/Voron/StorageEnvironmentOptions.cs
Labels: v4.2

#10004 RavenDB-14414: add failover when copying pal file
  src/Sparrow.Server/Platform/Pal.cs
Labels: v4.2

#10005 4.2 to 5.0 merge
  CONTRIBUTING.md
  SECURITY.md
  readme.md
  src/Raven.Client/Documents/Session/DocumentQuery.cs
  src/Raven.Client/Http/NodeSelector.cs
  src/Raven.Server/Config/Categories/TransactionMergerConfiguration.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/MapIndexBase.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreFromLocal.cs
  src/Raven.Server/Documents/Queries/AST/StringQueryVisitor.cs
  src/Raven.Server/Documents/Subscriptions/SubscriptionStorage.cs
  src/Raven.Server/Documents/TcpHandlers/SubscriptionDocumentsFetcher.cs
  src/Raven.Server/Documents/TransactionOperationsMerger.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/Context/DocumentsContextPool.cs
  src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
  src/Raven.Server/Utils/Cli/RavenCli.cs
  src/Sparrow.Server/LowMemory/MemoryInformation.cs
  src/Sparrow.Server/Platform/Pal.cs
  src/Voron/Impl/Paging/AbstractPager.cs
  src/Voron/StorageEnvironmentOptions.cs
  test/RachisTests/RavenDB_14348.cs
  test/RachisTests/SubscriptionFailoverWIthWaitingChains.cs
  test/SlowTests/MailingList/FacetsAndDocQuery.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
  test/Tests.Infrastructure/RavenTestBase.cs
Labels: v5.0

#10001 RavenDB-14076: backup to path with parent directory should work
  src/Raven.Server/Documents/PeriodicBackup/Retention/LocalRetentionPolicyRunner.cs
  src/Voron/Util/Settings/PathSettingBase.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Retention.cs
  test/StressTests/Server/Documents/PeriodicBackup/Retention.cs
Labels: v4.2

#10008 RavenDB-14076: fix failing test on linux
  test/SlowTests/Server/Documents/PeriodicBackup/Retention.cs
Labels: v4.2

#10007 4.2 to 5.0 merge
  src/Raven.Client/Documents/Linq/LinqPathProvider.cs
  src/Raven.Client/Documents/Queries/QueryFieldUtil.cs
  src/Raven.Server/Config/Categories/MemoryConfiguration.cs
  src/Raven.Server/Documents/PeriodicBackup/Retention/LocalRetentionPolicyRunner.cs
  src/Raven.Server/Documents/Queries/Parser/QueryParser.cs
  src/Raven.Server/Documents/Queries/Parser/QueryScanner.cs
  src/Voron/Util/Settings/PathSettingBase.cs
  test/SlowTests/Issues/RavenDB-14361.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Retention.cs
  test/StressTests/Databases.cs
  test/StressTests/Server/Documents/PeriodicBackup/Retention.cs
Labels: v5.0

#10006 RavenDB-14098: fix failing test
  test/SlowTests/Server/Documents/PeriodicBackup/RavenDB-11139.cs
Labels: v4.2
