Repository ravendb/ravendb, pull requests merged in 2019-10, with the labels that each got.

#9728 RavenDB-14078 Fixing NRE if S3 bucket doesn't exist
  src/Raven.Server/Documents/PeriodicBackup/Restore/FileInfoDetails.cs
Labels: v4.2

#9725 RavenDB-14059 Upgrading a watcher node from 4.1 to 4.2 shouldn't throw NotSupportedException
  src/Raven.Server/Rachis/RachisConsensus.cs
Labels: v4.2

#9730 RavenDB-13938 Don't display RevisionCreated in studio
  src/Raven.Studio/typescript/viewmodels/database/documents/editDocument.ts
Labels: v4.2

#9680 RavenDB-13978 - fix a race condition where we could end up repeating the same Raven-Replication-Version
  Raven.Database/Bundles/Replication/Impl/ReplicationHiLo.cs
Labels: v2.5

#9726 RavenDB-14077
  src/Raven.Server/Documents/PeriodicBackup/BackupConfigurationHelper.cs
  src/Raven.Server/Web/Studio/DataDirectoryInfo.cs
  src/Raven.Server/Web/System/AdminServerWideBackupHandler.cs
  src/Raven.Server/Web/System/OngoingTasksHandler.cs
  test/SlowTests/Issues/RavenDB_14077.cs
Labels: v4.2

#9732 RavenDB-14052 Refactor Help Text
  src/Raven.Studio/wwwroot/App/views/database/settings/refresh.html
Labels: v4.2

#9733 RavenDB-14079 Restore from S3 doesn't work
  src/Raven.Studio/typescript/models/resources/creation/backupCredentials.ts
Labels: v4.2

#9729 RavenDB-14085 negative skip and take values should throw
  src/Raven.Server/Documents/Queries/IndexQueryServerSide.cs
  test/SlowTests/Issues/RavenDB_14085.cs
Labels: v4.2

#9736 RavenDB-13971 UI Regression
  src/Raven.Studio/wwwroot/App/views/database/query/query.html
  src/Raven.Studio/wwwroot/Content/css/basic-layout.less
Labels: v4.2

#9731 RavenDB-14082 Ensure that tests aren't failing due to randomized cont…
  test/SlowTests/Voron/RavenDB_13940.cs
Labels: v4.2

#9737 RavenDB-14067 Unable to discover SQL import schema
  src/Raven.Server/SqlMigration/MySQL/MySqlDatabaseMigrator.Schema.cs
Labels: v4.2

#9739 RavenDB-14088 not with exist should yield proper RQL
  src/Raven.Client/Documents/Session/AbstractDocumentQuery.cs
  test/SlowTests/Issues/RavenDB_14088.cs
Labels: v4.2

#9741 RavenDB-13942 Revisions Bin menu item is not highlighed
  src/Raven.Studio/typescript/common/shell/menu/collectionMenuItem.ts
Labels: v4.2

#9742 RavenDB-14087 fixed NRE when assigning numeric array to a property in patch
  src/Raven.Server/Documents/Patch/BlittableObjectInstance.cs
  test/SlowTests/Issues/RavenDB_14087.cs
Labels: v4.2

#9738 RavenDB-13885 Total RavenDB Storage in Server Dashboard
  src/Raven.Studio/wwwroot/App/views/resources/serverDashboard.html
Labels: v4.2

#9734 RavenDB-13932 fix err msg when creating ongoing-regular-backup + fix …
  src/Raven.Server/ServerWide/Commands/PeriodicBackup/UpdatePeriodicBackupCommand.cs
  src/Raven.Studio/wwwroot/App/views/database/tasks/ongoingTasks.html
  test/SlowTests/Server/Documents/PeriodicBackup/ServerWideBackup.cs
Labels: v4.2

#9743 RDBC-372 : JsonSerializationException thrown when using RawDocumentQuery<BlittableJsonReaderObject> with projection
  src/Raven.Client/Documents/Session/Operations/QueryOperation.cs
  test/SlowTests/Issues/RDBC-372.cs
Labels: v4.2

#9748 RavenDB-1234 - fix configuration description
  src/Raven.Server/Config/Categories/ReplicationConfiguration.cs
Labels: v4.2

#9749 RavenDB-14056 Disabled Migrate button On Import Data -> From SQL page
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/sqlMigrationDetails.ts
Labels: v4.2

#9750 RavenDB-14031 include tab should have an eye
  src/Raven.Studio/typescript/viewmodels/database/query/query.ts
Labels: v4.2

#9752 RavenDB-14084 added the ability to index missing fields as null, by default they are ignored
  src/Raven.Server/Config/Categories/IndexingConfiguration.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/AnonymousLuceneDocumentConverter.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/JintLuceneDocumentConverter.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/LuceneDocumentConverter.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/LuceneDocumentConverterBase.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/LuceneIndexPersistence.cs
  test/SlowTests/Issues/RavenDB_14084.cs
Labels: v4.2

#9751 RavenDB-6033 Resources dropdown selector: Add ability to go up/down w…
  src/Raven.Studio/typescript/common/shell/databaseSwitcher.ts
  src/Raven.Studio/wwwroot/App/views/shell.html
Labels: v4.2

#9754 RDBC-390 facet query should escape field name and display name if necessary
  src/Raven.Client/Documents/Session/Tokens/FacetToken.cs
  test/SlowTests/Issues/RDBC_390.cs
Labels: v4.2

#9756 RavenDB-14072 do not wrap out of memory exceptions as IndexWriteException/IndexWriterCreationException
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/IndexWriteOperation.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/LuceneIndexPersistence.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/LuceneIndexWriter.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/LuceneSuggestionIndexWriter.cs
Labels: v4.2

#9760 RavenDB-14107 Ensure that tests aren't failing due to randomized content of data
  test/SlowTests/Voron/RavenDB_13940_Encrypted.cs
Labels: v4.2

#9763 RavenDB-14102 RavenDB Studio: patch fails parsing when string literal…
  src/Raven.Server/Documents/Queries/Parser/QueryScanner.cs
  test/SlowTests/Issues/RavenDB_14102.cs
Labels: v4.2

#9764 RavenDB-7070 remove restored databases after test completion
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Restore/RestoreFromS3.cs
Labels: v4.2

#9767 RavenDB-11488 Side by side indexing for map-reduce indexes with OutputReduceToCollection.
  src/Raven.Client/Documents/Indexes/IndexDefinition.cs
  src/Raven.Client/Documents/Indexes/IndexingOperation.cs
  src/Raven.Client/ServerWide/DatabaseRecord.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  src/Raven.Server/Documents/Indexes/MapIndexBase.cs
  src/Raven.Server/Documents/Indexes/MapReduce/Auto/AutoMapReduceIndex.cs
  src/Raven.Server/Documents/Indexes/MapReduce/ReduceOutputDocumentActions.cs
  src/Raven.Server/Documents/Indexes/MapReduce/Static/MapReduceIndex.cs
  src/Raven.Server/Documents/Indexes/MapReduce/Static/MapReduceIndexDefinition.cs
  src/Raven.Server/Documents/Indexes/MapReduce/Workers/CleanupDocumentsForMapReduce.cs
  src/Raven.Server/Documents/Indexes/Persistence/DeleteReduceOutputDocumentsCommand.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/OutputReduceIndexWriteOperation.cs
  src/Raven.Server/Documents/Indexes/Static/MapIndex.cs
  src/Raven.Server/Documents/Indexes/Workers/CleanupDocuments.cs
  src/Raven.Server/Extensions/JsonSerializationExtensions.cs
  src/Raven.Server/Json/BlittableJsonTextWriterExtensions.cs
  src/Raven.Server/ServerWide/Commands/Indexes/PutIndexCommand.cs
  src/Raven.Server/ServerWide/Commands/Indexes/PutIndexesCommand.cs
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexPerformance.ts
  src/Raven.Studio/wwwroot/App/views/database/indexes/indexPerformance.html
  src/Raven.Studio/wwwroot/Content/css/pages/index-performance.less
  src/Voron/Data/BTrees/Tree.Extensions.cs
  test/FastTests/Issues/RavenDB-11781.cs
  test/SlowTests/Data/RavenDB_11488/ravendb-11488-artificial-docs-not-included.ravendbdump
  test/SlowTests/Data/RavenDB_11488/ravendb-11488.ravendb-snapshot
  test/SlowTests/Server/Documents/Indexing/MapReduce/OutputReduceToCollectionTests.cs
  test/SlowTests/SlowTests.csproj
Labels: v4.2

#9766 RDBC-391 should be able to use operations with selected node tag when disable topology updates is true
  src/Raven.Client/Http/RequestExecutor.cs
  test/SlowTests/Issues/RDBC_391.cs
Labels: v4.2

#9769 RavenDB-14122 Debug Package Info: Include subscriptions and ETLs endp…
  src/Raven.Server/Documents/ETL/Handlers/EtlHandler.cs
  src/Raven.Server/Documents/Handlers/SubscriptionsHandler.cs
  src/Raven.Server/Web/System/OngoingTasksHandler.cs
Labels: v4.2

#9768 RavenDB-14105 JS error in Studio when doing a test patch
  src/Raven.Studio/typescript/viewmodels/database/patch/patchTester.ts
Labels: v4.2

#9772 RavenDB-14124 adding allocation count to endpoint /admin/debug/memory/allocations
  src/Raven.Server/Web/System/AdminAllocationDebugHandler.cs
Labels: v4.2

#9775 RavenDB-14126 updated SNMP to 11.3.100
  libs/Lextm.SharpSnmpLib.Engine.11.3.100.nupkg
  src/Raven.Server/Raven.Server.csproj
Labels: v4.2

#9777 RavenDB-14133 Making sure that ETL process which was stopped isn't re…
  src/Raven.Server/Documents/ETL/EtlLoader.cs
  src/Raven.Server/Documents/ETL/EtlProcess.cs
Labels: v4.2

#9781 RavenDB-14114 - skip the cleanup if the current allocation is the same as after the previous one
  src/Raven.Server/Documents/Indexes/Index.cs
Labels: v4.2

#9785 RavenDB-14106 Invalid error handling when replication attempts to talk to idle database
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/RavenServerStartup.cs
  test/SlowTests/Server/Replication/ExternalReplicationTests.cs
Labels: v4.2

#9788 RavenDB-14021 fix NRE when missing cloud settings
  test/SlowTests/Server/Documents/PeriodicBackup/Restore/RestoreFromGoogleCloud.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Restore/RestoreFromS3.cs
Labels: v4.2

#9784 RavenDB-14146 - Ignore TaskCanceledException on database shutdown
  src/Raven.Server/Documents/PeriodicBackup/BackupUploader.cs
Labels: v4.2

#9795 RDBC-392 remove whitespace from nodeUrl and nodeTag when adding a node
  src/Raven.Server/Documents/Handlers/Admin/RachisAdminHandler.cs
Labels: v4.2

#9798 RavenDB-10647 AfterQueryExecuted, AfterStreamExecuted and NegateNext should return self to enable chaining
  src/Raven.Client/Documents/Session/AsyncDocumentQuery.cs
  src/Raven.Client/Documents/Session/DocumentQuery.cs
  src/Raven.Client/Documents/Session/IDocumentQueryBase.cs
Labels: v5.0

#9790 RavenDB-14153 When serializing a command let's try to simplify JSON as well
  src/Raven.Client/Documents/Session/EntityToBlittable.cs
  test/SlowTests/Issues/RavenDB_14153.cs
Labels: v4.2

#9799 4.1 to 4.2 merge
  bench/Micro.Benchmark/Micro.Benchmark.csproj
  bench/Regression.Benchmark/Regression.Benchmark.csproj
  bench/Voron.Benchmark/Voron.Benchmark.csproj
  src/Raven.Client/Raven.Client.csproj
  src/Raven.Server/Raven.Server.csproj
  src/Sparrow/Sparrow.csproj
  test/BenchmarkTests/BenchmarkTests.csproj
  test/EmbeddedTests/EmbeddedTests.csproj
  test/FastTests/FastTests.csproj
  test/InterversionTests/InterversionTests.csproj
  test/RachisTests/RachisTests.csproj
  test/SlowTests/SlowTests.csproj
  test/StressTests/StressTests.csproj
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
  test/Tryouts/Tryouts.csproj
  tools/Raven.Debug/Raven.Debug.csproj
  tools/Raven.Migrator/Raven.Migrator.csproj
  tools/rvn/rvn.csproj
Labels: v4.2

#9801 RDBC-392 added Uri.IsWellFormedUriString
  src/Raven.Server/Documents/Handlers/Admin/RachisAdminHandler.cs
Labels: v4.2

#9804 RavenDB-14161 - allow to run Azure tests in debug
  test/Tests.Infrastructure/AzureStorageEmulatorFact.cs
Labels: v4.2

#9806 RavenDB-14121 fix Retention tests init failure
  test/StressTests/Server/Documents/PeriodicBackup/Retention.cs
Labels: v4.2

#9812 RavenDB-14101 Restore operation does not set proper Processed value
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/smugglerDatabaseDetails.ts
Labels: v4.2

#9810 RDBS-52 Fixing unhandled case of leaf compression:
  src/Raven.Server/Documents/Indexes/MapReduce/ReduceMapResultsBase.cs
  src/Voron/Data/BTrees/Tree.Compressed.cs
  src/Voron/Data/Compression/CompressionResult.cs
  src/Voron/Data/Compression/LeafPageCompressor.cs
  src/Voron/Debugging/DebugStuff.cs
  test/SlowTests/Voron/LeafsCompression/RDBS_52.cs
Labels: v4.1

#9816 RavenDB-14127 skipped test
  test/SlowTests/Server/Documents/ETL/RavenDB_8866.cs
Labels: v4.2

#9813 RavenDB-14169 - add support for types in Metadata
  src/Raven.Client/Json/BlittableJsonWriter.cs
  test/SlowTests/Core/Session/Advanced.cs
Labels: v4.2

#9811 RavenDB-12062 ACME V2 breaking changes
  src/Raven.Server/Commercial/LetsEncryptClient.cs
Labels: v4.2

#9817 RavenDB-13920 - When out of disk space, don't attempt to log
  src/Sparrow/Logging/LoggingSource.cs
Labels: v4.2

#9820 RavenDB-14147: fix case when db was added to idle list without unloading
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/ServerWide/ServerStore.cs
Labels: v4.2

#9818 RavenDB-14176 we need to merge field options from all where fields when query metadata is created
  src/Raven.Server/Documents/Queries/QueryMetadata.cs
  test/SlowTests/Issues/RavenDB_14176.cs
Labels: v4.2

#9814 RavenDB-14171 restore Console.Out for Tryouts
  libs/XunitLogger.4.0.99.nupkg
  test/Tests.Infrastructure/ConsoleTestOutputHelper.cs
  test/Tests.Infrastructure/LinuxRaceConditionWorkAround.cs
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
  test/Tryouts/Program.cs
Labels: v4.2

#9823 RavenDB-14171 don't redirect streams in tests
  test/Tests.Infrastructure/LinuxRaceConditionWorkAround.cs
Labels: v4.2

#9824 RavenDB-14126
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
Labels: v4.2

#9827 RavenDB-14188 - OS info is missing the latest macOS version name
  src/Raven.Server/Commercial/OsInfoExtensions.cs
Labels: v4.2

#9828 RavenDB-14154 Add /databases/*/tcp endpoint to Debug Package Info
  src/Raven.Server/Documents/Handlers/TcpManagementHandler.cs
Labels: v4.2

#9821 RavenDB-13696 Patch should preserve the order of properties
  src/Sparrow/Json/BlittableJsonReaderObject.cs
  test/SlowTests/Issues/RavenDB_13696.cs
Labels: v4.2

#9825 RavenDB-14183
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
Labels: v4.2

#9834 RavenDB-14185 forcing newer Microsoft.Win32.Registry package
  tools/Raven.Debug/Raven.Debug.csproj
  tools/Raven.Migrator/Raven.Migrator.csproj
Labels: v4.2

#9835 4.2 to 5.0 merge
  libs/XunitLogger.4.0.99.nupkg
  src/Raven.Client/Documents/Linq/RavenQueryProviderProcessor.cs
  src/Raven.Client/Json/BlittableJsonWriter.cs
  src/Raven.Server/Commercial/LetsEncryptClient.cs
  src/Raven.Server/Commercial/OsInfoExtensions.cs
  src/Raven.Server/Dashboard/ThreadsInfo.cs
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/Handlers/Admin/RachisAdminHandler.cs
  src/Raven.Server/Documents/Handlers/SubscriptionsHandler.cs
  src/Raven.Server/Documents/Handlers/TcpManagementHandler.cs
  src/Raven.Server/Documents/Queries/QueryMetadata.cs
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  src/Raven.Server/Documents/Subscriptions/SubscriptionConnectionState.cs
  src/Raven.Server/Documents/Subscriptions/SubscriptionStorage.cs
  src/Raven.Server/Documents/TcpHandlers/SubscriptionConnection.cs
  src/Raven.Server/Documents/TcpHandlers/TcpConnectionOptions.cs
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Utils/Cli/RavenCli.cs
  src/Raven.Server/Utils/ThreadsUsage.cs
  src/Raven.Server/Web/Studio/DataDirectoryInfo.cs
  src/Raven.Studio/typescript/models/database/tasks/exportDatabaseModel.ts
  src/Raven.Studio/typescript/models/database/tasks/periodicBackup/amazonSettings.ts
  src/Raven.Studio/typescript/models/database/tasks/periodicBackup/azureSettings.ts
  src/Raven.Studio/typescript/models/database/tasks/periodicBackup/backupSettings.ts
  src/Raven.Studio/typescript/models/database/tasks/periodicBackup/ftpSettings.ts
  src/Raven.Studio/typescript/models/database/tasks/periodicBackup/glacierSettings.ts
  src/Raven.Studio/typescript/models/database/tasks/periodicBackup/googleCloudSettings.ts
  src/Raven.Studio/typescript/models/database/tasks/periodicBackup/localSettings.ts
  src/Raven.Studio/typescript/models/database/tasks/periodicBackup/s3Settings.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/smugglerDatabaseDetails.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editPeriodicBackupTask.ts
  src/Raven.Studio/typescript/viewmodels/manage/editServerWideBackup.ts
  src/Raven.Studio/typescript/viewmodels/resources/createDatabase.ts
  src/Raven.Studio/wwwroot/App/views/database/tasks/editPeriodicBackupTask.html
  src/Raven.Studio/wwwroot/App/views/manage/editServerWideBackup.html
  src/Raven.Studio/wwwroot/App/views/partial/backupDestinations.html
  src/Sparrow/Json/BlittableJsonReaderObject.cs
  src/Sparrow/Logging/LoggingSource.cs
  test/RachisTests/AddNodeToClusterTests.cs
  test/RachisTests/SubscriptionFailoverWIthWaitingChains.cs
  test/SlowTests/Core/Session/Advanced.cs
  test/SlowTests/Issues/RavenDB_13696.cs
  test/SlowTests/Issues/RavenDB_14176.cs
  test/SlowTests/Issues/RavenDB_14178.cs
  test/SlowTests/Server/Documents/ETL/RavenDB_8866.cs
  test/SlowTests/Tests/Linq/WhereClause.cs
  test/Tests.Infrastructure/ConsoleTestOutputHelper.cs
  test/Tests.Infrastructure/LinuxRaceConditionWorkAround.cs
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
  test/Tryouts/Program.cs
  tools/Raven.Debug/Raven.Debug.csproj
  tools/Raven.Migrator/Raven.Migrator.csproj
Labels: v5.0

#9837 RavenDB-14200 : JS conversion extensions : fix NRE in NullableSupport
  src/Raven.Client/Util/JavascriptConversionExtensions.cs
  test/SlowTests/Issues/RavenDB-14200.cs
Labels: v4.2

#9845 RavenDB-14213 - Can't filter index by the replacement index status
  src/Raven.Studio/typescript/models/database/index/index.ts
Labels: v4.2
