Repository ravendb/ravendb, pull requests merged in 2019-03, with the labels that each got.

#8833 RavenDB-12980 Fixing failing test on 32 bits. It started to fail due …
  test/SlowTests/Server/Documents/Indexing/MapReduce/RavenDB_11643.cs
Labels: v4.1

#8832 RavenDB-12937 Data race in License manager -> renew license
  src/Raven.Studio/typescript/models/auth/licenseModel.ts
  src/Raven.Studio/typescript/viewmodels/shell/registration.ts
Labels: v4.1

#8836 RavenDB-12979 Fixing tests which stated to fail after reducing the in…
  test/SlowTests/Issues/RavenDB_12151.cs
Labels: v4.1

#8834 RavenDB-12982 Missing escaping of attachment name when getting attach…
  Raven.Client.Lightweight/Connection/Async/AsyncServerClient.cs
  Raven.Tests/Storage/Attachments.cs
Labels: v3.5

#8839 RavenDB-12992 we need to use token with timeout
  src/Raven.Server/Documents/Handlers/RevisionsHandler.cs
Labels: v4.2

#8837 RavenDB-12811 dashboard updates for non cluster admin operators
  src/Raven.Server/Dashboard/AbstractDashboardNotification.cs
  src/Raven.Server/Dashboard/DatabasesInfo.cs
  src/Raven.Server/Dashboard/DatabasesInfoNotificationSender.cs
  src/Raven.Server/Dashboard/DrivesUsage.cs
  src/Raven.Server/Dashboard/IndexingSpeed.cs
  src/Raven.Server/Dashboard/MachineResources.cs
  src/Raven.Server/Dashboard/TrafficWatch.cs
  src/Raven.Server/NotificationCenter/NotificationCenter.cs
  src/Raven.Server/NotificationCenter/NotificationCenterWebsocketWriter.cs
  src/Raven.Server/NotificationCenter/NotificationsBase.cs
  src/Raven.Studio/typescript/common/shell/accessManager.ts
  src/Raven.Studio/typescript/viewmodels/resources/serverDashboard.ts
  src/Raven.Studio/wwwroot/App/views/resources/serverDashboard.html
Labels: v4.2

#8845 RavenDB-12990 update title on database record
  src/Raven.Studio/wwwroot/App/views/database/settings/databaseRecord.html
Labels: v4.2

#8846 RavenDB-12987 monitoring -f throws when no data on graph
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexPerformance.ts
Labels: v4.2

#8844 RavenDB-12997 compact on disabled database has no action
  src/Raven.Studio/typescript/viewmodels/resources/databases.ts
  src/Raven.Studio/wwwroot/App/views/resources/databases.html
Labels: v4.2

#8843 RavenDB-12998 update text in delete database screen
  src/Raven.Studio/wwwroot/App/views/resources/deleteDatabaseConfirm.html
Labels: v4.2

#8842 RavenDB-12996 add missing title tags on databases page
  src/Raven.Studio/typescript/viewmodels/resources/databases.ts
  src/Raven.Studio/wwwroot/App/views/resources/databases.html
Labels: v4.2

#8841 4.1 to 4.2 merge
  src/Raven.Client/Json/BlittableExtensions.cs
  src/Raven.Embedded/RavenServerRunner.cs
  src/Raven.Embedded/ServerOptions.cs
  src/Raven.Studio/typescript/models/auth/licenseModel.ts
  src/Raven.Studio/typescript/viewmodels/common/cronEditor.ts
  src/Raven.Studio/typescript/viewmodels/shell/registration.ts
  src/Raven.TestDriver/TestServerOptions.cs
  test/FastTests/Issues/RavenDB_12731.cs
  test/SlowTests/Issues/RavenDB_12151.cs
  test/SlowTests/MailingList/Enzmann.cs
  test/SlowTests/Server/Documents/Indexing/MapReduce/RavenDB_11643.cs
Labels: v4.2

#8849 RavenDB-12988 issues when comparing revisions with delete revisions
  src/Raven.Studio/typescript/viewmodels/database/documents/editDocument.ts
  src/Raven.Studio/typescript/viewmodels/database/documents/editDocumentConnectedDocuments.ts
  src/Raven.Studio/wwwroot/Content/css/pages/documents-edit.less
Labels: v4.2

#8847 RavenDB-12991 automatically click add url button in connection string…
  src/Raven.Studio/typescript/viewmodels/database/settings/connectionStrings.ts
Labels: v4.2

#8848 RavenDB-12204 Unskipping test
  test/SlowTests/Issues/RavenDB-12204.cs
Labels: v4.2

#8853 RavenDB-7070 updated packages
  bench/Micro.Benchmark/Micro.Benchmark.csproj
  bench/Regression.Benchmark/Regression.Benchmark.csproj
  bench/Voron.Benchmark/Voron.Benchmark.csproj
  test/BenchmarkTests/BenchmarkTests.csproj
  test/EmbeddedTests/EmbeddedTests.csproj
  test/FastTests/FastTests.csproj
  test/InterversionTests/InterversionTests.csproj
  test/RachisTests/RachisTests.csproj
  test/SlowTests/SlowTests.csproj
  test/StressTests/StressTests.csproj
Labels: v4.1

#8854 4.1 to 4.2 merge
  bench/Micro.Benchmark/Micro.Benchmark.csproj
  bench/Regression.Benchmark/Regression.Benchmark.csproj
  bench/Voron.Benchmark/Voron.Benchmark.csproj
  test/BenchmarkTests/BenchmarkTests.csproj
  test/EmbeddedTests/EmbeddedTests.csproj
  test/FastTests/FastTests.csproj
  test/InterversionTests/InterversionTests.csproj
  test/RachisTests/RachisTests.csproj
  test/SlowTests/SlowTests.csproj
  test/StressTests/StressTests.csproj
  test/Tryouts/Tryouts.csproj
Labels: v4.2

#8855 RavenDB-13001 fixing test
  test/SlowTests/Smuggler/BackupDatabaseRecordTests.cs
Labels: v4.2

#8838 RavenDB-12981 fixed test
  test/SlowTests/Server/Documents/Indexing/Static/RavenDB_7691.cs
Labels: v4.2

#8825 RavenDB-12936 : counters work
  src/Raven.Server/Documents/CountersStorage.cs
  src/Raven.Server/Documents/DocumentPutAction.cs
  src/Raven.Server/Documents/Replication/ReplicationDocumentSender.cs
  test/SlowTests/Client/Counters/CountersCluster.cs
  test/Tests.Infrastructure/RavenTestBase.cs
Labels: v4.2

#8856 RavenDB-13004: Copy also .so and .dylib libraries on embedded tests
  test/EmbeddedTests/BasicTests.cs
Labels: v4.1

#8858 RavenDB-12874: CanPreformSeveralClusterTransactions - add NoTimeouts(…
  test/SlowTests/Cluster/ClusterTransactionTests.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
Labels: v4.1

#8860 RavenDB-12957 removing protection from memory methods leaving just Ge…
  src/Sparrow/Json/JsonOperationContext.cs
Labels: v4.1

#8862 4.1 to 4.2 merge
  src/Raven.Server/Documents/Replication/IncomingReplicationHandler.cs
  src/Raven.Server/RavenServerStartup.cs
  src/Raven.Server/Web/RequestHandler.cs
  src/Raven.Studio/typescript/common/generalUtils.ts
  src/Raven.Studio/typescript/common/helpers/view/viewHelpers.ts
  src/Raven.Studio/typescript/common/messagePublisher.ts
  src/Raven.Studio/typescript/common/notifications/models/abstractNotification.ts
  src/Raven.Studio/typescript/common/notifications/notificationCenter.ts
  src/Raven.Studio/typescript/viewmodels/common/confirmationDialog.ts
  src/Raven.Studio/typescript/viewmodels/common/showDataDialog.ts
  src/Raven.Studio/typescript/viewmodels/database/documents/editDocument.ts
  src/Raven.Studio/typescript/viewmodels/database/documents/editDocumentUploader.ts
  src/Raven.Studio/typescript/viewmodels/database/documents/revisionsBin.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexPerformance.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexes.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/visualizer/visualizerGraphGlobal.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/visualizer/visualizerTreeExplorer.ts
  src/Raven.Studio/typescript/viewmodels/database/patch/patch.ts
  src/Raven.Studio/typescript/viewmodels/database/query/query.ts
  src/Raven.Studio/typescript/viewmodels/database/settings/connectionStrings.ts
  src/Raven.Studio/typescript/viewmodels/database/settings/customSorters.ts
  src/Raven.Studio/typescript/viewmodels/database/settings/revertRevisions.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editSqlEtlTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editSubscriptionTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/importDatabaseFromFile.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/importDatabaseFromSql.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/ongoingTasks.ts
  src/Raven.Studio/typescript/viewmodels/manage/certificates.ts
  src/Raven.Studio/typescript/viewmodels/manage/cluster.ts
  src/Raven.Studio/typescript/viewmodels/manage/debugAdvancedObserverLog.ts
  src/Raven.Studio/typescript/viewmodels/manage/runningQueries.ts
  src/Raven.Studio/typescript/viewmodels/partial/columnsSelector.ts
  src/Raven.Studio/typescript/viewmodels/resources/databases.ts
  src/Raven.Studio/typescript/viewmodels/resources/manageDatabaseGroup.ts
  src/Raven.Studio/typescript/viewmodels/resources/serverDashboard.ts
  src/Raven.Studio/typescript/viewmodels/viewModelBase.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/columns/actionColumn.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/columns/hyperlinkColumn.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/columns/providers/documentBasedColumnsProvider.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/columns/textColumn.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/virtualGridUtils.ts
  src/Raven.Studio/typings/_studio/dto.d.ts
  src/Raven.Studio/wwwroot/App/views/common/confirmationDialog.html
  src/Raven.Studio/wwwroot/App/views/database/patch/patch.html
  src/Raven.Studio/wwwroot/App/views/database/query/query.html
  src/Raven.Studio/wwwroot/App/views/partial/columnsSelector.html
  src/Sparrow/Json/JsonOperationContext.cs
  test/SlowTests/Cluster/ClusterTransactionTests.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
Labels: v4.2

#8861 RavenDB-11725: Fix test LZ4
  test/StressTests/Voron/HugeTransactions.cs
Labels: v4.1

#8799 RDBC-282 test
  test/SlowTests/Issues/RDBC-282.cs
Labels: v4.1

#8818 RavenDB-12967 Race condition in data exploration means that we aren't…
  Raven.Database/Server/Controllers/StreamsController.cs
Labels: v3.5

#8864 RavenDB-12945 removed GlobalHttpClientTimeout
  src/Raven.Client/Documents/Commands/QueryCommand.cs
  src/Raven.Client/Http/RequestExecutor.cs
Labels: v4.2

#8865 4.1 to 4.2 merge
  test/SlowTests/Issues/RDBC-282.cs
  test/StressTests/Voron/HugeTransactions.cs
Labels: v4.2

#8867 RavenDB-12736 cluster stabilization
  src/Raven.Server/Rachis/Follower.cs
  src/Raven.Server/Rachis/FollowerAmbassador.cs
Labels: v4.1

#8870 4.1 to 4.2 merge
  src/Raven.Server/Rachis/Follower.cs
  src/Raven.Server/Rachis/FollowerAmbassador.cs
Labels: v4.2

#8871 RavenDB-12736 fixing PR comments
  src/Raven.Server/Rachis/Follower.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/Rachis/RachisStateMachine.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
Labels: v4.1

#8873 RavenDB-13011 Clear remains of removed node in the DatabaseRecord
  src/Raven.Client/ServerWide/DatabaseTopology.cs
Labels: v4.1

#8863 RavenDB-11470 Restore should not generate new change vectors
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreBackupTask.cs
  src/Raven.Server/Smuggler/Documents/Data/DatabaseSmugglerOptionsServerSide.cs
  src/Raven.Server/Smuggler/Documents/Data/ISmugglerDestination.cs
  src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
  src/Raven.Server/Smuggler/Documents/StreamDestination.cs
  test/SlowTests/Client/Attachments/AttachmentsSmuggler.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
  test/SlowTests/Smuggler/LegacySmugglerTests.cs
Labels: v4.1

#8877 4.1 to 4.2 merge
  src/Raven.Client/ServerWide/DatabaseTopology.cs
  src/Raven.Server/Config/Categories/StorageConfiguration.cs
  src/Raven.Server/Documents/CompactDatabaseTask.cs
  src/Raven.Server/Documents/ConfigurationStorage.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreBackupTask.cs
  src/Raven.Server/Documents/TcpHandlers/SubscriptionConnection.cs
  src/Raven.Server/Documents/TcpHandlers/SubscriptionDocumentsFetcher.cs
  src/Raven.Server/Rachis/Follower.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/Rachis/RachisStateMachine.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Smuggler/Documents/Data/DatabaseSmugglerOptionsServerSide.cs
  src/Raven.Server/Smuggler/Documents/Data/ISmugglerDestination.cs
  src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
  src/Raven.Server/Smuggler/Documents/StreamDestination.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/StorageEnvironmentOptions.cs
  test/SlowTests/Client/Attachments/AttachmentsSmuggler.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
  test/SlowTests/Smuggler/LegacySmugglerTests.cs
Labels: v4.2

#8884 Raven db 12242
  src/Raven.Studio/typescript/common/helpers/graph/graphHelper.ts
  src/Raven.Studio/typescript/common/query/graphQueryResults.ts
  src/Raven.Studio/typescript/viewmodels/database/query/query.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/virtualGrid.ts
  src/Raven.Studio/wwwroot/App/views/database/query/query.html
  src/Raven.Studio/wwwroot/Content/css/pages/query.less
  test/Studio/typescript/common/helpers/graph/graphHelper.spec.ts
Labels: v4.2

#8880 RavenDB-13025 break the loop for notifying cluster topology updates e…
  src/Raven.Server/ServerWide/ServerStore.cs
Labels: v4.1

#8887 RavenDB-9435 fix runtime prerequisites for libicu
  install_runtime_prerequisites.sh
Labels: v4.1

#8891 RavenDB-12839 update rainbow in menu
  src/Raven.Studio/typescript/common/shell/menu/items/manageServer.ts
  src/Raven.Studio/wwwroot/Content/css/icons.less
Labels: v4.2

#8890 RavenDB-9165: Add OutOfMemoryException handling to recovery tool.
  tools/Voron.Recovery/CommandLineApp.cs
  tools/Voron.Recovery/Recovery.cs
Labels: v4.2

#8893 RavenDB-13039 Shared global indexes can become out of sync if a tx mo…
  src/Voron/Data/Fixed/FixedSizeTree.cs
  src/Voron/Data/Tables/Table.cs
  test/FastTests/Voron/Bugs/GlobalFixedSizeTreeInMulitpleTables.cs
Labels: v4.1

#8895 RavenDB-7070 Fixing build in VALIDATE
  src/Sparrow/Json/JsonOperationContext.cs
Labels: v4.1

#8897 4.1 to 4.2 merge
  install_runtime_prerequisites.sh
  src/Raven.Client/Documents/Session/AbstractDocumentQuery.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Sparrow/Json/JsonOperationContext.cs
  src/Voron/Data/Fixed/FixedSizeTree.cs
  src/Voron/Data/Tables/Table.cs
  test/FastTests/Voron/Bugs/GlobalFixedSizeTreeInMulitpleTables.cs
Labels: v4.2

#8903 RavenDB-13021 Add throttling to cluster view
  src/Raven.Studio/typescript/models/database/cluster/clusterTopology.ts
Labels: v4.1

#8902 RavenDB-13044 Database displayed 2 times in db switcher
  src/Raven.Studio/wwwroot/App/views/shell.html
Labels: v4.1

#8901 RavenDB-13045 Docs icon not visible on databases view for a promotabl…
  src/Raven.Studio/wwwroot/App/views/resources/databases.html
Labels: v4.1

#8899 [RDoc-1412] add Obsolete for SkipRevisionCreation in DatabaseSmugglerOptions
  src/Raven.Client/Documents/Smuggler/DatabaseSmugglerOptions.cs
Labels: v4.1

#8898 RavenDB-13038 upgraded Jint
  libs/Jint.3.0.19-ravendb.nupkg
  src/Raven.Server/Documents/Indexes/Static/EsprimaReferencedCollectionVisitor.cs
  src/Raven.Server/Documents/Indexes/Static/EsprimaVisitor.cs
  src/Raven.Server/Documents/Indexes/Static/JavaScriptIndex.cs
  src/Raven.Server/Documents/Indexes/Static/JavaScriptIndexUtils.cs
  src/Raven.Server/Documents/Indexes/Static/JavaScriptMapOperation.cs
  src/Raven.Server/Documents/Indexes/Static/JavaScriptReduceOperation.cs
  src/Raven.Server/Documents/Patch/ScriptRunner.cs
  src/Raven.Server/Documents/Queries/QueryMetadata.cs
  src/Raven.Server/Extensions/JintExtensions.cs
  src/Raven.Server/Raven.Server.csproj
Labels: v4.2

#8905 RavenDB-13048 double escaping in studio
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexes.ts
Labels: v4.1

#8906 RavenDB-12999 buttons blended with background on create encrypted dat…
  src/Raven.Studio/wwwroot/App/views/resources/setupEncryptionKey.html
Labels: v4.2

#8907 RavenDB-13064 minor
  test/SlowTests/Issues/RavenDB-13064.cs
Labels: v4.1

#8908 4.1 to 4.2 merge
  src/Raven.Client/Documents/Operations/OngoingTasks/GetOngoingTaskInfoOperation.cs
  src/Raven.Client/Documents/Smuggler/DatabaseSmugglerOptions.cs
  src/Raven.Client/Http/HttpCache.cs
  src/Raven.Server/Documents/CatastrophicFailureHandler.cs
  src/Raven.Server/Documents/CompactDatabaseTask.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Rachis/CandidateAmbassador.cs
  src/Raven.Server/Rachis/FollowerAmbassador.cs
  src/Raven.Server/Web/System/OngoingTasksHandler.cs
  src/Raven.Studio/typescript/models/database/cluster/clusterTopology.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexes.ts
  src/Raven.Studio/wwwroot/App/views/resources/databases.html
  src/Raven.Studio/wwwroot/App/views/shell.html
  src/Voron/Exceptions/CatastrophicFailureNotification.cs
  src/Voron/StorageEnvironmentOptions.cs
  test/FastTests/Server/Replication/ReplicationTestBase.cs
  test/RachisTests/DatabaseCluster/OngoingTasks.cs
  test/SlowTests/Issues/RavenDB-13064.cs
  test/SlowTests/Issues/RavenDB_10744.cs
Labels: v4.2

#8909 RavenDB-10022 [Dashboard] Indicate each frame when it is polled
  src/Raven.Studio/typescript/viewmodels/resources/serverDashboard.ts
  src/Raven.Studio/wwwroot/App/views/resources/serverDashboard.html
  src/Raven.Studio/wwwroot/Content/css/animations.less
Labels: v4.2

#8910 RavenDB-12555 more space for indexing table in dashboard
  src/Raven.Studio/typescript/viewmodels/resources/serverDashboard.ts
  src/Raven.Studio/wwwroot/App/views/resources/serverDashboard.html
  src/Raven.Studio/wwwroot/Content/css/pages/dashboard.less
Labels: v4.2

#8911 RavenDB-13071 fix NRE
  src/Raven.Server/Commercial/LetsEncryptClient.cs
Labels: v4.1

#8916 RavenDB-11645 The version isn't alligned in the cluster view
  src/Raven.Studio/typescript/models/database/cluster/clusterNode.ts
  src/Raven.Studio/wwwroot/Content/css/pages/etl.less
Labels: v4.2

#8915 RavenDB-7177 [Studio : Databases : Create] adjustments
  src/Raven.Studio/wwwroot/App/views/resources/createDatabase.html
  src/Raven.Studio/wwwroot/App/views/resources/setupEncryptionKey.html
  src/Raven.Studio/wwwroot/Content/css/checkbox-toggle.less
Labels: v4.2

#8917 RavenDB-12965 database group screen is jumping when one node is down
  src/Raven.Studio/typescript/models/resources/info/databaseGroupNode.ts
  src/Raven.Studio/typescript/viewmodels/resources/addNewNodeToDatabaseGroup.ts
  src/Raven.Studio/typescript/viewmodels/resources/manageDatabaseGroup.ts
  src/Raven.Studio/wwwroot/App/views/resources/manageDatabaseGroup.html
Labels: v4.2

#8913 RavenDB-10312 Document View - Buttons Minors
  src/Raven.Studio/wwwroot/App/views/database/documents/editDocument.html
Labels: v4.2

#8919 RavenDB-12810 Dispose write transaction even when replay operation canceled in the middle
  src/Raven.Server/Documents/ReplayTxCommandHelper.cs
  test/SlowTests/Server/RecordingTransactionOperationsMergerTests.cs
Labels: v4.2

#8924 4.1. to 4.2 merge + updated to .NET Core 2.2.3
  bench/BulkInsert.Benchmark/BulkInsert.Benchmark.csproj
  bench/Indexing.Benchmark/Indexing.Benchmark.csproj
  bench/Micro.Benchmark/Micro.Benchmark.csproj
  bench/Regression.Benchmark/Regression.Benchmark.csproj
  bench/SubscriptionFailover.Benchmark/SubscriptionFailover.Benchmark.csproj
  bench/Subscriptions.Benchmark/Subscriptions.Benchmark.csproj
  bench/Voron.Benchmark/Voron.Benchmark.csproj
  src/Raven.Client/Documents/Smuggler/DatabaseSmugglerImportOptions.cs
  src/Raven.Embedded/ServerOptions.cs
  src/Raven.Server/Commercial/LetsEncryptClient.cs
  src/Raven.Server/Documents/Handlers/Debugging/StorageHandler.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Server/Smuggler/Documents/Data/DatabaseSmugglerOptionsServerSide.cs
  src/Raven.Studio/Raven.Studio.csproj
  src/Voron/Data/Tables/TableReport.cs
  test/BenchmarkTests/BenchmarkTests.csproj
  test/EmbeddedTests/EmbeddedTests.csproj
  test/FastTests/FastTests.csproj
  test/InterversionTests/InterversionTests.csproj
  test/RachisTests/DatabaseCluster/OngoingTasks.cs
  test/RachisTests/RachisTests.csproj
  test/SlowTests/Authentication/AuthenticationClusterTests.cs
  test/SlowTests/SlowTests.csproj
  test/StressTests/StressTests.csproj
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
  test/Tryouts/Tryouts.csproj
  tools/Raven.Debug/Raven.Debug.csproj
  tools/Raven.Migrator/Raven.Migrator.csproj
  tools/TypingsGenerator/TypingsGenerator.csproj
  tools/Voron.Recovery/Voron.Recovery.csproj
  tools/rvn/rvn.csproj
Labels: v4.2

#8925 RavenDB-9207 The list of Document Collections truncates long collect…
  src/Raven.Studio/typescript/common/settings/globalSettings.ts
  src/Raven.Studio/typescript/common/shell/menu.ts
  src/Raven.Studio/typescript/viewmodels/shell.ts
  src/Raven.Studio/wwwroot/App/views/shell.html
  src/Raven.Studio/wwwroot/Content/css/bootstrap/variables-body.less
  src/Raven.Studio/wwwroot/Content/css/main-menu.less
Labels: v4.2

#8927 Revert "RavenDB-12945 removed GlobalHttpClientTimeout"
  src/Raven.Client/Documents/Commands/QueryCommand.cs
  src/Raven.Client/Http/RequestExecutor.cs
Labels: v4.2

#8930 RavenDB-11139: Fix for NRE when continue backup task from older version.
  src/Raven.Server/Documents/PeriodicBackup/BackupTask.cs
Labels: v4.1

#8914 RavenDB-12104 Recover from exception during accepting TCP connection
  src/Raven.Server/NotificationCenter/Notifications/AlertType.cs
  src/Raven.Server/RavenServer.cs
Labels: v4.1

#8932 RavenDB-9782 - LicenseManager.ThrowIfCannotActivateLicense() : check also for monitoring existance
  src/Raven.Server/Commercial/LicenseManager.cs
Labels: v4.1

#8934 4.1 to 4.2 merge
  src/Raven.Client/Util/JavascriptConversionExtensions.cs
  src/Raven.Server/Commercial/LicenseManager.cs
  src/Raven.Server/Documents/Indexes/Static/EsprimaReferencedCollectionVisitor.cs
  src/Raven.Server/Documents/Indexes/Static/JavaScriptIndex.cs
  src/Raven.Server/Documents/PeriodicBackup/BackupTask.cs
  src/Raven.Server/Documents/Queries/EsprimaHasLoadOrIncludeVisitor.cs
  src/Raven.Server/Documents/Queries/QueryMetadata.cs
  src/Raven.Server/NotificationCenter/Notifications/AlertType.cs
  src/Raven.Server/RavenServer.cs
  test/SlowTests/Issues/RavenDB-13060.cs
  test/SlowTests/Issues/RavenDB-13086.cs
Labels: v4.2

#8937 RavenDB-13092 Blank certificates view on replica - Cannot read proper…
  src/Raven.Studio/typescript/viewmodels/manage/certificates.ts
Labels: v4.2

#8939 RavenDB-13047: Prevent log spamming when mentor hasn't sent all of th…
  src/Raven.Server/ServerWide/Maintenance/ClusterObserver.cs
Labels: v4.1

#8935 RavenDB-13018 Break documents iteration in subscription after we reac…
  src/Raven.Server/Documents/TcpHandlers/SubscriptionDocumentsFetcher.cs
Labels: v4.1

#8943 RavenDB-12931 / RavenDB-13116 There is nothing to migrate if we don't…
  src/Raven.Server/Storage/Schema/Updates/Documents/From16.cs
Labels: v4.2

#8944 RavenDB-10112 add runtime settings for x86
  src/Raven.Server/Raven.Server.csproj
Labels: v4.2

#8947 4.1 to 4.2 merge
  src/Raven.Client/Documents/Session/InMemoryDocumentSessionOperations.cs
  src/Raven.Client/Documents/Session/Operations/BatchOperation.cs
  src/Raven.Client/Documents/Subscriptions/SubscriptionWorker.cs
  src/Raven.Server/Documents/TcpHandlers/SubscriptionDocumentsFetcher.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterObserver.cs
  test/FastTests/Server/Replication/ReplicationTestBase.cs
  test/SlowTests/Issues/RavenDB-13086.cs
  test/SlowTests/Issues/RavenDB_13034.cs
  test/SlowTests/Issues/RavenDB_9576.cs
  test/SlowTests/Server/Replication/ReplicationCleanTombstones.cs
  tools/Raven.Migrator/Raven.Migrator.csproj
Labels: v4.2

#8951 RavenDB-13096: Increase timeouts for the specific cluster transaction…
  test/SlowTests/Cluster/ClusterTransactionTests.cs
Labels: v4.2

#8952 4.1 to 4.2 merge
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  test/SlowTests/Server/Documents/PeriodicBackup/RavenDB_12012.cs
Labels: v4.2

#8933 RavenDB-13093 Node not being deleted and hangs on pending for deletion
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/ServerWide/Commands/DeleteDatabaseCommand.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterObserver.cs
  test/RachisTests/AddNodeToClusterTests.cs
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
Labels: v4.1

#8954 4.1 to 4.2 merge
  src/Directory.Build.props
  src/Raven.Client/Documents/Linq/RavenQueryProviderProcessor.cs
  src/Raven.Client/Documents/Session/AbstractDocumentQuery.cs
  src/Raven.Client/Documents/Session/AsyncDocumentQuery.cs
  src/Raven.Client/Documents/Session/DocumentQuery.cs
  src/Raven.Client/Documents/Session/IAbstractDocumentQuery.cs
  src/Raven.Client/Documents/Session/IDocumentQueryBase.cs
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/ServerWide/Commands/DeleteDatabaseCommand.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterObserver.cs
  test/RachisTests/AddNodeToClusterTests.cs
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
  test/SlowTests/Issues/RavenDB_13006.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
  tools/Directory.Build.props
Labels: v4.2

#8955 RavenDB-13126 Added Raven/Esent/MaxSessions configuration option
  Raven.Database/Storage/Esent/TransactionalStorage.cs
  Raven.Database/Storage/Esent/TransactionalStorageConfigurator.cs
Labels: v2.5

#8957 RavenDB-13126 Added Raven/Esent/MaxSessions configuration option
  Raven.Abstractions/Data/Constants.cs
  Raven.Database/Storage/Esent/StorageConfigurator.cs
Labels: v3.0

#8956 RavenDB-13126 Added Raven/Esent/MaxSessions configuration option
  Raven.Abstractions/Data/Constants.cs
  Raven.Database/Storage/Esent/StorageConfigurator.cs
Labels: v3.5

#8960 RavenDB-13120 Failing test: CanBackupAndRestoreDatabaseRecord
  test/SlowTests/Smuggler/BackupDatabaseRecordTests.cs
Labels: v4.2

#8964 RavenDB-12757
  src/Raven.Studio/wwwroot/App/views/database/tasks/ongoingTasks.html
  src/Raven.Studio/wwwroot/Content/css/basic-layout.less
  src/Raven.Studio/wwwroot/Content/css/bootstrap/variables-body.less
  src/Raven.Studio/wwwroot/Content/css/pages/etl.less
  src/Raven.Studio/wwwroot/Content/css/pages/ongoing-tasks.less
  src/Raven.Studio/wwwroot/Content/css/styles-common.less
  src/Raven.Studio/wwwroot/Content/css/themes/light-theme-variables-override.less
Labels: v4.2

#8962 RavenDB-13117: Fix compare exchange and identities failing tests on linux.
  test/SlowTests/Server/Documents/PeriodicBackup/RavenDB-11139.cs
  test/SlowTests/Server/Documents/PeriodicBackup/RavenDB_12012.cs
Labels: v4.2

#8966 RavenDB-13065 Dashboard glitch on node just added to cluster
  src/Raven.Studio/typescript/viewmodels/resources/serverDashboard.ts
Labels: v4.1

#8963 RavenDB-12798 : Cannot project array's length to custom projection class
  src/Raven.Client/Documents/Linq/LinqPathProvider.cs
  src/Raven.Client/Documents/Linq/RavenQueryProviderProcessor.cs
  test/SlowTests/Issues/RavenDB-12798.cs
Labels: v4.1

#8969 4.1 to 4.2 merge
  src/Raven.Client/Documents/Linq/LinqPathProvider.cs
  src/Raven.Client/Documents/Linq/RavenQueryProviderProcessor.cs
  src/Raven.Client/Util/JavascriptConversionExtensions.cs
  src/Raven.Server/Documents/Handlers/Debugging/StorageHandler.cs
  src/Raven.Server/Web/Studio/StudioTasksHandler.cs
  src/Raven.Server/Web/System/AdminStorageHandler.cs
  src/Raven.Studio/typescript/viewmodels/resources/serverDashboard.ts
  test/SlowTests/Issues/RavenDB-12798.cs
  test/SlowTests/Issues/RavenDB-13016.cs
Labels: v4.2

#8972 RavenDB-12950 make sure we support of import/export features on migra…
  src/Raven.Studio/typescript/models/database/tasks/migrateRavenDbDatabaseModel.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/importDatabaseFromFile.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/migrateRavenDbDatabase.ts
  src/Raven.Studio/wwwroot/App/views/database/tasks/migrateRavenDbDatabase.html
Labels: v4.2

#8973 RavenDB-12984 make close button in themes selector bigger
  src/Raven.Studio/wwwroot/App/views/shell/chooseTheme.html
Labels: v4.2

#8971 RavenDB-12785 NRE when defining Output Collection on JS index
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/OutputReduceIndexWriteOperation.cs
  test/SlowTests/Data/RavenDB-12785.ravendbdump
  test/SlowTests/Issues/RavenDB-12785.cs
  test/SlowTests/SlowTests.csproj
Labels: v4.1

#8975 RavenDB-13155 layout issue in ongoing tasks
  src/Raven.Studio/wwwroot/App/views/database/tasks/ongoingTasks.html
  src/Raven.Studio/wwwroot/Content/css/pages/ongoing-tasks.less
  src/Raven.Studio/wwwroot/Content/css/styles-common.less
Labels: v4.2

#8974 RavenDB-12954: Display correct exception with Allowed AuthenticationS…
  src/Raven.Server/Web/RequestHandler.cs
Labels: v4.2

#8976 RavenDB-12931 When getting pages of a table tree we don't need to gra…
  src/Voron/Data/BTrees/Tree.cs
  src/Voron/Data/Fixed/FixedSizeTree.cs
  src/Voron/Impl/Transaction.cs
Labels: v4.2

#8977 RavenDB-12735 catch NotSupportedException and rethrow as IOException
  src/Sparrow/Json/BlittableJsonTextWriter.cs
Labels: v4.1

#8978 4.1 to 4.2 merge
  src/Sparrow/Json/BlittableJsonTextWriter.cs
Labels: v4.2

#8981 RavenDB-13037 fix OnNetworkDisconnectionANewLeaderIsElectedAfterRecon…
  test/RachisTests/ElectionTests.cs
Labels: v4.1

#8984 RavenDB-13152: invalid path in setup instruction
  src/Raven.Server/Commercial/SetupManager.cs
  src/Raven.Server/Program.cs
Labels: v4.2

#8982 RavenDB-13164: Update exception message for stack trace collector on …
  src/Raven.Server/Documents/Handlers/Debugging/ThreadsHandler.cs
Labels: v4.2

#8985 RavenDB-13168: Avoid scary users with regexps on invalid index name
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  src/Raven.Server/Utils/NameUtils.cs
  src/Raven.Server/Web/System/ResourceNameValidator.cs
Labels: v4.2

#8992 RavenDB-13205 - Replace Cron tutorial with RavenDB link
  src/Raven.Studio/typescript/viewmodels/database/tasks/editPeriodicBackupTask.ts
Labels: v4.1

#8991 RavenDB-13199 ignore only certs which are already in the cluster, not…
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
Labels: v4.2

#8990 RavenDB-13195 Table.IsOwned needs to take into account large values
  src/Voron/Data/Tables/Table.cs
  test/SlowTests/Issues/RavenDB_13195.cs
Labels: v4.1

#8994 RavenDB-7070 updated packages
  src/Raven.Server/Raven.Server.csproj
Labels: v4.1

#8993 4.1 to 4.2 merge
  src/Raven.Client/Documents/Operations/CompareExchange/DeleteCompareExchangeValueOperation.cs
  src/Raven.Client/Documents/Operations/CompareExchange/PutCompareExchangeValueOperation.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Studio/typescript/viewmodels/common/cronEditor.ts
  src/Voron/Data/Tables/Table.cs
  src/Voron/Impl/LowLevelTransaction.cs
  test/RachisTests/ElectionTests.cs
  test/SlowTests/Client/UniqueValues.cs
  test/SlowTests/Issues/RavenDB-13029.cs
  test/SlowTests/Server/Documents/PeriodicBackup/RavenDB-4613.cs
  test/Tests.Infrastructure/NightlyBuildAzureStorageEmulatorFact.cs
  tools/Raven.Debug/Raven.Debug.csproj
Labels: v4.2

#8979 RavenDB-11800 Don't allow adding node to the cluster when the leader initialize with port 0
  src/Raven.Client/ServerWide/Commands/GetNodeInfoCommand.cs
  src/Raven.Server/Documents/Handlers/Admin/RachisAdminHandler.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  test/RachisTests/AddNodeToClusterTests.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v4.1

#8996 RavenDB-13255 - Add LowerCaseWhitespaceAnalyzer to the dropdown in the studio
  src/Raven.Studio/typescript/models/database/index/indexFieldOptions.ts
Labels: v4.1

#8997 4.1 to 4.2 merge
  src/Raven.Client/Constants.cs
  src/Raven.Client/ServerWide/Commands/GetNodeInfoCommand.cs
  src/Raven.Server/Documents/Handlers/Admin/RachisAdminHandler.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Server/ServerWide/Commands/CompareExchangeCommands.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Utils/NameUtils.cs
  src/Raven.Server/Web/System/ResourceNameValidator.cs
  src/Raven.Studio/typescript/models/database/index/indexFieldOptions.ts
  test/BenchmarkTests/BenchmarkTests.csproj
  test/FastTests/FastTests.csproj
  test/RachisTests/AddNodeToClusterTests.cs
  test/SlowTests/Issues/RavenDB_13161.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v4.2

#8999 RavenDB-13219 prevent creating counters w/o name
  src/Raven.Server/Documents/Patch/ScriptRunner.cs
  test/SlowTests/Issues/RavenDB_13219.cs
Labels: v4.2

#9001 RavenDB-13252 InvalidQueryException when trying to project counter value if counter name has spaces
  src/Raven.Client/Documents/Linq/RavenQueryProviderProcessor.cs
  test/SlowTests/Issues/RavenDB_13252.cs
Labels: v4.1

#8998 RavenDB-13178 compilation of JavaScript index should not take into account the MaxStepsForScript
  libs/Jint.3.0.20-ravendb.nupkg
  src/Raven.Server/Documents/Indexes/Static/JavaScriptIndex.cs
  src/Raven.Server/Extensions/JintExtensions.cs
  src/Raven.Server/Raven.Server.csproj
  test/SlowTests/Issues/RavenDB_13178.cs
Labels: v4.2

#9002 4.1 to 4.2 merge
  src/Raven.Client/Documents/Linq/RavenQueryProviderProcessor.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Voron/Debugging/DetailedStorageReport.cs
  src/Voron/Debugging/StorageReportGenerator.cs
  src/Voron/StorageEnvironment.cs
  test/SlowTests/Issues/RavenDB_13252.cs
Labels: v4.2

#9006 RavenDB-13305 cache issue for studio resources in release mode
  src/Raven.Server/Web/System/StudioHandler.cs
Labels: v4.1

#9003 RavenDB-13269 - Index errors when using Count()
  src/Raven.Server/Documents/Indexes/Static/DynamicArray.cs
  test/FastTests/Server/Documents/Queries/Dynamic/MapReduce/BasicDynamicMapReduceQueries.cs
  test/FastTests/Server/Documents/Revisions/RevisionsTests.cs
  test/SlowTests/Core/Commands/Documents.cs
  test/SlowTests/Issues/RavenDB-11422.cs
  test/SlowTests/Issues/RavenDB-13269.cs
  test/SlowTests/Server/Documents/Patching/AdvancedPatching.cs
  test/SlowTests/Server/Documents/Revisions/RevisionsReplication.cs
  test/SlowTests/Smuggler/SmugglerApiTests.cs
Labels: v4.1

#9007 4.1 to 4.2 merge
  src/Raven.Server/Documents/Indexes/Static/DynamicArray.cs
  src/Raven.Server/Web/System/StudioHandler.cs
  test/FastTests/Server/Documents/Queries/Dynamic/MapReduce/BasicDynamicMapReduceQueries.cs
  test/FastTests/Server/Documents/Revisions/RevisionsTests.cs
  test/SlowTests/Core/Commands/Documents.cs
  test/SlowTests/Issues/RavenDB-11422.cs
  test/SlowTests/Issues/RavenDB-13269.cs
  test/SlowTests/Server/Documents/Patching/AdvancedPatching.cs
  test/SlowTests/Server/Documents/Revisions/RevisionsReplication.cs
  test/SlowTests/Smuggler/SmugglerApiTests.cs
Labels: v4.2

#9008 RavenDB-13316 fixing include paths for subscriptions using strongly t…
  src/Raven.Client/Documents/Subscriptions/DocumentSubscriptions.cs
  test/SlowTests/Issues/RavenDB_12257.cs
Labels: v4.2
