Repository ravendb/ravendb, pull requests merged in 2020-12, with the labels that each got.

#11495 RavenDB-15944: add CultureInfo to HashCalculator
  src/Raven.Client/Documents/Queries/HashCalculator.cs
  test/SlowTests/Issues/RavenDB_15944.cs
Labels: v4.2

#11499 RavenDB-15885 fixed assembly resolution that caused 'invalid cast exception' when creating an instance of analyzer
  src/Raven.Server/Documents/Indexes/Static/IndexCompiler.cs
Labels: v5.1

#11480 RavenDB-15935 better exception for actions that require database but none was specified via parameter or there is no default one
  src/Raven.Client/Documents/DocumentStore.cs
  src/Raven.Client/Documents/DocumentStoreBase.cs
  src/Raven.Client/Documents/Identity/AsyncMultiDatabaseHiLoIdGenerator.cs
  src/Raven.Client/Documents/Indexes/AbstractIndexCreationTask.cs
  src/Raven.Client/Documents/Indexes/IndexCreation.cs
  src/Raven.Client/Documents/Operations/MaintenanceOperationExecutor.cs
  src/Raven.Client/Documents/Operations/OperationExecutor.cs
  src/Raven.Client/Documents/Subscriptions/DocumentSubscriptions.cs
  src/Raven.Client/Documents/Subscriptions/SubscriptionWorker.cs
  src/Raven.Client/Extensions/DocumentStoreExtensions.cs
  test/SlowTests/Issues/RavenDB-10726.cs
  test/SlowTests/Issues/RavenDB_15935.cs
Labels: v4.2

#11471 RavenDB-15914 check conflict status for attachment and deleted attachment
  src/Raven.Server/Documents/AttachmentsStorage.cs
  src/Raven.Server/Documents/ConflictsStorage.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Replication/IncomingReplicationHandler.cs
  src/Raven.Server/Documents/Replication/ReplicationDocumentSender.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  test/SlowTests/Client/Attachments/AttachmentsReplication.cs
Labels: v4.2

#11503 RavenDB-15974 A custom analyzer that outputs multiple terms outputs p…
  Raven.Database/Indexing/LuceneAST.cs
Labels: v3.5

#11504 RavenDB-15972 Analyzer input box should be disabled when indexing is…
  src/Raven.Studio/typescript/models/database/index/indexFieldOptions.ts
Labels: v5.1

#11502 RavenDB-15969 Show the full analyzer name for custom analyzer
  src/Raven.Studio/typescript/models/database/index/indexFieldOptions.ts
Labels: v5.1

#11498 RavenDB-15941 Cluster log truncation should be limited by time
  src/Raven.Server/Rachis/Leader.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
Labels: v4.2

#11507 RavenDB-15957 Added debugging stuff that might help to narrow down th…
  src/Raven.Server/Documents/Queries/QueryBuilder.cs
  test/SlowTests/Issues/RavenDB_13563.cs
Labels: v5.0

#11494 RavenDB-15163 Retry the actions of index replacement inside the actua…
  src/Raven.Server/Documents/Handlers/IndexHandler.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  test/SlowTests/Issues/RavenDB_15163.cs
Labels: v4.2

#11501 RavenDB-15568 We need to take into account Indexing option from the d…
  src/Raven.Server/Documents/Indexes/IndexField.cs
  test/SlowTests/Issues/RavenDB_15568.cs
Labels: v5.1

#11505 RavenDB-15939 : better error message
  src/Raven.Server/Documents/Queries/Parser/QueryParser.cs
  test/SlowTests/Client/TimeSeries/Issues/RavenDB-15939.cs
Labels: v5.1

#11515 RavenDB-15968 added debug endpoint
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Web/System/DatabasesDebugHandler.cs
Labels: v5.1

#11514 RavenDB-15950 Allow to ignore file lock error when using docker share…
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Utils/FileLocker.cs
Labels: v5.1

#11519 RavenDB-15957 Cleanup old versions of Lucene.Net and Jint from the li…
  libs/Jint.3.0.27-ravendb.nupkg
  libs/Lucene.Net.3.0.32.nupkg
  src/Raven.Server/Documents/Queries/QueryBuilder.cs
Labels: v5.0

#11500 RavenDB-15880 - fix race in test
  test/SlowTests/Issues/RavenDB-15754.cs
Labels: v5.0

#11522 RavenDB-15698 Server-wide backup view fix text alignment
  src/Raven.Studio/wwwroot/Content/css/styles-common.less
Labels: v4.2

#11524 4.2 to 5.0 merge
  docker/ravendb-ubuntu/Dockerfile.arm32v7
  docker/ravendb-ubuntu/Dockerfile.x64
  src/Raven.Client/Documents/DocumentStore.cs
  src/Raven.Client/Documents/DocumentStoreBase.cs
  src/Raven.Client/Documents/Identity/AsyncMultiDatabaseHiLoIdGenerator.cs
  src/Raven.Client/Documents/Indexes/AbstractIndexCreationTask.cs
  src/Raven.Client/Documents/Indexes/IndexCreation.cs
  src/Raven.Client/Documents/Operations/MaintenanceOperationExecutor.cs
  src/Raven.Client/Documents/Operations/OperationExecutor.cs
  src/Raven.Client/Documents/Queries/HashCalculator.cs
  src/Raven.Client/Documents/Subscriptions/DocumentSubscriptions.cs
  src/Raven.Client/Documents/Subscriptions/SubscriptionWorker.cs
  src/Raven.Client/Extensions/DocumentStoreExtensions.cs
  src/Raven.Server/Documents/AttachmentsStorage.cs
  src/Raven.Server/Documents/ConflictsStorage.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Handlers/IndexHandler.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  src/Raven.Server/Documents/PeriodicBackup/Aws/RavenAwsS3Client.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackup.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
  src/Raven.Server/Documents/Replication/ChangeVectorExtensions.cs
  src/Raven.Server/Documents/Replication/ConflictManager.cs
  src/Raven.Server/Documents/Replication/IncomingReplicationHandler.cs
  src/Raven.Server/Documents/Replication/ReplicationDocumentSender.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/Documents/Replication/ResolveConflictOnReplicationConfigurationChange.cs
  src/Raven.Server/Indexing/VoronIndexOutput.cs
  src/Raven.Server/Rachis/Leader.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/Web/System/BackupDatabaseHandler.cs
  src/Raven.Server/Web/System/OngoingTasksHandler.cs
  src/Raven.Studio/wwwroot/Content/css/styles-common.less
  src/Voron/Data/Compression/DecompressionBuffersPool.cs
  src/Voron/Debugging/StorageReportGenerator.cs
  src/Voron/Impl/Journal/LazyTransactionBuffer.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/StorageEnvironmentOptions.cs
  test/FastTests/Issues/RavenDB-11424.cs
  test/FastTests/Server/Basic/ChangeVectorConflictStatusTests.cs
  test/SlowTests/Blittable/SerializeAndDeserializeMergedTransactionCommandTests.cs
  test/SlowTests/Client/Attachments/AttachmentsReplication.cs
  test/SlowTests/Issues/RavenDB-10726.cs
  test/SlowTests/Issues/RavenDB_15163.cs
  test/SlowTests/Issues/RavenDB_15911.cs
  test/SlowTests/Issues/RavenDB_15935.cs
  test/SlowTests/Issues/RavenDB_15944.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Restore/RestoreFromAzure.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Restore/RestoreFromGoogleCloud.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Restore/RestoreFromS3.cs
  test/SlowTests/Server/Replication/ReplicationConflictsTests.cs
  test/SlowTests/Server/Replication/ReplicationSpecialCases.cs
  test/SlowTests/SlowTests/Issues/RavenDB-15859.cs
Labels: v5.0

#11525 5.0 to 5.1 merge
  src/Raven.Client/Documents/DocumentStore.cs
  src/Raven.Client/Documents/DocumentStoreBase.cs
  src/Raven.Client/Documents/Identity/AsyncMultiDatabaseHiLoIdGenerator.cs
  src/Raven.Client/Documents/Indexes/AbstractIndexCreationTask.cs
  src/Raven.Client/Documents/Indexes/IndexCreation.cs
  src/Raven.Client/Documents/Operations/MaintenanceOperationExecutor.cs
  src/Raven.Client/Documents/Operations/OperationExecutor.cs
  src/Raven.Client/Documents/Queries/HashCalculator.cs
  src/Raven.Client/Documents/Subscriptions/DocumentSubscriptions.cs
  src/Raven.Client/Documents/Subscriptions/SubscriptionWorker.cs
  src/Raven.Client/Extensions/DocumentStoreExtensions.cs
  src/Raven.Server/Commercial/LicenseManager.cs
  src/Raven.Server/Documents/AttachmentsStorage.cs
  src/Raven.Server/Documents/ConflictsStorage.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Handlers/IndexHandler.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  src/Raven.Server/Documents/PeriodicBackup/Aws/RavenAwsS3Client.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackup.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
  src/Raven.Server/Documents/Queries/QueryBuilder.cs
  src/Raven.Server/Documents/Queries/RavenBooleanQuery.cs
  src/Raven.Server/Documents/Replication/ChangeVectorExtensions.cs
  src/Raven.Server/Documents/Replication/ConflictManager.cs
  src/Raven.Server/Documents/Replication/IncomingReplicationHandler.cs
  src/Raven.Server/Documents/Replication/ReplicationDocumentSender.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/Documents/Replication/ResolveConflictOnReplicationConfigurationChange.cs
  src/Raven.Server/Indexing/VoronIndexOutput.cs
  src/Raven.Server/Rachis/Leader.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
  src/Raven.Server/Web/System/BackupDatabaseHandler.cs
  src/Raven.Server/Web/System/OngoingTasksHandler.cs
  src/Raven.Studio/wwwroot/Content/css/styles-common.less
  src/Voron/Data/Compression/DecompressionBuffersPool.cs
  src/Voron/Debugging/StorageReportGenerator.cs
  src/Voron/Impl/Journal/LazyTransactionBuffer.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/StorageEnvironmentOptions.cs
  test/FastTests/Issues/RavenDB-11424.cs
  test/FastTests/Server/Basic/ChangeVectorConflictStatusTests.cs
  test/SlowTests/Blittable/SerializeAndDeserializeMergedTransactionCommandTests.cs
  test/SlowTests/Client/Attachments/AttachmentsReplication.cs
  test/SlowTests/Issues/RavenDB-10726.cs
  test/SlowTests/Issues/RavenDB-15754.cs
  test/SlowTests/Issues/RavenDB_13563.cs
  test/SlowTests/Issues/RavenDB_15163.cs
  test/SlowTests/Issues/RavenDB_15911.cs
  test/SlowTests/Issues/RavenDB_15935.cs
  test/SlowTests/Issues/RavenDB_15944.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Restore/RestoreFromAzure.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Restore/RestoreFromGoogleCloud.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Restore/RestoreFromS3.cs
  test/SlowTests/Server/Replication/ReplicationConflictsTests.cs
  test/SlowTests/Server/Replication/ReplicationSpecialCases.cs
  test/SlowTests/SlowTests/Issues/RavenDB-15859.cs
Labels: v5.1

#11523 RavenDB-15535 Investigate missing revisions from cluster tx
  src/Raven.Server/Documents/Replication/ReplicationDocumentSender.cs
  test/SlowTests/Issues/RavenDB-15535.cs
Labels: v4.2

#11530 RavenDB-15975 When we copy an encrypted page to in-memory buffer we n…
  src/Voron/Impl/Paging/CryptoPager.cs
  test/FastTests/Sparrow/EncryptionTests.cs
Labels: v5.0

#11529 RavenDB-15992 replacement of indexes cannot be interrupted - after indexes are replaced in collection of indexes the old index needs to be disposed
  src/Raven.Server/Documents/Indexes/IndexStore.cs
Labels: v4.2

#11532 4.2 to 5.0 merge
  bench/Regression.Benchmark/Regression.Benchmark.csproj
  src/Raven.Client/Documents/Smuggler/SmugglerResult.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  src/Raven.Server/Documents/Replication/ReplicationDocumentSender.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
  src/Raven.Server/Smuggler/Documents/StreamDestination.cs
  src/Raven.Server/Smuggler/Documents/StreamSource.cs
  test/BenchmarkTests/BenchmarkTests.csproj
  test/EmbeddedTests/EmbeddedTests.csproj
  test/FastTests/FastTests.csproj
  test/InterversionTests/InterversionTests.csproj
  test/LicenseTests/LicenseTests.csproj
  test/RachisTests/RachisTests.csproj
  test/SlowTests/Issues/RavenDB-15535.cs
  test/SlowTests/Server/Replication/ReplicationRevisionsTests.cs
  test/SlowTests/SlowTests.csproj
  test/StressTests/StressTests.csproj
  test/Tests.Infrastructure/RavenTestBase.cs
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
  tools/Raven.Migrator/Raven.Migrator.csproj
Labels: v5.0

#11533 5.0 to 5.1 merge
  libs/Lucene.Net.3.0.37.nupkg
  libs/Lucene.Net.3.0.38.nupkg
  src/Raven.Client/Documents/Indexes/IndexingOperation.cs
  src/Raven.Client/Documents/Indexes/IndexingPerformanceOperation.cs
  src/Raven.Client/Documents/Indexes/LuceneMergeDetails.cs
  src/Raven.Client/Documents/Indexes/StorageCommitDetails.cs
  src/Raven.Client/Documents/Smuggler/SmugglerResult.cs
  src/Raven.Server/Config/Categories/IndexingConfiguration.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  src/Raven.Server/Documents/Indexes/IndexingRunStats.cs
  src/Raven.Server/Documents/Indexes/IndexingStatsAggregator.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/IndexWriteOperation.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/LuceneIndexPersistence.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/LuceneIndexWriter.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/TimeTrackingIndexWriter.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/TimeTrackingSerialMergeScheduler.cs
  src/Raven.Server/Documents/Queries/RavenBooleanQuery.cs
  src/Raven.Server/Documents/Replication/ReplicationDocumentSender.cs
  src/Raven.Server/Indexing/LuceneVoronDirectory.cs
  src/Raven.Server/Indexing/VoronIndexOutput.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Server/ServerWide/TempCryptoStream.cs
  src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
  src/Raven.Server/Smuggler/Documents/StreamDestination.cs
  src/Raven.Server/Smuggler/Documents/StreamSource.cs
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexPerformance.ts
  src/Raven.Studio/wwwroot/App/views/database/indexes/indexPerformance.html
  src/Raven.Studio/wwwroot/Content/css/pages/index-performance.less
  src/Voron/Impl/Paging/CryptoPager.cs
  test/FastTests/Sparrow/EncryptionTests.cs
  test/SlowTests/Issues/RavenDB-15535.cs
  test/SlowTests/Issues/RavenDB_13972_encrypted.cs
  test/SlowTests/Server/Replication/ReplicationRevisionsTests.cs
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
  tools/Raven.Debug/Raven.Debug.csproj
  tools/Raven.Migrator/Raven.Migrator.csproj
Labels: v5.1

#11537 RavenDB-16001 Fix certificates view - support the case when a client …
  src/Raven.Studio/typescript/viewmodels/manage/certificates.ts
Labels: v5.1

#11536 RavenDB-16003 add cancellation tokens for quicker shutdown
  src/Raven.Client/Documents/Commands/GetRemoteTaskTopologyCommand.cs
  src/Raven.Client/Documents/Commands/GetTcpInfoForRemoteTaskCommand.cs
  src/Raven.Client/Http/RequestExecutor.cs
  src/Raven.Client/ServerWide/Commands/GetDatabaseTopologyCommand.cs
  src/Raven.Client/ServerWide/Commands/GetTcpInfoCommand.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
Labels: v4.2

#11539 4.2 to 5.0 merge
  src/Raven.Client/Documents/Commands/QueryCommand.cs
  src/Raven.Client/Documents/Queries/Facets/AggregationQuery.cs
  src/Raven.Client/Documents/Queries/HashCalculator.cs
  src/Raven.Client/Documents/Queries/IndexQuery.cs
  src/Raven.Client/Documents/Queries/Suggestions/SuggestionQuery.cs
  src/Raven.Client/Documents/Session/AbstractDocumentQuery.cs
  src/Raven.Client/Documents/Session/AsyncDocumentQuery.cs
  src/Raven.Client/Documents/Session/DocumentQuery.cs
  src/Raven.Client/Documents/Session/Operations/Lazy/LazyAggregationQueryOperation.cs
  src/Raven.Client/Documents/Session/Operations/Lazy/LazyQueryOperation.cs
  src/Raven.Client/Documents/Session/Operations/Lazy/LazySuggestionQueryOperation.cs
  src/Raven.Client/Json/Serialization/NewtonsoftJson/Internal/Converters/CachingJsonConverter.cs
  src/Raven.Client/ServerWide/Commands/GetDatabaseTopologyCommand.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/Extensions/RequestExecutorExtensions.cs
  test/SlowTests/Issues/RavenDB_15944.cs
Labels: v5.0

#11528 Avoid unnecessary scheduling of sync continuation on threadpool
  Raven.Client.Lightweight/Connection/Async/AsyncServerClient.cs
Labels: v3.5

#11542 5.0 to 5.1 merge
  src/Raven.Client/Documents/Commands/QueryCommand.cs
  src/Raven.Client/Documents/Queries/Facets/AggregationQuery.cs
  src/Raven.Client/Documents/Queries/HashCalculator.cs
  src/Raven.Client/Documents/Queries/IndexQuery.cs
  src/Raven.Client/Documents/Queries/Suggestions/SuggestionQuery.cs
  src/Raven.Client/Documents/Session/AbstractDocumentQuery.cs
  src/Raven.Client/Documents/Session/AsyncDocumentQuery.cs
  src/Raven.Client/Documents/Session/DocumentQuery.cs
  src/Raven.Client/Documents/Session/Operations/Lazy/LazyAggregationQueryOperation.cs
  src/Raven.Client/Documents/Session/Operations/Lazy/LazyQueryOperation.cs
  src/Raven.Client/Documents/Session/Operations/Lazy/LazySuggestionQueryOperation.cs
  src/Raven.Client/Http/RequestExecutor.cs
  src/Raven.Client/Json/Serialization/NewtonsoftJson/Internal/Converters/CachingJsonConverter.cs
  src/Raven.Client/ServerWide/Commands/GetDatabaseTopologyCommand.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/Includes/IncludeDocumentsCommand.cs
  src/Raven.Server/Documents/Queries/RavenBooleanQuery.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/Extensions/RequestExecutorExtensions.cs
  src/Raven.Server/Web/System/DatabasesDebugHandler.cs
  test/SlowTests/Issues/RavenDB_15944.cs
  tools/Raven.Debug/GCDump/EventPipeDotNetHeapDumper.cs
Labels: v5.1

#11547 RavenDB-15982 fixed issue with copying PAL and friends to MacOS package
  src/Directory.Build.props
  tools/Directory.Build.props
Labels: v5.1

#11550 RavenDB-16018 ignore if we cannot get file length because it was deleted
  test/SlowTests/Voron/Compaction/StorageCompactionTestsSlow.cs
Labels: v4.2

#11541 RavenDB-16011
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/LuceneDocumentConverterBase.cs
Labels: v5.0

#11481 RavenDB-15916 introduced global stack to EncryptionBuffersPool and aligned the code with JsonContextPoolBase
  src/Sparrow/Json/JsonContextPoolBase.cs
  src/Sparrow/Utils/CountingConcurrentStack.cs
  src/Voron/Impl/EncryptionBuffersPool.cs
Labels: v5.0

#11555 5.0 to 5.1 merge
  src/Raven.Client/Documents/Operations/DatabaseHealthCheckOperation.cs
  src/Raven.Client/Documents/Operations/GetOperationStateOperation.cs
  src/Raven.Client/Http/RequestExecutor.cs
  src/Raven.Server/Commercial/LicenseManager.cs
  src/Raven.Server/Commercial/SetupManager.cs
  src/Raven.Server/Config/Categories/ClusterConfiguration.cs
  src/Raven.Server/Documents/Handlers/Admin/RachisAdminHandler.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/LuceneDocumentConverterBase.cs
  src/Raven.Server/Program.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/Rachis/RachisLogHistory.cs
  src/Raven.Server/Rachis/RachisStateMachine.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterObserver.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Utils/ChangeVectorUtils.cs
  src/Raven.Server/Utils/Cli/RavenCli.cs
  src/Raven.Server/Web/Studio/LicenseHandler.cs
  src/Sparrow/Json/JsonContextPoolBase.cs
  src/Sparrow/Utils/CountingConcurrentStack.cs
  src/Voron/Impl/EncryptionBuffersPool.cs
  test/EmbeddedTests/SmugglerTests.cs
  test/FastTests/Server/Basic/ChangeVectorConflictStatusTests.cs
  test/FastTests/Voron/StorageTest.cs
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
  test/RachisTests/RavenDB-6602.cs
  test/SlowTests/Authentication/SetupCommands.cs
  test/SlowTests/Client/TimeSeries/Query/TimeSeriesDocumentQuery.cs
  test/SlowTests/Client/TimeSeries/Query/TimeSeriesLinqQuery.cs
  test/SlowTests/Client/TimeSeries/Query/TimeSeriesRawQuery.cs
  test/SlowTests/Issues/RavenDB_13732.cs
  test/SlowTests/Issues/RavenDB_15019.cs
  test/SlowTests/Issues/RavenDB_15409.cs
  test/SlowTests/Server/Documents/Indexing/Static/RavenDB_7691.cs
  test/SlowTests/Voron/Compaction/StorageCompactionTestsSlow.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v5.1

#11558 RavenDB-15955 Add support to save documents/indexes using ctrl + s.
  src/Raven.Studio/typescript/viewmodels/database/documents/editDocument.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/editIndex.ts
  src/Raven.Studio/typescript/viewmodels/database/patch/patch.ts
  src/Raven.Studio/typescript/viewmodels/database/query/query.ts
  src/Raven.Studio/wwwroot/App/views/database/patch/patch.html
  src/Raven.Studio/wwwroot/App/views/database/query/query.html
Labels: v5.1

#11557 RavenDB-16019 - set the MaxClauseCount for IIS
  Raven.Database/Server/RavenDBOptions.cs
  Raven.Database/Server/RavenDbServer.cs
Labels: v3.5

#11521 RavenDB-15499: Fix CanPassNodeTagToRestorePatchOperation test
  test/FastTests/Client/Subscriptions/SubscriptionsBasic.cs
  test/SlowTests/Issues/RavenDB-13735.cs
  test/SlowTests/Issues/RavenDB_13293.cs
  test/Tests.Infrastructure/RavenTestBase.cs
Labels: v4.2

#11560 RavenDB-16022 We can't assume that when we call DirectAdd on a value…
  src/Voron/Data/Fixed/FixedSizeTree.cs
  test/StressTests/Voron/LargeFixedSizeTreesStressCases.cs
Labels: v4.2

#11562 4.2 to 5.0 merge
  src/Raven.Client/Documents/Changes/DatabaseChanges.cs
  src/Raven.Client/Documents/Operations/MaintenanceOperationExecutor.cs
  src/Raven.Client/Documents/Operations/Operation.cs
  src/Raven.Client/Documents/Operations/OperationExecutor.Operations.cs
  src/Raven.Client/Documents/Smuggler/DatabaseSmuggler.cs
  src/Raven.Server/Documents/DocumentPutAction.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Replication/ChangeVectorParser.cs
  src/Raven.Server/Documents/Replication/IncomingReplicationHandler.cs
  src/Raven.Server/Documents/Replication/ResolveConflictOnReplicationConfigurationChange.cs
  src/Voron/Data/Fixed/FixedSizeTree.cs
  test/FastTests/Client/Subscriptions/SubscriptionsBasic.cs
  test/SlowTests/Cluster/ClusterTransactionTests.cs
  test/SlowTests/Issues/RavenDB-13735.cs
  test/SlowTests/Issues/RavenDB-15535.cs
  test/SlowTests/Issues/RavenDB_13293.cs
  test/StressTests/Voron/LargeFixedSizeTreesStressCases.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
  test/Tests.Infrastructure/RavenTestBase.cs
Labels: v5.0

#11566 RavenDB-15753 register additional assemblies by name and full name
  src/Raven.Server/Documents/Indexes/Static/IndexCompiler.cs
  test/SlowTests/Issues/RavenDB_15753.cs
Labels: v5.1

#11564 RavenDB-15511 tighten CanRemoveChangeVector test
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
  test/Tests.Infrastructure/RavenTestBase.cs
Labels: v4.2

#11563 RavenDB-15999 fortify tests
  test/SlowTests/Server/Replication/ReplicationRevisionsTests.cs
Labels: v4.2

#11556 RavenDB-15930: Long startup time with large transactions
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/StorageEnvironmentOptions.cs
  test/SlowTests/Issues/RavenDB_15930.cs
Labels: v4.2

#11567 4.2 to 5.0 merge
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/StorageEnvironmentOptions.cs
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
  test/SlowTests/Issues/RavenDB_15930.cs
  test/SlowTests/Server/Replication/ReplicationRevisionsTests.cs
  test/Tests.Infrastructure/RavenTestBase.cs
Labels: v5.0

#11568 5.0 to 5.1 merge
  src/Raven.Client/Documents/Changes/DatabaseChanges.cs
  src/Raven.Client/Documents/Operations/MaintenanceOperationExecutor.cs
  src/Raven.Client/Documents/Operations/Operation.cs
  src/Raven.Client/Documents/Operations/OperationExecutor.Operations.cs
  src/Raven.Client/Documents/Smuggler/DatabaseSmuggler.cs
  src/Raven.Server/Documents/DocumentPutAction.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Replication/ChangeVectorParser.cs
  src/Raven.Server/Documents/Replication/IncomingReplicationHandler.cs
  src/Raven.Server/Documents/Replication/ResolveConflictOnReplicationConfigurationChange.cs
  src/Voron/Data/Fixed/FixedSizeTree.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/StorageEnvironmentOptions.cs
  test/FastTests/Client/Subscriptions/SubscriptionsBasic.cs
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
  test/SlowTests/Cluster/ClusterTransactionTests.cs
  test/SlowTests/Issues/RavenDB-13735.cs
  test/SlowTests/Issues/RavenDB-15535.cs
  test/SlowTests/Issues/RavenDB_13293.cs
  test/SlowTests/Issues/RavenDB_15930.cs
  test/SlowTests/Server/Replication/ReplicationRevisionsTests.cs
  test/StressTests/Voron/LargeFixedSizeTreesStressCases.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
  test/Tests.Infrastructure/RavenTestBase.cs
Labels: v5.1

#11570 RavenDB-16026 Raspberry PI build does not copy PAL
  src/Directory.Build.props
  tools/Directory.Build.props
Labels: v5.1

#11572 RavenDB-16027: use manual flush in test
  test/SlowTests/Issues/RavenDB_15930.cs
Labels: v4.2

#11574 RavenDB-14634 fix debug endpoint to be a json
  src/Raven.Server/Documents/Handlers/Admin/RachisAdminHandler.cs
Labels: v4.2

#11573 4.2 to 5.0 merge
  src/Raven.Server/Documents/Includes/IncludeDocumentsCommand.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterObserver.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Utils/ChangeVectorUtils.cs
  test/SlowTests/Issues/RavenDB_13563.cs
  test/SlowTests/Issues/RavenDB_15930.cs
Labels: v5.0

#11576 5.0 to 5.1 merge
  src/Raven.Server/ServerWide/Maintenance/ClusterObserver.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Utils/ChangeVectorUtils.cs
  test/SlowTests/Issues/RavenDB_13563.cs
  test/SlowTests/Issues/RavenDB_15930.cs
Labels: v5.1

#11508 Async read and write support for counting stream
  Raven.Abstractions/Connection/CountingStream.cs
  Raven.Client.Lightweight/Connection/Implementation/HttpJsonRequest.cs
Labels: v3.5

#11538 ClusterAwareRequestExecuter schedule continuation synchronous
  Raven.Client.Lightweight/Connection/Request/ClusterAwareRequestExecuter.cs
Labels: v3.5

#11546 ResourceApiController make sure the delay task is canceled to avoid having the timers hang around when resourceStoreTask completes
  Raven.Database/Common/ResourceApiController.cs
Labels: v3.5

#11575 RavenDB-14947 Give better error message if trying to run update in qu…
  src/Raven.Studio/typescript/commands/database/patch/patchCommand.ts
  src/Raven.Studio/typescript/commands/database/query/queryCommand.ts
Labels: v5.0

#11580 4.2 to 5.0 merge
  src/Raven.Server/Documents/Handlers/Admin/RachisAdminHandler.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  test/SlowTests/Voron/Issues/RavenDB_13384.cs
Labels: v5.0

#11581 5.0 to 5.1 merge
  src/Raven.Server/Documents/Handlers/Admin/RachisAdminHandler.cs
  src/Raven.Studio/typescript/commands/database/patch/patchCommand.ts
  src/Raven.Studio/typescript/commands/database/query/queryCommand.ts
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  test/SlowTests/Voron/Issues/RavenDB_13384.cs
Labels: v5.1

#11583 RavenDB-16037 - Metadata projection doesn't return LastModified in the correct format
  src/Raven.Server/Documents/DocumentsStorage.cs
  test/SlowTests/Issues/RavenDB-16037.cs
Labels: v5.1

#11584 RavenDB-15899 Fix Load Query/Patch Dialogs Styling
  src/Raven.Studio/wwwroot/Content/css/pages/patch.less
Labels: v5.1

#11482 RavenDB-15936 fixed DirectoryNotFoundException
  src/Sparrow.Server/LowMemory/CheckPageFileOnHdd.cs
Labels: v4.2

#11509 Avoid GetWaiter ChunkedRemoteBulkInsertOperation
  Raven.Client.Lightweight/Document/ChunkedRemoteBulkInsertOperation.cs
Labels: v3.5

#11593 4.2 to 5.0 merge
  src/Raven.Client/Documents/Subscriptions/SubscriptionWorker.cs
  src/Raven.Client/ServerWide/Commands/TcpConnectionInfo.cs
  src/Raven.Server/Documents/DocumentPutAction.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Handlers/BatchRequestParser.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/LuceneDocumentConverterBase.cs
  src/Raven.Server/Documents/Indexes/Static/CurrentIndexingScope.cs
  src/Raven.Server/Documents/Indexes/Static/StaticIndexBase.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Sparrow.Server/LowMemory/CheckPageFileOnHdd.cs
  test/RachisTests/SubscriptionFailoverWIthWaitingChains.cs
  test/SlowTests/Issues/RavenDB-15983.cs
  test/SlowTests/Issues/RavenDB-16037.cs
  test/SlowTests/RavenDB-15796.cs
  test/StressTests/Voron/LargeFixedSizeTreesStressCases.cs
Labels: v5.0

#11595 5.0 to 5.1 merge
  src/Raven.Client/Documents/Subscriptions/SubscriptionWorker.cs
  src/Raven.Client/ServerWide/Commands/TcpConnectionInfo.cs
  src/Raven.Server/Documents/DocumentPutAction.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Handlers/BatchRequestParser.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/LuceneDocumentConverterBase.cs
  src/Raven.Server/Documents/Indexes/Static/CurrentIndexingScope.cs
  src/Raven.Server/Documents/Indexes/Static/StaticIndexBase.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Sparrow.Server/LowMemory/CheckPageFileOnHdd.cs
  test/RachisTests/SubscriptionFailoverWIthWaitingChains.cs
  test/SlowTests/Issues/RavenDB-15983.cs
  test/SlowTests/Issues/RavenDB-16037.cs
  test/SlowTests/RavenDB-15796.cs
  test/StressTests/Voron/LargeFixedSizeTreesStressCases.cs
Labels: v5.1

#11596 RavenDB-15837: fix and decrease running time of test
  test/RachisTests/SubscriptionFailoverWIthWaitingChains.cs
Labels: v4.2

#11594 RavenDB-16041 JS map/reduce should support complex reduce keys
  src/Raven.Server/Documents/Indexes/Static/JavaScriptReduceOperation.cs
  test/SlowTests/Issues/RavenDB-16041.cs
Labels: v4.2

#11599 RavenDB-16034 fix MissingRevision3 test
  test/SlowTests/Issues/RavenDB-15535.cs
Labels: v4.2

#11602 RavenDB-16044 : Add typed API for time-series bulk insert
  src/Raven.Client/Documents/BulkInsert/BulkInsertOperation.cs
  test/SlowTests/Client/TimeSeries/BulkInsert/BulkInsert.cs
  test/SlowTests/Client/TimeSeries/BulkInsert/TypedBulkInsert.cs
Labels: v5.1

#11597 RavenDB-15879 Adding standard deviation of 100MB to swap size check
  src/Raven.Server/ServerWide/ServerStore.cs
  test/SlowTests/Server/NotificationCenter/NotificationCenterTests.cs
Labels: v4.2

#11604 4.2 to 5.0 merge
  src/Raven.Client/Documents/Queries/RavenQuery.cs
  src/Raven.Client/Util/JavascriptConversionExtensions.cs
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/Indexes/CollectionOfBloomFilters.cs
  src/Raven.Server/Documents/Indexes/Static/JavaScriptReduceOperation.cs
  src/Raven.Studio/typescript/common/abstractWebSocketClient.ts
  src/Raven.Studio/typescript/common/adminLogsWebSocketClient.ts
  src/Raven.Studio/typescript/common/eventsWebSocketClient.ts
  src/Raven.Studio/typescript/common/trafficWatchWebSocketClient.ts
  src/Raven.Studio/typescript/viewmodels/manage/adminLogs.ts
  src/Raven.Studio/typescript/viewmodels/manage/trafficWatch.ts
  src/Raven.Studio/wwwroot/App/views/manage/adminLogs.html
  src/Raven.Studio/wwwroot/App/views/manage/trafficWatch.html
  src/Raven.Studio/wwwroot/Content/css/pages/admin-logs.less
  test/FastTests/Server/Documents/Indexing/BloomFilterTests.cs
  test/RachisTests/SubscriptionFailoverWIthWaitingChains.cs
  test/SlowTests/Issues/RavenDB-15535.cs
  test/SlowTests/Issues/RavenDB-16038.cs
  test/SlowTests/Issues/RavenDB-16041.cs
  test/StressTests/Issues/RavenDB_15780.cs
Labels: v5.0

#11605 5.0 to 5.1 merge
  src/Raven.Client/Documents/Queries/RavenQuery.cs
  src/Raven.Client/Util/JavascriptConversionExtensions.cs
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/Indexes/CollectionOfBloomFilters.cs
  src/Raven.Server/Documents/Indexes/Static/JavaScriptReduceOperation.cs
  src/Raven.Studio/typescript/common/abstractWebSocketClient.ts
  src/Raven.Studio/typescript/common/adminLogsWebSocketClient.ts
  src/Raven.Studio/typescript/common/eventsWebSocketClient.ts
  src/Raven.Studio/typescript/common/trafficWatchWebSocketClient.ts
  src/Raven.Studio/typescript/viewmodels/manage/adminLogs.ts
  src/Raven.Studio/typescript/viewmodels/manage/trafficWatch.ts
  src/Raven.Studio/wwwroot/App/views/manage/adminLogs.html
  src/Raven.Studio/wwwroot/App/views/manage/trafficWatch.html
  src/Raven.Studio/wwwroot/Content/css/pages/admin-logs.less
  test/FastTests/Server/Documents/Indexing/BloomFilterTests.cs
  test/RachisTests/SubscriptionFailoverWIthWaitingChains.cs
  test/SlowTests/Issues/RavenDB-15535.cs
  test/SlowTests/Issues/RavenDB-16038.cs
  test/SlowTests/Issues/RavenDB-16041.cs
  test/StressTests/Issues/RavenDB_15780.cs
Labels: v5.1
