Repository ravendb/ravendb, pull requests merged in 2020-08, with the labels that each got.

#10961 RavenDB-14724 Delete revisions when deleting a document
  src/Raven.Server/Documents/DocumentsStorage.cs
  test/SlowTests/Issues/RavenDB-14724.cs
Labels: v4.2

#10960 RavenDB-13536 Custom analyzer is not preserved in index edit
  src/Raven.Studio/typescript/models/database/index/indexFieldOptions.ts
Labels: v5.1

#10959 RavenDB-15323 Put Compare Exchange Tombstones below the Compare Exchange
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/smugglerDatabaseDetails.ts
Labels: v5.0

#10957 RavenDB-15457 Allow to disable admin-channel / logstream in system co…
  src/Raven.Server/Config/Categories/ServerConfiguration.cs
  src/Raven.Server/RavenServer.cs
Labels: v5.0

#10956 RavenDB-15445 Notification Center Position Fix
  src/Raven.Studio/wwwroot/Content/css/notification-center.less
Labels: v5.1

#10967 RavenDB-12895 Database Import does not mark failed index as skipped o…
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/smugglerDatabaseDetails.ts
  src/Raven.Studio/wwwroot/App/views/common/notificationCenter/detailViewer/operations/smugglerDatabaseDetails.html
  src/Raven.Studio/wwwroot/Content/css/pages/export-progress.less
Labels: v5.1

#10965 RavenDB-15440 NRE when getting counter which doesn't exist
  src/Raven.Client/Documents/Session/AsyncSessionDocumentCounters.cs
  test/SlowTests/Issues/RavenDB-15440.cs
Labels: v5.0

#10930 RavenDB-15370 Better error message when HUB database is disabled
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
Labels: v4.2

#10968 RavenDB-15465 Delete log for index operation and handle references
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/IndexWriteOperation.cs
  src/Raven.Server/Documents/Indexes/Workers/HandleReferences.cs
Labels: v4.2

#10970 RavenDB-15460 setting index priority
  src/Raven.Client/Documents/Indexes/AbstractIndexCreationTask.cs
  src/Raven.Client/Documents/Indexes/AbstractJavaScriptIndexCreationTask.cs
  src/Raven.Client/Documents/Indexes/AbstractMultiMapIndexCreationTask.cs
  test/SlowTests/Issues/RavenDB_15460.cs
Labels: v4.2

#10972 4.2 to 5.0 merge
  src/Raven.Client/Documents/Indexes/AbstractIndexCreationTask.cs
  src/Raven.Client/Documents/Indexes/AbstractJavaScriptIndexCreationTask.cs
  src/Raven.Client/Documents/Indexes/AbstractMultiMapIndexCreationTask.cs
  src/Raven.Client/Documents/Indexes/Counters/AbstractCountersIndexCreationTask.cs
  src/Raven.Client/Documents/Indexes/Counters/AbstractMultiMapCountersIndexCreationTask.cs
  src/Raven.Client/Documents/Indexes/TimeSeries/AbstractMultiMapTimeSeriesIndexCreationTask.cs
  src/Raven.Client/Documents/Indexes/TimeSeries/AbstractTimeSeriesIndexCreationTask.cs
  src/Raven.Client/Documents/Operations/IOperationProgress.cs
  src/Raven.Client/Documents/Operations/OngoingTasks/GetTaskInfoResult.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Handlers/BulkInsertHandler.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/IndexWriteOperation.cs
  src/Raven.Server/Documents/Indexes/Workers/HandleReferences.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackup.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  test/FastTests/Client/FirstClassPatch.cs
  test/SlowTests/Issues/RavenDB-14724.cs
  test/SlowTests/Issues/RavenDB_15460.cs
Labels: v5.0

#10976 RavenDB-15445 Notification Center Position Fix
  src/Raven.Studio/wwwroot/Content/css/notification-center.less
Labels: v5.0

#10975 RavenDB-15378 Counter value validation
  src/Raven.Studio/typescript/viewmodels/database/documents/setCounterDialog.ts
  src/Raven.Studio/wwwroot/App/views/database/documents/setCounterDialog.html
Labels: v5.0

#10983 RavenDB-15454 adjusting test
  test/SlowTests/Issues/RavenDB_13759.cs
Labels: v5.0

#10969 RavenDB-15469 - @expires and @refresh can be both defined in the metadata
  src/Raven.Server/Documents/Expiration/ExpirationStorage.cs
  test/SlowTests/Server/Documents/Expiration/ExpirationTests.cs
Labels: v4.2

#10977 RavenDB-15081: Fix attachment stream getting deleted while not all re…
  src/Raven.Server/Documents/AttachmentsStorage.cs
  src/Raven.Server/Documents/Replication/IncomingReplicationHandler.cs
  test/SlowTests/Server/Replication/ReplicationBasicTestsSlow.cs
Labels: v4.2

#10985 4.2 to 5.0 merge
  src/Raven.Server/Config/Categories/IndexingConfiguration.cs
  src/Raven.Server/Documents/AttachmentsStorage.cs
  src/Raven.Server/Documents/Expiration/ExpirationStorage.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/IndexingStatsAggregator.cs
  src/Raven.Server/Documents/Replication/IncomingReplicationHandler.cs
  src/Raven.Server/Rachis/AppendEntriesResponse.cs
  src/Raven.Server/Rachis/Follower.cs
  src/Raven.Server/Rachis/FollowerAmbassador.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/Rachis/Remote/RemoteConnection.cs
  test/SlowTests/Server/Documents/Expiration/ExpirationTests.cs
  test/SlowTests/Server/Replication/ReplicationBasicTestsSlow.cs
Labels: v5.0

#10989 RavenDB-15480 Expose the Managed Allocation Size in Indexing Performance
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexPerformance.ts
  src/Raven.Studio/wwwroot/Content/css/pages/index-performance.less
Labels: v4.2

#10990 5.0 to 5.1 merge
  src/Raven.Server/Config/Categories/IndexingConfiguration.cs
  src/Raven.Server/Documents/AttachmentsStorage.cs
  src/Raven.Server/Documents/Expiration/ExpirationStorage.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/IndexingStatsAggregator.cs
  src/Raven.Server/Documents/Indexes/Workers/HandleCompareExchangeReferences.cs
  src/Raven.Server/Documents/Indexes/Workers/HandleReferences.cs
  src/Raven.Server/Documents/Replication/IncomingReplicationHandler.cs
  src/Raven.Server/Documents/Subscriptions/SubscriptionStorage.cs
  src/Raven.Server/Documents/TcpHandlers/SubscriptionConnection.cs
  src/Raven.Server/Rachis/AppendEntriesResponse.cs
  src/Raven.Server/Rachis/Follower.cs
  src/Raven.Server/Rachis/FollowerAmbassador.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/Rachis/Remote/RemoteConnection.cs
  src/Raven.Server/ServerWide/Commands/Subscriptions/AcknowledgeSubscriptionBatchCommand.cs
  src/Raven.Studio/typescript/viewmodels/database/documents/setCounterDialog.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexPerformance.ts
  src/Raven.Studio/wwwroot/App/views/database/documents/setCounterDialog.html
  src/Raven.Studio/wwwroot/Content/css/pages/index-performance.less
  test/SlowTests/Client/Subscriptions/LimitSubscriptionsConnectionsAmount.cs
  test/SlowTests/Client/Subscriptions/SubscriptionsBasic.cs
  test/SlowTests/Issues/RavenDB_13759.cs
  test/SlowTests/Issues/RavenDB_15493.cs
  test/SlowTests/Server/Documents/Expiration/ExpirationTests.cs
  test/SlowTests/Server/Replication/ReplicationBasicTestsSlow.cs
Labels: v5.1

#10987 RavenDB-15492 Allow to invoke OnBeforeDelete when we call Delete…
  src/Raven.Client/Documents/Commands/Batches/DeleteCommandData.cs
  src/Raven.Client/Documents/DocumentStoreBase.cs
  src/Raven.Client/Documents/Session/InMemoryDocumentSessionOperations.cs
  test/SlowTests/Issues/RavenDB-15492.cs
Labels: v5.1

#10991 RavenDB-15497 - Infinite loop when timeout is exceeded in WaitForIndexesAfterSaveChanges
  src/Raven.Server/Documents/Handlers/BatchHandler.cs
Labels: v4.2

#10995 4.2 to 5.0 merge
  src/Raven.Server/Documents/Handlers/BatchHandler.cs
  test/SlowTests/Issues/RavenDB-8451.cs
Labels: v5.0

#10996 5.0 to 5.1 merge
  src/Raven.Server/Config/Categories/ConfigurationCategory.cs
  src/Raven.Server/Config/ConfigurationEntryValue.cs
  src/Raven.Server/Documents/Handlers/BatchHandler.cs
  test/SlowTests/DatabaseSettings/SettingsJson.cs
  test/SlowTests/Issues/RavenDB-8451.cs
Labels: v5.1

#10998 RavenDB-15497 - add a test
  test/SlowTests/Issues/RavenDB-15497.cs
Labels: v4.2

#10992 RavenDB-9548 switched from DJV to BlittableJsonWriter when building map-result
  src/Raven.Client/Json/Serialization/NewtonsoftJson/Internal/BlittableJsonWriter.cs
  src/Raven.Server/Documents/Indexes/MapReduce/Static/MapReduceIndex.cs
Labels: v5.1

#10999 RavenDB-13732 added attachmentsFor support to JS indexes
  src/Raven.Server/Documents/Indexes/Static/JavaScriptIndex.cs
  src/Raven.Server/Documents/ObjectInstanceBase.cs
  src/Raven.Server/Documents/Patch/AttachmentNameObjectInstance.cs
  src/Raven.Server/Documents/Patch/AttachmentObjectInstance.cs
  src/Raven.Server/Documents/Patch/JavaScriptUtils.cs
  test/SlowTests/Issues/RavenDB_13732.cs
Labels: v5.1

#11000 RavenDB-15443: Subscription worker should reconnect when subscription…
  src/Raven.Client/Documents/Subscriptions/SubscriptionWorker.cs
  src/Raven.Client/Exceptions/Documents/Subscriptions/SubscriptionClosedException.cs
  src/Raven.Server/Documents/Subscriptions/SubscriptionStorage.cs
  src/Raven.Server/Documents/TcpHandlers/SubscriptionConnection.cs
  test/SlowTests/Client/Subscriptions/RavenDB_7384.cs
Labels: v4.2

#10993 RavenDB-15443: Subscription worker should reconnect when subscription…
  src/Raven.Client/Documents/Subscriptions/SubscriptionWorker.cs
  src/Raven.Client/Exceptions/Documents/Subscriptions/SubscriptionClosedException.cs
  src/Raven.Server/Documents/Subscriptions/SubscriptionStorage.cs
  src/Raven.Server/Documents/TcpHandlers/SubscriptionConnection.cs
  test/SlowTests/Client/Subscriptions/RavenDB_7384.cs
  test/SlowTests/Client/Subscriptions/SubscriptionsBasic.cs
Labels: v5.0

#11001 RavenDB-7070 fixing warnings
  src/Raven.Client/Documents/Operations/Replication/PullReplicationDefinition.cs
  src/Raven.Server/Documents/Handlers/PullReplicationHandler.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/RavenServer.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/Web/System/TcpConnectionInfoHandler.cs
  test/SlowTests/Issues/FilteredReplicationTests.cs
  test/StressTests/Server/Replication/PullReplicationStressTests.cs
Labels: v5.1

#11006 RavenDB-15503 always try to remove database and index directories because Voron is creating temp ones
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  src/Raven.Server/Web/System/DatabaseHelper.cs
  test/EmbeddedTests/TestDriver/TestDriverExampleTest.cs
Labels: v4.2

#11009 4.2 to 5.0 merge
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  src/Raven.Server/Web/System/DatabaseHelper.cs
  test/EmbeddedTests/TestDriver/TestDriverExampleTest.cs
Labels: v5.0

#10902 RavenDB-15339 set 15 seconds default timeout
  src/Raven.Client/Documents/Commands/GetRemoteTaskTopologyCommand.cs
  src/Raven.Client/Documents/Commands/GetTcpInfoForRemoteTaskCommand.cs
  src/Raven.Client/ServerWide/Commands/GetDatabaseTopologyCommand.cs
  src/Raven.Client/ServerWide/Commands/GetTcpInfoCommand.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  test/RachisTests/DatabaseCluster/ReplicationTests.cs
Labels: v5.0

#11002 RavenDB-15504 Lazy query - Invoke IDocumentStore.OnBeforeQuery
  src/Raven.Client/Documents/Session/AbstractDocumentQuery.cs
  src/Raven.Client/Documents/Session/AsyncDocumentQuery.cs
  src/Raven.Client/Documents/Session/DocumentQuery.cs
  test/SlowTests/MailingList/Apo/Lazy.cs
Labels: v4.2

#11018 RavenDB-15505 fix NRE when calling TimeSeriesOperations for different database
  src/Raven.Client/Documents/TimeSeries/TimeSeriesOperations.cs
  test/SlowTests/Client/TimeSeries/Session/TimeSeriesTypedSessionTests.cs
Labels: v5.0

#11017 RavenDB-15472 Out of memory when exporting database
  src/Raven.Server/Utils/Enumerators/PulsedTransactionEnumerator.cs
Labels: v5.0

#11020 RavenDB-15353 fix edge case for UTC midnight
  test/SlowTests/Smuggler/SmugglerApiTests.cs
Labels: v5.0

#11022 4.2 to 5.0 merge
  src/Raven.Client/Documents/Session/AbstractDocumentQuery.cs
  src/Raven.Client/Documents/Session/AsyncDocumentQuery.cs
  src/Raven.Client/Documents/Session/DocumentQuery.cs
  src/Raven.Server/RavenServer.cs
  src/Raven.Server/Web/System/DatabasesHandler.cs
  test/RachisTests/SubscriptionFailoverWIthWaitingChains.cs
  test/SlowTests/Issues/RavenDB_15477.cs
  test/SlowTests/MailingList/Apo/Lazy.cs
Labels: v5.0

#11028 RavenDB-15177 fix splitting counters with unicode
  src/Raven.Server/Documents/CountersStorage.cs
  test/SlowTests/Client/Counters/CountersReplication.cs
Labels: v4.2

#11026 RavenDB-15512 We need to send throwOnTimeoutInWaitForReplicas in quer…
  src/Raven.Client/Documents/Commands/Batches/BatchCommand.cs
  test/SlowTests/Issues/RavenDB_15512.cs
Labels: v4.2

#11025 RavenDB-15353 baseline should have 0 seconds
  test/SlowTests/Smuggler/SmugglerApiTests.cs
Labels: v5.0

#11021 RavenDB-15486 reduce Thread.Sleep time
  test/FastTests/Server/Replication/ReplicationTestBase.cs
Labels: v5.0

#11029 RavenDB-15513 BlittableJsonReaderObject.GetHashCode cause a LOT of co…
  src/Sparrow/Json/BlittableJsonReaderObject.cs
  test/FastTests/Blittable/BlittableJsonEqualityTests.cs
  test/Tryouts/Program.cs
Labels: v5.0

#11030 RavenDB-15514 fix conflict between new and deleted counter
  src/Raven.Server/Documents/CountersStorage.cs
  test/SlowTests/Client/Counters/CountersReplication.cs
Labels: v4.2

#11036 RavenDB-15521 be sure that CV is applied to the metadata
  src/Raven.Client/Documents/Session/Operations/BatchOperation.cs
  test/SlowTests/Issues/RavenDB_15521.cs
Labels: v4.2

#11037 4.2 to 5.0 merge
  src/Raven.Client/Documents/Commands/Batches/BatchCommand.cs
  src/Raven.Client/Documents/DocumentStoreBase.cs
  src/Raven.Client/Documents/Session/Events.cs
  src/Raven.Client/Documents/Session/Operations/BatchOperation.cs
  src/Raven.Client/Http/RavenCommand.cs
  src/Raven.Client/Http/RequestExecutor.cs
  src/Raven.Server/Documents/CountersStorage.cs
  src/Raven.Server/Documents/Handlers/CountersHandler.cs
  src/Raven.Server/Documents/PeriodicBackup/BackupTask.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreBackupTaskBase.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreFromAzure.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreFromGoogleCloud.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreFromLocal.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreFromS3.cs
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterObserver.cs
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
  test/FastTests/Client/RequestExecutorTests.cs
  test/SlowTests/Client/Counters/CountersReplication.cs
  test/SlowTests/Issues/RavenDB-15080.cs
  test/SlowTests/Issues/RavenDB_15512.cs
  test/SlowTests/Issues/RavenDB_15521.cs
  test/SlowTests/Server/Documents/PeriodicBackup/RavenDB-11139.cs
Labels: v5.0

#11039 RavenDB-15525: PeriodicBackupStatus ToJson method is missing UploadToFtp
  src/Raven.Client/Documents/Operations/Backups/PeriodicBackupStatus.cs
Labels: v4.2

#11042 RavenDB-15527 make GetCompareExchangeValuesOperation(string[] keys) ctor public
  src/Raven.Client/Documents/Operations/CompareExchange/GetCompareExchangeValuesOperation.cs
Labels: v5.0

#11033 RavenDB-15518 Deserialization of 'HubName' when creating Sink Task
  src/Raven.Client/Documents/Operations/Replication/PullReplicationAsSink.cs
Labels: v5.1

#11047 RavenDB-15517: fix deadlock in PeriodicBackupRunner
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackup.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
Labels: v4.2

#11052 RavenDB-14799 throw if database is already faulted
  src/Raven.Server/Documents/DatabasesLandlord.cs
Labels: v4.2

#11051 RavenDB-15047 - apply the fix only for .NET Core (lose type information when using ToArray)
  Raven.Client.Lightweight/Indexes/ExpressionStringBuilder.cs
Labels: v3.5

#11054 4.2 to 5.0 merge
  src/Raven.Server/Commercial/LicenseHelper.cs
  src/Raven.Server/Commercial/LicenseManager.cs
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackup.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
  src/Raven.Server/Program.cs
  src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
  src/Raven.Server/Smuggler/Documents/DatabaseSmuggler.cs
  test/SlowTests/SlowTests.csproj
  test/SlowTests/Smuggler/Data/DocumentWithRevisions.ravendbdump
  test/SlowTests/Smuggler/Data/RevisionsWithoutADocument.ravendbdump
  test/SlowTests/Smuggler/LegacySmugglerTests.cs
Labels: v5.0

#11061 RavenDB-15545 sign Lucene
  libs/Lucene.Net.3.0.33.nupkg
  libs/Lucene.Net.3.0.34.nupkg
  src/Raven.Server/Raven.Server.csproj
Labels: v4.2

#11055 RavenDB-15536 Typo in message on Studio
  src/Raven.Studio/typescript/commands/resources/saveServerWideBackupCommand.ts
Labels: v5.0

#11065 RavenDB-15532 fix upload categories order
  scripts/upload.ps1
Labels: v5.0
