Repository ravendb/ravendb, pull requests merged in 2020-01, with the labels that each got.

#10010 RavenDB-14119: Add more assets to failing test
  test/SlowTests/Issues/RavenDB_13293.cs
Labels: v4.2

#10011 RavenDB-14420 Fix NextIdentityForOperationShouldBroadcastAndFail
  test/SlowTests/Cluster/ClusterOperationTests.cs
Labels: v4.2

#10012 RavenDB-14395 fix CleanTombstonesInTheClusterWithBackup
  test/SlowTests/Server/Replication/ReplicationCleanTombstones.cs
Labels: v4.2

#10018 4.2 to 5.0 merge
  src/Raven.Server/Documents/DocumentPutAction.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
  src/Sparrow/Json/LazyStringValue.cs
  test/SlowTests/Issues/RavenDB_11664.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Restore/RestoreFromAzure.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Restore/RestoreFromS3.cs
  test/SlowTests/Server/Documents/PeriodicBackup/ServerWideBackup.cs
  test/SlowTests/Server/Replication/ReplicationCleanTombstones.cs
Labels: v5.0

#10022 RavenDB-14421: cluster in test should be created with shouldRunInMemory: fals…
  test/RachisTests/SubscriptionFailoverWIthWaitingChains.cs
Labels: v4.2

#10020 RavenDB-13562 Adding flushed journal to reports
  src/Voron/Debugging/DetailedStorageReport.cs
  src/Voron/Debugging/StorageReportGenerator.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/StorageEnvironment.cs
Labels: v4.2

#10021 RavenDB-14419 Null propagation operator (??) in C# indexes is inconsi…
  src/Raven.Server/Documents/Indexes/Static/Roslyn/MapFunctionProcessor.cs
  src/Raven.Server/Documents/Indexes/Static/Roslyn/Rewriters/CoalesceRewriter.cs
  src/Raven.Server/Documents/Indexes/Static/Roslyn/Rewriters/ConditionalAccessExpressionRewriter.cs
  src/Raven.Server/Documents/Indexes/Static/Roslyn/Rewriters/ReduceIndex/ReduceFunctionProcessor.cs
  test/SlowTests/Issues/RavenDB-14419.cs
Labels: v4.2

#10013 RavenDB-14332 Allow to filter index that has errors
  src/Raven.Studio/typescript/models/database/index/index.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexes.ts
  src/Raven.Studio/typings/_studio/dto.d.ts
  src/Raven.Studio/wwwroot/App/views/database/indexes/indexes.html
Labels: v4.2

#10024 RavenDB-14425 Create icon for time series
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.eot
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.svg
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.ttf
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.woff
  src/Raven.Studio/wwwroot/Content/css/icons.less
Labels: v5.0

#10026 RavenDB-14444 - Missing error details for IndexWriteException
  src/Raven.Server/Documents/Indexes/IndexingRunStats.cs
Labels: v4.2

#10025 RavenDB-14443 - fix Concurrent access to HashSet in OutputReduceToCollectionActions
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  src/Raven.Server/Documents/Indexes/MapReduce/OutputToCollection/OutputReduceToCollectionActions.cs
Labels: v4.2

#10028 4.2 to 5.0 merge
  src/Raven.Client/Documents/Commands/QueryStreamCommand.cs
  src/Raven.Client/Documents/Commands/StreamCommand .cs
  src/Raven.Client/Documents/Operations/Attachments/GetAttachmentOperation.cs
  src/Raven.Client/Http/RavenCommand.cs
  src/Raven.Client/Util/StreamWithTimeout.cs
  src/Raven.Server/Documents/AttachmentsStorage.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Handlers/Debugging/NodeDebugHandler.cs
  src/Raven.Server/Documents/Indexes/IndexingRunStats.cs
  src/Raven.Server/Documents/Indexes/Static/JavaScriptIndexUtils.cs
  src/Raven.Server/Documents/Indexes/Static/Roslyn/MapFunctionProcessor.cs
  src/Raven.Server/Documents/Indexes/Static/Roslyn/Rewriters/CoalesceRewriter.cs
  src/Raven.Server/Documents/Indexes/Static/Roslyn/Rewriters/ConditionalAccessExpressionRewriter.cs
  src/Raven.Server/Documents/Indexes/Static/Roslyn/Rewriters/ReduceIndex/ReduceFunctionProcessor.cs
  src/Raven.Server/Documents/Patch/BlittableObjectInstance.cs
  src/Raven.Server/Documents/Patch/JavaScriptUtils.cs
  src/Raven.Server/Documents/PeriodicBackup/BackupTask.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
  src/Raven.Server/Documents/StreamsTempFile.cs
  src/Raven.Server/Rachis/Candidate.cs
  src/Raven.Server/Rachis/CandidateAmbassador.cs
  src/Raven.Server/Rachis/Elector.cs
  src/Raven.Server/Rachis/Follower.cs
  src/Raven.Server/Rachis/FollowerAmbassador.cs
  src/Raven.Server/Rachis/Leader.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/Rachis/Remote/RemoteConnection.cs
  src/Raven.Server/Rachis/Remote/SnapshotReader.cs
  src/Raven.Server/Web/RequestHandler.cs
  src/Raven.Studio/typescript/models/database/index/index.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexes.ts
  src/Raven.Studio/typings/_studio/dto.d.ts
  src/Raven.Studio/wwwroot/App/views/database/indexes/indexes.html
  src/Sparrow/Utils/TimeoutManager.cs
  src/Voron/Debugging/DetailedStorageReport.cs
  src/Voron/Debugging/StorageReportGenerator.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/StorageEnvironment.cs
  test/RachisTests/AddNodeToClusterTests.cs
  test/RachisTests/SubscriptionFailoverWIthWaitingChains.cs
  test/SlowTests/Blittable/SerializeAndDeserializeMergedTransactionCommandTests.cs
  test/SlowTests/Client/StreamingWithTimeout.cs
  test/SlowTests/Issues/RavenDB-14419.cs
  test/SlowTests/Issues/RavenDB-14439.cs
  test/SlowTests/Issues/RavenDB_14292.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
  test/StressTests/Server/Documents/PeriodicBackup/ServerWideBackupStress.cs
Labels: v5.0

#10029 Revert "RavenDB-14407 SelectFields should not mutate the original query"
  src/Raven.Client/Documents/Session/DocumentQuery.cs
  test/SlowTests/MailingList/FacetsAndDocQuery.cs
Labels: v4.2

#10031 RavenDB-14347 be more explicit to what address family we want to bind when creating TcpClient
  src/Raven.Client/Util/TcpUtils.cs
  test/Tests.Infrastructure/ProxyServer.cs
Labels: v4.2

#10032 RavenDB-14450 Making sure we that we don't delete entries while while…
  src/Raven.Server/Documents/DocumentsStorage.cs
  test/SlowTests/Issues/RavenDB_14450.cs
Labels: v4.2

#10034 RavenDB-13100 preserve time series names using document metadata
  src/Raven.Server/Documents/Handlers/TimeSeriesHandler.cs
Labels: v5.0

#10035 RavenDB-14384 tight the test
  test/SlowTests/Server/Replication/ReplicationCleanTombstones.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
Labels: v4.2

#10037 4.2 to 5.0 merge
  src/Raven.Client/Documents/Session/DocumentQuery.cs
  src/Raven.Client/Util/TcpUtils.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  src/Raven.Server/Documents/Indexes/MapReduce/OutputToCollection/OutputReduceToCollectionActions.cs
  src/Raven.Server/Rachis/CandidateAmbassador.cs
  src/Raven.Server/Rachis/FollowerAmbassador.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  test/SlowTests/Issues/RavenDB_14450.cs
  test/SlowTests/MailingList/FacetsAndDocQuery.cs
  test/SlowTests/Server/Replication/ReplicationCleanTombstones.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
  test/Tests.Infrastructure/ProxyServer.cs
  test/Tests.Infrastructure/RachisConsensusTestBase.cs
Labels: v5.0

#10039 RavenDB-14451
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Indexes/MapReduce/OutputToCollection/DeleteReduceOutputDocumentsCommand.cs
  src/Raven.Server/Documents/Indexes/MapReduce/OutputToCollection/OutputReduceToCollectionActions.cs
  src/Raven.Server/Documents/Indexes/MapReduce/OutputToCollection/OutputReduceToCollectionCommand.cs
  src/Raven.Server/Documents/Indexes/MapReduce/OutputToCollection/OutputReferencesPattern.cs
  test/SlowTests/Server/Documents/Indexing/MapReduce/RavenDB_12932.cs
  test/SlowTests/Server/Documents/Indexing/MapReduce/RavenDB_14451.cs
Labels: v4.2

#10042 RavenDB-14457 added the ability to configure HttpVersion via Conventions
  src/Raven.Client/Documents/Conventions/DocumentConventions.cs
  src/Raven.Client/Http/RequestExecutor.cs
Labels: v4.2

#10045 RavenDB-14461 Load should not throw when NoTracking is enabled and document do not exist on the server
  src/Raven.Client/Documents/Session/Operations/LoadOperation.cs
  src/Raven.Client/Documents/Session/Operations/LoadStartingWithOperation.cs
  test/SlowTests/Issues/RavenDB_14461.cs
Labels: v4.2

#10046 RavenDB-14437 tight the test ReplicationCleanTombstones.EtlTombstones…
  test/SlowTests/Server/Replication/ReplicationCleanTombstones.cs
  test/Tests.Infrastructure/RavenTestBase.cs
Labels: v4.2

#10048 RavenDB-14465 Projecting a null array fails
  src/Raven.Client/Documents/Session/Operations/QueryOperation.cs
  test/SlowTests/MailingList/ProjectioOfMissingProp.cs
Labels: v4.2

#10047 RavenDB-14281
  src/Raven.Client/Util/JavascriptConversionExtensions.cs
  test/SlowTests/Issues/RavenDB-14281.cs
Labels: v4.2

#10052 RavenDB-14466 - Side by side index is created after database restart
  src/Raven.Server/Extensions/JsonSerializationExtensions.cs
  test/SlowTests/Server/Documents/Indexing/MapReduce/RavenDB_12932.cs
Labels: v4.2

#10036 RavenDB-14393 - Index last etag is updated although the batch was canceled
  Raven.Database/Indexing/IndexingExecuter.cs
  Raven.Database/Indexing/ReducingExecuter.cs
Labels: v2.5

#10054 4.2 to 5.0 merge
  src/Raven.Client/Documents/Conventions/DocumentConventions.cs
  src/Raven.Client/Documents/Session/Operations/LoadOperation.cs
  src/Raven.Client/Documents/Session/Operations/LoadStartingWithOperation.cs
  src/Raven.Client/Documents/Session/Operations/QueryOperation.cs
  src/Raven.Client/Http/RequestExecutor.cs
  src/Raven.Client/Util/JavascriptConversionExtensions.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Indexes/MapReduce/OutputToCollection/DeleteReduceOutputDocumentsCommand.cs
  src/Raven.Server/Documents/Indexes/MapReduce/OutputToCollection/OutputReduceToCollectionActions.cs
  src/Raven.Server/Documents/Indexes/MapReduce/OutputToCollection/OutputReduceToCollectionCommand.cs
  src/Raven.Server/Documents/Indexes/MapReduce/OutputToCollection/OutputReferencesPattern.cs
  src/Raven.Server/Documents/Replication/IncomingReplicationHandler.cs
  src/Raven.Server/Documents/Replication/OutgoingReplicationHandler.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/Extensions/JsonSerializationExtensions.cs
  src/Raven.Server/Raven.Server.csproj
  test/RachisTests/DatabaseCluster/ReplicationTests.cs
  test/SlowTests/Issues/RavenDB-14272.cs
  test/SlowTests/Issues/RavenDB-14281.cs
  test/SlowTests/Issues/RavenDB_14461.cs
  test/SlowTests/MailingList/ProjectioOfMissingProp.cs
  test/SlowTests/Server/Documents/Indexing/MapReduce/RavenDB_12932.cs
  test/SlowTests/Server/Documents/Indexing/MapReduce/RavenDB_14451.cs
  test/SlowTests/Server/Replication/ReplicationCleanTombstones.cs
  test/Tests.Infrastructure/RavenTestBase.cs
  tools/Raven.Debug/Raven.Debug.csproj
  tools/Raven.Migrator/Raven.Migrator.csproj
Labels: v5.0

#10057 RavenDB-14436: cherry pick from RavenDB-14385
  test/SlowTests/Server/Documents/PeriodicBackup/Restore/RestoreFromGoogleCloud.cs
Labels: v4.2

#10051 RavenDB-14426 make the test master-master replication
  test/SlowTests/Client/TimeSeries/Issues/RavenDB-14426.cs
Labels: v5.0

#10049 RavenDB-14464: On operation initialization exchange the _result task …
  src/Raven.Client/Documents/Operations/Operation.cs
  test/StressTests/Issues/RavenDB_14464.cs
Labels: v4.2

#10060 RavenDB-14475 Allow to convert from generic subscription to non gener…
  src/Raven.Client/Documents/Subscriptions/DocumentSubscriptions.cs
  src/Raven.Client/Documents/Subscriptions/SubscriptionCriteria.cs
Labels: v4.2

#10053 Raven db 14462
  test/SlowTests/Issues/RavenDB-8451.cs
  tools/Voron.Recovery/CommandLineApp.cs
  tools/Voron.Recovery/Recovery.cs
  tools/Voron.Recovery/VoronRecoveryConfiguration.cs
Labels: v4.2

#10062 RavenDB-14477 EchoStream is blocking for the whole ReadTimeout period when reading from Google Storage
  src/Sparrow.Server/Utils/EchoStream.cs
Labels: v4.2

#10064 RavenDB-13655: Reduce number of concurrent threads in win-x86
  test/Tests.Infrastructure/TestBase.cs
Labels: v4.2

#10066 RavenDB-14479 - fix NRE
  src/Sparrow/Utils/NativeMemory.cs
Labels: v4.2

#10067 RavenDB-14422 stats are written in separate transaction so we need to wait for them to avoid a race
  test/SlowTests/Issues/RavenDB-14323.cs
Labels: v4.2

#10069 RavenDB-14236 disabled EnableHighTemporaryDirtyMemoryUse by default
  src/Raven.Server/Config/Categories/MemoryConfiguration.cs
Labels: v4.2

#10074 4.2 to 5.0 merge
  src/Raven.Client/Documents/Operations/Operation.cs
  src/Raven.Client/Documents/Subscriptions/DocumentSubscriptions.cs
  src/Raven.Client/Documents/Subscriptions/SubscriptionCriteria.cs
  src/Raven.Server/Config/Categories/MemoryConfiguration.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  src/Raven.Server/Documents/Indexes/IndexingStatsAggregator.cs
  src/Raven.Server/Documents/Indexes/MapReduce/OutputToCollection/DeleteReduceOutputDocumentsCommand.cs
  src/Raven.Server/Documents/Indexes/MapReduce/OutputToCollection/OutputReduceToCollectionActions.cs
  src/Raven.Server/Documents/Indexes/MapReduce/OutputToCollection/OutputReduceToCollectionCommand.cs
  src/Raven.Server/Documents/Indexes/MapReduce/Workers/CleanupDocumentsForMapReduce.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreBackupTaskBase.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.1/DatabaseOldestBackup.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.11/ServerCertificateExpiration.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.11/ServerCertificateExpirationLeft.cs
  src/Raven.Server/Monitoring/Snmp/SnmpOids.cs
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexes.ts
  src/Raven.Studio/wwwroot/App/views/database/indexes/indexes.html
  src/Sparrow.Server/Utils/EchoStream.cs
  src/Sparrow/Utils/NativeMemory.cs
  test/SlowTests/Issues/RavenDB-14323.cs
  test/SlowTests/Issues/RavenDB-8451.cs
  test/SlowTests/Server/Documents/Indexing/MapReduce/OutputReduceToCollectionTests.cs
  test/SlowTests/Server/Documents/Indexing/MapReduce/RavenDB_12932.cs
  test/SlowTests/Server/Documents/Indexing/MapReduce/RavenDB_14451.cs
  test/SlowTests/Server/Documents/PeriodicBackup/EncryptedBackupTest.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Restore/RestoreFromGoogleCloud.cs
  test/SlowTests/Server/Documents/PeriodicBackup/ServerWideBackup.cs
  test/StressTests/Issues/RavenDB_14464.cs
  test/Tests.Infrastructure/TestBase.cs
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
  tools/Raven.Migrator/Raven.Migrator.csproj
  tools/Voron.Recovery/CommandLineApp.cs
  tools/Voron.Recovery/Recovery.cs
  tools/Voron.Recovery/VoronRecoveryConfiguration.cs
Labels: v5.0

#10073 RavenDB-13921 updated to latest Jint
  libs/Jint.3.0.21-ravendb.nupkg
  libs/Jint.3.0.23-ravendb.nupkg
  src/Raven.Server/Documents/ETL/Providers/Raven/RavenEtlDocumentTransformer.cs
  src/Raven.Server/Documents/ETL/Providers/SQL/SqlDocumentTransformer.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/PropertyAccessor.cs
  src/Raven.Server/Documents/Indexes/Static/EsprimaVisitor.cs
  src/Raven.Server/Documents/Indexes/Static/JavaScriptIndex.cs
  src/Raven.Server/Documents/Indexes/Static/JavaScriptMapOperation.cs
  src/Raven.Server/Documents/Indexes/Static/JavaScriptReduceOperation.cs
  src/Raven.Server/Documents/Patch/BlittableObjectInstance.cs
  src/Raven.Server/Documents/Patch/JintNullPropagationReferenceResolver.cs
  src/Raven.Server/Documents/Patch/JsBlittableBridge.cs
  src/Raven.Server/Documents/Patch/PatchConflict.cs
  src/Raven.Server/Documents/Patch/ScriptRunner.cs
  src/Raven.Server/Documents/Patch/ScriptRunnerResult.cs
  src/Raven.Server/Documents/Queries/Results/QueryResultRetrieverBase.cs
  src/Raven.Server/Documents/TcpHandlers/SubscriptionDocumentsFetcher.cs
  src/Raven.Server/Raven.Server.csproj
Labels: v5.0

#10072 RavenDB-14448 added ForNode support to ServerOperationExecutor
  src/Raven.Client/ServerWide/Operations/ServerOperationExecutor.cs
  test/SlowTests/Issues/RavenDB_14448.cs
Labels: v4.2

#10076 RavenDB-14506 Handle reference - Optimization for reducing multiple necessary mapping + test
  src/Raven.Server/Documents/Indexes/IndexStorage.cs
  src/Raven.Server/Documents/Indexes/Static/CurrentIndexingScope.cs
  src/Raven.Server/Documents/Indexes/Workers/HandleReferences.cs
  test/SlowTests/Core/Indexing/ReferencedDocuments.cs
Labels: v4.2

#10081 RavenDB-6967 added the ability to delete index errors
  src/Raven.Client/Documents/Operations/Indexes/DeleteIndexErrorsOperation.cs
  src/Raven.Server/Documents/Handlers/IndexHandler.cs
  src/Raven.Server/Documents/Indexes/Errors/FaultyInMemoryIndex.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/IndexStorage.cs
  test/FastTests/Issues/RavenDB-13058.cs
  test/SlowTests/Issues/RavenDB_6967.cs
  test/Tests.Infrastructure/RavenTestBase.cs
Labels: v5.0

#10085 RavenDB-14525 - Adding 2 documents with case insensitive names creates 2 collections
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/DocumentsTransaction.cs
  test/FastTests/Issues/RavenDB-14525.cs
Labels: v4.2

#10087 RavenDB-14523: Increase timeout of ReshuffleAfterPromotion test
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
Labels: v4.2

#10088 4.2 to 5.0 merge
  src/CommonAssemblyInfo.cs
  src/Raven.Client/ServerWide/Operations/ServerOperationExecutor.cs
  src/Raven.Client/Util/StreamWithTimeout.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/DocumentsTransaction.cs
  src/Raven.Server/Documents/Indexes/IndexStorage.cs
  src/Raven.Server/Documents/Indexes/Static/CurrentIndexingScope.cs
  src/Raven.Server/Documents/Indexes/Static/TimeSeries/MapReduceTimeSeriesIndex.cs
  src/Raven.Server/Documents/Indexes/Workers/HandleReferences.cs
  src/Raven.Studio/typescript/commands/database/tasks/saveExternalReplicationTaskCommand.ts
  src/Raven.Studio/typescript/commands/database/tasks/savePeriodicBackupConfigurationCommand.ts
  src/Raven.Studio/typescript/common/generalUtils.ts
  src/Raven.Studio/typescript/common/shell/accessManager.ts
  src/Raven.Studio/typescript/common/shell/menu.ts
  src/Raven.Studio/typescript/common/shell/menu/items/manageServer.ts
  src/Raven.Studio/typescript/common/shell/menu/items/settings.ts
  src/Raven.Studio/typescript/common/shell/menu/leafMenuItem.ts
  src/Raven.Studio/typescript/viewmodels/database/settings/databaseRecord.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editExternalReplicationTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/ongoingTasks.ts
  src/Raven.Studio/typescript/viewmodels/manage/certificates.ts
  src/Raven.Studio/typescript/viewmodels/manage/serverWideBackupList.ts
  src/Raven.Studio/typescript/viewmodels/resources/manageDatabaseGroup.ts
  src/Raven.Studio/typings/_studio/dto.d.ts
  src/Raven.Studio/wwwroot/App/views/database/tasks/ongoingTasks.html
  src/Raven.Studio/wwwroot/App/views/shell.html
  src/Raven.Studio/wwwroot/App/views/shell/about.html
  src/Raven.Studio/wwwroot/Content/css/main-menu.less
  test/FastTests/Issues/RavenDB-14525.cs
  test/FastTests/RavenDB_14520.cs
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
  test/SlowTests/Core/Indexing/ReferencedDocuments.cs
  test/SlowTests/Issues/RavenDB_14448.cs
Labels: v5.0

#10086 RavenDB-13871 Copy Document ID
  src/Raven.Studio/typescript/viewmodels/database/documents/editDocument.ts
  src/Raven.Studio/wwwroot/App/views/database/documents/editDocument.html
  src/Raven.Studio/wwwroot/Content/css/pages/documents-edit.less
Labels: v4.2

#10092 RavenDB-14461
  src/Raven.Client/Documents/Session/Operations/Lazy/LazyLoadOperation.cs
  src/Raven.Client/Documents/Session/Operations/LoadOperation.cs
  test/SlowTests/Issues/RavenDB_14461.cs
Labels: v4.2

#10089 RavenDB-14527 Time series don't account for large time delta
  src/Raven.Server/Documents/TimeSeries/BitsBuffer.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesValuesSegment.cs
  test/SlowTests/Issues/RavenDB_14527.cs
Labels: v5.0

#10095 RavenDB-13765: throw (temporary) exception with details in case of Ca…
  src/Raven.Server/Documents/AttachmentsStorage.cs
  test/SlowTests/Issues/RavenDB-8451.cs
Labels: v4.2

#10096 4.2 to 5.0 merge
  src/Raven.Client/Documents/Session/Operations/Lazy/LazyLoadOperation.cs
  src/Raven.Client/Documents/Session/Operations/LoadOperation.cs
  src/Raven.Server/Documents/AttachmentsStorage.cs
  src/Raven.Studio/typescript/viewmodels/database/documents/editDocument.ts
  src/Raven.Studio/wwwroot/App/views/database/documents/editDocument.html
  src/Raven.Studio/wwwroot/Content/css/pages/documents-edit.less
  test/RachisTests/AddNodeToClusterTests.cs
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
  test/SlowTests/Issues/RavenDB-8451.cs
  test/SlowTests/Issues/RavenDB_12151.cs
  test/SlowTests/Issues/RavenDB_14461.cs
  test/StressTests/Rachis/AddNodeToClusterTests.cs
  test/StressTests/StressTests.csproj
Labels: v5.0

#10098 RavenDB-14500 Investigate why sometimes websocket disconnection is no…
  src/Raven.Studio/typescript/models/database/tasks/ongoingTaskBackupListModel.ts
Labels: v4.2

#10101 RavenDB-14422 we are expecting index errors in the test
  test/SlowTests/Issues/RavenDB-14323.cs
Labels: v4.2

#10103 RavenDB-14523 Fix test ReshuffleAfterPromotion
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
Labels: v4.2

#10107 RavenDB-14537 - Missing mapped reference document size in the stats
  src/Raven.Server/Documents/Indexes/Workers/HandleReferences.cs
Labels: v4.2

#10105 RavenDB-14535 - High unmanaged memory usage in a JavaScript index
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/JintLuceneDocumentConverter.cs
  src/Sparrow/Json/Parsing/ObjectJsonParser.cs
Labels: v4.2

#10106 RavenDB-14536 - TermsCachePerReader is never cleared
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/IndexedTerms.cs
Labels: v4.2

#10104 RavenDB-14236: Flushing occurs only when have something to write, so …
  src/Raven.Server/Config/Categories/MemoryConfiguration.cs
Labels: v4.2

#10109 4.2 to 5.0 merge
  src/Raven.Client/Http/RequestExecutor.cs
  src/Raven.Server/Config/Categories/SecurityConfiguration.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/JintLuceneDocumentConverter.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/IndexedTerms.cs
  src/Raven.Server/Documents/Indexes/Workers/HandleReferences.cs
  src/Raven.Server/Documents/TransactionOperationsMerger.cs
  src/Raven.Server/Https/ExternalCertificateValidator.cs
  src/Raven.Server/RavenServer.cs
  src/Raven.Server/Utils/DirectoryExecUtils.cs
  src/Raven.Studio/typescript/models/database/tasks/ongoingTaskBackupListModel.ts
  src/Sparrow/Json/Parsing/ObjectJsonParser.cs
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
  test/SlowTests/Issues/RavenDB-14323.cs
  test/SlowTests/Server/Documents/ETL/RavenDB_8866.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
Labels: v5.0

#10110 RavenDB-14540 use AsyncReaderWriterLock in DisposeLock
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/Rachis/Remote/RemoteConnection.cs
  src/Raven.Server/Raven.Server.csproj
  src/Sparrow.Server/Sparrow.Server.csproj
  src/Sparrow.Server/Utils/DisposeLock.cs
Labels: v4.2

#10113 4.2 to 5.0 merge
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/Rachis/Remote/RemoteConnection.cs
  src/Raven.Server/Raven.Server.csproj
  src/Sparrow.Server/Sparrow.Server.csproj
  src/Sparrow.Server/Utils/DisposeLock.cs
Labels: v5.0

#10112 RavenDB-14542 Support quoting for complex collection names
  src/Raven.Client/Documents/Session/Tokens/FromToken.cs
  test/SlowTests/Issues/RavenDB_14542.cs
Labels: v4.2

#10115 RavenDB-14159 fix RavenDB_14044 test to look only for the relevant ex…
  test/SlowTests/Cluster/ClusterMaintenanceTest.cs
Labels: v4.2

#10114 RavenDB-14395 tight CleanTombstonesInTheClusterWithBackup test
  test/SlowTests/Server/Replication/ReplicationCleanTombstones.cs
Labels: v4.2

#10117 4.2 to 5.0 merge
  src/Raven.Client/Documents/Session/Operations/QueryOperation.cs
  src/Raven.Client/Documents/Session/Tokens/FromToken.cs
  test/SlowTests/Cluster/ClusterMaintenanceTest.cs
  test/SlowTests/Issues/RavenDB_14542.cs
  test/SlowTests/Server/Replication/ReplicationCleanTombstones.cs
  test/SlowTests/Smuggler/RavenDB-14201.cs
  test/StressTests/Issues/RavenDB_12151.cs
Labels: v5.0

#10123 RavenDB-12989 Generate c# class uses latest revision for generating
  src/Raven.Studio/typescript/viewmodels/database/documents/editDocument.ts
  src/Raven.Studio/wwwroot/App/views/common/showDataDialog.html
  src/Raven.Studio/wwwroot/App/views/database/documents/editDocument.html
Labels: v4.2

#10118 RavenDB-14546 - Missing number of backup tasks
  src/Raven.Studio/wwwroot/App/views/database/tasks/ongoingTasks.html
Labels: v4.2

#10128 RavenDB-14421 fixed NRE
  test/RachisTests/SubscriptionFailoverWIthWaitingChains.cs
Labels: v4.2
