Repository ravendb/ravendb, pull requests merged in 2020-05, with the labels that each got.

#10500 Typo in 'documents'
  src/Raven.Studio/wwwroot/App/views/database/settings/refresh.html
Labels: v5.0

#10505 RavenDB-14365 use docId for time-series opertaions
  src/Raven.Client/Documents/Operations/TimeSeries/GetTimeSeriesOperation.cs
  src/Raven.Client/Documents/Operations/TimeSeries/TimeSeriesBatchOperation.cs
  src/Raven.Server/Documents/Handlers/TimeSeriesHandler.cs
  test/SlowTests/Client/TimeSeries/Issues/RavenDB-14633.cs
Labels: v5.0

#10509 RavenDB-14840 add github actions yaml to 4.2 branch
  .github/workflows/FastTests.yml
Labels: v4.2

#10506 RavenDB-14927 Time-series group by query should be aligned by the time unit
  src/Raven.Server/Documents/Queries/AST/Query.cs
  src/Raven.Server/Documents/Queries/Results/TimeSeriesRetriever.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesRollups.cs
  test/FastTests/Server/Documents/TimeSeriesRangeTests.cs
  test/SlowTests/Client/TimeSeries/Query/TimeSeriesLinqQuery.cs
Labels: v5.0

#10512 RavenDB-14365 use docId for time-series opertaions - studio part
  src/Raven.Studio/typescript/commands/database/documents/timeSeries/deleteTimeSeriesCommand.ts
  src/Raven.Studio/typescript/commands/database/documents/timeSeries/getTimeSeriesCommand.ts
  src/Raven.Studio/typescript/commands/database/documents/timeSeries/saveTimeSeriesCommand.ts
Labels: v5.0

#10513 HRINT-1620 fix timestamp servers error handling; use npm ci instead of
  scripts/buildProjects.ps1
  scripts/package.ps1
  scripts/sign.ps1
Labels: v4.2

#10510 RavenDB-14929 - Reduce the number of writes in Output Reduce to Collection
  src/Raven.Server/Documents/Indexes/MapReduce/OutputToCollection/OutputReduceToCollectionCommand.cs
  test/SlowTests/Server/Documents/Indexing/MapReduce/OutputReduceToCollectionTests.cs
Labels: v4.2

#10511 RavenDB-14931 Fix alignment issue on ARM with doubles
  src/Raven.Server/Documents/TimeSeries/StatefulTimeStampValue.cs
Labels: v5.0

#10516 RavenDB-10412 TempCryptoStream should not throw if we do not want to write or read anything to match the behavior of framework streams
  src/Raven.Server/ServerWide/TempCryptoStream.cs
  src/Raven.Server/Smuggler/Documents/StreamSource.cs
Labels: v5.0

#10518 RavenDB-14840 back to npm install
  scripts/buildProjects.ps1
Labels: v4.2

#10519 RavenDB-14926 support for creating index with Enumerable.Range in SelectMany
  src/Raven.Server/Documents/Indexes/Static/Roslyn/Rewriters/DynamicInvocationExpressionsRewriter.cs
  test/SlowTests/Issues/RavenDB_14926.cs
Labels: v4.2

#10523 4.2 to 5.0 merge
  scripts/buildProjects.ps1
  src/Raven.Server/Documents/Indexes/Static/Roslyn/Rewriters/DynamicInvocationExpressionsRewriter.cs
  src/Raven.Server/Documents/PeriodicBackup/Azure/RavenAzureClient.cs
  test/SlowTests/Issues/RavenDB_14926.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Azure.cs
Labels: v5.0

#10525 RavenDB-14949 don't verify time-series name upon replication
  src/Raven.Server/Documents/Replication/IncomingReplicationHandler.cs
Labels: v5.0

#10532 RavenDB-14924 commandDescription element for generateClientCert is wi…
  src/Raven.Server/Utils/Cli/RavenCli.cs
Labels: v4.2

#10531 RavenDB-14782 Different score returned from lucene for same documents
  libs/Lucene.Net.3.0.30.nupkg
  libs/Lucene.Net.3.0.31.nupkg
  src/Raven.Server/Raven.Server.csproj
Labels: v4.2

#10526 RavenDB-14948 Log retention time modified to check last write time to let hours resolution
  src/Sparrow/Logging/LoggingSource.cs
  test/SlowTests/SparrowTests/LoggingSourceTests.cs
  test/Tests.Infrastructure/RavenTestBase.cs
Labels: v4.2

#10535 RavenDB-14759 increase timeout
  src/Raven.Server/ServerWide/Maintenance/ClusterObserverLogEntry.cs
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
Labels: v4.2

#10538 4.2 to 5.0 merge
  libs/Lucene.Net.3.0.30.nupkg
  libs/Lucene.Net.3.0.31.nupkg
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Server/ServerWide/Maintenance/ClusterObserverLogEntry.cs
  src/Raven.Server/Smuggler/Documents/DatabaseSmuggler.cs
  src/Raven.Server/Utils/Cli/RavenCli.cs
  src/Sparrow/Logging/LoggingSource.cs
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
  test/SlowTests/Issues/RavenDB_5998.cs
  test/SlowTests/SlowTests.csproj
  test/SlowTests/Smuggler/Data/Document_Without_Attachment_Stream.ravendbdump
  test/SlowTests/Smuggler/Data/Identities_3.5.35288.ravendbdump
  test/SlowTests/Smuggler/Data/Indexes_And_Transformers_3.5.ravendbdump
  test/SlowTests/Smuggler/Data/Northwind_3.5.35168.ravendbdump
  test/SlowTests/Smuggler/Data/Revisions_3.5.35220.ravendbdump
  test/SlowTests/Smuggler/LegacySmugglerTests.cs
  test/SlowTests/Smuggler/RavenDB-12890.cs
  test/SlowTests/SparrowTests/LoggingSourceTests.cs
  test/Tests.Infrastructure/RavenTestBase.cs
Labels: v5.0

#10544 RavenDB-14942 Return empty list when object doesn't have time series
  src/Raven.Client/Documents/Session/InMemoryDocumentSessionOperations.cs
  test/SlowTests/Client/TimeSeries/Issues/RavenDB-13574.cs
  test/SlowTests/Client/TimeSeries/Session/TimeSeriesSessionTests.cs
  test/SlowTests/Smuggler/SmugglerApiTests.cs
Labels: v5.0

#10543 RavenDB-14827 generate new change vectors upon time-series import
  src/Raven.Server/Documents/Handlers/TimeSeriesHandler.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesStorage.cs
  test/SlowTests/Client/TimeSeries/Issues/RavenDB-14702.cs
Labels: v5.0

#10541 RavenDB-14634 fix tests
  test/FastTests/Client/Indexing/TimeSeries/BasicTimeSeriesIndexes.cs
  test/FastTests/Client/Queries/TimeSeries/BasicTimeSeriesQueries.cs
  test/SlowTests/Client/Indexing/TimeSeries/BasicTimeSeriesIndexes_MethodSyntax.cs
  test/SlowTests/Client/Indexing/TimeSeries/BasicTimeSeriesIndexes_MixedSyntax.cs
  test/SlowTests/Client/Indexing/TimeSeries/BasicTimeSeriesIndexes_StrongSyntax.cs
Labels: v5.0

#10539 RavenDB-14952 fixed NRE when doing full range facet query with alias when alias has the same name as one of the fields in index
  src/Raven.Server/Documents/Queries/QueryMetadata.cs
  test/SlowTests/Issues/RavenDB_14952.cs
Labels: v4.2

#10537 RavenDB-14790
  src/Sparrow/PeepingTomStream.cs
Labels: v5.0

#10550 RavenDB-14932 use UTF8Formatter
  src/Raven.Server/Documents/TimeSeries/TimeSeriesStorage.cs
Labels: v5.0

#10551 RavenDB-13947 Removing SqlEtlConfiguration.FactoryName in 5.0
  src/Raven.Client/Documents/Operations/ETL/SQL/SqlEtlConfiguration.cs
  src/Raven.Server/Documents/ETL/Providers/SQL/RelationalWriters/RelationalDatabaseWriter.cs
  src/Raven.Server/Documents/ETL/Providers/SQL/RelationalWriters/RelationalDatabaseWriterSimulator.cs
  src/Raven.Server/Web/System/OngoingTasksHandler.cs
Labels: v5.0

#10540 RavenDB-14964 allocate buffers from the pool and only for the indexing batch
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/AnonymousLuceneDocumentConverter.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/JintLuceneDocumentConverter.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/LuceneDocumentConverter.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/LuceneDocumentConverterBase.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/IndexWriteOperation.cs
  test/FastTests/Server/Documents/Indexing/Lucene/LuceneDocumentConverterTests.cs
  test/SlowTests/Tests/Indexes/LinqIndexesFromClient.cs
Labels: v4.2

#10548 RavenDB-14971 Add support for optional time ranges when quering time …
  src/Raven.Studio/typescript/commands/database/documents/timeSeries/getTimeSeriesCommand.ts
  src/Raven.Studio/typescript/viewmodels/database/timeSeries/editTimeSeries.ts
Labels: v5.0

#10534 RavenDB-14870
  src/Raven.Server/Documents/DocumentsTransaction.cs
  src/Raven.Server/Documents/Indexes/Auto/AutoIndexDocsEnumerator.cs
  src/Raven.Server/Documents/Indexes/IIndexedDocumentsEnumerator.cs
  src/Raven.Server/Documents/Indexes/Static/StaticIndexItemEnumerator.cs
  src/Raven.Server/Documents/Indexes/Workers/HandleReferences.cs
  src/Raven.Server/Documents/Indexes/Workers/MapItems.cs
  src/Voron/Data/Tables/Table.cs
  src/Voron/Impl/Transaction.cs
Labels: v5.0

#10542 RavenDB-14946 Expose TimeSeriesStatistics as client operation
  src/Raven.Client/Documents/Operations/TimeSeries/GetTimeSeriesStatisticsOperation.cs
  src/Raven.Client/Documents/Operations/TimeSeries/TimeSeriesStatistics.cs
  src/Raven.Client/Json/Converters/JsonDeserializationClient.cs
  src/Raven.Server/Documents/Handlers/TimeSeriesHandler.cs
  src/Raven.Studio/typescript/commands/database/documents/timeSeries/getTimeSeriesStatsCommand.ts
  test/SlowTests/Client/TimeSeries/Operations/TimeSeriesOperations.cs
  tools/TypingsGenerator/Program.cs
Labels: v5.0

#10552 RavenDB-14984 DirectoryStorageEnvironmentOptions.CreateJournalWriter …
  src/Sparrow/Utils/LazyWithExceptionRetry.cs
  src/Voron/StorageEnvironmentOptions.cs
Labels: v4.2

#10555 RavenDB-14972 Show all time-series related dates in UTC
  src/Raven.Studio/typescript/viewmodels/database/query/query.ts
  src/Raven.Studio/typescript/viewmodels/database/timeSeries/editTimeSeries.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/columnPreviewPlugin.ts
  src/Raven.Studio/typings/_studio/customTypings.d.ts
  src/Raven.Studio/wwwroot/App/views/database/timeSeries/editTimeSeries.html
  src/Raven.Studio/wwwroot/Content/css/pages/time-series-edit.less
Labels: v5.0

#10553 RavenDB-14923 Add support for cloud restore from Azure
  src/Raven.Studio/typescript/models/resources/creation/backupCredentials.ts
  src/Raven.Studio/typescript/models/resources/creation/databaseCreationModel.ts
  src/Raven.Studio/typings/_studio/dto.d.ts
  src/Raven.Studio/wwwroot/App/views/resources/createDatabase.html
Labels: v4.2

#10557 4.2 to 5.0 merge
  bench/Micro.Benchmark/Benchmarks/Hardware/Compare.cs
  bench/Micro.Benchmark/Benchmarks/Hardware/Diff.cs
  bench/Micro.Benchmark/Benchmarks/Hardware/Prefetch.cs
  bench/Micro.Benchmark/Benchmarks/Hardware/Prefetch2.cs
  bench/Micro.Benchmark/Benchmarks/Hardware/Search.cs
  bench/Micro.Benchmark/Benchmarks/LZ4/LZ4Benchmark.cs
  bench/Micro.Benchmark/Benchmarks/PageLocator/PlRandomRead.cs
  bench/Micro.Benchmark/Benchmarks/PageLocator/PlRandomWrite.cs
  bench/Micro.Benchmark/Benchmarks/Sorting/Sorting.cs
  bench/Micro.Benchmark/Micro.Benchmark.csproj
  bench/Regression.Benchmark/Regression.Benchmark.csproj
  bench/Voron.Benchmark/Voron.Benchmark.csproj
  src/Raven.Server/Documents/Handlers/IndexHandler.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/AnonymousLuceneDocumentConverter.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/JintLuceneDocumentConverter.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/LuceneDocumentConverter.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/LuceneDocumentConverterBase.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/IndexWriteOperation.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/LuceneIndexWriter.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/LuceneSuggestionIndexWriter.cs
  src/Raven.Server/Documents/Queries/QueryMetadata.cs
  src/Raven.Server/Indexing/LuceneVoronDirectory.cs
  src/Raven.Server/Indexing/VoronIndexOutput.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Server/Utils/ExceptionHelper.cs
  src/Raven.Studio/typescript/models/resources/creation/backupCredentials.ts
  src/Raven.Studio/typescript/models/resources/creation/databaseCreationModel.ts
  src/Raven.Studio/typings/_studio/dto.d.ts
  src/Raven.Studio/wwwroot/App/views/resources/createDatabase.html
  src/Sparrow.Server/Exceptions/DiskFullException.cs
  src/Sparrow/Utils/LazyWithExceptionRetry.cs
  src/Voron/StorageEnvironmentOptions.cs
  test/BenchmarkTests/BenchmarkTests.csproj
  test/EmbeddedTests/EmbeddedTests.csproj
  test/FastTests/FastTests.csproj
  test/FastTests/Server/Documents/Indexing/Lucene/LuceneDocumentConverterTests.cs
  test/InterversionTests/InterversionTests.csproj
  test/RachisTests/RachisTests.csproj
  test/SlowTests/Issues/RavenDB_14952.cs
  test/SlowTests/SlowTests.csproj
  test/SlowTests/Tests/Indexes/LinqIndexesFromClient.cs
  test/StressTests/StressTests.csproj
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
  test/Tryouts/Tryouts.csproj
  tools/Raven.Debug/Raven.Debug.csproj
  tools/Raven.Migrator/Raven.Migrator.csproj
Labels: v5.0

#10558 RavenDB-14964 do not hold the buffer in the reduce field
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/LuceneDocumentConverterBase.cs
Labels: v4.2

#10563 RavenDB-14993 - fix low memory handing in JsonContextPoolBase
  src/Sparrow/Json/JsonContextPoolBase.cs
Labels: v4.2

#10562 RavenDB-14986 support for setting field storage no and field indexing no in map-reduce
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/AnonymousLuceneDocumentConverter.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/JintLuceneDocumentConverter.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/LuceneDocumentConverter.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/LuceneDocumentConverterBase.cs
  src/Raven.Server/Documents/Indexes/Static/StaticIndexBase.cs
  test/SlowTests/Issues/RavenDB_14986.cs
Labels: v4.2

#10569 4.2 to 5.0 merge
  .github/workflows/FastTests.yml
  bench/BulkInsert.Benchmark/BulkInsert.Benchmark.csproj
  bench/Indexing.Benchmark/Indexing.Benchmark.csproj
  bench/Micro.Benchmark/Micro.Benchmark.csproj
  bench/Regression.Benchmark/Regression.Benchmark.csproj
  bench/SubscriptionFailover.Benchmark/SubscriptionFailover.Benchmark.csproj
  bench/Subscriptions.Benchmark/Subscriptions.Benchmark.csproj
  bench/Voron.Benchmark/StorageBenchmark.cs
  bench/Voron.Benchmark/Voron.Benchmark.csproj
  src/Raven.Embedded/ServerOptions.cs
  src/Raven.Server/Config/Categories/MemoryConfiguration.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/AnonymousLuceneDocumentConverter.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/JintLuceneDocumentConverter.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/LuceneDocumentConverter.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/LuceneDocumentConverterBase.cs
  src/Raven.Server/Documents/Indexes/Static/StaticIndexBase.cs
  src/Raven.Server/Documents/PeriodicBackup/GoogleCloud/RavenGoogleCloudClient.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Server/ServerWide/Context/ClusterContextPool.cs
  src/Raven.Server/ServerWide/Context/DocumentsContextPool.cs
  src/Raven.Server/ServerWide/Context/DocumentsOperationContext.cs
  src/Raven.Server/ServerWide/Context/TransactionContextPool.cs
  src/Raven.Server/ServerWide/Context/TransactionOperationContext.cs
  src/Raven.Studio/Raven.Studio.csproj
  src/Sparrow/Collections/FastList.cs
  src/Sparrow/Json/JsonContextPool.cs
  src/Sparrow/Json/JsonContextPoolBase.cs
  src/Sparrow/Json/JsonOperationContext.cs
  test/BenchmarkTests/BenchmarkTests.csproj
  test/EmbeddedTests/EmbeddedTests.csproj
  test/FastTests/FastTests.csproj
  test/InterversionTests/InterversionTests.csproj
  test/RachisTests/RachisTests.csproj
  test/SlowTests/Issues/RavenDB_14986.cs
  test/SlowTests/SlowTests.csproj
  test/StressTests/StressTests.csproj
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
  test/Tryouts/Tryouts.csproj
  tools/Raven.Debug/Raven.Debug.csproj
  tools/Raven.Migrator/Raven.Migrator.csproj
  tools/TypingsGenerator/TypingsGenerator.csproj
  tools/Voron.Recovery/Recovery.cs
  tools/Voron.Recovery/Voron.Recovery.csproj
  tools/rvn/rvn.csproj
Labels: v5.0

#10574 4.2 to 5.0 merge
  src/Raven.Server/Documents/Operations/Operations.cs
  src/Sparrow/Json/JsonOperationContext.cs
Labels: v5.0

#10572 RavenDB-15000 : Include TimeSerires via Load fails when From/To dates are not provided
  src/Raven.Server/Documents/Handlers/DocumentHandler.cs
  src/Raven.Server/Web/RequestHandler.cs
  test/SlowTests/Client/TimeSeries/Issues/RavenDB-15000.cs
  test/SlowTests/Client/TimeSeries/Query/TimeSeriesLinqQuery.cs
Labels: v5.0

#10575 RavenDB-15001 stabilizing the test
  test/SlowTests/Issues/RavenDB_14986.cs
Labels: v4.2

#10579 4.2 to 5.0 merge
  src/Raven.Server/Documents/Handlers/Debugging/MemoryDebugHandler.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/PeriodicBackup/Aws/RavenAwsClient.cs
  src/Raven.Server/Documents/PeriodicBackup/Aws/RavenAwsGlacierClient.cs
  src/Raven.Server/Documents/PeriodicBackup/Aws/RavenAwsS3Client.cs
  src/Raven.Studio/typescript/models/database/tasks/periodicBackup/amazonSettings.ts
  src/Sparrow.Server/Platform/PlatformSpecific.cs
  src/Sparrow/Json/JsonContextPoolBase.cs
  src/Sparrow/Size.cs
  src/Sparrow/Utils/NativeMemory.cs
  src/Voron/Impl/EncryptionBuffersPool.cs
  src/Voron/Impl/Paging/CryptoPager.cs
  src/Voron/StorageEnvironment.cs
  test/FastTests/Voron/EncryptionBufferPool.cs
  test/SlowTests/Issues/RavenDB_14986.cs
Labels: v5.0

#10583 RavenDB-15003 updated to latest NuGet syntax
  LICENSE
  LICENSE.txt
  scripts/assets/icon.png
  scripts/copyAssets.ps1
  scripts/nuget.ps1
  src/Directory.Build.props
  src/Raven.Client/Raven.Client.csproj
  src/Raven.Embedded/Raven.Embedded.csproj
  src/Raven.Embedded/Raven.Embedded.nuspec.template
  src/Raven.Server/Raven.Server.csproj
  src/Raven.TestDriver/Raven.TestDriver.csproj
Labels: v4.2

#10585 RavenDB-15015 : fix flaky test
  test/SlowTests/Client/TimeSeries/Issues/RavenDB-14702.cs
Labels: v5.0

#10567 RavenDB-14919
  src/Raven.Client/Documents/Commands/GetDocumentsCommand.cs
  src/Raven.Client/Documents/Operations/Counters/CountersDetail.cs
  src/Raven.Client/Documents/Operations/Counters/GetCountersOperation.cs
  src/Raven.Server/Documents/Handlers/CountersHandler.cs
  src/Raven.Server/Documents/Handlers/DocumentHandler.cs
  src/Raven.Server/Documents/Includes/IncludeCountersCommand.cs
  src/Sparrow/Json/JsonDeserializationBase.cs
  test/SlowTests/Issues/RavenDB_14919.cs
Labels: v4.2

#10584 RavenDB-15014 Avoid capitalizing time series roll up names
  src/Raven.Studio/wwwroot/Content/css/pages/time-series-config.less
Labels: v5.0

#10590 RavenDB-15033 - allow to disable the database/stop the index when we are out of cpu credits
  src/Raven.Server/Documents/Indexes/Index.cs
Labels: v4.2

#10593 RavenDB-15037 - add missing overload in the async session API
  src/Raven.Client/Documents/Session/IAsyncDocumentSession.cs
  test/SlowTests/Client/OptimisticConcurrency.cs
Labels: v4.2

#10591 RavenDB-13946 : remove obsolete 'ReplicationItemType.CounterTombstone'
  src/Raven.Server/Documents/Replication/IncomingReplicationHandler.cs
  src/Raven.Server/Documents/Replication/ReplicationItems/ReplicationBatchItem.cs
Labels: v5.0

#10597 RavenDB-15031 stabilizing the CanDeleteIndexErrors test
  test/SlowTests/Issues/RavenDB_6967.cs
  test/Tests.Infrastructure/RavenTestBase.cs
Labels: v5.0

#10598 RavenDB-15004 fixed: name field in GetDetailedCollectionStatisticsOperation is always null
  src/Raven.Client/Documents/Operations/CollectionStatistics.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Handlers/CollectionsHandler.cs
  test/SlowTests/Issues/RavenDB_14881.cs
Labels: v4.2

#10595 RavenDB-14975 - keep the same document id after counters import
  src/Raven.Server/Documents/Handlers/CountersHandler.cs
  test/SlowTests/Smuggler/SmugglerApiTests.cs
Labels: v4.2

#10599 RavenDB-15002 remove gcc dll dependency from win x86 libzstd binary
  libs/libzstd/libzstd.win.x86.dll
  src/Raven.Pal/build-libs/zstd-build-deps.sh
  src/Raven.Pal/build-libs/zstd.sh
Labels: v5.0

#10601 4.2 to 5.0 merge
  LICENSE
  LICENSE.txt
  scripts/assets/icon.png
  scripts/copyAssets.ps1
  scripts/nuget.ps1
  src/Directory.Build.props
  src/Raven.Client/Documents/Commands/GetDocumentsCommand.cs
  src/Raven.Client/Documents/Operations/CollectionStatistics.cs
  src/Raven.Client/Documents/Operations/Counters/CountersDetail.cs
  src/Raven.Client/Documents/Operations/Counters/GetCountersOperation.cs
  src/Raven.Client/Documents/Session/IAsyncDocumentSession.cs
  src/Raven.Client/Raven.Client.csproj
  src/Raven.Embedded/Raven.Embedded.csproj
  src/Raven.Embedded/Raven.Embedded.nuspec.template
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Handlers/CollectionsHandler.cs
  src/Raven.Server/Documents/Handlers/CountersHandler.cs
  src/Raven.Server/Documents/Handlers/DocumentHandler.cs
  src/Raven.Server/Documents/Includes/IncludeCountersCommand.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.TestDriver/Raven.TestDriver.csproj
  src/Sparrow/Json/JsonDeserializationBase.cs
  test/SlowTests/Client/OptimisticConcurrency.cs
  test/SlowTests/Issues/RavenDB_14881.cs
  test/SlowTests/Issues/RavenDB_14919.cs
  test/SlowTests/Smuggler/SmugglerApiTests.cs
Labels: v5.0

#10602 RavenDB-15043 fixed leak of context in MetadataAsDictionary of CompareExchangeValue
  src/Raven.Client/Documents/Operations/CompareExchange/CompareExchangeValueResultParser.cs
  src/Raven.Client/Documents/Operations/CompareExchange/GetCompareExchangeValueOperation.cs
  src/Raven.Client/Documents/Operations/CompareExchange/GetCompareExchangeValuesOperation.cs
  src/Raven.Client/Documents/Session/ClusterTransactionSession.cs
  src/Raven.Client/Documents/Session/Operations/Lazy/LazyGetCompareExchangeValueOperation.cs
  src/Raven.Client/Documents/Session/Operations/Lazy/LazyGetCompareExchangeValuesOperation.cs
  src/Raven.Client/Json/MetadataAsDictionary.cs
Labels: v5.0

#10604 RavenDB-14998 allow to append more than 127 tags per segment
  src/Raven.Server/Documents/TimeSeries/TimeSeriesValuesSegment.cs
  test/FastTests/Server/Documents/TimeSeries/TimeSeriesAppendTests.cs
  test/FastTests/Server/Documents/TimeSeries/TimeSeriesRangeTests.cs
Labels: v5.0

#10609 RavenDB-14965 Time-Series indexing progress - showing items/sec or do…
  src/Raven.Client/Documents/Indexes/IndexProgress.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Json/BlittableJsonTextWriterExtensions.cs
  src/Raven.Studio/typescript/models/database/index/indexProgress.ts
Labels: v5.0

#10610 RavenDB-6940 Feature/docker arm
  docker/build-ubuntu-arm.ps1
  docker/build-ubuntu.ps1
  docker/common.ps1
  docker/publish-ubuntu-arm.ps1
  docker/publish-ubuntu.ps1
  scripts/docker.ps1
Labels: v4.2

#10612 RavenDB-14823 get rid of TODOs in index defintion class
  src/Raven.Studio/typescript/models/database/index/indexDefinition.ts
Labels: v5.0

#10611 RavenDB-14876 Enhance time series view - separate columns for values …
  src/Raven.Studio/typescript/common/generalUtils.ts
  src/Raven.Studio/typescript/models/database/timeSeries/timeSeriesModel.ts
  src/Raven.Studio/typescript/viewmodels/database/timeSeries/deleteTimeSeries.ts
  src/Raven.Studio/typescript/viewmodels/database/timeSeries/editTimeSeries.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/columns/flagsColumn.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/virtualGrid.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/virtualGridController.ts
Labels: v5.0

#10614 RavenDB-15052 - Log start and end of each backup operation in Operations log
  src/Raven.Server/Documents/PeriodicBackup/ConcurrentBackupsCounter.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
Labels: v4.2

#10615 RavenDB-14935 Add Time Series to Smuggler Dialog
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/smugglerDatabaseDetails.ts
Labels: v5.0

#10616 4.2 to 5.0 merge
  docker/build-ubuntu.ps1
  docker/common.ps1
  docker/publish-ubuntu.ps1
  docker/ravendb-ubuntu/Dockerfile.arm32v7
  docker/ravendb-ubuntu/Dockerfile.x64
  docker/readme.md
  src/Raven.Server/Documents/PeriodicBackup/ConcurrentBackupsCounter.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.13/ServerBackupsCurrent.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.13/ServerBackupsMax.cs
  src/Raven.Server/Monitoring/Snmp/SnmpOids.cs
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
Labels: v5.0

#10617 RavenDB-15050 fix verious time series rollup issues
  src/Raven.Server/Documents/TimeSeries/TimeSeriesPolicyRunner.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesRollups.cs
  test/SlowTests/Client/TimeSeries/Policies/TimeSeriesConfigurationTests.cs
Labels: v5.0

#10620 RDBS-85 Fixed incorrect updates of last processed etags in ETL task s…
  src/Raven.Server/Documents/ETL/EtlProcess.cs
  src/Raven.Server/Documents/ETL/Providers/Raven/RavenEtl.cs
  test/SlowTests/Server/Documents/ETL/Raven/RDBS_85.cs
Labels: v4.2

#10619 RavenDB-15059 - Pass database name when exporting the config file in Pull Replication
  src/Raven.Studio/typescript/viewmodels/database/tasks/editPullReplicationHubTask.ts
Labels: v4.2

#10623 RavenDB-15046 added ability to reset counters index
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  test/SlowTests/Issues/RavenDB_15046.cs
Labels: v5.0

#10625 RavenDB-15056 Edit time-series value shouldn't send remove operation
  src/Raven.Studio/typescript/commands/database/documents/timeSeries/saveTimeSeriesCommand.ts
  src/Raven.Studio/typescript/viewmodels/database/timeSeries/editTimeSeriesEntry.ts
Labels: v5.0

#10624 RavenDB-15049 prevent from creating indexes with multiple maps, but with different source types
  src/Raven.Client/Documents/Indexes/IndexDefinition.cs
  test/SlowTests/Issues/RavenDB_15049.cs
Labels: v5.0

#10621 RavenDB-15060 - Ignore ObjectDisposedException when trying to add a new batch
  Raven.Database/Prefetching/PrefetchingBehavior.cs
Labels: v3.5

#10618 RavenDB-15057: Fix NRE in ReplicationLoader and add log
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
Labels: v4.2

#10632 RavenDB-15061 update time-series sample data
  src/Raven.Client/Documents/Operations/TimeSeries/TimeSeriesConfiguration.cs
  src/Raven.Client/Documents/Smuggler/DatabaseItemType.cs
  src/Raven.Client/Documents/Smuggler/DatabaseSmugglerOptions.cs
  src/Raven.Server/Documents/Patch/ScriptRunner.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesStorage.cs
  src/Raven.Server/Smuggler/Documents/StreamDestination.cs
  src/Raven.Server/Smuggler/Documents/StreamSource.cs
  src/Raven.Server/Web/Studio/EmbeddedData/Northwind.ravendbdump
  src/Raven.Server/Web/Studio/EmbeddedData/NorthwindModel.cs
  src/Raven.Server/Web/Studio/SampleDataHandler.cs
  test/SlowTests/Client/TimeSeries/Patch/TimeSeriesPatchTests.cs
Labels: v5.0

#10633 RavenDB-15072 fixed cartesian distance calculation
  src/Raven.Server/Documents/Indexes/Static/Spatial/SpatialDistanceFieldComparatorSource.cs
Labels: v4.2

#10629 RavenDB-14696: Don't add docs when toggling DBs, add print on assert …
  test/RachisTests/SubscriptionFailoverWIthWaitingChains.cs
Labels: v4.2

#10635 RavenDB-14960 added WaitForNonStaleResults
  test/SlowTests/Issues/RavenDB_5514.cs
Labels: v4.2
