Repository ravendb/ravendb, pull requests merged in 2020-07, with the labels that each got.

#10774 RavenDB-15269 Connect the dots for group-by time-series query + Raven…
  src/Raven.Studio/typescript/common/queryUtil.ts
  src/Raven.Studio/typescript/viewmodels/common/timeSeriesPlotDetails.ts
  src/Raven.Studio/wwwroot/App/views/common/timeSeriesPlotDetails.html
Labels: v5.0

#10775 RavenDB-15173 Time series - validate range dates in delete by range
  src/Raven.Studio/typescript/viewmodels/database/timeSeries/deleteTimeSeries.ts
  src/Raven.Studio/wwwroot/App/views/database/timeSeries/deleteTimeSeries.html
Labels: v5.0

#10771 RavenDB-15284 Rollup with more than 5 values should halt
  src/Raven.Server/Documents/TimeSeries/TimeSeriesRollups.cs
  test/SlowTests/Client/TimeSeries/Policies/TimeSeriesConfigurationTests.cs
Labels: v5.0

#10778 RavenDB-15068 Cluster wide transaction - better error when storing doc with empty string id or white spaces
  src/Raven.Server/ServerWide/Commands/ClusterTransactionCommand.cs
  test/SlowTests/Cluster/ClusterTransactionTests.cs
Labels: v4.2

#10780 RavenDB-15288 - NRE when creating up an incremental backup
  src/Raven.Server/Documents/PeriodicBackup/BackupTask.cs
  src/Raven.Server/Documents/PeriodicBackup/ConcurrentBackupsCounter.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
Labels: v4.2

#10781 RavenDB-15289 - fix NotImplementedException in Unity 3D
  src/Raven.Client/Http/RequestExecutor.cs
Labels: v4.2

#10782 RavenDB-10972 - better error message for tests
  src/Raven.Server/Commercial/LicenseManager.cs
Labels: v4.2

#10785 RavenDB-15182 Include info about rollup in UI
  src/Raven.Studio/typescript/models/database/timeSeries/timeSeriesModel.ts
  src/Raven.Studio/typescript/viewmodels/database/timeSeries/editTimeSeries.ts
  src/Raven.Studio/wwwroot/App/views/database/timeSeries/editTimeSeries.html
  src/Raven.Studio/wwwroot/App/views/database/timeSeries/editTimeSeriesEntry.html
Labels: v5.0

#10773 RavenDB-15175 Time series - Future dates tooltip
  src/Raven.Studio/typescript/common/generalUtils.ts
  src/Raven.Studio/typescript/models/database/documents/documentMetadata.ts
  src/Raven.Studio/typescript/models/database/tasks/ongoingTaskBackupListModel.ts
  src/Raven.Studio/typescript/models/resources/creation/backupCredentials.ts
  src/Raven.Studio/typescript/viewmodels/common/cronEditor.ts
  src/Raven.Studio/typescript/viewmodels/resources/serverDashboard.ts
  src/Raven.Studio/typescript/viewmodels/shell/about.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/columnPreviewPlugin.ts
Labels: v5.0

#10789 RavenDB-15134 fixing test
  test/SlowTests/Server/RecordingTransactionOperationsMergerTests.cs
Labels: v4.2

#10790 4.2 to 5.0 merge
  src/Raven.Client/Documents/Operations/Counters/GetCountersOperation.cs
  src/Raven.Client/Documents/Session/AsyncSessionDocumentCounters.cs
  src/Raven.Client/Documents/Session/InMemoryDocumentSessionOperations.cs
  src/Raven.Client/Http/RequestExecutor.cs
  src/Raven.Server/Commercial/LicenseManager.cs
  src/Raven.Server/Documents/ComputeHttpEtags.cs
  src/Raven.Server/Documents/CountersStorage.cs
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Handlers/CountersHandler.cs
  src/Raven.Server/Documents/PeriodicBackup/BackupTask.cs
  src/Raven.Server/Documents/PeriodicBackup/ConcurrentBackupsCounter.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
  src/Raven.Server/Documents/TransactionOperationsMerger.cs
  src/Raven.Server/Json/BlittableJsonTextWriterExtensions.cs
  src/Raven.Server/ServerWide/Commands/ClusterTransactionCommand.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  test/SlowTests/Client/Counters/CountersCluster.cs
  test/SlowTests/Client/Counters/CountersSingleNode.cs
  test/SlowTests/Client/Counters/PatchOnCounters.cs
  test/SlowTests/Client/Counters/SessionCounters.cs
  test/SlowTests/Cluster/ClusterTransactionTests.cs
  test/SlowTests/Issues/RavenDB_14919.cs
  test/SlowTests/Issues/RavenDB_15134.cs
  test/SlowTests/Issues/RavenDB_15282.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
  test/SlowTests/Server/RecordingTransactionOperationsMergerTests.cs
Labels: v5.0

#10791 RavenDB-15273 mark all counts as processed during restore
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreBackupTaskBase.cs
  src/Raven.Server/Smuggler/Documents/DatabaseSmuggler.cs
Labels: v5.0

#10796 RavenDB-14928 Query timing information should have specific entries f…
  src/Raven.Studio/wwwroot/Content/css/pages/query.less
Labels: v5.0

#10787 RavenDB-15294 V5: Failed to execute Compaction with Document Compress…
  src/Raven.Server/Storage/Schema/Updates/Documents/50000/From42017.cs
Labels: v5.0

#10799 [Studio] RavenDB-15137 Lock Change Vector panel size in document prop…
  src/Raven.Studio/wwwroot/App/views/database/documents/editDocument.html
  src/Raven.Studio/wwwroot/Content/css/pages/documents-edit.less
Labels: v5.0

#10797 RavenDB-15199 Display the number of counters with a thousands separator
  src/Raven.Studio/typescript/viewmodels/database/documents/editDocument.ts
  src/Raven.Studio/wwwroot/App/views/database/documents/editDocument.html
Labels: v5.0

#10804 RavenDB-15236: Don't AddAndStartOutgoingReplication if DocumentDataba…
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
Labels: v4.2

#10807 4.2 to 5.0 merge
  src/Raven.Server/Documents/Handlers/BatchRequestParser.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/Exceptions/InvalidCommandTypeException.cs
  src/Raven.Server/RavenServerStartup.cs
  src/Raven.Server/Routing/RequestRouter.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  test/SlowTests/Server/Documents/PeriodicBackup/ServerWideBackup.cs
Labels: v5.0

#10811 RavenDB-15291 : fix bug in UpdateDocumentCounters
  src/Raven.Server/Storage/Schema/Updates/Documents/50000/From42017.cs
Labels: v5.0

#10809 RavenDB-15314 Fix NRE during cluster transaction when deleting a non-existing document
  src/Raven.Server/Documents/Handlers/BatchHandler.cs
  test/SlowTests/Cluster/ClusterTransactionTests.cs
Labels: v4.2

#10815 RavenDB-15318 - Low memory values in the debug info package are incorrect
  src/Sparrow.Server/LowMemory/MemoryInformation.cs
Labels: v4.2

#10814 RavenDB-15236 - start the async task only if we have new destinations and log in case of any error
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
Labels: v4.2

#10812 RavenDB-14634 fix RapidRetentionAndRollupInACluster test
  src/Raven.Client/Documents/Operations/TimeSeries/TimeSeriesCollectionConfiguration.cs
  test/SlowTests/Client/TimeSeries/Policies/TimeSeriesConfigurationTests.cs
Labels: v5.0

#10800 RavenDB-15294
  test/SlowTests/Data/RavenDB_15294/northwind-4.2.103.zip
  test/SlowTests/Issues/RavenDB-15294.cs
  test/SlowTests/SlowTests.csproj
Labels: v5.0

#10805 RavenDB-12387 styling of indexing peformance
  src/Raven.Studio/wwwroot/Content/css/bootstrap/variables-header.less
  src/Raven.Studio/wwwroot/Content/css/pages/index-performance.less
  src/Raven.Studio/wwwroot/Content/css/themes/blue-theme-variables-override.less
  src/Raven.Studio/wwwroot/Content/css/toastr.less
Labels: v5.1

#10802 RavenDB-13209 Unified H2 Bold Styling
  src/Raven.Studio/wwwroot/App/views/database/indexes/indexPerformance.html
  src/Raven.Studio/wwwroot/App/views/database/indexes/indexes.html
  src/Raven.Studio/wwwroot/App/views/database/settings/revisions.html
  src/Raven.Studio/wwwroot/App/views/database/settings/timeSeries.html
  src/Raven.Studio/wwwroot/App/views/database/status/ongoingTasksStats.html
  src/Raven.Studio/wwwroot/App/views/database/status/statistics.html
  src/Raven.Studio/wwwroot/App/views/notifications/notificationCenter.html
  src/Raven.Studio/wwwroot/App/views/partial/ioStatsGraph.html
  src/Raven.Studio/wwwroot/App/views/resources/databases.html
Labels: v5.1

#10801 RavenDB-14739 Fix Change Vector Tooltip Position
  src/Raven.Studio/wwwroot/Content/css/pages/documents-edit.less
Labels: v5.1

#10792 RavenDB-7212 Bring back an option to collapse menu
  src/Raven.Studio/typescript/viewmodels/shell.ts
  src/Raven.Studio/wwwroot/App/views/shell.html
  src/Raven.Studio/wwwroot/Content/css/basic-layout.less
  src/Raven.Studio/wwwroot/Content/css/main-menu.less
Labels: v5.1

#10817 RavenDB-15188 Show 'Recent' tab when navigating to a database that do…
  src/Raven.Studio/typescript/viewmodels/database/timeSeries/editTimeSeries.ts
Labels: v5.0

#10819 RavenDB-15319 CreateClientCertificateCommand is not a read request
  src/Raven.Client/ServerWide/Operations/Certificates/CreateClientCertificateOperation.cs
Labels: v4.2

#10829 RavenDB-15329 Rename `Remove` to `Delete`
  src/Raven.Studio/wwwroot/App/views/database/patch/patchSyntax.html
Labels: v5.0

#10823 RavenDB-15327 fix time-series policy configuration equals
  src/Raven.Client/Documents/Operations/TimeSeries/TimeSeriesCollectionConfiguration.cs
  src/Raven.Client/Documents/Operations/TimeSeries/TimeSeriesConfiguration.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesPolicyRunner.cs
  test/SlowTests/Client/TimeSeries/Policies/TimeSeriesConfigurationTests.cs
Labels: v5.0

#10821 RavenDB-14428 Reset log number to zero in new day
  src/Raven.Server/Documents/Handlers/Admin/AdminLogsHandler.cs
  src/Sparrow/Logging/LoggingSource.cs
  test/SlowTests/SparrowTests/LoggingSourceTests.cs
Labels: v4.2

#10827 RavenDB-15329 Rename `Remove` to `Delete`
  src/Raven.Client/Documents/Commands/Batches/TimeSeriesBatchCommandData.cs
  src/Raven.Client/Documents/Operations/TimeSeries/TimeSeriesOperation.cs
  src/Raven.Client/Documents/Session/IAsyncSessionDocumentTimeSeries.cs
  src/Raven.Client/Documents/Session/ISessionDocumentTimeSeries.cs
  src/Raven.Client/Documents/Session/ISessionDocumentTimeSeriesBase.cs
  src/Raven.Client/Documents/Session/SessionDocumentTimeSeries.cs
  src/Raven.Client/Documents/Session/SessionTimeSeriesBase.cs
  src/Raven.Server/Documents/Handlers/TimeSeriesHandler.cs
  src/Raven.Server/Documents/Patch/ScriptRunner.cs
  src/Raven.Server/Documents/Replication/IncomingReplicationHandler.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesRollups.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesStorage.cs
  src/Raven.Studio/typescript/commands/database/documents/timeSeries/deleteTimeSeriesCommand.ts
  src/Raven.Studio/typescript/viewmodels/database/timeSeries/deleteTimeSeries.ts
  test/FastTests/Client/Indexing/TimeSeries/BasicTimeSeriesIndexes.cs
  test/FastTests/Client/Queries/TimeSeries/BasicTimeSeriesQueries.cs
  test/SlowTests/Client/Indexing/TimeSeries/BasicTimeSeriesIndexes_MethodSyntax.cs
  test/SlowTests/Client/Indexing/TimeSeries/BasicTimeSeriesIndexes_MixedSyntax.cs
  test/SlowTests/Client/Indexing/TimeSeries/BasicTimeSeriesIndexes_StrongSyntax.cs
  test/SlowTests/Client/TimeSeries/BulkInsert.cs
  test/SlowTests/Client/TimeSeries/Issues/RavenDB-13574.cs
  test/SlowTests/Client/TimeSeries/Issues/RavenDB-14293.cs
  test/SlowTests/Client/TimeSeries/Issues/RavenDB-14426.cs
  test/SlowTests/Client/TimeSeries/Operations/TimeSeriesOperations.cs
  test/SlowTests/Client/TimeSeries/Patch/TimeSeriesPatchTests.cs
  test/SlowTests/Client/TimeSeries/Policies/TimeSeriesConfigurationTests.cs
  test/SlowTests/Client/TimeSeries/Replication/TimeSeriesReplicationTests.cs
  test/SlowTests/Client/TimeSeries/Session/TimeSeriesIncludes.cs
  test/SlowTests/Client/TimeSeries/Session/TimeSeriesSessionTests.cs
  test/SlowTests/Client/TimeSeries/TimeSeriesStatsUpdate.cs
  test/SlowTests/Issues/RavenDB_14230.cs
  test/SlowTests/Issues/RavenDB_15240.cs
  tools/TypingsGenerator/Program.cs
Labels: v5.0

#10831 4.2 to 5.0 merge
  build.ps1
  scripts/buildProjects.ps1
  scripts/exec.ps1
  scripts/sign.ps1
  src/Raven.Client/ServerWide/Operations/Certificates/CreateClientCertificateOperation.cs
  src/Raven.Server/Documents/Handlers/Admin/AdminLogsHandler.cs
  src/Raven.Server/Documents/Handlers/BatchHandler.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Sparrow.Server/LowMemory/MemoryInformation.cs
  src/Sparrow/Logging/LoggingSource.cs
  test/SlowTests/Cluster/ClusterTransactionTests.cs
  test/SlowTests/SparrowTests/LoggingSourceTests.cs
Labels: v5.0

#10832 5.0 to 5.1 merge
  build.ps1
  scripts/buildProjects.ps1
  scripts/exec.ps1
  scripts/sign.ps1
  src/Raven.Client/Documents/Commands/Batches/TimeSeriesBatchCommandData.cs
  src/Raven.Client/Documents/Linq/LinqPathProvider.cs
  src/Raven.Client/Documents/Operations/TimeSeries/TimeSeriesCollectionConfiguration.cs
  src/Raven.Client/Documents/Operations/TimeSeries/TimeSeriesConfiguration.cs
  src/Raven.Client/Documents/Operations/TimeSeries/TimeSeriesOperation.cs
  src/Raven.Client/Documents/Queries/QueryFieldUtil.cs
  src/Raven.Client/Documents/Session/AbstractDocumentQuery.cs
  src/Raven.Client/Documents/Session/IAsyncSessionDocumentTimeSeries.cs
  src/Raven.Client/Documents/Session/ISessionDocumentTimeSeries.cs
  src/Raven.Client/Documents/Session/ISessionDocumentTimeSeriesBase.cs
  src/Raven.Client/Documents/Session/SessionDocumentTimeSeries.cs
  src/Raven.Client/Documents/Session/SessionTimeSeriesBase.cs
  src/Raven.Client/ServerWide/Operations/Certificates/CreateClientCertificateOperation.cs
  src/Raven.Server/Documents/Handlers/Admin/AdminLogsHandler.cs
  src/Raven.Server/Documents/Handlers/BatchHandler.cs
  src/Raven.Server/Documents/Handlers/TimeSeriesHandler.cs
  src/Raven.Server/Documents/Patch/ScriptRunner.cs
  src/Raven.Server/Documents/Replication/IncomingReplicationHandler.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesPolicyRunner.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesRollups.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesStorage.cs
  src/Raven.Studio/typescript/commands/database/documents/timeSeries/deleteTimeSeriesCommand.ts
  src/Raven.Studio/typescript/models/database/documents/timeSeriesPolicy.ts
  src/Raven.Studio/typescript/models/database/documents/timeValueEntry.ts
  src/Raven.Studio/typescript/viewmodels/database/timeSeries/deleteTimeSeries.ts
  src/Raven.Studio/typescript/viewmodels/database/timeSeries/editTimeSeries.ts
  src/Raven.Studio/wwwroot/App/views/database/patch/patchSyntax.html
  src/Sparrow.Server/LowMemory/MemoryInformation.cs
  src/Sparrow/Logging/LoggingSource.cs
  test/FastTests/Client/Indexing/TimeSeries/BasicTimeSeriesIndexes.cs
  test/FastTests/Client/Queries/TimeSeries/BasicTimeSeriesQueries.cs
  test/SlowTests/Client/Indexing/TimeSeries/BasicTimeSeriesIndexes_MethodSyntax.cs
  test/SlowTests/Client/Indexing/TimeSeries/BasicTimeSeriesIndexes_MixedSyntax.cs
  test/SlowTests/Client/Indexing/TimeSeries/BasicTimeSeriesIndexes_StrongSyntax.cs
  test/SlowTests/Client/TimeSeries/BulkInsert.cs
  test/SlowTests/Client/TimeSeries/Issues/RavenDB-13574.cs
  test/SlowTests/Client/TimeSeries/Issues/RavenDB-14293.cs
  test/SlowTests/Client/TimeSeries/Issues/RavenDB-14426.cs
  test/SlowTests/Client/TimeSeries/Operations/TimeSeriesOperations.cs
  test/SlowTests/Client/TimeSeries/Patch/TimeSeriesPatchTests.cs
  test/SlowTests/Client/TimeSeries/Policies/TimeSeriesConfigurationTests.cs
  test/SlowTests/Client/TimeSeries/Replication/TimeSeriesReplicationTests.cs
  test/SlowTests/Client/TimeSeries/Session/TimeSeriesIncludes.cs
  test/SlowTests/Client/TimeSeries/Session/TimeSeriesSessionTests.cs
  test/SlowTests/Client/TimeSeries/TimeSeriesStatsUpdate.cs
  test/SlowTests/Cluster/ClusterTransactionTests.cs
  test/SlowTests/Issues/EncryptedDatabaseGroup.cs
  test/SlowTests/Issues/RavenDB-14361.cs
  test/SlowTests/Issues/RavenDB-15234.cs
  test/SlowTests/Issues/RavenDB_14230.cs
  test/SlowTests/Issues/RavenDB_15240.cs
  test/SlowTests/SparrowTests/LoggingSourceTests.cs
  tools/TypingsGenerator/Program.cs
Labels: v5.1

#10833 HRINT-1704
  scripts/updateSourceWithBuildInfo.ps1
  scripts/version.ps1
Labels: v4.2

#10779 RavenDB-12486 Add option to collapse the properties panel
  src/Raven.Studio/typescript/viewmodels/database/documents/editDocument.ts
  src/Raven.Studio/wwwroot/App/views/database/documents/editDocument.html
  src/Raven.Studio/wwwroot/Content/css/basic-layout.less
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.eot
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.svg
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.ttf
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.woff
  src/Raven.Studio/wwwroot/Content/css/icons.less
  src/Raven.Studio/wwwroot/Content/css/pages/documents-edit.less
Labels: v5.1

#10810 RavenDB-15113 Fix Storage Report View when Index name is very long
  src/Raven.Studio/typescript/viewmodels/database/status/storageReport.ts
  src/Raven.Studio/typescript/viewmodels/manage/storageReport.ts
  src/Raven.Studio/wwwroot/App/views/database/status/storageReport.html
  src/Raven.Studio/wwwroot/App/views/manage/storageReport.html
  src/Raven.Studio/wwwroot/Content/css/pages/storage-report.less
  src/Raven.Studio/wwwroot/Content/css/styles-common.less
Labels: v5.1

#10834 4.2 to 5.0 merge
  scripts/updateSourceWithBuildInfo.ps1
  scripts/version.ps1
  src/Raven.Client/Documents/Operations/TimeSeries/TimeSeriesCollectionConfiguration.cs
  src/Raven.Client/Properties/VersionInfo.cs
  src/Raven.Server/Commercial/LicenseManager.cs
  src/Raven.Server/Commercial/LicenseStatus.cs
  src/Raven.Server/Commercial/LicenseStorage.cs
  src/Raven.Server/Commercial/SetupManager.cs
  src/Raven.Server/Documents/Handlers/Admin/RachisAdminHandler.cs
  src/Raven.Server/Json/JsonDeserializationServer.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.9/ServerLicenseExpiration.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.9/ServerLicenseExpirationLeft.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.9/ServerLicenseMaxCpuCores.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.9/ServerLicenseType.cs
  src/Raven.Server/Program.cs
  src/Raven.Server/RavenServer.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/SecretProtection.cs
  src/Raven.Server/ServerWide/ServerStatistics.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Web/Studio/LicenseHandler.cs
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
  src/Raven.Studio/typescript/viewmodels/shell/about.ts
  src/Raven.Studio/typescript/viewmodels/shell/registration.ts
  src/Raven.Studio/wwwroot/App/views/shell/about.html
  src/Voron/StorageEnvironment.cs
  src/Voron/StorageEnvironmentOptions.cs
  test/SlowTests/SparrowTests/LoggingSourceTests.cs
Labels: v5.0

#10836 RavenDB-13921 updated Jint
  libs/Jint.3.0.26-ravendb.nupkg
  libs/Jint.3.0.27-ravendb.nupkg
  src/Raven.Server/Raven.Server.csproj
Labels: v5.0

#10837 RavenDB-15335 do not monitor disabled databases
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.1/DatabaseOldestBackup.cs
Labels: v4.2

#10840 4.2 to 5.0 merge
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.1/DatabaseOldestBackup.cs
  src/Raven.Server/Raven.Server.csproj
  test/SlowTests/Issues/EncryptedDatabaseGroup.cs
  test/SlowTests/Issues/RavenDB_14881.cs
  tools/Raven.Debug/Raven.Debug.csproj
  tools/Raven.Migrator/Raven.Migrator.csproj
Labels: v5.0

#10843 RavenDB-14634 stabilize NotWaitingForNonStaleResultsShouldThrow
  test/SlowTests/Graph/BasicGraphQueries.cs
Labels: v5.0

#10839 RavenDB-14698 Patch help syntax in Blue/White theme
  src/Raven.Studio/wwwroot/Content/css/pages/patch.less
Labels: v5.1

#10844 RavenDB-15354 move test to x64
  test/SlowTests/RecoveryTests/SampleDatabaseRecovery.cs
Labels: v5.0

#10846 RavenDB-15341 : ArgumentOutOfRangeException when querying for last point
  src/Raven.Server/Documents/Queries/Results/TimeSeriesRetriever.cs
  test/SlowTests/Client/TimeSeries/Issues/RavenDB-15341.cs
Labels: v5.0

#10850 RavenDB-15340 Time series names are not visible in studio query results
  src/Raven.Studio/typescript/widgets/virtualGrid/columns/inlineTimeSeriesColumn.ts
Labels: v5.0

#10849 RavenDB-15365 support for custom Skip in Fact64BitAttribute
  test/Tests.Infrastructure/Fact64BitAttribute.cs
Labels: v5.0

#10848 RavenDB-15360 - Excessive logging of backup info
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
Labels: v4.2, v5.0

#10852 RavenDB-15236: fix possible NRE and deadlock in replication
  src/Raven.Server/Documents/Replication/OutgoingReplicationHandler.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
Labels: v4.2

#10854 RavenDB-15371 : Fix counters part in recovery tool
  src/Raven.Server/Documents/CountersStorage.cs
  tools/Voron.Recovery/Recovery.cs
Labels: v4.2

#10856 RavenDB-15359 delete empty time-series stats by the cleaner
  src/Raven.Server/Documents/Replication/IncomingReplicationHandler.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesStats.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesStorage.cs
  src/Voron/Data/Tables/Table.cs
  test/SlowTests/Client/TimeSeries/Policies/TimeSeriesConfigurationTests.cs
  test/SlowTests/Client/TimeSeries/Replication/TimeSeriesReplicationTests.cs
  test/SlowTests/Client/TimeSeries/Session/TimeSeriesSessionTests.cs
  test/StressTests/Client/TimeSeries/TimeSeriesStress.cs
Labels: v5.0

#10859 RavenDB-15374 Make nightly tests run from 6 PM UTC
  test/Tests.Infrastructure/NightlyBuildTheoryAttribute.cs
Labels: v4.2

#10858 4.2 to 5.0 merge
  src/Raven.Client/Util/EasyReaderWriterLock.cs
  src/Raven.Server/Commercial/LicenseManager.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
  src/Raven.Server/Documents/Replication/OutgoingReplicationHandler.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/Utils/AffinityHelper.cs
  src/Raven.Server/Utils/PoolOfThreads.cs
  test/Tests.Infrastructure/NightlyBuildTheoryAttribute.cs
  tools/Voron.Recovery/Recovery.cs
Labels: v5.0

#10860 RavenDB-14830 update windows container base image
  docker/ravendb-nanoserver/Dockerfile
  docker/ravendb-nanoserver/healthcheck.ps1
  docker/ravendb-nanoserver/install-raven.ps1
  docker/ravendb-nanoserver/run-raven.ps1
Labels: v4.2

#10857 RavenDB-15251 Counters are not saved for a cloned document
  src/Raven.Studio/typescript/commands/database/documents/cloneAttachmentsAndCountersCommand.ts
Labels: v5.0

#10851 RavenDB-13211 Manage Ongoing Tasks - Fix 'Not on node' label length
  src/Raven.Studio/wwwroot/Content/css/pages/ongoing-tasks.less
Labels: v5.1

#10862 RavenDB-15359 delete the stats only if it has count zero
  src/Raven.Server/Documents/TimeSeries/TimeSeriesStorage.cs
Labels: v5.0

#10868 HRINT-1715 - licensing adjustments for TimeSeries
  src/Raven.Client/Exceptions/Commercial/LimitType.cs
  src/Raven.Server/Commercial/LicenseManager.cs
  src/Raven.Server/Commercial/LicenseStatus.cs
  src/Raven.Server/Commercial/LicenseValidator.cs
  src/Raven.Server/Documents/Handlers/TimeSeriesHandler.cs
Labels: v5.0

#10871 RavenDB-15382: Add LogFileSize and MaxVerPages arguments to StorageEx…
  Raven.StorageExporter/Program.cs
  Raven.StorageExporter/StorageExporter.cs
  Raven.StorageExporter/StorgaeExporterConfiguration.cs
Labels: v3.5

#10873 RavenDB-15382: Add LogFileSize and MaxVerPages arguments to OfflineMi…
  src/Raven.Client/ServerWide/Operations/Migration/OfflineMigrationConfiguration.cs
Labels: v4.2

#10870 HRINT-1715 - licensing adjustments for TimeSeries
  src/Raven.Client/Exceptions/Commercial/LimitType.cs
  src/Raven.Server/Commercial/LicenseManager.cs
  src/Raven.Server/Commercial/LicenseStatus.cs
  src/Raven.Server/Commercial/LicenseValidator.cs
  src/Raven.Server/Documents/Handlers/TimeSeriesHandler.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesPolicyRunner.cs
Labels: v5.0

#10877 4.2 to 5.0 merge
  docker/ravendb-nanoserver/Dockerfile
  docker/ravendb-nanoserver/healthcheck.ps1
  docker/ravendb-nanoserver/install-raven.ps1
  docker/ravendb-nanoserver/run-raven.ps1
  src/Raven.Client/ServerWide/Operations/Migration/OfflineMigrationConfiguration.cs
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
  src/Raven.Server/ServerWide/ServerStore.cs
Labels: v5.0

#10878 HRINT-1715 - studio adjustments
  src/Raven.Studio/wwwroot/App/views/shell/about.html
Labels: v5.0

#10879 HRINT-1715 added missing assert
  src/Raven.Server/ServerWide/ServerStore.cs
Labels: v5.0

#10865 RavenDB-15228
  tools/Voron.Recovery/Recovery.cs
Labels: v5.0

#10863 RavenDB-14115 Overflow of name in Document Revision
  src/Raven.Studio/wwwroot/App/views/database/settings/revisions.html
  src/Raven.Studio/wwwroot/Content/css/pages/revisions.less
Labels: v5.1

#10881 RavenDB-15291 Making sure that we we increment tx marker during schem…
  src/Raven.Server/ServerWide/Context/TransactionOperationContext.cs
  src/Raven.Server/Storage/Schema/UpdateStep.cs
  src/Raven.Server/Storage/Schema/Updates/Documents/42017/From41016.cs
  src/Raven.Server/Storage/Schema/Updates/Documents/50000/From42017.cs
  src/Raven.Server/Storage/Schema/Updates/Server/42019/From42018.cs
Labels: v5.0

#10891 RavenDB-15393 Delete time-series not working
  src/Raven.Studio/typescript/commands/database/documents/timeSeries/deleteTimeSeriesCommand.ts
  src/Raven.Studio/typescript/commands/database/documents/timeSeries/saveTimeSeriesCommand.ts
  src/Raven.Studio/typescript/viewmodels/database/timeSeries/deleteTimeSeries.ts
  src/Raven.Studio/typings/_studio/dto.d.ts
  src/Raven.Studio/wwwroot/App/views/database/timeSeries/deleteTimeSeries.html
Labels: v5.0

#10889 RavenDB-15389 - Failed to recognize DiskFullException in Linux
  src/Sparrow.Server/Platform/Posix/Syscall.cs
Labels: v5.0

#10887 RavenDB-15373 tighten the test CanPropagateException
  test/SlowTests/Utils/InfrastructureTests.cs
Labels: v5.0

#10874 RavenDB-15218 Tests for restore time-series configuration by snapshot incremental backup
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
Labels: v5.0

#10892 RavenDB-15396 added tx-info endpoint for server storage
  src/Raven.Server/Documents/Handlers/Debugging/ServerTransactionDebugHandler.cs
  src/Raven.Server/Documents/Handlers/Debugging/TransactionDebugHandler.cs
Labels: v4.2

#10885 RavenDB-15339 set 15 seconds default timeout
  src/Raven.Client/Documents/Commands/GetRemoteTaskTopologyCommand.cs
  src/Raven.Client/Documents/Commands/GetTcpInfoForRemoteTaskCommand.cs
  src/Raven.Client/ServerWide/Commands/GetDatabaseTopologyCommand.cs
  src/Raven.Client/ServerWide/Commands/GetTcpInfoCommand.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  test/RachisTests/DatabaseCluster/ReplicationTests.cs
Labels: v4.2

#10893 RavenDB-15394 splitting must respect segment range
  src/Raven.Server/Documents/TimeSeries/TimeSeriesStorage.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesValuesSegment.cs
  test/SlowTests/Client/TimeSeries/Policies/TimeSeriesConfigurationTests.cs
  test/SlowTests/Client/TimeSeries/Replication/TimeSeriesReplicationTests.cs
Labels: v5.0

#10884 HRINT-1715 show correct error for not having rollups & retention
  src/Raven.Server/Documents/TimeSeries/TimeSeriesPolicyRunner.cs
Labels: v5.0

#10899 HRINT-1723 Fixing the scope of read transaction open on server store …
  src/Raven.Server/Documents/Replication/OutgoingReplicationHandler.cs
Labels: v5.0

#10905 RavenDB-15399 Recreating metadata should ignore time-series with 0 entries
  src/Raven.Server/Documents/TimeSeries/TimeSeriesPolicyRunner.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesStats.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesStorage.cs
  src/Raven.Server/Smuggler/Documents/DatabaseSource.cs
  test/SlowTests/Client/TimeSeries/Policies/TimeSeriesConfigurationTests.cs
  test/SlowTests/Client/TimeSeries/Replication/TimeSeriesReplicationTests.cs
Labels: v5.0

#10910 RavenDB-15404 - revert the change to the database restore
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreBackupTaskBase.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
Labels: v4.2

#10906 RavenDB-15402
  src/Raven.Client/Documents/Session/AsyncSessionDocumentCounters.cs
  test/SlowTests/Issues/RavenDB-15402.cs
Labels: v5.0

#10913 RavenDB-15411 Changing logs mode from Operations to Information
  src/Raven.Studio/typescript/viewmodels/manage/adminLogs.ts
Labels: v4.2

#10914 RavenDB-15413 Reducing the amount of unnecessary work when handling r…
  src/Raven.Server/Documents/CountersStorage.cs
  src/Raven.Server/Documents/Indexes/Workers/Counters/HandleCompareExchangeCountersReferences.cs
  src/Raven.Server/Documents/Indexes/Workers/Counters/HandleCountersReferences.cs
  src/Raven.Server/Documents/Indexes/Workers/HandleReferences.cs
  src/Raven.Server/Documents/Indexes/Workers/TimeSeries/HandleCompareExchangeTimeSeriesReferences.cs
  src/Raven.Server/Documents/Indexes/Workers/TimeSeries/HandleTimeSeriesReferences.cs
Labels: v5.0

#10820 RavenDB-15308 bumping schema version before the release
  src/Raven.Server/Storage/Schema/SchemaUpgrader.cs
  src/Raven.Server/Storage/Schema/Updates/Documents/50001/From42017.cs
  src/Raven.Server/Storage/Schema/Updates/Documents/50001/From50000.cs
Labels: v5.0

#10918 4.2 to 5.0 merge
  LICENSE.txt
  scripts/version.ps1
  src/Raven.Studio/typescript/viewmodels/manage/adminLogs.ts
Labels: v5.0

#10924 RavenDB-15408 IgnoreProcessorAffinityChanges should be respected
  src/Raven.Server/Commercial/LicenseManager.cs
Labels: v4.2

#10920 RavenDB-15407: fix NRE when calculating the size of snapshot restore
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreBackupTaskBase.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Restore/RestoreFromAzure.cs
Labels: v4.2

#10923 RavenDB-15407 - fix multiple calls for a single restore point folder
  src/Raven.Server/Documents/PeriodicBackup/Restore/AzureRestorePoints.cs
Labels: v4.2

#10872 RavenDB-13944 OS info details tooltip width
  src/Raven.Studio/wwwroot/Content/css/pages/etl.less
Labels: v5.1

#10866 RavenDB-15334 Performance improvements for encrypted dbs
  src/Raven.Server/Documents/CompactDatabaseTask.cs
  src/Raven.Server/Documents/ConfigurationStorage.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/IndexDefinitionBase.cs
  src/Raven.Server/Documents/StreamsTempFile.cs
  src/Raven.Server/Documents/TransactionOperationsMerger.cs
  src/Raven.Server/Indexing/VoronIndexOutput.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Voron/Data/Compression/DecompressionBuffersPool.cs
  src/Voron/Impl/Journal/IJournalCompressionBufferCryptoHandler.cs
  src/Voron/Impl/Journal/JournalReader.cs
  src/Voron/Impl/Journal/LazyTransactionBuffer.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/Impl/LowLevelTransaction.cs
  src/Voron/Impl/Paging/AbstractPager.cs
  src/Voron/Impl/Paging/CryptoPager.cs
  src/Voron/StorageEnvironment.cs
  src/Voron/StorageEnvironmentOptions.cs
  test/FastTests/Sparrow/EncryptionTests.cs
  test/SlowTests/Voron/Issues/RavenDB_10813.cs
  test/SlowTests/Voron/Issues/RavenDB_10825.cs
  test/SlowTests/Voron/RavenDB_13940_Encrypted.cs
  tools/Voron.Recovery/Recovery.cs
  tools/rvn/OfflineOperations.cs
Labels: v4.2

#10925 4.2 to 5.0 merge
  src/Raven.Server/Commercial/LicenseManager.cs
  src/Raven.Server/Documents/CompactDatabaseTask.cs
  src/Raven.Server/Documents/ConfigurationStorage.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/IndexDefinitionBase.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/AzureRestorePoints.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreBackupTaskBase.cs
  src/Raven.Server/Documents/StreamsTempFile.cs
  src/Raven.Server/Documents/TransactionOperationsMerger.cs
  src/Raven.Server/Indexing/VoronIndexOutput.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Voron/Data/Compression/DecompressionBuffersPool.cs
  src/Voron/Data/Tables/TableValueCompressor.cs
  src/Voron/Impl/Journal/IJournalCompressionBufferCryptoHandler.cs
  src/Voron/Impl/Journal/JournalReader.cs
  src/Voron/Impl/Journal/LazyTransactionBuffer.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/Impl/LowLevelTransaction.cs
  src/Voron/Impl/Paging/AbstractPager.cs
  src/Voron/Impl/Paging/CryptoPager.cs
  src/Voron/StorageEnvironment.cs
  src/Voron/StorageEnvironmentOptions.cs
  test/FastTests/Sparrow/EncryptionTests.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Restore/RestoreFromAzure.cs
  test/SlowTests/Voron/Issues/RavenDB_10813.cs
  test/SlowTests/Voron/Issues/RavenDB_10825.cs
  test/SlowTests/Voron/RavenDB_13940_Encrypted.cs
  tools/Voron.Recovery/Recovery.cs
  tools/rvn/OfflineOperations.cs
Labels: v5.0

#10929 RavenDB-15401 fix test
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
Labels: v5.0

#10926 RavenDB-15160 updated Lucene
  libs/Lucene.Net.3.0.31.nupkg
  libs/Lucene.Net.3.0.33.nupkg
  libs/dotnet-xunit.2.4.0-beta.1.build9999.nupkg
  src/Raven.Server/Raven.Server.csproj
  tools/Raven.Debug/Raven.Debug.csproj
Labels: v4.2

#10919 RavenDB-15410 Close socket before removing it
  src/Sparrow/Logging/LoggingSource.cs
Labels: v4.2

#10933 RavenDB-15379 fix test
  test/SlowTests/Client/TimeSeries/Query/QueryFromMultipleTimeSeries.cs
Labels: v5.0

#10932 RavenDB-15353 add more asserts
  src/Raven.Server/Documents/TimeSeries/TimeSeriesPolicyRunner.cs
  test/SlowTests/Smuggler/SmugglerApiTests.cs
Labels: v5.0

#10915 RavenDB-14533 Debug endpoint to show segments on time series
  src/Raven.Server/Documents/Handlers/TimeSeriesHandler.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesReader.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesStorage.cs
  test/SlowTests/Client/TimeSeries/Issues/RavenDB-14533.cs
Labels: v5.0

#10934 4.2 to 5.0 merge
  RavenDB.sln
  libs/Lucene.Net.3.0.33.nupkg
  src/CommonAssemblyInfo.Linux.cs
  src/CommonAssemblyInfo.Windows.cs
  src/Raven.Client/ServerWide/Commands/Cluster/DemoteClusterNodeCommand.cs
  src/Raven.Client/ServerWide/Commands/Cluster/PromoteClusterNodeCommand.cs
  src/Raven.Server/Commercial/LicenseManager.cs
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/ETL/EtlLoader.cs
  src/Raven.Server/Documents/Handlers/Admin/RachisAdminHandler.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreBackupTaskBase.cs
  src/Raven.Server/Documents/Replication/IncomingReplicationHandler.cs
  src/Raven.Server/Documents/Replication/OutgoingReplicationHandler.cs
  src/Raven.Server/Documents/Replication/ReplicationDocumentSender.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/Documents/TcpHandlers/SubscriptionConnection.cs
  src/Raven.Server/Documents/TcpHandlers/TcpConnectionOptions.cs
  src/Raven.Server/Rachis/Follower.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/Rachis/RachisStateMachine.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Sparrow/Logging/LoggingSource.cs
  src/Voron/Data/BTrees/Tree.cs
  src/Voron/Data/Compression/DecompressedLeafPage.cs
  test/LicenseTests/LicenseLimitsTests.cs
  test/LicenseTests/LicenseTests.csproj
  test/RachisTests/DatabaseCluster/RemoveNodeFromCluster.cs
  test/SlowTests/Issues/RavenDB_15409.cs
  test/SlowTests/Voron/LeafsCompression/RavenDB_15302.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
  test/Tests.Infrastructure/RavenTestBase.cs
  test/Tests.Infrastructure/TestBase.cs
  tools/Raven.Debug/Raven.Debug.csproj
Labels: v5.0

#10937 5.0 to 5.1 merge
  RavenDB.sln
  libs/Lucene.Net.3.0.33.nupkg
  src/CommonAssemblyInfo.Linux.cs
  src/CommonAssemblyInfo.Windows.cs
  src/Raven.Client/Documents/Session/AsyncSessionDocumentTimeSeries.cs
  src/Raven.Client/Json/Serialization/NewtonsoftJson/DefaultRavenContractResolver.cs
  src/Raven.Client/Json/Serialization/NewtonsoftJson/NewtonsoftJsonSerializationConventions.cs
  src/Raven.Client/ServerWide/Commands/Cluster/DemoteClusterNodeCommand.cs
  src/Raven.Client/ServerWide/Commands/Cluster/PromoteClusterNodeCommand.cs
  src/Raven.Server/Commercial/LicenseManager.cs
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/ETL/EtlLoader.cs
  src/Raven.Server/Documents/Handlers/Admin/RachisAdminHandler.cs
  src/Raven.Server/Documents/Handlers/TimeSeriesHandler.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreBackupTaskBase.cs
  src/Raven.Server/Documents/Replication/IncomingReplicationHandler.cs
  src/Raven.Server/Documents/Replication/OutgoingReplicationHandler.cs
  src/Raven.Server/Documents/Replication/ReplicationDocumentSender.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/Documents/TcpHandlers/SubscriptionConnection.cs
  src/Raven.Server/Documents/TcpHandlers/TcpConnectionOptions.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesPolicyRunner.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesReader.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesStorage.cs
  src/Raven.Server/Rachis/Follower.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/Rachis/RachisStateMachine.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Sparrow/Logging/LoggingSource.cs
  src/Voron/Data/BTrees/Tree.cs
  src/Voron/Data/Compression/DecompressedLeafPage.cs
  test/FastTests/Client/SerializationTweaking.cs
  test/LicenseTests/LicenseLimitsTests.cs
  test/LicenseTests/LicenseTests.csproj
  test/RachisTests/DatabaseCluster/RemoveNodeFromCluster.cs
  test/SlowTests/Client/TimeSeries/Issues/RavenDB-14533.cs
  test/SlowTests/Client/TimeSeries/Issues/RavenDB-14633.cs
  test/SlowTests/Client/TimeSeries/Issues/RavenDB-15246.cs
  test/SlowTests/Client/TimeSeries/Query/QueryFromMultipleTimeSeries.cs
  test/SlowTests/Issues/RavenDB_15409.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
  test/SlowTests/Smuggler/SmugglerApiTests.cs
  test/SlowTests/Voron/LeafsCompression/RavenDB_15302.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
  test/Tests.Infrastructure/RavenTestBase.cs
  test/Tests.Infrastructure/TestBase.cs
  tools/Raven.Debug/Raven.Debug.csproj
Labels: v5.1

#10938 RavenDB-15401 fix test
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
Labels: v5.0

#10940 RavenDB-15438 Parsing a query on index when index name is not quoted …
  src/Raven.Studio/typescript/common/queryUtil.ts
Labels: v5.0

#10950 RavenDB-15450 : Filtering and projecting sub-collection fails with reference scope error
  src/Raven.Client/Util/JavascriptConversionExtensions.cs
  test/SlowTests/Issues/RavenDB_15450.cs
Labels: v5.0

#10951 RavenDB-15372 restore backup - check for empty folder fixed & more info if RavenDB_10420.ShouldWork fail on this check
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreBackupTaskBase.cs
  test/SlowTests/Issues/RavenDB_10420.cs
Labels: v5.0

#10948 RavenDB-15244 ServerWideBackupShouldBackupIdleDatabase test - Adding information in failing and improve test timing
  test/SlowTests/Issues/RavenDB_14292.cs
Labels: v4.2

#10947 RavenDB-15451 added ForceRevisionCreationFor to Async API
  src/Raven.Client/Documents/Session/DocumentSessionRevisions.cs
  src/Raven.Client/Documents/Session/DocumentSessionRevisionsAsync.cs
  src/Raven.Client/Documents/Session/IRevisionsSessionOperationsAsync.cs
  test/SlowTests/Client/ForceRevisionCreation.cs
Labels: v4.2

#10939 RavenDB-14988
  src/Raven.Server/Documents/Queries/AST/Query.cs
  src/Raven.Server/Documents/Queries/Results/TimeSeriesRetriever.cs
  test/SlowTests/Client/TimeSeries/Query/TimeSeriesLinqQuery.cs
  test/SlowTests/Client/TimeSeries/Query/TimeSeriesRawQuery.cs
Labels: v5.0

#10931 RavenDB-15441 - add support for LINQ for first class patch
  src/Raven.Client/Documents/Session/InMemoryDocumentSessionOperations.cs
  test/FastTests/Client/FirstClassPatch.cs
Labels: v4.2

#10955 4.2 to 5.0 merge
  src/Raven.Client/Documents/Session/AdvancedSessionExtensionBase.cs
  src/Raven.Client/Documents/Session/DocumentSessionRevisions.cs
  src/Raven.Client/Documents/Session/DocumentSessionRevisionsAsync.cs
  src/Raven.Client/Documents/Session/IRevisionsSessionOperationsAsync.cs
  test/SlowTests/Client/ForceRevisionCreation.cs
  test/SlowTests/Client/TimeSeries/Issues/RavenDB-15246.cs
  test/SlowTests/Issues/RavenDB_14292.cs
Labels: v5.0

#10954 RavenDB-15441 - add support for Nullable type in first class patch
  src/Raven.Client/Documents/Session/InMemoryDocumentSessionOperations.cs
  test/FastTests/Client/FirstClassPatch.cs
Labels: v5.0

#10958 RavenDB-7070 deleting a database in a test
  test/SlowTests/RecoveryTests/SampleDatabaseRecovery.cs
Labels: v5.0
