Repository ravendb/ravendb, pull requests merged in 2020-11, with the labels that each got.

#11329 RavenDB-15734 About page style regression
  src/Raven.Studio/wwwroot/App/views/shell/about.html
  src/Raven.Studio/wwwroot/Content/css/pages/about.less
Labels: v5.1

#11316 RavenDB-15669 properly handle hash if no TS entries found
  src/Raven.Client/Documents/Session/AsyncSessionDocumentTimeSeries.cs
  src/Raven.Server/Documents/ComputeHttpEtags.cs
  src/Raven.Server/Documents/Handlers/DocumentHandler.cs
  src/Raven.Server/Documents/Handlers/TimeSeriesHandler.cs
  src/Raven.Server/Documents/Includes/IncludeTimeSeriesCommand.cs
  test/SlowTests/Client/TimeSeries/Issues/RavenDB-15246.cs
  test/SlowTests/Client/TimeSeries/Session/TimeSeriesRangesCache.cs
Labels: v5.0

#11330 RavenDB-14695 clear the bitmap array
  src/Raven.Server/Documents/Queries/LuceneIntegration/FastBitArray.cs
Labels: v4.2

#11335 5.0 to 5.1 merge
  src/Raven.Client/Documents/Session/AsyncSessionDocumentTimeSeries.cs
  src/Raven.Server/Documents/ComputeHttpEtags.cs
  src/Raven.Server/Documents/Handlers/TimeSeriesHandler.cs
  src/Raven.Server/Documents/Includes/IncludeTimeSeriesCommand.cs
  src/Raven.Server/Documents/Queries/LuceneIntegration/FastBitArray.cs
  test/SlowTests/Client/TimeSeries/Issues/RavenDB-15246.cs
  test/SlowTests/Client/TimeSeries/Session/TimeSeriesRangesCache.cs
Labels: v5.1

#11337 RDBCL-1378 use CpuUsage metric cache slot for io wait since it's calc…
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.5/IoWait.cs
  src/Raven.Server/Utils/MetricCacher.cs
Labels: v4.2

#11333 RavenDB-15797 The client test should not wait for client configuration to be changed while it is not changed in the server
  test/SlowTests/Issues/RavenDB-14978.cs
Labels: v5.0

#11340 RavenDB-15786 Increasing the number of MinThreads on Thread Pool (de…
  src/Raven.Server/Program.cs
  src/Raven.Server/RavenServer.cs
Labels: v4.2

#11342 4.2 to 5.0 merge
  src/Raven.Client/Documents/Commands/DropSubscriptionConnectionCommand.cs
  src/Raven.Client/Documents/Operations/ETL/ResetEtlOperation.cs
  src/Raven.Client/Documents/Operations/ResultsResponse.cs
  src/Raven.Client/Json/Serialization/JsonDeserializationClient.cs
  src/Raven.Client/ServerWide/Operations/Certificates/CertificateDefinition.cs
  src/Raven.Client/ServerWide/Operations/Certificates/EditClientCertificateOperation.cs
  src/Raven.Client/ServerWide/Operations/Certificates/GetCertificateMetadataOperation.cs
  src/Raven.Client/ServerWide/Operations/Certificates/GetCertificatesMetadataOperation.cs
  src/Raven.Client/ServerWide/Operations/Certificates/PutClientCertificateOperation.cs
  src/Raven.Server/Config/Categories/ServerConfiguration.cs
  src/Raven.Server/Documents/Subscriptions/SubscriptionStorage.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.5/IoWait.cs
  src/Raven.Server/Program.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/Commands/Subscriptions/AcknowledgeSubscriptionBatchCommand.cs
  src/Raven.Server/Utils/MetricCacher.cs
  src/Raven.Server/Web/Authentication/AdminCertificatesHandler.cs
  src/Raven.Studio/typescript/commands/auth/getCertificatesCommand.ts
  test/FastTests/Client/RavenCommandTest.cs
  test/SlowTests/Authentication/AuthenticationBasicTests.cs
  test/Tests.Infrastructure/RavenTestBase.cs
  test/Tests.Infrastructure/RavenTestHelper.cs
Labels: v5.0

#11343 RavenDB-15705 properly handling nested arrays which can be of type BlittableJsonReaderArray
  src/Raven.Server/Documents/Indexes/MapReduce/Static/MapReduceIndex.cs
Labels: v5.1

#11341 Raven db 15699
  src/Raven.Studio/typescript/commands/database/query/queryCommand.ts
Labels: v5.0

#11344 RavenDB-7070 fixing test and normalizing the messages
  src/Raven.Server/Documents/Subscriptions/SubscriptionStorage.cs
  src/Raven.Server/ServerWide/Commands/Subscriptions/AcknowledgeSubscriptionBatchCommand.cs
  src/Raven.Server/ServerWide/Commands/Subscriptions/UpdateSubscriptionClientConnectionTime.cs
  src/Raven.Server/Web/System/OngoingTasksHandler.cs
  test/FastTests/Client/Subscriptions/SubscriptionsBasic.cs
  test/SlowTests/Client/Subscriptions/SubscriptionsBasic.cs
Labels: v5.0

#11346 5.0 to 5.1 merge
  src/Raven.Client/Documents/Commands/DropSubscriptionConnectionCommand.cs
  src/Raven.Client/Documents/Operations/ETL/ResetEtlOperation.cs
  src/Raven.Client/Documents/Operations/ResultsResponse.cs
  src/Raven.Client/Json/Serialization/JsonDeserializationClient.cs
  src/Raven.Client/ServerWide/Operations/Certificates/CertificateDefinition.cs
  src/Raven.Client/ServerWide/Operations/Certificates/EditClientCertificateOperation.cs
  src/Raven.Client/ServerWide/Operations/Certificates/GetCertificateMetadataOperation.cs
  src/Raven.Client/ServerWide/Operations/Certificates/GetCertificatesMetadataOperation.cs
  src/Raven.Client/ServerWide/Operations/Certificates/PutClientCertificateOperation.cs
  src/Raven.Server/Config/Categories/ServerConfiguration.cs
  src/Raven.Server/Documents/Queries/AST/Query.cs
  src/Raven.Server/Documents/Queries/Results/TimeSeries/TimeSeriesRetriever.cs
  src/Raven.Server/Documents/Subscriptions/SubscriptionStorage.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.5/IoWait.cs
  src/Raven.Server/Program.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/Commands/Subscriptions/AcknowledgeSubscriptionBatchCommand.cs
  src/Raven.Server/ServerWide/Commands/Subscriptions/UpdateSubscriptionClientConnectionTime.cs
  src/Raven.Server/Utils/MetricCacher.cs
  src/Raven.Server/Web/Authentication/AdminCertificatesHandler.cs
  src/Raven.Server/Web/System/OngoingTasksHandler.cs
  src/Raven.Studio/typescript/commands/auth/getCertificatesCommand.ts
  src/Raven.Studio/typescript/commands/database/query/queryCommand.ts
  test/FastTests/Client/RavenCommandTest.cs
  test/FastTests/Client/Subscriptions/SubscriptionsBasic.cs
  test/SlowTests/Authentication/AuthenticationBasicTests.cs
  test/SlowTests/Client/Subscriptions/SubscriptionsBasic.cs
  test/SlowTests/Client/TimeSeries/Issues/RavenDB_15732.cs
  test/SlowTests/Client/TimeSeries/Query/TimeSeriesLinqQuery.cs
  test/SlowTests/Issues/RavenDB-14978.cs
  test/Tests.Infrastructure/RavenTestBase.cs
  test/Tests.Infrastructure/RavenTestHelper.cs
Labels: v5.1

#11347 RavenDB-15741 use EnumerateAndClear when cleaning EncryptionBufferPool on low memory, if not we will only clear allocations from current core
  src/Voron/Impl/EncryptionBuffersPool.cs
Labels: v5.0

#11348 Raven db 13565
  src/Raven.Studio/wwwroot/App/views/database/tasks/importDatabaseFromSql.html
  src/Raven.Studio/wwwroot/Content/css/pages/sql-migration.less
Labels: v5.1

#11350 RavenDB-15794 Circle spatial field not created for javascript index
  src/Raven.Server/Documents/Indexes/Static/JavaScriptIndex.cs
  test/SlowTests/Issues/RavenDB-15794.cs
Labels: v4.2

#11351 RavenDB-15297 - Fix for Studio
  src/Raven.Studio/typescript/viewmodels/database/tasks/editReplicationSinkTask.ts
Labels: v5.1

#11353 RavenDB-15816 exposed available worker and completion port threads in SNMP
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.14/ThreadPoolAvailableCompletionPortThreads.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.14/ThreadPoolAvailableWorkerThreads.cs
  src/Raven.Server/Monitoring/Snmp/SnmpOids.cs
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
Labels: v4.2

#11354 RavenDB-15786 Introducing separate options for worker threads and asy…
  src/Raven.Server/Config/Categories/ServerConfiguration.cs
  src/Raven.Server/Program.cs
Labels: v4.2

#11355 RavenDB-15785 introduced UseTaskAwaiterWhenNoSynchronizationContextIsAvailable
  src/Raven.Client/Util/AsyncHelpers.cs
Labels: v4.2

#11357 RavenDB-15723 Connection strings view title visibility fix
  src/Raven.Studio/wwwroot/App/views/database/settings/connectionStrings.html
  src/Raven.Studio/wwwroot/Content/css/pages/etl.less
  src/Raven.Studio/wwwroot/Content/css/styles-common.less
Labels: v5.1

#11352 RavenDB-15815 Fix merge 4.2->5.0
  test/FastTests/Client/RavenCommandTest.cs
Labels: v5.0

#11358 4.2 to 5.0 merge
  src/Raven.Client/Util/AsyncHelpers.cs
  src/Raven.Server/Config/Categories/ServerConfiguration.cs
  src/Raven.Server/Documents/Indexes/Static/JavaScriptIndex.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.14/ThreadPoolAvailableCompletionPortThreads.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.14/ThreadPoolAvailableWorkerThreads.cs
  src/Raven.Server/Monitoring/Snmp/SnmpOids.cs
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
  src/Raven.Server/Program.cs
  test/SlowTests/Issues/RavenDB-15794.cs
Labels: v5.0

#11359 5.0 to 5.1 merge
  src/Raven.Client/Documents/Subscriptions/DocumentSubscriptions.cs
  src/Raven.Client/Util/AsyncHelpers.cs
  src/Raven.Client/Util/JavascriptConversionExtensions.cs
  src/Raven.Server/Config/Categories/ServerConfiguration.cs
  src/Raven.Server/Documents/Indexes/Static/JavaScriptIndex.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.14/ThreadPoolAvailableCompletionPortThreads.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.14/ThreadPoolAvailableWorkerThreads.cs
  src/Raven.Server/Monitoring/Snmp/SnmpOids.cs
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
  src/Raven.Server/Program.cs
  test/FastTests/Client/RavenCommandTest.cs
  test/SlowTests/Client/Subscriptions/RavenDB-15553.cs
  test/SlowTests/Issues/RavenDB-15794.cs
Labels: v5.1

#11360 RavenDB-15815 Fix merge RavenCommandTest 5.0-> 5.1
  test/FastTests/Client/RavenCommandTest.cs
Labels: v5.1

#11362 RavenDB-7070 updated to .NET 5.0 RTM
  .github/workflows/FastTests.yml
  NuGet.Config
  bench/BulkInsert.Benchmark/BulkInsert.Benchmark.csproj
  bench/Indexing.Benchmark/Indexing.Benchmark.csproj
  bench/Micro.Benchmark/Micro.Benchmark.csproj
  bench/Regression.Benchmark/Regression.Benchmark.csproj
  bench/SubscriptionFailover.Benchmark/SubscriptionFailover.Benchmark.csproj
  bench/Subscriptions.Benchmark/Subscriptions.Benchmark.csproj
  bench/TimeSeries.Benchmark/TimeSeries.Benchmark.csproj
  bench/Voron.Benchmark/Voron.Benchmark.csproj
  scripts/buildProjects.ps1
  src/Raven.Client/Raven.Client.csproj
  src/Raven.Embedded/ServerOptions.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Studio/Raven.Studio.csproj
  src/Sparrow.Server/Sparrow.Server.csproj
  src/Sparrow/Sparrow.csproj
  src/Voron/Voron.csproj
  test/BenchmarkTests/BenchmarkTests.csproj
  test/EmbeddedTests/EmbeddedTests.csproj
  test/FastTests/FastTests.csproj
  test/InterversionTests/InterversionTests.csproj
  test/LicenseTests/LicenseTests.csproj
  test/RachisTests/RachisTests.csproj
  test/SlowTests/SlowTests.csproj
  test/StressTests/StressTests.csproj
  test/Studio/Studio.csproj
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
  test/Tryouts/Tryouts.csproj
  tools/Raven.Debug/Raven.Debug.csproj
  tools/Raven.Migrator/Raven.Migrator.csproj
  tools/TypingsGenerator/TypingsGenerator.csproj
  tools/Voron.Recovery/Voron.Recovery.csproj
  tools/rvn/rvn.csproj
Labels: v5.1

#11367 RavenDB-15823 Cannot create new index
  src/Raven.Studio/typescript/models/database/index/indexDefinition.ts
Labels: v5.1

#11365 RavenDB-7070 add timeout to server disposal in tests
  src/Raven.Server/RavenServer.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v4.2

#11361 RavenDB-14991: Rework subscription failing test
  test/RachisTests/SubscriptionFailoverWIthWaitingChains.cs
Labels: v4.2

#11374 RavenDB-15828 Fix 5.1 replication protocol to be compatible with 5.0
  src/Raven.Server/Documents/Replication/OutgoingReplicationHandler.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
Labels: v5.1

#11363 RavenDB-15704 Support plan in the studio for Cloud
  src/Raven.Studio/typescript/viewmodels/shell/about.ts
  src/Raven.Studio/wwwroot/App/views/shell/about.html
Labels: v4.2

#11371 RavenDB-15826 LazyLoad does not handle already included documents
  src/Raven.Client/Documents/Session/Operations/Lazy/LazyLoadOperation.cs
  test/SlowTests/Issues/RavenDB-15826.cs
Labels: v4.2

#11373 RavenDB-15827 : TimeSeries: C# parsing of Groupby value fails
  src/Raven.Client/Documents/Queries/TimeSeries/TimeSeriesQueryVisitor.cs
  test/SlowTests/Client/TimeSeries/Issues/RavenDB-15827.cs
Labels: v5.0

#11378 RavenDB-15831 fix failing test
  test/SlowTests/Client/TimeSeries/Session/TimeSeriesStreamingTests.cs
Labels: v5.1

#11379 4.2 to 5.0 merge
  bench/Regression.Benchmark/Regression.Benchmark.csproj
  src/Raven.Client/Documents/Queries/HashCalculator.cs
  src/Raven.Client/Documents/Session/Operations/Lazy/LazyLoadOperation.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.15/TcpActiveConnections.cs
  src/Raven.Server/Monitoring/Snmp/SnmpOids.cs
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Server/RavenServer.cs
  src/Raven.Server/Web/System/AdminTcpConnectionDebugInfoHandler.cs
  src/Raven.Studio/typescript/viewmodels/shell/about.ts
  src/Raven.Studio/wwwroot/App/views/shell/about.html
  src/Sparrow.Server/Extensions/TcpExtensions.cs
  test/BenchmarkTests/BenchmarkTests.csproj
  test/EmbeddedTests/EmbeddedTests.csproj
  test/FastTests/FastTests.csproj
  test/InterversionTests/InterversionTests.csproj
  test/LicenseTests/LicenseTests.csproj
  test/RachisTests/RachisTests.csproj
  test/RachisTests/RavenDB_14348.cs
  test/RachisTests/SubscriptionFailoverWIthWaitingChains.cs
  test/SlowTests/Issues/RavenDB-15826.cs
  test/SlowTests/Issues/RavenDB_15825.cs
  test/SlowTests/SlowTests.csproj
  test/StressTests/StressTests.csproj
  test/Tests.Infrastructure/ClusterTestBase.cs
  test/Tests.Infrastructure/TestBase.cs
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
  tools/Raven.Migrator/Raven.Migrator.csproj
Labels: v5.0

#11380 5.0 to 5.1 merge
  src/Raven.Client/Documents/Queries/HashCalculator.cs
  src/Raven.Client/Documents/Queries/TimeSeries/TimeSeriesQueryVisitor.cs
  src/Raven.Client/Documents/Session/Operations/Lazy/LazyLoadOperation.cs
  src/Raven.Server/Documents/Handlers/QueriesHandler.cs
  src/Raven.Server/Documents/Queries/IndexQueryServerSide.cs
  src/Raven.Server/Documents/Queries/QueryResultServerSide.cs
  src/Raven.Server/Documents/Queries/Results/QueryResultRetrieverBase.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.15/TcpActiveConnections.cs
  src/Raven.Server/Monitoring/Snmp/SnmpOids.cs
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
  src/Raven.Server/RavenServer.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/Web/System/AdminTcpConnectionDebugInfoHandler.cs
  src/Raven.Studio/typescript/commands/database/query/queryCommand.ts
  src/Raven.Studio/typescript/viewmodels/shell/about.ts
  src/Raven.Studio/wwwroot/App/views/shell/about.html
  src/Sparrow.Server/Extensions/TcpExtensions.cs
  test/RachisTests/RavenDB_14348.cs
  test/RachisTests/SubscriptionFailoverWIthWaitingChains.cs
  test/SlowTests/Client/TimeSeries/Issues/RavenDB-15827.cs
  test/SlowTests/Issues/RavenDB-15826.cs
  test/SlowTests/Issues/RavenDB_15825.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v5.1

#11381 RavenDB-15817 Expose timeSeriesFields based on parameter, not based o…
  test/SlowTests/Client/TimeSeries/Issues/RavenDB-15759.cs
Labels: v5.1

#11382 RavenDB-15645 bump documents version
  src/Raven.Server/Storage/Schema/SchemaUpgrader.cs
  src/Raven.Server/Storage/Schema/Updates/Documents/50002/From50001.cs
Labels: v5.0

#11383 RavenDB-15834 Make SnapshotInstalled() sync method - nothing is async there
  src/Raven.Server/Rachis/Follower.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/Rachis/RachisStateMachine.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
Labels: v4.2

#11375 RavenDB-15668 Document Revisions View - Enhancements
  src/Raven.Studio/typescript/models/database/documents/revisionsConfigurationEntry.ts
  src/Raven.Studio/typescript/viewmodels/database/settings/revisions.ts
  src/Raven.Studio/wwwroot/App/views/database/settings/revisions.html
Labels: v5.1

#11386 HRINT-1952 update base docker image
  docker/ravendb-ubuntu/Dockerfile.arm32v7
  docker/ravendb-ubuntu/Dockerfile.x64
Labels: v5.1

#11385 RavenDB-15842 Fix Stack overflow in Voron.Impl.LowLevelTransaction.ThrowObjectDisposed
  src/Voron/Impl/LowLevelTransaction.cs
Labels: v4.2

#11388 RavenDB-15843 Add TCP statistics to test resource snapshot
  test/Tests.Infrastructure/TestMetrics/TcpStatisticsProvider.cs
  test/Tests.Infrastructure/TestMetrics/TestResourceSnapshotWriter.cs
  test/Tests.Infrastructure/TestMetrics/TestResourcesAnalyzerMetricCacher.cs
  test/Tests.Infrastructure/TestResourcesAnalyzerMetricCacher.cs
  test/Tests.Infrastructure/XunitExtensions/PerformanceTestAssemblyRunner.cs
  test/Tests.Infrastructure/XunitExtensions/PerformanceTestClassRunner.cs
  test/Tests.Infrastructure/XunitExtensions/PerformanceTestCollectionRunner.cs
  test/Tests.Infrastructure/XunitExtensions/PerformanceTestExecutor.cs
Labels: v4.2

#11389 4.2 to 5.0 merge
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/Rachis/Leader.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Utils/PoolOfThreads.cs
  src/Voron/Impl/LowLevelTransaction.cs
  test/Tests.Infrastructure/TestMetrics/TcpStatisticsProvider.cs
  test/Tests.Infrastructure/TestMetrics/TestResourceSnapshotWriter.cs
  test/Tests.Infrastructure/TestMetrics/TestResourcesAnalyzerMetricCacher.cs
  test/Tests.Infrastructure/TestResourcesAnalyzerMetricCacher.cs
  test/Tests.Infrastructure/XunitExtensions/PerformanceTestAssemblyRunner.cs
  test/Tests.Infrastructure/XunitExtensions/PerformanceTestClassRunner.cs
  test/Tests.Infrastructure/XunitExtensions/PerformanceTestCollectionRunner.cs
  test/Tests.Infrastructure/XunitExtensions/PerformanceTestExecutor.cs
Labels: v5.0

#11399 RavenDB-15848 register additional assembles as known dlls
  src/Raven.Server/Documents/Indexes/Static/IndexCompiler.cs
Labels: v5.1

#11401 RavenDB-15833 Menu graphic issues
  src/Raven.Studio/typescript/common/shell/menu/generateMenuItems.ts
  src/Raven.Studio/wwwroot/Content/css/icons.less
  src/Raven.Studio/wwwroot/Content/css/main-menu.less
Labels: v5.1

#11398 RavenDB-15733 Allow to export revisions even when revision configurat…
  src/Raven.Studio/typescript/models/database/tasks/exportDatabaseModel.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/exportDatabase.ts
  src/Raven.Studio/wwwroot/App/views/database/tasks/exportDatabase.html
Labels: v4.2

#11394 RavenDB-15778 Fix the 'dirty' behavior for ongoing tasks
  src/Raven.Studio/typescript/models/database/settings/connectionStringRavenEtlModel.ts
  src/Raven.Studio/typescript/models/database/settings/connectionStringSqlEtlModel.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editExternalReplicationTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editPullReplicationSinkTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editRavenEtlTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editSqlEtlTask.ts
  src/Raven.Studio/wwwroot/App/views/database/tasks/editPeriodicBackupTask.html
Labels: v4.2

#11393 RavenDB-15731 Add more info to Enforce Revisions Configuration View
  src/Raven.Studio/typescript/viewmodels/database/settings/revisions.ts
Labels: v4.2

#11403 4.2 to 5.0 merge
  src/Raven.Studio/typescript/common/shell/accessManager.ts
  src/Raven.Studio/typescript/models/database/settings/connectionStringRavenEtlModel.ts
  src/Raven.Studio/typescript/models/database/settings/connectionStringSqlEtlModel.ts
  src/Raven.Studio/typescript/models/database/tasks/exportDatabaseModel.ts
  src/Raven.Studio/typescript/viewmodels/database/settings/revisions.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editExternalReplicationTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editPullReplicationSinkTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editRavenEtlTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editSqlEtlTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/exportDatabase.ts
  src/Raven.Studio/typescript/viewmodels/shell/about.ts
  src/Raven.Studio/wwwroot/App/views/database/tasks/editPeriodicBackupTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/exportDatabase.html
  src/Raven.Studio/wwwroot/App/views/shell/about.html
  test/FastTests/Client/RequestExecutorTests.cs
  test/SlowTests/Client/RequestExecutorTestsSlow.cs
Labels: v5.0

#11406 RavenDB-15779 HashCalculator use DateTime.GetDefaultRavenFormat
  src/Raven.Client/Documents/Queries/HashCalculator.cs
  test/FastTests/Client/Queries/QueryTests.cs
Labels: v5.0

#11405 RavenDB-15858 Fix Infinite recursion in query
  src/Raven.Client/Documents/Queries/HashCalculator.cs
  test/FastTests/Client/Queries/QueryTests.cs
Labels: v4.2

#11404 RavenDB-15769 : fix failing tests
  test/SlowTests/Client/TimeSeries/Issues/RavenDB-15010.cs
  test/SlowTests/Client/TimeSeries/Replication/TimeSeriesReplicationTests.cs
Labels: v5.0

#11407 RavenDB-15859 Endless query when doing optimized IN queries
  src/Raven.Server/Documents/Queries/LuceneIntegration/TermsMatchQuery.cs
  test/SlowTests/SlowTests/Issues/RavenDB-15859.cs
Labels: v4.2

#11408 RavenDB-15858 guard against infinite recursion
  src/Raven.Client/Documents/Queries/HashCalculator.cs
Labels: v4.2

#11410 4.2 to 5.0 merge
  src/Raven.Client/Documents/Queries/HashCalculator.cs
  src/Raven.Server/Documents/Queries/LuceneIntegration/TermsMatchQuery.cs
  test/FastTests/Client/Queries/QueryTests.cs
  test/SlowTests/SlowTests/Issues/RavenDB-15859.cs
Labels: v5.0

#11413 RavenDB-15714 refactor code
  src/Raven.Studio/typescript/viewmodels/shell/about.ts
Labels: v4.2

#11411 RavenDB-15856 Throw ObjectDisposedException instead of NRE when the p…
  src/Voron/Impl/Paging/AbstractPager.cs
  test/SlowTests/Issues/RavenDB_15856.cs
Labels: v4.2

#11414 RavenDB-15855 Avoid duplicated tasks of pull Replication
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  test/SlowTests/Server/Replication/PullReplicationTests.cs
Labels: v4.2

#11416 RavenDB-15836
  src/Raven.Client/Documents/Queries/TimeSeries/TimeSeriesQueryVisitor.cs
  test/SlowTests/Client/TimeSeries/Issues/RavenDB_15836.cs
Labels: v5.0

#11420 4.2 to 5.0 merge
  src/Raven.Client/Documents/Queries/HashCalculator.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Studio/typescript/viewmodels/shell/about.ts
  src/Voron/Impl/Paging/AbstractPager.cs
  test/SlowTests/Issues/RavenDB_15856.cs
  test/SlowTests/Issues/RavenDB_15866.cs
  test/SlowTests/Server/Replication/PullReplicationTests.cs
Labels: v5.0

#11418 RavenDB-15868
  src/Raven.Server/Commercial/LicenseHelper.cs
  src/Raven.Server/Commercial/LicenseManager.cs
Labels: v4.2

#11415 RavenDB-15722 Connections strings that are used by tasks - Fix behavior
  src/Raven.Studio/typescript/viewmodels/database/settings/connectionStrings.ts
  src/Raven.Studio/wwwroot/App/views/database/settings/connectionStrings.html
Labels: v5.1

#11421 5.0 to 5.1 merge
  src/Raven.Client/Documents/Queries/HashCalculator.cs
  src/Raven.Client/Properties/VersionInfo.cs
  src/Raven.Server/Commercial/LicenseManager.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/Queries/LuceneIntegration/TermsMatchQuery.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/Rachis/Leader.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Utils/PoolOfThreads.cs
  src/Raven.Studio/typescript/common/shell/accessManager.ts
  src/Raven.Studio/typescript/models/database/settings/connectionStringSqlEtlModel.ts
  src/Raven.Studio/typescript/models/database/tasks/exportDatabaseModel.ts
  src/Raven.Studio/typescript/viewmodels/database/settings/revisions.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editExternalReplicationTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editRavenEtlTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editSqlEtlTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/exportDatabase.ts
  src/Raven.Studio/typescript/viewmodels/shell/about.ts
  src/Raven.Studio/wwwroot/App/views/database/tasks/editPeriodicBackupTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/exportDatabase.html
  src/Raven.Studio/wwwroot/App/views/shell/about.html
  src/Voron/Impl/LowLevelTransaction.cs
  src/Voron/Impl/Paging/AbstractPager.cs
  test/FastTests/Client/Queries/QueryTests.cs
  test/FastTests/Client/RequestExecutorTests.cs
  test/SlowTests/Client/RequestExecutorTestsSlow.cs
  test/SlowTests/Issues/RavenDB_15856.cs
  test/SlowTests/Issues/RavenDB_15866.cs
  test/SlowTests/Server/Replication/PullReplicationTests.cs
  test/SlowTests/SlowTests/Issues/RavenDB-15859.cs
  test/Tests.Infrastructure/TestMetrics/TcpStatisticsProvider.cs
  test/Tests.Infrastructure/TestMetrics/TestResourceSnapshotWriter.cs
  test/Tests.Infrastructure/TestMetrics/TestResourcesAnalyzerMetricCacher.cs
  test/Tests.Infrastructure/TestResourcesAnalyzerMetricCacher.cs
  test/Tests.Infrastructure/XunitExtensions/PerformanceTestAssemblyRunner.cs
  test/Tests.Infrastructure/XunitExtensions/PerformanceTestClassRunner.cs
  test/Tests.Infrastructure/XunitExtensions/PerformanceTestCollectionRunner.cs
  test/Tests.Infrastructure/XunitExtensions/PerformanceTestExecutor.cs
  tools/Raven.Debug/Raven.Debug.csproj
Labels: v5.1

#11423 RavenDB-15606 Add "/admin/stats" end point to debug package
  src/Raven.Server/Web/System/AdminStatsHandler.cs
Labels: v4.2

#11425 RDBCL-1656 copy native binaries outside of publish pipeline
  scripts/package.ps1
Labels: v5.1

#11427 RavenDB-15832 Show counts on tabs when editing an index to indicate t…
  src/Raven.Studio/wwwroot/App/views/database/indexes/editIndex.html
Labels: v5.1

#11428 RDBCL-1656 fix native bin extension for osx
  scripts/package.ps1
  scripts/target.ps1
Labels: v5.1

#11419 RavenDB-15814 When node is passive and license is not activated, stat…
  src/Raven.Studio/typescript/viewmodels/shell/about.ts
  src/Raven.Studio/wwwroot/App/views/shell/about.html
Labels: v4.2

#11433 HRINT-1952 fix docker image tags using ubuntu focal
  docker/common.ps1
Labels: v5.1

#11432 RavenDB-15870 / RavenDB-15856 Let's try to throw ObjectDisposedExcept…
  src/Voron/Data/Compression/DecompressionBuffersPool.cs
  src/Voron/Impl/Paging/Windows32BitsMemoryMapPager.cs
Labels: v4.2

#11436 RavenDB-15830 Edit index tabs - Enhancements
  src/Raven.Studio/typescript/models/database/index/indexDefinition.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/editIndex.ts
  src/Raven.Studio/wwwroot/App/views/database/indexes/editIndex.html
Labels: v5.1

#11437 RavenDB-15720 Ongoing Hub & Sink Tasks Details: refactor details text
  src/Raven.Studio/wwwroot/App/views/database/tasks/ongoingTasks.html
Labels: v5.1

#11435 RavenDB-15819: use unreachable cluster index in test
  test/FastTests/Client/Subscriptions/SubscriptionsBasic.cs
Labels: v5.0

#11429 RavenDB-15800 - fix backup tests
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
Labels: v4.2

#11438 RavenDB-15846 Update the Enforce Revisions Configuration popup in 5.1
  src/Raven.Studio/typescript/viewmodels/database/settings/revisions.ts
Labels: v5.1

#11439 RavenDB-15718 Add Mentor Node to Server Wide Backup and external rep…
  src/Raven.Studio/typescript/models/database/tasks/serverWide/serverWideConfigurationModel.ts
  src/Raven.Studio/typescript/models/database/tasks/serverWide/serverWideExternalReplicationEditModel.ts
  src/Raven.Studio/typescript/models/database/tasks/tasksCommonContent.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editExternalReplicationTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editPeriodicBackupTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editRavenEtlTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editReplicationHubTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editReplicationSinkTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editSqlEtlTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editSubscriptionTask.ts
  src/Raven.Studio/typescript/viewmodels/manage/editServerWideBackup.ts
  src/Raven.Studio/typescript/viewmodels/manage/editServerWideExternalReplication.ts
  src/Raven.Studio/wwwroot/App/views/database/tasks/editExternalReplicationTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editPeriodicBackupTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editRavenEtlTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editReplicationHubTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editReplicationSinkTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editSqlEtlTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editSubscriptionTask.html
  src/Raven.Studio/wwwroot/App/views/manage/editServerWideBackup.html
  src/Raven.Studio/wwwroot/App/views/manage/editServerWideExternalReplication.html
  src/Raven.Studio/wwwroot/App/views/resources/addNewNodeToDatabaseGroup.html
Labels: v5.1

#11441 HRINT-1967 [build scripts] Add a NoBundling option, globalize build c…
  build.ps1
  scripts/buildProjects.ps1
  scripts/env.ps1
  scripts/package.ps1
Labels: v5.1

#11444 RavenDB-15783 Setting value to zero will save it as null
  src/Raven.Studio/typescript/models/database/settings/databaseSettingsModels.ts
Labels: v5.0

#11448 RavenDB-15588 Stay in rehab with index error
  src/Raven.Server/ServerWide/Maintenance/ClusterObserver.cs
  test/SlowTests/Issues/RavenDB-15588.cs
Labels: v4.2

#11447 RavenDB-15885 fixed issue with resolving custom analyzers
  src/Raven.Server/Documents/Indexes/Static/IndexCompiler.cs
  test/EmbeddedTests/BasicTests.cs
  test/EmbeddedTests/Data/MyCustomAnalyzers.dll
  test/EmbeddedTests/EmbeddedTestBase.cs
  test/EmbeddedTests/EmbeddedTests.csproj
  test/EmbeddedTests/Issues/RavenDB_15885.cs
  test/EmbeddedTests/SmugglerTests.cs
Labels: v5.1

#11446 RavenDB-15885 added test
  test/EmbeddedTests/BasicTests.cs
  test/EmbeddedTests/Data/MyCustomAnalyzers.dll
  test/EmbeddedTests/EmbeddedTestBase.cs
  test/EmbeddedTests/EmbeddedTests.csproj
  test/EmbeddedTests/Issues/RavenDB_15885.cs
  test/EmbeddedTests/SmugglerTests.cs
Labels: v5.0

#11452 RavenDB-15735 Suggest X509KeyStorageFlags.MachineKeySet when the private key in null
  src/Raven.Client/Documents/DocumentStore.cs
  src/Raven.Client/Http/RequestExecutor.cs
Labels: v5.0

#11451 RavenDB-15891 Cannot define time for incremental backup when setting …
  src/Raven.Studio/typescript/viewmodels/database/tasks/editPeriodicBackupTask.ts
Labels: v5.1

#11450 RavenDB-15844 Database list view - Alerts and perf hints should be l…
  src/Raven.Studio/typescript/viewmodels/resources/databases.ts
  src/Raven.Studio/wwwroot/App/views/resources/databases.html
  src/Raven.Studio/wwwroot/App/views/shell.html
Labels: v5.0

#11422 RavenDB-15625 stay in rehab with disabled index
  src/Raven.Server/ServerWide/Maintenance/ClusterObserver.cs
  test/SlowTests/Issues/RavenDB-15625.cs
Labels: v4.2

#11457 4.2 to 5.0 merge
  src/Raven.Server/ServerWide/Maintenance/ClusterObserver.cs
  src/Raven.Server/Web/System/AdminStatsHandler.cs
  src/Raven.Studio/typescript/viewmodels/shell/about.ts
  src/Raven.Studio/wwwroot/App/views/shell/about.html
  src/Voron/Data/Compression/DecompressionBuffersPool.cs
  src/Voron/Impl/Paging/Windows32BitsMemoryMapPager.cs
  test/SlowTests/Issues/RavenDB-15588.cs
  test/SlowTests/Issues/RavenDB-15625.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
Labels: v5.0

#11458 RDBS-92 bump lucene version
  libs/Lucene.Net.3.0.36.nupkg
  libs/Lucene.Net.3.0.37.nupkg
  src/Raven.Server/Raven.Server.csproj
Labels: v4.2

#11464 RavenDB-15690 properly detect changes in HasChanged when we have deletes
  src/Raven.Client/Documents/Session/InMemoryDocumentSessionOperations.cs
  test/SlowTests/Issues/RavenDB_15690.cs
Labels: v4.2

#11463 RavenDB-15884 JS indexes added support for return block statements in…
  src/Raven.Server/Documents/Indexes/Static/JavaScriptIndexUtils.cs
  src/Raven.Server/Documents/Indexes/Static/JavaScriptMapOperation.cs
  src/Raven.Server/Documents/Indexes/Static/JavaScriptReduceOperation.cs
  test/FastTests/Client/Indexing/JavaScriptIndexTests.cs
Labels: v5.0

#11461 RavenDB-15909 - fix NRE in stream query
  src/Sparrow/Json/CachedProperties.cs
  src/Sparrow/Json/JsonOperationContext.cs
  test/SlowTests/Issues/RavenDB-15909.cs
Labels: v5.0

#11460 RavenDB-15907 Custom analyzer is not shown in studio
  src/Raven.Studio/typescript/models/database/index/indexFieldOptions.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/editIndex.ts
  src/Raven.Studio/wwwroot/App/views/database/indexes/editIndex.html
Labels: v5.1

#11467 5.0 to 5.1 merge
  src/Raven.Client/Documents/Conventions/DocumentConventions.cs
  src/Raven.Client/Http/ClusterTopologyLocalCache.cs
  src/Raven.Client/Http/DatabaseTopologyLocalCache.cs
  src/Raven.Server/Documents/Indexes/Static/JavaScriptIndexUtils.cs
  src/Raven.Server/Documents/Indexes/Static/JavaScriptMapOperation.cs
  src/Raven.Server/Documents/Indexes/Static/JavaScriptReduceOperation.cs
  src/Sparrow/Json/AbstractBlittableJsonDocumentBuilder.cs
  src/Sparrow/Json/CachedProperties.cs
  src/Sparrow/Json/JsonContextPoolBase.cs
  src/Sparrow/Json/JsonOperationContext.cs
  src/Sparrow/Json/PerCoreContainer.cs
  src/Voron/Impl/EncryptionBuffersPool.cs
  src/Voron/Impl/Paging/CryptoPager.cs
  test/FastTests/Client/Indexing/JavaScriptIndexTests.cs
  test/SlowTests/Issues/RavenDB-15909.cs
  test/SlowTests/Issues/RavenDB_11825.cs
  test/Tests.Infrastructure/RavenTestBase.cs
Labels: v5.1

#11469 RavenDB-15925 Disable bundling into Single File Application
  scripts/buildProjects.ps1
  scripts/package.ps1
Labels: v5.1

#11476 4.2 to 5.0 merge
  libs/Lucene.Net.3.0.36.nupkg
  libs/Lucene.Net.3.0.37.nupkg
  src/Raven.Client/Documents/Linq/RavenQueryProviderProcessor.cs
  src/Raven.Client/Documents/Session/InMemoryDocumentSessionOperations.cs
  src/Raven.Client/Documents/Subscriptions/DocumentSubscriptions.cs
  src/Raven.Client/Util/JavascriptConversionExtensions.cs
  src/Raven.Server/Documents/Patch/ScriptRunner.cs
  src/Raven.Server/Raven.Server.csproj
  test/SlowTests/Issues/RavenDB-15903.cs
  test/SlowTests/Issues/RavenDB_15690.cs
Labels: v5.0

#11477 5.0 to 5.1 merge
  libs/Jint.3.0.27-ravendb.nupkg
  libs/Lucene.Net.3.0.32.nupkg
  libs/Lucene.Net.3.0.36.nupkg
  libs/Lucene.Net.3.0.37.nupkg
  src/Raven.Client/Documents/Linq/RavenQueryProviderProcessor.cs
  src/Raven.Client/Documents/Session/InMemoryDocumentSessionOperations.cs
  src/Raven.Client/Documents/Subscriptions/DocumentSubscriptions.cs
  src/Raven.Client/Util/JavascriptConversionExtensions.cs
  src/Raven.Server/Documents/CollectionRunner.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Patch/ScriptRunner.cs
  src/Raven.Server/Documents/Queries/CollectionQueryEnumerable.cs
  src/Raven.Server/Raven.Server.csproj
  test/SlowTests/Issues/RavenDB-15754.cs
  test/SlowTests/Issues/RavenDB-15903.cs
  test/SlowTests/Issues/RavenDB_15690.cs
Labels: v5.1

#11479 5.0 to 5.1 merge
  src/Raven.Client/Documents/Session/InMemoryDocumentSessionOperations.cs
  src/Raven.Client/Documents/Session/Operations/StreamOperation.cs
  src/Sparrow/Json/JsonOperationContext.cs
  test/SlowTests/Issues/RavenDB-15909.cs
Labels: v5.1

#11478 RavenDB-15881 fixing deadlocks in test
  test/SlowTests/Issues/RavenDB-15754.cs
Labels: v5.0

#11483 RavenDB-15938 fixed possible NRE on error
  src/Raven.Server/Documents/Indexes/Static/NuGet/MultiSourceNuGetFetcher.cs
Labels: v5.1

#11488 RavenDB-15925 added back gc-dump
  tools/Raven.Debug/CommandLineApp.cs
  tools/Raven.Debug/Raven.Debug.csproj
Labels: v5.1

#11485 RavenDB-15940 Filtered Replication is using the wrong fields for filt…
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  test/SlowTests/Issues/FilteredReplicationTests.cs
  test/Tests.Infrastructure/TestCertificatesHolder.cs
Labels: v5.1

#11486 RavenDB-15912 on data move should forget about cached compressed ids
  src/Voron/Data/RawData/ActiveRawDataSmallSection.cs
  src/Voron/Data/RawData/DataMovedDelegate.cs
  src/Voron/Data/RawData/RawDataSection.cs
  src/Voron/Data/Tables/Table.cs
  test/FastTests/Voron/RawData/SmallDataSection.cs
  test/SlowTests/Voron/Issues/RavenDB_15912.cs
Labels: v5.0

#11490 4.2 to 5.0 merge
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Sparrow/Json/JsonContextPoolBase.cs
  src/Sparrow/Utils/NativeMemoryCleaner.cs
  src/Voron/Impl/EncryptionBuffersPool.cs
  test/SlowTests/Issues/RavenDB-13697.cs
  test/Tests.Infrastructure/ObservableExtensions.cs
Labels: v5.0

#11492 5.0 to 5.1 merge
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Sparrow/Json/JsonContextPoolBase.cs
  src/Sparrow/Utils/NativeMemoryCleaner.cs
  src/Voron/Data/RawData/ActiveRawDataSmallSection.cs
  src/Voron/Data/RawData/DataMovedDelegate.cs
  src/Voron/Data/RawData/RawDataSection.cs
  src/Voron/Data/Tables/Table.cs
  src/Voron/Impl/EncryptionBuffersPool.cs
  test/FastTests/Voron/RawData/SmallDataSection.cs
  test/SlowTests/Issues/RavenDB-13697.cs
  test/SlowTests/Voron/Issues/RavenDB_15912.cs
  test/Tests.Infrastructure/ObservableExtensions.cs
Labels: v5.1

#11493 RavenDB-15949 fix tight loop upon tombstone cleaner
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  test/SlowTests/Issues/RavenDB-14655.cs
Labels: v5.1
