Repository ravendb/ravendb, pull requests merged in 2020-03, with the labels that each got.

#10295 RavenDB-14715 : fix failing tests
  test/SlowTests/Client/TimeSeries/Query/TimeSeriesLinqQuery.cs
  test/SlowTests/Client/TimeSeries/Query/TimeSeriesRawQuery.cs
Labels: v5.0

#10294 RavenDB-14704: Increase MoveToRehab timeout in idle database test
  test/StressTests/Issues/RavenDB-13987.cs
  test/StressTests/Server/Replication/ExternalReplicationStressTests.cs
Labels: v4.2

#10296 RavenDB-14427: increase WaitForValue timeout
  test/SlowTests/Server/Documents/PeriodicBackup/Restore/RestoreFromS3.cs
Labels: v4.2

#10300 4.2 to 5.0 merge
  test/SlowTests/Server/Documents/PeriodicBackup/Restore/RestoreFromS3.cs
  test/StressTests/Issues/RavenDB-13987.cs
  test/StressTests/Server/Replication/ExternalReplicationStressTests.cs
Labels: v5.0

#10303 RavenDB-14491 Work on time series charts L&F
  src/Raven.Studio/typescript/viewmodels/common/timeSeriesPlotDetails.ts
  src/Raven.Studio/wwwroot/App/views/common/timeSeriesPlotDetails.html
Labels: v5.0

#10301 RavenDB-14482 Use IdentityPartsSeparator from database instance
  src/Raven.Server/Documents/Indexes/MapReduce/OutputToCollection/DeleteReduceOutputDocumentsCommand.cs
  src/Raven.Server/Documents/Indexes/MapReduce/OutputToCollection/OutputReduceToCollectionActions.cs
  src/Raven.Server/Documents/Indexes/MapReduce/OutputToCollection/OutputReferencesPattern.cs
  test/SlowTests/Server/Documents/Indexing/MapReduce/RavenDB_12932.cs
Labels: v5.0

#10292 Ignore ramdisks while checking hdd | ssd
  src/Sparrow.Server/LowMemory/CheckPageFileOnHdd.cs
Labels: v4.2

#10293 RavenDB-14714 Better error on missing arguments for boost
  src/Raven.Server/Documents/Queries/QueryBuilder.cs
Labels: v4.2

#10302 RavenDB-14700 Improved logging when ETL process is stopped - checking…
  src/Raven.Client/Documents/Operations/ETL/EtlConfiguration.cs
  src/Raven.Client/Documents/Operations/ETL/Transformation.cs
  src/Raven.Server/Documents/ETL/EtlLoader.cs
Labels: v4.2

#10290 RavenDB-14703 using DynamicEnumerable when we have OrderBy or OrderByDescending
  src/Raven.Client/Documents/Indexes/ExpressionStringBuilder.cs
  src/Raven.Server/Documents/Indexes/Static/Linq/DynamicEnumerable.cs
  test/SlowTests/Issues/RavenDB_14703.cs
Labels: v4.2

#10289 RavenDB-14701 exposed roundFactor in IDocumentQuery
  src/Raven.Client/Documents/Session/AsyncDocumentQuery.Spatial.cs
  src/Raven.Client/Documents/Session/DocumentQuery.Spatial.cs
  src/Raven.Client/Documents/Session/IDocumentQueryBase.cs
  test/SlowTests/Issues/RavenDB-13682.cs
Labels: v4.2

#10288 RavenDB-14685 exposing events in the IDocumentStore interface
  src/Raven.Client/Documents/IDocumentStore.cs
  src/Raven.Embedded/EmbeddedServer.cs
  test/FastTests/Client/Events.cs
  test/FastTests/Issues/RavenDB-10931.cs
  test/SlowTests/Issues/RavenDB-10250.cs
  test/SlowTests/Issues/RavenDB-10566.cs
  test/SlowTests/Issues/RavenDB-11111.cs
  test/SlowTests/Issues/RavenDB-14276.cs
  test/SlowTests/Issues/RavenDB10215.cs
  test/SlowTests/Issues/RavenDB_10977.cs
  test/SlowTests/Issues/RavenDB_9889.cs
  test/SlowTests/MailingList/Jordan.cs
  test/SlowTests/MailingList/Severin.cs
  test/SlowTests/Tests/Linq/RavenDB14.cs
  test/StressTests/Issues/RavenDB_14464.cs
Labels: v4.2

#10304 RavenDB-7070 updated packages
  src/Raven.Server/Documents/Handlers/StreamCsvResultWriter.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Server/Smuggler/Documents/CsvStreamSource.cs
  test/SlowTests/Issues/RavenDB_12403.cs
  test/Tests.Infrastructure/TestResourceSnapshotWriter.cs
  tools/Raven.Migrator/Raven.Migrator.csproj
Labels: v4.2

#10305 4.2 to 5.0 merge
  src/Raven.Client/Documents/IDocumentStore.cs
  src/Raven.Client/Documents/Indexes/ExpressionStringBuilder.cs
  src/Raven.Client/Documents/Operations/ETL/EtlConfiguration.cs
  src/Raven.Client/Documents/Operations/ETL/Transformation.cs
  src/Raven.Client/Documents/Session/AsyncDocumentQuery.Spatial.cs
  src/Raven.Client/Documents/Session/DocumentQuery.Spatial.cs
  src/Raven.Client/Documents/Session/IDocumentQueryBase.cs
  src/Raven.Embedded/EmbeddedServer.cs
  src/Raven.Server/Documents/ETL/EtlLoader.cs
  src/Raven.Server/Documents/Handlers/StreamCsvResultWriter.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/JintLuceneDocumentConverter.cs
  src/Raven.Server/Documents/Indexes/Static/DynamicNullObject.cs
  src/Raven.Server/Documents/Indexes/Static/JavaScriptIndex.cs
  src/Raven.Server/Documents/Indexes/Static/Linq/DynamicEnumerable.cs
  src/Raven.Server/Documents/Patch/BlittableObjectInstance.cs
  src/Raven.Server/Documents/Patch/DynamicJsNull.cs
  src/Raven.Server/Documents/Patch/JintNullPropagationReferenceResolver.cs
  src/Raven.Server/Documents/Patch/ScriptRunner.cs
  src/Raven.Server/Documents/Queries/QueryBuilder.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Server/Smuggler/Documents/CsvStreamSource.cs
  src/Raven.Server/Utils/TypeConverter.cs
  src/Sparrow.Server/LowMemory/CheckPageFileOnHdd.cs
  test/FastTests/Client/Events.cs
  test/FastTests/Issues/RavenDB-10931.cs
  test/SlowTests/Issues/RavenDB-10250.cs
  test/SlowTests/Issues/RavenDB-10566.cs
  test/SlowTests/Issues/RavenDB-11111.cs
  test/SlowTests/Issues/RavenDB-13682.cs
  test/SlowTests/Issues/RavenDB-14276.cs
  test/SlowTests/Issues/RavenDB10215.cs
  test/SlowTests/Issues/RavenDB_10977.cs
  test/SlowTests/Issues/RavenDB_12403.cs
  test/SlowTests/Issues/RavenDB_14703.cs
  test/SlowTests/Issues/RavenDB_14712.cs
  test/SlowTests/Issues/RavenDB_9889.cs
  test/SlowTests/MailingList/Jordan.cs
  test/SlowTests/MailingList/Severin.cs
  test/SlowTests/Tests/Linq/RavenDB14.cs
  test/StressTests/Issues/RavenDB_14464.cs
  test/Tests.Infrastructure/TestResourceSnapshotWriter.cs
  tools/Raven.Migrator/Raven.Migrator.csproj
Labels: v5.0

#10306 RavenDB-14005 allow to get cmpxng values lazily
  src/Raven.Client/Documents/Session/ClusterTransactionSession.cs
  src/Raven.Client/Documents/Session/Operations/Lazy/LazyGetCompareExchangeValueOperation.cs
  src/Raven.Client/Documents/Session/Operations/Lazy/LazyGetCompareExchangeValuesOperation.cs
  test/SlowTests/Issues/RavenDB_14005.cs
Labels: v5.0

#10308 RavenDB-14688 add option to force nightly build tests
  test/Tests.Infrastructure/NightlyBuildTheoryAttribute.cs
Labels: v4.2

#10313 RavenDB-14726 - skip threads that aren't running anymore
  tools/Raven.Debug/StackTrace/StackTracer.cs
Labels: v4.2

#10311 RavenDB-13238 Editing index should go to list of indexes after submit
  src/Raven.Studio/typescript/viewmodels/database/indexes/editIndex.ts
Labels: v4.2

#10312 RavenDB-14725 - ignore errors in report alert, since there is nothing we can do there
  Raven.Database/Impl/BackgroundTaskExecuter/RavenThreadPool.cs
Labels: v3.5

#10316 RavenDB-14688 add assembly and class name fields to TestResourceSnapshot
  test/Tests.Infrastructure/TestResourceSnapshotWriter.cs
Labels: v4.2

#10315 RavenDB-13921 updated Jint
  libs/Jint.3.0.23-ravendb.nupkg
  libs/Jint.3.0.25-ravendb.nupkg
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/JintLuceneDocumentConverter.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/PropertyAccessor.cs
  src/Raven.Server/Documents/Indexes/Static/JavaScriptMapOperation.cs
  src/Raven.Server/Documents/Indexes/Static/JavaScriptReduceOperation.cs
  src/Raven.Server/Documents/Patch/BlittableObjectInstance.cs
  src/Raven.Server/Documents/Patch/JintNullPropagationReferenceResolver.cs
  src/Raven.Server/Documents/Patch/JsBlittableBridge.cs
  src/Raven.Server/Documents/Patch/ScriptRunnerResult.cs
  src/Raven.Server/Raven.Server.csproj
Labels: v5.0

#10319 RavenDB-7070 removing obsoletes
  src/Raven.Server/ServerWide/SecretProtection.cs
Labels: v4.2

#10318 4.2 to 5.0 merge
  src/Raven.Server/Config/Categories/HttpConfiguration.cs
  src/Raven.Server/Dashboard/DatabasesInfoNotificationSender.cs
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/ETL/EtlProcess.cs
  src/Raven.Server/Documents/Handlers/Debugging/ServerWideDebugInfoPackageHandler.cs
  src/Raven.Server/Documents/Handlers/ExpirationHandler.cs
  src/Raven.Server/Documents/Handlers/IndexHandler.cs
  src/Raven.Server/Documents/Handlers/RefreshHandler.cs
  src/Raven.Server/Documents/Handlers/ReplicationHandler.cs
  src/Raven.Server/Documents/Handlers/RevisionsHandler.cs
  src/Raven.Server/Documents/Handlers/SortersHandler.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  src/Raven.Server/Documents/PeriodicBackup/BackupTask.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
  src/Raven.Server/Documents/Replication/OutgoingReplicationHandler.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.1/DatabaseOldestBackup.cs
  src/Raven.Server/Monitoring/Snmp/SnmpOids.cs
  src/Raven.Server/RavenServer.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/Commands/ETL/DeleteEtlProcessStateCommand.cs
  src/Raven.Server/ServerWide/Commands/ETL/UpdateEtlProcessStateCommand.cs
  src/Raven.Server/ServerWide/Commands/IncrementClusterIdentitiesBatchCommand.cs
  src/Raven.Server/ServerWide/Commands/IncrementClusterIdentityCommand.cs
  src/Raven.Server/ServerWide/Commands/Monitoring/Snmp/UpdateSnmpDatabaseIndexesMappingCommand.cs
  src/Raven.Server/ServerWide/Commands/PeriodicBackup/UpdatePeriodicBackupStatusCommand.cs
  src/Raven.Server/ServerWide/Commands/Subscriptions/AcknowledgeSubscriptionBatchCommand.cs
  src/Raven.Server/ServerWide/Commands/Subscriptions/DeleteSubscriptionCommand.cs
  src/Raven.Server/ServerWide/Commands/Subscriptions/PutSubscriptionCommand.cs
  src/Raven.Server/ServerWide/Commands/Subscriptions/ToggleSubscriptionStateCommand.cs
  src/Raven.Server/ServerWide/Commands/Subscriptions/UpdateSubscriptionClientConnectionTime.cs
  src/Raven.Server/ServerWide/Commands/UpdateClusterIdentityCommand.cs
  src/Raven.Server/ServerWide/Commands/UpdateExternalReplicationStateCommand.cs
  src/Raven.Server/ServerWide/Commands/UpdateValueForDatabaseCommand.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterMaintenanceWorker.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterObserver.cs
  src/Raven.Server/ServerWide/RawDatabaseRecord.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Smuggler/Documents/DatabaseSource.cs
  src/Raven.Server/Smuggler/Migration/Migrator.cs
  src/Raven.Server/Web/Studio/DataDirectoryInfo.cs
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
  src/Raven.Server/Web/System/OngoingTasksHandler.cs
  src/Raven.Studio/typescript/viewmodels/database/indexes/editIndex.ts
  test/FastTests/Server/Documents/Indexing/Auto/BasicAutoMapIndexing.cs
  test/SlowTests/Issues/EncryptedDatabaseGroup.cs
  test/Tests.Infrastructure/NightlyBuildTheoryAttribute.cs
  test/Tests.Infrastructure/TestResourceSnapshotWriter.cs
  test/Tests.Infrastructure/XunitExtensions/PerformanceTestClassRunner.cs
  test/Tests.Infrastructure/XunitExtensions/PerformanceTestExecutor.cs
  tools/Raven.Debug/StackTrace/StackTracer.cs
Labels: v5.0

#10323 RavenDB-13343 Separate log messages
  src/Raven.Studio/typescript/viewmodels/manage/adminLogs.ts
  src/Raven.Studio/wwwroot/Content/css/pages/admin-logs.less
Labels: v4.2

#10322 RavenDB-14669 In log retention tests wait for retention to apply
  test/SlowTests/SparrowTests/LoggingSourceTests.cs
  test/Tests.Infrastructure/RavenTestBase.cs
Labels: v4.2

#10321 RavenDB-14630 Removing tabs from log header
  src/Sparrow/Logging/LoggingSource.cs
Labels: v4.2

#10320 RavenDB-14654: Include document tombstones in full backup
  src/Raven.Client/Documents/Operations/DatabaseStatistics.cs
  src/Raven.Server/Documents/Handlers/StatsHandler.cs
  src/Raven.Server/Documents/PeriodicBackup/BackupTask.cs
  src/Raven.Server/ServerWide/Commands/CompareExchangeCommands.cs
  test/SlowTests/Issues/RavenDB_14654.cs
Labels: v4.2

#10326 HRINT-1536 for existing topology set replication factor to total number of nodes
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
Labels: v4.2

#10327 HRINT-1536 promotable nodes shouldn't save documents from cluster transaction
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/Replication/ReplicationDocumentSender.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterObserver.cs
  test/RachisTests/DatabaseCluster/ReplicationTests.cs
Labels: v4.2

#10331 RDBS-72 Soft delete should keep the the database Id
  src/Raven.Server/ServerWide/Commands/RemoveNodeFromDatabaseCommand.cs
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
Labels: v4.2

#10332 RavenDB-14740 UnobservedTaskException thrown in RavenServer
  src/Raven.Server/Rachis/RachisConsensus.cs
Labels: v4.2

#10334 RavenDB-14730 Record Transaction Commands option isn't visible
  src/Raven.Studio/typescript/common/shell/accessManager.ts
Labels: v4.2

#10335 RavenDB-14742 - Set HttpProtocols to Http1 for Windows 2012
  src/Raven.Server/Config/Categories/HttpConfiguration.cs
  src/Sparrow/Platform/PlatformDetails.cs
Labels: v4.2

#10336 4.2 to 5.0 merge
  src/Raven.Client/Documents/Linq/RavenQueryProviderProcessor.cs
  src/Raven.Server/Config/Categories/HttpConfiguration.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/Replication/ReplicationDocumentSender.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Server/ServerWide/Commands/RemoveNodeFromDatabaseCommand.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterObserver.cs
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
  src/Raven.Studio/typescript/common/shell/accessManager.ts
  src/Sparrow/Platform/PlatformDetails.cs
  test/FastTests/Client/Query.cs
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
  test/RachisTests/DatabaseCluster/ReplicationTests.cs
  tools/Raven.Debug/Raven.Debug.csproj
  tools/Raven.Migrator/Raven.Migrator.csproj
  tools/rvn/CommandLineApp.cs
Labels: v5.0

#10342 RavenDB-14750 Bad check for HasServerCertificateCustomValidationCallback
  src/Raven.Client/Http/RequestExecutor.cs
Labels: v4.2

#10347 RavenDB-14761 run npm audit fix on studio
  src/Raven.Studio/package-lock.json
Labels: v4.2

#10340 RavenDB-13239 Admin Logs - Add 'copy log message' button
  src/Raven.Studio/typescript/viewmodels/manage/adminLogs.ts
  src/Raven.Studio/wwwroot/App/views/manage/adminLogs.html
  src/Raven.Studio/wwwroot/Content/css/pages/admin-logs.less
Labels: v4.2

#10343 RavenDB-14394 Allow deserializing an object with a property set to Enumerable.Empty<T>()
  src/Raven.Client/Json/Converters/JsonLinqEnumerableConverter.cs
  test/FastTests/Client/Load.cs
Labels: v4.2

#10348 RavenDB-14661 Patching on a stale index: Added Pawel's Test & updated…
  src/Raven.Server/Documents/Queries/AbstractQueryRunner.cs
  test/SlowTests/Client/Indexing/IndexesFromClient.cs
  test/SlowTests/Issues/RavenDB-2717.cs
  test/SlowTests/Issues/RavenDB_14661.cs
  test/SlowTests/Issues/RavenDB_2623.cs
Labels: v4.2

#10350 RavenDB-14459 Allow rerun batch command with store attachments
  src/Raven.Server/Documents/Handlers/BatchHandler.cs
  src/Raven.Server/SqlMigration/SqlMigrationWriter.cs
  test/SlowTests/Client/Attachments/AttachmentsSession.cs
Labels: v4.2

#10344 RavenDB-14757 Update PAL / Sodium to use new form of finding the dll,…
  src/Sparrow.Server/DynamicNativeLibraryResolver.cs
  src/Sparrow.Server/Platform/Pal.cs
  src/Sparrow.Server/Sodium.cs
  src/Sparrow.Server/Sparrow.Server.csproj
  src/Sparrow.Server/Utils/FileHelper.cs
  src/Voron/Voron.csproj
Labels: v5.0

#10351 RavenDB-14764: change encoding func for compare exchange url
  src/Raven.Studio/typescript/common/appUrl.ts
Labels: v4.2

#10353 RavenDB-7070 updated packages
  src/Raven.Server/Raven.Server.csproj
  test/SlowTests/Client/Attachments/AttachmentsSession.cs
  tools/Raven.Debug/Raven.Debug.csproj
Labels: v4.2

#10352 4.2 to 5.0 merge
  src/Raven.Client/Documents/Operations/Operation.cs
  src/Raven.Client/Documents/Smuggler/DatabaseSmuggler.cs
  src/Raven.Client/Http/RequestExecutor.cs
  src/Raven.Client/Json/Converters/JsonLinqEnumerableConverter.cs
  src/Raven.Server/Commercial/LicenseManager.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/Handlers/BatchHandler.cs
  src/Raven.Server/Documents/Indexes/CollectionOfBloomFilters.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  src/Raven.Server/Documents/Indexes/MapIndexBase.cs
  src/Raven.Server/Documents/Indexes/MapReduce/OutputToCollection/OutputReferencesPattern.cs
  src/Raven.Server/Documents/Queries/AbstractQueryRunner.cs
  src/Raven.Server/SqlMigration/SqlMigrationWriter.cs
  src/Raven.Studio/package-lock.json
  src/Raven.Studio/typescript/common/appUrl.ts
  src/Raven.Studio/typescript/viewmodels/manage/adminLogs.ts
  src/Raven.Studio/wwwroot/App/views/manage/adminLogs.html
  src/Raven.Studio/wwwroot/Content/css/pages/admin-logs.less
  test/EmbeddedTests/SmugglerTests.cs
  test/FastTests/Client/Load.cs
  test/FastTests/Server/Documents/Indexing/BloomFilterTests.cs
  test/SlowTests/Client/Attachments/AttachmentsSession.cs
  test/SlowTests/Client/Indexing/IndexesFromClient.cs
  test/SlowTests/Issues/RavenDB-14717.cs
  test/SlowTests/Issues/RavenDB-2717.cs
  test/SlowTests/Issues/RavenDB_14661.cs
  test/SlowTests/Issues/RavenDB_2623.cs
  test/SlowTests/Server/Documents/Indexing/MapReduce/RavenDB_14521.cs
Labels: v5.0

#10354 RavenDB-14770: build embedded server without file
  scripts/buildProjects.ps1
Labels: v4.2

#10355 RavenDB-14770: fix failing build
  scripts/buildProjects.ps1
Labels: v4.2

#10359 RavenDB-14751 fixed compare exchange reference handling in timeseries map-reduce indexes
  src/Raven.Server/Documents/Indexes/MapReduce/Static/MapReduceIndex.cs
  src/Raven.Server/Documents/Indexes/Static/TimeSeries/MapReduceTimeSeriesIndex.cs
  test/SlowTests/Issues/RavenDB_13644.cs
Labels: v5.0

#10363 RavenDB-14775 - Better error when using ToListAsync from a sync session
  src/Raven.Client/Documents/Session/DocumentSession.Query.cs
Labels: v4.2

#10375 RavenDB-14777 wait 5ms on task during bulk insert to balance better between internal number of batches and network/parsing speed
  src/Raven.Server/Documents/Handlers/BulkInsertHandler.cs
Labels: v4.2

#10349 RavenDB-14758 NRE in GetMinLastEtag if backup is not created
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
Labels: v4.2

#10367 RavenDB-14781 Ensure certificate serial number is exactly 20 bytes in…
  src/Raven.Server/Utils/CertificateUtils.cs
Labels: v4.2

#10370 RavenDB-14783: Switch ScriptEngine.MaxStatements to MaxStepsForTransf…
  src/Raven.Server/Smuggler/Documents/SmugglerPatcher.cs
  test/SlowTests/Issues/RavenDB-14783.cs
Labels: v4.2

#10369 RavenDB-14746 New lines are not respected in studio alerts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/alerts/genericAlertDetails.ts
  src/Raven.Studio/wwwroot/App/views/common/notificationCenter/detailViewer/alerts/genericAlertDetails.html
Labels: v4.2

#10379 4.2 to 5.0 merge
  scripts/buildProjects.ps1
  src/Raven.Client/Documents/Conventions/DocumentConventions.cs
  src/Raven.Client/Documents/Operations/DatabaseStatistics.cs
  src/Raven.Client/Documents/Session/DocumentSession.Query.cs
  src/Raven.Client/Documents/Session/InMemoryDocumentSessionOperations.cs
  src/Raven.Client/Exceptions/Database/DatabaseConcurrentLoadTimeoutException.cs
  src/Raven.Server/Config/Categories/StorageConfiguration.cs
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/Handlers/BulkInsertHandler.cs
  src/Raven.Server/Documents/Handlers/StatsHandler.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
  src/Raven.Server/Documents/ResourceCache.cs
  src/Raven.Server/Json/BlittableJsonTextWriterExtensions.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Server/Routing/RouteInformation.cs
  src/Raven.Server/ServerWide/ClusterCommandsVersionManager.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/Commands/ToggleDatabasesStateCommand.cs
  src/Raven.Server/ServerWide/Commands/UpdateValueCommand.cs
  src/Raven.Server/ServerWide/JsonDeserializationCluster.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Smuggler/Documents/SmugglerPatcher.cs
  src/Raven.Server/Utils/CertificateUtils.cs
  src/Raven.Server/Utils/IoMetrics/IoMetricsUtil.cs
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
  src/Raven.Server/Web/System/DatabasesHandler.cs
  src/Raven.Studio/typescript/commands/database/index/toggleDisableIndexingCommand.ts
  src/Raven.Studio/typescript/commands/resources/getDatabaseDetailedStatsCommand.ts
  src/Raven.Studio/typescript/common/shell/databasesManager.ts
  src/Raven.Studio/typescript/models/database/stats/statistics.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/alerts/genericAlertDetails.ts
  src/Raven.Studio/typescript/viewmodels/database/status/statistics.ts
  src/Raven.Studio/typescript/viewmodels/resources/databases.ts
  src/Raven.Studio/wwwroot/App/views/common/notificationCenter/detailViewer/alerts/genericAlertDetails.html
  src/Raven.Studio/wwwroot/App/views/database/status/statistics.html
  src/Sparrow.Server/Meters/IoMeterBuffer.cs
  test/FastTests/Sparrow/IoMetric.cs
  test/SlowTests/Client/Attachments/AttachmentsSession.cs
  test/SlowTests/Core/Session/Crud.cs
  test/SlowTests/Issues/RavenDB-14783.cs
  tools/Raven.Debug/Raven.Debug.csproj
Labels: v5.0

#10381 RavenDB-14603: add assert to test
  test/SlowTests/Server/Documents/PeriodicBackup/Retention.cs
Labels: v4.2

#10371 RavenDB-14769 Querying Search as Subclause return wrong results
  src/Raven.Server/Documents/Queries/Parser/QueryParser.cs
  src/Raven.Server/Documents/Queries/QueryBuilder.cs
  test/SlowTests/Issues/RavenDB14769.cs
Labels: v4.2

#10385 RavenDB-14583 fix CertificateCallback and also do the check after eac…
  src/Raven.Server/RavenServer.cs
Labels: v4.2

#10391 RavenDB-14804 : fix failing test
  test/SlowTests/Client/TimeSeries/Query/TimeSeriesLinqQuery.cs
Labels: v5.0

#10393 RavenDB-14810 Unable to preview document when chars & byte count of c…
  src/Raven.Server/Web/Studio/StudioCollectionsHandler.cs
  src/Sparrow/Json/LazyCompressedStringValue.cs
Labels: v4.2

#10398 RavenDB-14495 group by in time series doesn't seem to work properly
  src/Raven.Studio/typescript/models/database/timeSeries/timeSeriesQueryResult.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/columns/timeSeriesColumn.ts
Labels: v5.0

#10397 RavenDB-14474 saved query infers invalid collection name
  src/Raven.Studio/typescript/common/queryUtil.ts
Labels: v5.0

#10394 RavenDB-14778 Include collection columns are not shown by default
  src/Raven.Studio/typescript/widgets/virtualGrid/columns/providers/documentBasedColumnsProvider.ts
Labels: v5.0

#10395 RavenDB-14806 Cannot run select query when property name is "Group"
  src/Raven.Client/Documents/Linq/RavenQueryProviderProcessor.cs
  test/SlowTests/Issues/RavenDB-14806.cs
Labels: v4.2

#10401 RavenDB-14809 you can only pass string constant to load document
  src/Raven.Client/Documents/Indexes/ExpressionStringBuilder.cs
  test/SlowTests/Issues/RavenDB_14809.cs
Labels: v4.2

#10402 RavenDB-14803 Register socket use same log thread if it is already run & complete setup log run on same thread
  src/Sparrow/Logging/LoggingSource.cs
  test/SlowTests/SparrowTests/LoggingSourceTests.cs
Labels: v4.2

#10400 4.2 to 5.0 merge
  src/Raven.Client/Documents/Conventions/JsonNetBlittableEntitySerializer.cs
  src/Raven.Client/Documents/Identity/GenerateEntityIdOnTheClient.cs
  src/Raven.Client/Documents/Indexes/AbstractJavaScriptIndexCreationTask.cs
  src/Raven.Client/Documents/Indexes/ExpressionStringBuilder.cs
  src/Raven.Client/Documents/Linq/RavenQueryProviderProcessor.cs
  src/Raven.Client/Documents/Session/Operations/QueryOperation.cs
  src/Raven.Client/ServerWide/Operations/Certificates/CertificateDefinition.cs
  src/Raven.Server/Commercial/SetupInfo.cs
  src/Raven.Server/Commercial/SetupManager.cs
  src/Raven.Server/Documents/Handlers/PullReplicationHandler.cs
  src/Raven.Server/Documents/Indexes/Static/JavaScriptIndex.cs
  src/Raven.Server/Documents/TcpHandlers/SubscriptionConnection.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/Commands/PutCertificateCommand.cs
  src/Raven.Server/Utils/CertificateUtils.cs
  src/Raven.Server/Utils/Cli/RavenCli.cs
  src/Raven.Server/Web/Authentication/AdminCertificatesHandler.cs
  src/Raven.Server/Web/Studio/StudioCollectionsHandler.cs
  src/Raven.Studio/typescript/commands/database/documents/getDocumentsPreviewCommand.ts
  src/Raven.Studio/typescript/common/helpers/database/documentPropertyProvider.ts
  src/Raven.Studio/typescript/viewmodels/database/documents/documents.ts
  src/Raven.Studio/typescript/viewmodels/partial/columnsSelector.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/columns/textColumn.ts
  src/Raven.Studio/wwwroot/Content/css/virtual-grid.less
  src/Sparrow/Json/LazyCompressedStringValue.cs
  src/Sparrow/Logging/LoggingSource.cs
  test/SlowTests/Bugs/LiveProjections/LiveProjectionOnProducts.cs
  test/SlowTests/Bugs/ProjectingDates.cs
  test/SlowTests/Issues/RavenDB-14797.cs
  test/SlowTests/Issues/RavenDB-14806.cs
  test/SlowTests/Issues/RavenDB-14811.cs
  test/SlowTests/Issues/RavenDB_14809.cs
  test/SlowTests/Server/ServerStore.cs
  test/SlowTests/SparrowTests/LoggingSourceTests.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v5.0

#10404 RavenDB-14651 Moved state of timeseries() js call to the object itself
  src/Raven.Server/Documents/Patch/ScriptRunner.cs
Labels: v5.0

#10358 RavenDB-13478 allow to include counters in subscriptions
  src/Raven.Client/Documents/Session/Loaders/IncludeBuilder.cs
  src/Raven.Client/Documents/Subscriptions/DocumentSubscriptions.cs
  src/Raven.Client/Documents/Subscriptions/SubscriptionBatch.cs
  src/Raven.Client/Documents/Subscriptions/SubscriptionWorker.cs
  src/Raven.Client/Documents/Subscriptions/SubscriptionWorkerOptions.cs
  src/Raven.Client/ServerWide/Tcp/TcpConnectionHeader.cs
  src/Raven.Server/Documents/Handlers/DocumentHandler.cs
  src/Raven.Server/Documents/Includes/IncludeCountersCommand.cs
  src/Raven.Server/Documents/TcpHandlers/SubscriptionConnection.cs
  src/Raven.Server/Json/BlittableJsonTextWriterExtensions.cs
  test/SlowTests/Issues/RavenDB_13478.cs
  test/SlowTests/Issues/RavenDB_13759.cs
Labels: v5.0

#10410 RavenDB-14825 empty box on edit index page when reduce isn't defined
  src/Raven.Studio/wwwroot/App/views/database/indexes/editIndex.html
Labels: v4.2

#10409 RavenDB-14794 Disabling 'Create References to Results Collection' doe…
  src/Raven.Studio/typescript/models/database/index/additionalSource.ts
  src/Raven.Studio/typescript/models/database/index/indexDefinition.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/editIndex.ts
Labels: v4.2

#10407 RavenDB-14826 smuggler needs to trigger change event for timeseries when we are trying to append the entire segment
  src/Raven.Server/Documents/TimeSeries/TimeSeriesStorage.cs
  test/SlowTests/Issues/RavenDB_14826.cs
Labels: v5.0

#10411 RavenDB-14795 Javascript index lack the output reduce results results…
  src/Raven.Server/Documents/Indexes/Index.cs
Labels: v4.2

#10413 4.2 to 5.0 merge
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Smuggler/Documents/Handlers/SmugglerHandler.cs
  src/Raven.Server/Web/Studio/StudioTasksHandler.cs
  src/Raven.Studio/typescript/commands/database/tasks/getMigratorPathConfigurationCommand.ts
  src/Raven.Studio/typescript/models/database/index/additionalSource.ts
  src/Raven.Studio/typescript/models/database/index/indexDefinition.ts
  src/Raven.Studio/typescript/models/database/tasks/migrateDatabaseModel.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/editIndex.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/migrateDatabase.ts
  src/Raven.Studio/typings/_studio/dto.d.ts
  src/Raven.Studio/wwwroot/App/views/database/indexes/editIndex.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/migrateDatabase.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/migrateRavenDbDatabase.html
Labels: v5.0
