Repository ravendb/ravendb, pull requests merged in 2020-10, with the labels that each got.

#11188 RavenDB-12471 More exception to return HttpStatusCode.ServiceUnavailable
  src/Raven.Server/RavenServerStartup.cs
Labels: v4.2

#11186 RavenDB-15633 get rid of horizontal scroll in setup wizard
  src/Raven.Studio/wwwroot/Content/css/pages/setup.less
Labels: v5.1

#11184 RavenDB-15648 Backups list view - Fix badge label
  src/Raven.Studio/wwwroot/Content/css/styles-common.less
Labels: v5.1

#11183 RavenDB-15647 Backups list view - Fix scroll area
  src/Raven.Studio/wwwroot/Content/css/pages/backups.less
Labels: v5.1

#11171 RavenDB-15538: Missing attachment break replication #2
  src/Raven.Server/Documents/AttachmentsStorage.cs
  src/Raven.Server/Documents/Replication/IncomingReplicationHandler.cs
  src/Raven.Server/Documents/Replication/ReplicationDocumentSender.cs
  src/Raven.Server/Documents/Replication/ReplicationItems/AttachmentReplicationItem.cs
  src/Raven.Server/Documents/Replication/ReplicationItems/ReplicationBatchItem.cs
  test/SlowTests/Issues/RavenDB_15538.cs
Labels: v5.0

#11161 RavenDB-11299: Add support for RavenQuery.CmpXchg single projection q…
  src/Raven.Client/Documents/Linq/LinqPathProvider.cs
  src/Raven.Client/Documents/Linq/RavenQueryProviderProcessor.cs
  src/Raven.Server/Documents/Patch/ScriptRunner.cs
  src/Raven.Server/Documents/Queries/QueryMetadata.cs
  test/SlowTests/Client/QueriesWithCustomFunctions.cs
Labels: v5.1

#11189 RavenDB-15663 Don't show the uptime if db is offline
  src/Raven.Studio/wwwroot/App/views/resources/databases.html
Labels: v5.1

#11194 RavenDB-15566 more debug info
  test/SlowTests/Issues/RavenDB_3237.cs
Labels: v5.0

#11195 RavenDB-15574 more debug info
  test/Tests.Infrastructure/RavenTestBase.cs
Labels: v5.0

#11193 RavenDB-15387 fixing race condition in test
  test/FastTests/Issues/RavenDB-13058.cs
  test/SlowTests/Server/Documents/Indexing/MapReduce/RavenDB_14482.cs
  test/Tests.Infrastructure/RavenTestBase.cs
Labels: v4.2

#11196 RavenDB-15634 Double Scroll on Columns Selector Fix
  src/Raven.Studio/wwwroot/Content/css/column-selector.less
  src/Raven.Studio/wwwroot/Content/css/styles-common.less
Labels: v5.1

#11191 RavenDB-15653 Database Settings View - Restrict value visibility
  src/Raven.Studio/typescript/models/database/settings/databaseSettingsModels.ts
  src/Raven.Studio/typescript/viewmodels/database/settings/databaseSettings.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/columns/textColumn.ts
  src/Raven.Studio/wwwroot/App/views/database/settings/databaseSettings.html
  src/Raven.Studio/wwwroot/Content/css/pages/database-settings.less
Labels: v5.1

#11198 RavenDB-15681 fixed NRE
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
Labels: v5.0

#11201 RavenDB-7070 document store leak fix
  test/Tests.Infrastructure/TestBase.cs
  test/Tests.Infrastructure/Utils/DebugPackageHandler.cs
Labels: v4.2

#11199 5.0 to 5.1 merge
  src/CommonAssemblyInfo.cs
  src/Raven.Client/Documents/Operations/TimeSeries/TimeSeriesCollectionConfiguration.cs
  src/Raven.Server/Config/Categories/IndexingConfiguration.cs
  src/Raven.Server/Documents/AttachmentsStorage.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Replication/IncomingReplicationHandler.cs
  src/Raven.Server/Documents/Replication/ReplicationDocumentSender.cs
  src/Raven.Server/Documents/Replication/ReplicationItems/AttachmentReplicationItem.cs
  src/Raven.Server/Documents/Replication/ReplicationItems/ReplicationBatchItem.cs
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesPolicyRunner.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesRollups.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesStats.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesStorage.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesValuesSegment.cs
  src/Raven.Server/RavenServerStartup.cs
  test/FastTests/Issues/RavenDB-13058.cs
  test/SlowTests/Client/TimeSeries/Policies/TimeSeriesConfigurationTests.cs
  test/SlowTests/Client/TimeSeries/Query/QueryFromMultipleTimeSeries.cs
  test/SlowTests/Client/TimeSeries/Session/TimeSeriesSessionTests.cs
  test/SlowTests/Cluster/ClusterIndexNotificationsTest.cs
  test/SlowTests/Issues/RavenDB_15538.cs
  test/SlowTests/Issues/RavenDB_3237.cs
  test/SlowTests/Server/Documents/Indexing/MapReduce/RavenDB_14482.cs
  test/StressTests/Cluster/ClusterIndexNotificationsTestStress.cs
  test/Tests.Infrastructure/RavenTestBase.cs
Labels: v5.1

#11192 RavenDB-15667 Hub Replication Access Info is Not exported/imported wh…
  src/Raven.Studio/typescript/models/database/tasks/exportDatabaseModel.ts
  src/Raven.Studio/typescript/models/database/tasks/importDatabaseModel.ts
Labels: v5.1

#11202 RavenDB-15644 Hub global change vector should ignore any sink id
  src/Raven.Server/Documents/Replication/IncomingReplicationHandler.cs
  src/Raven.Server/ServerWide/Context/DocumentsOperationContext.cs
  test/SlowTests/Issues/FilteredReplicationTests.cs
Labels: v5.1

#11209 RavenDB-15684 Cannot Edit Server-Wide Backup Task
  src/Raven.Studio/typescript/commands/resources/getServerWideBackupCommand.ts
  src/Raven.Studio/typescript/commands/resources/getServerWideBackupLocationCommand.ts
  src/Raven.Studio/typescript/viewmodels/manage/editServerWideBackup.ts
  tools/TypingsGenerator/Program.cs
Labels: v5.1

#11190 RavenDB-14787 Check for null argument in client commands
  src/Raven.Client/Documents/Commands/CreateSubscriptionCommand.cs
  src/Raven.Client/Documents/Commands/MultiGet/MultiGetCommand.cs
  src/Raven.Client/Documents/Operations/Backups/UpdatePeriodicBackupOperation.cs
  src/Raven.Client/Documents/Operations/ConnectionStrings/PutConnectionStringOperation.cs
  src/Raven.Client/Documents/Operations/Counters/GetCountersOperation.cs
  src/Raven.Client/Documents/Operations/ETL/AddEtlOperation.cs
  src/Raven.Client/Documents/Operations/ETL/UpdateEtlOperation.cs
  src/Raven.Client/Documents/Operations/Expiration/ConfigureExpirationOperation.cs
  src/Raven.Client/Documents/Operations/Refresh/ConfigureRefreshOperation.cs
  src/Raven.Client/Documents/Operations/Replication/UpdateExternalReplicationOperation.cs
  src/Raven.Client/Documents/Operations/Replication/UpdatePullReplicationAsSinkOperation.cs
  src/Raven.Client/Documents/Operations/Revisions/ConfigureRevisionsOperation.cs
  src/Raven.Client/Documents/Operations/TransactionsRecording/StartTransactionsRecordingOperation.cs
  src/Raven.Client/ServerWide/Operations/RestoreBackupOperation.cs
Labels: v4.2

#11207 RavenDB-14286 Require inspection on new `RavenCommand`s for parallel execution if can be checked for fastest node
  test/FastTests/Client/RavenCommandTest.cs
Labels: v4.2

#11216 RavenDB-15575 Patch guide is not visible when using Blue theme
  src/Raven.Studio/wwwroot/Content/css/styles-common.less
  src/Raven.Studio/wwwroot/Content/css/themes/blue-theme-variables-override.less
Labels: v5.1

#11212 RavenDB-14360 Add info about backup files location
  src/Raven.Studio/typescript/models/database/tasks/periodicBackup/amazonSettings.ts
  src/Raven.Studio/typescript/models/database/tasks/periodicBackup/azureSettings.ts
  src/Raven.Studio/typescript/models/database/tasks/periodicBackup/ftpSettings.ts
  src/Raven.Studio/typescript/models/database/tasks/periodicBackup/googleCloudSettings.ts
  src/Raven.Studio/wwwroot/App/views/partial/backupDestinations.html
Labels: v5.1

#11211 RavenDB-15603 Items disappear in databases view when it is portrait mode
  src/Raven.Studio/typescript/common/shell/searchBox.ts
  src/Raven.Studio/typescript/viewmodels/shell.ts
  src/Raven.Studio/wwwroot/App/views/resources/databases.html
  src/Raven.Studio/wwwroot/App/views/shell.html
  src/Raven.Studio/wwwroot/Content/css/basic-layout.less
  src/Raven.Studio/wwwroot/Content/css/bootstrap/navbar.less
  src/Raven.Studio/wwwroot/Content/css/main-menu.less
  src/Raven.Studio/wwwroot/Content/css/pages/databases.less
Labels: v5.1

#11205 RavenDB-15482 Flatten nested fields under Settings when editing the D…
  src/Raven.Studio/typescript/viewmodels/database/settings/databaseRecord.ts
Labels: v4.2

#11220 4.2 to 5.0 merge
  src/Raven.Client/Documents/Commands/CreateSubscriptionCommand.cs
  src/Raven.Client/Documents/Commands/MultiGet/MultiGetCommand.cs
  src/Raven.Client/Documents/Operations/Backups/UpdatePeriodicBackupOperation.cs
  src/Raven.Client/Documents/Operations/ConnectionStrings/PutConnectionStringOperation.cs
  src/Raven.Client/Documents/Operations/Counters/GetCountersOperation.cs
  src/Raven.Client/Documents/Operations/DatabaseHealthCheckOperation.cs
  src/Raven.Client/Documents/Operations/ETL/AddEtlOperation.cs
  src/Raven.Client/Documents/Operations/ETL/UpdateEtlOperation.cs
  src/Raven.Client/Documents/Operations/Expiration/ConfigureExpirationOperation.cs
  src/Raven.Client/Documents/Operations/Refresh/ConfigureRefreshOperation.cs
  src/Raven.Client/Documents/Operations/Replication/UpdateExternalReplicationOperation.cs
  src/Raven.Client/Documents/Operations/Replication/UpdatePullReplicationAsSinkOperation.cs
  src/Raven.Client/Documents/Operations/Revisions/ConfigureRevisionsOperation.cs
  src/Raven.Client/Documents/Operations/TransactionsRecording/StartTransactionsRecordingOperation.cs
  src/Raven.Client/Http/RequestExecutor.cs
  src/Raven.Client/ServerWide/Operations/RestoreBackupOperation.cs
  src/Raven.Server/Documents/Handlers/StatsHandler.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesReader.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Studio/typescript/viewmodels/database/settings/databaseRecord.ts
  src/Sparrow.Server/Sparrow.Server.csproj
  test/BenchmarkTests/BenchmarkTests.csproj
  test/FastTests/Client/RavenCommandTest.cs
  test/FastTests/FastTests.csproj
  test/SlowTests/Issues/RavenDB_15538.cs
  tools/Raven.Migrator/Raven.Migrator.csproj
Labels: v5.0

#11219 RavenDB-15303 Expose Timings Chart Option
  src/Raven.Studio/typescript/viewmodels/database/query/query.ts
  src/Raven.Studio/wwwroot/App/views/database/query/query.html
Labels: v5.1

#11221 5.0 to 5.1 merge
  src/Raven.Client/Documents/Commands/CreateSubscriptionCommand.cs
  src/Raven.Client/Documents/Commands/MultiGet/MultiGetCommand.cs
  src/Raven.Client/Documents/Operations/Backups/UpdatePeriodicBackupOperation.cs
  src/Raven.Client/Documents/Operations/ConnectionStrings/PutConnectionStringOperation.cs
  src/Raven.Client/Documents/Operations/Counters/GetCountersOperation.cs
  src/Raven.Client/Documents/Operations/DatabaseHealthCheckOperation.cs
  src/Raven.Client/Documents/Operations/ETL/AddEtlOperation.cs
  src/Raven.Client/Documents/Operations/ETL/UpdateEtlOperation.cs
  src/Raven.Client/Documents/Operations/Expiration/ConfigureExpirationOperation.cs
  src/Raven.Client/Documents/Operations/Refresh/ConfigureRefreshOperation.cs
  src/Raven.Client/Documents/Operations/Replication/UpdateExternalReplicationOperation.cs
  src/Raven.Client/Documents/Operations/Replication/UpdatePullReplicationAsSinkOperation.cs
  src/Raven.Client/Documents/Operations/Revisions/ConfigureRevisionsOperation.cs
  src/Raven.Client/Documents/Operations/TransactionsRecording/StartTransactionsRecordingOperation.cs
  src/Raven.Client/Http/RequestExecutor.cs
  src/Raven.Client/ServerWide/Operations/RestoreBackupOperation.cs
  src/Raven.Server/Documents/Handlers/StatsHandler.cs
  src/Raven.Server/Documents/Indexes/MapReduce/Static/MapReduceIndex.cs
  src/Raven.Server/Documents/TimeSeries/SegmentHeader.cs
  src/Raven.Server/Documents/TimeSeries/StatefulTimeStampValue.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesReader.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesStorage.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesValuesSegment.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Studio/typescript/viewmodels/database/settings/databaseRecord.ts
  src/Sparrow.Server/Sparrow.Server.csproj
  test/BenchmarkTests/BenchmarkTests.csproj
  test/FastTests/Client/RavenCommandTest.cs
  test/FastTests/FastTests.csproj
  test/SlowTests/Client/TimeSeries/Query/QueryFromMultipleTimeSeries.cs
  test/SlowTests/Client/TimeSeries/Session/TimeSeriesSessionTests.cs
  test/SlowTests/Client/TimeSeries/Session/TimeSeriesTypedSessionTests.cs
  test/SlowTests/Issues/RavenDB_15538.cs
  test/SlowTests/Server/Documents/Indexing/MapReduce/OutputReduceToCollectionTests_Counters.cs
  test/SlowTests/Server/Documents/Indexing/MapReduce/OutputReduceToCollectionTests_TimeSeries.cs
  test/Tests.Infrastructure/TestBase.cs
  test/Tests.Infrastructure/Utils/DebugPackageHandler.cs
  tools/Raven.Migrator/Raven.Migrator.csproj
Labels: v5.1

#11223 RavenDB-15605 Bad view of IOStats
  src/Raven.Studio/typescript/models/database/status/ioStatsGraph.ts
  src/Raven.Studio/wwwroot/App/views/database/indexes/indexPerformance.html
  src/Raven.Studio/wwwroot/App/views/database/status/ongoingTasksStats.html
  src/Raven.Studio/wwwroot/App/views/partial/ioStatsGraph.html
  src/Raven.Studio/wwwroot/Content/css/pages/index-performance.less
  src/Raven.Studio/wwwroot/Content/css/pages/metrics.less
  src/Raven.Studio/wwwroot/Content/css/pages/time-series-details.less
Labels: v5.1

#11222 RavenDB-15679 Broken UI when compacting only documents
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/compactDatabaseDetails.ts
Labels: v5.0

#11225 RavenDB-14286 New commands added to checked list
  test/FastTests/Client/RavenCommandTest.cs
Labels: v5.0

#11226 RavenDB-14286 New commands added to checked list
  test/FastTests/Client/RavenCommandTest.cs
Labels: v5.1

#11218 RavenDB-15692: Incremental backup with no changes should set status.i…
  src/Raven.Server/Documents/PeriodicBackup/BackupTask.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
Labels: v5.1

#11215 RavenDB-14962 Fix test EtlTombstonesInTheCluster
  test/SlowTests/Server/Replication/ReplicationCleanTombstones.cs
Labels: v4.2

#11230 RavenDB-7070 use invariant culture when parsing numbers in BlittableObjectInstance
  src/Raven.Server/Documents/Patch/BlittableObjectInstance.cs
Labels: v5.0

#11232 RavenDB-15672 : fix failing test
  test/SlowTests/Client/TimeSeries/Query/QueryFromMultipleTimeSeries.cs
Labels: v5.0

#11231 RavenDB-15671 Fix failing TimeSeriesGroupByTag tests
  test/SlowTests/Client/TimeSeries/Query/TimeSeriesGroupByTag.cs
Labels: v5.1

#11233 RavenDB-15597 + RavenDB-15664 : Tasks => Main Menu, DatabaseRecord =>…
  src/Raven.Studio/typescript/common/appUrl.ts
  src/Raven.Studio/typescript/common/shell/menu/generateMenuItems.ts
  src/Raven.Studio/typescript/common/shell/menu/items/documents.ts
  src/Raven.Studio/typescript/common/shell/menu/items/indexes.ts
  src/Raven.Studio/typescript/common/shell/menu/items/settings.ts
  src/Raven.Studio/typescript/common/shell/menu/items/stats.ts
  src/Raven.Studio/typescript/common/shell/menu/items/tasks.ts
  src/Raven.Studio/typescript/common/shell/routerConfiguration.ts
  src/Raven.Studio/typescript/viewmodels/database/advanced/databaseRecord.ts
  src/Raven.Studio/wwwroot/App/views/database/advanced/databaseRecord.html
Labels: v5.1

#11234 4.2 to 5.0 merge
  test/SlowTests/Server/Replication/ReplicationCleanTombstones.cs
Labels: v5.0

#11236 5.0 to 5.1 merge
  src/Raven.Client/Documents/Session/TimeSeries/TimeSeriesEntry.cs
  src/Raven.Server/Documents/Patch/BlittableObjectInstance.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesStorage.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesValuesSegment.cs
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/compactDatabaseDetails.ts
  test/SlowTests/Client/TimeSeries/Query/QueryFromMultipleTimeSeries.cs
  test/SlowTests/Client/TimeSeries/Query/TimeSeriesLinqQuery.cs
  test/SlowTests/Client/TimeSeries/Session/TimeSeriesTypedSessionTests.cs
  test/SlowTests/Server/Replication/ReplicationCleanTombstones.cs
Labels: v5.1

#11238 RavenDB-15605 Bad view of IOStats
  src/Raven.Studio/typescript/models/database/status/ioStatsGraph.ts
  src/Raven.Studio/wwwroot/App/views/database/indexes/indexPerformance.html
  src/Raven.Studio/wwwroot/App/views/database/status/ongoingTasksStats.html
  src/Raven.Studio/wwwroot/App/views/partial/ioStatsGraph.html
  src/Raven.Studio/wwwroot/Content/css/pages/index-performance.less
  src/Raven.Studio/wwwroot/Content/css/pages/metrics.less
Labels: v4.2

#11241 RavenDB-15466 wrap certificate to discover improper dispose
  test/Tests.Infrastructure/TestCertificatesHolder.cs
Labels: v5.0

#11240 RavenDB-15694 Fix dropdown options in 'Create new database'
  src/Raven.Studio/wwwroot/App/views/resources/databases.html
Labels: v5.1

#11239 RavenDB-15695 Missing Vertical Scroll in Setup Wizard
  src/Raven.Studio/wwwroot/App/views/wizard/setupShell.html
  src/Raven.Studio/wwwroot/Content/css/basic-layout.less
  src/Raven.Studio/wwwroot/Content/css/pages/setup.less
Labels: v5.1

#11213 RavenDB-15658 : fix failing test
  test/SlowTests/Client/TimeSeries/Query/TimeSeriesLinqQuery.cs
Labels: v5.0

#11243 RavenDB-15701 EnsureNotPassive should wait for certificates to be applied
  src/Raven.Server/Commercial/SetupManager.cs
  src/Raven.Server/Documents/DatabaseRequestHandler.cs
  src/Raven.Server/Documents/Handlers/Admin/AdminConfigurationHandler.cs
  src/Raven.Server/Documents/Handlers/Admin/RachisAdminHandler.cs
  src/Raven.Server/Documents/Handlers/SecretKeyHandler.cs
  src/Raven.Server/Documents/Handlers/TimeSeriesHandler.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreBackupTaskBase.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Smuggler/Migration/Migrator.cs
  src/Raven.Server/Utils/Cli/RavenCli.cs
  src/Raven.Server/Web/Authentication/AdminCertificatesHandler.cs
  src/Raven.Server/Web/Studio/LicenseHandler.cs
  src/Raven.Server/Web/System/AdminConfigurationHandler.cs
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
  src/Raven.Server/Web/System/CompareExchangeHandler.cs
  src/Raven.Server/Web/System/OngoingTasksHandler.cs
  src/Raven.Server/Web/System/SetupHandler.cs
  test/InterversionTests/MixedClusterTestBase.cs
  test/LicenseTests/LicenseLimitsTests.cs
  test/RachisTests/DatabaseCluster/RemoveNodeFromCluster.cs
  test/SlowTests/Authentication/AuthenticationLetsEncryptTests.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
Labels: v5.0

#11244 RavenDB-15466 don't dispose test certificates
  test/SlowTests/Authentication/AuthenticationDebugPackageInfoTests.cs
  test/Tests.Infrastructure/TestCertificatesHolder.cs
Labels: v5.0

#11242 RavenDB-15700 Fixing map-reduce index debug endpoint used by map-redu…
  src/Raven.Server/Documents/Indexes/Debugging/IndexDebugExtensions.cs
  src/Raven.Server/Documents/Indexes/MapReduce/ReduceMapResultsBase.cs
  test/SlowTests/Data/RavenDB_15700/BewerberStatus.csv
  test/SlowTests/Data/RavenDB_15700/Bewerbung.csv
  test/SlowTests/Data/RavenDB_15700/Vakanz.csv
  test/SlowTests/Issues/RavenDB_15700.cs
  test/SlowTests/SlowTests.csproj
Labels: v4.2

#11245 4.2 to 5.0 merge
  src/Raven.Client/Documents/BulkInsert/BulkInsertOperation.cs
  src/Raven.Client/Documents/Commands/GetNextOperationIdCommand.cs
  src/Raven.Client/Documents/Commands/KillOperationCommand.cs
  src/Raven.Client/Documents/Indexes/PutIndexResult.cs
  src/Raven.Client/Documents/Operations/GetStatisticsOperation.cs
  src/Raven.Client/Documents/Operations/Operation.cs
  src/Raven.Client/Documents/Smuggler/DatabaseSmuggler.cs
  src/Raven.Client/ServerWide/Operations/ServerWideOperation.cs
  src/Raven.Server/Config/Categories/PerformanceHintsConfiguration.cs
  src/Raven.Server/Documents/Handlers/Admin/AdminIndexHandler.cs
  src/Raven.Server/Documents/Indexes/Debugging/IndexDebugExtensions.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  src/Raven.Server/Documents/Indexes/MapReduce/ReduceMapResultsBase.cs
  src/Raven.Server/NotificationCenter/Notifications/AlertType.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Web/Operations/OperationsHandler.cs
  src/Raven.Studio/typescript/models/database/status/ioStatsGraph.ts
  src/Raven.Studio/wwwroot/App/views/database/indexes/indexPerformance.html
  src/Raven.Studio/wwwroot/App/views/database/status/ongoingTasksStats.html
  src/Raven.Studio/wwwroot/App/views/partial/ioStatsGraph.html
  src/Raven.Studio/wwwroot/Content/css/pages/index-performance.less
  src/Raven.Studio/wwwroot/Content/css/pages/metrics.less
  test/SlowTests/Data/RavenDB_15700/BewerberStatus.csv
  test/SlowTests/Data/RavenDB_15700/Bewerbung.csv
  test/SlowTests/Data/RavenDB_15700/Vakanz.csv
  test/SlowTests/Issues/RavenDB-4563.cs
  test/SlowTests/Issues/RavenDB_13293.cs
  test/SlowTests/Issues/RavenDB_15700.cs
  test/SlowTests/Issues/RavenDB_2514.cs
  test/SlowTests/Server/NotificationCenter/NotificationCenterTests.cs
  test/SlowTests/SlowTests.csproj
  test/Tests.Infrastructure/ClusterTestBase.cs
  test/Tests.Infrastructure/RavenTestBase.cs
Labels: v5.0

#11246 RavenDB-15703 Fixing the export of subscriptions
  src/Raven.Server/Smuggler/Documents/DatabaseSource.cs
  test/SlowTests/Client/Subscriptions/RavenDB_15703.cs
Labels: v4.2

#11247 5.0 to 5.1 merge
  src/Raven.Client/Documents/BulkInsert/BulkInsertOperation.cs
  src/Raven.Client/Documents/Commands/GetNextOperationIdCommand.cs
  src/Raven.Client/Documents/Commands/KillOperationCommand.cs
  src/Raven.Client/Documents/Indexes/PutIndexResult.cs
  src/Raven.Client/Documents/Operations/GetStatisticsOperation.cs
  src/Raven.Client/Documents/Operations/Operation.cs
  src/Raven.Client/Documents/Smuggler/DatabaseSmuggler.cs
  src/Raven.Client/ServerWide/Operations/ServerWideOperation.cs
  src/Raven.Server/Config/Categories/PerformanceHintsConfiguration.cs
  src/Raven.Server/Documents/Handlers/Admin/AdminIndexHandler.cs
  src/Raven.Server/Documents/Indexes/Debugging/IndexDebugExtensions.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  src/Raven.Server/Documents/Indexes/MapReduce/ReduceMapResultsBase.cs
  src/Raven.Server/NotificationCenter/Notifications/AlertType.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Web/Operations/OperationsHandler.cs
  test/SlowTests/Authentication/AuthenticationDebugPackageInfoTests.cs
  test/SlowTests/Data/RavenDB_15700/BewerberStatus.csv
  test/SlowTests/Data/RavenDB_15700/Bewerbung.csv
  test/SlowTests/Data/RavenDB_15700/Vakanz.csv
  test/SlowTests/Issues/RavenDB-4563.cs
  test/SlowTests/Issues/RavenDB_13293.cs
  test/SlowTests/Issues/RavenDB_15700.cs
  test/SlowTests/Issues/RavenDB_2514.cs
  test/SlowTests/Server/NotificationCenter/NotificationCenterTests.cs
  test/SlowTests/SlowTests.csproj
  test/Tests.Infrastructure/ClusterTestBase.cs
  test/Tests.Infrastructure/RavenTestBase.cs
  test/Tests.Infrastructure/TestCertificatesHolder.cs
Labels: v5.1

#11250 5.0 to 5.1 merge + updated to .NET 5.0 RC2
  .github/workflows/FastTests.yml
  bench/Micro.Benchmark/Micro.Benchmark.csproj
  src/Raven.Client/Raven.Client.csproj
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Server/Smuggler/Documents/DatabaseSource.cs
  src/Raven.Studio/Raven.Studio.csproj
  src/Sparrow/Sparrow.csproj
  test/BenchmarkTests/BenchmarkTests.csproj
  test/FastTests/FastTests.csproj
  test/SlowTests/Client/Subscriptions/RavenDB_15703.cs
  test/SlowTests/SlowTests.csproj
  tools/Raven.Debug/Raven.Debug.csproj
  tools/Raven.Migrator/Raven.Migrator.csproj
  tools/Voron.Recovery/Voron.Recovery.csproj
  tools/rvn/rvn.csproj
Labels: v5.1

#11252 HRINT-1831 filtered replication should always pass revisions tombstones
  src/Raven.Client/Documents/Operations/Replication/PullReplicationAsSink.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/Handlers/PullReplicationHandler.cs
  src/Raven.Server/Documents/Replication/AllowedPathsValidator.cs
  src/Raven.Server/Documents/Replication/IncomingReplicationHandler.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  test/SlowTests/Issues/FilteredReplicationTests.cs
Labels: v5.1

#11253 RavenDB-15617 handle TS legacy issue in the lowest MoveNext
  src/Raven.Server/Documents/TimeSeries/TimeSeriesValuesSegment.cs
Labels: v5.0

#11251 RDBCL-1575: fix stale backups [cherry pick from v4.2]
  src/Raven.Server/Documents/PeriodicBackup/BackupTask.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
Labels: v5.1

#11249 RavenDB-15017 add info to AddGlobalChangeVectorToNewDocument
  test/RachisTests/DatabaseCluster/ReplicationTests.cs
Labels: v4.2

#11259 RavenDB-15707 fixed issue with PAL not being copied for Win7
  src/Raven.Server/Raven.Server.csproj
  tools/rvn/rvn.csproj
Labels: v5.1

#11258 RavenDB-15697 Add wait time for etag in EtlTombstonesInTheCluster
  test/SlowTests/Server/Replication/ReplicationCleanTombstones.cs
Labels: v4.2

#11263 RavenDB-15632 dispose the command in ETL to release the blittables
  src/Raven.Server/Documents/ETL/Providers/Raven/RavenEtl.cs
Labels: v4.2

#11266 5.0 to 5.1 merge
  src/Sparrow/Collections/FastList.cs
  src/Sparrow/Json/AbstractBlittableJsonDocumentBuilder.cs
  src/Sparrow/Json/BlittableJsonDocumentBuilder.cs
  src/Sparrow/Json/BlittableWriter.cs
  src/Sparrow/Json/ManualBlittableJsonDocumentBuilder.cs
  test/BenchmarkTests/Patching/Patch.cs
Labels: v5.1

#11267 RavenDB-15670 Platform not supported warning in LetsEncryptClient
  src/Raven.Server/Commercial/LetsEncryptClient.cs
Labels: v5.1

#11256 RavenDB-14992 unify WhoIsLocking code path and handle exceptions thrown by it
  src/Raven.Client/Exceptions/UnsuccessfulFileAccessException.cs
  src/Raven.Server/Utils/IOExtensions.cs
  test/Tryouts/Program.cs
Labels: v4.2

#11272 RavenDB-15622 address PR comments
  src/Raven.Server/Documents/TombstoneCleaner.cs
  src/Raven.Server/Documents/TransactionOperationsMerger.cs
Labels: v4.2

#11277 RavenDB-13901 Show CPU & Memory graphs on dashboard when view loads
  src/Raven.Studio/typescript/viewmodels/resources/serverDashboard.ts
Labels: v5.1

#11274 RavenDB-15597 Ongoing Tasks menu item location
  src/Raven.Studio/typescript/common/shell/menu/items/tasks.ts
  src/Raven.Studio/wwwroot/Content/css/icons.less
Labels: v5.1

#11273 RavenDB-15678 - Fix the server-wide link in the ongoing-tasks view
  src/Raven.Studio/wwwroot/App/views/database/tasks/ongoingTasks.html
Labels: v5.1

#11271 RavenDB-15140 The token of null ValueExpression set to "null"
  src/Raven.Server/Documents/Queries/Parser/QueryScanner.cs
  test/SlowTests/Client/Subscriptions/Subscriptions.cs
Labels: v5.0

#11257 RavenDB-15616 use the initial value if not found in the json
  src/Sparrow/Json/JsonDeserializationBase.cs
  test/FastTests/Issues/RavenDB-7493.cs
Labels: v5.1

#11284 RavenDB-15442 tight the test
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
Labels: v4.2

#11283 RavenDB-15458 increase test timeout
  test/RachisTests/DatabaseCluster/ReplicationTests.cs
Labels: v4.2

#11282 RavenDB-15597 update colors, add missing icons
  src/Raven.Studio/typescript/common/shell/menu/items/manageServer.ts
  src/Raven.Studio/typescript/common/shell/menu/items/stats.ts
  src/Raven.Studio/typescript/common/shell/menu/items/tasks.ts
  src/Raven.Studio/wwwroot/App/views/manage/createServerWideTask.html
  src/Raven.Studio/wwwroot/App/views/manage/serverWideTasks.html
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.eot
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.svg
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.ttf
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.woff
  src/Raven.Studio/wwwroot/Content/css/fonts/selection.json
  src/Raven.Studio/wwwroot/Content/css/icons.less
Labels: v5.1

#11281 RavenDB-15737 update the sink changes during HandleDatabaseRecordChange
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
Labels: v5.1

#11286 4.2 to 5.0 merge
  src/Raven.Client/Exceptions/UnsuccessfulFileAccessException.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/TombstoneCleaner.cs
  src/Raven.Server/Documents/TransactionOperationsMerger.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/Web/System/OngoingTasksHandler.cs
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
  test/RachisTests/DatabaseCluster/ReplicationTests.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
Labels: v5.0

#11289 RavenDB-15126 add more details to the failing reason
  test/StressTests/Cluster/ClusterIndexNotificationsTestStress.cs
Labels: v4.2

#11287 RavenDB-15739 - Search on ID throwing an exception
  src/Raven.Server/Documents/Queries/QueryBuilder.cs
  test/SlowTests/Issues/RavenDB-15739.cs
Labels: v4.2

#11292 4.2 to 5.0 merge
  src/Raven.Client/Documents/Operations/Replication/UpdatePullReplicationAsSinkOperation.cs
  src/Raven.Server/Config/Categories/StorageConfiguration.cs
  src/Raven.Server/Documents/Queries/QueryBuilder.cs
  src/Raven.Server/Program.cs
  src/Voron/Impl/EncryptionBuffersPool.cs
  test/SlowTests/Client/Attachments/BigDummyStream.cs
  test/SlowTests/Issues/RavenDB-15145.cs
  test/SlowTests/Issues/RavenDB-15739.cs
  test/SlowTests/Smuggler/BackupDatabaseRecordTests.cs
  test/StressTests/Cluster/ClusterIndexNotificationsTestStress.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v5.0

#11296 5.0 to 5.1 merge
  src/Raven.Client/Documents/Operations/Replication/UpdatePullReplicationAsSinkOperation.cs
  src/Raven.Client/Exceptions/UnsuccessfulFileAccessException.cs
  src/Raven.Server/Config/Categories/StorageConfiguration.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/Queries/Parser/QueryScanner.cs
  src/Raven.Server/Documents/Queries/QueryBuilder.cs
  src/Raven.Server/Documents/TombstoneCleaner.cs
  src/Raven.Server/Documents/TransactionOperationsMerger.cs
  src/Raven.Server/Program.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/Web/Studio/EmbeddedData/Northwind.ravendbdump
  src/Raven.Server/Web/Studio/SampleDataHandler.cs
  src/Raven.Server/Web/System/OngoingTasksHandler.cs
  src/Voron/Impl/EncryptionBuffersPool.cs
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
  test/RachisTests/DatabaseCluster/ReplicationTests.cs
  test/SlowTests/Authentication/AuthenticationEncryptionTests.cs
  test/SlowTests/Client/Attachments/BigDummyStream.cs
  test/SlowTests/Client/Subscriptions/Subscriptions.cs
  test/SlowTests/Issues/RavenDB-15145.cs
  test/SlowTests/Issues/RavenDB-15739.cs
  test/SlowTests/Issues/RavenDB_3417.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
  test/SlowTests/Smuggler/BackupDatabaseRecordTests.cs
  test/StressTests/Cluster/ClusterIndexNotificationsTestStress.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v5.1

#11299 RavenDB-15313 : Get counters - Use sorted hash set or don't relay on order
  src/Raven.Client/Documents/Operations/Counters/GetCountersOperation.cs
  test/SlowTests/Issues/RavenDB_14919.cs
  test/SlowTests/Issues/RavenDB_15313.cs
Labels: v4.2

#11295 RavenDB-15668 Document Revisions View - Enhancements
  src/Raven.Studio/wwwroot/App/views/database/settings/revisions.html
  src/Raven.Studio/wwwroot/Content/css/basic-layout.less
  src/Raven.Studio/wwwroot/Content/css/bootstrap/tooltip.less
  src/Raven.Studio/wwwroot/Content/css/bootstrap/variables-body.less
  src/Raven.Studio/wwwroot/Content/css/pages/ongoing-tasks.less
  src/Raven.Studio/wwwroot/Content/css/themes/blue-theme-variables-override.less
  src/Raven.Studio/wwwroot/Content/css/themes/light-theme-variables-override.less
Labels: v5.1

#11291 RDBCL-1378 keep track of iowait value
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.5/IoWait.cs
  src/Raven.Server/Monitoring/Snmp/SnmpOids.cs
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
  src/Raven.Server/RavenServer.cs
  src/Raven.Server/Utils/Cpu/CpuUsageCalculator.cs
  src/Raven.Server/Utils/Cpu/ProcessInfo.cs
  src/Raven.Server/Utils/MetricCacher.cs
Labels: v4.2

#11304 RavenDB-15764 support for C# record serialization
  src/Raven.Client/Json/Serialization/NewtonsoftJson/DefaultRavenContractResolver.cs
  src/Sparrow/Extensions/TypeExtensions.cs
  test/SlowTests/Issues/RavenDB_15764.cs
Labels: v5.1

#11312 RavenDB-15526 Changes to CreateRaftClusterAndGetLeader
  test/Tests.Infrastructure/ClusterTestBase.cs
Labels: v4.2

#11302 RavenDB-15762 Consider adding support for '"yyyy-MM-ddTHH:mm:ss.fffZ"…
  src/Raven.Server/Documents/Queries/Results/TimeSeriesRetriever.cs
Labels: v5.0

#11298 RavenDB-15316 Add certificate error to the notification center
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
Labels: v4.2

#11310 RavenDB-15706 better error when using bulk insert without db
  src/Raven.Client/Documents/BulkInsert/BulkInsertOperation.cs
  test/FastTests/Issues/RavenDB-15706.cs
Labels: v5.0

#11317 RavenDB-15706 better error when using bulk insert without db
  src/Raven.Client/Documents/BulkInsert/BulkInsertOperation.cs
  test/FastTests/RavenDB-15706.cs
Labels: v4.2

#11319 RavenDB-7070 fixing NuGet packages
  bench/Regression.Benchmark/Regression.Benchmark.csproj
  src/Raven.Server/Raven.Server.csproj
  test/BenchmarkTests/BenchmarkTests.csproj
  test/EmbeddedTests/EmbeddedTests.csproj
  test/FastTests/FastTests.csproj
  test/InterversionTests/InterversionTests.csproj
  test/LicenseTests/LicenseTests.csproj
  test/RachisTests/RachisTests.csproj
  test/SlowTests/SlowTests.csproj
  test/StressTests/StressTests.csproj
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
  tools/Raven.Migrator/Raven.Migrator.csproj
Labels: v5.1

#11322 RavenDB-13204 Collapse/Expand button - Remove active class
  src/Raven.Studio/wwwroot/App/views/database/advanced/databaseRecord.html
  src/Raven.Studio/wwwroot/App/views/database/documents/editDocument.html
Labels: v5.1

#11323 4.2 to 5.0 merge
  libs/Lucene.Net.3.0.34.nupkg
  libs/Lucene.Net.3.0.36.nupkg
  src/Raven.Client/Documents/Operations/Counters/GetCountersOperation.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/Handlers/Admin/AdminConfigurationHandler.cs
  src/Raven.Server/Documents/Handlers/ConfigurationHandler.cs
  src/Raven.Server/Documents/Queries/LuceneIntegration/FastBitArray.cs
  src/Raven.Server/Documents/Queries/LuceneIntegration/TermsMatchQuery.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/Indexing/VoronIndexInput.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.5/IoWait.cs
  src/Raven.Server/Monitoring/Snmp/SnmpOids.cs
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Server/RavenServer.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
  src/Raven.Server/Smuggler/Documents/DatabaseSource.cs
  src/Raven.Server/Utils/Cpu/CpuUsageCalculator.cs
  src/Raven.Server/Utils/Cpu/ProcessInfo.cs
  src/Raven.Server/Utils/MetricCacher.cs
  test/FastTests/Graph/ClientGraphQueries.cs
  test/SlowTests/Client/ClientConfigurationTests.cs
  test/SlowTests/Issues/RavenDB-14880.cs
  test/SlowTests/Issues/RavenDB-14978.cs
  test/SlowTests/Issues/RavenDB_14919.cs
  test/SlowTests/Issues/RavenDB_15313.cs
  test/SlowTests/Issues/RavenDB_4636.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
  test/SlowTests/Server/Replication/ReplicationWithRevisions.cs
  test/SlowTests/Smuggler/SmugglerApiTests.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
Labels: v5.0

#11324 RavenDB-15789 Enhancements to /debug/storage endpoints
  src/Raven.Server/Documents/Handlers/Debugging/StorageHandler.cs
Labels: v4.2

#11325 5.0 to 5.1 merge
  libs/Lucene.Net.3.0.34.nupkg
  libs/Lucene.Net.3.0.36.nupkg
  src/Raven.Client/Documents/BulkInsert/BulkInsertOperation.cs
  src/Raven.Client/Documents/Operations/Counters/GetCountersOperation.cs
  src/Raven.Client/Documents/Session/AbstractDocumentQuery.cs
  src/Raven.Client/Documents/Session/Tokens/CloseSubclauseToken.cs
  src/Raven.Client/Documents/Session/Tokens/OpenSubclauseToken.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/Handlers/Admin/AdminConfigurationHandler.cs
  src/Raven.Server/Documents/Handlers/ConfigurationHandler.cs
  src/Raven.Server/Documents/Queries/LuceneIntegration/FastBitArray.cs
  src/Raven.Server/Documents/Queries/LuceneIntegration/TermsMatchQuery.cs
  src/Raven.Server/Documents/Queries/QueryBuilder.cs
  src/Raven.Server/Documents/Queries/Results/TimeSeries/TimeSeriesRetriever.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/Indexing/VoronIndexInput.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.5/IoWait.cs
  src/Raven.Server/Monitoring/Snmp/SnmpOids.cs
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Server/RavenServer.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
  src/Raven.Server/Smuggler/Documents/DatabaseSource.cs
  src/Raven.Server/Utils/Cpu/CpuUsageCalculator.cs
  src/Raven.Server/Utils/Cpu/ProcessInfo.cs
  src/Raven.Server/Utils/MetricCacher.cs
  src/Voron/Impl/EncryptionBuffersPool.cs
  src/Voron/Impl/Paging/CryptoPager.cs
  test/FastTests/Graph/ClientGraphQueries.cs
  test/FastTests/Issues/RavenDB-15706.cs
  test/FastTests/Voron/EncryptionBufferPool.cs
  test/SlowTests/Client/ClientConfigurationTests.cs
  test/SlowTests/Issues/RavenDB-14880.cs
  test/SlowTests/Issues/RavenDB-14978.cs
  test/SlowTests/Issues/RavenDB-15693.cs
  test/SlowTests/Issues/RavenDB_14919.cs
  test/SlowTests/Issues/RavenDB_15313.cs
  test/SlowTests/Issues/RavenDB_4636.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
  test/SlowTests/Server/Replication/ReplicationWithRevisions.cs
  test/SlowTests/Smuggler/SmugglerApiTests.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
Labels: v5.1
