Repository ravendb/ravendb, pull requests merged in 2021-06, with the labels that each got.

#12298 RavenDB-16509 - Small fix for edit index view
  src/Raven.Studio/wwwroot/App/views/database/indexes/editIndex.html
Labels: v5.2

#12299 RavenDB-16794 Cluster Dashboard widget - Fix labels
  src/Raven.Studio/typescript/models/resources/widgets/cpuUsage.ts
  src/Raven.Studio/typescript/viewmodels/resources/serverDashboard.ts
  src/Raven.Studio/wwwroot/App/views/resources/serverDashboard.html
  src/Raven.Studio/wwwroot/App/views/resources/widgets/cpuUsageWidget.html
  src/Raven.Studio/wwwroot/App/views/resources/widgets/indexingWidget.html
  src/Raven.Studio/wwwroot/App/views/resources/widgets/trafficWidget.html
Labels: v5.2

#12300 RavenDB-16729 Issues.RavenDB_16510.CheckTcpTrafficWatchExceptionMessage(exceptionType: True)
  test/SlowTests/Issues/RavenDB-16510.cs
Labels: v4.2

#12301 RavenDB-16759 Skipping the test which made that not awaited async calls (intentional) can cause heap corruption
  test/SlowTests/Issues/RavenDB_14235.cs
Labels: v4.2

#12302 4.2 to 5.1 merge
  docker/publish-nanoserver.ps1
  src/Raven.Server/Commercial/LicenseManager.cs
  src/Raven.Server/Commercial/LicenseStatus.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/Web/Authentication/AdminCertificatesHandler.cs
  test/SlowTests/Client/Subscriptions/RavenDB_13761.cs
  test/SlowTests/Issues/RavenDB-16510.cs
  test/SlowTests/Issues/RavenDB_14235.cs
  test/SlowTests/Issues/RavenDB_9519.cs
  test/SlowTests/Server/Documents/ETL/EtlTestBase.cs
  test/SlowTests/Server/Documents/ETL/SQL/SqlEtlTests.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v5.1

#12304 5.1 to 5.2 merge
  src/Raven.Server/Commercial/LicenseManager.cs
  src/Raven.Server/Commercial/LicenseStatus.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/Web/Authentication/AdminCertificatesHandler.cs
  src/Sparrow/Json/LazyStringParser.cs
  test/SlowTests/Client/Subscriptions/RavenDB_13761.cs
  test/SlowTests/Client/TimeSeries/Issues/RavenDB-15020.cs
  test/SlowTests/Issues/RavenDB-16510.cs
  test/SlowTests/Issues/RavenDB-16782.cs
  test/SlowTests/Issues/RavenDB_14235.cs
  test/SlowTests/Issues/RavenDB_9519.cs
  test/SlowTests/Server/Documents/ETL/EtlTestBase.cs
  test/SlowTests/Server/Documents/ETL/SQL/SqlEtlTests.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v5.2

#12310 RavenDB-16803 / RavenDB-16507 Fixing another case where a newly created read transaction could get an already disposed pager state of a scratch file.
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/Impl/Paging/AbstractPager.cs
  src/Voron/Impl/Scratch/ScratchBufferPool.cs
  src/Voron/StorageEnvironment.cs
  test/SlowTests/Voron/RavenDB_16635.cs
Labels: v4.2

#12311 4.2 to 5.1 merge
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/Impl/Paging/AbstractPager.cs
  src/Voron/Impl/Scratch/ScratchBufferPool.cs
  src/Voron/StorageEnvironment.cs
  test/SlowTests/Voron/RavenDB_16635.cs
Labels: v5.1

#12312 5.1 to 5.2 merge
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/Impl/Paging/AbstractPager.cs
  src/Voron/Impl/Scratch/ScratchBufferPool.cs
  src/Voron/StorageEnvironment.cs
  test/SlowTests/Voron/RavenDB_16635.cs
Labels: v5.2

#12328 RavenDB-15216 Link to RQL documentation in Query->Syntax popup
  src/Raven.Studio/typescript/viewmodels/database/query/querySyntax.ts
  src/Raven.Studio/wwwroot/App/views/database/query/querySyntax.html
Labels: v4.2

#12326 RavenDB-15883 Server uptime isn't refreshed by the server dashboard
  src/Raven.Studio/typescript/viewmodels/resources/serverDashboard.ts
Labels: v5.1

#12324 RavenDB-16503 Add max cores to cluster - value not stored in textbox…
  src/Raven.Studio/typescript/models/database/cluster/addClusterNodeModel.ts
  src/Raven.Studio/typescript/viewmodels/manage/addClusterNode.ts
  src/Raven.Studio/wwwroot/App/views/manage/addClusterNode.html
  src/Raven.Studio/wwwroot/App/views/manage/assignCores.html
Labels: v5.1

#12309 RavenDB-16550 Change reset index icon + add info in confirmation
  src/Raven.Studio/wwwroot/App/views/database/indexes/indexes.html
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.eot
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.svg
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.ttf
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.woff
  src/Raven.Studio/wwwroot/Content/css/icons.less
Labels: v5.2

#12327 RavenDB-16821 move PendingRollingIndexException
  src/Raven.Client/Documents/Indexes/IndexDefinitionBuilder.cs
  src/Raven.Client/Exceptions/Documents/Indexes/PendingRollingIndexException.cs
  src/Raven.Server/RavenServerStartup.cs
  test/SlowTests/Rolling/RollingIndexesClusterTests.cs
Labels: v5.2

#12308 RavenDB-16584 Index throttling - Time scalse display in uneven interv…
  src/Raven.Studio/wwwroot/Content/css/main-menu.less
  src/Raven.Studio/wwwroot/Content/css/pages/index-performance.less
Labels: v5.2

#12322 RavenDB-16825 - convert from MemoryStream to FileStream if needed
  src/Raven.Server/Indexing/VoronIndexOutput.cs
Labels: v4.2

#12330 4.2 to 5.1 merge
  src/Raven.Server/Indexing/VoronIndexOutput.cs
  src/Raven.Studio/typescript/viewmodels/database/query/querySyntax.ts
  src/Raven.Studio/wwwroot/App/views/database/query/querySyntax.html
Labels: v5.1

#12331 RavenDB-15216 Link to RQL documentation in Query->Syntax popup (Fix v…
  src/Raven.Studio/wwwroot/App/views/database/query/querySyntax.html
Labels: v5.1

#12329 RavenDB-15419 Validation in create backup when Snapshot type is sele…
  src/Raven.Studio/typescript/models/database/tasks/periodicBackup/encryptionSettings.ts
  src/Raven.Studio/typescript/models/database/tasks/periodicBackup/periodicBackupConfiguration.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editPeriodicBackupTask.ts
  src/Raven.Studio/wwwroot/App/views/database/tasks/editPeriodicBackupTask.html
Labels: v4.2

#12315 RavenDB-16777: Fix creation of empty folder when database name start …
  src/Raven.Server/ServerWide/Commands/PutServerWideBackupConfigurationCommand.cs
  test/SlowTests/Issues/RavenDB_16777.cs
Labels: v4.2

#12332 RavenDB-15570 Edit index fields - Provide validation when both Indexi…
  src/Raven.Studio/typescript/models/database/index/indexFieldOptions.ts
  src/Raven.Studio/wwwroot/App/views/database/indexes/editIndex.html
Labels: v5.1

#12313 RavenDB-16759 Making sure that not awaited async calls (intentional) …
  src/Raven.Client/Documents/Session/InMemoryDocumentSessionOperations.cs
  test/SlowTests/Issues/RavenDB_14235.cs
Labels: v4.2

#12334 RavenDB-16839 fixing tests
  test/SlowTests/Issues/RavenDB-15890.cs
Labels: v5.1

#12335 RavenDB-15727 Replication Delay Time - Validation & Enhancement
  src/Raven.Studio/typescript/models/database/tasks/ongoingTaskReplicationEditModel.ts
  src/Raven.Studio/typescript/models/database/tasks/ongoingTaskReplicationHubEditModel.ts
  src/Raven.Studio/typescript/models/database/tasks/serverWide/serverWideExternalReplicationEditModel.ts
  src/Raven.Studio/wwwroot/App/views/database/tasks/editExternalReplicationTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editReplicationHubTask.html
  src/Raven.Studio/wwwroot/App/views/manage/editServerWideExternalReplication.html
Labels: v5.1

#12339 4.2 to 5.1 merge
  src/Raven.Client/Documents/Session/InMemoryDocumentSessionOperations.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/ServerWide/Commands/PutServerWideBackupConfigurationCommand.cs
  src/Raven.Studio/typescript/models/database/tasks/periodicBackup/encryptionSettings.ts
  src/Raven.Studio/typescript/models/database/tasks/periodicBackup/periodicBackupConfiguration.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editPeriodicBackupTask.ts
  src/Raven.Studio/wwwroot/App/views/database/tasks/editPeriodicBackupTask.html
  test/SlowTests/Issues/RavenDB-16510.cs
  test/SlowTests/Issues/RavenDB_14235.cs
  test/SlowTests/Issues/RavenDB_16777.cs
Labels: v5.1

#12340 RavenDB-16840 : fix flaky test
  test/SlowTests/Client/TimeSeries/Issues/RavenDB-15020.cs
Labels: v5.1

#12333 HRINT-2001 support custom api.ravendb.net url
  src/Raven.Server/Commercial/ApiHttpClient.cs
Labels: v4.2

#12343 RavenDB-16850 immediately materialize values of a single timeseries entry result because the memory block is reused during the enumeration
  src/Raven.Server/Documents/Indexes/Static/TimeSeries/DynamicTimeSeriesSegment.cs
  test/SlowTests/Issues/RavenDB_16850.cs
Labels: v5.1

#12346 RavenDB-16550 Update reset-index icon
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.eot
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.json
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.svg
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.ttf
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.woff
Labels: v5.2

#12344 RavenDB-15802 Fixing concurrent usage of the context. We were passing the context to the operation running in the background e.g. patch and using the same context for WriteOperationIdAndNodeTag()
  src/Raven.Server/Documents/Handlers/QueriesHandler.cs
  src/Raven.Server/Web/Studio/StudioCollectionsHandler.cs
Labels: v4.2

#12347 RavenDB-16833 Fixing possible memory corruption when throwing on detection of running async task
  src/Raven.Client/Documents/Session/InMemoryDocumentSessionOperations.cs
Labels: v5.1

#12349 RavenDB-16647 Pass actual memory info to OutOfMemoryDetails in OutOfMemoryNotifications when EarlyOutOfMemoryException is thrown
  src/Raven.Server/NotificationCenter/OutOfMemoryNotifications.cs
  src/Sparrow.Server/LowMemory/MemoryInformation.cs
Labels: v4.2

#12348 4.2 to 5.1 merge
  src/Raven.Client/ServerWide/Operations/CreateDatabaseOperation.cs
  src/Raven.Client/ServerWide/Operations/UpdateDatabaseOperation.cs
  src/Raven.Server/Commercial/ApiHttpClient.cs
  src/Raven.Server/Documents/Handlers/QueriesHandler.cs
  src/Raven.Server/Web/Authentication/AdminCertificatesHandler.cs
  src/Raven.Server/Web/Studio/StudioCollectionsHandler.cs
  src/Raven.Studio/typescript/commands/auth/replaceClusterCertificateCommand.ts
  src/Raven.Studio/typescript/viewmodels/manage/certificates.ts
  src/Raven.Studio/wwwroot/App/views/manage/certificates.html
  test/Tests.Infrastructure/ClusterTestBase.cs
Labels: v5.1

#12351 RavenDB-16368 Fixing ocassionally failing test due to Random() usage by providing contant seed parameter so we can be assert the number of journal files
  test/SlowTests/Issues/RavenDB_15930.cs
Labels: v4.2

#12352 RavenDB-16847 notify raft index change after server restart
  src/Raven.Server/Documents/DocumentDatabase.cs
  test/SlowTests/Cluster/ClusterIndexNotificationsTest.cs
Labels: v4.2

#12353 RavenDB-16842 We can get OperationCancelledException from an already disposed storage environment. In that case we want to have the same handling like for ObjectDisposedException.
  src/Raven.Server/Documents/Queries/QueryRunner.cs
Labels: v4.2

#12357 HRINT-2184 Try to include the blittable json in the exception message when a deserialization error happens
  src/Raven.Client/Json/Serialization/NewtonsoftJson/Internal/SessionBlittableJsonConverter.cs
Labels: v5.1

#12355 RavenDB-16550 Reset index icon + add info in confirmation
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexes.ts
  src/Raven.Studio/wwwroot/App/views/database/indexes/indexes.html
Labels: v5.2

#12350 RavenDB-16844 - NRE Handle request bug fixed
  src/Raven.Client/Documents/Session/Operations/Lazy/LazyRevisionOperation.cs
  test/FastTests/Server/Documents/Revisions/RevisionsTests.cs
Labels: v5.2

#12359 4.2 to 5.1 merge
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/Queries/QueryRunner.cs
  src/Raven.Server/NotificationCenter/OutOfMemoryNotifications.cs
  src/Sparrow.Server/LowMemory/MemoryInformation.cs
  test/SlowTests/Cluster/ClusterIndexNotificationsTest.cs
  test/SlowTests/Issues/RavenDB_15930.cs
  test/Tests.Infrastructure/TestBase.cs
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
  tools/Raven.Debug/StackTrace/StackTracer.cs
  tools/Voron.Recovery/Voron.Recovery.csproj
  tools/rvn/rvn.csproj
Labels: v5.1

#12360 5.1 to 5.2 merge
  src/Raven.Client/Documents/Session/InMemoryDocumentSessionOperations.cs
  src/Raven.Client/Json/Serialization/NewtonsoftJson/Internal/SessionBlittableJsonConverter.cs
  src/Raven.Client/ServerWide/Operations/CreateDatabaseOperation.cs
  src/Raven.Client/ServerWide/Operations/UpdateDatabaseOperation.cs
  src/Raven.Server/Commercial/ApiHttpClient.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/Handlers/QueriesHandler.cs
  src/Raven.Server/Documents/Indexes/Static/TimeSeries/DynamicTimeSeriesSegment.cs
  src/Raven.Server/Documents/Queries/QueryRunner.cs
  src/Raven.Server/NotificationCenter/OutOfMemoryNotifications.cs
  src/Raven.Server/Web/Authentication/AdminCertificatesHandler.cs
  src/Raven.Server/Web/Studio/StudioCollectionsHandler.cs
  src/Raven.Studio/typescript/commands/auth/replaceClusterCertificateCommand.ts
  src/Raven.Studio/typescript/common/generalUtils.ts
  src/Raven.Studio/typescript/viewmodels/common/timeSeriesPlotDetails.ts
  src/Raven.Studio/typescript/viewmodels/database/query/query.ts
  src/Raven.Studio/typescript/viewmodels/manage/certificates.ts
  src/Raven.Studio/wwwroot/App/views/common/timeSeriesPlotDetails.html
  src/Raven.Studio/wwwroot/App/views/manage/certificates.html
  src/Raven.Studio/wwwroot/Content/css/pages/query.less
  src/Sparrow.Server/LowMemory/MemoryInformation.cs
  test/SlowTests/Client/TimeSeries/Issues/RavenDB-15020.cs
  test/SlowTests/Cluster/ClusterIndexNotificationsTest.cs
  test/SlowTests/Issues/RavenDB_15930.cs
  test/SlowTests/Issues/RavenDB_16850.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
  test/Tests.Infrastructure/TestBase.cs
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
  tools/Raven.Debug/StackTrace/StackTracer.cs
  tools/Voron.Recovery/Voron.Recovery.csproj
  tools/rvn/rvn.csproj
Labels: v5.2

#12362 RavenDB-15966 Fix Studio for the latest 5.1 to 5.2 Merge
  src/Raven.Studio/typescript/viewmodels/manage/certificates.ts
  src/Raven.Studio/wwwroot/App/views/database/query/query.html
  src/Raven.Studio/wwwroot/App/views/manage/certificates.html
Labels: v5.2

#12367 RavenDB-16862 tighten SlowTests.Issues.RavenDB_15535.MissingRevisions
  test/SlowTests/Issues/RavenDB-15535.cs
Labels: v4.2

#12364 RavenDB-16076: fix failing test
  test/RachisTests/SubscriptionFailoverWIthWaitingChains.cs
Labels: v4.2

#12363 RavenDB-16485: add reasonable timeout, print status on failure in BackupTestBase
  test/Tests.Infrastructure/BackupTestBase.cs
Labels: v4.2

#12369 RavenDB-16584 set same gap color in ongoing task stats and indexing p…
  src/Raven.Studio/wwwroot/Content/css/pages/metrics.less
Labels: v5.2

#12374 RavenDB-16817 Don't put empty string to RemoteFolderName when creatin…
  src/Raven.Studio/typescript/models/database/tasks/periodicBackup/amazonSettings.ts
  src/Raven.Studio/typescript/models/database/tasks/periodicBackup/azureSettings.ts
  src/Raven.Studio/typescript/models/database/tasks/periodicBackup/googleCloudSettings.ts
Labels: v5.1

#12371 RavenDB-16867 We need to check all certificates matching a given pinning hash not only the first one in MaybeAllowConnectionBasedOnPinningHash()
  src/Raven.Server/RavenServer.cs
Labels: v4.2

#12375 RavenDB-16136 : Cannot include typed time series
  src/Raven.Client/Documents/Session/AsyncSessionDocumentTimeSeries.cs
  src/Raven.Client/Documents/Session/SessionDocumentTimeSeries.cs
  test/SlowTests/Client/TimeSeries/Issues/RavenDB-14164.cs
  test/SlowTests/Client/TimeSeries/Issues/RavenDB-16060.cs
  test/SlowTests/Client/TimeSeries/Session/TimeSeriesTypedSessionTests.cs
Labels: v5.2

#12377 4.2 to 5.1 merge
  bench/SubscriptionFailover.Benchmark/Program.cs
  src/Raven.Client/Documents/Operations/Backups/PeriodicBackupStatus.cs
  src/Raven.Server/Documents/PeriodicBackup/BackupTask.cs
  src/Raven.Server/RavenServer.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  test/BenchmarkTests/BenchmarkTestBase.cs
  test/FastTests/Server/Replication/ReplicationTestBase.cs
  test/RachisTests/AddNodeToClusterTests.cs
  test/RachisTests/Cluster.cs
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
  test/RachisTests/DatabaseCluster/EtlFailover.cs
  test/RachisTests/DatabaseCluster/OngoingTasks.cs
  test/RachisTests/DatabaseCluster/RemoveNodeFromCluster.cs
  test/RachisTests/DatabaseCluster/ReplicationTests.cs
  test/RachisTests/DisableNodeOnClusterTest.cs
  test/RachisTests/ElectionTests.cs
  test/RachisTests/EmergencyOperations.cs
  test/RachisTests/RavenDB-6602.cs
  test/RachisTests/SubscriptionsFailover.cs
  test/SlowTests/Authentication/AuthenticationClusterTests.cs
  test/SlowTests/Client/Attachments/AttachmentFailover.cs
  test/SlowTests/Client/Counters/CountersCluster.cs
  test/SlowTests/Cluster/ClusterModesForRequestExecutorTest.cs
  test/SlowTests/Cluster/ClusterOperationTests.cs
  test/SlowTests/Cluster/ClusterTransactionTests.cs
  test/SlowTests/ExtensionPoints/ExtensionPointsTests.cs
  test/SlowTests/Issues/EncryptedDatabaseGroup.cs
  test/SlowTests/Issues/RavenDB-11571.cs
  test/SlowTests/Issues/RavenDB-12132.cs
  test/SlowTests/Issues/RavenDB-12598.cs
  test/SlowTests/Issues/RavenDB-12921.cs
  test/SlowTests/Issues/RavenDB-13185.cs
  test/SlowTests/Issues/RavenDB-13341.cs
  test/SlowTests/Issues/RavenDB-13767.cs
  test/SlowTests/Issues/RavenDB-14880.cs
  test/SlowTests/Issues/RavenDB-14978.cs
  test/SlowTests/Issues/RavenDB-15890.cs
  test/SlowTests/Issues/RavenDB-15900.cs
  test/SlowTests/Issues/RavenDB-6886.cs
  test/SlowTests/Issues/RavenDB-7059.cs
  test/SlowTests/Issues/RavenDB_13293.cs
  test/SlowTests/Issues/RavenDB_13457.cs
  test/SlowTests/Issues/RavenDB_13796.cs
  test/SlowTests/Issues/RavenDB_14448.cs
  test/SlowTests/Issues/RavenDB_7912.cs
  test/SlowTests/Issues/RavenDB_8044.cs
  test/SlowTests/Server/Documents/ETL/Raven/RavenDB_13288.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Retention.cs
  test/SlowTests/Server/Replication/DisableDatabasePropagationInRaftCluster.cs
  test/SlowTests/Server/Replication/PullReplicationTests.cs
  test/SlowTests/Server/Replication/ReplicationConflictsTests.cs
  test/SlowTests/Server/Replication/ReplicationWriteAssurance.cs
  test/StressTests/Rachis/DatabaseCluster/ReplicationTestsStress.cs
  test/StressTests/Rachis/SubscriptionsFailoverStress.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
  test/Tests.Infrastructure/RavenTestBase.cs
Labels: v5.1

#12378 5.1 to 5.2 merge
  bench/SubscriptionFailover.Benchmark/Program.cs
  src/Raven.Client/Documents/Operations/Backups/PeriodicBackupStatus.cs
  src/Raven.Server/Documents/PeriodicBackup/BackupTask.cs
  src/Raven.Server/RavenServer.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Studio/typescript/models/database/tasks/periodicBackup/amazonSettings.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/destinations/azureSettings.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/destinations/googleCloudSettings.ts
  test/BenchmarkTests/BenchmarkTestBase.cs
  test/FastTests/Server/Replication/ReplicationTestBase.cs
  test/RachisTests/AddNodeToClusterTests.cs
  test/RachisTests/Cluster.cs
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
  test/RachisTests/DatabaseCluster/EtlFailover.cs
  test/RachisTests/DatabaseCluster/OngoingTasks.cs
  test/RachisTests/DatabaseCluster/RemoveNodeFromCluster.cs
  test/RachisTests/DatabaseCluster/ReplicationTests.cs
  test/RachisTests/DisableNodeOnClusterTest.cs
  test/RachisTests/ElectionTests.cs
  test/RachisTests/EmergencyOperations.cs
  test/RachisTests/RavenDB-6602.cs
  test/RachisTests/SubscriptionsFailover.cs
  test/SlowTests/Authentication/AuthenticationClusterTests.cs
  test/SlowTests/Client/Attachments/AttachmentFailover.cs
  test/SlowTests/Client/Counters/CountersCluster.cs
  test/SlowTests/Cluster/ClusterModesForRequestExecutorTest.cs
  test/SlowTests/Cluster/ClusterOperationTests.cs
  test/SlowTests/Cluster/ClusterTransactionTests.cs
  test/SlowTests/ExtensionPoints/ExtensionPointsTests.cs
  test/SlowTests/Issues/EncryptedDatabaseGroup.cs
  test/SlowTests/Issues/RavenDB-11571.cs
  test/SlowTests/Issues/RavenDB-12132.cs
  test/SlowTests/Issues/RavenDB-12598.cs
  test/SlowTests/Issues/RavenDB-12921.cs
  test/SlowTests/Issues/RavenDB-13185.cs
  test/SlowTests/Issues/RavenDB-13341.cs
  test/SlowTests/Issues/RavenDB-13767.cs
  test/SlowTests/Issues/RavenDB-14880.cs
  test/SlowTests/Issues/RavenDB-14978.cs
  test/SlowTests/Issues/RavenDB-15890.cs
  test/SlowTests/Issues/RavenDB-15900.cs
  test/SlowTests/Issues/RavenDB-6886.cs
  test/SlowTests/Issues/RavenDB-7059.cs
  test/SlowTests/Issues/RavenDB_13293.cs
  test/SlowTests/Issues/RavenDB_13457.cs
  test/SlowTests/Issues/RavenDB_13796.cs
  test/SlowTests/Issues/RavenDB_14448.cs
  test/SlowTests/Issues/RavenDB_7912.cs
  test/SlowTests/Issues/RavenDB_8044.cs
  test/SlowTests/Server/Documents/ETL/Raven/RavenDB_13288.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Retention.cs
  test/SlowTests/Server/Replication/DisableDatabasePropagationInRaftCluster.cs
  test/SlowTests/Server/Replication/PullReplicationTests.cs
  test/SlowTests/Server/Replication/ReplicationConflictsTests.cs
  test/SlowTests/Server/Replication/ReplicationWriteAssurance.cs
  test/StressTests/Rachis/DatabaseCluster/ReplicationTestsStress.cs
  test/StressTests/Rachis/SubscriptionsFailoverStress.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
  test/Tests.Infrastructure/RavenTestBase.cs
Labels: v5.2

#12382 RavenDB-15561 MinimumRevisionsToKeep - Refactor info text
  src/Raven.Studio/typescript/models/database/documents/revisionsConfigurationEntry.ts
  src/Raven.Studio/wwwroot/App/views/database/settings/revisions.html
Labels: v4.2

#12385 RavenDB-16517 - Offline activation of a license
  src/Raven.Server/Commercial/LicenseManager.cs
  src/Raven.Server/Config/Categories/LicenseConfiguration.cs
Labels: v5.1

#12390 RavenDB-16882 - log only when we deleted the notification
  src/Raven.Server/NotificationCenter/NotificationsStorage.cs
Labels: v4.2

#12387 [RavenDB-16249 Unskip passing test
  test/SlowTests/MailingList/JohanNilsson.cs
Labels: v4.2

#12381 RavenDB-16768: fix failing test, don't wait for WaitForExecutionOnSpecificNode on single node
  test/SlowTests/Client/Subscriptions/SubscriptionsBasic.cs
Labels: v5.1

#12321 RavenDB-16828: try to return the new leader if it changes while cluster creation in tests
  test/Tests.Infrastructure/ClusterTestBase.cs
Labels: v4.2

#12392 4.2 to 5.1 merge
  src/Raven.Server/Commercial/License.cs
  src/Raven.Server/Commercial/LicenseManager.cs
  src/Raven.Server/NotificationCenter/NotificationsStorage.cs
  src/Raven.Server/Rachis/Follower.cs
  src/Raven.Server/Rachis/Remote/RemoteConnection.cs
  src/Raven.Server/ServerWide/Commands/CompareExchangeCommands.cs
  src/Raven.Studio/typescript/models/database/documents/revisionsConfigurationEntry.ts
  src/Raven.Studio/wwwroot/App/views/database/settings/revisions.html
  src/Sparrow.Server/Json/Sync/BlittableJsonTextWriter.cs
  src/Sparrow/Json/AbstractBlittableJsonTextWriter.cs
  test/SlowTests/Issues/RavenDB-16827.cs
  test/SlowTests/MailingList/JohanNilsson.cs
  test/SlowTests/Server/Documents/PeriodicBackup/RavenDB-11139.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v5.1

#12396 5.1 to 5.2 merge
  src/Raven.Server/Commercial/License.cs
  src/Raven.Server/Commercial/LicenseManager.cs
  src/Raven.Server/Config/Categories/LicenseConfiguration.cs
  src/Raven.Server/NotificationCenter/NotificationsStorage.cs
  src/Raven.Server/Rachis/Follower.cs
  src/Raven.Server/Rachis/Remote/RemoteConnection.cs
  src/Raven.Server/ServerWide/Commands/CompareExchangeCommands.cs
  src/Raven.Studio/typescript/models/database/documents/revisionsConfigurationEntry.ts
  src/Raven.Studio/wwwroot/App/views/database/settings/revisions.html
  src/Sparrow.Server/Json/Sync/BlittableJsonTextWriter.cs
  src/Sparrow/Json/AbstractBlittableJsonTextWriter.cs
  test/SlowTests/Client/Subscriptions/SubscriptionsBasic.cs
  test/SlowTests/Issues/RavenDB-16827.cs
  test/SlowTests/MailingList/JohanNilsson.cs
  test/SlowTests/Server/Documents/PeriodicBackup/RavenDB-11139.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v5.2

#12397 RavenDB-16888 fix tight loop after missing attachment
  src/Raven.Server/Documents/Replication/ReplicationDocumentSender.cs
  src/Sparrow.Server/Collections/AsyncQueue.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
Labels: v4.2

#12395 RavenDB-16891 : ensure local file deletion in case of error during upload
  src/Raven.Server/Documents/ETL/Providers/OLAP/OlaptEtl.cs
Labels: v5.2

#12393 RavenDB-16802: log database wake up caller for test [5.1]
  src/Raven.Server/Documents/DatabasesLandlord.cs
  test/StressTests/Server/Replication/ExternalReplicationStressTests.cs
Labels: v5.1

#12400 RavenDB-16858 Fixing race condition betweenc ancelling the waiter in the queue and calling Release() on it.
  src/Sparrow/Utils/FifoSemaphore.cs
  test/SlowTests/Issues/RavenDB_16412_FifoSemaphoreTests.cs
Labels: v4.2

#12402 4.2 to 5.1 merge
  scripts/linux/pkg/deb/assets/ravendb/debian/ravendb.postrm
  scripts/linux/pkg/deb/assets/test.sh
  scripts/linux/pkg/deb/ubuntu_test.Dockerfile
  src/Raven.Server/Documents/Replication/ReplicationDocumentSender.cs
  src/Raven.Studio/typescript/viewmodels/common/detectBrowser.ts
  src/Raven.Studio/typescript/viewmodels/shell.ts
  src/Raven.Studio/typescript/viewmodels/wizard/welcome.ts
  src/Raven.Studio/wwwroot/App/views/common/detectBrowser.html
  src/Raven.Studio/wwwroot/App/views/shell.html
  src/Raven.Studio/wwwroot/App/views/wizard/welcome.html
  src/Sparrow.Server/Collections/AsyncQueue.cs
  src/Sparrow.Server/Json/Sync/BlittableJsonTextWriter.cs
  src/Sparrow/Json/AbstractBlittableJsonTextWriter.cs
  src/Sparrow/Utils/FifoSemaphore.cs
  test/SlowTests/Issues/RavenDB_16412_FifoSemaphoreTests.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
Labels: v5.1

#12401 RavenDB-16858 / RavenDB-16519 Getting back to use Queue instead of List.
  src/Sparrow/Utils/FifoSemaphore.cs
  test/SlowTests/Issues/RavenDB_16412_FifoSemaphoreTests.cs
Labels: v4.2

#12407 RavenDB-14301 Fix studio for the 4.2 to 5.1 merge
  src/Raven.Studio/wwwroot/App/views/shell.html
Labels: v5.1

#12406 RavenDB-16895
  src/Raven.Server/Program.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  test/SlowTests/Issues/RavenDB_16895.cs
Labels: v4.2

#12405 5.1 to 5.2 merge
  scripts/linux/pkg/deb/assets/ravendb/debian/ravendb.postrm
  scripts/linux/pkg/deb/assets/test.sh
  scripts/linux/pkg/deb/ubuntu_test.Dockerfile
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/IndexReadOperation.cs
  src/Raven.Server/Documents/Replication/ReplicationDocumentSender.cs
  src/Raven.Server/Program.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Studio/typescript/viewmodels/common/detectBrowser.ts
  src/Raven.Studio/typescript/viewmodels/shell.ts
  src/Raven.Studio/typescript/viewmodels/wizard/welcome.ts
  src/Raven.Studio/wwwroot/App/views/common/detectBrowser.html
  src/Raven.Studio/wwwroot/App/views/shell.html
  src/Raven.Studio/wwwroot/App/views/wizard/welcome.html
  src/Sparrow.Server/Collections/AsyncQueue.cs
  src/Sparrow.Server/Json/Sync/BlittableJsonTextWriter.cs
  src/Sparrow/Json/AbstractBlittableJsonTextWriter.cs
  src/Sparrow/Utils/FifoSemaphore.cs
  test/BenchmarkTests/BenchmarkTestBase.cs
  test/SlowTests/Issues/RavenDB_16412_FifoSemaphoreTests.cs
  test/SlowTests/Issues/RavenDB_16895.cs
  test/SlowTests/Rolling/RollingIndexesClusterTests.cs
  test/StressTests/Server/Replication/ExternalReplicationStressTests.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
  tools/Raven.Debug/StackTrace/StackTracer.cs
Labels: v5.2

#12419 RavenDB-16493 fix windows image tagging
  docker/build-nanoserver.ps1
Labels: v5.2

#12416 RavenDB-16049 IOStats & Indexing Performance Views: Auto-reconnect to…
  src/Raven.Studio/typescript/common/liveIOStatsWebSocketClient.ts
  src/Raven.Studio/typescript/common/liveIndexPerformanceWebSocketClient.ts
  src/Raven.Studio/typescript/models/database/status/ioStatsGraph.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexPerformance.ts
  src/Raven.Studio/typescript/viewmodels/database/status/ioStats.ts
  src/Raven.Studio/wwwroot/App/views/database/indexes/indexPerformance.html
  src/Raven.Studio/wwwroot/App/views/partial/ioStatsGraph.html
Labels: v5.2

#12415 RavenDB-16841 - Issues.RavenDB_16510.CheckTcpTrafficWatch
  test/SlowTests/Issues/RavenDB-16510.cs
Labels: v5.2

#12411 RavenDB-16820 - In traffic watch bulk docs displayed as none type
  src/Raven.Server/Documents/Handlers/BatchHandler.cs
Labels: v5.1

#12410 RavenDB-16900 - Double dispose in DisposeAsync in DisposeOnce
  src/Sparrow/Threading/DisposeOnce.cs
Labels: v4.2

#12420 RavenDB-16911 make sure database deletion is under r/w lock
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
Labels: v4.2

#12417 RavenDB-16860 Added Storage.MaxNumberOfRecyclableJournals configuration option
  src/Raven.Server/Config/Categories/StorageConfiguration.cs
  src/Raven.Server/Documents/CompactDatabaseTask.cs
  src/Raven.Server/Documents/ConfigurationStorage.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Voron/StorageEnvironmentOptions.cs
  test/SlowTests/Voron/Issues/RavenDB_16860.cs
Labels: v4.2

#12413 RavenDB-16769
  src/Raven.Server/Documents/ETL/Providers/OLAP/OlapTransformedItems.cs
  src/Raven.Server/Documents/ETL/Providers/OLAP/OlaptEtl.cs
  src/Raven.Server/Documents/ETL/Providers/OLAP/ParquetTransformedItems.cs
  src/Raven.Server/Documents/ETL/Providers/OLAP/UploadInfo.cs
  src/Raven.Server/Documents/PeriodicBackup/BackupTask.cs
  src/Raven.Server/Documents/PeriodicBackup/BackupUploader.cs
  src/Raven.Server/Documents/PeriodicBackup/GoogleCloud/RavenGoogleCloudClient.cs
  test/SlowTests/Server/Documents/ETL/Olap/AzureTests.cs
Labels: v5.2

#12418 RavenDB-13053 - fix shard DataDir
  src/Raven.Server/ServerWide/RawDatabaseRecord.cs
Labels: Sharding

#12425 HRINT-2184 we need to clear the BlittableJsonReader state on init to avoid MaxDepth exception if previous runs were unsuccessful
  src/Raven.Client/Documents/Conventions/JsonNetBlittableEntitySerializer.cs
  src/Raven.Client/Json/BlittableJsonReader.cs
  src/Raven.Client/Json/ExpressionHelper.cs
  test/FastTests/Issues/HRINT_2184.cs
Labels: v4.2

#12430 RavenDB-16920 - Argument Null Exception when storing empty string
  src/Sparrow/Extensions/EncodingsExtensions.cs
  test/EmbeddedTests/TestDriver/TestDriverExampleTest.cs
Labels: v5.1

#12412 RavenDB-15906 Show single entry when the Client certificate used is …
  src/Raven.Studio/typescript/viewmodels/manage/certificates.ts
Labels: v5.1

#12435 5.1 to 5.2 merge
  src/Raven.Client/Documents/Operations/DatabaseStatistics.cs
  src/Raven.Client/Documents/Session/AbstractDocumentQuery.cs
  src/Raven.Client/Documents/Session/AsyncDocumentQuery.cs
  src/Raven.Client/Documents/Session/DocumentQuery.cs
  src/Raven.Client/Documents/Session/IDocumentQueryBase.cs
  src/Raven.Client/Json/ExpressionHelper.cs
  src/Raven.Client/Json/Serialization/NewtonsoftJson/Internal/BlittableJsonReader.cs
  src/Raven.Client/Json/Serialization/NewtonsoftJson/Internal/NewtonsoftJsonBlittableEntitySerializer.cs
  src/Raven.Server/Config/Categories/StorageConfiguration.cs
  src/Raven.Server/Documents/CompactDatabaseTask.cs
  src/Raven.Server/Documents/ConfigurationStorage.cs
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Handlers/BatchHandler.cs
  src/Raven.Server/Documents/Handlers/StatsHandler.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesStorage.cs
  src/Raven.Server/Documents/TombstoneCleaner.cs
  src/Raven.Server/Json/BlittableJsonTextWriterExtensions.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Studio/aceBuild/README.txt
  src/Raven.Studio/aceBuild/addons/lib/ace/mode/rql_worker.js
  src/Raven.Studio/typescript/models/database/tasks/ongoingTaskSubscriptionEditModel.ts
  src/Raven.Studio/typescript/viewmodels/manage/certificates.ts
  src/Raven.Studio/wwwroot/Content/ace/worker-rql.js
  src/Sparrow/Extensions/EncodingsExtensions.cs
  src/Sparrow/Threading/DisposeOnce.cs
  src/Voron/StorageEnvironmentOptions.cs
  test/EmbeddedTests/TestDriver/TestDriverExampleTest.cs
  test/FastTests/Client/Queries/QueryTests.cs
  test/FastTests/Issues/HRINT_2184.cs
  test/SlowTests/Server/Documents/TimeSeries/TimeSeriesTombstoneCleaner.cs
  test/SlowTests/Server/Replication/ReplicationCleanTombstones.cs
  test/SlowTests/Voron/Issues/RavenDB_16860.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
Labels: v5.2

#12434 RDBC-414 returning IOrderedEnumerable to expose ThenBy and ThenByDescending methods
  src/Raven.Server/Documents/Indexes/Static/Linq/DynamicEnumerable.cs
  test/SlowTests/Issues/RDBC_414.cs
Labels: v4.2

#12441 RavenDB-16918 Test subscription area is empty
  src/Raven.Studio/wwwroot/App/views/database/tasks/editSubscriptionTask.html
Labels: v5.2

#12439 RavenDB-16932 Migrate data from another server - Advanced menu
  src/Raven.Studio/typescript/models/database/tasks/migrateRavenDbDatabaseModel.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/migrateRavenDbDatabase.ts
  src/Raven.Studio/wwwroot/App/views/database/tasks/migrateRavenDbDatabase.html
Labels: v4.2

#12437 RavenDB-14759 support for cancellation tokens in TCP Client
  src/Raven.Client/Documents/Subscriptions/SubscriptionWorker.cs
  src/Raven.Client/Util/TcpUtils.cs
  src/Raven.Server/Documents/Handlers/Debugging/NodeDebugHandler.cs
  src/Raven.Server/Documents/Replication/OutgoingReplicationHandler.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/Rachis/RachisStateMachine.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterMaintenanceSupervisor.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Web/System/TestConnectionHandler.cs
  test/Tests.Infrastructure/RachisConsensusTestBase.cs
Labels: v5.1

#12436 RavenDB-14759
  src/Raven.Server/Documents/DatabaseInfoCache.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/RavenServer.cs
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
  test/Tests.Infrastructure/TestBase.cs
  test/Tests.Infrastructure/Utils/DebugHelper.cs
  test/Tryouts/Program.cs
Labels: v4.2

#12428 RavenDB-16924 add more info upon failure
  test/Tests.Infrastructure/RavenTestBase.cs
Labels: v4.2

#12443 4.2 to 5.1 merge
  src/Raven.Server/Documents/DatabaseInfoCache.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/RavenServer.cs
  src/Raven.Studio/typescript/models/database/tasks/migrateRavenDbDatabaseModel.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/migrateRavenDbDatabase.ts
  src/Raven.Studio/wwwroot/App/views/database/tasks/migrateRavenDbDatabase.html
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
  test/Tests.Infrastructure/RavenTestBase.cs
  test/Tests.Infrastructure/TestBase.cs
  test/Tests.Infrastructure/Utils/DebugHelper.cs
Labels: v5.1

#12444 5.1 to 5.2 merge
  src/Raven.Client/Documents/Subscriptions/SubscriptionWorker.cs
  src/Raven.Client/Util/TcpUtils.cs
  src/Raven.Server/Documents/DatabaseInfoCache.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/Handlers/Debugging/NodeDebugHandler.cs
  src/Raven.Server/Documents/Replication/OutgoingReplicationHandler.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/Rachis/RachisStateMachine.cs
  src/Raven.Server/RavenServer.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterMaintenanceSupervisor.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Web/System/TestConnectionHandler.cs
  src/Raven.Studio/typescript/models/database/tasks/migrateRavenDbDatabaseModel.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/migrateRavenDbDatabase.ts
  src/Raven.Studio/wwwroot/App/views/database/tasks/migrateRavenDbDatabase.html
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
  test/Tests.Infrastructure/RachisConsensusTestBase.cs
  test/Tests.Infrastructure/RavenTestBase.cs
  test/Tests.Infrastructure/TestBase.cs
  test/Tests.Infrastructure/Utils/DebugHelper.cs
Labels: v5.2

#12446 RavenDB-16906 : TimeSeriesFor - better error on null entity
  src/Raven.Client/Documents/Session/SessionTimeSeriesBase.cs
  test/SlowTests/Client/TimeSeries/Issues/RavenDB-16906.cs
Labels: v5.1

#12447 RDBS-2070 updated Lucene
  libs/Lucene.Net.3.0.52001.nupkg
  libs/Lucene.Net.3.0.52002.nupkg
  libs/Lucene.Net.Contrib.Spatial.NTS.3.0.52001.nupkg
  libs/Lucene.Net.Contrib.Spatial.NTS.3.0.52002.nupkg
  src/Raven.Server/Raven.Server.csproj
Labels: v5.2

#12448 RavenDB-16925 : Review tests for undisposed attachments
  test/SlowTests/Client/Attachments/AttachmentsStreamTests.cs
  test/SlowTests/Client/TimeSeries/BulkInsert/BulkInsert.cs
  test/SlowTests/Client/TimeSeries/BulkInsert/TypedBulkInsert.cs
  test/SlowTests/Issues/FilteredReplicationTests.cs
  test/SlowTests/Issues/RavenDB-12292.cs
  test/SlowTests/Issues/RavenDB-16724.cs
  test/SlowTests/Issues/RavenDB-8451.cs
  test/SlowTests/Issues/RavenDB_11171.cs
  test/SlowTests/Issues/RavenDB_14235.cs
  test/SlowTests/Issues/RavenDB_8773.cs
  test/SlowTests/Server/Documents/ETL/Raven/RavenDB_10308.cs
  test/SlowTests/Server/Documents/ETL/Raven/RavenDB_11379.cs
  test/SlowTests/Server/Documents/ETL/Raven/RavenDB_7064.cs
  test/SlowTests/Server/RecordingTransactionOperationsMergerTests.cs
  test/StressTests/Client/Attachments/AttachmentsStreamStress.cs
Labels: v5.2

#12450 RavenDB-16611 fix NRE of getting a token for a disposed database
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
Labels: v5.1

#12453 RavenDB-16872 fix NRE in WaitMoveToRehabGraceTime test
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
Labels: v4.2

#12457 RavenDB-16942 try to reuse segments when allocations are big
  src/Sparrow.Server/ByteString.cs
  test/FastTests/Issues/RavenDB_16942.cs
Labels: v4.2

#12459 5.1 to 5.2 merge
  src/Raven.Client/Documents/BulkInsert/BulkInsertOperation.cs
  src/Raven.Client/Documents/Session/SessionTimeSeriesBase.cs
  src/Raven.Server/Config/Categories/MonitoringConfiguration.cs
  src/Raven.Server/Documents/ExecuteRateLimitedOperations.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Queries/AbstractQueryRunner.cs
  src/Raven.Server/Documents/Queries/DocumentIdQueryResult.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
  src/Sparrow.Server/ByteString.cs
  test/FastTests/Issues/RavenDB_16942.cs
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
  test/SlowTests/Client/TimeSeries/Issues/RavenDB-16906.cs
  test/StressTests/Issues/RavenDB-16934.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v5.2
