Repository ravendb/ravendb, pull requests merged in 2021-04, with the labels that each got.

#11936 RavenDB-16438 removed LINQ
  src/Raven.Server/Config/RavenConfiguration.cs
Labels: v5.0

#11935 RavenDB-16437 support for RC releases
  src/Raven.Embedded/RuntimeFrameworkVersionMatcher.cs
  test/EmbeddedTests/RuntimeFrameworkVersionMatcherTests.cs
Labels: v4.2

#11937 RavenDB-16439
  src/Raven.Server/Documents/Queries/QueryBuilder.cs
  test/SlowTests/Issues/RavenDB_16439.cs
Labels: v5.1

#11940 4.2 to 5.0 merge
  .github/workflows/codeql-analysis.yml
  src/Raven.Client/Documents/Conventions/DocumentConventions.cs
  src/Raven.Client/Documents/Session/AbstractDocumentQuery.cs
  src/Raven.Client/Documents/Session/InMemoryDocumentSessionOperations.cs
  src/Raven.Embedded/EmbeddedServer.cs
  src/Raven.Embedded/ProcessHelper.cs
  src/Raven.Embedded/RavenServerRunner.cs
  src/Raven.Embedded/RuntimeFrameworkVersionMatcher.cs
  src/Raven.Server/Config/Categories/IndexingConfiguration.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Sparrow/Utils/FifoSemaphore.cs
  test/EmbeddedTests/BasicTests.cs
  test/EmbeddedTests/RuntimeFrameworkVersionMatcherTests.cs
  test/SlowTests/Issues/RavenDB_16412.cs
  test/SlowTests/Issues/RavenDB_16412_FifoSemaphoreTests.cs
Labels: v5.0

#11941 5.0 to 5.1 merge
  .github/workflows/codeql-analysis.yml
  src/Raven.Client/Documents/Conventions/DocumentConventions.cs
  src/Raven.Client/Documents/Session/AbstractDocumentQuery.cs
  src/Raven.Client/Documents/Session/InMemoryDocumentSessionOperations.cs
  src/Raven.Embedded/EmbeddedServer.cs
  src/Raven.Embedded/ProcessHelper.cs
  src/Raven.Embedded/RavenServerRunner.cs
  src/Raven.Embedded/RuntimeFrameworkVersionMatcher.cs
  src/Raven.Server/Config/Categories/IndexingConfiguration.cs
  src/Raven.Server/Config/RavenConfiguration.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Sparrow/Utils/FifoSemaphore.cs
  test/EmbeddedTests/BasicTests.cs
  test/EmbeddedTests/RuntimeFrameworkVersionMatcherTests.cs
  test/SlowTests/Issues/RavenDB_16412.cs
  test/SlowTests/Issues/RavenDB_16412_FifoSemaphoreTests.cs
Labels: v5.1

#11947 RavenDB-16362 Subscription stats graph - Fix connection start line po…
  src/Raven.Studio/typescript/viewmodels/database/status/ongoingTasksStats.ts
Labels: v5.2

#11948 RavenDB-16446
  src/Raven.Server/Indexing/TempFileCache.cs
  src/Raven.Server/Indexing/VoronIndexOutput.cs
Labels: v5.1

#11949 4.2 to 5.0 merge
  src/Raven.Server/Documents/CompactDatabaseTask.cs
  src/Raven.Server/Documents/ConfigurationStorage.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Handlers/Debugging/StorageHandler.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/NotificationCenter/Notifications/AlertType.cs
  src/Raven.Studio/typescript/models/auth/licenseModel.ts
  src/Raven.Studio/typescript/viewmodels/shell.ts
  src/Raven.Studio/wwwroot/App/views/shell.html
  src/Raven.Studio/wwwroot/Content/css/styles-common.less
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/RecoverableFailureEventArgs.cs
  src/Voron/StorageEnvironment.cs
  src/Voron/StorageEnvironmentOptions.cs
Labels: v5.0

#11926 RavenDB-16418 IAsyncDocumentSession.StreamAsync method forcedly cast …
  src/Raven.Client/Documents/Session/AbstractDocumentQuery.cs
  src/Raven.Client/Documents/Session/AsyncDocumentQuery.cs
  src/Raven.Client/Documents/Session/AsyncDocumentSession.Stream.cs
  src/Raven.Client/Documents/Session/DocumentQuery.cs
  src/Raven.Client/Documents/Session/DocumentSession.Stream.cs
  src/Raven.Client/Documents/Session/IAbstractDocumentQueryImpl.cs
Labels: v5.1

#11951 RavenDB-16412 Fixing ObjectDiposedException. We can dispose internal …
  src/Sparrow/Utils/FifoSemaphore.cs
  test/SlowTests/Issues/RavenDB_16412_FifoSemaphoreTests.cs
Labels: v4.2

#11952 4.2 to 5.0 merge
  src/Raven.Server/Indexing/LuceneVoronDirectory.cs
  src/Raven.Server/Indexing/TempFileCache.cs
  src/Raven.Server/Indexing/VoronIndexOutput.cs
  src/Raven.Server/ServerWide/TempCryptoStream.cs
  src/Sparrow/Utils/FifoSemaphore.cs
  test/SlowTests/Issues/RavenDB_15911.cs
  test/SlowTests/Issues/RavenDB_16412_FifoSemaphoreTests.cs
Labels: v5.0

#11953 5.0 to 5.1 merge
  src/Raven.Server/Documents/CompactDatabaseTask.cs
  src/Raven.Server/Documents/ConfigurationStorage.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Handlers/Debugging/StorageHandler.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/NotificationCenter/Notifications/AlertType.cs
  src/Raven.Server/ServerWide/TempCryptoStream.cs
  src/Raven.Studio/typescript/models/auth/licenseModel.ts
  src/Raven.Studio/typescript/viewmodels/shell.ts
  src/Raven.Studio/wwwroot/App/views/shell.html
  src/Raven.Studio/wwwroot/Content/css/styles-common.less
  src/Sparrow/Utils/FifoSemaphore.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/RecoverableFailureEventArgs.cs
  src/Voron/StorageEnvironment.cs
  src/Voron/StorageEnvironmentOptions.cs
  test/SlowTests/Issues/RavenDB_16412_FifoSemaphoreTests.cs
Labels: v5.1

#11955 5.1 to 5.2 merge
  src/Raven.Client/Documents/Session/AbstractDocumentQuery.cs
  src/Raven.Client/Documents/Session/AsyncDocumentQuery.cs
  src/Raven.Client/Documents/Session/AsyncDocumentSession.Stream.cs
  src/Raven.Client/Documents/Session/DocumentQuery.cs
  src/Raven.Client/Documents/Session/DocumentSession.Stream.cs
  src/Raven.Client/Documents/Session/IAbstractDocumentQueryImpl.cs
  src/Raven.Server/Documents/CompactDatabaseTask.cs
  src/Raven.Server/Documents/ConfigurationStorage.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Handlers/Debugging/StorageHandler.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Indexing/LuceneVoronDirectory.cs
  src/Raven.Server/Indexing/TempFileCache.cs
  src/Raven.Server/Indexing/VoronIndexOutput.cs
  src/Raven.Server/NotificationCenter/Notifications/AlertType.cs
  src/Raven.Server/ServerWide/TempCryptoStream.cs
  src/Raven.Studio/typescript/models/auth/licenseModel.ts
  src/Raven.Studio/typescript/viewmodels/shell.ts
  src/Raven.Studio/wwwroot/App/views/shell.html
  src/Raven.Studio/wwwroot/Content/css/styles-common.less
  src/Sparrow/Utils/FifoSemaphore.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/RecoverableFailureEventArgs.cs
  src/Voron/StorageEnvironment.cs
  src/Voron/StorageEnvironmentOptions.cs
  test/SlowTests/Issues/RavenDB_15911.cs
  test/SlowTests/Issues/RavenDB_16412_FifoSemaphoreTests.cs
Labels: v5.2

#11956 RavenDB-16379 Modify Studio theme when cloud instance is accessed by …
  src/Raven.Studio/wwwroot/App/views/shell.html
Labels: v5.1

#11958 RavenDB-16448 Wrong separator char in backup path
  src/Raven.Studio/typescript/models/database/tasks/periodicBackup/backupConfiguration.ts
  src/Raven.Studio/wwwroot/App/views/partial/backupDestinations.html
Labels: v5.1

#11963 4.2 to 5.0 merge
  src/Voron/Impl/Journal/JournalFile.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/Impl/Scratch/ScratchBufferFile.cs
  src/Voron/Impl/Scratch/ScratchBufferPool.cs
  src/Voron/Impl/Scratch/ScratchBufferPoolInfo.cs
  src/Voron/StorageEnvironment.cs
  test/FastTests/Voron/Bugs/RavenDB_16464.cs
  test/SlowTests/Voron/Bugs/InvalidReleasesOfScratchPages.cs
Labels: v5.0

#11965 5.0 to 5.1 merge
  src/Voron/Impl/Journal/JournalFile.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/Impl/Scratch/ScratchBufferFile.cs
  src/Voron/Impl/Scratch/ScratchBufferPool.cs
  src/Voron/Impl/Scratch/ScratchBufferPoolInfo.cs
  src/Voron/StorageEnvironment.cs
  test/FastTests/Voron/Bugs/RavenDB_16464.cs
  test/SlowTests/Voron/Bugs/InvalidReleasesOfScratchPages.cs
Labels: v5.1

#11966 5.1 to 5.2 merge
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
  src/Raven.Studio/typescript/models/database/tasks/periodicBackup/backupConfiguration.ts
  src/Raven.Studio/wwwroot/App/views/partial/backupDestinations.html
  src/Voron/Impl/Journal/JournalFile.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/Impl/Scratch/ScratchBufferFile.cs
  src/Voron/Impl/Scratch/ScratchBufferPool.cs
  src/Voron/Impl/Scratch/ScratchBufferPoolInfo.cs
  src/Voron/StorageEnvironment.cs
  test/FastTests/Voron/Bugs/RavenDB_16464.cs
  test/SlowTests/Voron/Bugs/InvalidReleasesOfScratchPages.cs
Labels: v5.2

#11968 RavenDB-7070 updated packages
  bench/Regression.Benchmark/Regression.Benchmark.csproj
  src/Raven.Client/Raven.Client.csproj
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Studio/Raven.Studio.csproj
  test/BenchmarkTests/BenchmarkTests.csproj
  test/EmbeddedTests/EmbeddedTests.csproj
  test/FastTests/FastTests.csproj
  test/InterversionTests/InterversionTests.csproj
  test/LicenseTests/LicenseTests.csproj
  test/RachisTests/RachisTests.csproj
  test/SlowTests/SlowTests.csproj
  test/StressTests/StressTests.csproj
  tools/Raven.Debug/Raven.Debug.csproj
  tools/Raven.Migrator/Raven.Migrator.csproj
Labels: v4.2

#11972 RavenDB-16464 Fixed missing exception in the log record
  src/Voron/Impl/Journal/WriteAheadJournal.cs
Labels: v4.2

#11973 RavenDB-16477 fixed tree rendering
  src/Raven.Server/Documents/Handlers/Debugging/StorageHandler.cs
  src/Voron/Debugging/DebugStuff.cs
Labels: v5.1

#11967 RavenDB-15749 refactoring
  src/Raven.Client/Documents/Indexes/Spatial/SpatialOptions.cs
  src/Raven.Server/Documents/Handlers/QueriesHandler.cs
  src/Raven.Server/Documents/Handlers/Streaming/StreamingHandler.cs
  src/Raven.Server/Documents/Indexes/Spatial/Circle.cs
  src/Raven.Server/Documents/Indexes/Spatial/Coordinates.cs
  src/Raven.Server/Documents/Indexes/Spatial/Polygon.cs
  src/Raven.Server/Documents/Indexes/Spatial/SpatialShapeBase.cs
  src/Raven.Server/Documents/Indexes/Spatial/SpatialShapeType.cs
  src/Raven.Server/Documents/Indexes/Static/Spatial/ShapeStringReadWriter.cs
  src/Raven.Server/Documents/Queries/IndexQueryServerSide.cs
  src/Raven.Server/Documents/Queries/QueryBuilder.cs
  src/Raven.Server/Documents/Queries/QueryMetadata.cs
  src/Raven.Server/Json/BlittableJsonTextWriterExtensions.cs
  src/Sparrow/Json/LazyNumberValue.cs
  test/SlowTests/Tests/Spatial/DynamicSpatialQueries.cs
  tools/TypingsGenerator/Program.cs
Labels: v5.2

#11976 RavenDB-13198 Revert Revisions Page - Small Fixes
  src/Raven.Studio/typescript/viewmodels/database/settings/revertRevisions.ts
  src/Raven.Studio/wwwroot/App/views/database/settings/revertRevisions.html
Labels: v5.2

#11910 RavenDB-16407 - Try clearing the scratch buffers when getting an OOME
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Voron/Impl/Scratch/ScratchBufferPool.cs
Labels: v4.2

#11978 RavenDB-16482 CopyFileStream errors should be logged at Operation level
  src/Raven.Server/Indexing/VoronIndexOutput.cs
Labels: v4.2

#11964 RavenDB-16428 Make sure that we never attempt to remove a scratch file that is our current one
  src/Voron/Impl/Scratch/ScratchBufferPool.cs
  test/SlowTests/Voron/RavenDB_16428.cs
Labels: v4.2

#11961 RavenDB-16454 better exception when we are trying to allocate more than 1GB
  src/Sparrow/Json/ArenaMemoryAllocator.cs
  src/Sparrow/Json/UnmanagedWriteBuffer.cs
Labels: v5.1

#11979 4.2 to 5.0 merge
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/PeriodicBackup/Azure/RavenAzureClient.cs
  src/Raven.Server/Documents/PeriodicBackup/Retention/AzureRetentionPolicyRunner.cs
  src/Raven.Server/Indexing/VoronIndexOutput.cs
  src/Voron/Impl/Scratch/ScratchBufferPool.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Azure.cs
  test/SlowTests/Server/Documents/PeriodicBackup/GoogleCloud.cs
  test/SlowTests/Server/Documents/PeriodicBackup/RavenDB-4613.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Restore/RestoreFromAzure.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Retention.cs
  test/SlowTests/Voron/RavenDB_16428.cs
  test/StressTests/Server/Documents/PeriodicBackup/RetentionStress.cs
  test/Tests.Infrastructure/AmazonS3FactAttribute.cs
  test/Tests.Infrastructure/AzureFactAttribute.cs
  test/Tests.Infrastructure/AzureSasTokenFactAttribute.cs
  test/Tests.Infrastructure/AzureStorageEmulatorFact.cs
  test/Tests.Infrastructure/AzureTheoryAttribute.cs
  test/Tests.Infrastructure/MultiTheoryAttribute .cs
  test/Tests.Infrastructure/NightlyBuildAzureFact.cs
Labels: v5.0

#11981 5.0 to 5.1 merge
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/PeriodicBackup/Azure/RavenAzureClient.cs
  src/Raven.Server/Documents/PeriodicBackup/Retention/AzureRetentionPolicyRunner.cs
  src/Raven.Server/Indexing/VoronIndexOutput.cs
  src/Voron/Impl/Scratch/ScratchBufferPool.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Azure.cs
  test/SlowTests/Server/Documents/PeriodicBackup/GoogleCloud.cs
  test/SlowTests/Server/Documents/PeriodicBackup/RavenDB-4613.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Restore/RestoreFromAzure.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Retention.cs
  test/SlowTests/Voron/RavenDB_16428.cs
  test/StressTests/Server/Documents/PeriodicBackup/RetentionStress.cs
  test/Tests.Infrastructure/AmazonS3FactAttribute.cs
  test/Tests.Infrastructure/AzureFactAttribute.cs
  test/Tests.Infrastructure/AzureSasTokenFactAttribute.cs
  test/Tests.Infrastructure/AzureStorageEmulatorFact.cs
  test/Tests.Infrastructure/AzureTheoryAttribute.cs
  test/Tests.Infrastructure/MultiTheoryAttribute .cs
  test/Tests.Infrastructure/NightlyBuildAzureFact.cs
Labels: v5.1

#11984 RavenDB-16343 Show list of indexes in pop-up dialogs
  src/Raven.Studio/typescript/viewmodels/database/indexes/bulkIndexOperationConfirm.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexes.ts
  src/Raven.Studio/wwwroot/App/views/database/indexes/bulkIndexOperationConfirm.html
Labels: v5.2

#11982 RavenDB-16474 Missing the copy button in Conflict Resolution syntax e…
  src/Raven.Studio/typescript/common/copyToClipboard.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/additionalAssemblySyntax.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/additionalSourceSyntax.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/mapIndexSyntax.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/mapReduceIndexSyntax.ts
  src/Raven.Studio/typescript/viewmodels/database/patch/patchSyntax.ts
  src/Raven.Studio/typescript/viewmodels/database/query/querySyntax.ts
  src/Raven.Studio/typescript/viewmodels/database/settings/conflictResolutionScriptSyntax.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/subscriptionRqlSyntax.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/transformationScriptSyntax.ts
  src/Raven.Studio/wwwroot/App/views/database/settings/conflictResolutionScriptSyntax.html
Labels: v5.2

#11980 RavenDB-16480 allow /databases/*/smuggler/validate-options when using Read certificate
  src/Raven.Server/Smuggler/Documents/Handlers/SmugglerHandler.cs
Labels: v5.2

#11985 RavenDB-16264 we cannot change values of static fields - it affects other tests
  src/Raven.Client/Documents/Operations/Backups/BackupSettings.cs
  test/Tests.Infrastructure/AzureFactAttribute.cs
  test/Tests.Infrastructure/AzureSasTokenFactAttribute.cs
  test/Tests.Infrastructure/AzureTheoryAttribute.cs
Labels: v4.2

#11986 5.1 to 5.2 merge
  src/Raven.Client/Documents/Operations/Backups/BackupSettings.cs
  src/Raven.Server/Documents/Handlers/Debugging/StorageHandler.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/Static/Linq/DynamicEnumerable.cs
  src/Raven.Server/Documents/Indexes/Static/Roslyn/Rewriters/DynamicInvocationExpressionsRewriter.cs
  src/Raven.Server/Documents/PeriodicBackup/Azure/RavenAzureClient.cs
  src/Raven.Server/Documents/PeriodicBackup/Retention/AzureRetentionPolicyRunner.cs
  src/Raven.Server/Indexing/VoronIndexOutput.cs
  src/Sparrow/Json/ArenaMemoryAllocator.cs
  src/Sparrow/Json/UnmanagedWriteBuffer.cs
  src/Voron/Debugging/DebugStuff.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/Impl/Scratch/ScratchBufferPool.cs
  test/SlowTests/Issues/RDBC_414.cs
  test/SlowTests/Issues/RavenDB_16451.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Azure.cs
  test/SlowTests/Server/Documents/PeriodicBackup/GoogleCloud.cs
  test/SlowTests/Server/Documents/PeriodicBackup/RavenDB-4613.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Restore/RestoreFromAzure.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Retention.cs
  test/SlowTests/Voron/RavenDB_16428.cs
  test/StressTests/Server/Documents/PeriodicBackup/RetentionStress.cs
  test/Tests.Infrastructure/AmazonS3FactAttribute.cs
  test/Tests.Infrastructure/AzureFactAttribute.cs
  test/Tests.Infrastructure/AzureSasTokenFactAttribute.cs
  test/Tests.Infrastructure/AzureStorageEmulatorFact.cs
  test/Tests.Infrastructure/AzureTheoryAttribute.cs
  test/Tests.Infrastructure/MultiTheoryAttribute .cs
  test/Tests.Infrastructure/NightlyBuildAzureFact.cs
Labels: v5.2

#11987 RavenDB-16489 New icons set
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.eot
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.json
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.svg
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.ttf
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.woff
  src/Raven.Studio/wwwroot/Content/css/icons.less
Labels: v5.2

#11988 RavenDB-16441 Create icons for Server-Wide Custom Analyzers & Sorters
  src/Raven.Studio/typescript/common/shell/menu/items/manageServer.ts
Labels: v5.2

#11989 RavenDB-16467
  src/Raven.Client/Documents/Indexes/IndexDefinition.cs
  src/Raven.Server/Documents/Indexes/Static/IndexCompiler.cs
  test/SlowTests/Issues/RavenDB_15753.cs
Labels: v5.1

#11990 RavenDB-16475 Document Refresh Frequency is not updated
  src/Raven.Studio/typescript/viewmodels/database/settings/expiration.ts
  src/Raven.Studio/typescript/viewmodels/database/settings/refresh.ts
Labels: v4.2

#11995 RavenDB-16502 Fixing missing start date of cloned transaction
  src/Raven.Server/Documents/Handlers/Debugging/TransactionDebugHandler.cs
  src/Voron/Impl/LowLevelTransaction.cs
Labels: v4.2

#11997 RavenDB-16196 Display the seconds in Traffic Watch
  src/Raven.Studio/typescript/common/generalUtils.ts
  src/Raven.Studio/typescript/viewmodels/manage/trafficWatch.ts
Labels: v4.2

#11996 RavenDB-16264: fix failing azure tests
  test/SlowTests/Server/Documents/PeriodicBackup/Azure.cs
  test/SlowTests/Server/Documents/PeriodicBackup/RavenDB-4613.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Restore/RestoreFromAzure.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Retention.cs
Labels: v4.2

#11993 RavenDB-15988 support for FindIndex and FindLastIndex in indexes
  src/Raven.Server/Documents/Indexes/Static/DynamicArray.cs
  src/Raven.Server/Documents/Indexes/Static/Roslyn/Rewriters/DynamicLambdaExpressionsRewriter.cs
  test/SlowTests/Issues/RavenDB_15988.cs
Labels: v5.1

#11992 RavenDB-16103 added Name and Type to MountPointUsage
  src/Raven.Client/ServerWide/Operations/DatabasesInfo.cs
  src/Raven.Server/ServerWide/ServerStore.cs
Labels: v5.1

#11994 RavenDB-16498 Match null string contact behavior during indexing
  src/Raven.Server/Documents/Indexes/Static/DynamicNullObject.cs
  test/SlowTests/Issues/RavenDB-16498.cs
Labels: v5.1

#12002 4.2 to 5.0 merge
  src/Raven.Server/Documents/Handlers/Debugging/TransactionDebugHandler.cs
  src/Raven.Studio/typescript/viewmodels/database/settings/expiration.ts
  src/Raven.Studio/typescript/viewmodels/database/settings/refresh.ts
  src/Raven.Studio/typescript/viewmodels/manage/trafficWatch.ts
  src/Voron/Impl/LowLevelTransaction.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Azure.cs
  test/SlowTests/Server/Documents/PeriodicBackup/RavenDB-4613.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Restore/RestoreFromAzure.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Retention.cs
Labels: v5.0

#12006 5.0 to 5.1 merge
  src/Raven.Server/Documents/Handlers/Debugging/TransactionDebugHandler.cs
  src/Raven.Studio/typescript/viewmodels/database/settings/expiration.ts
  src/Raven.Studio/typescript/viewmodels/database/settings/refresh.ts
  src/Raven.Studio/typescript/viewmodels/manage/trafficWatch.ts
  src/Voron/Impl/LowLevelTransaction.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Azure.cs
  test/SlowTests/Server/Documents/PeriodicBackup/RavenDB-4613.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Restore/RestoreFromAzure.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Retention.cs
Labels: v5.1

#12005 RavenDB-15556 Get info from logs to future investigation of the faili ng test
  test/SlowTests/SparrowTests/LoggingSourceTests.cs
Labels: v4.2

#12003 RavenDB-16505 Make default of Databases.PulseReadTransactionLimitInMb setting depending on amount of available memory
  src/Raven.Server/Config/Categories/DatabaseConfiguration.cs
  src/Raven.Server/Config/RavenConfiguration.cs
Labels: v4.2

#12007 RavenDB-16483: make sure the old task id is used for ValueChanges on …
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  test/SlowTests/Server/Documents/PeriodicBackup/ServerWideBackup.cs
Labels: v4.2

#12009 RavenDB-16264: fix failing azure tests 2
  test/SlowTests/Server/Documents/PeriodicBackup/Azure.cs
Labels: v4.2

#12010 RavenDB-16264: fix failing azure tests v5.1
  test/SlowTests/Server/Documents/PeriodicBackup/Restore/RestoreFromAzure.cs
Labels: v5.1

#12014 RavenDB-16512 JsonEnumerableConverter needs to take into account that the array contract might have a custom item converter
  src/Raven.Client/Json/Serialization/NewtonsoftJson/Internal/Converters/JsonEnumerableConverter.cs
  test/SlowTests/Issues/RavenDB_16512.cs
Labels: v5.1

#12015 RavenDB-16481 Clicking CREATE DATABASE few times makes QR code genera…
  src/Raven.Studio/typescript/viewmodels/resources/setupEncryptionKey.ts
Labels: v5.1

#11998 RavenDB-15868 Prevent multi put node info requests in node start
  src/Raven.Server/Commercial/LicenseManager.cs
  src/Raven.Server/Documents/PeriodicBackup/ConcurrentBackupsCounter.cs
Labels: v4.2

#12018 RavenDB-16270 - Create a new license attribute: monitoringEndpoints
  src/Raven.Server/Commercial/LicenseManager.cs
  src/Raven.Server/Commercial/LicenseValidator.cs
  src/Raven.Server/Web/System/AdminMonitoringHandler.cs
Labels: v5.2

#12017 RavenDB-16511 Fix index replacement
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  src/Raven.Server/Indexing/LuceneVoronDirectory.cs
  src/Raven.Server/Indexing/TempFileCache.cs
  test/SlowTests/Issues/RavenDB_16511.cs
Labels: v4.2

#12019 RavenDB-16516 dispose TcpConnectionOptions when doing TestConnection or Ping to avoid getting into CLOSE_WAIT state
  src/Raven.Client/Http/HttpCache.cs
  src/Raven.Server/Documents/TcpHandlers/TcpConnectionOptions.cs
  src/Raven.Server/RavenServer.cs
Labels: v4.2

#12028 RavenDB-16515 Bug in edit document page
  src/Raven.Studio/typescript/common/extensions.ts
Labels: v5.2

#12027 RavenDB-16518 database switch is broken
  src/Raven.Studio/typescript/common/abstractWebSocketClient.ts
Labels: v5.2

#12026 RavenDB-16361 Add help link for Customized Sorters & Customized Anal…
  src/Raven.Studio/typescript/viewmodels/database/settings/customAnalyzers.ts
  src/Raven.Studio/typescript/viewmodels/database/settings/customSorters.ts
  src/Raven.Studio/typescript/viewmodels/manage/serverWideCustomAnalyzers.ts
  src/Raven.Studio/typescript/viewmodels/manage/serverWideCustomSorters.ts
  src/Raven.Studio/wwwroot/App/views/database/settings/customAnalyzers.html
  src/Raven.Studio/wwwroot/App/views/database/settings/customSorters.html
  src/Raven.Studio/wwwroot/App/views/manage/serverWideCustomAnalyzers.html
  src/Raven.Studio/wwwroot/App/views/manage/serverWideCustomSorters.html
Labels: v5.2

#12031 RavenDB-16534 - fix attribute name Additional Assemblies from NuGet
  src/Raven.Studio/wwwroot/App/views/shell/about.html
Labels: v5.1

#12030 RavenDB-15749 Map view for Spatial queries - Fix
  src/Raven.Server/Documents/Indexes/Spatial/Polygon.cs
  src/Raven.Server/Documents/Queries/QueryMetadata.cs
  src/Raven.Studio/typescript/viewmodels/database/query/query.ts
Labels: v5.2

#12029 RavenDB-16519 If we cancel on attemt to get a lock from FifoSemaphore then we must not leave the waiter in the queue.
  src/Sparrow/Utils/FifoSemaphore.cs
  test/SlowTests/Issues/RavenDB_16412_FifoSemaphoreTests.cs
Labels: v4.2

#12035 RavenDB-16516 dispose TcpConnectionOptions when having a Cluster connection type
  src/Raven.Server/Documents/TcpHandlers/TcpConnectionOptions.cs
  src/Raven.Server/Rachis/Remote/RemoteConnection.cs
  src/Raven.Server/RavenServer.cs
Labels: v4.2

#12039 RavenDB-15325 Indexing section on Server dashboard is not clear
  src/Raven.Studio/wwwroot/App/views/resources/serverDashboard.html
Labels: v5.2

#12040 4.2 to 5.0 merge
  src/Raven.Server/Documents/TcpHandlers/TcpConnectionOptions.cs
  src/Raven.Server/Rachis/Remote/RemoteConnection.cs
  src/Raven.Server/RavenServer.cs
Labels: v5.0

#12051 RavenDB-16143 Indexing progress makes that selected items get unselected
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexes.ts
Labels: v5.0

#12050 RavenDB-16424 IO stats - unable to import stats from debug package
  src/Raven.Server/Utils/IoMetrics/LiveIOStatsCollector.cs
  src/Raven.Studio/typescript/models/database/status/ioStatsGraph.ts
Labels: v4.2

#12048 RavenDB-16568 Red selection (which stays) after navigating on databas…
  src/Raven.Studio/typescript/widgets/virtualGrid/virtualRow.ts
Labels: v5.2

#12047 RavenDB-16380 Fix rainbows in RavenDB Studio
  src/Raven.Studio/wwwroot/Content/css/icons.less
Labels: v5.2

#12045 RavenDB-16554 invalid tooltip container - custom fields tooltip
  src/Raven.Studio/typescript/viewmodels/partial/columnsSelector.ts
Labels: v5.2

#12044 RavenDB-16553 Cluster dashboard doesn't react to menu collapse
  src/Raven.Studio/typescript/common/constants/events.ts
  src/Raven.Studio/typescript/common/shell/menu.ts
  src/Raven.Studio/typescript/viewmodels/resources/clusterDashboard.ts
  src/Raven.Studio/typescript/viewmodels/resources/widgets/abstractChartsWebsocketWidget.ts
  src/Raven.Studio/typescript/viewmodels/resources/widgets/abstractDatabaseAndNodeAwareTableWidget.ts
  src/Raven.Studio/typescript/viewmodels/resources/widgets/widget.ts
Labels: v5.2

#12038 RavenDB-16538 Fixing unhandled error in DetermineServerIp kills the server with bad error:
  src/Raven.Server/Config/Categories/SecurityConfiguration.cs
  src/Raven.Server/Config/RavenConfiguration.cs
  src/Raven.Server/Utils/UnhandledExceptions.cs
Labels: v4.2

#12054 RavenDB-16546 Query results view - minors
  src/Raven.Studio/wwwroot/App/views/database/query/query.html
  src/Raven.Studio/wwwroot/Content/css/icons.less
  src/Raven.Studio/wwwroot/Content/css/pages/query.less
  src/Raven.Studio/wwwroot/Content/css/styles-common.less
Labels: v5.2

#12046 RavenDB-16565 Capture stack traces for entire cluster doesn't work
  src/Raven.Server/ServerWide/DebugInfoPackageUtils.cs
  src/Raven.Studio/typescript/commands/maintenance/captureClusterStackTracesCommand.ts
Labels: v4.2

#12055 4.2 to 5.0 merge
  src/Raven.Server/Config/Categories/SecurityConfiguration.cs
  src/Raven.Server/Config/RavenConfiguration.cs
  src/Raven.Server/NotificationCenter/NotificationCenter.cs
  src/Raven.Server/NotificationCenter/Notifications/AlertType.cs
  src/Raven.Server/NotificationCenter/NotificationsStorage.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/DebugInfoPackageUtils.cs
  src/Raven.Server/Utils/IoMetrics/LiveIOStatsCollector.cs
  src/Raven.Server/Utils/UnhandledExceptions.cs
  src/Raven.Studio/typescript/commands/maintenance/captureClusterStackTracesCommand.ts
  src/Raven.Studio/typescript/models/database/status/ioStatsGraph.ts
  test/SlowTests/Client/ClientConfigurationTests.cs
  test/SlowTests/Server/Documents/PeriodicBackup/ServerWideBackup.cs
Labels: v5.0

#12056 5.0 to 5.1 merge
  src/Raven.Server/Config/Categories/SecurityConfiguration.cs
  src/Raven.Server/Config/RavenConfiguration.cs
  src/Raven.Server/NotificationCenter/NotificationCenter.cs
  src/Raven.Server/NotificationCenter/Notifications/AlertType.cs
  src/Raven.Server/NotificationCenter/NotificationsStorage.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/DebugInfoPackageUtils.cs
  src/Raven.Server/Utils/IoMetrics/LiveIOStatsCollector.cs
  src/Raven.Server/Utils/UnhandledExceptions.cs
  src/Raven.Studio/typescript/commands/maintenance/captureClusterStackTracesCommand.ts
  src/Raven.Studio/typescript/models/database/status/ioStatsGraph.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexes.ts
  test/SlowTests/Client/ClientConfigurationTests.cs
  test/SlowTests/Server/Documents/PeriodicBackup/ServerWideBackup.cs
Labels: v5.1

#12057 5.1 to 5.2 merge
  src/Raven.Server/Config/Categories/SecurityConfiguration.cs
  src/Raven.Server/Config/RavenConfiguration.cs
  src/Raven.Server/Documents/Indexes/Static/IndexCompiler.cs
  src/Raven.Server/Documents/Indexes/Static/NuGet/MultiSourceNuGetFetcher.cs
  src/Raven.Server/Documents/Indexes/Static/NuGet/NuGetFetcher.cs
  src/Raven.Server/Documents/Indexes/Static/NuGet/NuGetNativeLibraryResolver.cs
  src/Raven.Server/NotificationCenter/NotificationCenter.cs
  src/Raven.Server/NotificationCenter/Notifications/AlertType.cs
  src/Raven.Server/NotificationCenter/NotificationsStorage.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/DebugInfoPackageUtils.cs
  src/Raven.Server/Utils/IoMetrics/LiveIOStatsCollector.cs
  src/Raven.Server/Utils/UnhandledExceptions.cs
  src/Raven.Studio/typescript/commands/maintenance/captureClusterStackTracesCommand.ts
  src/Raven.Studio/typescript/models/database/status/ioStatsGraph.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexes.ts
  test/SlowTests/Client/ClientConfigurationTests.cs
  test/SlowTests/Data/RavenDB_15753/cat.jpg
  test/SlowTests/Issues/RavenDB_15753.cs
  test/SlowTests/Server/Documents/PeriodicBackup/ServerWideBackup.cs
  test/SlowTests/SlowTests.csproj
Labels: v5.2

#12058 RavenDB-16322 Warning triangle is out of place
  src/Raven.Studio/wwwroot/Content/css/pages/dashboard.less
Labels: v5.1

#12060 RavenDB-15747 build cross-platform deb on Linux with QEMU
  scripts/linux/pkg/deb/assets/build.sh
  scripts/linux/pkg/deb/build-deb.ps1
  scripts/linux/pkg/deb/build-deb.sh
  scripts/linux/pkg/deb/build-deb_ubuntu-bionic_amd64.ps1
  scripts/linux/pkg/deb/build-deb_ubuntu-bionic_armhf.ps1
  scripts/linux/pkg/deb/build-deb_ubuntu-bionic_armhf.sh
  scripts/linux/pkg/deb/build-deb_ubuntu-focal_amd64.ps1
  scripts/linux/pkg/deb/check_docker_cross.sh
  scripts/linux/pkg/deb/set-raven-platform-amd64.ps1
  scripts/linux/pkg/deb/set-raven-platform-armhf.ps1
  scripts/linux/pkg/deb/set-raven-platform-armhf.sh
  scripts/linux/pkg/deb/set-raven-version-env.ps1
  scripts/linux/pkg/deb/set-raven-version-env.sh
  scripts/linux/pkg/deb/test-deb-docker_ubuntu-bionic_amd64.ps1
  scripts/linux/pkg/deb/test-deb-docker_ubuntu-bionic_armhf.ps1
  scripts/linux/pkg/deb/test-deb-docker_ubuntu-focal_amd64.ps1
  scripts/linux/pkg/deb/test-deb-vagrant_ubuntu-bionic.ps1
  scripts/linux/pkg/deb/test-deb-vagrant_ubuntu-focal.ps1
  scripts/linux/pkg/deb/ubuntu_amd64.Dockerfile
  scripts/linux/pkg/deb/ubuntu_multiarch.Dockerfile
Labels: v4.2

#12064 RavenDB-16601 - fix missing Read-Only certificates property in the studio
  src/Raven.Server/Commercial/LicenseStatus.cs
Labels: v5.2

#12065 RavenDB-16600 Wrong size unit used in AdminMonitoringHandler.GetDiskM…
  src/Raven.Server/Web/System/AdminMonitoringHandler.cs
Labels: v5.2

#12063 RavenDB-16555 Missing QR code when opening encrypt backup section sec…
  src/Raven.Studio/typescript/viewmodels/resources/setupEncryptionKey.ts
Labels: v5.1

#12068 RavenDB-16602 Document Properties Panel: Titles for Additional Items
  src/Raven.Studio/wwwroot/App/views/database/documents/editDocument.html
  src/Raven.Studio/wwwroot/Content/css/pages/documents-edit.less
Labels: v5.2

#12070 RavenDB-16606 Longer node tags in cluster dashboard
  src/Raven.Studio/wwwroot/Content/css/pages/cluster-dashboard.less
Labels: v5.2

#12071 4.2 to 5.0 merge
  scripts/linux/pkg/deb/assets/build.sh
  scripts/linux/pkg/deb/build-deb.ps1
  scripts/linux/pkg/deb/build-deb.sh
  scripts/linux/pkg/deb/build-deb_ubuntu-bionic_amd64.ps1
  scripts/linux/pkg/deb/build-deb_ubuntu-bionic_armhf.ps1
  scripts/linux/pkg/deb/build-deb_ubuntu-bionic_armhf.sh
  scripts/linux/pkg/deb/build-deb_ubuntu-focal_amd64.ps1
  scripts/linux/pkg/deb/check_docker_cross.sh
  scripts/linux/pkg/deb/set-raven-platform-amd64.ps1
  scripts/linux/pkg/deb/set-raven-platform-armhf.ps1
  scripts/linux/pkg/deb/set-raven-platform-armhf.sh
  scripts/linux/pkg/deb/set-raven-version-env.ps1
  scripts/linux/pkg/deb/set-raven-version-env.sh
  scripts/linux/pkg/deb/test-deb-docker_ubuntu-bionic_amd64.ps1
  scripts/linux/pkg/deb/test-deb-docker_ubuntu-bionic_armhf.ps1
  scripts/linux/pkg/deb/test-deb-docker_ubuntu-focal_amd64.ps1
  scripts/linux/pkg/deb/test-deb-vagrant_ubuntu-bionic.ps1
  scripts/linux/pkg/deb/test-deb-vagrant_ubuntu-focal.ps1
  scripts/linux/pkg/deb/ubuntu_amd64.Dockerfile
  scripts/linux/pkg/deb/ubuntu_multiarch.Dockerfile
  src/Raven.Client/Documents/Indexes/IndexingOperation.cs
  src/Raven.Client/Exceptions/Documents/DocumentCollectionMismatchException.cs
  src/Raven.Server/Documents/Document.cs
  src/Raven.Server/Documents/DocumentPutAction.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Smuggler/Documents/Data/ISmugglerDestination.cs
  src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
  src/Raven.Server/Smuggler/Documents/DatabaseSmuggler.cs
  src/Raven.Server/Smuggler/Documents/StreamDestination.cs
  src/Raven.Studio/typescript/common/liveIndexPerformanceWebSocketClient.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexPerformance.ts
  src/Raven.Studio/typings/_studio/dto.d.ts
  src/Raven.Studio/wwwroot/App/views/database/indexes/indexPerformance.html
  src/Raven.Studio/wwwroot/Content/css/pages/index-performance.less
  test/SlowTests/Server/Documents/ModifyExistingDocument.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
Labels: v5.0

#12072 RavenDB-16578 AggregateBy should use IEnumerable<FacetBase> instead of IEnumerable<Facet>
  src/Raven.Client/Documents/Session/AsyncDocumentQuery.Facets.cs
  src/Raven.Client/Documents/Session/DocumentQuery.Facets.cs
  src/Raven.Client/Documents/Session/IAsyncDocumentQuery.cs
  src/Raven.Client/Documents/Session/IDocumentQuery.cs
  test/SlowTests/Issues/RavenDB_1466.cs
Labels: v5.2

#12074 5.0 to 5.1 merge
  src/Raven.Client/Documents/Indexes/IndexingOperation.cs
  src/Raven.Client/Exceptions/Documents/DocumentCollectionMismatchException.cs
  src/Raven.Server/Documents/Document.cs
  src/Raven.Server/Documents/DocumentPutAction.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Smuggler/Documents/Data/ISmugglerDestination.cs
  src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
  src/Raven.Server/Smuggler/Documents/DatabaseSmuggler.cs
  src/Raven.Server/Smuggler/Documents/StreamDestination.cs
  src/Raven.Studio/typescript/common/liveIndexPerformanceWebSocketClient.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexPerformance.ts
  src/Raven.Studio/typings/_studio/dto.d.ts
  src/Raven.Studio/wwwroot/App/views/database/indexes/indexPerformance.html
  src/Raven.Studio/wwwroot/Content/css/pages/index-performance.less
  test/SlowTests/Server/Documents/ModifyExistingDocument.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
Labels: v5.1

#12073 RavenDB-16590 marking overridable by index configurations with ServerWideOrPerDatabaseOrPerIndex so Studio can properly filter by them in edit index configuration view
  src/Raven.Server/Config/Attributes/ConfigurationEntryAttribute.cs
  src/Raven.Server/Config/Categories/IndexingConfiguration.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Web/System/DatabaseHelper.cs
Labels: v5.2

#12075 5.1 to 5.2 merge
  scripts/linux/pkg/deb/assets/build.sh
  scripts/linux/pkg/deb/build-deb.ps1
  scripts/linux/pkg/deb/build-deb.sh
  scripts/linux/pkg/deb/build-deb_ubuntu-bionic_armhf.sh
  scripts/linux/pkg/deb/check_docker_cross.sh
  scripts/linux/pkg/deb/set-raven-platform-amd64.ps1
  scripts/linux/pkg/deb/set-raven-platform-arm64.ps1
  scripts/linux/pkg/deb/set-raven-platform-arm64.sh
  scripts/linux/pkg/deb/set-raven-platform-armhf.ps1
  scripts/linux/pkg/deb/set-raven-platform-armhf.sh
  scripts/linux/pkg/deb/set-raven-version-env.ps1
  scripts/linux/pkg/deb/set-raven-version-env.sh
  scripts/linux/pkg/deb/ubuntu_amd64.Dockerfile
  scripts/linux/pkg/deb/ubuntu_multiarch.Dockerfile
  src/Raven.Client/Documents/Indexes/IndexingOperation.cs
  src/Raven.Client/Exceptions/Documents/DocumentCollectionMismatchException.cs
  src/Raven.Server/Documents/Document.cs
  src/Raven.Server/Documents/DocumentPutAction.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Smuggler/Documents/Data/ISmugglerDestination.cs
  src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
  src/Raven.Server/Smuggler/Documents/DatabaseSmuggler.cs
  src/Raven.Server/Smuggler/Documents/StreamDestination.cs
  src/Raven.Studio/typescript/common/liveIndexPerformanceWebSocketClient.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexPerformance.ts
  src/Raven.Studio/typescript/viewmodels/resources/setupEncryptionKey.ts
  src/Raven.Studio/typings/_studio/dto.d.ts
  src/Raven.Studio/wwwroot/App/views/database/indexes/indexPerformance.html
  src/Raven.Studio/wwwroot/Content/css/pages/dashboard.less
  src/Raven.Studio/wwwroot/Content/css/pages/index-performance.less
  test/SlowTests/Server/Documents/ModifyExistingDocument.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
Labels: v5.2

#12078 RavenDB-16603 Use pointer events none on tooltip in performance views
  src/Raven.Studio/typescript/models/database/status/ioStatsGraph.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexPerformance.ts
  src/Raven.Studio/typescript/viewmodels/database/status/ongoingTasksStats.ts
Labels: v4.2

#12080 RavenDB-16585 deleting node from database group vs lock mode
  src/Raven.Studio/typescript/viewmodels/resources/manageDatabaseGroup.ts
  src/Raven.Studio/wwwroot/App/views/resources/manageDatabaseGroup.html
Labels: v5.2

#12076 RavenDB-16588 moved NumberOfConcurrentSyncsPerPhysicalDrive to GlobalFlushingBehavior static field
  src/Raven.Server/Config/Categories/StorageConfiguration.cs
  src/Raven.Server/Documents/CompactDatabaseTask.cs
  src/Raven.Server/Documents/ConfigurationStorage.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Program.cs
  src/Voron/GlobalFlushingBehavior.cs
  src/Voron/StorageEnvironment.cs
  src/Voron/StorageEnvironmentOptions.cs
Labels: v5.2

#12079 RavenDB-16581 On index editing screen duplicate name exception should…
  src/Raven.Studio/typescript/models/database/index/indexDefinition.ts
Labels: v4.2

#12083 RavenDB-16587 hide lock buttons for autoindexes
  src/Raven.Studio/wwwroot/App/views/database/indexes/indexes.html
Labels: v4.2

#12077 RavenDB-16590 filter index configuration based on scope
  src/Raven.Studio/typescript/models/database/index/configurationItem.ts
  test/FastTests/Issues/RavenDB_16590.cs
Labels: v5.2

#12082 RavenDB-16547 better formatting of time series values
  src/Raven.Studio/typescript/viewmodels/database/query/query.ts
Labels: v5.2

#12081 RavenDB-16579 cluster dashboard - button for hiding welcome widget + …
  src/Raven.Studio/typescript/viewmodels/resources/clusterDashboard.ts
  src/Raven.Studio/wwwroot/App/views/resources/widgets/welcomeWidget.html
Labels: v5.2
