Repository ravendb/ravendb, pull requests merged in 2021-02, with the labels that each got.

#11715 RavenDB-16178: fix test
  test/RachisTests/SubscriptionFailoverWIthWaitingChains.cs
  test/RachisTests/SubscriptionsFailover.cs
Labels: v4.2

#11723 4.2 to 5.0 merge
  libs/Lucene.Net.3.0.41.nupkg
  libs/Lucene.Net.3.0.42.nupkg
  libs/Lucene.Net.Contrib.Spatial.NTS.3.0.17.nupkg
  libs/Lucene.Net.Contrib.Spatial.NTS.3.0.42.nupkg
  src/Raven.Server/Documents/Handlers/QueriesHandler.cs
  src/Raven.Server/Raven.Server.csproj
  test/RachisTests/SubscriptionFailoverWIthWaitingChains.cs
  test/RachisTests/SubscriptionsFailover.cs
  test/SlowTests/Issues/RavenDB-10046.cs
Labels: v5.0

#11725 5.0 to 5.1 merge
  libs/Lucene.Net.3.0.41.nupkg
  libs/Lucene.Net.3.0.42.nupkg
  libs/Lucene.Net.Contrib.Spatial.NTS.3.0.17.nupkg
  libs/Lucene.Net.Contrib.Spatial.NTS.3.0.42.nupkg
  src/Raven.Server/Documents/Handlers/QueriesHandler.cs
  src/Raven.Server/Raven.Server.csproj
  test/RachisTests/SubscriptionFailoverWIthWaitingChains.cs
  test/RachisTests/SubscriptionsFailover.cs
  test/SlowTests/Issues/RavenDB-10046.cs
Labels: v5.1

#11724 RavenDB-16028: fix can_backup_and_restore_with_timeseries test
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
Labels: v5.1

#11735 RavenDB-16145 when collection does not match in LoadDocument return null
  src/Raven.Server/Documents/Indexes/Static/CurrentIndexingScope.cs
  test/SlowTests/Issues/RavenDB_16145.cs
Labels: v5.1

#11733 RavenDB-15556 LoggingSource_WhileRetentionBySizeOn_ShouldKeepRetentionPolicy more information for future investigation
  test/SlowTests/SparrowTests/LoggingSourceTests.cs
Labels: v4.2

#11732 RavenDB-16191 - Azure backup retention policy isn't working when the remote folder name is null
  src/Raven.Server/Documents/PeriodicBackup/Retention/AzureRetentionPolicyRunner.cs
Labels: v4.2

#11731 RavenDB-15573: normalize the exception message
  src/Raven.Server/Documents/Subscriptions/SubscriptionStorage.cs
Labels: v5.0

#11730 RavenDB-16028: fix can_backup_and_restore_with_timeseries test 5.0
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
Labels: v5.0

#11729 RavenDB-16188 Fixing ocassionally failing test. We might get VoronUnr…
  test/SlowTests/Issues/RavenDB_6414.cs
Labels: v4.2

#11727 RavenDB-14748 Race condition in the test fixed and asserts changed to be more specific specific
  test/SlowTests/Issues/RavenDB_10637.cs
Labels: v4.2

#11705 RavenDB-15905 Using aggressively cache when load lazily
  src/Raven.Client/Documents/Commands/MultiGet/MultiGetCommand.cs
  src/Raven.Client/Documents/Session/AsyncDocumentSession.Lazy.cs
  src/Raven.Client/Documents/Session/DocumentSession.cs
  test/SlowTests/Bugs/Caching/UseCachingInLazyTests.cs
Labels: v5.0

#11737 4.2 to 5.0 merge
  src/Raven.Server/Documents/PeriodicBackup/BackupTask.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
  src/Raven.Server/Documents/PeriodicBackup/Retention/AzureRetentionPolicyRunner.cs
  test/SlowTests/Issues/RavenDB_10637.cs
  test/SlowTests/Issues/RavenDB_6414.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
  test/SlowTests/SparrowTests/LoggingSourceTests.cs
Labels: v5.0

#11742 5.0 to 5.1 merge
  libs/Lucene.Net.3.0.39.nupkg
  src/Raven.Client/Documents/Commands/MultiGet/MultiGetCommand.cs
  src/Raven.Client/Documents/Session/AsyncDocumentSession.Lazy.cs
  src/Raven.Client/Documents/Session/DocumentSession.cs
  src/Raven.Server/Documents/PeriodicBackup/BackupTask.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
  src/Raven.Server/Documents/PeriodicBackup/Retention/AzureRetentionPolicyRunner.cs
  src/Raven.Server/Documents/Subscriptions/SubscriptionStorage.cs
  src/Raven.Server/Web/System/OngoingTasksHandler.cs
  test/SlowTests/Bugs/Caching/UseCachingInLazyTests.cs
  test/SlowTests/Issues/RavenDB_10637.cs
  test/SlowTests/Issues/RavenDB_6414.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
  test/SlowTests/SparrowTests/LoggingSourceTests.cs
Labels: v5.1

#11739 RavenDB-15771 Use session.Advanced.NumberOfRequests instead of reques tExecutor.NumberOfServerRequests to prevent periodic request fail the test
  test/SlowTests/MailingList/AggresiveCacheWithLazy.cs
Labels: v5.0

#11738 RavenDB-16132 Use session.Advanced.NumberOfRequests instead of reques tExecutor.NumberOfServerRequests to prevent periodic request fail the test
  test/SlowTests/MailingList/AggresiveCacheWithLazy.cs
Labels: v5.0

#11736 RavenDB-16170: Use ConcurrentQueue in SmugglerResult
  src/Raven.Client/Documents/Smuggler/SmugglerResult.cs
  src/Raven.Server/Documents/PeriodicBackup/BackupTask.cs
  src/Raven.Server/Documents/PeriodicBackup/BackupUploader.cs
Labels: v4.2

#11746 RavenDB-15929 ThreadUsage consider two thread with same CpuUsage and TotalProcessorTime as the same one fixed
  src/Raven.Server/Dashboard/ThreadsInfo.cs
  test/FastTests/Server/ThreadUsageTests.cs
Labels: v4.2

#11691 RavenDB-15745 spatial performance optimizations
  libs/Lucene.Net.3.0.52000.nupkg
  libs/Lucene.Net.Contrib.Spatial.NTS.3.0.52000.nupkg
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/IndexReadOperation.cs
  src/Raven.Server/Documents/Indexes/Static/Spatial/BBoxStrategyThatSupportsAllShapes.cs
  src/Raven.Server/Documents/Indexes/Static/Spatial/ShapeStringReadWriter.cs
  src/Raven.Server/Documents/Indexes/Static/Spatial/SpatialDistanceFieldComparatorSource.cs
  src/Raven.Server/Documents/Indexes/Static/Spatial/SpatialField.cs
  src/Raven.Server/Documents/Indexes/Static/StaticIndexBase.cs
  src/Raven.Server/Documents/Queries/QueryBuilder.cs
  src/Raven.Server/Raven.Server.csproj
Labels: v5.2

#11753 RavenDB-16217 fixed deserialization issue
  src/Raven.Client/Documents/Smuggler/SmugglerResult.cs
Labels: v4.2

#11756 4.2 to 5.0 merge
  .github/workflows/FastTests.yml
  bench/BulkInsert.Benchmark/BulkInsert.Benchmark.csproj
  bench/Indexing.Benchmark/Indexing.Benchmark.csproj
  bench/Micro.Benchmark/Micro.Benchmark.csproj
  bench/Regression.Benchmark/Regression.Benchmark.csproj
  bench/SubscriptionFailover.Benchmark/SubscriptionFailover.Benchmark.csproj
  bench/Subscriptions.Benchmark/Subscriptions.Benchmark.csproj
  bench/Voron.Benchmark/Voron.Benchmark.csproj
  src/Raven.Client/Documents/Smuggler/SmugglerResult.cs
  src/Raven.Embedded/ServerOptions.cs
  src/Raven.Server/Dashboard/ThreadsInfo.cs
  src/Raven.Server/Documents/DocumentPutAction.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/IndexStorage.cs
  src/Raven.Server/Documents/Indexes/IndexingRunStats.cs
  src/Raven.Server/Documents/Indexes/IndexingStatsAggregator.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/IndexWriteOperation.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/LuceneIndexPersistence.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/LuceneIndexWriter.cs
  src/Raven.Server/Documents/PeriodicBackup/BackupTask.cs
  src/Raven.Server/Documents/PeriodicBackup/BackupUploader.cs
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Studio/Raven.Studio.csproj
  test/BenchmarkTests/BenchmarkTests.csproj
  test/EmbeddedTests/EmbeddedTests.csproj
  test/FastTests/FastTests.csproj
  test/FastTests/Server/ThreadUsageTests.cs
  test/InterversionTests/InterversionTests.csproj
  test/LicenseTests/LicenseTests.csproj
  test/RachisTests/RachisTests.csproj
  test/SlowTests/Issues/RavenDB-15898.cs
  test/SlowTests/Issues/RavenDB-4222.cs
  test/SlowTests/Issues/RavenDB-4446.cs
  test/SlowTests/Issues/RavenDB_16193.cs
  test/SlowTests/SlowTests.csproj
  test/StressTests/StressTests.csproj
  test/Tests.Infrastructure/RavenTestBase.cs
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
  test/Tryouts/Tryouts.csproj
  tools/Raven.Debug/Raven.Debug.csproj
  tools/Raven.Migrator/Raven.Migrator.csproj
  tools/TypingsGenerator/TypingsGenerator.csproj
  tools/Voron.Recovery/Voron.Recovery.csproj
  tools/rvn/rvn.csproj
Labels: v5.0

#11755 RavenDB-16229 - Memory leak when patching a large collection
  src/Raven.Server/Documents/CollectionRunner.cs
Labels: v5.0

#11750 RavenDB-16223 Fix icon files conflict
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.eot
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.svg
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.ttf
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.woff
  src/Raven.Studio/wwwroot/Content/css/icons.less
Labels: v5.2

#11757 5.0 to 5.1 merge
  .github/workflows/FastTests.yml
  bench/BulkInsert.Benchmark/BulkInsert.Benchmark.csproj
  bench/Indexing.Benchmark/Indexing.Benchmark.csproj
  bench/Micro.Benchmark/Micro.Benchmark.csproj
  bench/Regression.Benchmark/Regression.Benchmark.csproj
  bench/SubscriptionFailover.Benchmark/SubscriptionFailover.Benchmark.csproj
  bench/Subscriptions.Benchmark/Subscriptions.Benchmark.csproj
  bench/TimeSeries.Benchmark/TimeSeries.Benchmark.csproj
  bench/Voron.Benchmark/Voron.Benchmark.csproj
  src/Raven.Client/Documents/Smuggler/SmugglerResult.cs
  src/Raven.Client/Raven.Client.csproj
  src/Raven.Embedded/ServerOptions.cs
  src/Raven.Server/Dashboard/ThreadsInfo.cs
  src/Raven.Server/Documents/DocumentPutAction.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/IndexStorage.cs
  src/Raven.Server/Documents/Indexes/IndexingRunStats.cs
  src/Raven.Server/Documents/Indexes/IndexingStatsAggregator.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/IndexWriteOperation.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/LuceneIndexPersistence.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/LuceneIndexWriter.cs
  src/Raven.Server/Documents/PeriodicBackup/BackupTask.cs
  src/Raven.Server/Documents/PeriodicBackup/BackupUploader.cs
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Studio/Raven.Studio.csproj
  src/Sparrow.Server/Sparrow.Server.csproj
  src/Voron/Voron.csproj
  test/BenchmarkTests/BenchmarkTests.csproj
  test/EmbeddedTests/EmbeddedTests.csproj
  test/FastTests/FastTests.csproj
  test/FastTests/Server/ThreadUsageTests.cs
  test/InterversionTests/InterversionTests.csproj
  test/LicenseTests/LicenseTests.csproj
  test/RachisTests/RachisTests.csproj
  test/SlowTests/Issues/RavenDB-15898.cs
  test/SlowTests/Issues/RavenDB-4222.cs
  test/SlowTests/Issues/RavenDB-4446.cs
  test/SlowTests/Issues/RavenDB_16193.cs
  test/SlowTests/MailingList/AggresiveCacheWithLazy.cs
  test/SlowTests/SlowTests.csproj
  test/StressTests/StressTests.csproj
  test/Studio/Studio.csproj
  test/Tests.Infrastructure/RavenTestBase.cs
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
  test/Tryouts/Tryouts.csproj
  tools/Raven.Debug/Raven.Debug.csproj
  tools/Raven.Migrator/Raven.Migrator.csproj
  tools/TypingsGenerator/TypingsGenerator.csproj
  tools/Voron.Recovery/Voron.Recovery.csproj
  tools/rvn/rvn.csproj
Labels: v5.1

#11759 5.1 to 5.2 merge
  .github/workflows/FastTests.yml
  SECURITY.md
  bench/BulkInsert.Benchmark/BulkInsert.Benchmark.csproj
  bench/Indexing.Benchmark/Indexing.Benchmark.csproj
  bench/Micro.Benchmark/Micro.Benchmark.csproj
  bench/Regression.Benchmark/Regression.Benchmark.csproj
  bench/SubscriptionFailover.Benchmark/SubscriptionFailover.Benchmark.csproj
  bench/Subscriptions.Benchmark/Subscriptions.Benchmark.csproj
  bench/TimeSeries.Benchmark/TimeSeries.Benchmark.csproj
  bench/Voron.Benchmark/Voron.Benchmark.csproj
  src/Raven.Client/Documents/Smuggler/SmugglerResult.cs
  src/Raven.Client/Raven.Client.csproj
  src/Raven.Embedded/ServerOptions.cs
  src/Raven.Server/Dashboard/ThreadsInfo.cs
  src/Raven.Server/Documents/DocumentPutAction.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/IndexStorage.cs
  src/Raven.Server/Documents/Indexes/IndexingRunStats.cs
  src/Raven.Server/Documents/Indexes/IndexingStatsAggregator.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/IndexWriteOperation.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/LuceneIndexPersistence.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/LuceneIndexWriter.cs
  src/Raven.Server/Documents/PeriodicBackup/BackupTask.cs
  src/Raven.Server/Documents/PeriodicBackup/BackupUploader.cs
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Studio/Raven.Studio.csproj
  src/Sparrow.Server/Sparrow.Server.csproj
  src/Voron/Voron.csproj
  test/BenchmarkTests/BenchmarkTests.csproj
  test/EmbeddedTests/EmbeddedTests.csproj
  test/FastTests/FastTests.csproj
  test/FastTests/Server/ThreadUsageTests.cs
  test/InterversionTests/InterversionTests.csproj
  test/LicenseTests/LicenseTests.csproj
  test/RachisTests/RachisTests.csproj
  test/SlowTests/Issues/RavenDB-15898.cs
  test/SlowTests/Issues/RavenDB-4222.cs
  test/SlowTests/Issues/RavenDB-4446.cs
  test/SlowTests/Issues/RavenDB_16193.cs
  test/SlowTests/MailingList/AggresiveCacheWithLazy.cs
  test/SlowTests/SlowTests.csproj
  test/StressTests/StressTests.csproj
  test/Studio/Studio.csproj
  test/Tests.Infrastructure/RavenTestBase.cs
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
  test/Tryouts/Tryouts.csproj
  tools/Raven.Debug/Raven.Debug.csproj
  tools/Raven.Migrator/Raven.Migrator.csproj
  tools/TypingsGenerator/TypingsGenerator.csproj
  tools/Voron.Recovery/Voron.Recovery.csproj
  tools/rvn/rvn.csproj
Labels: v5.2

#11763 RavenDB-16235 we cannot dispose CachedFieldItem immediately because reader could be already in use
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/LuceneDocumentConverterBase.cs
  src/Raven.Server/Json/LazyStringValueReader.cs
  test/SlowTests/Issues/RavenDB_16235.cs
Labels: v5.0

#11765 RavenDB-16089 fix RapidRetention test
  test/StressTests/Client/TimeSeries/TimeSeriesStress.cs
Labels: v5.0

#11764 RavenDB-16236 should be able to index nested json values that are in the array
  src/Raven.Server/Documents/Indexes/MapReduce/Static/MapReduceIndex.cs
  test/SlowTests/Issues/RavenDB_16236.cs
Labels: v5.1

#11767 4.2 to 5.0 merge
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/MapReduce/OutputToCollection/OutputReduceIndexWriteOperation.cs
Labels: v5.0

#11768 5.0 to 5.1 merge
  src/Raven.Server/Documents/CollectionRunner.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/MapReduce/OutputToCollection/OutputReduceIndexWriteOperation.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/LuceneDocumentConverterBase.cs
  src/Raven.Server/Documents/Queries/CollectionQueryEnumerable.cs
  src/Raven.Server/Json/LazyStringValueReader.cs
  test/SlowTests/Issues/RavenDB-16068.cs
  test/SlowTests/Issues/RavenDB_16235.cs
  test/StressTests/Client/TimeSeries/TimeSeriesStress.cs
Labels: v5.1

#11758 RavenDB-16047 /databases endpoint - return database topology on an error as well
  src/Raven.Server/Web/System/DatabasesHandler.cs
Labels: v5.0

#11772 RavenDB-16248 Indexing performance view breaks when we have cmp exch
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexPerformance.ts
  src/Raven.Studio/wwwroot/App/views/database/indexes/indexPerformance.html
  src/Raven.Studio/wwwroot/Content/css/pages/index-performance.less
Labels: v5.1

#11769 RavenDB-16241 Unskipping ExtensionPointsTests
  test/SlowTests/ExtensionPoints/ExtensionPointsTests.cs
Labels: v5.1

#11774 RavenDB-15978 remove unused ids from changevector
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
Labels: v4.2

#11776 RavenDB-1234 - allow to disable requests throttling
  Raven.Database/Server/AppBuilderExtensions.cs
Labels: v3.5

#11770 RavenDB-16163 Adding more debug details in case the error happens again
  src/Voron/Impl/Backup/IncrementalBackup.cs
  src/Voron/Impl/FileHeaders/FileHeader.cs
  src/Voron/Impl/Journal/JournalReader.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
Labels: v4.2

#11777 4.2 to 5.0 merge
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Voron/Impl/Backup/IncrementalBackup.cs
  src/Voron/Impl/FileHeaders/FileHeader.cs
  src/Voron/Impl/Journal/JournalReader.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
Labels: v5.0

#11779 RavenDB-16260 - add missing ReadAsync
  src/Raven.Client/Documents/Operations/Attachments/AttachmentStream.cs
Labels: v4.2

#11782 4.2 to 5.0 merge
  src/Raven.Client/Documents/Operations/Attachments/AttachmentStream.cs
  src/Raven.Server/Web/Studio/StudioTasksHandler.cs
  src/Raven.Server/Web/System/OngoingTasksHandler.cs
  src/Raven.Studio/typescript/commands/serverWide/testPeriodicBackupCredentialsCommand.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editPeriodicBackupTask.ts
  src/Raven.Studio/typescript/viewmodels/manage/editServerWideBackup.ts
Labels: v5.0

#11783 5.0 to 5.1 merge
  src/Raven.Client/Documents/Operations/Attachments/AttachmentStream.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/Web/Studio/StudioTasksHandler.cs
  src/Raven.Server/Web/System/DatabasesHandler.cs
  src/Raven.Server/Web/System/OngoingTasksHandler.cs
  src/Raven.Studio/typescript/commands/serverWide/testPeriodicBackupCredentialsCommand.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editPeriodicBackupTask.ts
  src/Raven.Studio/typescript/viewmodels/manage/editServerWideBackup.ts
  src/Voron/Impl/Backup/IncrementalBackup.cs
  src/Voron/Impl/FileHeaders/FileHeader.cs
  src/Voron/Impl/Journal/JournalReader.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  test/SlowTests/Server/Documents/Indexing/Static/RavenDB_7691.cs
Labels: v5.1

#11781 RavenDB-16265: Add Compressed flag to page when number of OverFlowPages is same after compression from not compressed
  src/Voron/Data/Tables/Table.cs
  test/FastTests/Server/Documents/DocCompression.cs
  test/SlowTests/Issues/RavenDB_16265.cs
Labels: v5.0

#11784 5.1 to 5.2 merge
  src/Raven.Client/Documents/Operations/Attachments/AttachmentStream.cs
  src/Raven.Server/Documents/CollectionRunner.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/MapReduce/OutputToCollection/OutputReduceIndexWriteOperation.cs
  src/Raven.Server/Documents/Indexes/MapReduce/Static/MapReduceIndex.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/LuceneDocumentConverterBase.cs
  src/Raven.Server/Documents/Indexes/Static/Roslyn/Rewriters/MethodDynamicParametersRewriter.cs
  src/Raven.Server/Documents/Queries/CollectionQueryEnumerable.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/Json/LazyStringValueReader.cs
  src/Raven.Server/Web/Studio/StudioTasksHandler.cs
  src/Raven.Server/Web/System/DatabasesHandler.cs
  src/Raven.Server/Web/System/OngoingTasksHandler.cs
  src/Raven.Studio/typescript/commands/serverWide/testPeriodicBackupCredentialsCommand.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexPerformance.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editPeriodicBackupTask.ts
  src/Raven.Studio/typescript/viewmodels/manage/editServerWideBackup.ts
  src/Raven.Studio/wwwroot/App/views/database/indexes/indexPerformance.html
  src/Raven.Studio/wwwroot/Content/css/pages/index-performance.less
  src/Voron/Data/Tables/Table.cs
  src/Voron/Impl/Backup/IncrementalBackup.cs
  src/Voron/Impl/FileHeaders/FileHeader.cs
  src/Voron/Impl/Journal/JournalReader.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  test/FastTests/Server/Documents/DocCompression.cs
  test/SlowTests/ExtensionPoints/ExtensionPointsTests.cs
  test/SlowTests/Issues/RavenDB-16068.cs
  test/SlowTests/Issues/RavenDB-16254.cs
  test/SlowTests/Issues/RavenDB_16235.cs
  test/SlowTests/Issues/RavenDB_16236.cs
  test/SlowTests/Issues/RavenDB_16265.cs
  test/SlowTests/Server/Documents/Indexing/Static/RavenDB_7691.cs
  test/StressTests/Client/TimeSeries/TimeSeriesStress.cs
Labels: v5.2

#11786 RavenDB-16261 decreased number of slots per core for per core lazy string values list to 32 to reduce potentially huge cache (cores x 32 x 8192 x 80 bytes)
  src/Sparrow/Json/JsonOperationContext.cs
  src/Sparrow/Json/PerCoreContainer.cs
Labels: v5.0

#11788 RDBS-2070 bumped Lucene
  libs/Lucene.Net.3.0.42.nupkg
  libs/Lucene.Net.3.0.43.nupkg
  libs/Lucene.Net.Contrib.Spatial.NTS.3.0.42.nupkg
  libs/Lucene.Net.Contrib.Spatial.NTS.3.0.43.nupkg
  src/Raven.Server/Raven.Server.csproj
Labels: v4.2

#11787 RavenDB-16262 fixed NRE in subscriptions when including counters that do not exist in document
  src/Raven.Server/Json/BlittableJsonTextWriterExtensions.cs
  test/SlowTests/Issues/RavenDB_16262.cs
Labels: v5.0

#11792 RavenDB-16272 Expose number of bytes that are effectively in use by …
  src/Raven.Server/Documents/Handlers/Debugging/MemoryDebugHandler.cs
  src/Voron/Impl/EncryptionBuffersPool.cs
  test/FastTests/Voron/EncryptionBufferPool.cs
Labels: v5.0

#11800 RavenDB-16264: Don't use batch delete for deleting multiple blobs
  src/Raven.Server/Documents/PeriodicBackup/Azure/RavenAzureClient.cs
  src/Raven.Server/Documents/PeriodicBackup/Retention/RetentionPolicyRunnerBase.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Azure.cs
Labels: v4.2

#11804 RavenDB-15847 Expose page file (swap) usage on Windows and expose it in SNMP
  src/Sparrow.Server/LowMemory/MemoryInformation.cs
Labels: v4.2

#11798 RavenDB-16211 Keep topology Etag when write database record
  src/Raven.Server/ServerWide/ServerStore.cs
  test/SlowTests/Client/ClientConfigurationTests.cs
Labels: v4.2

#11805 4.2 to 5.0 merge
  src/Raven.Client/Documents/Subscriptions/DocumentSubscriptions.cs
  src/Raven.Client/Util/JavascriptConversionExtensions.cs
  src/Raven.Server/Documents/PeriodicBackup/Azure/RavenAzureClient.cs
  src/Raven.Server/Documents/PeriodicBackup/Retention/RetentionPolicyRunnerBase.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.6/ServerEncryptionBuffersMemoryInPool.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.6/ServerEncryptionBuffersMemoryInUse.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.6/ServerManagedMemory.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.6/ServerUnmanagedMemory .cs
  src/Raven.Server/Monitoring/Snmp/SnmpOids.cs
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Sparrow.Server/LowMemory/MemoryInformation.cs
  src/Voron/Impl/EncryptionBuffersPool.cs
  test/FastTests/Client/Subscriptions/SubscriptionsBasic.cs
  test/FastTests/Voron/EncryptionBufferPool.cs
  test/SlowTests/Client/ClientConfigurationTests.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Azure.cs
Labels: v5.0

#11806 5.0 to 5.1 merge
  src/Raven.Client/Documents/Subscriptions/DocumentSubscriptions.cs
  src/Raven.Client/Util/JavascriptConversionExtensions.cs
  src/Raven.Server/Documents/Handlers/Debugging/MemoryDebugHandler.cs
  src/Raven.Server/Documents/PeriodicBackup/Azure/RavenAzureClient.cs
  src/Raven.Server/Documents/PeriodicBackup/Retention/RetentionPolicyRunnerBase.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.6/ServerEncryptionBuffersMemoryInPool.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.6/ServerEncryptionBuffersMemoryInUse.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.6/ServerManagedMemory.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.6/ServerUnmanagedMemory .cs
  src/Raven.Server/Monitoring/Snmp/SnmpOids.cs
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Sparrow.Server/LowMemory/MemoryInformation.cs
  src/Voron/Impl/EncryptionBuffersPool.cs
  test/FastTests/Client/Subscriptions/SubscriptionsBasic.cs
  test/FastTests/Voron/EncryptionBufferPool.cs
  test/SlowTests/Client/ClientConfigurationTests.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Azure.cs
Labels: v5.1

#11807 RavenDB-16278 added additional check to see if we do not have indexing errors
  test/SlowTests/Server/Documents/Indexing/MapReduce/OutputReduceToCollectionTests.cs
Labels: v4.2

#11808 RavenDB-16283 fixed race condition in test
  test/SlowTests/Issues/RavenDB_10505.cs
Labels: v4.2

#11809 RavenDB-16293 AdditionalSources should affect index definition hash code because it is being used when calculating index etag
  src/Raven.Client/Documents/Indexes/IndexDefinition.cs
  src/Raven.Client/Extensions/DictionaryExtensions.cs
  src/Raven.Client/Extensions/EnumerableExtension.cs
  test/SlowTests/Issues/RavenDB_16293.cs
Labels: v4.2

#11810 RavenDB-14107 Fixing ocassionally failing test. Making sure that the …
  test/SlowTests/Voron/RavenDB_13940_Encrypted.cs
Labels: v4.2

#11813 4.2 to 5.0 merge
  src/Raven.Client/Documents/Indexes/IndexDefinition.cs
  src/Raven.Client/Extensions/DictionaryExtensions.cs
  src/Raven.Client/Extensions/EnumerableExtension.cs
  test/SlowTests/Issues/RavenDB_10505.cs
  test/SlowTests/Issues/RavenDB_16293.cs
  test/SlowTests/Server/Documents/Indexing/MapReduce/OutputReduceToCollectionTests.cs
  test/SlowTests/Voron/RavenDB_13940_Encrypted.cs
Labels: v5.0

#11814 5.0 to 5.1 merge
  src/Raven.Client/Documents/Indexes/IndexDefinition.cs
  src/Raven.Client/Extensions/DictionaryExtensions.cs
  src/Raven.Client/Extensions/EnumerableExtension.cs
  src/Voron/Impl/EncryptionBuffersPool.cs
  test/SlowTests/Issues/RavenDB_10505.cs
  test/SlowTests/Issues/RavenDB_16293.cs
  test/SlowTests/Server/Documents/Indexing/MapReduce/OutputReduceToCollectionTests.cs
  test/SlowTests/Voron/RavenDB_13940_Encrypted.cs
Labels: v5.1

#11816 RavenDB-16299 fixed race condition between removing or replacing an index and starting or stopping all of the indexes
  src/Raven.Server/Documents/Indexes/IndexStore.cs
Labels: v4.2

#11815 RavenDB-16289 do not register low memory for test in EncryptionBufferPool
  src/Voron/Impl/EncryptionBuffersPool.cs
  test/FastTests/Voron/EncryptionBufferPool.cs
Labels: v5.0
