Repository ravendb/ravendb, pull requests merged in 2021-11, with the labels that each got.

#12967 RavenDB-17428 Import Data View: Improve Migrator Path info
  src/Raven.Studio/typescript/viewmodels/database/tasks/migrateDatabase.ts
Labels: v5.2

#12960 RavenDB-16878 Show raft index in the compare exchange view
  src/Raven.Studio/typescript/viewmodels/database/cmpXchg/cmpXchg.ts
  src/Raven.Studio/typescript/viewmodels/database/cmpXchg/editCmpXchg.ts
  src/Raven.Studio/typescript/viewmodels/database/documents/deleteCompareExchangeProgress.ts
  src/Raven.Studio/wwwroot/App/views/database/cmpXchg/editCmpXchg.html
Labels: v5.2

#12947 RavenDB-17416 - Prevent us from throwing an exception during error handling
  src/Raven.Server/Documents/Indexes/Index.cs
Labels: v4.2

#12949 RavenDB-17420 Allow to define boost on in queries
  src/Raven.Server/Documents/Queries/LuceneIntegration/InQuery.cs
  test/SlowTests/Issues/RavenDB-17420.cs
Labels: v5.2

#12971 RavenDB-16995 fix Can_import_export_replication_certs test
  test/SlowTests/Issues/FilteredReplicationTests.cs
Labels: v5.1

#12968 RavenDB-17263 : Incorrect Custom Partition Value when testing OLAP script
  src/Raven.Server/Documents/ETL/Providers/OLAP/OlapDocumentTransformer.cs
  test/SlowTests/Server/Documents/ETL/Olap/RavenDB_17263.cs
Labels: v5.2

#12969 RavenDB-17435 If Pg server is already activeted then we shouldn't throw
  src/Raven.Server/Integrations/PostgreSQL/PgServer.cs
Labels: v5.3

#12972 4.2 to 5.1 merge
  readme.md
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Utils/ChangeVectorUtils.cs
  src/Raven.Server/Web/System/StudioHandler.cs
  src/Raven.Studio/package-lock.json
  src/Raven.Studio/typescript/commands/maintenance/getStackTraceForThreadCommand.ts
  src/Raven.Studio/typescript/common/generalUtils.ts
  src/Raven.Studio/typescript/viewmodels/manage/captureStackTraces.ts
  src/Raven.Studio/typescript/viewmodels/manage/debugAdvancedThreadsRuntime.ts
  src/Raven.Studio/typescript/viewmodels/manage/threadStackTrace.ts
  src/Raven.Studio/typings/_studio/dto.d.ts
  src/Raven.Studio/wwwroot/App/views/manage/threadStackTrace.html
  src/Raven.Studio/wwwroot/Content/css/pages/debug-advanced.less
  src/Voron/Impl/Scratch/ScratchBufferFile.cs
  test/SlowTests/Issues/RavenDB_17353.cs
Labels: v5.1

#12974 5.1 to 5.2 merge
  readme.md
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  src/Raven.Server/Utils/ChangeVectorUtils.cs
  src/Raven.Server/Web/System/StudioHandler.cs
  src/Raven.Studio/package-lock.json
  src/Raven.Studio/typescript/commands/maintenance/getStackTraceForThreadCommand.ts
  src/Raven.Studio/typescript/common/generalUtils.ts
  src/Raven.Studio/typescript/viewmodels/manage/captureStackTraces.ts
  src/Raven.Studio/typescript/viewmodels/manage/debugAdvancedThreadsRuntime.ts
  src/Raven.Studio/typescript/viewmodels/manage/threadStackTrace.ts
  src/Raven.Studio/typings/_studio/dto.d.ts
  src/Raven.Studio/wwwroot/App/views/manage/threadStackTrace.html
  src/Raven.Studio/wwwroot/Content/css/pages/debug-advanced.less
  src/Voron/Impl/Scratch/ScratchBufferFile.cs
  test/SlowTests/Issues/FilteredReplicationTests.cs
  test/SlowTests/Issues/RavenDB-17082.cs
  test/SlowTests/Issues/RavenDB_17353.cs
Labels: v5.2

#12975 5.2 to 5.3 merge
  readme.md
  src/Raven.Client/Json/Serialization/NewtonsoftJson/Internal/BlittableJsonWriter.cs
  src/Raven.Server/Documents/ETL/Providers/OLAP/OlapDocumentTransformer.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Queries/LuceneIntegration/InQuery.cs
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  src/Raven.Server/Web/System/StudioHandler.cs
  src/Raven.Studio/package-lock.json
  src/Raven.Studio/typescript/commands/maintenance/getStackTraceForThreadCommand.ts
  src/Raven.Studio/typescript/common/generalUtils.ts
  src/Raven.Studio/typescript/viewmodels/database/cmpXchg/cmpXchg.ts
  src/Raven.Studio/typescript/viewmodels/database/cmpXchg/editCmpXchg.ts
  src/Raven.Studio/typescript/viewmodels/database/documents/deleteCompareExchangeProgress.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/migrateDatabase.ts
  src/Raven.Studio/typescript/viewmodels/manage/captureStackTraces.ts
  src/Raven.Studio/typescript/viewmodels/manage/debugAdvancedThreadsRuntime.ts
  src/Raven.Studio/typescript/viewmodels/manage/threadStackTrace.ts
  src/Raven.Studio/typings/_studio/dto.d.ts
  src/Raven.Studio/wwwroot/App/views/database/cmpXchg/editCmpXchg.html
  src/Raven.Studio/wwwroot/App/views/manage/threadStackTrace.html
  src/Raven.Studio/wwwroot/Content/css/pages/debug-advanced.less
  src/Voron/Impl/Scratch/ScratchBufferFile.cs
  test/SlowTests/Issues/FilteredReplicationTests.cs
  test/SlowTests/Issues/RavenDB-17082.cs
  test/SlowTests/Issues/RavenDB-17282.cs
  test/SlowTests/Issues/RavenDB-17420.cs
  test/SlowTests/Issues/RavenDB_17353.cs
  test/SlowTests/Server/Documents/ETL/Olap/RavenDB_17263.cs
Labels: v5.3

#12973 RavenDB-17288 test fix
  test/SlowTests/Issues/RavenDB-15900.cs
Labels: v4.2

#12981 RavenDB-17369 Include brackets inside the update statement.
  src/Raven.Studio/languageService/grammar/BaseRqlParser.g4
  src/Raven.Studio/languageService/src/generated/BaseRqlParser.interp
  src/Raven.Studio/languageService/src/generated/BaseRqlParser.ts
  src/Raven.Studio/languageService/src/generated/BaseRqlParserVisitor.ts
  src/Raven.Studio/languageService/test/grammar/updateStatement.spec.ts
Labels: v5.3

#12985 RavenDB-16877 : flaky test
  test/SlowTests/Server/Documents/ETL/Olap/FailoverTests.cs
Labels: v5.2

#12987 5.1 to 5.2 merge
  bench/Regression.Benchmark/Regression.Benchmark.csproj
  src/Raven.Server/Documents/Handlers/Debugging/ThreadsHandler.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Server/Utils/ThreadsUsage.cs
  src/Raven.Studio/typescript/commands/licensing/getConnectivityToLicenseServerCommand.ts
  src/Raven.Studio/typescript/commands/version/getLatestVersionInfoCommand.ts
  src/Raven.Studio/typescript/viewmodels/shell/about.ts
  src/Raven.Studio/wwwroot/App/views/shell/about.html
  src/Raven.Studio/wwwroot/Content/css/pages/about.less
  test/BenchmarkTests/BenchmarkTests.csproj
  test/EmbeddedTests/EmbeddedTests.csproj
  test/FastTests/FastTests.csproj
  test/InterversionTests/InterversionTests.csproj
  test/LicenseTests/LicenseTests.csproj
  test/RachisTests/RachisTests.csproj
  test/SlowTests/Issues/RavenDB-15900.cs
  test/SlowTests/SlowTests.csproj
  test/StressTests/StressTests.csproj
  tools/Raven.Debug/CommandLineApp.cs
  tools/Raven.Debug/StackTrace/StackTracer.cs
  tools/Raven.Migrator/Raven.Migrator.csproj
Labels: v5.2

#12988 5.2 to 5.3 merge
  bench/Regression.Benchmark/Regression.Benchmark.csproj
  src/Raven.Server/Documents/Handlers/Debugging/ThreadsHandler.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Server/Utils/ThreadsUsage.cs
  src/Raven.Studio/typescript/commands/licensing/getConnectivityToLicenseServerCommand.ts
  src/Raven.Studio/typescript/commands/version/getLatestVersionInfoCommand.ts
  src/Raven.Studio/typescript/viewmodels/shell/about.ts
  src/Raven.Studio/wwwroot/App/views/shell/about.html
  src/Raven.Studio/wwwroot/Content/css/pages/about.less
  test/BenchmarkTests/BenchmarkTests.csproj
  test/EmbeddedTests/EmbeddedTests.csproj
  test/FastTests/FastTests.csproj
  test/InterversionTests/InterversionTests.csproj
  test/LicenseTests/LicenseTests.csproj
  test/RachisTests/RachisTests.csproj
  test/SlowTests/Issues/RavenDB-15900.cs
  test/SlowTests/Server/Documents/ETL/Olap/FailoverTests.cs
  test/SlowTests/SlowTests.csproj
  test/StressTests/StressTests.csproj
  tools/Raven.Debug/CommandLineApp.cs
  tools/Raven.Debug/StackTrace/StackTracer.cs
  tools/Raven.Migrator/Raven.Migrator.csproj
Labels: v5.3

#12984 RavenDB-17423 Collection size limitation when using "Not In" clause
  src/Raven.Server/Documents/Queries/LuceneIntegration/InQuery.cs
  test/SlowTests/Issues/RavenDB_17423.cs
Labels: v5.1

#12994 5.1 to 5.2 merge
  src/Raven.Server/Documents/Queries/LuceneIntegration/InQuery.cs
  test/SlowTests/Issues/RavenDB_17423.cs
Labels: v5.2

#12995 RavenDB-7070 update docker tags before release
  docker/build-nanoserver.ps1
  docker/common.ps1
  docker/publish-nanoserver.ps1
Labels: v5.2

#12997 5.2 to 5.3 merge
  src/Raven.Server/Documents/Queries/LuceneIntegration/InQuery.cs
  test/SlowTests/Issues/RavenDB_17423.cs
Labels: v5.3

#12999 RavenDB-15919 throw exception when license doesn't support concurrent subscriptions
  src/Raven.Client/Extensions/TaskExtensions.cs
  src/Raven.Server/Documents/TcpHandlers/SubscriptionConnection.cs
  test/SlowTests/Client/Subscriptions/ConcurrentSubscriptionsTests.cs
Labels: v5.3

#12992 RavenDB-17139 Rename title: Current Value => Total Value
  src/Raven.Studio/wwwroot/App/views/database/timeSeries/editTimeSeriesEntry.html
Labels: v5.3

#13007 RavenDB-17466 Cluster version must not exceed `MyCommandsVersion`
  src/Raven.Server/Rachis/Leader.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/ServerWide/ClusterCommandsVersionManager.cs
Labels: v4.2

#13008 RavenDB-15919 snapshot SubscriptionState
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  test/RachisTests/AddNodeToClusterTests.cs
Labels: v5.3

#13013 4.2 to 5.1 merge
  src/Raven.Server/Rachis/Leader.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/ServerWide/ClusterCommandsVersionManager.cs
Labels: v5.1

#13014 5.1 to 5.2 merge
  src/Raven.Server/Rachis/Leader.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/ServerWide/ClusterCommandsVersionManager.cs
Labels: v5.2

#13016 RavenDB-17461 Replace DocId initial value to avoid getting unnecessary documents in 'Not In'.
  src/Raven.Server/Documents/Queries/LuceneIntegration/InQuery.cs
Labels: v5.1

#13009 RavenDB-17266 Show Force Update button for all license types
  src/Raven.Studio/typescript/viewmodels/shell/about.ts
  src/Raven.Studio/wwwroot/App/views/shell/about.html
Labels: v4.2

#13017 RavenDB-17468 - Subscription task status is not active + 3 clients are connected
  src/Raven.Server/Web/System/OngoingTasksHandler.cs
Labels: v5.3

#13023 RavenDB-17476 Add the document ID property automatically to JSON if missing before sending to Elasticsearch
  src/Raven.Server/Documents/ETL/Providers/Elasticsearch/ElasticSearchDocumentTransformer.cs
  src/Raven.Server/Documents/ETL/Providers/Elasticsearch/ElasticSearchEtl.cs
  src/Raven.Server/Documents/ETL/Providers/Elasticsearch/ElasticSearchItem.cs
  src/Raven.Server/Documents/ETL/Providers/Elasticsearch/ElasticSearchProperty.cs
  src/Raven.Server/Documents/ETL/Providers/Elasticsearch/ElasticsearchIndexWriterSimulator.cs
  test/SlowTests/Server/Documents/ETL/Elasticsearch/ElasticSearchEtlTestBase.cs
  test/SlowTests/Server/Documents/ETL/Elasticsearch/ElasticSearchEtlTests.cs
  test/SlowTests/Server/Documents/ETL/Elasticsearch/RavenDB_17476.cs
Labels: v5.3

#13020 RavenDB-17459 Fix password
  src/Raven.Studio/typescript/models/database/settings/postgreSqlCredentialsModel.ts
Labels: v5.3

#13024 RavenDB-15919 - Fix test
  test/SlowTests/Client/Subscriptions/ConcurrentSubscriptionsTests.cs
Labels: v5.3

#13021 RavenDB-17348 allow to change subscription mode when all connections are dropped
  src/Raven.Server/Documents/Subscriptions/SubscriptionConnectionsState.cs
  test/SlowTests/Client/Subscriptions/ConcurrentSubscriptionsTests.cs
Labels: v5.3

#13019 RavenDB-17460: add snapshot of CompareExchangeByExpiration
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/CompareExchangeExpirationStorage.cs
  test/SlowTests/Cluster/CompareExchangeExpirationTest.cs
Labels: v5.1

#13028 4.2 to 5.1 merge
  src/Raven.Client/Documents/Linq/LinqPathProvider.cs
  src/Raven.Client/Documents/Linq/RavenQueryProviderProcessor.cs
  src/Raven.Server/Documents/Patch/JavaScriptUtils.cs
  src/Raven.Server/Documents/Queries/QueryMetadata.cs
  src/Raven.Server/Documents/Queries/SelectField.cs
  src/Raven.Studio/typescript/viewmodels/shell/about.ts
  src/Raven.Studio/wwwroot/App/views/shell/about.html
  test/SlowTests/Issues/RavenDB-16038.cs
  test/SlowTests/Issues/RavenDB_16033.cs
Labels: v5.1

#13029 5.1 to 5.2 merge
  src/Raven.Client/Documents/Linq/LinqPathProvider.cs
  src/Raven.Client/Documents/Linq/RavenQueryProviderProcessor.cs
  src/Raven.Server/Documents/Patch/JavaScriptUtils.cs
  src/Raven.Server/Documents/Queries/LuceneIntegration/InQuery.cs
  src/Raven.Server/Documents/Queries/QueryMetadata.cs
  src/Raven.Server/Documents/Queries/SelectField.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/CompareExchangeExpirationStorage.cs
  src/Raven.Studio/typescript/viewmodels/shell/about.ts
  src/Raven.Studio/wwwroot/App/views/shell/about.html
  test/SlowTests/Cluster/CompareExchangeExpirationTest.cs
  test/SlowTests/Issues/RavenDB-16038.cs
  test/SlowTests/Issues/RavenDB_16033.cs
Labels: v5.2

#13030 5.2 to 5.3 merge
  src/Raven.Client/Documents/Linq/LinqPathProvider.cs
  src/Raven.Client/Documents/Linq/RavenQueryProviderProcessor.cs
  src/Raven.Server/Documents/Patch/JavaScriptUtils.cs
  src/Raven.Server/Documents/Queries/LuceneIntegration/InQuery.cs
  src/Raven.Server/Documents/Queries/QueryMetadata.cs
  src/Raven.Server/Documents/Queries/SelectField.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/CompareExchangeExpirationStorage.cs
  src/Raven.Studio/typescript/viewmodels/shell/about.ts
  src/Raven.Studio/wwwroot/App/views/shell/about.html
  test/SlowTests/Cluster/CompareExchangeExpirationTest.cs
  test/SlowTests/Issues/RavenDB-16038.cs
  test/SlowTests/Issues/RavenDB_16033.cs
Labels: v5.3

#13026 RavenDB-17485 Incorrect results in time series table for group by action
  src/Raven.Studio/typescript/viewmodels/database/query/query.ts
Labels: v5.2

#13025 RavenDB-17477 Verify existing Elasticsearch index definition that property having doc id isn't analyzed
  src/Raven.Server/Documents/ETL/Providers/Elasticsearch/ElasticSearchEtl.cs
  test/SlowTests/Server/Documents/ETL/Elasticsearch/ElasticSearchEtlTestBase.cs
  test/SlowTests/Server/Documents/ETL/Elasticsearch/RavenDB_17477.cs
Labels: v5.3

#13041 RavenDB-17477 Skipping a test that is the suspicion of test hangs
  test/SlowTests/Server/Documents/ETL/Elasticsearch/RavenDB_17477.cs
Labels: v5.3

#13053 RavenDB-17242: Sorting using multiple comparers.
  src/Corax/Queries/SortingMatch.Comparers.cs
  src/Corax/Queries/SortingMatch.Erasure.cs
  src/Corax/Queries/SortingMatch.cs
  src/Corax/Queries/SortingMultiMatch.Erasure.cs
  src/Corax/Queries/SortingMultiMatch.cs
  test/FastTests/Corax/OrderByMultiSorting.cs
Labels: Corax

#13042 RavenDB-17498 Allow rerun ExecuteRateLimitedOperations
  src/Raven.Server/Documents/ExecuteRateLimitedOperations.cs
  test/SlowTests/Server/TransactionMergerTests.cs
Labels: v4.2

#13056 RavenDB-17518 : LegacyReplication violation isn't caught
  src/Raven.Server/Documents/Replication/ReplicationDocumentSender.cs
  test/InterversionTests/RavenDB-17518.cs
Labels: v4.2

#13057 RavenDB-17518 : 5.1 fix
  src/Raven.Server/Documents/Replication/ReplicationDocumentSender.cs
  test/InterversionTests/RavenDB-17518.cs
Labels: v5.1

#13060 RavenDB-17502 Fixing the usage of transaction operation context in `DatabaseRequestHandler.DatabaseConfigurations` since `setupConfigurationFunc` might return a blittable that's used later on
  src/Raven.Server/Documents/DatabaseRequestHandler.cs
  src/Raven.Server/Integrations/PostgreSQL/Handlers/PostgreSqlIntegrationHandler.cs
Labels: v5.3

#13063 RavenDB-17515: Don't add document to resend list if it doesn't match …
  src/Raven.Server/Documents/Subscriptions/SubscriptionProcessor/DocumentsSubscriptionProcessor.cs
  test/SlowTests/Client/Subscriptions/ConcurrentSubscriptionsTests.cs
Labels: v5.3

#13069 RavenDB-17514 Delete by Query confirmation modal: Index name is not …
  src/Raven.Studio/wwwroot/App/views/database/query/deleteDocumentsMatchingQueryConfirm.html
Labels: v5.2

#13068 RavenDB-17517 Transfer all whitespaces into hidden channel in update statement.
  src/Raven.Studio/languageService/grammar/BaseRqlLexer.g4
  src/Raven.Studio/languageService/grammar/BaseRqlParser.g4
  src/Raven.Studio/languageService/src/generated/BaseRqlLexer.interp
  src/Raven.Studio/languageService/src/generated/BaseRqlLexer.tokens
  src/Raven.Studio/languageService/src/generated/BaseRqlLexer.ts
  src/Raven.Studio/languageService/src/generated/BaseRqlParser.interp
  src/Raven.Studio/languageService/src/generated/BaseRqlParser.tokens
  src/Raven.Studio/languageService/src/generated/BaseRqlParser.ts
  src/Raven.Studio/languageService/test/grammar/updateStatement.spec.ts
Labels: v5.3

#13067 RavenDB-17516 Clicking on the middle mouse button in tasks doesn't op…
  src/Raven.Studio/wwwroot/App/views/database/tasks/ongoingTasks.html
Labels: v4.2

#13072 RavenDB-17493 Incremental timeseries count - Add toLocaleString()
  src/Raven.Studio/typescript/viewmodels/database/documents/editDocumentConnectedDocuments.ts
Labels: v5.3

#13071 RavenDB-16206 Query builder optimization.
  src/Raven.Client/Documents/Session/AbstractDocumentQuery.cs
Labels: v5.1

#12966 RavenDB-17419 Throws when detects whole document comparison in a conditional statement.
  src/Raven.Client/Documents/Linq/RavenQueryProviderProcessor.cs
  test/SlowTests/Issues/RavenDB-17419.cs
Labels: v5.2

#13073 RavenDB-17512 Disable the 'Add Transformation Script' btn when editin…
  src/Raven.Studio/wwwroot/App/views/database/tasks/editElasticSearchEtlTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editOlapEtlTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editRavenEtlTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editSqlEtlTask.html
Labels: v5.3

#13074 RavenDB-17535 : add incremental time series query tests
  test/SlowTests/Client/TimeSeries/Issues/RavenDB-15020.cs
  test/SlowTests/Client/TimeSeries/Query/IncrementalTimeSeriesQueries.cs
Labels: v5.3

#13076 4.2 to 5.1 merge
  src/Raven.Server/Documents/ConflictsStorage.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/ExecuteRateLimitedOperations.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/MapReduce/OutputToCollection/OutputReduceToCollectionActions.cs
  src/Raven.Server/Documents/Indexes/Workers/HandleReferencesBase.ReferencesState.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Voron/Impl/LowLevelTransaction.cs
  src/Voron/StorageEnvironment.cs
  test/SlowTests/Server/TransactionMergerTests.cs
  test/SlowTests/Voron/Issues/RDBCL_1977.cs
Labels: v5.1

#13077 5.1 to 5.2 merge
  src/Raven.Client/Documents/Session/AbstractDocumentQuery.cs
  src/Raven.Server/Documents/ConflictsStorage.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/ExecuteRateLimitedOperations.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/MapReduce/OutputToCollection/OutputReduceToCollectionActions.cs
  src/Raven.Server/Documents/Indexes/Workers/HandleReferencesBase.ReferencesState.cs
  src/Raven.Server/Documents/Replication/ReplicationDocumentSender.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/Web/System/OngoingTasksHandler.cs
  src/Voron/Impl/LowLevelTransaction.cs
  src/Voron/StorageEnvironment.cs
  test/InterversionTests/RavenDB-17518.cs
  test/SlowTests/Server/Replication/PullReplicationTests.cs
  test/SlowTests/Server/TransactionMergerTests.cs
  test/SlowTests/Voron/Issues/RDBCL_1977.cs
Labels: v5.2

#13083 5.2 to 5.3 merge
  src/Raven.Client/Documents/Linq/RavenQueryProviderProcessor.cs
  src/Raven.Client/Documents/Session/AbstractDocumentQuery.cs
  src/Raven.Server/Documents/ConflictsStorage.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/ExecuteRateLimitedOperations.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/MapReduce/OutputToCollection/OutputReduceToCollectionActions.cs
  src/Raven.Server/Documents/Indexes/Workers/HandleReferencesBase.ReferencesState.cs
  src/Raven.Server/Documents/Patch/JavaScriptUtils.cs
  src/Raven.Server/Documents/Queries/Results/QueryResultRetrieverBase.cs
  src/Raven.Server/Documents/Queries/Results/TimeSeries/TimeSeriesRetriever.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.1/DatabaseBase.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.1/DatabaseFaultedCount.cs
  src/Raven.Server/Monitoring/Snmp/SnmpOids.cs
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/Web/System/OngoingTasksHandler.cs
  src/Raven.Studio/wwwroot/App/views/database/query/deleteDocumentsMatchingQueryConfirm.html
  src/Voron/Impl/LowLevelTransaction.cs
  src/Voron/StorageEnvironment.cs
  test/InterversionTests/RavenDB-17518.cs
  test/SlowTests/Issues/RavenDB-17418.cs
  test/SlowTests/Issues/RavenDB-17419.cs
  test/SlowTests/Server/Replication/PullReplicationTests.cs
  test/SlowTests/Server/TransactionMergerTests.cs
  test/SlowTests/Voron/Issues/RDBCL_1977.cs
Labels: v5.3

#13082 RavenDB-17516 Clicking on the middle mouse button in tasks doesn't op…
  src/Raven.Studio/wwwroot/App/views/database/tasks/ongoingTasks.html
Labels: v5.1

#13086 RDBCL-1977 Fixing test compilation if someone doesn't have .net 6 sdk installed (VS 2022 took advantage of new c# feature that there is no need to add curly brackets after namespace)
  test/SlowTests/Voron/Issues/RDBCL_1977.cs
Labels: v4.2

#13095 RavenDB-17493 NaN should be the initial values for StatefulTimestampValue
  src/Raven.Server/Documents/TimeSeries/TimeSeriesValuesSegment.cs
Labels: v5.3

#13098 RavenDB-17551 Paging is ignoring offset
  src/Raven.Server/Documents/Queries/CollectionQueryEnumerable.cs
  test/SlowTests/Issues/RavenDB-17551.cs
Labels: v5.2

#13107 RavenDB-17478 PowerBI: "Field count mismatch when mapping column types" on some RQL queries
  src/Raven.Server/Integrations/PostgreSQL/PgQuery.cs
  test/SlowTests/Server/Integrations/PostgreSQL/RavenDB_17478.cs
Labels: v5.3

#13052 RavenDB-17483 - Fix GetAll subscriptions debug endpoint to get all connections when subscription is concurrent
  src/Raven.Server/Documents/Handlers/SubscriptionsHandler.cs
  src/Raven.Server/Documents/Subscriptions/SubscriptionStorage.cs
Labels: v5.3

#13002 RavenDB-17143 add more info to test
  test/SlowTests/Server/Replication/PullReplicationTests.cs
Labels: v5.2

#13113 RavenDB-17552 get incremental TS should populate the tag
  src/Raven.Server/Documents/Handlers/TimeSeriesHandler.cs
  test/SlowTests/Client/TimeSeries/IncrementalTimeSeriesTests.cs
Labels: v5.3

#13109 RavenDB-17545 Caching index metadata.
  src/Raven.Client/Documents/Session/AsyncDocumentSession.Query.cs
  src/Raven.Client/Documents/Session/DocumentSession.Query.cs
  src/Raven.Client/Documents/Session/IndexMetadataCache.cs
Labels: v5.1

#13116 4.2 to 5.1 merge
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  src/Raven.Server/Documents/Indexes/MapReduce/OutputToCollection/OutputReduceToCollectionCommand.cs
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  src/Raven.Server/ServerWide/Commands/RemoveNodeFromDatabaseCommand.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterObserver.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  test/SlowTests/Issues/RavenDB-15483.cs
  test/SlowTests/Issues/RavenDB-17096.cs
  test/SlowTests/Issues/RavenDB-17311.cs
  test/SlowTests/Issues/RavenDB_7912.cs
  test/SlowTests/RavenDB-14303.cs
  test/SlowTests/Server/TransactionMergerTests.cs
  test/SlowTests/Voron/Issues/RDBCL_1977.cs
Labels: v5.1

#13117 5.1 to 5.2 merge
  src/Raven.Client/Documents/Session/AsyncDocumentSession.Query.cs
  src/Raven.Client/Documents/Session/DocumentSession.Query.cs
  src/Raven.Client/Documents/Session/IndexMetadataCache.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  src/Raven.Server/Documents/Indexes/MapReduce/OutputToCollection/OutputReduceToCollectionCommand.cs
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  src/Raven.Server/ServerWide/Commands/RemoveNodeFromDatabaseCommand.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterObserver.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Studio/wwwroot/App/views/database/tasks/ongoingTasks.html
  test/SlowTests/Issues/RavenDB-15483.cs
  test/SlowTests/Issues/RavenDB-17096.cs
  test/SlowTests/Issues/RavenDB-17311.cs
  test/SlowTests/Issues/RavenDB_7912.cs
  test/SlowTests/RavenDB-14303.cs
  test/SlowTests/Server/TransactionMergerTests.cs
  test/SlowTests/Voron/Issues/RDBCL_1977.cs
Labels: v5.2

#13118 5.2 to 5.3 merge
  src/Raven.Client/Documents/Session/AsyncDocumentSession.Query.cs
  src/Raven.Client/Documents/Session/DocumentSession.Query.cs
  src/Raven.Client/Documents/Session/IndexMetadataCache.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  src/Raven.Server/Documents/Indexes/MapReduce/OutputToCollection/OutputReduceToCollectionCommand.cs
  src/Raven.Server/Documents/Queries/CollectionQueryEnumerable.cs
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  src/Raven.Server/ServerWide/Commands/RemoveNodeFromDatabaseCommand.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterObserver.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Studio/wwwroot/App/views/database/tasks/ongoingTasks.html
  test/SlowTests/Issues/RavenDB-15483.cs
  test/SlowTests/Issues/RavenDB-17096.cs
  test/SlowTests/Issues/RavenDB-17311.cs
  test/SlowTests/Issues/RavenDB-17551.cs
  test/SlowTests/Issues/RavenDB_7912.cs
  test/SlowTests/RavenDB-14303.cs
  test/SlowTests/Server/Replication/PullReplicationTests.cs
  test/SlowTests/Server/TransactionMergerTests.cs
  test/SlowTests/Voron/Issues/RDBCL_1977.cs
Labels: v5.3

#13122 RavenDB-17564 Making sure that errors on index open or index definition update are written to the log configured on the operations level
  src/Raven.Server/Documents/Indexes/IndexStore.cs
Labels: v4.2

#13115 RavenDB-17430 Create new icon for the Thread's Stack Trace
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.eot
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.svg
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.ttf
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.woff
  src/Raven.Studio/wwwroot/Content/css/icons.less
Labels: v4.2

#13075 RavenDB-17537 Error when querying Auto-Index with quotes
  src/Raven.Studio/typescript/common/queryUtil.ts
  src/Raven.Studio/typescript/models/database/query/queryCriteria.ts
Labels: v4.2

#13084 RavenDB-17273 Added the query parameters in "page size too big" window.
  src/Raven.Server/Documents/DatabaseRequestHandler.cs
  src/Raven.Server/Documents/Handlers/QueriesHandler.cs
Labels: v5.2

#13123 RavenDB-14634 better logging for error during NotifyLeaderAboutRemoval
  src/Raven.Server/Documents/DatabasesLandlord.cs
Labels: v4.2

#13125 RavenDB-17552 merge DEC & INC for nodes details
  src/Raven.Server/Documents/TimeSeries/TimeSeriesReader.cs
  test/SlowTests/Client/TimeSeries/IncrementalTimeSeriesTests.cs
Labels: v5.3

#13127 4.2 to 5.1 merge
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  src/Raven.Studio/typescript/common/queryUtil.ts
  src/Raven.Studio/typescript/models/database/query/queryCriteria.ts
Labels: v5.1

#13128 5.1 to 5.2 merge
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  src/Raven.Studio/typescript/common/queryUtil.ts
  src/Raven.Studio/typescript/models/database/query/queryCriteria.ts
Labels: v5.2

#13130 RavenDB-17430 Updated the Thread's Stack Trace icon
  src/Raven.Studio/typescript/viewmodels/manage/debugAdvancedThreadsRuntime.ts
  src/Raven.Studio/wwwroot/App/views/manage/threadStackTrace.html
Labels: v5.2

#13131 RavenDB-17567 Hide Tag column for incremental TS
  src/Raven.Studio/typescript/viewmodels/database/timeSeries/editTimeSeries.ts
Labels: v5.3

#13135 RavenDB-17191 test fix
  test/SlowTests/Server/Replication/ReplicationCleanTombstones.cs
Labels: v5.2

#13133 RavenDB-17387 - fixed Exporting or importing collections loses capitalization on node name
  src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
  test/SlowTests/Smuggler/SmugglerApiTests.cs
Labels: v5.2

#13137 RavenDB-17574 - fix exception during query
  src/Raven.Client/Documents/Linq/RavenQueryProvider.cs
  test/SlowTests/Issues/RavenDB-17574.cs
Labels: v4.2

#13141 RavenDB-17543 Compound sorting fix in static indexes.
  src/Raven.Server/Documents/Indexes/Static/DynamicArray.cs
  test/SlowTests/Issues/RavenDB_17543.cs
  test/SlowTests/MailingList/IndexCompilation.cs
Labels: v5.2

#13140 RavenDB-17152
  src/Raven.Studio/typescript/widgets/virtualGrid/columnPreviewPlugin.ts
Labels: v4.2

#13134 RavenDB-17462 : fix flaky test
  test/SlowTests/Server/Documents/ETL/Olap/FailoverTests.cs
Labels: v5.2

#13142 RavenDB-17572: Fix wrong hashing of double value in reduce key processor
  src/Raven.Server/Documents/Handlers/IndexHandler.cs
  src/Raven.Server/Documents/Indexes/IndexDefinitionBase.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  src/Raven.Server/Documents/Indexes/MapReduce/Auto/AutoMapReduceIndex.cs
  src/Raven.Server/Documents/Indexes/MapReduce/ReduceKeyProcessor.cs
  src/Raven.Server/Documents/Indexes/MapReduce/Static/MapReduceIndex.cs
  src/Raven.Server/Documents/Indexes/Static/AbstractCountersAndTimeSeriesJavaScriptIndex.cs
  src/Raven.Server/Documents/Indexes/Static/Counters/CountersJavaScriptIndex.cs
  src/Raven.Server/Documents/Indexes/Static/Counters/MapCountersIndex.cs
  src/Raven.Server/Documents/Indexes/Static/IndexCompilationCache.cs
  src/Raven.Server/Documents/Indexes/Static/JavaScriptIndex.cs
  src/Raven.Server/Documents/Indexes/Static/JavaScriptReduceOperation.cs
  src/Raven.Server/Documents/Indexes/Static/MapIndex.cs
  src/Raven.Server/Documents/Indexes/Static/TimeSeries/MapTimeSeriesIndex.cs
  src/Raven.Server/Documents/Indexes/Static/TimeSeries/TimeSeriesJavaScriptIndex.cs
  src/Raven.Server/Web/Studio/StudioIndexHandler.cs
  test/FastTests/Server/Documents/Indexing/MapReduce/ReduceKeyProcessorTests.cs
  test/SlowTests/Issues/RavenDB_17572.cs
  test/SlowTests/Server/Documents/Indexing/Auto/RavenDB_9535.cs
Labels: v5.2

#13149 4.2 to 5.1 merge
  src/Raven.Client/Documents/Linq/RavenQueryProvider.cs
  src/Raven.Client/Documents/Operations/Backups/BackupSettings.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/PeriodicBackup/Aws/RavenAwsS3Client.cs
  src/Raven.Server/Rachis/Leader.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/ServerWide/Commands/AddOrUpdateCompareExchangeBatchCommand.cs
  src/Raven.Server/ServerWide/Commands/CommandBase.cs
  src/Raven.Server/ServerWide/Commands/CompareExchangeCommands.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
  src/Raven.Server/Web/System/CompareExchangeHandler.cs
  src/Raven.Studio/typescript/models/database/tasks/periodicBackup/s3Settings.ts
  src/Raven.Studio/typescript/models/resources/creation/backupCredentials.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/columnPreviewPlugin.ts
  src/Raven.Studio/wwwroot/App/views/partial/backupDestinations.html
  src/Raven.Studio/wwwroot/App/views/resources/createDatabase.html
  test/SlowTests/Issues/RavenDB-16961.cs
  test/SlowTests/Issues/RavenDB-17574.cs
  test/SlowTests/Issues/RavenDB_16966.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Restore/RestoreFromS3.cs
Labels: v5.1

#13151 RavenDB-15637 Added passing tests to make sure we're correctly handling the new parameter for deleteDocumentsOf<collection>Behavior functions, not just the generic one - deleteDocumentsBehavior()
  test/SlowTests/Server/Documents/ETL/RavenDB_15637.cs
Labels: v5.3

#13150 5.1 to 5.2 merge
  src/Raven.Client/Documents/Linq/RavenQueryProvider.cs
  src/Raven.Client/Documents/Operations/Backups/BackupSettings.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/PeriodicBackup/Aws/RavenAwsS3Client.cs
  src/Raven.Server/Rachis/Leader.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/ServerWide/Commands/AddOrUpdateCompareExchangeBatchCommand.cs
  src/Raven.Server/ServerWide/Commands/CommandBase.cs
  src/Raven.Server/ServerWide/Commands/CompareExchangeCommands.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
  src/Raven.Server/Web/System/CompareExchangeHandler.cs
  src/Raven.Studio/typescript/models/resources/creation/backupCredentials.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/destinations/s3Settings.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/columnPreviewPlugin.ts
  src/Raven.Studio/wwwroot/App/views/database/tasks/destinations/s3Settings.html
  src/Raven.Studio/wwwroot/App/views/resources/createDatabase.html
  test/SlowTests/Issues/RavenDB-16961.cs
  test/SlowTests/Issues/RavenDB-17574.cs
  test/SlowTests/Issues/RavenDB_16966.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Restore/RestoreFromS3.cs
Labels: v5.2

#13153 RavenDB-17542 Add ForcePathStyle to S3 Settings
  src/Raven.Studio/typescript/viewmodels/resources/createDatabase.ts
  src/Raven.Studio/wwwroot/App/views/database/tasks/destinations/s3Settings.html
  src/Raven.Studio/wwwroot/App/views/resources/createDatabase.html
Labels: v5.2

#13152 5.2 to 5.3 merge
  src/Raven.Client/Documents/Linq/RavenQueryProvider.cs
  src/Raven.Client/Documents/Operations/Backups/BackupSettings.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Handlers/IndexHandler.cs
  src/Raven.Server/Documents/Indexes/IndexDefinitionBase.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  src/Raven.Server/Documents/Indexes/MapReduce/Auto/AutoMapReduceIndex.cs
  src/Raven.Server/Documents/Indexes/MapReduce/ReduceKeyProcessor.cs
  src/Raven.Server/Documents/Indexes/MapReduce/Static/MapReduceIndex.cs
  src/Raven.Server/Documents/Indexes/Static/AbstractCountersAndTimeSeriesJavaScriptIndex.cs
  src/Raven.Server/Documents/Indexes/Static/Counters/CountersJavaScriptIndex.cs
  src/Raven.Server/Documents/Indexes/Static/Counters/MapCountersIndex.cs
  src/Raven.Server/Documents/Indexes/Static/DynamicArray.cs
  src/Raven.Server/Documents/Indexes/Static/IndexCompilationCache.cs
  src/Raven.Server/Documents/Indexes/Static/JavaScriptIndex.cs
  src/Raven.Server/Documents/Indexes/Static/JavaScriptReduceOperation.cs
  src/Raven.Server/Documents/Indexes/Static/MapIndex.cs
  src/Raven.Server/Documents/Indexes/Static/TimeSeries/MapTimeSeriesIndex.cs
  src/Raven.Server/Documents/Indexes/Static/TimeSeries/TimeSeriesJavaScriptIndex.cs
  src/Raven.Server/Documents/PeriodicBackup/Aws/RavenAwsS3Client.cs
  src/Raven.Server/Rachis/Leader.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/ServerWide/Commands/AddOrUpdateCompareExchangeBatchCommand.cs
  src/Raven.Server/ServerWide/Commands/CommandBase.cs
  src/Raven.Server/ServerWide/Commands/CompareExchangeCommands.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
  src/Raven.Server/Web/Studio/StudioIndexHandler.cs
  src/Raven.Server/Web/System/CompareExchangeHandler.cs
  src/Raven.Studio/typescript/models/resources/creation/backupCredentials.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/destinations/s3Settings.ts
  src/Raven.Studio/typescript/viewmodels/manage/debugAdvancedThreadsRuntime.ts
  src/Raven.Studio/typescript/viewmodels/resources/createDatabase.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/columnPreviewPlugin.ts
  src/Raven.Studio/wwwroot/App/views/database/tasks/destinations/s3Settings.html
  src/Raven.Studio/wwwroot/App/views/manage/threadStackTrace.html
  src/Raven.Studio/wwwroot/App/views/resources/createDatabase.html
  test/FastTests/Server/Documents/Indexing/MapReduce/ReduceKeyProcessorTests.cs
  test/SlowTests/Issues/RavenDB-16961.cs
  test/SlowTests/Issues/RavenDB-17574.cs
  test/SlowTests/Issues/RavenDB_16966.cs
  test/SlowTests/Issues/RavenDB_17543.cs
  test/SlowTests/Issues/RavenDB_17572.cs
  test/SlowTests/MailingList/IndexCompilation.cs
  test/SlowTests/Server/Documents/ETL/Olap/FailoverTests.cs
  test/SlowTests/Server/Documents/Indexing/Auto/RavenDB_9535.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Restore/RestoreFromS3.cs
  test/SlowTests/Server/Replication/ReplicationCleanTombstones.cs
  test/SlowTests/Smuggler/SmugglerApiTests.cs
Labels: v5.3

#13154 RavenDB-17430 Create new icon for the Thread's Stack Trace
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.eot
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.svg
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.ttf
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.woff
  src/Raven.Studio/wwwroot/Content/css/icons.less
Labels: v5.1

#13148 RavenDB-17308 Using mmap() instead of posix_memalign() when allocating 4KB aligned memory for the encryption buffers and journal reader recovery.
  src/Sparrow.Server/Platform/PlatformSpecific.cs
Labels: v4.2

#13158 RavenDB-17170 : fix flaky test
  test/SlowTests/Server/Documents/ETL/EtlTestBase.cs
  test/SlowTests/Server/Documents/ETL/EtlTimeSeriesTests.cs
Labels: v5.1

#13163 RavenDB-15502
  test/SlowTests/Issues/RavenDB-15080.cs
Labels: v5.1

#13156 RavenDB-17587 Incremental time-series import should overwrite existing values
  src/Raven.Server/Documents/Handlers/TimeSeriesHandler.cs
  src/Raven.Server/Documents/Patch/ScriptRunner.cs
  src/Raven.Server/Documents/Replication/IncomingReplicationHandler.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesRollups.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesStorage.cs
  test/SlowTests/Server/Documents/ETL/ClusterEtlTimeSeriesTests.cs
  test/SlowTests/Server/Documents/ETL/EtlTimeSeriesTests.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
  test/SlowTests/Smuggler/SmugglerApiTests.cs
  test/Tests.Infrastructure/BackupTestBase.cs
Labels: v5.3

#13165 5.1 to 5.2 merge
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.eot
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.svg
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.ttf
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.woff
  src/Raven.Studio/wwwroot/Content/css/icons.less
  src/Sparrow.Server/Platform/PlatformSpecific.cs
  test/SlowTests/Issues/RavenDB-15080.cs
  test/SlowTests/Server/Documents/ETL/EtlTimeSeriesTests.cs
Labels: v5.2

#13159 RavenDB-17547 Add button to refresh database stats in Studio
  src/Raven.Studio/typescript/viewmodels/database/status/statistics.ts
  src/Raven.Studio/wwwroot/App/views/database/status/statistics.html
Labels: v4.2

#13157 RavenDB-17125 Report the Responsible Node for the Hub Task
  src/Raven.Studio/wwwroot/App/views/database/tasks/ongoingTasks.html
Labels: v5.1

#13168 5.2 to 5.3 merge
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.eot
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.svg
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.ttf
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.woff
  src/Raven.Studio/wwwroot/Content/css/icons.less
  src/Sparrow.Server/Platform/PlatformSpecific.cs
  test/SlowTests/Issues/RavenDB-15080.cs
  test/SlowTests/Server/Documents/ETL/EtlTimeSeriesTests.cs
Labels: v5.3

#13175 RavenDB-17590 Fixing Benchmark tests when using encryption
  test/BenchmarkTests/BenchmarkTestBase.cs
  test/BenchmarkTests/Indexing/Index.cs
  test/BenchmarkTests/Patching/Patch.cs
Labels: v4.2

#13184 RavenDB-17596 handle zstd sos in deb build
  scripts/linux/pkg/deb/assets/ravendb/debian/rules
Labels: v5.2

#13179 RavenDB-17549 - Infinity loop inside BinaryMatch
  src/Corax/Queries/MergeHelper.cs
  src/Corax/Queries/MultiTermMatch.cs
  test/FastTests/Corax/CoraxQueries.cs
Labels: Corax

#13178 RavenDB-17219 : flaky test
  test/StressTests/Server/Documents/ETL/Olap/LocalTestsStress.cs
Labels: v5.2

#13167 RavenDB-15357: increase subscription timeout in test
  test/SlowTests/Client/Subscriptions/LimitSubscriptionsConnectionsAmount.cs
Labels: v5.2

#12950 RavenDB-16371 introduced IndexStartupBehavior
  src/Raven.Server/Config/Categories/IndexingConfiguration.cs
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  test/SlowTests/Issues/RavenDB_14641.cs
  test/SlowTests/Issues/RavenDB_16371.cs
Labels: v4.2

#13185 RavenDB-17369 Autocomplete enhancements
  src/Raven.Studio/aceBuild/addons/lib/ace/mode/rql_highlight_rules.js
  src/Raven.Studio/languageService/src/autocompleteUtils.ts
  src/Raven.Studio/languageService/src/providers/fields.ts
  src/Raven.Studio/languageService/src/providers/keywords.ts
  src/Raven.Studio/languageService/test/TRASH.ts
  src/Raven.Studio/languageService/test/autocomplete/FakeMetadataProvider.ts
  src/Raven.Studio/languageService/test/autocomplete/fields.spec.ts
  src/Raven.Studio/languageService/test/autocomplete/from.spec.ts
  src/Raven.Studio/languageService/test/autocomplete/include.spec.ts
  src/Raven.Studio/languageService/test/autocomplete/where.spec.ts
  src/Raven.Studio/wwwroot/Content/ace/mode-rql.js
Labels: v5.3

#13190 4.2 to 5.1 merge
  src/Raven.Server/Config/Categories/IndexingConfiguration.cs
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/Handlers/TransactionsRecordingHandler.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  src/Raven.Server/Documents/Indexes/MapReduce/OutputToCollection/OutputReduceIndexWriteOperation.cs
  src/Raven.Server/Documents/Indexes/MapReduce/OutputToCollection/OutputReduceToCollectionActions.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/LuceneIndexPersistence.cs
  src/Raven.Studio/typescript/viewmodels/database/status/statistics.ts
  src/Raven.Studio/typescript/viewmodels/manage/debugAdvancedRecordTransactionCommands.ts
  src/Raven.Studio/wwwroot/App/views/database/status/statistics.html
  src/Raven.Studio/wwwroot/App/views/manage/debugAdvancedRecordTransactionCommands.html
  src/Raven.Studio/wwwroot/App/views/manage/debugAdvancedReplayTransactionCommands.html
  test/BenchmarkTests/BenchmarkTestBase.cs
  test/BenchmarkTests/Indexing/Index.cs
  test/BenchmarkTests/Patching/Patch.cs
  test/SlowTests/Issues/RavenDB_14641.cs
  test/SlowTests/Issues/RavenDB_16371.cs
Labels: v5.1
