Repository ravendb/ravendb, pull requests merged in 2021-08, with the labels that each got.

#12605 RavenDB-17054 We need to get the write lock when accessing compression.buffers during ZeroCompressionBuffer() call.
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  test/SlowTests/Voron/Issues/RavenDB_17054.cs
Labels: v4.2

#12613 RavenDB-17087 IndexCompilationException in index with recurse using a…
  src/Raven.Client/Documents/Indexes/ExpressionStringBuilder.cs
  test/SlowTests/Issues/RavenDB-17087.cs
Labels: v5.2

#12617 RavenDB-17013 Cluster Dashboard Widgets: Highlighted rows (Stripes) …
  src/Raven.Studio/typescript/widgets/virtualGrid/virtualRow.ts
Labels: v5.2

#12612 RavenDB-17076 Import - check ClusterTransactionId for null
  src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
Labels: v5.2

#12600 RavenDB-17080 Clicking on empty space pops up abort dialog - Fix
  src/Raven.Studio/wwwroot/App/views/manage/infoPackage.html
Labels: v5.2

#12593 RavenDB-17027 Going to recent document doesn't always work
  src/Raven.Studio/typescript/viewmodels/database/documents/editDocument.ts
Labels: v5.1

#12620 RavenDB-17079 fix - `Attachments.GetNames ` not returning the correct number of attachment after deletion
  src/Raven.Client/Documents/Session/Operations/BatchOperation.cs
  test/SlowTests/Issues/RavenDB-17079.cs
Labels: v4.2

#12619 RavenDB-16808 `session.Advanced.NumberOfRequests` increased when no request sent because of aggressive cache
  test/SlowTests/Issues/RavenDB_16808cs.cs
Labels: v4.2

#12621 4.2 to 5.1 merge
  src/Raven.Server/Documents/DatabaseRequestHandler.cs
  src/Raven.Server/Documents/Handlers/CollectionsHandler.cs
  src/Raven.Server/Documents/Handlers/DocumentHandler.cs
  src/Raven.Server/Documents/Handlers/QueriesHandler.cs
  src/Raven.Server/Documents/Handlers/RevisionsHandler.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/LuceneIndexPersistence.cs
  src/Raven.Server/Json/BlittableJsonTextWriterExtensions.cs
  src/Raven.Server/NotificationCenter/Notifications/Details/PagingPerformanceDetails.cs
  src/Raven.Server/NotificationCenter/Paging.cs
  src/Raven.Server/Web/System/CompareExchangeHandler.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/Impl/LowLevelTransaction.cs
  src/Voron/Impl/Scratch/ScratchBufferPool.cs
  src/Voron/StorageEnvironment.cs
  test/SlowTests/Issues/RavenDB_17018.cs
  test/SlowTests/Voron/Issues/RavenDB_17054.cs
  test/SlowTests/Voron/Issues/RavenDB_17088.cs
Labels: v5.1

#12624 5.1 to 5.2 merge
  src/Raven.Server/Documents/DatabaseRequestHandler.cs
  src/Raven.Server/Documents/Handlers/CollectionsHandler.cs
  src/Raven.Server/Documents/Handlers/DocumentHandler.cs
  src/Raven.Server/Documents/Handlers/QueriesHandler.cs
  src/Raven.Server/Documents/Handlers/RevisionsHandler.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/LuceneIndexPersistence.cs
  src/Raven.Server/Json/BlittableJsonTextWriterExtensions.cs
  src/Raven.Server/NotificationCenter/Notifications/Details/PagingPerformanceDetails.cs
  src/Raven.Server/NotificationCenter/Paging.cs
  src/Raven.Server/Web/System/CompareExchangeHandler.cs
  src/Raven.Studio/typescript/models/database/status/storageReportItem.ts
  src/Raven.Studio/typescript/viewmodels/database/documents/editDocument.ts
  src/Raven.Studio/typescript/viewmodels/database/status/storageReport.ts
  src/Raven.Studio/typescript/viewmodels/manage/storageReport.ts
  src/Raven.Studio/wwwroot/Content/css/pages/storage-report.less
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/Impl/LowLevelTransaction.cs
  src/Voron/Impl/Scratch/ScratchBufferPool.cs
  src/Voron/StorageEnvironment.cs
  test/SlowTests/Issues/RavenDB_17018.cs
  test/SlowTests/Voron/Issues/RavenDB_17054.cs
  test/SlowTests/Voron/Issues/RavenDB_17088.cs
Labels: v5.2

#12625 RavenDB-14721 Path selector is not updated when creating a db
  src/Raven.Studio/typescript/viewmodels/resources/createDatabase.ts
  src/Raven.Studio/wwwroot/App/views/resources/createDatabase.html
Labels: v5.2

#12623 RavenDB-13470 Replication stats graph - Added number of replicated co…
  src/Raven.Client/Documents/Replication/IncomingReplicationPerformanceStats.cs
  src/Raven.Server/Documents/Replication/IncomingReplicationHandler.cs
  src/Raven.Server/Documents/Replication/IncomingReplicationStatsAggregator.cs
  src/Raven.Studio/typescript/viewmodels/database/status/ongoingTasksStats.ts
Labels: v4.2

#12627 RavenDB-16857
  src/Raven.Server/Documents/Indexes/IndexStore.cs
Labels: v5.2

#12626 RavenDB-16857
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
Labels: v4.2

#12630 RavenDB-17018 Fixed bug causing crash while accumulating totalDocumentsSize of null CompareExchange values
  src/Raven.Server/Web/System/CompareExchangeHandler.cs
  test/SlowTests/Issues/RavenDB_17018.cs
Labels: v4.2

#12622 RavenDB-16961 Enforce revision handle document tombstone
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  test/SlowTests/Issues/RavenDB-16961.cs
Labels: v4.2

#12634 RavenDB-17098 Traffic Watch view - Fix missing tooltip for source column
  src/Raven.Studio/typescript/viewmodels/manage/trafficWatch.ts
Labels: v5.2

#12642 RavenDB-17103 Fix handling of index id
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexes.ts
Labels: v5.2

#12638 RavenDB-17006 We need to use RemoteCertificateValidationCallback for the cluster dashboard websocket when connecting to a remote node.
  src/Raven.Server/NotificationCenter/Handlers/ProxyWebSocketConnection.cs
  test/SlowTests/Issues/RavenDB_17006.cs
Labels: v5.2

#12639 RavenDB-17102 Revert "RavenDB-17005 Fix support for PBEwithHmacSHA-256 encrypted ce…
  src/Raven.Server/ServerWide/SecretProtection.cs
Labels: v5.2

#12645 RavenDB-17108 Try to avoid stack overflow on overly complex indexing …
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/LuceneDocumentConverterBase.cs
  src/Raven.Server/Utils/TypeConverter.cs
Labels: v5.2

#12647 4.2 to 5.1 merge
  src/Raven.Client/Documents/Replication/IncomingReplicationPerformanceStats.cs
  src/Raven.Client/Documents/Session/Operations/BatchOperation.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  src/Raven.Server/Documents/Replication/IncomingReplicationStatsAggregator.cs
  src/Raven.Server/Documents/Replication/ReplicationItems/CounterReplicationItem.cs
  src/Raven.Server/Documents/ResourceCache.cs
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  src/Raven.Server/Json/BlittableJsonTextWriterExtensions.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.1/5.1.7/TotalDatabaseCountOfStaleIndexes.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.1/5.1.7/TotalDatabaseNumberOfErrorIndexes.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.1/5.1.7/TotalDatabaseNumberOfIndexes.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.1/5.1.8/TotalDatabaseMapIndexIndexedPerSecond.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.1/5.1.8/TotalDatabaseMapReduceIndexMappedPerSecond.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.1/5.1.8/TotalDatabaseMapReduceIndexReducedPerSecond.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.1/DatabaseBase.cs
  src/Raven.Server/Monitoring/Snmp/SnmpOids.cs
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Web/System/CompareExchangeHandler.cs
  src/Raven.Studio/typescript/viewmodels/database/status/ongoingTasksStats.ts
  test/SlowTests/Issues/EncryptedDatabaseGroup.cs
  test/SlowTests/Issues/RavenDB-16961.cs
  test/SlowTests/Issues/RavenDB-17079.cs
  test/SlowTests/Issues/RavenDB_16808cs.cs
  test/SlowTests/Issues/RavenDB_17018.cs
  test/Tests.Infrastructure/RavenTestBase.cs
Labels: v5.1

#12648 5.1 to 5.2 merge
  src/Raven.Client/Documents/Replication/IncomingReplicationPerformanceStats.cs
  src/Raven.Client/Documents/Session/Operations/BatchOperation.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  src/Raven.Server/Documents/Replication/IncomingReplicationStatsAggregator.cs
  src/Raven.Server/Documents/Replication/ReplicationItems/CounterReplicationItem.cs
  src/Raven.Server/Documents/ResourceCache.cs
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  src/Raven.Server/Json/BlittableJsonTextWriterExtensions.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.1/5.1.7/TotalDatabaseCountOfStaleIndexes.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.1/5.1.7/TotalDatabaseNumberOfErrorIndexes.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.1/5.1.7/TotalDatabaseNumberOfIndexes.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.1/5.1.8/TotalDatabaseMapIndexIndexedPerSecond.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.1/5.1.8/TotalDatabaseMapReduceIndexMappedPerSecond.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.1/5.1.8/TotalDatabaseMapReduceIndexReducedPerSecond.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.1/DatabaseBase.cs
  src/Raven.Server/Monitoring/Snmp/SnmpOids.cs
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Web/System/CompareExchangeHandler.cs
  src/Raven.Studio/typescript/viewmodels/database/status/ongoingTasksStats.ts
  test/SlowTests/Issues/EncryptedDatabaseGroup.cs
  test/SlowTests/Issues/RavenDB-16961.cs
  test/SlowTests/Issues/RavenDB-17079.cs
  test/SlowTests/Issues/RavenDB_16808cs.cs
  test/SlowTests/Issues/RavenDB_17018.cs
  test/Tests.Infrastructure/RavenTestBase.cs
Labels: v5.2

#12651 RavenDB-17113 Remove text-center form notifications
  src/Raven.Studio/wwwroot/App/views/common/notificationCenter/detailViewer/alerts/etlTransformOrLoadErrorDetails.html
  src/Raven.Studio/wwwroot/App/views/common/notificationCenter/detailViewer/alerts/genericAlertDetails.html
  src/Raven.Studio/wwwroot/App/views/common/notificationCenter/detailViewer/alerts/newVersionAvailableDetails.html
  src/Raven.Studio/wwwroot/App/views/common/notificationCenter/detailViewer/licenseLimitDetails.html
  src/Raven.Studio/wwwroot/App/views/common/notificationCenter/detailViewer/operations/bulkInsertDetails.html
  src/Raven.Studio/wwwroot/App/views/common/notificationCenter/detailViewer/operations/replayTransactionCommandsDetails.html
  src/Raven.Studio/wwwroot/App/views/common/notificationCenter/detailViewer/performanceHint/hugeDocumentsDetails.html
  src/Raven.Studio/wwwroot/App/views/common/notificationCenter/detailViewer/performanceHint/indexingDetails.html
  src/Raven.Studio/wwwroot/App/views/common/notificationCenter/detailViewer/performanceHint/pagingDetails.html
  src/Raven.Studio/wwwroot/App/views/common/notificationCenter/detailViewer/performanceHint/requestLatencyDetails.html
  src/Raven.Studio/wwwroot/App/views/common/notificationCenter/detailViewer/performanceHint/slowSqlDetails.html
  src/Raven.Studio/wwwroot/App/views/common/notificationCenter/detailViewer/performanceHint/slowWriteDetails.html
  src/Raven.Studio/wwwroot/App/views/common/notificationCenter/detailViewer/recentErrorDetails.html
Labels: v5.2

#12655 RavenDB-17119 updated to latest CsvHelper NuGet package
  src/Raven.Server/Documents/Handlers/StreamCsvResultWriter.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Server/Smuggler/Documents/CsvStreamSource.cs
Labels: v5.2

#12661 4.2 to 5.1 merge
  src/Raven.Client/Documents/Changes/EvictItemsFromCacheBasedOnChanges.cs
  src/Raven.Client/Documents/DocumentStore.cs
  src/Raven.Client/Documents/Operations/Replication/InternalReplication.cs
  src/Raven.Client/Http/RequestExecutor.cs
  src/Raven.Client/ServerWide/DatabaseTopology.cs
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  src/Raven.Server/Documents/Replication/ConflictManager.cs
  src/Raven.Server/Documents/Replication/OutgoingReplicationHandler.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/Documents/Replication/ResolveConflictOnReplicationConfigurationChange.cs
  src/Raven.Server/Documents/ResourceCache.cs
  src/Raven.Server/Rachis/Leader.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/Commands/UpdateTopologyCommand.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterMaintenanceWorker.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterObserver.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
  src/Raven.Server/Web/System/DatabasesHandler.cs
  src/Sparrow.Server/AsyncManualResetEvent.cs
  src/Sparrow/Utils/ThreadingHelper.cs
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
  test/RachisTests/DatabaseCluster/ReplicationTests.cs
  test/SlowTests/Issues/RavenDB-12921.cs
  test/SlowTests/Issues/RavenDB-14880.cs
  test/SlowTests/Server/Documents/Indexing/MapReduce/OutputReduceToCollectionTests.cs
  test/SlowTests/Server/Replication/PullReplicationTests.cs
  test/StressTests/Rachis/DatabaseCluster/ClusterDatabaseMaintenanceStress.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
  test/Tests.Infrastructure/RavenTestBase.cs
Labels: v5.1

#12658 RavenDB-16961 test
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  test/SlowTests/Issues/RavenDB-16961.cs
Labels: v4.2

#12671 RavenDB-17058 remove redundant old dependencies
  docker/ravendb-ubuntu/Dockerfile.arm32v7
  docker/ravendb-ubuntu/Dockerfile.x64
Labels: v4.2

#12672 RavenDB-16516 removing OutgoingReplicationHandler from the outgoing list requires immediate disposal since the instance is no longer used
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
Labels: v4.2

#12675 RavenDB-16516 disposing TcpConnectionOptions if we failed to run pull replication as a sink (can fail in IncomingInitialHandshake because stream can be already closed)
  src/Raven.Server/Documents/Replication/OutgoingReplicationHandler.cs
Labels: v4.2

#12676 4.2 to 5.1 merge
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/PeriodicBackup/BackupTask.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestorePointsBase.cs
  src/Raven.Server/Documents/Replication/OutgoingReplicationHandler.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  src/Raven.Server/Documents/TcpHandlers/TcpConnectionOptions.cs
  test/SlowTests/Issues/RavenDB-16961.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Retention.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v5.1

#12677 5.1 to 5.2 merge
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/PeriodicBackup/BackupTask.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestorePointsBase.cs
  src/Raven.Server/Documents/Replication/OutgoingReplicationHandler.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  src/Raven.Server/Documents/TcpHandlers/TcpConnectionOptions.cs
  test/SlowTests/Client/TimeSeries/Policies/TimeSeriesConfigurationTests.cs
  test/SlowTests/Issues/RavenDB-16961.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Retention.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v5.2

#12656 RavenDB-15890 more info to test
  test/SlowTests/Issues/RavenDB-15890.cs
Labels: v5.2

#12657 RavenDB-17105 Collection View: Keep the customized displayed columns …
  src/Raven.Studio/typescript/viewmodels/database/documents/documents.ts
Labels: v5.1

#12654 RavenDB-17023 Allow to create a new ongoing-task as disabled
  src/Raven.Studio/typescript/models/database/tasks/ongoingTaskModel.ts
  src/Raven.Studio/typescript/models/database/tasks/ongoingTaskOlapEtlEditModel.ts
  src/Raven.Studio/typescript/models/database/tasks/ongoingTaskOlapEtlTransformationModel.ts
  src/Raven.Studio/typescript/models/database/tasks/ongoingTaskRavenEtlEditModel.ts
  src/Raven.Studio/typescript/models/database/tasks/ongoingTaskReplicationEditModel.ts
  src/Raven.Studio/typescript/models/database/tasks/ongoingTaskReplicationHubEditModel.ts
  src/Raven.Studio/typescript/models/database/tasks/ongoingTaskReplicationSinkEditModel.ts
  src/Raven.Studio/typescript/models/database/tasks/ongoingTaskSqlEtlEditModel.ts
  src/Raven.Studio/typescript/models/database/tasks/ongoingTaskSubscriptionEditModel.ts
  src/Raven.Studio/typescript/models/database/tasks/periodicBackup/backupConfiguration.ts
  src/Raven.Studio/typescript/models/database/tasks/periodicBackup/manualBackupConfiguration.ts
  src/Raven.Studio/typescript/models/database/tasks/periodicBackup/periodicBackupConfiguration.ts
  src/Raven.Studio/typescript/models/database/tasks/serverWide/serverWideConfigurationModel.ts
  src/Raven.Studio/typescript/models/database/tasks/serverWide/serverWideExternalReplicationEditModel.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editExternalReplicationTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editOlapEtlTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editPeriodicBackupTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editRavenEtlTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editReplicationHubTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editReplicationSinkTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editSqlEtlTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editSubscriptionTask.ts
  src/Raven.Studio/typescript/viewmodels/manage/editServerWideBackup.ts
  src/Raven.Studio/typescript/viewmodels/manage/editServerWideExternalReplication.ts
  src/Raven.Studio/wwwroot/App/views/database/tasks/editExternalReplicationTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editOlapEtlTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editPeriodicBackupTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editRavenEtlTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editReplicationHubTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editReplicationSinkTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editSqlEtlTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editSubscriptionTask.html
  src/Raven.Studio/wwwroot/App/views/manage/editServerWideBackup.html
  src/Raven.Studio/wwwroot/App/views/manage/editServerWideExternalReplication.html
Labels: v5.2

#12683 RavenDB-17138 check for topology update at the end of each request
  src/Raven.Server/Documents/DatabaseRequestHandler.cs
  src/Raven.Server/Web/ServerRequestHandler.cs
  test/StressTests/Cluster/ClusterIndexNotificationsTestStress.cs
Labels: v4.2

#12690 RavenDB-17141 Fix memory leak in DatabasesCache
  src/Raven.Server/Documents/ResourceCache.cs
  test/SlowTests/Issues/RavenDB-17141.cs
Labels: v4.2

#12687 RavenDB-17066 - Fixed Assertion Failed at `string.IsNullOrEmpty(context.LastDatabaseChangeVector) == false`
  src/Raven.Server/Documents/Replication/IncomingReplicationHandler.cs
Labels: v5.2

#12678 RavenDB-16883 added CancellationTokens to few additional flows inside subscriptions to cancel faster when database is being shutdown
  src/Raven.Server/Documents/Subscriptions/SubscriptionStorage.cs
  src/Raven.Server/Documents/TcpHandlers/SubscriptionConnection.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Sparrow/Utils/TimeoutManager.cs
Labels: v4.2

#12680 RavenDB-17129 added 'Security.Certificate.Validation.KeyUsages' configuration option
  src/Raven.Server/Config/Categories/SecurityConfiguration.cs
  src/Raven.Server/ServerWide/SecretProtection.cs
  src/Raven.Server/Web/System/SetupHandler.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v5.2

#12686 RavenDB-17024 Added support for arm64 docker image in build scripts
  docker/build-ubuntu.ps1
  docker/common.ps1
  docker/ravendb-ubuntu/Dockerfile.arm64v8
Labels: v4.2

#12692 RavenDB-17141 fix test
  test/SlowTests/Issues/RavenDB-17141.cs
Labels: v4.2

#12688 RavenDB-17048 - Make `/admin/debug/memory/gc` EP more human readable
  src/Raven.Server/Documents/Handlers/Debugging/MemoryDebugHandler.cs
Labels: v5.1

#12691 4.2 to 5.1 merge
  docker/build-ubuntu.ps1
  docker/common.ps1
  docker/ravendb-ubuntu/Dockerfile.arm64v8
  src/Raven.Client/Documents/Subscriptions/SubscriptionBatch.cs
  src/Raven.Server/Documents/DatabaseRequestHandler.cs
  src/Raven.Server/Documents/Includes/IncludeDocumentsCommand.cs
  src/Raven.Server/Documents/ResourceCache.cs
  src/Raven.Server/Documents/Subscriptions/SubscriptionStorage.cs
  src/Raven.Server/Documents/TcpHandlers/SubscriptionConnection.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Web/ServerRequestHandler.cs
  src/Sparrow/Utils/TimeoutManager.cs
  test/SlowTests/Issues/RavenDB-16975.cs
  test/SlowTests/Issues/RavenDB-17141.cs
  test/StressTests/Cluster/ClusterIndexNotificationsTestStress.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v5.1

#12693 5.1 to 5.2 merge
  docker/build-ubuntu.ps1
  docker/common.ps1
  docker/ravendb-ubuntu/Dockerfile.arm64v8
  src/Raven.Client/Documents/Subscriptions/SubscriptionBatch.cs
  src/Raven.Server/Documents/DatabaseRequestHandler.cs
  src/Raven.Server/Documents/Handlers/Debugging/MemoryDebugHandler.cs
  src/Raven.Server/Documents/Includes/IncludeDocumentsCommand.cs
  src/Raven.Server/Documents/ResourceCache.cs
  src/Raven.Server/Documents/Subscriptions/SubscriptionStorage.cs
  src/Raven.Server/Documents/TcpHandlers/SubscriptionConnection.cs
  src/Raven.Server/Json/BlittableJsonTextWriterExtensions.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Web/ServerRequestHandler.cs
  src/Raven.Studio/typescript/viewmodels/database/documents/documents.ts
  src/Sparrow/Utils/TimeoutManager.cs
  test/SlowTests/Issues/RavenDB-16975.cs
  test/SlowTests/Issues/RavenDB-17141.cs
  test/StressTests/Cluster/ClusterIndexNotificationsTestStress.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v5.2

#12695 RavenDB-17024 Add support for arm64 Docker image in build scripts
  docker/common.ps1
  docker/ravendb-ubuntu/Dockerfile.arm64v8
Labels: v5.1

#12696 RavenDB-17024 Add support for arm64 Docker image in build scripts
  docker/common.ps1
  docker/ravendb-ubuntu/Dockerfile.arm64v8
Labels: v5.2

#12701 RavenDB-16494 Review `as` operators in typescript - part II
  src/Raven.Studio/typescript/commands/resources/getRestorePointsCommand.ts
  src/Raven.Studio/typescript/common/appUrl.ts
  src/Raven.Studio/typescript/common/messagePublisher.ts
  src/Raven.Studio/typescript/common/settings/abstractSettings.ts
  src/Raven.Studio/typescript/models/database/documents/recentDocuments.ts
  src/Raven.Studio/typescript/models/database/documents/timeSeriesPolicy.ts
  src/Raven.Studio/typescript/models/database/index/indexDefinition.ts
  src/Raven.Studio/typescript/models/database/index/indexFieldOptions.ts
  src/Raven.Studio/typescript/models/database/settings/databaseSettingsModels.ts
  src/Raven.Studio/typescript/models/database/tasks/ongoingTaskReplicationHubEditModel.ts
  src/Raven.Studio/typescript/models/database/tasks/serverWide/serverWideBackupListModel.ts
  src/Raven.Studio/typescript/models/database/tasks/serverWide/serverWideExternalReplicationEditModel.ts
  src/Raven.Studio/typescript/models/database/tasks/serverWide/serverWideExternalReplicationListModel.ts
  src/Raven.Studio/typescript/models/resources/clusterDashboard/lineChart.ts
  src/Raven.Studio/typescript/models/resources/serverDashboard/dashboardChart.ts
  src/Raven.Studio/typescript/models/wizard/serverSetup.ts
  src/Raven.Studio/typescript/viewmodels/common/cronEditor.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/alerts/etlTransformOrLoadErrorDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/compactDatabaseDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/enforceRevisionsConfigurationDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/revertRevisionsDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/smugglerDatabaseDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/performanceHint/hugeDocumentsDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/performanceHint/indexingDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/performanceHint/pagingDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/performanceHint/requestLatencyDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/performanceHint/slowSqlDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/performanceHint/slowWriteDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/timeSeriesPlotDetails.ts
  src/Raven.Studio/typescript/viewmodels/database/documents/editDocument.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexErrors.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/visualizer/visualizerGraphDetails.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/visualizer/visualizerTreeExplorer.ts
  src/Raven.Studio/typescript/viewmodels/database/query/query.ts
  src/Raven.Studio/typescript/viewmodels/database/settings/revertRevisions.ts
  src/Raven.Studio/typescript/viewmodels/database/status/ongoingTasksStats.ts
  src/Raven.Studio/typescript/viewmodels/database/status/statistics.ts
  src/Raven.Studio/typescript/viewmodels/database/status/storageReport.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/backups.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editRavenEtlTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/importDatabaseFromSql.ts
  src/Raven.Studio/typescript/viewmodels/database/timeSeries/editTimeSeries.ts
  src/Raven.Studio/typescript/viewmodels/manage/debugAdvancedMemoryMappedFiles.ts
  src/Raven.Studio/typescript/viewmodels/manage/debugAdvancedObserverLog.ts
  src/Raven.Studio/typescript/viewmodels/manage/serverWideTasks.ts
  src/Raven.Studio/typescript/viewmodels/manage/trafficWatch.ts
  src/Raven.Studio/typescript/viewmodels/partial/columnsSelector.ts
  src/Raven.Studio/typescript/viewmodels/resources/serverDashboard.ts
  src/Raven.Studio/typescript/viewmodels/resources/widgets/websocketBasedWidget.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/columns/customColumn.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/columns/providers/documentBasedColumnsProvider.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/virtualGrid.ts
  src/Raven.Studio/typings/_studio/dto.d.ts
Labels: v5.2

#12706 RavenDB-17144 Ctrl+D/EOF handling
  tools/rvn/AdminChannel.cs
Labels: v4.2

#12699 RavenDB-17148 Set TasksMax to infinity in ravendb service systemd uni…
  scripts/linux/pkg/deb/assets/ravendb/debian/ravendb.service
  scripts/linux/ravendb.service
Labels: v4.2

#12705 RavenDB-16943 - Test ShouldRetrain on TableValueCompressor
  src/Voron/Data/Tables/TableValueCompressor.cs
Labels: v5.2

#12707 RavenDB-16811 Retry assert if the thread didn't update in the thread list yet
  test/FastTests/Server/ThreadUsageTests.cs
Labels: v4.2
