Repository ravendb/ravendb, pull requests merged in 2021-09, with the labels that each got.

#12719 4.2 to 5.1 merge
  src/Raven.Client/Http/RequestExecutor.cs
  src/Raven.Server/Config/Categories/BackupConfiguration.cs
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/Handlers/Debugging/MemoryDebugHandler.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/LuceneIndexPersistence.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/LuceneSuggestionIndexWriter.cs
  src/Raven.Server/Documents/PeriodicBackup/Aws/RavenAwsClient.cs
  src/Raven.Server/Documents/PeriodicBackup/Aws/RavenAwsGlacierClient.cs
  src/Raven.Server/Documents/PeriodicBackup/Aws/RavenAwsS3Client.cs
  src/Raven.Server/Documents/PeriodicBackup/Azure/RavenAzureClient.cs
  src/Raven.Server/Documents/PeriodicBackup/BackupTask.cs
  src/Raven.Server/Documents/PeriodicBackup/BackupUploader.cs
  src/Raven.Server/Documents/PeriodicBackup/GoogleCloud/RavenGoogleCloudClient.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/AzureRestorePoints.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/GoogleCloudRestorePoints.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreFromAzure.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreFromGoogleCloud.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreFromS3.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/S3RestorePoints.cs
  src/Raven.Server/Documents/ResourceCache.cs
  src/Raven.Server/Indexing/LuceneVoronDirectory.cs
  src/Raven.Server/Indexing/TempFileCache.cs
  src/Raven.Server/Rachis/RachisLogHistory.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/Web/Studio/StudioTasksHandler.cs
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
  src/Sparrow.Server/Sodium.cs
  src/Voron/Impl/Paging/AbstractPager.cs
  src/Voron/Impl/Paging/Windows32BitsMemoryMapPager.cs
  test/SlowTests/Issues/EncryptedDatabaseGroup.cs
  test/SlowTests/Issues/RavenDB-17141.cs
  test/SlowTests/Issues/RavenDB_16511.cs
  test/SlowTests/Issues/RavenDB_9381.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Aws.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Azure.cs
  test/SlowTests/Server/Documents/PeriodicBackup/CloudBackupTestBase.cs
  test/SlowTests/Server/Documents/PeriodicBackup/GoogleCloud.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Restore/RestoreFromGoogleCloud.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Restore/RestoreFromS3.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Retention.cs
  test/SlowTests/Tests/TempFileCacheTests.cs
  test/StressTests/Server/Encryption/EncryptionStressTests.cs
  test/Tests.Infrastructure/RavenTestBase.cs
Labels: v5.1

#12720 5.1 to 5.2 merge
  src/Raven.Client/Http/RequestExecutor.cs
  src/Raven.Server/Config/Categories/BackupConfiguration.cs
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/ETL/Providers/OLAP/OlaptEtl.cs
  src/Raven.Server/Documents/Handlers/Debugging/MemoryDebugHandler.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/LuceneIndexPersistence.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/LuceneSuggestionIndexWriter.cs
  src/Raven.Server/Documents/PeriodicBackup/Aws/RavenAwsClient.cs
  src/Raven.Server/Documents/PeriodicBackup/Aws/RavenAwsGlacierClient.cs
  src/Raven.Server/Documents/PeriodicBackup/Aws/RavenAwsS3Client.cs
  src/Raven.Server/Documents/PeriodicBackup/Azure/RavenAzureClient.cs
  src/Raven.Server/Documents/PeriodicBackup/BackupTask.cs
  src/Raven.Server/Documents/PeriodicBackup/BackupUploader.cs
  src/Raven.Server/Documents/PeriodicBackup/GoogleCloud/RavenGoogleCloudClient.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/AzureRestorePoints.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/GoogleCloudRestorePoints.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreFromAzure.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreFromGoogleCloud.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreFromS3.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/S3RestorePoints.cs
  src/Raven.Server/Documents/ResourceCache.cs
  src/Raven.Server/Indexing/LuceneVoronDirectory.cs
  src/Raven.Server/Indexing/TempFileCache.cs
  src/Raven.Server/Rachis/RachisLogHistory.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/Web/Studio/StudioTasksHandler.cs
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
  src/Sparrow.Server/Sodium.cs
  src/Voron/Impl/Paging/AbstractPager.cs
  src/Voron/Impl/Paging/Windows32BitsMemoryMapPager.cs
  test/SlowTests/Issues/EncryptedDatabaseGroup.cs
  test/SlowTests/Issues/RavenDB-17141.cs
  test/SlowTests/Issues/RavenDB_16511.cs
  test/SlowTests/Issues/RavenDB_9381.cs
  test/SlowTests/Server/Documents/ETL/EtlTestBase.cs
  test/SlowTests/Server/Documents/ETL/Olap/AzureTests.cs
  test/SlowTests/Server/Documents/ETL/Olap/GoogleCloudTests.cs
  test/SlowTests/Server/Documents/ETL/Olap/S3Tests.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Aws.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Azure.cs
  test/SlowTests/Server/Documents/PeriodicBackup/CloudBackupTestBase.cs
  test/SlowTests/Server/Documents/PeriodicBackup/GoogleCloud.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Restore/RestoreFromGoogleCloud.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Restore/RestoreFromS3.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Retention.cs
  test/SlowTests/Tests/TempFileCacheTests.cs
  test/StressTests/Server/Encryption/EncryptionStressTests.cs
  test/Tests.Infrastructure/RavenTestBase.cs
Labels: v5.2

#12727 RavenDB-17175 Fix conflict between document and deletion on different collections
  src/Raven.Server/Documents/DocumentPutAction.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  test/SlowTests/Server/Replication/ReplicationOfConflicts.cs
Labels: v4.2

#12725 RavenDB-17127: Fixed - Assert cache paging offest is not negative
  src/Raven.Server/Documents/Queries/IndexQueryServerSide.cs
  test/SlowTests/Issues/RavenDB-17127.cs
Labels: v4.2

#12724 RavenDB-17173 fix restore of snapshot backups when compression recovery files were backed up
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreBackupTaskBase.cs
  src/Voron/Data/Tables/TableValueCompressor.cs
  src/Voron/Impl/Backup/FullBackup.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
Labels: v5.1

#12729 4.2 to 5.1 merge
  src/Raven.Server/Config/Categories/BackupConfiguration.cs
  src/Raven.Server/Documents/DocumentPutAction.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/PeriodicBackup/Aws/RavenAwsGlacierClient.cs
  src/Raven.Server/Documents/PeriodicBackup/Aws/RavenAwsS3Client.cs
  src/Raven.Server/Documents/PeriodicBackup/Azure/LegacyRavenAzureClient.cs
  src/Raven.Server/Documents/PeriodicBackup/Azure/RavenAzureClient.cs
  src/Raven.Server/Documents/PeriodicBackup/Azure/ReadOnlyNestedStream.cs
  src/Raven.Server/Documents/PeriodicBackup/BackupUploader.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/AzureRestorePoints.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreFromAzure.cs
  src/Raven.Server/Documents/PeriodicBackup/Retention/AzureRetentionPolicyRunner.cs
  src/Raven.Server/Documents/PeriodicBackup/SubStream.cs
  src/Raven.Server/Documents/Queries/IndexQueryServerSide.cs
  src/Raven.Server/Web/Studio/StudioTasksHandler.cs
  test/SlowTests/Issues/RavenDB-17127.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Azure.cs
  test/SlowTests/Server/Documents/PeriodicBackup/RavenDB-4613.cs
  test/SlowTests/Server/Replication/ReplicationOfConflicts.cs
Labels: v5.1

#12730 5.1 to 5.2 merge
  src/Raven.Server/Config/Categories/BackupConfiguration.cs
  src/Raven.Server/Documents/DocumentPutAction.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/PeriodicBackup/Aws/RavenAwsGlacierClient.cs
  src/Raven.Server/Documents/PeriodicBackup/Aws/RavenAwsS3Client.cs
  src/Raven.Server/Documents/PeriodicBackup/Azure/LegacyRavenAzureClient.cs
  src/Raven.Server/Documents/PeriodicBackup/Azure/RavenAzureClient.cs
  src/Raven.Server/Documents/PeriodicBackup/Azure/ReadOnlyNestedStream.cs
  src/Raven.Server/Documents/PeriodicBackup/BackupUploader.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/AzureRestorePoints.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreBackupTaskBase.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreFromAzure.cs
  src/Raven.Server/Documents/PeriodicBackup/Retention/AzureRetentionPolicyRunner.cs
  src/Raven.Server/Documents/PeriodicBackup/SubStream.cs
  src/Raven.Server/Documents/Queries/IndexQueryServerSide.cs
  src/Raven.Server/Web/Studio/StudioTasksHandler.cs
  src/Voron/Data/Tables/TableValueCompressor.cs
  src/Voron/Impl/Backup/FullBackup.cs
  test/SlowTests/Issues/RavenDB-17127.cs
  test/SlowTests/Server/Documents/ETL/Olap/AzureTests.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Azure.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
  test/SlowTests/Server/Documents/PeriodicBackup/RavenDB-4613.cs
  test/SlowTests/Server/Replication/ReplicationOfConflicts.cs
Labels: v5.2

#12740 RavenDB-17012 - add missing overloads to the interface
  src/Raven.Client/Documents/IDocumentStore.cs
  test/SlowTests/Issues/RavenDB-17012.cs
Labels: v5.2

#12739 RavenDB-17177 use default conventions when deserializing IOperationResult to avoid a situation when serializer with TypeNameHandling.None is used
  src/Raven.Client/Documents/BulkInsert/BulkInsertOperation.cs
  src/Raven.Client/Documents/Operations/GetOperationStateOperation.cs
  src/Raven.Client/Documents/Operations/Operation.cs
  test/SlowTests/Issues/RavenDB_17177.cs
Labels: v4.2

#12732 RavenDB-17183 added OAuth source to the exception message
  src/Raven.Server/Smuggler/Migration/ApiKey/Authenticator.cs
  src/Raven.Server/Smuggler/Migration/ApiKey/ErrorResponseException.cs
Labels: v4.2

#12743 4.2 to 5.1 merge
  docker/ravendb-ubuntu/Dockerfile.arm32v7
  docker/ravendb-ubuntu/Dockerfile.arm64v8
  docker/ravendb-ubuntu/Dockerfile.x64
  docker/ravendb-ubuntu/cert-utils.sh
  docker/ravendb-ubuntu/run-raven.sh
  docker/ravendb-ubuntu/server-utils.sh
  src/Raven.Client/Documents/Session/DocumentInfo.cs
  src/Raven.Client/Documents/Session/InMemoryDocumentSessionOperations.cs
  src/Raven.Client/Documents/Session/Operations/BatchOperation.cs
  src/Raven.Server/Documents/PeriodicBackup/Azure/RavenAzureClient.cs
  src/Raven.Server/Documents/PeriodicBackup/Azure/ReadOnlyNestedStream.cs
  src/Raven.Server/Smuggler/Migration/ApiKey/Authenticator.cs
  src/Raven.Server/Smuggler/Migration/ApiKey/ErrorResponseException.cs
  src/Raven.Server/Web/Studio/LicenseHandler.cs
  test/SlowTests/Issues/RavenDB_13315.cs
  test/SlowTests/Issues/RavenDB_17177.cs
  tools/TypingsGenerator/Program.cs
Labels: v5.1

#12744 5.1 to 5.2 merge
  docker/ravendb-ubuntu/Dockerfile.arm32v7
  docker/ravendb-ubuntu/Dockerfile.arm64v8
  docker/ravendb-ubuntu/Dockerfile.x64
  docker/ravendb-ubuntu/cert-utils.sh
  docker/ravendb-ubuntu/run-raven.sh
  docker/ravendb-ubuntu/server-utils.sh
  src/Raven.Client/Documents/Session/DocumentInfo.cs
  src/Raven.Client/Documents/Session/InMemoryDocumentSessionOperations.cs
  src/Raven.Client/Documents/Session/Operations/BatchOperation.cs
  src/Raven.Server/Documents/PeriodicBackup/Azure/RavenAzureClient.cs
  src/Raven.Server/Documents/PeriodicBackup/Azure/ReadOnlyNestedStream.cs
  src/Raven.Server/Smuggler/Migration/ApiKey/Authenticator.cs
  src/Raven.Server/Smuggler/Migration/ApiKey/ErrorResponseException.cs
  src/Raven.Server/Web/Studio/LicenseHandler.cs
  test/SlowTests/Issues/RavenDB_13315.cs
  test/SlowTests/Issues/RavenDB_17177.cs
  tools/TypingsGenerator/Program.cs
Labels: v5.2

#12745 RavenDB-17193 Use higher timeout when exporting files from a file system using Smuggler
  Raven.Database/Smuggler/SmugglerRemoteFilesOperations.cs
Labels: v3.5

#12742 RavenDB-17184 Readonly certificates - Fix time series
  src/Raven.Studio/wwwroot/App/views/database/settings/timeSeries.html
  src/Raven.Studio/wwwroot/App/views/shell/about.html
Labels: v5.2

#12747 RavenDB-17151 Elastic Search ETL - Create Icon
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.eot
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.svg
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.ttf
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.woff
  src/Raven.Studio/wwwroot/Content/css/icons.less
Labels: v5.2

#12754 RavenDB-17184 ReadOnly certificates - Fix Refresh & Expiration
  src/Raven.Studio/wwwroot/App/views/database/settings/expiration.html
  src/Raven.Studio/wwwroot/App/views/database/settings/refresh.html
Labels: v5.2

#12756 RavenDB-17199 GetZipArchiveForSnapshot() must use a temporary file in…
  src/Raven.Server/Documents/PeriodicBackup/Restore/AzureRestorePoints.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/GoogleCloudRestorePoints.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreBackupTaskBase.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreFromAzure.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreFromGoogleCloud.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreFromS3.cs
Labels: v4.2

#12757 RavenDB-17180 :
  test/SlowTests/Server/Documents/ETL/Olap/LocalTests.cs
Labels: v5.2

#12755 RavenDB-16992 use SwapBytes for the deleted revision etag
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  test/SlowTests/Server/Documents/Revisions/RevisionsReplication.cs
Labels: v4.2

#12721 RavenDB-17146: fix NRE when Operation is completed before AddOperation finish
  src/Raven.Server/Documents/Operations/Operations.cs
Labels: v4.2

#12751 RavenDB-17086 Clear query results when running an empty query
  src/Raven.Studio/typescript/viewmodels/database/query/query.ts
  src/Raven.Studio/wwwroot/App/views/database/query/query.html
Labels: v5.2

#12759 RavenDB-17200
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
  test/SlowTests/Issues/RavenDB_10991.cs
  test/SlowTests/Issues/RavenDB_17200.cs
Labels: v4.2

#12760 4.2 to 5.1 merge
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Operations/Operations.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/AzureRestorePoints.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/GoogleCloudRestorePoints.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreBackupTaskBase.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreFromAzure.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreFromGoogleCloud.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreFromS3.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/S3RestorePoints.cs
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  src/Raven.Server/Utils/DeleteOnCloseZipArchive.cs
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
  src/Raven.Server/Web/System/OngoingTasksHandler.cs
  src/Sparrow.Server/Utils/EchoStream.cs
  src/Voron/Data/RawData/ActiveRawDataSmallSection.cs
  src/Voron/Data/Tables/Table.cs
  test/SlowTests/Issues/RavenDB_10991.cs
  test/SlowTests/Issues/RavenDB_17200.cs
  test/SlowTests/Server/Documents/Revisions/RevisionsReplication.cs
  test/SlowTests/Server/Replication/ReplicationOfConflicts.cs
Labels: v5.1

#12762 5.1 to 5.2 merge
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Operations/Operations.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/AzureRestorePoints.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/GoogleCloudRestorePoints.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreBackupTaskBase.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreFromAzure.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreFromGoogleCloud.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreFromS3.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/S3RestorePoints.cs
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  src/Raven.Server/Utils/DeleteOnCloseZipArchive.cs
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
  src/Raven.Server/Web/System/OngoingTasksHandler.cs
  src/Sparrow.Server/Utils/EchoStream.cs
  src/Voron/Data/RawData/ActiveRawDataSmallSection.cs
  src/Voron/Data/Tables/Table.cs
  test/SlowTests/Issues/RavenDB-16958.cs
  test/SlowTests/Issues/RavenDB-16961.cs
  test/SlowTests/Issues/RavenDB_10991.cs
  test/SlowTests/Issues/RavenDB_17200.cs
  test/SlowTests/Server/Documents/Revisions/RevisionsReplication.cs
  test/SlowTests/Server/Replication/ReplicationOfConflicts.cs
  test/StressTests/Server/Encryption/EncryptionStressTests.cs
Labels: v5.2

#12764 RavenDB-17209 removing Debug assertions because Azure and AWS streams do not support getting length and checking the position
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreBackupTaskBase.cs
Labels: v4.2

#12765 RavenDB-17213 fixing test
  test/SlowTests/Tests/Indexes/DynamicDictionaryIndexesTests.cs
Labels: v4.2

#12766 4.2 to 5.1 merge
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreBackupTaskBase.cs
  test/SlowTests/Tests/Indexes/DynamicDictionaryIndexesTests.cs
Labels: v5.2

#12761 RavenDB-17206 Collection size limitation when using "Not In" clause
  src/Raven.Server/Documents/Queries/LuceneIntegration/InQuery.cs
  test/SlowTests/Issues/RavenDB-17206.cs
Labels: v5.1, v5.2

#12767 RavenDB-16116 time series edit - UI issue
  src/Raven.Studio/typescript/viewmodels/database/timeSeries/editTimeSeries.ts
  src/Raven.Studio/wwwroot/App/views/database/timeSeries/editTimeSeries.html
  src/Raven.Studio/wwwroot/Content/css/pages/time-series-edit.less
Labels: v5.1

#12769 5.1 to 5.2 merge
  src/Raven.Server/Documents/Queries/LuceneIntegration/InQuery.cs
  test/SlowTests/Client/Attachments/AttachmentsStreamTests.cs
  test/SlowTests/Issues/RavenDB-17206.cs
Labels: v5.2

#12771 RavenDB-16890 Broken filtered replication UI
  src/Raven.Studio/wwwroot/App/views/database/tasks/editReplicationHubTask.html
  src/Raven.Studio/wwwroot/Content/css/styles-common.less
Labels: v5.1

#12778 RavenDB-17225 removed space from Tombstones.RetentionTimeWithReplicat…
  src/Raven.Server/Config/Attributes/ConfigurationEntryAttribute.cs
  src/Raven.Server/Config/Categories/TombstoneConfiguration.cs
Labels: v5.1

#12781 RavenDB-16994 ErrorIndexStartupBehavior.ResetAndStart should also apply to Faulty indexes
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  test/SlowTests/Issues/RavenDB_16994.cs
Labels: v5.2

#12780 RavenDB-17130 fixed issue with IfEntityIs returning always null in index
  src/Raven.Server/Documents/Indexes/Static/Extensions/DynamicExtensionMethods.cs
  src/Raven.Server/Documents/Indexes/Static/Extensions/MetadataExtensions.cs
  src/Raven.Server/Documents/Indexes/Static/Roslyn/Rewriters/CollectionNameRetriever.cs
  test/SlowTests/Issues/RavenDB_17130.cs
Labels: v4.2

#12779 RavenDB-17226 exit fast when we have a catastrophic failure in server storage - this will allow services to restart
  src/Raven.Server/ServerWide/ServerStore.cs
Labels: v4.2

#12784 4.2 to 5.1 merge
  scripts/updateFrameworkVersion.ps1
  src/Raven.Embedded/RuntimeFrameworkVersionMatcher.cs
  src/Raven.Embedded/ServerOptions.cs
  src/Raven.Server/Documents/Indexes/Static/Extensions/DynamicExtensionMethods.cs
  src/Raven.Server/Documents/Indexes/Static/Extensions/MetadataExtensions.cs
  src/Raven.Server/Documents/Indexes/Static/Roslyn/Rewriters/CollectionNameRetriever.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.1/5.1.9/TotalDatabaseDataWrittenPerSecond.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.1/5.1.9/TotalDatabaseWritesPerSecond.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.2.X/6/DatabaseDataWrittenPerSecond.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.2.X/6/DatabaseWritesPerSecond.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.7/ServerRequestAverageDuration.cs
  src/Raven.Server/Monitoring/Snmp/SnmpDatabase.cs
  src/Raven.Server/Monitoring/Snmp/SnmpOids.cs
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  test/EmbeddedTests/RuntimeFrameworkVersionMatcherTests.cs
  test/SlowTests/Issues/RavenDB_17130.cs
Labels: v5.1

#12785 5.1 to 5.2 merge
  scripts/updateFrameworkVersion.ps1
  src/Raven.Embedded/RuntimeFrameworkVersionMatcher.cs
  src/Raven.Embedded/ServerOptions.cs
  src/Raven.Server/Config/Attributes/ConfigurationEntryAttribute.cs
  src/Raven.Server/Config/Categories/TombstoneConfiguration.cs
  src/Raven.Server/Documents/Indexes/Static/Extensions/DynamicExtensionMethods.cs
  src/Raven.Server/Documents/Indexes/Static/Extensions/MetadataExtensions.cs
  src/Raven.Server/Documents/Indexes/Static/Roslyn/Rewriters/CollectionNameRetriever.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.1/5.1.9/TotalDatabaseDataWrittenPerSecond.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.1/5.1.9/TotalDatabaseWritesPerSecond.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.2.X/6/DatabaseDataWrittenPerSecond.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.2.X/6/DatabaseWritesPerSecond.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.7/ServerRequestAverageDuration.cs
  src/Raven.Server/Monitoring/Snmp/SnmpDatabase.cs
  src/Raven.Server/Monitoring/Snmp/SnmpOids.cs
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Studio/wwwroot/App/views/database/tasks/editReplicationHubTask.html
  src/Raven.Studio/wwwroot/Content/css/styles-common.less
  test/EmbeddedTests/RuntimeFrameworkVersionMatcherTests.cs
  test/SlowTests/Issues/RavenDB_17130.cs
Labels: v5.2

#12786 RavenDB-17232 Ensure we put the `Artificial` flag properly
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Indexes/MapReduce/OutputToCollection/DeleteReduceOutputDocumentsCommand.cs
  src/Raven.Server/Documents/Indexes/MapReduce/OutputToCollection/OutputReduceToCollectionCommand.cs
  test/SlowTests/Core/Indexing/OutputReduceToCollectionClusterTests.cs
Labels: v4.2

#12789 4.2 to 5.1 merge
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Indexes/MapReduce/OutputToCollection/DeleteReduceOutputDocumentsCommand.cs
  src/Raven.Server/Documents/Indexes/MapReduce/OutputToCollection/OutputReduceToCollectionCommand.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/Fields/FieldCacheKey.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/LuceneDocumentConverterBase.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Server/ServerWide/SecretProtection.cs
  test/SlowTests/Core/Indexing/OutputReduceToCollectionClusterTests.cs
  test/SlowTests/Issues/RavenDB-16889.cs
  test/SlowTests/Issues/RavenDB-16961.cs
  test/SlowTests/Issues/RavenDB_17018.cs
  test/StressTests/Server/Encryption/EncryptionStressTests.cs
  tools/Raven.Debug/Raven.Debug.csproj
Labels: v5.1

#12790 5.1 to 5.2 merge
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Indexes/MapReduce/OutputToCollection/DeleteReduceOutputDocumentsCommand.cs
  src/Raven.Server/Documents/Indexes/MapReduce/OutputToCollection/OutputReduceToCollectionCommand.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/Fields/FieldCacheKey.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/LuceneDocumentConverterBase.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Server/ServerWide/SecretProtection.cs
  test/SlowTests/Core/Indexing/OutputReduceToCollectionClusterTests.cs
  test/SlowTests/Issues/RavenDB_17018.cs
  test/StressTests/Server/Encryption/EncryptionStressTests.cs
  tools/Raven.Debug/Raven.Debug.csproj
Labels: v5.2

#12791 RavenDB-17181 Allow client certificate expiry option in days rather t…
  src/Raven.Studio/typescript/models/auth/certificateModel.ts
  src/Raven.Studio/wwwroot/App/views/manage/certificates.html
Labels: v5.2

#12793 RavenDB-17244 Navigating to non-existing index on index list causes N…
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexes.ts
Labels: v5.2

#12792 RavenDB-17233 Check required role for cluster admin/operator
  src/Raven.Studio/typescript/common/shell/menu/items/manageServer.ts
Labels: v5.2

#12802 RavenDB-17257 Filtering on Threads Runtime Info should check Thread I…
  src/Raven.Studio/typescript/viewmodels/manage/debugAdvancedThreadsRuntime.ts
  src/Raven.Studio/wwwroot/App/views/manage/debugAdvancedThreadsRuntime.html
Labels: v5.2

#12803 RavenDB-17248 When Admin Logs are paused and clear is clicked - it s…
  src/Raven.Studio/typescript/viewmodels/manage/adminLogs.ts
Labels: v5.2

#12805 RavenDB-17018 Add total documents size in performance hint
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/performanceHint/pagingDetails.ts
Labels: v4.2

#12806 RavenDB-17207 OLAP ETL Task: Fix conditions for opening Test Area
  src/Raven.Studio/typescript/models/database/tasks/ongoingTaskOlapEtlEditModel.ts
Labels: v5.2
