Repository ravendb/ravendb, pull requests merged in 2021-12, with the labels that each got.

#13191 5.1 to 5.2 merge
  src/Raven.Server/Config/Categories/IndexingConfiguration.cs
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/Handlers/TransactionsRecordingHandler.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  src/Raven.Server/Documents/Indexes/MapReduce/OutputToCollection/OutputReduceIndexWriteOperation.cs
  src/Raven.Server/Documents/Indexes/MapReduce/OutputToCollection/OutputReduceToCollectionActions.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/LuceneIndexPersistence.cs
  src/Raven.Studio/typescript/commands/database/index/dumpIndexCommand.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/dumpDialog.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/editIndex.ts
  src/Raven.Studio/typescript/viewmodels/database/status/statistics.ts
  src/Raven.Studio/typescript/viewmodels/manage/debugAdvancedRecordTransactionCommands.ts
  src/Raven.Studio/wwwroot/App/views/common/notificationCenter/detailViewer/operations/dumpRawIndexDataDetails.html
  src/Raven.Studio/wwwroot/App/views/database/indexes/dumpDialog.html
  src/Raven.Studio/wwwroot/App/views/database/indexes/editIndex.html
  src/Raven.Studio/wwwroot/App/views/database/status/statistics.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/ongoingTasks.html
  src/Raven.Studio/wwwroot/App/views/manage/debugAdvancedRecordTransactionCommands.html
  src/Raven.Studio/wwwroot/App/views/manage/debugAdvancedReplayTransactionCommands.html
  test/BenchmarkTests/BenchmarkTestBase.cs
  test/BenchmarkTests/Indexing/Index.cs
  test/BenchmarkTests/Patching/Patch.cs
  test/SlowTests/Issues/RavenDB_14641.cs
  test/SlowTests/Issues/RavenDB_16042.cs
  test/SlowTests/Issues/RavenDB_16371.cs
  test/SlowTests/Issues/RavenDB_16994.cs
Labels: v5.2

#13194 5.2. to 5.3 merge
  scripts/linux/pkg/deb/assets/ravendb/debian/rules
  src/Raven.Client/Documents/Indexes/AbstractIndexCreationTask.cs
  src/Raven.Client/Documents/Indexes/ExpressionStringBuilder.cs
  src/Raven.Client/Documents/Indexes/IndexingOperation.cs
  src/Raven.Server/Config/Categories/IndexingConfiguration.cs
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/Handlers/TransactionsRecordingHandler.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  src/Raven.Server/Documents/Indexes/MapReduce/OutputToCollection/OutputReduceIndexWriteOperation.cs
  src/Raven.Server/Documents/Indexes/MapReduce/OutputToCollection/OutputReduceToCollectionActions.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/LuceneIndexPersistence.cs
  src/Raven.Server/Documents/Indexes/Static/EsprimaReferencedCollectionVisitor.cs
  src/Raven.Server/Documents/Indexes/Static/JavaScriptIndex.cs
  src/Raven.Server/Documents/Indexes/Static/Roslyn/MapFunctionProcessor.cs
  src/Raven.Server/Documents/Indexes/Static/Roslyn/Rewriters/MethodDetectorRewriter.cs
  src/Raven.Server/Documents/Indexes/Static/Roslyn/Rewriters/NoTrackingRewriter.cs
  src/Raven.Server/Documents/Indexes/Static/Roslyn/Rewriters/ReduceIndex/ReduceFunctionProcessor.cs
  src/Raven.Studio/typescript/commands/database/debug/getEnvironmentStorageReportCommand.ts
  src/Raven.Studio/typescript/commands/database/index/dumpIndexCommand.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/dumpDialog.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/editIndex.ts
  src/Raven.Studio/typescript/viewmodels/database/status/statistics.ts
  src/Raven.Studio/typescript/viewmodels/database/status/storageReport.ts
  src/Raven.Studio/typescript/viewmodels/manage/debugAdvancedRecordTransactionCommands.ts
  src/Raven.Studio/wwwroot/App/views/common/notificationCenter/detailViewer/operations/dumpRawIndexDataDetails.html
  src/Raven.Studio/wwwroot/App/views/database/indexes/dumpDialog.html
  src/Raven.Studio/wwwroot/App/views/database/indexes/editIndex.html
  src/Raven.Studio/wwwroot/App/views/database/status/statistics.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/ongoingTasks.html
  src/Raven.Studio/wwwroot/App/views/manage/debugAdvancedRecordTransactionCommands.html
  src/Raven.Studio/wwwroot/App/views/manage/debugAdvancedReplayTransactionCommands.html
  src/Voron/Data/Tables/Table.cs
  src/Voron/Data/Tables/TableReport.cs
  src/Voron/Debugging/StorageReportGenerator.cs
  test/BenchmarkTests/BenchmarkTestBase.cs
  test/BenchmarkTests/Indexing/Index.cs
  test/BenchmarkTests/Patching/Patch.cs
  test/SlowTests/Client/Subscriptions/LimitSubscriptionsConnectionsAmount.cs
  test/SlowTests/Issues/RavenDB_14641.cs
  test/SlowTests/Issues/RavenDB_16042.cs
  test/SlowTests/Issues/RavenDB_16353.cs
  test/SlowTests/Issues/RavenDB_16371.cs
  test/SlowTests/Issues/RavenDB_16994.cs
  test/SlowTests/Voron/Storage/StorageReportGenerationTests.cs
  test/StressTests/Server/Documents/ETL/Olap/LocalTestsStress.cs
Labels: v5.3

#13197 RavenDB-17609 exposed OnBeforeRequest and OnSucceedRequest in IDocumentStore
  src/Raven.Client/Documents/IDocumentStore.cs
  test/FastTests/Client/RequestExecutorTests.cs
Labels: v5.2

#13143 RavenDB-17475 - Add Incremental TS to Sample Data
  src/Raven.Server/Web/Studio/EmbeddedData/Northwind.ravendbdump
Labels: v5.3

#13195 RavenDB-16870 : flaky test
  test/SlowTests/Client/TimeSeries/Policies/TimeSeriesConfigurationTests.cs
Labels: v5.1

#13204 RavenDB-17606: Stop index references processing stage when there is memory pressure
  src/Raven.Server/Documents/Indexes/Index.cs
Labels: v4.2

#13186 RavenDB-16689 : adjustments to flaky test
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
  test/SlowTests/Issues/RavenDB-15588.cs
Labels: v4.2

#13206 RavenDB-17462
  test/SlowTests/Issues/RavenDB-17096.cs
  test/SlowTests/Server/Documents/ETL/Olap/FailoverTests.cs
Labels: v5.2

#13139 RavenDB-17281 Query explanations in studio are ordered by id, even if…
  src/Raven.Studio/typescript/viewmodels/database/query/query.ts
Labels: v5.2

#13212 RavenDB-17621 - SlowTests.Voron.Storage.StorageReportGenerationTests.…
  test/SlowTests/Voron/Storage/StorageReportGenerationTests.cs
Labels: v5.2

#13210 RavenDB-17594 Create new icon for 'Dump index files'
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.eot
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.svg
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.ttf
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.woff
  src/Raven.Studio/wwwroot/Content/css/icons.less
Labels: v4.2

#13214 RavenDB-17632 Corax - bump index version and pointer fix.
  src/Corax/Queries/MergeHelper.cs
  src/Raven.Server/Documents/Indexes/IndexDefinitionBase.cs
Labels: Corax

#13203 RavenDB-17606: Stop index references processing stage when there is memory pressure
  src/Raven.Client/Documents/Indexes/ReduceRunDetails.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/IndexingRunStats.cs
  src/Raven.Server/Documents/Indexes/IndexingStatsAggregator.cs
  src/Raven.Server/Documents/Indexes/Workers/CleanupDocuments.cs
  src/Raven.Server/Documents/Indexes/Workers/MapItems.cs
Labels: v5.2

#13196 RavenDB-17311 : flaky test
  test/SlowTests/Issues/RavenDB-17096.cs
Labels: v4.2

#13213 RavenDB-13669 Check actual client-cert before redirecting to error page
  src/Raven.Server/Web/System/StudioHandler.cs
Labels: v4.2

#13219 RavenDB-17627 better exception during SNMP engine start
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
Labels: v4.2

#13189 RavenDB-17579: Cluster command that trigger databases should wait for IndexNotification 4.2
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
  src/Raven.Server/Web/System/AdminServerWideBackupHandler.cs
Labels: v4.2

#13221 4.2 to 5.1 merge
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
  src/Raven.Server/Web/System/StudioHandler.cs
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.eot
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.svg
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.ttf
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.woff
  src/Raven.Studio/wwwroot/Content/css/icons.less
  test/SlowTests/Issues/RavenDB-15588.cs
  test/SlowTests/Issues/RavenDB-17096.cs
Labels: v5.1

#13222 5.1 to 5.2 merge
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
  src/Raven.Server/Web/System/AdminServerWideHandler.cs
  src/Raven.Server/Web/System/StudioHandler.cs
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.eot
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.svg
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.ttf
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.woff
  src/Raven.Studio/wwwroot/Content/css/icons.less
  test/SlowTests/Client/TimeSeries/Policies/TimeSeriesConfigurationTests.cs
  test/SlowTests/Issues/RavenDB-15588.cs
  test/SlowTests/Issues/RavenDB-17096.cs
Labels: v5.2

#13225 5.2 to 5.3 merge
  src/Raven.Client/Documents/IDocumentStore.cs
  src/Raven.Client/Documents/Indexes/ReduceRunDetails.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/IndexingRunStats.cs
  src/Raven.Server/Documents/Indexes/IndexingStatsAggregator.cs
  src/Raven.Server/Documents/Indexes/Workers/CleanupDocuments.cs
  src/Raven.Server/Documents/Indexes/Workers/MapItems.cs
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
  src/Raven.Server/Web/System/AdminServerWideHandler.cs
  src/Raven.Server/Web/System/StudioHandler.cs
  src/Raven.Studio/typescript/models/database/index/index.ts
  src/Raven.Studio/typescript/models/database/index/indexProgress.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexes.ts
  src/Raven.Studio/typescript/viewmodels/database/query/query.ts
  src/Raven.Studio/wwwroot/App/views/database/indexes/indexes.html
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.eot
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.svg
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.ttf
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.woff
  src/Raven.Studio/wwwroot/Content/css/icons.less
  test/FastTests/Client/RequestExecutorTests.cs
  test/SlowTests/Client/TimeSeries/Policies/TimeSeriesConfigurationTests.cs
  test/SlowTests/Issues/RavenDB-15588.cs
  test/SlowTests/Issues/RavenDB-17096.cs
  test/SlowTests/Server/Documents/ETL/Olap/FailoverTests.cs
  test/SlowTests/Voron/Storage/StorageReportGenerationTests.cs
Labels: v5.3

#13231 fixing invalid merge
  src/Raven.Studio/typescript/viewmodels/database/query/query.ts
Labels: v5.3

#13232 RavenDB-17595 Dump Index: Add access level
  src/Raven.Studio/wwwroot/App/views/database/indexes/editIndex.html
Labels: v5.3

#13224 RavenDB-17633: Rearrange the backup timer if the backup got active by other node and then got active by current node while running
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackup.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
Labels: v4.2

#13230 RavenDB-17640 [Corax-Analyzers] Incrementing the outputPtr in Utf8 processing.
  src/Corax/Analyzers/Analyzer.cs
  test/FastTests/Corax/SimplePipeline.cs
Labels: Corax

#13234 4.2 to 5.1 merge
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackup.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
  src/Raven.Server/Rachis/Leader.cs
  src/Raven.Server/Rachis/RachisLogHistory.cs
  src/Raven.Server/Rachis/RachisStateMachine.cs
  test/RachisTests/RavenDB_14348.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
  test/Tests.Infrastructure/RachisConsensusTestBase.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v5.1

#13235 RavenDB-17143 Add more time to test
  test/SlowTests/Server/Replication/PullReplicationTests.cs
Labels: v5.2

#13245 5.1 to 5.2 merge
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackup.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
  src/Raven.Server/Rachis/Leader.cs
  src/Raven.Server/Rachis/RachisLogHistory.cs
  src/Raven.Server/Rachis/RachisStateMachine.cs
  test/RachisTests/RavenDB_14348.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
  test/Tests.Infrastructure/RachisConsensusTestBase.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v5.2

#13275 RavenDB-17477 Fixing possible deadlock caused by calling ConcurrentEsEtlTests.Wait() in the constructor of the test
  test/SlowTests/Server/Documents/ETL/Elasticsearch/ElasticSearchEtlTestBase.cs
  test/SlowTests/Server/Documents/ETL/Elasticsearch/ElasticSearchEtlTests.cs
  test/SlowTests/Server/Documents/ETL/Elasticsearch/RavenDB_17477.cs
Labels: v5.3

#13246 RavenDB-17620 Fixing ocassionally failing test. The problem was the usage of wrong index instance (`replacementIndex` instead of `index`) and that we didn't call `WaitForIndexing(store)` inside `CallDuringFinallyOfExecuteIndexing()`
  test/SlowTests/Issues/RavenDB_17237.cs
Labels: v5.2

#13247 RavenDB-17647 Fixing randomly failing TreeReportContainsPartialInfoAboutStreams test. Let's use megabyte precision.
  test/SlowTests/Voron/Storage/StorageReportGenerationTests.cs
Labels: v5.2

#13262 RavenDB-15552 Awaiting a task in the test instead of waiting for it. hat caused FastTests hangs when running with maxParallelThreads - 1 and maxRunningTests - 1
  test/FastTests/Server/Documents/Revisions/RevisionsTests.cs
Labels: v5.1

#13260 RavenDB-17449 Exception message improvement - adding extra info about transactions that have been skipped the journal
  src/Voron/Impl/Journal/JournalReader.cs
Labels: v4.2

#13248 RavenDB-17260 Let's use the default paths when running in cluster even when running in-memory (we still create some temp files in that mode)
  test/Tests.Infrastructure/RavenTestBase.cs
Labels: v4.2

#13279 RavenDB-17683 Identities View: fix the next document description when…
  src/Raven.Studio/typescript/viewmodels/database/identities/identities.ts
  src/Raven.Studio/wwwroot/App/views/database/identities/identities.html
Labels: v5.3

#13229 RavenDB-17641: Primitives support for search functionality.
  src/Corax/IndexSearcher.cs
  src/Corax/Queries/ITermProvider.cs
  src/Corax/Queries/MultiTermMatch.cs
  src/Corax/Queries/TermProvider.Contains.cs
  src/Corax/Queries/TermProvider.In.cs
  src/Corax/Queries/TermProvider.StartWith.cs
  src/Voron/Data/CompactTrees/CompactTree.Iterator.cs
  src/Voron/Slice.cs
  test/FastTests/Corax/BoostingQuery.cs
  test/FastTests/Corax/IndexSearcher.cs
  test/FastTests/Voron/Slices.cs
Labels: Corax

#13267 RavenDB-15357 cherry pick from v5.2
  test/SlowTests/Client/Subscriptions/LimitSubscriptionsConnectionsAmount.cs
Labels: v5.1

#13298 RavenDB-17715 Studio builds scripts: gulp agonistic
  src/Raven.Studio/package.json
Labels: v4.2

#13293 RavenDB-17204 add more info to test
  test/SlowTests/Rolling/RollingIndexesClusterTests.cs
Labels: v5.2

#13290 RavenDB-17699 Bug with Conditional Gets - 2nd request gives different…
  src/Raven.Client/Documents/Commands/MultiGet/MultiGetCommand.cs
  test/SlowTests/Issues/RavenDB-17699.cs
Labels: v5.3

#13283 RavenDB-16336 : flaky test
  test/StressTests/Server/Documents/ETL/Olap/LocalTestsStress.cs
Labels: v5.2

#13274 RavenDB-17586 distinguish between new subscription and a modified one
  src/Raven.Server/Documents/Subscriptions/SubscriptionStorage.cs
Labels: v5.3

#13273 RavenDB-16003 close subscription worker faster
  src/Raven.Client/Documents/Subscriptions/SubscriptionWorker.cs
Labels: v4.2

#13272 RavenDB-17681 Remove 'try to connect' when viewing imported json
  src/Raven.Studio/wwwroot/App/views/database/indexes/indexPerformance.html
  src/Raven.Studio/wwwroot/App/views/partial/ioStatsGraph.html
Labels: v5.2

#13271 RavenDB-17653 Cluster View: Disable the 'Step Down' option when ther…
  src/Raven.Studio/typescript/viewmodels/manage/cluster.ts
  src/Raven.Studio/wwwroot/App/views/manage/cluster.html
Labels: v5.2

#13269 RavenDB-17663 Refactor timeseries patch sample code
  src/Raven.Studio/typescript/viewmodels/database/patch/patchSyntax.ts
Labels: v5.2

#13268 RavenDB-17654 Cluster View: Limit the maximum number of cores to use
  src/Raven.Studio/typescript/viewmodels/manage/assignCores.ts
Labels: v5.2

#13259 RavenDB-17676 Error in console when plotting time series entries (v5.2)
  src/Raven.Studio/typescript/viewmodels/database/query/query.ts
Labels: v5.2

#13258 RavenDB-17637 Revert Revisions: Add 'local' input-group-addon
  src/Raven.Studio/wwwroot/App/views/database/settings/revertRevisions.html
Labels: v5.2

#13266 RavenDB-17657 Cannot export the Server IO Stats
  src/Raven.Studio/typescript/models/database/status/ioStatsGraph.ts
  src/Raven.Studio/typescript/viewmodels/database/status/ioStats.ts
  src/Raven.Studio/typescript/viewmodels/manage/serverWideIoStats.ts
Labels: v5.2

#13255 RavenDB-17688 Docker ServerUrl override
  docker/ravendb-nanoserver/run-raven.ps1
  docker/ravendb-ubuntu/run-raven.sh
Labels: v4.2, v5.3

#13252 RavenDB-17309 : Add support for Select after Select
  src/Raven.Client/Documents/Linq/RavenQueryProviderProcessor.cs
  src/Raven.Client/Util/JavascriptConversionExtensions.cs
  test/SlowTests/Issues/RavenDB_17006.cs
  test/SlowTests/Issues/RavenDB_17309.cs
Labels: v5.2

#13251 Raven db 17595 dump index fix for52
  src/Raven.Studio/wwwroot/App/views/database/indexes/editIndex.html
Labels: v5.2

#13241 RavenDB-15053 Filter time series results - Fix
  src/Raven.Studio/typescript/common/queryUtil.ts
  src/Raven.Studio/typescript/viewmodels/database/timeSeries/editTimeSeries.ts
  src/Raven.Studio/wwwroot/App/views/database/timeSeries/editTimeSeries.html
Labels: v5.3

#13277 RavenDB-17566 Fields projection using index.
  src/Raven.Client/Documents/Conventions/DocumentConventions.cs
  test/SlowTests/Issues/RavenDB-17566.cs
Labels: v5.2

#13299 4.2 to 5.1 merge
  .github/workflows/FastTests.yml
  bench/BulkInsert.Benchmark/BulkInsert.Benchmark.csproj
  bench/Indexing.Benchmark/Indexing.Benchmark.csproj
  bench/Micro.Benchmark/Micro.Benchmark.csproj
  bench/Regression.Benchmark/Regression.Benchmark.csproj
  bench/SubscriptionFailover.Benchmark/SubscriptionFailover.Benchmark.csproj
  bench/Subscriptions.Benchmark/Subscriptions.Benchmark.csproj
  bench/TimeSeries.Benchmark/TimeSeries.Benchmark.csproj
  bench/Voron.Benchmark/Voron.Benchmark.csproj
  docker/ravendb-nanoserver/run-raven.ps1
  docker/ravendb-ubuntu/run-raven.sh
  src/Raven.Client/Documents/Subscriptions/SubscriptionWorker.cs
  src/Raven.Embedded/ServerOptions.cs
  src/Raven.Server/Documents/ETL/EtlProcess.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Studio/Raven.Studio.csproj
  src/Raven.Studio/package.json
  src/Sparrow.Server/Sparrow.Server.csproj
  src/Voron/Impl/Journal/JournalReader.cs
  src/Voron/Voron.csproj
  test/BenchmarkTests/BenchmarkTests.csproj
  test/EmbeddedTests/EmbeddedTests.csproj
  test/FastTests/FastTests.csproj
  test/InterversionTests/InterversionTests.csproj
  test/LicenseTests/LicenseTests.csproj
  test/RachisTests/RachisTests.csproj
  test/SlowTests/Issues/RavenDB-17698.cs
  test/SlowTests/SlowTests.csproj
  test/StressTests/StressTests.csproj
  test/Studio/Studio.csproj
  test/Tests.Infrastructure/RavenTestBase.cs
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
  test/Tryouts/Tryouts.csproj
  tools/Raven.Debug/Raven.Debug.csproj
  tools/Raven.Migrator/Raven.Migrator.csproj
  tools/TypingsGenerator/TypingsGenerator.csproj
  tools/Voron.Recovery/Voron.Recovery.csproj
  tools/rvn/rvn.csproj
Labels: v5.1

#13300 RavenDB-17424 added 'Indexing.TimeSinceLastQueryAfterWhichDeepCleanupCanBeExecutedInMin' configuration option
  src/Raven.Server/Config/Categories/IndexingConfiguration.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
Labels: v4.2

#13242 RavenDB-17666 - export the escaped id correctly when using smuggler
  src/Raven.Server/Smuggler/Documents/StreamDestination.cs
  src/Sparrow/Json/JsonOperationContext.cs
  src/Sparrow/Json/Parsing/JsonParserState.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
Labels: v4.2

#13297 RavenDB-17651 - Quering with AnyAsync on propery that doesn't exist should return total results of zero
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Queries/CollectionQueryEnumerable.cs
  test/SlowTests/Issues/RavenDB-17651.cs
Labels: v4.2

#13301 5.1 to 5.2 merge
  .github/workflows/FastTests.yml
  bench/BulkInsert.Benchmark/BulkInsert.Benchmark.csproj
  bench/Indexing.Benchmark/Indexing.Benchmark.csproj
  bench/Micro.Benchmark/Micro.Benchmark.csproj
  bench/Regression.Benchmark/Regression.Benchmark.csproj
  bench/SubscriptionFailover.Benchmark/SubscriptionFailover.Benchmark.csproj
  bench/Subscriptions.Benchmark/Subscriptions.Benchmark.csproj
  bench/TimeSeries.Benchmark/TimeSeries.Benchmark.csproj
  bench/Voron.Benchmark/Voron.Benchmark.csproj
  docker/ravendb-nanoserver/run-raven.ps1
  docker/ravendb-ubuntu/run-raven.sh
  src/Raven.Client/Documents/Subscriptions/SubscriptionWorker.cs
  src/Raven.Embedded/ServerOptions.cs
  src/Raven.Server/Documents/ETL/EtlProcess.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Studio/Raven.Studio.csproj
  src/Raven.Studio/package.json
  src/Sparrow.Server/Sparrow.Server.csproj
  src/Voron/Impl/Journal/JournalReader.cs
  src/Voron/Voron.csproj
  test/BenchmarkTests/BenchmarkTests.csproj
  test/EmbeddedTests/EmbeddedTests.csproj
  test/FastTests/FastTests.csproj
  test/FastTests/Server/Documents/Revisions/RevisionsTests.cs
  test/InterversionTests/InterversionTests.csproj
  test/LicenseTests/LicenseTests.csproj
  test/RachisTests/RachisTests.csproj
  test/SlowTests/Issues/RavenDB-17698.cs
  test/SlowTests/SlowTests.csproj
  test/StressTests/StressTests.csproj
  test/Studio/Studio.csproj
  test/Tests.Infrastructure/RavenTestBase.cs
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
  test/Tryouts/Tryouts.csproj
  tools/Raven.Debug/Raven.Debug.csproj
  tools/Raven.Migrator/Raven.Migrator.csproj
  tools/TypingsGenerator/TypingsGenerator.csproj
  tools/Voron.Recovery/Voron.Recovery.csproj
  tools/rvn/rvn.csproj
Labels: v5.2

#13303 4.2 to 5.1 merge
  src/Raven.Server/Config/Categories/IndexingConfiguration.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  src/Raven.Server/Documents/PeriodicBackup/Aws/RavenAwsGlacierClient.cs
  src/Raven.Server/Documents/PeriodicBackup/Aws/RavenAwsS3Client.cs
  src/Raven.Server/Documents/PeriodicBackup/Azure/LegacyRavenAzureClient.cs
  src/Raven.Server/Documents/PeriodicBackup/Azure/RavenAzureClient.cs
  src/Raven.Server/Documents/Queries/CollectionQueryEnumerable.cs
  src/Raven.Server/Smuggler/Documents/StreamDestination.cs
  src/Raven.Server/Web/Studio/StudioTasksHandler.cs
  test/SlowTests/Issues/RavenDB-17651.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
Labels: v5.1

#13304 5.1 to 5.2 merge
  src/Raven.Server/Config/Categories/IndexingConfiguration.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  src/Raven.Server/Documents/PeriodicBackup/Aws/RavenAwsGlacierClient.cs
  src/Raven.Server/Documents/PeriodicBackup/Aws/RavenAwsS3Client.cs
  src/Raven.Server/Documents/PeriodicBackup/Azure/LegacyRavenAzureClient.cs
  src/Raven.Server/Documents/PeriodicBackup/Azure/RavenAzureClient.cs
  src/Raven.Server/Documents/Queries/CollectionQueryEnumerable.cs
  src/Raven.Server/Smuggler/Documents/StreamDestination.cs
  src/Raven.Server/Web/Studio/StudioTasksHandler.cs
  test/SlowTests/Issues/RavenDB-17651.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
Labels: v5.2

#13314 RavenDB-17667 : flaky test
  test/SlowTests/Issues/RavenDB-15080.cs
Labels: v5.1

#13321 RavenDB-17714 Failed to test credentials for AWS with custom URL
  src/Raven.Studio/typescript/models/database/tasks/periodicBackup/amazonSettings.ts
  src/Raven.Studio/typescript/models/database/tasks/periodicBackup/glacierSettings.ts
  src/Raven.Studio/typescript/models/database/tasks/periodicBackup/s3Settings.ts
Labels: v4.2

#13324 RavenDB-17687 Adding default value of QueryInspectionNode to avoid calling null delegate.
  src/Corax/Queries/BinaryMatch.cs
  src/Corax/Queries/BoostingMatch.cs
  src/Corax/Queries/MultiTermBoostingMatch.cs
  src/Corax/Queries/QueryInspectionNode.cs
  src/Corax/Queries/TermMatch.cs
Labels: Corax

#13325 5.3 to feature/corax merge
  src/Raven.Client/Documents/Commands/MultiGet/MultiGetCommand.cs
  src/Raven.Client/Documents/Session/Operations/MultiGetOperation.cs
  src/Raven.Server/Documents/Replication/IncomingReplicationHandler.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesStorage.cs
  src/Raven.Studio/typescript/models/database/tasks/periodicBackup/amazonSettings.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/destinations/glacierSettings.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/destinations/s3Settings.ts
  test/SlowTests/Issues/RavenDB-15080.cs
  test/SlowTests/Issues/RavenDB_17317.cs
  test/SlowTests/Server/Documents/TimeSeries/TimeSeriesTombstoneCleaner.cs
Labels: Corax

#13317 RavenDB-17689 Invalid load document results when we are projecting a …
  src/Raven.Server/Documents/Document.cs
  src/Raven.Server/Documents/Queries/Results/QueryResultRetrieverBase.cs
  test/SlowTests/Issues/RavenDB-17689.cs
Labels: v4.2

#13322 RavenDB-17716 Unable to load identities
  src/Raven.Studio/typescript/viewmodels/database/identities/identities.ts
Labels: v5.3

#13315 RavenDB-17719 MergedDocumentReplicationCommand dispose replication item only on committed transaction
  src/Raven.Server/Documents/Replication/IncomingReplicationHandler.cs
Labels: v4.2

#13336 RavenDB-17424 Make the NoQuery timespan configurable on index cleanup
  src/Raven.Server/Config/Categories/IndexingConfiguration.cs
  src/Raven.Studio/typescript/models/database/index/configurationItem.ts
  test/FastTests/Issues/RavenDB_16590.cs
Labels: v5.2

#13326 RavenDB-14191 protect against cross site scripting
  src/Raven.Server/Web/System/StudioHandler.cs
Labels: v4.2

#13328 RavenDB-7829 Use HSTS to remember that the studio is running with HTTPS
  src/Raven.Server/Config/Categories/SecurityConfiguration.cs
  src/Raven.Server/Web/System/StudioHandler.cs
Labels: v5.2

#13340 RavenDB-17669 Document Properties: race in changing the tabs
  src/Raven.Studio/typescript/widgets/virtualGrid/virtualGrid.ts
Labels: v5.2

#13341 RavenDB-17744 Bump node-forge package
  src/Raven.Studio/package-lock.json
  src/Raven.Studio/package.json
  src/Raven.Studio/typings/_studio/customTypings.d.ts
  src/Raven.Studio/typings/custom_node-forge.d.ts
Labels: v5.3

#13333 RavenDB-16804 : ETL stats fixes
  src/Raven.Server/Documents/ETL/EtlProcess.cs
  src/Raven.Server/Documents/ETL/Stats/EtlPerformanceStats.cs
  src/Raven.Server/Documents/ETL/Stats/EtlRunStats.cs
  src/Raven.Server/Documents/ETL/Stats/EtlStatsAggregator.cs
  src/Raven.Server/Documents/ETL/Stats/EtlStatsScope.cs
  test/SlowTests/Server/Documents/ETL/Raven/RavenDB_12800.cs
  test/SlowTests/Server/Documents/ETL/RavenDB_12079.cs
  test/SlowTests/Server/Documents/ETL/RavenDB_16804.cs
  test/SlowTests/Server/Documents/ETL/RavenDB_8866.cs
  test/SlowTests/Server/Documents/ETL/SQL/SqlEtlTests.cs
Labels: v5.2

#13327 RavenDB-17317 - Time series value does not update across all nodes
  src/Raven.Server/Documents/TimeSeries/TimeSeriesStorage.cs
  test/SlowTests/Issues/RavenDB_15240.cs
  test/SlowTests/Issues/RavenDB_17317.cs
  test/SlowTests/Server/Documents/TimeSeries/TimeSeriesTombstoneCleaner.cs
  test/Tryouts/Program.cs
Labels: v5.2

#13296 RavenDB-17626 Cast IEnumerable<T> into IEnumerable<dynamic> inside SelectMany
  src/Raven.Server/Documents/Indexes/Static/Roslyn/Rewriters/DynamicLambdaExpressionsRewriter.cs
  test/SlowTests/Issues/RavenDB_17626.cs
Labels: v4.2

#13346 4.2 to 5.2 merge
  src/Raven.Server/Documents/Document.cs
  src/Raven.Server/Documents/Indexes/Static/Roslyn/Rewriters/DynamicLambdaExpressionsRewriter.cs
  src/Raven.Server/Documents/Queries/Results/QueryResultRetrieverBase.cs
  src/Raven.Server/Documents/Replication/IncomingReplicationHandler.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Server/Web/System/StudioHandler.cs
  test/SlowTests/Issues/RavenDB-17689.cs
  test/SlowTests/Issues/RavenDB_17626.cs
Labels: v5.2

#13236 RavenDB-17612 add try/catch to test
  test/SlowTests/RavenDB-14303.cs
Labels: v4.2

#13354 RavenDB-17719 fix double dispose of replication item
  src/Raven.Server/Documents/Replication/IncomingReplicationHandler.cs
Labels: v5.2

#13352 5.2 into 5.3 merge
  src/Raven.Server/Documents/Document.cs
  src/Raven.Server/Documents/ETL/EtlProcess.cs
  src/Raven.Server/Documents/ETL/Stats/EtlPerformanceStats.cs
  src/Raven.Server/Documents/ETL/Stats/EtlRunStats.cs
  src/Raven.Server/Documents/ETL/Stats/EtlStatsAggregator.cs
  src/Raven.Server/Documents/ETL/Stats/EtlStatsScope.cs
  src/Raven.Server/Documents/Indexes/Static/Roslyn/Rewriters/DynamicLambdaExpressionsRewriter.cs
  src/Raven.Server/Documents/Queries/Results/QueryResultRetrieverBase.cs
  src/Raven.Server/Documents/Replication/IncomingReplicationHandler.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesStorage.cs
  src/Raven.Server/Web/System/StudioHandler.cs
  src/Raven.Studio/typescript/viewmodels/database/status/ongoingTasksStats.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/virtualGrid.ts
  test/SlowTests/Issues/RavenDB-17689.cs
  test/SlowTests/Issues/RavenDB_15240.cs
  test/SlowTests/Issues/RavenDB_17317.cs
  test/SlowTests/Issues/RavenDB_17626.cs
  test/SlowTests/Server/Documents/ETL/Raven/RavenDB_12800.cs
  test/SlowTests/Server/Documents/ETL/RavenDB_12079.cs
  test/SlowTests/Server/Documents/ETL/RavenDB_16804.cs
  test/SlowTests/Server/Documents/ETL/RavenDB_8866.cs
  test/SlowTests/Server/Documents/ETL/SQL/SqlEtlTests.cs
  test/SlowTests/Server/Documents/TimeSeries/TimeSeriesTombstoneCleaner.cs
Labels: v5.3
