Repository ravendb/ravendb, pull requests merged in 2021-01, with the labels that each got.

#11633 RavenDB-16052 Frequent dashboard style recalculation causing 20% CPU
  src/Raven.Studio/typescript/viewmodels/resources/serverDashboard.ts
  src/Raven.Studio/wwwroot/Content/css/pages/dashboard.less
Labels: v4.2

#11632 RavenDB-16056 Improve Index name title
  src/Raven.Studio/wwwroot/App/views/database/indexes/editIndex.html
Labels: v5.1

#11624 RavenDB-16062 Fix tooltip format in Ongoing Tasks Stats
  src/Raven.Studio/typescript/viewmodels/database/status/ongoingTasksStats.ts
Labels: v5.1

#11620 RavenDB-15788 Broken failed Enforce Revision Configuration message
  src/Raven.Studio/typescript/commands/database/settings/enforceRevisionsConfigurationCommand.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/enforceRevisionsConfigurationDetails.ts
Labels: v5.0

#11617 RavenDB-15758 Display TS value names for a new TS entry
  src/Raven.Studio/typescript/viewmodels/database/timeSeries/editTimeSeries.ts
  src/Raven.Studio/typescript/viewmodels/database/timeSeries/editTimeSeriesEntry.ts
Labels: v5.1

#11616 RavenDB-16064 Fix admin logs filtering
  src/Raven.Studio/typescript/viewmodels/manage/adminLogs.ts
Labels: v5.1

#11615 RavenDB-16046: Exception handling in tests, increase server dispose t…
  test/StressTests/Client/Attachments/AttachmentsHugeFiles.cs
  test/Tests.Infrastructure/RavenTestBase.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v4.2

#11613 Prerequisites script requires Mono but it is no longer required by .Net 5.0
  install_build_prerequisites.sh
  scripts/checkPrerequisites.ps1
Labels: v5.1

#11629 RavenDB-15978: wait for topology to apply on all nodes on cluster creation in test
  test/Tests.Infrastructure/ClusterTestBase.cs
Labels: v4.2

#11600 RavenDB-15984 add encryption as extra dimention for benchmark tests
  test/BenchmarkTests/BenchmarkTestBase.cs
  test/BenchmarkTests/Indexing/Index.cs
  test/BenchmarkTests/Init.cs
  test/BenchmarkTests/Patching/Patch.cs
Labels: v4.2

#11607 RavenDB-15917 Cached useOldFailureCheckOperation to static
  src/Raven.Client/Http/RequestExecutor.cs
Labels: v4.2

#11579 RavenDB-16031 Wrong javascript index result when groupby on nested ob…
  src/Raven.Server/Documents/Indexes/CompiledIndexField.cs
  src/Raven.Server/Documents/Indexes/Debugging/IndexDebugExtensions.cs
  src/Raven.Server/Documents/Indexes/MapReduce/Static/MapReduceIndex.cs
  src/Raven.Server/Documents/Indexes/MapReduce/Static/MapReduceIndexDefinition.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/DictionaryAccessor.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/PropertyAccessor.cs
  src/Raven.Server/Documents/Indexes/Static/JavaScriptReduceOperation.cs
  src/Raven.Server/Utils/TypeConverter.cs
  test/SlowTests/Issues/RavenDB-16031.cs
Labels: v4.2

#11592 RavenDB-15993 Separate context for builder in StreamOperation & reset+renew context on too high cachedProperties amount & memory size
  src/Raven.Client/Documents/Session/Operations/StreamOperation.cs
  src/Sparrow/Json/BlittableJsonDocumentBuilder.cs
  src/Sparrow/Json/CachedProperties.cs
  src/Sparrow/Json/Parsing/UnmanagedJsonParserHelper.cs
  test/SlowTests/Core/Streaming/QueryStreaming.cs
Labels: v5.1

#11637 4.2 to 5.0 merge
  src/Raven.Client/Documents/Commands/MultiGet/MultiGetCommand.cs
  src/Raven.Client/Documents/Subscriptions/SubscriptionWorker.cs
  src/Raven.Client/Exceptions/Documents/Subscriptions/SubscriptionDoesNotBelongToNodeException.cs
  src/Raven.Client/Http/RequestExecutor.cs
  src/Raven.Server/Documents/DatabaseInfoCache.cs
  src/Raven.Server/Documents/DocumentPutAction.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Indexes/CompiledIndexField.cs
  src/Raven.Server/Documents/Indexes/Debugging/IndexDebugExtensions.cs
  src/Raven.Server/Documents/Indexes/MapReduce/Static/MapReduceIndex.cs
  src/Raven.Server/Documents/Indexes/MapReduce/Static/MapReduceIndexDefinition.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/DictionaryAccessor.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/PropertyAccessor.cs
  src/Raven.Server/Documents/Indexes/Static/JavaScriptReduceOperation.cs
  src/Raven.Server/Documents/Replication/OutgoingReplicationHandler.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  src/Raven.Server/Documents/TcpHandlers/SubscriptionConnection.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/ServerWide/Commands/Subscriptions/AcknowledgeSubscriptionBatchCommand.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterObserver.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Utils/ChangeVectorUtils.cs
  src/Raven.Server/Utils/TypeConverter.cs
  src/Raven.Studio/typescript/models/resources/info/databaseInfo.ts
  src/Raven.Studio/typescript/viewmodels/resources/serverDashboard.ts
  src/Raven.Studio/wwwroot/App/views/resources/databases.html
  src/Raven.Studio/wwwroot/Content/css/pages/dashboard.less
  test/BenchmarkTests/BenchmarkTestBase.cs
  test/BenchmarkTests/Indexing/Index.cs
  test/BenchmarkTests/Init.cs
  test/BenchmarkTests/Patching/Patch.cs
  test/FastTests/Server/Replication/ReplicationTestBase.cs
  test/RachisTests/AddNodeToClusterTests.cs
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
  test/RachisTests/SubscriptionsFailover.cs
  test/SlowTests/Data/RavenDB_15898/1.ravendbdump
  test/SlowTests/Issues/RavenDB-15898.cs
  test/SlowTests/Issues/RavenDB-16031.cs
  test/SlowTests/Issues/RavenDB-16035.cs
  test/SlowTests/Server/NotificationCenter/NotificationCenterTests.cs
  test/SlowTests/SlowTests.csproj
  test/StressTests/Client/Attachments/AttachmentsHugeFiles.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
  test/Tests.Infrastructure/RavenTestBase.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v5.0

#11638 5.0 to 5.1 merge
  src/Raven.Client/Documents/Commands/MultiGet/MultiGetCommand.cs
  src/Raven.Client/Documents/Subscriptions/SubscriptionWorker.cs
  src/Raven.Client/Exceptions/Documents/Subscriptions/SubscriptionDoesNotBelongToNodeException.cs
  src/Raven.Client/Http/RequestExecutor.cs
  src/Raven.Server/Documents/DatabaseInfoCache.cs
  src/Raven.Server/Documents/DocumentPutAction.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Indexes/CompiledIndexField.cs
  src/Raven.Server/Documents/Indexes/Debugging/IndexDebugExtensions.cs
  src/Raven.Server/Documents/Indexes/MapReduce/Static/MapReduceIndex.cs
  src/Raven.Server/Documents/Indexes/MapReduce/Static/MapReduceIndexDefinition.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/DictionaryAccessor.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/PropertyAccessor.cs
  src/Raven.Server/Documents/Indexes/Static/JavaScriptReduceOperation.cs
  src/Raven.Server/Documents/Replication/OutgoingReplicationHandler.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  src/Raven.Server/Documents/TcpHandlers/SubscriptionConnection.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/ServerWide/Commands/Subscriptions/AcknowledgeSubscriptionBatchCommand.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterObserver.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Utils/ChangeVectorUtils.cs
  src/Raven.Server/Utils/TypeConverter.cs
  src/Raven.Studio/typescript/commands/database/settings/enforceRevisionsConfigurationCommand.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/enforceRevisionsConfigurationDetails.ts
  src/Raven.Studio/typescript/viewmodels/resources/serverDashboard.ts
  src/Raven.Studio/wwwroot/App/views/resources/databases.html
  src/Raven.Studio/wwwroot/Content/css/pages/dashboard.less
  test/BenchmarkTests/BenchmarkTestBase.cs
  test/BenchmarkTests/Indexing/Index.cs
  test/BenchmarkTests/Init.cs
  test/BenchmarkTests/Patching/Patch.cs
  test/FastTests/Server/Replication/ReplicationTestBase.cs
  test/RachisTests/AddNodeToClusterTests.cs
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
  test/RachisTests/SubscriptionsFailover.cs
  test/SlowTests/Data/RavenDB_15898/1.ravendbdump
  test/SlowTests/Issues/RavenDB-15898.cs
  test/SlowTests/Issues/RavenDB-16031.cs
  test/SlowTests/Issues/RavenDB-16035.cs
  test/SlowTests/Server/NotificationCenter/NotificationCenterTests.cs
  test/SlowTests/SlowTests.csproj
  test/StressTests/Client/Attachments/AttachmentsHugeFiles.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
  test/Tests.Infrastructure/RavenTestBase.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v5.1

#11634 Remote changes base concurrent
  Raven.Client.Lightweight/Changes/RemoteChangesClientBase.cs
Labels: v3.5

#11640 RDBS-92 fix time
  src/Raven.Server/Documents/Indexes/Index.cs
Labels: v5.1

#11642 RavenDB-16086 Recovery needs to take into account that a modified pa…
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  test/SlowTests/Issues/RavenDB_16086.cs
Labels: v4.2

#11644 RavenDB-16087 Cannot read property 'databaseChangeVector' of undefined
  src/Raven.Studio/typescript/viewmodels/database/status/statistics.ts
Labels: v5.1

#11628 RavenDB-15782 Pull Replication in the About page
  src/Raven.Studio/wwwroot/App/views/shell/about.html
  src/Raven.Studio/wwwroot/Content/css/pages/about.less
Labels: v5.1

#11646 4.2 to 5.0 merge
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  test/SlowTests/Cluster/ClusterTransactionTests.cs
  test/SlowTests/Issues/RavenDB-13697.cs
  test/SlowTests/Issues/RavenDB_15409.cs
  test/SlowTests/Issues/RavenDB_16086.cs
  test/Tests.Infrastructure/RavenTestBase.cs
  test/Tests.Infrastructure/RavenTestHelper.cs
Labels: v5.0

#11647 5.0 to 5.1 merge
  libs/microsoft.dotnet.xunit.performance.1.0.0-alpha-build0041.nupkg
  libs/microsoft.dotnet.xunit.performance.run.core.1.0.0-alpha-build0041.nupkg
  libs/microsoft.dotnet.xunit.performance.runner.cli.1.0.0-alpha-build0041.nupkg
  src/Raven.Server/Documents/TimeSeries/TimeSeriesPolicyRunner.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  test/SlowTests/Cluster/ClusterTransactionTests.cs
  test/SlowTests/Issues/RavenDB-13697.cs
  test/SlowTests/Issues/RavenDB_15409.cs
  test/SlowTests/Issues/RavenDB_16086.cs
  test/SlowTests/Smuggler/SmugglerApiTests.cs
  test/Tests.Infrastructure/RavenTestBase.cs
  test/Tests.Infrastructure/RavenTestHelper.cs
Labels: v5.1

#11650 RavenDB-14744 avoid updating sibling etag on new connections
  src/Raven.Server/Documents/Replication/OutgoingReplicationHandler.cs
Labels: v4.2

#11649 RavenDB-16068 - delay token when processing the ExecuteRateLimitedOperations
  src/Raven.Server/Documents/CollectionRunner.cs
Labels: v4.2

#11648 RavenDB-16068 - temporarily revert the page size fix in CollectionRunner
  src/Raven.Server/Documents/CollectionRunner.cs
Labels: v5.0

#11652 RavenDB-15984 add encryption as extra dimention for benchmark tests -…
  test/BenchmarkTests/BenchmarkTestBase.cs
Labels: v4.2

#11651 RavenDB-16000: Mark Changes API connection state as faulted if failed…
  src/Raven.Client/Documents/Changes/DatabaseChanges.cs
  test/SlowTests/Issues/RavenDB-13697.cs
Labels: v4.2

#11656 RavenDB-16102 - fix start after in SeekByPrimaryKeyPrefix
  src/Voron/Data/Tables/Table.cs
  test/SlowTests/Issues/IAsyncDocumentSessionExtensionsTest.cs
Labels: v4.2

#11655 RDBS-92 cherry-pick from 5.1
  libs/Lucene.Net.3.0.37.nupkg
  libs/Lucene.Net.3.0.40.nupkg
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/IndexFacetedReadOperation.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/IndexSearcherHolder.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/LuceneIndexPersistence.cs
  src/Raven.Server/Documents/Queries/Sorting/AlphaNumeric/AlphaNumericComparatorSource.cs
  src/Raven.Server/Documents/Queries/Sorting/AlphaNumeric/AlphaNumericFieldComparator.cs
  src/Raven.Server/Program.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Server/ServerWide/ServerStore.cs
  test/SlowTests/Data/RavenDB_8355/MySorterWithDiagnostics.cs
  test/Tests.Infrastructure/RachisConsensusTestBase.cs
  test/Tests.Infrastructure/TestBase.cs
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
Labels: v4.2

#11657 4.2 to 5.0 merge
  .github/workflows/FastTests.yml
  bench/BulkInsert.Benchmark/BulkInsert.Benchmark.csproj
  bench/Indexing.Benchmark/Indexing.Benchmark.csproj
  bench/Micro.Benchmark/Micro.Benchmark.csproj
  bench/Regression.Benchmark/Regression.Benchmark.csproj
  bench/SubscriptionFailover.Benchmark/SubscriptionFailover.Benchmark.csproj
  bench/Subscriptions.Benchmark/Subscriptions.Benchmark.csproj
  bench/Voron.Benchmark/Voron.Benchmark.csproj
  libs/Lucene.Net.3.0.40.nupkg
  src/Raven.Embedded/ServerOptions.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/IndexFacetedReadOperation.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/IndexSearcherHolder.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/LuceneIndexPersistence.cs
  src/Raven.Server/Documents/Queries/Sorting/AlphaNumeric/AlphaNumericComparatorSource.cs
  src/Raven.Server/Documents/Queries/Sorting/AlphaNumeric/AlphaNumericFieldComparator.cs
  src/Raven.Server/Program.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Studio/Raven.Studio.csproj
  src/Voron/Data/Tables/Table.cs
  test/BenchmarkTests/BenchmarkTests.csproj
  test/EmbeddedTests/EmbeddedTests.csproj
  test/FastTests/FastTests.csproj
  test/InterversionTests/InterversionTests.csproj
  test/LicenseTests/LicenseTests.csproj
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
  test/RachisTests/RachisTests.csproj
  test/SlowTests/Cluster/ClusterModesForRequestExecutorTest.cs
  test/SlowTests/Data/RavenDB_8355/MySorterWithDiagnostics.cs
  test/SlowTests/Issues/IAsyncDocumentSessionExtensionsTest.cs
  test/SlowTests/Server/Replication/ReplicationCleanTombstones.cs
  test/SlowTests/SlowTests.csproj
  test/StressTests/StressTests.csproj
  test/Tests.Infrastructure/ProxyServer.cs
  test/Tests.Infrastructure/RachisConsensusTestBase.cs
  test/Tests.Infrastructure/TestBase.cs
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
  test/Tryouts/Tryouts.csproj
  tools/Raven.Debug/Raven.Debug.csproj
  tools/Raven.Migrator/Raven.Migrator.csproj
  tools/TypingsGenerator/TypingsGenerator.csproj
  tools/Voron.Recovery/Voron.Recovery.csproj
  tools/rvn/rvn.csproj
Labels: v5.0

#11660 5.0 to 5.1 merge
  src/Voron/Data/Tables/Table.cs
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
  test/SlowTests/Cluster/ClusterModesForRequestExecutorTest.cs
  test/SlowTests/Issues/IAsyncDocumentSessionExtensionsTest.cs
  test/SlowTests/Server/Replication/ReplicationCleanTombstones.cs
  test/Tests.Infrastructure/ProxyServer.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v5.1

#11664 RavenDB-16104 - update lucene
  libs/Lucene.Net.3.0.40.nupkg
  libs/Lucene.Net.3.0.41.nupkg
  src/Raven.Server/Raven.Server.csproj
Labels: v4.2

#11667 Revert "RavenDB-15984 add encryption as extra dimention for benchmark…
  test/BenchmarkTests/BenchmarkTestBase.cs
Labels: v4.2

#11670 RavenDB-16123 etag should be long
  src/Raven.Server/Utils/ChangeVectorUtils.cs
  test/FastTests/Server/Basic/ChangeVectorConflictStatusTests.cs
Labels: v4.2

#11676 RavenDB-16129 change date time to UTC
  test/SlowTests/Client/TimeSeries/BulkInsert.cs
  test/SlowTests/Client/TimeSeries/Session/TimeSeriesSessionTests.cs
Labels: v5.0

#11677 RavenDB-16129 change date time to UTC
  test/SlowTests/Client/TimeSeries/BulkInsert/BulkInsert.cs
  test/SlowTests/Client/TimeSeries/BulkInsert/TypedBulkInsert.cs
  test/SlowTests/Client/TimeSeries/Session/TimeSeriesSessionTests.cs
Labels: v5.1

#11684 RavenDB-16150 - Allow to set temp path for backups
  src/Raven.Server/Config/Categories/BackupConfiguration.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
Labels: v4.2

#11681 RavenDB-16139
  src/Raven.Server/Config/Categories/IndexingConfiguration.cs
  src/Raven.Server/Config/Categories/StorageConfiguration.cs
Labels: v4.2

#11694 RavenDB-16135 pass $type in RevertResult so deserialization can work properly
  src/Raven.Client/Documents/Operations/Revisions/RevertResult.cs
  test/SlowTests/Issues/RavenDB_16135.cs
Labels: v4.2

#11700 5.0 to 5.1 merge
  src/Raven.Client/Documents/Operations/Revisions/RevertResult.cs
  test/SlowTests/Issues/RavenDB_16135.cs
Labels: v5.1

#11695 RavenDB-15353 - test fix
  test/SlowTests/Smuggler/SmugglerApiTests.cs
Labels: v5.0

#11693 RavenDB-16146 wrap next binary expression after negation in subclauses
  src/Raven.Client/Documents/Linq/RavenQueryProviderProcessor.cs
  test/SlowTests/Issues/RavenDB_16146.cs
Labels: v4.2

#11692 RavenDB-16145 throw if requested collection name in LoadDocument does not match the actual one
  src/Raven.Server/Documents/Indexes/Static/CurrentIndexingScope.cs
  test/SlowTests/Issues/RavenDB_16145.cs
Labels: v5.1

#11697 RavenDB-15405 Register load configurations of time series policy runner and the dismiss of it's alert to the license change
  src/Raven.Server/Documents/DocumentDatabase.cs
Labels: v5.0

#11679 RavenDB-16067 Fix color for Identities tooltip in stats view
  src/Raven.Studio/wwwroot/Content/css/pages/stats.less
Labels: v5.1

#11682 RavenDB-16156 Fix flags during putting deleted revision from cluster tx
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  test/SlowTests/Issues/RavenDB_16156.cs
Labels: v4.2

#11675 RavenDB-14754: add debug info for test
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
  test/StressTests/Issues/RavenDB-13987.cs
Labels: v4.2

#11662 RavenDB-15499: tighten tests
  test/SlowTests/Issues/RavenDB_13293.cs
Labels: v4.2

#11702 RavenDB-14744: Don't move loading idle database to rehab in cluster o…
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterMaintenanceWorker.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterObserver.cs
  test/StressTests/Issues/RavenDB_14744.cs
Labels: v4.2

#11704 RavenDB-16172 fix NRE during CompleteDeletionIfNeeded
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
Labels: v4.2

#11636 RavenDB-16078 Projection with streaming gets us an NRE
  src/Raven.Server/Documents/Document.cs
  src/Raven.Server/Documents/Queries/Results/QueryResultRetrieverBase.cs
  test/SlowTests/Issues/RavenDB-16078.cs
Labels: v5.1

#11706 4.2 to 5.0 merge
  src/Raven.Client/Documents/Linq/RavenQueryProviderProcessor.cs
  src/Raven.Client/Documents/Subscriptions/SubscriptionWorker.cs
  src/Raven.Server/Documents/ClusterTransactionWaiter.cs
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Handlers/BatchHandler.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  src/Raven.Server/Documents/TcpHandlers/SubscriptionConnection.cs
  src/Raven.Server/Documents/TcpHandlers/TcpConnectionOptions.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterMaintenanceWorker.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterObserver.cs
  src/Voron/Impl/Journal/JournalReader.cs
  src/Voron/Impl/Journal/RecoveryOverflowDetector.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/Impl/LowLevelTransaction.cs
  src/Voron/Impl/Scratch/ScratchBufferFile.cs
  src/Voron/Impl/Scratch/ScratchBufferPool.cs
  test/RachisTests/SubscriptionsFailover.cs
  test/SlowTests/Cluster/ClusterTransactionTests.cs
  test/SlowTests/Issues/RavenDB-15535.cs
  test/SlowTests/Issues/RavenDB_13293.cs
  test/SlowTests/Issues/RavenDB_16146.cs
  test/SlowTests/Issues/RavenDB_16156.cs
  test/SlowTests/Server/Documents/PeriodicBackup/EncryptedBackupTest.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
  test/SlowTests/Server/Documents/PeriodicBackup/RavenDB-11139.cs
  test/SlowTests/Server/Documents/PeriodicBackup/RavenDB-13229.cs
  test/SlowTests/Server/Documents/PeriodicBackup/RavenDB_12012.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Restore/RestoreFromAzure.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Restore/RestoreFromGoogleCloud.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Restore/RestoreFromS3.cs
  test/SlowTests/Server/Replication/ReplicationRevisionsTests.cs
  test/SlowTests/Voron/Issues/RavenDB_16023.cs
  test/StressTests/Issues/RavenDB-13987.cs
  test/StressTests/Issues/RavenDB_14744.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
  test/Tests.Infrastructure/RavenTestBase.cs
Labels: v5.0

#11707 5.0 to 5.1 merge
  src/Raven.Client/Documents/Linq/RavenQueryProviderProcessor.cs
  src/Raven.Client/Documents/Operations/Revisions/GetRevisionsOperation.cs
  src/Raven.Client/Documents/Operations/Revisions/RevisionsResult.cs
  src/Raven.Client/Documents/Subscriptions/SubscriptionWorker.cs
  src/Raven.Server/Documents/ClusterTransactionWaiter.cs
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Handlers/BatchHandler.cs
  src/Raven.Server/Documents/Replication/ReplicationItems/AttachmentReplicationItem.cs
  src/Raven.Server/Documents/Replication/ReplicationItems/AttachmentTombstoneReplicationItem.cs
  src/Raven.Server/Documents/Replication/ReplicationItems/CounterReplicationItem.cs
  src/Raven.Server/Documents/Replication/ReplicationItems/DocumentReplicationItem.cs
  src/Raven.Server/Documents/Replication/ReplicationItems/ReplicationBatchItem.cs
  src/Raven.Server/Documents/Replication/ReplicationItems/RevisionTombstoneReplicationItem.cs
  src/Raven.Server/Documents/Replication/ReplicationItems/TimeSeriesReplicationItem.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  src/Raven.Server/Documents/TcpHandlers/SubscriptionConnection.cs
  src/Raven.Server/Documents/TcpHandlers/TcpConnectionOptions.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterMaintenanceWorker.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterObserver.cs
  src/Sparrow/Json/LazyStringValue.cs
  src/Voron/Impl/Journal/JournalReader.cs
  src/Voron/Impl/Journal/RecoveryOverflowDetector.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/Impl/LowLevelTransaction.cs
  src/Voron/Impl/Scratch/ScratchBufferFile.cs
  src/Voron/Impl/Scratch/ScratchBufferPool.cs
  src/Voron/Slice.cs
  test/FastTests/Client/RavenCommandTest.cs
  test/FastTests/Server/Documents/Revisions/RevisionsTests.cs
  test/FastTests/Utils/RevisionsHelper.cs
  test/RachisTests/SubscriptionsFailover.cs
  test/SlowTests/Cluster/ClusterTransactionTests.cs
  test/SlowTests/Issues/RavenDB-15535.cs
  test/SlowTests/Issues/RavenDB_13293.cs
  test/SlowTests/Issues/RavenDB_16146.cs
  test/SlowTests/Issues/RavenDB_16156.cs
  test/SlowTests/Server/Documents/PeriodicBackup/EncryptedBackupTest.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
  test/SlowTests/Server/Documents/PeriodicBackup/RavenDB-11139.cs
  test/SlowTests/Server/Documents/PeriodicBackup/RavenDB-13229.cs
  test/SlowTests/Server/Documents/PeriodicBackup/RavenDB_12012.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Restore/RestoreFromAzure.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Restore/RestoreFromGoogleCloud.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Restore/RestoreFromS3.cs
  test/SlowTests/Server/Replication/ReplicationRevisionsTests.cs
  test/SlowTests/Smuggler/SmugglerApiTests.cs
  test/SlowTests/Voron/Issues/RavenDB_16023.cs
  test/StressTests/Issues/RavenDB-13987.cs
  test/StressTests/Issues/RavenDB_14744.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
  test/Tests.Infrastructure/RavenTestBase.cs
Labels: v5.1

#11709 RDBS-108 Ensure the tombstone table is created
  src/Raven.Server/Documents/DocumentsStorage.cs
  test/SlowTests/Server/Replication/ReplicationCleanTombstones.cs
Labels: v4.2

#11716 RavenDB-16181 Revert EncryptionBuffersPool.Instance.Disabled in TestBase
  test/Tests.Infrastructure/TestBase.cs
Labels: v5.0

#11717 RavenDB-16179 avoid race - index stats are written in a separate tx
  test/SlowTests/Issues/RavenDB_10998.cs
Labels: v4.2

#11718 4.2 to 5.0 merge
  src/Raven.Server/Config/Categories/StorageConfiguration.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  test/SlowTests/Issues/RavenDB_10998.cs
  test/SlowTests/Server/Replication/ReplicationCleanTombstones.cs
Labels: v5.0

#11721 RavenDB-16162 Avoid duplicate edges in graph visualizer
  src/Raven.Server/Documents/Handlers/QueriesHandler.cs
Labels: v4.2
