Repository ravendb/ravendb, pull requests merged in 2022-02, with the labels that each got.

#13577 5.2 to 5.3 merge
  src/CommonAssemblyInfo.cs
  src/Raven.Client/Documents/Subscriptions/SubscriptionWorker.cs
  src/Raven.Client/Exceptions/Documents/Subscriptions/SubscriptionMessageTypeException.cs
  src/Raven.Client/Http/RequestExecutor.cs
  src/Raven.Studio/wwwroot/App/views/shell/about.html
  test/SlowTests/Core/Commands/Documents.cs
  test/SlowTests/Issues/RavenDB-15900.cs
Labels: v5.3

#13580 RavenDB-17948 async should return `Task` instead of `void`
  src/Raven.Server/Documents/Handlers/Debugging/ServerWideDebugInfoPackageHandler.cs
Labels: v4.2

#13574 RavenDB-17707 - StressTests.Client.TimeSeries.Policies.TimeSeriesConf…
  src/Raven.Server/Documents/Handlers/TimeSeriesHandler.cs
  src/Raven.Server/Documents/Replication/IncomingReplicationHandler.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesReader.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesSliceHolder.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesStats.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesStorage.cs
Labels: v5.2

#13582 Bump node-forge from 0.10.0 to 1.2.1 in /src/Raven.Studio
  src/Raven.Studio/package-lock.json
  src/Raven.Studio/package.json
Labels: v5.3

#13585 RavenDB-17906 - fixed WriteDatabaseRecord context usage
  src/Raven.Server/Documents/Handlers/Debugging/ServerWideDebugInfoPackageHandler.cs
Labels: v4.2

#13575 RavenDB-15840 - SlowTests.Client.TimeSeries.Policies.TimeSeriesConfig…
  test/StressTests/Client/TimeSeries/Policies/TimeSeriesConfigurationTestsStress.cs
Labels: v5.2

#13588 4.2 to 5.2 merge
  src/Raven.Client/Documents/Subscriptions/SubscriptionWorker.cs
  src/Raven.Client/Exceptions/Documents/Subscriptions/SubscriptionMessageTypeException.cs
  src/Raven.Server/Documents/Handlers/Admin/RachisAdminHandler.cs
  src/Raven.Server/Documents/Handlers/Debugging/ServerWideDebugInfoPackageHandler.cs
  src/Raven.Server/Rachis/AppendEntriesResponse.cs
  src/Raven.Server/Rachis/Follower.cs
  src/Raven.Server/Rachis/FollowerAmbassador.cs
  src/Raven.Server/Rachis/Leader.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/Rachis/RachisStateMachine.cs
  src/Raven.Server/Rachis/Remote/RemoteConnection.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/Commands/Subscriptions/ToggleSubscriptionStateCommand.cs
  src/Raven.Server/ServerWide/Commands/Subscriptions/UpdateSubscriptionClientConnectionTime.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Web/System/DatabasesHandler.cs
  test/InterversionTests/MixedClusterTests.cs
  test/RachisTests/AddNodeToClusterTests.cs
  test/SlowTests/Cluster/ParallelClusterTransactionsTests.cs
  test/StressTests/Cluster/ClusterStressTests.cs
  test/Tests.Infrastructure/RavenTestBase.cs
Labels: v5.2

#13589 5.2 to 5.3 merge
  .github/workflows/compile.yml
  .github/workflows/conventions.yml
  .github/workflows/slackNotify.yml
  scripts/githubActions/CompileGenerateMessage.sh
  scripts/githubActions/ConventionsGenerateMessage.sh
  scripts/githubActions/commitMessageConventions.ps1
  scripts/githubActions/commitWhitespaceConventions.ps1
  scripts/githubActions/sendSlackNotification.sh
  scripts/githubActions/set_github_label.ps1
  src/Raven.Client/Documents/Subscriptions/SubscriptionWorker.cs
  src/Raven.Client/Exceptions/Documents/Subscriptions/SubscriptionMessageTypeException.cs
  src/Raven.Server/Documents/Handlers/Admin/RachisAdminHandler.cs
  src/Raven.Server/Documents/Handlers/Debugging/ServerWideDebugInfoPackageHandler.cs
  src/Raven.Server/Rachis/AppendEntriesResponse.cs
  src/Raven.Server/Rachis/Follower.cs
  src/Raven.Server/Rachis/FollowerAmbassador.cs
  src/Raven.Server/Rachis/Leader.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/Rachis/RachisStateMachine.cs
  src/Raven.Server/Rachis/Remote/RemoteConnection.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/Commands/Subscriptions/ToggleSubscriptionStateCommand.cs
  src/Raven.Server/ServerWide/Commands/Subscriptions/UpdateSubscriptionClientConnectionTime.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Web/System/DatabasesHandler.cs
  test/InterversionTests/MixedClusterTests.cs
  test/RachisTests/AddNodeToClusterTests.cs
  test/SlowTests/Cluster/ParallelClusterTransactionsTests.cs
  test/StressTests/Client/TimeSeries/Policies/TimeSeriesConfigurationTestsStress.cs
  test/StressTests/Cluster/ClusterStressTests.cs
  test/Tests.Infrastructure/RavenTestBase.cs
Labels: v5.3

#13593 HRINT-255 Missing script - github actions
  scripts/githubActions/claSigned.ps1
Labels: v4.2

#12527 RavenDB-16274 Sharded import/export WIP
  src/Raven.Client/Documents/Smuggler/DatabaseSmuggler.cs
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/Handlers/Admin/AdminIndexHandler.cs
  src/Raven.Server/Documents/Handlers/LegacyReplicationHandler.cs
  src/Raven.Server/Documents/PeriodicBackup/BackupTask.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreBackupTaskBase.cs
  src/Raven.Server/Documents/ShardedHandlers/ShardedCommands/ShardedImportCommand.cs
  src/Raven.Server/Documents/ShardedHandlers/ShardedCommands/ShardedStreamCommand.cs
  src/Raven.Server/Documents/ShardedHandlers/ShardedOperationHandler.cs
  src/Raven.Server/Documents/ShardedHandlers/ShardedSmugglerHandler.cs
  src/Raven.Server/Documents/Sharding/ShardedContext.cs
  src/Raven.Server/Documents/Sharding/ShardedRequestHandler.cs
  src/Raven.Server/Documents/Subscriptions/SubscriptionStorage.cs
  src/Raven.Server/Smuggler/Documents/CsvStreamSource.cs
  src/Raven.Server/Smuggler/Documents/Data/ISmugglerDestination.cs
  src/Raven.Server/Smuggler/Documents/Data/ISmugglerSource.cs
  src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
  src/Raven.Server/Smuggler/Documents/DatabaseDestinationActions.cs
  src/Raven.Server/Smuggler/Documents/DatabaseSmuggler.cs
  src/Raven.Server/Smuggler/Documents/DatabaseSource.cs
  src/Raven.Server/Smuggler/Documents/Handlers/SmugglerHandler.cs
  src/Raven.Server/Smuggler/Documents/ShardedDatabaseSmuggler.cs
  src/Raven.Server/Smuggler/Documents/SmugglerBase.cs
  src/Raven.Server/Smuggler/Documents/StreamDestination.cs
  src/Raven.Server/Smuggler/Documents/StreamSource.cs
  src/Raven.Server/Smuggler/Migration/AbstractLegacyMigrator.cs
  src/Raven.Server/Smuggler/Migration/Importer.cs
  src/Raven.Server/Smuggler/Migration/Migrator_V2.cs
  src/Raven.Server/Smuggler/Migration/Migrator_V3.cs
  src/Raven.Server/Utils/ShardHelper.cs
  src/Raven.Server/Web/RequestHandler.Helper.cs
  src/Raven.Server/Web/RequestHandler.cs
  src/Raven.Server/Web/Studio/SampleDataHandler.cs
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
  test/SlowTests/Issues/RavenDB-13937.cs
  test/SlowTests/Issues/RavenDB_5998.cs
  test/SlowTests/Sharding/SmugglerTests.cs
Labels: Sharding

#13601 HRINT-255 Changed label assigning
  .github/workflows/conventions.yml
Labels: v4.2

#13600 RavenDB-17963 Making sure we're waiting for all attachments to be pro…
  test/SlowTests/Server/Documents/ETL/Raven/RavenDB_12800.cs
  test/SlowTests/Server/Documents/ETL/SQL/SqlEtlTests.cs
Labels: v4.2

#13606 4.2 to 5.2 merge
  .github/workflows/conventions.yml
  src/Raven.Server/Commercial/LicenseManager.cs
  src/Raven.Server/Commercial/LicenseStatus.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.1/DatabaseFaultedCount.cs
  src/Raven.Server/ServerWide/SecretProtection.cs
  test/SlowTests/Server/Documents/ETL/Raven/RavenDB_12800.cs
  test/SlowTests/Server/Documents/ETL/SQL/SqlEtlTests.cs
Labels: v5.2

#13607 5.2 to 5.3 merge
  .github/workflows/conventions.yml
  src/Raven.Server/Commercial/LicenseManager.cs
  src/Raven.Server/Commercial/LicenseStatus.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.1/DatabaseFaultedCount.cs
  src/Raven.Server/ServerWide/SecretProtection.cs
  test/SlowTests/Server/Documents/ETL/Raven/RavenDB_12800.cs
  test/SlowTests/Server/Documents/ETL/SQL/SqlEtlTests.cs
Labels: v5.3

#13608 5.3 to feature/corax merge
  .github/workflows/conventions.yml
  scripts/githubActions/claSigned.ps1
  src/Raven.Server/Commercial/LicenseManager.cs
  src/Raven.Server/Commercial/LicenseStatus.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/IndexFacetedReadOperation.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.1/DatabaseFaultedCount.cs
  src/Raven.Server/ServerWide/SecretProtection.cs
  test/SlowTests/Server/Documents/ETL/Raven/RavenDB_12800.cs
  test/SlowTests/Server/Documents/ETL/SQL/SqlEtlTests.cs
  test/Tests.Infrastructure/AmazonS3FactAttribute.cs
Labels: feature/corax

#13611 5.3 into sharding merge
  .github/workflows/conventions.yml
  scripts/githubActions/claSigned.ps1
  src/Raven.Server/Commercial/LicenseManager.cs
  src/Raven.Server/Commercial/LicenseStatus.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/IndexFacetedReadOperation.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.1/DatabaseFaultedCount.cs
  src/Raven.Server/ServerWide/SecretProtection.cs
  test/SlowTests/Server/Documents/ETL/Raven/RavenDB_12800.cs
  test/SlowTests/Server/Documents/ETL/SQL/SqlEtlTests.cs
  test/Tests.Infrastructure/AmazonS3FactAttribute.cs
Labels: feature/sharding

#13612 RavenDB-18000 added ShardingDevelopmentHelper
  src/Sparrow/Utils/DevelopmentHelper.cs
Labels: Sharding

#13617 HRINT-255 Run studio tests in feature branches
  .github/workflows/StudioTests.yml
Labels: Sharding

#13618 HRINT-255 Run studio tests in feature branches
  .github/workflows/StudioTests.yml
Labels: Corax

#13615 HRINT-2463 Added JunitXml.TestLogger package
  test/BenchmarkTests/BenchmarkTests.csproj
  test/EmbeddedTests/EmbeddedTests.csproj
  test/FastTests/FastTests.csproj
  test/InterversionTests/InterversionTests.csproj
  test/LicenseTests/LicenseTests.csproj
  test/RachisTests/RachisTests.csproj
  test/SlowTests/SlowTests.csproj
  test/StressTests/StressTests.csproj
  test/Studio/Studio.csproj
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
  test/Tryouts/Tryouts.csproj
Labels: v4.2

#13610 RavenDB-17998 fixed issue with compacting an index with NGram analyzer - we need to open indexing scope beforehand
  src/Raven.Server/Documents/Indexes/Index.cs
  test/SlowTests/Issues/RavenDB_17998.cs
Labels: v4.2

#13629 4.2 to 5.2 merge
  src/Raven.Server/Documents/Indexes/MapReduce/ReduceMapResultsBase.cs
  src/Voron/Data/BTrees/Tree.Compressed.cs
  src/Voron/Data/BTrees/Tree.cs
  src/Voron/Data/BTrees/TreeIterator.cs
  src/Voron/Data/BTrees/TreePageSplitter.cs
  src/Voron/Data/BTrees/TreeRebalancer.cs
  test/BenchmarkTests/BenchmarkTests.csproj
  test/EmbeddedTests/EmbeddedTests.csproj
  test/FastTests/FastTests.csproj
  test/InterversionTests/InterversionTests.csproj
  test/LicenseTests/LicenseTests.csproj
  test/RachisTests/RachisTests.csproj
  test/SlowTests/SlowTests.csproj
  test/SlowTests/Voron/Issues/RavenDB_11643_Voron.cs
  test/SlowTests/Voron/LeafsCompression/Data/RavenDB-17660-page-5728-compressed
  test/SlowTests/Voron/LeafsCompression/RavenDB_17660.cs
  test/StressTests/StressTests.csproj
  test/Studio/Studio.csproj
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
  test/Tryouts/Tryouts.csproj
Labels: v5.2

#13630 RDBCL-2065 switched to 52000
  src/Raven.Server/Storage/Schema/SchemaUpgrader.cs
  src/Raven.Server/Storage/Schema/Updates/Server/52000/From50000.cs
Labels: v5.2

#13624 RavenDB-16101 Add a sharding toggle in the create database dialog
  src/Raven.Studio/typescript/models/resources/creation/databaseCreationModel.ts
  src/Raven.Studio/wwwroot/App/views/resources/createDatabase.html
Labels: Sharding

#13619 RavenDB-17777 Fix the order of the duplicate configurations
  src/Raven.Server/Config/Categories/SecurityConfiguration.cs
  src/Raven.Server/Config/Categories/StorageConfiguration.cs
Labels: v5.3

#13641 RavenDB-18003 Filter keyword in a projection fails
  src/Raven.Server/Documents/Queries/Parser/QueryParser.cs
  src/Raven.Server/Documents/Queries/Parser/QueryScanner.cs
  test/FastTests/Issues/RavenDB-17636.cs
Labels: v5.3

#13637 RavenDB-18027 - NRE fixed
  src/Raven.Server/ServerWide/SecretProtection.cs
Labels: v4.2

#13645 RavenDB-18028 Return the cluster-wide index enable/disable option the UI
  src/Raven.Studio/wwwroot/App/views/database/indexes/indexes.html
Labels: v5.2

#13643 RavenDB-17999: add schema upgrade tests for CompareExchange And Expiration
  test/SlowTests/Cluster/CompareExchangeExpirationTest.cs
  test/SlowTests/SchemaUpgrade/Issues/SystemVersion/RavenDB_17999/CompareExchange_Expiration_RavenData_v5.2_from50000.zip
  test/SlowTests/SlowTests.csproj
Labels: v5.2

#13642 RavenDB-17999: add schema upgrade tests for CompareExchange And Expiration
  test/SlowTests/Cluster/CompareExchangeExpirationTest.cs
  test/SlowTests/SchemaUpgrade/Issues/SystemVersion/RavenDB_17999/CompareExchange_Expiration_RavenData_v5.2_from50000.zip
  test/SlowTests/SchemaUpgrade/Issues/SystemVersion/RavenDB_17999/CompareExchange_Expiration_RavenData_v5.2_new_from50000.zip
  test/SlowTests/SchemaUpgrade/Issues/SystemVersion/RavenDB_17999/CompareExchange_Expiration_RavenData_v5.3_from50000.zip
  test/SlowTests/SlowTests.csproj
Labels: v5.3

#13653 RavenDB-18057 - remove GetIndexesStatisticsOperation which is racy
  test/SlowTests/Issues/RavenDB-17937.cs
Labels: v4.2

#13656 RavenDB-18005 Fix the auto-generated query syntax
  src/Raven.Studio/typescript/common/queryUtil.ts
Labels: v5.3

#13665 Added .Net 6 sdk to github actions
  .github/workflows/FastTests.yml
Labels: v4.2

#13655 RavenDB-18061 added WriteStreamAsync to AsyncBlittableJsonTextWriter and removed WriteStream from AbstractBlittableJsonTextWriter
  src/Raven.Server/Smuggler/Documents/StreamDestination.cs
  src/Sparrow/Json/AbstractBlittableJsonTextWriter.cs
  src/Sparrow/Json/AsyncBlittableJsonTextWriter.cs
Labels: v5.3

#13662 RavenDB-18021 added SNMP endpoint for experimental features
  src/Raven.Server/Commercial/SetupManager.cs
  src/Raven.Server/Config/Categories/CoreConfiguration.cs
  src/Raven.Server/Documents/Queries/GraphQueryRunner.cs
  src/Raven.Server/Exceptions/FeaturesAvailabilityException.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.16/FeatureAnyExperimental.cs
  src/Raven.Server/Monitoring/Snmp/SnmpOids.cs
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Utils/Features/Feature.cs
  src/Raven.Server/Utils/Features/FeatureGuardian.cs
  src/Raven.Server/Utils/Features/FeaturesAvailability.cs
  src/Raven.Server/Web/System/SetupHandler.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v4.2

#13676 RavenDB-17622 Expose new stats on indexing performance view
  src/Raven.Client/Documents/Indexes/IndexingPerformanceOperation.cs
  src/Raven.Server/Documents/Indexes/IndexingStatsAggregator.cs
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexPerformance.ts
Labels: v5.2

#13674 RavenDB-17702 remove empty change vector and fix TryPutSegmentDirectly
  src/Raven.Server/Documents/TimeSeries/TimeSeriesStorage.cs
  test/SlowTests/Issues/RavenDB-17702.cs
Labels: v5.2

#13670 RavenDB-18068 do not fail to load database if we failed to delete DatabaseInfoCache
  src/Raven.Server/Documents/DatabaseInfoCache.cs
  src/Raven.Server/Documents/DatabasesLandlord.cs
Labels: v4.2

#13679 RavenDB-16801 - StressTests.Client.TimeSeries.TimeSeriesStress.RapidR…
  test/StressTests/Client/TimeSeries/TimeSeriesStress.cs
Labels: v5.2

#13678 RavenDB-17702 rename
  src/Raven.Server/Documents/TimeSeries/TimeSeriesStorage.cs
Labels: v5.2

#13681 RavenDB-17260 Deletion of in-memory replacement index must take into account that we there might be temp files of previous replacement in the same temp directory because we cannot restart in-memory environment and move its directory.
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  test/SlowTests/Issues/RavenDB_17260.cs
Labels: v4.2

#13683 4.2 to 5.2 merge
  .github/workflows/FastTests.yml
  src/Raven.Server/Commercial/SetupManager.cs
  src/Raven.Server/Config/Categories/CoreConfiguration.cs
  src/Raven.Server/Documents/DatabaseInfoCache.cs
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  src/Raven.Server/Documents/Queries/GraphQueryRunner.cs
  src/Raven.Server/Exceptions/FeaturesAvailabilityException.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.16/FeatureAnyExperimental.cs
  src/Raven.Server/Monitoring/Snmp/SnmpOids.cs
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Utils/Features/Feature.cs
  src/Raven.Server/Utils/Features/FeatureGuardian.cs
  src/Raven.Server/Utils/Features/FeaturesAvailability.cs
  src/Raven.Server/Web/System/SetupHandler.cs
  test/RachisTests/DatabaseCluster/RemoveNodeFromCluster.cs
  test/SlowTests/Issues/RavenDB_17260.cs
  test/Tests.Infrastructure/TestBase.cs
  tools/rvn/rvn.csproj
Labels: v5.2

#13677 RavenDB-17223 fix CanIndexRollups test
  test/SlowTests/Client/TimeSeries/Issues/RavenDB-16060.cs
  test/SlowTests/Client/TimeSeries/Operations/TimeSeriesOperations.cs
  test/SlowTests/Client/TimeSeries/Policies/TimeSeriesConfigurationTests.cs
  test/SlowTests/Client/TimeSeries/Query/QueryFromMultipleTimeSeries.cs
  test/SlowTests/Client/TimeSeries/Session/TimeSeriesTypedSessionTests.cs
  test/SlowTests/Issues/RavenDB_14932.cs
  test/Tests.Infrastructure/RavenTestBase.cs
  test/Tests.Infrastructure/TimeSeriesTestBase.cs
Labels: v5.2

#13684 5.2 to 5.3 merge
  .github/workflows/FastTests.yml
  src/Raven.Client/Documents/Indexes/IndexingPerformanceOperation.cs
  src/Raven.Server/Commercial/SetupManager.cs
  src/Raven.Server/Config/Categories/CoreConfiguration.cs
  src/Raven.Server/Config/Categories/IndexingConfiguration.cs
  src/Raven.Server/Documents/DatabaseInfoCache.cs
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/Handlers/BulkInsertHandler.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  src/Raven.Server/Documents/Indexes/IndexingStatsAggregator.cs
  src/Raven.Server/Documents/Queries/GraphQueryRunner.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesStorage.cs
  src/Raven.Server/Exceptions/FeaturesAvailabilityException.cs
  src/Raven.Server/Integrations/PostgreSQL/Handlers/PostgreSqlIntegrationHandler.cs
  src/Raven.Server/Integrations/PostgreSQL/PgServer.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.16/FeatureAnyExperimental.cs
  src/Raven.Server/Monitoring/Snmp/SnmpOids.cs
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
  src/Raven.Server/RavenServer.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Utils/Features/Feature.cs
  src/Raven.Server/Utils/Features/FeatureGuardian.cs
  src/Raven.Server/Utils/Features/FeaturesAvailability.cs
  src/Raven.Server/Web/System/SetupHandler.cs
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexPerformance.ts
  test/FastTests/Client/BulkInserts.cs
  test/RachisTests/DatabaseCluster/RemoveNodeFromCluster.cs
  test/SlowTests/Client/BulkInserts.cs
  test/SlowTests/Client/TimeSeries/Issues/RavenDB-16060.cs
  test/SlowTests/Client/TimeSeries/Operations/TimeSeriesOperations.cs
  test/SlowTests/Client/TimeSeries/Policies/TimeSeriesConfigurationTests.cs
  test/SlowTests/Client/TimeSeries/Query/QueryFromMultipleTimeSeries.cs
  test/SlowTests/Client/TimeSeries/Session/TimeSeriesTypedSessionTests.cs
  test/SlowTests/Issues/RavenDB-17702.cs
  test/SlowTests/Issues/RavenDB_14932.cs
  test/SlowTests/Issues/RavenDB_17260.cs
  test/StressTests/Client/TimeSeries/TimeSeriesStress.cs
  test/Tests.Infrastructure/RavenTestBase.cs
  test/Tests.Infrastructure/TestBase.cs
  test/Tests.Infrastructure/TimeSeriesTestBase.cs
  tools/rvn/rvn.csproj
Labels: v5.3

#13685 HRINT-2463 Use newest Microsoft.NET.Test.Sdk package
  bench/Regression.Benchmark/Regression.Benchmark.csproj
  test/BenchmarkTests/BenchmarkTests.csproj
  test/EmbeddedTests/EmbeddedTests.csproj
  test/FastTests/FastTests.csproj
  test/InterversionTests/InterversionTests.csproj
  test/LicenseTests/LicenseTests.csproj
  test/RachisTests/RachisTests.csproj
  test/SlowTests/SlowTests.csproj
  test/StressTests/StressTests.csproj
Labels: v4.2

#13687 4.2 to 5.2 merge
  bench/Regression.Benchmark/Regression.Benchmark.csproj
  src/Raven.Server/Raven.Server.csproj
  test/BenchmarkTests/BenchmarkTests.csproj
  test/EmbeddedTests/EmbeddedTests.csproj
  test/FastTests/FastTests.csproj
  test/InterversionTests/InterversionTests.csproj
  test/LicenseTests/LicenseTests.csproj
  test/RachisTests/RachisTests.csproj
  test/SlowTests/SlowTests.csproj
  test/StressTests/StressTests.csproj
Labels: v5.2

#13689 5.2 to 5.3 merge
  bench/Regression.Benchmark/Regression.Benchmark.csproj
  src/Raven.Server/Documents/Handlers/Debugging/ServerWideDebugInfoPackageHandler.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Server/ServerWide/DebugInfoPackageUtils.cs
  test/BenchmarkTests/BenchmarkTests.csproj
  test/EmbeddedTests/EmbeddedTests.csproj
  test/FastTests/FastTests.csproj
  test/InterversionTests/InterversionTests.csproj
  test/LicenseTests/LicenseTests.csproj
  test/RachisTests/RachisTests.csproj
  test/SlowTests/Authentication/AuthenticationDebugPackageInfoTests.cs
  test/SlowTests/SlowTests.csproj
  test/StressTests/StressTests.csproj
Labels: v5.3

#13692 RavenDB-18062 Merge restore and compile tasks into one task
  .gitignore
  src/Raven.Studio/package.json
  src/Raven.Studio/scripts/fix_packages.js
Labels: v5.3

#13691 RavenDB-18062 Merge restore and compile tasks into one task
  .gitignore
  src/Raven.Studio/package.json
Labels: v4.2

#13686 RavenDB-17499 - SlowTests.Issues.RavenDB_16961.StripRevisionFlagFromT…
  test/SlowTests/Issues/RavenDB-16961.cs
Labels: v4.2

#13703 bump npm packages
  src/Raven.Studio/package-lock.json
  src/Raven.Studio/package.json
Labels: v5.3

#13697 RavenDB-15556 test fix
  test/SlowTests/SparrowTests/LoggingSourceTests.cs
Labels: v4.2

#13704 HRINT-2567 Display tests with full namespaces for test filtering to work properly
  test/SlowTests/Graph/AdvancedGraphQueries.cs
Labels: v4.2

#13705 4.2 to 5.2 merge
  .gitignore
  src/Raven.Studio/package.json
  test/RachisTests/SubscriptionFailoverWIthWaitingChains.cs
  test/SlowTests/Graph/AdvancedGraphQueries.cs
  test/SlowTests/Issues/RavenDB-16961.cs
  test/SlowTests/SparrowTests/LoggingSourceTests.cs
Labels: v5.2

#13706 5.2 to 5.3 merge
  .gitignore
  test/RachisTests/SubscriptionFailoverWIthWaitingChains.cs
  test/SlowTests/Graph/AdvancedGraphQueries.cs
  test/SlowTests/Issues/RavenDB-16961.cs
  test/SlowTests/SparrowTests/LoggingSourceTests.cs
Labels: v5.3

#13710 HRINT-2574 Changed logger to default microsoft trx format
  test/BenchmarkTests/BenchmarkTests.csproj
  test/EmbeddedTests/EmbeddedTests.csproj
  test/FastTests/FastTests.csproj
  test/InterversionTests/InterversionTests.csproj
  test/LicenseTests/LicenseTests.csproj
  test/RachisTests/RachisTests.csproj
  test/SlowTests/SlowTests.csproj
  test/StressTests/StressTests.csproj
  test/Studio/Studio.csproj
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
  test/Tryouts/Tryouts.csproj
Labels: v4.2

#13708 RavenDB-18096 - Casting to a numberic type in an index
  src/Raven.Server/Json/BlittableNumber.cs
  test/SlowTests/Issues/RavenDB-18096.cs
Labels: v4.2
