Repository ravendb/ravendb, pull requests merged in 2022-03, with the labels that each got.

#13719 RavenDB-17855 : flaky test adjustments
  test/SlowTests/Issues/RavenDB_17231.cs
Labels: v4.2

#13693 RavenDB-18079 fix skipping beyond number of entries for embedded iterator
  src/Voron/Data/Fixed/FixedSizeIterators.cs
  test/SlowTests/Core/Commands/Documents.cs
  test/SlowTests/Server/Documents/Patching/AdvancedPatching.cs
Labels: v4.2

#13716 RavenDB-18110 - better error when we fail to read the attachment stream
  src/Raven.Server/Documents/Replication/ReplicationItems/AttachmentReplicationItem.cs
Labels: v5.3

#13723 bump npm packages - fix
  src/Raven.Studio/package-lock.json
  src/Raven.Studio/package.json
Labels: v5.3

#13724 5.2 to 5.3 merge
  src/Raven.Server/Documents/CollectionName.cs
  src/Raven.Server/Documents/CountersStorage.cs
  src/Raven.Server/Documents/ETL/EtlLoader.cs
  src/Raven.Server/Documents/Indexes/Static/Counters/MapCountersIndex.cs
  src/Raven.Server/Documents/Indexes/Static/Counters/MapReduceCountersIndex.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/Documents/TombstoneCleaner.cs
  src/Raven.Server/Json/BlittableNumber.cs
  src/Raven.Server/Raven.Server.csproj
  src/Voron/Data/Fixed/FixedSizeIterators.cs
  test/BenchmarkTests/BenchmarkTests.csproj
  test/EmbeddedTests/EmbeddedTests.csproj
  test/FastTests/FastTests.csproj
  test/InterversionTests/InterversionTests.csproj
  test/InterversionTests/RavenDB-17518.cs
  test/LicenseTests/LicenseTests.csproj
  test/RachisTests/RachisTests.csproj
  test/SlowTests/Core/Commands/Documents.cs
  test/SlowTests/Issues/RavenDB-18096.cs
  test/SlowTests/Issues/RavenDB_17231.cs
  test/SlowTests/Server/Documents/Counters/CountersTombstoneCleaner.cs
  test/SlowTests/Server/Documents/ETL/EtlCountersTests.cs
  test/SlowTests/Server/Documents/Patching/AdvancedPatching.cs
  test/SlowTests/SlowTests.csproj
  test/StressTests/StressTests.csproj
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
  test/Tryouts/Tryouts.csproj
  tools/Raven.Debug/Raven.Debug.csproj
Labels: v5.3

#13735 RavenDB-18076: Baseline benchmark update.
  bench/Directory.Build.props
  bench/Voron.Benchmark/Configuration.cs
  bench/Voron.Benchmark/Program.cs
  bench/Voron.Benchmark/StorageBenchmark.cs
  bench/Voron.Benchmark/Table/TableFillRandom.cs
  bench/Voron.Benchmark/Table/TableInsertRandom.cs
  bench/Voron.Benchmark/Utils.cs
  bench/Voron.Benchmark/Voron.Benchmark.csproj
Labels: v5.2, v5.3

#13736 RavenDB-18143 skipped FastTests.Server.Documents.DocCompression.Can_compact_from_no_compression_to_compressed on macOS
  test/FastTests/Server/Documents/DocCompression.cs
  test/Tests.Infrastructure/LicenseRequiredFactAttribute.cs
  test/Tests.Infrastructure/LicenseRequiredTheoryAttribute.cs
  test/Tests.Infrastructure/MultiplatformFactAttribute.cs
  test/Tests.Infrastructure/MultiplatformTheoryAttribute.cs
  test/Tests.Infrastructure/NightlyBuildMultiplatformFactAttribute.cs
  test/Tests.Infrastructure/NightlyBuildMultiplatformTheoryAttribute.cs
Labels: v5.2

#13739 RavenDB-18143 skipped FastTests.Server.Documents.DocCompression.Can_compact_from_compression_to_not_compressed on macOS
  test/FastTests/Server/Documents/DocCompression.cs
Labels: v5.2

#13740 RavenDB-18143 updated libsodium.mac.x64.dylib
  libs/libsodium/libsodium.mac.x64.dylib
  test/FastTests/Server/Documents/DocCompression.cs
Labels: v5.2

#13745 5.2 to 5.3 merge
  bench/Directory.Build.props
  bench/Voron.Benchmark/Configuration.cs
  bench/Voron.Benchmark/Program.cs
  bench/Voron.Benchmark/StorageBenchmark.cs
  bench/Voron.Benchmark/Table/TableFillRandom.cs
  bench/Voron.Benchmark/Table/TableInsertRandom.cs
  bench/Voron.Benchmark/Utils.cs
  bench/Voron.Benchmark/Voron.Benchmark.csproj
  libs/libsodium/libsodium.mac.x64.dylib
  test/FastTests/Server/Documents/DocCompression.cs
  test/Tests.Infrastructure/LicenseRequiredFactAttribute.cs
  test/Tests.Infrastructure/LicenseRequiredTheoryAttribute.cs
  test/Tests.Infrastructure/MultiplatformFactAttribute.cs
  test/Tests.Infrastructure/MultiplatformTheoryAttribute.cs
  test/Tests.Infrastructure/NightlyBuildMultiplatformFactAttribute.cs
  test/Tests.Infrastructure/NightlyBuildMultiplatformTheoryAttribute.cs
Labels: v5.3

#13748 RavenDB-18058 : flaky test adjustments
  test/SlowTests/Server/Documents/ETL/Olap/LocalTests.cs
  test/SlowTests/Server/Documents/ETL/Olap/S3Tests.cs
Labels: v5.2

#13746 RavenDB-17947 : clean olap test from s3
  test/SlowTests/Server/Documents/ETL/Olap/S3Tests.cs
Labels: v5.3

#13743 RavenDB-18076 : fix errors in Voron.Benchmark - v4.2 fix
  bench/Voron.Benchmark/StorageBenchmark.cs
  bench/Voron.Benchmark/Voron.Benchmark.csproj
Labels: v4.2

#13732 RavenDB-18142: CSV filename was not UrlEncoded
  src/Raven.Server/Documents/Handlers/StreamCsvResultWriter.cs
Labels: v5.3

#13752 RavenDB-18001 : flaky test adjustments
  test/SlowTests/Client/Counters/CountersReplication.cs
Labels: v4.2

#13754 RavenDB-18092 Instead of throwing exception on LoadLicenseLimits call…
  src/Raven.Server/Documents/Indexes/IndexStore.cs
Labels: v4.2

#13760 RavenDB-18157 added indexer to DynamicArray
  src/Raven.Server/Documents/Indexes/Static/DynamicArray.cs
  test/FastTests/Issues/RavenDB_18157.cs
Labels: v5.2

#13751 RavenDB-17955_new - adding logs
  src/Raven.Server/Documents/Handlers/Debugging/ServerWideDebugInfoPackageHandler.cs
Labels: v5.2

#13764 RavenDB-17107 Sharding - Studio work - development helper
  src/Raven.Studio/typescript/common/developmentHelper.ts
  src/Raven.Studio/typescript/common/helpers/database/collectionsTracker.ts
  src/Raven.Studio/typescript/common/shell/databasesManager.ts
  src/Raven.Studio/typescript/common/shell/footer.ts
  src/Raven.Studio/typescript/viewmodels/common/sharding/shardAwareContainer.ts
  src/Raven.Studio/typescript/viewmodels/database/query/query.ts
  src/Raven.Studio/typescript/viewmodels/database/settings/studioConfiguration.ts
  src/Raven.Studio/typescript/viewmodels/shardViewModelBase.ts
  src/Raven.Studio/typescript/viewmodels/shell.ts
  src/Raven.Studio/wwwroot/Content/css/basic-layout.less
Labels: Sharding

#13765 RavenDB-17577 Adding new configuration option Indexing.Static.RequireAdminToDeployJavaScriptIndexes
  src/Raven.Server/Config/Categories/IndexingConfiguration.cs
  src/Raven.Server/Documents/Handlers/Admin/AdminIndexHandler.cs
  test/SlowTests/Issues/RavenDB_17577.cs
Labels: v5.2

#13770 RavenDB-18152 - Add AddOrPatch and AddOrIncrement to IAsyncAdvancedSessionOperations
  src/Raven.Client/Documents/Session/IAsyncAdvancedSessionOperations.Patch.cs
Labels: v5.2

#13775 RavenDB-17122 Forcing flush of the bulk insert's request stream when doing the initial write.
  src/Raven.Client/Documents/BulkInsert/BulkInsertOperation.cs
Labels: v4.2

#13776 RavenDB-17122 Forcing flush of the bulk insert's request stream when doing the initial write.
  src/Raven.Client/Documents/BulkInsert/BulkInsertOperation.cs
  test/FastTests/Client/BulkInserts.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v5.2

#13781 RavenDB-17599 Adjustments to RavenExplicitDataAttibute
  test/FastTests/Server/Documents/Indexing/Auto/BasicAutoMapIndexing.cs
  test/FastTests/Server/Documents/Indexing/Auto/BasicAutoMapReduceIndexing.cs
  test/FastTests/Server/Documents/Indexing/Static/BasicStaticMapIndexing.cs
  test/FastTests/Server/Documents/Indexing/Static/BasicStaticMapReduceIndexing.cs
  test/SlowTests/Corax/CoraxSlowQueryTests.cs
  test/SlowTests/Server/Documents/Indexing/ExactSearchOnAutoIndex_RavenDB_8006.cs
  test/Tests.Infrastructure/RavenDataAttribute.cs
  test/Tests.Infrastructure/RavenExplicitDataAttribute.cs
  test/Tests.Infrastructure/RavenLowLevelTestBase.cs
  test/Tests.Infrastructure/RavenTestBase.cs
Labels: Corax

#13784 RavenDB-17933: fix race condition in test
  test/SlowTests/Client/Subscriptions/SubscriptionsBasic.cs
Labels: v4.2

#13793 4.2 to 5.2 merge
  test/SlowTests/Client/Subscriptions/SubscriptionsBasic.cs
Labels: v5.2

#13794 5.2 to 5.3 merge
  .github/workflows/FastTests.yml
  bench/BulkInsert.Benchmark/BulkInsert.Benchmark.csproj
  bench/Indexing.Benchmark/Indexing.Benchmark.csproj
  bench/Micro.Benchmark/Micro.Benchmark.csproj
  bench/Regression.Benchmark/Regression.Benchmark.csproj
  bench/SubscriptionFailover.Benchmark/SubscriptionFailover.Benchmark.csproj
  bench/Subscriptions.Benchmark/Subscriptions.Benchmark.csproj
  bench/TimeSeries.Benchmark/TimeSeries.Benchmark.csproj
  bench/Voron.Benchmark/Voron.Benchmark.csproj
  src/Raven.Client/Documents/BulkInsert/BulkInsertOperation.cs
  src/Raven.Client/Documents/Session/IAsyncAdvancedSessionOperations.Patch.cs
  src/Raven.Client/Raven.Client.csproj
  src/Raven.Embedded/ServerOptions.cs
  src/Raven.Server/Config/Categories/IndexingConfiguration.cs
  src/Raven.Server/Documents/Handlers/Admin/AdminIndexHandler.cs
  src/Raven.Server/Documents/Handlers/Debugging/ServerWideDebugInfoPackageHandler.cs
  src/Raven.Server/Documents/Indexes/Static/DynamicArray.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Studio/Raven.Studio.csproj
  src/Sparrow.Server/Sparrow.Server.csproj
  src/Voron/Voron.csproj
  test/BenchmarkTests/BenchmarkTests.csproj
  test/EmbeddedTests/EmbeddedTests.csproj
  test/FastTests/Client/BulkInserts.cs
  test/FastTests/FastTests.csproj
  test/FastTests/Issues/RavenDB_18157.cs
  test/InterversionTests/InterversionTests.csproj
  test/LicenseTests/LicenseTests.csproj
  test/RachisTests/RachisTests.csproj
  test/SlowTests/Client/Subscriptions/SubscriptionsBasic.cs
  test/SlowTests/Issues/RavenDB-17250.cs
  test/SlowTests/Issues/RavenDB_17577.cs
  test/SlowTests/Server/Documents/Counters/CountersTombstoneCleaner.cs
  test/SlowTests/SlowTests.csproj
  test/StressTests/StressTests.csproj
  test/Tests.Infrastructure/TestBase.cs
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
  test/Tryouts/Tryouts.csproj
  tools/Raven.Debug/Raven.Debug.csproj
  tools/Raven.Migrator/Raven.Migrator.csproj
  tools/TypingsGenerator/TypingsGenerator.csproj
  tools/Voron.Recovery/Voron.Recovery.csproj
  tools/rvn/rvn.csproj
Labels: v5.3

#13796 RavenDB-18293 disable TCP Compression on macOS if ZSTD cannot be loaded
  src/Raven.Client/Documents/Conventions/DocumentConventions.cs
  test/Tests.Infrastructure/Utils/TestOutcomeAnalyzer.cs
Labels: v5.3

#13797 RavenDB-18295 introduced RavenFactAttribute & RavenTheoryAttribute
  test/FastTests/Client/BulkInserts.cs
  test/Tests.Infrastructure/RavenFactAttribute.cs
  test/Tests.Infrastructure/RavenTestCategory.cs
  test/Tests.Infrastructure/RavenTheoryAttribute.cs
  test/Tests.Infrastructure/XunitExtensions/RavenTraitDiscoverer.cs
Labels: Sharding

#13780 RavenDB-7070 Synchronizing RavenDataAttribute with feature/corax branch. Added RavenDataExplicitConfiguration.
  test/Tests.Infrastructure/RavenDataAttribute.cs
  test/Tests.Infrastructure/RavenExplicitDataAttribute.cs
Labels: Sharding

#13798 5.3 to corax merge
  .github/workflows/FastTests.yml
  bench/BulkInsert.Benchmark/BulkInsert.Benchmark.csproj
  bench/Indexing.Benchmark/Indexing.Benchmark.csproj
  bench/Micro.Benchmark/Micro.Benchmark.csproj
  bench/Regression.Benchmark/Regression.Benchmark.csproj
  bench/SubscriptionFailover.Benchmark/SubscriptionFailover.Benchmark.csproj
  bench/Subscriptions.Benchmark/Subscriptions.Benchmark.csproj
  bench/TimeSeries.Benchmark/TimeSeries.Benchmark.csproj
  bench/Voron.Benchmark/Program.cs
  bench/Voron.Benchmark/Voron.Benchmark.csproj
  src/Corax/Corax.csproj
  src/Raven.Client/Documents/BulkInsert/BulkInsertOperation.cs
  src/Raven.Client/Documents/Conventions/DocumentConventions.cs
  src/Raven.Client/Documents/Session/IAsyncAdvancedSessionOperations.Patch.cs
  src/Raven.Client/Raven.Client.csproj
  src/Raven.Embedded/ServerOptions.cs
  src/Raven.Server/Config/Categories/IndexingConfiguration.cs
  src/Raven.Server/Documents/Handlers/Admin/AdminIndexHandler.cs
  src/Raven.Server/Documents/Handlers/Debugging/ServerWideDebugInfoPackageHandler.cs
  src/Raven.Server/Documents/Indexes/Static/DynamicArray.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Studio/Raven.Studio.csproj
  src/Sparrow.Server/Sparrow.Server.csproj
  src/Voron/Voron.csproj
  test/BenchmarkTests/BenchmarkTests.csproj
  test/EmbeddedTests/EmbeddedTests.csproj
  test/FastTests/Client/BulkInserts.cs
  test/FastTests/FastTests.csproj
  test/FastTests/Issues/RavenDB_18157.cs
  test/InterversionTests/InterversionTests.csproj
  test/LicenseTests/LicenseTests.csproj
  test/RachisTests/RachisTests.csproj
  test/SlowTests/Client/Subscriptions/SubscriptionsBasic.cs
  test/SlowTests/Cluster/ClusterIndexNotificationsTest.cs
  test/SlowTests/Issues/RavenDB-15900.cs
  test/SlowTests/Issues/RavenDB-17250.cs
  test/SlowTests/Issues/RavenDB_17577.cs
  test/SlowTests/Server/Documents/Counters/CountersTombstoneCleaner.cs
  test/SlowTests/SlowTests.csproj
  test/StressTests/Cluster/ClusterIndexNotificationsTestStress.cs
  test/StressTests/StressTests.csproj
  test/Tests.Infrastructure/TestBase.cs
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
  test/Tests.Infrastructure/Utils/TestOutcomeAnalyzer.cs
  test/Tryouts/CoraxEnron.cs
  test/Tryouts/Tryouts.csproj
  tools/Raven.Debug/Raven.Debug.csproj
  tools/Raven.Migrator/Raven.Migrator.csproj
  tools/TypingsGenerator/TypingsGenerator.csproj
  tools/Voron.Recovery/Voron.Recovery.csproj
  tools/rvn/rvn.csproj
Labels: Corax

#13799 5.3 to sharding merge
  .github/workflows/FastTests.yml
  bench/BulkInsert.Benchmark/BulkInsert.Benchmark.csproj
  bench/Indexing.Benchmark/Indexing.Benchmark.csproj
  bench/Micro.Benchmark/Micro.Benchmark.csproj
  bench/Regression.Benchmark/Regression.Benchmark.csproj
  bench/SubscriptionFailover.Benchmark/SubscriptionFailover.Benchmark.csproj
  bench/Subscriptions.Benchmark/Subscriptions.Benchmark.csproj
  bench/TimeSeries.Benchmark/TimeSeries.Benchmark.csproj
  bench/Voron.Benchmark/Voron.Benchmark.csproj
  src/Raven.Client/Documents/BulkInsert/BulkInsertOperation.cs
  src/Raven.Client/Documents/Conventions/DocumentConventions.cs
  src/Raven.Client/Documents/Session/IAsyncAdvancedSessionOperations.Patch.cs
  src/Raven.Client/Raven.Client.csproj
  src/Raven.Embedded/ServerOptions.cs
  src/Raven.Server/Config/Categories/IndexingConfiguration.cs
  src/Raven.Server/Documents/Handlers/Admin/AdminIndexHandler.cs
  src/Raven.Server/Documents/Handlers/Debugging/ServerWideDebugInfoPackageHandler.cs
  src/Raven.Server/Documents/Indexes/Static/DynamicArray.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Studio/Raven.Studio.csproj
  src/Sparrow.Server/Sparrow.Server.csproj
  src/Voron/Voron.csproj
  test/BenchmarkTests/BenchmarkTests.csproj
  test/EmbeddedTests/EmbeddedTests.csproj
  test/FastTests/Client/BulkInserts.cs
  test/FastTests/FastTests.csproj
  test/FastTests/Issues/RavenDB_18157.cs
  test/InterversionTests/InterversionTests.csproj
  test/LicenseTests/LicenseTests.csproj
  test/RachisTests/RachisTests.csproj
  test/SlowTests/Client/Subscriptions/SubscriptionsBasic.cs
  test/SlowTests/Cluster/ClusterIndexNotificationsTest.cs
  test/SlowTests/Issues/RavenDB-15900.cs
  test/SlowTests/Issues/RavenDB-17250.cs
  test/SlowTests/Issues/RavenDB_17577.cs
  test/SlowTests/Server/Documents/Counters/CountersTombstoneCleaner.cs
  test/SlowTests/SlowTests.csproj
  test/StressTests/Cluster/ClusterIndexNotificationsTestStress.cs
  test/StressTests/StressTests.csproj
  test/Tests.Infrastructure/TestBase.cs
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
  test/Tests.Infrastructure/Utils/TestOutcomeAnalyzer.cs
  test/Tryouts/Tryouts.csproj
  tools/Raven.Debug/Raven.Debug.csproj
  tools/Raven.Migrator/Raven.Migrator.csproj
  tools/TypingsGenerator/TypingsGenerator.csproj
  tools/Voron.Recovery/Voron.Recovery.csproj
  tools/rvn/rvn.csproj
Labels: Sharding

#13800 RavenDB-17943 exposed SearchEngineMode and DatabaseMode in Options
  test/Tests.Infrastructure/RavenDataAttribute.cs
  test/Tests.Infrastructure/RavenTestBase.cs
Labels: Sharding

#13804 RavenDB-18300 Adding debug info to the exception message when a committed and flushed transaction was not found in ActiveTransactions
  src/Voron/StorageEnvironment.cs
Labels: v5.3

#13807 4.2 to 5.3 merge
  src/Voron/StorageEnvironment.cs
Labels: v5.3

#13815 RavenDB-17301 : flaky test adjustments
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
Labels: v4.2

#13817 RavenDB-17599: unreachable code detected and casting warning cleanup
  src/Voron/Data/Sets/PForDecoder.cs
  src/Voron/Data/Sets/SetLeafPage.cs
Labels: Corax

#13825 RavenDB-18123 Setup Wizard Welcome Screen - Fix the info msg
  src/Raven.Studio/wwwroot/App/views/wizard/welcome.html
Labels: v5.2

#13824 4.2 to 5.2 merge
  .github/workflows/conventions.yml
  .github/workflows/label.yml
  src/Raven.Server/ServerWide/Maintenance/ClusterObserver.cs
  src/Raven.Server/Web/System/DatabasesHandler.cs
  src/Sparrow/Json/UnmanagedBuffersPool.cs
  src/Voron/Data/Tables/Table.cs
  src/Voron/Impl/Backup/FullBackup.cs
  src/Voron/Impl/FileHeaders/HeaderAccessor.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/Impl/Paging/AbstractPager.cs
  src/Voron/Platform/Posix/PosixTempMemoryMapPager.cs
  src/Voron/Platform/Win32/WindowsMemoryMapPager.cs
  src/Voron/StorageEnvironment.cs
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
  test/SlowTests/Issues/RavenDB-15625.cs
  test/SlowTests/Voron/Issues/RavenDB_18059.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
  test/Tests.Infrastructure/RavenTestBase.cs
  tools/Raven.Debug/GCDump/GCHeapDumper.cs
Labels: v5.2

#13829 5.2 to 5.3 merge
  .github/workflows/conventions.yml
  .github/workflows/label.yml
  src/Raven.Server/ServerWide/Maintenance/ClusterObserver.cs
  src/Raven.Server/Web/System/DatabasesHandler.cs
  src/Raven.Studio/wwwroot/App/views/wizard/welcome.html
  src/Sparrow/Json/UnmanagedBuffersPool.cs
  src/Voron/Data/Tables/Table.cs
  src/Voron/Impl/Backup/FullBackup.cs
  src/Voron/Impl/FileHeaders/HeaderAccessor.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/Impl/Paging/AbstractPager.cs
  src/Voron/Platform/Posix/PosixTempMemoryMapPager.cs
  src/Voron/Platform/Win32/WindowsMemoryMapPager.cs
  src/Voron/StorageEnvironment.cs
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
  test/SlowTests/Issues/RavenDB-15625.cs
  test/SlowTests/Voron/Issues/RavenDB_18059.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
  test/Tests.Infrastructure/RavenTestBase.cs
  tools/Raven.Debug/GCDump/GCHeapDumper.cs
Labels: v5.3

#13834 RavenDB-18070 - Sharding - Create Sample Data View Endpoints - GET /databases/*/studio/sample-data/classes
  src/Raven.Server/Documents/Handlers/Processors/AbstractSampleDataHandlerProcessorForGetSampleDataClasses.cs
  src/Raven.Server/Documents/Handlers/Processors/SampleDataHandlerProcessorForGetSampleDataClasses.cs
  src/Raven.Server/Documents/Handlers/Processors/SampleDataHandlerProcessorForPostSampleData.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/ShardedSampleDataHandlerProcessorForGetSampleDataClasses.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/ShardedSampleDataHandlerProcessorForPostSampleData.cs
  src/Raven.Server/Documents/Sharding/Handlers/ShardedSampleDataHandler.cs
  src/Raven.Server/Web/Studio/SampleDataHandler.cs
Labels: Sharding

#13833 RavenDB-18299 Unreachable code detected and casting warning cleanup
  src/Corax/IndexWriter.cs
  src/Corax/Queries/SortingMatch.Comparers.cs
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxDocumentConverter.cs
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxQueryEvaluator.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/LuceneIndexWriteOperation.cs
  test/FastTests/Corax/IndexSearcher.cs
  test/FastTests/Corax/OrderByMultiSorting.cs
  test/FastTests/Corax/OrderBySorting.cs
Labels: Corax

#13835 RavenDB-18214 address PR comment & fix tests
  src/Raven.Server/Documents/Sharding/Handlers/Processors/ShardedIndexHandlerProcessorForGetDatabaseIndexStatistics.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/ShardedIndexHandlerProcessorForGetIndexesStatus.cs
  test/SlowTests/Core/Commands/Other.cs
  test/SlowTests/Sharding/ShardedIndexHandlerTests.cs
Labels: Sharding

#13729 RDBS-8983 Rolling index updates seems to be broken
  src/Raven.Client/Documents/Indexes/RollingIndex.cs
  src/Raven.Client/ServerWide/DatabaseRecord.cs
  src/Raven.Server/Documents/Handlers/Debugging/ServerWideDebugInfoPackageHandler.cs
  src/Raven.Server/Documents/Indexes/Auto/AutoIndexDefinitionBaseServerSide.cs
  src/Raven.Server/Documents/Indexes/Errors/FaultyAutoIndexDefinition.cs
  src/Raven.Server/Documents/Indexes/Errors/FaultyIndexDefinition.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/IndexDefinitionBaseServerSide.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  src/Raven.Server/Documents/Indexes/Static/MapIndexDefinition.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  test/SlowTests/Rolling/RollingIndexesClusterTests.cs
Labels: v5.2

#13832 RavenDB-18269 Always show the Replace License button in the about page
  src/Raven.Studio/wwwroot/App/views/shell/about.html
Labels: v5.3

#13838 RavenDB-17861 Remove '@timeseries-snapshot' from metadata
  src/Raven.Studio/typescript/models/database/documents/documentMetadata.ts
Labels: v5.2

#13849 RavenDB-18334 fixed SmugglerResult deserialization
  src/Raven.Client/Documents/Smuggler/SmugglerResult.cs
  src/Sparrow/Json/JsonDeserializationBase.cs
  test/FastTests/Issues/RavenDB_18334.cs
Labels: v5.2

#13850 RavenDB-18018
  src/Raven.Server/Documents/Handlers/Processors/AbstractStudioStatsHandlerProcessorForGetFooterStats.cs
  src/Raven.Server/Documents/Handlers/Processors/StudioStatsHandlerProcessorForGetFooterStats.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/ShardedStudioStatsHandlerProcessorForGetFooterStats.cs
  src/Raven.Server/Documents/Sharding/Handlers/ShardedStudioStatsHandler.cs
  src/Raven.Server/Documents/Studio/FooterStatistics.cs
  src/Raven.Server/Web/Studio/StudioStatsHandler.cs
  test/FastTests/Sharding/Queries/BasicShardedQueryTests.cs
  test/SlowTests/Client/Operations/GetStudioFooterStatisticsOperationTests.cs
  test/Tests.Infrastructure/RavenTestBase.cs
Labels: Sharding

#13864 RavenDB-18212 implemented DELETE /databases/*/indexes
  src/Raven.Server/Documents/Handlers/IndexHandler.cs
  src/Raven.Server/Documents/Handlers/Processors/Indexes/AbstractIndexHandlerProcessorForDelete.cs
  src/Raven.Server/Documents/Handlers/Processors/Indexes/IndexHandlerProcessorForDelete.cs
  src/Raven.Server/Documents/Indexes/AbstractIndexDeleteProcessor.cs
  src/Raven.Server/Documents/Indexes/DatabaseIndexDeleteProcessor.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  src/Raven.Server/Documents/Indexes/Sharding/ShardedIndexDeleteProcessor.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Indexes/ShardedIndexHandlerProcessorForDelete.cs
  src/Raven.Server/Documents/Sharding/Handlers/ShardedIndexHandler.cs
  src/Raven.Server/Documents/Sharding/ShardedContext.Indexes.cs
Labels: Sharding

#13866 RavenDB-18359 sign setup-as-service.ps1 in build scripts
  scripts/copyAssets.ps1
Labels: v4.2

#13862 RavenDB-18338 IncrementalTimeSeriesTests.MultipleOperationsOnIncremen…
  test/SlowTests/Client/TimeSeries/IncrementalTimeSeriesTests.cs
Labels: v5.3

#13861 RavenDB-18337 - add the tcp listener only when it was successfully started
  src/Raven.Server/RavenServer.cs
Labels: v5.3

#13868 RavenDB-18215 Sharding - Edit Index View
  src/Raven.Studio/typescript/commands/database/index/getIndexDefinitionCommand.ts
  src/Raven.Studio/typescript/common/shell/clusterTopologyManager.ts
  src/Raven.Studio/typescript/models/resources/database.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/editIndex.ts
  src/Raven.Studio/typescript/viewmodels/shell.ts
Labels: Sharding

#13870 Build studio on push
  .github/workflows/compile.yml
Labels: v4.2

#13848 RavenDB-18332 FirstOrDefault in reduce may return null instead of dyn…
  src/Raven.Server/Documents/Indexes/Static/Extensions/LinqOnDynamic.cs
  test/SlowTests/Issues/RavenDB-18332.cs
Labels: v5.2

#13872 5.2 to 5.3 merge
  .github/workflows/compile.yml
  scripts/copyAssets.ps1
  src/Raven.Server/Documents/Indexes/Static/Extensions/LinqOnDynamic.cs
  src/Raven.Server/RavenServer.cs
  test/FastTests/Sparrow/ByteStringTests.cs
  test/SlowTests/Issues/RavenDB-16498.cs
  test/SlowTests/Issues/RavenDB-18332.cs
Labels: v5.3

#13876 RavenDB-18214 implemented /databases/*/indexes/staleness
  src/Raven.Server/Documents/Commands/GetIndexStalenessCommand.cs
  src/Raven.Server/Documents/Handlers/IndexHandler.cs
  src/Raven.Server/Documents/Handlers/Processors/Indexes/AbstractIndexHandlerProcessorForStale.cs
  src/Raven.Server/Documents/Handlers/Processors/Indexes/IndexHandlerProcessorForStale.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Indexes/ShardedIndexHandlerProcessorForStale.cs
  src/Raven.Server/Documents/Sharding/Handlers/ShardedIndexHandler.cs
  test/Tests.Infrastructure/Operations/GetIndexStalenessOperation.cs
Labels: Sharding

#13875 RavenDB-18214 Sharding - Indexes List View Endpoints
  src/Raven.Client/Documents/Operations/Indexes/GetIndexesOperation.cs
  src/Raven.Server/Documents/Commands/GetIndexesProgressCommand.cs
  src/Raven.Server/Documents/Handlers/Processors/Indexes/AbstractIndexHandlerProcessorForGetAll.cs
  src/Raven.Server/Json/JsonDeserializationServer.cs
Labels: Sharding

#13879 RavenDB-17943 introduced MaintenanceOperationExecutorTester
  src/Raven.Client/Documents/Operations/MaintenanceOperationExecutor.cs
  test/SlowTests/Issues/RavenDB-3314.cs
  test/Tests.Infrastructure/Extensions/OperationExecutorExtensions.cs
  test/Tests.Infrastructure/Utils/MaintenanceOperationExecutorTester.cs
Labels: Sharding

#13890 RavenDB-18278 Sharding - Unused Database IDs View
  src/Raven.Studio/typescript/commands/resources/getDatabaseStatsCommand.ts
  src/Raven.Studio/typescript/common/shell/menu/items/settings.ts
  src/Raven.Studio/typescript/viewmodels/database/advanced/databaseIDs.ts
Labels: Sharding

#13887 RavenDB-18219 Sharding - Database Record View
  src/Raven.Studio/typescript/common/shell/menu/items/settings.ts
  src/Raven.Studio/typescript/viewmodels/database/advanced/databaseRecord.ts
  src/Raven.Studio/typescript/viewmodels/shardViewModelBase.ts
Labels: Sharding

#13878 RavenDB-18368 Cleanup and refactoring of internal sharding API
  src/Raven.Client/ServerWide/DatabaseRecord.cs
  src/Raven.Client/ServerWide/Sharding/MigrationStatus.cs
  src/Raven.Client/ServerWide/Sharding/ShardBucketMigration.cs
  src/Raven.Client/ServerWide/Sharding/ShardBucketRange.cs
  src/Raven.Client/Util/ClientShardHelper.cs
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/ETL/EtlLoader.cs
  src/Raven.Server/Documents/ETL/EtlProcess.cs
  src/Raven.Server/Documents/Handlers/Debugging/ServerWideDebugInfoPackageHandler.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  src/Raven.Server/Documents/Replication/BucketMigrationReplication.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/Documents/ShardedDocumentDatabase.cs
  src/Raven.Server/Documents/Sharding/Handlers/ShardedBatchHandler.cs
  src/Raven.Server/Documents/Sharding/Handlers/ShardedDocumentHandler.cs
  src/Raven.Server/Documents/Sharding/Handlers/ShardedHiLoHandler.cs
  src/Raven.Server/Documents/Sharding/Handlers/ShardedOngoingTasks.cs
  src/Raven.Server/Documents/Sharding/Queries/ShardedQueryProcessor.cs
  src/Raven.Server/Documents/Sharding/ShardLocator.cs
  src/Raven.Server/Documents/Sharding/ShardedDatabaseContext.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/Commands/ClusterTransactionCommand.cs
  src/Raven.Server/ServerWide/Commands/DeleteDatabaseCommand.cs
  src/Raven.Server/ServerWide/Commands/ETL/UpdateEtlProcessStateCommand.cs
  src/Raven.Server/ServerWide/Commands/RemoveNodeFromDatabaseCommand.cs
  src/Raven.Server/ServerWide/Commands/Sharding/DestinationMigrationConfirmCommand.cs
  src/Raven.Server/ServerWide/Commands/Sharding/SourceMigrationCleanupCommand.cs
  src/Raven.Server/ServerWide/Commands/Sharding/SourceMigrationSendCompletedCommand.cs
  src/Raven.Server/ServerWide/Commands/Sharding/StartBucketMigrationCommand.cs
  src/Raven.Server/ServerWide/Commands/Subscriptions/AcknowledgeSubscriptionBatchCommand.cs
  src/Raven.Server/ServerWide/Commands/Subscriptions/RecordBatchSubscriptionDocumentsCommand.cs
  src/Raven.Server/ServerWide/Commands/Subscriptions/UpdateSubscriptionClientConnectionTime.cs
  src/Raven.Server/ServerWide/Commands/UpdateTopologyCommand.cs
  src/Raven.Server/ServerWide/JsonDeserializationCluster.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterObserver.cs
  src/Raven.Server/ServerWide/Maintenance/Sharding/BucketsMigrator.cs
  src/Raven.Server/ServerWide/RawDatabaseRecord.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Smuggler/Documents/MultiShardedDestination.cs
  src/Raven.Server/Smuggler/Documents/SingleShardDatabaseSmuggler.cs
  src/Raven.Server/Utils/ShardHelper.cs
  src/Raven.Server/Web/System/OngoingTasksHandler.cs
  test/SlowTests/Sharding/BucketMigration/BucketsMigratorTests.cs
  test/SlowTests/Sharding/Cluster/ReshardingTests.cs
  test/SlowTests/Sharding/ETL/ShardedEtlFailoverTests.cs
  test/SlowTests/Sharding/ETL/ShardedEtlTests.cs
Labels: Sharding

#13901 RavenDB-18383 fix System.ArgumentException: Invalid time unit None
  src/Raven.Server/Documents/TimeSeries/TimeSeriesPolicyRunner.cs
  test/SlowTests/Client/TimeSeries/Policies/TimeSeriesConfigurationTests.cs
Labels: v5.2

#13913 RavenDB-18212 Sharding - Indexes List View - side by side
  src/Raven.Studio/typescript/commands/database/index/openFaultyIndexCommand.ts
  src/Raven.Studio/typescript/components/models/indexes.d.ts
  src/Raven.Studio/typescript/components/pages/database/indexes/IndexPanel.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/IndexesPage.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/IndexesStatsReducer.ts
  src/Raven.Studio/typescript/components/services/IndexesService.ts
  src/Raven.Studio/typescript/models/database/tasks/ongoingTaskReplicationHubDefinitionListModel.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexesOLD.ts
  src/Raven.Studio/wwwroot/App/views/database/indexes/indexesOLD.html
Labels: Sharding

#13915 RavenDB-18381 - fix replication for existing segments with removed stats
  src/Raven.Server/Documents/TimeSeries/TimeSeriesStorage.cs
  test/SlowTests/Data/RavenDB_18381/2022-03-27-12-38-05-8912792.ravendb-snapshot
  test/SlowTests/Server/Documents/TimeSeries/TimeSeriesTombstoneCleaner.cs
  test/SlowTests/SlowTests.csproj
Labels: v5.2

#13898 RavenDB-18059 Adding additional infot the exception message to verify if that's the real problem
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/StorageEnvironment.cs
Labels: v4.2

#13924 RavenDB-18351 Fix Local destination for OLAP connection string
  src/Raven.Studio/typescript/viewmodels/database/settings/connectionStrings.ts
Labels: v5.3

#13923 RavenDB-18221 Sharding - Database Settings View - First implementation
  src/Raven.Studio/typescript/common/shell/menu/items/settings.ts
  src/Raven.Studio/typescript/models/database/settings/databaseSettingsModels.ts
  src/Raven.Studio/typescript/viewmodels/database/settings/databaseSettings.ts
Labels: Sharding

#13925 5.2 to 5.3 merge
  src/Raven.Server/Dashboard/Cluster/ClusterDashboardNotificationType.cs
  src/Raven.Server/Dashboard/Cluster/ClusterDashboardNotifications.cs
  src/Raven.Server/Dashboard/Cluster/Notifications/OngoingTasksNotificationSender.cs
  src/Raven.Server/Dashboard/Cluster/Notifications/OngoingTasksPayload.cs
  src/Raven.Server/Dashboard/DashboardNotificationType.cs
  src/Raven.Server/Dashboard/DatabasesInfoRetriever.cs
  src/Raven.Server/Dashboard/DatabasesOngoingTasksInfo.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesPolicyRunner.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesStorage.cs
  src/Raven.Studio/typescript/viewmodels/resources/addWidgetModal.ts
  src/Raven.Studio/typescript/viewmodels/resources/clusterDashboard.ts
  src/Raven.Studio/typescript/viewmodels/resources/widgets/ongoingTasksWidget.ts
  src/Raven.Studio/wwwroot/App/views/resources/widgets/ongoingTasksWidget.html
  src/Raven.Studio/wwwroot/Content/css/pages/cluster-dashboard.less
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/StorageEnvironment.cs
  test/SlowTests/Client/TimeSeries/BulkInsert/BulkInsert.cs
  test/SlowTests/Client/TimeSeries/Policies/TimeSeriesConfigurationTests.cs
  test/SlowTests/Data/RavenDB_18381/2022-03-27-12-38-05-8912792.ravendb-snapshot
  test/SlowTests/Server/Documents/TimeSeries/TimeSeriesTombstoneCleaner.cs
  test/SlowTests/SlowTests.csproj
  tools/TypingsGenerator/Program.cs
Labels: v5.3

#13927 5.3 to corax merge
  src/Raven.Server/Dashboard/Cluster/ClusterDashboardNotificationType.cs
  src/Raven.Server/Dashboard/Cluster/ClusterDashboardNotifications.cs
  src/Raven.Server/Dashboard/Cluster/Notifications/OngoingTasksNotificationSender.cs
  src/Raven.Server/Dashboard/Cluster/Notifications/OngoingTasksPayload.cs
  src/Raven.Server/Dashboard/DashboardNotificationType.cs
  src/Raven.Server/Dashboard/DatabasesInfoRetriever.cs
  src/Raven.Server/Dashboard/DatabasesOngoingTasksInfo.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesPolicyRunner.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesStorage.cs
  src/Raven.Studio/package-lock.json
  src/Raven.Studio/package.json
  src/Raven.Studio/typescript/viewmodels/database/settings/connectionStrings.ts
  src/Raven.Studio/typescript/viewmodels/resources/addWidgetModal.ts
  src/Raven.Studio/typescript/viewmodels/resources/clusterDashboard.ts
  src/Raven.Studio/typescript/viewmodels/resources/widgets/ongoingTasksWidget.ts
  src/Raven.Studio/wwwroot/App/views/resources/widgets/ongoingTasksWidget.html
  src/Raven.Studio/wwwroot/Content/css/pages/cluster-dashboard.less
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/StorageEnvironment.cs
  test/SlowTests/Client/TimeSeries/BulkInsert/BulkInsert.cs
  test/SlowTests/Client/TimeSeries/Policies/TimeSeriesConfigurationTests.cs
  test/SlowTests/Data/RavenDB_18381/2022-03-27-12-38-05-8912792.ravendb-snapshot
  test/SlowTests/Server/Documents/TimeSeries/TimeSeriesTombstoneCleaner.cs
  test/SlowTests/SlowTests.csproj
  tools/TypingsGenerator/Program.cs
Labels: Corax

#13929 5.3 to sharding merge
  src/Raven.Server/Dashboard/Cluster/ClusterDashboardNotificationType.cs
  src/Raven.Server/Dashboard/Cluster/ClusterDashboardNotifications.cs
  src/Raven.Server/Dashboard/Cluster/Notifications/OngoingTasksNotificationSender.cs
  src/Raven.Server/Dashboard/Cluster/Notifications/OngoingTasksPayload.cs
  src/Raven.Server/Dashboard/DashboardNotificationType.cs
  src/Raven.Server/Dashboard/DatabasesInfoRetriever.cs
  src/Raven.Server/Dashboard/DatabasesOngoingTasksInfo.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesPolicyRunner.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesStorage.cs
  src/Raven.Studio/package-lock.json
  src/Raven.Studio/package.json
  src/Raven.Studio/typescript/viewmodels/database/settings/connectionStrings.ts
  src/Raven.Studio/typescript/viewmodels/resources/addWidgetModal.ts
  src/Raven.Studio/typescript/viewmodels/resources/clusterDashboard.ts
  src/Raven.Studio/typescript/viewmodels/resources/widgets/ongoingTasksWidget.ts
  src/Raven.Studio/wwwroot/App/views/resources/widgets/ongoingTasksWidget.html
  src/Raven.Studio/wwwroot/Content/css/pages/cluster-dashboard.less
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/StorageEnvironment.cs
  test/SlowTests/Client/TimeSeries/BulkInsert/BulkInsert.cs
  test/SlowTests/Client/TimeSeries/Policies/TimeSeriesConfigurationTests.cs
  test/SlowTests/Data/RavenDB_18381/2022-03-27-12-38-05-8912792.ravendb-snapshot
  test/SlowTests/Server/Documents/TimeSeries/TimeSeriesTombstoneCleaner.cs
  test/SlowTests/SlowTests.csproj
  tools/TypingsGenerator/Program.cs
Labels: Sharding

#13934 RavenDB-18212 Sharding - Indexes List View
  src/Raven.Studio/typescript/components/common/UncontrolledTooltip.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/IndexPanel.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/IndexesPage.tsx
  src/Raven.Studio/typescript/components/utils/IndexUtils.ts
  src/Raven.Studio/typescript/models/database/index/indexOLD.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexesOLD.ts
Labels: Sharding

#13950 RavenDB-7070 all WaitForCompletion methods should have timeout in tests
  test/BenchmarkTests/Indexing/Index.cs
  test/EmbeddedTests/SmugglerTests.cs
  test/FastTests/Issues/RavenDB-13499.cs
  test/FastTests/Issues/RavenDB_13906.cs
  test/FastTests/Server/Documents/DocCompression.cs
  test/RachisTests/DatabaseCluster/AtomicClusterReadWriteTests.cs
  test/SlowTests/Client/Attachments/AttachmentsSmuggler.cs
  test/SlowTests/Client/Counters/CountersReplication.cs
  test/SlowTests/Client/Counters/PatchOnCounters.cs
  test/SlowTests/Graph/AdvancedGraphQueries.cs
  test/SlowTests/Issues/FilteredReplicationTests.cs
  test/SlowTests/Issues/RDBC-128.cs
  test/SlowTests/Issues/RavenDB-11196.cs
  test/SlowTests/Issues/RavenDB-11789.cs
  test/SlowTests/Issues/RavenDB-11824.cs
  test/SlowTests/Issues/RavenDB-11837.cs
  test/SlowTests/Issues/RavenDB-11893.cs
  test/SlowTests/Issues/RavenDB-13444.cs
  test/SlowTests/Issues/RavenDB-13491.cs
  test/SlowTests/Issues/RavenDB-14783.cs
  test/SlowTests/Issues/RavenDB-15294.cs
  test/SlowTests/Issues/RavenDB-16614.cs
  test/SlowTests/Issues/RavenDB-3987.cs
  test/SlowTests/Issues/RavenDB-9959.cs
  test/SlowTests/Issues/RavenDB_10600.cs
  test/SlowTests/Issues/RavenDB_11032.cs
  test/SlowTests/Issues/RavenDB_11985.cs
  test/SlowTests/Issues/RavenDB_17200.cs
  test/SlowTests/Issues/RavenDB_7028.cs
  test/SlowTests/Issues/RavenDB_8603.cs
  test/SlowTests/Issues/RavenDB_8892.cs
  test/SlowTests/Issues/RavenDB_9519.cs
  test/SlowTests/Server/Basic/CollectionTests.cs
  test/SlowTests/Server/Documents/CompressAllCollectionsTest.cs
  test/SlowTests/Server/Documents/ETL/Olap/BackupTests.cs
  test/SlowTests/Server/Documents/ETL/RavenDB_13218.cs
  test/SlowTests/Server/Documents/Indexing/MapReduce/OutputReduceToCollectionReplicationTests.cs
  test/SlowTests/Server/Documents/Migration/MongoDBMigrationTest.cs
  test/SlowTests/Server/Documents/PeriodicBackup/RavenDB_12012.cs
  test/SlowTests/Server/RecordingTransactionOperationsMergerTests.cs
  test/SlowTests/Server/Replication/ReplicationRevisionsTests.cs
  test/SlowTests/Server/TransactionMergerTests.cs
  test/SlowTests/Smuggler/SmugglerApiTests.cs
  test/StressTests/Client/TimeSeries/TimeSeriesStress.cs
  test/StressTests/Issues/RavenDB_14464.cs
  test/StressTests/Server/Replication/ExternalReplicationStressTests.cs
Labels: v5.2

#13919 RavenDB-16365 - creating better error message when using Properties inside Struct
  src/Raven.Client/Extensions/MemberInfoExtensions.cs
  test/SlowTests/Client/TimeSeries/Issues/RavenDB_16365.cs
Labels: v5.2

#13932 RavenDB-18396 switched Client API to use HTTP2 by default
  src/Raven.Client/Documents/Conventions/DocumentConventions.cs
Labels: Sharding

#13963 RavenDB-18217 Sharding - Indexing Performance View - fix view height
  src/Raven.Studio/wwwroot/Content/css/pages/sharding.less
Labels: Sharding
