Repository ravendb/ravendb, pull requests merged in 2022-08, with the labels that each got.

#14656 RavenDB-19034 fix Infinite leader/follower negotiation
  src/Raven.Server/Rachis/Follower.cs
  test/RachisTests/ElectionTests.cs
  test/Tests.Infrastructure/RachisConsensusTestBase.cs
  test/Tryouts/Program.cs
Labels: v5.2

#14660 RavenDB-7070 make selfsigned cert bash script easier to use
  scripts/certificates/bash/generate-selfsigned-cert.sh
Labels: v5.2

#14664 RavenDB-19002 / RavenDB-19046 / RavenDB-17287 If a database load has…
  src/Raven.Server/Documents/ResourceCache.cs
  test/SlowTests/Issues/RavenDB_19002.cs
Labels: v5.2

#14667 5.2 to 5.3 merge
  scripts/certificates/bash/generate-selfsigned-cert.sh
  src/Raven.Server/Documents/ResourceCache.cs
  src/Raven.Server/Rachis/Follower.cs
  test/RachisTests/ElectionTests.cs
  test/SlowTests/Issues/RavenDB_19002.cs
  test/SlowTests/Server/Documents/ETL/Olap/FailoverTests.cs
  test/SlowTests/Server/Documents/ETL/Olap/LocalTests.cs
  test/SlowTests/Server/Documents/ETL/Olap/S3Tests.cs
  test/Tests.Infrastructure/RachisConsensusTestBase.cs
  test/Tryouts/Program.cs
Labels: v5.3

#14666 RavenDB-12603 Query Index with a Given Term - Missing escape character
  src/Raven.Studio/typescript/common/queryUtil.ts
Labels: v5.2

#14665 RavenDB-13633 Active Tabs in Properties Pane upon New Document
  src/Raven.Studio/typescript/viewmodels/database/documents/editDocument.ts
Labels: v5.2

#14668 5.3 to 5.4 merge
  scripts/certificates/bash/generate-selfsigned-cert.sh
  src/Raven.Server/Documents/ResourceCache.cs
  src/Raven.Server/Rachis/Follower.cs
  test/RachisTests/ElectionTests.cs
  test/SlowTests/Issues/RavenDB_19002.cs
  test/SlowTests/Server/Documents/ETL/Olap/FailoverTests.cs
  test/SlowTests/Server/Documents/ETL/Olap/LocalTests.cs
  test/SlowTests/Server/Documents/ETL/Olap/S3Tests.cs
  test/Tests.Infrastructure/RachisConsensusTestBase.cs
  test/Tryouts/Program.cs
Labels: v5.4

#14673 RavenDB-19045 : fix flaky test Can_Set_Pin_To_Node_Pull_Replication_As_Sink
  test/SlowTests/Server/Documents/OngoingTasks/PinOnGoingTaskToMentorNode.cs
  test/SlowTests/Server/Documents/OngoingTasks/PinOnGoingTaskToMentorNodeServerWide.cs
Labels: v5.2

#14674 RavenDB-19077 - Add the index version to the index stats
  src/Raven.Server/Documents/Handlers/IndexHandler.cs
  src/Raven.Server/Json/BlittableJsonTextWriterExtensions.cs
Labels: v5.2

#14669 RavenDB-18798 - Subscription noop ack might remove a resend item
  src/Raven.Server/Documents/Subscriptions/SubscriptionConnectionBase.cs
  src/Raven.Server/Documents/Subscriptions/SubscriptionConnectionsState.cs
  src/Raven.Server/Documents/Subscriptions/SubscriptionConnectionsStateForShard.cs
  src/Raven.Server/ServerWide/Commands/Subscriptions/AcknowledgeSubscriptionBatchCommand.cs
  test/SlowTests/Client/Subscriptions/ConcurrentSubscriptionsTests.cs
Labels: v6.0

#14676 5.3 to 5.4 merge
  src/Raven.Server/Config/Categories/PerformanceHintsConfiguration.cs
  src/Raven.Server/Documents/Handlers/IndexHandler.cs
  src/Raven.Server/Documents/Indexes/MapReduce/Static/MapReduceIndex.cs
  src/Raven.Server/Documents/Indexes/Static/IndexCompiler.cs
  src/Raven.Server/Documents/Indexes/Static/MapIndex.cs
  src/Raven.Server/Documents/Indexes/Static/Roslyn/Rewriters/StackDepthRetriever.cs
  src/Raven.Server/Documents/Indexes/Static/StaticIndexBase.cs
  src/Raven.Server/Json/BlittableJsonTextWriterExtensions.cs
  src/Raven.Studio/typescript/viewmodels/database/documents/editDocument.ts
  test/SlowTests/Issues/RavenDB_18938.cs
  test/SlowTests/Server/Documents/OngoingTasks/PinOnGoingTaskToMentorNode.cs
  test/SlowTests/Server/Documents/OngoingTasks/PinOnGoingTaskToMentorNodeServerWide.cs
Labels: v5.4

#14680 RavenDB-9024 Show number of conflicts per document
  src/Raven.Server/Documents/Handlers/ReplicationHandler.cs
  src/Raven.Studio/typescript/viewmodels/database/conflicts/conflicts.ts
  src/Raven.Studio/typings/_studio/dto.d.ts
  src/Raven.Studio/wwwroot/App/views/database/conflicts/conflicts.html
  src/Raven.Studio/wwwroot/Content/css/pages/conflicts.less
Labels: v5.4

#14687 RavenDB-18704 Remove misleading XML comments
  src/Raven.Client/Documents/Session/IDocumentSession.cs
Labels: v5.2

#14688 RavenDB-18537 Sharding - Ongoing Tasks List View
  src/Raven.Studio/typescript/commands/database/index/getIndexesProgressCommand.ts
  src/Raven.Studio/typescript/commands/database/tasks/getOngoingTasksCommand.ts
  src/Raven.Studio/typescript/components/common/PopoverWithHover.tsx
  src/Raven.Studio/typescript/components/models/indexes.d.ts
  src/Raven.Studio/typescript/components/models/tasks.d.ts
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexDistribution.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexProgressTooltip.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexesPage.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexesStatsReducer.ts
  src/Raven.Studio/typescript/components/pages/database/tasks/list/OngoingEtlTaskProgressTooltip.tsx
  src/Raven.Studio/typescript/components/pages/database/tasks/list/OngoingTasksPage.tsx
  src/Raven.Studio/typescript/components/pages/database/tasks/list/OngoingTasksReducer.ts
  src/Raven.Studio/typescript/components/pages/database/tasks/list/ongoingTasksOLD.ts
  src/Raven.Studio/typescript/components/pages/database/tasks/list/panels/ElasticSearchEtlPanel.tsx
  src/Raven.Studio/typescript/components/pages/database/tasks/list/panels/ExternalReplicationPanel.tsx
  src/Raven.Studio/typescript/components/pages/database/tasks/list/panels/KafkaEtlPanel.tsx
  src/Raven.Studio/typescript/components/pages/database/tasks/list/panels/OlapEtlPanel.tsx
  src/Raven.Studio/typescript/components/pages/database/tasks/list/panels/OngoingEtlTaskDistribution.tsx
  src/Raven.Studio/typescript/components/pages/database/tasks/list/panels/PeriodicBackupPanel.tsx
  src/Raven.Studio/typescript/components/pages/database/tasks/list/panels/RabbitMqEtlPanel.tsx
  src/Raven.Studio/typescript/components/pages/database/tasks/list/panels/RavenEtlPanel.tsx
  src/Raven.Studio/typescript/components/pages/database/tasks/list/panels/ReplicationHubConnectedSinkPanel.tsx
  src/Raven.Studio/typescript/components/pages/database/tasks/list/panels/ReplicationHubDefinitionPanel.tsx
  src/Raven.Studio/typescript/components/pages/database/tasks/list/panels/ReplicationSinkPanel.tsx
  src/Raven.Studio/typescript/components/pages/database/tasks/list/panels/SqlEtlPanel.tsx
  src/Raven.Studio/typescript/components/pages/database/tasks/list/panels/SubscriptionPanel.tsx
  src/Raven.Studio/typescript/components/pages/database/tasks/list/panels/SubscriptionTaskDistribution.tsx
  src/Raven.Studio/typescript/components/pages/database/tasks/list/shared.tsx
Labels: v6.0

#14682 RavenDB-7070 Adding messages to Debug.Assert so we'll know exacly which one has failed if that reproduces again (it happens occasionally on macos in debug)
  src/Sparrow/Json/ArenaMemoryAllocator.cs
Labels: v5.2

#14681 RavenDB-7070 remove spaces from filenames
  src/Raven.Client/Documents/Commands/StreamCommand.cs
  src/Raven.Server/Documents/Includes/IncludeDocumentsDuringTimeSeriesLoadingCommand.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.6/ServerUnmanagedMemory.cs
Labels: v5.2

#14678 RavenDB-13053 add ticket number to the todos
  src/Raven.Server/Documents/Handlers/Batches/AbstractBatchCommandReader.cs
  src/Raven.Server/Documents/Indexes/MapReduce/Static/Sharding/ShardedAggregatedAnonymousObjects.cs
  src/Raven.Server/Documents/Sharding/Executors/AllNodesExecutor.cs
  src/Raven.Server/Documents/Sharding/Executors/ShardExecutor.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Collections/ShardedCollectionsHandlerProcessorForGetCollectionDocuments.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Documents/ShardedDocumentHandlerProcessorForGet.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/OngoingTasks/ShardedOngoingTasksHandlerProcessorForDeleteOngoingTask.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/OngoingTasks/ShardedOngoingTasksHandlerProcessorForDeleteSubscriptionTasks.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/OngoingTasks/ShardedOngoingTasksHandlerProcessorForGetOngoingTasksInfo.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Queries/ShardedQueriesHandlerProcessorForGet.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Replication/ShardedOngoingTasksHandlerProcessorForUpdateExternalReplication.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Replication/ShardedPullReplicationHandlerProcessorForUpdatePullReplicationOnSinkNode.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Revisions/ShardedRevisionsHandlerProcessorForGetRevisions.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Revisions/ShardedRevisionsHandlerProcessorForGetRevisionsBin.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Studio/ShardedStudioCollectionFieldsHandlerProcessorForGetCollectionFields.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Subscriptions/ShardedSubscriptionsHandlerProcessorForDropSubscriptionConnection.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Subscriptions/ShardedSubscriptionsHandlerProcessorForGetConnectionDetails.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Subscriptions/ShardedSubscriptionsHandlerProcessorForGetResend.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/TimeSeries/ShardedTimeSeriesHandlerProcessorForGetTimeSeries.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/TimeSeries/ShardedTimeSeriesHandlerProcessorForGetTimeSeriesRanges.cs
  src/Raven.Server/Documents/Sharding/Operations/FetchDocumentsFromShardsOperation.cs
  src/Raven.Server/Documents/Sharding/Operations/GetShardedOperationStateOperation.cs
  src/Raven.Server/Documents/Sharding/Queries/ShardedMapReduceQueryResultsMerger.cs
  src/Raven.Server/Documents/Sharding/Queries/ShardedQueryProcessor.cs
  src/Raven.Server/Documents/Sharding/ShardedDatabaseContext.Indexes.cs
  src/Raven.Server/Documents/Sharding/ShardedDatabaseContext.Streaming.cs
  src/Raven.Server/Documents/Sharding/ShardedDatabaseContext.Subscriptions.cs
  src/Raven.Server/Documents/Sharding/ShardedDatabaseContext.cs
  src/Raven.Server/Documents/Sharding/Subscriptions/OrchestratedSubscriptionConnection.cs
  src/Raven.Server/Documents/Sharding/Subscriptions/SubscriptionConnectionsStateOrchestrator.cs
  src/Raven.Server/Documents/Subscriptions/SubscriptionConnectionBase.cs
  src/Raven.Server/Documents/TcpHandlers/SubscriptionConnectionForShard.cs
  src/Raven.Server/Web/Studio/Sharding/Processors/ShardedStudioCollectionsHandlerProcessorForPreviewCollection.cs
Labels: v6.0

#14692 RavenDB-7070 Obsolete Spatial4n.Core cleanup in test
  test/SlowTests/Issues/RavenDB-18936.cs
Labels: v5.4

#14698 RavenDB-19105 Add original InvalidJournalException as inner exception…
  src/Raven.Server/Storage/Layout/StorageLoader.cs
  src/Voron/Exceptions/InvalidJournalException.cs
Labels: v5.2

#14694 RavenDB-17952 - SlowTests.Client.TimeSeries.Issues.RavenDB_16366.CanU…
  test/SlowTests/Client/TimeSeries/Issues/RavenDB-16366.cs
Labels: v5.2

#14684 RavenDB-18996 Invalid GetChangeVectorFor and GetMetadataFor code summary
  src/Raven.Client/Documents/Session/IAdvancedDocumentSessionOperations.cs
  src/Raven.Client/Documents/Session/InMemoryDocumentSessionOperations.cs
Labels: v5.2

#14672 RavenDB-13373 Add 'exact' for queries on Auto Index Terms
  src/Raven.Studio/typescript/common/queryUtil.ts
Labels: v5.2

#14671 RavenDB-17391 Redesign preview icon, add preview-off icon
  src/Raven.Studio/wwwroot/App/views/database/settings/integrations.html
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon/preview-off.svg
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon/preview.svg
  src/Raven.Studio/wwwroot/Content/css/styles-common.less
Labels: v5.3, v5.4

#14707 RavenDB-18699 Provide visual information about dealing with single sh…
  src/Raven.Studio/typescript/common/appUrl.ts
  src/Raven.Studio/typescript/viewmodels/shell.ts
  src/Raven.Studio/wwwroot/App/views/shell.html
Labels: v6.0

#14710 RavenDB-16741 Cluster dashboard - add Server & OS info
  src/Raven.Server/Dashboard/Cluster/Notifications/ClusterOverviewNotificationSender.cs
  src/Raven.Server/Dashboard/Cluster/Notifications/ClusterOverviewPayload.cs
  src/Raven.Studio/typescript/viewmodels/resources/widgets/clusterOverviewWidget.ts
Labels: v5.3

#14702 RavenDB-17981 Making Highlighting tests more accurate. Removes duplicated tests.
  test/SlowTests/Tests/Querying/DynamicIndexesWithCollections.cs
  test/SlowTests/Tests/Querying/UsingDynamicQueryWithLocalServer.cs
  test/SlowTests/Tests/Querying/UsingDynamicQueryWithRemoteServer.cs
Labels: v5.3

#14689 RavenDB-18849: Reimplementation of Boosting
  src/Corax/Queries/AndNotMatch.cs
  src/Corax/Queries/BinaryMatch.Boolean.cs
  src/Corax/Queries/MultiTermBoostingMatch.cs
  src/Corax/Queries/SortingMatch/SortingMatch.cs
  src/Corax/Utils/Sorting.cs
  test/FastTests/Corax/BoostingQuery.cs
  test/FastTests/Corax/IndexSearcher.cs
Labels: v5.4

#14716 RavenDB-18872: Fixing and issue with an optimization.
  src/Corax/IndexEntry/IndexEntryReader.cs
Labels: v5.4

#14715 5.2 to 5.3 merge
  src/Raven.Client/Documents/Commands/StreamCommand.cs
  src/Raven.Client/Documents/Indexes/IndexDefinition.cs
  src/Raven.Client/Documents/Session/IAdvancedDocumentSessionOperations.cs
  src/Raven.Client/Documents/Session/IDocumentSession.cs
  src/Raven.Client/Documents/Session/InMemoryDocumentSessionOperations.cs
  src/Raven.Server/Documents/Includes/IncludeDocumentsDuringTimeSeriesLoadingCommand.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.6/ServerUnmanagedMemory.cs
  src/Raven.Server/Storage/Layout/StorageLoader.cs
  src/Raven.Studio/typescript/common/queryUtil.ts
  src/Sparrow/Json/ArenaMemoryAllocator.cs
  src/Voron/Exceptions/InvalidJournalException.cs
  test/SlowTests/Client/TimeSeries/Issues/RavenDB-16366.cs
  test/SlowTests/Issues/RavenDB-17597.cs
Labels: v5.3

#14721 RavenDB-19129 Assertion message improvements. If ResetArena() was cal…
  src/Sparrow/Json/ArenaMemoryAllocator.cs
Labels: v5.2

#14719 RavenDB-18991 - Fix QueriesShouldFailoverIfIndexIsCompactingCluster …
  src/Raven.Client/ServerWide/Operations/CompactDatabaseOperation.cs
  test/SlowTests/Issues/RavenDB-18554.cs
Labels: v5.2

#14713 RavenDB-18701 - System.IO.IOException should be treated as out of dis…
  src/Raven.Server/Indexing/TempFileCache.cs
  src/Raven.Server/Indexing/VoronIndexOutput.cs
  src/Raven.Server/Utils/ExceptionHelper.cs
  src/Voron/Platform/Win32/Win32NativeFileMethods.cs
Labels: v5.2

#14728 RavenDB-18726 - Sharding - Streaming - Handlers - Address PR comments
  src/Raven.Server/Documents/Handlers/StreamCsvResultWriter.cs
  src/Raven.Server/Documents/Sharding/Queries/ShardedQueryProcessor.cs
Labels: v6.0

#14729 5.4 to 6.0 merge
  bench/Voron.Benchmark/Corax/AndOrBenchmark.cs
  bench/Voron.Benchmark/Corax/InBenchmark.cs
  bench/Voron.Benchmark/Corax/OrderByBenchmark.cs
  bench/Voron.Benchmark/Corax/StartWithBenchmark.cs
  src/Corax/IndexEntry/IndexEntryReader.cs
  src/Corax/IndexEntry/IndexEntryTableEncoding.cs
  src/Corax/IndexEntry/IndexEntryWriter.cs
  src/Corax/IndexWriter.cs
  src/Corax/Queries/AndNotMatch.cs
  src/Corax/Queries/BinaryMatch.Boolean.cs
  src/Corax/Queries/MultiTermBoostingMatch.cs
  src/Corax/Queries/SortingMatch/SortingMatch.cs
  src/Corax/Utils/Sorting.cs
  src/Raven.Server/Documents/Indexes/Persistence/Corax/AnonymousCoraxDocumentConverter.cs
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxDocumentConverter.cs
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxDocumentConverterBase.cs
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxIndexWriteOperation.cs
  src/Raven.Server/Documents/Indexes/Persistence/Corax/JintCoraxDocumentConverter.cs
  src/Sparrow.Server/Binary/BitReader.cs
  src/Sparrow.Server/Collections/Persistent/BinaryTree.cs
  src/Sparrow.Server/Compression/Encoder3Gram.cs
  src/Sparrow/Binary/Bits.cs
  src/Sparrow/Binary/PtrBitVector.cs
  src/Sparrow/Utils/ZstdLib.cs
  src/Voron/Data/CompactTrees/CompactTree.Debug.cs
  src/Voron/Data/CompactTrees/CompactTree.cs
  src/Voron/Data/Containers/Container.cs
  src/Voron/Data/Fixed/FixedSizeTree.cs
  src/Voron/Data/Tables/Table.cs
  src/Voron/Impl/LowLevelTransaction.cs
  test/FastTests/Corax/BoostingQuery.cs
  test/FastTests/Corax/Bugs/CompactTreeAddAndRemove.cs
  test/FastTests/Corax/Bugs/CompactTreeOptimizedLookup.cs
  test/FastTests/Corax/Bugs/Terms.log.gz
  test/FastTests/Corax/Bugs/repro-2.log.gz
  test/FastTests/Corax/CoraxQueries.cs
  test/FastTests/Corax/DeleteTest.cs
  test/FastTests/Corax/IndexEntryWriter.cs
  test/FastTests/Corax/IndexSearcher.cs
  test/FastTests/Corax/OrderByMultiSorting.cs
  test/FastTests/Corax/OrderBySorting.cs
  test/FastTests/Corax/RawCoraxFlag.cs
  test/FastTests/Corax/SpatialTests.cs
  test/FastTests/Corax/Suggestions.cs
  test/FastTests/FastTests.csproj
  test/FastTests/Sparrow/Bits.cs
  test/Tryouts/Program.cs
Labels: v6.0

#14695 RavenDB-18998 - support for sharded skip and take
  src/Raven.Server/Documents/Sharding/Queries/ShardedQueryProcessor.cs
  test/FastTests/Sharding/Queries/BasicShardedQueryTests.cs
Labels: v6.0

#14725 RavenDB-18260 Sharding - Queries - TimeLimitedQueryToken. Passing cancelation token from CreateTimeLimitedQueryToken() to query requests sent from orchestrator to shards.
  src/Raven.Client/Documents/Commands/QueryCommand.cs
  src/Raven.Client/Documents/Queries/HashCalculator.cs
  src/Raven.Server/Documents/Handlers/Processors/Queries/AbstractQueriesHandlerProcessorForGet.cs
  src/Raven.Server/Documents/Handlers/Processors/Queries/DatabaseQueriesHandlerProcessorForGet.cs
  src/Raven.Server/Documents/Sharding/Commands/ShardedQueryCommand.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Queries/ShardedQueriesHandlerProcessorForGet.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Smuggler/ShardedSmugglerHandlerProcessorForExport.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Streaming/ShardedStreamingHandlerProcessorForGetStreamQuery.cs
  src/Raven.Server/Documents/Sharding/Queries/ShardedQueryProcessor.cs
  src/Raven.Server/Documents/Sharding/Queries/ShardedQueryStreamProcessor.cs
  src/Raven.Server/Documents/Sharding/ShardedDatabaseContext.cs
Labels: v6.0

#14712 RavenDB-18674 - Fix duplicate declared function name printing to log.
  src/Raven.Server/Documents/Queries/AST/JavascriptCodeQueryVisitor.cs
  src/Raven.Server/Documents/Queries/AST/QueryVisitor.cs
  src/Raven.Server/Documents/Queries/AST/StringQueryVisitor.cs
  test/SlowTests/Issues/RavenDB-18674.cs
Labels: v5.2

#14685 RavenDB-18523 - Fix not abling to include counters, and time series w…
  src/Raven.Server/Documents/Includes/IncludeRevisionsCommand.cs
  src/Raven.Server/Documents/Queries/QueryMetadata.cs
  test/SlowTests/Tests/Linq/CanQueryAndIncludeRevisions.cs
Labels: v5.2

#14732 RavenDB-19109 Add manual ways to disable indexes & databases
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Indexes/Index.cs
Labels: v5.4

#14747 RavenDB-17996 Avoid marking document as dirty if only read operations or no-op operations are performed on metadata in session API
  src/Raven.Client/Json/MetadataAsDictionary.cs
  test/SlowTests/Issues/RavenDB-17996.cs
Labels: v5.2

#14753 RavenDB-18427 Unexpected behavior for saving same entity with different id
  src/Raven.Client/Documents/Session/InMemoryDocumentSessionOperations.cs
  test/SlowTests/Issues/RavenDB-18427.cs
Labels: v5.4

#14758 RavenDB-15091 - RachisTests.DatabaseCluster.ClusterDatabaseMaintenance.ChangeUrlOfMultiNodeCluster
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
Labels: v5.2

#14711 RavenDB-18137 : OLAP GoogleCloudTests fail-on-running-twice
  test/SlowTests/Server/Documents/ETL/Olap/GoogleCloudTests.cs
Labels: v5.2

#14768 RavenDB-19173 Fixing tests that failed during nightly builds only
  test/SlowTests/Authentication/AuthenticationBasicTests.cs
Labels: v5.2

#14733 RavenDB-19144 Disable the Document ID input when 'Test' is in progress
  src/Raven.Studio/wwwroot/App/views/database/patch/patch.html
Labels: v5.2

#14769 5.2 to 5.3 merge
  src/Raven.Client/Properties/AssemblyInfo.Linux.cs
  src/Raven.Client/Properties/AssemblyInfo.Windows.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/IndexReadOperation.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/LuceneIndexPersistence.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreBackupTaskBase.cs
  src/Raven.Studio/wwwroot/App/views/database/patch/patch.html
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
  test/SlowTests/Authentication/AuthenticationBasicTests.cs
  test/SlowTests/Issues/RavenDB-16595.cs
  test/SlowTests/Server/Documents/ETL/Olap/GoogleCloudTests.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Restore/RestoreFromAzure.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Restore/RestoreFromGoogleCloud.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Restore/RestoreFromS3.cs
  test/Tests.Infrastructure/RavenTestBase.Backup.cs
  tools/Raven.Debug/CommandLineApp.cs
  tools/Raven.Debug/LogTrafficWatch/TrafficWatchReplay.cs
Labels: v5.3

#14770 5.3 to 5.4 merge
  src/Raven.Client/Properties/AssemblyInfo.Linux.cs
  src/Raven.Client/Properties/AssemblyInfo.Windows.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxIndexPersistence.cs
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxIndexReadOperation.cs
  src/Raven.Server/Documents/Indexes/Persistence/IndexPersistenceBase.cs
  src/Raven.Server/Documents/Indexes/Persistence/IndexReadOperationBase.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/LuceneIndexPersistence.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/LuceneIndexReadOperation.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreBackupTaskBase.cs
  src/Raven.Studio/wwwroot/App/views/database/patch/patch.html
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
  test/SlowTests/Authentication/AuthenticationBasicTests.cs
  test/SlowTests/Cluster/ClusterTransactionTests.cs
  test/SlowTests/Issues/RavenDB-16595.cs
  test/SlowTests/Server/Documents/ETL/Olap/GoogleCloudTests.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Restore/RestoreFromAzure.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Restore/RestoreFromGoogleCloud.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Restore/RestoreFromS3.cs
  test/Tests.Infrastructure/RavenTestBase.Backup.cs
  tools/Raven.Debug/CommandLineApp.cs
  tools/Raven.Debug/LogTrafficWatch/TrafficWatchReplay.cs
Labels: v5.4

#14771 RavenDB-18990 Prevent from returning null page from GetFirst10AllocatedPages(). It's a method used for debug purposes only.
  src/Voron/Impl/Scratch/ScratchBufferFile.cs
Labels: v5.2

#14772 RavenDB-18992 Adding more details to the assertion message
  test/SlowTests/Issues/RavenDB_15930.cs
Labels: v5.2

#14759 RavenDB-19109 Disable.marker test.
  test/SlowTests/Issues/RavenDB-19109.cs
Labels: v5.2

#14775 RavenDB-19144 Refactored: 1. throttle => debouce 2. Added spinner
  src/Raven.Studio/typescript/viewmodels/database/patch/patchTester.ts
  src/Raven.Studio/wwwroot/App/views/database/patch/patch.html
Labels: v5.2

#14776 RavenDB-19196 Setup Wizard: Provide default IP Address in Unsecure flow
  src/Raven.Studio/typescript/viewmodels/wizard/unsecured.ts
Labels: v5.2

#14778 RavenDB-19141 Fixing race condition in tests. We should rely on the n…
  src/Voron/StorageEnvironmentOptions.cs
  test/SlowTests/Voron/Issues/RavenDB_10225_Voron.cs
  test/SlowTests/Voron/Issues/RavenDB_7097.cs
Labels: v5.2

#14779 RavenDB-18829 Making sure that we are not still deleting before addin…
  test/SlowTests/Issues/RavenDB-17311.cs
Labels: v5.2

#14780 RavenDB-19145: Add CancellationToken to GetDocumentsStartingWith method
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Queries/CollectionQueryEnumerable.cs
Labels: v5.2

#14793 RavenDB-19076 Filter returns same amount as query against index.
  test/SlowTests/Issues/RavenDB-19076.cs
Labels: v5.3, v5.4

#14800 RavenDB-17684 Revisions View: Add yellow star to indicate there are c…
  src/Raven.Studio/typescript/models/database/documents/revisionsConfigurationEntry.ts
  src/Raven.Studio/typescript/viewmodels/database/settings/revisions.ts
  src/Raven.Studio/wwwroot/App/views/database/settings/revisions.html
Labels: v5.2

#14795 RavenDB-19211 When calculating CPU let's force the metric to wait until the task refreshing the value is done. This prevents strange CPU spikes returned by SNMP.
  src/Raven.Server/ServerWide/ServerMetricCacher.cs
  src/Raven.Server/Utils/MetricCacher.cs
Labels: v5.4

#14804 RavenDB-18689 fixing filtering by stale index
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexesPage.tsx
Labels: v6.0

#14799 RavenDB-19244 Revisions Settings view: Fix Merge bug
  src/Raven.Studio/typescript/models/database/documents/revisionsConfigurationEntry.ts
Labels: v5.2

#14798 RavenDB-18915 - open the file with the correct file share flag
  test/SlowTests/SparrowTests/LoggingSourceTests.cs
Labels: v5.2

#14797 RavenDB-18523 - Unable to include counters, time series when including revisions
  src/Raven.Server/Documents/Includes/IncludeRevisionsCommand.cs
  test/SlowTests/Tests/Linq/CanQueryAndIncludeRevisions.cs
Labels: v5.2

#14811 RavenDB-19166 when exporting querying results as csv ignoreLimit is n…
  src/Raven.Studio/typescript/commands/database/query/queryCommand.ts
  src/Raven.Studio/typescript/viewmodels/database/query/query.ts
Labels: v5.2

#14810 RavenDB-18581 Stacks in exported file are reversed
  src/Raven.Studio/typescript/viewmodels/manage/captureStackTraces.ts
Labels: v5.2

#14806 RavenDB-19249 Sharding - admin js console - db list
  src/Raven.Studio/typescript/viewmodels/manage/adminJsConsole.ts
Labels: v6.0

#14805 RavenDB-18276 Sharding - Stats View - ability to render view from eac…
  src/Raven.Studio/typescript/components/pages/database/status/statistics/IndexesDatabaseStats.tsx
Labels: v6.0

#14821 Revert "RavenDB-19211 When calculating CPU let's force the metric to wait until the task refreshing the value is done. This prevents strange CPU spikes returned by SNMP."
  src/Raven.Server/ServerWide/ServerMetricCacher.cs
  src/Raven.Server/Utils/MetricCacher.cs
Labels: v5.4

#14833 Revert "Revert "RavenDB-19211 When calculating CPU let's force the metric to wait until the task refreshing the value is done. This prevents strange CPU spikes returned by SNMP.""
  src/Raven.Server/ServerWide/ServerMetricCacher.cs
  src/Raven.Server/Utils/MetricCacher.cs
Labels: v5.4
