Repository ravendb/ravendb, pull requests merged in 2022-06, with the labels that each got.

#14313 5.2 to 5.3 merge
  src/Raven.Client/Documents/Session/Operations/StreamOperation.cs
  src/Raven.Client/ServerWide/Operations/DatabasesInfo.cs
  src/Raven.Server/Config/Categories/MonitoringConfiguration.cs
  src/Raven.Server/Dashboard/DatabasesInfoRetriever.cs
  src/Raven.Server/Dashboard/DrivesUsage.cs
  src/Raven.Server/Documents/DatabaseMetricCacher.cs
  src/Raven.Server/Documents/Handlers/BatchHandler.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/LuceneIndexWriter.cs
  src/Raven.Server/Documents/PeriodicBackup/BackupHelper.cs
  src/Raven.Server/Indexing/VoronIndexOutput.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.2.X/2/DatabaseStorageDiskIosReadOperations.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.2.X/2/DatabaseStorageDiskIosWriteOperations.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.2.X/2/DatabaseStorageDiskQueueLength.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.2.X/2/DatabaseStorageDiskReadThroughput.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.2.X/2/DatabaseStorageDiskRemainingSpace.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.2.X/2/DatabaseStorageDiskWriteThroughput.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.10/ServerStorageDiskIosReadOperations.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.10/ServerStorageDiskIosWriteOperations.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.10/ServerStorageDiskQueueLength.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.10/ServerStorageDiskReadThroughput.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.10/ServerStorageDiskRemainingSpace.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.10/ServerStorageDiskRemainingSpacePercentage.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.10/ServerStorageDiskWriteThroughput.cs
  src/Raven.Server/Monitoring/Snmp/SnmpDatabase.cs
  src/Raven.Server/Monitoring/Snmp/SnmpOids.cs
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
  src/Raven.Server/RavenServer.cs
  src/Raven.Server/ServerWide/ServerMetricCacher.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Storage/StorageSpaceMonitor.cs
  src/Raven.Server/Utils/Monitoring/DatabaseMetrics.cs
  src/Raven.Server/Utils/Monitoring/ServerMetrics.cs
  src/Raven.Server/Web/Studio/DataDirectoryInfo.cs
  src/Raven.Server/Web/System/AdminMonitoringHandler.cs
  src/Sparrow.Server/Platform/Posix/Syscall.cs
  src/Sparrow.Server/Platform/Posix/sysinfo_t.cs
  src/Sparrow.Server/Utils/DiskStatsGetter.cs
  src/Sparrow.Server/Utils/DiskUtils.cs
  src/Voron/Impl/Paging/RvnMemoryMapPager.cs
  src/Voron/Platform/Posix/PosixHelper.cs
  src/Voron/Platform/Win32/Win32NativeFileMethods.cs
  src/Voron/StorageEnvironmentOptions.cs
  src/Voron/Util/EndOfDiskSpaceEvent.cs
  test/SlowTests/Client/Attachments/AttachmentsReplication.cs
  test/SlowTests/Issues/RavenDB-15497.cs
  test/SlowTests/Issues/RavenDB-18659.cs
  test/SlowTests/Issues/RavenDB-18688.cs
  test/SlowTests/Monitoring/DiskStatsGetterTest.cs
  tools/rvn/CommandLineApp.cs
  tools/rvn/InitSetupParams.cs
Labels: v5.3

#14329 RavenDB-18710 Keep Edit CmpXchg view open when editing & saving
  src/Raven.Studio/typescript/viewmodels/database/cmpXchg/editCmpXchg.ts
Labels: v5.3

#14322 RavenDB-18709: Improved the logic for YieldOr
  src/Corax/Queries/BinaryMatch.Boolean.cs
  src/Corax/Queries/TermMatch.cs
  test/FastTests/Corax/BoostingQuery.cs
Labels: v5.4

#14336 5.3 to 5.4 merge
  src/Raven.Client/ServerWide/Operations/DatabasesInfo.cs
  src/Raven.Studio/typescript/viewmodels/database/cmpXchg/editCmpXchg.ts
Labels: v5.4

#14328 RavenDB-18720 Increase buffer size for the number converter.
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxDocumentConverterBase.cs
Labels: v5.4

#14337 RavenDB-18651 Warnings fix
  test/SlowTests/Corax/CanUseCoraxOnlyAsExperimental.cs
Labels: v5.4

#14326 HRINT-2750 fix windows docker tags once and for all
  docker/build-nanoserver.ps1
  docker/common.ps1
  docker/publish-nanoserver.ps1
Labels: v5.4

#14333 RavenDB-18445 - Sharding - Ongoing Tasks - Get
  src/Raven.Server/Documents/Sharding/Handlers/Processors/OngoingTasks/ShardedOngoingTasksHandlerProcessorForGetOngoingTaskInfo.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/OngoingTasks/ShardedOngoingTasksHandlerProcessorForGetOngoingTasks.cs
Labels: v6.0

#14338 5.4 to 6.0 merge
  docker/build-nanoserver.ps1
  docker/common.ps1
  docker/publish-nanoserver.ps1
  src/Corax/Queries/BinaryMatch.Boolean.cs
  src/Corax/Queries/TermMatch.cs
  src/Raven.Client/ServerWide/Operations/DatabasesInfo.cs
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxDocumentConverterBase.cs
  src/Raven.Studio/typescript/viewmodels/database/cmpXchg/editCmpXchg.ts
  test/FastTests/Corax/BoostingQuery.cs
  test/SlowTests/Corax/CanUseCoraxOnlyAsExperimental.cs
Labels: v6.0

#14319 RavenDB-18676 - add a log only in case of low memory
  src/Sparrow/LowMemory/LowMemoryNotification.cs
Labels: v5.2

#14345 RavenDB-18725 Bump replication protocol to ensure replication to older versions
  src/Raven.Client/ServerWide/Tcp/TcpConnectionHeader.cs
  src/Raven.Server/Documents/Replication/ReplicationDocumentSender.cs
Labels: v5.3

#14344 RavenDB-17828 Initial name for cloned index
  src/Raven.Studio/typescript/viewmodels/database/indexes/editIndex.ts
Labels: v5.4

#14352 RavenDB-18729 implemented /databases/*/etl/progress endpoint
  src/Raven.Server/Documents/Commands/ETL/GetEtlTaskProgressCommand.cs
  src/Raven.Server/Documents/ETL/Handlers/EtlHandler.cs
  src/Raven.Server/Documents/ETL/Handlers/Processors/AbstractEtlHandlerProcessorForProgress.cs
  src/Raven.Server/Documents/ETL/Handlers/Processors/EtlHandlerProcessorForProgress.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/ETL/ShardedEtlHandlerProcessorForProgress.cs
  src/Raven.Server/Documents/Sharding/Handlers/ShardedEtlHandler.cs
  src/Raven.Server/Json/JsonDeserializationServer.cs
Labels: v6.0

#14354 RavenDB-18650 set search engine for index
  src/Raven.Server/Web/Studio/StudioDatabaseTasksHandler.cs
  src/Raven.Studio/typescript/models/database/index/configurationItem.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/editIndex.ts
  src/Raven.Studio/wwwroot/App/views/database/indexes/editIndex.html
  src/Raven.Studio/wwwroot/App/views/wizard/welcome.html
Labels: v5.4

#14340 RavenDB-18697 Fix loading screen logo size
  src/Raven.Studio/wwwroot/Content/css/styles-common.less
  src/Raven.Studio/wwwroot/Content/img/ravendb_logo_white.svg
  src/Raven.Studio/wwwroot/index.html
Labels: v5.3

#14355 RavenDB-18728 - Sharding - Move operation endpoint processors to use `AddRemoteOperation`
  src/Raven.Client/Documents/Operations/Revisions/RevertResult.cs
  src/Raven.Server/Documents/Handlers/Admin/Processors/Revisions/AbstractAdminRevisionsHandlerProcessorForEnforceRevisionsConfiguration.cs
  src/Raven.Server/Documents/Handlers/Admin/Processors/Revisions/AdminRevisionsHandlerProcessorForEnforceRevisionsConfiguration.cs
  src/Raven.Server/Documents/Sharding/Handlers/Admin/Processors/Revisions/ShardedAdminRevisionsHandlerProcessorForEnforceRevisionsConfiguration.cs
  test/FastTests/Server/Documents/Revisions/RevisionsTests.cs
Labels: v6.0

#14358 RavenDB-18759 undefined should be handled same way as implicit null
  src/Raven.Server/Documents/Indexes/Static/JavaScript/DynamicJsNull.cs
  src/Raven.Server/Documents/Indexes/Static/JavaScript/RecursiveJsFunction.cs
  src/Raven.Server/Utils/TypeConverter.cs
  test/SlowTests/Issues/RavenDB_18759.cs
Labels: v5.3

#14367 RavenDB-7070 avoid mixing async with sync
  test/SlowTests/Server/Documents/PeriodicBackup/Aws.cs
  test/SlowTests/Tests/Linq/CanQueryAndIncludeRevisions.cs
Labels: v5.2

#14363 RavenDB-18756 implemented /databases/*/multi_get endpoint
  src/Raven.Server/Documents/Handlers/MultiGetHandler.cs
  src/Raven.Server/Documents/Handlers/Processors/MultiGet/AbstractMultiGetHandlerProcessorForPost.cs
  src/Raven.Server/Documents/Handlers/Processors/MultiGet/MultiGetHandlerProcessorForPost.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/MultiGet/ShardedMultiGetHandlerProcessorForPost.cs
  src/Raven.Server/Documents/Sharding/Handlers/ShardedMultiGetHandler.cs
  src/Raven.Server/Routing/RequestRouter.cs
  src/Raven.Server/Routing/RouteInformation.cs
  test/SlowTests/Client/Lazy/Async/lazyAsync.cs
Labels: v6.0

#14359 RavenDB-16409 - Client.TimeSeries.BulkInsert.CanAppendALotOfValuesAnd…
  test/SlowTests/Client/TimeSeries/BulkInsert/BulkInsert.cs
Labels: v5.2

#14383 5.3 to 5.4 merge
  .github/workflows/FastTests.yml
  bench/BulkInsert.Benchmark/BulkInsert.Benchmark.csproj
  bench/Indexing.Benchmark/Indexing.Benchmark.csproj
  bench/Micro.Benchmark/Micro.Benchmark.csproj
  bench/Regression.Benchmark/Regression.Benchmark.csproj
  bench/SubscriptionFailover.Benchmark/SubscriptionFailover.Benchmark.csproj
  bench/Subscriptions.Benchmark/Subscriptions.Benchmark.csproj
  bench/TimeSeries.Benchmark/TimeSeries.Benchmark.csproj
  bench/Voron.Benchmark/Voron.Benchmark.csproj
  src/Corax/Corax.csproj
  src/Raven.Client/Raven.Client.csproj
  src/Raven.Embedded/ServerOptions.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Studio/Raven.Studio.csproj
  src/Sparrow.Server/Sparrow.Server.csproj
  src/Sparrow/Sparrow.csproj
  src/Voron/Voron.csproj
  test/BenchmarkTests/BenchmarkTests.csproj
  test/EmbeddedTests/EmbeddedTests.csproj
  test/FastTests/FastTests.csproj
  test/InterversionTests/InterversionTests.csproj
  test/LicenseTests/LicenseTests.csproj
  test/RachisTests/RachisTests.csproj
  test/SlowTests/SlowTests.csproj
  test/StressTests/StressTests.csproj
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
  test/Tryouts/Tryouts.csproj
  tools/Raven.Debug/Raven.Debug.csproj
  tools/Raven.Migrator/Raven.Migrator.csproj
  tools/TypingsGenerator/TypingsGenerator.csproj
  tools/Voron.Recovery/Voron.Recovery.csproj
  tools/rvn/rvn.csproj
Labels: v5.4

#14384 5.4 to 6.0 merge
  .github/workflows/FastTests.yml
  bench/BulkInsert.Benchmark/BulkInsert.Benchmark.csproj
  bench/Indexing.Benchmark/Indexing.Benchmark.csproj
  bench/Micro.Benchmark/Micro.Benchmark.csproj
  bench/Regression.Benchmark/Regression.Benchmark.csproj
  bench/SubscriptionFailover.Benchmark/SubscriptionFailover.Benchmark.csproj
  bench/Subscriptions.Benchmark/Subscriptions.Benchmark.csproj
  bench/TimeSeries.Benchmark/TimeSeries.Benchmark.csproj
  bench/Voron.Benchmark/Voron.Benchmark.csproj
  src/Corax/Corax.csproj
  src/Raven.Client/Raven.Client.csproj
  src/Raven.Embedded/ServerOptions.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Studio/Raven.Studio.csproj
  src/Sparrow.Server/Sparrow.Server.csproj
  src/Sparrow/Sparrow.csproj
  src/Voron/Voron.csproj
  test/BenchmarkTests/BenchmarkTests.csproj
  test/EmbeddedTests/EmbeddedTests.csproj
  test/FastTests/FastTests.csproj
  test/InterversionTests/InterversionTests.csproj
  test/LicenseTests/LicenseTests.csproj
  test/RachisTests/RachisTests.csproj
  test/SlowTests/SlowTests.csproj
  test/StressTests/StressTests.csproj
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
  test/Tryouts/Tryouts.csproj
  tools/Raven.Debug/Raven.Debug.csproj
  tools/Raven.Migrator/Raven.Migrator.csproj
  tools/TypingsGenerator/TypingsGenerator.csproj
  tools/Voron.Recovery/Voron.Recovery.csproj
  tools/rvn/rvn.csproj
Labels: v6.0

#14385 RavenDB-18748 Change background color for ETL Test Results
  src/Raven.Studio/wwwroot/Content/css/pages/etl.less
Labels: v5.3

#14398 RavenDB-18273 Sharding - Integrations View - padding issues
  src/Raven.Studio/wwwroot/App/views/database/settings/integrations.html
Labels: v6.0

#14397 RavenDB-18266 Sharding - Custom Sorters View
  src/Raven.Studio/typescript/viewmodels/database/settings/customSorters.ts
  src/Raven.Studio/wwwroot/App/views/database/settings/customSorters.html
Labels: v6.0

#14396 RavenDB-18479 Sharding - Revert Revisions View
  src/Raven.Studio/typescript/common/shell/menu/items/settings.ts
  src/Raven.Studio/typescript/viewmodels/database/settings/revertRevisions.ts
Labels: v6.0

#14395 RavenDB-18291 Sharding - Patch View
  src/Raven.Studio/typescript/common/shell/menu/items/documents.ts
  src/Raven.Studio/typescript/viewmodels/common/validationHelpers.ts
  src/Raven.Studio/typescript/viewmodels/database/patch/docsIdsBasedOnQueryFetcher.ts
  src/Raven.Studio/typescript/viewmodels/database/patch/patch.ts
  src/Raven.Studio/typescript/viewmodels/database/patch/patchTester.ts
Labels: v6.0

#14393 RavenDB-18794: add debug info
  test/SlowTests/Client/Subscriptions/RavenDB_9512.cs
Labels: v5.3

#14389 RavenDB-13106 fix dropping replication migration handlers
  src/Raven.Server/Documents/Replication/BucketMigrationReplication.cs
  src/Raven.Server/Documents/Replication/Incoming/IncomingMigrationReplicationHandler.cs
  src/Raven.Server/Documents/Replication/Incoming/IncomingReplicationHandler.cs
  src/Raven.Server/Documents/Replication/Outgoing/OutgoingMigrationReplicationHandler.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/Documents/Replication/Senders/MigrationReplicationDocumentSender.cs
  src/Raven.Server/ServerWide/Commands/Sharding/SourceMigrationCleanupCommand.cs
  src/Raven.Server/ServerWide/Commands/Sharding/StartBucketMigrationCommand.cs
  test/SlowTests/Sharding/Cluster/ReshardingTests.cs
  test/SlowTests/Sharding/Cluster/SubscriptionsWithReshardingTests.cs
  test/Tests.Infrastructure/RavenTestBase.Sharding.cs
  test/Tests.Infrastructure/RavenTestBase.cs
Labels: v6.0

#14403 RavenDB-18613 - Remove ClusterWideTransaction_WhenRestoreFromIncrementalBackupAfterStoreAndDelete_ShouldDeleteInTheDestination test log if we cant reproduce the bug in 2 weeks
  test/RachisTests/DatabaseCluster/AtomicClusterReadWriteTests.cs
Labels: v5.2

#14408 RavenDB-18819 add libzstd to the NuGet package for osx-arm64
  src/Raven.Client/Raven.Client.csproj
Labels: v5.3

#14411 HRINT-2716 New symbol to run test in alphabetic order
  test/Tests.Infrastructure/CommonTestsAssemblyInfo.cs
Labels: v5.2

#14414 RavenDB-18586 Handle empty options in test script results
  src/Raven.Studio/wwwroot/App/views/database/tasks/editKafkaEtlTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editRabbitMqEtlTask.html
Labels: v5.4

#14417 RavenDB-18724 Display the license id on the License Expired view
  src/Raven.Studio/wwwroot/App/views/shell/registration.html
Labels: v5.2

#14409 RavenDB-18737 Indexing Performance - Corax colors
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexPerformance.ts
  src/Raven.Studio/wwwroot/App/views/database/indexes/indexPerformance.html
  src/Raven.Studio/wwwroot/Content/css/pages/index-performance.less
Labels: v5.4

#14420 5.2 to 5.3 merge
  src/Raven.Client/Exceptions/ExceptionDispatcher.cs
  src/Raven.Client/Exceptions/RavenTimeoutException.cs
  src/Raven.Client/Http/RequestExecutor.cs
  src/Raven.Client/Raven.Client.csproj
  src/Raven.Server/Documents/Handlers/BatchHandler.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Server/RavenServerStartup.cs
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexErrorDetails.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexErrors.ts
  src/Raven.Studio/typescript/viewmodels/database/patch/patch.ts
  src/Raven.Studio/typings/_studio/dto.d.ts
  src/Raven.Studio/wwwroot/App/views/database/indexes/indexErrorDetails.html
  src/Raven.Studio/wwwroot/App/views/database/patch/patch.html
  src/Raven.Studio/wwwroot/App/views/shell/registration.html
  src/Raven.Studio/wwwroot/Content/css/pages/etl.less
  test/RachisTests/DatabaseCluster/AtomicClusterReadWriteTests.cs
  test/SlowTests/Issues/RavenDB-15497.cs
  test/SlowTests/Issues/RavenDB-18688.cs
  test/SlowTests/Issues/RavenDB_9723.cs
  test/Tests.Infrastructure/CommonTestsAssemblyInfo.cs
Labels: v5.3

#14421 RavenDB-18806: Raw values should not be indexed as they can contain null terminated strings
  src/Corax/IndexWriter.cs
  src/Voron/Data/CompactTrees/CompactTree.cs
Labels: v5.4

#14428 RavenDB-18664 - fixing NRE that resulted in a faulted WaitForTopologyUpdate task
  src/Raven.Client/Http/DatabaseTopologyLocalCache.cs
  test/SlowTests/Issues/RavenDB-18664.cs
Labels: v5.3

#14425 RavenDB-18683 limit the number of notifications that we show at first
  src/Raven.Studio/typescript/common/notifications/notificationCenter.ts
  src/Raven.Studio/wwwroot/App/views/notifications/notificationCenter.html
Labels: v5.3

#14392 RavenDB-14436: make sure to use the _reasonableTimeout for backup in …
  test/Tests.Infrastructure/RavenTestBase.Backup.cs
Labels: v5.2

#14434 RavenDB-18831: Keys encoding will fail-fast when passing null symbols as non terminators.
  src/Sparrow.Server/Compression/Encoder3Gram.cs
  test/FastTests/Corax/RawCoraxFlag.cs
Labels: v5.4

#14435 RavenDB-18824 Fixing the argument passed to throw method
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxDocumentConverterBase.cs
Labels: v5.4

#14430 RavenDB-18834 Prevent stack overflow on complicated nested json
  src/Sparrow/Json/AbstractBlittableJsonTextWriter.cs
Labels: v5.2

#14441 RavenDB-18281 implemented WS /databases/*/debug/io-metrics/live
  src/Raven.Server/Documents/Handlers/IoMetricsHandler.cs
  src/Raven.Server/Documents/Handlers/Processors/IoMetrics/AbstractIoMetricsHandlerProcessorForLive.cs
  src/Raven.Server/Documents/Handlers/Processors/IoMetrics/IoMetricsHandlerProcessorForLive.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/IoMetrics/ShardedIoMetricsHandlerProcessorForLive.cs
  src/Raven.Server/Documents/Sharding/Handlers/ShardedIoMetricsHandler.cs
Labels: v6.0

#14443 RavenDB-18812 stabilizing test
  test/SlowTests/Issues/RavenDB-15497.cs
Labels: v5.2

#14452 5.3 to 5.4 merge
  src/Raven.Client/Http/DatabaseTopologyLocalCache.cs
  src/Raven.Server/Integrations/PostgreSQL/HardcodedQuery.cs
  src/Raven.Server/Integrations/PostgreSQL/Messages/Bind.cs
  src/Raven.Server/Integrations/PostgreSQL/Messages/Close.cs
  src/Raven.Server/Integrations/PostgreSQL/Messages/Describe.cs
  src/Raven.Server/Integrations/PostgreSQL/Messages/Parse.cs
  src/Raven.Server/Integrations/PostgreSQL/Messages/Query.cs
  src/Raven.Server/Integrations/PostgreSQL/Npgsql/NpgsqlConfig.cs
  src/Raven.Server/Integrations/PostgreSQL/Npgsql/current_setting_query.csv
  src/Raven.Server/Integrations/PostgreSQL/Npgsql/version_current_setting_query.csv
  src/Raven.Server/Integrations/PostgreSQL/PgQuery.cs
  src/Raven.Server/Integrations/PostgreSQL/PgSession.cs
  src/Raven.Server/Integrations/PostgreSQL/PgTransaction.cs
  src/Raven.Server/Integrations/PostgreSQL/RqlQuery.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Studio/typescript/common/notifications/notificationCenter.ts
  src/Raven.Studio/wwwroot/App/views/notifications/notificationCenter.html
  src/Sparrow/Json/AbstractBlittableJsonTextWriter.cs
  test/SlowTests/Issues/RavenDB-15497.cs
  test/SlowTests/Issues/RavenDB-18664.cs
  test/SlowTests/Server/Integrations/PostgreSQL/RavenDB_18716.cs
  test/Tests.Infrastructure/RavenTestBase.Backup.cs
Labels: v5.4

#14458 RavenDB-18851 Avoid throwing an exception when recording transaction, especially on `catch` & `finally`
  src/Raven.Server/Documents/TransactionOperationsMerger.cs
Labels: v4.2

#14462 RavenDB-18859 - Infinite loop when having a popular document in LoadDocument
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/Workers/HandleReferences.cs
  src/Raven.Server/Documents/Indexes/Workers/HandleReferencesBase.ReferencesState.cs
  test/SlowTests/Issues/RavenDB-15754.cs
Labels: v5.3

#14412 RavenDB-17473 Using Mono.Posix to call stat system call
  src/Sparrow.Server/Sparrow.Server.csproj
  src/Sparrow.Server/Utils/DiskStatsGetter.cs
  src/Sparrow.Server/Utils/DiskUtils.cs
Labels: v5.2

#14465 RavenDB-18760 - Failing InterversionTests on 5.3 and 5.4 branches
  test/InterversionTests/SmugglerTests.cs
Labels: v5.3

#14466 4.2 to 5.2 merge
  src/Raven.Server/Documents/TransactionOperationsMerger.cs
  src/Raven.Server/Raven.Server.csproj
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
  tools/Raven.Migrator/Raven.Migrator.csproj
Labels: v5.2

#14467 5.2 to 5.3 merge
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/Workers/HandleReferences.cs
  src/Raven.Server/Documents/Indexes/Workers/HandleReferencesBase.ReferencesState.cs
  src/Raven.Server/Documents/TransactionOperationsMerger.cs
  src/Raven.Server/Raven.Server.csproj
  src/Sparrow.Server/Sparrow.Server.csproj
  src/Sparrow.Server/Utils/DiskStatsGetter.cs
  src/Sparrow.Server/Utils/DiskUtils.cs
  test/SlowTests/Issues/RavenDB-15754.cs
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
  tools/Raven.Migrator/Raven.Migrator.csproj
Labels: v5.3

#14468 5.3 to 5.4 merge
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/Workers/HandleReferences.cs
  src/Raven.Server/Documents/Indexes/Workers/HandleReferencesBase.ReferencesState.cs
  src/Raven.Server/Documents/TransactionOperationsMerger.cs
  src/Raven.Server/Raven.Server.csproj
  src/Sparrow.Server/Sparrow.Server.csproj
  src/Sparrow.Server/Utils/DiskStatsGetter.cs
  src/Sparrow.Server/Utils/DiskUtils.cs
  test/InterversionTests/SmugglerTests.cs
  test/SlowTests/Issues/RavenDB-15754.cs
  test/SlowTests/Issues/RavenDB_8369.cs
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
  test/Tryouts/Program.cs
  tools/Raven.Migrator/Raven.Migrator.csproj
Labels: v5.4

#14459 RavenDB-17310 - Tombstones_should_be_cleaned_only_after_backup_with_s…
  test/SlowTests/Issues/RavenDB_8369.cs
Labels: v4.2
