Repository ravendb/ravendb, pull requests merged in 2022-11, with the labels that each got.

#15197 RavenDB-19495 Use `Backup.TempPath` on one time backup
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
  src/Raven.Server/Utils/BackupUtils.cs
  src/Raven.Server/Web/System/OngoingTasksHandler.cs
Labels: v5.2

#15198 RavenDB-19182 - Sharding - /docs endpoint discrepancy
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Documents/ShardedDocumentHandlerProcessorForGet.cs
Labels: v6.0

#15056 RavenDB-19385 Request timeout not applied for lazy queries
  src/Raven.Server/Documents/Handlers/MultiGetHandler.cs
  src/Sparrow.Server/Compression/Encoder3Gram.cs
  test/SlowTests/Issues/RavenDB-19385.cs
Labels: v5.4

#15103 RavenDB-19057 - Sharding - Replication - Server-Wide
  test/RachisTests/DatabaseCluster/ReplicationTests.cs
  test/SlowTests/Sharding/Replication/ShardedExternalReplicationTests.cs
Labels: v6.0

#15210 5.2 to 5.3 merge
  src/Raven.Client/Documents/Linq/RavenQueryProviderProcessor.cs
  src/Raven.Client/Json/Serialization/JsonDeserializationClient.cs
  src/Raven.Client/ServerWide/Operations/ModifyDatabaseTopologyOperation.cs
  src/Raven.Client/ServerWide/Operations/ModifyDatabaseTopologyResult.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesPolicyRunner.cs
  src/Raven.Server/Utils/BackupUtils.cs
  src/Raven.Server/Web/RequestHandler.cs
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
  src/Raven.Server/Web/System/DatabasesHandler.cs
  src/Raven.Server/Web/System/OngoingTasksHandler.cs
  test/FastTests/Client/RavenCommandTest.cs
  test/SlowTests/Issues/RavenDB-14806.cs
  test/SlowTests/Issues/RavenDB-19100.cs
  test/StressTests/Client/TimeSeries/Policies/TimeSeriesConfigurationTestsStress.cs
Labels: v5.4

#15216 RavenDB-19463 Hide `InsufficientExecutionStackException` when it comes from `parameters.ToString()` inside InvalidQueryException.
  src/Raven.Client/Exceptions/InvalidQueryException.cs
Labels: v5.2

#15214 RavenDB-7070 IndexMerging tests - assert with respecting new line on all platforms
  test/SlowTests/Server/Documents/Indexing/IndexMerging.cs
Labels: v5.4

#15228 RavenDB-17872 - Fixing an NRE when updating the metadata in compare exchange
  src/Raven.Server/ServerWide/Commands/ClusterTransactionCommand.cs
  test/SlowTests/Issues/RavenDB-17872.cs
Labels: v5.2

#15207 Option to specify node tag for initial node
  src/Raven.Server/Documents/Handlers/Admin/RachisAdminHandler.cs
Labels: v5.4

#15232 5.3 to 5.4 merge
  src/Raven.Client/Documents/Session/ClusterTransactionSession.cs
  src/Raven.Client/Exceptions/InvalidQueryException.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/Handlers/BatchHandler.cs
  test/SlowTests/Issues/RavenDB-17872.cs
  test/SlowTests/Issues/RavenDB-18373.cs
  test/StressTests/Issues/RavenDB_13528.cs
  test/StressTests/Voron/Issues/RavenDB_19273.cs
Labels: v5.4

#15233 RavenDB-19521 Query view: Fix the sample syntax
  src/Raven.Studio/typescript/viewmodels/database/query/querySyntax.ts
Labels: v5.4

#15205 RavenDB-18754 - Ensure order of the returned results for `/databases/…
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Documents/ShardedDocumentHandlerProcessorForGet.cs
  src/Raven.Server/Documents/Sharding/ShardedDatabaseContext.Streaming.cs
  test/SlowTests/Issues/IAsyncDocumentSessionExtensionsTest.cs
Labels: v6.0

#15251 RavenDB-7070 remove static from _options in DatabaseDestination
  src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
Labels: v5.2

#15258 RavenDB-19537 Remove word 'Count' from stats page
  src/Raven.Studio/typescript/models/database/tasks/replicationAccessBaseModel.ts
  src/Raven.Studio/wwwroot/App/views/database/status/statistics.html
Labels: v5.4

#15262 5.2 to 5.3 merge
  .github/workflows/FastTests.yml
  .github/workflows/FastTestsARM.yml
  RavenDB.sln
  bench/BulkInsert.Benchmark/BulkInsert.Benchmark.csproj
  bench/Indexing.Benchmark/Indexing.Benchmark.csproj
  bench/Micro.Benchmark/Micro.Benchmark.csproj
  bench/Regression.Benchmark/Regression.Benchmark.csproj
  bench/SubscriptionFailover.Benchmark/SubscriptionFailover.Benchmark.csproj
  bench/Subscriptions.Benchmark/Subscriptions.Benchmark.csproj
  bench/TimeSeries.Benchmark/TimeSeries.Benchmark.csproj
  bench/Voron.Benchmark/Voron.Benchmark.csproj
  src/Raven.Client/Raven.Client.csproj
  src/Raven.Embedded/ServerOptions.cs
  src/Raven.Server/Documents/DocumentPutAction.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
  src/Raven.Studio/Raven.Studio.csproj
  src/Sparrow.Server/Sparrow.Server.csproj
  src/Voron/Voron.csproj
  test/BenchmarkTests/BenchmarkTests.csproj
  test/EmbeddedTests/EmbeddedTests.csproj
  test/FastTests/FastTests.csproj
  test/InterversionTests/InterversionTests.csproj
  test/LicenseTests/LicenseTests.csproj
  test/RachisTests/RachisTests.csproj
  test/SlowTests/SlowTests.csproj
  test/StressTests/StressTests.csproj
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
  test/Tryouts/Tryouts.csproj
  tools/Raven.Debug/Raven.Debug.csproj
  tools/Raven.Migrator/Raven.Migrator.csproj
  tools/TypingsGenerator/TypingsGenerator.csproj
  tools/Voron.Recovery/Voron.Recovery.csproj
  tools/rvn/rvn.csproj
Labels: v5.3

#15264 5.3 to 5.4 merge
  .github/workflows/FastTests.yml
  .github/workflows/FastTestsARM.yml
  RavenDB.sln
  bench/BulkInsert.Benchmark/BulkInsert.Benchmark.csproj
  bench/Indexing.Benchmark/Indexing.Benchmark.csproj
  bench/Micro.Benchmark/Micro.Benchmark.csproj
  bench/Regression.Benchmark/Regression.Benchmark.csproj
  bench/SubscriptionFailover.Benchmark/SubscriptionFailover.Benchmark.csproj
  bench/Subscriptions.Benchmark/Subscriptions.Benchmark.csproj
  bench/TimeSeries.Benchmark/TimeSeries.Benchmark.csproj
  bench/Voron.Benchmark/Voron.Benchmark.csproj
  src/Corax/Corax.csproj
  src/Raven.Client/Raven.Client.csproj
  src/Raven.Embedded/ServerOptions.cs
  src/Raven.Server/Documents/DocumentPutAction.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
  src/Raven.Studio/Raven.Studio.csproj
  src/Sparrow.Server/Sparrow.Server.csproj
  src/Voron/Voron.csproj
  test/BenchmarkTests/BenchmarkTests.csproj
  test/EmbeddedTests/EmbeddedTests.csproj
  test/FastTests/FastTests.csproj
  test/InterversionTests/InterversionTests.csproj
  test/LicenseTests/LicenseTests.csproj
  test/RachisTests/RachisTests.csproj
  test/SlowTests/SlowTests.csproj
  test/StressTests/StressTests.csproj
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
  test/Tryouts/Tryouts.csproj
  tools/Raven.Debug/Raven.Debug.csproj
  tools/Raven.Migrator/Raven.Migrator.csproj
  tools/TypingsGenerator/TypingsGenerator.csproj
  tools/Voron.Dictionary.Generator/Voron.Dictionary.Generator.csproj
  tools/Voron.Recovery/Voron.Recovery.csproj
  tools/rvn/rvn.csproj
Labels: v5.4

#15206 RavenDB-19497 - Throw NotSupportedException on attempt of Incremental Time Series bulk insert
  src/Raven.Client/Documents/BulkInsert/BulkInsertOperation.cs
  test/SlowTests/Client/TimeSeries/BulkInsert/BulkInsert.cs
Labels: v5.4

#15229 RavenDB-19488 Return empty results when skipped more docs than queried index size
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/IndexQueryingScope.cs
  test/SlowTests/Issues/RavenDB-19488.cs
Labels: v5.2

#15266 RavenDB-7070 Convert `actual` too in `AssertEqualRespectingNewLines` and `AssertStartsWithRespectingNewLines`
  test/Tests.Infrastructure/RavenTestHelper.cs
Labels: v5.4

#15268 RavenDB-19535 when RAVEN_IS_RUNNING_ON_CI is set to true we require all connections to work
  test/SlowTests/Issues/RavenDB_16303.cs
  test/SlowTests/Server/Documents/ETL/ConnectionStringTests.cs
  test/SlowTests/Server/Documents/ETL/SQL/SqlEtlTests.cs
  test/SlowTests/Server/Documents/Migration/AttachmentsTest.cs
  test/SlowTests/Server/Documents/Migration/BasicMigrationTests.cs
  test/SlowTests/Server/Documents/Migration/MsSQLSchemaTest.cs
  test/SlowTests/Server/Documents/Migration/PatchTest.cs
  test/SlowTests/Server/Documents/Migration/RecursiveMigrationTest.cs
  test/SlowTests/Server/Documents/Migration/SqlAwareTestBase.cs
  test/SlowTests/Server/Documents/Migration/TestMigrationTest.cs
  test/Tests.Infrastructure/AmazonGlacierFactAttribute.cs
  test/Tests.Infrastructure/AmazonGlacierTheoryAttribute.cs
  test/Tests.Infrastructure/AmazonS3FactAttribute.cs
  test/Tests.Infrastructure/AmazonS3TheoryAttribute.cs
  test/Tests.Infrastructure/AzureFactAttribute.cs
  test/Tests.Infrastructure/AzureSasTokenFactAttribute.cs
  test/Tests.Infrastructure/AzureTheoryAttribute.cs
  test/Tests.Infrastructure/ConnectionString/MongoDBConnectionString.cs
  test/Tests.Infrastructure/ConnectionString/MssqlConnectionString.cs
  test/Tests.Infrastructure/ConnectionString/MySqlConnectionString.cs
  test/Tests.Infrastructure/ConnectionString/OracleConnectionString.cs
  test/Tests.Infrastructure/ConnectionString/SqlConnectionString.cs
  test/Tests.Infrastructure/CustomS3FactAttribute.cs
  test/Tests.Infrastructure/GoogleCloudFactAttribute.cs
  test/Tests.Infrastructure/RequiresMongoDBFactAttribute.cs
  test/Tests.Infrastructure/RequiresMsSqlFactAttribute.cs
  test/Tests.Infrastructure/RequiresMsSqlInlineData.cs
  test/Tests.Infrastructure/RequiresMsSqlRetryFactAttribute.cs
  test/Tests.Infrastructure/RequiresMsSqlRetryTheoryAttribute.cs
  test/Tests.Infrastructure/RequiresMySqlFactAttribute.cs
  test/Tests.Infrastructure/RequiresMySqlInlineData.cs
  test/Tests.Infrastructure/RequiresNpgSqlFactAttribute.cs
  test/Tests.Infrastructure/RequiresNpgSqlInlineData.cs
  test/Tests.Infrastructure/RequiresOracleSqlFactAttribute.cs
  test/Tests.Infrastructure/RequiresOracleSqlInlineData.cs
Labels: v5.2

#15270 5.2 to 5.3 merge
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/IndexQueryingScope.cs
  src/Raven.Server/Documents/PeriodicBackup/Aws/RavenAwsS3Client.cs
  src/Raven.Server/Documents/Replication/IncomingReplicationHandler.cs
  src/Raven.Server/Documents/Replication/OutgoingReplicationHandler.cs
  src/Raven.Server/Documents/Replication/ReplicationDocumentSender.cs
  test/SlowTests/Issues/RavenDB-19488.cs
  test/SlowTests/Issues/RavenDB_16303.cs
  test/SlowTests/Server/Documents/ETL/ConnectionStringTests.cs
  test/SlowTests/Server/Documents/ETL/Elasticsearch/ElasticSearchEtlTests.cs
  test/SlowTests/Server/Documents/ETL/Elasticsearch/RavenDB_17476.cs
  test/SlowTests/Server/Documents/ETL/Elasticsearch/RavenDB_17477.cs
  test/SlowTests/Server/Documents/ETL/SQL/SqlEtlTests.cs
  test/SlowTests/Server/Documents/Migration/AttachmentsTest.cs
  test/SlowTests/Server/Documents/Migration/BasicMigrationTests.cs
  test/SlowTests/Server/Documents/Migration/MsSQLSchemaTest.cs
  test/SlowTests/Server/Documents/Migration/PatchTest.cs
  test/SlowTests/Server/Documents/Migration/RecursiveMigrationTest.cs
  test/SlowTests/Server/Documents/Migration/SqlAwareTestBase.cs
  test/SlowTests/Server/Documents/Migration/TestMigrationTest.cs
  test/SlowTests/Server/Documents/PeriodicBackup/CustomS3.cs
  test/SlowTests/Server/Replication/ReplicationSpecialCases.cs
  test/Tests.Infrastructure/AmazonGlacierFactAttribute.cs
  test/Tests.Infrastructure/AmazonGlacierTheoryAttribute.cs
  test/Tests.Infrastructure/AmazonS3FactAttribute.cs
  test/Tests.Infrastructure/AmazonS3TheoryAttribute.cs
  test/Tests.Infrastructure/AzureFactAttribute.cs
  test/Tests.Infrastructure/AzureSasTokenFactAttribute.cs
  test/Tests.Infrastructure/AzureTheoryAttribute.cs
  test/Tests.Infrastructure/ConnectionString/ElasticSearchTestNodes.cs
  test/Tests.Infrastructure/ConnectionString/MongoDBConnectionString.cs
  test/Tests.Infrastructure/ConnectionString/MssqlConnectionString.cs
  test/Tests.Infrastructure/ConnectionString/MySqlConnectionString.cs
  test/Tests.Infrastructure/ConnectionString/OracleConnectionString.cs
  test/Tests.Infrastructure/ConnectionString/SqlConnectionString.cs
  test/Tests.Infrastructure/CustomS3FactAttribute.cs
  test/Tests.Infrastructure/GoogleCloudFactAttribute.cs
  test/Tests.Infrastructure/RequiresElasticSearchRetryFactAttribute.cs
  test/Tests.Infrastructure/RequiresMongoDBFactAttribute.cs
  test/Tests.Infrastructure/RequiresMsSqlFactAttribute.cs
  test/Tests.Infrastructure/RequiresMsSqlInlineData.cs
  test/Tests.Infrastructure/RequiresMsSqlRetryFactAttribute.cs
  test/Tests.Infrastructure/RequiresMsSqlRetryTheoryAttribute.cs
  test/Tests.Infrastructure/RequiresMySqlFactAttribute.cs
  test/Tests.Infrastructure/RequiresMySqlInlineData.cs
  test/Tests.Infrastructure/RequiresNpgSqlFactAttribute.cs
  test/Tests.Infrastructure/RequiresNpgSqlInlineData.cs
  test/Tests.Infrastructure/RequiresOracleSqlFactAttribute.cs
  test/Tests.Infrastructure/RequiresOracleSqlInlineData.cs
  tools/Raven.Migrator/Raven.Migrator.csproj
Labels: v5.3

#15255 RavenDB-19534: IndexEntryReader no longer uses spans and doesnt need to be a ref struct
  src/Corax/IndexEntry/IndexEntryReader.cs
  src/Corax/IndexSearcher/IndexSearcher.cs
  src/Corax/IndexWriter.cs
  src/Corax/Queries/SortingMatch/SortingMultiMatch.cs
  src/Corax/Utils/IndexEntryFieldIterator.cs
  src/Corax/Utils/SpatialPointFieldIterator.cs
  test/FastTests/Corax/Bugs/IndexEntryReaderBigDoc.cs
  test/FastTests/Corax/Bugs/RavenDB-19283.cs
  test/FastTests/Corax/DynamicFieldsTests.cs
  test/FastTests/Corax/IndexEntryWriter.cs
  test/FastTests/Corax/SpatialTests.cs
Labels: Corax, v5.4

#15280 RavenDB-19547 - Custom S3 URL stopped working after upgrading to the recent Nuget
  src/Raven.Server/Documents/PeriodicBackup/Aws/RavenAwsS3Client.cs
  test/SlowTests/Server/Documents/PeriodicBackup/CustomS3.cs
Labels: v5.2

#15282 RavenDB-19474: Hanging on CompareExchange after Database.Initialize
  src/Raven.Server/Documents/DocumentDatabase.cs
  test/SlowTests/Issues/RavenDB_19474.cs
Labels: v5.2

#15285 5.3 to 5.4 merge
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Handlers/Admin/AdminTombstoneHandler.cs
  src/Raven.Server/Documents/PeriodicBackup/Aws/RavenAwsS3Client.cs
  src/Raven.Server/Documents/TombstoneCleaner.cs
  src/Raven.Server/Raven.Server.csproj
  test/SlowTests/Issues/RavenDB_15240.cs
  test/SlowTests/Server/Documents/PeriodicBackup/CustomS3.cs
Labels: v5.4

#15288 5.3 to 5.4 merge
  src/Raven.Server/Documents/DocumentDatabase.cs
  test/SlowTests/Issues/RavenDB_19474.cs
Labels: v5.4

#15296 RavenDB-19551 Studio v6.0 issues
  src/Raven.Studio/typescript/common/shell/menu/items/indexes.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexCleanup.ts
  src/Raven.Studio/wwwroot/App/views/database/indexes/indexErrors.html
Labels: v6.0

#15295 RavenDB-19555 Reduce JsString allocations
  src/Raven.Server/Documents/Indexes/Static/Counters/CounterEntryObjectInstance.cs
  src/Raven.Server/Documents/Indexes/Static/JavaScript/AttachmentNameObjectInstance.cs
  src/Raven.Server/Documents/Indexes/Static/JavaScript/AttachmentObjectInstance.cs
  src/Raven.Server/Documents/Indexes/Static/JavaScriptMapOperation.cs
  src/Raven.Server/Documents/Indexes/Static/JavaScriptReduceOperation.cs
  src/Raven.Server/Documents/Indexes/Static/TimeSeries/TimeSeriesSegmentObjectInstance.cs
  src/Raven.Server/Documents/Patch/BlittableObjectInstance.cs
  src/Raven.Server/Documents/Patch/JavaScriptUtils.cs
  src/Raven.Server/Documents/Patch/JintNullPropagationReferenceResolver.cs
  src/Raven.Server/Documents/Patch/JsBlittableBridge.cs
  src/Raven.Server/Documents/Patch/ScriptRunnerResult.cs
Labels: v5.4

#15304 RavenDB-19562 Fixing 'Ensure 'ThreadStatic' is only used with static fields' warning in Voron
  src/Voron/Data/BTrees/Tree.cs
Labels: v5.2

#15305 5.2 to 5.3 merge
  src/Raven.Client/Documents/Indexes/ExpressionStringBuilder.cs
  src/Raven.Client/ServerWide/DatabaseRecord.cs
  src/Raven.Server/Documents/PeriodicBackup/BackupHelper.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
  src/Raven.Server/ServerWide/Commands/PeriodicBackup/UpdatePeriodicBackupCommand.cs
  src/Voron/Data/BTrees/Tree.cs
  test/SlowTests/Issues/RavenDB-13553.cs
  test/SlowTests/Issues/RavenDB_18588.cs
Labels: v5.3

#15311 RavenDB-19551 Studio v6.0 issues
  src/Raven.Studio/typescript/components/hooks/useChanges.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/DatabasesPage.tsx
Labels: v6.0

#15315 RavenDB-19566 fixed WebSocket connections after migration to .NET 7
  src/Raven.Client/Util/HttpMethods.cs
  src/Raven.Server/Routing/RequestRouter.cs
Labels: v5.4

#15313 RavenDB-19478 Expose Optimize index option in the Studio
  src/Raven.Studio/typescript/commands/database/index/optimizeIndexCommand.ts
  src/Raven.Studio/typescript/common/notifications/notificationCenter.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/optimizeIndexDetails.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/dumpDialog.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/editIndex.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/optimizeDialog.ts
  src/Raven.Studio/wwwroot/App/views/common/notificationCenter/detailViewer/operations/optimizeIndexDetails.html
  src/Raven.Studio/wwwroot/App/views/database/indexes/dumpDialog.html
  src/Raven.Studio/wwwroot/App/views/database/indexes/editIndex.html
  src/Raven.Studio/wwwroot/App/views/database/indexes/optimizeDialog.html
  tools/TypingsGenerator/Program.cs
Labels: v5.2

#15318 RavenDB-19504_5.2: Fixed ravendb 5.2 crashes on importing dump with timeseries on encrypted
  src/Raven.Server/Documents/Handlers/TimeSeriesHandler.cs
  src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
Labels: v5.2

#15326 RavenDB-19331: Fixed failing tests for M1 processor
  test/FastTests/Sparrow/SmallSet.cs
Labels: v5.4

#15328 5.2 to 5.3 merge
  src/Raven.Client/Constants.cs
  src/Raven.Client/Documents/Indexes/ExpressionStringBuilder.cs
  src/Raven.Client/Documents/Session/ClusterTransactionSession.cs
  src/Raven.Client/Exceptions/CompareExchangeInvalidKeyException.cs
  src/Raven.Server/Documents/Handlers/BatchHandler.cs
  src/Raven.Server/Documents/Handlers/TimeSeriesHandler.cs
  src/Raven.Server/Documents/Indexes/Static/DynamicArray.cs
  src/Raven.Server/Documents/Indexes/Static/Linq/DynamicEnumerable.cs
  src/Raven.Server/Rachis/AppendEntriesResponse.cs
  src/Raven.Server/Rachis/Follower.cs
  src/Raven.Server/Rachis/Remote/RemoteConnection.cs
  src/Raven.Server/ServerWide/Commands/ClusterTransactionCommand.cs
  src/Raven.Server/ServerWide/Commands/CompareExchangeCommands.cs
  src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
  src/Raven.Server/Utils/TypeConverter.cs
  src/Raven.Studio/typescript/commands/database/index/optimizeIndexCommand.ts
  src/Raven.Studio/typescript/common/notifications/notificationCenter.ts
  src/Raven.Studio/typescript/models/database/tasks/tasksCommonContent.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/optimizeIndexDetails.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/dumpDialog.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/editIndex.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/optimizeDialog.ts
  src/Raven.Studio/wwwroot/App/views/common/notificationCenter/detailViewer/operations/optimizeIndexDetails.html
  src/Raven.Studio/wwwroot/App/views/database/indexes/dumpDialog.html
  src/Raven.Studio/wwwroot/App/views/database/indexes/editIndex.html
  src/Raven.Studio/wwwroot/App/views/database/indexes/optimizeDialog.html
  test/FastTests/Client/BulkInserts.cs
  test/SlowTests/Cluster/ClusterTransactionTests.cs
  test/SlowTests/Issues/RavenDB-16614.cs
  test/SlowTests/Issues/RavenDB-17872.cs
  test/SlowTests/Issues/RavenDB_19557.cs
  tools/TypingsGenerator/Program.cs
Labels: v5.3

#15330 5.3 to 5.4 merge
  src/Raven.Client/Constants.cs
  src/Raven.Client/Documents/Indexes/ExpressionStringBuilder.cs
  src/Raven.Client/Documents/Session/ClusterTransactionSession.cs
  src/Raven.Client/Exceptions/CompareExchangeInvalidKeyException.cs
  src/Raven.Server/Documents/Handlers/BatchHandler.cs
  src/Raven.Server/Documents/Indexes/Static/DynamicArray.cs
  src/Raven.Server/Documents/Indexes/Static/Linq/DynamicEnumerable.cs
  src/Raven.Server/Rachis/AppendEntriesResponse.cs
  src/Raven.Server/Rachis/Follower.cs
  src/Raven.Server/Rachis/Remote/RemoteConnection.cs
  src/Raven.Server/ServerWide/Commands/ClusterTransactionCommand.cs
  src/Raven.Server/ServerWide/Commands/CompareExchangeCommands.cs
  src/Raven.Server/Utils/TypeConverter.cs
  src/Raven.Studio/typescript/commands/database/index/optimizeIndexCommand.ts
  src/Raven.Studio/typescript/common/notifications/notificationCenter.ts
  src/Raven.Studio/typescript/models/database/tasks/tasksCommonContent.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/optimizeIndexDetails.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/dumpDialog.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/editIndex.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/optimizeDialog.ts
  src/Raven.Studio/wwwroot/App/views/common/notificationCenter/detailViewer/operations/optimizeIndexDetails.html
  src/Raven.Studio/wwwroot/App/views/database/indexes/dumpDialog.html
  src/Raven.Studio/wwwroot/App/views/database/indexes/editIndex.html
  src/Raven.Studio/wwwroot/App/views/database/indexes/optimizeDialog.html
  test/FastTests/Client/BulkInserts.cs
  test/SlowTests/Cluster/ClusterTransactionTests.cs
  test/SlowTests/Issues/RavenDB-16614.cs
  test/SlowTests/Issues/RavenDB-17872.cs
  test/SlowTests/Issues/RavenDB_19557.cs
  tools/TypingsGenerator/Program.cs
Labels: v5.4

#15331 RavenDB-19478 Expose Optimize index option in the Studio
  src/Raven.Studio/typescript/viewmodels/database/indexes/editIndex.ts
  src/Raven.Studio/wwwroot/App/views/database/indexes/editIndex.html
Labels: v5.4

#15332 RavenDB-19536 Allow to cleanup tombsones from the studio
  src/Raven.Server/Documents/Handlers/Admin/AdminTombstoneHandler.cs
  src/Raven.Studio/typescript/commands/database/debug/forceTombstonesCleanupCommand.ts
  src/Raven.Studio/typescript/commands/database/debug/getTombstonesStateCommand.ts
  src/Raven.Studio/typescript/common/appUrl.ts
  src/Raven.Studio/typescript/common/shell/menu/items/settings.ts
  src/Raven.Studio/typescript/viewmodels/database/advanced/tombstonesState.ts
  src/Raven.Studio/typings/_studio/computedAppUrls.d.ts
  src/Raven.Studio/typings/_studio/dto.d.ts
  src/Raven.Studio/wwwroot/App/views/database/advanced/tombstonesState.html
  tools/TypingsGenerator/Program.cs
Labels: v5.2

#15336 RavenDB-19536 small text fix
  src/Raven.Studio/typescript/commands/database/debug/getTombstonesStateCommand.ts
Labels: v5.2

#15337 RavenDB-19337 fixed issue with passing an array to cmpxchg in JS indexes
  src/Raven.Server/Documents/Indexes/Static/JavaScriptIndex.cs
  test/SlowTests/Issues/RavenDB_13644.cs
Labels: v5.4

#15338 RavenDB-19445 fixing test
  test/FastTests/Issues/RavenDB_16942.cs
Labels: v5.2

#15341 RavenDB-19581 - updated backup regions in the studio
  src/Raven.Studio/typescript/models/database/tasks/periodicBackup/amazonSettings.ts
Labels: v5.2

#15345 RavenDB-19281 Add threshold to start flush and sync when performing replacement of side-by-side index.
  src/Raven.Server/Config/Categories/IndexingConfiguration.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Studio/typescript/models/database/index/configurationItem.ts
  src/Voron/Impl/Journal/JournalFile.cs
  test/FastTests/Issues/RavenDB_16590.cs
Labels: v5.4

#15349 RavenDB-5055 Add `BinaryExpressionSyntax` support in `IndexMerger` | Add additional validation.
  src/Raven.Server/Documents/Indexes/IndexMerging/IndexMerger.cs
  test/SlowTests/Server/Documents/Indexing/IndexMerging.cs
Labels: v5.2

#15357 5.2 to 5.3 merge
  src/Raven.Server/Documents/Handlers/Admin/AdminTombstoneHandler.cs
  src/Raven.Studio/package-lock.json
  src/Raven.Studio/typescript/commands/database/debug/forceTombstonesCleanupCommand.ts
  src/Raven.Studio/typescript/commands/database/debug/getTombstonesStateCommand.ts
  src/Raven.Studio/typescript/common/appUrl.ts
  src/Raven.Studio/typescript/common/shell/menu/items/settings.ts
  src/Raven.Studio/typescript/models/database/tasks/periodicBackup/amazonSettings.ts
  src/Raven.Studio/typescript/viewmodels/database/advanced/tombstonesState.ts
  src/Raven.Studio/typings/_studio/computedAppUrls.d.ts
  src/Raven.Studio/typings/_studio/dto.d.ts
  src/Raven.Studio/wwwroot/App/views/database/advanced/tombstonesState.html
  test/FastTests/Issues/RavenDB_16942.cs
  tools/TypingsGenerator/Program.cs
Labels: v5.3

#15356 RavenDB-19255 mark field as internal
  src/Raven.Client/Documents/Operations/Backups/GetPeriodicBackupStatusOperation.cs
  src/Raven.Studio/typescript/test/stubs/TasksStubs.ts
Labels: v6.0

#15358 5.3 to 5.4 merge
  src/Raven.Server/Documents/Handlers/Admin/AdminTombstoneHandler.cs
  src/Raven.Server/Integrations/PostgreSQL/Messages/MessageBuilder.cs
  src/Raven.Server/Integrations/PostgreSQL/RqlQuery.cs
  src/Raven.Studio/package-lock.json
  src/Raven.Studio/typescript/commands/database/debug/forceTombstonesCleanupCommand.ts
  src/Raven.Studio/typescript/commands/database/debug/getTombstonesStateCommand.ts
  src/Raven.Studio/typescript/common/appUrl.ts
  src/Raven.Studio/typescript/common/shell/menu/items/settings.ts
  src/Raven.Studio/typescript/models/database/tasks/periodicBackup/amazonSettings.ts
  src/Raven.Studio/typescript/viewmodels/database/advanced/tombstonesState.ts
  src/Raven.Studio/typings/_studio/computedAppUrls.d.ts
  src/Raven.Studio/typings/_studio/dto.d.ts
  src/Raven.Studio/wwwroot/App/views/database/advanced/tombstonesState.html
  test/FastTests/Issues/RavenDB_16942.cs
  test/SlowTests/Issues/RavenDB-19583.cs
  tools/TypingsGenerator/Program.cs
Labels: v5.4
