Repository ravendb/ravendb, pull requests merged in 2022-07, with the labels that each got.

#14477 RavenDB-18878 - Failed sharded export tests
  test/SlowTests/Sharding/Backup/ShardedPeriodicBackupTests .cs
  test/SlowTests/Sharding/Backup/ShardedSmugglerTests.cs
Labels: v6.0

#14482 RavenDB-18583 Revisions Settings: Do not mark fields with required er…
  src/Raven.Studio/typescript/viewmodels/database/settings/revisions.ts
  src/Raven.Studio/wwwroot/App/views/database/settings/revisions.html
Labels: v5.3

#14456 RavenDB-18779 Fix Database Group Topology Position
  src/Raven.Studio/wwwroot/App/views/database/tasks/ongoingTasks.html
  src/Raven.Studio/wwwroot/Content/css/pages/ongoing-tasks.less
Labels: v5.4

#14449 RavenDB-18625 New document created under @empty collection
  src/Raven.Studio/typescript/models/database/documents/document.ts
Labels: v5.3

#14453 RavenDB-18825 Error in Unused Database IDs view for a new empty database
  src/Raven.Studio/typescript/viewmodels/database/advanced/databaseIDs.ts
  src/Raven.Studio/wwwroot/App/views/database/advanced/databaseIDs.html
  src/Raven.Studio/wwwroot/App/views/database/status/statistics.html
Labels: v5.3

#14480 RavenDB-18835 update acknowledgements file
  docs/acknowledgements.txt
Labels: v5.3

#14469 RavenDB-18603 - QueriesShouldFailoverIfIndexIsCompacting test fails
  test/SlowTests/Issues/RavenDB-18554.cs
Labels: v5.2

#14494 RavenDB-18887 there is no guarantee of order of the columns when fetching from Oracle
  test/SlowTests/Server/Documents/Migration/OracleSQLSchemaTest.cs
Labels: v5.2

#14498 5.3 to 5.4 merge
  build.ps1
  docs/acknowledgements.txt
  scripts/target.ps1
  scripts/upload.ps1
  src/Raven.Studio/typescript/models/database/documents/document.ts
  src/Raven.Studio/typescript/viewmodels/database/advanced/databaseIDs.ts
  src/Raven.Studio/typescript/viewmodels/database/settings/revisions.ts
  src/Raven.Studio/wwwroot/App/views/database/advanced/databaseIDs.html
  src/Raven.Studio/wwwroot/App/views/database/settings/revisions.html
  src/Raven.Studio/wwwroot/App/views/database/status/statistics.html
  src/Raven.Studio/wwwroot/App/views/manage/certificates.html
  src/Raven.Studio/wwwroot/Content/css/bootstrap/normalize.less
  src/Raven.Studio/wwwroot/Content/css/pages/certificates.less
  test/SlowTests/Issues/RavenDB-18554.cs
  test/SlowTests/Issues/RavenDB_8369.cs
  test/SlowTests/Server/Documents/Migration/OracleSQLSchemaTest.cs
Labels: v5.4

#14504 5.2 to 5.3 merge
  docs/readme.linux.txt
  scripts/linux/install-daemon.sh
  scripts/linux/ravendb.service
  src/Raven.Server/Commercial/LicenseManager.cs
  src/Raven.Server/Commercial/LicenseStatus.cs
  src/Raven.Server/Commercial/LicenseValidator.cs
Labels: v5.3

#14506 5.3 to 5.4 merge
  docs/readme.linux.txt
  scripts/linux/install-daemon.sh
  scripts/linux/ravendb.service
  src/Raven.Server/Commercial/LicenseManager.cs
  src/Raven.Server/Commercial/LicenseStatus.cs
  src/Raven.Server/Commercial/LicenseValidator.cs
Labels: v5.4

#14505 RavenDB-16816 Add tooltips to column headers in some cluster dashboa…
  src/Raven.Studio/typescript/viewmodels/resources/widgets/databaseIndexingWidget.ts
  src/Raven.Studio/typescript/viewmodels/resources/widgets/databaseStorageWidget.ts
  src/Raven.Studio/typescript/viewmodels/resources/widgets/databaseTrafficWidget.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/columns/nodeTagColumn.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/columns/textColumn.ts
  src/Raven.Studio/typings/_studio/dto.d.ts
Labels: v5.2

#14507 RavenDB-18597 Expose flags for deleted revision
  src/Raven.Studio/wwwroot/App/views/database/documents/editDocument.html
Labels: v5.2

#14510 RavenDB-18282 Sharding - Storage Report View
  src/Raven.Server/Documents/Commands/Storage/GetEnvironmentStorageReportCommand.cs
  src/Raven.Server/Documents/Commands/Storage/GetStorageReportCommand.cs
  src/Raven.Studio/typescript/commands/database/debug/getEnvironmentStorageReportCommand.ts
  src/Raven.Studio/typescript/commands/database/debug/getStorageReportCommand.ts
  src/Raven.Studio/typescript/viewmodels/database/status/storageReport.ts
Labels: v6.0

#14509 RavenDB-18695 - add a new license type
  src/Raven.Server/Commercial/LicenseType.cs
Labels: v5.2

#14520 RavenDB-18011 SSL error while using replication with TCP compression
  src/Sparrow/Utils/ZstdStream.cs
Labels: v5.3

#14508 RavenDB-18695 - licensing changes
  src/Raven.Server/Commercial/LicenseManager.cs
  src/Raven.Server/Commercial/LicenseStatus.cs
  src/Raven.Server/Commercial/LicenseValidator.cs
Labels: v5.4

#14532 5.2 to 5.3 merge
  .github/workflows/FastTests.yml
  bench/BulkInsert.Benchmark/BulkInsert.Benchmark.csproj
  bench/Indexing.Benchmark/Indexing.Benchmark.csproj
  bench/Micro.Benchmark/Micro.Benchmark.csproj
  bench/Regression.Benchmark/Regression.Benchmark.csproj
  bench/SubscriptionFailover.Benchmark/SubscriptionFailover.Benchmark.csproj
  bench/Subscriptions.Benchmark/Subscriptions.Benchmark.csproj
  bench/TimeSeries.Benchmark/TimeSeries.Benchmark.csproj
  bench/Voron.Benchmark/Voron.Benchmark.csproj
  src/Raven.Client/Raven.Client.csproj
  src/Raven.Embedded/ServerOptions.cs
  src/Raven.Server/Commercial/LicenseType.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/Commands/DeleteServerWideTaskCommand.cs
  src/Raven.Studio/Raven.Studio.csproj
  src/Raven.Studio/typescript/viewmodels/resources/widgets/databaseIndexingWidget.ts
  src/Raven.Studio/typescript/viewmodels/resources/widgets/databaseStorageWidget.ts
  src/Raven.Studio/typescript/viewmodels/resources/widgets/databaseTrafficWidget.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/columns/nodeTagColumn.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/columns/textColumn.ts
  src/Raven.Studio/typings/_studio/dto.d.ts
  src/Raven.Studio/wwwroot/App/views/database/documents/editDocument.html
  src/Sparrow.Server/Sparrow.Server.csproj
  src/Voron/Voron.csproj
  test/BenchmarkTests/BenchmarkTests.csproj
  test/EmbeddedTests/EmbeddedTests.csproj
  test/FastTests/FastTests.csproj
  test/InterversionTests/InterversionTests.csproj
  test/LicenseTests/LicenseTests.csproj
  test/RachisTests/RachisTests.csproj
  test/SlowTests/Server/Documents/PeriodicBackup/ServerWideBackup.cs
  test/SlowTests/SlowTests.csproj
  test/StressTests/StressTests.csproj
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
  test/Tryouts/Tryouts.csproj
  tools/Raven.Debug/Raven.Debug.csproj
  tools/Raven.Migrator/Raven.Migrator.csproj
  tools/TypingsGenerator/TypingsGenerator.csproj
  tools/Voron.Recovery/Voron.Recovery.csproj
  tools/rvn/rvn.csproj
Labels: v5.3

#14530 RavenDB-18931 Remove graph API related stuff from 6.0 studio
  src/Raven.Client/Constants.cs
  src/Raven.Studio/typescript/commands/database/query/debugGraphOutputCommand.ts
  src/Raven.Studio/typescript/common/query/graphQueryResults.ts
  src/Raven.Studio/typescript/viewmodels/database/query/query.ts
  src/Raven.Studio/typings/_studio/dto.d.ts
  src/Raven.Studio/wwwroot/App/views/database/query/query.html
  src/Raven.Studio/wwwroot/App/views/wizard/welcome.html
  src/Raven.Studio/wwwroot/Content/css/pages/query.less
Labels: v6.0

#14535 5.3 to 5.4 merge
  .github/workflows/FastTests.yml
  bench/BulkInsert.Benchmark/BulkInsert.Benchmark.csproj
  bench/Indexing.Benchmark/Indexing.Benchmark.csproj
  bench/Micro.Benchmark/Micro.Benchmark.csproj
  bench/Regression.Benchmark/Regression.Benchmark.csproj
  bench/SubscriptionFailover.Benchmark/SubscriptionFailover.Benchmark.csproj
  bench/Subscriptions.Benchmark/Subscriptions.Benchmark.csproj
  bench/TimeSeries.Benchmark/TimeSeries.Benchmark.csproj
  bench/Voron.Benchmark/Voron.Benchmark.csproj
  src/Corax/Corax.csproj
  src/Raven.Client/Raven.Client.csproj
  src/Raven.Embedded/ServerOptions.cs
  src/Raven.Server/Commercial/LicenseType.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/Commands/DeleteServerWideTaskCommand.cs
  src/Raven.Studio/Raven.Studio.csproj
  src/Raven.Studio/typescript/viewmodels/resources/widgets/databaseIndexingWidget.ts
  src/Raven.Studio/typescript/viewmodels/resources/widgets/databaseStorageWidget.ts
  src/Raven.Studio/typescript/viewmodels/resources/widgets/databaseTrafficWidget.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/columns/nodeTagColumn.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/columns/textColumn.ts
  src/Raven.Studio/typings/_studio/dto.d.ts
  src/Raven.Studio/wwwroot/App/views/database/documents/editDocument.html
  src/Sparrow.Server/Sparrow.Server.csproj
  src/Sparrow/Utils/ZstdStream.cs
  src/Voron/Voron.csproj
  test/BenchmarkTests/BenchmarkTests.csproj
  test/EmbeddedTests/EmbeddedTests.csproj
  test/FastTests/FastTests.csproj
  test/InterversionTests/InterversionTests.csproj
  test/LicenseTests/LicenseTests.csproj
  test/RachisTests/RachisTests.csproj
  test/SlowTests/Server/Documents/PeriodicBackup/ServerWideBackup.cs
  test/SlowTests/SlowTests.csproj
  test/StressTests/StressTests.csproj
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
  test/Tryouts/Tryouts.csproj
  tools/Raven.Debug/Raven.Debug.csproj
  tools/Raven.Migrator/Raven.Migrator.csproj
  tools/TypingsGenerator/TypingsGenerator.csproj
  tools/Voron.Dictionary.Generator/Voron.Dictionary.Generator.csproj
  tools/Voron.Recovery/Voron.Recovery.csproj
  tools/rvn/rvn.csproj
Labels: v5.4

#14539 RavenDB-18944 [CoraxBooleanQuery-BetweenMatch] Convert long into double when opposite side is double.
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxBooleanQuery.cs
  test/FastTests/Corax/QueriesFromRavenDb.cs
Labels: v5.4

#14540 RavenDB-17010 - cloning only the relevant fields that needs to be cloned
  src/Raven.Server/Smuggler/Documents/SmugglerPatcher.cs
Labels: v5.2

#14538 RavenDB-18862 - allow to take samples of the cpu threads
  src/Raven.Server/Dashboard/ThreadsInfo.cs
  src/Raven.Server/Documents/Handlers/Debugging/ThreadsHandler.cs
  src/Raven.Server/ServerWide/ServerMetricCacher.cs
  src/Raven.Server/Utils/ThreadsUsage.cs
Labels: v5.3

#14529 RavenDB-18537 Sharding - Ongoing Tasks List View - fixes for non-shar…
  src/Raven.Server/Json/BlittableJsonTextWriterExtensions.cs
  src/Raven.Server/Web/System/Processors/OngoingTasks/OngoingTasksHandlerProcessorForGetOngoingTaskInfo.cs
  src/Raven.Server/Web/System/Processors/OngoingTasks/OngoingTasksHandlerProcessorForGetOngoingTasks.cs
  src/Raven.Studio/typescript/common/dbLiveIOStatsWebSocketClient.ts
  src/Raven.Studio/typescript/viewmodels/database/advanced/databaseIDs.ts
Labels: v6.0

#14542 RavenDB-18689 Sharding - indexes view - enhacements
  src/Raven.Studio/typescript/commands/resources/getEssentialDatabaseStatsCommand.ts
  src/Raven.Studio/typescript/components/models/indexes.d.ts
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexDistribution.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexPanel.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexProgressTooltip.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexesPage.spec.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexesPage.stories.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexesPage.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexesStatsReducer.ts
  src/Raven.Studio/typescript/components/utils/IndexUtils.ts
  src/Raven.Studio/typescript/models/database/index/indexProgressOLD.ts
  src/Raven.Studio/typescript/test/fixtures/indexes_stats.json
  src/Raven.Studio/typescript/test/stubs/IndexesStubs.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/forceParallelDeploymentConfirm.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexStalenessReasons.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexesOLD.ts
  src/Raven.Studio/wwwroot/App/views/database/indexes/indexStalenessReasons.html
  src/Raven.Studio/wwwroot/App/views/shell.html
Labels: v6.0

#14512 RavenDB-18908 Support multiple result set in map-reduce visualize
  src/Raven.Server/Documents/Indexes/Debugging/IndexDebugExtensions.cs
Labels: v5.3

#14546 RavenDB-18957 Support for linq queries using a dictionary entity type
  src/Raven.Client/Documents/Linq/LinqPathProvider.cs
  src/Raven.Client/Documents/Linq/RavenQueryProviderProcessor.cs
  test/FastTests/Client/Query.cs
Labels: v5.3

#14548 Raven db 18862 Fix defference between total thread CPU usage to process CPU usage in Linux
  src/Raven.Server/Dashboard/ThreadsInfo.cs
  src/Raven.Server/Utils/ThreadsUsage.cs
Labels: v5.2

#14547 RavenDB-18921 - formatting of messages in the decision log
  src/Raven.Server/ServerWide/Maintenance/ClusterObserver.cs
Labels: v5.2

#14551 5.2 to 5.3 merge
  src/Raven.Client/Documents/Queries/Explanation/Explanations.cs
  src/Raven.Client/Documents/Session/AbstractDocumentQuery.Explanations.cs
  src/Raven.Client/Documents/Session/AbstractDocumentQuery.cs
  src/Raven.Client/Http/NodeSelector.cs
  src/Raven.Server/Dashboard/ThreadsInfo.cs
  src/Raven.Server/Documents/Handlers/Admin/AdminLogsHandler.cs
  src/Raven.Server/Documents/Handlers/Debugging/ThreadsHandler.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/NotificationCenter/OutOfMemoryNotifications.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterObserver.cs
  src/Raven.Server/ServerWide/ServerMetricCacher.cs
  src/Raven.Server/Smuggler/Documents/SmugglerPatcher.cs
  src/Raven.Server/Utils/ThreadsUsage.cs
  src/Raven.Server/Web/RequestHandler.cs
  src/Raven.Studio/typescript/common/bindingHelpers/datePickerBindingHandler.ts
  src/Raven.Studio/typescript/viewmodels/manage/adminLogs.ts
  src/Raven.Studio/wwwroot/App/views/manage/adminLogs.html
  src/Raven.Studio/wwwroot/Content/css/pages/admin-logs.less
  src/Sparrow.Server/LowMemory/MemoryInformation.cs
  src/Sparrow/Logging/LoggingSource.cs
  src/Sparrow/LowMemory/LowMemoryNotification.cs
  src/Sparrow/Utils/MemoryUtils.cs
  src/Sparrow/Utils/NativeMemory.cs
  test/FastTests/Server/Documents/Indexing/Auto/BasicAutoMapIndexing.cs
  test/SlowTests/Issues/RavenDB-17903.cs
  test/SlowTests/Issues/RavenDB-18619.cs
  test/SlowTests/Server/Documents/PeriodicBackup/RavenDB-11139.cs
Labels: v5.3

#14553 RavenDB-18461 Throw NotImplementedExceptionInCorax instead of Voron exception.
  src/Raven.Server/Documents/Indexes/Index.cs
Labels: v5.4

#14559 RavenDB-18276 Sharding - Stats View
  src/Raven.Studio/typescript/commands/database/index/getIndexesStatsCommand.ts
  src/Raven.Studio/typescript/commands/resources/getDatabaseDetailedStatsCommand.ts
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexesPage.stories.tsx
  src/Raven.Studio/typescript/components/pages/database/status/statistics/DetailedDatabaseStats.tsx
  src/Raven.Studio/typescript/components/pages/database/status/statistics/IndexesDatabaseStats.tsx
  src/Raven.Studio/typescript/components/pages/database/status/statistics/StatisticsPage.spec.tsx
  src/Raven.Studio/typescript/components/pages/database/status/statistics/StatisticsPage.stories.tsx
  src/Raven.Studio/typescript/components/pages/database/status/statistics/StatisticsPage.tsx
  src/Raven.Studio/typescript/components/services/IndexesService.ts
  src/Raven.Studio/typescript/models/database/stats/indexStatistics.ts
  src/Raven.Studio/typescript/test/mocks/MockIndexesService.ts
Labels: v6.0

#14554 RavenDB-18689 Sharding - indexes view - enhacements
  src/Raven.Studio/typescript/components/common/RichPanel.tsx
  src/Raven.Studio/typescript/components/hooks/useChanges.tsx
  src/Raven.Studio/typescript/components/hooks/useChangesContext.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexPanel.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexProgressTooltip.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexesPage.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexesStatsReducer.ts
  src/Raven.Studio/typescript/components/pages/resources/databases/DatabasesPage.tsx
  src/Raven.Studio/typescript/components/utils/common.ts
  src/Raven.Studio/typescript/test/mocks/MockChangesContext.ts
  src/Raven.Studio/typescript/test/storybookTestUtils.tsx
Labels: v6.0

#14575 RavenDB-18978 disabled preview features for all projects except corax,server, voron and tools
  src/Corax/Corax.csproj
  src/Directory.Build.props
  src/Raven.Server/Raven.Server.csproj
  src/Voron/Voron.csproj
  tools/Directory.Build.props
  tools/TypingsGenerator/TypingsGenerator.csproj
  tools/Voron.Dictionary.Generator/Voron.Dictionary.Generator.csproj
  tools/Voron.Recovery/Voron.Recovery.csproj
  tools/rvn/rvn.csproj
Labels: v5.4

#14577 RavenDB-18929 - QueriesShouldFailoverIfIndexIsCompactingClaster fails
  test/SlowTests/Issues/RavenDB-18554.cs
Labels: v5.2

#14572 RavenDB-18840 Create "ignore-all" configuration for eslint and pretti…
  src/Raven.Studio/.prettierignore
  src/Raven.Studio/.prettierrc.json
Labels: v5.2

#14580 HRINT-2914 Added workflow for arm architecture
  .github/workflows/FastTestsARM.yml
Labels: v5.2

#14579 RavenDB-18983 Fix syntax sample for RabbitMQ
  src/Raven.Studio/wwwroot/App/views/database/tasks/transformationScriptSyntax.html
Labels: v5.4

#14565 RavenDB-15541 Add Hub task details in ongoing task list view
  src/Raven.Studio/typescript/models/database/tasks/ongoingTaskReplicationHubDefinitionListModel.ts
  src/Raven.Studio/wwwroot/App/views/database/tasks/ongoingTasks.html
  src/Raven.Studio/wwwroot/Content/css/styles-common.less
Labels: v5.2

#14566 RavenDB-16643 Raven ETL => RavenDB ETL
  src/Raven.Studio/typescript/viewmodels/database/status/ongoingTasksStats.ts
Labels: v5.2

#14571 RavenDB-18951 - Fix Bulk_Insert_2NodesDown_1NodeRestart/Should_Throw_…
  src/Raven.Client/Documents/Subscriptions/SubscriptionWorker.cs
  src/Raven.Client/Http/NodeSelector.cs
  src/Raven.Client/Http/RequestExecutor.cs
Labels: v5.2

#14556 Raven db 15427 Test fix and collecting info for further test failure invastigation
  test/SlowTests/SparrowTests/LoggingSourceTests.cs
Labels: v5.2

#14582 RavenDB-18981 - Memory leak in the ArenaMemoryAllocator
  src/Sparrow/Json/ArenaMemoryAllocator.cs
  test/FastTests/Blittable/BlittableJsonWriterTests/ArenaMemoryAllocatorTests.cs
  test/FastTests/Blittable/BlittableJsonWriterTests/ManualBuilderTests.cs
Labels: v5.2

#14433 RavenDB-18760 - Failing InterversionTests on 5.3 and 5.4 branches - f…
  src/Raven.Server/Smuggler/Documents/Handlers/SmugglerHandler.cs
Labels: v4.2

#14590 4.2 to 5.2 merge
  src/Raven.Server/Smuggler/Documents/Handlers/SmugglerHandler.cs
Labels: v5.2

#14591 5.2 to 5.3 merge
  .github/workflows/FastTestsARM.yml
  src/Raven.Client/Documents/Subscriptions/SubscriptionWorker.cs
  src/Raven.Client/Http/NodeSelector.cs
  src/Raven.Client/Http/RequestExecutor.cs
  src/Raven.Server/Smuggler/Documents/Handlers/SmugglerHandler.cs
  src/Raven.Studio/.prettierignore
  src/Raven.Studio/.prettierrc.json
  src/Raven.Studio/typescript/common/generalUtils.ts
  src/Raven.Studio/typescript/models/database/tasks/ongoingTaskReplicationHubDefinitionListModel.ts
  src/Raven.Studio/typescript/models/resources/widgets/taskItem.ts
  src/Raven.Studio/typescript/viewmodels/database/status/ongoingTasksStats.ts
  src/Raven.Studio/typescript/viewmodels/resources/widgets/abstractDatabaseAndNodeAwareTableWidget.ts
  src/Raven.Studio/typescript/viewmodels/resources/widgets/ongoingTasksWidget.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/columns/iconsPlusTextColumn.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/columns/multiNodeTagsColumn.ts
  src/Raven.Studio/typings/_studio/dto.d.ts
  src/Raven.Studio/wwwroot/App/views/database/tasks/ongoingTasks.html
  src/Raven.Studio/wwwroot/App/views/resources/widgets/ongoingTasksWidget.html
  src/Raven.Studio/wwwroot/Content/css/pages/cluster-dashboard.less
  src/Raven.Studio/wwwroot/Content/css/styles-common.less
  src/Sparrow/Json/ArenaMemoryAllocator.cs
  test/FastTests/Blittable/BlittableJsonWriterTests/ArenaMemoryAllocatorTests.cs
  test/FastTests/Blittable/BlittableJsonWriterTests/ManualBuilderTests.cs
  test/SlowTests/Issues/RavenDB-18554.cs
  test/SlowTests/SparrowTests/LoggingSourceTests.cs
Labels: v5.3

#14598 5.3 to 5.4 merge
  .github/workflows/FastTestsARM.yml
  src/Raven.Client/Documents/Subscriptions/SubscriptionWorker.cs
  src/Raven.Client/Http/NodeSelector.cs
  src/Raven.Client/Http/RequestExecutor.cs
  src/Raven.Server/Smuggler/Documents/Handlers/SmugglerHandler.cs
  src/Raven.Studio/.prettierignore
  src/Raven.Studio/.prettierrc.json
  src/Raven.Studio/typescript/common/helpers/view/icomoonHelpers.ts
  src/Raven.Studio/typescript/models/database/tasks/ongoingTaskReplicationHubDefinitionListModel.ts
  src/Raven.Studio/typescript/models/resources/widgets/taskItem.ts
  src/Raven.Studio/typescript/viewmodels/database/status/ongoingTasksStats.ts
  src/Raven.Studio/typescript/viewmodels/resources/widgets/abstractDatabaseAndNodeAwareTableWidget.ts
  src/Raven.Studio/typescript/viewmodels/resources/widgets/ongoingTasksWidget.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/columns/iconsPlusTextColumn.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/columns/multiNodeTagsColumn.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/virtualGrid.ts
  src/Raven.Studio/typings/_studio/dto.d.ts
  src/Raven.Studio/webpack.config.js
  src/Raven.Studio/wwwroot/App/views/database/tasks/ongoingTasks.html
  src/Raven.Studio/wwwroot/App/views/resources/widgets/ongoingTasksWidget.html
  src/Raven.Studio/wwwroot/Content/css/pages/cluster-dashboard.less
  src/Raven.Studio/wwwroot/Content/css/styles-common.less
  src/Raven.Studio/wwwroot/Content/css/virtual-grid.less
  src/Sparrow/Json/ArenaMemoryAllocator.cs
  test/FastTests/Blittable/BlittableJsonWriterTests/ArenaMemoryAllocatorTests.cs
  test/FastTests/Blittable/BlittableJsonWriterTests/ManualBuilderTests.cs
  test/SlowTests/Issues/RavenDB-18554.cs
  test/SlowTests/SparrowTests/LoggingSourceTests.cs
Labels: v5.4

#14594 RavenDB-18993 Ensure that index thread exists (test fix)
  test/SlowTests/Issues/RavenDB-15890.cs
Labels: v5.3

#14593 RavenDB-18936 Support for CreateFields on arrays inside JavaScriptIndex
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/JintLuceneDocumentConverter.cs
  test/SlowTests/Issues/RavenDB-18936.cs
Labels: v5.2

#14617 RavenDB-19008 - Use the correct event when collecting the allocations
  src/Raven.Server/Web/System/AdminAllocationDebugHandler.cs
  test/FastTests/Server/DebugMemoryTests.cs
Labels: v5.2

#14622 RavenDB-19003 fixing NRE
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Collections/ShardedCollectionsHandlerProcessorForGetCollectionStats.cs
  src/Raven.Server/Documents/Sharding/Operations/IShardedOperation.cs
Labels: v6.0

#14599 RavenDB-17817 Display the parameter in delete/update by query
  src/Raven.Server/Documents/Handlers/QueriesHandler.cs
Labels: v5.2

#14612 RavenDB-18804 - Add the request size to the traffic watch
  src/Raven.Client/Documents/Changes/ChangeNotification.cs
  src/Raven.Client/Util/StreamWithTimeout.cs
  src/Raven.Server/RavenServerStartup.cs
  src/Raven.Server/Web/RequestHandler.cs
Labels: v5.2

#14608 RavenDB-18911 Backup Task: Test credentials results do not show
  src/Raven.Studio/typescript/viewmodels/database/tasks/editPeriodicBackupTask.ts
  src/Raven.Studio/typescript/viewmodels/manage/editServerWideBackup.ts
Labels: v5.3

#14621 RavenDB-19009 Export/Import View: Fix PostgreSQL toggle
  src/Raven.Studio/wwwroot/App/views/database/tasks/smugglerDatabaseRecord.html
Labels: v5.3

#14633 5.2 to 5.3 merge
  src/Raven.Client/Documents/Changes/ChangeNotification.cs
  src/Raven.Client/Exceptions/ExceptionDispatcher.cs
  src/Raven.Client/Util/StreamWithTimeout.cs
  src/Raven.Server/Documents/Handlers/QueriesHandler.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/JintLuceneDocumentConverter.cs
  src/Raven.Server/RavenServerStartup.cs
  src/Raven.Server/Web/RequestHandler.cs
  src/Raven.Server/Web/System/AdminAllocationDebugHandler.cs
  test/FastTests/Server/DebugMemoryTests.cs
  test/SlowTests/Issues/RavenDB-18554.cs
  test/SlowTests/Issues/RavenDB-18936.cs
  test/Tests.Infrastructure/RavenTestBase.Cluster.cs
  test/Tests.Infrastructure/RavenTestBase.Indexes.cs
Labels: v5.3

#14643 RavenDB-18963 Studio - update npm packages
  src/Raven.Studio/jest.config.js
  src/Raven.Studio/package-lock.json
  src/Raven.Studio/package.json
Labels: v5.3

#14642 RavenDB-18804 Studio: Add request size to Traffic Watch
  src/Raven.Studio/typescript/viewmodels/manage/trafficWatch.ts
Labels: v5.2

#14641 RavenDB-18995 Downgrade TraceEvent
  tools/Raven.Debug/GCDump/Graph.cs
  tools/Raven.Debug/Raven.Debug.csproj
Labels: v5.2

#14639 RavenDB-18645 - fixed GET collections/docs
  src/Raven.Client/Documents/Session/Operations/StreamOperation.cs
  src/Raven.Server/Documents/Handlers/Processors/Collections/AbstractCollectionsHandlerProcessorForGetCollectionDocuments.cs
  src/Raven.Server/Documents/Handlers/Processors/Collections/CollectionsHandlerProcessorForGetCollectionDocuments.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Collections/ShardedCollectionsHandlerProcessorForGetCollectionDocuments.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Documents/ShardedDocumentHandlerProcessorForGet.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Streaming/ShardedStreamingHandlerProcessorForGetDocs.cs
  test/SlowTests/Sharding/Client/Operations/GetCollectionStatisticsOperationTests.cs
Labels: v6.0

#14635 RavenDB-18942 - add the unmanaged allocations made by Lucene to the stats
  src/Raven.Server/Documents/Handlers/Debugging/MemoryDebugHandler.cs
  src/Raven.Server/Program.cs
  src/Sparrow/Utils/MemoryUtils.cs
  src/Sparrow/Utils/NativeMemory.cs
Labels: v5.2

#14644 RavenDB-17275 Grid does not show stripes after clicking the up/down s…
  src/Raven.Studio/typescript/widgets/virtualGrid/virtualRow.ts
Labels: v5.2

#14602 RavenDB-19002 Fixing possible leak of DocumentDatabase instances by making sure that ResourceUsage<T>.TryRemove() removes the isntance that we really want and pass via the parameter.
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/ResourceCache.cs
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
  test/SlowTests/Issues/RavenDB_19002.cs
  test/StressTests/Rachis/DatabaseCluster/ClusterDatabaseMaintenanceStress.cs
Labels: v5.2

#14651 Raven.Client - Reduce dependencies for net5 and net6
  src/Raven.Client/Raven.Client.csproj
  src/Sparrow/Sparrow.csproj
Labels: v5.4

#14647 RavenDB-18961 Making sure that database dispose is not hanging forever if an operation task was not even started yet. Adding 30 seconds timeout in general to wait for an operation.
  src/Raven.Server/Documents/Operations/Operations.cs
Labels: v5.2

#14648 RavenDB-19033 Fixing the implementation of DatabaseLandlord.UnloadAndLockDatabase() so it respects that the database can be already locked
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/ResourceCache.cs
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
  test/SlowTests/Issues/RavenDB_19033.cs
  test/StressTests/Rachis/DatabaseCluster/ClusterDatabaseMaintenanceStress.cs
Labels: v5.2

#14649 RavenDB-19023 Fixing unobserved exception coming from SnmpDatabase if a database has been disabled meanwhile
  src/Raven.Server/Monitoring/Snmp/SnmpDatabase.cs
Labels: v5.2

#14650 RavenDB-18919 Ignoring exceptions in StorageSpaceMonitor if a database is shutting down
  src/Raven.Server/Storage/StorageSpaceMonitor.cs
Labels: v5.2
