Repository ravendb/ravendb, pull requests merged in 2022-04, with the labels that each got.

#13968 RavenDB-18075 Workaround for a codegen optimization issue which resulted in AVE during gc_heap::mark_object_simple
  src/Raven.Server/Documents/Queries/Parser/QueryParser.cs
Labels: v5.2

#13971 RavenDB-18395 Missing cron expressions for an existing Server-Wide ba…
  src/Raven.Studio/typescript/viewmodels/manage/editServerWideBackup.ts
  src/Raven.Studio/wwwroot/App/views/manage/editServerWideBackup.html
Labels: v5.3

#13966 RavenDB-18270 move analyzers handling inside the ShardedIndexesContext
  src/Raven.Server/Documents/Indexes/AbstractCompilationCache.cs
  src/Raven.Server/Documents/Indexes/Analysis/AnalyzerCompilationCache.cs
  src/Raven.Server/Documents/Indexes/Sorting/SorterCompilationCache.cs
  src/Raven.Server/Documents/Sharding/ShardedDatabaseContext.Indexes.cs
  src/Raven.Server/Documents/Sharding/ShardedDatabaseContext.cs
Labels: Sharding

#13951 RavenDB-18247 Sharding - Identities View
  src/Raven.Studio/typescript/common/shell/menu/items/documents.ts
  src/Raven.Studio/typescript/viewmodels/database/identities/identities.ts
Labels: Sharding

#13948 RavenDB-18264 Sharding - Time Series Settings View
  src/Raven.Studio/typescript/common/shell/menu/items/settings.ts
  src/Raven.Studio/typescript/viewmodels/database/settings/timeSeries.ts
Labels: Sharding

#13942 RavenDB-18311 Validate domain name does not start or end with '-'
  src/Raven.Studio/typescript/models/wizard/domainInfo.ts
Labels: v5.2

#13973 RavenDB-7070 ImportIncrementalAsync should take into account the CancellationToken passed when waiting for operation
  src/Raven.Client/Documents/Smuggler/DatabaseSmuggler.cs
  test/SlowTests/Issues/RavenDB_5998.cs
  test/SlowTests/Smuggler/LegacySmugglerTests.cs
Labels: v5.2

#13972 RavenDB-16951 Studio dashboard tooltips problem with long entries
  src/Raven.Studio/wwwroot/Content/css/basic-layout.less
Labels: v5.2

#13969 RavenDB-18399 Support for Nullable DateOnly&TimeOnly for conventers and MapReduce.
  src/Raven.Client/Documents/Indexes/ExpressionStringBuilder.cs
  src/Raven.Client/Json/Serialization/IJsonWriter.cs
  src/Raven.Client/Json/Serialization/NewtonsoftJson/Internal/BlittableJsonWriter.cs
  src/Raven.Server/Documents/Indexes/MapReduce/ReduceKeyProcessor.cs
  src/Raven.Server/Documents/Indexes/MapReduce/Static/MapReduceIndex.cs
  src/Raven.Server/Documents/Indexes/Static/StaticIndexBase.cs
  src/Raven.Server/Utils/TypeConverter.cs
  src/Sparrow/Json/Parsing/ObjectJsonParser.cs
  test/SlowTests/Issues/RavenDB-17250.cs
  test/SlowTests/Issues/RavenDB-18399.cs
  test/SlowTests/Issues/RavenDB-18404.cs
Labels: v5.3

#13980 RavenDB-18266 Sharding - Custom Sorters View
  src/Raven.Studio/typescript/commands/resources/getDatabaseStatsCommand.ts
  src/Raven.Studio/typescript/common/autoComplete/remoteMetadataProvider.ts
  src/Raven.Studio/typescript/common/rqlLanguageService.ts
  src/Raven.Studio/typescript/common/shell/menu/items/settings.ts
  src/Raven.Studio/typescript/viewmodels/database/patch/patch.ts
  src/Raven.Studio/typescript/viewmodels/database/query/query.ts
  src/Raven.Studio/typescript/viewmodels/database/settings/customSorters.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editSubscriptionTask.ts
Labels: v6.0

#13981 RavenDB-18268 Sharding - Custom Analyzers View
  src/Raven.Studio/typescript/common/shell/menu/items/settings.ts
  src/Raven.Studio/typescript/viewmodels/database/settings/customAnalyzers.ts
Labels: v6.0

#13985 RavenDB-18410 Custom Sorters View: Grid results not showing
  src/Raven.Studio/wwwroot/App/views/database/settings/customSorters.html
Labels: v5.3

#13982 RavenDB-18414 AddOrPatch / Patch session API adds needless $type valu…
  src/Raven.Client/Documents/Session/InMemoryDocumentSessionOperations.Patch.cs
  src/Raven.Client/Json/Serialization/IJsonSerializer.cs
  src/Raven.Client/Json/Serialization/NewtonsoftJson/Internal/NewtonsoftJsonJsonSerializer.cs
  src/Raven.Client/Json/Serialization/TypeNameHandling.cs
  test/SlowTests/Issues/RavenDB_18414.cs
Labels: v5.2

#13991 RavenDB-18246 added a test
  test/SlowTests/Issues/RavenDB_6967.cs
  test/Tests.Infrastructure/RavenTestBase.Indexes.cs
  test/Tests.Infrastructure/RavenTestHelper.cs
  test/Tests.Infrastructure/Utils/MaintenanceOperationExecutorTester.cs
Labels: v6.0

#13992 5.2 to 5.3 merge
  src/Raven.Client/Documents/Session/InMemoryDocumentSessionOperations.Patch.cs
  src/Raven.Client/Documents/Smuggler/DatabaseSmuggler.cs
  src/Raven.Client/Extensions/MemberInfoExtensions.cs
  src/Raven.Client/Json/Serialization/IJsonSerializer.cs
  src/Raven.Client/Json/Serialization/NewtonsoftJson/Internal/NewtonsoftJsonJsonSerializer.cs
  src/Raven.Client/Json/Serialization/TypeNameHandling.cs
  src/Raven.Server/Commercial/SetupManager.cs
  src/Raven.Server/Documents/Indexes/IndexingRunStats.cs
  src/Raven.Server/Documents/Indexes/IndexingStatsAggregator.cs
  src/Raven.Server/Documents/Indexes/MapReduce/Auto/ReduceMapResultsOfAutoIndex.cs
  src/Raven.Server/Documents/Indexes/MapReduce/ReduceMapResultsBase.cs
  src/Raven.Server/Documents/Indexes/MapReduce/Static/ReduceMapResultsOfStaticIndex.cs
  src/Raven.Server/Documents/Queries/Parser/QueryParser.cs
  src/Raven.Studio/typescript/models/wizard/domainInfo.ts
  src/Raven.Studio/wwwroot/Content/css/basic-layout.less
  test/SlowTests/Client/TimeSeries/Issues/RavenDB_16365.cs
  test/SlowTests/Issues/RavenDB_18331.cs
  test/SlowTests/Issues/RavenDB_18414.cs
  test/SlowTests/Issues/RavenDB_5998.cs
  test/SlowTests/Smuggler/LegacySmugglerTests.cs
Labels: v5.3

#13990 RavenDB-18259 Sharding - Document Expiration View
  src/Raven.Studio/typescript/common/shell/menu/items/settings.ts
  src/Raven.Studio/typescript/viewmodels/database/settings/expiration.ts
Labels: v6.0

#13988 RavenDB-18405 Edit Database Settings: Allow to set time values to -1
  src/Raven.Studio/typescript/models/database/settings/databaseSettingsModels.ts
Labels: v5.2

#13993 5.3 to 6.0 merge
  src/Raven.Client/Documents/Indexes/ExpressionStringBuilder.cs
  src/Raven.Client/Documents/Session/InMemoryDocumentSessionOperations.Patch.cs
  src/Raven.Client/Documents/Smuggler/DatabaseSmuggler.cs
  src/Raven.Client/Extensions/MemberInfoExtensions.cs
  src/Raven.Client/Json/Serialization/IJsonSerializer.cs
  src/Raven.Client/Json/Serialization/IJsonWriter.cs
  src/Raven.Client/Json/Serialization/NewtonsoftJson/Internal/BlittableJsonWriter.cs
  src/Raven.Client/Json/Serialization/NewtonsoftJson/Internal/NewtonsoftJsonJsonSerializer.cs
  src/Raven.Client/Json/Serialization/TypeNameHandling.cs
  src/Raven.Server/Commercial/SetupManager.cs
  src/Raven.Server/Documents/Indexes/IndexingRunStats.cs
  src/Raven.Server/Documents/Indexes/IndexingStatsAggregator.cs
  src/Raven.Server/Documents/Indexes/MapReduce/Auto/ReduceMapResultsOfAutoIndex.cs
  src/Raven.Server/Documents/Indexes/MapReduce/ReduceKeyProcessor.cs
  src/Raven.Server/Documents/Indexes/MapReduce/ReduceMapResultsBase.cs
  src/Raven.Server/Documents/Indexes/MapReduce/Static/MapReduceIndex.cs
  src/Raven.Server/Documents/Indexes/MapReduce/Static/ReduceMapResultsOfStaticIndex.cs
  src/Raven.Server/Documents/Indexes/Static/StaticIndexBase.cs
  src/Raven.Server/Documents/Sharding/Queries/ShardedMapReduceQueryResultsMerger.cs
  src/Raven.Server/Utils/TypeConverter.cs
  src/Raven.Studio/typescript/models/wizard/domainInfo.ts
  src/Raven.Studio/typescript/viewmodels/manage/editServerWideBackup.ts
  src/Raven.Studio/wwwroot/App/views/database/settings/customSorters.html
  src/Raven.Studio/wwwroot/App/views/manage/editServerWideBackup.html
  src/Raven.Studio/wwwroot/Content/css/basic-layout.less
  src/Sparrow/Json/Parsing/ObjectJsonParser.cs
  test/SlowTests/Client/TimeSeries/Issues/RavenDB_16365.cs
  test/SlowTests/Issues/RavenDB-17250.cs
  test/SlowTests/Issues/RavenDB-18399.cs
  test/SlowTests/Issues/RavenDB-18404.cs
  test/SlowTests/Issues/RavenDB_18331.cs
  test/SlowTests/Issues/RavenDB_18414.cs
  test/SlowTests/Issues/RavenDB_5998.cs
  test/SlowTests/Smuggler/LegacySmugglerTests.cs
Labels: v6.0

#13965 RavenDB-18397: Found the cause and simplified the code on other primitives.
  src/Corax/IndexSearcher/IndexSearcher.MultiTermMatches.cs
  src/Corax/IndexSearcher/IndexSearcher.TermMatch.cs
  test/SlowTests/MailingList/IndexMerging.cs
Labels: Corax

#14001 RavenDB-18418 Open dialog + Show spinner while loading stack trace
  src/Raven.Studio/typescript/viewmodels/manage/debugAdvancedThreadsRuntime.ts
  src/Raven.Studio/typescript/viewmodels/manage/threadStackTrace.ts
  src/Raven.Studio/wwwroot/App/views/manage/threadStackTrace.html
Labels: v5.2

#14000 5.3 to corax merge
  src/Raven.Client/Documents/Indexes/ExpressionStringBuilder.cs
  src/Raven.Client/Documents/Session/InMemoryDocumentSessionOperations.Patch.cs
  src/Raven.Client/Documents/Smuggler/DatabaseSmuggler.cs
  src/Raven.Client/Extensions/MemberInfoExtensions.cs
  src/Raven.Client/Json/Serialization/IJsonSerializer.cs
  src/Raven.Client/Json/Serialization/IJsonWriter.cs
  src/Raven.Client/Json/Serialization/NewtonsoftJson/Internal/BlittableJsonWriter.cs
  src/Raven.Client/Json/Serialization/NewtonsoftJson/Internal/NewtonsoftJsonJsonSerializer.cs
  src/Raven.Client/Json/Serialization/TypeNameHandling.cs
  src/Raven.Server/Commercial/SetupManager.cs
  src/Raven.Server/Documents/Indexes/IndexingRunStats.cs
  src/Raven.Server/Documents/Indexes/IndexingStatsAggregator.cs
  src/Raven.Server/Documents/Indexes/MapReduce/Auto/ReduceMapResultsOfAutoIndex.cs
  src/Raven.Server/Documents/Indexes/MapReduce/ReduceKeyProcessor.cs
  src/Raven.Server/Documents/Indexes/MapReduce/ReduceMapResultsBase.cs
  src/Raven.Server/Documents/Indexes/MapReduce/Static/MapReduceIndex.cs
  src/Raven.Server/Documents/Indexes/MapReduce/Static/ReduceMapResultsOfStaticIndex.cs
  src/Raven.Server/Documents/Indexes/Static/StaticIndexBase.cs
  src/Raven.Server/Documents/Queries/Parser/QueryParser.cs
  src/Raven.Server/Utils/TypeConverter.cs
  src/Raven.Studio/typescript/models/wizard/domainInfo.ts
  src/Raven.Studio/typescript/viewmodels/manage/editServerWideBackup.ts
  src/Raven.Studio/wwwroot/App/views/database/settings/customSorters.html
  src/Raven.Studio/wwwroot/App/views/manage/editServerWideBackup.html
  src/Raven.Studio/wwwroot/Content/css/basic-layout.less
  src/Sparrow/Json/Parsing/ObjectJsonParser.cs
  test/SlowTests/Client/Indexing/Counters/BasicCountersIndexes_JavaScript.cs
  test/SlowTests/Client/TimeSeries/Issues/RavenDB_16365.cs
  test/SlowTests/Issues/RavenDB-17250.cs
  test/SlowTests/Issues/RavenDB-18399.cs
  test/SlowTests/Issues/RavenDB-18404.cs
  test/SlowTests/Issues/RavenDB_18331.cs
  test/SlowTests/Issues/RavenDB_18414.cs
  test/SlowTests/Issues/RavenDB_5998.cs
  test/SlowTests/Smuggler/LegacySmugglerTests.cs
Labels: Corax

#14004 RavenDB-18394 Error when going to the backups view (using the databas…
  src/Raven.Studio/typescript/viewmodels/database/tasks/backups.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/ongoingTasks.ts
Labels: v5.3

#14002 RavenDB-18422 Expose the SQL PK values to the migration script
  src/Raven.Server/SqlMigration/GenericDatabaseMigrator.cs
  src/Raven.Server/SqlMigration/Model/SqlMigrationDocument.cs
Labels: v5.2

#14005 RavenDB-18302 Allow to copy the conflicted documents
  src/Raven.Studio/typescript/viewmodels/database/conflicts/conflicts.ts
  src/Raven.Studio/wwwroot/App/views/database/conflicts/conflicts.html
Labels: v5.2

#14010 RavenDB-18425 Async fix in test
  test/SlowTests/Issues/RavenDB-17250.cs
Labels: Corax

#14020 RavenDB-18009 Database list view - shard wide view - initial draft
  src/Raven.Studio/typescript/commands/resources/deleteDatabaseCommand.ts
  src/Raven.Studio/typescript/common/appUrl.ts
  src/Raven.Studio/typescript/components/hooks/useAccessManager.ts
  src/Raven.Studio/typescript/components/hooks/useActiveDatabase.ts
  src/Raven.Studio/typescript/components/hooks/useAppUrls.ts
  src/Raven.Studio/typescript/components/hooks/useServices.ts
  src/Raven.Studio/typescript/components/models/databases.d.ts
  src/Raven.Studio/typescript/components/pages/database/indexes/IndexPanel.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/IndexToolbarActions.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/IndexesPage.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/DatabasePanel.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/DatabasesCounter.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/DatabasesFilter.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/DatabasesPage.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/DatabasesStatsReducer.ts
  src/Raven.Studio/typescript/components/pages/resources/databases/DatabasesToolbarActions.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/NoDatabases.tsx
  src/Raven.Studio/typescript/components/services/DatabasesService.ts
  src/Raven.Studio/typescript/models/resources/info/databaseInfo.ts
  src/Raven.Studio/typescript/viewmodels/resources/databases.ts
  src/Raven.Studio/typescript/viewmodels/resources/databasesOld.ts
  src/Raven.Studio/wwwroot/App/views/resources/databases.html
Labels: v6.0

#14018 RavenDB-18422 Avoid using @sql-keys in the metadata in favor of Sql-K…
  src/Raven.Server/SqlMigration/Model/SqlMigrationDocument.cs
Labels: v5.2

#14015 RavenDB-18086 Display index source (Created By) in Index History view
  src/Raven.Studio/wwwroot/App/views/database/indexes/editIndex.html
  src/Raven.Studio/wwwroot/Content/css/pages/edit-index.less
Labels: v5.2

#14021 RavenDB-7070 properly detect current build version after moving to v6.0
  src/Raven.Server/Smuggler/Documents/Processors/BuildVersion.cs
  src/Raven.Server/Smuggler/Documents/Processors/IndexProcessor.cs
  src/Raven.Server/Smuggler/Documents/SmugglerBase.cs
  src/Raven.Server/Smuggler/Migration/MajorVersion.cs
  src/Raven.Server/Smuggler/Migration/Migrator.cs
  src/Raven.Server/Web/RequestHandler.Helper.cs
Labels: v6.0

#14023 RavenDB-18358 fix failing test
  src/Raven.Server/Documents/ShardedTcpHandlers/ShardedSubscriptionConnection.cs
  src/Raven.Server/Documents/TcpHandlers/SubscriptionConnection.cs
Labels: v6.0

#14027 RavenDB-18009 Database list view - shard wide view
  src/Raven.Studio/typescript/commands/resources/saveDatabaseLockModeCommand.ts
  src/Raven.Studio/typescript/components/models/databases.d.ts
  src/Raven.Studio/typescript/components/pages/resources/databases/DatabasePanel.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/DatabasesFilter.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/DatabasesPage.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/DatabasesStatsReducer.ts
  src/Raven.Studio/typescript/components/services/DatabasesService.ts
  src/Raven.Studio/typescript/components/utils/DatabaseUtils.ts
  src/Raven.Studio/typescript/viewmodels/resources/databasesOld.ts
Labels: v6.0

#14019 RavenDB-17993 show only refresh btn when database has error and fails…
  src/Raven.Studio/wwwroot/App/views/resources/databases.html
Labels: v5.3

#14034 RavenDB-18444 Can't view sharded database on a remote node
  src/Raven.Studio/typescript/common/shell/databasesManager.spec.ts
  src/Raven.Studio/typescript/common/shell/databasesManager.ts
  src/Raven.Studio/typescript/components/pages/resources/databases/DatabasesStatsReducer.ts
  src/Raven.Studio/typescript/components/utils/DatabaseUtils.ts
  src/Raven.Studio/typescript/models/resources/database.ts
  src/Raven.Studio/typescript/models/resources/shard.ts
  src/Raven.Studio/typescript/models/resources/shardedDatabase.ts
Labels: v6.0

#14031 RavenDB-18393 add support for canactivate redirect to shardAwareConta…
  src/Raven.Studio/typescript/viewmodels/common/sharding/shardAwareContainer.ts
Labels: v6.0

#14038 RavenDB-18449 : fix failing test ShardedEtlTests.OlapEtl_S3_Destination
  test/SlowTests/Sharding/ETL/ShardedEtlTests.cs
Labels: v6.0

#14024 RavenDB-18371 Integration of AndNot in CoraxQueryEvaluator.
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxQueryEvaluator.cs
  test/SlowTests/Core/Querying/Searching.cs
Labels: Corax

#14041 RavenDB-18100 RavenDB Tasks: Add info/warning about uploading the des…
  src/Raven.Studio/typescript/viewmodels/database/tasks/editExternalReplicationTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editRavenEtlTask.ts
  src/Raven.Studio/typescript/viewmodels/manage/editServerWideExternalReplication.ts
  src/Raven.Studio/wwwroot/App/views/database/tasks/editExternalReplicationTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editRavenEtlTask.html
  src/Raven.Studio/wwwroot/App/views/manage/editServerWideExternalReplication.html
  src/Raven.Studio/wwwroot/App/views/partial/certificateUploadInfoForOngoingTasks.html
Labels: v5.3

#14042 RavenDB-17974 For expired certificate: Allow to generate a new one wi…
  src/Raven.Studio/typescript/models/auth/certificateModel.ts
  src/Raven.Studio/typescript/viewmodels/manage/certificates.ts
  src/Raven.Studio/wwwroot/App/views/manage/certificates.html
Labels: v5.3

#14037 RavenDB-17991 Compact Database Popup: Explain about compressing docu…
  src/Raven.Studio/wwwroot/App/views/resources/compactDatabaseDialog.html
Labels: v5.3

#14046 RavenDB-7070 Fixing not awaited tests that are run in parallel in StressTests. This caused occasional crashes due to unhandled exceptions.
  test/StressTests/Issues/RavenDB-5763.cs
  test/StressTests/Server/Replication/ExternalReplicationStressTests_NoDispose.cs
Labels: v5.3

#14008 RavenDB-18426 Allow to project `id()` from map index while projection…
  src/Raven.Server/Documents/Queries/FieldsToFetch.cs
  src/Raven.Server/Documents/Queries/Results/QueryResultRetrieverBase.cs
  test/SlowTests/Issues/RavenDB-18426.cs
Labels: v5.3

#14039 RavenDB-18420: Reschedule Backup Timer If DocumentDatabase Failed To Load
  src/Raven.Server/Documents/DatabasesLandlord.cs
  test/StressTests/Issues/RavenDB_18420.cs
Labels: v4.2

#14047 RavenDB-17972 [Corax] Filter support
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxIndexReadOperation.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/LuceneIndexReadOperation.cs
  src/Raven.Server/Documents/Indexes/Persistence/QueryFilter.cs
  test/FastTests/Issues/RavenDB-17636.cs
Labels: Corax

#14057 HRINT-2667 prepare 6.0 alpha builds
  scripts/upload.ps1
  scripts/version.ps1
Labels: v6.0

#14052 RavenDB-18456 [Corax] Support for Exact in DeleteCommit
  src/Corax/IndexWriter.cs
  test/SlowTests/Tests/NestedIndexing/CanIndexReferencedEntity.cs
Labels: Corax

#14011 RavenDB-18437 - Show the browser message only when the request came from the studio
  src/Raven.Server/Extensions/HttpExtensions.cs
  src/Raven.Server/Routing/RequestRouter.cs
Labels: v5.2

#14068 RavenDB-18024 Notify user that enable/disable indexing requires datab…
  src/Raven.Server/Config/Categories/IndexingConfiguration.cs
  src/Raven.Studio/typescript/common/helpers/view/viewHelpers.ts
  src/Raven.Studio/typescript/viewmodels/common/confirmationDialog.ts
  src/Raven.Studio/typescript/viewmodels/database/settings/databaseSettings.ts
  src/Raven.Studio/typescript/viewmodels/resources/databases.ts
  src/Raven.Studio/typings/_studio/dto.d.ts
  src/Raven.Studio/wwwroot/App/views/common/confirmationDialog.html
Labels: v5.2

#14063 RavenDB-18417 Document formatting in the Studio re-sort property order
  src/Raven.Studio/aceBuild/addons/lib/ace/mode/json/checkNumericKey.js
  src/Raven.Studio/aceBuild/addons/lib/ace/mode/json/json_parse_with_number_check.js
  src/Raven.Studio/wwwroot/Content/ace/worker-raven_document.js
Labels: v5.2

#14064 RavenDB-18466 Failure in updating the ETL process state results in looping and getting stuck
  src/Raven.Server/Documents/ETL/EtlProcess.cs
Labels: v5.2

#14059 RavenDB-7070 updated to .NET 6.0.4 & 4.2 to 5.2 merge
  .github/workflows/FastTests.yml
  bench/BulkInsert.Benchmark/BulkInsert.Benchmark.csproj
  bench/Indexing.Benchmark/Indexing.Benchmark.csproj
  bench/Micro.Benchmark/Micro.Benchmark.csproj
  bench/Regression.Benchmark/Regression.Benchmark.csproj
  bench/SubscriptionFailover.Benchmark/SubscriptionFailover.Benchmark.csproj
  bench/Subscriptions.Benchmark/Subscriptions.Benchmark.csproj
  bench/TimeSeries.Benchmark/TimeSeries.Benchmark.csproj
  bench/Voron.Benchmark/Voron.Benchmark.csproj
  src/Raven.Embedded/ServerOptions.cs
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Studio/Raven.Studio.csproj
  src/Sparrow.Server/Sparrow.Server.csproj
  src/Voron/Voron.csproj
  test/BenchmarkTests/BenchmarkTests.csproj
  test/EmbeddedTests/EmbeddedTests.csproj
  test/FastTests/FastTests.csproj
  test/InterversionTests/InterversionTests.csproj
  test/LicenseTests/LicenseTests.csproj
  test/RachisTests/RachisTests.csproj
  test/SlowTests/SlowTests.csproj
  test/StressTests/Issues/RavenDB-5763.cs
  test/StressTests/Issues/RavenDB_18420.cs
  test/StressTests/Server/Replication/ExternalReplicationStressTests_NoDispose.cs
  test/StressTests/StressTests.csproj
  test/Studio/Studio.csproj
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
  test/Tryouts/Tryouts.csproj
  tools/Raven.Debug/Raven.Debug.csproj
  tools/Raven.Migrator/Raven.Migrator.csproj
  tools/TypingsGenerator/TypingsGenerator.csproj
  tools/Voron.Recovery/Voron.Recovery.csproj
  tools/rvn/rvn.csproj
Labels: v5.2

#14012 RavenDB-18436 Server Dashboard: Handle the OngoingTasks notification …
  src/Raven.Server/Dashboard/DatabasesInfoNotificationSender.cs
  src/Raven.Server/Dashboard/DatabasesInfoRetriever.cs
  src/Raven.Server/NotificationCenter/Handlers/ServerDashboardHandler.cs
Labels: v5.2

#14072 RavenDB-18467 tab is allowed character in headers
  test/SlowTests/Client/Attachments/AttachmentsCrud.cs
  test/SlowTests/Client/Attachments/AttachmentsReplication.cs
Labels: v5.2

#14079 RavenDB-17661 - Allow to get revisions bin info even when revisions settings are disabled
  src/Raven.Server/Documents/Handlers/RevisionsHandler.cs
  test/SlowTests/Issues/RavenDB-17661.cs
Labels: v5.2

#14073 RavenDB-18422 Use @sql-keys (as was originally intended), avoid setti…
  src/Raven.Server/SqlMigration/Model/SqlMigrationDocument.cs
Labels: v5.3

#14080 RavenDB-18329 Allow to define Store:No & Index:No in Map-Reduce index
  src/Raven.Studio/typescript/models/database/index/indexDefinition.ts
  src/Raven.Studio/typescript/models/database/index/indexFieldOptions.ts
Labels: v5.3

#14077 RavenDB-17680 Fix hidden dropdown
  src/Raven.Studio/wwwroot/Content/css/animations.less
Labels: v5.3

#14076 RavenDB-17662 Fix Copy button positioning
  src/Raven.Studio/wwwroot/App/views/database/indexes/additionalAssemblySyntax.html
  src/Raven.Studio/wwwroot/App/views/database/indexes/additionalSourceSyntax.html
  src/Raven.Studio/wwwroot/App/views/database/indexes/mapIndexSyntax.html
  src/Raven.Studio/wwwroot/App/views/database/indexes/mapReduceIndexSyntax.html
  src/Raven.Studio/wwwroot/App/views/database/patch/patchSyntax.html
  src/Raven.Studio/wwwroot/App/views/database/query/querySyntax.html
  src/Raven.Studio/wwwroot/App/views/database/settings/conflictResolutionScriptSyntax.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/subscriptionRqlSyntax.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/transformationScriptSyntax.html
  src/Raven.Studio/wwwroot/Content/css/styles-common.less
Labels: v5.3

#14075 RavenDB-17652 Change Indexing Performance icon
  src/Raven.Studio/typescript/common/shell/menu/items/indexes.ts
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.eot
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.svg
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.ttf
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon.woff
  src/Raven.Studio/wwwroot/Content/css/fonts/selection.json
  src/Raven.Studio/wwwroot/Content/css/icons.less
Labels: v5.3

#14081 5.2 to 5.3 merge
  src/Raven.Server/Documents/Handlers/RevisionsHandler.cs
  test/SlowTests/Issues/RavenDB-17661.cs
Labels: v5.3

#14092 RavenDB-17661 - allow deleting from the revisions bin when revisions are disabled
  src/Raven.Server/Documents/Handlers/Admin/AdminRevisionsHandler.cs
  test/SlowTests/Issues/RavenDB-17661.cs
Labels: v5.2

#14093 5.2. to 5.3 merge
  src/Raven.Server/Documents/Handlers/Admin/AdminRevisionsHandler.cs
  test/SlowTests/Issues/RavenDB-17661.cs
Labels: v5.3

#14061 RavenDB-18160 Make sure that StorageEnvironment can be collected by GC if leaked and its finalizer will be called
  src/Voron/StorageEnvironment.cs
Labels: v4.2

#14096 fixed github workflows configuration
  .github/workflows/StudioTests.yml
Labels: v6.0

#14097 RavenDB-18083 There is no need to opend write transaction when writing an attachment to temp file.
  src/Raven.Server/Documents/Handlers/BulkInsertHandler.cs
Labels: v5.2

#14103 RavenDB-18387 Sharding - Index Terms View
  src/Raven.Studio/typescript/common/shell/menu/items/indexes.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexTerms.ts
Labels: v6.0

#14102 RavenDB-18285 Sharding - Ongoing Tasks Stats View
  src/Raven.Studio/typescript/common/shell/menu/items/stats.ts
  src/Raven.Studio/typescript/viewmodels/database/status/ongoingTasksStats.ts
Labels: v6.0

#14101 RavenDB-18282 Sharding - Storage Report View
  src/Raven.Studio/typescript/common/shell/menu/items/stats.ts
  src/Raven.Studio/typescript/viewmodels/database/status/storageReport.ts
Labels: v6.0

#14098 RavenDB-18482 escape the backslash
  src/Raven.Studio/typescript/common/queryUtil.spec.ts
  src/Raven.Studio/typescript/common/queryUtil.ts
Labels: v5.3

#14100 RavenDB-18280 Sharding - IO Stats View
  src/Raven.Studio/typescript/common/shell/menu/items/stats.ts
  src/Raven.Studio/typescript/viewmodels/database/status/ioStats.ts
Labels: v6.0

#14105 RavenDB-18490 Searching with the usage of multiple phrases must not add +"?" to Lucene query so we'll get correct results
  src/Raven.Server/Documents/Queries/QueryBuilder.cs
  test/SlowTests/Issues/RavenDB_18490.cs
Labels: v5.2

#14110 RavenDB-18483 Corax - customizable between.
  src/Corax/IndexSearcher/IndexSearcher.UnaryMatches.cs
  src/Corax/Queries/UnaryMatch.Between.cs
  src/Corax/Queries/UnaryMatch.Ordinal.cs
  test/FastTests/Corax/IndexSearcher.cs
Labels: Corax

#14111 RavenDB-18495 Copy button overlaps 'Revision' label
  src/Raven.Studio/wwwroot/App/views/database/documents/editDocument.html
  src/Raven.Studio/wwwroot/Content/css/styles-common.less
Labels: v5.3

#14114 RavenDB-18505 Migration from MongoDB test doesn't cleanup created database
  test/SlowTests/Server/Documents/Migration/MongoDBMigrationTest.cs
  test/Tests.Infrastructure/ConnectionString/MongoDBConnectionString.cs
Labels: v4.2

#14120 RavenDB-18078 Highlight - negative for start fregment index, better h…
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Highlightings/FastVectorHightlighter/BaseFragmentsBuilder.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/IndexReadOperation.cs
  test/SlowTests/Tests/Issues/RavenDB-18078.cs
Labels: v5.3

#14118 RavenDB-18511 Improve setup wizard with BYO certificate that doesn't …
  src/Raven.Server/Commercial/SetupManager.cs
Labels: v5.3

#14135 RavenDB-18346 Sharding - Studio - Tasks View
  src/Raven.Studio/typescript/common/shell/menu/items/tasks.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/backups.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/createOngoingTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editElasticSearchEtlTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editExternalReplicationTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editOlapEtlTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editPeriodicBackupTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editRavenEtlTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editReplicationHubTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editReplicationSinkTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editSqlEtlTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editSubscriptionTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/ongoingTasks.ts
Labels: v6.0
