Repository ravendb/ravendb, pull requests merged in 2022-05, with the labels that each got.

#14151 RavenDB-18558 Fix overflow when database name is too long
  src/Raven.Studio/wwwroot/App/views/resources/createDatabase.html
  src/Raven.Studio/wwwroot/App/views/resources/deleteDatabaseConfirm.html
Labels: v5.2

#14154 RavenDB-18352 Running test OLAP ETL script first time gives endless-s…
  src/Raven.Studio/typescript/viewmodels/database/tasks/editOlapEtlTask.ts
Labels: v5.3

#14160 RavenDB-18489 When node is red, the graph edge is connected to a gree…
  src/Raven.Studio/typescript/models/database/cluster/clusterGraph.ts
Labels: v5.2

#14147 RavenDB-18389 Sharding - Dump Index Dialog
  src/Raven.Studio/typescript/commands/database/index/dumpIndexCommand.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/dumpDialog.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/editIndex.ts
Labels: v6.0

#14161 RavenDB-18438 PostgreSQL View - don't call server when user doesn't h…
  src/Raven.Studio/typescript/viewmodels/database/settings/integrations.ts
  src/Raven.Studio/wwwroot/App/views/database/settings/integrations.html
Labels: v5.3

#14163 RavenDB-18438 PostgreSQL View - don't call server when user doesn't h…
  src/Raven.Studio/wwwroot/App/views/database/settings/integrations.html
Labels: v5.3

#14162 RavenDB-17967 Setup: Selecting 0.0.0.0 as IP address of a node should…
  src/Raven.Studio/typescript/models/wizard/nodeInfo.ts
Labels: v5.3

#14165 RavenDB-18542 Wrong highlighting for index definition
  src/Raven.Studio/aceBuild/addons/lib/ace/mode/ravenMapLinq_highlight_rules.js
  src/Raven.Studio/typescript/models/database/index/indexAceAutoCompleteProvider.ts
  src/Raven.Studio/wwwroot/Content/ace/mode-ravenMapLinq.js
Labels: v5.3

#14169 RavenDB-18085 [Sharding] Documents listing - fixes
  src/Raven.Studio/typescript/commands/database/documents/getDocumentsFromCollectionCommand.ts
  src/Raven.Studio/typescript/common/autoComplete/remoteMetadataProvider.ts
  src/Raven.Studio/typescript/common/helpers/database/collectionsTracker.ts
  src/Raven.Studio/typescript/components/pages/database/indexes/IndexesPage.tsx
  src/Raven.Studio/typescript/models/database/documents/collection.ts
  src/Raven.Studio/typescript/models/database/documents/collectionsStats.ts
  src/Raven.Studio/typescript/models/database/index/indexAceAutoCompleteProvider.ts
  src/Raven.Studio/typescript/viewmodels/database/conflicts/conflicts.ts
  src/Raven.Studio/typescript/viewmodels/database/documents/documents.ts
  src/Raven.Studio/typescript/viewmodels/database/documents/editDocument.ts
  src/Raven.Studio/wwwroot/App/views/common/sharding/shardAwareContainer.html
  src/Raven.Studio/wwwroot/App/views/common/sharding/shardingContext.html
Labels: v6.0

#14167 RavenDB-18445 Sharding - Ongoing Tasks - Get - TEMP - ability to show…
  src/Raven.Studio/typescript/viewmodels/database/tasks/ongoingTasks.ts
Labels: v6.0

#14148 RavenDB-18545 - Fix - Can't select a field that its name is equal to …
  src/Raven.Client/Documents/Session/Tokens/GroupByKeyToken.cs
  test/SlowTests/Issues/RavenDB-18545.cs
Labels: v5.2

#14176 RavenDB-18575 - Changing aseertion. ModifyLocalServer is not mandatory.
  test/SlowTests/Tools/SetupSecuredClusterUsingRvn.cs
Labels: v5.2

#14048 RavenDB-18413 Timings aren't filled after ToQueryable
  src/Raven.Client/Documents/Queries/Timings/QueryTimings.cs
  src/Raven.Client/Documents/Session/AbstractDocumentQuery.Timings.cs
  src/Raven.Client/Documents/Session/AbstractDocumentQuery.cs
  src/Raven.Client/Documents/Session/DocumentQuery.cs
Labels: v5.2

#14188 RavenDB-18596 - fix suggestions for backup folders when using a UNC path
  src/Raven.Server/Web/Studio/FolderPath.cs
Labels: v5.2

#14187 RavenDB-18124 Added confirmation dialog when providing your own cert…
  src/Raven.Studio/typescript/viewmodels/wizard/finish.ts
  src/Raven.Studio/typescript/viewmodels/wizard/secureInstructions.ts
  src/Raven.Studio/wwwroot/App/views/wizard/finish.html
  src/Raven.Studio/wwwroot/App/views/wizard/secureInstructions.html
Labels: v5.2

#14193 RavenDB-18599 Menu item Recent should be All Documents
  src/Raven.Studio/typescript/common/shell/menu/items/documents.ts
  src/Raven.Studio/wwwroot/App/views/shell.html
Labels: v5.3

#14189 RavenDB-18565 Patch & Query Views: refactor the disable-auto-indexes…
  src/Raven.Studio/wwwroot/App/views/database/patch/patch.html
  src/Raven.Studio/wwwroot/App/views/database/query/query.html
  src/Raven.Studio/wwwroot/App/views/database/settings/studioConfiguration.html
Labels: v5.3

#14199 RavenDB-18444 Can't view sharded database on a remote node
  src/Raven.Studio/typescript/commands/database/index/getIndexDebugSourceDocumentsCommand.ts
  src/Raven.Studio/typescript/commands/database/index/getIndexMapReduceTreeCommand.ts
  src/Raven.Studio/typescript/common/liveIndexPerformanceWebSocketClient.ts
  src/Raven.Studio/typescript/common/shell/menu/items/documents.ts
  src/Raven.Studio/typescript/common/shell/menu/items/indexes.ts
  src/Raven.Studio/typescript/common/shell/menu/items/settings.ts
  src/Raven.Studio/typescript/common/shell/menu/items/stats.ts
  src/Raven.Studio/typescript/common/shell/menu/items/tasks.ts
  src/Raven.Studio/typescript/viewmodels/common/sharding/allShardsDialog.ts
  src/Raven.Studio/typescript/viewmodels/common/sharding/shardAwareContainer.ts
  src/Raven.Studio/typescript/viewmodels/common/sharding/shardSelector.ts
  src/Raven.Studio/typescript/viewmodels/common/sharding/shardingContext.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexPerformance.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/visualizer/visualizer.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/importParent.ts
  src/Raven.Studio/typescript/viewmodels/shardViewModelBase.ts
  src/Raven.Studio/typings/_studio/dto.d.ts
  src/Raven.Studio/wwwroot/App/views/common/sharding/allShardsDialog.html
  src/Raven.Studio/wwwroot/App/views/common/sharding/shardSelector.html
  src/Raven.Studio/wwwroot/App/views/common/sharding/shardingContext.html
Labels: v6.0

#14184 RavenDB-18122 Cluster View: Provide info about how to bootstrap the c…
  src/Raven.Studio/typescript/viewmodels/manage/cluster.ts
  src/Raven.Studio/wwwroot/App/views/manage/cluster.html
  src/Raven.Studio/wwwroot/App/views/resources/serverDashboard.html
  src/Raven.Studio/wwwroot/Content/css/pages/about.less
  src/Raven.Studio/wwwroot/Content/css/styles-common.less
Labels: v5.2

#14202 5.2 to 5.3 merge
  .github/workflows/FastTests.yml
  bench/BulkInsert.Benchmark/BulkInsert.Benchmark.csproj
  bench/Indexing.Benchmark/Indexing.Benchmark.csproj
  bench/Micro.Benchmark/Micro.Benchmark.csproj
  bench/Regression.Benchmark/Regression.Benchmark.csproj
  bench/SubscriptionFailover.Benchmark/SubscriptionFailover.Benchmark.csproj
  bench/Subscriptions.Benchmark/Subscriptions.Benchmark.csproj
  bench/TimeSeries.Benchmark/TimeSeries.Benchmark.csproj
  bench/Voron.Benchmark/Voron.Benchmark.csproj
  src/Raven.Client/Raven.Client.csproj
  src/Raven.Embedded/ServerOptions.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/AnonymousLuceneDocumentConverter.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/JintLuceneDocumentConverter.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/LuceneDocumentConverterBase.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Studio/Raven.Studio.csproj
  src/Raven.Studio/typescript/viewmodels/manage/cluster.ts
  src/Raven.Studio/wwwroot/App/views/manage/cluster.html
  src/Raven.Studio/wwwroot/App/views/resources/serverDashboard.html
  src/Raven.Studio/wwwroot/Content/css/pages/about.less
  src/Raven.Studio/wwwroot/Content/css/styles-common.less
  src/Sparrow.Server/Sparrow.Server.csproj
  src/Voron/Voron.csproj
  test/BenchmarkTests/BenchmarkTests.csproj
  test/EmbeddedTests/EmbeddedTests.csproj
  test/FastTests/FastTests.csproj
  test/InterversionTests/InterversionTests.csproj
  test/LicenseTests/LicenseTests.csproj
  test/RachisTests/RachisTests.csproj
  test/SlowTests/Issues/RavenDB-18594.cs
  test/SlowTests/SlowTests.csproj
  test/StressTests/StressTests.csproj
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
  test/Tryouts/Tryouts.csproj
  tools/Raven.Debug/Raven.Debug.csproj
  tools/Raven.Migrator/Raven.Migrator.csproj
  tools/TypingsGenerator/TypingsGenerator.csproj
  tools/Voron.Recovery/Voron.Recovery.csproj
  tools/rvn/rvn.csproj
Labels: v5.3

#14208 RavenDB-7070 removed possible task deadlocks
  test/FastTests/Client/HiLo.cs
  test/SlowTests/Client/Subscriptions/SubscriptionOperationsSignaling.cs
  test/SlowTests/Client/Subscriptions/Subscriptions.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Restore/RestoreFromGoogleCloud.cs
  test/SlowTests/Server/RecordingTransactionOperationsMergerTests.cs
  test/SlowTests/SparrowTests/LoggingSourceTests.cs
Labels: v4.2

#14221 RavenDB-18235 Sharding - Edit SQL ETL View
  src/Raven.Studio/wwwroot/App/views/database/tasks/editSqlEtlTask.html
Labels: v6.0

#14218 RavenDB-18229 Sharding - Edit Replication Hub View - No need for node…
  src/Raven.Studio/typescript/commands/database/tasks/getReplicationHubTaskInfoCommand.ts
Labels: v6.0

#14220 RavenDB-18233 Sharding - Edit RavenDB ETL View
  src/Raven.Studio/wwwroot/App/views/database/tasks/editRavenEtlTask.html
Labels: v6.0

#14219 RavenDB-18620 - Minor backward compatibly change to support id
  src/Raven.Server/Documents/Handlers/Debugging/QueriesDebugHandler.cs
Labels: v5.3

#14215 RavenDB-17030 - SlowTests.Issues.RavenDB_15430.MarkPolicyAfterRollup
  test/SlowTests/Issues/RavenDB_15430.cs
Labels: v5.2

#14210 RavenDB-18610 Missing the node type icon in the Cluster Topology Graph
  src/Raven.Studio/typescript/common/helpers/view/icomoonHelpers.ts
  src/Raven.Studio/typescript/models/database/cluster/clusterGraph.ts
  src/Raven.Studio/webpack.config.js
  src/Raven.Studio/wwwroot/Content/css/checkbox-toggle.less
Labels: v5.3

#14224 RavenDB-18199 Fixing failing test on Linux due to line endings
  test/SlowTests/Sharding/Issues/RavenDB_18199.cs
  test/Tests.Infrastructure/RavenTestHelper.cs
Labels: v6.0

#14229 RavenDB-18640 Using cached value for extended memory info during CanContinueBatch because it was too expensive to calculate it each time
  src/Raven.Server/Dashboard/Cluster/Notifications/MemoryUsageNotificationSender.cs
  src/Raven.Server/Dashboard/MachineResourcesNotificationSender.cs
  src/Raven.Server/Documents/ETL/EtlProcess.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.6/ServerTotalMemory.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.6/ServerTotalSwapSize.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.6/ServerTotalSwapUsage.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.6/ServerWorkingSetSwapUsage.cs
  src/Raven.Server/ServerWide/Memory/MemoryUsageGuard.cs
  src/Raven.Server/ServerWide/ServerMetricCacher.cs
  src/Raven.Server/Utils/MetricCacher.cs
  src/Raven.Server/Web/System/AdminMonitoringHandler.cs
  test/Tests.Infrastructure/TestMetrics/TestResourcesAnalyzerMetricCacher.cs
Labels: v5.2

#14230 5.2 to 5.3 merge
  src/Raven.Server/Dashboard/Cluster/Notifications/MemoryUsageNotificationSender.cs
  src/Raven.Server/Dashboard/MachineResourcesNotificationSender.cs
  src/Raven.Server/Documents/ETL/EtlProcess.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/PeriodicBackup/Aws/RavenAwsS3Client.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.6/ServerTotalMemory.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.6/ServerTotalSwapSize.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.6/ServerTotalSwapUsage.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.6/ServerWorkingSetSwapUsage.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Server/ServerWide/Memory/MemoryUsageGuard.cs
  src/Raven.Server/ServerWide/ServerMetricCacher.cs
  src/Raven.Server/Utils/MetricCacher.cs
  src/Raven.Server/Web/System/AdminMonitoringHandler.cs
  test/SlowTests/Issues/RavenDB_15430.cs
  test/SlowTests/Server/Documents/PeriodicBackup/CustomS3.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Restore/RestoreFromCustomS3.cs
  test/Tests.Infrastructure/TestMetrics/TestResourcesAnalyzerMetricCacher.cs
Labels: v5.3

#14226 RavenDB-18473 Let us ignore the creation of the attachment tombstone if it already exists.
  src/Raven.Server/Documents/AttachmentsStorage.cs
  test/SlowTests/Issues/RavenDB_18473.cs
Labels: v5.2

#14233 RavenDB-18276 Sharding - Stats View
  src/Raven.Studio/typescript/commands/resources/getDatabaseDetailedStatsCommand.ts
  src/Raven.Studio/typescript/viewmodels/database/status/statistics.ts
Labels: v6.0

#14238 RavenDB-7070 Print to the console the info about GC we force to run due to IO failures when running tests
  src/Raven.Server/Utils/IOExtensions.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v5.2

#14234 RavenDB-18209 Sharding - Query View
  src/Raven.Studio/typescript/common/autoComplete/remoteMetadataProvider.ts
  src/Raven.Studio/typescript/common/rqlLanguageService.ts
  src/Raven.Studio/typescript/viewmodels/database/patch/patch.ts
  src/Raven.Studio/typescript/viewmodels/database/query/query.ts
  src/Raven.Studio/typescript/viewmodels/database/settings/customSorters.ts
Labels: v6.0

#14231 RavenDB-18590 handle a race that disconnected leader can commit a NOOP command without having a consensus
  src/Raven.Server/Rachis/Elector.cs
  src/Raven.Server/Rachis/Follower.cs
  src/Raven.Server/Rachis/Leader.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/Rachis/Remote/RemoteConnection.cs
  test/RachisTests/ElectionTests.cs
Labels: v5.2

#14228 RavenDB-18638 - SlowTests.Sharding.ETL.ShardedEtlTests.SlowTests.Shar…
  test/SlowTests/Sharding/ETL/ShardedEtlTests.cs
Labels: v6.0

#14241 5.2 to 5.3 merge
  src/Raven.Client/Exceptions/Documents/Subscriptions/SubscriptionClosedException.cs
  src/Raven.Server/Documents/AttachmentsStorage.cs
  src/Raven.Server/Documents/Subscriptions/SubscriptionStorage.cs
  src/Raven.Server/Documents/TcpHandlers/SubscriptionConnection.cs
  src/Raven.Server/Rachis/Elector.cs
  src/Raven.Server/Rachis/Follower.cs
  src/Raven.Server/Rachis/Leader.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/Rachis/Remote/RemoteConnection.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Utils/IOExtensions.cs
  src/Raven.Server/Web/System/DatabasesDebugHandler.cs
  test/RachisTests/ElectionTests.cs
  test/SlowTests/Client/Subscriptions/SubscriptionsBasic.cs
  test/SlowTests/Issues/RavenDB_18473.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v5.3

#14242 RavenDB-18518 Add the new Generation & Expiration icons
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon/expiration.svg
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon/generation.svg
Labels: v5.3

#14247 RavenDB-17963 Adding retry arrtibute to SQL ETL tests so we won't faili immediately on connection errors
  test/SlowTests/Server/Documents/ETL/SQL/SqlEtlTests.cs
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
Labels: v4.2

#14259 RavenDB-18150: move backup logs to operations
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
Labels: v5.2

#14256 5.2 to 5.3 merge
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackup.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.1/DatabaseOldestBackup.cs
  src/Raven.Server/Rachis/Follower.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/Utils/BackupUtils.cs
  src/Raven.Server/Web/System/DatabasesHandler.cs
  src/Raven.Server/Web/System/OngoingTasksHandler.cs
  test/RachisTests/CommandsTests.cs
  test/RachisTests/ElectionTests.cs
  test/SlowTests/Issues/RavenDB-18442.cs
  test/SlowTests/Server/Documents/ETL/SQL/SqlEtlTests.cs
  test/Tests.Infrastructure/RachisConsensusTestBase.cs
  test/Tests.Infrastructure/RavenTestHelper.cs
Labels: v5.3

#14255 RavenDB-18643 OnProgress event in BulkInsert
  src/Raven.Client/Documents/BulkInsert/BulkInsertOperation.cs
  src/Raven.Client/Documents/Operations/BulkInsertObservableOperation.cs
  src/Raven.Client/Documents/Operations/BulkInsertObserver.cs
  src/Raven.Client/Documents/Session/Events.cs
  test/SlowTests/Issues/RavenDB-18643.cs
Labels: v5.3

#14264 5.3 to feature/corax merge
  src/Raven.Client/Documents/BulkInsert/BulkInsertOperation.cs
  src/Raven.Client/Documents/BulkInsert/BulkInsertOptions.cs
  src/Raven.Client/Documents/Operations/BulkInsertObserver.cs
  src/Raven.Client/Documents/Session/Events.cs
  src/Raven.Client/Exceptions/Documents/Subscriptions/SubscriptionClosedException.cs
  src/Raven.Server/Dashboard/Cluster/Notifications/MemoryUsageNotificationSender.cs
  src/Raven.Server/Dashboard/MachineResourcesNotificationSender.cs
  src/Raven.Server/Documents/AttachmentsStorage.cs
  src/Raven.Server/Documents/ETL/EtlProcess.cs
  src/Raven.Server/Documents/Handlers/Debugging/QueriesDebugHandler.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/PeriodicBackup/Aws/RavenAwsS3Client.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackup.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
  src/Raven.Server/Documents/Subscriptions/SubscriptionStorage.cs
  src/Raven.Server/Documents/TcpHandlers/SubscriptionConnection.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.1/DatabaseOldestBackup.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.6/ServerTotalMemory.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.6/ServerTotalSwapSize.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.6/ServerTotalSwapUsage.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.6/ServerWorkingSetSwapUsage.cs
  src/Raven.Server/Rachis/Elector.cs
  src/Raven.Server/Rachis/Follower.cs
  src/Raven.Server/Rachis/Leader.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/Rachis/Remote/RemoteConnection.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Server/ServerWide/Memory/MemoryUsageGuard.cs
  src/Raven.Server/ServerWide/ServerMetricCacher.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Utils/BackupUtils.cs
  src/Raven.Server/Utils/IOExtensions.cs
  src/Raven.Server/Utils/MetricCacher.cs
  src/Raven.Server/Web/System/AdminMonitoringHandler.cs
  src/Raven.Server/Web/System/DatabasesDebugHandler.cs
  src/Raven.Server/Web/System/DatabasesHandler.cs
  src/Raven.Server/Web/System/OngoingTasksHandler.cs
  src/Raven.Studio/typescript/common/helpers/view/icomoonHelpers.ts
  src/Raven.Studio/typescript/models/database/cluster/clusterGraph.ts
  src/Raven.Studio/webpack.config.js
  src/Raven.Studio/wwwroot/Content/css/checkbox-toggle.less
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon/expiration.svg
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon/generation.svg
  test/RachisTests/CommandsTests.cs
  test/RachisTests/ElectionTests.cs
  test/SlowTests/Client/Subscriptions/SubscriptionsBasic.cs
  test/SlowTests/Issues/RavenDB-18442.cs
  test/SlowTests/Issues/RavenDB-18643.cs
  test/SlowTests/Issues/RavenDB_15430.cs
  test/SlowTests/Issues/RavenDB_18473.cs
  test/SlowTests/Server/Documents/ETL/SQL/SqlEtlTests.cs
  test/SlowTests/Server/Documents/PeriodicBackup/CustomS3.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Restore/RestoreFromCustomS3.cs
  test/Tests.Infrastructure/RachisConsensusTestBase.cs
  test/Tests.Infrastructure/RavenTestHelper.cs
  test/Tests.Infrastructure/TestBase.cs
  test/Tests.Infrastructure/TestMetrics/TestResourcesAnalyzerMetricCacher.cs
Labels: Corax

#14265 RavenDB-18090 Add ElasticSearch ETL to the Tasks Panel in the Cluster…
  src/Raven.Server/Dashboard/DatabasesInfoRetriever.cs
  src/Raven.Server/Dashboard/DatabasesOngoingTasksInfo.cs
  src/Raven.Studio/typescript/viewmodels/resources/widgets/ongoingTasksWidget.ts
  src/Raven.Studio/wwwroot/Content/css/pages/cluster-dashboard.less
Labels: v5.3

#14266 RavenDB-18664 - add the actual error to the exception
  src/Raven.Client/Http/RequestExecutor.cs
Labels: v5.2

#14263 RavenDB-18234 - Edit RavenDB ETL View Endpoints
  src/Raven.Server/Documents/ETL/Providers/Raven/Handlers/RavenEtlHandler.cs
  src/Raven.Server/Documents/Handlers/Processors/ETL/AbstractEtlHandlerProcessorForTestEtl.cs
  src/Raven.Server/Documents/Handlers/Processors/ETL/EtlHandlerProcessorForTestEtl.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/ETL/ShardedEtlHandlerProcessorForTestEtl.cs
  src/Raven.Server/Documents/Sharding/Handlers/ShardedRavenEtlHandler.cs
Labels: v6.0

#14272 RavenDB-18276 Sharding - Stats View
  src/Raven.Server/Json/BlittableJsonTextWriterExtensions.cs
  src/Raven.Studio/jest.config.js
  src/Raven.Studio/scripts/setup_runtime.ts
  src/Raven.Studio/typescript/commands/resources/getDatabaseStatsCommand.ts
  src/Raven.Studio/typescript/commands/resources/getEssentialDatabaseStatsCommand.ts
  src/Raven.Studio/typescript/common/appUrl.ts
  src/Raven.Studio/typescript/common/shell/menu/items/stats.ts
  src/Raven.Studio/typescript/components/models/common.d.ts
  src/Raven.Studio/typescript/components/models/indexes.d.ts
  src/Raven.Studio/typescript/components/pages/database/status/statistics/DetailedDatabaseStats.tsx
  src/Raven.Studio/typescript/components/pages/database/status/statistics/EssentialDatabaseStatsComponent.tsx
  src/Raven.Studio/typescript/components/pages/database/status/statistics/StatisticsPage.spec.tsx
  src/Raven.Studio/typescript/components/pages/database/status/statistics/StatisticsPage.stories.tsx
  src/Raven.Studio/typescript/components/pages/database/status/statistics/StatisticsPage.tsx
  src/Raven.Studio/typescript/components/services/DatabasesService.ts
  src/Raven.Studio/typescript/models/database/stats/statistics.ts
  src/Raven.Studio/typescript/test/DatabaseStubs.ts
  src/Raven.Studio/typescript/test/mocks/MockDatabasesService.ts
  src/Raven.Studio/typescript/viewmodels/database/patch/patch.ts
  src/Raven.Studio/typescript/viewmodels/database/query/query.ts
  src/Raven.Studio/typescript/viewmodels/database/settings/customSorters.ts
  src/Raven.Studio/typescript/viewmodels/database/status/statistics.ts
  src/Raven.Studio/wwwroot/App/views/database/status/statistics.html
  tools/TypingsGenerator/Program.cs
Labels: v6.0

#14273 RavenDB-18665 Adding a new permissions to certificate leads to radio …
  src/Raven.Studio/wwwroot/App/views/manage/certificates.html
Labels: v5.2

#14275 5.2 to 5.3 merge
  src/Raven.Client/Http/RequestExecutor.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
  src/Raven.Studio/wwwroot/App/views/manage/certificates.html
  test/RachisTests/DatabaseCluster/AtomicClusterReadWriteTests.cs
  test/SlowTests/Issues/RavenDB_15409.cs
  test/SlowTests/SparrowTests/LoggingSourceTests.cs
  test/Tests.Infrastructure/Utils/DummyWebSocket.cs
Labels: v5.3

#14274 RavenDB-18621 : Reset should Not be mandatory when saving an ETL task
  src/Raven.Server/Documents/Handlers/Processors/OngoingTasks/AbstractOngoingTasksHandlerProcessorForAddEtl.cs
Labels: v6.0

#14292 RavenDB-18686 Enable button is not visible on databases page
  src/Raven.Studio/wwwroot/App/views/resources/databases.html
Labels: v5.3

#14284 RavenDB-18104 proper auth for /databases/*/subscription-tasks/state endpoint
  src/Raven.Server/Documents/Handlers/Processors/Databases/AbstractHandlerProcessorForUpdateDatabaseConfiguration.cs
  src/Raven.Server/Documents/Handlers/Processors/OngoingTasks/OngoingTasksHandlerProcessorForToggleTaskState.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/OngoingTasks/ShardedOngoingTasksHandlerProcessorForToggleTaskState.cs
  src/Raven.Server/Documents/Sharding/Handlers/ShardedOngoingTasksHandler.cs
  src/Raven.Server/Web/System/OngoingTasksHandler.cs
Labels: v6.0

#14285 RavenDB-18681 - Fix RavenDB-18442 test failure.
  test/SlowTests/Issues/RavenDB-18442.cs
Labels: v5.2

#14294 RavenDB-18389 Sharding - Dump Index Dialog
  src/Raven.Studio/typescript/components/common/MultipleDatabaseLocationSelector.stories.tsx
  src/Raven.Studio/typescript/components/common/MultipleDatabaseLocationSelector.tsx
  src/Raven.Studio/typescript/components/common/SingleDatabaseLocationSelector.stories.tsx
  src/Raven.Studio/typescript/components/common/SingleDatabaseLocationSelector.tsx
  src/Raven.Studio/typescript/viewmodels/database/indexes/bulkIndexOperationConfirm.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/dumpDialog.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexes.ts
  src/Raven.Studio/typings/_studio/dto.d.ts
  src/Raven.Studio/wwwroot/App/views/database/indexes/dumpDialog.html
Labels: v6.0

#14295 RavenDB-18623 Apply-to-All-Collections should not show when adding s…
  src/Raven.Studio/typescript/models/database/tasks/ongoingTaskElasticSearchEtlTransformationModel.ts
  src/Raven.Studio/typescript/models/database/tasks/ongoingTaskOlapEtlTransformationModel.ts
  src/Raven.Studio/typescript/models/database/tasks/ongoingTaskRavenEtlTransformationModel.ts
  src/Raven.Studio/typescript/models/database/tasks/ongoingTaskSqlEtlTransformationModel.ts
Labels: v5.3

#14291 RavenDB-17913: fix race condition in test
  test/SlowTests/Client/Subscriptions/SubscriptionsBasic.cs
Labels: v5.3

#14288 RavenDB-18677 Ensure no replication from multiple nodes to rehab
  src/Raven.Client/ServerWide/DatabaseTopology.cs
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/Replication/IncomingReplicationHandler.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
Labels: v5.2

#14298 5.2 to 5.3 merge
  src/Raven.Client/Http/ClusterTopology.cs
  src/Raven.Client/ServerWide/DatabaseTopology.cs
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/Indexes/Auto/AutoIndexDefinitionBaseServerSide.cs
  src/Raven.Server/Documents/Indexes/Auto/AutoMapIndexDefinition.cs
  src/Raven.Server/Documents/Indexes/MapReduce/Auto/AutoMapReduceIndexDefinition.cs
  src/Raven.Server/Documents/Replication/IncomingReplicationHandler.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/Rachis/Candidate.cs
  src/Raven.Server/Rachis/CandidateAmbassador.cs
  src/Raven.Server/Rachis/Remote/RemoteConnection.cs
  src/Sparrow.Server/LowMemory/MemoryInformation.cs
  src/Sparrow/Json/UnmanagedBuffersPool.cs
  src/Sparrow/LowMemory/LowMemoryNotification.cs
  test/FastTests/Server/Documents/Indexing/Auto/BasicAutoMapIndexing.cs
  test/FastTests/Server/Documents/Indexing/Auto/BasicAutoMapReduceIndexing.cs
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
  test/RachisTests/ElectionTests.cs
  test/SlowTests/Issues/RavenDB-18442.cs
  test/Tests.Infrastructure/RachisConsensusTestBase.cs
Labels: v5.3

#14299 RavenDB-18387 Sharding - Index Terms View - query fields from all nodes
  src/Raven.Studio/typescript/commands/database/index/getIndexEntriesFieldsCommand.ts
  src/Raven.Studio/typescript/common/autoComplete/remoteMetadataProvider.ts
  src/Raven.Studio/typescript/common/shell/menu/items/indexes.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexTerms.ts
Labels: v6.0

#14300 RavenDB-18649 Corax as Experimental feature only / Allowing to set search engine per index
  src/Raven.Client/Constants.cs
  src/Raven.Client/Documents/Indexes/AbstractIndexCreationTask.cs
  src/Raven.Server/Config/Categories/IndexingConfiguration.cs
  src/Raven.Server/Config/RavenConfiguration.cs
  src/Raven.Server/Documents/Handlers/Admin/AdminIndexHandler.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Utils/Features/Feature.cs
  src/Raven.Server/Utils/Features/FeatureGuardian.cs
  test/FastTests/Issues/RavenDB-11791.cs
  test/SlowTests/Corax/CanUseCoraxOnlyAsExperimental.cs
Labels: Corax, v5.4

#14306 RavenDB-18689 Sharding - indexes view - enhacements
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexDistribution.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexPanel.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexProgressTooltip.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexesPage.stories.tsx
  src/Raven.Studio/typescript/test/stubs/IndexesStubs.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/bulkIndexOperationConfirm.ts
  src/Raven.Studio/typescript/viewmodels/shell.ts
  src/Raven.Studio/wwwroot/App/views/database/indexes/bulkIndexOperationConfirm.html
  src/Raven.Studio/wwwroot/App/views/shell.html
Labels: v6.0

#14302 RavenDB-18659 : Timeseries stream could not parse start/end
  src/Raven.Client/Documents/Session/Operations/StreamOperation.cs
  test/SlowTests/Issues/RavenDB-18659.cs
Labels: v5.2
