Repository ravendb/ravendb, pull requests merged in 2022-09, with the labels that each got.

#14836 RavenDB-18384 - SlowTests.Client.TimeSeries.Query.QueryFromMultipleTi…
  test/SlowTests/Client/TimeSeries/Query/QueryFromMultipleTimeSeries.cs
Labels: v5.3

#14834 RavenDB-17195 Flood of Errors in Studio from DeleteByQuery
  src/Raven.Studio/typescript/common/notifications/models/virtualBulkInsertFailures.ts
  src/Raven.Studio/typescript/common/notifications/models/virtualDeleteByQueryFailures.ts
  src/Raven.Studio/typescript/common/notifications/models/virtualUpdateByQueryFailures.ts
  src/Raven.Studio/typescript/common/notifications/notificationCenter.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/abstractOperationDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/bulkInsertDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/deleteDocumentsDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/patchDocumentsDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/virtualOperations/virtualBulkInsertFailuresDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/virtualOperations/virtualDeleteByQueryFailuresDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/virtualOperations/virtualUpdateByQueryFailuresDetails.ts
  src/Raven.Studio/typings/_studio/dto.d.ts
  src/Raven.Studio/wwwroot/App/views/common/notificationCenter/detailViewer/virtualOperations/virtualBulkInsertFailuresDetails.html
  src/Raven.Studio/wwwroot/App/views/common/notificationCenter/detailViewer/virtualOperations/virtualDeleteByQueryFailuresDetails.html
  src/Raven.Studio/wwwroot/App/views/common/notificationCenter/detailViewer/virtualOperations/virtualUpdateByQueryFailuresDetails.html
  src/Raven.Studio/wwwroot/App/views/notifications/notificationCenter.html
Labels: v5.2

#14827 RavenDB-17951 : adjustments to flaky test
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
Labels: v5.2

#14816 RavenDB-18745 Fix Setup Wizard Certificate List
  src/Raven.Studio/wwwroot/App/views/wizard/certificate.html
  src/Raven.Studio/wwwroot/Content/css/styles-common.less
Labels: v5.2

#14815 RavenDB-19136 If the client certificate used to access is going to ex…
  src/Raven.Studio/typescript/models/auth/clientCertificateModel.ts
  src/Raven.Studio/typescript/viewmodels/shell.ts
  src/Raven.Studio/wwwroot/App/views/shell.html
Labels: v5.4

#14803 RavenDB-17083 Add indexes/performance endpoint to debug package
  src/Raven.Server/Documents/Handlers/IndexHandler.cs
Labels: v5.4

#14802 RavenDB-18935 - The test Sinks_should_not_update_hubs_change_vector2 …
  src/Raven.Client/ServerWide/DatabaseTopology.cs
Labels: v5.2

#14817 RavenDB-19260: Added test that allows us to check for unit of work behavior
  test/FastTests/Blittable/MutatingJsonTests.cs
Labels: v5.4

#14828 RavenDB-17980 Cleanup topology files for TestDriver
  src/Raven.TestDriver/RavenTestDriver.cs
  test/EmbeddedTests/TestDriver/TestDriverExampleTest.cs
  test/SlowTests/Issues/RavenDB-17980.cs
Labels: v5.4

#14844 5.2 to 5.3 merge
  .gitignore
  libs/librvnpal/librvnpal.arm.32.so
  libs/librvnpal/librvnpal.arm.64.so
  libs/librvnpal/librvnpal.linux.x64.so
  libs/librvnpal/librvnpal.mac.arm64.dylib
  libs/librvnpal/librvnpal.mac.x64.dylib
  libs/librvnpal/librvnpal.win.x64.dll
  libs/librvnpal/librvnpal.win.x86.dll
  libs/librvnpal/librvnpal.win7.x64.dll
  libs/librvnpal/librvnpal.win7.x86.dll
  src/Raven.Client/Documents/Linq/RavenQueryProvider.cs
  src/Raven.Client/Documents/Session/ClusterTransactionSession.cs
  src/Raven.Client/Documents/Session/InMemoryDocumentSessionOperations.cs
  src/Raven.Client/ServerWide/DatabaseTopology.cs
  src/Raven.Pal/README.txt
  src/Raven.Pal/Raven.Pal.vcxproj
  src/Raven.Pal/Raven.Pal.vcxproj.filters
  src/Raven.Pal/build-all-windows.bat
  src/Raven.Pal/build-libs/crossbuild.sh
  src/Raven.Pal/pal.ver
  src/Raven.Pal/src/posix/fileutils.c
  src/Raven.Pal/src/rvngetpalver.c
  src/Raven.Server/Documents/Handlers/IndexHandler.cs
  src/Raven.Server/Documents/Handlers/TimeSeriesHandler.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Studio/typescript/common/notifications/models/virtualBulkInsertFailures.ts
  src/Raven.Studio/typescript/common/notifications/models/virtualDeleteByQueryFailures.ts
  src/Raven.Studio/typescript/common/notifications/models/virtualUpdateByQueryFailures.ts
  src/Raven.Studio/typescript/common/notifications/notificationCenter.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/abstractOperationDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/bulkInsertDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/deleteDocumentsDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/patchDocumentsDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/virtualOperations/virtualBulkInsertFailuresDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/virtualOperations/virtualDeleteByQueryFailuresDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/virtualOperations/virtualUpdateByQueryFailuresDetails.ts
  src/Raven.Studio/typings/_studio/dto.d.ts
  src/Raven.Studio/wwwroot/App/views/common/notificationCenter/detailViewer/virtualOperations/virtualBulkInsertFailuresDetails.html
  src/Raven.Studio/wwwroot/App/views/common/notificationCenter/detailViewer/virtualOperations/virtualDeleteByQueryFailuresDetails.html
  src/Raven.Studio/wwwroot/App/views/common/notificationCenter/detailViewer/virtualOperations/virtualUpdateByQueryFailuresDetails.html
  src/Raven.Studio/wwwroot/App/views/notifications/notificationCenter.html
  src/Raven.Studio/wwwroot/App/views/wizard/certificate.html
  src/Raven.Studio/wwwroot/Content/css/styles-common.less
  src/Sparrow.Server/Platform/Pal.cs
  test/FastTests/Client/Subscriptions/SubscriptionsBasic.cs
  test/FastTests/Issues/RavenDB-12430.cs
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
  test/SlowTests/Client/Subscriptions/RavenDB-8831.cs
  test/SlowTests/Client/Subscriptions/RavenDB_3484.cs
  test/SlowTests/Client/Subscriptions/SubscriptionsBasic.cs
  test/SlowTests/Issues/RavenDB-17872.cs
  test/StressTests/Voron/Issues/RavenDB_19273.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v5.3

#14845 5.3 to 5.4 merge
  .gitignore
  libs/librvnpal/librvnpal.arm.32.so
  libs/librvnpal/librvnpal.arm.64.so
  libs/librvnpal/librvnpal.linux.x64.so
  libs/librvnpal/librvnpal.mac.arm64.dylib
  libs/librvnpal/librvnpal.mac.x64.dylib
  libs/librvnpal/librvnpal.win.x64.dll
  libs/librvnpal/librvnpal.win.x86.dll
  libs/librvnpal/librvnpal.win7.x64.dll
  libs/librvnpal/librvnpal.win7.x86.dll
  src/Raven.Client/Documents/Linq/RavenQueryProvider.cs
  src/Raven.Client/Documents/Session/ClusterTransactionSession.cs
  src/Raven.Client/Documents/Session/InMemoryDocumentSessionOperations.cs
  src/Raven.Client/ServerWide/DatabaseTopology.cs
  src/Raven.Pal/README.txt
  src/Raven.Pal/Raven.Pal.vcxproj
  src/Raven.Pal/Raven.Pal.vcxproj.filters
  src/Raven.Pal/build-all-windows.bat
  src/Raven.Pal/build-libs/crossbuild.sh
  src/Raven.Pal/pal.ver
  src/Raven.Pal/src/posix/fileutils.c
  src/Raven.Pal/src/rvngetpalver.c
  src/Raven.Server/Documents/Handlers/IndexHandler.cs
  src/Raven.Server/Documents/Handlers/TimeSeriesHandler.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Studio/typescript/common/notifications/models/virtualBulkInsertFailures.ts
  src/Raven.Studio/typescript/common/notifications/models/virtualDeleteByQueryFailures.ts
  src/Raven.Studio/typescript/common/notifications/models/virtualUpdateByQueryFailures.ts
  src/Raven.Studio/typescript/common/notifications/notificationCenter.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/abstractOperationDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/bulkInsertDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/deleteDocumentsDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/patchDocumentsDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/virtualOperations/virtualBulkInsertFailuresDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/virtualOperations/virtualDeleteByQueryFailuresDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/virtualOperations/virtualUpdateByQueryFailuresDetails.ts
  src/Raven.Studio/typings/_studio/dto.d.ts
  src/Raven.Studio/wwwroot/App/views/common/notificationCenter/detailViewer/virtualOperations/virtualBulkInsertFailuresDetails.html
  src/Raven.Studio/wwwroot/App/views/common/notificationCenter/detailViewer/virtualOperations/virtualDeleteByQueryFailuresDetails.html
  src/Raven.Studio/wwwroot/App/views/common/notificationCenter/detailViewer/virtualOperations/virtualUpdateByQueryFailuresDetails.html
  src/Raven.Studio/wwwroot/App/views/notifications/notificationCenter.html
  src/Raven.Studio/wwwroot/App/views/wizard/certificate.html
  src/Raven.Studio/wwwroot/Content/css/styles-common.less
  src/Sparrow.Server/Platform/Pal.cs
  test/FastTests/Client/Subscriptions/SubscriptionsBasic.cs
  test/FastTests/Issues/RavenDB-12430.cs
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
  test/SlowTests/Client/Subscriptions/RavenDB-8831.cs
  test/SlowTests/Client/Subscriptions/RavenDB_3484.cs
  test/SlowTests/Client/Subscriptions/SubscriptionsBasic.cs
  test/SlowTests/Client/TimeSeries/Query/QueryFromMultipleTimeSeries.cs
  test/SlowTests/Issues/RavenDB-17872.cs
  test/StressTests/Voron/Issues/RavenDB_19273.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v5.4

#14846 RavenDB-18980 Put disk metrics on Cluster Dashboard
  src/Raven.Server/Dashboard/Cluster/ClusterDashboardNotificationType.cs
  src/Raven.Server/Dashboard/Cluster/ClusterDashboardNotifications.cs
  src/Raven.Server/Dashboard/Cluster/Notifications/IoStatsNotificationSender.cs
  src/Raven.Server/Dashboard/Cluster/Notifications/IoStatsPayload.cs
  src/Raven.Server/Dashboard/DatabasesInfoRetriever.cs
  src/Raven.Server/NotificationCenter/Handlers/ClusterDashboardConnection.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Studio/typescript/models/resources/clusterDashboard/lineChart.ts
  src/Raven.Studio/typescript/models/resources/widgets/ioStats.ts
  src/Raven.Studio/typescript/viewmodels/resources/addWidgetModal.ts
  src/Raven.Studio/typescript/viewmodels/resources/clusterDashboard.ts
  src/Raven.Studio/typescript/viewmodels/resources/widgets/abstractChartsWebsocketWidget.ts
  src/Raven.Studio/typescript/viewmodels/resources/widgets/cpuUsageWidget.ts
  src/Raven.Studio/typescript/viewmodels/resources/widgets/indexingWidget.ts
  src/Raven.Studio/typescript/viewmodels/resources/widgets/ioStatsWidget.ts
  src/Raven.Studio/typescript/viewmodels/resources/widgets/memoryUsageWidget.ts
  src/Raven.Studio/typescript/viewmodels/resources/widgets/settings/ioStatsWidgetSettings.ts
  src/Raven.Studio/typescript/viewmodels/resources/widgets/trafficWidget.ts
  src/Raven.Studio/typings/_studio/dto.d.ts
  src/Raven.Studio/wwwroot/App/views/resources/widgets/ioStatsWidget.html
  src/Raven.Studio/wwwroot/App/views/resources/widgets/settings/ioStatsWidgetSettings.html
  src/Raven.Studio/wwwroot/Content/css/pages/cluster-dashboard.less
  tools/TypingsGenerator/Program.cs
Labels: v5.2

#14808 RavenDB-15427 Avoid cancelling compression on setup change
  src/Sparrow/Logging/LoggingSource.cs
Labels: v5.2

#14842 RavenDB-19207 Add aliases for lucene's config keys
  src/Raven.Server/Config/Categories/IndexingConfiguration.cs
  src/Raven.Studio/typescript/models/database/index/configurationItem.ts
  test/FastTests/Issues/RavenDB_16590.cs
Labels: v5.4

#14857 RavenDB-19282 Enable the following experimental features is displayed…
  src/Raven.Studio/wwwroot/App/views/wizard/security.html
  src/Raven.Studio/wwwroot/App/views/wizard/welcome.html
Labels: v5.3

#14855 RavenDB-19283 Corax - ArgumentOutOfRangeException during indexing
  test/FastTests/Corax/Bugs/RavenDB-19283.cs
Labels: Corax, v5.4

#14868 RavenDB-19136 If the client certificate used to access is going to ex…
  src/Raven.Studio/typescript/models/auth/clientCertificateModel.ts
  src/Raven.Studio/typescript/viewmodels/shell.ts
Labels: v5.4

#14867 RavenDB-19284 IO stats widget - allocate height
  src/Raven.Studio/typescript/models/resources/widgets/ioStats.ts
  src/Raven.Studio/wwwroot/App/views/resources/widgets/ioStatsWidget.html
Labels: v5.4

#14861 Adding passing test for querying on BigInteger using Linq query provi…
  test/SlowTests/MailingList/BigIntegerUsage.cs
Labels: v5.4

#14801 RavenDB-17157 Capability to customize all sessions to invoke WaitForReplicationAfterSaveChanges and WaitForIndexesAfterSaveChanges internally
  test/SlowTests/Issues/RavenDB-17157.cs
Labels: v5.4

#14870 RavenDB-19294 remove the disable.markers after test finishes
  test/SlowTests/Issues/RavenDB-19109.cs
Labels: v5.2

#14871 5.2 to 5.3 merge
  src/Raven.Studio/typescript/models/resources/widgets/ioStats.ts
  src/Raven.Studio/wwwroot/App/views/resources/widgets/ioStatsWidget.html
  test/SlowTests/Issues/RavenDB-19109.cs
Labels: v5.3

#14874 5.3 to 5.4 merge
  src/Raven.Studio/typescript/models/resources/widgets/ioStats.ts
  src/Raven.Studio/wwwroot/App/views/resources/widgets/ioStatsWidget.html
  src/Raven.Studio/wwwroot/App/views/wizard/security.html
  src/Raven.Studio/wwwroot/App/views/wizard/welcome.html
  test/SlowTests/Issues/RavenDB-19109.cs
Labels: v5.4

#14872 RavenDB-17942 Add server-settings icon
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon/database-settings.svg
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon/server-settings.svg
Labels: v5.3

#14873 RavenDB-19299: Buffer was been doubled instead of considering the actual data size.
  src/Corax/IndexEntry/IndexEntryWriter.cs
Labels: v5.4

#14880 RavenDB-19309: Wrong calculation of extra required space would cause invalid entries.
  src/Corax/IndexEntry/IndexEntryWriter.cs
Labels: v5.4

#14881 RavenDB-19313 - fix the error message, the Value is already disposed at this point
  src/Raven.Server/Smuggler/Documents/DatabaseSmuggler.cs
Labels: v5.2

#14878 RavenDB-19274 Add avg response size to Traffic Watch stats
  src/Raven.Studio/typescript/viewmodels/manage/trafficWatch.ts
  src/Raven.Studio/wwwroot/App/views/manage/trafficWatch.html
  src/Raven.Studio/wwwroot/Content/css/pages/traffic-watch.less
Labels: v5.2

#14782 RavenDB-19015: Replay traffic watch tool for queries
  tools/Raven.Debug/CommandLineApp.cs
  tools/Raven.Debug/LogTrafficWatch/TrafficWatchReplay.cs
Labels: v5.2

#14885 RavenDB-19310 Low level Voron tests might randomly fail because of CompressionAccelerationStats.LastAcceleration
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/StorageEnvironmentOptions.cs
  test/FastTests/Voron/StorageTest.cs
Labels: v5.2

#14891 RavenDB-19294 we need to use separate server, because in this case we can fail any test that is being executed at the same time
  test/SlowTests/Issues/RavenDB-19109.cs
Labels: v5.2

#14893 RavenDB-18285 Sharding - Ongoing Tasks Stats View
  src/Raven.Studio/typescript/common/liveEtlStatsWebSocketClient.ts
  src/Raven.Studio/typescript/common/liveReplicationStatsWebSocketClient.ts
  src/Raven.Studio/typescript/common/liveSubscriptionStatsWebSocketClient.ts
  src/Raven.Studio/typescript/viewmodels/database/status/ongoingTasksStats.ts
Labels: v6.0

#14892 RavenDB-19270 Fix storage key prefix
  src/Raven.Studio/typescript/common/storage/storageKeyProvider.ts
  src/Raven.Studio/webpack.config.js
  src/Raven.Studio/wwwroot/version.txt
Labels: v5.4

#14858 RavenDB-19076 Different results when using the `Filter` keyword
  src/Raven.Studio/typescript/viewmodels/database/query/query.ts
Labels: v5.3

#14894 5.2 to 5.3 merge
  src/Raven.Client/Json/Serialization/JsonDeserializationClient.cs
  src/Raven.Client/ServerWide/Operations/TrafficWatch/GetTrafficWatchConfigurationOperation.cs
  src/Raven.Client/ServerWide/Operations/TrafficWatch/PutTrafficWatchConfigurationOperation.cs
  src/Raven.Server/Config/Categories/ConfigurationCategory.cs
  src/Raven.Server/Config/Categories/ConfigurationCategoryType.cs
  src/Raven.Server/Config/Categories/TrafficWatchConfiguration.cs
  src/Raven.Server/Config/RavenConfiguration.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/IndexStorage.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  src/Raven.Server/Documents/Indexes/Workers/HandleReferences.cs
  src/Raven.Server/Json/JsonDeserializationServer.cs
  src/Raven.Server/Program.cs
  src/Raven.Server/Smuggler/Documents/DatabaseSmuggler.cs
  src/Raven.Server/TrafficWatch/TrafficWatchHandler.cs
  src/Raven.Server/TrafficWatch/TrafficWatchManager.cs
  src/Raven.Server/TrafficWatch/TrafficWatchToLog.cs
  src/Raven.Studio/typescript/viewmodels/manage/trafficWatch.ts
  src/Raven.Studio/wwwroot/App/views/manage/trafficWatch.html
  src/Raven.Studio/wwwroot/Content/css/pages/traffic-watch.less
  src/Sparrow/Json/JsonDeserializationBase.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/StorageEnvironmentOptions.cs
  test/FastTests/Client/RavenCommandTest.cs
  test/FastTests/Server/TrafficWatchConfigurationTests.cs
  test/FastTests/Voron/StorageTest.cs
  test/SlowTests/Issues/RavenDB-19016.cs
  test/SlowTests/Issues/RavenDB-19109.cs
  tools/Raven.Debug/CommandLineApp.cs
  tools/Raven.Debug/LogTrafficWatch/TrafficWatchReplay.cs
Labels: v5.3

#14895 5.3 to 5.4 merge
  src/Raven.Client/Json/Serialization/JsonDeserializationClient.cs
  src/Raven.Client/ServerWide/Operations/TrafficWatch/GetTrafficWatchConfigurationOperation.cs
  src/Raven.Client/ServerWide/Operations/TrafficWatch/PutTrafficWatchConfigurationOperation.cs
  src/Raven.Server/Config/Categories/ConfigurationCategory.cs
  src/Raven.Server/Config/Categories/ConfigurationCategoryType.cs
  src/Raven.Server/Config/Categories/TrafficWatchConfiguration.cs
  src/Raven.Server/Config/RavenConfiguration.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/IndexStorage.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  src/Raven.Server/Documents/Indexes/Workers/HandleReferences.cs
  src/Raven.Server/Json/JsonDeserializationServer.cs
  src/Raven.Server/Program.cs
  src/Raven.Server/Smuggler/Documents/DatabaseSmuggler.cs
  src/Raven.Server/TrafficWatch/TrafficWatchHandler.cs
  src/Raven.Server/TrafficWatch/TrafficWatchManager.cs
  src/Raven.Server/TrafficWatch/TrafficWatchToLog.cs
  src/Raven.Studio/typescript/viewmodels/database/query/query.ts
  src/Raven.Studio/typescript/viewmodels/manage/trafficWatch.ts
  src/Raven.Studio/wwwroot/App/views/manage/trafficWatch.html
  src/Raven.Studio/wwwroot/Content/css/pages/traffic-watch.less
  src/Sparrow/Json/JsonDeserializationBase.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/StorageEnvironmentOptions.cs
  test/FastTests/Client/RavenCommandTest.cs
  test/FastTests/Server/TrafficWatchConfigurationTests.cs
  test/FastTests/Voron/StorageTest.cs
  test/SlowTests/Issues/RavenDB-19016.cs
  test/SlowTests/Issues/RavenDB-19109.cs
  tools/Raven.Debug/CommandLineApp.cs
  tools/Raven.Debug/LogTrafficWatch/TrafficWatchReplay.cs
Labels: v5.4

#14899 RavenDB-19327 spurious calls in collection tracker
  src/Raven.Studio/typescript/common/helpers/database/collectionsTracker.ts
  src/Raven.Studio/typescript/models/database/documents/collection.ts
Labels: v5.2

#14907 RavenDB-19311 Import Data From SQL View: Add a sample connection stri…
  src/Raven.Studio/typescript/viewmodels/database/tasks/importDatabaseFromSql.ts
  src/Raven.Studio/wwwroot/App/views/database/tasks/importDatabaseFromSql.html
Labels: v5.4

#14875 RavenDB-19287 Rename 'Document Preview' to 'Index Entry Preview'
  src/Raven.Studio/typescript/widgets/virtualGrid/columns/providers/documentBasedColumnsProvider.ts
Labels: v5.2

#14905 RavenDB-19314 Remove backslash validation from document id
  src/Raven.Studio/typescript/viewmodels/database/documents/editDocument.ts
Labels: v5.2

#14913 RavenDB-19258 Making sure that an error in reading index error count won't mark a whole database as errored
  src/Raven.Server/Documents/Indexes/Index.cs
Labels: v5.2

#14910 RavenDB-7070 Reduce the time we wait for Kafka server availability detection
  test/Tests.Infrastructure/ConnectionString/KafkaConnectionString.cs
Labels: v5.4

#14912 RavenDB-19084 Use a single rewrite method in order to avoid cloning the query twice
  src/Raven.Server/Documents/Sharding/Queries/AbstractShardedQueryProcessor.cs
Labels: v6.0

#14916 5.2 to 5.3 merge
  src/Raven.Server/Config/Categories/IndexingConfiguration.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Studio/typescript/viewmodels/database/documents/editDocument.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/importDatabaseFromSql.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/columns/providers/documentBasedColumnsProvider.ts
  src/Raven.Studio/wwwroot/App/views/database/tasks/importDatabaseFromSql.html
  src/Voron/Impl/Journal/JournalReader.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/StorageEnvironmentOptions.cs
  test/SlowTests/Voron/Issues/RavenDB_19278.cs
  test/SlowTests/Voron/RavenDB_13940.cs
Labels: v5.3

#14917 5.3 to 5.4 merge
  src/Raven.Server/Config/Categories/IndexingConfiguration.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Studio/typescript/viewmodels/database/documents/editDocument.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/importDatabaseFromSql.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/columns/providers/documentBasedColumnsProvider.ts
  src/Raven.Studio/wwwroot/App/views/database/tasks/importDatabaseFromSql.html
  src/Voron/Impl/Journal/JournalReader.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/StorageEnvironmentOptions.cs
  test/SlowTests/Voron/Issues/RavenDB_19278.cs
  test/SlowTests/Voron/RavenDB_13940.cs
Labels: v5.4

#14918 RavenDB-19346 / RavenDB-19278 When trying to read a transaction heade…
  src/Voron/Impl/Journal/JournalReader.cs
Labels: v5.2

#14919 5.2 to 5.3 merge
  src/Voron/Impl/Journal/JournalReader.cs
Labels: v5.3

#14921 5.3 to 5.4 merge
  src/Voron/Impl/Journal/JournalReader.cs
Labels: v5.4

#14909 RavenDB-17530 Regex support inside Corax
  src/Corax/IndexSearcher/MultiTermMatches/IndexSearcher.MultiTermMatch.Simple.cs
  src/Corax/Queries/TermProviders/TermProvider.Regex.cs
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxQueryBuilder.cs
  test/FastTests/Client/Queries/RegexQueryTests.cs
Labels: v5.4

#14929 RavenDB-19352 Removing unnecessary allocation in CoraxIndexWriteOperation
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxIndexWriteOperation.cs
Labels: v5.4

#14927 RavenDB-19107 Traffic watch log to a separate file
  src/Raven.Studio/typescript/commands/maintenance/getTrafficWatchConfigurationCommand.ts
  src/Raven.Studio/typescript/commands/maintenance/saveTrafficWatchConfigurationCommand.ts
  src/Raven.Studio/typescript/common/extensions.ts
  src/Raven.Studio/typescript/models/resources/trafficWatchConfiguration.ts
  src/Raven.Studio/typescript/viewmodels/manage/adminLogs.ts
  src/Raven.Studio/typescript/viewmodels/manage/adminLogsTrafficWatchDialog.ts
  src/Raven.Studio/typescript/viewmodels/manage/trafficWatch.ts
  src/Raven.Studio/wwwroot/App/views/manage/adminLogs.html
  src/Raven.Studio/wwwroot/App/views/manage/adminLogsTrafficWatchDialog.html
  src/Raven.Studio/wwwroot/App/views/manage/trafficWatch.html
  src/Raven.Studio/wwwroot/Content/css/pages/traffic-watch.less
  tools/TypingsGenerator/Program.cs
Labels: v5.2

#14923 RavenDB-5055 IndexMerger fixes.
  src/Raven.Server/Documents/Indexes/IndexMerging/IndexData.cs
  src/Raven.Server/Documents/Indexes/IndexMerging/IndexMerger.cs
  src/Raven.Server/Documents/Indexes/IndexMerging/IndexVisitor.cs
  test/SlowTests/Server/Documents/Indexing/IndexMerging.cs
Labels: v5.2

#14920 RavenDB-19218 Taking into account that we sometimes we mix regular en…
  src/Voron/Data/BTrees/Tree.cs
Labels: v5.2

#14914 RavenDB-19344: handle timeout, network exceptions when they are wrapped by RavenException
  src/Raven.Client/Documents/Subscriptions/SubscriptionWorker.cs
  test/SlowTests/Client/Subscriptions/SubscriptionsBasic.cs
Labels: v5.2

#14932 RavenDB-18636 Ensure that index thread exists (test fix)
  test/SlowTests/Issues/RavenDB-15890.cs
Labels: v5.2

#14931 RavenDB-18257 Handling of Not Modified status code when dealing with sharded queries.
  src/Raven.Client/Documents/Commands/QueryCommand.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/LuceneIndexReadOperation.Sharding.cs
  src/Raven.Server/Documents/Sharding/Commands/ShardedQueryCommand.cs
  src/Raven.Server/Documents/Sharding/Operations/IShardedReadOperation.cs
  src/Raven.Server/Documents/Sharding/Operations/ShardedQueryOperation.cs
  src/Raven.Server/Documents/Sharding/Queries/ShardedQueryProcessor.cs
  test/FastTests/Server/Documents/Queries/NotModifiedQueryResults.cs
  test/SlowTests/Sharding/Queries/RavenDB_18257.cs
Labels: v6.0

#14934 RavenDB-17122 Retrying Simple_Bulk_Insert_With_Ssl() test
  test/SlowTests/Client/BulkInserts.cs
Labels: v5.2

#14935 RavenDB-19295 fixing test
  test/SlowTests/Issues/RavenDB-17980.cs
Labels: v5.4

#14933 5.2 to 5.3 merge
  src/Raven.Client/Documents/Commands/GetNextServerOperationIdCommand.cs
  src/Raven.Client/Documents/Commands/KillServerOperationCommand.cs
  src/Raven.Client/Documents/Subscriptions/SubscriptionWorker.cs
  src/Raven.Server/Documents/Handlers/Debugging/ServerWideDebugInfoPackageHandler.cs
  src/Raven.Server/Documents/Indexes/IndexMerging/IndexData.cs
  src/Raven.Server/Documents/Indexes/IndexMerging/IndexMerger.cs
  src/Raven.Server/Documents/Indexes/IndexMerging/IndexVisitor.cs
  src/Raven.Server/ServerWide/DebugInfoPackageUtils.cs
  src/Raven.Server/Web/Operations/OperationsServerHandler.cs
  src/Raven.Studio/typescript/commands/maintenance/getTrafficWatchConfigurationCommand.ts
  src/Raven.Studio/typescript/commands/maintenance/saveTrafficWatchConfigurationCommand.ts
  src/Raven.Studio/typescript/common/extensions.ts
  src/Raven.Studio/typescript/models/resources/trafficWatchConfiguration.ts
  src/Raven.Studio/typescript/viewmodels/manage/adminLogs.ts
  src/Raven.Studio/typescript/viewmodels/manage/adminLogsTrafficWatchDialog.ts
  src/Raven.Studio/typescript/viewmodels/manage/trafficWatch.ts
  src/Raven.Studio/wwwroot/App/views/manage/adminLogs.html
  src/Raven.Studio/wwwroot/App/views/manage/adminLogsTrafficWatchDialog.html
  src/Raven.Studio/wwwroot/App/views/manage/trafficWatch.html
  src/Raven.Studio/wwwroot/Content/css/pages/traffic-watch.less
  src/Voron/Data/BTrees/Tree.cs
  test/FastTests/Client/RavenCommandTest.cs
  test/RachisTests/AddNodeToClusterTests.cs
  test/SlowTests/Client/BulkInserts.cs
  test/SlowTests/Client/Subscriptions/SubscriptionsBasic.cs
  test/SlowTests/Issues/RavenDB-15890.cs
  test/SlowTests/Server/Documents/Indexing/IndexMerging.cs
  tools/TypingsGenerator/Program.cs
Labels: v5.3

#14938 RavenDB-19360 observer is set in the background task, so we need to wait for it before setting the value to avoid NRE
  test/FastTests/Client/Subscriptions/SubscriptionsBasic.cs
  test/RachisTests/DatabaseCluster/ReplicationTests.cs
  test/SlowTests/Client/Subscriptions/RavenDB-8831.cs
  test/SlowTests/Client/Subscriptions/RavenDB_3484.cs
  test/SlowTests/Client/Subscriptions/SubscriptionsBasic.cs
  test/SlowTests/Cluster/ClusterTransactionTests.cs
  test/SlowTests/Issues/RavenDB-18554.cs
  test/SlowTests/Server/Replication/ReplicationWriteAssurance.cs
  test/Tests.Infrastructure/RavenTestBase.Cluster.cs
Labels: v5.2

#14937 5.3 to 5.4 merge
  src/Raven.Client/Documents/Commands/GetNextServerOperationIdCommand.cs
  src/Raven.Client/Documents/Commands/KillServerOperationCommand.cs
  src/Raven.Client/Documents/Subscriptions/SubscriptionWorker.cs
  src/Raven.Server/Documents/Handlers/Debugging/ServerWideDebugInfoPackageHandler.cs
  src/Raven.Server/Documents/Indexes/IndexMerging/IndexData.cs
  src/Raven.Server/Documents/Indexes/IndexMerging/IndexMerger.cs
  src/Raven.Server/Documents/Indexes/IndexMerging/IndexVisitor.cs
  src/Raven.Server/ServerWide/DebugInfoPackageUtils.cs
  src/Raven.Server/Web/Operations/OperationsServerHandler.cs
  src/Raven.Studio/typescript/commands/maintenance/getTrafficWatchConfigurationCommand.ts
  src/Raven.Studio/typescript/commands/maintenance/saveTrafficWatchConfigurationCommand.ts
  src/Raven.Studio/typescript/common/extensions.ts
  src/Raven.Studio/typescript/models/resources/trafficWatchConfiguration.ts
  src/Raven.Studio/typescript/viewmodels/manage/adminLogs.ts
  src/Raven.Studio/typescript/viewmodels/manage/adminLogsTrafficWatchDialog.ts
  src/Raven.Studio/typescript/viewmodels/manage/trafficWatch.ts
  src/Raven.Studio/wwwroot/App/views/manage/adminLogs.html
  src/Raven.Studio/wwwroot/App/views/manage/adminLogsTrafficWatchDialog.html
  src/Raven.Studio/wwwroot/App/views/manage/trafficWatch.html
  src/Raven.Studio/wwwroot/Content/css/pages/traffic-watch.less
  src/Voron/Data/BTrees/Tree.cs
  test/FastTests/Client/RavenCommandTest.cs
  test/RachisTests/AddNodeToClusterTests.cs
  test/SlowTests/Client/BulkInserts.cs
  test/SlowTests/Client/Subscriptions/SubscriptionsBasic.cs
  test/SlowTests/Issues/RavenDB-15890.cs
  test/SlowTests/Server/Documents/Indexing/IndexMerging.cs
  tools/TypingsGenerator/Program.cs
Labels: v5.4

#14939 RavenDB-19122 Fixing occasionally failing test. The suspicion is that…
  test/SlowTests/Issues/RavenDB_16193.cs
Labels: v5.2

#14951 5.2 to 5.3 merge
  .github/workflows/FastTests.yml
  .github/workflows/FastTestsARM.yml
  bench/BulkInsert.Benchmark/BulkInsert.Benchmark.csproj
  bench/Indexing.Benchmark/Indexing.Benchmark.csproj
  bench/Micro.Benchmark/Micro.Benchmark.csproj
  bench/Regression.Benchmark/Regression.Benchmark.csproj
  bench/SubscriptionFailover.Benchmark/SubscriptionFailover.Benchmark.csproj
  bench/Subscriptions.Benchmark/Subscriptions.Benchmark.csproj
  bench/TimeSeries.Benchmark/TimeSeries.Benchmark.csproj
  bench/Voron.Benchmark/Voron.Benchmark.csproj
  src/Raven.Client/Raven.Client.csproj
  src/Raven.Embedded/ServerOptions.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Studio/Raven.Studio.csproj
  src/Sparrow.Server/Sparrow.Server.csproj
  src/Voron/Voron.csproj
  test/BenchmarkTests/BenchmarkTests.csproj
  test/EmbeddedTests/EmbeddedTests.csproj
  test/FastTests/Client/Subscriptions/SubscriptionsBasic.cs
  test/FastTests/FastTests.csproj
  test/InterversionTests/InterversionTests.csproj
  test/LicenseTests/LicenseTests.csproj
  test/RachisTests/DatabaseCluster/ReplicationTests.cs
  test/RachisTests/RachisTests.csproj
  test/SlowTests/Client/Subscriptions/RavenDB-8831.cs
  test/SlowTests/Client/Subscriptions/RavenDB_3484.cs
  test/SlowTests/Client/Subscriptions/SubscriptionsBasic.cs
  test/SlowTests/Cluster/ClusterTransactionTests.cs
  test/SlowTests/Issues/RavenDB-18554.cs
  test/SlowTests/Issues/RavenDB_16193.cs
  test/SlowTests/Server/Replication/ReplicationWriteAssurance.cs
  test/SlowTests/SlowTests.csproj
  test/StressTests/StressTests.csproj
  test/Tests.Infrastructure/RavenTestBase.Cluster.cs
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
  test/Tryouts/Tryouts.csproj
  tools/Raven.Debug/Raven.Debug.csproj
  tools/Raven.Migrator/Raven.Migrator.csproj
  tools/TypingsGenerator/TypingsGenerator.csproj
  tools/Voron.Recovery/Voron.Recovery.csproj
  tools/rvn/rvn.csproj
Labels: v5.3

#14953 5.3 to 5.4 merge
  .github/workflows/FastTests.yml
  .github/workflows/FastTestsARM.yml
  bench/BulkInsert.Benchmark/BulkInsert.Benchmark.csproj
  bench/Indexing.Benchmark/Indexing.Benchmark.csproj
  bench/Micro.Benchmark/Micro.Benchmark.csproj
  bench/Regression.Benchmark/Regression.Benchmark.csproj
  bench/SubscriptionFailover.Benchmark/SubscriptionFailover.Benchmark.csproj
  bench/Subscriptions.Benchmark/Subscriptions.Benchmark.csproj
  bench/TimeSeries.Benchmark/TimeSeries.Benchmark.csproj
  bench/Voron.Benchmark/Voron.Benchmark.csproj
  src/Raven.Client/Raven.Client.csproj
  src/Raven.Embedded/ServerOptions.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Studio/Raven.Studio.csproj
  src/Sparrow.Server/Sparrow.Server.csproj
  src/Voron/Voron.csproj
  test/BenchmarkTests/BenchmarkTests.csproj
  test/EmbeddedTests/EmbeddedTests.csproj
  test/FastTests/Client/Subscriptions/SubscriptionsBasic.cs
  test/FastTests/FastTests.csproj
  test/InterversionTests/InterversionTests.csproj
  test/LicenseTests/LicenseTests.csproj
  test/RachisTests/DatabaseCluster/ReplicationTests.cs
  test/RachisTests/RachisTests.csproj
  test/SlowTests/Client/Subscriptions/RavenDB-8831.cs
  test/SlowTests/Client/Subscriptions/RavenDB_3484.cs
  test/SlowTests/Client/Subscriptions/SubscriptionsBasic.cs
  test/SlowTests/Cluster/ClusterTransactionTests.cs
  test/SlowTests/Issues/RavenDB-18554.cs
  test/SlowTests/Issues/RavenDB_16193.cs
  test/SlowTests/Server/Replication/ReplicationWriteAssurance.cs
  test/SlowTests/SlowTests.csproj
  test/StressTests/StressTests.csproj
  test/Tests.Infrastructure/RavenTestBase.Cluster.cs
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
  test/Tryouts/Tryouts.csproj
  tools/Raven.Debug/Raven.Debug.csproj
  tools/Raven.Migrator/Raven.Migrator.csproj
  tools/TypingsGenerator/TypingsGenerator.csproj
  tools/Voron.Recovery/Voron.Recovery.csproj
  tools/rvn/rvn.csproj
Labels: v5.4

#14952 RavenDB-19367 we cannot use the static instance of the LowMemoryNotification because it is not designed to be used concurrently (inactiveHandler is a List)
  src/Sparrow/LowMemory/LowMemoryNotification.cs
  test/FastTests/Issues/RavenDB_10732.cs
Labels: v5.2

#14945 RavenDB-18257 Fixing typo
  src/Raven.Server/Documents/Sharding/Operations/IShardedReadOperation.cs
Labels: v6.0

#14959 fixed tests after merge
  src/Raven.Studio/scripts/setup_jest.js
  src/Raven.Studio/typescript/common/storage/__mocks__/storageKeyProvider.ts
Labels: v6.0

#14968 RavenDB-17872 - Get and update compare exchange metadata in the session.
  src/Raven.Client/Documents/Session/ClusterTransactionSession.cs
Labels: v5.2

#14963 RavenDB-19169 - SlowTests.Issues.RavenDB_18554.QueriesShouldFailoverIfIndexIsCompactingCluster fails.
  test/SlowTests/Issues/RavenDB-18554.cs
  test/Tests.Infrastructure/RavenTestBase.Cluster.cs
Labels: v5.2

#14958 RavenDB-19265 Auto index page on light color scheme
  src/Raven.Studio/wwwroot/Content/css/pages/edit-index.less
Labels: v5.2

#14957 RavenDB-18788 Reducing timeout for MREs used in the test. If we fail to dispose the database from the test then let's print that to the console
  test/RachisTests/RavenDB_18013.cs
Labels: v5.2

#14947 RavenDB-19327 spurious calls in collection tracker
  src/Raven.Studio/wwwroot/App/views/database/documents/documents.html
  src/Raven.Studio/wwwroot/App/views/database/documents/revisionsBin.html
  src/Raven.Studio/wwwroot/App/views/database/indexes/indexErrors.html
  src/Raven.Studio/wwwroot/App/views/database/query/query.html
  src/Raven.Studio/wwwroot/App/views/manage/adminLogs.html
  src/Raven.Studio/wwwroot/App/views/manage/debugAdvancedObserverLog.html
  src/Raven.Studio/wwwroot/App/views/manage/trafficWatch.html
Labels: v5.4

#14960 RavenDB-7070 add convenience script for resetting cert replacement st…
  scripts/certificates/bash/reset-replacement-status.sh
Labels: v5.2

#14973 RavenDB-18909 manually handling RavenEtlTestScriptResult conversion to DJV like in previous versions
  src/Raven.Server/Documents/ETL/Providers/Raven/Handlers/Processors/AbstractEtlHandlerProcessorForTest.cs
  src/Raven.Server/Documents/ETL/Providers/Raven/Test/RavenEtlTestScriptResult.cs
  src/Raven.Server/Documents/ETL/Test/TestEtlScriptResult.cs
Labels: v6.0

#14971 RavenDB-19364 [Corax test] Assert on filtered buffer.
  test/FastTests/Corax/IndexSearcher.cs
Labels: v5.4

#14978 RavenDB-19282 Enable the following experimental features is displayed…
  src/Raven.Studio/wwwroot/App/views/wizard/security.html
Labels: v6.0

#14981 RavenDB-16926 - Fix SlowTests.Issues.RavenDB_15900.RemoveEntryFromRaftLogTest
  src/Raven.Server/ServerWide/ClusterCommandsVersionManager.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  test/SlowTests/Issues/RavenDB-15900.cs
Labels: v5.2

#14980 RavenDB-19329 Cluster Dashboard: internal ips on cluster overview
  src/Raven.Server/Dashboard/Cluster/Notifications/ClusterOverviewNotificationSender.cs
Labels: v5.4

#14983 RavenDB-19225 Limit the number of HttpClient instances recreation during error handling. Do not recreate more often that once per 5 seconds
  src/Raven.Client/Http/RequestExecutor.cs
  test/SlowTests/Issues/EncryptedDatabaseGroup.cs
Labels: v5.2

#14982 RavenDB-19223 Admin endpoint allowing to clear the pool of HttpClient instances
  src/Raven.Client/Http/RequestExecutor.cs
  src/Raven.Server/Documents/Handlers/Debugging/NodeDebugHandler.cs
Labels: v5.2

#14986 5.2 to 5.3 merge
  scripts/certificates/bash/reset-replacement-status.sh
  src/Raven.Client/Documents/Session/ClusterTransactionSession.cs
  src/Raven.Client/Http/RequestExecutor.cs
  src/Raven.Server/Config/Categories/DatabaseConfiguration.cs
  src/Raven.Server/Documents/Handlers/Debugging/NodeDebugHandler.cs
  src/Raven.Server/ServerWide/ClusterCommandsVersionManager.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Studio/wwwroot/App/views/database/documents/documents.html
  src/Raven.Studio/wwwroot/App/views/database/documents/revisionsBin.html
  src/Raven.Studio/wwwroot/App/views/database/indexes/indexErrors.html
  src/Raven.Studio/wwwroot/App/views/database/query/query.html
  src/Raven.Studio/wwwroot/App/views/manage/adminLogs.html
  src/Raven.Studio/wwwroot/App/views/manage/debugAdvancedObserverLog.html
  src/Raven.Studio/wwwroot/App/views/manage/trafficWatch.html
  src/Raven.Studio/wwwroot/Content/css/pages/edit-index.less
  src/Sparrow/LowMemory/LowMemoryNotification.cs
  test/FastTests/Issues/RavenDB_10732.cs
  test/RachisTests/RavenDB_18013.cs
  test/SlowTests/Issues/EncryptedDatabaseGroup.cs
  test/SlowTests/Issues/RavenDB-15900.cs
  test/SlowTests/Issues/RavenDB-18554.cs
  test/Tests.Infrastructure/RavenTestBase.Cluster.cs
Labels: v5.3

#14991 5.3 to 5.4 merge
  scripts/certificates/bash/reset-replacement-status.sh
  src/Raven.Client/Documents/Session/ClusterTransactionSession.cs
  src/Raven.Client/Http/RequestExecutor.cs
  src/Raven.Server/Config/Categories/DatabaseConfiguration.cs
  src/Raven.Server/Documents/Handlers/Debugging/NodeDebugHandler.cs
  src/Raven.Server/ServerWide/ClusterCommandsVersionManager.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Studio/wwwroot/App/views/database/documents/documents.html
  src/Raven.Studio/wwwroot/App/views/database/documents/revisionsBin.html
  src/Raven.Studio/wwwroot/App/views/database/indexes/indexErrors.html
  src/Raven.Studio/wwwroot/App/views/database/query/query.html
  src/Raven.Studio/wwwroot/App/views/manage/adminLogs.html
  src/Raven.Studio/wwwroot/App/views/manage/debugAdvancedObserverLog.html
  src/Raven.Studio/wwwroot/App/views/manage/trafficWatch.html
  src/Raven.Studio/wwwroot/Content/css/pages/edit-index.less
  src/Sparrow/LowMemory/LowMemoryNotification.cs
  test/FastTests/Issues/RavenDB_10732.cs
  test/RachisTests/RavenDB_18013.cs
  test/SlowTests/Issues/EncryptedDatabaseGroup.cs
  test/SlowTests/Issues/RavenDB-15900.cs
  test/SlowTests/Issues/RavenDB-18554.cs
  test/Tests.Infrastructure/RavenTestBase.Cluster.cs
Labels: v5.4

#14987 RavenDB-18788 Added debug details for investigation purposes
  test/RachisTests/RavenDB_18013.cs
Labels: v5.2

#14969 RavenDB-19317 Lowercase the term when performing TermMatch on FullTextSearch field.
  src/Corax/Analyzers/Analyzer.cs
  src/Corax/IndexSearcher/IndexSearcher.TermMatch.cs
  src/Corax/IndexSearcher/IndexSearcher.cs
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxBooleanQuery.cs
  test/SlowTests/Issues/RavenDB-19317.cs
Labels: Corax, v5.4

#14998 RavenDB-19317 Fixing compilation after merge
  src/Raven.Server/Documents/Queries/MoreLikeThis/Corax/MoreLikeThis.cs
Labels: Corax, v5.4

#14984 RavenDB-17721 - Fix CanPreformSeveralClusterTransactions test failure
  test/SlowTests/Cluster/ClusterTransactionTests.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
Labels: v5.2

#14993 RavenDB-19350 CSV export when using javascript projections throws an …
  src/Raven.Server/Documents/Queries/Results/QueryResultRetrieverBase.cs
  test/SlowTests/Issues/RavenDB-19350.cs
Labels: v5.4

#14999 RavenDB-7070 Turn off Corax complex tests for MoreLikeThis.
  test/SlowTests/Client/MoreLikeThis/MoreLikeThisTests.cs
  test/SlowTests/Issues/RavenDB-11089.cs
Labels: Corax, v5.4

#15001 RavenDB-19338 Remove hardcoded version from studio
  src/Raven.Studio/typescript/common/storage/storageKeyProvider.ts
  src/Raven.Studio/typescript/common/versionProvider.ts
  src/Raven.Studio/typescript/viewmodels/wizard/secureInstructions.ts
  src/Raven.Studio/wwwroot/App/views/wizard/secureInstructions.html
Labels: v5.4

#15019 RavenDB-14282 support for timings in facet queries
  src/Raven.Server/Documents/Handlers/QueriesHandler.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/IndexFacetedReadOperation.cs
  src/Raven.Server/Documents/Queries/QueryRunner.cs
  src/Raven.Server/Documents/Queries/Timings/QueryTimingsScope.cs
Labels: v5.4

#15017 RavenDB-19019 added OlapEtl to DisableOngoingTasksIfNeeded
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreBackupTaskBase.cs
  test/SlowTests/Smuggler/BackupDatabaseRecordTests.cs
Labels: v5.2

#15009 RavenDB-19378 Removed the incorrect validation
  src/Raven.Studio/typescript/models/wizard/nodeInfo.ts
Labels: v5.2

#15018 RavenDB-17453 disable topology cache for embedded
  src/Raven.Embedded/EmbeddedServer.cs
  test/EmbeddedTests/BasicTests.cs
Labels: v5.4

#15016 RavenDB-17767 added AvailableMemoryForProcessing to SNMP
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.6/ServerAvailableMemoryForProcessing.cs
  src/Raven.Server/Monitoring/Snmp/SnmpOids.cs
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
Labels: v5.2

#15010 RavenDB-19359 Add note that * is a glob pattern
  src/Raven.Studio/typescript/models/database/tasks/replicationAccessBaseModel.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editReplicationHubTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editReplicationSinkTask.ts
  src/Raven.Studio/wwwroot/App/views/database/tasks/editReplicationHubTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editReplicationSinkTask.html
Labels: v5.4

#15021 RavenDB-19401 Recreate HttpClient on SocketError.TryAgain socket erro…
  src/Raven.Client/Http/RequestExecutor.cs
Labels: v5.2

#15008 RavenDB-19363 - SlowTests.Issues.RavenDB_15430.MarkPolicyAfterRollup
  test/SlowTests/Issues/RavenDB_15430.cs
Labels: v5.2

#15022 5.2 to 5.3 merge
  src/Raven.Client/Documents/Conventions/DocumentConventions.cs
  src/Raven.Client/Http/RequestExecutor.cs
  src/Raven.Client/Util/HttpClientHandlerHelper.cs
  src/Raven.Server/Commercial/LicenseManager.cs
  src/Raven.Server/Documents/Handlers/Admin/RachisAdminHandler.cs
  src/Raven.Server/Documents/Handlers/Debugging/ServerWideDebugInfoPackageHandler.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreBackupTaskBase.cs
  src/Raven.Server/Documents/TcpHandlers/SubscriptionConnection.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.6/ServerAvailableMemoryForProcessing.cs
  src/Raven.Server/Monitoring/Snmp/SnmpOids.cs
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Smuggler/Migration/Migrator.cs
  src/Raven.Server/Utils/ReplicationUtils.cs
  src/Raven.Server/Web/RequestHandler.cs
  src/Raven.Server/Web/Studio/DataDirectoryInfo.cs
  src/Raven.Server/Web/System/TestConnectionHandler.cs
  src/Raven.Studio/typescript/models/wizard/nodeInfo.ts
  test/InterversionTests/MixedClusterTestBase.cs
  test/RachisTests/AddNodeToClusterTests.cs
  test/RachisTests/RavenDB_18013.cs
  test/SlowTests/Cluster/ClusterTransactionTests.cs
  test/SlowTests/Cluster/CompareExchangeExpirationTest.cs
  test/SlowTests/Issues/RavenDB-16958.cs
  test/SlowTests/Issues/RavenDB_15430.cs
  test/SlowTests/Smuggler/BackupDatabaseRecordTests.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
Labels: v5.3

#15020 RDBC-631 TimeOnly DateOnly support for single projections
  src/Sparrow/Json/BlittableJsonReaderObject.cs
  test/SlowTests/Issues/RDBC-631.cs
Labels: v5.3

#15025 RavenDB-19389 / RavenDB-18257 When we send a query without an etag th…
  src/Raven.Client/Http/RavenCommand.cs
  src/Raven.Client/Http/RequestExecutor.cs
  src/Raven.Server/Documents/Sharding/Commands/ShardedQueryCommand.cs
  src/Raven.Server/Documents/Sharding/Queries/ShardedQueryProcessor.cs
  src/Raven.Server/Web/Http/ProxyCommand.cs
Labels: v6.0

#15007 RavenDB-16939 - SlowTests.Cluster.ClusterOperationTests.ChangesApiFa…
  test/SlowTests/Cluster/ClusterOperationTests.cs
Labels: v5.2

#15030 RavenDB-19399 increase default HttpPooledConnectionLifetime for Server conventions to 19min
  src/Raven.Client/Documents/Conventions/DocumentConventions.cs
Labels: v5.2

#15031 Referenced project branch was renamed frtom "master" to "main"
  test/SlowTests/Issues/RavenDB_15753.cs
Labels: v5.4

#15037 RavenDB-19193 solved storybook compilation issue after upgrade to sto…
  src/Raven.Studio/.storybook/main.js
  src/Raven.Studio/package-lock.json
  src/Raven.Studio/package.json
  src/Raven.Studio/scripts/setup_jest.js
  src/Raven.Studio/typescript/common/__mocks__/versionProvider.ts
  src/Raven.Studio/typescript/common/storage/__mocks__/storageKeyProvider.ts
Labels: v6.0

#15029 RavenDB-19256 throwing an exception when trying to connect to sharded database
  src/Raven.Server/Integrations/PostgreSQL/PgServer.cs
  src/Raven.Server/Integrations/PostgreSQL/PgSession.cs
  test/SlowTests/Server/Integrations/PostgreSQL/PostgreSqlIntegrationTestBase.cs
  test/SlowTests/Server/Integrations/PostgreSQL/RavenDB_19256.cs
  test/Tests.Infrastructure/RavenTestBase.Sharding.cs
Labels: v6.0

#15035 RavenDB-5055 Suggest deletion instead of merging when the index is a subset of another.
  src/Raven.Server/Documents/Indexes/IndexMerging/IndexMerger.cs
  test/SlowTests/Server/Documents/Indexing/IndexMerging.cs
Labels: v5.2

#15034 RavenDB-19286 Invalid query from the client side when using CompareTo…
  src/Raven.Client/Documents/Linq/RavenQueryProviderProcessor.cs
  test/SlowTests/Issues/RavenDB-19286.cs
Labels: v5.4

#15039 5.2 to 5.3 merge
  src/Raven.Client/Documents/Conventions/DocumentConventions.cs
  src/Raven.Server/Documents/Indexes/IndexMerging/IndexMerger.cs
  test/RachisTests/RavenDB_18013.cs
  test/SlowTests/Cluster/ClusterOperationTests.cs
  test/SlowTests/Server/Documents/Indexing/IndexMerging.cs
Labels: v5.3

#15041 RavenDB-18468 - SlowTests.Issues.RavenDB_16358.AggressiveCacheWithTim…
  test/SlowTests/Issues/RavenDB_16358.cs
Labels: v5.2

#15040 RavenDB-19296 - SlowTests.Server.Documents.TimeSeries.TimeSeriesTombs…
  test/SlowTests/Server/Documents/TimeSeries/TimeSeriesTombstoneCleaner.cs
Labels: v5.2

#15038 RavenDB-19228 Test fix - don't throw when cannot open the errored index
  test/SlowTests/Issues/RavenDB_18357.cs
Labels: v5.4

#15046 RavenDB-19312 Failure to restore because of cluster OperationTimeout
  src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
Labels: v5.2

#15049 5.2 to 5.3 merge
  src/Raven.Client/Documents/Operations/Replication/UpdatePullReplicationAsSinkOperation.cs
  src/Raven.Client/Util/CertificateLoaderUtil.cs
  src/Raven.Client/Util/TcpUtils.cs
  src/Raven.Server/Commercial/LetsEncryptClient.cs
  src/Raven.Server/Commercial/SetupInfo.cs
  src/Raven.Server/Commercial/SetupManager.cs
  src/Raven.Server/Commercial/SetupWizard/SetupWizardUtils.cs
  src/Raven.Server/Documents/Handlers/Admin/RachisAdminHandler.cs
  src/Raven.Server/Documents/Handlers/PullReplicationHandler.cs
  src/Raven.Server/Documents/Handlers/TimeSeriesHandler.cs
  src/Raven.Server/Documents/Includes/IncludeTimeSeriesCommand.cs
  src/Raven.Server/Documents/Patch/ScriptRunner.cs
  src/Raven.Server/Documents/Queries/Results/TimeSeries/TimeSeriesRetriever.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesStats.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesStorage.cs
  src/Raven.Server/NotificationCenter/Handlers/ProxyWebSocketConnection.cs
  src/Raven.Server/RavenServer.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/Commands/PutServerWideBackupConfigurationCommand.cs
  src/Raven.Server/ServerWide/SecretProtection.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
  src/Raven.Server/Storage/Schema/Updates/Server/42012/From40011.cs
  src/Raven.Server/Utils/CertificateUtils.cs
  src/Raven.Server/Utils/Cli/RavenCli.cs
  src/Raven.Server/Web/Authentication/AdminCertificatesHandler.cs
  src/Raven.Server/Web/System/OngoingTasksHandler.cs
  src/Raven.Server/Web/System/SetupHandler.cs
  test/SlowTests/Authentication/AuthenticationBasicTests.cs
  test/SlowTests/ExtensionPoints/ExtensionPointsTests.cs
  test/SlowTests/Issues/RavenDB-15807.cs
  test/SlowTests/Issues/RavenDB_16358.cs
  test/SlowTests/Server/Documents/PeriodicBackup/ServerWideBackup.cs
  test/SlowTests/Server/Documents/TimeSeries/TimeSeriesTombstoneCleaner.cs
  test/SlowTests/Server/ServerStore.cs
  test/SlowTests/Smuggler/BackupDatabaseRecordTests.cs
  test/StressTests/Issues/RavenDB-15145.cs
  test/StressTests/Server/Replication/PullReplicationStressTests.cs
  test/Tests.Infrastructure/RavenTestBase.Certificates.cs
  test/Tests.Infrastructure/TestCertificatesHolder.cs
Labels: v5.3

#15050 5.3 to 5.4 merge
  src/Raven.Client/Documents/Conventions/DocumentConventions.cs
  src/Raven.Client/Documents/Operations/Replication/UpdatePullReplicationAsSinkOperation.cs
  src/Raven.Client/Util/CertificateLoaderUtil.cs
  src/Raven.Client/Util/TcpUtils.cs
  src/Raven.Server/Commercial/LetsEncryptClient.cs
  src/Raven.Server/Commercial/SetupInfo.cs
  src/Raven.Server/Commercial/SetupManager.cs
  src/Raven.Server/Commercial/SetupWizard/SetupWizardUtils.cs
  src/Raven.Server/Documents/Handlers/Admin/RachisAdminHandler.cs
  src/Raven.Server/Documents/Handlers/PullReplicationHandler.cs
  src/Raven.Server/Documents/Handlers/TimeSeriesHandler.cs
  src/Raven.Server/Documents/Includes/IncludeTimeSeriesCommand.cs
  src/Raven.Server/Documents/Indexes/IndexMerging/IndexMerger.cs
  src/Raven.Server/Documents/Patch/ScriptRunner.cs
  src/Raven.Server/Documents/Queries/Results/TimeSeries/TimeSeriesRetriever.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesStats.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesStorage.cs
  src/Raven.Server/NotificationCenter/Handlers/ProxyWebSocketConnection.cs
  src/Raven.Server/RavenServer.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/Commands/PutServerWideBackupConfigurationCommand.cs
  src/Raven.Server/ServerWide/SecretProtection.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
  src/Raven.Server/Storage/Schema/Updates/Server/42012/From40011.cs
  src/Raven.Server/Utils/CertificateUtils.cs
  src/Raven.Server/Utils/Cli/RavenCli.cs
  src/Raven.Server/Web/Authentication/AdminCertificatesHandler.cs
  src/Raven.Server/Web/System/OngoingTasksHandler.cs
  src/Raven.Server/Web/System/SetupHandler.cs
  test/RachisTests/RavenDB_18013.cs
  test/SlowTests/Authentication/AuthenticationBasicTests.cs
  test/SlowTests/Cluster/ClusterOperationTests.cs
  test/SlowTests/ExtensionPoints/ExtensionPointsTests.cs
  test/SlowTests/Issues/RavenDB-15807.cs
  test/SlowTests/Issues/RavenDB_16358.cs
  test/SlowTests/Server/Documents/Indexing/IndexMerging.cs
  test/SlowTests/Server/Documents/PeriodicBackup/ServerWideBackup.cs
  test/SlowTests/Server/Documents/TimeSeries/TimeSeriesTombstoneCleaner.cs
  test/SlowTests/Server/ServerStore.cs
  test/SlowTests/Smuggler/BackupDatabaseRecordTests.cs
  test/StressTests/Issues/RavenDB-15145.cs
  test/StressTests/Server/Replication/PullReplicationStressTests.cs
  test/Tests.Infrastructure/RavenTestBase.Certificates.cs
  test/Tests.Infrastructure/TestCertificatesHolder.cs
Labels: v5.4
