Repository ravendb/ravendb, pull requests merged in 2023-05, with the labels that each got.

#16372 RavenDB-20390: fix sharded subscription with cv set to last document after replication
  src/Raven.Server/Documents/Sharding/Subscriptions/ShardedDocumentsDatabaseSubscriptionProcessor.cs
  src/Raven.Server/Documents/Subscriptions/SubscriptionProcessor/DocumentsDatabaseSubscriptionProcessor.cs
  test/SlowTests/Sharding/Issues/RavenDB_20390.cs
Labels: v6.0

#16374 RavenDB-20358 Fixing the return (and reset) of the context used by a shard command while it was still running.
  src/Raven.Server/Documents/Sharding/Executors/AbstractExecutor.cs
Labels: v6.0

#16375 RavenDB-20329 unify responsible node for subscriptions
  src/Raven.Client/ServerWide/DatabaseRecord.cs
  src/Raven.Client/Util/ClientShardHelper.cs
  src/Raven.Server/Documents/OngoingTasks/AbstractOngoingTasks.cs
  src/Raven.Server/Documents/Sharding/ShardedDatabaseContext.Subscriptions.cs
  src/Raven.Server/Documents/Sharding/Subscriptions/OrchestratedSubscriptionConnection.cs
  src/Raven.Server/Documents/Subscriptions/AbstractSubscriptionStorage.cs
  src/Raven.Server/Documents/Subscriptions/Sharding/ShardSubscriptionStorage.cs
  src/Raven.Server/Documents/Subscriptions/SubscriptionBinder.cs
  src/Raven.Server/Documents/Subscriptions/SubscriptionConnectionBase.cs
  src/Raven.Server/Documents/Subscriptions/SubscriptionStorage.cs
  src/Raven.Server/Documents/TcpHandlers/SubscriptionConnection.cs
  src/Raven.Server/Documents/TcpHandlers/SubscriptionConnectionForShard.cs
  src/Raven.Server/ServerWide/Commands/Subscriptions/AcknowledgeSubscriptionBatchCommand.cs
  src/Raven.Server/ServerWide/Commands/Subscriptions/RecordBatchSubscriptionDocumentsCommand.cs
  src/Raven.Server/ServerWide/Commands/Subscriptions/UpdateSubscriptionClientConnectionTime.cs
  test/RachisTests/SubscriptionsFailover.cs
Labels: v6.0

#16368 RavenDB-15446 enable eslint for studio
  src/Raven.Studio/typescript/components/common/CreateDatabase.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexFilter.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexSelectActions.tsx
  src/Raven.Studio/typescript/components/pages/database/tasks/list/OngoingTasksPage.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/DatabasePanel.tsx
  src/Raven.Studio/typescript/models/resources/creation/backupCredentials.ts
Labels: v6.0, Studio

#16379 RavenDB-20329 move RachisTests::SubscriptionsFailover to use sharded mode
  test/RachisTests/SubscriptionFailoverWIthWaitingChains.cs
  test/RachisTests/SubscriptionsFailover.cs
Labels: v6.0

#16380 RavenDB-20417 Sharding - Fix LoadStartingWith not to return results from cache
  src/Raven.Server/Documents/Handlers/Processors/Streaming/StreamingHandlerProcessorForGetDocs.cs
  test/FastTests/Client/Documents/Load.cs
Labels: v6.0

#16381 RavenDB-20329 move all rachis tests in the root folder to sharded
  test/RachisTests/DisableNodeOnClusterTest.cs
  test/RachisTests/RavenDB_14348.cs
  test/RachisTests/SubscriptionFailoverWIthWaitingChains.cs
Labels: v6.0

#16383 RavenDB-20329 move rachis tests of ongoing tasks to use sharding
  test/RachisTests/DatabaseCluster/OngoingTasks.cs
Labels: v6.0

#16384 RavenDB-20053 uncomment SkipDrainAllRequests for tests
  test/Tests.Infrastructure/RavenTestBase.cs
Labels: v6.0

#16386 RavenDB-20053 use different paths for shard replicas
  test/Tests.Infrastructure/RavenTestBase.Sharding.cs
Labels: v6.0

#16389 RavenDB-20369 - Sharding - Replication - Missing attachment loop
  src/Raven.Server/Documents/Replication/Outgoing/AbstractOutgoingReplicationHandler.cs
  src/Raven.Server/Documents/Sharding/Handlers/ShardedIncomingReplicationHandler.cs
  src/Raven.Server/Documents/Sharding/Handlers/ShardedOutgoingReplicationHandler.cs
  test/SlowTests/Sharding/Replication/ShardedExternalReplicationTests.cs
Labels: v6.0

#16394 RavenDB-20350 Do NOT allow to edit change vector in subscription when…
  src/Raven.Studio/typescript/viewmodels/database/tasks/editSubscriptionTask.ts
  src/Raven.Studio/wwwroot/App/views/database/tasks/editSubscriptionTask.html
Labels: v6.0, Studio

#16396 RavenDB-20368 Sharding - Export - No details are shown
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/smugglerDatabaseDetails.ts
Labels: v6.0, Studio

#16411 RavenDB-20368 Sharding - Export - No details are shown
  src/Raven.Client/Documents/Smuggler/ShardedSmugglerProgress.cs
  src/Raven.Client/Documents/Smuggler/SmugglerResult.cs
Labels: v6.0

#16409 RavenDB-18539 Refine About view
  src/Raven.Studio/wwwroot/App/views/shell/about.html
  src/Raven.Studio/wwwroot/Content/css/pages/about.less
  src/Raven.Studio/wwwroot/Content/css/styles-common-scoped.less
Labels: v6.0, Studio

#16340 RavenDB-20335 Unify modals
  src/Raven.Studio/typescript/components/pages/database/indexes/list/BulkIndexOperationConfirm.tsx
  src/Raven.Studio/typescript/durandalPlugins/bootstrapModal.ts
  src/Raven.Studio/wwwroot/App/views/common/confirmationDialog.html
  src/Raven.Studio/wwwroot/App/views/database/indexes/clearIndexErrorsConfirm.html
  src/Raven.Studio/wwwroot/App/views/database/indexes/deleteIndexesConfirm.html
  src/Raven.Studio/wwwroot/App/views/resources/compactDatabaseDialog.html
  src/Raven.Studio/wwwroot/App/views/resources/deleteDatabaseConfirm.html
  src/Raven.Studio/wwwroot/App/views/resources/disableDatabaseToggleConfirm.html
  src/Raven.Studio/wwwroot/App/views/resources/disableIndexingToggleConfirm.html
  src/Raven.Studio/wwwroot/Content/css/modals.less
  src/Raven.Studio/wwwroot/Content/css/styles-common-scoped.less
  src/Raven.Studio/wwwroot/Content/scss/bs5variables.scss
Labels: v6.0, Studio

#16414 RavenDB-20431 add shard number after adding new document in Studio
  src/Raven.Server/Documents/Sharding/Commands/ShardedSingleNodeBatchCommand.cs
  src/Raven.Server/Documents/Sharding/Handlers/Batches/ShardedBatchCommand.cs
  src/Raven.Server/Documents/Sharding/Operations/ShardedBatchOperation.cs
Labels: v6.0

#16367 RavenDB-15446 enable eslint for studio
  src/Raven.Studio/typescript/common/helpers/database/sqlConnectionStringSyntax.ts
Labels: v5.4, Studio

#16416 RavenDB-20070 Handle nested generic types
  src/Raven.Client/Json/Serialization/NewtonsoftJson/DefaultRavenSerializationBinder.cs
Labels: v5.2

#16371 RavenDB-20412 Disabled external replication allows deletion of tombstones
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  test/SlowTests/Issues/RavenDB-20412.cs
Labels: v5.2

#16376 RavenDB-20042: Never-ending backup - stuck on retention policy
  src/Raven.Server/Documents/PeriodicBackup/Retention/RetentionPolicyRunnerBase.cs
Labels: v5.2

#16391 RavenDB-20202: Cluster node health check issue when experiencing a timeout and topology update simultaneously (Test fix)
  test/SlowTests/Issues/RavenDB_20202.cs
Labels: v5.2

#16366 RavenDB-20398 - fix parsing the thread id when the thread name is included in the thread frame
  tools/Raven.Debug/StackTrace/StackTracer.cs
Labels: v5.4

#16395 RavenDB-20399 Document ID not visible in Related section
  .gitignore
  src/Raven.Studio/typescript/common/helpers/database/documentHelpers.ts
Labels: v5.4

#16398 RavenDB-20416: fix updating subscription with LastDocument if last doc is from replication
  src/Raven.Server/Documents/Handlers/SubscriptionsHandler.cs
  src/Raven.Server/Documents/Subscriptions/SubscriptionConnectionsState.cs
  test/SlowTests/Issues/RavenDB_20416.cs
Labels: v5.4

#16419 RavenDB-20451 - add the document id to the error message
  src/Raven.Server/Documents/Patch/ScriptRunner.cs
Labels: v5.4

#16385 RavenDB-20189: Delay date isn't updated after we delay backup
  src/Raven.Client/Documents/Operations/Backups/PeriodicBackupStatus.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
  src/Raven.Server/ServerWide/Commands/DelayBackupCommand.cs
  src/Raven.Server/Utils/BackupUtils.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
Labels: v5.2

#16365 RavenDB-19745 account attachment stream by bucket
  src/Raven.Server/Documents/AttachmentsStorage.Sharding.cs
  src/Raven.Server/Documents/AttachmentsStorage.cs
  src/Raven.Server/Documents/Schemas/Attachments.cs
  src/Raven.Server/Web/Studio/Processors/BucketsHandlerProcessorForGetBucket.cs
  src/Voron/Data/Tables/Table.cs
  src/Voron/Data/Tables/TableSchema.IndexDefinitions.cs
  src/Voron/Slice.cs
  test/SlowTests/Sharding/Backup/ShardedSmugglerTests.cs
  test/SlowTests/Sharding/Cluster/BucketStatsTests.cs
Labels: v6.0

#16421 5.2 to 5.4 merge
  src/Raven.Client/Documents/Operations/Backups/PeriodicBackupStatus.cs
  src/Raven.Client/Json/Serialization/NewtonsoftJson/DefaultRavenSerializationBinder.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
  src/Raven.Server/Documents/PeriodicBackup/Retention/RetentionPolicyRunnerBase.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/ServerWide/Commands/DelayBackupCommand.cs
  src/Raven.Server/Utils/BackupUtils.cs
  test/SlowTests/Issues/RavenDB-20412.cs
  test/SlowTests/Issues/RavenDB_20202.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
Labels: v5.4

#16425 RavenDB-20455 Fix blurry code on non-default themes
  src/Raven.Studio/typescript/components/pages/database/tasks/createSampleData/CreateSampleData.scss
  src/Raven.Studio/typescript/components/pages/database/tasks/createSampleData/CreateSampleData.tsx
  src/Raven.Studio/wwwroot/Content/css/prism.less
Labels: v6.0, Studio

#16426 RavenDB-20439 Fixed Filter by Name input positioning
  src/Raven.Studio/typescript/components/common/Toggles.scss
  src/Raven.Studio/typescript/components/pages/resources/databases/DatabasesPage.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/DatabasesFilter.scss
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/DatabasesFilter.tsx
Labels: v6.0, Studio

#16424 RavenDB-20416: fix updating subscription with LastDocument if last doc is from replication
  src/Raven.Server/Documents/Handlers/Processors/Collections/CollectionsHandlerProcessorForGetLastChangeVector.cs
  src/Raven.Server/Documents/Handlers/Processors/Subscriptions/SubscriptionsHandlerProcessorForTrySubscription.cs
  src/Raven.Server/Documents/Handlers/SubscriptionsHandler.cs
  src/Raven.Server/Documents/Subscriptions/SubscriptionConnectionsState.cs
  src/Raven.Server/Documents/Subscriptions/SubscriptionStorage.cs
  test/SlowTests/Issues/RavenDB_20416.cs
Labels: v6.0

#16430 RavenDB-20073 Improve "add shard" modal in manage database group
  src/Raven.Studio/typescript/commands/database/dbGroup/addShardToDatabaseGroupCommand.ts
  src/Raven.Studio/typescript/viewmodels/resources/addNewShardToDatabaseGroup.ts
  src/Raven.Studio/wwwroot/App/views/resources/addNewShardToDatabaseGroup.html
Labels: v6.0, Studio

#16429 RavenDB-20459 Add caption or info to select all databases checkbox
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexSelectActions.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/DatabasesSelectActions.tsx
Labels: v6.0, Studio

#16434 RavenDB-20463 - Error when trying to migrate tables from SQL
  src/Raven.Studio/typescript/viewmodels/database/tasks/importDatabaseFromSql.ts
Labels: v5.4, Studio

#16433 RavenDB-20417 & RavenDB-20431 address PR comments
  src/Raven.Server/Documents/Handlers/Processors/Queries/AbstractQueriesHandlerProcessorForGet.cs
  src/Raven.Server/Documents/Handlers/Processors/Streaming/AbstractStreamingHandlerProcessorForGetStreamQuery.cs
  src/Raven.Server/Documents/Handlers/Processors/Streaming/StreamingHandlerProcessorForGetDocs.cs
  src/Raven.Server/Documents/Handlers/Processors/TimeSeries/TimeSeriesHandlerProcessorForGetTimeSeries.cs
  src/Raven.Server/Documents/Handlers/Processors/TimeSeries/TimeSeriesHandlerProcessorForGetTimeSeriesRanges.cs
  src/Raven.Server/Documents/Sharding/Operations/ShardedBatchOperation.cs
  src/Raven.Server/Extensions/HttpExtensions.cs
  src/Raven.Server/Web/RequestHandler.cs
Labels: v6.0

#16441 RavenDB-7070 add RavenData to WillGetIndexStatsFromStorageOrReader
  test/SlowTests/Issues/RavenDB_16193.cs
Labels: v6.0

#16442 RavenDB-20436 fixing test
  test/FastTests/Blittable/PeepingTomTest.cs
Labels: v5.2

#16449 RavenDB-20470 Subscription details improvements
  src/Raven.Studio/typescript/components/common/LazyLoad.stories.tsx
  src/Raven.Studio/typescript/components/common/LocationDistribution.stories.tsx
  src/Raven.Studio/typescript/components/common/RichPanel.stories.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexDistribution.tsx
  src/Raven.Studio/typescript/components/pages/database/tasks/list/OngoingTaskPage.scss
  src/Raven.Studio/typescript/components/pages/database/tasks/panels/OngoingEtlTaskDistribution.tsx
  src/Raven.Studio/typescript/components/pages/database/tasks/panels/SubscriptionPanel.tsx
  src/Raven.Studio/typescript/components/pages/database/tasks/panels/SubscriptionTaskDistribution.tsx
Labels: v6.0, Studio

#16436 RavenDB-18179 Mark query results as stale if resharding is happening during query execution
  src/Raven.Client/ServerWide/Sharding/ShardingConfiguration.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Sharding/Operations/Queries/AbstractShardedQueryOperation.cs
  src/Raven.Server/Documents/Sharding/Operations/Queries/ShardedFacetedQueryOperation.cs
  src/Raven.Server/Documents/Sharding/Operations/Queries/ShardedIndexEntriesQueryOperation.cs
  src/Raven.Server/Documents/Sharding/Operations/Queries/ShardedQueryOperation.cs
  src/Raven.Server/Documents/Sharding/Operations/Queries/ShardedSuggestionQueryOperation.cs
  src/Raven.Server/ServerWide/ShardingStore.cs
  test/SlowTests/Sharding/Issues/RavenDB_18179.cs
Labels: v6.0

#16451 RavenDB-20471 Fix change vector styling in Database Stats
  src/Raven.Studio/typescript/components/pages/database/status/statistics/partials/DetailedDatabaseStats.tsx
  src/Raven.Studio/typescript/components/pages/database/status/statistics/partials/EssentialDatabaseStatsComponent.tsx
Labels: v6.0, Studio

#16437 RavenDB-20297 added DatabaseStatus to the /studio-tasks/databases/state endpoint
  src/Raven.Server/Web/System/Processors/Studio/StudioDatabasesHandlerForGetDatabasesState.cs
  src/Raven.Studio/typescript/test/stubs/DatabasesStubs.ts
Labels: v6.0

#16452 RavenDb-20432 Fix alignment on the Backup Restore view
  src/Raven.Studio/wwwroot/App/views/resources/createDatabase.html
  src/Raven.Studio/wwwroot/Content/css/checkbox-toggle.less
  src/Raven.Studio/wwwroot/Content/css/styles-common-scoped.less
Labels: v6.0, Studio

#16454 RavenDB-20461 Client-configuration view: Verify text
  src/Raven.Studio/typescript/components/pages/database/settings/clientConfiguration/ClientDatabaseConfiguration.tsx
  src/Raven.Studio/typescript/components/pages/resources/manageServer/clientConfiguration/ClientGlobalConfiguration.tsx
Labels: v6.0, Studio

#16457 RavenDB-20254 Create RadioToggleWithIconProps for form
  src/Raven.Studio/typescript/components/common/Form.tsx
  src/Raven.Studio/typescript/components/common/RadioToggle.tsx
  src/Raven.Studio/typescript/components/common/Toggles.stories.tsx
  src/Raven.Studio/typescript/components/pages/resources/manageDatabaseGroup/partials/ReorderNodes.tsx
Labels: v6.0, Studio

#16461 RavenDB-20477 - SlowTests.Client.TimeSeries.Replication.TimeSeriesRep…
  test/SlowTests/Client/TimeSeries/Replication/TimeSeriesReplicationTests.cs
Labels: v6.0

#16462 RavenDB-20479 - SlowTests.Client.TimeSeries.Replication.TimeSeriesRep…
  test/SlowTests/Client/TimeSeries/Replication/TimeSeriesReplicationTests.cs
Labels: v6.0

#16459 RavenDB-20289 Changed size value source when writing QueryResult for BlittableJsonReaderObject
  src/Raven.Server/Json/BlittableJsonTextWriterExtensions.cs
Labels: v5.4

#16458 RavenDB-20444 Skip inner subclauses when applying boosting via `DocumentQuery`.
  src/Raven.Client/Documents/Session/AbstractDocumentQuery.cs
  test/SlowTests/Issues/RavenDB-20444.cs
Labels: v5.4

#16468 5.4 to 6.0 merge
  src/Raven.Client/Documents/Session/AbstractDocumentQuery.cs
  src/Raven.Client/ServerWide/Operations/TrafficWatch/PutTrafficWatchConfigurationOperation.cs
  src/Raven.Server/Config/Categories/MemoryConfiguration.cs
  src/Raven.Server/Config/Categories/TrafficWatchConfiguration.cs
  src/Raven.Server/Json/BlittableJsonTextWriterExtensions.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.6/1.6.11/ServerGcLohSize.cs
  src/Raven.Server/Monitoring/Snmp/SnmpOids.cs
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
  src/Raven.Server/Program.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/TrafficWatch/TrafficWatchToLog.cs
  src/Raven.Studio/typescript/models/resources/trafficWatchConfiguration.ts
  src/Raven.Studio/typescript/viewmodels/manage/adminLogsTrafficWatchDialog.ts
  src/Raven.Studio/wwwroot/App/views/manage/adminLogsTrafficWatchDialog.html
  src/Sparrow/LowMemory/LowMemoryNotification.cs
  test/FastTests/Server/TrafficWatchConfigurationTests.cs
  test/SlowTests/Issues/RavenDB-20444.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v6.0

#16469 RavenDB-20492 - SlowTests.Client.TimeSeries.Issues.RavenDB_14426.Merg…
  test/SlowTests/Client/TimeSeries/Issues/RavenDB-14426.cs
Labels: v6.0

#16478 RavenDB-20346 Test fix - `CanUpdateFanout`
  test/FastTests/Corax/RavenIntegration.cs
Labels: v5.4

#16473 RavenDB-20497 Add a test for customizing AfterStreamExecuted
  test/SlowTests/Core/Streaming/QueryStreaming.cs
Labels: v5.2

#16477 RavenDB-20443 Apply boost to inner query inside `CachingQuery` instead of applying it to `CachingQuery`,
  src/Raven.Server/Documents/Queries/LuceneIntegration/CachingQuery.cs
  test/SlowTests/Issues/RavenDB-20444.cs
Labels: v5.4

#16481 RavenDB-7070 avoid mixing async & Wait() in tests
  src/Raven.Server/Rachis/RachisConsensus.cs
  test/SlowTests/Server/Documents/OngoingTasks/PinOnGoingTaskToMentorNode.cs
Labels: v5.2

#16476 RavenDB-20500 - Get the correct document size for the HugeDocuments notification
  src/Raven.Server/Documents/Handlers/BatchHandler.cs
Labels: v5.2

#16488 RavenDB-20509 Fix temporary buffers bar in Storage widget
  src/Raven.Studio/wwwroot/App/views/resources/widgets/storageWidget.html
Labels: v6.0, Studio

#16489 5.2 to 5.4 merge
  src/Raven.Server/Commercial/LicenseManager.cs
  src/Raven.Server/Documents/Handlers/BatchHandler.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/ServerWide/ClusterCommandsVersionManager.cs
  test/SlowTests/Core/Streaming/QueryStreaming.cs
  test/SlowTests/Server/Documents/OngoingTasks/PinOnGoingTaskToMentorNode.cs
Labels: v5.4

#16483 RavenDB-20199 - SlowTests.Sharding.Replication.ShardedExternalReplica…
  test/SlowTests/Sharding/Replication/ShardedExternalReplicationTests.cs
Labels: v6.0

#16487 RavenDB-20478 - SlowTests.Client.Attachments.AttachmentsReplication.A…
  test/SlowTests/Client/Attachments/AttachmentsReplication.cs
Labels: v6.0

#16479 RavenDB-20495 ClusterCommandsVersionManager should not be static
  src/Raven.Server/Documents/Handlers/Processors/Batches/AbstractClusterTransactionRequestProcessor.cs
  src/Raven.Server/Documents/Indexes/AbstractIndexCreateController.cs
  src/Raven.Server/Rachis/Candidate.cs
  src/Raven.Server/Rachis/Follower.cs
  src/Raven.Server/Rachis/FollowerAmbassador.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/Rachis/RachisVersionValidation.cs
  src/Raven.Server/RavenServer.cs
  src/Raven.Server/ServerWide/ClusterCommandsVersionManager.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/ClusterValidator.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterObserver.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Smuggler/Documents/Actions/AbstractDatabaseCompareExchangeActions.cs
  src/Raven.Server/Smuggler/Documents/Actions/DatabaseIndexActions.cs
  test/SlowTests/Issues/RavenDB-15900.cs
  test/Tests.Infrastructure/RachisConsensusTestBase.cs
Labels: v6.0

#16491 5.4 to 6.0 merge
  src/Raven.Server/Commercial/LicenseManager.cs
  src/Raven.Server/Documents/ETL/Providers/Raven/RavenEtlDocumentTransformer.cs
  src/Raven.Server/Documents/Handlers/Batches/Commands/ClusterTransactionMergedCommand.cs
  src/Raven.Server/Documents/Handlers/DocumentHandler.cs
  src/Raven.Server/Documents/Queries/LuceneIntegration/CachingQuery.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/ServerWide/ClusterCommandsVersionManager.cs
  test/SlowTests/Core/Streaming/QueryStreaming.cs
  test/SlowTests/Issues/RavenDB-19696.cs
  test/SlowTests/Issues/RavenDB-20444.cs
  test/SlowTests/Server/Documents/OngoingTasks/PinOnGoingTaskToMentorNode.cs
Labels: v6.0

#16490 RavenDB-20496 Fix Manage Database Group styling for non-default themes
  src/Raven.Studio/typescript/components/common/DatabaseGroup.scss
  src/Raven.Studio/typescript/components/common/DatabaseGroup.tsx
  src/Raven.Studio/typescript/components/pages/resources/manageDatabaseGroup/ManageDatabaseGroupPage.tsx
Labels: v6.0, Studio

#16492 RavenDB-20502 - SlowTests.Client.Attachments.AttachmentsReplication.A…
  test/SlowTests/Client/Attachments/AttachmentsReplication.cs
Labels: v6.0

#16496 RavenDB-19439 - add RetryFact
  test/SlowTests/Tools/SetupSecuredClusterUsingRvn.cs
  test/Tests.Infrastructure/LicenseRequiredFactAttribute.cs
  test/Tests.Infrastructure/LicenseRequiredRetryFactAttribute.cs
Labels: v5.2

#16494 RavenDB-20422 get replication errors in tests infra
  src/Raven.Server/Documents/Replication/IncomingConnectionInfo.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  test/SlowTests/Server/Documents/OngoingTasks/PinOnGoingTaskToMentorNode.cs
  test/Tests.Infrastructure/RavenTestBase.Replication.cs
Labels: v5.2

#16495 RavenDB-20351 Catch indexing OOM Exception in encrypted database low memory state.
  src/Raven.Server/Documents/Indexes/Index.cs
Labels: v5.4

#16484 RavenDB-18421 Add hint to exception when media is write protected.
  src/Raven.Server/Indexing/TempFileCache.cs
  src/Raven.Server/Utils/ExceptionHelper.cs
  src/Sparrow.Server/Platform/PalHelper.cs
Labels: v5.4

#16482 RavenDB-20505 Don't clone patch parameters
  src/Raven.Server/Documents/Patch/JavaScriptUtils.cs
  src/Raven.Server/Documents/Patch/ScriptRunner.cs
  test/FastTests/Issues/RavenDB-20505.cs
Labels: v5.4

#16504 RavenDB-20098 Allow to pass specific client certificate thumbprints i…
  src/Raven.Studio/typescript/models/resources/trafficWatchConfiguration.ts
Labels: v5.4, Studio

#16503 RavenDB-20039 Add the flushing time to the slow writes notification -…
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/performanceHint/slowIoDetails.ts
Labels: v5.4, Studio

#16501 RavenDB-20486 Add documentation link to Client Configuration views
  src/Raven.Studio/typescript/components/pages/database/settings/clientConfiguration/ClientDatabaseConfiguration.tsx
  src/Raven.Studio/typescript/components/pages/resources/manageServer/clientConfiguration/ClientGlobalConfiguration.tsx
Labels: v6.0, Studio

#16497 RavenDB-18997 - Failing InterversionTests InterversionTests.MixedClus…
  test/InterversionTests/MixedClusterTests.cs
Labels: v6.0

#16511 RavenDB-15446 enable eslint for studio
  src/Raven.Studio/typescript/components/pages/database/tasks/createSampleData/CreateSampleData.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/DatabasesPage.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/DatabaseDistribution.tsx
Labels: v6.0, Studio

#16509 RavenDB-20430 Change margins to flex gap property
  src/Raven.Studio/typescript/components/common/DatabaseGroup.scss
  src/Raven.Studio/typescript/components/common/LazyLoad.stories.tsx
  src/Raven.Studio/typescript/components/common/ProgressCircle.scss
  src/Raven.Studio/typescript/components/common/RichPanel.scss
  src/Raven.Studio/typescript/components/common/RichPanel.stories.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexPanel.tsx
  src/Raven.Studio/typescript/components/pages/database/tasks/panels/PeriodicBackupPanel.tsx
  src/Raven.Studio/typescript/components/pages/database/tasks/shared.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/DatabasePanel.tsx
  src/Raven.Studio/typescript/components/pages/resources/manageDatabaseGroup/partials/ReorderNodes.tsx
Labels: v6.0, Studio

#16508 5.4 to 6.0 merge
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Patch/JavaScriptUtils.cs
  src/Raven.Server/Documents/Patch/ScriptRunner.cs
  src/Raven.Server/Documents/Replication/Stats/IncomingConnectionInfo.cs
  src/Raven.Server/Documents/SlowWriteNotification.cs
  src/Raven.Server/Documents/TransactionMerger/AbstractTransactionOperationsMerger.cs
  src/Raven.Server/Documents/TransactionMerger/DocumentsTransactionOperationsMerger.cs
  src/Raven.Server/Indexing/TempFileCache.cs
  src/Raven.Server/NotificationCenter/Notifications/Details/SlowIoDetails.cs
  src/Raven.Server/NotificationCenter/NotificationsStorage.cs
  src/Raven.Server/NotificationCenter/SlowWriteNotifications.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/ServerWide/TransactionMerger/ClusterTransactionOperationsMerger.cs
  src/Raven.Server/Utils/ExceptionHelper.cs
  src/Raven.Studio/typescript/common/notifications/notificationCenter.ts
  src/Raven.Studio/typescript/models/resources/trafficWatchConfiguration.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/performanceHint/slowIoDetails.ts
  src/Sparrow.Server/IoChange.cs
  src/Sparrow.Server/Meters/IoMeterBuffer.cs
  src/Sparrow.Server/Platform/PalHelper.cs
  src/Voron/Debugging/CommitStats.cs
  src/Voron/Impl/Journal/IJournalWriter.cs
  src/Voron/Impl/Journal/JournalFile.cs
  src/Voron/Impl/Journal/JournalWriter.cs
  src/Voron/Impl/Journal/LazyTransactionBuffer.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/Impl/LowLevelTransaction.cs
  test/FastTests/Issues/RavenDB-20505.cs
  test/SlowTests/Issues/RavenDB-10450.cs
  test/SlowTests/Issues/RavenDB_12040.cs
  test/SlowTests/Issues/RavenDB_20039.cs
  test/SlowTests/Server/Documents/OngoingTasks/PinOnGoingTaskToMentorNode.cs
  test/SlowTests/Tools/SetupSecuredClusterUsingRvn.cs
  test/Tests.Infrastructure/LicenseRequiredFactAttribute.cs
  test/Tests.Infrastructure/LicenseRequiredRetryFactAttribute.cs
  test/Tests.Infrastructure/RavenTestBase.Replication.cs
  tools/TypingsGenerator/Program.cs
Labels: v6.0

#16507 RavenDB-20524 Database create button sometimes doesn't work
  src/Raven.Studio/typescript/models/resources/creation/databaseCreationModel.ts
Labels: v6.0, Studio

#16521 RavenDB-20354 & RavenDB-20410 : flaky tests adjustments
  test/SlowTests/Sharding/ETL/ShardedEtlTests.cs
Labels: v6.0

#16493 RavenDB-20429 add debug info
  test/SlowTests/Sharding/Encryption/ShardedEncryption.cs
Labels: v6.0

#16520 RavenDB-19759 Show the document was saved using a cluster transaction
  src/Raven.Studio/typescript/viewmodels/database/documents/editDocument.ts
  src/Raven.Studio/wwwroot/App/views/database/documents/editDocument.html
Labels: v5.4, Studio

#16515 RavenDB-20517 Fix disabled inputs look on non-default themes
  src/Raven.Studio/wwwroot/Content/scss/_bs5extend.scss
  src/Raven.Studio/wwwroot/Content/scss/_colors.scss
  src/Raven.Studio/wwwroot/Content/scss/bs5variables.scss
Labels: v6.0, Studio

#16524 RavenDB-20386 track facet results by DisplayName instead of FieldName in first place because we can use the same field multiple times with different aggregating methods.
  src/Raven.Server/Documents/Sharding/Queries/Facets/ShardedFacetedQueryProcessor.cs
  test/SlowTests/MailingList/FacetsMultipleAggregation.cs
Labels: v6.0

#16525 RavenDB-20409 : fix flaky test
  test/SlowTests/Issues/RavenDB_20206.cs
  test/SlowTests/Server/Documents/PeriodicBackup/RavenDB-11139.cs
  test/SlowTests/Sharding/Backup/ShardedRestoreBackupTests.cs
  test/SlowTests/Sharding/Backup/ShardedSmugglerTests.cs
  test/Tests.Infrastructure/RavenTestBase.Cluster.cs
Labels: v6.0

#16526 RavenDB-20442 Fix toasts for non-default themes
  src/Raven.Studio/wwwroot/Content/css/styles-blue.less
  src/Raven.Studio/wwwroot/Content/css/styles-classic.less
  src/Raven.Studio/wwwroot/Content/css/styles-light.less
  src/Raven.Studio/wwwroot/Content/css/toastr.less
Labels: v6.0, Studio

#16533 RavenDB-20550 we were setting IsEncrypted inside AbstractTransactionOperationsMerger too early, database loads this value in DocumentDatabase.Initialize
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/TransactionMerger/AbstractTransactionOperationsMerger.cs
  src/Raven.Server/Documents/TransactionMerger/DocumentsTransactionOperationsMerger.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/ServerWide/TransactionMerger/ClusterTransactionOperationsMerger.cs
Labels: v6.0

#16527 RavenDB-20402: SlowTests.Server.Documents.PeriodicBackup.ServerWideBackup.CanStoreAndEditServerWideBackupForIdleDatabase
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/ServerWide/ServerStore.cs
Labels: v5.2

#16530 RavenDB-20539: Improved clarity of the exception message thrown on attachment missing
  src/Raven.Server/Documents/AttachmentsStorage.cs
  src/Raven.Server/Documents/ETL/Providers/Raven/Enumerators/AttachmentTombstonesToRavenEtlItems.cs
  src/Raven.Server/Documents/ETL/Providers/Raven/RavenEtlDocumentTransformer.cs
Labels: v5.2

#16541 RavenDB-20550 Adding debug assertions to ensure that we don't use async commit feature with encryption or on 32 bits
  src/Voron/Impl/LowLevelTransaction.cs
Labels: v5.4

#16549 5.2 to 5.4 merge
  src/Raven.Server/Documents/AttachmentsStorage.cs
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/ETL/Providers/Raven/Enumerators/AttachmentTombstonesToRavenEtlItems.cs
  src/Raven.Server/Documents/ETL/Providers/Raven/RavenEtlDocumentTransformer.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Sparrow.Server/LowMemory/MemoryInformation.cs
  src/Sparrow.Server/Platform/Posix/CGroupHelper.cs
  src/Sparrow.Server/Platform/Posix/Syscall.cs
  src/Sparrow.Server/Platform/Posix/sysinfo_t.cs
  test/FastTests/Sparrow/FileSystemUtilsTest.cs
Labels: v5.4

#16550 5.4 to 6.0 merge
  src/Raven.Client/Documents/Operations/Backups/BackupSettings.cs
  src/Raven.Client/ServerWide/Operations/Certificates/SecurityClearanceAttribute.cs
  src/Raven.Server/Documents/AttachmentsStorage.Sharding.cs
  src/Raven.Server/Documents/AttachmentsStorage.cs
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/ETL/Providers/Raven/Enumerators/AttachmentTombstonesToRavenEtlItems.cs
  src/Raven.Server/Documents/ETL/Providers/Raven/RavenEtlDocumentTransformer.cs
  src/Raven.Server/Documents/Handlers/Processors/OngoingTasks/AbstractOngoingTasksHandlerProcessorForBackupDatabaseOnce.cs
  src/Raven.Server/Documents/Handlers/Processors/OngoingTasks/AbstractOngoingTasksHandlerProcessorForPutConnectionString.cs
  src/Raven.Server/Documents/Handlers/Processors/OngoingTasks/AbstractOngoingTasksHandlerProcessorForUpdatePeriodicBackup.cs
  src/Raven.Server/Documents/PeriodicBackup/BackupConfigurationHelper.cs
  src/Raven.Server/RavenServer.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Utils/SecurityClearanceValidator.cs
  src/Raven.Server/Web/RequestHandler.cs
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
  src/Raven.Server/Web/System/DatabasesHandler.cs
  src/Sparrow.Server/LowMemory/MemoryInformation.cs
  src/Sparrow.Server/Platform/Posix/CGroupHelper.cs
  src/Sparrow.Server/Platform/Posix/Syscall.cs
  src/Sparrow.Server/Platform/Posix/sysinfo_t.cs
  src/Voron/Impl/LowLevelTransaction.cs
  test/FastTests/Sparrow/FileSystemUtilsTest.cs
  test/SlowTests/Issues/RavenDB_19948.cs
  test/Tests.Infrastructure/RavenTestBase.Encryption.cs
Labels: v6.0

#16537 RavenDB-20312 Filtering deselects items
  src/Raven.Studio/typescript/components/pages/resources/databases/DatabasesPage.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/DatabasesSelectActions.tsx
Labels: v6.0, Studio

#16551 RavenDB-20557 defensive coding
  src/Raven.Client/Documents/Changes/ChangeNotification.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/Sharding/ShardedDatabaseContext.cs
Labels: v6.0

#16548 RavenDB-20380 Allow to skip implicit null in map-reduce output from orchestrator
  src/Raven.Server/Documents/Indexes/MapReduce/Static/AggregatedAnonymousObjects.cs
  src/Raven.Server/Documents/Indexes/MapReduce/Static/Sharding/ShardedAggregatedAnonymousObjects.cs
  src/Raven.Server/Documents/Sharding/Queries/IndexEntries/ShardedMapReduceIndexEntriesQueryResultsMerger.cs
  src/Raven.Server/Documents/Sharding/Queries/ShardedMapReduceQueryResultsMerger.cs
  test/SlowTests/Issues/RavenDB_12334.cs
Labels: v6.0

#16556 RavenDB-20561 fixing edit document view after 5.4 -> 6.0 merge
  src/Raven.Studio/typescript/viewmodels/database/documents/editDocument.ts
Labels: v6.0, Studio

#16555 RavenDB-20554 Fix Stats > Time Series popover positioning
  src/Raven.Studio/typescript/components/pages/database/status/statistics/partials/EssentialDatabaseStatsComponent.tsx
Labels: v6.0, Studio

#16554 RavenDB-20397 asserting in DatabaseObservationState values
  src/Raven.Server/ServerWide/Maintenance/ClusterObserver.cs
  test/FastTests/Server/Documents/Indexing/Auto/BasicAutoMapIndexing.cs
Labels: v6.0

#16559 RavenDB-20395: SlowTests.Server.Documents.PeriodicBackup.Retention.can_delete_backups_by_date_s3
  test/SlowTests/Server/Documents/PeriodicBackup/Retention.cs
Labels: v5.2

#16560 RavenDB-20567 / RavenDB-20550 Skipping tests using async commit on 32bits. This is not supported.
  test/FastTests/Voron/Bugs/RavenDB_8036.cs
  test/FastTests/Voron/Optimizations/EarlyLockRelease.cs
  test/SlowTests/Voron/Issues/RavenDB_13640.cs
  test/SlowTests/Voron/Storage/RavenDB7698.cs
Labels: v5.4

#16558 RavenDB-20563 updated Parquet.Net to 4.12.0
  src/Raven.Server/Documents/ETL/EtlProcess.cs
  src/Raven.Server/Documents/ETL/Providers/OLAP/ParquetTransformedItems.cs
  src/Raven.Server/Documents/Queries/QueryMetadata.cs
  src/Raven.Server/Raven.Server.csproj
  test/FastTests/Corax/Bugs/IndexEntryReaderBigDoc.cs
  test/SlowTests/Corax/Bugs/CompactTreeAddAndRemove.cs
  test/SlowTests/Issues/RavenDB-17157.cs
  test/SlowTests/Server/Documents/ETL/Olap/AzureTests.cs
  test/SlowTests/Server/Documents/ETL/Olap/GoogleCloudTests.cs
  test/SlowTests/Server/Documents/ETL/Olap/LocalTests.cs
  test/SlowTests/Server/Documents/ETL/Olap/S3Tests.cs
  test/SlowTests/Sharding/ETL/ShardedEtlTests.cs
  test/StressTests/Corax/Bugs/CompactTreeOptimizedLookup.cs
  test/StressTests/Server/Documents/ETL/Olap/LocalTestsStress.cs
Labels: v6.0

#16557 RavenDB-20466 Set the transaction holder for read transactions as well
  src/Voron/StorageEnvironment.cs
Labels: v5.4

#16561 5.4 to 6.0 merge
  build.ps1
  scripts/archive.ps1
  src/Raven.Server/Raven.Server.csproj
  src/Sparrow.Server/Platform/Posix/sysinfo_t.cs
  test/FastTests/Voron/Bugs/RavenDB_8036.cs
  test/FastTests/Voron/Optimizations/EarlyLockRelease.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Retention.cs
  test/SlowTests/Voron/Issues/RavenDB_13640.cs
  test/SlowTests/Voron/Storage/RavenDB7698.cs
Labels: v6.0

#16562 RavenDB-7070 re-enabled tests for both Lucene and Corax
  test/SlowTests/Issues/RavenDB-17250.cs
  test/SlowTests/Issues/RavenDB-18594.cs
  test/SlowTests/Issues/RavenDB-19426.cs
  test/SlowTests/Issues/RavenDB_12650.cs
  test/SlowTests/Issues/RavenDB_18357.cs
  test/SlowTests/Issues/RavenDb827.cs
  test/SlowTests/Tests/Faceted/Aggregation.cs
Labels: v5.4

#16563 RavenDB-20456 If we fail during abstract pager creation (file creation) then we need to dispose the underlying handle / stream
  src/Voron/Impl/Paging/RvnMemoryMapPager.cs
  src/Voron/Impl/Paging/Windows32BitsMemoryMapPager.cs
  src/Voron/Platform/Posix/Posix32BitsMemoryMapPager.cs
  src/Voron/Platform/Posix/PosixTempMemoryMapPager.cs
  src/Voron/Platform/Win32/WindowsMemoryMapPager.cs
Labels: v5.4

#16571 RavenDB-20588 MySQL import configuration broken
  src/Raven.Studio/wwwroot/App/views/database/tasks/importDatabaseFromSql.html
Labels: v5.4, Studio

#16572 RavenDB-20594 pinned boostrap version
  src/Raven.Studio/package-lock.json
  src/Raven.Studio/package.json
Labels: v6.0, Studio
