Repository ravendb/ravendb, pull requests merged in 2023-08, with the labels that each got.

#16948 RavenDB-20973 Fix description for SkippedResults param
  src/Raven.Client/Documents/Session/QueryStatistics.cs
Labels: v5.4

#16957 RavenDB-20939 Corax indexes should be able to specify storage option …
  src/Raven.Studio/typescript/models/database/index/indexFieldOptions.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/editIndex.ts
  src/Raven.Studio/wwwroot/App/views/database/indexes/editIndex.html
Labels: v6.0, Studio

#16941 RavenDB-20971 Validation message swap min and max
  src/Raven.Studio/typescript/components/common/shell/setup.ts
Labels: v6.0, Studio

#16747 RavenDB-20735 Cluster nodes graph cut on /studio/index.html#admin/set…
  src/Raven.Studio/typescript/models/database/cluster/clusterGraph.ts
  src/Raven.Studio/typescript/viewmodels/manage/cluster.ts
Labels: v6.0, Studio

#16952 RavenDB-19337 Upgrade to Jint 3.0.0-beta-2050
  src/Raven.Server/Documents/Patch/JintNullPropagationReferenceResolver.cs
  src/Raven.Server/Documents/Patch/JintPreventResolvingTasksReferenceResolver.cs
  src/Raven.Server/Documents/Patch/JsBlittableBridge.cs
  src/Raven.Server/Documents/Queries/QueryMetadata.cs
  src/Raven.Server/Documents/TcpHandlers/SubscriptionConnection.cs
  src/Raven.Server/Raven.Server.csproj
Labels: v6.0

#16950 RavenDB-20715 - SlowTests.Client.Attachments.AttachmentsReplication.A…
  test/SlowTests/Client/Attachments/AttachmentsReplication.cs
Labels: v6.0

#16946 RavenDB-20961: fix failing test
  test/SlowTests/Sharding/Cluster/SubscriptionsWithReshardingTests.cs
  test/SlowTests/Sharding/Subscriptions/ShardedSubscriptionSlowTests.cs
Labels: v6.0

#16886 RavenDB_19900: added an option to modify the timeout of GetDatabaseTo…
  src/Raven.Client/Http/RavenCommand.cs
  src/Raven.Client/Http/RequestExecutor.cs
  test/SlowTests/Issues/RavenDB_19900.cs
Labels: v5.4

#16963 RavenDB-19581 - update regions
  src/Raven.Studio/typescript/models/database/tasks/periodicBackup/amazonSettings.ts
Labels: v5.4, Studio

#16964 RavenDB-7070: Remove Debug.Assert due to floating-point encoding. In the case of big numbers (like Ticks), it can lead to having different numbers.
  src/Corax/IndexWriter.cs
  test/FastTests/Corax/IndexSearcher.cs
Labels: v6.0

#16947 RavenDB-20960 SlowTests.Issues.RavenDB_20783.NullTimerInRecordFastest
  src/Raven.Client/Documents/Conventions/DocumentConventions.cs
  src/Raven.Client/Http/RequestExecutor.cs
  test/SlowTests/Issues/RavenDB-20783.cs
Labels: v5.4

#16970 RavenDB-20991: Clicking the Abort button for a one-time manual backup doesn't interrupt the backup process
  src/Raven.Server/Web/System/OngoingTasksHandler.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
Labels: v5.4

#16967 RavenDB-20752 - SlowTests.Client.Attachments.AttachmentsReplication.P…
  test/SlowTests/Client/Attachments/AttachmentsReplication.cs
Labels: v6.0

#16965 RavenDB-20918 Move dictionary training from initialization into indexing thread for better UX.
  src/Raven.Client/Documents/Indexes/IndexingOperation.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxIndexPersistence.cs
  src/Raven.Server/Documents/Indexes/Persistence/IndexPersistenceBase.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/LuceneIndexPersistence.cs
Labels: Corax, v6.0

#16969 RavenDB-20979 Use` PulsedTransactionEnumerator` during the dictionary …
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxDocumentTrainEnumerator.cs
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxDocumentTrainSourceEnumerator.cs
  src/Voron/Data/Tables/Table.cs
  test/SlowTests/Issues/RavenDB-20979.cs
Labels: Corax, v6.0

#16977 RavenDB-20529 Corax: can include NULL value in facet results.
  test/SlowTests/Issues/RavenDB-20529.cs
Labels: Corax, v6.0

#16979 RavenDB-20990 Allow to make Proximity Search with distance 0
  src/Raven.Client/Documents/Session/AbstractDocumentQuery.cs
  src/Raven.Client/Documents/Session/IDocumentQueryBase.cs
  test/SlowTests/Issues/RavenDB_20990.cs
Labels: v5.4

#16988 RavenDB-20983 Release and version bump should be done separately from…
  build.ps1
  publish-stable-release.ps1
Labels: v5.2

#16987 RavenDB-20974 Add word-break to index name in modal
  src/Raven.Studio/wwwroot/App/views/database/indexes/indexStalenessReasons.html
Labels: v5.4, Studio

#16985 RavenDB-21000 Making sure that we'll wait for a task (with 30 seconds timeout) so we won't leak it
  src/Raven.Server/Background/BackgroundWorkBase.cs
Labels: v5.4

#16973 RavenDB-18224: drop ActiveBatchesFromSender for RecordBatchSubscriptionDocumentsCommand
  src/Raven.Server/Documents/Sharding/Subscriptions/ShardedDocumentsDatabaseSubscriptionProcessor.cs
  src/Raven.Server/Documents/Subscriptions/Processor/AbstractSubscriptionProcessor.cs
  src/Raven.Server/Documents/Subscriptions/Processor/DocumentsDatabaseSubscriptionProcessor.cs
  src/Raven.Server/Documents/Subscriptions/Processor/ISubscriptionProcessor.cs
  src/Raven.Server/Documents/Subscriptions/Processor/OrchestratedSubscriptionProcessor.cs
  src/Raven.Server/Documents/Subscriptions/Processor/RevisionsDatabaseSubscriptionProcessor.cs
  src/Raven.Server/Documents/Subscriptions/Processor/TestSubscriptionProcessor.cs
  src/Raven.Server/Documents/Subscriptions/Sharding/SubscriptionConnectionsStateForShard.cs
  src/Raven.Server/Documents/Subscriptions/SubscriptionConnectionsState.cs
  src/Raven.Server/Documents/TcpHandlers/SubscriptionConnection.cs
  src/Raven.Server/ServerWide/Commands/Subscriptions/RecordBatchSubscriptionDocumentsCommand.cs
Labels: v6.0

#16975 RavenDB-20755 - SlowTests.Server.Replication.AutomaticConflictResolut…
  test/SlowTests/Server/Replication/ReplicationAutomaticConflictResolution.cs
Labels: v6.0

#16976 RavenDB-20997 remove node from cluster should not delete sharded database
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  test/SlowTests/Sharding/ShardingTopologyTests.cs
Labels: v6.0

#16978 RavenDB-20481 Corax OR query: support for not equals | Test adjustment.
  src/Raven.Server/Documents/Indexes/Persistence/Corax/QueryOptimizer/CoraxBooleanQueryBase.cs
  test/SlowTests/MailingList/Oregon.cs
Labels: Corax, v6.0

#16980 RavenDB-7070: Use local context instead of static to avoid deadlocks in parallel test execution.
  test/FastTests/Corax/Bugs/RavenDB-19283.cs
  test/FastTests/Corax/DynamicFieldsTests.cs
  test/FastTests/Corax/SpatialTests.cs
Labels: Corax, v6.0

#16990 RavenDB-20999 Fixing heap corruption when we are dealing with a lot o…
  src/Sparrow.Server/ByteString.cs
  src/Voron/Data/PostingLists/NativeIntegersList.cs
  test/FastTests/Corax/Bugs/PostingListSize.cs
Labels: Corax, v6.0

#16989 RavenDB-20977 Text overflow in Query Timings
  src/Raven.Studio/typescript/common/timingsChart.ts
  src/Raven.Studio/wwwroot/App/views/database/query/query.html
  src/Raven.Studio/wwwroot/App/views/manage/queryTimingsDialog.html
  src/Raven.Studio/wwwroot/Content/css/pages/query.less
  src/Raven.Studio/wwwroot/Content/css/styles-common.less
Labels: v5.4, Studio

#16991 RavenDB-20866 - SlowTests.Sharding.BucketMigration.DocumentsMigration…
  src/Raven.Server/Documents/Sharding/Handlers/ShardedOutgoingReplicationHandler.cs
Labels: v6.0

#16997 RavenDB-20839 - fix failing test - CanImportRevisions1
  test/SlowTests/Smuggler/LegacySmugglerTests.cs
Labels: v6.0

#16993 RavenDB-20972 Projection does not return the @id metadata property
  src/Raven.Server/Documents/Document.cs
  src/Raven.Server/Documents/Queries/Results/QueryResultRetrieverBase.cs
  test/SlowTests/Issues/RavenDB-20972.cs
Labels: v5.4

#17000 RavenDB-21009 - Fix RavenDB_20425 failing tests on 6.0
  test/FastTests/Utils/RevisionsHelper.cs
  test/SlowTests/RavenDB-20425.cs
Labels: v6.0

#17005 RavenDB-21028: skip 4.x Interversion tests on linux, categorize and fix Interversion smuggler tests
  test/InterversionTests/BasicTests.cs
  test/InterversionTests/MixedClusterTests.cs
  test/InterversionTests/RavenDB-17518.cs
  test/InterversionTests/RavenDB-17556.cs
  test/InterversionTests/ReplicationTests.cs
  test/InterversionTests/SmugglerTests.cs
  test/Tests.Infrastructure/InterversionTest/ServerBuildRetriever.cs
  test/Tests.Infrastructure/RavenTestCategory.cs
Labels: v6.0

#16986 RavenDB-20821 Reducing memory usage when skipping huge number of compressed docs / revisions during replication
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Handlers/Streaming/StreamingHandler.cs
  src/Raven.Server/Documents/Queries/Dynamic/CollectionQueryRunner.cs
  src/Raven.Server/Documents/Replication/ReplicationDocumentSender.cs
  src/Raven.Server/Documents/Replication/ReplicationItems/DocumentReplicationItem.cs
  src/Raven.Server/Documents/Replication/ReplicationItems/ReplicationBatchItem.cs
  src/Raven.Server/Smuggler/Documents/DatabaseSource.cs
  src/Raven.Server/Utils/Enumerators/PulsedTransactionEnumerator.cs
  src/Raven.Server/Utils/Enumerators/TransactionForgetAboutDocumentEnumerator.cs
  src/Voron/Impl/Transaction.cs
Labels: v5.4

#16998 RavenDB-20956 - NRE at /databases/*/debug/replication/all-items becau…
  src/Raven.Server/Documents/Replication/ReplicationItems/CounterReplicationItem.cs
  src/Raven.Server/Documents/Replication/ReplicationItems/DocumentReplicationItem.cs
  src/Raven.Server/Documents/Replication/ReplicationItems/RevisionTombstoneReplicationItem.cs
  src/Raven.Server/Documents/Replication/ReplicationItems/TimeSeriesReplicationItem.cs
Labels: v6.0

#17003 RavenDB-20909 - Proxy command loops forever when the targeted node is down
  test/RachisTests/AddNodeToClusterTests.cs
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
Labels: v6.0

#17001 5.4 to 6.0 merge
  build.ps1
  publish-stable-release.ps1
  src/Raven.Client/Documents/BulkInsert/BulkInsertOperation.cs
  src/Raven.Client/Documents/BulkInsert/BulkInsertOptions.cs
  src/Raven.Client/Documents/Commands/Batches/ICommandData.cs
  src/Raven.Client/Documents/Commands/GetDocumentsCommand.cs
  src/Raven.Client/Documents/Conventions/DocumentConventions.cs
  src/Raven.Client/Documents/Operations/Backups/PeriodicBackupConfiguration.cs
  src/Raven.Client/Documents/Operations/CompareExchange/CompareExchangeValue.cs
  src/Raven.Client/Documents/Operations/CompareExchange/CompareExchangeValueResultParser.cs
  src/Raven.Client/Documents/Session/AbstractDocumentQuery.cs
  src/Raven.Client/Documents/Session/ClusterTransactionSession.cs
  src/Raven.Client/Documents/Session/IDocumentQueryBase.cs
  src/Raven.Client/Documents/Session/InMemoryDocumentSessionOperations.cs
  src/Raven.Client/Documents/Session/Operations/LoadOperation.cs
  src/Raven.Client/Documents/Session/Operations/QueryOperation.cs
  src/Raven.Client/Exceptions/Documents/BulkInsert/BulkInsertClientException.cs
  src/Raven.Client/Exceptions/Documents/BulkInsert/BulkInsertInvalidOperationException.cs
  src/Raven.Client/Http/RequestExecutor.cs
  src/Raven.Client/Util/StreamWithTimeout.cs
  src/Raven.Server/Background/BackgroundWorkBase.cs
  src/Raven.Server/Documents/Document.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/Handlers/Batches/BatchRequestParser.cs
  src/Raven.Server/Documents/Handlers/DocumentHandler.cs
  src/Raven.Server/Documents/Handlers/Processors/Documents/AbstractDocumentHandlerProcessorForGet.cs
  src/Raven.Server/Documents/Handlers/Processors/Documents/DocumentHandlerProcessorForGet.cs
  src/Raven.Server/Documents/Includes/IncludeCompareExchangeValuesCommand.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Queries/Dynamic/CollectionQueryRunner.cs
  src/Raven.Server/Documents/Queries/Results/QueryResultRetrieverBase.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Documents/ShardedDocumentHandlerProcessorForGet.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/TimeSeries/ShardedTimeSeriesHandlerProcessorForGetTimeSeries.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/TimeSeries/ShardedTimeSeriesHandlerProcessorForGetTimeSeriesRanges.cs
  src/Raven.Server/Documents/Sharding/Operations/FetchDocumentsFromShardsOperation.cs
  src/Raven.Server/Documents/Sharding/Queries/AbstractShardedQueryProcessor.cs
  src/Raven.Server/Json/BlittableJsonTextWriterExtensions.cs
  src/Raven.Server/ServerWide/Commands/PeriodicBackup/UpdatePeriodicBackupCommand.cs
  src/Raven.Server/ServerWide/Commands/PutServerWideBackupConfigurationCommand.cs
  src/Raven.Server/Utils/BackupUtils.cs
  src/Raven.Server/Web/System/OngoingTasksHandler.cs
  src/Raven.Studio/typescript/common/timingsChart.ts
  src/Raven.Studio/typescript/models/database/tasks/periodicBackup/amazonSettings.ts
  src/Raven.Studio/typescript/models/database/tasks/periodicBackup/backupConfiguration.ts
  src/Raven.Studio/typescript/models/database/tasks/periodicBackup/periodicBackupConfiguration.ts
  src/Raven.Studio/wwwroot/App/views/database/indexes/indexStalenessReasons.html
  src/Raven.Studio/wwwroot/App/views/database/query/query.html
  src/Raven.Studio/wwwroot/App/views/manage/queryTimingsDialog.html
  src/Raven.Studio/wwwroot/Content/css/pages/query.less
  src/Raven.Studio/wwwroot/Content/css/styles-common-scoped.less
  test/FastTests/Client/BulkInserts.cs
  test/SlowTests/Client/Attachments/BulkInsertAttachments.cs
  test/SlowTests/Client/TimeSeries/BulkInsert/BulkInsert.cs
  test/SlowTests/Client/TimeSeries/BulkInsert/TypedBulkInsert.cs
  test/SlowTests/Issues/RavenDB-17745.cs
  test/SlowTests/Issues/RavenDB-19629.cs
  test/SlowTests/Issues/RavenDB-20783.cs
  test/SlowTests/Issues/RavenDB-20972.cs
  test/SlowTests/Issues/RavenDB_20990.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
Labels: v6.0

#17009 RavenDB-21051 - InterversionTests.MixedClusterTests.IncrementalUpgrade
  test/Tests.Infrastructure/InterversionTest/UpgradeTestSuit.cs
Labels: v6.0

#17007 RavenDB-21052 In case of border element we've to swap "arrays" to check if there is a gap | apply mask to value in array to avoid "fake" gap
  src/Corax/Queries/Meta/SortHelper.cs
  src/Corax/Queries/SortingMatches/SortingMatch.cs
  test/FastTests/Corax/Bugs/RavenDB-21052.cs
Labels: v6.0

#16968 RavenDB-18224: add more details & fix NRE in GetSubscriptionResend endpoint
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Handlers/SubscriptionsHandler.cs
  src/Raven.Server/Documents/Subscriptions/SubscriptionStorage.cs
  src/Voron/Data/Tables/TableValueReader.cs
  test/RachisTests/AddNodeToClusterTests.cs
  test/SlowTests/Client/Subscriptions/ConcurrentSubscriptionsTests.cs
Labels: v5.4

#17008 RavenDB-20501 - SlowTests.Client.Attachments.AttachmentsReplication.D…
  test/SlowTests/Client/Attachments/AttachmentsReplication.cs
Labels: v6.0

#17015 RavenDB-17745 Reduce test time
  test/SlowTests/Issues/RavenDB-17745.cs
Labels: v5.4

#17017 RavenDB-21054 Map-Reduce Visualizer Text Overflow
  src/Raven.Studio/wwwroot/App/views/database/indexes/visualizer/visualizer.html
  src/Raven.Studio/wwwroot/Content/css/styles-common-scoped.less
Labels: v6.0, Studio

#17022 RavenDB-16201 Kafka and RabbitMQ Sink support (studio filter by state)
  src/Raven.Studio/typescript/components/pages/database/tasks/ongoingTasks/OngoingTasksFilter.tsx
  src/Raven.Studio/typescript/components/pages/database/tasks/ongoingTasks/OngoingTasksPage.tsx
Labels: v6.0, Studio

#17016 RavenDB-21029 Storage widget icons
  src/Raven.Studio/wwwroot/App/views/resources/widgets/storageWidget.html
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon/ravendb-data.svg
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon/storage-free.svg
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon/storage-used.svg
  src/Raven.Studio/wwwroot/Content/css/pages/cluster-dashboard.less
Labels: v6.0, Studio

#17024 RavenDB-21053 added 'Http.Http2.MaxStreamsPerConnection' configuration option and changed default from 100 to unlimited
  src/Raven.Server/Config/Categories/HttpConfiguration.cs
  src/Raven.Server/RavenServer.cs
Labels: v5.4

#17026 RavenDB-20992 We should not provide the ability to delay a one-time m…
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/smugglerDatabaseDetails.ts
Labels: v5.4, Studio

#17030 RavenDB-20965 - Can't recover from entire shard being in Rehab
  src/Raven.Server/ServerWide/Maintenance/ClusterObserver.cs
  test/SlowTests/Sharding/Cluster/ShardedClusterObserverTests.cs
  test/Tryouts/Program.cs
Labels: v6.0

#17035 RavenDB-20852 - SlowTests.Client.TimeSeries.Policies.TimeSeriesConfig…
  test/SlowTests/Client/TimeSeries/Policies/TimeSeriesConfigurationTests.cs
Labels: v6.0

#17031 RavenDB-21057 - Wrong collection at /databases/*/debug/replication/al…
  src/Raven.Server/Documents/Replication/ReplicationItems/DocumentReplicationItem.cs
Labels: v6.0

#17032 RavenDB-20754 - SlowTests.Server.Replication.AutomaticConflictResolut…
  test/SlowTests/Server/Replication/ReplicationAutomaticConflictResolution.cs
Labels: v6.0

#17050 RavenDB-7070 added SecPageTables to MemInfo
  src/Raven.Server/Platform/Posix/MemInfoReader.cs
Labels: v5.2

#17044 RavenDB-20931 - SlowTests.Sharding.Replication.ShardedExternalReplica…
  test/SlowTests/Sharding/Replication/ShardedExternalReplicationTests.cs
Labels: v6.0

#17040 RavenDB-21087 Fixing few issues in SliceSmallSet:
  src/Voron/Impl/SliceSmallSet.cs
  test/FastTests/Corax/Bugs/RavenDB_21087.cs
Labels: Corax, v6.0

#17055 RavenDB-21027 Reset bitset for each document in `AllIn`.
  src/Corax/Queries/UnaryMatch.Ordinal.cs
  test/FastTests/Corax/RavenIntegration.cs
Labels: Corax, v6.0

#17051 RavenDB-21005 "Start indexing" on an errored index doesn't start it
  src/Raven.Studio/typescript/components/pages/database/indexes/list/BulkIndexOperationConfirm.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/list/useIndexesPage.tsx
Labels: v6.0, Studio

#17058 RavenDB-21072 Ongoing tasks view doesn't work in mixed cluster
  src/Raven.Studio/typescript/commands/database/tasks/getOngoingTasksCommand.ts
Labels: v6.0, Studio

#17063 RavenDB-21110 & RavenDB-21111 & RavenDB-21109 Clear native list to avoid accessing memory from already disposed allocator.
  src/Corax/IndexWriter.cs
Labels: Corax, v6.0

#17064 RavenDB-21030 Storage report: Close/back button missing on Select Sha…
  src/Raven.Studio/typescript/viewmodels/common/sharding/shardSelector.ts
  src/Raven.Studio/typescript/viewmodels/common/sharding/shardingContext.ts
  src/Raven.Studio/wwwroot/App/views/common/sharding/shardSelector.html
Labels: v6.0, Studio

#17052 RavenDB-20079 Default DateTime value in IndexDefinition map is stored as default(DateTime)
  src/Raven.Client/Documents/Indexes/ExpressionStringBuilder.cs
  test/SlowTests/Issues/RavenDB_20079.cs
Labels: v5.4

#17065 5.4 to 6.0 merge
  src/Raven.Client/Documents/Operations/Operation.cs
  src/Raven.Client/Documents/Smuggler/DatabaseSmuggler.cs
  src/Raven.Server/Config/Categories/HttpConfiguration.cs
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Handlers/Batches/Commands/MergedBatchCommand.cs
  src/Raven.Server/Documents/Handlers/Processors/OngoingTasks/OngoingTasksHandlerProcessorForBackupDatabaseOnce.cs
  src/Raven.Server/Documents/Handlers/Processors/Streaming/StreamingHandlerProcessorForGetDocs.cs
  src/Raven.Server/Documents/Patch/ScriptRunner.cs
  src/Raven.Server/Documents/Queries/Dynamic/CollectionQueryRunner.cs
  src/Raven.Server/Documents/Replication/ReplicationItems/DocumentReplicationItem.cs
  src/Raven.Server/Documents/Replication/ReplicationItems/ReplicationBatchItem.cs
  src/Raven.Server/Documents/Replication/Senders/MigrationReplicationDocumentSender.cs
  src/Raven.Server/Documents/Replication/Senders/ReplicationDocumentSenderBase.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Server/RavenServer.cs
  src/Raven.Server/Smuggler/Documents/DatabaseSource.cs
  src/Raven.Server/Utils/Enumerators/PulsedTransactionEnumerator.cs
  src/Raven.Server/Utils/Enumerators/TransactionForgetAboutDocumentEnumerator.cs
  src/Raven.Studio/typescript/common/copyToClipboard.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/alerts/etlTransformOrLoadErrorDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/smugglerDatabaseDetails.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/additionalAssemblySyntax.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/additionalSourceSyntax.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/mapIndexSyntax.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/mapReduceIndexSyntax.ts
  src/Raven.Studio/typescript/viewmodels/database/patch/patchSyntax.ts
  src/Raven.Studio/typescript/viewmodels/database/query/querySyntax.ts
  src/Raven.Studio/typescript/viewmodels/database/settings/conflictResolutionScriptSyntax.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/queueSinkSyntax.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/subscriptionRqlSyntax.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/transformationScriptSyntax.ts
  src/Raven.Studio/typescript/viewmodels/manage/threadStackTrace.ts
  src/Raven.Studio/typescript/viewmodels/resources/setupEncryptionKey.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/columnPreviewPlugin.ts
  src/Raven.Studio/wwwroot/App/views/common/notificationCenter/detailViewer/operations/smugglerDatabaseDetails.html
  src/Voron/Impl/Transaction.cs
  test/SlowTests/Issues/RavenDB-17745.cs
  test/SlowTests/Issues/RavenDB-21028.cs
  test/SlowTests/Issues/RavenDB-4840.cs
  test/SlowTests/Issues/RavenDB_20084.cs
  test/SlowTests/Server/NotificationCenter/HugeDocuments.cs
Labels: v6.0

#17066 RavenDB-21138 Add support for sharded databases in studio test index …
  src/Raven.Studio/typescript/commands/database/index/testIndexCommand.ts
  src/Raven.Studio/typescript/models/database/index/testIndex.ts
  src/Raven.Studio/typescript/viewmodels/common/sharding/inlineShardSelector.ts
  src/Raven.Studio/typescript/viewmodels/common/sharding/shardSelector.ts
  src/Raven.Studio/typescript/viewmodels/common/sharding/shardingContext.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/editIndex.ts
  src/Raven.Studio/wwwroot/App/views/common/sharding/inlineShardSelector.html
  src/Raven.Studio/wwwroot/App/views/common/sharding/shardSelector.html
  src/Raven.Studio/wwwroot/App/views/database/indexes/editIndex.html
Labels: v6.0, Studio

#17074 RavenDB-21132: Marvin fails when pointer is null.
  src/Sparrow/Hashing.cs
  test/FastTests/Sparrow/Hashing.cs
Labels: v5.4

#17069 RavenDB-21143: Fixed sized cache and improved codegen
  src/Corax/Queries/MultiTermMatch.cs
  src/Corax/Queries/SortingMatches/SortingMatch.cs
  src/Corax/Queries/SortingMatches/SortingMultiMatch.cs
  src/Voron/PageLocator.cs
  src/Voron/TransactionPersistentContext.cs
Labels: v6.0

#17068 RavenDB-21142 TreeCursor: allocate FastStack via ObjectPool to avoid expensive Array.Resize calls
  src/Voron/Data/BTrees/TreeCursor.cs
Labels: v6.0

#17072 RavenDB-21144: Improvements for PageTable
  src/Sparrow.Server/AdvMemory.cs
  src/Sparrow.Server/Collections/LockFree/Counter32.cs
  src/Sparrow.Server/Collections/LockFree/Counter64.cs
  src/Sparrow.Server/Collections/LockFree/CounterBase.cs
  src/Sparrow.Server/Collections/LockFree/DictionaryImpl.Enumerators.cs
  src/Sparrow.Server/Collections/LockFree/DictionaryImpl.cs
  src/Sparrow.Server/Collections/LockFree/DictionaryImplBoxed.cs
  src/Sparrow.Server/Collections/LockFree/DictionaryImplInt.cs
  src/Sparrow.Server/Collections/LockFree/DictionaryImplIntPtr.cs
  src/Sparrow.Server/Collections/LockFree/DictionaryImplLong.cs
  src/Sparrow.Server/Collections/LockFree/DictionaryImplRef.cs
  src/Sparrow.Server/Collections/LockFree/DictionaryImplUInt.cs
  src/Sparrow.Server/Collections/LockFree/DictionaryImplULong.cs
  src/Sparrow.Server/Collections/LockFree/DictionaryImpl`2.cs
  src/Sparrow.Server/Collections/LockFree/DictionaryImpl`3.cs
  src/Sparrow.Server/Collections/LockFree/LICENSE
  src/Sparrow.Server/Collections/LockFree/LockFreeConcurrentDictionary.cs
  src/Sparrow.Server/Collections/LockFree/Readme.md
  src/Voron/Util/PageTable.cs
Labels: v6.0

#17086 RavenDB-21165 Test index results view doesn't show results
  src/Raven.Studio/typescript/viewmodels/database/indexes/editIndex.ts
Labels: v6.0, Studio

#17087 Revert "RavenDB-20628 - Cluster wide transaction : throw `TaskCanceledException` when fails on timeout"
  src/Raven.Client/Http/ServerNode.cs
  src/Raven.Client/ServerWide/Operations/BuildNumber.cs
  src/Raven.Server/Commercial/LicenseManager.cs
  src/Raven.Server/Documents/ClusterTransactionWaiter.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Handlers/BatchHandler.cs
  src/Raven.Server/Rachis/RachisLogHistory.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/Commands/ClusterTransactionCommand.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/ServerWide/ServerVersion.cs
  src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
  src/Raven.Server/Web/System/DatabasesHandler.cs
  test/InterversionTests/MixedClusterTestBase.cs
  test/InterversionTests/RavenDB-20628-Interversion.cs
  test/SlowTests/Issues/RavenDB-20628.cs
  test/Tests.Infrastructure/InterversionTestBase.cs
Labels: v5.4

#17096 RavenDB-21177 Discard frequency in PostingList during Lookup-Fill Mul…
  src/Corax/Queries/MultiTermMatch.cs
Labels: Corax, v6.0

#17095 RavenDB-21157 IOException is expected
  test/SlowTests/Issues/RavenDB-21028.cs
Labels: v5.4

#17097 RavenDB-21159 : flaky test adjustments
  test/SlowTests/Sharding/ETL/ShardedEtlFailoverTests.cs
  test/Tests.Infrastructure/RavenTestBase.Etl.cs
  test/Tests.Infrastructure/RavenTestBase.ShardedEtlTestBase.cs
Labels: v6.0

#17105 RavenDB-21167 we need to write metadata as is, if it goes through WriteMetadata extension method then it takes internal properties from the Document resulting in duplicate values in json with a lot of nulls
  src/Raven.Server/Web/Studio/Processors/AbstractStudioCollectionsHandlerProcessorForPreviewCollection.cs
  src/Raven.Server/Web/Studio/Processors/StudioCollectionsHandlerProcessorForPreviewCollection.cs
  src/Raven.Server/Web/Studio/Sharding/Processors/ShardedStudioCollectionsHandlerProcessorForPreviewCollection.cs
Labels: v6.0

#17104 RavenDB-20978 fixed issue with executing facet query on map-reduce index, facet operations should not be detected as projections
  src/Raven.Server/Documents/Sharding/Queries/AbstractShardedQueryProcessor.cs
  test/SlowTests/Issues/RavenDB_20978.cs
Labels: v6.0

#17106 5.4 to 6.0 merge
  src/Raven.Client/Documents/Indexes/ExpressionStringBuilder.cs
  src/Sparrow/Hashing.cs
  test/FastTests/Sparrow/Hashing.cs
  test/SlowTests/Issues/RavenDB-21028.cs
  test/SlowTests/Issues/RavenDB_20079.cs
Labels: v6.0

#17103 RavenDB-21185: Simplified and added extra diagnostics to the PageLocator
  src/Voron/Data/Containers/Container.cs
  src/Voron/Impl/LowLevelTransaction.cs
  src/Voron/PageLocator.cs
Labels: v6.0

#17118 RavenDB-19337 Replace PropertyDescriptor usage with JsValue in time series array creation
  src/Raven.Server/Documents/Indexes/Static/TimeSeries/TimeSeriesSegmentObjectInstance.cs
Labels: v6.0

#17116 RavenDB-20688: make sure we don't use disposed LazyStringValue and skip concurrent subscription test on sharding
  src/Raven.Server/Documents/Subscriptions/Processor/DocumentsDatabaseSubscriptionProcessor.cs
  test/StressTests/Rachis/SubscriptionsFailoverStress.cs
Labels: v6.0

#17107 RavenDB-21190 Track all updates when updating term references for EntryTermReader
  src/Corax/IndexWriter.cs
  test/FastTests/Corax/UpdateSameEntryTwiceInOneBatch.cs
Labels: Corax, v6.0

#17120 5.4 to 6.0 merge
  src/Raven.Server/Monitoring/ServerLimitsMonitor.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.17/ServerLimits.cs
  src/Raven.Server/Monitoring/Snmp/SnmpOids.cs
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
  src/Raven.Server/NotificationCenter/Notifications/AlertType.cs
  src/Raven.Server/NotificationCenter/Notifications/Details/ServerLimitsDetails.cs
  src/Raven.Server/Platform/Posix/LimitsReader.cs
  src/Raven.Server/ServerWide/ServerMetricCacher.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Utils/MetricCacher.cs
Labels: v6.0

#17119 RavenDB-21064 Utilities for License limitations in RavenDB 6.0
  src/Raven.Studio/typescript/components/utils/licenseLimitsUtils.tsx
Labels: v6.0, Studio

#17126 RavenDB-21080 both of the results have exact same score so there is no guarantee of order in the results
  test/SlowTests/Core/Indexing/MultiMap.cs
Labels: v6.0

#17129 RavenDB-21177 Decode entries during PostingListRead in SortingMatch
  src/Corax/Queries/MultiTermMatch.cs
  src/Corax/Queries/SortingMatches/SortingMatch.cs
  test/SlowTests/Corax/RavenDB-21177.cs
Labels: Corax, v6.0

#17132 RavenDB-21161 Arguments is null in case when random order has no parameter.
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxQueryBuilder.cs
  test/SlowTests/Issues/RavenDB_11257.cs
Labels: Corax, v6.0

#17099 RavenDB-20865 - RachisTests.AddNodeToClusterTests.AddingNodeToClusterUpdatesClusterRequestExecutorTopology_RavenDB_20702
  src/Raven.Server/ServerWide/ServerStore.cs
Labels: v6.0

#17138 RavenDB-20173 - SlowTests.Client.Operations.StudioOperationsTests.ShouldGetNotModifiedStatusForGetStudioCollectionFields
  src/Raven.Server/Documents/Handlers/Processors/Studio/AbstractStudioCollectionFieldsHandlerProcessorForGetCollectionFields.cs
  src/Raven.Server/Documents/Handlers/Processors/Studio/StudioCollectionFieldsHandlerProcessorForGetCollectionFields.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Studio/ShardedStudioCollectionFieldsHandlerProcessorForGetCollectionFields.cs
Labels: v6.0

#17137 5.4 to 6.0 merge
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/Commands/DelayBackupCommand.cs
  src/Raven.Server/ServerWide/Commands/ETL/DeleteEtlProcessStateCommand.cs
  src/Raven.Server/ServerWide/Commands/ETL/UpdateEtlProcessStateCommand.cs
  src/Raven.Server/ServerWide/Commands/IncrementClusterIdentitiesBatchCommand.cs
  src/Raven.Server/ServerWide/Commands/IncrementClusterIdentityCommand.cs
  src/Raven.Server/ServerWide/Commands/Monitoring/Snmp/UpdateSnmpDatabaseIndexesMappingCommand.cs
  src/Raven.Server/ServerWide/Commands/PeriodicBackup/UpdatePeriodicBackupStatusCommand.cs
  src/Raven.Server/ServerWide/Commands/Sharding/ShardedUpdateExternalReplicationStateCommand.cs
  src/Raven.Server/ServerWide/Commands/Subscriptions/AcknowledgeSubscriptionBatchCommand.cs
  src/Raven.Server/ServerWide/Commands/Subscriptions/DeleteSubscriptionCommand.cs
  src/Raven.Server/ServerWide/Commands/Subscriptions/PutSubscriptionCommand.cs
  src/Raven.Server/ServerWide/Commands/Subscriptions/RecordBatchSubscriptionDocumentsCommand.cs
  src/Raven.Server/ServerWide/Commands/Subscriptions/ToggleSubscriptionStateCommand.cs
  src/Raven.Server/ServerWide/Commands/Subscriptions/UpdateSubscriptionClientConnectionTime.cs
  src/Raven.Server/ServerWide/Commands/UpdateClusterIdentityCommand.cs
  src/Raven.Server/ServerWide/Commands/UpdateExternalReplicationStateCommand.cs
  src/Raven.Server/ServerWide/Commands/UpdateValueForDatabaseCommand.cs
  src/Raven.Studio/typescript/viewmodels/manage/trafficWatch.ts
  src/Sparrow/Utils/MemoryUtils.cs
  src/Voron/Data/Tables/Table.cs
  src/Voron/Data/Tables/TableValueCompressor.cs
Labels: v6.0

#17141 RavenDB-21217 Fix licenseType NRE
  src/Raven.Studio/typescript/models/auth/licenseModel.ts
  src/Raven.Studio/typescript/models/database/tasks/periodicBackup/backupConfiguration.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editPeriodicBackupTask.ts
  src/Raven.Studio/typescript/viewmodels/manage/createServerWideTask.ts
  src/Raven.Studio/typescript/viewmodels/manage/editServerWideBackup.ts
  src/Raven.Studio/typescript/viewmodels/manage/editServerWideExternalReplication.ts
Labels: v6.0, Studio

#17140 5.4 to 6.0 merge
  src/Raven.Server/Documents/PeriodicBackup/Restore/AbstractRestoreBackupTask.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
  test/SlowTests/Client/Subscriptions/ConcurrentSubscriptionsTests.cs
  test/SlowTests/Issues/RavenDB-16659.cs
Labels: v6.0

#17143 RavenDB-19967 Notification/warning about tombstone cleaner subscriber…
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/alerts/blockingTombstonesDetails.ts
Labels: v5.4, Studio

#17145 RavenDB-21219 - fix NRE in Dispose when database initialization fails
  src/Raven.Server/Documents/DocumentDatabase.cs
Labels: v5.4

#17142 RavenDB-21063 Fixing assertions in test
  test/SlowTests/Server/Documents/Queries/Dynamic/Map/DynamicQueriesEnumsNestedFieldsAndCollections.cs
Labels: v6.0

#17150 RavenDB-21005 "Start indexing" on an errored index doesn't start it
  src/Raven.Studio/typescript/components/pages/database/indexes/list/useIndexesPage.tsx
Labels: v6.0, Studio

#17151 RavenDB-21084 : Sharding - disable database doesn't remove the sharded database from ShardedDatabasesCache
  src/Raven.Server/Documents/DatabasesLandlord.cs
  test/SlowTests/Sharding/Issues/RavenDB_21084.cs
Labels: v6.0
