Repository ravendb/ravendb, pull requests merged in 2023-04, with the labels that each got.

#16163 RavenDB-20239 Huge document is download as text instead as a JSON
  src/Raven.Studio/typescript/viewmodels/database/documents/editDocument.ts
Labels: v5.2, Studio

#16162 RavenDB-20252 Database stats - values are hidden when value is zero
  src/Raven.Studio/typescript/components/pages/database/status/statistics/partials/IndexesDatabaseStats.tsx
Labels: v6.0, Studio

#16160 RavenDB-19772 Sharding - Backup - Delay
  src/Raven.Studio/typescript/components/pages/database/tasks/panels/PeriodicBackupPanel.tsx
Labels: v6.0, Studio

#16082 RDoc-2397 Document 6.0 docker Linux image breaking changes in readmes
  docker/readme.md
Labels: v6.0

#16165 RavenDB-19983 Added link in Studio to the cluster docs
  src/Raven.Studio/typescript/viewmodels/manage/cluster.ts
  src/Raven.Studio/wwwroot/App/views/manage/cluster.html
Labels: v5.4, Studio

#16166 RavenDB-19720 - Verify that deleting an orchestrator removes it from the `ShardedDatabasesCache`
  src/Raven.Server/Documents/DatabasesLandlord.cs
Labels: v6.0

#16171 RavenDB-20266 Revamp Create Sample Data View
  src/Raven.Studio/wwwroot/App/views/database/tasks/createSampleData.html
  src/Raven.Studio/wwwroot/Content/css/feedback.less
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon/magic-wand.svg
  src/Raven.Studio/wwwroot/Content/css/pages/sample-data.less
  src/Raven.Studio/wwwroot/Content/css/styles-common-scoped.less
  src/Raven.Studio/wwwroot/Content/img/documents.svg
  src/Raven.Studio/wwwroot/Content/img/feedback.svg
  src/Raven.Studio/wwwroot/Content/img/sample-data.png
  src/Raven.Studio/wwwroot/Content/img/shapes.svg
Labels: v6.0, Studio

#16183 5.2 to 5.4 merge
  src/Raven.Client/Http/NodeSelector.cs
  src/Raven.Client/Http/RequestExecutor.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/Handlers/Admin/AdminConfigurationHandler.cs
  src/Raven.Server/Documents/Handlers/StatsHandler.cs
  src/Raven.Studio/typescript/common/downloader.ts
  src/Raven.Studio/typescript/viewmodels/database/documents/editDocument.ts
  src/Raven.Studio/typescript/viewmodels/manage/infoPackage.ts
  src/Raven.Studio/wwwroot/App/views/manage/infoPackage.html
  src/Raven.Studio/wwwroot/Content/css/pages/info-package.less
  src/Raven.Studio/wwwroot/Content/css/styles-common.less
  src/Raven.Studio/wwwroot/Content/img/info_package.png
  src/Raven.Studio/wwwroot/Content/img/info_package.svg
  test/SlowTests/Issues/RavenDB_20202.cs
  tools/TypingsGenerator/Program.cs
Labels: v5.4

#16154 RavenDB-20247 - fix int overflow
  src/Sparrow.Server/Meters/GeneralWaitPerformanceMetrics.cs
  src/Sparrow.Server/Meters/PerformanceMetrics.cs
  src/Sparrow.Server/Meters/TransactionPerformanceMetrics.cs
Labels: v5.2

#16185 RavenDB-20255 Fix unnecessary scroll on Client Configuration page
  src/Raven.Studio/wwwroot/App/views/database/settings/clientConfiguration.html
  src/Raven.Studio/wwwroot/App/views/database/settings/revertRevisions.html
Labels: v6.0, Studio

#16190 RavenDB-20250 Client configuration - allow to select both options: 'U…
  src/Raven.Studio/typescript/models/database/settings/clientConfigurationModel.ts
Labels: v5.2, Studio

#16191 5.2 to 5.4 merge
  src/Raven.Client/Http/HttpCache.cs
  src/Raven.Studio/typescript/models/database/settings/clientConfigurationModel.ts
  src/Sparrow.Server/Meters/GeneralWaitPerformanceMetrics.cs
  src/Sparrow.Server/Meters/PerformanceMetrics.cs
  src/Sparrow.Server/Meters/TransactionPerformanceMetrics.cs
  test/FastTests/Client/HttpCacheTests.cs
Labels: v5.4

#16189 RavenDB-20282 Database appears to be NOT encrypted in the databases view
  src/Raven.Server/Web/System/Processors/Studio/StudioDatabasesHandlerForGetDatabases.cs
Labels: v6.0

#16187 RavenDB-20125 & RavenDB-19968 Ensure that `Indexes` methods are waiting for exceptions in test.
  test/SlowTests/Issues/RavenDB_18357.cs
Labels: Corax, v5.4

#16194 RavenDB-20280 Expose cluster topology in redux
  src/Raven.Studio/typescript/components/common/shell/clusterSlice.ts
  src/Raven.Studio/typescript/components/common/shell/databasesSlice.ts
  src/Raven.Studio/typescript/components/common/shell/setup.ts
  src/Raven.Studio/typescript/components/hooks/__mocks__/useClusterTopologyManager.ts
  src/Raven.Studio/typescript/components/hooks/hooksForAutoMock.json
  src/Raven.Studio/typescript/components/hooks/useClusterTopologyManager.ts
  src/Raven.Studio/typescript/components/pages/resources/databases/DatabasesPage.stories.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/DatabasesPage.tsx
  src/Raven.Studio/typescript/components/pages/resources/manageDatabaseGroup/ManageDatabaseGroupPage.stories.tsx
  src/Raven.Studio/typescript/components/pages/resources/manageDatabaseGroup/partials/useGroup.ts
  src/Raven.Studio/typescript/components/store.ts
  src/Raven.Studio/typescript/test/mocks/hooks/MockClusterTopologyManager.ts
  src/Raven.Studio/typescript/test/mocks/hooks/MockHooks.ts
  src/Raven.Studio/typescript/test/mocks/store/MockClusterManager.ts
  src/Raven.Studio/typescript/test/mocks/store/MockStore.ts
Labels: v6.0, Studio

#16198 RavenDB-20028 Minor fixes for MultiToggle component
  src/Raven.Studio/typescript/components/common/Toggles.scss
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/DatabasesFilter.scss
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/DatabasesFilter.tsx
  src/Raven.Studio/wwwroot/Content/scss/_colors.scss
  src/Raven.Studio/wwwroot/Content/scss/_custom-properties.scss
Labels: v6.0, Studio

#16196 RavenDB-20263 Improve LoadingView spinner
  src/Raven.Studio/typescript/components/common/LoadingView.tsx
  src/Raven.Studio/typescript/components/common/Spinners.stories.tsx
  src/Raven.Studio/wwwroot/Content/scss/_bs5extend.scss
Labels: v6.0, Studio

#16193 RavenDB-20262 /databases/*/indexes endpoint does not require nodeTag now
  src/Raven.Server/Documents/Handlers/IndexHandler.cs
  src/Raven.Server/Documents/Handlers/Processors/Indexes/AbstractIndexHandlerProcessorForGetAll.cs
  src/Raven.Server/Documents/Handlers/Processors/Indexes/IndexHandlerProcessorForGetAll.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Indexes/ShardedIndexHandlerProcessorForGetAll.cs
  test/SlowTests/Core/Commands/Indexes.cs
Labels: v6.0

#16200 RavenDB-20271 Databases view glitchy cluster info for a cluster where…
  src/Raven.Studio/typescript/components/common/shell/databasesSlice.ts
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/ValidDatabasePropertiesPanel.spec.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/ValidDatabasePropertiesPanel.tsx
  src/Raven.Studio/typescript/test/mocks/services/MockDatabasesService.ts
  src/Raven.Studio/typescript/test/stubs/DatabasesStubs.ts
Labels: v6.0, Studio

#16197 RavenDB-20222 when querying counters or timeseries index we need to use ConstantComparer by default, because there is no @last-modified field available
  src/Raven.Server/Documents/Sharding/Queries/AbstractShardedQueryProcessor.cs
  src/Raven.Server/Documents/Sharding/Queries/ShardedQueryProcessor.cs
  src/Raven.Server/Documents/Sharding/Queries/ShardedQueryProcessorBase.cs
  src/Raven.Server/Documents/Sharding/Queries/ShardedQueryStreamProcessor.cs
  test/SlowTests/Client/Indexing/Counters/BasicCountersIndexes_JavaScript.cs
  test/SlowTests/Client/Indexing/TimeSeries/BasicTimeSeriesIndexes_JavaScript.cs
Labels: v6.0

#16192 RavenDB-20267
  src/Raven.Client/Documents/Session/Operations/StreamOperation.cs
  test/SlowTests/Client/TimeSeries/Session/TimeSeriesStreamingTests.cs
Labels: v6.0

#16201 RavenDB-19886 added User-Agent to server-side HttpClients
  src/Raven.Server/Commercial/ApiHttpClient.cs
  src/Raven.Server/Commercial/LetsEncrypt/LetsEncryptSimulationHelper.cs
  src/Raven.Server/Commercial/LetsEncrypt/RavenDnsRecordHelper.cs
  src/Raven.Server/Commercial/LetsEncryptClient.cs
  src/Raven.Server/Commercial/SetupParameters.cs
  src/Raven.Server/Documents/PeriodicBackup/Azure/LegacyRavenAzureClient.cs
  src/Raven.Server/Documents/PeriodicBackup/RavenStorageClient.cs
  src/Raven.Server/RavenServer.cs
  src/Raven.Server/ServerWide/BackgroundTasks/LatestVersionCheck.cs
  src/Raven.Server/Smuggler/Documents/Handlers/SmugglerHandler.cs
  src/Raven.Server/Smuggler/Migration/AbstractLegacyMigrator.cs
  src/Raven.Server/Smuggler/Migration/ApiKey/Authenticator.cs
  src/Raven.Server/Smuggler/Migration/Importer.cs
  src/Raven.Server/Smuggler/Migration/Migrator.cs
  src/Raven.Server/Smuggler/Migration/MigratorOptions.cs
  src/Raven.Server/Utils/Cli/RavenCli.cs
  src/Raven.Server/Utils/RavenHttpClient.cs
  tools/rvn/rvn.csproj
Labels: v5.2

#16202 5.2 to 5.4 merge
  src/Raven.Server/Commercial/ApiHttpClient.cs
  src/Raven.Server/Commercial/LetsEncrypt/LetsEncryptSimulationHelper.cs
  src/Raven.Server/Commercial/LetsEncrypt/RavenDnsRecordHelper.cs
  src/Raven.Server/Commercial/LetsEncryptClient.cs
  src/Raven.Server/Commercial/SetupParameters.cs
  src/Raven.Server/Documents/PeriodicBackup/Azure/LegacyRavenAzureClient.cs
  src/Raven.Server/Documents/PeriodicBackup/RavenStorageClient.cs
  src/Raven.Server/RavenServer.cs
  src/Raven.Server/ServerWide/BackgroundTasks/LatestVersionCheck.cs
  src/Raven.Server/Smuggler/Documents/Handlers/SmugglerHandler.cs
  src/Raven.Server/Smuggler/Migration/AbstractLegacyMigrator.cs
  src/Raven.Server/Smuggler/Migration/ApiKey/Authenticator.cs
  src/Raven.Server/Smuggler/Migration/Importer.cs
  src/Raven.Server/Smuggler/Migration/Migrator.cs
  src/Raven.Server/Smuggler/Migration/MigratorOptions.cs
  src/Raven.Server/Utils/Cli/RavenCli.cs
  src/Raven.Server/Utils/RavenHttpClient.cs
  tools/rvn/rvn.csproj
Labels: v5.4

#16205 RavenDB-20226 support for decimal operations in reduce on LazyStringValue when index entries are requested
  src/Sparrow/Json/LazyStringValue.cs
  test/SlowTests/Sharding/Issues/RavenDB_20226.cs
Labels: v6.0

#16206 RavenDB-20287 allow to install prerelease NuGet packages
  src/Raven.Server/Config/Categories/IndexingConfiguration.cs
  src/Raven.Server/Documents/Indexes/Static/NuGet/MultiSourceNuGetFetcher.cs
  src/Raven.Server/Documents/Indexes/Static/NuGet/NuGetFetcher.cs
  src/Raven.Server/Program.cs
  test/SlowTests/Issues/RavenDB_15753.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v5.4

#16195 RavenDB-20238 exposed orchestrator info state in /studio-tasks/databases/state endpoint
  src/Raven.Server/Web/System/Processors/Studio/StudioDatabasesHandlerForGetDatabasesState.cs
  src/Raven.Studio/typescript/common/shell/databasesManager.spec.ts
  src/Raven.Studio/typescript/components/common/shell/databasesSlice.ts
  src/Raven.Studio/typescript/components/common/shell/setup.ts
  src/Raven.Studio/typescript/components/hooks/useLicenseStatus.ts
  src/Raven.Studio/typescript/components/models/databases.d.ts
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/DatabasePanel.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/ValidDatabasePropertiesPanel.spec.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/ValidDatabasePropertiesPanel.tsx
  src/Raven.Studio/typescript/test/mocks/services/MockDatabasesService.ts
  src/Raven.Studio/typings/_studio/dto.d.ts
Labels: v6.0

#16208 RavenDB-20046 comment out latest docker tags for the beta period
  docker/common.ps1
Labels: v6.0

#16211 RavenDB-20144 Neon `Lzcnt` is using 64 bit number (Intel LZCNT is using 32bit)
  src/Corax/Utils/EntryIdEncodings.cs
  test/FastTests/Corax/Ranking/QuantizationTest.cs
Labels: Corax, v5.4

#16209 RavenDB-20226 added support for short, int, long (fixes RavenDB_7996)
  src/Sparrow/Json/LazyStringValue.cs
Labels: v6.0

#16207 RavenDB-20290 Use ValueTuple in GetValueTokenTupleByIndex
  src/Raven.Server/Utils/ConflictResolverAdvisor.cs
  src/Sparrow/Json/BlittableJsonReaderArray.cs
Labels: v5.4

#16217 RavenDB-7070 Uncomment assertions
  test/FastTests/Client/Indexing/TimeSeries/BasicTimeSeriesIndexes.cs
Labels: v5.4

#16223 RavenDB-20269 Ensure no Microsoft logs are written if they are disabled
  src/Raven.Server/Utils/MicrosoftLogging/SparrowLoggerWrapper.cs
Labels: v5.2

#16229 RavenDB-20113 Prettify license modal
  src/Raven.Studio/wwwroot/App/views/common/notificationCenter/detailViewer/licenseLimitDetails.html
  src/Raven.Studio/wwwroot/App/views/manage/infoPackage.html
  src/Raven.Studio/wwwroot/App/views/shell/registration.html
  src/Raven.Studio/wwwroot/Content/css/modals.less
  src/Raven.Studio/wwwroot/Content/css/styles-common-scoped.less
  src/Raven.Studio/wwwroot/Content/img/license.svg
Labels: v6.0, Studio

#16218 RavenDB-20235 Backup status icon red, text in green
  src/Raven.Studio/typescript/components/common/RichPanel.scss
  src/Raven.Studio/typescript/components/common/Toggles.scss
  src/Raven.Studio/typescript/components/common/Type.scss
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/DatabasePanel.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/DatabasesFilter.scss
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/ValidDatabasePropertiesPanel.tsx
  src/Raven.Studio/wwwroot/Content/css/icons.less
  src/Raven.Studio/wwwroot/Content/scss/_bs5extend.scss
  src/Raven.Studio/wwwroot/Content/scss/_colors.scss
  src/Raven.Studio/wwwroot/Content/scss/bs5variables.scss
Labels: v6.0, Studio

#16230 RavenDB-20243 SlowTests.Server.Documents.Revisions.RevertRevisionsTests.RevertResolvedConflictByLocalToOriginal
  test/SlowTests/Server/Documents/Revisions/RevertRevisionsTests.cs
Labels: v5.4

#16231 RavenDB-7070 moving tests to stress
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
  test/SlowTests/Authentication/AuthenticationBasicTests.cs
  test/SlowTests/Cluster/ClusterOperationTests.cs
  test/SlowTests/Cluster/ClusterTransactionTests.cs
  test/SlowTests/Issues/RavenDB-17903.cs
  test/SlowTests/Monitoring/DiskStatsGetterTest.cs
  test/SlowTests/Server/Documents/ETL/Olap/LocalTests.cs
  test/SlowTests/Server/Documents/PeriodicBackup/ServerWideBackup.cs
  test/StressTests/Cluster/ClusterOperationTestsStress.cs
  test/StressTests/Cluster/ClusterTransactionTestsStress.cs
  test/StressTests/Issues/RavenDB_17903_Stress.cs
  test/StressTests/Rachis/DatabaseCluster/ClusterDatabaseMaintenanceStress.cs
  test/StressTests/Server/Documents/PeriodicBackup/ServerWideBackupStress.cs
Labels: v5.4

#16237 RavenDB-20251 Fix jumpy ui on cluster dashboard
  src/Raven.Studio/wwwroot/Content/css/pages/cluster-dashboard.less
Labels: v6.0, Studio

#16232 RavenDB-20291 Fix blurry status badge on hover
  src/Raven.Studio/typescript/components/common/RichPanel.scss
  src/Raven.Studio/typescript/components/common/RichPanel.tsx
Labels: v6.0, Studio

#16236 RavenDB-20264 Shard selector overlaps view
  src/Raven.Studio/wwwroot/App/views/common/sharding/shardSelector.html
  src/Raven.Studio/wwwroot/App/views/common/sharding/shardingContext.html
  src/Raven.Studio/wwwroot/Content/css/pages/sharding.less
Labels: v6.0, Studio

#16238 RavenDB-20253 Make errors and hints more visible
  src/Raven.Studio/typescript/components/common/RichPanel.scss
  src/Raven.Studio/typescript/components/common/Type.scss
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/ValidDatabasePropertiesPanel.tsx
Labels: v6.0, Studio

#16239 RavenDB-20205: Raven will not calculate the number of entries in Corax's indexes but will take it directly from Corax.
  src/Corax/IndexWriter.cs
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxIndexReadOperation.cs
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxIndexWriteOperation.cs
  test/FastTests/Corax/Bugs/OptimizedUpdatesOnIndexes.cs
  test/FastTests/Corax/RavenIntegration.cs
Labels: Corax, v5.4

#16241 RavenDB-20298 Fix filter indexes by name
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexFilter.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexesPage.tsx
Labels: v6.0, Studio

#16242 RavenDB-20249: Don't override `canExtractFromIndex` in the case of Corax's map-reduce indexes.
  src/Raven.Server/Documents/CollectionRunner.cs
  src/Raven.Server/Documents/Indexes/Debugging/IndexDebugExtensions.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Queries/Dynamic/CollectionQueryRunner.cs
  src/Raven.Server/Documents/Queries/FieldsToFetch.cs
  src/Raven.Server/Documents/Queries/GraphQueryRunner.cs
  test/FastTests/Corax/MapReduceProjection.cs
Labels: Corax, v5.4

#16244 RavenDB-20302 Fix menu tooltips
  src/Raven.Studio/typescript/common/shell/accessManager.ts
  src/Raven.Studio/typescript/common/shell/menu.ts
  src/Raven.Studio/wwwroot/Content/scss/_main-menu.scss
Labels: v6.0, Studio

#16245 RavenDB-20219 Single and Multi selectors
  src/Raven.Studio/typescript/components/common/Checkbox.stories.tsx
  src/Raven.Studio/typescript/components/common/LocationSpecificDetails.scss
  src/Raven.Studio/typescript/components/common/MultiCheckboxToggle.tsx
  src/Raven.Studio/typescript/components/common/Radio.stories.tsx
  src/Raven.Studio/typescript/components/common/Radio.tsx
  src/Raven.Studio/typescript/components/common/SingleDatabaseLocationSelector.tsx
  src/Raven.Studio/typescript/components/common/Toggles.scss
  src/Raven.Studio/typescript/components/common/Toggles.stories.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/DatabasesFilter.scss
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/DatabasesFilter.tsx
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon/clear.svg
  src/Raven.Studio/wwwroot/Content/scss/_bs5extend.scss
Labels: v6.0, Studio

#16252 HRINT-3161 Get dry_run from env var
  docker/publish-nanoserver.ps1
  docker/publish-ubuntu.ps1
Labels: v5.2

#16251 RavenDB-20251 Fix jumpy UI in cluster dashboard view
  src/Raven.Studio/wwwroot/Content/css/pages/cluster-dashboard.less
Labels: v6.0, Studio

#16249 RavenDB-20249 Fixing a test which started to fail on sharded database when using Corax.
  test/SlowTests/Core/Querying/Paging.cs
Labels: v6.0

#16257 RavenDB-20309 Increase contrast between placeholder and value
  src/Raven.Studio/wwwroot/Content/scss/bs5variables.scss
Labels: v6.0, Studio

#16256 RavenDB-20303 Corax - update of entry with dynamic fields.
  src/Corax/IndexWriter.cs
  src/Corax/Mappings/IndexFieldsMapping.cs
  test/FastTests/Corax/RavenIntegration.cs
Labels: Corax, v5.4

#16246 RavenDB-19080 make sharded & non-sharded output identical
  src/Raven.Server/Documents/Handlers/Processors/Subscriptions/AbstractSubscriptionsHandlerProcessorForGetConnectionDetails.cs
  src/Raven.Server/Documents/Handlers/Processors/Subscriptions/SubscriptionsHandlerProcessorForGetConnectionDetails.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Subscriptions/ShardedSubscriptionsHandlerProcessorForGetConnectionDetails.cs
Labels: v6.0

#16247 RavenDB-20311 blocked OrderByDistance for map-reduce indexes in sharding
  src/Raven.Server/Documents/Sharding/Queries/AbstractShardedQueryProcessor.cs
  test/SlowTests/Issues/RavenDB-19544.cs
Labels: v6.0

#16260 RavenDB-20315 Fix docker tags for ubuntu images having ubuntu version…
  docker/common.ps1
Labels: v5.4

#16178 RavenDB-20002 - fixed Adding new shard is not always distributed correctly
  src/Raven.Server/Web/System/ShardedAdminDatabaseHandler.cs
  test/SlowTests/Sharding/ShardingTopologyTests.cs
Labels: v6.0

#16270 RavenDB-20314 support importing dump when change-vector is null
  src/Raven.Server/Documents/BlittableMetadataModifier.cs
Labels: v6.0

#16284 5.2 to 5.4 merge
  src/Raven.Server/Dashboard/DatabasesInfoRetriever.cs
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/ETL/EtlLoader.cs
  src/Raven.Server/Documents/Handlers/PullReplicationHandler.cs
  src/Raven.Server/Documents/PeriodicBackup/BackupTask.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/Documents/Subscriptions/SubscriptionStorage.cs
  src/Raven.Server/Json/JsonDeserializationServer.cs
  src/Raven.Server/ServerWide/RawDatabaseRecord.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Utils/BackupUtils.cs
  src/Raven.Server/Web/System/OngoingTasksHandler.cs
  test/SlowTests/Issues/RavenDB-19379.cs
  test/SlowTests/Issues/RavenDB_20084.cs
  test/Tests.Infrastructure/RavenTestBase.Backup.cs
Labels: v5.4

#16280 RavenDB-20077 : certificate with permissions for sharded database should allow access to individual shards
  src/Raven.Server/RavenServer.cs
  test/SlowTests/Sharding/Encryption/ShardedEncryption.cs
Labels: v6.0

#16278 RavenDB-20330 write to a temp path
  src/Raven.Server/Smuggler/Documents/StreamDestination.cs
Labels: v6.0

#16277 RavenDB-7070 minor sharded client API fixes
  src/Raven.Client/ServerWide/Operations/AddDatabaseNodeOperation.cs
  src/Raven.Client/ServerWide/Operations/PromoteDatabaseNodeOperation.cs
Labels: v6.0

#16286 RavenDB-20316 Make .sh scripts executable
  docker/ravendb-ubuntu/cert-utils.sh
  docker/ravendb-ubuntu/link-legacy-datadir.sh
  docker/ravendb-ubuntu/server-utils.sh
Labels: v6.0

#16281 RavenDB-7070 Introduced ParallelTestBase and making sure that tests inherit from it (so we're sure that RAVEN_MAX_RUNNING_TESTS is respected).
  test/FastTests/Issues/RavenDB_12623.cs
  test/FastTests/Server/Documents/Indexing/Static/DynamicBlittableJsonTests.cs
  test/FastTests/Voron/PostingLists/PostingListLeafPageTests.cs
  test/FastTests/Voron/StorageTest.cs
  test/SlowTests/Issues/RavenDB_3620.cs
  test/SlowTests/Tests/TestsInheritanceTests.cs
  test/Tests.Infrastructure/NoDisposalNeeded.cs
  test/Tests.Infrastructure/NoDisposalNoOutputNeeded.cs
  test/Tests.Infrastructure/ParallelTestBase.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v5.4

#16224 RavenDB-20185: Fix bug causing `number of currently running backups` endpoint to return -1 after delaying/snoozing backup
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
Labels: v5.2

#16297 RavenDB-18687 Instead of generating an auto index name based on the fields let's use the name from the definition.
  src/Raven.Server/Documents/Indexes/Auto/AutoMapIndexDefinition.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  src/Raven.Server/Documents/Indexes/MapReduce/Auto/AutoMapReduceIndexDefinition.cs
  src/Raven.Server/Documents/Queries/Dynamic/DynamicQueryMapping.cs
  test/SlowTests/Data/RavenDB_18687/auto_indexes.ravendbdump
  test/SlowTests/Issues/RavenDB_18687.cs
  test/SlowTests/SlowTests.csproj
Labels: v6.0

#16298 RavenDB-7070 Fixing problem with hanging FastTests due to missing base.Dispose() call in a few tests after introducing ParallelTestBase
  test/FastTests/Server/Documents/Indexing/Static/DynamicBlittableJsonTests.cs
  test/FastTests/Voron/PostingLists/PostingListLeafPageTests.cs
  test/SlowTests/Issues/RavenDB_3620.cs
  test/Tests.Infrastructure/ParallelTestBase.cs
Labels: v5.4

#16294 RavenDB-20162 : bucket migration commands should update EtagForBackup
  src/Raven.Server/Documents/PeriodicBackup/BackupTask.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/Sharding/SingleShardRestoreBackupTask.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/Commands/Sharding/SourceMigrationSendCompletedCommand.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/ServerWide/ShardingStore.cs
  src/Raven.Server/Smuggler/Documents/DatabaseSource.cs
  src/Raven.Server/Utils/ShardHelper.cs
  test/SlowTests/Sharding/Cluster/ReshardingTests.cs
  test/Tests.Infrastructure/RavenTestBase.Sharding.cs
Labels: v6.0

#16273 RavenDB-20327 Can't click anywhere (outside modal) when shard selecto…
  src/Raven.Studio/wwwroot/App/views/common/sharding/shardSelector.html
  src/Raven.Studio/wwwroot/Content/css/modals.less
Labels: v6.0, Studio

#16303 RavenDB-20344
  src/Sparrow.Server/Collections/SmallSet.cs
  test/FastTests/Sparrow/SmallSet.cs
Labels: v5.4

#16301 RavenDB-20328 CollectionStatistics should ignore casing
  src/Raven.Client/Documents/Operations/CollectionStatistics.cs
  src/Raven.Client/Documents/Operations/MaintenanceOperationExecutor.cs
  src/Raven.Client/Documents/Operations/OperationExecutor.cs
  src/Raven.Client/Documents/Smuggler/DatabaseSmuggler.cs
  src/Raven.Server/Documents/Sharding/Executors/ShardExecutor.cs
  test/FastTests/Server/Documents/Collections.cs
Labels: v6.0

#16291 RavenDB-20085 Changed CanTranslateDateTimeMinValueMaxValue to be consistent
  test/SlowTests/Issues/RavenDB-10493.cs
Labels: v6.0

#16296 RavenDB-20084: Fix backup status update issue for idle databases (test improvements)
  test/SlowTests/Issues/RavenDB_20084.cs
Labels: v5.2

#16275 RavenDB-17708 Added property name for index projection if set in conventions
  src/Raven.Client/Documents/Linq/RavenQueryProviderProcessor.cs
  test/SlowTests/Issues/RavenDB-17708.cs
Labels: v6.0

#16315 5.2 to 5.4 merge
  src/Raven.Client/Constants.cs
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Web/Studio/StudioDatabaseTasksHandler.cs
  src/Raven.Studio/typescript/commands/resources/restartDatabaseCommand.ts
  src/Raven.Studio/typescript/viewmodels/resources/databases.ts
  src/Raven.Studio/typings/_studio/dto.d.ts
  src/Raven.Studio/wwwroot/App/views/resources/databases.html
  test/SlowTests/Issues/RavenDB_19743.cs
  test/SlowTests/Issues/RavenDB_20084.cs
Labels: v5.4

#16318 5.4 to 6.0 merge
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Web/Studio/StudioDatabaseTasksHandler.cs
  src/Raven.Studio/typescript/commands/resources/restartDatabaseCommand.ts
  src/Raven.Studio/typings/_studio/dto.d.ts
  src/Voron/Data/PostingLists/PostingListLeafPage.cs
  test/SlowTests/Issues/RavenDB_19743.cs
  test/SlowTests/Issues/RavenDB_20059.cs
  test/SlowTests/Issues/RavenDB_20084.cs
Labels: v6.0

#16322 RavenDB-20346 Test fix - wait for the value.
  test/FastTests/Corax/RavenIntegration.cs
Labels: v6.0

#16302 RavenDB-20332 Truncate long index/database name
  src/Raven.Studio/typescript/components/common/RichPanel.scss
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexPanel.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexesPage.scss
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/DatabasePanel.tsx
Labels: v6.0, Studio

#16319 RavenDB-17649 Restart database - Added text info
  src/Raven.Studio/typescript/viewmodels/database/settings/databaseSettings.ts
  src/Raven.Studio/typescript/viewmodels/resources/databases.ts
  src/Raven.Studio/wwwroot/App/views/database/query/querySyntax.html
Labels: v5.2, Studio

#16314 RavenDB-15446 Studio conventions
  .github/workflows/studioConventions.yml
Labels: v5.2

#16290 RavenDB-20337: `HardResetToNewCluster` leads to null `ClusterTransactionId` and `DatabaseTopologyId`
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  test/RachisTests/EmergencyOperations.cs
Labels: v5.2

#16320 RavenDB-7070 Removing unused field
  src/Corax/Queries/SortingMatch/SortingMatch.cs
Labels: v5.4

#16326 5.2 to 5.4 merge
  .github/workflows/studioConventions.yml
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Studio/typescript/viewmodels/database/settings/databaseSettings.ts
  src/Raven.Studio/typescript/viewmodels/resources/databases.ts
  src/Raven.Studio/wwwroot/App/views/database/query/querySyntax.html
  test/RachisTests/EmergencyOperations.cs
Labels: v5.4

#16327 5.4 to 6.0 merge
  .github/workflows/studioConventions.yml
  src/Corax/Queries/SortingMatch/SortingMatch.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Studio/typescript/viewmodels/database/settings/databaseSettings.ts
  src/Raven.Studio/wwwroot/App/views/database/query/querySyntax.html
  test/RachisTests/EmergencyOperations.cs
Labels: v6.0

#16330 RavenDB-20371 disable HttpCache free space cleanup during test execution
  src/Raven.Client/Http/HttpCache.cs
  test/FastTests/Server/Documents/Queries/NotModifiedQueryResults.cs
Labels: v6.0

#16332 RavenDB-20372: Memory leak issue in RequestExecutor (v5.2)
  src/Raven.Server/ServerWide/ServerStore.cs
Labels: v5.2

#16331 RavenDB-20373 added proxy to '/databases/*/admin/studio-tasks/folder-…
  src/Raven.Server/Web/Studio/Processors/StudioDatabaseTasksHandlerProcessorForGetFolderPathOptionsForDatabaseAdmin.cs
  src/Raven.Server/Web/Studio/Processors/StudioDatabaseTasksHandlerProcessorForGetFolderPathOptionsForOperator.cs
  src/Raven.Server/Web/Studio/Processors/StudioStudioDatabaseTasksHandlerProcessorForGetFolderPathOptionsForDatabaseAdmin.cs
  src/Raven.Server/Web/Studio/Sharding/ShardedStudioDatabaseTasksHandler.cs
  src/Raven.Server/Web/Studio/StudioDatabaseTasksHandler.cs
  src/Raven.Server/Web/Studio/StudioTasksHandler.cs
Labels: v6.0

#16329 RavenDB-20356 - SlowTests.Sharding.Replication.ShardedExternalReplica…
  test/SlowTests/Sharding/Replication/ShardedExternalReplicationTests.cs
Labels: v6.0

#16335 RavenDB-19960: Enhance test stability - PeriodicBackupTestsSlow.Shoul…
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
Labels: v5.2

#16338 RavenDB-20360 : fix DeleteSecretKey for sharded databases
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/Commands/RemoveNodeFromDatabaseCommand.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
  src/Raven.Server/Web/System/ShardedAdminDatabaseHandler.cs
  test/SlowTests/Sharding/Cluster/ReshardingTests.cs
  test/SlowTests/Sharding/Encryption/ShardedEncryption.cs
Labels: v6.0

#16337 RavenDB-20353 use ConcurrentDictionary for Operations in AbstractShardedMultiOperation
  src/Raven.Server/Documents/Sharding/Operations/AbstractShardedMultiOperation.cs
Labels: v6.0

#16336 RavenDB-20359 - SlowTests.Server.Replication.ReplicationTombstoneTest…
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Replication/ShardedReplicationHandlerProcessorForGetTombstones.cs
  src/Raven.Server/Documents/Tombstone.cs
Labels: v6.0

#16342 RavenDB-19737 : fix InvalidCastException in RawShardingConfiguration.Prefixed
  src/Raven.Server/ServerWide/Sharding/RawShardingConfiguration.cs
  test/SlowTests/Sharding/PrefixedSharding.cs
Labels: v6.0

#16344 5.4 to 6.0 merge
  src/Corax/IndexSearcher/IndexSearcher.Search.cs
  src/Corax/IndexSearcher/IndexSearcher.cs
  src/Corax/IndexSearcher/MultiTermMatches/IndexSearcher.MultiTermMatches.In.cs
  src/Corax/Queries/BoostingMatch.cs
  src/Corax/Queries/SortingMatch/Comparers/IMatchComparer.cs
  src/Corax/Queries/SortingMatch/Comparers/SortingMatch.AlphanumericAscendingMatchComparer.cs
  src/Corax/Queries/SortingMatch/Comparers/SortingMatch.AlphanumericDescendingMatchComparer.cs
  src/Corax/Queries/SortingMatch/Comparers/SortingMatch.AscendingMatchComparer.cs
  src/Corax/Queries/SortingMatch/Comparers/SortingMatch.Comparers.cs
  src/Corax/Queries/SortingMatch/Comparers/SortingMatch.CustomMatchComparer.cs
  src/Corax/Queries/SortingMatch/Comparers/SortingMatch.DescendingMatchComparer.cs
  src/Corax/Queries/SortingMatch/Comparers/SortingMatch.SpatialAscendingMatchComparer.cs
  src/Corax/Queries/SortingMatch/Comparers/SortingMatch.SpatialDescendingMatchComparer.cs
  src/Corax/Queries/SortingMatch/SortingMatch.cs
  src/Corax/Queries/SortingMatch/SortingMatchHeap.cs
  src/Corax/Queries/SortingMatch/SortingMultiMatch.Erasure.cs
  src/Corax/Queries/TermProviders/TermProvider.In.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Handlers/Debugging/NodeDebugHandler.cs
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxIndexReadOperation.cs
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxQueryBuilder.cs
  src/Raven.Server/Documents/Replication/ReplicationItems/AttachmentReplicationItem.cs
  src/Raven.Server/Documents/Replication/ReplicationItems/AttachmentTombstoneReplicationItem.cs
  src/Raven.Server/Documents/Replication/ReplicationItems/CounterReplicationItem.cs
  src/Raven.Server/Documents/Replication/ReplicationItems/DocumentReplicationItem.cs
  src/Raven.Server/Documents/Replication/ReplicationItems/ReplicationBatchItem.cs
  src/Raven.Server/Documents/Replication/ReplicationItems/RevisionTombstoneReplicationItem.cs
  src/Raven.Server/Documents/Replication/ReplicationItems/TimeSeriesReplicationItem.cs
  src/Raven.Server/Documents/Replication/Senders/ReplicationDocumentSenderBase.cs
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  src/Raven.Server/Documents/Sharding/Handlers/ShardedIncomingReplicationHandler.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Storage/Schema/Updates/Documents/50001/From42017.cs
  src/Sparrow/Json/ArenaMemoryAllocator.cs
  test/FastTests/Corax/Bugs/SortingMatchHeapTests.cs
  test/FastTests/Corax/IndexSearcher.cs
  test/FastTests/Corax/RawCoraxFlag.cs
  test/FastTests/FastTests.csproj
  test/SlowTests/Client/Indexing/TimeSeries/BasicTimeSeriesIndexes_StrongSyntax.cs
  test/SlowTests/MailingList/ZNS2.cs
  test/SlowTests/Server/Documents/ETL/EtlTimeSeriesTests.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
Labels: v6.0

#16347 RavenDB-20375 use proper cert validation for sharded database changes
  src/Raven.Client/Documents/Changes/AbstractDatabaseChanges.cs
  src/Raven.Server/Documents/Sharding/Changes/ShardedChangesClientConnection.cs
  src/Raven.Server/Documents/Sharding/Changes/ShardedDatabaseChanges.cs
  src/Raven.Server/ServerWide/ShardingStore.cs
Labels: v6.0

#16350 RavenDB-20318: fix db name
  src/Raven.Server/Documents/Commands/Subscriptions/GetSubscriptionConnectionsDetailsCommand.cs
Labels: v6.0

#16316 RavenDB-18198 Migrate queries tests for sharding
  test/SlowTests/Issues/RavenDB-13349.cs
  test/SlowTests/Issues/RavenDB-16963.cs
  test/SlowTests/Issues/RavenDB_14269.cs
  test/SlowTests/Issues/RavenDB_15166.cs
  test/SlowTests/Issues/RavenDB_19548.cs
  test/SlowTests/Issues/RavenDB_3326.cs
  test/SlowTests/MailingList/MultipleLoad.cs
  test/SlowTests/MailingList/ProjectionTests.cs
  test/SlowTests/Server/Documents/Indexing/ExactSearchOnAutoIndex_RavenDB_8006.cs
Labels: v6.0

#16354 5.4 to 6.0 merge
  src/Raven.Client/Http/RequestExecutor.cs
  src/Raven.Server/Documents/ETL/Providers/Raven/RavenEtl.cs
  src/Raven.Server/ServerWide/ServerStore.cs
Labels: v6.0

#16358 RavenDB-20389 use proper database name in index controllers
  src/Raven.Server/Documents/Indexes/AbstractIndexCreateController.cs
  src/Raven.Server/Documents/Indexes/AbstractIndexLockModeController.cs
  src/Raven.Server/Documents/Indexes/AbstractIndexPriorityController.cs
  src/Raven.Server/Documents/Indexes/AbstractIndexStateController.cs
  src/Raven.Server/Documents/Indexes/DatabaseIndexDeleteController.cs
  src/Raven.Server/Documents/Indexes/DatabaseIndexLockModeController.cs
  src/Raven.Server/Documents/Indexes/DatabaseIndexPriorityController.cs
  src/Raven.Server/Documents/Indexes/DatabaseIndexStateController.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  src/Raven.Server/Documents/Indexes/Sharding/ShardedDatabaseIndexCreateController.cs
  src/Raven.Server/Documents/Indexes/Sharding/ShardedDatabaseIndexDeleteController.cs
  src/Raven.Server/Documents/Indexes/Sharding/ShardedDatabaseIndexLockModeController.cs
  src/Raven.Server/Documents/Indexes/Sharding/ShardedDatabaseIndexPriorityController.cs
  src/Raven.Server/Documents/Indexes/Sharding/ShardedDatabaseIndexStateController.cs
  src/Raven.Server/Documents/Indexes/Sharding/ShardedIndexLockModeController.cs
  src/Raven.Server/Documents/Indexes/Sharding/ShardedIndexPriorityController.cs
  src/Raven.Server/Documents/Indexes/Sharding/ShardedIndexStateController.cs
  src/Raven.Server/Documents/Indexes/Sharding/ShardedIndexStore.cs
Labels: v6.0

#16357 RavenDB-20387
  src/Sparrow/Json/ArenaMemoryAllocator.cs
Labels: v5.2

#16362 RavenDB-7070 Increasing Regex timeout (Querying) in tests.
  test/Tests.Infrastructure/RavenTestBase.cs
Labels: v5.4
