Repository ravendb/ravendb, pull requests merged in 2023-07, with the labels that each got.

#16787 RavenDB-17761 - Failing test SlowTests.Server.Replication.ExternalRep…
  test/SlowTests/Server/Replication/ExternalReplicationTests.cs
Labels: v6.0

#16786 RavenDB-20460 - add replication factor validation for adding new shard
  src/Raven.Server/Web/System/ShardedAdminDatabaseHandler.cs
Labels: v6.0

#16785 RavenDB-20785: Validation code is failing when transaction is null.
  src/Voron/Data/BTrees/Tree.cs
Labels: v6.0

#16790 RavenDB-20778 Index name overflow
  src/Raven.Studio/typescript/components/pages/database/indexes/list/ConfirmResetIndex.tsx
Labels: v6.0, Studio

#16655 RavenDB-20625 Add toggle possibility to filtering options for smaller screens
  src/Raven.Studio/typescript/components/common/StickyHeader.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/DatabasesPage.tsx
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon/filter.svg
Labels: v6.0, Studio

#16800 RavenDB-20656 properly skip revision document
  src/Raven.Server/Smuggler/Documents/DatabaseSmuggler.cs
Labels: v5.4

#16793 5.4 to 6.0 merge
  libs/Lucene.Net.3.0.54009.nupkg
  libs/Lucene.Net.Contrib.Spatial.NTS.3.0.54009.nupkg
  src/Raven.Client/Documents/Identity/IHiLoIdGenerator.cs
  src/Raven.Client/Documents/Indexes/ExpressionStringBuilder.cs
  src/Raven.Client/Documents/Operations/Operation.cs
  src/Raven.Client/Documents/Session/Operations/StreamOperation.cs
  src/Raven.Client/Documents/Smuggler/DatabaseItemType.cs
  src/Raven.Client/Documents/Smuggler/DatabaseSmugglerOptions.cs
  src/Raven.Client/Documents/Smuggler/SmugglerProgressBase.cs
  src/Raven.Client/Documents/Smuggler/SmugglerResult.cs
  src/Raven.Client/Documents/Subscriptions/AbstractSubscriptionWorker.cs
  src/Raven.Client/ServerWide/Commands/GetTcpInfoCommand.cs
  src/Raven.Client/ServerWide/Operations/ServerWideOperation.cs
  src/Raven.Server/Documents/DocumentFlags.cs
  src/Raven.Server/Documents/Handlers/Debugging/NodeDebugHandler.cs
  src/Raven.Server/Documents/Queries/Results/QueryResultRetrieverBase.cs
  src/Raven.Server/Documents/Queries/Results/TimeSeries/TimeSeriesRetriever.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  src/Raven.Server/NotificationCenter/Handlers/ProxyWebSocketConnection.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/Commands/UpdateValueForDatabaseCommand.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterMaintenanceSupervisor.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Smuggler/Documents/Actions/DatabaseRecordActions.cs
  src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
  src/Raven.Server/Smuggler/Documents/DatabaseSmuggler.cs
  src/Raven.Server/Smuggler/Documents/SmugglerBase.cs
  src/Raven.Server/Smuggler/Documents/SmugglerPatcher.cs
  src/Raven.Server/Smuggler/Documents/StreamDestination.cs
  src/Raven.Server/Smuggler/Documents/StreamSource.cs
  src/Raven.Server/Smuggler/Migration/Importer.cs
  src/Raven.Server/Utils/LruDictionary.cs
  src/Raven.Server/Utils/ReplicationUtils.cs
  src/Raven.Server/Web/System/Processors/Tcp/DatabaseTcpConnectionInfoHandlerProcessorForGet.cs
  src/Raven.Studio/typescript/models/database/tasks/smugglerDatabaseRecord.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/smugglerDatabaseDetails.ts
  src/Raven.Studio/typescript/viewmodels/manage/trafficWatch.ts
  src/Raven.Studio/wwwroot/App/views/database/tasks/smugglerDatabaseRecord.html
  test/SlowTests/Issues/RavenDB-20145.cs
  test/SlowTests/Issues/RavenDB-20731.cs
  test/SlowTests/Issues/RavenDB_19693.cs
  test/SlowTests/Issues/RavenDB_20656.cs
  test/SlowTests/Issues/RavenDB_20760.cs
  test/SlowTests/Sharding/Issues/RavenDB_20390.cs
  test/SlowTests/Smuggler/BackupDatabaseRecordTests.cs
Labels: v6.0

#16803 RavenDB-20012 added inner exception to SNMP exception handling
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
Labels: v5.4

#16802 RavenDB-20544: Fix the failing test that occurs due to a race condition between PutLicense and UpdateLicenseLimits
  src/Raven.Server/Commercial/LicenseManager.cs
  test/SlowTests/Server/Documents/PeriodicBackup/RavenDB-20544.cs
Labels: v5.2

#16795 RavenDB-20784 Fix margins on Certificates view
  src/Raven.Studio/wwwroot/App/views/manage/certificates.html
Labels: v5.4, Studio

#16805 RavenDB-20670 Fix Admin Logs merge regressions
  src/Raven.Studio/wwwroot/App/views/manage/adminLogs.html
  src/Raven.Studio/wwwroot/Content/css/styles-common-scoped.less
Labels: v6.0, Studio

#16807 5.2 to 5.4 merge
  src/Raven.Server/Commercial/LicenseManager.cs
  test/SlowTests/Server/Documents/PeriodicBackup/RavenDB-20544.cs
Labels: v5.4

#16808 5.4 to 6.0 merge
  src/Raven.Server/Commercial/LicenseManager.cs
  src/Raven.Server/Documents/DatabaseRequestHandler.cs
  src/Raven.Server/Documents/Handlers/Admin/AdminMemoryHandler.cs
  src/Raven.Server/Documents/Handlers/Admin/AdminScriptRunnersDebugInfoHandler.cs
  src/Raven.Server/Documents/Handlers/Admin/RachisAdminHandler.cs
  src/Raven.Server/Documents/Handlers/Debugging/MemoryDebugHandler.cs
  src/Raven.Server/Documents/Handlers/Debugging/NodeDebugHandler.cs
  src/Raven.Server/Documents/Handlers/Debugging/ProcStatsHandler.cs
  src/Raven.Server/Documents/Handlers/Debugging/ServerInfoHandler.cs
  src/Raven.Server/Documents/Handlers/Debugging/ServerTransactionDebugHandler.cs
  src/Raven.Server/Documents/Handlers/Debugging/ServerWideDebugInfoPackageHandler.cs
  src/Raven.Server/Documents/Handlers/Debugging/ServerWideQueriesDebugHandler.cs
  src/Raven.Server/Documents/Handlers/Debugging/ThreadsHandler.cs
  src/Raven.Server/Documents/Handlers/SecretKeyHandler.cs
  src/Raven.Server/Documents/Indexes/IndexMerging/IndexMerger.cs
  src/Raven.Server/Documents/Sharding/Handlers/ShardedDatabaseRequestHandler.cs
  src/Raven.Server/Monitoring/Snmp/SnmpHandler.cs
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
  src/Raven.Server/NotificationCenter/Handlers/ServerNotificationCenterHandler.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/TrafficWatch/TrafficWatchHandler.cs
  src/Raven.Server/Web/RequestHandler.cs
  src/Raven.Server/Web/ServerRequestHandler.cs
  src/Raven.Server/Web/Studio/LicenseHandler.cs
  src/Raven.Server/Web/Studio/StudioFeedbackHandler.cs
  src/Raven.Server/Web/Studio/StudioTasksHandler.cs
  src/Raven.Server/Web/System/AdminAllocationDebugHandler.cs
  src/Raven.Server/Web/System/AdminCpuCreditsHandler.cs
  src/Raven.Server/Web/System/AdminDebugQueryClauseCacheHandler.cs
  src/Raven.Server/Web/System/AdminIoMetricsHandler.cs
  src/Raven.Server/Web/System/AdminMetricsHandler.cs
  src/Raven.Server/Web/System/AdminMonitoringHandler.cs
  src/Raven.Server/Web/System/AdminPrometheusMonitoringHandler.cs
  src/Raven.Server/Web/System/AdminStatsHandler.cs
  src/Raven.Server/Web/System/AdminStorageHandler.cs
  src/Raven.Server/Web/System/AdminTcpConnectionDebugInfoHandler.cs
  src/Raven.Server/Web/System/BackupDatabaseHandler.cs
  src/Raven.Server/Web/System/CorsPreflightHandler.cs
  src/Raven.Server/Web/System/DatabasesDebugHandler.cs
  src/Raven.Server/Web/System/DatabasesHandler.cs
  src/Raven.Server/Web/System/DebugHandler.cs
  src/Raven.Server/Web/System/EmptyMessageHandler.cs
  src/Raven.Server/Web/System/SetupHandler.cs
  src/Raven.Server/Web/System/StudioDatabasesHandler.cs
  src/Raven.Server/Web/System/StudioHandler.cs
  src/Raven.Server/Web/System/TcpConnectionInfoHandler.cs
  src/Raven.Server/Web/System/TestConnectionHandler.cs
  src/Raven.Studio/wwwroot/App/views/manage/certificates.html
  test/RachisTests/AddNodeToClusterTests.cs
  test/SlowTests/Server/Documents/Indexing/IndexMerging.cs
  test/SlowTests/Server/Documents/PeriodicBackup/RavenDB-20544.cs
  test/SlowTests/Tests/TestsInheritanceTests.cs
Labels: v6.0

#16819 5.4 to 6.0 merge
  src/Raven.Server/ServerWide/OperationCancelToken.cs
Labels: v6.0

#16826 RavenDB-20756 - Go over all place in tests where we do modifyDatabaseRecord(record)
  test/SlowTests/Issues/RavenDB_18357.cs
  test/SlowTests/Server/Replication/ReplicationConflictsTests.cs
Labels: v6.0

#16829 RavenDB-20580 Info Hub floating & anchored component
  src/Raven.Studio/typescript/components/common/AboutView.scss
  src/Raven.Studio/typescript/components/common/AboutView.stories.tsx
  src/Raven.Studio/typescript/components/common/AboutView.tsx
  src/Raven.Studio/typescript/components/pages/database/tasks/backups/BackupsPage.tsx
  src/Raven.Studio/typescript/components/pages/resources/manageServer/adminJsConsole/AdminJsConsole.spec.tsx
  src/Raven.Studio/typescript/components/pages/resources/manageServer/adminJsConsole/AdminJsConsole.tsx
  src/Raven.Studio/wwwroot/Content/img/info-hub.svg
Labels: v6.0, Studio

#16832 5.4 to 6.0 merge
  src/Raven.Client/Constants.cs
  src/Raven.Client/Http/ClusterRequestExecutor.cs
  src/Raven.Client/Http/RequestExecutor.cs
  src/Raven.Server/Documents/DatabaseRequestHandler.cs
  src/Raven.Server/Documents/Handlers/Admin/RachisAdminHandler.cs
  src/Raven.Server/Documents/Sharding/Handlers/ShardedDatabaseRequestHandler.cs
  src/Raven.Server/Routing/RavenActionAttribute.cs
  src/Raven.Server/Routing/RequestRouter.cs
  src/Raven.Server/Routing/RouteInformation.cs
  src/Raven.Server/Routing/RouteScanner.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterObserver.cs
  src/Raven.Server/Web/RequestHandlerContext.cs
  src/Raven.Server/Web/ServerRequestHandler.cs
  src/Raven.Server/Web/System/DatabasesHandler.cs
  test/SlowTests/Issues/RavenDB_20150.cs
Labels: v6.0

#16828 RavenDB-20782 Passing HighlightingOptions via DocumentQuery.
  src/Raven.Client/Documents/Session/DocumentQuery.Highlightings.cs
  test/SlowTests/Issues/RavenDB-20782.cs
Labels: v5.4

#16838 RavenDB-20845 Fix access icon positioning
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/AccessIcon.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/DatabasePanel.tsx
Labels: v6.0, Studio

#16834 RavenDB-20813 Remove link from connected clients section
  src/Raven.Studio/typescript/components/pages/database/tasks/panels/SubscriptionPanel.tsx
Labels: v6.0, Studio

#16842 RavenDB-19151 In case when Initialization failed we can get NRE on _reduceKeyProcessor disposal.
  src/Raven.Server/Documents/Indexes/MapReduce/Auto/AutoMapReduceIndex.cs
Labels: v5.4

#16841 RavenDB-19644 Dispose copied document in AttachmentStorage.
  src/Raven.Server/Documents/AttachmentsStorage.cs
Labels: v5.4

#16833 RavenDB-20336: modify test so loaded docs are on the same shard
  test/FastTests/Client/Subscriptions/SubscriptionsBasic.cs
Labels: v6.0

#16849 RavenDB-20700 revert Lucene.Net 3.0.60008
  libs/Lucene.Net.3.0.54009.nupkg
  libs/Lucene.Net.3.0.60007.nupkg
  libs/Lucene.Net.3.0.60008.nupkg
  libs/Lucene.Net.Contrib.Spatial.NTS.3.0.54009.nupkg
  libs/Lucene.Net.Contrib.Spatial.NTS.3.0.60007.nupkg
  libs/Lucene.Net.Contrib.Spatial.NTS.3.0.60008.nupkg
  src/Raven.Server/Raven.Server.csproj
Labels: v6.0

#16848 RavenDB-20698 Improve the source of logger in AbstractTransactionOperationsMerger
  src/Raven.Server/Documents/TransactionMerger/AbstractTransactionOperationsMerger.cs
Labels: v6.0

#16852 RavenDB-20860 Fix scss build warnings
  src/Raven.Studio/typescript/components/common/DatabaseGroup.scss
  src/Raven.Studio/typescript/components/common/LocationDistribution.scss
  src/Raven.Studio/typescript/components/pages/database/tasks/list/OngoingTaskPage.scss
  src/Raven.Studio/wwwroot/Content/scss/_bs5extend.scss
  src/Raven.Studio/wwwroot/Content/scss/_colors.scss
  src/Raven.Studio/wwwroot/Content/scss/bs5variables.scss
Labels: v6.0, Studio

#16837 RavenDB-20805 Fix admin logs actions layout
  src/Raven.Studio/wwwroot/App/views/manage/adminLogs.html
Labels: v5.4, Studio

#16839 RavenDB-20851 Modify <Select> look
  src/Raven.Studio/typescript/components/common/Form.tsx
  src/Raven.Studio/typescript/components/common/Select.tsx
  src/Raven.Studio/typescript/components/pages/resources/manageServer/clientConfiguration/ClientGlobalConfiguration.tsx
  src/Raven.Studio/wwwroot/Content/scss/_bs5extend.scss
Labels: v6.0, Studio

#16840 RavenDB-20780 Add information about `Patching.MaxStepsForScript` configuration option when patching throws `StatementsCountOverflowException `.
  src/Raven.Server/Documents/Patch/ScriptRunner.cs
  test/SlowTests/Issues/RavenDB-20780.cs
  test/SlowTests/Server/Documents/Patching/AdvancedPatching.cs
  test/SlowTests/Server/Documents/Patching/PatchingConfigurationsTests.cs
Labels: v5.4

#16843 5.4 to 6.0 merge
  src/Raven.Client/Documents/Smuggler/SmugglerProgressBase.cs
  src/Raven.Client/ServerWide/Operations/RestoreProgress.cs
  src/Raven.Client/ServerWide/Operations/RestoreResult.cs
  src/Raven.Server/Documents/AttachmentsStorage.cs
  src/Raven.Server/Documents/Handlers/AttachmentHandler.cs
  src/Raven.Server/Documents/Handlers/Batches/Commands/MergedBatchCommand.cs
  src/Raven.Server/Documents/Indexes/MapReduce/Auto/AutoMapReduceIndex.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/AbstractRestoreBackupTask.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreBackupTask.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreSnapshotTask.cs
  src/Raven.Server/Documents/Replication/ResolveConflictOnReplicationConfigurationChange.cs
  src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
  src/Raven.Studio/typescript/components/common/AboutView.stories.tsx
  src/Raven.Studio/typescript/components/common/AboutView.tsx
  src/Raven.Studio/typescript/components/common/MultipleDatabaseLocationSelector.tsx
  src/Raven.Studio/typescript/components/common/SingleDatabaseLocationSelector.tsx
  src/Raven.Studio/typescript/components/pages/database/tasks/backups/BackupsPage.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/BulkDatabaseResetConfirm.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/store/databasesViewActions.ts
  src/Raven.Studio/typescript/components/services/TasksService.ts
  src/Raven.Studio/typescript/test/stubs/DatabasesStubs.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/smugglerDatabaseDetails.ts
  src/Raven.Studio/typescript/viewmodels/manage/trafficWatch.ts
  src/Raven.Studio/wwwroot/App/views/common/notificationCenter/detailViewer/operations/smugglerDatabaseDetails.html
  src/Raven.Studio/wwwroot/Content/css/pages/export-progress.less
  test/SlowTests/RavenDB-19644.cs
Labels: v6.0

#16860 RavenDB-20700 need to clear batchContinuationResult before entering again the main loop.
  src/Raven.Server/Documents/Indexes/Workers/MapItems.cs
Labels: v5.4

#16844 RavenDB-20749: fix update query for sharded subscription
  src/Raven.Server/Documents/Handlers/Processors/Subscriptions/AbstractSubscriptionsHandlerProcessorForPostSubscription.cs
  src/Raven.Server/Documents/Handlers/Processors/Subscriptions/SubscriptionsHandlerProcessorForPostSubscription.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Subscriptions/ShardedSubscriptionsHandlerProcessorForPostSubscription.cs
  src/Raven.Server/Documents/Sharding/Handlers/ShardedSubscriptionsHandler.cs
  test/SlowTests/Sharding/Cluster/SubscriptionsWithReshardingTests.cs
  test/SlowTests/Sharding/Subscriptions/ShardedSubscriptionSlowTests.cs
Labels: v6.0

#16864 RavenDB-20875 Create tag for build in teamcity
  scripts/version.ps1
Labels: v5.2

#16863 RavenDB-20842: fix NRE in Subscription PreparePerformanceStats
  src/Raven.Server/Documents/Subscriptions/LiveSubscriptionPerformanceCollector.cs
Labels: v5.4

#16873 RavenDB-20656 Skipping non-document items when exporting a database w…
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/smugglerDatabaseDetails.ts
Labels: v5.4, Studio

#16871 RavenDB-20873 added missing description
  src/Raven.Server/Monitoring/Snmp/SnmpOids.cs
Labels: v5.4

#16874 RavenDB-20339 - handle TimeSeries change vectors & move & fix tests […
  src/Raven.Server/Documents/Replication/Incoming/IncomingReplicationHandler.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesStorage.cs
  src/Raven.Server/Utils/ChangeVector.cs
  test/SlowTests/Client/TimeSeries/IncrementalTimeSeriesTests.cs
  test/SlowTests/Client/TimeSeries/Replication/TimeSeriesReplicationTests.cs
  test/SlowTests/Issues/RavenDB_17317.cs
  test/SlowTests/Server/Documents/TimeSeries/TimeSeriesTombstoneCleaner.cs
Labels: v6.0

#16859 RavenDB-20859 Show index operation messages
  src/Raven.Studio/typescript/commands/database/index/disableIndexCommand.ts
  src/Raven.Studio/typescript/commands/database/index/enableIndexCommand.ts
  src/Raven.Studio/typescript/commands/database/index/forceIndexReplace.ts
  src/Raven.Studio/typescript/commands/database/index/resetIndexCommand.ts
  src/Raven.Studio/typescript/commands/database/index/togglePauseIndexingCommand.ts
  src/Raven.Studio/typescript/components/pages/database/indexes/list/useIndexesPage.tsx
Labels: v6.0, Studio

#16880 RavenDB-20880 Indexes list view: Index status icon sometimes goes dark
  src/Raven.Studio/typescript/components/common/ProgressCircle.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexDistribution.tsx
Labels: v6.0, Studio

#16877 RavenDB-20874 Link indexing errors
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexPanel.tsx
Labels: v6.0, Studio

#16876 RavenDB-20870 Unselect all on cancel
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexSelectActions.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexesPage.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/list/useIndexesPage.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/DatabasesSelectActions.tsx
Labels: v6.0, Studio

#16878 RavenDB-20543 Missing collection name fix
  src/Raven.Server/SqlMigration/GenericDatabaseMigrator.cs
  test/SlowTests/Server/Documents/Migration/BasicMigrationTests.cs
Labels: v5.4

#16884 RavenDB-20894 Custom scrollbar
  src/Raven.Studio/typescript/components/common/AboutView.stories.tsx
  src/Raven.Studio/typescript/components/common/AceEditor.scss
  src/Raven.Studio/typescript/components/common/Code.scss
  src/Raven.Studio/typescript/components/pages/database/tasks/createSampleData/CreateSampleData.scss
  src/Raven.Studio/wwwroot/Content/css/styles-common-scoped.less
  src/Raven.Studio/wwwroot/Content/scss/_layout-tools.scss
Labels: v6.0, Studio

#16885 RavenDB-20887 Fix Running Index indicator
  src/Raven.Studio/typescript/components/common/ProgressCircle.scss
Labels: v6.0, Studio

#16887 RavenDB-20886 Index count mismatch on sharded database
  src/Raven.Studio/typescript/common/shell/databasesManager.ts
Labels: v6.0, Studio

#16893 RavenDB-20898 The new "Test Index" footer does not allow you to selec…
  src/Raven.Studio/wwwroot/Content/css/bootstrap/variables-body.less
  src/Raven.Studio/wwwroot/Content/css/pages/edit-index.less
Labels: v6.0, Studio

#16825 RavenDB-20634 Id property of embedded object is not wrapped in `Id()` JavaScript function by LINQ.
  src/Raven.Client/Documents/Linq/RavenQueryProviderProcessor.cs
  src/Raven.Client/Util/JavascriptConversionExtensions.cs
  test/SlowTests/Issues/RavenDB-11767.cs
  test/SlowTests/Issues/RavenDB-13016.cs
  test/SlowTests/Issues/RavenDB-20634.cs
Labels: v6.0

#16896 HRINT-3309 Create Gihub Release
  build.ps1
  scripts/githubReleases.ps1
Labels: v5.2

#16895 5.4 to 6.0 merge
  src/Raven.Client/Http/NodeSelector.cs
  src/Raven.Client/Http/RequestExecutor.cs
  src/Raven.Server/Documents/Subscriptions/LiveSubscriptionPerformanceCollector.cs
  src/Raven.Server/Monitoring/Snmp/SnmpOids.cs
  src/Raven.Server/SqlMigration/GenericDatabaseMigrator.cs
  src/Raven.Studio/package-lock.json
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/smugglerDatabaseDetails.ts
  test/SlowTests/Issues/RavenDB-20783.cs
  test/SlowTests/Server/Documents/Migration/BasicMigrationTests.cs
Labels: v6.0

#16904 RavenDB-20904 SearchOptions & SearchOperator: Fix comments descriptions
  src/Raven.Client/Documents/Queries/SearchOperator.cs
  src/Raven.Client/Documents/SearchOptions.cs
  src/Raven.Client/Documents/Session/AbstractDocumentQuery.cs
  src/Raven.Client/Documents/Session/IAbstractDocumentQuery.cs
  src/Raven.Client/Documents/Session/IDocumentQueryBase.cs
Labels: v5.2

#16902 RavenDB-19847: Fix for SlowTests.Server.Documents.PeriodicBackup.PeriodicBackupTestsSlow.ShouldScheduleNextBackupAfterServerRestartCorrectly()
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
Labels: v5.2

#16906 5.4 to 6.0 merge
  build.ps1
  scripts/githubReleases.ps1
  src/Raven.Client/Http/RequestExecutor.cs
  test/SlowTests/Issues/RavenDB-20882.cs
  test/SlowTests/Issues/RavenDB_20914.cs
Labels: v6.0

#16908 RavenDB-20711 Update RavenDB logo with no gradient
  src/Raven.Server/Web/Assets/AuthError.html
  src/Raven.Server/Web/Assets/Unsafe.html
  src/Raven.Studio/wwwroot/Content/img/ravendb_logo.png
  src/Raven.Studio/wwwroot/Content/img/ravendb_logo.svg
  src/Raven.Studio/wwwroot/icons/android-chrome-192x192.png
  src/Raven.Studio/wwwroot/icons/android-chrome-512x512.png
  src/Raven.Studio/wwwroot/icons/apple-touch-icon-precomposed.png
  src/Raven.Studio/wwwroot/icons/apple-touch-icon.png
  src/Raven.Studio/wwwroot/icons/favicon-16x16.png
  src/Raven.Studio/wwwroot/icons/favicon-32x32.png
  src/Raven.Studio/wwwroot/icons/favicon.ico
  src/Raven.Studio/wwwroot/icons/mstile-150x150.png
Labels: v5.4

#16866 RavenDB-20788 : wait for SourceMigrationCleanup command to be applied in orchestrators before starting bucket deletion
  src/Raven.Server/Documents/Sharding/ShardedDocumentDatabase.cs
Labels: v6.0

#16915 RavenDB-20931 tighten the test
  test/SlowTests/Sharding/Replication/ShardedExternalReplicationTests.cs
  test/Tests.Infrastructure/ReplicationInstance.cs
Labels: v6.0

#16916 RavenDB-20912 adjust tests
  test/SlowTests/Sharding/Cluster/BucketStatsTests.cs
Labels: v6.0

#16910 RavenDB-20890 better exception when compacting sharded database
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
Labels: v6.0

#16907 RavenDB-20915 changed Databases.MaxIdleTimeInSec scope to ServerWideOrPerDatabase
  src/Raven.Server/Config/Categories/DatabaseConfiguration.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Web/System/DatabasesDebugHandler.cs
  test/SlowTests/Issues/RavenDB_20915.cs
Labels: v5.4

#16914 RavenDB-20908 Importing SQL import configuration doesn't preserve emb…
  src/Raven.Studio/typescript/models/database/tasks/sql/sqlMigration.ts
Labels: v5.4, Studio

#16918 5.2 to 5.4 merge
  src/Raven.Client/Documents/Queries/SearchOperator.cs
  src/Raven.Client/Documents/SearchOptions.cs
  src/Raven.Client/Documents/Session/AbstractDocumentQuery.cs
  src/Raven.Client/Documents/Session/IAbstractDocumentQuery.cs
  src/Raven.Client/Documents/Session/IDocumentQueryBase.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
Labels: v5.4

#16920 RavenDB-19967: Notification/warning about tombstone cleaner subscribers disabled (Studio part)
  src/Raven.Studio/typescript/common/notifications/notificationCenter.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/alerts/blockingTombstonesDetails.ts
  src/Raven.Studio/wwwroot/App/views/common/notificationCenter/detailViewer/alerts/blockingTombstonesDetails.html
  tools/TypingsGenerator/Program.cs
Labels: v5.4

#16917 RavenDB-20882 Support for surrogate characters in alphanumerical sorting.
  src/Raven.Server/Documents/Queries/Sorting/AlphaNumeric/AlphaNumericFieldComparator.cs
  test/SlowTests/Issues/RavenDB-20882.cs
Labels: v6.0

#16921 RavenDB-20927 Corax: can delete null/empty from stored values.
  src/Corax/IndexWriter.cs
  test/SlowTests/Issues/RavenDB_20927.cs
Labels: v6.0

#16923 RavenDB-19967: Notification/warning about tombstone cleaner subscribers disabled (failing test fix)
  test/SlowTests/Issues/RavenDB-19967.cs
Labels: v5.4

#16924 RavenDB-7070 we should not await for the log to be written in NotifyAboutClusterTopologyAndConnectivityChanges
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Utils/UnhandledExceptions.cs
Labels: v5.4

#16922 RavenDB-20653 NativeList test
  src/Voron/Util/NativeList.cs
  test/FastTests/Corax/EntriesModificationsTests.cs
  test/SlowTests/Voron/NativeListTests.cs
Labels: v6.0

#16925 RavenDB-20901 properly counting number of returned items, we now are iterating one item more to check if we haven't encountered e.g. counter group where all the items contain same etag
  src/Raven.Server/Documents/Indexes/Test/TestIndexRun.cs
  src/Raven.Server/Documents/Indexes/Workers/MapItems.cs
Labels: v6.0

#16926 RavenDB-20923 Corax - sorting more than 4K doubles (with negative val…
  src/Corax/IndexWriter.cs
  test/SlowTests/Corax/RavenDB-20923.cs
Labels: v6.0

#16928 RavenDB-20547 - SlowTests.Client.TimeSeries.Replication.TimeSeriesRep…
  test/SlowTests/Client/TimeSeries/Replication/TimeSeriesReplicationTests.cs
Labels: v6.0

#16897 RavenDB-20807 - SlowTests.Server.Replication.ReplicationOfConflicts.R…
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  test/SlowTests/Sharding/Replication/ShardedExternalReplicationTests.cs
Labels: v6.0

#16929 RavenDB-20944 Corax doesn't delete index entries
  src/Corax/IndexWriter.cs
Labels: v6.0

#16938 RavenDB-20700 - Expose the managed allocations usage for Lucene term cache
  libs/Lucene.Net.3.0.54009.nupkg
  libs/Lucene.Net.3.0.54010.nupkg
  libs/Lucene.Net.Contrib.Spatial.NTS.3.0.54009.nupkg
  libs/Lucene.Net.Contrib.Spatial.NTS.3.0.54010.nupkg
  src/Raven.Server/Documents/Handlers/Debugging/MemoryDebugHandler.cs
  src/Raven.Server/Indexing/LuceneCleaner.cs
  src/Raven.Server/Indexing/LuceneVoronDirectory.cs
  src/Raven.Server/Raven.Server.csproj
  src/Sparrow/Utils/MemoryUtils.cs
  src/Sparrow/Utils/NativeMemory.cs
Labels: v5.4

#16935 RavenDB-20958 fixing test
  test/SlowTests/Core/Indexing/BloomFilters.cs
Labels: v5.4

#16939 5.4 to 6.0 merge
  libs/Lucene.Net.3.0.60008.nupkg
  libs/Lucene.Net.3.0.60009.nupkg
  libs/Lucene.Net.Contrib.Spatial.NTS.3.0.60008.nupkg
  libs/Lucene.Net.Contrib.Spatial.NTS.3.0.60009.nupkg
  src/Raven.Client/Documents/Operations/Backups/PeriodicBackupConfiguration.cs
  src/Raven.Client/Documents/Operations/ETL/Elasticsearch/ElasticSearchEtlConfiguration.cs
  src/Raven.Client/Documents/Operations/ETL/EtlConfiguration.cs
  src/Raven.Client/Documents/Operations/ETL/OLAP/OlapEtlConfiguration.cs
  src/Raven.Client/Documents/Operations/ETL/Queue/QueueEtlConfiguration.cs
  src/Raven.Client/Documents/Operations/ETL/RavenEtlConfiguration.cs
  src/Raven.Client/Documents/Operations/ETL/SQL/SqlEtlConfiguration.cs
  src/Raven.Client/Documents/Operations/Replication/ExternalReplication.cs
  src/Raven.Client/Documents/Operations/Replication/ExternalReplicationBase.cs
  src/Raven.Client/Documents/Operations/Replication/InternalReplication.cs
  src/Raven.Client/Documents/Operations/Replication/PullReplicationAsSink.cs
  src/Raven.Client/Documents/Operations/Replication/PullReplicationDefinition.cs
  src/Raven.Client/Documents/Replication/ReplicationNode.cs
  src/Raven.Client/ServerWide/Operations/OngoingTasks/ITombstoneDeletionBlocker.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/ETL/EtlLoader.cs
  src/Raven.Server/Documents/Handlers/Debugging/MemoryDebugHandler.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
  src/Raven.Server/Documents/Replication/BucketMigrationReplication.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/Documents/TombstoneCleaner.cs
  src/Raven.Server/Indexing/LuceneCleaner.cs
  src/Raven.Server/Indexing/LuceneVoronDirectory.cs
  src/Raven.Server/Json/JsonDeserializationServer.cs
  src/Raven.Server/NotificationCenter/TombstoneNotifications.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Utils/UnhandledExceptions.cs
  src/Raven.Studio/typescript/models/database/tasks/ongoingTaskElasticSearchEtlEditModel.ts
  src/Raven.Studio/typescript/models/database/tasks/ongoingTaskModel.ts
  src/Raven.Studio/typescript/models/database/tasks/ongoingTaskOlapEtlEditModel.ts
  src/Raven.Studio/typescript/models/database/tasks/ongoingTaskQueueEtlEditModel.ts
  src/Raven.Studio/typescript/models/database/tasks/ongoingTaskRavenEtlEditModel.ts
  src/Raven.Studio/typescript/models/database/tasks/ongoingTaskReplicationEditModel.ts
  src/Raven.Studio/typescript/models/database/tasks/ongoingTaskReplicationHubEditModel.ts
  src/Raven.Studio/typescript/models/database/tasks/ongoingTaskSqlEtlEditModel.ts
  src/Raven.Studio/typescript/models/database/tasks/periodicBackup/backupConfiguration.ts
  src/Raven.Studio/typescript/models/database/tasks/periodicBackup/periodicBackupConfiguration.ts
  src/Raven.Studio/typescript/test/stubs/TasksStubs.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/alerts/blockingTombstonesDetails.ts
  src/Sparrow/Utils/MemoryUtils.cs
  src/Sparrow/Utils/NativeMemory.cs
  test/SlowTests/Core/Indexing/BloomFilters.cs
  test/SlowTests/Issues/RavenDB-19967.cs
  test/SlowTests/Issues/RavenDB_10656.cs
  test/SlowTests/Server/Documents/Indexing/MapReduce/OutputReduceToCollectionReplicationTests.cs
  test/SlowTests/Server/Documents/Revisions/RevisionsReplication.cs
  test/Tests.Infrastructure/ReplicationTestBase.cs
  tools/TypingsGenerator/Program.cs
Labels: v6.0

#16942 RavenDB-20889 fixing remote endpoints in ETL and Subscriptions performance stats proxy
  src/Raven.Server/Documents/ETL/Handlers/Processors/AbstractEtlHandlerProcessorForPerformanceLive.cs
  src/Raven.Server/Documents/Handlers/Processors/Subscriptions/AbstractSubscriptionsHandlerProcessorForPerformanceLive.cs
Labels: v6.0

#16945 RavenDB-20394 - SlowTests.Sharding.Cluster.ShardedClusterObserverTests.DynamicNodeDistributionForOrchestrator
  test/SlowTests/Sharding/Cluster/ShardedClusterObserverTests.cs
Labels: v6.0

#16951 RavenDB-20968 dereference shard & orchestrator executors
  src/Raven.Server/Documents/Sharding/Executors/AbstractExecutor.cs
  src/Raven.Server/Documents/Sharding/ShardedDatabaseContext.cs
Labels: v6.0
