Repository ravendb/ravendb, pull requests merged in 2023-01, with the labels that each got.

#15525 RavenDB-19660 Reduce contention on the AllocHGlobal
  src/Raven.Server/Documents/Sharding/Commands/ShardedQueryCommand.cs
  src/Raven.Server/Documents/Sharding/Executors/ShardExecutor.cs
  src/Raven.Server/Documents/Sharding/Operations/ShardedQueryOperation.cs
  test/FastTests/Sharding/Queries/BasicShardedQueryTests.cs
Labels: v6.0

#15523 RavenDB-16277 : Sharding - Encryption - add test
  test/SlowTests/Sharding/Encryption/ShardedEncryption.cs
Labels: v6.0

#15471 RavenDB-19668: use different schemas for document storage
  src/Raven.Server/Documents/AttachmentsStorage.cs
  src/Raven.Server/Documents/ConflictsStorage.cs
  src/Raven.Server/Documents/CountersStorage.cs
  src/Raven.Server/Documents/DocumentPutAction.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Handlers/DocumentHandler.cs
  src/Raven.Server/Documents/Handlers/Processors/Attachments/AttachmentHandlerProcessorForGetHashCount.cs
  src/Raven.Server/Documents/Handlers/Processors/Stats/StatsHandlerProcessorForGetDatabaseStatistics.cs
  src/Raven.Server/Documents/Indexes/IndexStorage.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
  src/Raven.Server/Documents/Replication/Incoming/IncomingReplicationHandler.cs
  src/Raven.Server/Documents/Replication/Outgoing/DatabaseOutgoingReplicationHandler.cs
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  src/Raven.Server/Documents/Schemas/Attachments.cs
  src/Raven.Server/Documents/Schemas/Conflicts.cs
  src/Raven.Server/Documents/Schemas/Counters.cs
  src/Raven.Server/Documents/Schemas/DeletedRanges.cs
  src/Raven.Server/Documents/Schemas/Documents.cs
  src/Raven.Server/Documents/Schemas/Revisions.cs
  src/Raven.Server/Documents/Schemas/TimeSeries.cs
  src/Raven.Server/Documents/Schemas/Tombstones.cs
  src/Raven.Server/Documents/Sharding/ShardedDocumentsStorage.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesReader.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesStorage.cs
  src/Raven.Server/NotificationCenter/BackgroundWork/DatabaseStatsSender.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterMaintenanceWorker.cs
  src/Raven.Server/Smuggler/Documents/DatabaseSource.cs
  src/Raven.Server/Storage/Schema/SchemaUpgrader.cs
  src/Raven.Server/Storage/Schema/Updates/Documents/60000/From50002.cs
  test/SlowTests/Client/Attachments/AttachmentsRevisions.cs
  test/SlowTests/Issues/RavenDB-8451.cs
  test/SlowTests/Sharding/Cluster/BucketStats.cs
Labels: v6.0

#15506 RavenDB-7070 Revert WIP code.
  src/Raven.Server/Program.cs
Labels: Corax, v5.4

#15520 RavenDB-19716 : Sharding - Backup - NRE when going to backup tab in studio
  src/Raven.Client/Documents/Operations/Backups/Sharding/GetShardedPeriodicBackupStatusOperation.cs
  src/Raven.Server/Web/System/Processors/Backups/BackupDatabaseHandlerProcessorForGetPeriodicBackupStatus.cs
  test/SlowTests/Sharding/Backup/ShardedBackupTests .cs
Labels: v6.0

#15501 RavenDB-17575 - Requests carrying timeseries are not visible on studio dashboards
  src/Raven.Server/Dashboard/DatabasesInfoRetriever.cs
Labels: v5.2

#15427 RavenDB-18515 - Creating replication from SINK to HUB results NRE
  src/Raven.Server/Utils/ThreadsUsage.cs
  test/SlowTests/Issues/RavenDB-18515.cs
Labels: v5.2

#15532 RavenDB-19724 - Improve the performance of PutDocument
  src/Raven.Server/Documents/DocumentPutAction.cs
Labels: v5.4

#15536 RavenDB-19680 add EP to start the resharding
  src/Raven.Server/Documents/Sharding/Handlers/ReshardingHandler.cs
  src/Raven.Server/ServerWide/Commands/Sharding/StartBucketMigrationCommand.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterObserver.cs
Labels: v6.0

#15537 RavenDB-18753 Sharding - Manage database group - ability to edit sing…
  src/Raven.Studio/typescript/components/pages/resources/manageDatabaseGroup/NodeInfoComponent.tsx
  src/Raven.Studio/typescript/components/pages/resources/manageDatabaseGroup/ShardsGroup.tsx
  src/Raven.Studio/typescript/viewmodels/shell.ts
  src/Raven.Studio/wwwroot/App/views/shell.html
Labels: v6.0

#15535 RavenDB-7070 Marking the test as non disposable so SlowTests.Tests.NoNonDisposableTests.ShouldExist won't be failing
  test/FastTests/Corax/EntriesModificationsTests.cs
Labels: v5.4

#15538 RavenDB-19680 change EP to POST
  src/Raven.Server/Documents/Sharding/Handlers/ReshardingHandler.cs
Labels: v6.0

#15528 RavenDB-19663: Snapshot backup without indexes does not calculate in lack of indexes for the space required for backup
  src/Raven.Server/Documents/PeriodicBackup/BackupTask.cs
Labels: v5.2

#15542 5.3 to 5.4 merge
  bench/Micro.Benchmark/Micro.Benchmark.csproj
  bench/Regression.Benchmark/Regression.Benchmark.csproj
  bench/Voron.Benchmark/Voron.Benchmark.csproj
  src/Raven.Server/Dashboard/DatabasesInfoRetriever.cs
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/PeriodicBackup/BackupTask.cs
  src/Raven.Server/Documents/TcpHandlers/SubscriptionConnection.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Server/Storage/Schema/SchemaUpgrader.cs
  src/Raven.Server/Utils/ThreadsUsage.cs
  test/BenchmarkTests/BenchmarkTests.csproj
  test/EmbeddedTests/EmbeddedTests.csproj
  test/FastTests/FastTests.csproj
  test/InterversionTests/InterversionTests.csproj
  test/LicenseTests/LicenseTests.csproj
  test/RachisTests/RachisTests.csproj
  test/SlowTests/Issues/RavenDB-18515.cs
  test/SlowTests/Issues/RavenDB-19519.cs
  test/SlowTests/SlowTests.csproj
  test/StressTests/StressTests.csproj
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
  tools/rvn/rvn.csproj
Labels: v5.4

#15547 RavenDB-18116 add to sharded subscription try the shard number
  src/Raven.Client/Extensions/BlittableJsonExtensions.cs
  src/Raven.Server/Documents/Sharding/Operations/ShardedSubscriptionTryoutOperation.cs
Labels: v6.0

#15548 RavenDB-19732 SlowTests.Issues.RavenDB_19519.SchemaUpgradeAddedToInitLog - increased Server.MaxTimeForTaskToWaitForDatabaseToLoad
  test/SlowTests/Issues/RavenDB-19519.cs
Labels: v5.4

#15550 RavenDB-19636 Improve GenerateSchema method to consider multiple documents for determining column types
  src/Raven.Server/Integrations/PostgreSQL/RqlQuery.cs
  test/SlowTests/Issues/RavenDB-19636.cs
Labels: v5.3

#15551 RavenDB-19735 : Sharding - Bucket Stats - wrong stats when tree has multiple pages
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/DocumentsTransaction.cs
  src/Raven.Server/Documents/Sharding/ShardedDocumentsStorage.cs
  src/Voron/Impl/LowLevelTransaction.cs
  src/Voron/Impl/Transaction.cs
  test/SlowTests/Sharding/Cluster/BucketStats.cs
Labels: v6.0

#15545 RavenDB-19361 - use a struct allocator to avoid heap allocation when …
  src/Corax/Queries/AllEntriesMatch.cs
  src/Voron/Data/Containers/Container.cs
  src/Voron/Debugging/StorageReportGenerator.cs
Labels: Corax, v5.4

#15561 RavenDB-19607 exclude web socket requests from request time duration metrics
  src/Raven.Server/RavenServerStartup.cs
Labels: v5.4

#15552 RavenDB-19736 - Add details to the PutIndexCommand logging
  src/Raven.Server/ServerWide/Commands/Indexes/PutIndexCommand.cs
Labels: v5.4

#15549 RavenDB-19516 - Delay Replication on missing attachments loop
  src/Raven.Server/Documents/Replication/OutgoingReplicationHandler.cs
Labels: v5.2

#15564 RavenDB-19727 - add before and after memory stats after running the GC operation
  src/Raven.Server/Documents/Handlers/Admin/AdminMemoryHandler.cs
Labels: v5.4

#15566 RavenDB-19739 Fix small bug in load-balance test
  test/SlowTests/Issues/RavenDB-14978.cs
Labels: v5.2

#15568 5.2 to 5.3 merge
  src/Raven.Server/Config/Categories/LogsConfiguration.cs
  src/Raven.Server/Documents/Handlers/Admin/AdminLogsHandler.cs
  src/Raven.Server/Documents/Replication/OutgoingReplicationHandler.cs
  src/Raven.Server/NotificationCenter/NotificationCenter.cs
  src/Raven.Server/NotificationCenter/Notifications/AlertType.cs
  src/Raven.Server/RavenServer.cs
  src/Raven.Server/Utils/MicrosoftLogging/MicrosoftLoggingProvider.cs
  src/Raven.Server/Utils/MicrosoftLogging/SparrowLoggerWrapper.cs
  src/Raven.Server/Utils/MicrosoftLogging/WebHostBuilderExtensions.cs
  test/SlowTests/Client/Subscriptions/LimitSubscriptionsConnectionsAmount.cs
  test/SlowTests/Issues/RavenDB-14978.cs
  test/SlowTests/Issues/RavenDB-19519.cs
  test/SlowTests/SparrowTests/MicrosoftLogTests.cs
Labels: v5.3

#15569 5.3 to 5.4 merge
  src/Raven.Server/Config/Categories/LogsConfiguration.cs
  src/Raven.Server/Documents/Handlers/Admin/AdminLogsHandler.cs
  src/Raven.Server/Documents/Replication/OutgoingReplicationHandler.cs
  src/Raven.Server/Integrations/PostgreSQL/RqlQuery.cs
  src/Raven.Server/NotificationCenter/NotificationCenter.cs
  src/Raven.Server/NotificationCenter/Notifications/AlertType.cs
  src/Raven.Server/RavenServer.cs
  src/Raven.Server/Utils/MicrosoftLogging/MicrosoftLoggingProvider.cs
  src/Raven.Server/Utils/MicrosoftLogging/SparrowLoggerWrapper.cs
  src/Raven.Server/Utils/MicrosoftLogging/WebHostBuilderExtensions.cs
  test/SlowTests/Client/Subscriptions/LimitSubscriptionsConnectionsAmount.cs
  test/SlowTests/Issues/RavenDB-14978.cs
  test/SlowTests/Issues/RavenDB-19636.cs
  test/SlowTests/SparrowTests/MicrosoftLogTests.cs
Labels: v5.4

#15570 RavenDB-7070 Updating PR template by adding additional check about testing by QA team
  .github/pull_request_template.md
Labels: v5.4

#15575 RavenDB-19677 Sharding - Studio - Go to all shards mode not working
  src/Raven.Studio/typescript/common/appUrl.ts
Labels: v6.0

#15577 RavenDB-17977 - change function access to internal
  src/Raven.Client/ServerWide/DatabaseRecord.cs
  src/Raven.Client/ServerWide/Sharding/ShardingConfiguration.cs
Labels: v6.0

#15582 5.2 to 5.3 merge
  src/Raven.Server/Documents/Replication/OutgoingReplicationHandler.cs
  src/Raven.Server/NotificationCenter/Notifications/Details/ExceptionDetails.cs
Labels: v5.3

#15574 RavenDB-19633 EmbeddedTest configure log path to uniq location
  test/EmbeddedTests/BasicTests.cs
  test/EmbeddedTests/EmbeddedTestBase.cs
  test/EmbeddedTests/Issues/RavenDB_15885.cs
  test/EmbeddedTests/SmugglerTests.cs
Labels: v5.4

#15588 RavenDB-19662
  src/Raven.Client/Documents/Operations/Backups/Sharding/ShardRestoreSettings.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/Sharding/ShardedRestoreOrchestrationTask.cs
  test/SlowTests/Sharding/Backup/ShardedRestoreBackupTests.cs
  test/Tests.Infrastructure/RavenTestBase.ShardedBackupTestsBase.cs
Labels: v6.0

#15586 RavenDB-18185 : Resharding - ETL tests
  test/SlowTests/Sharding/ETL/ShardedEtlTests.cs
Labels: v6.0

#15581 RavenDB-18183 - Sharding - Resharding - External & Pull Replication -…
  test/InterversionTests/ReplicationTests.cs
  test/RachisTests/DatabaseCluster/ReplicationTests.cs
  test/SlowTests/Server/Replication/ExternalReplicationTests.cs
  test/SlowTests/Sharding/Replication/ShardedExternalReplicationTests.cs
Labels: v6.0

#15579 RavenDB-16758 Refactor exception message when swap size is 0
  src/Raven.Server/ServerWide/ServerStore.cs
Labels: v5.2

#15553 RavenDB-16751 Allow to get number of revisions in ETL script
  src/Raven.Server/Documents/ETL/EtlTransformer.cs
  test/SlowTests/Issues/RavenDB-16751.cs
Labels: v5.4

#15556 RavenDB-19538 Metadata not tracked in the subscription session
  src/Raven.Client/Documents/Subscriptions/SubscriptionBatch.cs
  test/SlowTests/Issues/RavenDB-19538.cs
Labels: v5.4

#15595 RavenDB-18753 Sharding - Manage database group
  src/Raven.Studio/typescript/commands/database/dbGroup/addNodeToShardCommand.ts
  src/Raven.Studio/typescript/commands/database/dbGroup/addShardToDatabaseGroupCommand.ts
  src/Raven.Studio/typescript/components/pages/resources/manageDatabaseGroup/ManageDatabaseGroupPage.tsx
  src/Raven.Studio/typescript/viewmodels/resources/addNewOrchestatorToDatabaseGroup.ts
  src/Raven.Studio/typescript/viewmodels/resources/addNewShardToDatabaseGroup.ts
  src/Raven.Studio/wwwroot/App/views/resources/addNewOrchestratorToDatabaseGroup.html
  src/Raven.Studio/wwwroot/App/views/resources/addNewShardToDatabaseGroup.html
  tools/TypingsGenerator/Program.cs
Labels: v6.0

#15596 RavenDB-19761 Fix metadata modification for collection view
  src/Raven.Server/Documents/Sharding/Changes/ShardedChangesClientConnection.cs
  src/Raven.Server/Web/Studio/Sharding/Processors/ShardedStudioCollectionsHandlerProcessorForPreviewCollection.cs
Labels: v6.0

#15587 RavenDB-19731 Show the Raft Index tooltip after saving
  src/Raven.Studio/typescript/viewmodels/database/cmpXchg/editCmpXchg.ts
Labels: v5.4

#15599 RavenDB-18009 Database list view - shard wide view
  src/Raven.Studio/typescript/commands/database/tasks/testSubscriptionTaskCommand.ts
  src/Raven.Studio/typescript/components/pages/resources/databases/DatabasesToolbarActions.tsx
Labels: v6.0

#15598 RavenDB-19758: Disable VxSort in architectures without hardware PopCount instructions
  src/Sparrow.Server/Utils/VxSort/VectorizedSort.cs
  src/Sparrow.Server/Utils/VxSort/VectorizedSort.generated.cs
  src/Sparrow.Server/Utils/VxSort/codegen/sorting_main.py
Labels: Corax, v5.4

#15600 RavenDB-19766 Optimization if user knows what shards it is on
  src/Raven.Server/Documents/Sharding/Queries/ShardedQueryProcessor.cs
Labels: v6.0

#15601 RavenDB-19758: Removed VxSort for 32 bits for all platforms.
  src/Sparrow.Server/Utils/VxSort/VectorizedSort.cs
  src/Sparrow.Server/Utils/VxSort/VectorizedSort.generated.cs
  src/Sparrow.Server/Utils/VxSort/codegen/sorting_main.py
Labels: v5.4

#15602 RavenDB-19746 fix issue with allocating less than allocation unit
  src/Sparrow.Server/ByteString.cs
Labels: v5.2

#15605 RavenDB-15091 - RachisTests.DatabaseCluster.ClusterDatabaseMaintenance.ChangeUrlOfMultiNodeCluster
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
Labels: v5.2

#15594 RavenDB-16500 - Cannot start SinkToHub replication
  src/Raven.Client/Documents/Operations/Replication/PullReplicationDefinition.cs
  test/SlowTests/Server/Replication/PullReplicationTests.cs
Labels: v5.2

#15592 RavenDB-19760 - fix gc dump output file
  tools/Raven.Debug/GCDump/GCHeapDump.cs
Labels: v5.2

#15607 5.2 to 5.4 merge
  src/Raven.Client/Documents/Operations/Backups/DelayBackupOperation.cs
  src/Raven.Client/Documents/Operations/Backups/PeriodicBackupStatus.cs
  src/Raven.Client/Documents/Operations/OngoingTasks/GetTaskInfoResult.cs
  src/Raven.Client/Documents/Operations/Replication/PullReplicationDefinition.cs
  src/Raven.Client/Http/ClusterTopology.cs
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/PeriodicBackup/BackupTask.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/ServerWide/ClusterCommandsVersionManager.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/Commands/DelayBackupCommand.cs
  src/Raven.Server/ServerWide/Commands/UpdateValueForDatabaseCommand.cs
  src/Raven.Server/ServerWide/JsonDeserializationCluster.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Smuggler/Documents/CsvStreamSource.cs
  src/Raven.Server/Utils/BackupUtils.cs
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
  src/Raven.Server/Web/System/OngoingTasksHandler.cs
  src/Raven.Studio/typescript/commands/database/tasks/delayBackupCommand.ts
  src/Raven.Studio/typescript/models/database/tasks/ongoingTaskBackupListModel.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/smugglerDatabaseDetails.ts
  src/Raven.Studio/wwwroot/App/views/common/notificationCenter/detailViewer/operations/smugglerDatabaseDetails.html
  src/Sparrow.Server/ByteString.cs
  test/EmbeddedTests/BasicTests.cs
  test/EmbeddedTests/EmbeddedTestBase.cs
  test/EmbeddedTests/Issues/RavenDB_15885.cs
  test/EmbeddedTests/SmugglerTests.cs
  test/FastTests/Client/RavenCommandTest.cs
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
  test/RachisTests/EmergencyOperations.cs
  test/SlowTests/Issues/RavenDB_9519.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
  test/SlowTests/Server/Replication/PullReplicationTests.cs
  test/SlowTests/Smuggler/RavenDB-16709.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
  test/Tests.Infrastructure/RavenTestBase.Backup.cs
  tools/Raven.Debug/GCDump/GCHeapDump.cs
Labels: v5.4

#15615 RavenDB-19774 - test RavenDB_18515.Can_Set_Pin_To_Node_Pull_Replication_As_Sink fails
  test/SlowTests/Issues/RavenDB-18515.cs
Labels: v5.2

#15616 RavenDB-18009 Database list view - improve topology data design
  src/Raven.Studio/typescript/components/common/NodeSet.tsx
  src/Raven.Studio/wwwroot/Content/scss/_bs5extend.scss
Labels: v6.0

#15620 RavenDB-19753: It is unsafe for MemoizationMatchProvider be a struct.
  src/Corax/Queries/MemoizationMatch.Provider.cs
  src/Corax/Utils/MemoizationMatchProviderRef.cs
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxQueryBuilder.cs
  src/Raven.Server/Documents/Indexes/Persistence/Corax/QueryOptimizer/CoraxAndQueries.cs
Labels: Corax, v5.4

#15625 RavenDB-19776 Sharding - modify debug EP path
  src/Raven.Server/Web/Studio/Processors/AbstractBucketsHandlerProcessorForGetBucket.cs
  src/Raven.Server/Web/Studio/Processors/AbstractBucketsHandlerProcessorForGetBuckets.cs
  src/Raven.Server/Web/Studio/Sharding/BucketsHandler.cs
  src/Raven.Server/Web/Studio/Sharding/ShardedBucketsHandler.cs
  src/Raven.Studio/typescript/commands/database/debug/getBucketCommand.ts
  src/Raven.Studio/typescript/commands/database/debug/getBucketsCommand.ts
  src/Raven.Studio/typescript/commands/database/tasks/delayBackupCommand.ts
Labels: v6.0

#15641 RavenDB-19235 Add the ability to cancel and delay server-wide backups…
  src/Raven.Studio/wwwroot/App/views/common/notificationCenter/detailViewer/operations/smugglerDatabaseDetails.html
Labels: v5.4

#15640 RavenDB-19834 Fix 2022 => 2023
  src/CommonAssemblyInfo.cs
  src/Raven.Studio/wwwroot/App/views/shell/about.html
Labels: v5.2

#15632 RavenDB-19823 Opening counters tab on a document ends with TypeError:…
  src/Raven.Studio/typescript/viewmodels/database/documents/editDocument.ts
Labels: v5.4

#15626 RavenDB-19798 decrease number of held items in ocumentBuilder for x86 to avoid holding more than 300mb of managed memory when running process for a long time
  src/Sparrow/Json/AbstractBlittableJsonDocumentBuilder.cs
Labels: v5.2

#15646 RavenDB-19179 Fix margin issues
  src/Raven.Studio/typescript/viewmodels/database/settings/databaseSettings.ts
  src/Raven.Studio/wwwroot/App/views/common/detectBrowser.html
  src/Raven.Studio/wwwroot/App/views/common/sharding/shardSelector.html
  src/Raven.Studio/wwwroot/App/views/database/advanced/databaseIDs.html
  src/Raven.Studio/wwwroot/App/views/database/documents/editDocument.html
  src/Raven.Studio/wwwroot/App/views/database/identities/identities.html
  src/Raven.Studio/wwwroot/App/views/database/indexes/additionalTabsCommonText.html
  src/Raven.Studio/wwwroot/App/views/database/indexes/deleteIndexesConfirm.html
  src/Raven.Studio/wwwroot/App/views/database/indexes/dumpDialog.html
  src/Raven.Studio/wwwroot/App/views/database/indexes/editIndex.html
  src/Raven.Studio/wwwroot/App/views/database/indexes/mapIndexSyntax.html
  src/Raven.Studio/wwwroot/App/views/database/indexes/mapReduceIndexSyntax.html
  src/Raven.Studio/wwwroot/App/views/database/indexes/optimizeDialog.html
  src/Raven.Studio/wwwroot/App/views/database/patch/patch.html
  src/Raven.Studio/wwwroot/App/views/database/patch/patchSyntax.html
  src/Raven.Studio/wwwroot/App/views/database/settings/clientConfiguration.html
  src/Raven.Studio/wwwroot/App/views/database/settings/connectionStringElasticSearch.html
  src/Raven.Studio/wwwroot/App/views/database/settings/connectionStrings.html
  src/Raven.Studio/wwwroot/App/views/database/settings/databaseSettings.html
  src/Raven.Studio/wwwroot/App/views/database/settings/revertRevisions.html
  src/Raven.Studio/wwwroot/App/views/database/settings/revisions.html
  src/Raven.Studio/wwwroot/App/views/database/settings/saveDatabaseSettingsConfirm.html
  src/Raven.Studio/wwwroot/App/views/database/settings/studioConfiguration.html
  src/Raven.Studio/wwwroot/App/views/database/settings/timeSeries.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editElasticSearchEtlTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editExternalReplicationTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editKafkaEtlTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editOlapEtlTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editRabbitMqEtlTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editRavenEtlTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editReplicationHubTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editReplicationSinkTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editSqlEtlTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/exportDatabase.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/generateReplicationCertificateConfirm.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/importDatabaseFromFile.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/migrateRavenDbDatabase.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/smugglerDatabaseRecord.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/transformationScriptSyntax.html
  src/Raven.Studio/wwwroot/App/views/database/timeSeries/filterTimeSeries.html
  src/Raven.Studio/wwwroot/App/views/manage/adminLogs.html
  src/Raven.Studio/wwwroot/App/views/manage/adminLogsTrafficWatchDialog.html
  src/Raven.Studio/wwwroot/App/views/manage/captureStackTraces.html
  src/Raven.Studio/wwwroot/App/views/manage/certificates.html
  src/Raven.Studio/wwwroot/App/views/manage/clientConfiguration.html
  src/Raven.Studio/wwwroot/App/views/manage/editServerWideExternalReplication.html
  src/Raven.Studio/wwwroot/App/views/manage/serverSettings.html
  src/Raven.Studio/wwwroot/App/views/manage/studioConfiguration.html
  src/Raven.Studio/wwwroot/App/views/manage/threadStackTrace.html
  src/Raven.Studio/wwwroot/App/views/manage/trafficWatchQueriesDialog.html
  src/Raven.Studio/wwwroot/App/views/notifications/notificationCenter.html
  src/Raven.Studio/wwwroot/App/views/resources/widgets/settings/storageWidgetSettings.html
  src/Raven.Studio/wwwroot/App/views/resources/widgets/welcomeWidget.html
  src/Raven.Studio/wwwroot/App/views/shell/about.html
  src/Raven.Studio/wwwroot/App/views/shell/registration.html
  src/Raven.Studio/wwwroot/App/views/wizard/certificate.html
  src/Raven.Studio/wwwroot/App/views/wizard/setupShell.html
  src/Raven.Studio/wwwroot/App/views/wizard/unsecured.html
Labels: v6.0

#15649 5.2 to 5.4 merge
  src/CommonAssemblyInfo.cs
  src/Raven.Client/ServerWide/DatabaseTopology.cs
  src/Raven.Server/Smuggler/Documents/Data/ISmugglerDestination.cs
  src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
  src/Raven.Server/Smuggler/Documents/DatabaseSmuggler.cs
  src/Raven.Server/Smuggler/Documents/StreamDestination.cs
  src/Raven.Studio/wwwroot/App/views/shell/about.html
  src/Sparrow/Json/AbstractBlittableJsonDocumentBuilder.cs
  test/SlowTests/Cluster/ClusterObserverTests.cs
  test/SlowTests/Issues/RavenDB-18515.cs
  test/StressTests/Rachis/DatabaseCluster/ClusterDatabaseMaintenanceStress.cs
Labels: v5.4

#15643 RavenDB-19837 Anonymous projection when using custom conventions fix.
  src/Raven.Client/Documents/Conventions/DocumentConventions.cs
  src/Raven.Client/Documents/Linq/RavenQueryProviderProcessor.cs
  test/SlowTests/Issues/RavenDB-19837.cs
Labels: v6.0

#15614 RavenDB-19235: Add the ability to cancel and delay ongoing backups by Operator
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
Labels: v5.2

#15657 RavenDB-19746 added test for ByteStringContext.DefragmentSegments
  src/Sparrow.Server/ByteString.cs
  test/FastTests/Issues/RavenDB_19746.cs
Labels: v5.4

#15656 RavenDB-19852 MultiGetHandler will follow `AcceptEncoding` from request.
  src/Raven.Server/Documents/Handlers/MultiGetHandler.cs
  test/SlowTests/Issues/RavenDB-19852.cs
Labels: v5.4

#15654 RavenDB-19843 Lucene - order by ticks when field contains dates.
  src/Raven.Server/Config/Categories/IndexingConfiguration.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/LuceneIndexReadOperation.cs
  src/Raven.Studio/typescript/models/database/index/configurationItem.ts
  test/FastTests/Issues/RavenDB_16590.cs
Labels: v5.4

#15652 RavenDB-17966 Unskip facet tests on Corax
  test/SlowTests/Core/Commands/Querying.cs
  test/SlowTests/Core/Querying/Intersection.cs
  test/SlowTests/Tests/Faceted/LargeFacets.cs
  test/SlowTests/Tests/Faceted/LazyFacets.cs
Labels: v5.4

#15662 5.2 to 5.4 merge
  src/Raven.Server/Config/Categories/ReplicationConfiguration.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/LuceneIndexReadOperation.cs
  src/Raven.Server/Documents/Replication/ReplicationDocumentSender.cs
  src/Raven.Server/Indexing/LuceneCleaner.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Utils/Enumerators/PulsedEnumerationState.cs
  test/SlowTests/Issues/RavenDB-19561.cs
  test/SlowTests/Issues/RavenDB_13972.cs
  test/SlowTests/Issues/RavenDB_13972_32_bits.cs
  test/SlowTests/Issues/RavenDB_13972_encrypted.cs
Labels: v5.4

#15665 RavenDB-19235: failing test fix
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
Labels: v5.2

#15679 RavenDB-19858 - Communications with previous versions servers' fails after adding Tcp Compression on cluster communication
  src/Raven.Client/ServerWide/Tcp/TcpNegotiation.cs
Labels: v5.4

#15673 RavenDB-18384 - SlowTests.Client.TimeSeries.Query.QueryFromMultipleTi…
  test/SlowTests/Client/TimeSeries/Query/QueryFromMultipleTimeSeries.cs
Labels: v5.2

#15678 RavenDB-17071 - SlowTests.Cluster.CompareExchangeExpirationTest.CanAd…
  test/SlowTests/Cluster/CompareExchangeExpirationTest.cs
Labels: v5.2

#15677 RavenDB-19857 Use universal time when validating certificate for developer license
  src/Raven.Server/Commercial/LicenseManager.cs
Labels: v5.4

#15676 RavenDB-18689 respect the node for any proxy command
  src/Raven.Server/Documents/Handlers/Processors/AbstractHandlerProxyReadProcessor.cs
Labels: v6.0

#15622 RavenDB-19657 - Failing test StressTests.Client.TimeSeries.TimeSeries…
  src/Raven.Server/Documents/Queries/Results/TimeSeries/TimeSeriesRetriever.cs
Labels: v5.4

#15675 RavenDB-7070 fix docker publish tags for v5.3
  docker/common.ps1
  docker/publish-nanoserver.ps1
Labels: v5.3

#15672 RavenDB-19854 `Logs.Microsoft.ConfigurationPath` as `ReadOnlyPath`
  src/Raven.Server/Config/Categories/LogsConfiguration.cs
Labels: v5.2

#15697 RavenDB-16167 Added SpreadElement handling in EsprimaVisitor
  src/Raven.Server/Documents/Indexes/Static/EsprimaVisitor.cs
  test/SlowTests/Issues/RavenDB-16167.cs
Labels: v5.4

#15702 RavenDB-16108 Backup restore: show that indexes were skipped in the result table (when user set skip indexes).
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreBackupTaskBase.cs
  src/Raven.Server/Smuggler/Documents/DatabaseSmuggler.cs
Labels: v5.4

#15658 RavenDB-18883: Send noop ack cluster command once per state
  src/Raven.Server/Documents/Subscriptions/SubscriptionConnectionsState.cs
  src/Raven.Server/Documents/TcpHandlers/SubscriptionConnection.cs
Labels: v5.4

#15701 RavenDB-19878 Index Errors View: Fix column name
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexErrors.ts
Labels: v5.2

#15705 5.2 to 5.4 merge
  src/Raven.Server/Config/Categories/LogsConfiguration.cs
  src/Raven.Server/Rachis/Follower.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Studio/typescript/commands/resources/compactDatabaseCommand.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexErrors.ts
  src/Raven.Studio/typescript/viewmodels/resources/compactDatabaseDialog.ts
  src/Raven.Studio/wwwroot/App/views/resources/compactDatabaseDialog.html
  test/RachisTests/RavenDB_19654.cs
  test/SlowTests/Cluster/CompareExchangeExpirationTest.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
Labels: v5.4

#15685 RavenDB-19858 - Add tests for cluster communication with tcp compression
  test/InterversionTests/MixedClusterTestBase.cs
  test/InterversionTests/MixedClusterTests.cs
  test/SlowTests/RavenDB-18634.cs
Labels: v5.4

#15706 RavenDB-19681 Sharding - Studio - For sharded database block clone of…
  src/Raven.Studio/typescript/viewmodels/database/documents/editDocument.ts
  src/Raven.Studio/wwwroot/App/views/database/documents/editDocument.html
Labels: v6.0

#15707 RavenDB-19881 Database selector: show you dealing with sharded database
  src/Raven.Studio/wwwroot/App/views/shell.html
Labels: v6.0

#15708 RavenDB-19883 Block tombstones view for sharded database
  src/Raven.Studio/typescript/common/shell/menu/items/settings.ts
  src/Raven.Studio/typescript/viewmodels/database/advanced/tombstonesState.ts
  src/Raven.Studio/wwwroot/App/views/database/advanced/tombstonesState.html
Labels: v6.0

#15709 RavenDB-19880 Test patch is broken
  src/Raven.Studio/wwwroot/Content/css/pages/patch-global.less
  src/Raven.Studio/wwwroot/Content/css/pages/patch.less
  src/Raven.Studio/wwwroot/Content/css/styles.less
Labels: v6.0

#15712 RavenDB-18447 Sharding - The document's properties pane hides the sha…
  src/Raven.Studio/wwwroot/App/views/shell.html
  src/Raven.Studio/wwwroot/Content/css/bootstrap/variables-body.less
  src/Raven.Studio/wwwroot/Content/css/root.less
  src/Raven.Studio/wwwroot/Content/scss/_colors.scss
  src/Raven.Studio/wwwroot/Content/scss/bs5variables.scss
Labels: v6.0

#15695 RavenDB-19874 Fix param name in log message
  src/Raven.Server/Commercial/LicenseManager.cs
Labels: v5.2

#15717 RavenDB-18276 Sharding - Stats View
  src/Raven.Studio/typescript/components/pages/database/status/statistics/logic/models.d.ts
  src/Raven.Studio/typescript/components/pages/database/status/statistics/logic/statisticsSlice.ts
  src/Raven.Studio/typescript/components/pages/database/status/statistics/partials/IndexesDatabaseStats.tsx
  src/Raven.Studio/typescript/components/pages/database/status/statistics/partials/StatsHeader.tsx
Labels: v6.0

#15721 RavenDB-19591 DB stats view - tooltips are broken
  src/Raven.Studio/typescript/components/pages/database/status/statistics/partials/EssentialDatabaseStatsComponent.tsx
  src/Raven.Studio/wwwroot/Content/css/_bs5.scss
  src/Raven.Studio/wwwroot/Content/scss/_bs5extend.scss
  src/Raven.Studio/wwwroot/Content/scss/bs5variables.scss
Labels: v6.0

#15731 RavenDB-19269: fix racy test & bad assert
  test/RachisTests/SubscriptionsFailover.cs
  test/Tryouts/Program.cs
  test/Tryouts/Tryouts.csproj
Labels: v5.4

#15711 RavenDB-19707 - Fix InterversionTests SmugglerTests
  test/InterversionTests/SmugglerTests.cs
Labels: v5.2

#15727 RavenDB-18741: add retry fact to AdditionalAssemblies with NuGet tests
  test/SlowTests/Issues/RavenDB_15753.cs
Labels: v5.2

#15732 RavenDB-19907 Fix param name in log message (2)
  src/Raven.Server/Commercial/LicenseManager.cs
Labels: v5.2

#15667 RavenDB-19853 - Update Lucene
  libs/Lucene.Net.3.0.54003.nupkg
  libs/Lucene.Net.3.0.54004.nupkg
  libs/Lucene.Net.Contrib.Spatial.NTS.3.0.54003.nupkg
  libs/Lucene.Net.Contrib.Spatial.NTS.3.0.54004.nupkg
  src/Raven.Server/Raven.Server.csproj
Labels: v5.4

#15635 Implement a JsString wrapper for LazyStringValue and LazyCompressedStringValue
  src/Raven.Server/Documents/Indexes/Static/JavaScriptReduceOperation.cs
  src/Raven.Server/Documents/Indexes/Static/LazyCompressedJsString.cs
  src/Raven.Server/Documents/Indexes/Static/LazyJsString.cs
  src/Raven.Server/Documents/Patch/BlittableObjectInstance.cs
  src/Raven.Server/Documents/Patch/JintNullPropagationReferenceResolver.cs
  src/Raven.Server/Documents/Patch/JintPreventResolvingTasksReferenceResolver.cs
  src/Raven.Server/Documents/Patch/JintStringConverter.cs
  src/Raven.Server/Documents/Patch/JsBlittableBridge.cs
  src/Raven.Server/Documents/Patch/ScriptRunner.cs
  src/Raven.Server/Raven.Server.csproj
Labels: v6.0

#15734 RavenDB-18193: fix asserting the wrong task
  test/SlowTests/Client/Subscriptions/SubscriptionsBasic.cs
Labels: v5.2
