Repository ravendb/ravendb, pull requests merged in 2023-03, with the labels that each got.

#15910 RavenDB-19851 Adding facet tests for Corax
  test/SlowTests/Core/Querying/Searching.cs
  test/SlowTests/Issues/RavenDB-3179.cs
  test/SlowTests/Issues/RavenDB_2672.cs
  test/SlowTests/MailingList/CanFacetOnList.cs
  test/SlowTests/MailingList/CanRetrieveFacetCountsOfQueryResults.cs
  test/SlowTests/MailingList/CanRetrieveFacetCountsOfQueryResults2.cs
  test/SlowTests/MailingList/FacetCountTest.cs
  test/SlowTests/MailingList/FacetQueryNotCorrectWithDefaultFieldSpecified.cs
  test/SlowTests/MailingList/FacetsMultipleAggregation.cs
  test/SlowTests/MailingList/Georgiosd.cs
  test/SlowTests/MailingList/JustFacetSearch.cs
  test/SlowTests/MailingList/Samina3.cs
  test/SlowTests/MailingList/TomCabanski.cs
  test/SlowTests/SlowTests/Faceted/FacetPaging.cs
  test/SlowTests/Tests/Faceted/FacetedIndexLimit.cs
Labels: Corax, v5.4

#15916 RavenDB-18009 Database list view - shard wide view
  src/Raven.Studio/jest.config.js
  src/Raven.Studio/package-lock.json
  src/Raven.Studio/package.json
  src/Raven.Studio/scripts/setup_jest.js
  src/Raven.Studio/typescript/common/appUrl.ts
  src/Raven.Studio/typescript/components/pages/resources/databases/DatabasesPage.spec.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/DatabasesPage.stories.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/DatabasesPage.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/DatabaseNodeSetItem.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/DatabasePanel.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/ValidDatabasePropertiesPanel.tsx
  src/Raven.Studio/typescript/test/htmlLoader.js
  src/Raven.Studio/typescript/test/stubs/DatabasesStubs.ts
  src/Raven.Studio/typescript/viewmodels/resources/databasesOld.ts
Labels: v6.0

#15917 RavenDB-7070 fixed issue with cloning of blittable in sharded changes API with multiple subscribers + fixed issue with not using appropriate topology when database is being removed
  src/Raven.Server/Documents/Sharding/Changes/ShardedChangesClientConnection.cs
  src/Raven.Server/ServerWide/Commands/DeleteDatabaseCommand.cs
Labels: v6.0

#15921 RavenDB-20026 Can't Enable/Disable ongoing task
  src/Raven.Studio/typescript/components/pages/database/tasks/shared.tsx
Labels: v6.0

#15918 5.2 to 5.4 merge
  src/Raven.Server/Documents/PeriodicBackup/BackupHelper.cs
  src/Raven.Server/Documents/PeriodicBackup/BackupTask.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreBackupTaskBase.cs
  src/Raven.Server/Web/System/OngoingTasksHandler.cs
  test/SlowTests/Issues/RavenDB-18442.cs
Labels: v5.4

#15922 RavenDB-19241 - fixing PR comments
  src/Raven.Server/Documents/Sharding/Background/ShardedPeriodicDocumentsMigrator.cs
  test/SlowTests/Sharding/BucketMigration/PeriodicDocumentsMigrationTests.cs
Labels: v6.0

#15887 5.4 to 6.0 merge
  .github/workflows/studioLabel.yml
  .github/workflows/versionLabel.yml
  docker/build-nanoserver.ps1
  docker/common.ps1
  docker/publish-nanoserver.ps1
  docker/ravendb-nanoserver/Dockerfile.1809
  docker/ravendb-nanoserver/Dockerfile.ltsc2022
  scripts/sign.ps1
  src/Corax/Queries/SortingMatch/SortingMatch.cs
  src/Raven.Client/Documents/Linq/RavenQueryProvider.cs
  src/Raven.Client/Documents/Linq/RavenQueryProviderProcessor.cs
  src/Raven.Client/Documents/Session/AsyncDocumentSession.cs
  src/Raven.Client/Documents/Session/DocumentSession.cs
  src/Raven.Client/Documents/Session/IAdvancedSessionOperations.cs
  src/Raven.Client/Documents/Session/IAsyncAdvancedSessionOperations.cs
  src/Raven.Client/Documents/Session/InMemoryDocumentSessionOperations.cs
  src/Raven.Client/Documents/Subscriptions/AbstractSubscriptionWorker.cs
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxQueryBuilder.cs
  src/Raven.Server/Documents/Indexes/Static/JavaScriptMapOperation.cs
  src/Raven.Server/Documents/Queries/MoreLikeThis/Corax/MoreLikeThis.cs
  src/Raven.Server/Documents/Queries/QueryBuilderHelper.cs
  test/SlowTests/Bugs/Distinct.cs
  test/SlowTests/Corax/CoraxSlowQueryTests.cs
  test/SlowTests/Issues/GH-15634.cs
  test/SlowTests/Issues/RavenDB-19541.cs
  test/SlowTests/Issues/RavenDB-19964.cs
  test/SlowTests/Issues/RavenDB_17973.cs
  test/SlowTests/Issues/RavenDB_19440.cs
  test/SlowTests/Issues/RavenDB_19598.cs
  test/SlowTests/MailingList/OrderByProjectSameField.cs
  test/SlowTests/Server/Documents/ETL/ClusterEtlTimeSeriesTests.cs
  test/Tests.Infrastructure/RavenTestBase.cs
  test/Tests.Infrastructure/RavenTestHelper.cs
Labels: v6.0

#15923 5.2 to 5.4 merge
  bench/Micro.Benchmark/Micro.Benchmark.csproj
  bench/Regression.Benchmark/Regression.Benchmark.csproj
  bench/Voron.Benchmark/Voron.Benchmark.csproj
  bench/VxSort.Benchmark/VxSort.Benchmark.csproj
  src/Raven.Server/Documents/Handlers/Debugging/DatabaseDebugInfoPackageHandler.cs
  src/Raven.Server/Documents/Handlers/Debugging/ServerWideDebugInfoPackageHandler.cs
  src/Raven.Server/Documents/Handlers/Debugging/StorageHandler.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Server/ServerWide/LocalEndpointClient.cs
  test/BenchmarkTests/BenchmarkTests.csproj
  test/EmbeddedTests/EmbeddedTests.csproj
  test/FastTests/FastTests.csproj
  test/FastTests/Server/Documents/Indexing/RavenLinqOptimizerTests.cs
  test/InterversionTests/InterversionTests.csproj
  test/LicenseTests/LicenseTests.csproj
  test/RachisTests/RachisTests.csproj
  test/SlowTests/Authentication/AuthenticationDebugPackageInfoTests.cs
  test/SlowTests/Server/Documents/Indexing/IndexMerging.cs
  test/SlowTests/SlowTests.csproj
  test/StressTests/StressTests.csproj
  tools/Raven.Debug/Raven.Debug.csproj
  tools/Raven.Migrator/Raven.Migrator.csproj
  tools/rvn/rvn.csproj
Labels: v5.4

#15927 RavenDB-19886: add RetryFact
  test/SlowTests/Authentication/AuthenticationLetsEncryptTests.cs
Labels: v5.2

#15932 RavenDB-18009 Database list view - shard wide view
  src/Raven.Studio/typescript/commands/commandBase.ts
  src/Raven.Studio/typescript/commands/database/index/togglePauseIndexingCommand.ts
  src/Raven.Studio/typescript/components/common/PopoverWithHover.tsx
  src/Raven.Studio/typescript/components/common/shell/databasesSlice.ts
  src/Raven.Studio/typescript/components/models/databases.d.ts
  src/Raven.Studio/typescript/components/pages/database/indexes/list/useIndexesPage.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/DatabasesPage.spec.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/DatabasesPage.stories.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/DatabasesPage.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/DatabaseDistribution.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/DatabasePanel.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/ValidDatabasePropertiesPanel.tsx
  src/Raven.Studio/typescript/components/services/IndexesService.ts
  src/Raven.Studio/typescript/test/mocks/services/MockDatabasesService.ts
  src/Raven.Studio/typescript/viewmodels/resources/disableIndexingToggleConfirm.ts
  src/Raven.Studio/wwwroot/App/views/resources/disableIndexingToggleConfirm.html
Labels: v6.0, Studio

#15931 RavenDB-20035 Handle includes correctly when property value is null
  src/Raven.Server/Utils/IncludeUtil.cs
  test/SlowTests/Sharding/Issues/RavenDB_20035.cs
Labels: v6.0

#15934 RavenDB-7070 fixing test after NuGet package upgrade
  test/SlowTests/Issues/RavenDB_5051.cs
  test/Tests.Infrastructure/RavenTestHelper.cs
Labels: v5.2

#15939 RavenDB-19726 Add endpoint to get MicrosoftLogs state
  src/Raven.Server/Documents/Handlers/Admin/AdminLogsHandler.cs
  src/Raven.Server/Utils/MicrosoftLogging/MicrosoftLoggingProvider.cs
Labels: v5.2

#15940 5.2 to 5.4 merge
  .github/workflows/studioLabel.yml
  .github/workflows/versionLabel.yml
  src/Raven.Server/Documents/ETL/EtlProcess.cs
  src/Raven.Server/Documents/Handlers/Admin/AdminLogsHandler.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxIndexReadOperation.cs
  src/Raven.Server/Documents/PeriodicBackup/BackupUploader.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
  src/Raven.Server/Documents/Replication/IncomingReplicationHandler.cs
  src/Raven.Server/Documents/Replication/OutgoingReplicationHandler.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/Documents/TransactionOperationsMerger.cs
  src/Raven.Server/Rachis/Candidate.cs
  src/Raven.Server/Rachis/CandidateAmbassador.cs
  src/Raven.Server/Rachis/Elector.cs
  src/Raven.Server/Rachis/Follower.cs
  src/Raven.Server/Rachis/FollowerAmbassador.cs
  src/Raven.Server/Rachis/Leader.cs
  src/Raven.Server/RavenServer.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterMaintenanceSupervisor.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterMaintenanceWorker.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterObserver.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Utils/Metrics/MetricsScheduler.cs
  src/Raven.Server/Utils/MicrosoftLogging/MicrosoftLoggingProvider.cs
  src/Raven.Server/Utils/PoolOfThreads.cs
  src/Raven.Server/Utils/ThreadsUsage.cs
  src/Raven.Server/Web/System/OngoingTasksHandler.cs
  src/Sparrow.Server/Utils/TaskExecutor.cs
  src/Sparrow.Server/Utils/ThreadNames.cs
  src/Sparrow/Logging/LoggingSource.cs
  src/Voron/GlobalFlushingBehavior.cs
  src/Voron/GlobalPrefetchingBehavior.cs
  test/FastTests/Server/ThreadUsageTests.cs
  test/FastTests/Voron/CompactTreeTests.cs
  test/SlowTests/Authentication/AuthenticationLetsEncryptTests.cs
  test/SlowTests/Issues/RavenDB_5051.cs
Labels: v5.4

#15920 RavenDB-15601 Additional option to collect debug-info
  src/Raven.Server/Documents/Handlers/Debugging/ServerWideDebugInfoPackageHandler.cs
Labels: v5.2

#15952 RavenDB-20058: HOPE encoder was not properly building optimized dictionaries.
  src/Voron/Data/CompactTrees/CompactTree.RandomBranchKeyScanner.cs
  src/Voron/Data/CompactTrees/CompactTree.cs
Labels: Corax, v5.4

#15948 RavenDB-20018 normalized the usage of cancellation tokens
  src/Raven.Server/Documents/Handlers/Admin/RachisAdminHandler.cs
  src/Raven.Server/Documents/Handlers/Batches/AbstractBatchCommandReader.cs
  src/Raven.Server/Documents/Handlers/Batches/DatabaseBatchCommandsReader.cs
  src/Raven.Server/Documents/Handlers/IndexHandler.cs
  src/Raven.Server/Documents/Handlers/Processors/Batches/AbstractBatchHandlerProcessorForBulkDocs.cs
  src/Raven.Server/Documents/Handlers/Processors/Collections/CollectionsHandlerProcessorForGetCollectionDocuments.cs
  src/Raven.Server/Documents/Handlers/Processors/Queries/AbstractQueriesHandlerProcessorForGet.cs
  src/Raven.Server/Documents/Handlers/Processors/Rachis/AbstractRachisHandlerProcessorForWaitForIndexNotifications.cs
  src/Raven.Server/Documents/Handlers/Processors/Rachis/RachisHandlerProcessorForWaitForIndexNotifications.cs
  src/Raven.Server/Documents/Handlers/Processors/Streaming/AbstractStreamingHandlerProcessorForGetDocs.cs
  src/Raven.Server/Documents/Handlers/Processors/Streaming/StreamingHandlerProcessorForGetDocs.cs
  src/Raven.Server/Documents/Sharding/Handlers/Batches/ShardedBatchCommandsReader.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Collections/ShardedCollectionsHandlerProcessorForGetCollectionDocuments.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Rachis/ShardedRachisHandlerProcessorForWaitForIndexNotifications.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Streaming/ShardedStreamingHandlerProcessorForGetDocs.cs
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
Labels: v6.0

#15949 RavenDB-19979 added TotalSwapUsage to the MemoryUsagePayload and MachineResources
  src/Raven.Server/Dashboard/Cluster/Notifications/MemoryUsageNotificationSender.cs
  src/Raven.Server/Dashboard/Cluster/Notifications/MemoryUsagePayload.cs
  src/Raven.Server/Dashboard/MachineResources.cs
  src/Raven.Server/Dashboard/MachineResourcesNotificationSender.cs
Labels: v5.4

#15943 RavenDB-20056 `Bm25Relevance` as class to avoid storing managed function pointer in unmanaged memory.
  src/Corax/Queries/MultiTermMatch.cs
  src/Corax/Queries/TermMatch.cs
  src/Corax/Utils/Bm25Relevance.cs
  test/FastTests/Corax/Ranking/RankingFunctionTests.cs
Labels: Corax, v5.4

#15937 RavenDB-19587 Create new splash screen for v6.0 in studio (improvements)
  src/Raven.Studio/wwwroot/Content/css/splash-screen.less
  src/Raven.Studio/wwwroot/Content/img/splash-screen-ravendb-logo.svg
  src/Raven.Studio/wwwroot/index.html
Labels: v6.0, Studio

#15962 RavenDB-18888 Provide possibility to define UID:GID of user created during .deb package post-inst
  scripts/linux/pkg/deb/assets/ravendb/debian/ravendb.postinst
Labels: v5.2

#15968 RavenDB-20061 Check if user/group exists already
  scripts/linux/pkg/deb/assets/ravendb/debian/ravendb.postinst
Labels: v5.2

#15969 RavenDB-19843 Set default value of order by ticks when field contains dates to false
  src/Raven.Server/Config/Categories/IndexingConfiguration.cs
  test/SlowTests/Issues/RavenDB-19843.cs
Labels: v5.4

#15967 RavenDB-19686 - Enahnce Database Record Validation on Database Put when Sharding configuration is invalid
  src/Raven.Server/Web/System/DatabaseHelper.cs
Labels: v6.0

#15973 5.2 to 5.4 merge
  scripts/linux/pkg/deb/assets/build.sh
  scripts/linux/pkg/deb/assets/ravendb/debian/ravendb.postinst
  src/Raven.Server/Documents/Handlers/Debugging/ServerWideDebugInfoPackageHandler.cs
Labels: v5.4

#15974 5.4 to 6.0 merge
  scripts/linux/pkg/deb/assets/build.sh
  scripts/linux/pkg/deb/assets/ravendb/debian/ravendb.postinst
  src/Corax/Queries/MultiTermMatch.cs
  src/Corax/Queries/TermMatch.cs
  src/Corax/Utils/Bm25Relevance.cs
  src/Raven.Server/Config/Categories/IndexingConfiguration.cs
  src/Raven.Server/Dashboard/Cluster/Notifications/MemoryUsageNotificationSender.cs
  src/Raven.Server/Dashboard/Cluster/Notifications/MemoryUsagePayload.cs
  src/Raven.Server/Dashboard/MachineResources.cs
  src/Raven.Server/Documents/Handlers/Admin/Processors/Indexes/AbstractAdminIndexHandlerProcessorForPut.cs
  src/Raven.Server/Documents/Handlers/Debugging/ServerWideDebugInfoPackageHandler.cs
  src/Raven.Server/Documents/Handlers/DocumentHandler.cs
  src/Raven.Server/Documents/Indexes/Errors/FaultyInMemoryIndex.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreSnapshotTask.cs
  src/Raven.Server/ServerWide/Commands/Indexes/PutIndexesCommand.cs
  src/Raven.Server/Utils/Cpu/CpuHelper.cs
  src/Raven.Server/Utils/Cpu/CpuUsageCalculator.cs
  src/Raven.Server/Utils/Cpu/CpuUsageExtensionPoint.cs
  src/Raven.Server/Utils/ThreadsUsage.cs
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
  src/Voron/Data/CompactTrees/CompactTree.RandomBranchKeyScanner.cs
  src/Voron/Data/CompactTrees/CompactTree.cs
  test/FastTests/Corax/Ranking/RankingFunctionTests.cs
  test/SlowTests/Corax/IndexBackwardCompatibilityAndPersistence.cs
  test/SlowTests/Issues/RavenDB-19101.cs
  test/SlowTests/Issues/RavenDB-19843.cs
Labels: v6.0

#15975 RavenDB-19843 Removed unnecessary assert in test and updated configuration option description
  src/Raven.Server/Config/Categories/IndexingConfiguration.cs
  test/SlowTests/Issues/RavenDB-19843.cs
Labels: v5.4

#15956 RavenDB-19205 Increase precision of `TimeOnly` deserialization (.NET7 and above only).
  test/EmbeddedTests/Issues/RavenDB_19205.cs
  test/SlowTests/Issues/RavenDB-19205.cs
Labels: v5.4

#15985 5.4 to 6.0 merge
  src/Raven.Server/Config/Categories/IndexingConfiguration.cs
  src/Sparrow/Json/LazyStringParser.cs
  test/EmbeddedTests/Issues/RavenDB_19205.cs
  test/SlowTests/Issues/RavenDB-19843.cs
Labels: v6.0

#15991 RavenDB-20023 Wait of the StartBucketMigration command to be committed.
  src/Raven.Server/Documents/Sharding/Handlers/ReshardingHandler.cs
Labels: v6.0

#15984 RavenDB-19243 Sort by score when boosting is involved when Corax is search engine.
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxQueryBuilder.cs
  test/FastTests/Corax/RavenIntegration.cs
Labels: Corax, v5.4

#15992 RavenDB-20082 add more debug info to the failed test CanMoveOneBucket
  test/SlowTests/Sharding/Cluster/ReshardingTests.cs
Labels: v6.0

#15996 RavenDB-19828 Modal scroll fixes
  src/Raven.Studio/wwwroot/Content/css/bootstrap/modals.less
  src/Raven.Studio/wwwroot/Content/css/pages/etl.less
Labels: v6.0, Studio

#15994 RavenDB-20068 Fix query settings positioning
  src/Raven.Studio/wwwroot/App/views/database/query/query.html
Labels: v6.0, Studio

#15946 RavenDB-19205 AutoIndex will use ticks for `DateOnly` and `TimeOnly`.
  src/Raven.Server/Json/BlittableJsonTraverserHelper.cs
  src/Raven.Server/Utils/TypeConverter.cs
  test/SlowTests/Issues/RavenDB-19205.cs
Labels: v6.0

#15950 RavenDB-19943 - SlowTests.Issues.RavenDB_19545.RemovingTimeSeriesEntr…
  test/SlowTests/Issues/RavenDB_19545.cs
Labels: v5.2

#16000 RavenDB-20041 Explain that Document Defaults override the Conflicting Document Defaults
  src/Raven.Studio/typescript/viewmodels/database/settings/revisions.ts
Labels: v5.2, Studio

#16002 5.2 to 5.4 merge
  src/Raven.Client/Json/Serialization/NewtonsoftJson/DefaultRavenSerializationBinder.cs
  src/Raven.Client/Json/Serialization/NewtonsoftJson/NewtonsoftJsonSerializationConventions.cs
  src/Raven.Studio/typescript/commands/maintenance/disableAdminLogsMicrosoftCommand.ts
  src/Raven.Studio/typescript/commands/maintenance/enableAdminLogsMicrosoftCommand.ts
  src/Raven.Studio/typescript/commands/maintenance/getAdminLogsMicrosoftConfigurationCommand.ts
  src/Raven.Studio/typescript/commands/maintenance/getAdminLogsMicrosoftStateCommand.ts
  src/Raven.Studio/typescript/commands/maintenance/saveAdminLogsMicrosoftConfigurationCommand.ts
  src/Raven.Studio/typescript/common/bindingHelpers/aceEditorBindingHandler.ts
  src/Raven.Studio/typescript/viewmodels/database/settings/revisions.ts
  src/Raven.Studio/typescript/viewmodels/manage/adminLogs.ts
  src/Raven.Studio/typescript/viewmodels/manage/configureMicrosoftLogsDialog.ts
  src/Raven.Studio/wwwroot/App/views/manage/adminLogs.html
  src/Raven.Studio/wwwroot/App/views/manage/configureMicrosoftLogsDialog.html
  test/SlowTests/Issues/RavenDB_19545.cs
  test/SlowTests/Issues/RavenDB_20070.cs
Labels: v5.4, Studio

#15998 RavenDB-19590 Disabled not supported import for sharded database
  src/Raven.Studio/wwwroot/App/views/database/tasks/importCollectionFromCsv.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/importDatabaseFromSql.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/migrateDatabase.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/migrateRavenDbDatabase.html
Labels: v6.0, Studio

#16003 5.4 to 6.0 merge
  src/Raven.Client/Json/Serialization/NewtonsoftJson/DefaultRavenSerializationBinder.cs
  src/Raven.Client/Json/Serialization/NewtonsoftJson/NewtonsoftJsonSerializationConventions.cs
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxQueryBuilder.cs
  src/Raven.Studio/typescript/commands/maintenance/disableAdminLogsMicrosoftCommand.ts
  src/Raven.Studio/typescript/commands/maintenance/enableAdminLogsMicrosoftCommand.ts
  src/Raven.Studio/typescript/commands/maintenance/getAdminLogsMicrosoftConfigurationCommand.ts
  src/Raven.Studio/typescript/commands/maintenance/getAdminLogsMicrosoftStateCommand.ts
  src/Raven.Studio/typescript/commands/maintenance/saveAdminLogsMicrosoftConfigurationCommand.ts
  src/Raven.Studio/typescript/common/bindingHelpers/aceEditorBindingHandler.ts
  src/Raven.Studio/typescript/viewmodels/database/settings/revisions.ts
  src/Raven.Studio/typescript/viewmodels/manage/adminLogs.ts
  src/Raven.Studio/typescript/viewmodels/manage/configureMicrosoftLogsDialog.ts
  src/Raven.Studio/wwwroot/App/views/manage/adminLogs.html
  src/Raven.Studio/wwwroot/App/views/manage/configureMicrosoftLogsDialog.html
  test/FastTests/Corax/RavenIntegration.cs
  test/SlowTests/Issues/RavenDB_19545.cs
  test/SlowTests/Issues/RavenDB_20070.cs
Labels: v6.0, Studio

#15999 RavenDB-19337 Use string as property key in CounterEntryObjectInstance and TimeSeriesSegmentObjectInstance
  src/Raven.Server/Documents/Indexes/Static/Counters/CounterEntryObjectInstance.cs
  src/Raven.Server/Documents/Indexes/Static/TimeSeries/TimeSeriesSegmentObjectInstance.cs
Labels: v6.0

#16014 RavenDB-20088 Fix main menu regression
  src/Raven.Studio/wwwroot/Content/css/_bs5.scss
  src/Raven.Studio/wwwroot/Content/css/bootstrap/variables-body.less
  src/Raven.Studio/wwwroot/Content/css/styles-common-scoped.less
  src/Raven.Studio/wwwroot/Content/css/themes/blue-theme-variables-override.less
  src/Raven.Studio/wwwroot/Content/css/themes/light-theme-variables-override.less
  src/Raven.Studio/wwwroot/Content/scss/_colors.scss
  src/Raven.Studio/wwwroot/Content/scss/_custom-properties.scss
  src/Raven.Studio/wwwroot/Content/scss/_main-menu.scss
Labels: v6.0, Studio

#15987 RavenDB-20027 - Sharding - Handlers - Create endpoint to call ShardedPeriodicDocumentsMigrator.ExecuteMoveDocuments directly
  src/Raven.Server/Documents/Handlers/Admin/AdminShardingHandler.cs
  src/Raven.Server/Documents/Sharding/Handlers/Admin/ShardedAdminShardingHandler.cs
  test/SlowTests/Sharding/BucketMigration/PeriodicDocumentsMigrationTests.cs
Labels: v6.0

#16007 RavenDB-19984 Fix for getting collection name | Adding new functionality for IndexMerger.
  src/Raven.Server/Documents/Indexes/IndexMerging/IndexData.cs
  src/Raven.Server/Documents/Indexes/IndexMerging/IndexMerger.cs
  src/Raven.Server/Documents/Indexes/IndexMerging/IndexVisitor.cs
  test/SlowTests/Server/Documents/Indexing/IndexMerging.cs
Labels: v5.4

#15928 RDBCL-2590 - Backups stopped working for one of the DBs due to replic…
  src/Raven.Server/Documents/Replication/IncomingReplicationHandler.cs
  src/Raven.Server/Documents/Replication/OutgoingReplicationHandler.cs
Labels: v5.4

#16018 RavenDB-18009 Database list view - shard wide view
  src/Raven.Studio/typescript/components/common/shell/databasesSlice.ts
  src/Raven.Studio/typescript/components/hooks/useClusterTopologyManager.ts
  src/Raven.Studio/typescript/components/models/databases.d.ts
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexesPage.stories.tsx
  src/Raven.Studio/typescript/components/pages/database/status/statistics/StatisticsPage.spec.tsx
  src/Raven.Studio/typescript/components/pages/database/tasks/backups/BackupsPage.stories.tsx
  src/Raven.Studio/typescript/components/pages/database/tasks/list/OngoingTasksPage.stories.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/DatabasesPage.spec.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/DatabasesPage.stories.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/DatabasesPage.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/DatabaseDistribution.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/DatabasePanel.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/DatabasesCounter.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/DatabasesFilter.tsx
  src/Raven.Studio/typescript/components/pages/resources/manageDatabaseGroup/ManageDatabaseGroupPage.stories.tsx
  src/Raven.Studio/typescript/components/utils/DatabaseUtils.ts
  src/Raven.Studio/typescript/test/mocks/store/MockAccessManager.ts
  src/Raven.Studio/typescript/test/mocks/store/MockStore.ts
Labels: v6.0, Studio

#15945 RavenDB-20022 Add the /setup/alive to the ping endpoint
  src/Raven.Server/Documents/Handlers/Debugging/NodeDebugHandler.cs
Labels: v5.4

#16010 RavenDB-20063 - Inter-version testing between 5.4 & 6.0 non-sharded
  test/InterversionTests/MixedClusterTests.cs
  test/InterversionTests/ReplicationTests.cs
  test/InterversionTests/SmugglerTests.cs
  test/Tests.Infrastructure/InterversionTest/UpgradeTestSuit.cs
Labels: v6.0

#15995 RavenDB-19589 Indicate cluster node and shard (if sharded) in exported file names
  src/Raven.Studio/typescript/components/utils/DatabaseUtils.spec.ts
  src/Raven.Studio/typescript/components/utils/DatabaseUtils.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexPerformance.ts
  src/Raven.Studio/typescript/viewmodels/database/status/ioStats.ts
  src/Raven.Studio/typescript/viewmodels/database/status/ongoingTasksStats.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editReplicationHubTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/exportDatabase.ts
Labels: v6.0, Studio

#16023 RavenDB-19992: Allocations optimization
  src/Voron/Data/CompactTrees/CompactPageFlags.cs
  src/Voron/Data/CompactTrees/CompactPageHeader.cs
  src/Voron/Data/CompactTrees/CompactTree.Debug.cs
  src/Voron/Data/CompactTrees/CompactTree.Iterator.cs
  src/Voron/Data/CompactTrees/CompactTree.RandomBranchKeyScanner.cs
  src/Voron/Data/CompactTrees/CompactTree.RandomIterator.cs
  src/Voron/Data/CompactTrees/CompactTree.cs
Labels: Corax, v5.4

#16021 RavenDB-20092 added convention test
  src/Raven.Server/Config/Categories/IndexingConfiguration.cs
  src/Raven.Server/Config/Categories/StorageConfiguration.cs
  src/Raven.Server/Storage/StorageSpaceMonitor.cs
  test/FastTests/Issues/RavenDB_20092.cs
Labels: v5.2

#16024 5.2 to 5.4 merge + updated to .NET 7.0.4
  .github/workflows/FastTests.yml
  .github/workflows/FastTestsARM.yml
  .github/workflows/studioLabel.yml
  bench/BulkInsert.Benchmark/BulkInsert.Benchmark.csproj
  bench/Indexing.Benchmark/Indexing.Benchmark.csproj
  bench/Micro.Benchmark/Micro.Benchmark.csproj
  bench/Regression.Benchmark/Regression.Benchmark.csproj
  bench/SubscriptionFailover.Benchmark/SubscriptionFailover.Benchmark.csproj
  bench/Subscriptions.Benchmark/Subscriptions.Benchmark.csproj
  bench/TimeSeries.Benchmark/TimeSeries.Benchmark.csproj
  bench/Voron.Benchmark/Voron.Benchmark.csproj
  src/Corax/Corax.csproj
  src/Raven.Client/Raven.Client.csproj
  src/Raven.Embedded/ServerOptions.cs
  src/Raven.Server/Config/Categories/IndexingConfiguration.cs
  src/Raven.Server/Config/Categories/StorageConfiguration.cs
  src/Raven.Server/Documents/PeriodicBackup/RavenFtpClient.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Server/Storage/StorageSpaceMonitor.cs
  src/Raven.Studio/Raven.Studio.csproj
  src/Sparrow.Server/Sparrow.Server.csproj
  src/Voron/Voron.csproj
  test/BenchmarkTests/BenchmarkTests.csproj
  test/EmbeddedTests/EmbeddedTests.csproj
  test/FastTests/FastTests.csproj
  test/FastTests/Issues/RavenDB_20092.cs
  test/InterversionTests/InterversionTests.csproj
  test/LicenseTests/LicenseTests.csproj
  test/RachisTests/RachisTests.csproj
  test/SlowTests/SlowTests.csproj
  test/StressTests/StressTests.csproj
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
  test/Tryouts/Tryouts.csproj
  tools/Raven.Debug/Raven.Debug.csproj
  tools/Raven.Migrator/Raven.Migrator.csproj
  tools/TypingsGenerator/TypingsGenerator.csproj
  tools/Voron.Dictionary.Generator/Voron.Dictionary.Generator.csproj
  tools/Voron.Recovery/Voron.Recovery.csproj
  tools/rvn/rvn.csproj
Labels: v5.4, Studio

#16026 RavenDB-20101 Ability to fine tune sharding deployment during db crea…
  src/Raven.Studio/typescript/models/resources/creation/databaseCreationModel.ts
  src/Raven.Studio/typescript/viewmodels/resources/createDatabase.ts
  src/Raven.Studio/typings/_studio/dto.d.ts
  src/Raven.Studio/wwwroot/App/views/resources/createDatabase.html
Labels: v6.0, Studio

#15983 RavenDB-19730 Querying performance / memory improvements
  src/Raven.Server/Documents/Commands/Streaming/PostQueryStreamCommand.cs
  src/Raven.Server/Documents/Handlers/Processors/Queries/AbstractQueriesHandlerProcessorForGet.cs
  src/Raven.Server/Documents/Queries/IndexQueryServerSide.cs
  src/Raven.Server/Documents/Sharding/Commands/Querying/AbstractShardedQueryCommand.cs
  src/Raven.Server/Documents/Sharding/Commands/Querying/ShardedQueryCommand.cs
  src/Raven.Server/Documents/Sharding/Executors/ShardExecutor.cs
  src/Raven.Server/Documents/Sharding/Queries/AbstractShardedQueryProcessor.cs
  src/Raven.Server/Documents/Sharding/Queries/Facets/ShardedFacetedQueryProcessor.cs
  src/Raven.Server/Documents/Sharding/Queries/IndexEntries/ShardedIndexEntriesQueryProcessor.cs
  src/Raven.Server/Documents/Sharding/Queries/ShardedQueryProcessorBase.cs
  src/Raven.Server/Documents/Sharding/Queries/ShardedQueryStreamProcessor.cs
  src/Raven.Server/Documents/Sharding/Queries/Suggestions/ShardedSuggestionQueryProcessor.cs
  src/Sparrow/Json/BlittableJsonReaderBase.cs
  src/Sparrow/Json/BlittableJsonReaderObject.cs
Labels: v6.0

#16029 RavenDB-19836 Uncaught TypeError: Cannot read properties of null (rea…
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexPerformance.ts
Labels: v5.4, Studio

#16030 RavenDB-20108 Stats of a specific shard throws
  src/Raven.Studio/typescript/components/common/shell/databasesSlice.ts
  src/Raven.Studio/typescript/components/pages/database/status/statistics/logic/statisticsSlice.ts
Labels: v6.0, Studio

#15724 RavenDB-18881: throw on revisions subscription on sharded database
  src/Raven.Server/Documents/Handlers/Processors/Subscriptions/AbstractSubscriptionsHandlerProcessorForPostSubscription.cs
  src/Raven.Server/Documents/Handlers/Processors/Subscriptions/AbstractSubscriptionsHandlerProcessorForPutSubscription.cs
  src/Raven.Server/Documents/Handlers/Processors/Subscriptions/AbstractSubscriptionsHandlerProcessorForTrySubscription.cs
  src/Raven.Server/Documents/Handlers/Processors/Subscriptions/SubscriptionsHandlerProcessorForPostSubscription.cs
  src/Raven.Server/Documents/Handlers/Processors/Subscriptions/SubscriptionsHandlerProcessorForPutSubscription.cs
  src/Raven.Server/Documents/Handlers/SubscriptionsHandler.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Subscriptions/ShardedSubscriptionsHandlerProcessorForPostSubscription.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Subscriptions/ShardedSubscriptionsHandlerProcessorForPutSubscription.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Subscriptions/ShardedSubscriptionsHandlerProcessorForTrySubscription.cs
  src/Raven.Server/Documents/Sharding/Handlers/ShardedSubscriptionsHandler.cs
Labels: v6.0

#16032 RavenDB-20105 Running index does not have a status icon
  src/Raven.Studio/typescript/components/common/ProgressCircle.scss
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexDistribution.tsx
Labels: v6.0, Studio

#16036 RavenDB-19992: Persistent Dictionaries improvements
  src/Voron/Data/CompactTrees/CompactTree.Dictionaries.cs
  src/Voron/Data/CompactTrees/CompactTree.cs
  src/Voron/Data/CompactTrees/PersistentDictionary.cs
  src/Voron/Data/CompactTrees/PersistentDictionaryLocator.cs
  src/Voron/StorageEnvironment.cs
Labels: Corax, v5.4

#16028 RavenDB-20086 Review of encodings/decoding in `IndexWriter`
  src/Corax/IndexWriter.cs
  src/Corax/Utils/EntryIdEncodings.cs
  test/FastTests/Corax/BoostingQuery.cs
Labels: Corax, v5.4

#16038 RavenDB-20075 Add ability to scroll views in storybook
  src/Raven.Studio/typescript/components/common/RichPanel.scss
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexesPage.stories.tsx
  src/Raven.Studio/typescript/components/pages/database/status/statistics/StatisticsPage.stories.tsx
  src/Raven.Studio/typescript/components/pages/database/tasks/backups/BackupsPage.stories.tsx
  src/Raven.Studio/typescript/components/pages/database/tasks/list/OngoingTasksPage.stories.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/DatabasesPage.stories.tsx
  src/Raven.Studio/typescript/components/pages/resources/manageDatabaseGroup/ManageDatabaseGroupPage.stories.tsx
  src/Raven.Studio/typescript/test/storybookTestUtils.tsx
Labels: v6.0, Studio

#16034 RavenDB-20030 Add a new orchestrator to the database group popup
  src/Raven.Studio/wwwroot/App/views/shell/registration.html
  src/Raven.Studio/wwwroot/Content/css/modals.less
  src/Raven.Studio/wwwroot/Content/scss/_sizes.scss
Labels: v6.0, Studio

#16027 RavenDB-20036 Add License Id to all exception and logs in RenewLetsEncryptCertificate method
  src/Raven.Server/RavenServer.cs
Labels: v5.2

#16043 RavenDB-20120 Clicking on the alerts on a non-orchestrator node resul…
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/ValidDatabasePropertiesPanel.tsx
Labels: v6.0, Studio

#16045 RavenDB-20121 reduce number of alerts during resharding
  src/Raven.Server/Documents/Replication/Outgoing/OutgoingMigrationReplicationHandler.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/Documents/Replication/ShardReplicationLoader.cs
  src/Raven.Server/Documents/Replication/Stats/IncomingConnectionInfo.cs
  src/Raven.Server/Documents/Sharding/ShardedDocumentDatabase.cs
Labels: v6.0

#16050 RavenDB-15357 fix failing test
  src/Raven.Server/Documents/TcpHandlers/SubscriptionConnection.cs
Labels: v5.4

#16049 RavenDB-20111 fix a leak on TcpConnectionOptions
  src/Raven.Server/Documents/Sharding/Handlers/ShardedOutgoingReplicationHandler.cs
  src/Raven.Server/Documents/Sharding/ShardedDatabaseContext.ReplicationLoader.cs
Labels: v6.0

#16046 RavenDB-20028 Revamp currently selected database in database list
  src/Raven.Studio/typescript/components/common/RichPanel.scss
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/DatabasePanel.tsx
  src/Raven.Studio/wwwroot/Content/css/bootstrap/variables-header.less
  src/Raven.Studio/wwwroot/Content/css/themes/light-theme-colors-override.less
  src/Raven.Studio/wwwroot/Content/scss/_colors.scss
Labels: v6.0, Studio

#16047 RavenDB-20029 Temporary patch to reduce errors on system with only cgroup2
  src/Sparrow.Server/Platform/Posix/KernelVirtualFileSystemUtils.cs
Labels: v5.2

#16054 RavenDB-20130 - change intervesion test from 5.2 to 5.4
  test/InterversionTests/MixedClusterTests.cs
Labels: v6.0

#16048 RavenDB-20135 handle shard proxy
  src/Raven.Server/Documents/Handlers/Processors/AbstractHandlerProxyProcessor.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/OngoingTasks/ShardedOngoingTasksHandlerProcessorForGetOngoingTasks.cs
Labels: v6.0

#16057 RavenDB-20146 Fix Server-Wide Tasks modal
  src/Raven.Studio/wwwroot/App/views/manage/createServerWideTask.html
Labels: v6.0, Studio

#16061 RavenDB-20132 Corax won't be experimental in v6.0
  src/Raven.Studio/typescript/viewmodels/database/indexes/editIndex.ts
  src/Raven.Studio/wwwroot/App/views/database/indexes/editIndex.html
  src/Raven.Studio/wwwroot/App/views/wizard/security.html
Labels: v6.0, Studio

#16062 RavenDB-19611 Sharding - ETL - Queues - disable unsupported tasks for…
  src/Raven.Studio/typescript/viewmodels/database/tasks/createOngoingTask.ts
  src/Raven.Studio/wwwroot/App/views/database/tasks/createOngoingTask.html
  src/Raven.Studio/wwwroot/Content/css/pages/ongoing-tasks.less
Labels: v6.0, Studio

#16058 RavenDB-20132 Corax is no longer experimental
  src/Raven.Server/Config/RavenConfiguration.cs
  src/Raven.Server/Documents/Indexes/Index.cs
Labels: v6.0

#16056 RavenDB-20025 wait for cluster to be not passive
  src/Raven.Server/ServerWide/ServerStore.cs
Labels: v6.0

#16065 RavenDB-20007 Reduce main menu collections list padding
  src/Raven.Studio/wwwroot/Content/scss/_main-menu.scss
Labels: v6.0, Studio

#16067 RavenDB-20132 removing unnecessary tests
  test/SlowTests/Corax/CanUseCoraxOnlyAsExperimental.cs
Labels: v6.0

#16066 5.2 to 5.4 merge
  src/Sparrow.Server/ByteString.cs
  src/Sparrow.Server/Platform/Posix/KernelVirtualFileSystemUtils.cs
  src/Voron/Data/Tables/Table.cs
Labels: v5.4

#16074 5.2 to 5.4 merge
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/virtualOperations/virtualUpdateByQueryDetails.ts
  src/Sparrow/Utils/MemoryUtils.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
Labels: v5.4

#16071 RavenDB-20170 fix NRE during importing of old dump
  src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
  test/SlowTests/Smuggler/SmugglerApiTests.cs
Labels: v5.4

#16077 RavenDB-19979 Show current SWAP usage and total
  src/Raven.Studio/typescript/models/resources/widgets/memoryUsage.ts
  src/Raven.Studio/wwwroot/App/views/resources/widgets/memoryUsageWidget.html
Labels: v5.4, Studio

#16076 RavenDB-20025 do not spam UpdateServerPublishedUrlsCommand in mixed cluster
  src/Raven.Server/ServerWide/ServerStore.cs
Labels: v6.0

#16078 5.4 to 6.0 merge
  bench/Voron.Benchmark/Corax/CoraxEntryIdEncodings.cs
  src/Corax/IndexWriter.cs
  src/Corax/Utils/EntryIdEncodings.cs
  src/Raven.Client/Documents/Smuggler/SmugglerProgressBase.cs
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  src/Raven.Server/RavenServer.cs
  src/Raven.Server/Smuggler/Documents/Actions/AbstractDatabaseCompareExchangeActions.cs
  src/Raven.Server/Smuggler/Documents/Actions/DatabaseRecordActions.cs
  src/Raven.Server/Smuggler/Documents/Data/ISmugglerDestination.cs
  src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
  src/Raven.Server/Smuggler/Documents/MultiShardedDestination.cs
  src/Raven.Server/Smuggler/Documents/SmugglerBase.cs
  src/Raven.Server/Smuggler/Documents/StreamDestination.cs
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/virtualOperations/virtualUpdateByQueryDetails.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexPerformance.ts
  src/Raven.Studio/typescript/viewmodels/shell.ts
  src/Sparrow.Server/ByteString.cs
  src/Sparrow.Server/Compression/Encoder3Gram.cs
  src/Sparrow.Server/Compression/HopeEncoder.cs
  src/Sparrow.Server/Platform/Posix/KernelVirtualFileSystemUtils.cs
  src/Sparrow/Utils/MemoryUtils.cs
  src/Voron/Data/CompactTrees/CompactKey.cs
  src/Voron/Data/CompactTrees/CompactKeyCacheScope.cs
  src/Voron/Data/CompactTrees/CompactTree.Dictionaries.cs
  src/Voron/Data/CompactTrees/CompactTree.cs
  src/Voron/Data/CompactTrees/PersistentDictionary.cs
  src/Voron/Data/CompactTrees/PersistentDictionaryLocator.cs
  src/Voron/Data/Tables/Table.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/Impl/LowLevelTransaction.cs
  src/Voron/StorageEnvironment.cs
  test/FastTests/Corax/BoostingQuery.cs
  test/FastTests/Corax/Ranking/QuantizationTest.cs
  test/SlowTests/Smuggler/SmugglerApiTests.cs
Labels: v6.0

#16080 RavenDB-20175 fix theme bug in React components
  src/Raven.Studio/typescript/components/common/LocationDistribution.scss
  src/Raven.Studio/typescript/components/common/LocationSpecificDetails.scss
  src/Raven.Studio/wwwroot/Content/css/_bs5.scss
  src/Raven.Studio/wwwroot/Content/css/root.less
  src/Raven.Studio/wwwroot/Content/scss/_colors.scss
  src/Raven.Studio/wwwroot/Content/scss/_custom-properties.scss
  src/Raven.Studio/wwwroot/Content/scss/_main-menu.scss
  src/Raven.Studio/wwwroot/Content/scss/bs5variables.scss
Labels: v6.0, Studio

#16079 RavenDB-19637 Ctrl+Enter in document search bar to open a new tab
  src/Raven.Studio/typescript/common/shell/searchBox.ts
  src/Raven.Studio/wwwroot/App/views/shell.html
Labels: v5.4, Studio

#16084 RavenDB-19927 Creating an index with a configuration that is Not per-…
  src/Raven.Studio/typescript/models/database/index/configurationItem.ts
  src/Raven.Studio/wwwroot/App/views/database/indexes/editIndex.html
  src/Raven.Studio/wwwroot/Content/css/pages/edit-index.less
Labels: v5.2, Studio

#16081 RavenDB-20137 Lucene package update fixing internal field cache issue which resulted in returning invalid query results
  libs/Lucene.Net.3.0.54004.nupkg
  libs/Lucene.Net.3.0.54006.nupkg
  libs/Lucene.Net.Contrib.Spatial.NTS.3.0.54004.nupkg
  libs/Lucene.Net.Contrib.Spatial.NTS.3.0.54006.nupkg
  src/Raven.Server/Raven.Server.csproj
Labels: v5.4

#16090 5.2 to 5.4 merge
  src/Raven.Server/Documents/ETL/EtlTransformer.cs
  src/Raven.Server/Documents/Patch/JavaScriptUtils.cs
  src/Raven.Server/Documents/Patch/ScriptRunner.cs
  src/Raven.Server/Documents/Patch/ScriptRunnerCache.cs
  test/SlowTests/Issues/RavenDB_20059.cs
Labels: v5.4

#16099 RavenDB-19772 Sharding - Backup - Delay
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/smugglerDatabaseDetails.ts
Labels: v5.2, Studio

#16105 RavenDB-20000 Resetting index shows 'Up To Date' even when still in p…
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexDistribution.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexesStatsReducer.ts
  src/Raven.Studio/typescript/components/pages/database/indexes/list/useIndexesPage.tsx
Labels: v6.0, Studio

#16104 RavenDB-20190 race condition on databases page
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/ValidDatabasePropertiesPanel.tsx
Labels: v6.0, Studio

#16103 RavenDB-20188 6.0 theme should rotate the color scheme for cloud admins
  src/Raven.Studio/wwwroot/Content/css/root.less
  src/Raven.Studio/wwwroot/Content/css/styles-common-scoped.less
Labels: v6.0, Studio

#16102 RavenDB-20187 add thousands separator
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexDistribution.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexProgressTooltip.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/DatabaseDistribution.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/ValidDatabasePropertiesPanel.tsx
Labels: v6.0, Studio

#16094 RavenDB-20021 Revisions icon glitch
  src/Raven.Studio/wwwroot/Content/css/pages/documents-edit.less
  src/Raven.Studio/wwwroot/Content/css/styles-common-scoped.less
Labels: v6.0, Studio

#16093 RavenDB-18989 Collapse Menu button isn't visible
  src/Raven.Studio/wwwroot/Content/scss/_main-menu.scss
Labels: v6.0, Studio

#16095 RavenDB-20186 return appropriate number of indexes in /studio-tasks/databases endpoint
  src/Raven.Server/ServerWide/RawDatabaseRecord.cs
  src/Raven.Server/Web/System/Processors/Studio/StudioDatabasesHandlerForGetDatabases.cs
Labels: v6.0

#16106 RavenDB-20055 Cluster dashboard does not show time when hovering over…
  src/Raven.Studio/typescript/models/resources/clusterDashboard/lineChart.ts
  src/Raven.Studio/wwwroot/App/views/resources/clusterDashboard.html
Labels: v5.4, Studio

#16110 RavenDB-19883
  src/Raven.Studio/typescript/commands/database/debug/forceTombstonesCleanupCommand.ts
  src/Raven.Studio/typescript/commands/database/debug/getTombstonesStateCommand.ts
  src/Raven.Studio/typescript/common/shell/menu/items/settings.ts
  src/Raven.Studio/typescript/viewmodels/database/advanced/tombstonesState.ts
  src/Raven.Studio/wwwroot/App/views/database/advanced/tombstonesState.html
Labels: v6.0, Studio

#16013 RavenDB-15330 - Put raft commands with `DontCareId` in the history log as well
  src/Raven.Server/Rachis/RachisConsensus.cs
  test/SlowTests/Issues/RavenDB-15330.cs
Labels: v5.4

#16115 RavenDB-20209 Error opening ongoing tasks stats
  src/Raven.Studio/typescript/common/appUrl.ts
Labels: v6.0, Studio

#16112 RavenDB-19747 - block having a two digit shard number
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Web/System/ShardedAdminDatabaseHandler.cs
Labels: v6.0

#16111 RavenDB-20204 use the index delete controller to delete the index
  src/Raven.Server/Documents/Indexes/AbstractIndexDeleteController.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
Labels: v6.0

#16122 RavenDB-19762 - update Lucene
  libs/Lucene.Net.3.0.54006.nupkg
  libs/Lucene.Net.3.0.54007.nupkg
  libs/Lucene.Net.Contrib.Spatial.NTS.3.0.54006.nupkg
  libs/Lucene.Net.Contrib.Spatial.NTS.3.0.54007.nupkg
  src/Raven.Server/Raven.Server.csproj
Labels: v5.4

#16117 RavenDB-20208 npm update
  src/Raven.Studio/package-lock.json
  src/Raven.Studio/package.json
Labels: v6.0, Studio

#16129 RavenDB-20212 Cannot build deb package for Ubuntu 22.04/arm64- Unable…
  scripts/linux/pkg/deb/ubuntu_multiarch.Dockerfile
Labels: v5.2

#16127 RavenDB-19587 Create new splash screen for v6.0 in studio (improvements)
  src/Raven.Studio/typescript/components/common/SplashScreen.scss
  src/Raven.Studio/wwwroot/Content/css/splash-screen.less
  src/Raven.Studio/wwwroot/index.html
Labels: v6.0, Studio

#16133 RavenDB-20148 UI Regression - Databases view: db not woken up/nor sel…
  src/Raven.Studio/typescript/components/common/ButtonVariants.stories.tsx
  src/Raven.Studio/typescript/components/common/RichPanel.scss
  src/Raven.Studio/typescript/components/common/RichPanel.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/DatabasesPage.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/DatabasePanel.tsx
  src/Raven.Studio/wwwroot/Content/scss/_colors.scss
  src/Raven.Studio/wwwroot/Content/scss/_custom-properties.scss
Labels: v6.0, Studio

#15982 RavenDB-19482 Add alias to query when using ProjectInto with reserved keyword
  src/Raven.Client/Documents/Linq/RavenQueryProviderProcessor.cs
  test/SlowTests/Issues/RavenDB-19482.cs
Labels: v5.4

#16136 RavenDB-19886 always use the same URI for order finalization in LetsEncrypt
  src/Raven.Server/Commercial/LetsEncryptClient.cs
Labels: v5.2

#16138 RavenDB-20224 do not require nodeTag when /databases/*/indexes?namesOnly=true
  src/Raven.Server/Documents/Handlers/Processors/Indexes/AbstractIndexHandlerProcessorForGetAllNames.cs
  src/Raven.Server/Documents/Handlers/Processors/Indexes/IndexHandlerProcessorForGetAll.cs
  src/Raven.Server/Documents/Handlers/Processors/Indexes/IndexHandlerProcessorForGetAllNames.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Indexes/ShardedIndexHandlerProcessorForGetAllNames.cs
Labels: v6.0

#16146 5.2 to 5.4 merge
  src/Raven.Server/Commercial/LetsEncryptClient.cs
  src/Raven.Server/Config/Categories/DatabaseConfiguration.cs
  src/Raven.Server/Documents/ETL/ExtractedItem.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  test/SlowTests/Issues/RavenDB-20136.cs
  test/SlowTests/Issues/RavenDB_20206.cs
Labels: v5.4

#16147 RavenDB-20192 Prevent of infinite loop in the negotiation
  src/Raven.Server/Rachis/Follower.cs
  test/RachisTests/LogDivergenceTests.cs
  test/RachisTests/RavenDB_19654.cs
Labels: v5.4

#16150 merge 5.4 into 6.0
  src/Raven.Client/Documents/Linq/RavenQueryProviderProcessor.cs
  src/Raven.Client/Documents/Session/Operations/StreamOperation.cs
  src/Raven.Server/Commercial/LetsEncryptClient.cs
  src/Raven.Server/Config/Categories/DatabaseConfiguration.cs
  src/Raven.Server/Documents/AttachmentsStorage.cs
  src/Raven.Server/Documents/CompoundKeyHelper.cs
  src/Raven.Server/Documents/DocumentPutAction.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/DocumentsTransaction.cs
  src/Raven.Server/Documents/ETL/ExtractedItem.cs
  src/Raven.Server/Documents/Handlers/Processors/Streaming/AbstractStreamingHandlerProcessorForGetDocs.cs
  src/Raven.Server/Documents/Handlers/Processors/Streaming/StreamingHandlerProcessorForGetDocs.cs
  src/Raven.Server/Documents/Handlers/ReplicationHandler.cs
  src/Raven.Server/Documents/Handlers/Streaming/IStreamResultsWriter.cs
  src/Raven.Server/Documents/Handlers/Streaming/StreamJsonlResultsWriter.cs
  src/Raven.Server/Documents/Handlers/Streaming/StreamResultsWriter.cs
  src/Raven.Server/Documents/Replication/ConflictManager.cs
  src/Raven.Server/Documents/Replication/Incoming/IncomingReplicationHandler.cs
  src/Raven.Server/Documents/Replication/ReplicationItems/AttachmentReplicationItem.cs
  src/Raven.Server/Documents/Replication/ReplicationItems/AttachmentTombstoneReplicationItem.cs
  src/Raven.Server/Documents/Replication/ReplicationItems/CounterReplicationItem.cs
  src/Raven.Server/Documents/Replication/ReplicationItems/DocumentReplicationItem.cs
  src/Raven.Server/Documents/Replication/ReplicationItems/ReplicationBatchItem.cs
  src/Raven.Server/Documents/Replication/ReplicationItems/RevisionTombstoneReplicationItem.cs
  src/Raven.Server/Documents/Replication/ReplicationItems/TimeSeriesReplicationItem.cs
  src/Raven.Server/Documents/Replication/ReplicationItems/TombstoneReplicationItem.cs
  src/Raven.Server/Documents/Replication/ResolveConflictOnReplicationConfigurationChange.cs
  src/Raven.Server/Documents/Replication/Senders/ReplicationDocumentSenderBase.cs
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Documents/ShardedDocumentHandlerProcessorForGet.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Streaming/ShardedStreamingHandlerProcessorForGetDocs.cs
  src/Raven.Server/Rachis/Follower.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/RavenTransaction.cs
  src/Voron/Data/BTrees/Tree.Stream.cs
  test/RachisTests/LogDivergenceTests.cs
  test/RachisTests/RavenDB_19654.cs
  test/SlowTests/Client/Attachments/AttachmentsReplication.cs
  test/SlowTests/Client/Counters/CountersReplication.cs
  test/SlowTests/Client/TimeSeries/Replication/TimeSeriesReplicationTests.cs
  test/SlowTests/Issues/RavenDB-19482.cs
  test/SlowTests/Issues/RavenDB-20033.cs
  test/SlowTests/Issues/RavenDB-20136.cs
  test/SlowTests/Issues/RavenDB_19421_2.cs
  test/SlowTests/Issues/RavenDB_20206.cs
Labels: v6.0

#16085 RavenDB-20045 Update readmes for Windows docker images after ltsc2022 image is released
  docker/readme.md
Labels: v5.4

#16152 RavenDB-19664
  src/Raven.Client/Documents/Session/InMemoryDocumentSessionOperations.cs
Labels: v5.4
