Repository ravendb/ravendb, pull requests merged in 2023-12, with the labels that each got.

#17789 RavenDB-21653 : fix flaky test
  test/SlowTests/Issues/RavenDB_14006.cs
Labels: v5.4

#17786 RavenDB-21766 Fix z-index for test container info text
  src/Raven.Studio/wwwroot/App/views/database/tasks/editKafkaEtlTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editOlapEtlTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editRabbitMqEtlTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editRavenEtlTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editSqlEtlTask.html
  src/Raven.Studio/wwwroot/Content/css/styles-common.less
Labels: v5.4, Studio

#17780 RavenDB-17745 fix test
  src/Raven.Client/Documents/BulkInsert/BulkInsertOperation.cs
  src/Raven.Client/Util/StreamWithTimeout.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/Handlers/BulkInsertHandler.cs
  test/SlowTests/Issues/RavenDB-17745.cs
Labels: v5.4

#17795 RavenDB-21772 Tombstone cleaner can start only after the initialization of indexes
  src/Raven.Server/Documents/DocumentDatabase.cs
Labels: v5.4

#17797 5.4 to 6.0 merge
  .github/workflows/codeql-analysis.yml
  scripts/assets/run.sh
  scripts/linux/install-daemon.sh
  scripts/linux/pkg/deb/assets/ravendb/debian/ravendb.service
  scripts/linux/ravendb.service
  src/Raven.Client/Util/StreamWithTimeout.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Json/BlittableJsonTextWriterExtensions.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterObserver.cs
  src/Raven.Server/ServerWide/Maintenance/DatabaseTopologyUpdater.cs
  src/Raven.Studio/wwwroot/App/views/database/tasks/editKafkaEtlTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editOlapEtlTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editRabbitMqEtlTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editRavenEtlTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editSqlEtlTask.html
  src/Raven.Studio/wwwroot/Content/css/styles-common-scoped.less
  src/Sparrow.Server/Extensions/RavenDateTimeExtensions.cs
  test/SlowTests/Issues/RavenDB-17745.cs
  test/SlowTests/Issues/RavenDB_14006.cs
  test/SlowTests/Tests/Faceted/DynamicFacets.cs
  test/SlowTests/Tests/Suggestions/Suggestions.cs
  test/xunit.runner.CI.json
Labels: v6.0

#17799 RavenDB-7070 fixing tests after merge
  src/Raven.Server/Documents/Sharding/Operations/Queries/ShardedFacetedQueryOperation.cs
  src/Raven.Server/Documents/Sharding/Operations/Queries/ShardedSuggestionQueryOperation.cs
  test/SlowTests/Issues/RavenDB_14006.cs
Labels: v6.0

#17807 RavenDB-7070 fixed xUnit2020 warning
  test/FastTests/Issues/RavenDB-12926.cs
  test/FastTests/Issues/RavenDB_10765.cs
  test/FastTests/Server/Documents/Indexing/Auto/BasicAutoMapIndexing.cs
  test/FastTests/Server/Documents/TimeSeries/TimeSeriesRangeTests.cs
  test/FastTests/Sparrow/ChangeThreadPriorityTest.cs
  test/FastTests/Voron/ValidHeaders.cs
  test/RachisTests/AddNodeToClusterTests.cs
  test/RachisTests/CommandsTests.cs
  test/RachisTests/DatabaseCluster/ReplicationTests.cs
  test/RachisTests/ElectionTests.cs
  test/RachisTests/SubscriptionsFailover.cs
  test/SlowTests/Client/Subscriptions/ConcurrentSubscriptionsTests.cs
  test/SlowTests/Client/Subscriptions/LimitSubscriptionsConnectionsAmount.cs
  test/SlowTests/Client/Subscriptions/Subscriptions.cs
  test/SlowTests/Client/Subscriptions/SubscriptionsBasic.cs
  test/SlowTests/Cluster/NServiceBusCaseTest.cs
  test/SlowTests/Core/Session/Advanced.cs
  test/SlowTests/Issues/RavenDB-11836.cs
  test/SlowTests/Issues/RavenDB1229.cs
  test/SlowTests/Issues/RavenDB_15409.cs
  test/SlowTests/Issues/RavenDB_15538.cs
  test/SlowTests/Issues/RavenDB_19033.cs
  test/SlowTests/Issues/RavenDB_20416.cs
  test/SlowTests/Issues/RavenDB_8031.cs
  test/SlowTests/Rolling/RollingIndexesClusterTests.cs
  test/SlowTests/Server/Documents/ETL/Elasticsearch/ElasticSearchEtlTestBase.cs
  test/SlowTests/Server/Documents/ETL/Queue/QueueEtlTestBase.cs
  test/SlowTests/Server/Documents/QueueSink/QueueSinkTestBase.cs
  test/SlowTests/Server/NotificationCenter/HugeDocuments.cs
  test/SlowTests/Server/Replication/AutomaticConflictResolvingOnPut.cs
  test/SlowTests/Server/Replication/PullReplicationPreventDeletionsTests.cs
  test/SlowTests/Server/Replication/ReplicationCleanTombstones.cs
  test/SlowTests/Server/Replication/ReplicationOfConflicts.cs
  test/SlowTests/Sharding/BucketMigration/DocumentsMigrationTests.cs
  test/SlowTests/Sharding/Cluster/SubscriptionsWithReshardingTests.cs
  test/SlowTests/Sharding/Subscriptions/ShardedSubscriptionSlowTests.cs
  test/SlowTests/SparrowTests/MicrosoftLogTests.cs
  test/SlowTests/Voron/Issues/RavenDB_15912.cs
  test/SlowTests/Voron/LargeFixedSizeTrees.cs
  test/StressTests/Rachis/SubscriptionFailoverWithWaitingChainsStress.cs
  test/StressTests/Rachis/SubscriptionsFailoverStress.cs
  test/Tests.Infrastructure/RachisConsensusTestBase.cs
  test/Tests.Infrastructure/RavenTestBase.Backup.cs
  test/Tests.Infrastructure/RavenTestBase.TimeSeries.cs
  test/Tests.Infrastructure/ReplicationTestBase.cs
Labels: v6.0

#17809 RavenDB-21779 look into nested ConfigurationCategories when scanning properties
  src/Raven.Server/Config/Categories/IntegrationsConfiguration.cs
  src/Raven.Server/Config/Categories/MonitoringConfiguration.cs
  src/Raven.Server/Config/RavenConfiguration.cs
Labels: v5.4

#17814 5.4 to 6.0 merge
  src/Raven.Server/Documents/ETL/Providers/Queue/Kafka/KafkaEtl.cs
  src/Raven.Studio/package-lock.json
  test/StressTests/Corax/Bugs/PostingListTestsExtended.cs
Labels: v6.0

#17815 RavenDB-20934 : add debug info to flaky test
  test/SlowTests/Sharding/ETL/ShardedEtlFailoverTests.cs
Labels: v6.0

#17819 RavenDB-21791 flags field name for decimal values in full .NET Framework is 'flags' not '_flags'
  src/Sparrow/Utils/DecimalHelper.cs
  test/EmbeddedTests/BasicTests.cs
Labels: v5.4

#17825 RavenDB-19969 - StressTests.Client.TimeSeries.TimeSeriesStress.PatchTimestamp_IntegrationTest
  test/StressTests/Client/TimeSeries/TimeSeriesStress.cs
Labels: v5.4

#17821 RavenDB-15091 - add assert and message to test
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
Labels: v5.4

#17778 RavenDB-21715 Fix test DisableAutoMapReduceIndexClusterWideAndEnableA…
  test/SlowTests/Issues/RavenDB-20922.cs
Labels: v5.4

#17829 RavenDB-21792 Error when opening OLAP ETL view
  src/Raven.Studio/wwwroot/App/views/database/tasks/editOlapEtlTask.html
Labels: v6.0, Studio

#17824 RavenDB-21275: make sure to not use lsv that was yielded by IEnumerable
  src/Raven.Server/Documents/DocumentsStorage.cs
  test/SlowTests/Sharding/Client/Operations/GetDocumentConflictsTests.cs
Labels: v6.0

#17830 5.4 to 6.0 merge
  src/Raven.Server/Config/Categories/IntegrationsConfiguration.cs
  src/Raven.Server/Config/Categories/MonitoringConfiguration.cs
  src/Raven.Server/Config/RavenConfiguration.cs
  src/Sparrow/Utils/DecimalHelper.cs
  test/EmbeddedTests/BasicTests.cs
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
  test/SlowTests/Issues/RavenDB-20922.cs
  test/StressTests/Client/TimeSeries/TimeSeriesStress.cs
Labels: v6.0

#17820 RavenDB-21786 PowerBI integration - skip getting unchecked property value for document which does not have the property
  src/Raven.Server/Integrations/PostgreSQL/RqlQuery.cs
  test/SlowTests/Server/Integrations/PostgreSQL/RavenDB-21786.cs
Labels: v5.4

#17838 merge v5.4 -> v6.0
  src/Raven.Server/Documents/Handlers/Processors/Configuration/ConfigurationHandlerProcessorForPostTimeSeriesConfiguration.cs
  src/Raven.Server/Documents/Handlers/SubscriptionsHandler.cs
  src/Raven.Server/Documents/Sharding/Handlers/ShardedSubscriptionsHandler.cs
  src/Raven.Server/Exceptions/RaftIndexWaitAggregateException.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Smuggler/Documents/Actions/DatabaseRecordActions.cs
  src/Raven.Server/Web/RequestHandler.cs
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
  src/Raven.Server/Web/System/ShardedAdminDatabaseHandler.cs
  test/SlowTests/Tests/TestsInheritanceTests.cs
Labels: v6.0

#17832 RavenDB-20980 Memory improvements during indexing
  src/Corax/Indexing/EntriesModifications.cs
  src/Corax/Indexing/IndexWriter.Debug.cs
  src/Corax/Indexing/IndexWriter.cs
  src/Voron/Util/ContextBoundNativeList.cs
  src/Voron/Util/NativeList.cs
Labels: Corax, v6.0

#17844 RavenDB-19969 - split test to x86 and x64
  test/StressTests/Client/TimeSeries/TimeSeriesStress.cs
Labels: v5.4

#17843 RavenDB-20714 Adding extra debug info for failing flaky ETL test
  test/SlowTests/Issues/RavenDB-20136.cs
Labels: v5.4

#17842 RavenDB-19835 - Expected exception that shouldn't create a notification
  src/Raven.Server/Rachis/Exceptions.cs
  src/Raven.Server/Rachis/FollowerAmbassador.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
Labels: v5.4

#17840 RavenDB-21248: Fix logic for moving database into rehab (Test fix)
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
Labels: v5.4

#17837 RavenDB-19970 - StressTests.Client.TimeSeries.TimeSeriesStress.RapidR…
  test/StressTests/Client/TimeSeries/TimeSeriesStress.cs
Labels: v5.4

#17790 RavenDB-21490 Throw NotSupportedInCoraxException on attempt to dump or optimize Corax index
  src/Raven.Server/Documents/Handlers/Admin/AdminIndexHandler.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxIndexPersistence.cs
  src/Raven.Server/Documents/Indexes/Persistence/IndexPersistenceBase.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/LuceneIndexPersistence.cs
  test/SlowTests/Issues/RavenDB-21490.cs
Labels: Corax, v6.0

#17828 RavenDB-21710 - fixed DeleteDatabaseCommand not updating the raft etag in topology
  src/Raven.Server/ServerWide/Commands/DeleteDatabaseCommand.cs
  test/SlowTests/Issues/RavenDB_21553.cs
Labels: v6.0

#17853 RavenDB-20950 Consider not showing already set backup credentials
  src/Raven.Studio/typescript/viewmodels/database/tasks/destinations/googleCloudSettings.ts
  src/Raven.Studio/wwwroot/App/views/database/tasks/destinations/googleCloudSettings.html
Labels: v5.4, Studio

#17854 5.4 to 6.0 merge
  src/Raven.Server/Rachis/Exceptions.cs
  src/Raven.Server/Rachis/FollowerAmbassador.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/ServerWide/Commands/PromoteDatabaseNodeCommand.cs
  src/Voron/Data/Tables/TableValueCompressor.cs
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
  test/SlowTests/Issues/RDBC-128.cs
  test/SlowTests/Issues/RavenDB-20136.cs
  test/SlowTests/Issues/RavenDB_15856.cs
  test/SlowTests/Issues/RavenDB_3207.cs
  test/SlowTests/Issues/RavenDB_7674.cs
  test/SlowTests/Server/Documents/QueueSink/KafkaQueueSinkTests.cs
  test/SlowTests/SlowTests/Bugs/TimeoutTester.cs
  test/SlowTests/Voron/Issues/RavenDB_21107.cs
  test/StressTests/Client/TimeSeries/TimeSeriesStress.cs
Labels: v6.0

#17826 RavenDB-21743 `AutoMapReduceIndex` fanout index should have at least one '[]'.
  src/Raven.Server/Documents/Indexes/MapReduce/Auto/AutoMapReduceIndex.cs
  test/SlowTests/Issues/RavenDB_10925.cs
  test/SlowTests/Tests/TestsInheritanceTests.cs
Labels: v5.4

#17848 RavenDB-21793 Better context for disabled server-wide backup status dropdown
  src/Raven.Studio/typescript/components/pages/database/tasks/backups/BackupsPage.tsx
  src/Raven.Studio/typescript/components/pages/database/tasks/ongoingTasks/panels/PeriodicBackupPanel.tsx
  src/Raven.Studio/typescript/components/pages/database/tasks/shared/shared.tsx
  src/Raven.Studio/wwwroot/Content/scss/bs5variables.scss
Labels: v6.0, Studio

#17856 RavenDB-18015: SlowTests.Server.Documents.PeriodicBackup.Retention.can_delete_backups_by_date_azure (Expanded Debug Information)
  test/StressTests/Issues/RavenDB-13987.cs
  test/Tests.Infrastructure/RavenTestBase.Backup.cs
Labels: v6.0

#17855 RavenDB-20790 Use Security.Certificate.ExpiringThresholdInDays to jud…
  src/Raven.Server/Web/Studio/StudioTasksHandler.cs
  src/Raven.Studio/typescript/commands/resources/getStudioBootstrapCommand.ts
  src/Raven.Studio/typescript/common/settings/serverSettings.ts
  src/Raven.Studio/typescript/models/auth/clientCertificateModel.ts
  src/Raven.Studio/typescript/viewmodels/manage/certificates.ts
  src/Raven.Studio/typescript/viewmodels/resources/widgets/licenseWidget.ts
  src/Raven.Studio/typescript/viewmodels/shell.ts
  tools/TypingsGenerator/Program.cs
Labels: v6.0

#17847 RavenDB-21805: Test for server-wide periodic backup with pinned mentor node and failure scenario
  test/StressTests/Server/Documents/PeriodicBackup/PeriodicBackupTestsStress.cs
Labels: v5.4

#17862 RavenDB-21760 Handle reserved keywords in index definition
  src/Raven.Client/Documents/Indexes/ExpressionStringBuilder.cs
  test/SlowTests/Issues/RavenDB-21760.cs
Labels: v5.4

#17858 RavenDB-21780 - InvalidOperationException when trying to enforce revisions configuration on specific collections which one of them doesn't exist
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  test/SlowTests/Issues/RavenDB_21780.cs
Labels: v5.4

#17863 RavenDB-21814 use IOperationResult instead of BackupResult
  test/Tests.Infrastructure/RavenTestBase.Backup.cs
Labels: v6.0

#17857 RavenDB-19585 - Client doesn't failover if the topology changed
  src/Raven.Client/Http/RequestExecutor.cs
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
Labels: v5.4

#17860 RavenDB-21809 Add badges to Storybook
  src/Raven.Studio/typescript/components/common/BadgesVariants.stories.tsx
Labels: v6.0, Studio

#17872 RavenDB-20122 : High CPU when watcher is waiting for the leader to come up
  src/Raven.Server/ServerWide/ServerStore.cs
Labels: v5.4

#17882 RavenDB-21244 Add the process that is locking the file to the error message on Windows
  src/Voron/Impl/Paging/Windows32BitsMemoryMapPager.cs
  src/Voron/Platform/Win32/Win32NativeFileMethods.cs
  src/Voron/Platform/Win32/WindowsMemoryMapPager.cs
Labels: v5.4

#17883 RavenDB-20593: Trimmed mapping function to match mapPrefix
  src/Raven.Server/Documents/Indexes/Static/AbstractCountersAndTimeSeriesJavaScriptIndex.cs
  test/SlowTests/Issues/RavenDB-20593.cs
Labels: v5.4

#17885 5.4 to 6.0 merge
  src/Raven.Server/Documents/Indexes/Static/AbstractCountersAndTimeSeriesJavaScriptIndex.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Voron/Impl/Paging/Windows32BitsMemoryMapPager.cs
  src/Voron/Platform/Win32/Win32NativeFileMethods.cs
  src/Voron/Platform/Win32/WindowsMemoryMapPager.cs
  test/SlowTests/Issues/RavenDB-20593.cs
  test/SlowTests/Issues/RavenDB_14041.cs
Labels: v6.0

#17873 RavenDB-21806 Fix warning text when using 'Limit' in RQL
  src/Raven.Studio/wwwroot/App/views/database/query/query.html
Labels: v6.0, Studio

#17890 RavenDB-21797 Fix regex in `schemaInfo.ps1`
  scripts/schemaInfo.ps1
Labels: v5.4

#17889 RavenDB-21797 Regexes fix in `schemaInfo.ps1`
  scripts/schemaInfo.ps1
Labels: v6.0

#17886 RavenDB-21848: Fix for the issue where Importing a SuperUser crashed the process
  src/Voron/Data/Tables/TableValueCompressor.cs
Labels: v5.4

#17884 RavenDB-21824 Database state load - fail silently
  src/Raven.Studio/typescript/commands/resources/getDatabaseStateForStudioCommand.ts
Labels: v6.0, Studio

#17876 RavenDB-21360 fix test DisableAutoMapIndexClusterWideAndEnableLocally
  test/SlowTests/Issues/RavenDB-20922.cs
Labels: v6.0

#17879 RavenDB-21755 Fix test can_incremental_snapshot_and_restore_with_subs…
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
Labels: v6.0

#17892 5.4 to 6.0 merge
  src/Voron/Data/Tables/TableValueCompressor.cs
  test/SlowTests/Issues/RavenDB-20922.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
Labels: v6.0

#17895 RavenDB-21802 Should_Delete_All_Documents_Without_Timeout fix
  src/Raven.Client/Documents/BulkInsert/BulkInsertOperation.cs
Labels: v5.4

#17759 RavenDB-21711 Implementation of RavenDB-17745 (heartbeats from bulk I…
  src/Raven.Client/Documents/BulkInsert/BulkInsertOperation.cs
  src/Raven.Client/Documents/BulkInsert/BulkInsertWriterBase.cs
  src/Raven.Server/Documents/Handlers/BulkInsert/BulkInsertHandler.cs
  src/Raven.Server/Documents/Handlers/Processors/BulkInsert/AbstractBulkInsertHandlerProcessor.cs
  src/Raven.Server/Documents/Sharding/Handlers/BulkInsert/ShardedBulkInsertHandler.cs
  src/Raven.Server/Documents/Sharding/ShardedDatabaseContext.Testing.cs
  test/SlowTests/Issues/RavenDB-17745.cs
Labels: v6.0

#17896 5.4 to 6.0 merge
  src/Raven.Client/Documents/BulkInsert/BulkInsertOperation.cs
Labels: v6.0

#17898 RavenDB-21804: fix Invalid JSON returned from the Subscription test when using include
  src/Raven.Server/Documents/Handlers/Processors/Subscriptions/SubscriptionsHandlerProcessorForTrySubscription.cs
  src/Raven.Server/Documents/Includes/AbstractIncludesCommand.cs
  src/Raven.Server/Documents/Includes/DatabaseIncludesCommandImpl.cs
  src/Raven.Server/Documents/Includes/Sharding/OrchestratorIncludesCommandImpl.cs
  src/Raven.Server/Documents/Includes/Sharding/ShardIncludesCommandImpl.cs
  test/SlowTests/Client/Subscriptions/SubscriptionsBasic.cs
Labels: v6.0

#17897 RavenDB-21852 Fixing ArgumentOutOfRangeException throw by GetOngoingTaskInfoOperation() for OngoingTaskType.QueueSink
  src/Raven.Client/Documents/Operations/OngoingTasks/GetOngoingTaskInfoOperation.cs
  src/Raven.Client/Json/Serialization/JsonDeserializationClient.cs
  src/Raven.Server/Documents/OngoingTasks/OngoingTasks.cs
  test/SlowTests/Server/Documents/QueueSink/QueueSinkTestBase.cs
  test/SlowTests/Server/Documents/QueueSink/RabbitMqSinkTests.cs
  test/SlowTests/Server/Documents/QueueSink/RavenDB_21852.cs
Labels: v6.0

#17893 RavenDB-21810 Fix validation errors positioning
  src/Raven.Studio/typescript/components/common/Form.stories.tsx
  src/Raven.Studio/typescript/components/common/Form.tsx
  src/Raven.Studio/typescript/components/common/FormCollectionsSelect.tsx
  src/Raven.Studio/typescript/components/common/select/Select.stories.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/clientConfiguration/ClientDatabaseConfiguration.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/documentRevisions/EditRevision.tsx
  src/Raven.Studio/typescript/components/pages/resources/manageServer/clientConfiguration/ClientGlobalConfiguration.tsx
  src/Raven.Studio/wwwroot/Content/scss/_bs5extend.scss
  src/Raven.Studio/wwwroot/Content/scss/bs5variables.scss
Labels: v6.0, Studio

#17899 RavenDB-20867 - adjust failing test
  test/SlowTests/Sharding/ShardingTopologyTests.cs
Labels: v6.0

#17909 RavenDB-21868 Fix OID descriptions
  src/Raven.Server/Monitoring/Snmp/SnmpOids.cs
Labels: v5.4

#17887 RavenDB-17753 Server store (System) will take into account "Storage.Temp" configuration option for temporary directory
  src/Raven.Server/ServerWide/ServerStore.cs
  test/SlowTests/Issues/RavenDB_17753.cs
Labels: v5.4

#17906 RavenDB-21866 : Timeseries doesn't load in ETL when filtering by series name in its original casing
  src/Raven.Server/Documents/ETL/Providers/Raven/RavenEtlDocumentTransformer.cs
  test/SlowTests/Issues/RavenDB_21866.cs
Labels: v5.4

#17874 RavenDB-19970 - StressTests.Client.TimeSeries.TimeSeriesStress.RapidR…
  src/Raven.Server/Documents/TimeSeries/TimeSeriesStorage.cs
Labels: v5.4

#17900 RavenDB-20426 : HandleSpecificClusterDatabaseChanged - throw if database is already faulted
  src/Raven.Server/Documents/DatabasesLandlord.cs
Labels: v6.0

#17908 RavenDB-21606 : flaky test adjustments
  test/SlowTests/Server/Documents/TimeSeries/TimeSeriesTombstoneCleaner.cs
Labels: v6.0

#17914 RavenDB-21830 Fix Ace Editor full screen
  src/Raven.Studio/wwwroot/Content/css/bootstrap/variables-body.less
  src/Raven.Studio/wwwroot/Content/css/styles-common-scoped.less
Labels: v6.0, Studio

#17915 RavenDB-21746 Fix rvn init-setup-params default Addresses field values
  tools/rvn/InitSetupParams.cs
Labels: v5.4

#17916 RavenDB-21747 The rvn create-setup-package creates values.yaml without --generate-helm-values
  tools/rvn/CommandLineApp.cs
Labels: v5.4

#17922 RavenDB-7070: Solved warnings and removed preview language usage.
  src/Corax/Corax.csproj
  src/Sparrow.Server/Collections/Persistent/BinaryTree.cs
  src/Sparrow.Server/Compression/Encoder3Gram.cs
  src/Voron/Data/CompactTrees/CompactKey.cs
  src/Voron/Data/CompactTrees/CompactKeyCacheScope.cs
  src/Voron/Util/ActiveTransactions.cs
  src/Voron/Voron.csproj
Labels: v6.0

#17925 fixed studio
  src/Raven.Studio/typescript/common/shell/footer.ts
Labels: v6.0, Studio

#17924 RavenDB-21536 Revert "Disable codepaths with Vector128.Load on ARM platforms to avoid segmentation faults."
  src/Corax/Utils/EntryIdEncodings.cs
  src/Sparrow.Server/Platform/PlatformSpecific.cs
  src/Sparrow.Server/Strings/StringsExtensions.cs
  src/Voron/Data/Containers/Container.cs
  src/Voron/Data/Lookups/Lookup.cs
  src/Voron/Util/PFor/FastPForDecoder.cs
Labels: v6.0

#17926 fixed studio (v5.4)
  src/Raven.Studio/typescript/common/shell/footer.ts
Labels: v5.4, Studio
