Repository ravendb/ravendb, pull requests merged in 2024-09, with the labels that each got.

#19189 RavenDB-22807 - skip creating a delay task if not needed
  src/Sparrow.Server/Utils/DiskStatsGetter/DiskStatsGetter.cs
Labels: v5.4

#19190 RavenDB-22643 while generating offline database info, we need to pena read tx in server store in order to get the backup status, but in DatabasesLandlord the databases that are still loading are being disposed in parallel without any await
  src/Raven.Server/Documents/DocumentDatabase.cs
Labels: v6.0

#19186 RavenDB-22848 - StressTests.Issues.RavenDB_18420.ShouldRescheduleBackupTimerIfDocumentDatabaseFailedToLoad
  src/Raven.Server/Documents/DatabasesLandlord.cs
Labels: v5.4

#19204 RavenDB-22366 - fix XML docs warnings in timeseries
  src/Raven.Client/Documents/Session/ISessionDocumentTimeSeriesBase.cs
Labels: v6.0

#19157 RavenDB-22709-v5.4 - Add validation to prevent empty Url on client AP…
  src/Raven.Client/Documents/Operations/Replication/PullReplicationAsSink.cs
Labels: v5.4

#19200 RavenDB-22709 - revert changes made in PullReplicationAsSink
  src/Raven.Client/Documents/Operations/Replication/PullReplicationAsSink.cs
Labels: v6.0

#19209 RavenDB-22822 fix test and prevent reusing the same raft command instance
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/ServerWide/Commands/CommandBase.cs
  test/RachisTests/CommandsTests.cs
Labels: v5.4

#19210 RavenDB-22857 - Remove Disposed Replication Handlers from _incoming/_…
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  test/SlowTests/Issues/RavenDB_22709.cs
Labels: v5.4

#19208 RavenDB-22767 - set the read and write delay timeout for the StreamWithTimeout correctly
  src/Raven.Client/Util/StreamWithTimeout.cs
Labels: v5.4

#19222 Merge release/v6.0 to v6.0
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Studio/typescript/common/timingsChart.ts
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/create/formBackup/createDatabaseFromBackupValidation.ts
Labels: v6.0

#19223 Merge release/v6.1 to v6.1
  src/Raven.Client/Documents/Operations/Replication/PullReplicationAsSink.cs
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Studio/typescript/common/timingsChart.ts
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/create/formBackup/createDatabaseFromBackupValidation.ts
Labels: v6.1

#19225 5.4 to 6.0 merge
  src/Raven.Client/Documents/Operations/ConnectionStrings/ConnectionString.cs
  src/Raven.Client/Documents/Operations/ETL/Elasticsearch/ElasticsearchConnectionString.cs
  src/Raven.Client/Documents/Operations/ETL/OLAP/OlapConnectionString.cs
  src/Raven.Client/Documents/Operations/ETL/Queue/KafkaConnectionSettings.cs
  src/Raven.Client/Documents/Operations/ETL/Queue/QueueConnectionString.cs
  src/Raven.Client/Documents/Operations/ETL/Queue/RabbitMqConnectionSettings.cs
  src/Raven.Client/Documents/Operations/ETL/RavenConnectionString.cs
  src/Raven.Client/Documents/Operations/ETL/SQL/SqlConnectionString.cs
  src/Raven.Client/Util/StreamWithTimeout.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/ServerWide/Commands/CommandBase.cs
  src/Raven.Server/ServerWide/OperationCancelToken.cs
  src/Sparrow.Server/Utils/DiskStatsGetter/DiskStatsGetter.cs
  test/RachisTests/CommandsTests.cs
  test/SlowTests/Issues/RavenDB_22709.cs
  test/SlowTests/Server/Documents/ETL/ConnectionStringTests.cs
Labels: v6.0

#19226 6.0 to 6.1 merge
  src/Raven.Client/Constants.cs
  src/Raven.Client/Documents/Operations/ConnectionStrings/ConnectionString.cs
  src/Raven.Client/Documents/Operations/ETL/Elasticsearch/ElasticsearchConnectionString.cs
  src/Raven.Client/Documents/Operations/ETL/OLAP/OlapConnectionString.cs
  src/Raven.Client/Documents/Operations/ETL/Queue/KafkaConnectionSettings.cs
  src/Raven.Client/Documents/Operations/ETL/Queue/QueueConnectionString.cs
  src/Raven.Client/Documents/Operations/ETL/Queue/RabbitMqConnectionSettings.cs
  src/Raven.Client/Documents/Operations/ETL/RavenConnectionString.cs
  src/Raven.Client/Documents/Operations/ETL/SQL/SqlConnectionString.cs
  src/Raven.Client/Documents/Session/ISessionDocumentTimeSeriesBase.cs
  src/Raven.Client/ServerWide/DatabaseRecord.cs
  src/Raven.Client/Util/StreamWithTimeout.cs
  src/Raven.Server/Documents/ConflictsStorage.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/DocumentIdWorker.cs
  src/Raven.Server/Documents/Handlers/Debugging/ServerWideDebugInfoPackageHandler.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/AbstractRestoreBackupTask.cs
  src/Raven.Server/Documents/Replication/Incoming/IncomingReplicationHandler.cs
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/ServerWide/Commands/CommandBase.cs
  src/Raven.Server/ServerWide/OperationCancelToken.cs
  src/Raven.Server/ServerWide/RawDatabaseRecord.cs
  src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
  src/Raven.Server/Smuggler/Documents/StreamSource.cs
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
  src/Sparrow.Server/Utils/DiskStatsGetter/DiskStatsGetter.cs
  test/RachisTests/CommandsTests.cs
  test/SlowTests/Data/RavenDB_21263/revisionsWithLargeChangeVector-oldDatabaseVersion.ravendb-snapshot
  test/SlowTests/Data/RavenDB_21263/test1111-emptySupportedFeatures.ravendbdump
  test/SlowTests/Data/RavenDB_21263/test1111-withoutSupportedFeatures.ravendbdump
  test/SlowTests/Issues/RavenDB_21263.cs
  test/SlowTests/Issues/RavenDB_22709.cs
  test/SlowTests/Server/Documents/ETL/ConnectionStringTests.cs
  test/SlowTests/SlowTests.csproj
Labels: v6.1

#19228 6.1 to 6.2 merge
  src/Raven.Client/Constants.cs
  src/Raven.Client/Documents/Operations/ConnectionStrings/ConnectionString.cs
  src/Raven.Client/Documents/Operations/ETL/Elasticsearch/ElasticsearchConnectionString.cs
  src/Raven.Client/Documents/Operations/ETL/OLAP/OlapConnectionString.cs
  src/Raven.Client/Documents/Operations/ETL/Queue/KafkaConnectionSettings.cs
  src/Raven.Client/Documents/Operations/ETL/Queue/QueueConnectionString.cs
  src/Raven.Client/Documents/Operations/ETL/Queue/RabbitMqConnectionSettings.cs
  src/Raven.Client/Documents/Operations/ETL/RavenConnectionString.cs
  src/Raven.Client/Documents/Operations/ETL/SQL/SqlConnectionString.cs
  src/Raven.Client/Documents/Operations/Replication/PullReplicationAsSink.cs
  src/Raven.Client/Documents/Session/ISessionDocumentTimeSeriesBase.cs
  src/Raven.Client/ServerWide/DatabaseRecord.cs
  src/Raven.Client/Util/StreamWithTimeout.cs
  src/Raven.Server/Documents/ConflictsStorage.cs
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/DocumentIdWorker.cs
  src/Raven.Server/Documents/Handlers/Debugging/ServerWideDebugInfoPackageHandler.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/AbstractRestoreBackupTask.cs
  src/Raven.Server/Documents/Replication/Incoming/IncomingReplicationHandler.cs
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/ServerWide/Commands/CommandBase.cs
  src/Raven.Server/ServerWide/OperationCancelToken.cs
  src/Raven.Server/ServerWide/RawDatabaseRecord.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
  src/Raven.Server/Smuggler/Documents/StreamSource.cs
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
  src/Raven.Studio/typescript/common/timingsChart.ts
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/create/formBackup/createDatabaseFromBackupValidation.ts
  src/Sparrow.Server/Utils/DiskStatsGetter/DiskStatsGetter.cs
  test/RachisTests/CommandsTests.cs
  test/SlowTests/Data/RavenDB_21263/revisionsWithLargeChangeVector-oldDatabaseVersion.ravendb-snapshot
  test/SlowTests/Data/RavenDB_21263/test1111-emptySupportedFeatures.ravendbdump
  test/SlowTests/Data/RavenDB_21263/test1111-withoutSupportedFeatures.ravendbdump
  test/SlowTests/Issues/RavenDB_21263.cs
  test/SlowTests/Issues/RavenDB_22709.cs
  test/SlowTests/Server/Documents/ETL/ConnectionStringTests.cs
  test/SlowTests/SlowTests.csproj
Labels: v6.2

#19241 RavenDB-22880 - SlowTests.Issues.RavenDB_22709.PullReplicationWithSin…
  test/SlowTests/Issues/RavenDB_22709.cs
Labels: v6.0

#19234 RavenDB-20877: Environment variables adjustment
  src/Sparrow/AdvInstructionSet.cs
  src/Voron/VoronConfiguration.cs
Labels: v6.2

#19246 RavenDB-22457 - Fixing test using read only memory
  test/StressTests/Voron/HugeTransactions.cs
Labels: v6.2

#19242 5.4 to 6.0 merge
  src/Raven.Client/Documents/Indexes/IndexProgress.cs
  src/Raven.Client/Documents/Indexes/IndexStats.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/IndexItem.cs
  src/Raven.Server/Documents/Indexes/IndexItemType.cs
  src/Raven.Server/Documents/Indexes/IndexStorage.cs
  src/Raven.Server/Documents/Indexes/MapIndexBase.cs
  src/Raven.Server/Documents/Indexes/MapReduce/Auto/AutoMapReduceIndex.cs
  src/Raven.Server/Documents/Indexes/MapReduce/MapReduceIndexingContext.cs
  src/Raven.Server/Documents/Indexes/MapReduce/OutputToCollection/OutputReduceLuceneIndexWriteOperation.cs
  src/Raven.Server/Documents/Indexes/MapReduce/ReduceMapResultsBase.cs
  src/Raven.Server/Documents/Indexes/MapReduce/Static/MapReduceIndex.cs
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxIndexWriteOperation.cs
  src/Raven.Server/Documents/Indexes/Persistence/Corax/OutputReduceCoraxIndexWriteOperation.cs
  src/Raven.Server/Documents/Indexes/Persistence/IndexWriteOperationBase.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/LuceneIndexPersistence.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/LuceneIndexWriteOperation.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/LuceneIndexWriter.cs
  src/Raven.Server/Documents/Indexes/Static/Counters/MapCountersIndex.cs
  src/Raven.Server/Documents/Indexes/Static/Counters/MapReduceCountersIndex.cs
  src/Raven.Server/Documents/Indexes/Static/MapIndex.cs
  src/Raven.Server/Documents/Indexes/Static/TimeSeries/MapReduceTimeSeriesIndex.cs
  src/Raven.Server/Documents/Indexes/Static/TimeSeries/MapTimeSeriesIndex.cs
  src/Raven.Server/Documents/Indexes/Test/TestIndexWriteOperation.cs
  src/Raven.Server/Documents/Indexes/Workers/Cleanup/CleanupDocuments.cs
  src/Raven.Server/Documents/Indexes/Workers/Cleanup/CleanupDocumentsForMapReduce.cs
  src/Raven.Server/Documents/Indexes/Workers/Cleanup/CleanupItemsBase.cs
  src/Raven.Server/Documents/Indexes/Workers/Cleanup/CleanupTimeSeries.cs
  src/Raven.Server/Documents/Indexes/Workers/Cleanup/CleanupTimeSeriesForMapReduce.cs
  src/Raven.Server/Documents/Indexes/Workers/Cleanup/TombstoneIndexItem.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesDeletedRangeEntry.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesStorage.cs
  src/Raven.Server/Indexing/IndexTransactionCache.cs
  src/Raven.Server/Json/BlittableJsonTextWriterExtensions.cs
  src/Raven.Server/ServerWide/DeferrableTimeout.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Studio/typescript/test/stubs/IndexesStubs.ts
  test/FastTests/Client/Indexing/TimeSeries/BasicTimeSeriesIndexes.cs
  test/SlowTests/Client/Indexing/TimeSeries/BasicTimeSeriesIndexes_JavaScript.cs
  test/SlowTests/Client/Indexing/TimeSeries/BasicTimeSeriesIndexes_MethodSyntax.cs
  test/SlowTests/Client/Indexing/TimeSeries/BasicTimeSeriesIndexes_MixedSyntax.cs
  test/SlowTests/Client/Indexing/TimeSeries/BasicTimeSeriesIndexes_StrongSyntax.cs
  test/SlowTests/Issues/RavenDB_15240.cs
  test/SlowTests/Issues/RavenDB_21681.cs
  test/SlowTests/Issues/RavenDB_22829_DeferrableTimerTests.cs
  test/SlowTests/Server/Documents/ETL/EtlTimeSeriesTests.cs
  test/SlowTests/Server/Documents/Indexing/MapReduce/RavenDB_11643.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
Labels: v6.0

#19247 RavenDB-22872 Ensure we comparing tombstone ID with a document tombstone
  src/Raven.Server/Documents/DocumentsStorage.cs
  test/SlowTests/Issues/RavenDB_22872.cs
Labels: v5.4

#19248 RavenDB-22874 - Tombstones from artificial documents are being replic…
  test/SlowTests/Issues/RavenDB_22874.cs
Labels: v5.4

#19250 RavenDB-22883 - Use a single cancellation token for the entire write process of the response
  src/Raven.Server/Documents/Handlers/AttachmentHandler.cs
Labels: v5.4

#19251 RavenDB-22877 - SlowTests.Issues.RavenDB_21681.ShouldUpdateMapReduceI…
  test/SlowTests/Issues/RavenDB_21681.cs
Labels: v5.4

#19252 RavenDB-22885 - Use the correct cancellation token for the operation
  src/Raven.Server/Documents/Handlers/BulkInsertHandler.cs
Labels: v5.4

#19253 5.4 to 6.0 merge
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Handlers/AttachmentHandler.cs
  src/Raven.Server/Documents/Handlers/Processors/BulkInsert/AbstractBulkInsertHandlerProcessor.cs
  src/Raven.Server/Documents/Handlers/Processors/BulkInsert/BulkInsertHandlerProcessor.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/LuceneAnalyzerAdapterForQuerying.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/BulkInsert/ShardedBulkInsertHandlerProcessor.cs
  src/Voron/Data/Lookups/Lookup.cs
  test/SlowTests/Issues/RavenDB_21263.cs
  test/SlowTests/Issues/RavenDB_21681.cs
  test/SlowTests/Issues/RavenDB_22872.cs
Labels: v6.0

#19258 RavenDB-22821 Use cache in LuceneAnalyzerAdapterForQuerying
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/LuceneAnalyzerAdapterForQuerying.cs
Labels: v6.0

#19266 RavenDB-22898 bumped 6.2 to 7.0
  .github/workflows/FastTests.yml
  .github/workflows/StudioTests.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/studioConventions.yml
  SECURITY.md
  docker/common.ps1
  docker/compose/linux-cluster/docker-compose.yml
  docker/compose/win-cluster/docker-compose.yml
  docker/debug/build-ubuntu-debug.ps1
  docker/debug/ravendb-ubuntu-debug/Dockerfile
  docker/manifest/manifest.yml
  docker/readme.md
  docker/run-linux.ps1
  docker/run-nanoserver.ps1
  docs/readme.linux.txt
  scripts/certificates/powershell/dev-create-authenticated-cluster-with-subdomains.ps1
  scripts/certificates/powershell/dev-create-authenticated-cluster.ps1
  scripts/version.ps1
  src/CommonAssemblyInfo.cs
  src/Raven.Client/DocumentationUrls.cs
  src/Raven.Client/Properties/VersionInfo.cs
  src/Raven.Embedded/Raven.Embedded.nuspec.template
  src/Raven.Server/Monitoring/Snmp/Templates/zabbix_ravendb_template.xml
  src/Raven.Server/Program.cs
  src/Raven.Server/RavenServer.cs
  src/Raven.Server/ServerWide/ServerVersion.cs
  src/Raven.Studio/typescript/commands/commandBase.ts
  src/Raven.Studio/wwwroot/version.txt
Labels: v7.0

#19272 Merge release/v6.2 to 6.2
  .github/workflows/FastTests.yml
  .github/workflows/StudioTests.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/studioConventions.yml
  SECURITY.md
  docker/common.ps1
  docker/compose/linux-cluster/docker-compose.yml
  docker/compose/win-cluster/docker-compose.yml
  docker/debug/build-ubuntu-debug.ps1
  docker/debug/ravendb-ubuntu-debug/Dockerfile
  docker/manifest/manifest.yml
  docker/ravendb-ubuntu/run-raven.sh
  docker/readme.md
  docker/run-linux.ps1
  docker/run-nanoserver.ps1
  docs/readme.linux.txt
  docs/readme.windows.txt
  readme.md
  scripts/certificates/powershell/dev-create-authenticated-cluster-with-subdomains.ps1
  scripts/certificates/powershell/dev-create-authenticated-cluster.ps1
  scripts/raspberry-pi/setup.sh
  scripts/raspberry-pi/start.sh
  scripts/updateSourceWithBuildInfo.ps1
  scripts/version.ps1
  src/CommonAssemblyInfo.cs
  src/Raven.Client/DocumentationUrls.cs
  src/Raven.Client/Properties/VersionInfo.cs
  src/Raven.Embedded/Raven.Embedded.nuspec.template
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxDocumentConverterBase.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/LuceneAnalyzerAdapterForQuerying.cs
  src/Raven.Server/Documents/Sharding/Queries/AbstractShardedQueryProcessor.cs
  src/Raven.Server/Monitoring/Snmp/Templates/zabbix_ravendb_template.xml
  src/Raven.Server/NotificationCenter/Indexing.cs
  src/Raven.Server/Program.cs
  src/Raven.Server/RavenServer.cs
  src/Raven.Server/ServerWide/ClusterCommandsVersionManager.cs
  src/Raven.Server/ServerWide/ServerVersion.cs
  src/Raven.Server/Storage/Schema/SchemaUpgrader.cs
  src/Raven.Server/Storage/Schema/Updates/CoraxIndex/62000/From61000.cs
  src/Raven.Server/Storage/Schema/Updates/Documents/62000/From61000.cs
  src/Raven.Server/Storage/Schema/Updates/LuceneIndex/62000/From61000.cs
  src/Raven.Server/Storage/Schema/Updates/Server/62000/From61000.cs
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
  src/Raven.Studio/typescript/commands/commandBase.ts
  src/Raven.Studio/wwwroot/version.txt
Labels: v6.2

#19278 Merge release/v5.4 to 5.4
  .github/workflows/FastTests.yml
  .github/workflows/FastTestsARM.yml
  .github/workflows/StudioTests.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/compile.yml
  .github/workflows/conventions.yml
  .github/workflows/slackNotify.yml
  .github/workflows/studioConventions.yml
  .github/workflows/studioLabel.yml
  .github/workflows/versionLabel.yml
  docker/common.ps1
Labels: v5.4

#19279 Merge release/v6.0 to 6.0
  .github/workflows/FastTests.yml
  .github/workflows/FastTestsARM.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/compile.yml
  .github/workflows/conventions.yml
  .github/workflows/slackNotify.yml
  .github/workflows/studioLabel.yml
  .github/workflows/versionLabel.yml
  docker/common.ps1
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/LuceneAnalyzerAdapterForQuerying.cs
Labels: v6.0

#19280 Merge release/v6.2 into 6.2
  .github/workflows/FastTests.yml
  .github/workflows/FastTestsARM.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/compile.yml
  .github/workflows/conventions.yml
  .github/workflows/slackNotify.yml
  .github/workflows/studioLabel.yml
  .github/workflows/versionLabel.yml
  docker/common.ps1
Labels: v6.2

#19276 RavenDB-22534 Assert the link in the test without including the version (the prefix is fixed across all versions)
  test/SlowTests/Issues/RavenDB_22534.cs
Labels: v6.2

#19256 RavenDB-22695 Cannot see the pull replication state on the hub
  src/Raven.Studio/typescript/components/pages/database/tasks/ongoingTasks/OngoingTasksReducer.ts
Labels: v6.0, Studio

#19289 Merge release/v6.0 to v6.0
  src/CommonAssemblyInfo.cs
  src/Raven.Client/Properties/VersionInfo.cs
Labels: v6.0

#19294 Merge release/v5.4 to v5.4
  src/CommonAssemblyInfo.cs
  src/Raven.Client/Properties/VersionInfo.cs
Labels: v5.4

#19199 RavenDB-22659 Cancelling the restore doesn't always delete the database
  src/Raven.Server/Documents/Handlers/QueriesHandler.cs
  src/Raven.Server/Documents/Operations/Operations.cs
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
  test/SlowTests/Issues/RavenDB-22659.cs
Labels: v5.4

#19249 RavenDB-22869 Object.entries() possible NRE
  src/Raven.Studio/languageService/test/autocomplete/FakeMetadataProvider.ts
  src/Raven.Studio/typescript/common/settings/studioSettings.ts
  src/Raven.Studio/typescript/components/common/shell/accessManagerSlice.ts
  src/Raven.Studio/typescript/models/auth/certificateModel.ts
  src/Raven.Studio/typescript/models/database/cluster/clusterTopology.ts
  src/Raven.Studio/typescript/models/database/dbGroup/databaseGroupGraph.ts
  src/Raven.Studio/typescript/models/database/documents/documentMetadata.ts
  src/Raven.Studio/typescript/models/database/documents/timeSeriesConfigurationEntry.ts
  src/Raven.Studio/typescript/models/database/index/indexDefinition.ts
  src/Raven.Studio/typescript/models/database/settings/connectionStringKafkaModel.ts
  src/Raven.Studio/typescript/models/database/timeSeries/timeSeriesEntryModel.ts
  src/Raven.Studio/typescript/models/resources/database.ts
  src/Raven.Studio/typescript/models/resources/shardedDatabase.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/alerts/complexFieldsAlertDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/enforceRevisionsConfigurationDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/revertRevisionsDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/performanceHint/indexingDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/performanceHint/pagingDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/performanceHint/requestLatencyDetails.ts
  src/Raven.Studio/typescript/viewmodels/database/identities/identities.ts
  src/Raven.Studio/typescript/viewmodels/database/query/query.ts
  src/Raven.Studio/typescript/viewmodels/database/query/queryPlan.ts
  src/Raven.Studio/typescript/viewmodels/database/settings/timeSeries.ts
  src/Raven.Studio/typescript/viewmodels/database/status/ongoingTasksStats.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editSubscriptionTask.ts
  src/Raven.Studio/typescript/viewmodels/manage/debugAdvancedMemoryMappedFiles.ts
Labels: v6.0, Studio

#19313 RavenDB-22714 Compact database button in shard storage report doesn't…
  src/Raven.Studio/typescript/common/appUrl.ts
  src/Raven.Studio/typescript/components/pages/resources/databases/DatabasesPage.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/DatabasePanel.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/store/databasesViewActions.ts
  src/Raven.Studio/typescript/viewmodels/database/status/storageReport.ts
  src/Raven.Studio/typescript/viewmodels/resources/compactDatabaseDialog.ts
  src/Raven.Studio/wwwroot/App/views/resources/compactDatabaseDialog.html
Labels: v6.0, Studio

#19308 RavenDB-22935 Broken backup notification
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/smugglerDatabaseDetails.ts
Labels: v5.4, Studio

#19304 RavenDB-22530 When editing SQL ETL place a warning there that the connection string is using a factory that is depracated
  src/Raven.Studio/typescript/viewmodels/database/tasks/editSqlEtlTask.ts
  src/Raven.Studio/wwwroot/App/views/database/tasks/editSqlEtlTask.html
Labels: v5.4, Studio

#19301 RavenDB-22777 Fix cut popovers in database creator
  src/Raven.Studio/typescript/components/common/ConditionalPopover.tsx
  src/Raven.Studio/typescript/components/common/LicenseRestrictedMessage.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/create/formBackup/steps/CreateDatabaseFromBackupStepBasicInfo.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/create/formBackup/steps/source/CreateDatabaseFromBackupStepSource.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/create/regular/steps/CreateDatabaseRegularStepBasicInfo.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/create/regular/steps/CreateDatabaseRegularStepReplicationAndSharding.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/create/shared/EncryptionUnavailableMessage.tsx
  src/Raven.Studio/wwwroot/Content/scss/bs5variables.scss
Labels: v6.0, Studio

#19296 RavenDB-22680 Add deleted time series progress bar
  src/Raven.Studio/typescript/models/database/index/indexProgress.ts
  src/Raven.Studio/wwwroot/App/views/database/indexes/indexes.html
  src/Raven.Studio/wwwroot/Content/css/pages/indexes.less
Labels: v5.4, Studio

#18940 RavenDB-22367 Add VirtualTable and VirtualTableWithLazyLoading components
  src/Raven.Studio/.eslintrc.js
  src/Raven.Studio/.nvmrc
  src/Raven.Studio/package-lock.json
  src/Raven.Studio/package.json
  src/Raven.Studio/tsconfig.json
  src/Raven.Studio/typescript/commands/database/documents/getDocumentsPreviewCommand.ts
  src/Raven.Studio/typescript/components/common/Code.tsx
  src/Raven.Studio/typescript/components/common/SizeGetter.stories.tsx
  src/Raven.Studio/typescript/components/common/SizeGetter.tsx
  src/Raven.Studio/typescript/components/common/VirtualGrid.stories.tsx
  src/Raven.Studio/typescript/components/common/VirtualGrid.tsx
  src/Raven.Studio/typescript/components/common/virtualTable/VirtualTable.scss
  src/Raven.Studio/typescript/components/common/virtualTable/VirtualTable.stories.tsx
  src/Raven.Studio/typescript/components/common/virtualTable/VirtualTable.tsx
  src/Raven.Studio/typescript/components/common/virtualTable/VirtualTableWithLazyLoading.tsx
  src/Raven.Studio/typescript/components/common/virtualTable/bits/VirtualTableBodyWrapper.tsx
  src/Raven.Studio/typescript/components/common/virtualTable/bits/VirtualTableHead.tsx
  src/Raven.Studio/typescript/components/common/virtualTable/bits/VirtualTableState.tsx
  src/Raven.Studio/typescript/components/common/virtualTable/cells/CellDocumentPreview.tsx
  src/Raven.Studio/typescript/components/common/virtualTable/cells/CellDocumentValue.tsx
  src/Raven.Studio/typescript/components/common/virtualTable/cells/CellValue.tsx
  src/Raven.Studio/typescript/components/common/virtualTable/cells/CellWithCopy.tsx
  src/Raven.Studio/typescript/components/common/virtualTable/columnProviders/useDocumentColumnsProvider.tsx
  src/Raven.Studio/typescript/components/common/virtualTable/commonComponents/columnsSelect/TableDisplaySettings.scss
  src/Raven.Studio/typescript/components/common/virtualTable/commonComponents/columnsSelect/TableDisplaySettings.tsx
  src/Raven.Studio/typescript/components/common/virtualTable/commonComponents/columnsSelect/useTableDisplaySettings.ts
  src/Raven.Studio/typescript/components/common/virtualTable/hooks/useVirtualTableWithLazyLoading.ts
  src/Raven.Studio/typescript/components/common/virtualTable/utils/commonColumnDefs.tsx
  src/Raven.Studio/typescript/components/common/virtualTable/utils/documentColumnDefs.tsx
  src/Raven.Studio/typescript/components/common/virtualTable/utils/virtualTableConstants.ts
  src/Raven.Studio/typescript/components/common/virtualTable/utils/virtualTableUtils.ts
  src/Raven.Studio/typescript/components/pages/database/settings/customSorters/DatabaseCustomSorterTest.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/customSorters/DatabaseCustomSorterTestResult.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/customSorters/DatabaseCustomSorters.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/tombstones/TombstonesState.spec.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/tombstones/TombstonesState.stories.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/tombstones/TombstonesState.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/tombstones/useTombstonesStateColumns.tsx
  src/Raven.Studio/typescript/components/services/DatabasesService.ts
  src/Raven.Studio/typescript/models/database/documents/document.ts
  src/Raven.Studio/typescript/test/fixtures/query_result.json
  src/Raven.Studio/typescript/test/mocks/store/MockCollectionsTracker.ts
  src/Raven.Studio/wwwroot/Content/css/basic-layout.less
  src/Raven.Studio/wwwroot/Content/css/root.less
  src/Raven.Studio/wwwroot/Content/scss/_colors.scss
  src/Raven.Studio/wwwroot/Content/scss/_custom-properties.scss
  src/Raven.Studio/wwwroot/Content/scss/bs5variables.scss
Labels: v6.0, Studio

#19292 RavenDB-22899 - Set the ReadTimeout and the WriteTimeout from a single place
  src/Raven.Client/Util/StreamWithTimeout.cs
Labels: v5.4

#19303 RavenDB-22931 ConditionalLoadAsync fix
  src/Raven.Client/Documents/Session/AsyncDocumentSession.ConditionalLoad.cs
  test/SlowTests/Issues/Issue_19302.cs
Labels: v5.4

#19315 RavenDB-22866 fixing studio compilation
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexesPage.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/list/useIndexesPage.tsx
Labels: v6.0, Studio

#19320 RavenDB-22944 Remove unused Conventions Slack Notifications
  .github/workflows/compile.yml
  .github/workflows/conventions.yml
  .github/workflows/slackNotify.yml
  scripts/githubActions/CompileGenerateMessage.sh
  scripts/githubActions/ConventionsGenerateMessage.sh
Labels: v5.4

#19321 5.4 to 6.0 merge
  .github/workflows/compile.yml
  .github/workflows/conventions.yml
  .github/workflows/slackNotify.yml
  scripts/githubActions/CompileGenerateMessage.sh
  scripts/githubActions/ConventionsGenerateMessage.sh
Labels: v6.0

#19324 RavenDB-22943 Database name comparison needs to be case insensitive
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/create/formBackup/createDatabaseFromBackupValidation.ts
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/create/regular/createDatabaseRegularValidation.ts
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/create/shared/createDatabaseSharedValidation.tsx
Labels: Studio, v6.2

#19330 RavenDB-21634 Added option to not ignore expiration run exception in the test
  src/Raven.Server/Documents/Expiration/ExpiredDocumentsCleaner.cs
  test/SlowTests/Server/Documents/Expiration/ExpirationTests.cs
Labels: v6.0

#19331 RavenDB-22767 Adding caller name to a low-level transaction so we'll be able to find area causing a hanging read trasanaction more easily if it happens
  src/Raven.Server/Documents/Handlers/Debugging/TransactionDebugHandler.cs
  src/Raven.Server/Documents/Indexes/QueryOperationContext.cs
  src/Raven.Server/ServerWide/Context/TransactionOperationContext.cs
  src/Voron/Impl/LowLevelTransaction.cs
Labels: v5.4

#19338 RavenDB-22628 If you make a mistake with 2FA code, it will only work in a new window
  src/Raven.Server/RavenServer.cs
Labels: v6.0

#19326 RavenDB-22412 Striped background for partially online databases
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/DatabasePanel.tsx
  src/Raven.Studio/wwwroot/Content/scss/_bs5extend.scss
Labels: v6.0, Studio

#19347 RavenDB-22942 Add export and import indexes to omni search
  src/Raven.Studio/typescript/common/shell/menu/items/indexes.ts
Labels: Studio, v6.2

#19332 RavenDB-22906 - SlowTests.Issues.RavenDB_17702.InsertOldSegmentAfterDeletionProblem1(options: DatabaseMode = Single , SearchEngineMode = Lucene)
  src/Raven.Server/Documents/TimeSeries/TimeSeriesStorage.cs
  test/SlowTests/Issues/RavenDB-17702.cs
Labels: v5.4

#19350 RavenDB-22961 Fix RadioToggle disabled state
  src/Raven.Studio/typescript/components/common/Toggles.scss
Labels: v6.0, Studio
