Repository ravendb/ravendb, pull requests merged in 2024-12, with the labels that each got.

#19683 RavenDB-23129 Making sure that JournalReader.Complete is always called so we'll unmap file mappings when using 32-bits pagers
  src/Voron/Impl/Backup/IncrementalBackup.cs
  src/Voron/Impl/Journal/JournalReader.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
Labels: v7.0

#19668 RavenDB-22265 Audit log on client certificates management operations
  src/Raven.Server/Web/Authentication/AdminCertificatesHandler.cs
Labels: v5.4

#19691 RavenDB-22996 Fix virtual grid flicking
  src/Raven.Studio/typescript/test/mocks/services/MockDatabasesService.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/virtualGrid.ts
Labels: v6.0, Studio

#19687 RavenDB-23130 / RavenDB-23152 Fixing occasionally failing JavaScriptIndexTests.CanAllowStringCompilation test
  test/FastTests/Server/Documents/Indexing/Static/JavaScriptIndexTests.cs
Labels: v6.0

#19690 RavenDB-23192 Create database wizard doesn't refresh required wizard steps after enabling & disabling Sharding
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/create/regular/steps/CreateDatabaseRegularStepReplicationAndSharding.tsx
Labels: Studio, v6.2

#19692 RavenDB-23098 Fixing ocassionally failing test due to replacing an index and getting index errors concurrently
  test/SlowTests/Corax/RavenDB_22811.cs
Labels: v6.2

#19711 5.4 to 6.0 merge
  src/Raven.Client/Documents/Session/IAsyncSessionDocumentTimeSeries.cs
  src/Raven.Server/Documents/CountersRepairTask.cs
  src/Raven.Server/Documents/CountersStorage.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Handlers/CountersHandler.cs
  src/Raven.Server/ServerWide/Commands/ClusterTransactionCommand.cs
  src/Raven.Server/Web/Authentication/AdminCertificatesHandler.cs
  src/Voron/Impl/Transaction.cs
  test/SlowTests/Client/TimeSeries/Session/TimeSeriesSessionTests.cs
  test/SlowTests/Client/TimeSeries/Session/TimeSeriesStreamingTests.cs
  test/SlowTests/Cluster/ClusterTransactionTests.cs
  test/SlowTests/Issues/RavenDB_22835.cs
Labels: v6.0

#19719 RavenDB-23290 avoid issue with different ex message being generated when current culture is not invariant
  test/SlowTests/Cluster/ClusterTransactionTests.cs
Labels: v5.4

#19718 6.2 to 7.0 merge
  src/Corax/Querying/Matches/SortingMatches/NumericalMaxHeapSorter.cs
  src/Corax/Querying/Matches/SortingMatches/TextualMaxHeapSorter.cs
  src/Raven.Client/Documents/Operations/Counters/CounterBatch.cs
  src/Raven.Client/Documents/Operations/TimeSeries/TimeSeriesOperation.cs
  src/Raven.Client/Documents/Operations/TimeSeries/TimeSeriesRange.cs
  src/Raven.Client/Documents/Session/IAsyncSessionDocumentTimeSeries.cs
  src/Raven.Server/Documents/CountersRepairTask.cs
  src/Raven.Server/Documents/CountersStorage.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Handlers/CountersHandler.cs
  src/Raven.Server/ServerWide/Commands/ClusterTransactionCommand.cs
  src/Raven.Server/Web/Authentication/AdminCertificatesHandler.cs
  src/Raven.Studio/typescript/commands/database/documents/getRevisionsBinEntryCommand.ts
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/create/regular/steps/CreateDatabaseRegularStepReplicationAndSharding.tsx
  src/Raven.Studio/typescript/widgets/virtualGrid/virtualGrid.ts
  src/Voron/Impl/Transaction.cs
  test/FastTests/Corax/Bugs/RavenDB_23245.cs
  test/FastTests/Server/Documents/Indexing/Static/JavaScriptIndexTests.cs
  test/SlowTests/Client/TimeSeries/Session/TimeSeriesSessionTests.cs
  test/SlowTests/Client/TimeSeries/Session/TimeSeriesStreamingTests.cs
  test/SlowTests/Cluster/ClusterTransactionTests.cs
  test/SlowTests/Corax/RavenDB_22811.cs
  test/SlowTests/Issues/RavenDB_22835.cs
Labels: v7.0

#19723 RavenDB-7070 bumped version from 6.2 to 7.0
  .github/workflows/FastTests.yml
  .github/workflows/StudioTests.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/studioConventions.yml
  SECURITY.md
  docker/common.ps1
  docker/compose/linux-cluster/docker-compose.yml
  docker/compose/win-cluster/docker-compose.yml
  docker/debug/build-ubuntu-debug.ps1
  docker/debug/ravendb-ubuntu-debug/Dockerfile
  docker/manifest/manifest.yml
  docker/readme.md
  docker/run-linux.ps1
  docker/run-nanoserver.ps1
  docs/readme.linux.txt
  docs/readme.windows.txt
  readme.md
  scripts/certificates/powershell/dev-create-authenticated-cluster-with-subdomains.ps1
  scripts/certificates/powershell/dev-create-authenticated-cluster.ps1
  scripts/raspberry-pi/setup.sh
  scripts/raspberry-pi/start.sh
  scripts/updateSourceWithBuildInfo.ps1
  scripts/version.ps1
  src/CommonAssemblyInfo.cs
  src/Raven.Client/DocumentationUrls.cs
  src/Raven.Client/Documents/Operations/Revisions/EnforceRevisionsConfigurationOperation.cs
  src/Raven.Client/Properties/VersionInfo.cs
  src/Raven.Embedded/Raven.Embedded.nuspec.template
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxDocumentConverterBase.cs
  src/Raven.Server/Monitoring/Snmp/Templates/zabbix_ravendb_template.xml
  src/Raven.Server/NotificationCenter/Indexing.cs
  src/Raven.Server/Program.cs
  src/Raven.Server/RavenServer.cs
  src/Raven.Studio/typescript/commands/commandBase.ts
Labels: v7.0

#19725 RavenDB-7070 more adjustments after version bump
  docker/common.ps1
  src/Raven.Server/ServerWide/ServerVersion.cs
  src/Raven.Studio/wwwroot/version.txt
Labels: v7.0

#19724 RavenDB-7070 bumped version from 7.0 to 7.1
  .github/workflows/FastTests.yml
  .github/workflows/StudioTests.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/studioConventions.yml
  SECURITY.md
  docker/common.ps1
  docker/compose/linux-cluster/docker-compose.yml
  docker/compose/win-cluster/docker-compose.yml
  docker/debug/build-ubuntu-debug.ps1
  docker/debug/ravendb-ubuntu-debug/Dockerfile
  docker/manifest/manifest.yml
  docker/readme.md
  docker/run-linux.ps1
  docker/run-nanoserver.ps1
  docs/readme.linux.txt
  docs/readme.windows.txt
  readme.md
  scripts/certificates/powershell/dev-create-authenticated-cluster-with-subdomains.ps1
  scripts/certificates/powershell/dev-create-authenticated-cluster.ps1
  scripts/raspberry-pi/setup.sh
  scripts/raspberry-pi/start.sh
  scripts/updateSourceWithBuildInfo.ps1
  scripts/version.ps1
  src/CommonAssemblyInfo.cs
  src/Raven.Client/DocumentationUrls.cs
  src/Raven.Client/Properties/VersionInfo.cs
  src/Raven.Embedded/Raven.Embedded.nuspec.template
  src/Raven.Server/Monitoring/Snmp/Templates/zabbix_ravendb_template.xml
  src/Raven.Server/Program.cs
  src/Raven.Server/RavenServer.cs
  src/Raven.Server/ServerWide/ServerVersion.cs
  src/Raven.Studio/typescript/commands/commandBase.ts
  src/Raven.Studio/wwwroot/version.txt
Labels: v7.1

#19729 RavenDB-7070 more fixes after version bump
  src/Raven.Server/Documents/Handlers/Processors/Smuggler/AbstractSmugglerHandlerProcessor.cs
  src/Raven.Server/Smuggler/Documents/Processors/BuildVersion.cs
  src/Raven.Server/Smuggler/Documents/Processors/IndexProcessor.cs
  src/Raven.Server/Smuggler/Documents/SmugglerBase.cs
Labels: v7.0

#19731 RavenDB-22978 updated Jint to 4.1.0
  Directory.Packages.props
  src/Raven.Server/Documents/Indexes/Static/AcornimaReferencedCollectionVisitor.cs
  src/Raven.Server/Documents/Indexes/Static/AcornimaVisitor.cs
  src/Raven.Server/Documents/Indexes/Static/JavaScript/AttachmentNameObjectInstance.cs
  src/Raven.Server/Documents/Indexes/Static/JavaScript/AttachmentObjectInstance.cs
  src/Raven.Server/Documents/Indexes/Static/JavaScriptIndex.cs
  src/Raven.Server/Documents/Indexes/Static/JavaScriptIndexUtils.cs
  src/Raven.Server/Documents/Indexes/Static/JavaScriptMapOperation.cs
  src/Raven.Server/Documents/Indexes/Static/JavaScriptReduceOperation.cs
  src/Raven.Server/Documents/Patch/JavaScriptUtils.cs
  src/Raven.Server/Documents/Patch/ScriptRunner.cs
  src/Raven.Server/Documents/Queries/AST/Query.cs
  src/Raven.Server/Documents/Queries/HasSpecialMethodVisitor.cs
  src/Raven.Server/Documents/Queries/Parser/QueryParser.cs
  src/Raven.Server/Documents/Queries/QueryMetadata.cs
  src/Raven.Server/Documents/TcpHandlers/SubscriptionConnection.cs
  src/Raven.Server/Extensions/JintExtensions.cs
  test/SlowTests/Client/Indexing/TimeSeries/BasicTimeSeriesIndexes_JavaScript.cs
  test/SlowTests/Issues/RavenDB-16031.cs
  test/SlowTests/Issues/RavenDB-8213.cs
  test/SlowTests/Issues/RavenDB_16293.cs
  test/SlowTests/Issues/RavenDB_20059.cs
  test/SlowTests/Server/Documents/DataArchival/DataArchivalIndexingTests.cs
  test/SlowTests/Server/Documents/ETL/Olap/AzureTests.cs
  test/SlowTests/Server/Documents/ETL/Olap/GoogleCloudTests.cs
  test/SlowTests/Server/Documents/ETL/Olap/LocalTests.cs
  test/SlowTests/Server/Documents/ETL/Olap/S3Tests.cs
  test/SlowTests/Sharding/ETL/ShardedEtlTests.cs
Labels: v7.0

#19730 RavenDB-22977 removed obsoletes
  src/Raven.Client/Documents/Commands/GetDocumentsResult.cs
  src/Raven.Client/Documents/Identity/GenerateEntityIdOnTheClient.cs
  src/Raven.Client/Documents/Session/AsyncDocumentSession.cs
  src/Raven.Client/Documents/Session/DocumentSession.cs
  src/Raven.Client/Documents/Session/InMemoryDocumentSessionOperations.cs
  src/Raven.Embedded/ServerOptions.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Highlightings/FastVectorHightlighter/BaseFragmentsBuilder.cs
  src/Sparrow/LowMemory/MemoryInfoResult.cs
Labels: v7.0

#19748 RavenDB-7070 fix FullVersion update in build scripts
  docker/ravendb-ubuntu/run-raven.sh
  docker/readme.md
Labels: v7.0

#19751 7.0 to 7.1 merge
  src/Raven.Client/Documents/Operations/Revisions/EnforceRevisionsConfigurationOperation.cs
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxDocumentConverterBase.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesStats.cs
  src/Raven.Server/NotificationCenter/Indexing.cs
  src/Raven.Server/Smuggler/Documents/Processors/BuildVersion.cs
  src/Raven.Studio/typescript/components/pages/database/settings/connectionStrings/EditConnectionStrings.tsx
  test/Tests.Infrastructure/RavenFactAttribute.cs
  test/Tests.Infrastructure/RavenRetryFactAttribute.cs
  test/Tests.Infrastructure/RavenRetryTheoryAttribute.cs
  test/Tests.Infrastructure/RavenTheoryAttribute.cs
  test/Tests.Infrastructure/SnowflakeHelper.cs
Labels: v7.1

#19750 RavenDB-23269 Cannot fix the 2FA code using Backspace
  src/Raven.Studio/typescript/viewmodels/twoFactorShell.ts
  src/Raven.Studio/wwwroot/App/views/twoFactorShell.html
Labels: v5.4, Studio

#19745 RavenDB-23298 : fix failing test
  test/SlowTests/Issues/RavenDB_22835.cs
Labels: v5.4

#19743 RavenDB-23065 - Don't use StreamWithTimeout for substreams
  src/Raven.Server/Web/RequestHandler.cs
Labels: v5.4

#19735 RavenDB-21964 - add debug info
  test/SlowTests/Client/Subscriptions/ConcurrentSubscriptionsTests.cs
Labels: v5.4

#19733 RavenDB-23171 avoid creating database for server only operations
  src/Raven.Server/ServerWide/ServerStore.cs
  test/SlowTests/Authentication/AuthenticationLetsEncryptTests.cs
Labels: v5.4

#19726 RavenDB-23111 Added managed heap sizes after last GC to /admin/debug/memory/stats endpoint
  src/Raven.Server/Documents/Handlers/Debugging/MemoryDebugHandler.cs
Labels: v5.4

#19639 RavenDB-23183 - Ensure the cached items are cleared before returning the array to the ArrayPool
  src/Raven.Client/Documents/Commands/MultiGet/MultiGetCommand.cs
  test/StressTests/Client/MultiGet.cs
Labels: v5.4

#19744 RavenDB-23207 fix test LastSetStateDetermineTheStateAutoMapIndex
  test/SlowTests/Issues/RavenDB-20922.cs
Labels: v7.1

#19749 RavenDB-23307 Mock scrollWidth and scrollHeight
  src/Raven.Studio/scripts/setup_jest.js
  src/Raven.Studio/typescript/components/pages/database/settings/tombstones/TombstonesState.spec.tsx
Labels: v6.0, Studio

#19650 RavenDB-23081: Improved parsing of QueryStringParameters.
  src/Raven.Server/Documents/Handlers/Processors/Batches/AbstractBatchHandlerProcessorForBulkDocs.cs
  src/Raven.Server/Documents/Handlers/Processors/Documents/AbstractDocumentHandlerProcessorForGet.cs
  src/Raven.Server/Documents/Handlers/Processors/Queries/AbstractQueriesHandlerProcessorForGet.cs
  src/Raven.Server/Web/AbstractQueryStringParameters.cs
Labels: v6.2

#19758 RavenDB-19445 Fixing concurrency issue in RavenDB_16942.ByteStringContext_Should_Reuse_When_Large_Allocations_Are_Requested test
  test/FastTests/Issues/RavenDB_16942.cs
Labels: v5.4

#19753 RavenDB-23215 Always show 'All revisions' and 'Revisions bin' menu items
  src/Raven.Studio/typescript/common/helpers/database/collectionsTracker.ts
Labels: Studio, v7.0

#19760 RavenDB-23321 Add curly and react/jsx-curly-brace-presence eslint rules
  .git-blame-ignore-revs
  src/Raven.Studio/.eslintrc.js
  src/Raven.Studio/typescript/common/abstractWebSocketClient.ts
  src/Raven.Studio/typescript/common/appUrl.ts
  src/Raven.Studio/typescript/common/bindingHelpers/aceEditorBindingHandler.ts
  src/Raven.Studio/typescript/common/defaultAceCompleter.ts
  src/Raven.Studio/typescript/common/generalUtils.ts
  src/Raven.Studio/typescript/common/helpers/database/documentHelpers.ts
  src/Raven.Studio/typescript/common/inputCursor.ts
  src/Raven.Studio/typescript/common/queryUtil.ts
  src/Raven.Studio/typescript/common/shell/databaseSwitcher.ts
  src/Raven.Studio/typescript/common/storage/savedPatchesStorage.ts
  src/Raven.Studio/typescript/common/storage/savedQueriesStorage.ts
  src/Raven.Studio/typescript/components/common/AboutView.stories.tsx
  src/Raven.Studio/typescript/components/common/customAnalyzers/DeleteCustomAnalyzerConfirm.tsx
  src/Raven.Studio/typescript/components/common/customSorters/DeleteCustomSorterConfirm.tsx
  src/Raven.Studio/typescript/components/common/formDestinations/Local.tsx
  src/Raven.Studio/typescript/components/common/steps/Steps.stories.tsx
  src/Raven.Studio/typescript/components/pages/BootstrapPlaygroundPage.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/list/migration/export/ExportIndexes.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/list/migration/import/ImportIndexes.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/shared/DeleteIndexesConfirmBody.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/databaseRecord/DatabaseRecordAboutView.tsx
  src/Raven.Studio/typescript/components/pages/resources/about/partials/RequestSupportModal.tsx
  src/Raven.Studio/typescript/models/database/cluster/addClusterNodeModel.ts
  src/Raven.Studio/typescript/models/database/documents/collectionsStats.ts
  src/Raven.Studio/typescript/models/resources/clusterDashboard/lineChart.ts
  src/Raven.Studio/typescript/viewmodels/common/validationHelpers.ts
  src/Raven.Studio/typescript/viewmodels/database/cmpXchg/editCmpXchg.ts
  src/Raven.Studio/typescript/viewmodels/database/documents/editDocument.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/editIndex.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexPerformance.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/visualizer/visualizerGraphDetails.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/visualizer/visualizerGraphGlobal.ts
  src/Raven.Studio/typescript/viewmodels/database/patch/docsIdsBasedOnQueryFetcher.ts
  src/Raven.Studio/typescript/viewmodels/database/query/query.ts
  src/Raven.Studio/typescript/viewmodels/database/settings/timeSeries.ts
  src/Raven.Studio/typescript/viewmodels/database/status/ongoingTasksStats.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/destinations/ftpSettings.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editOlapEtlTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editPeriodicBackupTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editSubscriptionTask.ts
  src/Raven.Studio/typescript/viewmodels/manage/assignCores.ts
  src/Raven.Studio/typescript/viewmodels/manage/editServerWideBackup.ts
  src/Raven.Studio/typescript/viewmodels/partial/columnsSelector.ts
  src/Raven.Studio/typescript/viewmodels/resources/addNewShardToDatabaseGroup.ts
  src/Raven.Studio/typescript/viewmodels/resources/widgets/abstractTransformingChartsWebsocketWidget.ts
  src/Raven.Studio/typescript/viewmodels/resources/widgets/ongoingTasksWidget.ts
Labels: v6.0

#19752 5.4 to 6.0 merge
  src/Raven.Client/Documents/Commands/MultiGet/MultiGetCommand.cs
  src/Raven.Client/Documents/Session/Loaders/IncludeBuilder.cs
  src/Raven.Server/Documents/Handlers/Debugging/MemoryDebugHandler.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterMaintenanceSupervisor.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterMaintenanceWorker.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Web/RequestHandler.cs
  src/Raven.Studio/typescript/viewmodels/database/documents/editDocumentConnectedDocuments.ts
  src/Raven.Studio/typescript/viewmodels/twoFactorShell.ts
  src/Raven.Studio/wwwroot/App/views/twoFactorShell.html
  test/SlowTests/Authentication/AuthenticationLetsEncryptTests.cs
  test/SlowTests/Client/Subscriptions/ConcurrentSubscriptionsTests.cs
  test/SlowTests/Cluster/CompareExchangeTests.cs
  test/SlowTests/Issues/RavenDB-17650.cs
  test/SlowTests/Issues/RavenDB-22959.cs
  test/SlowTests/Issues/RavenDB_22835.cs
  test/StressTests/Client/MultiGet.cs
  test/Tests.Infrastructure/RavenTestBase.cs
Labels: v6.0

#19762 release/5.4 to 5.4 merge
  src/CommonAssemblyInfo.cs
  src/Raven.Client/Properties/VersionInfo.cs
  src/Raven.Server/Documents/Indexes/Workers/Counters/HandleCompareExchangeCountersReferences.cs
  src/Raven.Server/Documents/Indexes/Workers/Counters/HandleCountersReferences.cs
  src/Raven.Server/Documents/Indexes/Workers/HandleNotNormalizedCompareExchangeReferences.cs
  src/Raven.Server/Documents/Indexes/Workers/HandleNotNormalizedDocumentReferences.cs
  src/Raven.Server/Documents/Indexes/Workers/HandleReferences.cs
  src/Raven.Server/Documents/Indexes/Workers/TimeSeries/HandleCompareExchangeTimeSeriesReferences.cs
  src/Raven.Server/Documents/Indexes/Workers/TimeSeries/HandleTimeSeriesReferences.cs
  src/Raven.Studio/typescript/viewmodels/shell/registration.ts
  test/SlowTests/Issues/RavenDB-15754.cs
Labels: v5.4

#19763 release/6.0 to 6.0 merge
  src/CommonAssemblyInfo.cs
  src/Raven.Client/Properties/VersionInfo.cs
  src/Raven.Server/Documents/Indexes/Workers/Counters/HandleCompareExchangeCountersReferences.cs
  src/Raven.Server/Documents/Indexes/Workers/Counters/HandleCountersReferences.cs
  src/Raven.Server/Documents/Indexes/Workers/HandleNotNormalizedCompareExchangeReferences.cs
  src/Raven.Server/Documents/Indexes/Workers/HandleNotNormalizedDocumentReferences.cs
  src/Raven.Server/Documents/Indexes/Workers/HandleReferences.cs
  src/Raven.Server/Documents/Indexes/Workers/TimeSeries/HandleCompareExchangeTimeSeriesReferences.cs
  src/Raven.Server/Documents/Indexes/Workers/TimeSeries/HandleTimeSeriesReferences.cs
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexPanel.tsx
  src/Raven.Studio/typescript/components/utils/IndexUtils.ts
  src/Raven.Studio/typescript/viewmodels/shell/registration.ts
  test/SlowTests/Issues/RavenDB-15754.cs
Labels: v6.0

#19764 release/6.2 to 6.2 merge
  src/CommonAssemblyInfo.cs
  src/Raven.Client/Properties/VersionInfo.cs
  src/Raven.Server/Documents/Indexes/Workers/Counters/HandleCompareExchangeCountersReferences.cs
  src/Raven.Server/Documents/Indexes/Workers/Counters/HandleCountersReferences.cs
  src/Raven.Server/Documents/Indexes/Workers/HandleNotNormalizedCompareExchangeReferences.cs
  src/Raven.Server/Documents/Indexes/Workers/HandleNotNormalizedDocumentReferences.cs
  src/Raven.Server/Documents/Indexes/Workers/HandleReferences.cs
  src/Raven.Server/Documents/Indexes/Workers/TimeSeries/HandleCompareExchangeTimeSeriesReferences.cs
  src/Raven.Server/Documents/Indexes/Workers/TimeSeries/HandleTimeSeriesReferences.cs
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexPanel.tsx
  src/Raven.Studio/typescript/components/utils/IndexUtils.ts
  src/Raven.Studio/typescript/viewmodels/shell/registration.ts
  test/SlowTests/Issues/RavenDB-15754.cs
Labels: v6.2

#19759 RavenDB-23188 Fix Non-Consistent noCaching Behavior
  src/Raven.Client/Http/RavenCommand.cs
  src/Raven.Client/Http/RequestExecutor.cs
  test/SlowTests/Issues/RavenDB-23188.cs
Labels: v5.4

#19770 RavenDB-17761 - Failing test SlowTests.Server.Replication.ExternalReplicationTests.RavenDB_17187_CheckInternalShowsInStats
  test/SlowTests/Server/Replication/ExternalReplicationTests.cs
Labels: v6.2

#19767 RavenDB-17678 Support export time series query results to CSV
  src/Raven.Server/Documents/Handlers/StreamCsvBlittableQueryResultWriter.cs
  src/Raven.Server/Documents/Handlers/StreamCsvDocumentQueryResultWriter.cs
  src/Raven.Server/Documents/Handlers/StreamCsvResultWriter.cs
  src/Raven.Server/Documents/Handlers/TimeSeriesCsvWriter.cs
  src/Raven.Server/Documents/Queries/Results/QueryResultRetrieverBase.cs
  test/SlowTests/Issues/RavenDB_17678.cs
  test/SlowTests/Issues/RavenDB_9519.cs
Labels: v5.4

#19772 RavenDB-23279 Run Snowflake tests only nightly
  test/SlowTests/Server/Documents/ETL/Snowflake/SnowflakeEtlTests.cs
  test/Tests.Infrastructure/RequiresSnowflakeFactAttribute.cs
  test/Tests.Infrastructure/RequiresSnowflakeRetryFactAttribute.cs
  test/Tests.Infrastructure/RequiresSnowflakeRetryTheoryAttribute.cs
Labels: v7.1

#19779 6.0 to 6.2 merge
  test/SlowTests/Issues/RavenDB-17650.cs
Labels: v6.2

#19785 RavenDB-23340 Adjust deb scripts for .Net 9, set default version
  scripts/linux/pkg/deb/assets/build.sh
  scripts/linux/pkg/deb/build-deb.ps1
  scripts/linux/pkg/deb/set-raven-version-env.ps1
Labels: v7.0

#19783 RavenDB-19410 Using GUID instead of Random to create the key for test
  test/SlowTests/Cluster/CompareExchangeExpirationTest.cs
Labels: v5.4

#19781 RavenDB-23214 Expose developer license on About
  src/Raven.Studio/wwwroot/App/views/shell/about.html
  src/Raven.Studio/wwwroot/Content/css/bootstrap/type.less
Labels: v5.4, Studio

#19794 RavenDB-23178 fix (cv should be copied to the clipboard exactly as re…
  src/Raven.Studio/typescript/components/pages/database/status/statistics/partials/DetailedDatabaseStats.tsx
  src/Raven.Studio/typescript/viewmodels/database/documents/editDocument.ts
Labels: v6.0, Studio

#19782 RavenDB-23345 Fix width of RichAlert component to always have 100%
  src/Raven.Studio/typescript/components/common/RichAlert.tsx
Labels: v6.0, Studio

#19790 RavenDB-23353 allow to load any certificate in the UpdatePullReplicationAsSinkOperation, we are performing the validation ourselves
  src/Raven.Client/Documents/Operations/Replication/UpdatePullReplicationAsSinkOperation.cs
  test/StressTests/Issues/RavenDB-15145.cs
Labels: v7.0

#19800 5.4 to 6.0 merge
  src/Raven.Studio/wwwroot/App/views/shell.html
  src/Raven.Studio/wwwroot/Content/css/bootstrap/badges.less
  src/Raven.Studio/wwwroot/Content/css/bootstrap/buttons.less
  src/Raven.Studio/wwwroot/Content/css/bootstrap/type.less
  src/Raven.Studio/wwwroot/Content/css/bootstrap/variables-body.less
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon/community.svg
  test/SlowTests/Cluster/CompareExchangeExpirationTest.cs
Labels: v6.0

#19803 6.0 to 6.2 merge
  src/Raven.Client/Documents/Session/Operations/StreamOperation.cs
  src/Raven.Server/Documents/Handlers/Processors/Streaming/AbstractStreamingHandlerProcessorForGetStreamQuery.cs
  src/Raven.Server/Documents/Handlers/Processors/Streaming/StreamingHandlerProcessorForGetStreamQuery.cs
  src/Raven.Server/Documents/Handlers/StreamCsvResultWriter.cs
  src/Raven.Server/Documents/Handlers/StreamJsonFileBlittableQueryResultWriter.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Queries/ShardedStreamQueryCsvResult.cs
  src/Raven.Server/Documents/Queries/StreamDocumentIndexQueryResult.cs
  src/Raven.Server/Documents/Queries/StreamJsonlBlittableQueryResultWriter.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Streaming/ShardedStreamingHandlerProcessorForGetStreamQuery.cs
  src/Raven.Server/Documents/Sharding/Queries/ShardedQueryResultDocument.cs
  src/Raven.Server/Documents/Sharding/Queries/ShardedQueryStreamProcessor.cs
  src/Raven.Studio/typescript/components/common/AboutView.scss
  src/Raven.Studio/typescript/components/common/FeatureAvailabilitySummary.spec.tsx
  src/Raven.Studio/typescript/components/common/FeatureAvailabilitySummary.tsx
  src/Raven.Studio/typescript/components/common/HrHeader.tsx
  src/Raven.Studio/typescript/components/common/RichAlert.tsx
  src/Raven.Studio/typescript/components/common/select/Select.stories.tsx
  src/Raven.Studio/typescript/components/common/select/Select.tsx
  src/Raven.Studio/typescript/components/common/select/SelectCreatable.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/documentRevisions/DocumentRevisions.spec.tsx
  src/Raven.Studio/typescript/components/pages/database/status/statistics/partials/DetailedDatabaseStats.tsx
  src/Raven.Studio/typescript/components/pages/resources/about/AboutPage.spec.tsx
  src/Raven.Studio/typescript/components/pages/resources/about/AboutPage.tsx
  src/Raven.Studio/typescript/components/pages/resources/about/partials/LicenseDetails.tsx
  src/Raven.Studio/typescript/viewmodels/database/documents/editDocument.ts
  src/Raven.Studio/wwwroot/App/views/shell.html
  src/Raven.Studio/wwwroot/Content/css/bootstrap/badges.less
  src/Raven.Studio/wwwroot/Content/css/bootstrap/buttons.less
  src/Raven.Studio/wwwroot/Content/css/bootstrap/type.less
  src/Raven.Studio/wwwroot/Content/css/bootstrap/variables-body.less
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon/community.svg
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon/console.svg
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon/support.svg
  src/Raven.Studio/wwwroot/Content/img/pages/about/support.svg
  test/SlowTests/Cluster/CompareExchangeExpirationTest.cs
  test/SlowTests/Issues/RDBC_622.cs
  test/SlowTests/Issues/RavenDB_16050.cs
  test/SlowTests/Tests/TestsInheritanceTests.cs
Labels: v6.2

#19802 RavenDB-23370: Update benchmarks to .Net 9.0
  Directory.Packages.props
  bench/Micro.Benchmark/Benchmarks/BatchedIntegerEncoding.cs
  bench/Micro.Benchmark/Benchmarks/Dictionary.cs
  bench/Micro.Benchmark/Benchmarks/Hardware/Compare.cs
  bench/Micro.Benchmark/Benchmarks/Hardware/Diff.cs
  bench/Micro.Benchmark/Benchmarks/Hardware/Prefetch.cs
  bench/Micro.Benchmark/Benchmarks/Hardware/Prefetch2.cs
  bench/Micro.Benchmark/Benchmarks/Hardware/Search.cs
  bench/Micro.Benchmark/Benchmarks/Hashing.XXHash32.cs
  bench/Micro.Benchmark/Benchmarks/Hashing.XXHash64.cs
  bench/Micro.Benchmark/Benchmarks/HopeEncoder.cs
  bench/Micro.Benchmark/Benchmarks/IntegerEncoding.cs
  bench/Micro.Benchmark/Benchmarks/LZ4/LZ4Benchmark.cs
  bench/Micro.Benchmark/Benchmarks/PageLocator/PlRandomRead.cs
  bench/Micro.Benchmark/Benchmarks/PageLocator/PlRandomWrite.cs
  bench/Micro.Benchmark/Benchmarks/PointerBenchmarks.cs
  bench/Micro.Benchmark/Benchmarks/Sorting/Sorting.cs
  bench/Micro.Benchmark/Benchmarks/TypeCache.cs
  bench/Micro.Benchmark/Benchmarks/Zstd/ZstdBenchmark.cs
  bench/Micro.Benchmark/Benchmarks/Zstd/ZstdPageBenchmark.cs
  bench/Micro.Benchmark/Program.cs
  bench/ServerStoreTxMerger.Benchmark/ServerStoreTxMerger.Benchmark.csproj
  tools/Raven.Debug/Raven.Debug.csproj
Labels: v7.0

#19793 RavenDB-23190 Enable/disable ongoing task is visible only after hard refresh
  src/Raven.Studio/typescript/components/pages/database/tasks/ongoingTasks/OngoingTasksReducer.ts
Labels: Studio, v6.2

#19805 6.2 to 7.0 merge
  src/Raven.Client/Documents/Session/Operations/StreamOperation.cs
  src/Raven.Server/Commercial/LetsEncrypt/RavenDnsRecordHelper.cs
  src/Raven.Server/Commercial/LetsEncrypt/SettingsZipFileHelper.cs
  src/Raven.Server/Documents/Handlers/Processors/Streaming/AbstractStreamingHandlerProcessorForGetStreamQuery.cs
  src/Raven.Server/Documents/Handlers/Processors/Streaming/StreamingHandlerProcessorForGetStreamQuery.cs
  src/Raven.Server/Documents/Handlers/StreamCsvResultWriter.cs
  src/Raven.Server/Documents/Handlers/StreamJsonFileBlittableQueryResultWriter.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Queries/ShardedStreamQueryCsvResult.cs
  src/Raven.Server/Documents/Queries/StreamDocumentIndexQueryResult.cs
  src/Raven.Server/Documents/Queries/StreamJsonlBlittableQueryResultWriter.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Streaming/ShardedStreamingHandlerProcessorForGetStreamQuery.cs
  src/Raven.Server/Documents/Sharding/Queries/ShardedQueryResultDocument.cs
  src/Raven.Server/Documents/Sharding/Queries/ShardedQueryStreamProcessor.cs
  src/Raven.Studio/typescript/components/common/AboutView.scss
  src/Raven.Studio/typescript/components/common/FeatureAvailabilitySummary.spec.tsx
  src/Raven.Studio/typescript/components/common/FeatureAvailabilitySummary.tsx
  src/Raven.Studio/typescript/components/common/HrHeader.tsx
  src/Raven.Studio/typescript/components/common/Icon.stories.tsx
  src/Raven.Studio/typescript/components/common/RichAlert.tsx
  src/Raven.Studio/typescript/components/common/select/Select.stories.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/documentRevisions/DocumentRevisions.spec.tsx
  src/Raven.Studio/typescript/components/pages/database/status/statistics/partials/DetailedDatabaseStats.tsx
  src/Raven.Studio/typescript/components/pages/resources/about/AboutPage.spec.tsx
  src/Raven.Studio/typescript/components/pages/resources/about/AboutPage.tsx
  src/Raven.Studio/typescript/components/pages/resources/about/partials/LicenseDetails.tsx
  src/Raven.Studio/typescript/viewmodels/database/documents/editDocument.ts
  src/Raven.Studio/wwwroot/App/views/shell.html
  src/Raven.Studio/wwwroot/Content/css/bootstrap/badges.less
  src/Raven.Studio/wwwroot/Content/css/bootstrap/buttons.less
  src/Raven.Studio/wwwroot/Content/css/bootstrap/type.less
  src/Raven.Studio/wwwroot/Content/css/bootstrap/variables-body.less
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon/community.svg
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon/console.svg
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon/support.svg
  src/Raven.Studio/wwwroot/Content/img/pages/about/support.svg
  test/SlowTests/Cluster/CompareExchangeExpirationTest.cs
  test/SlowTests/Issues/RDBC_622.cs
  test/SlowTests/Issues/RavenDB_16050.cs
  test/SlowTests/Tests/TestsInheritanceTests.cs
Labels: v7.0

#19801 RavenDB-23104 - print idle explanation in test
  test/SlowTests/Server/Replication/PullReplicationTests.cs
Labels: v5.4

#19816 RavenDB-20465 fix tooltip
  src/Raven.Studio/typescript/components/pages/database/settings/studioConfiguration/StudioDatabaseConfiguration.tsx
Labels: v6.0, Studio

#19809 RavenDB-22287 switch TimeoutManager to Task.Delay on low core instances
  src/Sparrow/Utils/TimeoutManager.cs
Labels: v6.2

#19821 RavenDB-22287 switch TimeoutManager to Task.Delay on low core instances
  src/Sparrow/Utils/TimeoutManager.cs
Labels: v6.2

#19810 RavenDB-23391 switched default http compression algorithm to zstd and enabled bulk insert compression by default
  src/Raven.Client/Documents/BulkInsert/BulkInsertOperation.cs
  src/Raven.Client/Documents/BulkInsert/BulkInsertOptions.cs
  src/Raven.Client/Documents/Conventions/DocumentConventions.cs
Labels: v7.0

#19820 RavenDB-23367 adjust thread name
  src/Sparrow/Logging/LoggingSource.cs
Labels: v6.2

#19826 RavenDB-22689 fix test
  test/SlowTests/Issues/RavenDB-16659.cs
Labels: v5.4

#19824 RavenDB-23059 fix test CannotDeleteDatabaseWhenRestoreCancelledOnNonR…
  test/SlowTests/Issues/RavenDB-22659.cs
Labels: v5.4

#19813 RavenDB-23348 - Increase wait for rehab timeout
  test/SlowTests/Issues/RavenDB-17650.cs
Labels: v5.4

#19812 RavenDB-23348 - Increase wait for rehab timeout
  test/SlowTests/Issues/RavenDB-17650.cs
Labels: v6.0

#19823 RavenDB-23364 Improve visibility of disabled check
  src/Raven.Studio/typescript/components/common/Check.stories.tsx
  src/Raven.Studio/typescript/components/common/Checkbox.stories.tsx
  src/Raven.Studio/typescript/components/common/Form.stories.tsx
  src/Raven.Studio/wwwroot/Content/scss/_bs5extend.scss
  src/Raven.Studio/wwwroot/Content/scss/bs5variables.scss
Labels: v6.0, Studio

#19791 RavenDB-23336 Propagate the `RequestedByUser` flag when creating statistics to ensure proper results count in Corax.
  src/Raven.Client/Documents/Linq/RavenQueryProviderProcessor.cs
  src/Raven.Client/Documents/Session/AsyncDocumentQuery.cs
  src/Raven.Client/Documents/Session/DocumentQuery.cs
  test/SlowTests/Issues/RavenDB_23336.cs
Labels: Corax, v6.0

#19828 RavenDB-7070 code cleanup
  test/Tests.Infrastructure/RavenMultiplatformFactAttribute.cs
Labels: v5.4

#19833 RavenDB-23368 Run Snowflake tests only on one platform
  test/SlowTests/Authentication/AuthenticationBasicTests.cs
  test/SlowTests/Monitoring/DiskStatsGetterTest.cs
  test/SlowTests/Server/Documents/ETL/Snowflake/SnowflakeEtlTests.cs
  test/Tests.Infrastructure/NightlyBuildMultiplatformFactAttribute.cs
  test/Tests.Infrastructure/NightlyBuildMultiplatformTheoryAttribute.cs
  test/Tests.Infrastructure/RavenMultiplatformFactAttribute.cs
  test/Tests.Infrastructure/RavenMultiplatformTheoryAttribute.cs
Labels: v7.0

#19830 5.4 to 6.0 merge
  bench/Micro.Benchmark/Benchmarks/Parsing/DateTimeParsing.cs
  src/Sparrow/Json/LazyStringParser.cs
  test/FastTests/Utils/TimeParsing.cs
  test/SlowTests/Issues/RavenDB-16659.cs
  test/SlowTests/Issues/RavenDB-22659.cs
  test/SlowTests/Server/Replication/PullReplicationTests.cs
Labels: v6.0

#19827 RavenDB-23319 double the default WorkerSamplePeriod & SupervisorSamplePeriod values
  src/Raven.Server/Config/Categories/ClusterConfiguration.cs
Labels: v5.4

#19829 RavenDB-23351 - handle long paths in EmbeddedTestBase
  test/EmbeddedTests/EmbeddedTestBase.cs
Labels: v5.4

#19834 5.4 to 6.0 merge
  src/Raven.Server/Config/Categories/ClusterConfiguration.cs
  test/EmbeddedTests/EmbeddedTestBase.cs
Labels: v6.0

#19814 RavenDB-23343 7.0 Admin Logs: Top-level dropdown Level should not allow to be set to Off
  src/Raven.Studio/typescript/components/pages/resources/manageServer/adminLogs/AdminLogs.tsx
Labels: Studio, v7.0

#19850 RavenDB-23314: skip high allocating tests on 32Bits
  test/SlowTests/Cluster/ClusterTransactionTests.cs
  test/SlowTests/Cluster/CompareExchangeTests.cs
  test/SlowTests/Tests/TestsInheritanceTests.cs
Labels: v5.4

#19854 RavenDB-23314: skip high allocating tests on 32Bits [6.0]
  test/SlowTests/Cluster/ClusterTransactionTests.cs
Labels: v6.0

#19855 6.0 to 6.2 merge
  src/Raven.Studio/typescript/components/common/virtualTable/partials/VirtualTableColumnSettings.tsx
  src/Raven.Studio/typescript/components/common/virtualTable/partials/VirtualTableHead.scss
  src/Raven.Studio/typescript/components/common/virtualTable/partials/VirtualTableHead.tsx
  test/SlowTests/Cluster/ClusterTransactionTests.cs
Labels: v6.2

#19856 6.2 to 7.0 merge
  src/Raven.Studio/typescript/components/common/virtualTable/partials/VirtualTableColumnSettings.tsx
  src/Raven.Studio/typescript/components/common/virtualTable/partials/VirtualTableHead.scss
  src/Raven.Studio/typescript/components/common/virtualTable/partials/VirtualTableHead.tsx
  test/SlowTests/Cluster/ClusterTransactionTests.cs
Labels: v7.0

#19865 7.0 to 7.1 merge
  src/Corax/Utils/VectorValue.cs
  src/Raven.Client/Documents/Linq/RavenQueryProviderProcessor.cs
  src/Raven.Server/Config/Categories/LogsConfiguration.cs
  src/Raven.Server/Documents/Handlers/Processors/Indexes/IndexHandlerProcessorForTerms.cs
  src/Raven.Server/Documents/Indexes/Auto/IndexSearchEngineHelper.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/IndexStorage.cs
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxQueryBuilder.cs
  src/Raven.Server/Documents/Indexes/Static/StaticIndexBase.cs
  src/Raven.Server/Documents/Indexes/VectorSearch/GenerateEmbeddings.cs
  src/Raven.Server/Documents/Queries/Dynamic/DynamicQueryMapping.cs
  src/Raven.Server/Documents/Queries/Dynamic/DynamicQueryRunner.cs
  src/Raven.Server/Documents/Queries/Dynamic/DynamicQueryToIndexMatcher.cs
  src/Raven.Server/Documents/Queries/QueryMetadata.cs
  src/Raven.Server/Logging/RavenLogManagerServerExtensions.cs
  src/Raven.Server/NLog.template.config
  src/Raven.Studio/typescript/components/common/ConditionalPopover.tsx
  src/Raven.Studio/typescript/components/common/virtualTable/partials/VirtualTableColumnSettings.tsx
  src/Raven.Studio/typescript/components/common/virtualTable/partials/VirtualTableHead.scss
  src/Raven.Studio/typescript/components/common/virtualTable/partials/VirtualTableHead.tsx
  src/Raven.Studio/typescript/components/pages/resources/manageServer/adminLogs/AdminLogs.tsx
  src/Raven.Studio/typescript/components/pages/resources/manageServer/adminLogs/bits/AdminLogsFilterField.tsx
  src/Raven.Studio/typescript/components/pages/resources/manageServer/adminLogs/common/adminLogsUtils.ts
  src/Raven.Studio/typescript/components/pages/resources/manageServer/adminLogs/disk/settings/AdminLogsConfigLogs.tsx
  src/Raven.Studio/typescript/components/pages/resources/manageServer/adminLogs/view/AdminLogsViewSettingsModal.tsx
  src/Raven.Studio/typescript/components/utils/common.ts
  src/Sparrow/Constants.cs
  src/Voron/Data/Graphs/Hnsw.SimilarityMethods.cs
  test/FastTests/Corax/Vectors/Int8VectorSimilarityTests.cs
  test/FastTests/Corax/Vectors/VectorAutoIndexClientApi.cs
  test/FastTests/Corax/Vectors/VectorAutoIndexDefinitionTests.cs
  test/FastTests/Corax/Vectors/VectorJavaScriptIndexing.cs
  test/FastTests/Server/Documents/Queries/Dynamic/Map/CreationOfAutoMapIndexDefinition.cs
  test/FastTests/Server/Documents/Queries/Dynamic/MapReduce/CreationOfAutoMapReduceIndexDefinition.cs
  test/FastTests/Voron/Graphs/BasicGraphs.cs
  test/SlowTests/Cluster/ClusterTransactionTests.cs
  test/SlowTests/Issues/RavenDB-14963.cs
  test/SlowTests/Issues/RavenDB-22076.cs
  test/SlowTests/Issues/RavenDB-23361.cs
  test/SlowTests/Issues/RavenDB_7919.cs
  test/SlowTests/Server/Documents/ETL/Queue/AmazonSqs/AmazonSqsEtlTests.cs
  test/SlowTests/Server/Documents/ETL/Queue/AzureQueueStorageEtlTests.cs
  test/SlowTests/Server/Documents/Queries/Dynamic/Map/MatchingAutoMapIndexesForDynamicQueries.cs
  test/SlowTests/Server/Documents/Queries/Dynamic/MapReduce/MatchingAutoMapReduceIndexesForDynamicQueries.cs
  test/SlowTests/Server/Documents/Queries/Dynamic/MapReduce/RavenDB_8075.cs
  test/SlowTests/Server/Documents/Queries/MatchingAutoMapReduceIndexesForDynamicQueriesSlow.cs
Labels: v7.1
