Repository ravendb/ravendb, pull requests merged in 2024-01, with the labels that each got.

#17932 RavenDB-21873 Fix text 2023 => 2024 (v5.4)
  src/CommonAssemblyInfo.cs
  src/Raven.Studio/wwwroot/App/views/shell/about.html
Labels: v5.4

#17933 RavenDB-21873 Fix text 2023 => 2024 (v6.0)
  src/Raven.Studio/wwwroot/App/views/shell/about.html
Labels: v6.0, Studio

#17935 RavenDB-21638 'show backup progress' does not open dialog when clicked on non-responsible node in the Studio
  src/Raven.Studio/typescript/components/pages/database/tasks/ongoingTasks/panels/PeriodicBackupPanel.tsx
Labels: v6.0, Studio

#17934 RavenDB-17686 - SlowTests.Server.Replication.ReplicationCleanTombstones.EtlTombstonesInTheCluster
  test/SlowTests/Server/Replication/ReplicationCleanTombstones.cs
Labels: v5.4

#17930 RavenDB-21749 - WhatChanged does not return old value for RemovedFiel…
  src/Raven.Client/Json/BlittableOperation.cs
  test/SlowTests/Client/WhatChangedTests.cs
Labels: v5.4

#17923 RavenDB-21799 Include indexing errors to exception message in `SlowTests.Issues.RavenDB_21668.Can_Query_Map_Reduce_Index`
  test/SlowTests/Issues/RavenDB-21668.cs
Labels: v5.4

#17941 RavenDB-21880 Some description fixes in HttpConfiguration.cs (5.4)
  src/Raven.Server/Config/Categories/HttpConfiguration.cs
Labels: v5.4

#17910 RavenDB-21867 Database settings view: Fix tooltip for server-wide keys
  src/Raven.Studio/wwwroot/App/views/database/settings/databaseSettings.html
Labels: v6.0, Studio

#17949 5.4 to 6.0 merge
  src/Raven.Client/Json/BlittableOperation.cs
  src/Raven.Server/Config/Categories/HttpConfiguration.cs
  src/Raven.Server/RavenServer.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Utils/CertificateUtils.cs
  src/Raven.Server/Utils/Cli/RavenCli.cs
  src/Raven.Server/Web/Authentication/AdminCertificatesHandler.cs
  src/Sparrow.Server/Sparrow.Server.csproj
  src/Sparrow.Server/Utils/DiskStatsGetter.cs
  src/Sparrow.Server/Utils/DiskStatsGetter/DiskStatsGetter.cs
  src/Sparrow.Server/Utils/DiskStatsGetter/DiskStatsResult.cs
  src/Sparrow.Server/Utils/DiskStatsGetter/IDiskStatsGetter.cs
  src/Sparrow.Server/Utils/DiskStatsGetter/IDiskStatsRawResult.cs
  src/Sparrow.Server/Utils/DiskStatsGetter/LinuxDiskStatsGetter.cs
  src/Sparrow.Server/Utils/DiskStatsGetter/LinuxDiskStatsRawResult.cs
  src/Sparrow.Server/Utils/DiskStatsGetter/NotImplementedDiskStatsGetter.cs
  src/Sparrow.Server/Utils/DiskStatsGetter/WindowsDiskStatsGetter.cs
  src/Sparrow.Server/Utils/DiskStatsGetter/WindowsDiskStatsRawResult.cs
  src/Sparrow.Server/Utils/DiskUtils.cs
  src/Sparrow/Platform/PlatformDetails.cs
  test/SlowTests/Client/WhatChangedTests.cs
  test/SlowTests/ExtensionPoints/ExtensionPointsTests.cs
  test/SlowTests/Issues/RavenDB-21668.cs
  test/SlowTests/Monitoring/DiskStatsGetterTest.cs
  test/SlowTests/Server/Replication/ReplicationCleanTombstones.cs
  test/Tests.Infrastructure/RequiresMySqlInlineData.cs
  tools/rvn/CommandLineApp.cs
  tools/rvn/InitSetupParams.cs
Labels: v6.0

#17953 RavenDB-19337 Upgrade to Jint 3.0.0-beta-2059
  src/Raven.Server/Documents/ETL/EtlTransformer.cs
  src/Raven.Server/Documents/ETL/Providers/OLAP/OlapDocumentTransformer.cs
  src/Raven.Server/Documents/ETL/Providers/Queue/Kafka/KafkaDocumentTransformer.cs
  src/Raven.Server/Documents/ETL/Providers/Queue/RabbitMq/RabbitMqDocumentTransformer.cs
  src/Raven.Server/Documents/ETL/Providers/Raven/RavenEtlDocumentTransformer.cs
  src/Raven.Server/Documents/ETL/Providers/SQL/SqlDocumentTransformer.cs
  src/Raven.Server/Documents/Indexes/Static/AbstractCountersAndTimeSeriesJavaScriptIndex.cs
  src/Raven.Server/Documents/Indexes/Static/JavaScript/AttachmentObjectInstance.cs
  src/Raven.Server/Documents/Indexes/Static/JavaScript/RecursiveJsFunction.cs
  src/Raven.Server/Documents/Indexes/Static/JavaScriptIndex.cs
  src/Raven.Server/Documents/Indexes/Static/JavaScriptMapOperation.cs
  src/Raven.Server/Documents/Indexes/Static/JavaScriptReduceOperation.cs
  src/Raven.Server/Documents/Indexes/Static/LazyCompressedJsString.cs
  src/Raven.Server/Documents/Indexes/Static/LazyJsString.cs
  src/Raven.Server/Documents/Patch/JavaScriptUtils.cs
  src/Raven.Server/Documents/Patch/JintNullPropagationReferenceResolver.cs
  src/Raven.Server/Documents/Patch/JsBlittableBridge.cs
  src/Raven.Server/Documents/Patch/ScriptRunner.cs
  src/Raven.Server/Extensions/JintExtensions.cs
  src/Raven.Server/Raven.Server.csproj
  test/SlowTests/Issues/RavenDB_14687.cs
  test/SlowTests/Issues/RavenDB_16346.cs
Labels: v6.0

#17962 RavenDB-19961 Retrying a test which is ocassionally failing
  test/SlowTests/Issues/RavenDB_15930.cs
Labels: v5.4

#17957 RavenDB-20555 - add the page size to the log message
  src/Raven.Server/Documents/Indexes/Persistence/IndexReadOperationBase.cs
Labels: v5.4

#17967 RavenDB-21888 Revent accidentally introduced change used for debugging
  src/Raven.Client/Http/RequestExecutor.cs
Labels: v5.4

#17965 RavenDB-21908
  src/Raven.Client/Constants.cs
  src/Raven.Server/RavenServer.cs
  src/Raven.Server/RavenServerStartup.cs
  src/Raven.Server/Routing/RequestRouter.cs
Labels: v5.4

#17961 RavenDB-21871 Support for nullable numeric values inside `InQuery`.
  src/Raven.Server/Documents/Queries/LuceneQueryHelper.cs
  test/FastTests/Client/Queries/InQuery.cs
  test/SlowTests/Tests/TestsInheritanceTests.cs
Labels: v5.4

#17963 RavenDB-21811 - Cluster wide slower performance in 6.0
  src/Raven.Server/Rachis/FollowerAmbassador.cs
Labels: v5.4

#17936 RavenDB-21874 - Can't add database ID to unused database IDs
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
  src/Voron/StorageEnvironment.cs
  test/SlowTests/Issues/RavenDB-21242.cs
Labels: v5.4

#17969 RavenDB-21888 We are not able to detect the leak of HttpCacheItem based on the finalizer.
  src/Raven.Client/Http/HttpCache.cs
Labels: v5.4

#17970 RavenDB-21920 - enforce uniqueness of Queue ETL task names
  src/Raven.Client/ServerWide/DatabaseRecord.cs
  test/SlowTests/Server/Documents/ETL/Queue/KafkaEtlTests.cs
Labels: v5.4

#17964 5.4 to 6.0 merge
  .github/pull_request_template.md
  src/Raven.Client/Documents/BulkInsert/BulkInsertOperation.cs
  src/Raven.Client/Http/HttpCache.cs
  src/Raven.Client/Http/RequestExecutor.cs
  src/Raven.Client/ServerWide/DatabaseRecord.cs
  src/Raven.Client/Util/WeakReferencingTimer.cs
  src/Raven.Server/Documents/Indexes/Persistence/IndexReadOperationBase.cs
  src/Raven.Server/Documents/Queries/LuceneQueryHelper.cs
  src/Raven.Server/Rachis/FollowerAmbassador.cs
  src/Raven.Server/RavenServer.cs
  src/Raven.Server/RavenServerStartup.cs
  src/Raven.Server/Routing/RequestRouter.cs
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
  src/Voron/StorageEnvironment.cs
  test/FastTests/Client/Queries/InQuery.cs
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
  test/SlowTests/Issues/RavenDB-21242.cs
  test/SlowTests/Issues/RavenDB_15930.cs
  test/SlowTests/Server/Documents/ETL/Queue/KafkaEtlTests.cs
  test/SlowTests/Tests/TestsInheritanceTests.cs
Labels: v6.0

#17974 RavenDB-21871 Fixing NRE for nullable Dates in Corax `InQuery`
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxQueryBuilder.cs
Labels: v6.0

#17976 RavenDB-21921 starting from .NET 8 SDK the --self-contained is a mandatory parameter
  scripts/buildProjects.ps1
Labels: v5.4

#17977 5.4 to 6.0 merge
  scripts/buildProjects.ps1
  src/Raven.Client/ServerWide/Operations/Logs/SetLogsConfigurationOperation.cs
  src/Raven.Client/ServerWide/Operations/TrafficWatch/PutTrafficWatchConfigurationOperation.cs
  src/Raven.Server/Config/Categories/TrafficWatchConfiguration.cs
  src/Raven.Server/Config/JsonConfigFileModifier.cs
  src/Raven.Server/Config/SettingsJsonModifier.cs
  src/Raven.Server/Documents/Handlers/Admin/AdminLogsHandler.cs
  src/Raven.Server/Exceptions/PersistConfigurationException.cs
  src/Raven.Server/TrafficWatch/TrafficWatchHandler.cs
  src/Raven.Server/TrafficWatch/TrafficWatchToLog.cs
  test/SlowTests/SparrowTests/ModifyConfigurationTests.cs
Labels: v6.0

#17983 5.4 to 6.0 merge
  src/Raven.Server/Config/JsonConfigFileModifier.cs
  src/Raven.Server/Documents/Handlers/Admin/AdminLogsHandler.cs
  src/Raven.Server/TrafficWatch/TrafficWatchHandler.cs
  src/Raven.Server/Utils/MicrosoftLogging/MicrosoftLoggingConfiguration.cs
  src/Raven.Studio/typescript/models/resources/trafficWatchConfiguration.ts
  test/SlowTests/SparrowTests/ModifyConfigurationTests.cs
Labels: v6.0

#17975 RavenDB-21858 Cannot download the dump file generated by /admin/debug/dump endpoint
  src/Raven.Server/Web/System/AdminDumpHandler.cs
  tools/Raven.Debug/CommandLineApp.cs
  tools/Raven.Debug/Dump/Dumper.cs
  tools/Raven.Debug/GCDump/GCHeapDumper.cs
  tools/Raven.Debug/Utils/PosixFileExtensions.cs
Labels: v5.4

#17985 RavenDB-7070 - skip logging of queries that allocate less than 32MB
  src/Raven.Server/Documents/Indexes/Persistence/IndexReadOperationBase.cs
Labels: v5.4

#17987 RavenDB-21927: update change vector when task gets back on previously…
  src/Raven.Server/Documents/Sharding/Subscriptions/SubscriptionConnectionsStateOrchestrator.cs
  src/Raven.Server/Documents/Subscriptions/AbstractSubscriptionConnectionsState.cs
  src/Raven.Server/Documents/Subscriptions/SubscriptionBinder.cs
  src/Raven.Server/Documents/Subscriptions/SubscriptionConnectionsState.cs
  test/SlowTests/Client/Subscriptions/ConcurrentSubscriptionsTests.cs
Labels: v6.0

#17989 5.4 to 6.0 merge
  src/CommonAssemblyInfo.Linux.cs
  src/CommonAssemblyInfo.Windows.cs
  src/Raven.Server/Documents/Indexes/Persistence/IndexReadOperationBase.cs
  src/Raven.Server/Web/System/AdminDumpHandler.cs
  tools/Raven.Debug/CommandLineApp.cs
  tools/Raven.Debug/Dump/Dumper.cs
  tools/Raven.Debug/GCDump/GCHeapDumper.cs
  tools/Raven.Debug/Utils/PosixFileExtensions.cs
Labels: v6.0

#17992 RavenDB-21943 2fa UI is broken on 6.0
  src/Raven.Studio/typescript/viewmodels/twoFactorShell.ts
Labels: v6.0, Studio

#17959 RavenDB-21790 Enabling `stats` in the console turns off Logging Thread
  src/Raven.Server/Utils/Cli/RavenCli.cs
Labels: v5.4

#17991 RavenDB-20171 Added messages to Assert.Equal() calls so we'll know for sure which one is ocassionally failing
  test/FastTests/Sparrow/Memory.cs
Labels: v5.4

#17978 RavenDB-21920 - Enforce uniqueness of Queue Sink task names
  src/Raven.Client/ServerWide/DatabaseRecord.cs
  test/SlowTests/Server/Documents/QueueSink/KafkaQueueSinkTests.cs
  test/SlowTests/Server/Documents/QueueSink/RabbitMqSinkTests.cs
  test/SlowTests/Tests/TestsInheritanceTests.cs
  test/Tests.Infrastructure/RavenTestCategory.cs
Labels: v6.0

#17990 RavenDB-20155 - ClusterTransactionShouldBeRedirectedFromPromotableNode fails
  src/Raven.Server/ServerWide/Maintenance/ClusterMaintenanceSupervisor.cs
Labels: v5.4

#18002 5.4 to 6.0 merge
  src/Raven.Server/Documents/AttachmentsStorage.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterMaintenanceSupervisor.cs
  src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
  src/Raven.Server/Utils/Cli/RavenCli.cs
  src/Raven.Studio/typescript/commands/maintenance/saveAdminLogsMicrosoftConfigurationCommand.ts
  src/Raven.Studio/typescript/models/resources/trafficWatchConfiguration.ts
  src/Raven.Studio/typescript/viewmodels/manage/adminLogs.ts
  src/Raven.Studio/typescript/viewmodels/manage/adminLogsTrafficWatchDialog.ts
  src/Raven.Studio/typescript/viewmodels/manage/configureMicrosoftLogsDialog.ts
  src/Raven.Studio/typings/_studio/dto.d.ts
  src/Raven.Studio/wwwroot/App/views/manage/adminLogs.html
  src/Raven.Studio/wwwroot/App/views/manage/adminLogsTrafficWatchDialog.html
  src/Raven.Studio/wwwroot/App/views/manage/configureMicrosoftLogsDialog.html
  src/Sparrow.Server/Utils/DiskUtils.cs
  test/FastTests/Sparrow/Memory.cs
  test/SlowTests/Issues/RavenDB_19033.cs
  test/SlowTests/Issues/RavenDB_20843.cs
  test/SlowTests/Monitoring/DiskStatsGetterTest.cs
  test/Tests.Infrastructure/NightlyBuildMultiplatformFactAttribute.cs
Labels: v6.0

#17994 RavenDB-21936 Fixing the allocation size for a counter group name when purging counter tombstones
  src/Raven.Server/Documents/CountersStorage.cs
Labels: v5.4

#18004 RavenDB-21940 Ensure valid access to test endpoints
  src/Raven.Server/Web/System/EmptyMessageHandler.cs
Labels: v5.4

#18003 5.4 to 6.0 merge
  src/Raven.Server/Documents/CountersStorage.cs
Labels: v6.0

#18007 RavenDB-21957: Support ticks for the new JavaScript index only. Ensure that old indexes do not use ticks.
  src/Raven.Server/Documents/Indexes/IndexDefinitionBaseServerSide.cs
  src/Raven.Server/Documents/Indexes/Persistence/Corax/JintCoraxDocumentConverter.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/JintLuceneDocumentConverter.cs
  src/Raven.Server/Utils/TypeConverter.cs
  test/SlowTests/Data/RavenDB_21957/js_index_with_dates_54112.ravendb-snapshot
  test/SlowTests/Issues/RavenDB-19625.cs
  test/SlowTests/SlowTests.csproj
Labels: v5.4

#18006 RavenDB-21960 Add server endpoint to expose indexes metadata
  src/Raven.Server/Documents/Handlers/IndexHandler.cs
  test/SlowTests/Authentication/AuthenticationDebugPackageInfoTests.cs
  test/SlowTests/Issues/RavenDB-21960.cs
Labels: v5.4

#18009 RavenDB-21940 Fixing failing test after changing URL of test endpoint
  test/SlowTests/Issues/RavenDB_7162.cs
Labels: v5.4

#18011 RavenDB-21905 Typo in Indexing.NuGetAllowPreleasePackages + Fix some descriptions
  src/Raven.Server/Config/Categories/IndexingConfiguration.cs
Labels: v5.4

#18013 5.4 to 6.0 merge + RavenDB-21957 adjustments for 6.0
  src/Raven.Server/Documents/Handlers/IndexHandler.cs
  src/Raven.Server/Documents/Indexes/IndexDefinitionBaseServerSide.cs
  src/Raven.Server/Documents/Indexes/Persistence/Corax/JintCoraxDocumentConverter.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/Documents/JintLuceneDocumentConverter.cs
  src/Raven.Server/Utils/TypeConverter.cs
  src/Raven.Server/Web/System/EmptyMessageHandler.cs
  test/SlowTests/Authentication/AuthenticationDebugPackageInfoTests.cs
  test/SlowTests/Data/RavenDB_21957/js_index_with_dates_54112.ravendb-snapshot
  test/SlowTests/Issues/RavenDB-19625.cs
  test/SlowTests/Issues/RavenDB-21960.cs
  test/SlowTests/Issues/RavenDB_7162.cs
  test/SlowTests/SlowTests.csproj
Labels: v6.0

#18008 RavenDB-21962 Remove Lazy Transaction support.
  src/Raven.Server/Documents/Handlers/Admin/TransactionsModeHandler.cs
  src/Raven.Server/Documents/Handlers/Debugging/TransactionDebugHandler.cs
  src/Raven.Server/Documents/Sharding/Handlers/Admin/ShardedTransactionsModeHandler.cs
  src/Raven.Server/ServerWide/Context/DocumentsOperationContext.cs
  src/Voron/Impl/Journal/JournalFile.cs
  src/Voron/Impl/Journal/LazyTransactionBuffer.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/Impl/LowLevelTransaction.cs
  src/Voron/StorageEnvironment.cs
  src/Voron/StorageEnvironmentOptions.cs
  src/Voron/TransactionsMode.cs
  test/FastTests/Voron/LazyTransactionsRespectPageBoundaries.cs
  test/SlowTests/Issues/RavenDB_10946.cs
  test/SlowTests/Voron/Bugs/StorageEnvDisposeWithLazyTx.cs
Labels: v6.0

#18019 RavenDB-19337 Upgrade to Jint 3.0.0
  src/Raven.Server/Documents/Indexes/Static/EsprimaVisitor.cs
  src/Raven.Server/Documents/Indexes/Static/JavaScriptMapOperation.cs
  src/Raven.Server/Documents/Patch/JintNullPropagationReferenceResolver.cs
  src/Raven.Server/Documents/Patch/JintPreventResolvingTasksReferenceResolver.cs
  src/Raven.Server/Raven.Server.csproj
Labels: v6.0

#18016 RavenDB-21957 Added test fir 6.0 version using snapshot from 6.0.1
  test/SlowTests/Data/RavenDB_21957/js_index_with_dates_601.ravendb-snapshot
  test/SlowTests/Issues/RavenDB-19625.cs
  test/SlowTests/SlowTests.csproj
Labels: v6.0

#18021 RavenDB-7070 - update .gitignore
  .gitignore
Labels: v6.0

#17993 RachisTests.DatabaseCluster.RemoveNodeFromCluster.HardResetToNewClusterTest(tag: "A") fails
  test/RachisTests/DatabaseCluster/RemoveNodeFromCluster.cs
Labels: v5.4

#18027 5.4 to 6.0 merge
  .gitignore
  src/Raven.Server/Config/Categories/IndexingConfiguration.cs
  src/Raven.Server/Documents/Handlers/Debugging/StorageHandler.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesStorage.cs
  src/Raven.Server/Web/System/AdminStorageHandler.cs
  src/Voron/Debugging/DetailedStorageReport.cs
  src/Voron/Debugging/StorageReportGenerator.cs
  src/Voron/StorageEnvironment.cs
  test/FastTests/RavenDB_14520.cs
  test/FastTests/Server/Documents/Queries/HighlightingQuery.cs
  test/FastTests/Voron/Containers/ContainerTests.cs
  test/FastTests/Voron/PostingLists/PostingListLeafPageTests.cs
  test/FastTests/Voron/PostingLists/PostingListTests.cs
  test/SlowTests/Client/DatabaseSettingsOperationTests.cs
  test/SlowTests/DatabaseSettings/DatabaseSettings.cs
  test/SlowTests/DatabaseSettings/SettingsJson.cs
  test/SlowTests/Issues/RavenDB_18414.cs
  test/SlowTests/Server/Documents/ETL/Raven/RavenDB_13220.cs
  test/SlowTests/Tests/TestsInheritanceTests.cs
  test/SlowTests/Voron/PalTest/PalMmapFunctionTests.cs
  test/StressTests/Corax/Bugs/PostingListTestsExtended.cs
Labels: v6.0

#18032 5.4 to 6.0 merge
  src/Raven.Client/Documents/DocumentStore.cs
  test/RachisTests/DatabaseCluster/RemoveNodeFromCluster.cs
  test/SlowTests/Issues/RavenDB-21879.cs
Labels: v6.0

#18035 RavenDB-19922 - wait for the cluster observer to determine the responsible node for a new backup task
  src/Raven.Server/Web/System/OngoingTasksHandler.cs
Labels: v5.4

#18036 5.4 to 6.0 merge
  src/Raven.Server/Documents/Handlers/Processors/OngoingTasks/OngoingTasksHandlerProcessorForBackupDatabaseNow.cs
Labels: v6.0

#18034 RavenDB-14341 Explanations / Introduction DocumentationUrls
  src/Raven.Client/DocumentationUrls.cs
  src/Raven.Client/Documents/Queries/Explanation/ExplanationOptions.cs
  src/Raven.Client/Documents/Session/AbstractDocumentQuery.Explanations.cs
  src/Raven.Client/Documents/Session/DocumentQuery.cs
  src/Raven.Client/Documents/Session/IDocumentQueryBase.cs
Labels: v6.0

#18037 RavenDB-21833 fix setting _lastWriteToStream
  src/Raven.Client/Documents/BulkInsert/BulkInsertOperation.cs
  test/SlowTests/Issues/RavenDB-17745.cs
Labels: v5.4

#18044 5.4 to 6.0 merge
  src/Raven.Client/Documents/BulkInsert/BulkInsertOperation.cs
  src/Raven.Client/Documents/BulkInsert/BulkInsertWriter.cs
  src/Raven.Client/Documents/BulkInsert/BulkInsertWriterBase.cs
  test/SlowTests/Issues/RavenDB-17745.cs
Labels: v6.0

#18047 RavenDB-21950 Persist Microsoft logs should overid the currnt configu…
  src/Raven.Studio/typescript/commands/maintenance/saveAdminLogsMicrosoftConfigurationCommand.ts
Labels: v6.0, v5.4, Studio

#18046 RavenDB-21996 Querying API documentation
  src/Raven.Client/DocumentationUrls.cs
  src/Raven.Client/Documents/Linq/IRavenQueryable.cs
  src/Raven.Client/Documents/Linq/RavenQueryInspector.cs
  src/Raven.Client/Documents/Session/AbstractDocumentQuery.Explanations.cs
  src/Raven.Client/Documents/Session/AsyncDocumentSession.Query.cs
  src/Raven.Client/Documents/Session/DocumentSession.Query.cs
  src/Raven.Client/Documents/Session/IAdvancedSessionOperations.Query.cs
  src/Raven.Client/Documents/Session/IAsyncAdvancedSessionOperations.Query.cs
Labels: v6.0

#18050 RavenDB-21706 more debug info
  test/SlowTests/Authentication/AuthenticationBasicTests.cs
Labels: v5.4

#18056 RavenDB-21955 Grace period before closing JSON-preview tooltip to fac…
  src/Raven.Studio/typescript/widgets/virtualGrid/columnPreviewPlugin.ts
Labels: v5.4, Studio

#18049 RavenDB-21938 : fix flaky test
  test/SlowTests/Server/Documents/ETL/Raven/BasicRavenEtlTests.cs
Labels: v5.4

#18051 RavenDB-21833 Ensure flushing occurs when the timeout is imminent
  src/Raven.Client/Documents/BulkInsert/BulkInsertOperation.cs
Labels: v5.4

#18055 RavenDB-21088 fix and tests
  src/Raven.Server/Documents/Handlers/Processors/Debugging/AbstractStorageHandlerProcessorForGetEnvironmentReport.cs
  src/Raven.Server/Documents/Handlers/Processors/Debugging/StorageHandlerProcessorForGetEnvironmentReport.cs
  src/Raven.Server/Documents/Handlers/Processors/Debugging/StorageHandlerProcessorForGetScratchBufferReport.cs
  src/Raven.Server/Web/System/AdminStorageHandler.cs
  test/SlowTests/Issues/RavenDB-21088.cs
Labels: v6.0

#18020 RavenDB-20963 - CreateRaftCluster method throws on tests
  src/Raven.Server/Rachis/Leader.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
Labels: v6.0

#18063 RavenDB-21088 we need to return 404 if env is missing
  src/Raven.Server/Documents/Handlers/Debugging/StorageHandler.cs
Labels: v5.4

#18061 RavenDB-22005 Attempt to fix .RavenDB_18059.RaceConditionBetweenFullBackupAndUpdateDatabaseStateAfterSync(compressionAlgorithm: Zstd) test
  test/SlowTests/Voron/Issues/RavenDB_18059.cs
Labels: v5.4

#18038 RavenDB-21989 - don't materialize the database record in HandleClusterDatabaseChanged
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/ETL/EtlLoader.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
  src/Raven.Server/Documents/Sharding/ShardedDatabaseContext.Subscriptions.cs
  src/Raven.Server/Documents/Sharding/ShardedDatabaseContext.cs
  src/Raven.Server/Documents/Subscriptions/AbstractSubscriptionStorage.cs
  src/Raven.Server/Documents/Subscriptions/Sharding/ShardSubscriptionStorage.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
  test/StressTests/Server/Documents/PeriodicBackup/PeriodicBackupTestsStress.cs
Labels: v6.0

#18067 5.4 to 6.0 merge
  src/Raven.Server/Documents/Handlers/Admin/AdminLogsHandler.cs
  src/Raven.Server/Utils/MicrosoftLogging/MicrosoftLoggingConfiguration.cs
  src/Raven.Studio/typescript/commands/maintenance/saveAdminLogsMicrosoftConfigurationCommand.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/columnPreviewPlugin.ts
  test/SlowTests/Authentication/AuthenticationBasicTests.cs
  test/SlowTests/Issues/RavenDB-21088.cs
  test/SlowTests/Server/Documents/ETL/Raven/BasicRavenEtlTests.cs
  test/SlowTests/SparrowTests/MicrosoftLogTests.cs
  test/SlowTests/Tests/TestsInheritanceTests.cs
  test/SlowTests/Voron/Issues/RavenDB_18059.cs
Labels: v6.0

#18070 RavenDB-7070 Fixing studio build
  src/Raven.Studio/typescript/widgets/virtualGrid/columnPreviewPlugin.ts
Labels: v6.0, Studio

#18069 RavenDB-22000 Ensure flushing occurs when the timeout is imminent
  src/Raven.Client/Documents/BulkInsert/BulkInsertOperation.cs
  src/Raven.Client/Documents/BulkInsert/BulkInsertWriterBase.cs
Labels: v6.0
