Repository ravendb/ravendb, pull requests merged in 2024-06, with the labels that each got.

#18595 RavenDB-22210 Add test CA certificates to store with retries
  test/SlowTests/Issues/RavenDB-22210.cs
Labels: v5.4

#18596 RavenDB-22431 ensure that result order of cluster wide tx in sharded database
  src/Raven.Server/Documents/Handlers/Processors/Batches/AbstractBatchHandlerProcessorForBulkDocs.cs
  src/Raven.Server/Documents/Handlers/Processors/Batches/AbstractClusterTransactionRequestProcessor.cs
  src/Raven.Server/ServerWide/Commands/ClusterTransactionCommand.cs
  test/SlowTests/Cluster/ClusterTransactionTests.cs
Labels: v6.0

#18597 RavenDB-22221 marked NextPageStart as Obsolete
  src/Raven.Client/Documents/Commands/GetDocumentsResult.cs
Labels: v6.0

#18584 RavenDB-22423 Lucene - rollback indexing for document where exception happened during indexing/mapping.
  src/Raven.Server/Documents/Indexes/MapIndexBase.cs
  test/SlowTests/Issues/RavenDB_22406.cs
Labels: v6.0

#18604 RavenDB-22382 - Execute the expiration command outside the read transaction
  src/Raven.Server/Documents/Expiration/ExpiredDocumentsCleaner.cs
Labels: v5.4

#18607 RavenDB-22382 - Execute the expiration command outside the read transaction
  src/Raven.Server/Documents/DataArchival/DataArchivist.cs
  src/Raven.Server/Documents/Expiration/ExpiredDocumentsCleaner.cs
Labels: v6.0

#18603 RavenDB-22438 Connection string dialog is closed when we get any changes api update
  src/Raven.Studio/typescript/components/pages/database/settings/connectionStrings/ConnectionStrings.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/connectionStrings/store/connectionStringsSlice.ts
Labels: v6.0, Studio

#18608 merge RavenDB-22438 from release/v6.0 to v6.0
  src/Raven.Studio/typescript/components/pages/database/settings/connectionStrings/ConnectionStrings.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/connectionStrings/store/connectionStringsSlice.ts
Labels: v6.0, Studio

#18610 RavenDB-22362 Unify audit log lines
  src/Raven.Server/Documents/DatabaseRequestHandler.cs
  src/Raven.Server/Documents/Handlers/Admin/AdminAnalyzersHandler.cs
  src/Raven.Server/Documents/Handlers/Admin/AdminIndexHandler.cs
  src/Raven.Server/Documents/Handlers/Admin/AdminSortersHandler.cs
  src/Raven.Server/Documents/Handlers/IndexHandler.cs
  src/Raven.Server/Documents/Handlers/QueriesHandler.cs
  src/Raven.Server/Documents/Handlers/Streaming/StreamingHandler.cs
  src/Raven.Server/Integrations/PostgreSQL/Handlers/PostgreSqlIntegrationHandler.cs
  src/Raven.Server/Web/Authentication/AdminCertificatesHandler.cs
  src/Raven.Server/Web/Authentication/TwoFactorAuthenticationHandler.cs
  src/Raven.Server/Web/RequestHandler.Audit.cs
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
  src/Raven.Server/Web/System/Analyzers/AdminAnalyzersHandler.cs
  src/Raven.Server/Web/System/DatabasesHandler.cs
  src/Raven.Server/Web/System/OngoingTasksHandler.cs
  src/Raven.Server/Web/System/Sorters/AdminSortersHandler.cs
Labels: v5.4

#18612 5.4 to 6.0 merge
  src/Raven.Server/Documents/Handlers/Admin/Processors/Indexes/AbstractAdminIndexHandlerProcessorForPut.cs
  src/Raven.Server/Documents/Handlers/Admin/Processors/Sorters/AbstractAdminSortersHandlerProcessorForDelete.cs
  src/Raven.Server/Documents/Handlers/Admin/Processors/Sorters/AbstractAdminSortersHandlerProcessorForPut.cs
  src/Raven.Server/Documents/Handlers/Processors/Analyzers/AbstractAdminAnalyzersHandlerProcessorForDelete.cs
  src/Raven.Server/Documents/Handlers/Processors/Analyzers/AbstractAdminAnalyzersHandlerProcessorForPut.cs
  src/Raven.Server/Documents/Handlers/Processors/Indexes/AbstractIndexHandlerProcessorForDelete.cs
  src/Raven.Server/Documents/Handlers/Processors/Indexes/IndexHandlerProcessorForReset.cs
  src/Raven.Server/Documents/Handlers/Processors/OngoingTasks/AbstractOngoingTasksHandlerProcessorForPutConnectionString.cs
  src/Raven.Server/Documents/Handlers/Processors/OngoingTasks/AbstractOngoingTasksHandlerProcessorForRemoveConnectionString.cs
  src/Raven.Server/Documents/Handlers/Processors/Queries/AbstractDatabaseOperationQueriesHandlerProcessor.cs
  src/Raven.Server/Documents/Handlers/Processors/Streaming/AbstractStreamingHandlerProcessorForGetStreamQuery.cs
  src/Raven.Server/Integrations/PostgreSQL/Handlers/Processors/AbstractPostgreSqlIntegrationHandlerProcessorForAddUser.cs
  src/Raven.Server/Integrations/PostgreSQL/Handlers/Processors/AbstractPostgreSqlIntegrationHandlerProcessorForDeleteUser.cs
  src/Raven.Server/Web/Authentication/AdminCertificatesHandler.cs
  src/Raven.Server/Web/Authentication/TwoFactorAuthenticationHandler.cs
  src/Raven.Server/Web/RequestHandler.Audit.cs
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
  src/Raven.Server/Web/System/Analyzers/AdminAnalyzersHandler.cs
  src/Raven.Server/Web/System/DatabasesHandler.cs
  src/Raven.Server/Web/System/Sorters/AdminSortersHandler.cs
  test/SlowTests/Issues/RavenDB-22210.cs
Labels: v6.0

#18616 RavenDB-22398 Contact Sales -> Contact Us
  src/Raven.Studio/typescript/components/pages/resources/about/partials/ChangeLogModal.tsx
Labels: v6.0, Studio

#18625 merge release/v6.0 to v6.0
  src/Raven.Server/Documents/AbstractBackgroundWorkStorage.cs
  src/Raven.Studio/typescript/components/common/shell/setup.ts
  src/Raven.Studio/typescript/components/pages/database/settings/customSorters/DatabaseCustomSortersServerWideList.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/customSorters/DatabaseCustomSortersServerWideListItem.tsx
  src/Raven.Studio/typescript/components/pages/resources/about/partials/ChangeLogModal.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/DatabaseDistribution.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/DatabaseNodeSetItem.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/DatabaseTopologyNodeSetItem.tsx
Labels: v6.0

#18632 merge Revert of RavenDB-21926 from release/v6.0 to v6.0
  bench/Voron.Benchmark/Utils.cs
  src/Raven.Server/Documents/AttachmentsStorage.cs
  src/Raven.Server/Documents/ConflictsStorage.cs
  src/Raven.Server/Documents/Indexes/Debugging/IndexDebugExtensions.cs
  src/Raven.Server/Documents/Indexes/IndexStorage.cs
  src/Raven.Server/Documents/Indexes/MapReduce/MapReduceIndexBase.cs
  src/Raven.Server/Documents/Indexes/MapReduce/OutputToCollection/OutputReduceToCollectionActions.cs
  src/Raven.Server/Documents/Indexes/MapReduce/ReduceMapResultsBase.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesStats.cs
  src/Raven.Server/Rachis/FollowerAmbassador.cs
  src/Voron/Data/BTrees/Tree.Compressed.cs
  src/Voron/Data/BTrees/Tree.MultiTree.cs
  src/Voron/Data/BTrees/Tree.Stream.cs
  src/Voron/Data/BTrees/Tree.cs
  src/Voron/Data/BTrees/TreeMutableState.cs
  src/Voron/Data/BTrees/TreePageSplitter.cs
  src/Voron/Data/BTrees/TreeRebalancer.cs
  src/Voron/Data/CompactTrees/CompactTree.cs
  src/Voron/Data/Lookups/Lookup.cs
  src/Voron/Data/Tables/Table.cs
  src/Voron/Data/Tables/TableSchema.cs
  src/Voron/Data/Tables/TableValueCompressor.cs
  src/Voron/Debugging/DebugStuff.cs
  src/Voron/Debugging/StorageReportGenerator.cs
  src/Voron/Impl/Backup/IncrementalBackup.cs
  src/Voron/Impl/Compaction/StorageCompaction.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/Impl/LowLevelTransaction.cs
  src/Voron/Impl/StorageEnvironmentState.cs
  src/Voron/Impl/Transaction.cs
  src/Voron/StorageEnvironment.cs
  test/FastTests/Voron/Bugs/RavenDB_9225.cs
  test/FastTests/Voron/Tables/Allocations.cs
  test/FastTests/Voron/Trees/Basic.cs
  test/FastTests/Voron/Trees/CanDefrag.cs
  test/FastTests/Voron/Trees/Deletes.cs
  test/FastTests/Voron/Trees/FreeSpaceTest.cs
  test/FastTests/Voron/Trees/ItemsCount.cs
  test/FastTests/Voron/Trees/TreeStateTests.cs
  test/FastTests/Voron/Trees/Updates.cs
  test/SlowTests/Issues/RavenDB-8451.cs
  test/SlowTests/Issues/RavenDB_10382.cs
  test/SlowTests/Voron/Bugs/RavenDB_8962.cs
  test/SlowTests/Voron/Issues/RavenDB_10813.cs
  test/SlowTests/Voron/Issues/RavenDB_10825.cs
  test/SlowTests/Voron/Issues/RavenDB_11643_Voron.cs
  test/SlowTests/Voron/LargeValues.cs
  test/SlowTests/Voron/LeafsCompression/RDBS_52.cs
  test/SlowTests/Voron/LeafsCompression/RavenDB_12700_Voron.cs
  test/SlowTests/Voron/LeafsCompression/RavenDB_16363.cs
  test/SlowTests/Voron/LeafsCompression/RavenDB_17660.cs
  test/SlowTests/Voron/LeafsCompression/RavenDB_5384.cs
  test/SlowTests/Voron/RavenDB_21926.cs
  test/SlowTests/Voron/Storage/Increments.cs
  test/SlowTests/Voron/Streams/CanUseStream.cs
  test/StressTests/Voron/PageSplitterStressTests.cs
Labels: v6.0

#18647 RavenDB-20325 Backup/Export doesn't take into account time series del…
  src/Raven.Studio/typescript/models/database/tasks/exportDatabaseModel.ts
  src/Raven.Studio/typescript/models/database/tasks/importDatabaseModel.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/smugglerDatabaseDetails.ts
  src/Raven.Studio/wwwroot/App/views/database/tasks/exportDatabase.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/importDatabaseFromFile.html
Labels: v5.4, Studio

#18644 RavenDB-22387 Export visible columns to CSV - studio does not include…
  src/Raven.Studio/typescript/viewmodels/partial/columnsSelector.ts
Labels: v6.0, Studio

#18651 RavenDB-21833 switch BulkInsertWithDelay to work on Http1 and Http2
  src/Raven.Server/RavenServer.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  test/SlowTests/Issues/RavenDB-17745.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v6.0

#18662 5.4 to 6.0 merge
  scripts/linux/pkg/deb/assets/build.sh
  scripts/linux/pkg/deb/build-deb_ubuntu-noble_amd64.ps1
  scripts/linux/pkg/deb/set-ubuntu-noble.ps1
  scripts/linux/pkg/deb/set-ubuntu-noble.sh
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.1/5.1.11/ActiveOngoingTasksBase.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.1/5.1.11/OngoingTasksBase.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.1/5.1.11/TotalNumberOfActiveBackupTasks.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.1/5.1.11/TotalNumberOfActiveElasticSearchEtlTasks.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.1/5.1.11/TotalNumberOfActiveExternalReplicationTasks.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.1/5.1.11/TotalNumberOfActiveOlapEtlTasks.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.1/5.1.11/TotalNumberOfActiveOngoingTasks.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.1/5.1.11/TotalNumberOfActivePullReplicationAsSinkTasks.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.1/5.1.11/TotalNumberOfActiveQueueEtlTasks.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.1/5.1.11/TotalNumberOfActiveQueueSinkTasks.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.1/5.1.11/TotalNumberOfActiveRavenEtlTasks.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.1/5.1.11/TotalNumberOfActiveSqlEtlTasks.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.1/5.1.11/TotalNumberOfActiveSubscriptionTasks.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.1/5.1.11/TotalNumberOfBackupTasks.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.1/5.1.11/TotalNumberOfElasticSearchEtlTasks.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.1/5.1.11/TotalNumberOfExternalReplicationTasks.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.1/5.1.11/TotalNumberOfOlapEtlTasks.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.1/5.1.11/TotalNumberOfOngoingTasks.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.1/5.1.11/TotalNumberOfPullReplicationAsSinkTasks.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.1/5.1.11/TotalNumberOfQueueEtlTasks.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.1/5.1.11/TotalNumberOfQueueSinkTasks.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.1/5.1.11/TotalNumberOfRavenEtlTasks.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.1/5.1.11/TotalNumberOfSqlEtlTasks.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.1/5.1.11/TotalNumberOfSubscriptionTasks.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Database/5.1/DatabaseBase.cs
  src/Raven.Server/Monitoring/Snmp/SnmpOids.cs
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
  test/FastTests/Issues/RavenDB_21412.cs
Labels: v6.0

#18663 merge release/v5.4 to v5.4
  src/Raven.Server/Documents/Document.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Includes/IncludeDocumentsCommand.cs
  src/Raven.Server/Documents/Indexes/Errors/FaultyInMemoryIndex.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/MapIndexBase.cs
  src/Raven.Server/Documents/Indexes/MapReduce/MapReduceIndexBase.cs
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxIndexQueryingScope.cs
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxIndexReadOperation.cs
  src/Raven.Server/Documents/Indexes/Persistence/IndexOperationBase.cs
  src/Raven.Server/Documents/Indexes/Persistence/IndexQueryingScopeBase.cs
  src/Raven.Server/Documents/Indexes/Persistence/IndexReadOperationBase.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/LuceneIndexQueryingScope.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/LuceneIndexReadOperation.cs
  src/Raven.Server/Documents/Indexes/Persistence/QueryFilter.cs
  src/Raven.Server/Documents/Indexes/Static/Counters/MapCountersIndex.cs
  src/Raven.Server/Documents/Indexes/Static/TimeSeries/MapTimeSeriesIndex.cs
  src/Raven.Server/Documents/Patch/BlittableObjectInstance.cs
  src/Raven.Server/Documents/Patch/JavaScriptUtils.cs
  src/Raven.Server/Documents/Patch/ScriptRunner.cs
  src/Raven.Server/Documents/Queries/CollectionQueryEnumerable.cs
  src/Raven.Server/Documents/Queries/QueriedDocument.cs
  src/Raven.Server/Documents/Queries/Results/GraphQueryResultRetriever.cs
  src/Raven.Server/Documents/Queries/Results/IQueryResultRetriever.cs
  src/Raven.Server/Documents/Queries/Results/MapQueryResultRetriever.cs
  src/Raven.Server/Documents/Queries/Results/MapReduceQueryResultRetriever.cs
  src/Raven.Server/Documents/Queries/Results/QueriedDocumentCache.cs
  src/Raven.Server/Documents/Queries/Results/QueryResultRetrieverBase.cs
  src/Raven.Server/Documents/Queries/Results/TimeSeries/TimeSeriesRetriever.cs
  src/Raven.Server/Json/BlittableJsonTraverserHelper.cs
  src/Raven.Server/Utils/Enumerators/PulsedTransactionEnumerator.cs
  src/Raven.Server/Utils/LruDictionary.cs
  src/Raven.Studio/typescript/models/database/index/index.ts
  src/Voron/Constants.cs
  src/Voron/Impl/Transaction.cs
  test/FastTests/Server/Documents/Indexing/BasicAnalyzers.cs
  test/FastTests/Server/Documents/Indexing/Lucene/LuceneDocumentConverterTests.cs
  test/SlowTests/Issues/RavenDB-17134.cs
  test/SlowTests/Issues/RavenDB_21900.cs
  test/SlowTests/Verifications/RavenDB_2239.cs
Labels: v5.4

#18643 Raven db 22271
  src/Raven.Client/Documents/Operations/Revisions/RevisionsCollectionConfiguration.cs
  src/Raven.Client/Documents/Operations/Revisions/RevisionsConfiguration.cs
  src/Raven.Server/Documents/DatabaseRequestHandler.cs
  src/Raven.Server/Documents/Handlers/RevisionsHandler.cs
  src/Raven.Server/Json/JsonDeserializationServer.cs
Labels: v5.4

#18675 RavenDB-21833 - Remove unnecessary flush which might run concurrently with writing to the stream
  src/Raven.Client/Documents/BulkInsert/BulkInsertOperation.cs
  src/Raven.Client/Documents/BulkInsert/BulkInsertWriterBase.cs
Labels: v6.0

#18672 RavenDB-22417 - UpdateDefinitionWithoutState fails
  test/SlowTests/Issues/RavenDB-15890.cs
Labels: v5.4

#18670 RavenDB-22413 - Majority of replicas doesn't take itself into account
  src/Raven.Server/Documents/Handlers/BatchHandler.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  test/SlowTests/Issues/RavenDB-22413.cs
Labels: v5.4

#18668 RavenDB-17604 fixing test
  test/SlowTests/Issues/RavenDB_17604.cs
Labels: v5.4

#18676 RavenDB-22478 removed duplicate property
  src/Raven.Server/Json/BlittableJsonTextWriterExtensions.cs
Labels: v5.4

#18678 merge relase/v5.4 to v5.4
  src/CommonAssemblyInfo.cs
  src/Raven.Client/Properties/VersionInfo.cs
Labels: v5.4

#18679 merge release/v6.0 to v6.0
  src/CommonAssemblyInfo.cs
  src/Raven.Client/Properties/VersionInfo.cs
Labels: v6.0

#18631 RavenDB-22455 - Allow to import a disabled revisions configuration
  src/Raven.Server/ServerWide/ClusterStateMachine.License.cs
Labels: v6.0

#18637 RavenDB-22430 Update query statistics after all results are retrieved from IndexReadOperation
  src/Raven.Server/Documents/Indexes/Index.cs
Labels: Corax, v6.0

#18688 RavenDB-22485 Use dotnet-runtime-deps deps for Ubuntu 22 and lower
  scripts/linux/pkg/deb/assets/build.sh
Labels: v5.4

#18689 5.4 to 6.0 merge
  scripts/linux/pkg/deb/assets/build.sh
  src/Raven.Server/Documents/Handlers/Admin/RachisAdminHandler.cs
  src/Raven.Server/Json/BlittableJsonTextWriterExtensions.cs
  test/SlowTests/Issues/RavenDB-15890.cs
Labels: v6.0

#18658 RavenDB-13389 Expose DocumentsOperationContext, TransactionOperationContext and ClusterOperationContext in Admin JS Console
  src/Raven.Server/Documents/Patch/AdminJsConsole.cs
  src/Raven.Server/Documents/Patch/JavaScriptUtils.cs
  test/SlowTests/Issues/RavenDB-13389.cs
Labels: v5.4

#18685 CSV-763 Use uglify-js v2.6.0
  src/Raven.Studio/aceBuild/package-lock.json
  src/Raven.Studio/aceBuild/package.json
Labels: v6.0, Studio

#18681 RavenDB-21833 bulk insert fix
  src/Raven.Client/Documents/BulkInsert/BulkInsertOperation.cs
  src/Raven.Client/Documents/BulkInsert/BulkInsertWriterBase.cs
Labels: v6.0

#18682 RavenDB-22351 Sharing the instance of table stats in case of switching between compressed and uncompressed schema in the same transaction
  src/Raven.Server/Storage/Schema/Updates/Documents/40014/From40013.cs
  src/Voron/Data/Tables/Table.cs
  src/Voron/Data/Tables/TableSchemaStatsReference.cs
  src/Voron/Impl/Transaction.cs
Labels: v5.4

#18683 RavenDB-17196 use same @metadata instance
  src/Raven.Server/Documents/Patch/BlittableObjectInstance.cs
  src/Raven.Server/Documents/Patch/JavaScriptUtils.cs
  test/SlowTests/Issues/RavenDB_17196.cs
Labels: v5.4

#18699 RavenDB-22413 - Majority of replicas doesn't take itself into account (v6.0)
  src/Raven.Server/Documents/Handlers/Processors/Batches/BatchHandlerProcessorForBulkDocs.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  test/SlowTests/Issues/RavenDB-22413.cs
Labels: v6.0

#18696 RavenDB-22494 Fix err msg for invalid percentile in time series query
  src/Raven.Server/Documents/Queries/Results/TimeSeries/PercentileAggregation.cs
Labels: v5.4

#18590 RavenDB-22421 switched to libsodium NuGet and version 1.0.20
  bench/Micro.Benchmark/Micro.Benchmark.csproj
  bench/Voron.Benchmark/Voron.Benchmark.csproj
  libs/libsodium/libsodium.arm.32.so
  libs/libsodium/libsodium.arm.64.so
  libs/libsodium/libsodium.linux.x64.so
  libs/libsodium/libsodium.mac.arm64.dylib
  libs/libsodium/libsodium.mac.x64.dylib
  libs/libsodium/libsodium.win.x64.dll
  libs/libsodium/libsodium.win.x86.dll
  src/Raven.Server/Raven.Server.csproj
  src/Sparrow/Platform/Sodium.cs
  test/Tryouts/Tryouts.csproj
  tools/rvn/rvn.csproj
Labels: Future, v6.1

#18598 RavenDB-22150 align delta with rest of the API in CounterOperation
  src/Raven.Client/Documents/Operations/Counters/CounterBatch.cs
  test/SlowTests/Issues/RavenDB_22150.cs
Labels: Future, v6.1

#18599 RavenDB-21859 both Load and LazyLoad should return null when id is null
  src/Raven.Client/Documents/Session/AsyncDocumentSession.Lazy.cs
  src/Raven.Client/Documents/Session/DocumentSession.Lazy.cs
  test/SlowTests/Issues/RavenDB_21859.cs
Labels: Future, v6.1

#18714 RavenDB-22406 Backward compatibility for handling complex fields for Corax.
  src/Raven.Server/Documents/Indexes/IndexDefinitionBaseServerSide.cs
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxDocumentConverterBase.cs
  test/SlowTests/Data/RavenDB_22406/RavenDB_22406.ravendb-snapshot
  test/SlowTests/Issues/RavenDB_22406.cs
  test/SlowTests/SlowTests.csproj
Labels: Corax, v6.0

#18715 RavenDB-22365 Confusing message for SQL ETL after upgrade from 5.4.11…
  src/Raven.Studio/wwwroot/App/views/database/settings/connectionStringSql.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/importDatabaseFromSql.html
Labels: v5.4, Studio

#18716 RavenDB-22365 Confusing message for SQL ETL after upgrade from 5.4.11…
  src/Raven.Studio/typescript/components/pages/database/settings/connectionStrings/editForms/SqlConnectionString.tsx
Labels: v6.0, Studio

#18718 RavenDB-22213 Studio showing Insufficient security clearance while it…
  src/Raven.Studio/wwwroot/App/views/shell.html
Labels: v6.0, Studio

#18717 RavenDB-22472 Update ravenClientVersion in commandBase
  src/Raven.Studio/typescript/commands/commandBase.ts
Labels: v6.0, Studio

#18704 RavenDB-22476 Fix missing space for Status in Index Progress Tooltip
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexProgressTooltip.tsx
Labels: v6.0, Studio

#18719 RavenDB-19578 Provide copy button in error dialogs
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/recentErrorDetails.ts
  src/Raven.Studio/wwwroot/App/views/common/notificationCenter/detailViewer/recentErrorDetails.html
Labels: v5.4, Studio

#18723 RavenDB-22472 Update ravenClientVersion in commandBase (v6.1)
  src/Raven.Studio/typescript/commands/commandBase.ts
Labels: Studio, v6.1

#18721 RavenDB-21996 Moved documentation links to DocumentationUrls
  src/Raven.Client/DocumentationUrls.cs
  src/Raven.Client/Documents/Queries/Timings/QueryTimings.cs
  src/Raven.Client/Documents/Session/IDocumentQuery.cs
  src/Raven.Client/Documents/Session/IQueryBase.cs
Labels: v6.0

#18722 RavenDB-22471 Displayed `created` info in indexing view is toggling between two different values while indexing
  src/Raven.Studio/typescript/components/models/indexes.ts
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexDistribution.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexesStatsReducer.ts
  src/Raven.Studio/typescript/components/pages/database/indexes/list/useIndexesPage.tsx
  src/Raven.Studio/typescript/components/utils/IndexUtils.ts
Labels: v6.0, Studio

#18728 HRINT-3697 adjust windows Docker image tags
  docker/common.ps1
Labels: v6.1

#18725 5.4 to 6.0 merge
  src/Raven.Server/Documents/Patch/AdminJsConsole.cs
  src/Raven.Server/Documents/Patch/BlittableObjectInstance.cs
  src/Raven.Server/Documents/Patch/JavaScriptUtils.cs
  src/Raven.Server/Documents/Queries/Results/TimeSeries/PercentileAggregation.cs
  src/Raven.Server/Storage/Schema/Updates/Documents/40014/From40013.cs
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/recentErrorDetails.ts
  src/Raven.Studio/wwwroot/App/views/common/notificationCenter/detailViewer/recentErrorDetails.html
  src/Raven.Studio/wwwroot/App/views/database/settings/connectionStringSql.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/importDatabaseFromSql.html
  src/Voron/Data/Tables/Table.cs
  src/Voron/Data/Tables/TableSchemaStatsReference.cs
  src/Voron/Impl/Transaction.cs
  test/SlowTests/Issues/RavenDB-13389.cs
  test/SlowTests/Issues/RavenDB_17196.cs
Labels: v6.0

#18729 RavenDB-22368
  .gitignore
  src/Raven.Server/Raven.Server.csproj
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
  tools/Raven.Migrator/Raven.Migrator.csproj
  tools/rvn/rvn.csproj
Labels: v6.1

#18734 RavenDB-22296: UnobservedTaskException in subscription
  src/Raven.Server/Documents/Subscriptions/SubscriptionConnectionBase.cs
Labels: v6.0

#18732 RavenDB-22481 Error when switching databases on revisions config view
  src/Raven.Studio/typescript/components/pages/database/indexes/cleanup/useIndexCleanup.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/conflictResolution/ConflictResolution.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/connectionStrings/ConnectionStrings.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/customAnalyzers/DatabaseCustomAnalyzers.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/customSorters/DatabaseCustomSorterTest.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/customSorters/DatabaseCustomSorters.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/documentRevisions/DocumentRevisions.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/tombstones/TombstonesState.tsx
  src/Raven.Studio/typescript/components/pages/database/tasks/createSampleData/CreateSampleData.tsx
Labels: v6.0, Studio

#18731 RavenDB-22501 Exception in studio on delete all items in collection
  src/Raven.Studio/typescript/common/notifications/models/groupedVirtualNotification.ts
  src/Raven.Studio/typescript/common/notifications/models/virtualBulkInsert.ts
  src/Raven.Studio/typescript/common/notifications/models/virtualBulkInsertFailures.ts
  src/Raven.Studio/typescript/common/notifications/models/virtualDeleteByQuery.ts
  src/Raven.Studio/typescript/common/notifications/models/virtualDeleteByQueryFailures.ts
  src/Raven.Studio/typescript/common/notifications/models/virtualUpdateByQuery.ts
  src/Raven.Studio/typescript/common/notifications/models/virtualUpdateByQueryFailures.ts
  src/Raven.Studio/typescript/common/notifications/notificationCenter.ts
Labels: v6.0, Studio

#18726 RavenDB-22447 Incorrect "Connection String Not Defined" Error in SQL …
  src/Raven.Studio/typescript/components/pages/database/tasks/ongoingTasks/panels/RavenEtlPanel.tsx
  src/Raven.Studio/typescript/components/pages/database/tasks/ongoingTasks/panels/ReplicationSinkPanel.tsx
  src/Raven.Studio/typescript/components/pages/database/tasks/ongoingTasks/panels/SqlEtlPanel.tsx
Labels: v6.0, Studio

#18724 RavenDB-21545 For a RavenDB Cloud license do not show Download Now in…
  src/Raven.Studio/typescript/components/pages/resources/about/partials/VersionsSummary.tsx
Labels: v6.0, Studio

#18720 RavenDB-21545 For a RavenDB Cloud license do not show Download Now in…
  src/Raven.Server/Web/System/BuildVersionHandler.cs
  src/Raven.Studio/typescript/viewmodels/shell/about.ts
  src/Raven.Studio/wwwroot/App/views/shell/about.html
Labels: v5.4

#18733 RavenDB-21768 we need to wait for Initialize task to finish, not the Task<Task>
  src/Raven.Client/Documents/Operations/Operation.cs
Labels: v5.4

#18730 RavenDB-21706 marked /databases/*/admin/pull-replication/generate-certificate endpoint as heavy in tests
  test/SlowTests/Authentication/AuthenticationBasicTests.cs
Labels: v5.4

#18713 RavenDB-17474 Set https scheme in Docker automatically if cert options are passed through one of the available channels (5.4)
  docker/ravendb-nanoserver/run-raven.ps1
  docker/ravendb-ubuntu/run-raven.sh
Labels: v5.4

#18737 RavenDB-22484
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.11/WellKnownAdminIssuers.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.18/MonitorLockContentionCount.cs
  src/Raven.Server/Monitoring/Snmp/SnmpOids.cs
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
Labels: v5.4

#18712 RavenDB-17474 Set https scheme in Docker automatically if cert options are passed through one of the available channels
  docker/ravendb-nanoserver/run-raven.ps1
  docker/ravendb-ubuntu/run-raven.sh
Labels: v6.0

#18739 RavenDB-21428 Ongoing tasks view: Subscription connection errors can'…
  src/Raven.Studio/typescript/common/generalUtils.ts
  src/Raven.Studio/typescript/viewmodels/database/status/ongoingTasksStats.ts
  src/Raven.Studio/wwwroot/Content/css/pages/metrics.less
Labels: v6.0, Studio

#18744 RavenDB-20285 Add links to ongoing tasks widget
  src/Raven.Studio/typescript/common/appUrl.ts
  src/Raven.Studio/typescript/viewmodels/resources/widgets/ongoingTasksWidget.ts
  src/Raven.Studio/typescript/widgets/virtualGrid/columns/multiNodeTagsColumn.ts
  src/Raven.Studio/typings/_studio/dto.d.ts
Labels: v5.4, Studio

#18738 RavenDB-21640 Buggy popovers in Client Configuration view
  src/Raven.Studio/typescript/components/pages/database/settings/clientConfiguration/ClientDatabaseConfiguration.tsx
Labels: v6.0, Studio

#18752 RavenDB-22535
  src/Raven.Server/Program.cs
  src/Raven.Server/ServerWide/ServerVersion.cs
  src/Raven.Server/Utils/Cli/CommandLineSwitches.cs
Labels: v6.1

#18747 RavenDB-21683 adding index created timestamp to the result etag calculation in order to avoid a situation where result etag is the same after changing index configuration option that could affect the returned results
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/IndexStorage.cs
  test/SlowTests/Issues/RavenDB_21683.cs
Labels: v5.4

#18743 RavenDB-22426 Replace System.Data.SqlClient NuGet package with Micros…
  src/Raven.Studio/typescript/components/pages/database/settings/connectionStrings/editForms/SqlConnectionString.tsx
  src/Raven.Studio/typings/_studio/dto.d.ts
Labels: v6.0, Studio
