Repository ravendb/ravendb, pull requests merged in 2024-05, with the labels that each got.

#18424 RavenDB-22305 - Missing DirtyMemory from the memory notification
  src/Raven.Server/Dashboard/Cluster/Notifications/MemoryUsageNotificationSender.cs
  src/Raven.Server/Documents/Handlers/Debugging/MemoryDebugHandler.cs
  src/Raven.Server/Documents/TransactionOperationsMerger.cs
  src/Raven.Server/Monitoring/MetricsProvider.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.6/ServerDirtyMemory.cs
  src/Raven.Server/NotificationCenter/OutOfMemoryNotifications.cs
  src/Raven.Server/Utils/Cli/RavenCli.cs
  src/Sparrow.Server/LowMemory/MemoryInformation.cs
  src/Sparrow/LowMemory/DirtyMemoryState.cs
  src/Sparrow/LowMemory/LowMemoryNotification.cs
  src/Sparrow/LowMemory/MemoryInfoResult.cs
  src/Sparrow/Utils/MemoryUtils.cs
  test/Tests.Infrastructure/TestMetrics/TestResourceSnapshotWriter.cs
Labels: v5.4

#18440 RavenDB-22313 Checking cancellation token during the load phase of Elasticsearch, Kafka and RabbitMQ ETLs.
  src/Raven.Server/Documents/ETL/Providers/Elasticsearch/ElasticSearchEtl.cs
  src/Raven.Server/Documents/ETL/Providers/Queue/Kafka/KafkaEtl.cs
  src/Raven.Server/Documents/ETL/Providers/Queue/RabbitMq/RabbitMqEtl.cs
Labels: v5.4

#18459 RavenDB-22036 Added tests and throwing exception on side-by-side reset of replacement index
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  test/SlowTests/Issues/RavenDB-22036.cs
Labels: v6.0

#18460 RavenDB-20246 Identities View: Explain better the meaning of the Document ID Prefix
  src/Raven.Studio/typescript/viewmodels/database/identities/identities.ts
  src/Raven.Studio/wwwroot/App/views/database/identities/identities.html
Labels: v5.4, Studio

#18467 RavenDB-21757 - fix failing test
  test/SlowTests/Sharding/Subscriptions/ShardedSubscriptionClusterTests.cs
Labels: v6.0

#18472 RavenDB-22275 Updated Raven.Client to .NET 8
  src/Raven.Client/Raven.Client.csproj
Labels: v5.4

#18473 RavenDB-22320 JavaScript error breaking Certificates view
  src/Raven.Studio/typescript/viewmodels/manage/certificates.ts
Labels: v5.4, Studio

#18471 RavenDB-22036 Allow resetting an index Side-by-side (studio work)
  src/Raven.Studio/typescript/commands/database/index/resetIndexCommand.ts
  src/Raven.Studio/typescript/components/pages/database/indexes/list/ConfirmResetIndex.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexPanel.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexesPage.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexesPageList.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/list/useIndexesPage.tsx
  src/Raven.Studio/typescript/components/services/IndexesService.ts
  tools/TypingsGenerator/Program.cs
Labels: v6.0

#18475 RavenDB-22330 / RavenDB-13830 / RavenDB-10621 / RavenDB-21987 Skippin…
  test/SlowTests/Issues/RavenDB_10621.cs
Labels: v5.4

#18478 RavenDB-22330 Fixing AllTestsShouldUseRavenFactOrRavenTheoryAttributes test
  test/SlowTests/Tests/TestsInheritanceTests.cs
Labels: v5.4

#18481 RavenDB-21250 Reset selected indexes
  src/Raven.Studio/typescript/components/pages/database/indexes/list/ConfirmResetIndexes.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexPanel.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexSelectActions.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexesPage.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexesPageList.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/list/partials/ResetIndexesButton.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/list/useIndexesPage.tsx
Labels: v6.0, Studio

#18474 RavenDB-7070 Fixing warnings
  src/Raven.Embedded/EmbeddedServer.cs
  src/Raven.Embedded/ProcessHelper.cs
  src/Raven.Server/Documents/ETL/Providers/Elasticsearch/BlittableJsonElasticSerializer.cs
  src/Raven.Server/Documents/ETL/Providers/Elasticsearch/ElasticSearchEtl.cs
  test/FastTests/Corax/Bugs/RavenDB-22285.cs
  test/SlowTests/Server/Documents/ETL/Elasticsearch/ElasticSearchEtlTestBase.cs
  test/SlowTests/Server/Documents/ETL/Elasticsearch/ElasticSearchEtlTests.cs
  test/SlowTests/Server/Documents/ETL/Elasticsearch/RavenDB_17476.cs
  test/SlowTests/Server/Documents/ETL/Elasticsearch/RavenDB_17477.cs
  test/SlowTests/Sharding/ETL/ShardedEtlTests.cs
  test/Tests.Infrastructure/ConnectionString/ElasticSearchTestNodes.cs
Labels: v6.0

#18484 RavenDB-22225 avoid opening write tx in the same test thread
  test/RachisTests/BasicTests.cs
Labels: v5.4

#18453 RavenDB-22322 "Bump version ..." commits should be executed against 'release/v6.0' branch
  scripts/version.ps1
Labels: v6.0

#18493 RavenDB-22348: ReadBigEndianInt64 is missing advance pointer
  src/Voron/ValueReader.cs
Labels: v5.4

#18485 RavenDB-19844 Add the LuceneUnmanagedAllocations to the cluster dashboard
  src/Raven.Server/Dashboard/Cluster/Notifications/MemoryUsageNotificationSender.cs
  src/Raven.Server/Dashboard/Cluster/Notifications/MemoryUsagePayload.cs
  src/Raven.Studio/typescript/models/resources/widgets/memoryUsage.ts
  src/Raven.Studio/wwwroot/App/views/resources/widgets/memoryUsageWidget.html
Labels: v5.4

#18487 RavenDB-22257 Making the transaction owner check on tx dispose to be Debug only.
  src/Raven.Server/Documents/ReplayTxCommandHelper.cs
  src/Voron/Impl/LowLevelTransaction.cs
  test/RachisTests/BasicTests.cs
  test/SlowTests/Voron/Issues/RavenDB_22257.cs
Labels: v5.4

#18463 RavenDB-20934 : add debug info to flaky test
  test/SlowTests/Sharding/ETL/ShardedEtlFailoverTests.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
Labels: v6.0

#18496 RavenDB-21854 : add more debug info to flaky test
  test/SlowTests/Server/Documents/ETL/Raven/BasicRavenEtlTests.cs
  test/Tests.Infrastructure/RavenTestBase.Etl.cs
  test/Tests.Infrastructure/RavenTestBase.Sharding.cs
Labels: v6.0

#18486 5.4 to 6.0 merge
  src/Raven.Client/Documents/Operations/Operation.cs
  src/Raven.Server/Commercial/SetupWizard/LetsEncryptSetupUtils.cs
  src/Raven.Server/Dashboard/Cluster/Notifications/MemoryUsageNotificationSender.cs
  src/Raven.Server/Dashboard/Cluster/Notifications/MemoryUsagePayload.cs
  src/Raven.Server/Documents/ETL/Providers/Elasticsearch/ElasticSearchEtl.cs
  src/Raven.Server/Documents/ETL/Providers/Queue/Kafka/KafkaEtl.cs
  src/Raven.Server/Documents/ETL/Providers/Queue/RabbitMq/RabbitMqEtl.cs
  src/Raven.Server/Documents/Expiration/ExpiredDocumentsCleaner.cs
  src/Raven.Server/Documents/Handlers/Admin/AdminLogsHandler.cs
  src/Raven.Server/Documents/Handlers/Debugging/MemoryDebugHandler.cs
  src/Raven.Server/Documents/ReplayTxCommandHelper.cs
  src/Raven.Server/Documents/TransactionMerger/AbstractTransactionOperationsMerger.cs
  src/Raven.Server/Monitoring/MetricsProvider.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.6/ServerDirtyMemory.cs
  src/Raven.Server/NotificationCenter/OutOfMemoryNotifications.cs
  src/Raven.Server/ServerWide/CompareExchangeExpirationStorage.cs
  src/Raven.Server/Utils/Cli/RavenCli.cs
  src/Raven.Studio/typescript/models/resources/widgets/memoryUsage.ts
  src/Raven.Studio/typescript/viewmodels/database/identities/identities.ts
  src/Raven.Studio/typescript/viewmodels/manage/certificates.ts
  src/Raven.Studio/wwwroot/App/views/database/identities/identities.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editElasticSearchEtlTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editExternalReplicationTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editKafkaEtlTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editOlapEtlTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editPeriodicBackupTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editRabbitMqEtlTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editRavenEtlTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editReplicationHubTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editReplicationSinkTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editSqlEtlTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editSubscriptionTask.html
  src/Raven.Studio/wwwroot/App/views/manage/editServerWideBackup.html
  src/Raven.Studio/wwwroot/App/views/manage/editServerWideExternalReplication.html
  src/Raven.Studio/wwwroot/App/views/partial/taskResponsibleNodeSection.html
  src/Raven.Studio/wwwroot/App/views/partial/taskResponsibleNodeSection_ForBackup.html
  src/Raven.Studio/wwwroot/App/views/resources/addNewNodeToDatabaseGroup.html
  src/Raven.Studio/wwwroot/App/views/resources/widgets/memoryUsageWidget.html
  src/Sparrow.Server/LowMemory/MemoryInformation.cs
  src/Sparrow/Logging/LoggingSource.cs
  src/Sparrow/LowMemory/DirtyMemoryState.cs
  src/Sparrow/LowMemory/LowMemoryNotification.cs
  src/Sparrow/LowMemory/MemoryInfoResult.cs
  src/Sparrow/Utils/MemoryUtils.cs
  src/Voron/Impl/LowLevelTransaction.cs
  src/Voron/StorageEnvironment.cs
  src/Voron/ValueReader.cs
  test/FastTests/Voron/PostingLists/PostingListLeafPageTests.cs
  test/RachisTests/BasicTests.cs
  test/SlowTests/Issues/RavenDB_10621.cs
  test/SlowTests/SparrowTests/DownloadLogsCommand.cs
  test/SlowTests/SparrowTests/LoggingSourceTests.cs
  test/SlowTests/Tests/TestsInheritanceTests.cs
  test/SlowTests/Tools/SetupSecuredClusterUsingRvn.cs
  test/SlowTests/Voron/Issues/RavenDB_22257.cs
  test/Tests.Infrastructure/TestMetrics/TestResourceSnapshotWriter.cs
Labels: v6.0

#18498 RavenDB-22339 avoid NRE in ShardExecutor Dispose
  src/Raven.Server/Documents/Sharding/Executors/ShardExecutor.cs
Labels: v6.0

#18511 RavenDB-17620 Retrying ocassionally failing test
  test/SlowTests/Issues/RavenDB_17237.cs
Labels: v5.4

#18509 RavenDB-22188 Cannot view a MultiGet request in the Traffic Watch - l…
  src/Raven.Studio/typescript/viewmodels/manage/trafficWatch.ts
Labels: v5.4, Studio

#18512 RavenDB-22157 - dispose DocumentInfoHelper in ShardedIncomingReplicat…
  src/Raven.Server/Documents/Sharding/Handlers/ShardedIncomingReplicationHandler.cs
Labels: v6.0

#18515 RavenDB-21690 Better indication if query results are from cache or we…
  src/Raven.Studio/typescript/viewmodels/database/query/query.ts
  src/Raven.Studio/wwwroot/App/views/database/query/query.html
Labels: v6.0, Studio

#18514 RavenDB-21923 Add the connectivity to the license server to the Expir…
  src/Raven.Studio/typescript/viewmodels/shell/registration.ts
  src/Raven.Studio/wwwroot/App/views/shell/about.html
  src/Raven.Studio/wwwroot/App/views/shell/registration.html
  src/Raven.Studio/wwwroot/Content/css/pages/registration.less
  src/Raven.Studio/wwwroot/Content/css/styles-common.less
Labels: v5.4, Studio

#18508 RavenDB-16665 better detection of related document ids
  src/Raven.Studio/typescript/common/helpers/database/documentHelpers.spec.ts
  src/Raven.Studio/typescript/common/helpers/database/documentHelpers.ts
Labels: v5.4, Studio

#18505 RavenDB-19844 - Add the LuceneManagedAllocations to the cluster dashboard
  src/Raven.Server/Dashboard/Cluster/Notifications/MemoryUsageNotificationSender.cs
  src/Raven.Server/Dashboard/Cluster/Notifications/MemoryUsagePayload.cs
  src/Raven.Studio/typescript/models/resources/widgets/memoryUsage.ts
  src/Raven.Studio/wwwroot/App/views/resources/widgets/memoryUsageWidget.html
Labels: v5.4

#18507 5.4 to 6.0 merge
  src/Raven.Server/Documents/Document.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Indexes/Errors/FaultyInMemoryIndex.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/MapIndexBase.cs
  src/Raven.Server/Documents/Indexes/MapReduce/MapReduceIndexBase.cs
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxIndexReadOperation.cs
  src/Raven.Server/Documents/Indexes/Persistence/IndexOperationBase.cs
  src/Raven.Server/Documents/Indexes/Persistence/IndexQueryingScopeBase.cs
  src/Raven.Server/Documents/Indexes/Persistence/IndexReadOperationBase.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/LuceneIndexQueryingScope.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/LuceneIndexReadOperation.cs
  src/Raven.Server/Documents/Indexes/Persistence/QueryFilter.cs
  src/Raven.Server/Documents/Indexes/Static/Counters/MapCountersIndex.cs
  src/Raven.Server/Documents/Indexes/Static/TimeSeries/MapTimeSeriesIndex.cs
  src/Raven.Server/Documents/Patch/BlittableObjectInstance.cs
  src/Raven.Server/Documents/Patch/JavaScriptUtils.cs
  src/Raven.Server/Documents/Patch/ScriptRunner.cs
  src/Raven.Server/Documents/Queries/CollectionQueryEnumerable.cs
  src/Raven.Server/Documents/Queries/QueriedDocument.cs
  src/Raven.Server/Documents/Queries/Results/IQueryResultRetriever.cs
  src/Raven.Server/Documents/Queries/Results/MapQueryResultRetriever.cs
  src/Raven.Server/Documents/Queries/Results/MapReduceQueryResultRetriever.cs
  src/Raven.Server/Documents/Queries/Results/QueriedDocumentCache.cs
  src/Raven.Server/Documents/Queries/Results/QueryResultRetrieverBase.cs
  src/Raven.Server/Documents/Queries/Results/Sharding/ShardedMapReduceResultRetriever.cs
  src/Raven.Server/Documents/Queries/Results/TimeSeries/TimeSeriesRetriever.cs
  src/Raven.Server/Documents/ResourceCache.cs
  src/Raven.Server/Documents/Sharding/Queries/ShardedQueryResultDocument.cs
  src/Raven.Server/Documents/Sharding/Queries/ShardedQueryResultDocumentExtensions.cs
  src/Raven.Server/Json/BlittableJsonTraverserHelper.cs
  src/Raven.Server/Utils/Enumerators/PulsedTransactionEnumerator.cs
  src/Raven.Server/Utils/LruDictionary.cs
  src/Voron/Constants.cs
  src/Voron/Impl/Transaction.cs
  test/FastTests/Server/Documents/Indexing/BasicAnalyzers.cs
  test/FastTests/Server/Documents/Indexing/Lucene/LuceneDocumentConverterTests.cs
  test/SlowTests/Issues/RavenDB-17134.cs
  test/SlowTests/Issues/RavenDB-21693.cs
  test/SlowTests/Issues/RavenDB_19033.cs
  test/SlowTests/Issues/RavenDB_21900.cs
Labels: v6.0

#18519 RavenDB-22308 Throw meaningful exception when HttpMessageHandler doesn't accept client certificates
  src/Raven.Client/Http/RequestExecutor.cs
Labels: v5.4

#18491 RavenDB-22316: Fixed the case where the last symbol has to be skipped.
  src/Sparrow.Server/Compression/Encoder3Gram.cs
  test/FastTests/Sparrow/Encoder3GramTests.cs
Labels: v5.4

#18525 RavenDB-22278 Make sure ResponseStream, MemoryStream and StreamReader are disposed - v5.4
  src/Raven.Client/Http/RequestExecutor.cs
Labels: v5.4

#18518 RavenDB-22278 Make sure ResponseStream, MemoryStream and StreamReader are disposed in RequestExecutor.ReadExceptionFromServer
  src/Raven.Client/Http/RequestExecutor.cs
Labels: v6.0

#18531 RavenDB-22372 adjust settings.json permissions after copying into the…
  docker/ravendb-ubuntu/Dockerfile.arm32v7
  docker/ravendb-ubuntu/Dockerfile.arm64v8
  docker/ravendb-ubuntu/Dockerfile.x64
Labels: v6.0

#18533 RavenDB-22362 Unify audit log lines v6.0
  src/Raven.Server/Documents/Handlers/Admin/Processors/Indexes/AbstractAdminIndexHandlerProcessorForPut.cs
  src/Raven.Server/Documents/Handlers/Admin/Processors/Sorters/AbstractAdminSortersHandlerProcessorForDelete.cs
  src/Raven.Server/Documents/Handlers/Admin/Processors/Sorters/AbstractAdminSortersHandlerProcessorForPut.cs
  src/Raven.Server/Documents/Handlers/Processors/Analyzers/AbstractAdminAnalyzersHandlerProcessorForDelete.cs
  src/Raven.Server/Documents/Handlers/Processors/Analyzers/AbstractAdminAnalyzersHandlerProcessorForPut.cs
  src/Raven.Server/Documents/Handlers/Processors/Indexes/AbstractIndexHandlerProcessorForDelete.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
  src/Raven.Server/RavenServer.cs
  src/Raven.Server/Web/Authentication/AdminCertificatesHandler.cs
  src/Raven.Server/Web/Authentication/TwoFactorAuthenticationHandler.cs
  src/Raven.Server/Web/RequestHandler.Audit.cs
  src/Raven.Server/Web/RequestHandler.cs
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
  src/Raven.Server/Web/System/Analyzers/AdminAnalyzersHandler.cs
  src/Raven.Server/Web/System/DatabasesHandler.cs
  src/Raven.Server/Web/System/Sorters/AdminSortersHandler.cs
Labels: v6.0

#18535 RavenDB-20603 About page - fix TLS 1.2 -> 1.3
  src/Raven.Studio/typescript/components/pages/resources/about/partials/LicenseDetails.tsx
Labels: v6.0, Studio

#18536 5.4 to 6.0 merge
  src/Raven.Client/Documents/Linq/RavenQueryProviderProcessor.cs
  src/Raven.Client/Http/RequestExecutor.cs
  src/Sparrow.Server/Compression/Encoder3Gram.cs
  test/FastTests/Issues/RavenDB_12235.cs
  test/FastTests/Sparrow/Encoder3GramTests.cs
  test/SlowTests/Client/Queries/FullTextSearch.cs
  test/SlowTests/Issues/RavenDB-22323.cs
  test/SlowTests/Issues/RavenDB_12346.cs
Labels: v6.0

#18539 merge release/v6.0 to v6.0
  src/CommonAssemblyInfo.cs
  src/Raven.Client/Properties/VersionInfo.cs
Labels: v6.0

#18541 RavenDB-7070 wait for 15 seconds and not 15,000,000 ms
  test/SlowTests/Issues/RavenDB-19379.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
Labels: v5.4

#18540 RavenDB-22372 save one RUN call in the Dockerfile
  docker/ravendb-ubuntu/Dockerfile.arm32v7
  docker/ravendb-ubuntu/Dockerfile.arm64v8
  docker/ravendb-ubuntu/Dockerfile.x64
Labels: v6.0

#18477 RavenDB-22305 - Missing DirtyMemory from the memory notification
  src/Raven.Server/Documents/Handlers/Debugging/MemoryDebugHandler.cs
  src/Sparrow.Server/LowMemory/MemoryInformation.cs
  test/Tests.Infrastructure/TestMetrics/TestResourceSnapshotWriter.cs
Labels: v6.0

#18543 5.4 to 6.0 merge
  test/SlowTests/Issues/RavenDB-19379.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
Labels: v6.0

#18538 RavenDB-22376 - Revisions.GetAsync fails in sharding
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Revisions/ShardedRevisionsHandlerProcessorForGetRevisions.cs
  test/SlowTests/SlowTests/Issues/RavenDB-22376.cs
Labels: v6.0

#18544 RavenDB-22377 Clear previous projection cache when performing `CacheClean` on PulseTransaction to avoid holding invalid pointers.
  src/Raven.Server/Documents/Queries/Results/QueriedDocumentCache.cs
  src/Raven.Server/Documents/Queries/Results/QueryResultRetrieverBase.cs
  test/SlowTests/Verifications/RavenDB_2239.cs
Labels: v5.4

#18547 RavenDB-22324 - Fix RavenDB_20628 failing tests
  test/SlowTests/Issues/RavenDB-20628.cs
Labels: v5.4

#18550 RavenDB-22385 Remove community limits on indexes
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexesPageAboutView.tsx
  src/Raven.Studio/typescript/components/pages/resources/about/partials/LicenseDetails.tsx
Labels: v6.0, Studio

#18552 RavenDB-22199 Flush reuqest stream to send the headers in all customized HttpContent implementations
  src/Raven.Client/Documents/BulkInsert/BulkInsertOperation.cs
  src/Raven.Client/Documents/Smuggler/DatabaseSmuggler.cs
  src/Raven.Client/Http/AttachmentStreamContent.cs
  src/Raven.Client/Json/BlittableJsonContent.cs
  src/Raven.Server/Documents/PeriodicBackup/ProgressableStreamContent.cs
Labels: v5.4

#18558 RavenDB-22378 - fix failing test
  test/SlowTests/Issues/RavenDB-21693.cs
  test/SlowTests/Issues/RavenDB_19033.cs
Labels: v6.0

#18557 RavenDB-22399 Decrypting and Encrypting streams should not use synchronous IO in async methods
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/PeriodicBackup/BackupTask.cs
  src/Raven.Server/Documents/PeriodicBackup/EncryptedBackup.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreBackupTaskBase.cs
  src/Raven.Server/Smuggler/Documents/Handlers/SmugglerHandler.cs
Labels: v5.4

#18560 RavenDB-22400 -SlowTests.Server.Documents.PeriodicBackup.PeriodicBackupTestsSlow.can_snapshot_and_restore_with_subscription
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
Labels: v5.4

#18563 HRINT-3664 - license modifications
  src/Raven.Server/Commercial/LicenseStatus.cs
Labels: v6.0

#18575 RavenDB-22366 XML docs warnings in IncludeBuilder
  src/Raven.Client/Documents/Session/Loaders/IncludeBuilder.cs
Labels: v6.0

#18572 RavenDB-22414 License - MaxClusterSize equal 0 means Infinity
  src/Raven.Studio/typescript/components/common/shell/licenseSlice.ts
  src/Raven.Studio/typescript/components/pages/resources/about/partials/LicenseDetails.tsx
Labels: v6.0, Studio

#18570 RavenDB-22196 Show referenced collections on v6.0
  src/Raven.Studio/typescript/components/models/indexes.ts
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexPanel.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexesStatsReducer.ts
  src/Raven.Studio/typescript/components/pages/database/status/statistics/partials/IndexesDatabaseStats.tsx
  src/Raven.Studio/typescript/components/pages/database/status/statistics/store/models.d.ts
  src/Raven.Studio/typescript/components/pages/database/status/statistics/store/statisticsViewSlice.ts
  src/Raven.Studio/typescript/test/fixtures/indexes_stats.json
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon/referenced-collections.svg
Labels: v6.0, Studio

#18571 RavenDB-22375
  src/Raven.Server/Documents/Handlers/Processors/Batches/AbstractBatchHandlerProcessorForBulkDocs.cs
  src/Raven.Server/Documents/Handlers/Processors/Documents/AbstractDocumentHandlerProcessorForGet.cs
  src/Raven.Server/Documents/Handlers/Processors/Queries/AbstractQueriesHandlerProcessorForGet.cs
  src/Raven.Server/Web/AbstractQueryStringParameters.cs
Labels: v6.0

#18581 RavenDB-7070 updated NuGet packages
  bench/Regression.Benchmark/Regression.Benchmark.csproj
  src/Raven.Server/Raven.Server.csproj
  test/BenchmarkTests/BenchmarkTests.csproj
  test/EmbeddedTests/EmbeddedTests.csproj
  test/FastTests/FastTests.csproj
  test/InterversionTests/InterversionTests.csproj
  test/LicenseTests/LicenseTests.csproj
  test/RachisTests/RachisTests.csproj
  test/SlowTests/SlowTests.csproj
  test/StressTests/StressTests.csproj
  tools/Raven.Migrator/Raven.Migrator.csproj
Labels: v5.4

#18580 RavenDB-7070 updated NuGet packages
  bench/Micro.Benchmark/Micro.Benchmark.csproj
  bench/Regression.Benchmark/Regression.Benchmark.csproj
  src/Raven.Server/Raven.Server.csproj
  test/BenchmarkTests/BenchmarkTests.csproj
  test/EmbeddedTests/EmbeddedTests.csproj
  test/FastTests/FastTests.csproj
  test/InterversionTests/InterversionTests.csproj
  test/LicenseTests/LicenseTests.csproj
  test/RachisTests/RachisTests.csproj
  test/SlowTests/SlowTests.csproj
  test/StressTests/StressTests.csproj
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
  tools/Raven.Migrator/Raven.Migrator.csproj
  tools/Voron.Recovery/Voron.Recovery.csproj
Labels: v6.0

#18568 RavenDB-22410 Corax search - analyzer produces multiple tokens from a single word
  src/Corax/Querying/IndexSearcher.Search.cs
  test/SlowTests/Issues/RavenDB_22410.cs
Labels: Corax, v6.0

#18561 RavenDB-22404 - Failure to create the cluster debug package
  src/Raven.Server/Documents/Handlers/Debugging/ServerWideDebugInfoPackageHandler.cs
Labels: v5.4

#18582 5.4 to 6.0 merge
  docker/ravendb-nanoserver/Dockerfile.1809
  docker/ravendb-nanoserver/Dockerfile.ltsc2022
  docker/ravendb-ubuntu/Dockerfile.arm32v7
  docker/ravendb-ubuntu/Dockerfile.arm64v8
  docker/ravendb-ubuntu/Dockerfile.x64
  src/Raven.Server/Documents/Handlers/Debugging/ServerWideDebugInfoPackageHandler.cs
  src/Raven.Server/Documents/Handlers/Processors/Batches/BatchHandlerProcessorForBulkDocs.cs
  src/Raven.Server/Properties/Settings/settings.docker.posix.json
  src/Raven.Server/Properties/Settings/settings.docker.windows.json
  test/SlowTests/Issues/RavenDB-17157.cs
  test/SlowTests/Issues/RavenDB-18373.cs
  test/SlowTests/Issues/RavenDB-18688.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
Labels: v6.0

#18576 RavenDB-22394: On update subscription populate PinToMentorNode from e…
  src/Raven.Client/Documents/Commands/UpdateSubscriptionCommand.cs
  src/Raven.Client/Documents/Subscriptions/SubscriptionCriteria.cs
  src/Raven.Client/Extensions/BlittableJsonTextWriterExtensions.cs
  src/Raven.Server/Documents/Handlers/Processors/Subscriptions/AbstractSubscriptionsHandlerProcessorForGetSubscription.cs
  src/Raven.Server/Documents/Handlers/Processors/Subscriptions/AbstractSubscriptionsHandlerProcessorForPostSubscription.cs
  src/Raven.Server/Documents/Sharding/Handlers/ShardedSubscriptionsHandler.cs
  src/Raven.Server/ServerWide/Commands/Sharding/PutShardedSubscriptionCommand.cs
  test/FastTests/Client/Subscriptions/SubscriptionsBasic.cs
Labels: v6.0

#18585 RavenDB-22416 - add tests
  test/FastTests/Server/Documents/Indexing/Static/JavaScriptIndexTests.cs
  test/SlowTests/Core/ScriptedPatching/ScriptedPatchTests.cs
Labels: v6.0

#18579 RavenDB-21679 Fix NRE
  src/Raven.Server/Documents/Handlers/Processors/Smuggler/AbstractSmugglerHandlerProcessorForImportDir.cs
Labels: v6.0

#18588 RavenDB-22369 During the index entry building phase, also check if the field has the `Search` option.
  src/Corax/Indexing/IndexWriter.IndexEntryBuilder.cs
  src/Corax/Indexing/IndexWriter.cs
  src/Corax/Indexing/IndexedField.cs
Labels: v6.0

#18591 RavenDB-22427 Cannot use 'in' operator to search for 'MaxClusterSize' in null
  src/Raven.Studio/typescript/components/common/shell/licenseSlice.ts
Labels: v6.0, Studio

#18593 RavenDB-22428 Test fix : extensive memory testing is done only on X64 platforms.
  test/SlowTests/Corax/GrowableBufferTests.cs
Labels: v6.0

#18569 RavenDB-17122 use async method instead of AsyncHelpers.RunSync in async context
  src/Raven.Client/Documents/BulkInsert/BulkInsertOperation.cs
  src/Raven.Client/Documents/Identity/GenerateEntityIdOnTheClient.cs
  src/Raven.Client/Documents/Session/AsyncDocumentSession.cs
  src/Raven.Client/Documents/Session/DocumentSession.cs
  src/Raven.Client/Documents/Session/InMemoryDocumentSessionOperations.cs
  src/Raven.Client/Documents/Subscriptions/SubscriptionBatch.cs
  src/Raven.Client/Json/Serialization/NewtonsoftJson/Internal/NewtonsoftJsonBlittableEntitySerializer.cs
Labels: v6.0
