Repository ravendb/ravendb, pull requests merged in 2024-08, with the labels that each got.

#18952 RavenDB-22357 Wrong db info in database list in studio
  src/Raven.Studio/typescript/components/pages/resources/databases/DatabasesPage.spec.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/DatabasesPage.stories.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/ValidDatabasePropertiesPanel.spec.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/ValidDatabasePropertiesPanel.tsx
Labels: v6.0, Studio

#18963 RavenDB-22719 '_.remove' replaced with 'filter' bug
  src/Raven.Studio/typescript/common/helpers/database/collectionsTracker.ts
  src/Raven.Studio/typescript/common/notifications/protractedCommandsDetector.ts
Labels: v6.0, Studio

#18964 RavenDB-22720 Order of databases in the db switcher is reversed
  src/Raven.Studio/typescript/components/shell/studioSearchWithDatabaseSelector/databaseSwitcher/DatabaseSwitcher.tsx
Labels: Studio, v6.1

#18970 RavenDB-22627 fixing test
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreBackupTaskBase.cs
Labels: v5.4

#18966 5.4 to 6.0 merge
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/AbstractRestoreBackupTask.cs
  src/Raven.Server/Documents/Replication/Incoming/IncomingPullReplicationHandler.cs
  src/Raven.Server/ServerWide/Context/DocumentsOperationContext.cs
  src/Raven.Server/ServerWide/JsonDeserializationCluster.cs
  src/Raven.Server/Smuggler/Documents/StreamDestination.cs
  src/Raven.Server/Smuggler/Documents/StreamSource.cs
  src/Raven.Server/Utils/ChangeVector.cs
  test/SlowTests/Issues/FilteredReplicationTests.cs
  test/SlowTests/Issues/RavenDB-17650.cs
  test/SlowTests/Smuggler/BackupDatabaseRecordTests.cs
Labels: v6.0

#18972 6.0 to 6.1 merge
  src/Corax/Querying/Matches/SortingMatches/CompactKeyComparer.cs
  src/Corax/Querying/Matches/SortingMatches/HeapSorterBuilder.cs
  src/Corax/Querying/Matches/SortingMatches/NumericalMaxHeapSorter.cs
  src/Corax/Querying/Matches/SortingMatches/SortingMatch.BasicsComparers.cs
  src/Corax/Querying/Matches/SortingMatches/SortingMatch.Comparers.cs
  src/Corax/Querying/Matches/SortingMatches/SortingMatch.cs
  src/Corax/Querying/Matches/SortingMatches/SortingMultiMatch.Comparers.cs
  src/Corax/Querying/Matches/SortingMatches/SortingMultiMatch.IndirectComparers.cs
  src/Corax/Querying/Matches/SortingMatches/SortingMultiMatch.cs
  src/Corax/Querying/Matches/SortingMatches/TextualMaxHeapSorter.cs
  src/Corax/Querying/TermsReader.cs
  src/Corax/Utils/Spatial/SpatialResult.cs
  src/Corax/Utils/Spatial/SpatialUtils.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/AbstractRestoreBackupTask.cs
  src/Raven.Server/Documents/Replication/Incoming/IncomingPullReplicationHandler.cs
  src/Raven.Server/ServerWide/Context/DocumentsOperationContext.cs
  src/Raven.Server/ServerWide/JsonDeserializationCluster.cs
  src/Raven.Server/Smuggler/Documents/StreamDestination.cs
  src/Raven.Server/Smuggler/Documents/StreamSource.cs
  src/Raven.Server/Utils/ChangeVector.cs
  src/Raven.Studio/typescript/common/notifications/protractedCommandsDetector.ts
  src/Raven.Studio/typescript/components/pages/resources/databases/DatabasesPage.spec.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/DatabasesPage.stories.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/ValidDatabasePropertiesPanel.spec.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/ValidDatabasePropertiesPanel.tsx
  src/Voron/Util/ContextBoundNativeList.cs
  test/FastTests/Corax/CompoundSorting.cs
  test/FastTests/Corax/RavenDB_22561.cs
  test/FastTests/Corax/SortingComparers.cs
  test/SlowTests/Corax/RavenDB_21818.cs
  test/SlowTests/Issues/FilteredReplicationTests.cs
  test/SlowTests/Issues/RavenDB-17650.cs
  test/SlowTests/Issues/RavenDB_22504.cs
  test/SlowTests/Smuggler/BackupDatabaseRecordTests.cs
Labels: v6.1

#18967 RavenDB-22727 Fixes after npm update
  src/Raven.Studio/typescript/common/settings/abstractSettings.ts
  src/Raven.Studio/typescript/common/typeUtils.spec.ts
  src/Raven.Studio/typescript/common/typeUtils.ts
  src/Raven.Studio/typescript/components/common/ButtonWithSpinner.tsx
  src/Raven.Studio/typescript/components/common/Form.tsx
Labels: v6.0, Studio

#18968 RavenDB-22698 Making more strict the parsing of LazyStringParser.TryParseTimeSpan() by not skipping any characters when searching for '.' character separating milliseconds
  src/Sparrow/Json/LazyStringParser.cs
  test/FastTests/Utils/TimeParsing.cs
Labels: v5.4

#18965 RavenDB-21634 Adjusting the assertion so we'll have more details once it fails again
  test/SlowTests/Server/Documents/Expiration/ExpirationTests.cs
Labels: v6.0

#18974 RavenDB-7070 removed dead code
  src/Raven.Server/ServerWide/Context/TransactionOperationContext.cs
Labels: v6.0

#18977 RavenDB-22734 - StressTests.Issues.FilteredReplicationTestsStress.Si…
  test/StressTests/Issues/FilteredReplicationTestsStress.cs
Labels: v5.4

#18962 RavenDB-22661 implemented cleanup mechanism for PoolOfThreads
  src/Raven.Server/Utils/PoolOfThreads.cs
Labels: v5.4

#18976 RavenDB-22729 : Prevent adding prefixes with different casing
  src/Raven.Server/ServerWide/ShardingStore.cs
  test/SlowTests/Sharding/PrefixedSharding.cs
Labels: v6.1

#18980 5.4 to 6.0 merge
  src/Raven.Server/Utils/PoolOfThreads.cs
  src/Sparrow/Json/LazyStringParser.cs
  test/FastTests/Utils/TimeParsing.cs
  test/StressTests/Issues/FilteredReplicationTestsStress.cs
Labels: v6.0

#18889 RavenDB-20200: Fix for SlowTests.Issues.RavenDB_15409.DoNotCallUpdateLicenseLimitsCommandOnEveryLeaderChange
  test/SlowTests/Issues/RavenDB_15409.cs
  test/Tests.Infrastructure/RavenTestBase.Cluster.cs
Labels: v5.4

#18985 RavenDB-22627 - fix writing of Studio and RevisionsForConflicts fields in db record on restore
  src/Raven.Server/Smuggler/Documents/StreamDestination.cs
Labels: v5.4

#18983 CSV-763 Remove dryice and override uglify-js version
  src/Raven.Studio/aceBuild/.nvmrc
  src/Raven.Studio/aceBuild/Makefile.dryice.js
  src/Raven.Studio/aceBuild/package-lock.json
  src/Raven.Studio/aceBuild/package.json
Labels: v5.4, Studio

#18948 RavenDB-22709 - Pull Replication Connection Failure When Two Sinks Have the Same Database Name
  src/Raven.Client/Documents/Operations/Replication/PullReplicationAsHub.cs
  src/Raven.Client/Documents/Operations/Replication/PullReplicationAsSink.cs
  src/Raven.Client/Documents/Operations/Replication/PullReplicationDefinition.cs
  src/Raven.Client/Documents/Replication/ReplicationNode.cs
  src/Raven.Server/Documents/Replication/Outgoing/OutgoingPullReplicationHandler.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  test/SlowTests/Issues/RavenDB_22709.cs
Labels: v6.0

#18949 RavenDB-22269 Audit log on database configuration change
  src/Raven.Server/Documents/Handlers/Admin/AdminConfigurationHandler.cs
Labels: v5.4

#18950 RavenDB-22269 Audit log on database configuration change
  src/Raven.Server/Documents/Handlers/Admin/Processors/Configuration/AbstractAdminConfigurationHandlerProcessorForPutSettings.cs
Labels: v6.0

#18992 5.4 to 6.0 merge
  src/Raven.Client/Documents/Operations/Replication/PullReplicationAsHub.cs
  src/Raven.Client/Documents/Operations/Replication/PullReplicationDefinition.cs
  src/Raven.Client/Documents/Smuggler/SmugglerResult.cs
  src/Raven.Server/Dashboard/Cluster/AbstractClusterDashboardNotificationSender.cs
  src/Raven.Server/Dashboard/ThreadsInfoNotificationSender.cs
  src/Raven.Server/Documents/Handlers/Processors/Batches/BatchHandlerProcessorForBulkDocs.cs
  src/Raven.Server/Documents/HugeDocuments.cs
  src/Raven.Server/Documents/Replication/Outgoing/OutgoingPullReplicationHandler.cs
  src/Raven.Server/Monitoring/ServerLimitsMonitor.cs
  src/Raven.Server/NotificationCenter/AbstractNotificationCenter.cs
  src/Raven.Server/NotificationCenter/BackgroundWork/PostponedNotificationsSender.cs
  src/Raven.Server/NotificationCenter/ConflictRevisionsExceeded.cs
  src/Raven.Server/NotificationCenter/ConnectedWatcher.cs
  src/Raven.Server/NotificationCenter/EtlNotifications.cs
  src/Raven.Server/NotificationCenter/Handlers/DatabaseNotificationCenterHandler.cs
  src/Raven.Server/NotificationCenter/Handlers/Processors/AbstractDatabaseNotificationCenterHandlerProcessorForWatch.cs
  src/Raven.Server/NotificationCenter/Handlers/ServerNotificationCenterHandler.cs
  src/Raven.Server/NotificationCenter/Indexing.cs
  src/Raven.Server/NotificationCenter/NotificationTableValue.cs
  src/Raven.Server/NotificationCenter/NotificationsBase.cs
  src/Raven.Server/NotificationCenter/NotificationsStorage.cs
  src/Raven.Server/NotificationCenter/Paging.cs
  src/Raven.Server/NotificationCenter/RequestLatency.cs
  src/Raven.Server/NotificationCenter/SlowWriteNotifications.cs
  src/Raven.Server/NotificationCenter/TombstoneNotifications.cs
  src/Raven.Server/Smuggler/Documents/StreamDestination.cs
  src/Raven.Server/Utils/ExceptionHelper.cs
  src/Voron/Impl/Backup/StreamExtensions.cs
  src/Voron/Impl/Compaction/StorageCompaction.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/Util/DataCopier.cs
  test/SlowTests/Issues/FilteredReplicationTests.cs
  test/SlowTests/Issues/RavenDB_15409.cs
  test/Tests.Infrastructure/RavenTestBase.Cluster.cs
Labels: v6.0

#18991 RavenDB-22739 Fixing the concurrent modification / usage of DynamicJsonValue.ModificationsIndex in a static instance of AggressiveCachingPulseValue which resulted in sending invalid JSON via Changes API and missing invalidation of the cache in RavenDB Client
  src/Raven.Server/Documents/Changes/AbstractChangesClientConnection.cs
  src/Raven.Server/Documents/Changes/ChangesClientConnection.cs
Labels: v6.0

#18987 RavenDB-22679 Added test for case from Github Discussions
  test/SlowTests/Issues/RavenDB_22679_GH_Discussions_18969.cs
Labels: v6.0

#18984 RavenDB-22627 - Missing database record properties on full backup restore - v6.0
  src/Raven.Client/Documents/Smuggler/DatabaseSmugglerOptions.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/AbstractRestoreBackupTask.cs
  src/Raven.Server/Smuggler/Documents/ShardedDatabaseSmuggler.cs
  src/Raven.Server/Smuggler/Documents/StreamDestination.cs
  src/Raven.Server/Smuggler/Documents/StreamSource.cs
  test/SlowTests/Smuggler/BackupDatabaseRecordTests.cs
Labels: v6.0

#18994 RavenDB-22740 bumped version to 6.2
  .github/workflows/FastTests.yml
  .github/workflows/StudioTests.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/studioConventions.yml
  SECURITY.md
  docker/common.ps1
  docker/compose/linux-cluster/docker-compose.yml
  docker/compose/win-cluster/docker-compose.yml
  docker/debug/build-ubuntu-debug.ps1
  docker/debug/ravendb-ubuntu-debug/Dockerfile
  docker/manifest/manifest.yml
  docker/readme.md
  docker/run-linux.ps1
  docker/run-nanoserver.ps1
  docs/readme.linux.txt
  scripts/certificates/powershell/dev-create-authenticated-cluster-with-subdomains.ps1
  scripts/certificates/powershell/dev-create-authenticated-cluster.ps1
  scripts/version.ps1
  src/CommonAssemblyInfo.cs
  src/Raven.Client/DocumentationUrls.cs
  src/Raven.Client/Properties/VersionInfo.cs
  src/Raven.Embedded/Raven.Embedded.nuspec.template
  src/Raven.Server/Monitoring/Snmp/Templates/zabbix_ravendb_template.xml
  src/Raven.Server/Program.cs
  src/Raven.Server/RavenServer.cs
  src/Raven.Server/ServerWide/ServerVersion.cs
  src/Raven.Studio/typescript/commands/commandBase.ts
  src/Raven.Studio/wwwroot/version.txt
Labels: v6.2

#18995 6.0 to 6.1 merge
  src/Raven.Client/Documents/Operations/Replication/PullReplicationAsHub.cs
  src/Raven.Client/Documents/Operations/Replication/PullReplicationAsSink.cs
  src/Raven.Client/Documents/Operations/Replication/PullReplicationDefinition.cs
  src/Raven.Client/Documents/Replication/ReplicationNode.cs
  src/Raven.Client/Documents/Smuggler/DatabaseSmugglerOptions.cs
  src/Raven.Client/Documents/Smuggler/SmugglerResult.cs
  src/Raven.Server/Dashboard/Cluster/AbstractClusterDashboardNotificationSender.cs
  src/Raven.Server/Dashboard/ThreadsInfoNotificationSender.cs
  src/Raven.Server/Documents/Changes/AbstractChangesClientConnection.cs
  src/Raven.Server/Documents/Changes/ChangesClientConnection.cs
  src/Raven.Server/Documents/Handlers/Admin/Processors/Configuration/AbstractAdminConfigurationHandlerProcessorForPutSettings.cs
  src/Raven.Server/Documents/Handlers/Processors/Batches/BatchHandlerProcessorForBulkDocs.cs
  src/Raven.Server/Documents/HugeDocuments.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/AbstractRestoreBackupTask.cs
  src/Raven.Server/Documents/Replication/Outgoing/OutgoingPullReplicationHandler.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/Monitoring/ServerLimitsMonitor.cs
  src/Raven.Server/NotificationCenter/AbstractNotificationCenter.cs
  src/Raven.Server/NotificationCenter/BackgroundWork/PostponedNotificationsSender.cs
  src/Raven.Server/NotificationCenter/ConflictRevisionsExceeded.cs
  src/Raven.Server/NotificationCenter/ConnectedWatcher.cs
  src/Raven.Server/NotificationCenter/EtlNotifications.cs
  src/Raven.Server/NotificationCenter/Handlers/DatabaseNotificationCenterHandler.cs
  src/Raven.Server/NotificationCenter/Handlers/Processors/AbstractDatabaseNotificationCenterHandlerProcessorForWatch.cs
  src/Raven.Server/NotificationCenter/Handlers/ServerNotificationCenterHandler.cs
  src/Raven.Server/NotificationCenter/Indexing.cs
  src/Raven.Server/NotificationCenter/NotificationTableValue.cs
  src/Raven.Server/NotificationCenter/NotificationsBase.cs
  src/Raven.Server/NotificationCenter/NotificationsStorage.cs
  src/Raven.Server/NotificationCenter/Paging.cs
  src/Raven.Server/NotificationCenter/RequestLatency.cs
  src/Raven.Server/NotificationCenter/SlowWriteNotifications.cs
  src/Raven.Server/NotificationCenter/TombstoneNotifications.cs
  src/Raven.Server/Smuggler/Documents/ShardedDatabaseSmuggler.cs
  src/Raven.Server/Smuggler/Documents/StreamDestination.cs
  src/Raven.Server/Smuggler/Documents/StreamSource.cs
  src/Raven.Server/Utils/ExceptionHelper.cs
  src/Voron/Impl/Backup/StreamExtensions.cs
  src/Voron/Impl/Compaction/StorageCompaction.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  src/Voron/Util/DataCopier.cs
  test/SlowTests/Issues/FilteredReplicationTests.cs
  test/SlowTests/Issues/RavenDB_15409.cs
  test/SlowTests/Issues/RavenDB_22679_GH_Discussions_18969.cs
  test/SlowTests/Issues/RavenDB_22709.cs
  test/SlowTests/Smuggler/BackupDatabaseRecordTests.cs
  test/Tests.Infrastructure/RavenTestBase.Cluster.cs
Labels: v6.1

#18997 RavenDB-22739 Adding a test case (it was failing ocassionally since the issue was racy)
  test/SlowTests/Issues/RavenDB_22739.cs
Labels: v6.0

#18996 RavenDB-22739 Fixing the concurrent modification / usage of DynamicJsonValue.ModificationsIndex in a static instance of AggressiveCachingPulseValue which resulted in sending invalid JSON via Changes API and missing invalidation of the cache in RavenDB Client
  src/Raven.Server/Documents/ChangesClientConnection.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  test/SlowTests/Issues/RavenDB_22739.cs
  test/SlowTests/Server/Documents/Notifications/ChangesTests.cs
Labels: v5.4

#18990 RavenDB-22646 - Fix test RavenDB_22345.Handle_Outdated_Leader_On_RachisMergedCommand
  test/SlowTests/Issues/RavenDB-22345.cs
Labels: v6.0

#18998 RavenDB-22605 add proxy to '/admin/cluster/log' EP
  src/Raven.Server/Documents/Handlers/Admin/RachisAdminHandler.cs
  src/Raven.Server/Documents/Handlers/Admin/RachisAdminHandlerProcessorForGetClusterLogs.cs
Labels: v6.0

#19008 RavenDB-22748 Store value `isSecureServer` is not updated for secured server
  src/Raven.Studio/typescript/components/common/shell/accessManagerSlice.ts
Labels: v6.0, Studio

#18938 RavenDB-22683 - Error during replication [v54]
  src/Raven.Server/Documents/Replication/IncomingReplicationHandler.cs
Labels: v5.4

#18937 RavenDB-22683 - Error during replication
  src/Raven.Server/Documents/Replication/Incoming/AbstractIncomingReplicationHandler.cs
  src/Raven.Server/Documents/Replication/Incoming/IncomingReplicationHandler.cs
Labels: v6.0

#19003 RavenDB-22701 - SlowTests.Server.Replication.ReplicationConflictsTests.DatabaseChangeVectorShouldBeIdentical
  test/SlowTests/Server/Replication/ReplicationConflictsTests.cs
Labels: v5.4

#18999 RavenDB-22742 - SlowTests.Server.Replication.PullReplicationTests.Upd…
  test/SlowTests/Server/Replication/PullReplicationTests.cs
Labels: v5.4

#19006 RavenDB-22744 Forcing the cluster wide transaction to mark the compare exchange tombstone as handled
  test/SlowTests/Issues/RavenDB_20150.cs
  test/SlowTests/Sharding/Cluster/ShardedClusterObserverTests.cs
Labels: v6.0

#19010 RavenDB-22750 IndexTimestamp and LastQueryTime are in UTC so we need to write them in a proper format in JSON
  src/Raven.Server/Json/BlittableJsonTextWriterExtensions.cs
  test/SlowTests/Issues/RavenDB_22750.cs
Labels: v5.4

#19009 RavenDB-22749 removing database after test is completed
  test/SlowTests/Server/Documents/Notifications/ChangesTests.cs
Labels: v5.4

#19011 5.4 to 6.0 merge
  src/Raven.Server/Documents/Changes/AbstractChangesClientConnection.cs
  src/Raven.Server/Documents/Changes/ChangesClientConnection.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterMaintenanceSupervisor.cs
  test/RachisTests/TopologyChangesTests.cs
  test/SlowTests/Cluster/ClusterMaintenanceTest.cs
  test/SlowTests/Issues/RavenDB-18515.cs
  test/SlowTests/Issues/RavenDB-22531.cs
  test/SlowTests/Issues/RavenDB_17018.cs
  test/SlowTests/Server/Documents/ETL/SQL/SqlEtlTests.cs
  test/SlowTests/Server/Documents/Notifications/ChangesTests.cs
  test/SlowTests/Server/Replication/PullReplicationTests.cs
  test/SlowTests/Server/Replication/ReplicationConflictsTests.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
  test/Tests.Infrastructure/RachisConsensusTestBase.cs
  test/Tests.Infrastructure/RavenTestBase.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v6.0

#19014 6.0 to 6.1 merge
  src/Raven.Server/Documents/Changes/AbstractChangesClientConnection.cs
  src/Raven.Server/Documents/Changes/ChangesClientConnection.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/Handlers/Admin/RachisAdminHandler.cs
  src/Raven.Server/Documents/Handlers/Admin/RachisAdminHandlerProcessorForGetClusterLogs.cs
  src/Raven.Server/Documents/Replication/Incoming/AbstractIncomingReplicationHandler.cs
  src/Raven.Server/Documents/Replication/Incoming/IncomingReplicationHandler.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterMaintenanceSupervisor.cs
  src/Raven.Studio/typescript/components/common/shell/accessManagerSlice.ts
  test/RachisTests/TopologyChangesTests.cs
  test/SlowTests/Cluster/ClusterMaintenanceTest.cs
  test/SlowTests/Issues/RavenDB-18515.cs
  test/SlowTests/Issues/RavenDB-22345.cs
  test/SlowTests/Issues/RavenDB-22531.cs
  test/SlowTests/Issues/RavenDB_17018.cs
  test/SlowTests/Issues/RavenDB_20150.cs
  test/SlowTests/Issues/RavenDB_22739.cs
  test/SlowTests/Server/Documents/ETL/SQL/SqlEtlTests.cs
  test/SlowTests/Server/Documents/Notifications/ChangesTests.cs
  test/SlowTests/Server/Replication/PullReplicationTests.cs
  test/SlowTests/Server/Replication/ReplicationConflictsTests.cs
  test/SlowTests/Sharding/Cluster/ShardedClusterObserverTests.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
  test/Tests.Infrastructure/RachisConsensusTestBase.cs
  test/Tests.Infrastructure/RavenTestBase.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v6.1

#19019 RavenDB-22531 - Add unsupported report status to the exception
  src/Raven.Server/ServerWide/Maintenance/ClusterMaintenanceSupervisor.cs
Labels: v5.4

#19017 RavenDB-22753 Fixing IndexCreation.CreateIndexes() which ignored SearchEngineType
  src/Raven.Client/Documents/Indexes/AbstractIndexCreationTask.cs
  src/Raven.Client/Documents/Indexes/IndexCreation.cs
  test/SlowTests/Issues/RavenDB_22753.cs
Labels: v5.4

#19015 RavenDB-20985 create new customSettings for each node
  test/Tests.Infrastructure/ClusterTestBase.cs
Labels: v5.4

#19021 RavenDB-22754 - SlowTests.Issues.FilteredReplicationTests.Can_pull_an…
  test/Tests.Infrastructure/ClusterTestBase.cs
Labels: v6.0

#19007 RavenDB-21914 - ClusterWideTransaction_WhenStoreDocWithEmptyStringId_ShouldThrowInformativeError fails
  src/Raven.Server/ServerWide/Commands/ClusterTransactionCommand.cs
  test/SlowTests/Cluster/ClusterTransactionTests.cs
Labels: v6.0

#19022 5.4 to 6.0 merge
  src/Raven.Client/Documents/Indexes/AbstractIndexCreationTask.cs
  src/Raven.Client/Documents/Indexes/IndexCreation.cs
  src/Raven.Server/Json/BlittableJsonTextWriterExtensions.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterMaintenanceSupervisor.cs
  test/RachisTests/DatabaseCluster/AtomicClusterReadWriteTests.cs
  test/SlowTests/Issues/RavenDB-21050.cs
  test/SlowTests/Issues/RavenDB_22750.cs
  test/SlowTests/Issues/RavenDB_22753.cs
  test/SlowTests/Server/Documents/Notifications/ChangesTests.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
  test/Tests.Infrastructure/RavenTestBase.Backup.cs
Labels: v6.0

#19023 6.0 to 6.1 merge
  src/Raven.Client/Documents/Indexes/AbstractIndexCreationTask.cs
  src/Raven.Client/Documents/Indexes/IndexCreation.cs
  src/Raven.Server/Json/BlittableJsonTextWriterExtensions.cs
  src/Raven.Server/ServerWide/Commands/ClusterTransactionCommand.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterMaintenanceSupervisor.cs
  src/Raven.Studio/typescript/components/pages/database/status/statistics/store/statisticsViewSlice.ts
  test/RachisTests/DatabaseCluster/AtomicClusterReadWriteTests.cs
  test/SlowTests/Cluster/ClusterTransactionTests.cs
  test/SlowTests/Issues/RavenDB-21050.cs
  test/SlowTests/Issues/RavenDB_22750.cs
  test/SlowTests/Issues/RavenDB_22753.cs
  test/SlowTests/Server/Documents/Notifications/ChangesTests.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
  test/Tests.Infrastructure/RavenTestBase.Backup.cs
Labels: v6.1

#19024 6.1 to 6.2 merge
  src/Raven.Client/Documents/Indexes/AbstractIndexCreationTask.cs
  src/Raven.Client/Documents/Indexes/IndexCreation.cs
  src/Raven.Server/Json/BlittableJsonTextWriterExtensions.cs
  src/Raven.Server/ServerWide/Commands/ClusterTransactionCommand.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterMaintenanceSupervisor.cs
  src/Raven.Studio/typescript/components/pages/database/status/statistics/store/statisticsViewSlice.ts
  test/RachisTests/DatabaseCluster/AtomicClusterReadWriteTests.cs
  test/SlowTests/Cluster/ClusterTransactionTests.cs
  test/SlowTests/Issues/RavenDB-21050.cs
  test/SlowTests/Issues/RavenDB_22750.cs
  test/SlowTests/Issues/RavenDB_22753.cs
  test/SlowTests/Server/Documents/Notifications/ChangesTests.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
  test/Tests.Infrastructure/RavenTestBase.Backup.cs
Labels: v6.2

#19025 RavenDB-22599 Wrong number of documents in the main database view
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/ValidDatabasePropertiesPanel.spec.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/ValidDatabasePropertiesPanel.tsx
Labels: v6.0, Studio

#18960 RavenDB-22717 - serialize dynamic index SupportDuplicateKeys field
  src/Voron/Data/Tables/TableSchema.IndexDefinitions.cs
  test/FastTests/Voron/Tables/Serialization.cs
Labels: v6.0

#19033 RDBQA-82 Handle AllowEncryptedDatabasesOverHttp in old database creator (v5.4)
  src/Raven.Studio/typescript/viewmodels/resources/createDatabase.ts
Labels: v5.4, Studio

#19030 RavenDB-22657 Failed to import config to sink
  src/Raven.Studio/typescript/common/certificateUtils.ts
  src/Raven.Studio/typings/custom_node-forge.d.ts
Labels: v5.4, Studio

#19034 RavenDB-22762 Modify `GetBackupFilesAndAssertCountAsync` to handle sharded database
  test/RachisTests/DatabaseCluster/AtomicClusterReadWriteTests.cs
  test/SlowTests/Issues/RavenDB-21050.cs
  test/Tests.Infrastructure/RavenTestBase.Backup.cs
Labels: v6.0

#19032 RDBQA-82 Handle AllowEncryptedDatabasesOverHttp in new database creator (v6.0)
  src/Raven.Studio/typescript/components/common/shell/accessManagerSlice.ts
  src/Raven.Studio/typescript/components/common/shell/accessManagerSliceSelectors.ts
  src/Raven.Studio/typescript/components/common/shell/setup.ts
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/create/regular/steps/CreateDatabaseRegularStepBasicInfo.tsx
Labels: v6.0, Studio

#19044 RavenDB-22771 Adjust enable-debugging.sh for single file deployment
  scripts/linux/enable-debugging.sh
Labels: v6.1

#19054 5.4 to 6.0 merge
  src/Raven.Server/Config/Categories/ConfigurationCategoryType.cs
  src/Raven.Server/Config/Categories/DebugConfiguration.cs
  src/Raven.Server/Config/RavenConfiguration.cs
  src/Raven.Server/Documents/Handlers/Admin/AdminLogsHandler.cs
  src/Raven.Server/Documents/Handlers/Debugging/ThreadsHandler.cs
  src/Raven.Server/EventListener/AbstractEventListener.cs
  src/Raven.Server/EventListener/AbstractEventsHandler.cs
  src/Raven.Server/EventListener/AllocationsEventListener.cs
  src/Raven.Server/EventListener/AllocationsHandler.cs
  src/Raven.Server/EventListener/ContentionEventsHandler.cs
  src/Raven.Server/EventListener/ContentionEventsListener.cs
  src/Raven.Server/EventListener/Event.cs
  src/Raven.Server/EventListener/EventComparerByDuration.cs
  src/Raven.Server/EventListener/EventListener.cs
  src/Raven.Server/EventListener/EventListenerMode.cs
  src/Raven.Server/EventListener/EventListenerToLog.cs
  src/Raven.Server/EventListener/EventType.cs
  src/Raven.Server/EventListener/EventsListener.cs
  src/Raven.Server/EventListener/GcEventsHandler.cs
  src/Raven.Server/EventListener/GcEventsListener.cs
  src/Raven.Server/Json/JsonDeserializationServer.cs
  src/Raven.Server/Program.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Web/System/AdminGcDebugHandler.cs
  src/Raven.Studio/typescript/common/certificateUtils.ts
  src/Raven.Studio/typings/custom_node-forge.d.ts
  test/FastTests/Server/DebugMemoryTests.cs
Labels: v6.0

#19062 RavenDB-22786 we use raw json for ClusterTransactionCommand so we need to put the command directly to the leader
  src/Raven.Server/Documents/Handlers/Admin/RachisAdminHandler.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
Labels: v5.4

#19070 6.0 to 6.1 merge
  .github/workflows/FastTests.yml
  .github/workflows/FastTestsARM.yml
  bench/BulkInsert.Benchmark/BulkInsert.Benchmark.csproj
  bench/Indexing.Benchmark/Indexing.Benchmark.csproj
  bench/Micro.Benchmark/Micro.Benchmark.csproj
  bench/Regression.Benchmark/Regression.Benchmark.csproj
  bench/ServerStoreTxMerger.Benchmark/ServerStoreTxMerger.Benchmark.csproj
  bench/ServerStoreTxMerger.Benchmark/ServerStoreTxMergerBenchTests.cs
  bench/SubscriptionFailover.Benchmark/SubscriptionFailover.Benchmark.csproj
  bench/Subscriptions.Benchmark/Subscriptions.Benchmark.csproj
  bench/TimeSeries.Benchmark/TimeSeries.Benchmark.csproj
  bench/Voron.Benchmark/Voron.Benchmark.csproj
  bench/VxSort.Benchmark/SmallSortBench.cs
  bench/VxSort.Benchmark/SortBench.cs
  bench/VxSort.Benchmark/Utils/TimePerNColumn.cs
  bench/VxSort.Benchmark/VxSort.Benchmark.csproj
  src/Corax/Corax.csproj
  src/Raven.Client/Raven.Client.csproj
  src/Raven.Embedded/ServerOptions.cs
  src/Raven.Server/Documents/CountersStorage.cs
  src/Raven.Server/Documents/Handlers/Admin/RachisAdminHandler.cs
  src/Raven.Server/Rachis/Leader.cs
  src/Raven.Server/Rachis/PutRaftCommand.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/JsonDeserializationCluster.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterObserver.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
  src/Raven.Studio/Raven.Studio.csproj
  src/Sparrow.Server/Sparrow.Server.csproj
  src/Voron/Data/Tables/Table.cs
  src/Voron/Voron.csproj
  test/BenchmarkTests/BenchmarkTests.csproj
  test/EmbeddedTests/EmbeddedTests.csproj
  test/FastTests/FastTests.csproj
  test/FastTests/Server/Documents/Indexing/Auto/BasicAutoMapIndexing.cs
  test/InterversionTests/InterversionTests.csproj
  test/LicenseTests/LicenseTests.csproj
  test/RachisTests/BasicCluster.cs
  test/RachisTests/BasicTests.cs
  test/RachisTests/CommandsTests.cs
  test/RachisTests/RachisTests.csproj
  test/RachisTests/TopologyChangesTests.cs
  test/SlowTests/Issues/RavenDB-15890.cs
  test/SlowTests/Issues/RavenDB-20922.cs
  test/SlowTests/RavenDB-14303.cs
  test/SlowTests/SlowTests.csproj
  test/StressTests/StressTests.csproj
  test/Tests.Infrastructure/RachisConsensusTestBase.cs
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
  test/Tryouts/Tryouts.csproj
  tools/Raven.Debug/Raven.Debug.csproj
  tools/Raven.Migrator/Raven.Migrator.csproj
  tools/TypingsGenerator/TypingsGenerator.csproj
  tools/Voron.Dictionary.Generator/Voron.Dictionary.Generator.csproj
  tools/Voron.Recovery/Voron.Recovery.csproj
  tools/rvn/rvn.csproj
Labels: v6.1

#19071 Merge v6.1 to v6.2
  .github/workflows/FastTests.yml
  .github/workflows/FastTestsARM.yml
  bench/BulkInsert.Benchmark/BulkInsert.Benchmark.csproj
  bench/Indexing.Benchmark/Indexing.Benchmark.csproj
  bench/Micro.Benchmark/Micro.Benchmark.csproj
  bench/Regression.Benchmark/Regression.Benchmark.csproj
  bench/ServerStoreTxMerger.Benchmark/ServerStoreTxMerger.Benchmark.csproj
  bench/ServerStoreTxMerger.Benchmark/ServerStoreTxMergerBenchTests.cs
  bench/SubscriptionFailover.Benchmark/SubscriptionFailover.Benchmark.csproj
  bench/Subscriptions.Benchmark/Subscriptions.Benchmark.csproj
  bench/TimeSeries.Benchmark/TimeSeries.Benchmark.csproj
  bench/Voron.Benchmark/Voron.Benchmark.csproj
  bench/VxSort.Benchmark/SmallSortBench.cs
  bench/VxSort.Benchmark/SortBench.cs
  bench/VxSort.Benchmark/Utils/TimePerNColumn.cs
  bench/VxSort.Benchmark/VxSort.Benchmark.csproj
  src/Corax/Corax.csproj
  src/Raven.Client/Raven.Client.csproj
  src/Raven.Embedded/ServerOptions.cs
  src/Raven.Server/Documents/CountersStorage.cs
  src/Raven.Server/Documents/Handlers/Admin/RachisAdminHandler.cs
  src/Raven.Server/Rachis/PutRaftCommand.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/JsonDeserializationCluster.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterObserver.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
  src/Raven.Studio/Raven.Studio.csproj
  src/Sparrow.Server/Sparrow.Server.csproj
  src/Voron/Data/Tables/Table.cs
  src/Voron/Voron.csproj
  test/BenchmarkTests/BenchmarkTests.csproj
  test/EmbeddedTests/EmbeddedTests.csproj
  test/FastTests/FastTests.csproj
  test/FastTests/Server/Documents/Indexing/Auto/BasicAutoMapIndexing.cs
  test/InterversionTests/InterversionTests.csproj
  test/LicenseTests/LicenseTests.csproj
  test/RachisTests/BasicCluster.cs
  test/RachisTests/BasicTests.cs
  test/RachisTests/CommandsTests.cs
  test/RachisTests/RachisTests.csproj
  test/RachisTests/TopologyChangesTests.cs
  test/SlowTests/Issues/RavenDB-15890.cs
  test/SlowTests/Issues/RavenDB-20922.cs
  test/SlowTests/RavenDB-14303.cs
  test/SlowTests/SlowTests.csproj
  test/StressTests/StressTests.csproj
  test/Tests.Infrastructure/RachisConsensusTestBase.cs
  test/Tests.Infrastructure/Tests.Infrastructure.csproj
  test/Tryouts/Tryouts.csproj
  tools/Raven.Debug/Raven.Debug.csproj
  tools/Raven.Migrator/Raven.Migrator.csproj
  tools/TypingsGenerator/TypingsGenerator.csproj
  tools/Voron.Dictionary.Generator/Voron.Dictionary.Generator.csproj
  tools/Voron.Recovery/Voron.Recovery.csproj
  tools/rvn/rvn.csproj
Labels: v6.2

#19075 RavenDB-7070 revert NuGet package update
  src/Raven.Server/Raven.Server.csproj
Labels: v6.0

#19076 6.0 to 6.1 merge
  src/Raven.Server/Raven.Server.csproj
Labels: v6.1

#19059 RavenDB-22782: We are not accounting for memory allocated through the direct interface.
  src/Sparrow.Server/ByteString.cs
Labels: v6.0

#19077 6.0 to 6.1 merge
  src/Sparrow.Server/ByteString.cs
Labels: v6.1

#19078 6.1 to 6.1 merge
  src/Raven.Client/Constants.cs
  src/Raven.Client/Documents/Linq/RavenQueryProviderProcessor.cs
  src/Raven.Client/Documents/Session/AbstractDocumentQuery.Sharding.cs
  src/Raven.Client/Documents/Session/AbstractDocumentQuery.cs
  src/Raven.Client/Documents/Session/Querying/Sharding/IQueryShardedContextBuilder.cs
  src/Raven.Client/Documents/Session/Querying/Sharding/QueryShardedContextBuilder.cs
  src/Raven.Server/Documents/Sharding/Queries/AbstractShardedQueryProcessor.cs
  src/Raven.Server/Raven.Server.csproj
  src/Sparrow.Server/ByteString.cs
  test/SlowTests/Issues/RavenDB-1847.cs
  test/SlowTests/Issues/RavenDB-21777.cs
  test/SlowTests/MailingList/spokeypokey/spokeypokey2.cs
  test/SlowTests/Sharding/PrefixedSharding.cs
Labels: v6.2

#19068 RavenDB-22787 More info on test failures
  test/RachisTests/DatabaseCluster/AtomicClusterReadWriteTests.cs
  test/SlowTests/Issues/RavenDB-21050.cs
Labels: v5.4

#19081 RavenDB-22736 - add missing return false in UpdateTopologyAsync in case of disposing
  src/Raven.Client/Http/RequestExecutor.cs
Labels: v5.4

#19084 RavenDB-22787 More info on test failures
  test/RachisTests/DatabaseCluster/AtomicClusterReadWriteTests.cs
  test/SlowTests/Issues/RavenDB-21050.cs
  test/Tests.Infrastructure/RavenTestBase.Backup.cs
Labels: v5.4

#19088 5.4 to 6.0 merge
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  src/Raven.Server/EventListener/AbstractEventListener.cs
  src/Raven.Server/EventListener/AllocationsHandler.cs
  src/Raven.Server/EventListener/ContentionEventsHandler.cs
  src/Raven.Server/EventListener/EventListener.cs
  src/Raven.Server/EventListener/EventListenerToLog.cs
  src/Raven.Server/EventListener/EventType.cs
  src/Raven.Server/EventListener/EventsListener.cs
  src/Raven.Server/EventListener/ThreadsHandler.cs
  src/Raven.Studio/typescript/commands/maintenance/getAdminLogsEventListenerConfigurationCommand.ts
  src/Raven.Studio/typescript/commands/maintenance/saveAdminLogsEventListenerConfigurationCommand.ts
  src/Raven.Studio/typescript/common/generalUtils.ts
  src/Raven.Studio/typescript/viewmodels/manage/adminLogs.ts
  src/Raven.Studio/typescript/viewmodels/manage/configureEventListenerDialog.ts
  src/Raven.Studio/wwwroot/App/views/manage/adminLogs.html
  src/Raven.Studio/wwwroot/App/views/manage/configureEventListenerDialog.html
  src/Raven.Studio/wwwroot/Content/css/pages/admin-logs.less
  src/Sparrow/Json/LazyStringValue.cs
  test/FastTests/Utils/RevisionsHelper.cs
  test/SlowTests/Issues/RavenDB-18513.cs
  test/SlowTests/Issues/RavenDB_16135.cs
  test/SlowTests/Server/Documents/Revisions/RevertRevisionsByCollectionTests.cs
  tools/TypingsGenerator/Program.cs
Labels: v6.0

#19091 6.0 to 6.1 merge
  src/Raven.Client/Documents/Operations/GetDetailedStatisticsOperation.cs
  src/Raven.Client/Documents/Operations/GetEssentialStatisticsOperation.cs
  src/Raven.Client/Documents/Operations/GetStatisticsOperation.cs
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  src/Raven.Server/EventListener/AbstractEventListener.cs
  src/Raven.Server/EventListener/AllocationsHandler.cs
  src/Raven.Server/EventListener/ContentionEventsHandler.cs
  src/Raven.Server/EventListener/EventListener.cs
  src/Raven.Server/EventListener/EventListenerToLog.cs
  src/Raven.Server/EventListener/EventType.cs
  src/Raven.Server/EventListener/EventsListener.cs
  src/Raven.Server/EventListener/ThreadsHandler.cs
  src/Raven.Studio/typescript/commands/maintenance/getAdminLogsEventListenerConfigurationCommand.ts
  src/Raven.Studio/typescript/commands/maintenance/saveAdminLogsEventListenerConfigurationCommand.ts
  src/Raven.Studio/typescript/common/generalUtils.ts
  src/Raven.Studio/typescript/viewmodels/manage/adminLogs.ts
  src/Raven.Studio/typescript/viewmodels/manage/configureEventListenerDialog.ts
  src/Raven.Studio/wwwroot/App/views/manage/adminLogs.html
  src/Raven.Studio/wwwroot/App/views/manage/configureEventListenerDialog.html
  src/Raven.Studio/wwwroot/Content/css/pages/admin-logs.less
  src/Sparrow/Json/LazyStringValue.cs
  test/FastTests/Utils/RevisionsHelper.cs
  test/InterversionTests/MixedClusterTestBase.cs
  test/InterversionTests/MixedClusterTests.cs
  test/SlowTests/Issues/RavenDB-18513.cs
  test/SlowTests/Issues/RavenDB_16135.cs
  test/SlowTests/Server/Documents/Revisions/RevertRevisionsByCollectionTests.cs
  test/Tests.Infrastructure/InterversionTest/UpgradeTestSuit.cs
  tools/TypingsGenerator/Program.cs
Labels: v6.1

#19093 RavenDB-7070 revert NuGet package update
  src/Raven.Server/Raven.Server.csproj
Labels: v6.1

#19094 6.1 to 6.2 merge
  src/Raven.Client/Documents/Operations/GetDetailedStatisticsOperation.cs
  src/Raven.Client/Documents/Operations/GetEssentialStatisticsOperation.cs
  src/Raven.Client/Documents/Operations/GetStatisticsOperation.cs
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  src/Raven.Server/EventListener/AbstractEventListener.cs
  src/Raven.Server/EventListener/AllocationsHandler.cs
  src/Raven.Server/EventListener/ContentionEventsHandler.cs
  src/Raven.Server/EventListener/EventListener.cs
  src/Raven.Server/EventListener/EventListenerToLog.cs
  src/Raven.Server/EventListener/EventType.cs
  src/Raven.Server/EventListener/EventsListener.cs
  src/Raven.Server/EventListener/ThreadsHandler.cs
  src/Raven.Server/Raven.Server.csproj
  src/Raven.Studio/typescript/commands/maintenance/getAdminLogsEventListenerConfigurationCommand.ts
  src/Raven.Studio/typescript/commands/maintenance/saveAdminLogsEventListenerConfigurationCommand.ts
  src/Raven.Studio/typescript/common/generalUtils.ts
  src/Raven.Studio/typescript/viewmodels/manage/adminLogs.ts
  src/Raven.Studio/typescript/viewmodels/manage/configureEventListenerDialog.ts
  src/Raven.Studio/wwwroot/App/views/manage/adminLogs.html
  src/Raven.Studio/wwwroot/App/views/manage/configureEventListenerDialog.html
  src/Raven.Studio/wwwroot/Content/css/pages/admin-logs.less
  src/Sparrow/Json/LazyStringValue.cs
  test/FastTests/Utils/RevisionsHelper.cs
  test/InterversionTests/MixedClusterTestBase.cs
  test/InterversionTests/MixedClusterTests.cs
  test/SlowTests/Issues/RavenDB-18513.cs
  test/SlowTests/Issues/RavenDB_16135.cs
  test/SlowTests/Server/Documents/Revisions/RevertRevisionsByCollectionTests.cs
  test/Tests.Infrastructure/InterversionTest/UpgradeTestSuit.cs
  tools/TypingsGenerator/Program.cs
Labels: v6.2

#19087 RavenDB-22800
  src/Raven.Server/Platform/Posix/LimitsReader.cs
  src/Raven.Server/ServerWide/ServerMetricCacher.cs
Labels: v5.4

#19080 RavenDB-21464 - Consider Disable property on update subscription
  src/Raven.Client/Documents/Subscriptions/SubscriptionCriteria.cs
  src/Raven.Client/Extensions/BlittableJsonTextWriterExtensions.cs
  src/Raven.Server/Documents/Handlers/SubscriptionsHandler.cs
  test/FastTests/Client/Subscriptions/SubscriptionsBasic.cs
Labels: v5.4

#19097 RavenDB-22783 Move license check from PreInitialize to Initialize.
  src/Raven.Server/ServerWide/ServerStore.cs
Labels: v6.1

#19074 RavenDB-22738 About page missing license details
  src/Raven.Studio/typescript/components/pages/resources/about/partials/LicenseDetails.tsx
Labels: Studio, v6.1

#19107 RavenDB-22808 Fix admin logs settings layout
  src/Raven.Studio/wwwroot/App/views/manage/adminLogs.html
Labels: v6.0, Studio

#19089 RavenDB-22744 Report cluster trx index when NoChanges and update cluster trx index on other shard commands
  src/Raven.Server/Documents/Sharding/ShardedDocumentDatabase.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterMaintenanceSupervisor.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterMaintenanceWorker.cs
  test/SlowTests/Sharding/Cluster/ShardedClusterObserverTests.cs
Labels: v6.0

#19114 5.4 to 6.0 merge
  src/Raven.Client/Documents/Subscriptions/SubscriptionCriteria.cs
  src/Raven.Client/Extensions/BlittableJsonTextWriterExtensions.cs
  src/Raven.Server/Documents/Handlers/Processors/Subscriptions/AbstractSubscriptionsHandlerProcessorForPostSubscription.cs
  src/Raven.Server/Documents/Handlers/SubscriptionsHandler.cs
  src/Raven.Server/Documents/Subscriptions/Processor/RevisionsDatabaseSubscriptionProcessor.cs
  src/Raven.Server/Platform/Posix/LimitsReader.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.License.cs
  src/Raven.Server/ServerWide/ServerMetricCacher.cs
  test/FastTests/Client/Subscriptions/SubscriptionsBasic.cs
  test/FastTests/Server/Basic/SampleData.cs
  test/SlowTests/Client/Subscriptions/RevisionsSubscriptions.cs
Labels: v6.0

#19117 6.0 to 6.1 merge
  src/Raven.Client/Documents/Subscriptions/SubscriptionCriteria.cs
  src/Raven.Client/Extensions/BlittableJsonTextWriterExtensions.cs
  src/Raven.Server/Documents/Handlers/Processors/Indexes/IndexHandlerProcessorForConvertAutoIndex.cs
  src/Raven.Server/Documents/Handlers/Processors/Subscriptions/AbstractSubscriptionsHandlerProcessorForPostSubscription.cs
  src/Raven.Server/Documents/Handlers/SubscriptionsHandler.cs
  src/Raven.Server/Documents/Sharding/ShardedDocumentDatabase.cs
  src/Raven.Server/Documents/Subscriptions/Processor/RevisionsDatabaseSubscriptionProcessor.cs
  src/Raven.Server/Platform/Posix/LimitsReader.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.License.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterMaintenanceSupervisor.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterMaintenanceWorker.cs
  src/Raven.Server/ServerWide/ServerMetricCacher.cs
  src/Raven.Studio/typescript/commands/database/index/getIndexAutoConvertCommand.ts
  src/Raven.Studio/typescript/common/shell/databasesManager.ts
  src/Raven.Studio/typescript/common/storage/convertedIndexesToStaticStorage.ts
  src/Raven.Studio/typescript/components/pages/database/indexes/cleanup/carouselCards/MergeIndexesCard.tsx
  src/Raven.Studio/typescript/viewmodels/database/indexes/convertToStaticDialog.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/editIndex.ts
  src/Raven.Studio/wwwroot/App/views/database/indexes/convertToStaticDialog.html
  src/Raven.Studio/wwwroot/App/views/database/indexes/editIndex.html
  src/Raven.Studio/wwwroot/App/views/manage/adminLogs.html
  test/FastTests/Client/Subscriptions/SubscriptionsBasic.cs
  test/FastTests/Server/Basic/SampleData.cs
  test/SlowTests/Client/Subscriptions/RevisionsSubscriptions.cs
  test/SlowTests/Issues/RavenDB_22498.cs
  test/SlowTests/Sharding/Cluster/ShardedClusterObserverTests.cs
  tools/TypingsGenerator/Program.cs
Labels: v6.1

#19119 RavenDB-22809 using directly createdump for dump creation instead of DiagnosticsClient
  scripts/linux/enable-debugging.sh
  scripts/package.ps1
  tools/Raven.Debug/Dump/Dumper.cs
Labels: v6.1

#19122 6.1 to 6.2 merge
  build.ps1
  scripts/buildProjects.ps1
  scripts/linux/enable-debugging.sh
  scripts/package.ps1
  src/Raven.Client/Documents/Subscriptions/SubscriptionCriteria.cs
  src/Raven.Client/Extensions/BlittableJsonTextWriterExtensions.cs
  src/Raven.Server/Documents/Handlers/Processors/Indexes/IndexHandlerProcessorForConvertAutoIndex.cs
  src/Raven.Server/Documents/Handlers/Processors/Subscriptions/AbstractSubscriptionsHandlerProcessorForPostSubscription.cs
  src/Raven.Server/Documents/Handlers/SubscriptionsHandler.cs
  src/Raven.Server/Documents/Sharding/ShardedDocumentDatabase.cs
  src/Raven.Server/Documents/Subscriptions/Processor/RevisionsDatabaseSubscriptionProcessor.cs
  src/Raven.Server/Platform/Posix/LimitsReader.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.License.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterMaintenanceSupervisor.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterMaintenanceWorker.cs
  src/Raven.Server/ServerWide/ServerMetricCacher.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
  src/Raven.Studio/typescript/commands/database/index/getIndexAutoConvertCommand.ts
  src/Raven.Studio/typescript/common/shell/databasesManager.ts
  src/Raven.Studio/typescript/common/storage/convertedIndexesToStaticStorage.ts
  src/Raven.Studio/typescript/components/pages/database/indexes/cleanup/carouselCards/MergeIndexesCard.tsx
  src/Raven.Studio/typescript/components/pages/resources/about/partials/LicenseDetails.tsx
  src/Raven.Studio/typescript/viewmodels/database/indexes/convertToStaticDialog.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/editIndex.ts
  src/Raven.Studio/wwwroot/App/views/database/indexes/convertToStaticDialog.html
  src/Raven.Studio/wwwroot/App/views/database/indexes/editIndex.html
  src/Raven.Studio/wwwroot/App/views/manage/adminLogs.html
  test/FastTests/Client/Subscriptions/SubscriptionsBasic.cs
  test/FastTests/Server/Basic/SampleData.cs
  test/InterversionTests/RavenDB-22634.cs
  test/SlowTests/Client/Subscriptions/RevisionsSubscriptions.cs
  test/SlowTests/Issues/RavenDB_22498.cs
  test/SlowTests/Sharding/Cluster/ShardedClusterObserverTests.cs
  tools/Raven.Debug/Dump/Dumper.cs
  tools/TypingsGenerator/Program.cs
Labels: v6.2

#19121 RavenDB-22765 Change main menu collapse icon
  src/Raven.Studio/wwwroot/Content/css/main-menu.less
Labels: v5.4, Studio

#19101 RavenDB-22787 Make sure to mark backup task as completed only after the `RunningTask` is set to null
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
Labels: v5.4

#19126 5.4 to 6.0 merge
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
Labels: v6.0

#19127 6.0 to 6.1 merge
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
Labels: v6.1

#19085 RavenDB-20829 - add missing include ids to _knownMissingIds in subscription session [v5.4]
  src/Raven.Client/Documents/Session/InMemoryDocumentSessionOperations.cs
  src/Raven.Client/Documents/Subscriptions/SubscriptionBatch.cs
  src/Raven.Server/Documents/DocumentFlags.cs
  src/Raven.Server/Documents/Handlers/DocumentHandler.cs
  src/Raven.Server/Documents/Handlers/SubscriptionsHandler.cs
  src/Raven.Server/Documents/Includes/IncludeDocumentsCommand.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Queries/Dynamic/CollectionQueryRunner.cs
  src/Raven.Server/Documents/Queries/GraphQueryRunner.cs
  src/Raven.Server/Documents/TcpHandlers/SubscriptionConnection.cs
  src/Raven.Server/Json/BlittableJsonTextWriterExtensions.cs
  test/SlowTests/Issues/RavenDB-11166.cs
Labels: v5.4

#19129 RavenDB-22765 Change main menu collapse icon for 6.0
  src/Raven.Studio/wwwroot/Content/scss/_main-menu.scss
Labels: v6.0, Studio

#19053 RavenDB-22557 Disable restoring encrypted snapshot on unsecure server
  src/Raven.Studio/typescript/components/common/select/Select.scss
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/create/formBackup/createDatabaseFromBackupDataUtils.ts
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/create/formBackup/steps/source/BackupSourceAmazonS3.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/create/formBackup/steps/source/BackupSourceAzure.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/create/formBackup/steps/source/BackupSourceGoogleCloud.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/create/formBackup/steps/source/BackupSourceLocal.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/create/formBackup/steps/source/BackupSourceRavenCloud.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/create/formBackup/steps/source/CreateDatabaseFromBackupStepSource.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/create/formBackup/steps/source/RestorePointField.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/create/formBackup/steps/source/restorePointUtils.ts
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/create/formBackup/steps/source/useRestorePointUtils.ts
Labels: v6.0, Studio

#19042 RavenDB-22764 OS tooltip constantly blinking
  src/Raven.Studio/wwwroot/App/views/manage/cluster.html
Labels: v5.4, Studio

#19103 RavenDB-22773 - Fix throwing TaskCanceledException in WaitForLeaderChange, on interversion tests
  src/Raven.Server/Rachis/Follower.cs
Labels: v6.0

#19100 RavenDB-22317 Extract field name in group by from more kinds of expression if possible
  src/Raven.Server/Documents/Indexes/Static/Roslyn/Rewriters/RewritersHelper.cs
  test/SlowTests/Issues/RavenDB-22317.cs
Labels: v6.0

#19115 RavenDB-22811 Fixing unexpected indexing errors on complex fields in Corax after side-by-side indexing
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxDocumentConverterBase.cs
  test/SlowTests/Corax/RavenDB_22811.cs
Labels: Corax, v6.0

#19128 RavenDB-22775-v6 - Test Hub/Sink Replication [for v6]
  src/Raven.Client/Documents/Operations/Replication/PullReplicationAsHub.cs
  src/Raven.Client/Documents/Operations/Replication/PullReplicationAsSink.cs
  src/Raven.Client/Documents/Operations/Replication/PullReplicationDefinition.cs
  src/Raven.Server/Documents/Replication/Incoming/IncomingPullReplicationHandler.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  test/SlowTests/Issues/RavenDB-19967.cs
Labels: v6.0

#19131 RavenDB-22817 - Persisting configuration should be ClusterAdmin operation
  src/Raven.Server/Documents/Handlers/Admin/AdminLogsHandler.cs
  src/Raven.Server/TrafficWatch/TrafficWatchHandler.cs
  src/Raven.Server/Web/ServerRequestHandler.cs
Labels: v5.4

#19135 5.4 to 6.0 merge
  src/Raven.Server/Documents/Handlers/Admin/AdminLogsHandler.cs
  src/Raven.Server/TrafficWatch/TrafficWatchHandler.cs
  src/Raven.Server/Web/ServerRequestHandler.cs
  src/Raven.Studio/wwwroot/App/views/manage/cluster.html
  test/SlowTests/Issues/RavenDB-22564.cs
Labels: v6.0

#19035 RavenDB-22534 Corax - Configuration option for handling of Complex fields
  src/Corax/Mappings/IndexFieldBinding.cs
  src/Raven.Server/Config/Categories/IndexingConfiguration.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/IndexDefinitionBaseServerSide.cs
  src/Raven.Server/Documents/Indexes/IndexStorage.cs
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxDocumentConverterBase.cs
  src/Raven.Server/NotificationCenter/Indexing.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Web/Studio/EmbeddedData/Northwind.ravendbdump
  src/Raven.Studio/typescript/models/database/index/configurationItem.ts
  test/FastTests/Corax/Bugs/RavenDB-19442.cs
  test/FastTests/Issues/RavenDB_16590.cs
  test/FastTests/Issues/RavenDB_21557.cs
  test/FastTests/Sharding/Queries/BasicShardedMapReduceQueryTests.cs
  test/SlowTests/Client/Indexing/Counters/BasicCountersIndexes_StrongSyntax.cs
  test/SlowTests/Corax/IndexSearcher.cs
  test/SlowTests/Corax/RavenDB-21430.cs
  test/SlowTests/Corax/RavenDB-21689.cs
  test/SlowTests/Data/RavenDB_22534/RavenDB_22534.ravendb-snapshot
  test/SlowTests/Issues/RavenDB-10995.cs
  test/SlowTests/Issues/RavenDB-14797.cs
  test/SlowTests/Issues/RavenDB-15298.cs
  test/SlowTests/Issues/RavenDB-16031.cs
  test/SlowTests/Issues/RavenDB-17097.cs
  test/SlowTests/Issues/RavenDB-22523.cs
  test/SlowTests/Issues/RavenDB_16850.cs
  test/SlowTests/Issues/RavenDB_18357.cs
  test/SlowTests/Issues/RavenDB_19546.cs
  test/SlowTests/Issues/RavenDB_22406.cs
  test/SlowTests/Issues/RavenDB_22534.cs
  test/SlowTests/MailingList/CanRetrieveFacetCountsOfQueryResults.cs
  test/SlowTests/MailingList/CanRetrieveFacetCountsOfQueryResults2.cs
  test/SlowTests/MailingList/DataSetIndexTest.cs
  test/SlowTests/MailingList/ItemsBySetIdIndexTests.cs
  test/SlowTests/SlowTests.csproj
  test/SlowTests/Tests/Linq/OfTypeSuppor3.cs
Labels: Corax, v6.1

#19136 RavenDB-22806 - Add ForgetAbout to enumerator used in subscription v6.0
  src/Raven.Server/Documents/Subscriptions/Processor/RevisionsDatabaseSubscriptionProcessor.cs
  src/Raven.Server/Documents/Subscriptions/Sharding/ShardDocumentSubscriptionFetcher.cs
  src/Raven.Server/Documents/Subscriptions/SubscriptionConnectionsState.cs
  src/Raven.Server/Documents/Subscriptions/SubscriptionFetcher.cs
  src/Raven.Server/Utils/Enumerators/TransactionForgetAboutAbstractEnumerator.cs
  src/Raven.Server/Utils/Enumerators/TransactionForgetAboutCurrentPreviousRevisionEnumerator.cs
  src/Raven.Server/Utils/Enumerators/TransactionForgetAboutDocumentEnumerator.cs
Labels: v6.0

#19139 RavenDB-22824 Support for nullable enums in configuration.
  src/Raven.Server/Config/Categories/ConfigurationCategory.cs
  test/SlowTests/Issues/RavenDB_22824.cs
Labels: v6.1

#19137 RavenDB-22820 OpenTelemetry: Allows users to define the server instance ID via configuration.
  src/Raven.Server/Config/Categories/MonitoringConfiguration.cs
  src/Raven.Server/RavenServer.cs
Labels: v6.1

#19145 RavenDB-22765 Use chevron icon in html for main menu back button
  src/Raven.Studio/wwwroot/App/views/shell.html
  src/Raven.Studio/wwwroot/Content/scss/_main-menu.scss
Labels: v6.0, Studio

#19141 RavenDB-22826 Add timeseries to relevant endpoints descriptions.
  src/Raven.Server/Monitoring/Snmp/SnmpOids.cs
Labels: v5.4

#19149 RavenDB-21469 - Port from 6.0
  src/Raven.Server/RavenServer.cs
Labels: v5.4

#19146 RavenDB-22246 renamed the property
  src/Raven.Embedded/RavenServerRunner.cs
  src/Raven.Embedded/ServerOptions.cs
  test/LicenseTests/LicenseOptionsTests.cs
Labels: v5.4

#19143 RavenDB-22246: Introduce an option in TestDriver to throw if there is no license or license could not be activated (Specific breaking changes for v6.1)
  src/Raven.Embedded/RavenServerRunner.cs
  src/Raven.Embedded/ServerOptions.cs
  src/Raven.TestDriver/TestServerOptions.cs
  test/LicenseTests/LicenseOptionsTests.cs
Labels: v6.1

#19144 RavenDB-22823 In tests ignore cluster transaction while checking compare exchange tombstone to clean
  test/SlowTests/Issues/RavenDB_20206.cs
  test/SlowTests/Server/Documents/PeriodicBackup/RavenDB-11139.cs
  test/SlowTests/Utils/CompareExchangeTombstonCleanerTestHelper.cs
Labels: v5.4

#19150 RavenDB-22440 : flaky test adjustments
  test/StressTests/Server/Documents/ETL/Olap/LocalTestsStress.cs
Labels: v5.4

#18947 RavenDB-22035 - Added wait for ResponsibleNode command to be applied in backup test area to prevent race
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
  test/Tests.Infrastructure/RavenTestBase.Backup.cs
Labels: v5.4

#19160 RavenDB-22487 : flaky test adjustments
  test/SlowTests/Server/Documents/ETL/Olap/FailoverTests.cs
Labels: v5.4

#19151 RavenDB-22641 XML documentation of some IServerOperation implementations.
  src/Raven.Client/DocumentationUrls.cs
  src/Raven.Client/Documents/Indexes/Analysis/AnalyzerDefinition.cs
  src/Raven.Client/Documents/Operations/OngoingTasks/GetTaskInfoResult.cs
  src/Raven.Client/Documents/Queries/Sorting/SorterDefinition.cs
  src/Raven.Client/ServerWide/DatabaseRecord.cs
  src/Raven.Client/ServerWide/Operations/Analyzers/DeleteServerWideAnalyzerOperation.cs
  src/Raven.Client/ServerWide/Operations/Analyzers/PutServerWideAnalyzersOperation.cs
  src/Raven.Client/ServerWide/Operations/OngoingTasks/DeleteServerWideTaskOperation.cs
  src/Raven.Client/ServerWide/Operations/OngoingTasks/ToggleServerWideTaskStateOperation.cs
  src/Raven.Client/ServerWide/Operations/SetDatabaseDynamicDistributionOperation.cs
  src/Raven.Client/ServerWide/Operations/SetDatabasesLockOperation.cs
  src/Raven.Client/ServerWide/Operations/Sorters/DeleteServerWideSorterOperation.cs
  src/Raven.Client/ServerWide/Operations/Sorters/PutServerWideSortersOperation.cs
  src/Raven.Client/ServerWide/Operations/UpdateUnusedDatabasesOperation.cs
Labels: v6.0

#19166 RavenDB-22839 - add missing dispose in case of an error
  src/Raven.Server/Documents/Patch/JavaScriptUtils.cs
Labels: v5.4

#19158 RavenDB-22671 Fix readability for index progress on various themes
  src/Raven.Studio/typescript/components/common/ProgressCircle.scss
Labels: v6.0, Studio

#19170 RavenDB-22498 Add the ability to convert auto index to static (save whole JSON response)
  src/Raven.Studio/typescript/viewmodels/database/indexes/convertToStaticDialog.ts
Labels: v6.0, Studio

#19168 RavenDB-22577 Making sure that we'll wait for the completion of BlittableJsonContent.SerializeToStreamAsync after HttpClient.SendAsync has already completed
  src/Raven.Client/Http/RavenCommand.cs
  src/Raven.Client/Json/BlittableJsonContent.cs
Labels: v5.4

#19179 5.4 to 6.0 merge
  src/Raven.Client/Http/RavenCommand.cs
  src/Raven.Client/Json/BlittableJsonContent.cs
  src/Raven.Server/Documents/Patch/JavaScriptUtils.cs
  src/Raven.Server/EventListener/EventListener.cs
  src/Raven.Server/EventListener/EventListenerToLog.cs
  src/Raven.Server/EventListener/EventType.cs
  src/Raven.Server/EventListener/EventsListener.cs
  src/Raven.Server/EventListener/GcEventsHandler.cs
  src/Raven.Server/EventListener/GcEventsListener.cs
  src/Raven.Studio/typescript/viewmodels/manage/configureEventListenerDialog.ts
  test/SlowTests/Server/Documents/ETL/Olap/FailoverTests.cs
Labels: v6.0

#19169 RavenDB-22831 Fixing failing Corax test since with the behavior on 6.1 it was expected to fail. The old behavior is verified by this test on 6.0 branch.
  test/SlowTests/Corax/RavenDB_22811.cs
Labels: v6.1

#19175 RavenDB-21148 - InterversionTests.RavenDB_17518.ShouldNotReplicateIncrementalTimeSeriesToOldServer2
  test/InterversionTests/RavenDB-17518.cs
Labels: v6.0

#19173 RavenDB-22795 - add comments for operations that implement IMaintenanceOperation
  src/Raven.Client/Documents/Indexes/IndexDefinition.cs
  src/Raven.Client/Documents/Indexes/IndexLockMode.cs
  src/Raven.Client/Documents/Indexes/IndexPriority.cs
  src/Raven.Client/Documents/Operations/Analyzers/DeleteAnalyzerOperation.cs
  src/Raven.Client/Documents/Operations/Analyzers/PutAnalyzersOperation.cs
  src/Raven.Client/Documents/Operations/Configuration/ClientConfiguration.cs
  src/Raven.Client/Documents/Operations/Configuration/PutClientConfigurationOperation.cs
  src/Raven.Client/Documents/Operations/ETL/ResetEtlOperation.cs
  src/Raven.Client/Documents/Operations/Indexes/DeleteIndexErrorsOperation.cs
  src/Raven.Client/Documents/Operations/Indexes/DeleteIndexOperation.cs
  src/Raven.Client/Documents/Operations/Indexes/DisableIndexOperation.cs
  src/Raven.Client/Documents/Operations/Indexes/EnableIndexOperation.cs
  src/Raven.Client/Documents/Operations/Indexes/ResetIndexOperation.cs
  src/Raven.Client/Documents/Operations/Indexes/SetIndexesLockOperation.cs
  src/Raven.Client/Documents/Operations/Indexes/SetIndexesPriorityOperation.cs
  src/Raven.Client/Documents/Operations/Indexes/StartIndexOperation.cs
  src/Raven.Client/Documents/Operations/Indexes/StartIndexingOperation.cs
  src/Raven.Client/Documents/Operations/Indexes/StopIndexOperation.cs
  src/Raven.Client/Documents/Operations/Indexes/StopIndexingOperation.cs
  src/Raven.Client/Documents/Operations/Replication/RegisterReplicationHubAccessOperation.cs
  src/Raven.Client/Documents/Operations/Replication/ReplicationHubAccess.cs
  src/Raven.Client/Documents/Operations/Replication/UnregisterReplicationHubAccessOperation.cs
  src/Raven.Client/Documents/Operations/Sorters/DeleteSorterOperation.cs
  src/Raven.Client/Documents/Operations/Sorters/PutSortersOperation.cs
  src/Raven.Client/Documents/Operations/TransactionsRecording/StartTransactionsRecordingOperation.cs
  src/Raven.Client/Documents/Operations/TransactionsRecording/StopTransactionsRecordingOperation.cs
  src/Raven.Client/Http/LoadBalanceBehavior.cs
  src/Raven.Client/Http/ReadBalanceBehavior.cs
  src/Raven.Client/ServerWide/Operations/Configuration/PutDatabaseSettingsOperation.cs
Labels: v6.0

#19184 RavenDB-22703 NonExisting posting list index version check for v6.1
  src/Raven.Server/Documents/Indexes/IndexDefinitionBaseServerSide.cs
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxDocumentConverterBase.cs
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxQueryBuilder.cs
Labels: v6.1

#19183 RavenDB-22686 bump Lucene,Corax,Documents and Server storage version to 61_000
  src/Raven.Server/Storage/Schema/SchemaUpgrader.cs
  src/Raven.Server/Storage/Schema/Updates/CoraxIndex/61000/From60000.cs
  src/Raven.Server/Storage/Schema/Updates/Documents/61000/From60000.cs
  src/Raven.Server/Storage/Schema/Updates/LuceneIndex/61000/From60000.cs
  src/Raven.Server/Storage/Schema/Updates/Server/61000/From60000.cs
Labels: v6.1
