Repository ravendb/ravendb, pull requests merged in 2024-03, with the labels that each got.

#18172 RavenDB-22067 - make sure not task delay a negative timespan
  test/StressTests/Issues/RavenDB_14292.cs
Labels: v5.4

#18169 RavenDB-22119: wait for index in test
  test/SlowTests/Client/Subscriptions/RevisionsSubscriptions.cs
  test/SlowTests/Issues/RavenDB_20708.cs
Labels: v6.0

#18175 5.4 to 6.0 merge
  src/Raven.Server/Documents/Handlers/Processors/Batches/AbstractClusterTransactionRequestProcessor.cs
  src/Raven.Server/RavenServerStartup.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  test/InterversionTests/RavenDB-20628-backward-compatibility.cs
  test/SlowTests/Issues/RavenDB_20708.cs
  test/SlowTests/Issues/RavenDB_2955.cs
  test/SlowTests/Server/Documents/Indexing/ExactSearchOnAutoIndex_RavenDB_8006.cs
  test/StressTests/Issues/RavenDB_14292.cs
Labels: v6.0

#18179 RDBC-797 dispose the fastest node timer
  src/Raven.Client/Http/RequestExecutor.cs
Labels: v5.4

#18178 RavenDB-22124 Add info in Queue sink Info Hub - that database will not become idle
  src/Raven.Studio/typescript/viewmodels/database/tasks/EditKafkaSinkTaskInfoHub.tsx
  src/Raven.Studio/typescript/viewmodels/database/tasks/EditRabbitMqSinkTaskInfoHub.tsx
Labels: v6.0, Studio

#18183 5.4 to 6.0 merge
  src/Raven.Client/Http/RequestExecutor.cs
Labels: v6.0

#18184 RavenDB-21799 Updated SlowTests.Issues.RavenDB_21668.Can_Query_Map_Reduce_Index
  test/SlowTests/Issues/RavenDB-21668.cs
Labels: v5.4

#18180 RavenDB-22108: fix hanged test
  src/Raven.Server/Documents/PeriodicBackup/BackupTask.cs
  test/RachisTests/BasicTests.cs
  test/SlowTests/Client/Subscriptions/ConcurrentSubscriptionsTests.cs
  test/SlowTests/Client/Subscriptions/RavenDB_9117.cs
  test/SlowTests/Cluster/ClusterObserverTests.cs
  test/SlowTests/ExtensionPoints/ExtensionPointsTests.cs
  test/SlowTests/Issues/RavenDB-15754.cs
  test/SlowTests/Issues/RavenDB-21028.cs
  test/SlowTests/Server/Documents/ETL/EtlTestBase.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
  test/SlowTests/Server/Documents/PeriodicBackup/RavenDB-20544.cs
  test/SlowTests/SparrowTests/MicrosoftLogTests.cs
  test/StressTests/Rachis/DatabaseCluster/ClusterDatabaseMaintenanceStress.cs
  test/Tests.Infrastructure/RavenTestBase.Backup.cs
  test/Tests.Infrastructure/Utils/DummyWebSocket.cs
Labels: v5.4

#18191 RavenDB-22033 Filter out expired certificates by default
  src/Raven.Studio/typescript/viewmodels/manage/certificates.ts
Labels: v5.4, Studio

#18190 RavenDB-21985 Make show staleness reason button better visible
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexProgressTooltip.tsx
Labels: v6.0, Studio

#18186 RavenDB-22054 After creating an incremental backup, `Last full backup…
  src/Raven.Studio/typescript/components/pages/database/tasks/ongoingTasks/panels/PeriodicBackupPanel.tsx
Labels: v6.0, Studio

#18187 RavenDB-21992 Changed test to run only on x64
  test/SlowTests/SlowTests/Indexes/MapReduceIndexOnLargeDataSet.cs
Labels: v5.4

#18176 RavenDB-22090: Failing tests in local environment.
  test/SlowTests/Issues/RavenDB-21784.cs
  test/SlowTests/Server/Documents/ETL/ConnectionStringTests.cs
  test/SlowTests/Server/Documents/QueueSink/RabbitMqSinkTests.cs
  test/SlowTests/Sharding/ETL/ShardedEtlTests.cs
Labels: v6.0

#18193 5.4 to 6.0 merge
  src/Raven.Server/Documents/PeriodicBackup/BackupTask.cs
  src/Raven.Studio/typescript/viewmodels/manage/certificates.ts
  test/RachisTests/BasicTests.cs
  test/SlowTests/Client/Subscriptions/ConcurrentSubscriptionsTests.cs
  test/SlowTests/Client/Subscriptions/RavenDB_9117.cs
  test/SlowTests/Cluster/ClusterObserverTests.cs
  test/SlowTests/ExtensionPoints/ExtensionPointsTests.cs
  test/SlowTests/Issues/RavenDB-15754.cs
  test/SlowTests/Issues/RavenDB-21028.cs
  test/SlowTests/Issues/RavenDB-21668.cs
  test/SlowTests/Issues/RavenDB-21784.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
  test/SlowTests/Server/Documents/PeriodicBackup/RavenDB-20544.cs
  test/SlowTests/Server/Documents/QueueSink/RabbitMqSinkTests.cs
  test/SlowTests/Sharding/ETL/ShardedEtlTests.cs
  test/SlowTests/SlowTests/Indexes/MapReduceIndexOnLargeDataSet.cs
  test/SlowTests/SparrowTests/MicrosoftLogTests.cs
  test/SlowTests/Tests/TestsInheritanceTests.cs
  test/StressTests/Rachis/DatabaseCluster/ClusterDatabaseMaintenanceStress.cs
  test/Tests.Infrastructure/RavenTestBase.Backup.cs
  test/Tests.Infrastructure/RavenTestBase.Etl.cs
  test/Tests.Infrastructure/Utils/DummyWebSocket.cs
Labels: v6.0

#18174 RavenDB-22119: wait for index in test
  test/SlowTests/Client/Subscriptions/RevisionsSubscriptions.cs
Labels: v5.4

#18194 RavenDB-22131 - use cluster nodes in test instead of all Servers list
  test/SlowTests/Issues/RavenDB-19922.cs
Labels: v5.4

#18189 RavenDB-22116 add debug method to delete document by etag
  src/Raven.Server/Documents/DocumentsStorage.Debug.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Voron/Data/Tables/Table.cs
Labels: v5.4

#18198 RavenDB-22080 Eslint no unused vars as warning
  src/Raven.Studio/.eslintrc.js
Labels: v6.0, Studio

#18200 RavenDB-21797 Updated `UpgradeInfoHandler`
  src/Raven.Server/Web/Studio/UpgradeInfoHandler.cs
Labels: v6.0

#18202 RavenDB-22111 Fixing the order of checks to address a PR comment
  src/Raven.Server/RavenServerStartup.cs
Labels: v6.0

#18207 RavenDB-22128 : add test
  test/SlowTests/Issues/RavenDB_22128.cs
Labels: v5.4

#18206 RavenDB-21233 Add ignore MaxStepsForScript limit button in studio
  src/Raven.Studio/typescript/commands/database/patch/patchCommand.ts
  src/Raven.Studio/typescript/viewmodels/database/patch/patch.ts
  src/Raven.Studio/wwwroot/App/views/database/patch/patch.html
Labels: v5.4, Studio

#18177 RavenDB-21945 Wait limited time for get disk stats
  src/Raven.Server/RavenServer.cs
  src/Sparrow.Server/Utils/DiskStatsGetter/DiskStatsGetter.cs
  src/Sparrow.Server/Utils/DiskStatsGetter/IDiskStatsGetter.cs
  src/Sparrow.Server/Utils/DiskStatsGetter/LinuxDiskStatsGetter.cs
  src/Sparrow.Server/Utils/DiskStatsGetter/NotImplementedDiskStatsGetter.cs
  src/Sparrow.Server/Utils/DiskStatsGetter/WindowsDiskStatsGetter.cs
  src/Sparrow.Server/Utils/DiskUtils.cs
  test/SlowTests/Monitoring/DiskStatsGetterTest.cs
  test/Tests.Infrastructure/RavenTestCategory.cs
Labels: v5.4

#18209 RavenDB-22134 MaybeBreakTies has to use non-negative number for comparison. IndirectComparer has to apply negative scalar to the result after comparison.
  src/Corax/Querying/Matches/SortingMatches/SortingMatch.Comparers.cs
  src/Corax/Querying/Matches/SortingMatches/SortingMultiMatch.Comparers.cs
  test/SlowTests/Corax/CoraxOrderBy.cs
Labels: v6.0

#18213 RavenDB-21558 Register all pages that belong to `RootObjects` to avoid false positive gap reporting in Storage page report.
  src/Voron/StorageEnvironment.cs
Labels: Corax, v6.0

#18218 RavenDB-21012 Fixing occasionally failing test related to a tombstone blockage notification
  test/SlowTests/Issues/RavenDB-19967.cs
Labels: v6.0

#18219 RavenDB-21980 - documentation for DocumentSession stream
  src/Raven.Client/DocumentationUrls.cs
  src/Raven.Client/Documents/Session/IAdvancedSessionOperations.Stream.cs
Labels: v6.0

#18224 RavenDB-21947 - RachisTests.DatabaseCluster.ClusterDatabaseMaintenance.ClientShouldFailoverWhenTalkingToLoneDisconnectedNode
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
Labels: v5.4

#18222 5.4 to 6.0 merge
  src/Raven.Server/Documents/DocumentsStorage.Debug.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/RavenServer.cs
  src/Raven.Studio/typescript/commands/database/patch/patchCommand.ts
  src/Raven.Studio/typescript/viewmodels/database/patch/patch.ts
  src/Raven.Studio/wwwroot/App/views/database/patch/patch.html
  src/Sparrow.Server/Utils/DiskStatsGetter/DiskStatsGetter.cs
  src/Sparrow.Server/Utils/DiskStatsGetter/IDiskStatsGetter.cs
  src/Sparrow.Server/Utils/DiskStatsGetter/LinuxDiskStatsGetter.cs
  src/Sparrow.Server/Utils/DiskStatsGetter/NotImplementedDiskStatsGetter.cs
  src/Sparrow.Server/Utils/DiskStatsGetter/WindowsDiskStatsGetter.cs
  src/Sparrow.Server/Utils/DiskUtils.cs
  src/Voron/Data/Tables/Table.cs
  test/FastTests/Client/AsyncHelperTest.cs
  test/SlowTests/Issues/RavenDB-19922.cs
  test/SlowTests/Issues/RavenDB_22128.cs
  test/SlowTests/Monitoring/DiskStatsGetterTest.cs
  test/Tests.Infrastructure/RavenTestCategory.cs
Labels: v6.0

#18226 RavenDB-21911 Fix significance level calculation
  test/SlowTests/Monitoring/DiskStatsGetterTest.cs
Labels: v5.4

#18228 RavenDB-17620 Using MRE to stop the index in a test instead of Thread.Sleep to avoid races
  test/SlowTests/Issues/RavenDB_17237.cs
Labels: v5.4

#18229 RavenDB-22132 - Fix ClusterTransactionTests.ClusterTransactionConflict test for sharding
  test/SlowTests/Cluster/ClusterTransactionTests.cs
Labels: v6.0

#18195 RavenDB-22050 NRE in bulk insert heartbeat
  src/Raven.Client/Documents/BulkInsert/BulkInsertOperation.cs
Labels: v5.4

#18239 RavenDB-22051 More info to ResponsibleNodeForBackup_PinnedMentorNode …
  test/SlowTests/Issues/RavenDB-19922.cs
Labels: v5.4

#18244 5.4 to 6.0 merge
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
  test/SlowTests/Authentication/AuthenticationLetsEncryptTests.cs
  test/SlowTests/Issues/RavenDB-19922.cs
  test/SlowTests/Issues/RavenDB_11255.cs
  test/SlowTests/Issues/RavenDB_17237.cs
  test/SlowTests/Monitoring/DiskStatsGetterTest.cs
  test/SlowTests/Tests/TestsInheritanceTests.cs
  test/Tests.Infrastructure/RavenIntegrationRetryFactAttribute.cs
Labels: v6.0

#18246 RavenDB-22149: fix NRE in subscription tryout
  src/Raven.Server/Documents/Subscriptions/Processor/AbstractSubscriptionProcessor.cs
  src/Raven.Server/Documents/Subscriptions/Processor/TestSubscriptionProcessor.cs
Labels: v6.0

#18247 RavenDB-22109: Ensure `VerifyLicense` is invoked in all `RavenServer` instantiations
  src/Raven.Server/Program.cs
  src/Raven.Server/RavenServer.cs
Labels: v5.4

#18248 RavenDB-22109: Ensure `VerifyLicense` is invoked in all `RavenServer` instantiations
  src/Raven.Server/Program.cs
  src/Raven.Server/RavenServer.cs
Labels: v6.0

#18245 RavenDB-21965 Avoid adding to `Reply` if shouldn't
  src/Raven.Server/Documents/Handlers/Batches/Commands/MergedBatchCommand.cs
  src/Raven.Server/Documents/Handlers/Batches/Commands/MergedBatchCommandDto.cs
  src/Raven.Server/Documents/Patch/PatchDocumentCommand.cs
  src/Raven.Server/Documents/TransactionMerger/Commands/JsonPatchCommand.cs
  test/FastTests/Client/BatchCommandWithNoReplyFlagTest.cs
Labels: v6.0

#18259 RavenDB-22050 NRE in bulk insert heartbeat
  src/Raven.Client/Documents/BulkInsert/BulkInsertOperation.cs
Labels: v6.0

#18256 RavenDB-22090: Do not cause a double dispose.
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
Labels: v5.4

#18263 RavenDB-21991 Modify test to get more info on failing
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
Labels: v5.4

#18264 RavenDB-7070 Reverting Jint to 3.0.0
  src/Raven.Server/Raven.Server.csproj
Labels: v6.0

#18272 5.4 to 6.0 merge
  src/Raven.Client/Raven.Client.csproj
  src/Sparrow/Sparrow.csproj
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
Labels: v6.0

#18227 RavenDB-22138 When receiving 503 Studio says the document was not found
  src/Raven.Studio/typescript/viewmodels/database/documents/editDocument.ts
Labels: v6.0, Studio

#18278 RavenDB-7070 Fixing build error because of referencing Microsoft.Bcl.AsyncInterfaces.dll in different versions. Fixing warnings
  src/Raven.Client/Documents/Queries/Facets/Facet.cs
  src/Raven.Server/Raven.Server.csproj
  src/Sparrow/Json/AbstractBlittableJsonTextWriter.cs
Labels: v6.0

#18270 RavenDB-20123 Properly waiting for cache to be outdated
  test/SlowTests/Bugs/Caching/UseCachingInLazyTests.cs
Labels: v5.4

#18276 RavenDB-21922 - fix failing tests
  src/Raven.Server/Documents/Replication/Incoming/IncomingReplicationHandler.cs
Labels: v6.0

#18286 RavenDB-22129 - Remove Client API code that checks if Cluster Transaction is supported
  src/Raven.Client/Http/RequestExecutor.cs
Labels: v5.4

#18289 RavenDB-22156 - MixedClusterTests.UpgradeDirectlyFrom42X is failing when updating from 4.2.0 (v5.4)
  src/Raven.Server/Documents/Handlers/BatchHandler.cs
  test/InterversionTests/MixedClusterTests.cs
Labels: v5.4

#18285 RavenDB-22156 - MixedClusterTests.UpgradeDirectlyFrom42X is failing when updating from 4.2.0
  src/Raven.Server/Documents/Handlers/Processors/Batches/AbstractClusterTransactionRequestProcessor.cs
  test/InterversionTests/MixedClusterTests.cs
Labels: v6.0

#18282 RavenDB-22180 increase max number of concurrent backups to 128
  test/Tests.Infrastructure/TestBase.cs
Labels: v6.0

#18234 RavenDB-21636 SlowTests.Issues.RavenDB_20084.ShouldUpdateBackupInfoIf…
  src/Raven.Server/Utils/BackupUtils.cs
  test/SlowTests/Issues/RavenDB_20084.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
Labels: v6.0

#18299 RavenDB-22203 `database` object is passed as name in command
  src/Raven.Studio/typescript/commands/database/dbGroup/startReshardingCommand.ts
  src/Raven.Studio/typescript/commands/database/documents/saveConflictSolverConfigurationCommand.ts
  src/Raven.Studio/typescript/commands/database/tasks/delayBackupCommand.ts
  src/Raven.Studio/typescript/commands/database/tasks/getPeriodicBackupConfigurationCommand.ts
  src/Raven.Studio/typescript/commands/database/tasks/saveSubscriptionTaskCommand.ts
  src/Raven.Studio/typescript/commands/resources/getDatabaseRecordCommand.ts
Labels: v6.0, Studio

#18301 RavenDB-7070 avoid sync over async in tests
  test/SlowTests/Server/Documents/ETL/EtlTestBase.cs
Labels: v5.4

#18296 RavenDB-22202 Add index to `AdditionalDebugInformation.AdditionalDebugInformation`
  src/Raven.Server/ServerWide/Commands/ClusterTransactionCommand.cs
Labels: v6.0

#18300 5.4 to 6.0 merge
  src/Raven.Client/Http/RequestExecutor.cs
  test/InterversionTests/SmugglerTests.cs
  test/RachisTests/AddNodeToClusterTests.cs
  test/RachisTests/DatabaseCluster/ClusterDatabaseMaintenance.cs
  test/RachisTests/DatabaseCluster/ReplicationTests.cs
  test/SlowTests/Bugs/Caching/UseCachingInLazyTests.cs
  test/SlowTests/Cluster/ClusterModesForRequestExecutorTest.cs
  test/SlowTests/Cluster/ClusterObserverTests.cs
  test/SlowTests/Issues/RDoc-1995.cs
  test/SlowTests/Issues/RavenDB-19967.cs
  test/SlowTests/Issues/RavenDB_14235.cs
  test/SlowTests/Issues/RavenDB_19529.cs
  test/SlowTests/Server/Documents/ETL/EtlTimeSeriesTests.cs
  test/SlowTests/Server/Documents/ETL/Olap/FailoverTests.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Restore/RestoreFromAzure.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Restore/RestoreFromGoogleCloud.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Restore/RestoreFromS3.cs
  test/SlowTests/Server/Replication/ReplicationCleanTombstones.cs
  test/SlowTests/Smuggler/BackupDatabaseRecordTests.cs
  test/StressTests/Issues/RavenDB-15080.cs
  test/StressTests/Rachis/DatabaseCluster/ClusterDatabaseMaintenanceStress.cs
  test/StressTests/Server/Documents/ETL/Olap/LocalTestsStress.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
  test/Tests.Infrastructure/InterversionTestBase.cs
  test/Tests.Infrastructure/RavenTestBase.Etl.cs
Labels: v6.0

#18309 RavenDB-22174 Adding more debug info if the test fails again
  test/SlowTests/Issues/RavenDB_11255.cs
Labels: v5.4

#18304 RavenDB-21636 ShouldUpdateBackupInfoIfDatabaseUnloaded - remove local…
  src/Raven.Server/Utils/BackupUtils.cs
  test/SlowTests/Issues/RavenDB_20084.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
Labels: v5.4

#18308 RavenDB-22172 Fixing exception message in ClusterTestBase
  test/Tests.Infrastructure/ClusterTestBase.cs
Labels: v6.0
