Repository ravendb/ravendb, pull requests merged in 2024-11, with the labels that each got.

#19554 RavenDB-23101 fixed issue with zstd in EmbeddedTests
  src/Sparrow/Utils/ZstdLib.cs
  test/EmbeddedTests/DynamicNativeLibraryResolver.cs
  test/EmbeddedTests/EmbeddedTestBase.cs
Labels: v7.0

#19562 RavenDB-23106 added Polly to LetsEncryptClient to handle Retry-After header properly
  src/Raven.Server/Commercial/LetsEncryptClient.cs
Labels: v5.4

#19561 RavenDB-23105 Fix some comments in SecurityConfigurations.cs
  src/Raven.Server/Config/Categories/SecurityConfiguration.cs
Labels: v6.0

#19566 5.4 to 6.0 merge
  src/Raven.Client/Documents/BulkInsert/BulkInsertOperation.cs
  src/Raven.Server/Commercial/LetsEncryptClient.cs
  src/Raven.Server/Rachis/LogSummary.cs
  src/Raven.Server/Rachis/RachisConsensus.Debug.cs
  src/Raven.Server/Rachis/RachisLogHistory.cs
  src/Raven.Studio/typescript/commands/database/cluster/getClusterLogCommand.ts
  src/Raven.Studio/typescript/viewmodels/manage/debugAdvancedClusterDebug.ts
Labels: v6.0

#19567 6.0 to 6.2 merge
  src/Raven.Client/Documents/BulkInsert/BulkInsertOperation.cs
  src/Raven.Client/Documents/Commands/GetRemoteTaskTopologyCommand.cs
  src/Raven.Server/Commercial/LetsEncryptClient.cs
  src/Raven.Server/Config/Categories/SecurityConfiguration.cs
  src/Raven.Server/Documents/Replication/Incoming/IncomingPullReplicationHandler.cs
  src/Raven.Server/Documents/Replication/Incoming/IncomingReplicationHandler.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/Rachis/LogSummary.cs
  src/Raven.Server/Rachis/RachisConsensus.Debug.cs
  src/Raven.Server/Rachis/RachisLogHistory.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Web/System/DatabasesDebugHandler.cs
  src/Raven.Server/Web/System/TcpConnectionInfoHandler.cs
  src/Raven.Studio/typescript/commands/database/cluster/getClusterLogCommand.ts
  src/Raven.Studio/typescript/viewmodels/manage/debugAdvancedClusterDebug.ts
  test/SlowTests/Server/Replication/PullReplicationTests.cs
Labels: v6.2

#19568 6.2 to 7.0 merge
  src/Raven.Client/Constants.cs
  src/Raven.Client/Documents/BulkInsert/BulkInsertOperation.cs
  src/Raven.Client/Documents/Commands/GetRemoteTaskTopologyCommand.cs
  src/Raven.Client/Documents/Linq/LinqPathProvider.cs
  src/Raven.Client/Documents/Linq/RavenQueryProviderProcessor.cs
  src/Raven.Client/Documents/Queries/RavenQuery.cs
  src/Raven.Client/Exceptions/Database/BackupAlreadyRunningException.cs
  src/Raven.Client/Exceptions/ExceptionDispatcher.cs
  src/Raven.Client/Properties/VersionInfo.cs
  src/Raven.Client/Util/JavascriptConversionExtensions.cs
  src/Raven.Server/Commercial/LetsEncryptClient.cs
  src/Raven.Server/Config/Categories/SecurityConfiguration.cs
  src/Raven.Server/Documents/Handlers/Processors/OngoingTasks/AbstractOngoingTasksHandlerProcessorForBackupDatabaseNow.cs
  src/Raven.Server/Documents/Handlers/Processors/OngoingTasks/OngoingTasksHandlerProcessorForBackupDatabaseNow.cs
  src/Raven.Server/Documents/Handlers/Processors/OngoingTasks/OngoingTasksHandlerProcessorForGetRunningBackupOperationStatus.cs
  src/Raven.Server/Documents/Operations/AbstractOperations.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
  src/Raven.Server/Documents/Replication/Incoming/IncomingPullReplicationHandler.cs
  src/Raven.Server/Documents/Replication/Incoming/IncomingReplicationHandler.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/OngoingTasks/ShardedOngoingTasksHandlerProcessorForBackupDatabaseNow.cs
  src/Raven.Server/Integrations/PostgreSQL/RqlQuery.cs
  src/Raven.Server/Rachis/LogSummary.cs
  src/Raven.Server/Rachis/RachisConsensus.Debug.cs
  src/Raven.Server/Rachis/RachisLogHistory.cs
  src/Raven.Server/RavenServer.cs
  src/Raven.Server/RavenServerStartup.cs
  src/Raven.Server/Routing/RavenActionAttribute.cs
  src/Raven.Server/Routing/RequestRouter.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Utils/BackupUtils.cs
  src/Raven.Server/Web/System/DatabasesDebugHandler.cs
  src/Raven.Server/Web/System/OngoingTasksHandler.cs
  src/Raven.Server/Web/System/StudioHandler.cs
  src/Raven.Server/Web/System/TcpConnectionInfoHandler.cs
  src/Raven.Studio/package-lock.json
  src/Raven.Studio/package.json
  src/Raven.Studio/typescript/commands/database/cluster/getClusterLogCommand.ts
  src/Raven.Studio/typescript/components/common/select/Select.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/cleanup/IndexCleanup.spec.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/cleanup/IndexCleanupAboutView.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/cleanup/carouselCards/RemoveSubindexesCard.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/cleanup/carouselCards/UnmergableIndexesCard.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/cleanup/navItems/MergeSuggestionsErrorsNavItem.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/cleanup/navItems/UnmergableIndexesNavItem.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/connectionStrings/EditConnectionStrings.tsx
  src/Raven.Studio/typescript/viewmodels/manage/debugAdvancedClusterDebug.ts
  src/Raven.Studio/wwwroot/App/views/shell.html
  test/FastTests/Client/RavenQueryTests.cs
  test/RachisTests/DatabaseCluster/AtomicClusterReadWriteTests.cs
  test/SlowTests/Issues/EncryptedDatabaseGroup.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
  test/SlowTests/Server/Replication/PullReplicationTests.cs
  test/SlowTests/Sharding/Backup/ShardedBackupTests .cs
  test/SlowTests/Sharding/Backup/ShardedRestoreBackupTests.cs
  test/SlowTests/Sharding/Cluster/ReshardingTests.cs
  test/SlowTests/Sharding/Cluster/ShardedClusterObserverTests.cs
  test/SlowTests/Sharding/PrefixedSharding.cs
  test/Tests.Infrastructure/RavenTestBase.Backup.cs
  test/Tests.Infrastructure/RavenTestBase.ShardedBackupTestBase.cs
Labels: v7.0

#19570 RavenDB-23069 Index Cleanup view: Add link to documentation
  src/Raven.Studio/typescript/components/pages/database/indexes/cleanup/IndexCleanupAboutView.tsx
Labels: Studio, v6.2

#19551 RavenDB-23099 Fix XML comments for DeleteRevisionsOperation
  src/Raven.Client/DocumentationUrls.cs
  src/Raven.Client/Documents/Operations/Revisions/DeleteRevisionsOperation.cs
Labels: v6.2

#19555 RavenDB-21946 - Conflict resolution LastModifiedTime value is not updated after saving
  src/Raven.Client/Documents/Operations/Configuration/GetConflictSolverConfigurationOperation.cs
  test/FastTests/Client/RavenCommandTest.cs
  test/SlowTests/Issues/RavenDB_21946.cs
Labels: v6.2

#19577 RavenDB-23115 the date in the description needs to be an invariant string
  src/Raven.Server/Documents/PeriodicBackup/BackupUploader.cs
Labels: v5.4

#19579 5.4 to 6.0 merge
  src/Raven.Server/Documents/PeriodicBackup/BackupUploader.cs
Labels: v6.0

#19581 6.2 to 7.0 merge
  src/Raven.Client/DocumentationUrls.cs
  src/Raven.Client/Documents/Operations/Revisions/DeleteRevisionsOperation.cs
  src/Raven.Client/Json/Serialization/JsonDeserializationClient.cs
  src/Raven.Client/ServerWide/ConflictSolver.cs
  src/Raven.Server/Documents/PeriodicBackup/BackupUploader.cs
  src/Raven.Studio/typescript/components/pages/database/indexes/cleanup/IndexCleanupAboutView.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/documentRevisions/DocumentRevisions.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/documentRevisions/revertRevisions/RevertRevisions.spec.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/documentRevisions/revertRevisions/RevertRevisions.tsx
  test/SlowTests/Issues/RavenDB_21946.cs
Labels: v7.0

#19586 RavenDB-23131 introduced internal ConfigureHttpMessageHandler method to inject different certificate validation callback for sharding
  src/Raven.Client/Documents/Conventions/DocumentConventions.cs
  src/Raven.Client/Http/DefaultRavenHttpClientFactory.cs
  src/Raven.Client/Http/HttpClientCacheKey.cs
  src/Raven.Client/Http/RequestExecutor.cs
  src/Raven.Server/ServerWide/ShardingStore.cs
  src/Raven.Server/Utils/RavenServerHttpClientFactory.cs
  test/FastTests/Issues/RavenDB_22436.cs
Labels: v6.0

#19575 RavenDB-23113 About page typo
  src/Raven.Studio/typescript/common/generalUtils.ts
  src/Raven.Studio/typescript/models/auth/licenseModel.ts
Labels: v5.4, Studio

#19576 RavenDB-23113 About page typo
  src/Raven.Studio/typescript/common/generalUtils.ts
  src/Raven.Studio/typescript/models/auth/licenseModel.ts
Labels: v6.0, Studio

#19588 RavenDB-23024 Fix dependency array in Backups page
  src/Raven.Studio/typescript/components/pages/database/tasks/backups/BackupsPage.tsx
Labels: v6.0, Studio

#19540 RavenDB-23086 Virtual table: add column filter
  src/Raven.Studio/typescript/components/common/virtualTable/VirtualTable.stories.tsx
  src/Raven.Studio/typescript/components/common/virtualTable/VirtualTable.tsx
  src/Raven.Studio/typescript/components/common/virtualTable/VirtualTableWithLazyLoading.tsx
  src/Raven.Studio/typescript/components/common/virtualTable/bits/VirtualTableHead.tsx
  src/Raven.Studio/typescript/components/common/virtualTable/columnProviders/useDocumentColumnsProvider.tsx
  src/Raven.Studio/typescript/components/common/virtualTable/utils/commonColumnDefs.tsx
  src/Raven.Studio/typescript/components/common/virtualTable/utils/documentColumnDefs.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/customSorters/DatabaseCustomSorterTestResult.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/tombstones/TombstonesState.tsx
  src/Raven.Studio/typescript/test/storybookTestUtils.tsx
Labels: v6.0, Studio

#19597 6.0 to 6.2 merge
  src/Raven.Client/DocumentationUrls.cs
  src/Raven.Client/Documents/Conventions/DocumentConventions.cs
  src/Raven.Client/Http/DefaultRavenHttpClientFactory.cs
  src/Raven.Client/Http/HttpClientCacheKey.cs
  src/Raven.Client/Http/RequestExecutor.cs
  src/Raven.Client/ServerWide/Operations/Certificates/DeleteCertificateOperation.cs
  src/Raven.Client/ServerWide/Operations/Certificates/EditClientCertificateOperation.cs
  src/Raven.Client/ServerWide/Operations/Certificates/PutClientCertificateOperation.cs
  src/Raven.Client/ServerWide/Operations/Certificates/ReplaceClusterCertificateOperation.cs
  src/Raven.Client/ServerWide/Operations/Configuration/PutServerWideClientConfigurationOperation.cs
  src/Raven.Client/ServerWide/Operations/Logs/SetLogsConfigurationOperation.cs
  src/Raven.Client/ServerWide/Operations/ReorderDatabaseMembersOperation.cs
  src/Raven.Client/ServerWide/Operations/TrafficWatch/PutTrafficWatchConfigurationOperation.cs
  src/Raven.Server/Monitoring/MetricsProvider.cs
  src/Raven.Server/ServerWide/ShardingStore.cs
  src/Raven.Server/Utils/Monitoring/ServerMetrics.cs
  src/Raven.Server/Utils/RavenServerHttpClientFactory.cs
  src/Raven.Server/Web/System/AdminPrometheusMonitoringHandler.cs
  src/Raven.Studio/typescript/common/generalUtils.ts
  src/Raven.Studio/typescript/components/common/virtualTable/VirtualTable.stories.tsx
  src/Raven.Studio/typescript/components/common/virtualTable/VirtualTable.tsx
  src/Raven.Studio/typescript/components/common/virtualTable/VirtualTableWithLazyLoading.tsx
  src/Raven.Studio/typescript/components/common/virtualTable/bits/VirtualTableHead.tsx
  src/Raven.Studio/typescript/components/common/virtualTable/columnProviders/useDocumentColumnsProvider.tsx
  src/Raven.Studio/typescript/components/common/virtualTable/utils/commonColumnDefs.tsx
  src/Raven.Studio/typescript/components/common/virtualTable/utils/documentColumnDefs.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/customSorters/DatabaseCustomSorterTestResult.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/tombstones/TombstonesState.tsx
  src/Raven.Studio/typescript/components/pages/database/tasks/backups/BackupsPage.tsx
  src/Raven.Studio/typescript/models/auth/licenseModel.ts
  src/Raven.Studio/typescript/test/storybookTestUtils.tsx
  test/FastTests/Issues/RavenDB_22436.cs
Labels: v6.2

#19598 RavenDB-23137 Fix studio v7.0 build
  src/Raven.Studio/typescript/components/common/Icon.stories.tsx
Labels: Studio, v7.0

#19601 RavenDB-23135 upon server startup ensure update of license limits
  src/Raven.Server/Commercial/LicenseManager.cs
Labels: v5.4

#19599 RavenDB-22840 - RemoveRevertFlagAfterNewInfo2 Fails (v5.4)
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  src/Voron/Data/Tables/Table.cs
  test/SlowTests/Issues/RavenDB-22840.cs
Labels: v5.4

#19604 RavenDB-22997 Move query timings into a separate column
  src/Raven.Studio/typescript/viewmodels/manage/trafficWatch.ts
  src/Raven.Studio/wwwroot/Content/css/styles-common-scoped.less
Labels: Studio, v6.2

#19608 RavenDB-23147 Add new paths used by RavenDB to deb & docker
  docker/ravendb-ubuntu/Dockerfile.arm32v7
  docker/ravendb-ubuntu/Dockerfile.arm64v8
  docker/ravendb-ubuntu/Dockerfile.x64
  scripts/linux/pkg/deb/assets/ravendb/debian/ravendb.postinst
  scripts/linux/pkg/deb/assets/ravendb/debian/ravendb.service
  scripts/linux/pkg/deb/ubuntu_test.Dockerfile
Labels: v7.0

#19615 RavenDB-23157 Admin logs: minor fixes
  src/Raven.Studio/typescript/components/pages/resources/manageServer/adminLogs/AdminLogs.tsx
  src/Raven.Studio/typescript/components/pages/resources/manageServer/adminLogs/bits/AdminLogsVirtualList.tsx
  src/Raven.Studio/wwwroot/Content/scss/_bs5extend.scss
Labels: Studio, v7.0

#19607 RavenDB-22532 Update license stubs
  src/Raven.Studio/typescript/test/stubs/LicenseStubs.ts
Labels: v6.0, Studio

#19606 RavenDB-23133 Databases: fix NRE
  src/Raven.Studio/typescript/viewmodels/resources/databases.ts
Labels: v5.4, Studio

#19616 RavenDB-22345 - CanCreateClusterTransactionRequest2
  src/Raven.Client/Exceptions/ExceptionDispatcher.cs
  src/Raven.Server/Rachis/Follower.cs
Labels: v6.0

#19625 RavenDB-23070 Dismiss cluster transaction error notification
  src/Raven.Server/Documents/DocumentDatabase.cs
Labels: v5.4

#19638 RavenDB-22947 Cluster Dashboard: GC widget - fixed icons
  src/Raven.Studio/wwwroot/App/views/resources/widgets/gcInfoWidget.html
Labels: Studio, v6.2

#19644 RavenDB-22947 Cluster Dashboard: GC widget - fixed icons
  src/Raven.Studio/wwwroot/App/views/resources/widgets/gcInfoWidget.html
Labels: v6.0, Studio

#19643 RavenDB-22947 Cluster Dashboard: GC widget
  src/Raven.Studio/typescript/viewmodels/resources/widgets/gcInfoWidget.ts
Labels: v5.4, Studio

#19646 RavenDB-22363 Test fix: there is a chance of race condition between finishing replacement (pausing and rerunning the index) and receiving information from the database record during `WaitForIndexing`.
  test/SlowTests/Issues/RavenDB_22363.cs
Labels: v6.0

#19648 RavenDB-20951 Fix cluster dashboard nodes container
  src/Raven.Studio/typescript/models/resources/widgets/gcInfo.ts
  src/Raven.Studio/wwwroot/App/views/resources/widgets/gcInfoWidget.html
  src/Raven.Studio/wwwroot/Content/css/pages/cluster-dashboard.less
  src/Raven.Studio/wwwroot/Content/css/styles-common-scoped.less
Labels: v6.0, Studio

#19647 RavenDB-23089 Testfix: wait for the error to be persisted before reading it in the test.
  test/SlowTests/Issues/RavenDB-22369.cs
Labels: v6.0

#19649 6.0 to 6.2 merge
  src/Raven.Client/Documents/Indexes/IndexingOperation.cs
  src/Raven.Client/Properties/VersionInfo.cs
  src/Raven.Server/Commercial/LicenseAttribute.cs
  src/Raven.Server/Commercial/LicenseStatus.cs
  src/Raven.Server/Commercial/LicenseValidator.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/IndexDefinitionBaseServerSide.cs
  src/Raven.Server/Documents/Indexes/MapReduce/Static/MapReduceIndex.cs
  src/Raven.Server/Documents/Indexes/Static/CurrentIndexingScope.cs
  src/Raven.Server/Documents/Indexes/Static/MapIndex.cs
  src/Raven.Server/Documents/Indexes/Workers/Counters/HandleCompareExchangeCountersReferences.cs
  src/Raven.Server/Documents/Indexes/Workers/Counters/HandleCountersReferences.cs
  src/Raven.Server/Documents/Indexes/Workers/HandleNotNormalizedCompareExchangeReferences.cs
  src/Raven.Server/Documents/Indexes/Workers/HandleNotNormalizedDocumentReferences.cs
  src/Raven.Server/Documents/Indexes/Workers/HandleReferences.cs
  src/Raven.Server/Documents/Indexes/Workers/TimeSeries/HandleCompareExchangeTimeSeriesReferences.cs
  src/Raven.Server/Documents/Indexes/Workers/TimeSeries/HandleTimeSeriesReferences.cs
  src/Raven.Studio/typescript/models/auth/licenseModel.ts
  src/Raven.Studio/typescript/models/resources/widgets/gcInfo.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexPerformance.ts
  src/Raven.Studio/typescript/viewmodels/resources/widgets/gcInfoWidget.ts
  src/Raven.Studio/wwwroot/App/views/database/indexes/indexPerformance.html
  src/Raven.Studio/wwwroot/App/views/resources/widgets/gcInfoWidget.html
  src/Raven.Studio/wwwroot/Content/css/pages/cluster-dashboard.less
  src/Raven.Studio/wwwroot/Content/css/styles-common-scoped.less
  test/SlowTests/Data/RavenDB_23100/2024-11-18-17-16-52-7843589.ravendb-snapshot
  test/SlowTests/Data/RavenDB_23100/2024-11-19-08-30-34-7519596.ravendb-snapshot
  test/SlowTests/Data/RavenDB_23100/2024-11-19-10-39-25-6242058.ravendb-snapshot
  test/SlowTests/Data/RavenDB_23100/2024-11-19-10-43-34-8245899.ravendb-snapshot
  test/SlowTests/Issues/RavenDB-22369.cs
  test/SlowTests/Issues/RavenDB-23100.cs
  test/SlowTests/Issues/RavenDB_22363.cs
  test/SlowTests/SlowTests.csproj
Labels: v6.2

#19660 6.2 to 7.0 merge
  src/Raven.Client/Documents/Indexes/IndexingOperation.cs
  src/Raven.Client/Properties/VersionInfo.cs
  src/Raven.Server/Commercial/LicenseAttribute.cs
  src/Raven.Server/Commercial/LicenseStatus.cs
  src/Raven.Server/Commercial/LicenseValidator.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/IndexDefinitionBaseServerSide.cs
  src/Raven.Server/Documents/Indexes/MapReduce/Static/MapReduceIndex.cs
  src/Raven.Server/Documents/Indexes/Static/CurrentIndexingScope.cs
  src/Raven.Server/Documents/Indexes/Static/MapIndex.cs
  src/Raven.Server/Documents/Indexes/Workers/Counters/HandleCompareExchangeCountersReferences.cs
  src/Raven.Server/Documents/Indexes/Workers/Counters/HandleCountersReferences.cs
  src/Raven.Server/Documents/Indexes/Workers/HandleNotNormalizedCompareExchangeReferences.cs
  src/Raven.Server/Documents/Indexes/Workers/HandleNotNormalizedDocumentReferences.cs
  src/Raven.Server/Documents/Indexes/Workers/HandleReferences.cs
  src/Raven.Server/Documents/Indexes/Workers/TimeSeries/HandleCompareExchangeTimeSeriesReferences.cs
  src/Raven.Server/Documents/Indexes/Workers/TimeSeries/HandleTimeSeriesReferences.cs
  src/Raven.Studio/typescript/models/auth/licenseModel.ts
  src/Raven.Studio/typescript/models/resources/widgets/gcInfo.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexPerformance.ts
  src/Raven.Studio/typescript/viewmodels/resources/widgets/gcInfoWidget.ts
  src/Raven.Studio/wwwroot/App/views/database/indexes/indexPerformance.html
  src/Raven.Studio/wwwroot/App/views/resources/widgets/gcInfoWidget.html
  src/Raven.Studio/wwwroot/Content/css/pages/cluster-dashboard.less
  src/Raven.Studio/wwwroot/Content/css/styles-common-scoped.less
  src/Sparrow/RecyclableMemoryStreamFactory.cs
  test/SlowTests/Data/RavenDB_23100/2024-11-18-17-16-52-7843589.ravendb-snapshot
  test/SlowTests/Data/RavenDB_23100/2024-11-19-08-30-34-7519596.ravendb-snapshot
  test/SlowTests/Data/RavenDB_23100/2024-11-19-10-39-25-6242058.ravendb-snapshot
  test/SlowTests/Data/RavenDB_23100/2024-11-19-10-43-34-8245899.ravendb-snapshot
  test/SlowTests/Issues/RavenDB-22369.cs
  test/SlowTests/Issues/RavenDB-23100.cs
  test/SlowTests/Issues/RavenDB_22363.cs
  test/SlowTests/SlowTests.csproj
Labels: v7.0

#19657 RavenDB-14963 - Add CountOfRevisions to Notifications.DatabaseStatsChanged info
  src/Raven.Server/NotificationCenter/BackgroundWork/AbstractDatabaseStatsSender.cs
  src/Raven.Server/NotificationCenter/BackgroundWork/DatabaseStatsSender.cs
  src/Raven.Server/NotificationCenter/BackgroundWork/NotificationCenterDatabaseStats.cs
  src/Raven.Server/NotificationCenter/Notifications/DatabaseStatsChanged.cs
Labels: v7.0

#19663 RavenDB-22637 : XML documentation of IOperation - revert properties back to fields
  src/Raven.Client/Documents/Operations/Counters/CounterBatch.cs
  src/Raven.Client/Documents/Operations/TimeSeries/TimeSeriesOperation.cs
  src/Raven.Client/Documents/Operations/TimeSeries/TimeSeriesRange.cs
Labels: v6.0

#19627 RavenDB-21326 - Switch between decrementing _lowLevelTransaction.DecompressedBufferBytes and Allocator.Release on Transaction.ForgetAbout
  src/Voron/Impl/Transaction.cs
Labels: v5.4

#19667 RavenDB-23070 After executing one by one return with correct values
  src/Raven.Server/Documents/DocumentDatabase.cs
Labels: v6.0

#19637 RavenDB-23072 Limit cluster transaction database command batch by space size
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/ServerWide/Commands/ClusterTransactionCommand.cs
  test/SlowTests/Cluster/ClusterTransactionTests.cs
Labels: v5.4

#19675 RavenDB-23054: Added delete and stream for Incremental Async Session
  src/Raven.Client/Documents/Session/IAsyncSessionDocumentTimeSeries.cs
  test/SlowTests/Client/TimeSeries/Session/TimeSeriesSessionTests.cs
  test/SlowTests/Client/TimeSeries/Session/TimeSeriesStreamingTests.cs
Labels: v5.4

#19676 RavenDB-23187 Admin logs improvements
  src/Raven.Studio/typescript/components/pages/resources/manageServer/adminLogs/AdminLogs.tsx
  src/Raven.Studio/typescript/components/pages/resources/manageServer/adminLogs/bits/AdminLogsFilterField.tsx
  src/Raven.Studio/typescript/components/pages/resources/manageServer/adminLogs/bits/AdminLogsVirtualList.tsx
  src/Raven.Studio/typescript/components/pages/resources/manageServer/adminLogs/store/adminLogsMiddleware.ts
  src/Raven.Studio/typescript/components/pages/resources/manageServer/adminLogs/store/adminLogsSlice.ts
  src/Raven.Studio/typescript/components/pages/resources/manageServer/adminLogs/view/AdminLogsExportButton.tsx
  src/Raven.Studio/typescript/components/pages/resources/manageServer/adminLogs/view/AdminLogsViewSettingsModal.tsx
Labels: Studio, v7.0
