Repository ravendb/ravendb, pull requests merged in 2024-04, with the labels that each got.

#18310 5.4 to 6.0 merge
  src/Raven.Server/ServerWide/Commands/ClusterTransactionCommand.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Utils/BackupUtils.cs
  test/FastTests/Client/Subscriptions/SubscriptionsBasic.cs
  test/InterversionTests/MixedClusterTestBase.cs
  test/RachisTests/BasicTests.cs
  test/RachisTests/SubscriptionFailoverWIthWaitingChains.cs
  test/SlowTests/Authentication/AuthenticationLetsEncryptTests.cs
  test/SlowTests/Client/Subscriptions/ConcurrentSubscriptionsTests.cs
  test/SlowTests/Client/Subscriptions/RavenDB_3491.cs
  test/SlowTests/Client/Subscriptions/TestSubscriptionOnDisabledDatabase.cs
  test/SlowTests/Cluster/ClusterTransactionTests.cs
  test/SlowTests/Core/Session/Advanced.cs
  test/SlowTests/Issues/RavenDB-16468.cs
  test/SlowTests/Issues/RavenDB-16659.cs
  test/SlowTests/Issues/RavenDB-17096.cs
  test/SlowTests/Issues/RavenDB-17624.cs
  test/SlowTests/Issues/RavenDB-17650.cs
  test/SlowTests/Issues/RavenDB-17745.cs
  test/SlowTests/Issues/RavenDB14709.cs
  test/SlowTests/Issues/RavenDB_11255.cs
  test/SlowTests/Issues/RavenDB_12259.cs
  test/SlowTests/Issues/RavenDB_17231.cs
  test/SlowTests/Issues/RavenDB_19548.cs
  test/SlowTests/Issues/RavenDB_20084.cs
  test/SlowTests/Issues/RavenDB_3232.cs
  test/SlowTests/Issues/RavenDB_6285.cs
  test/SlowTests/Issues/RavenDB_7589.cs
  test/SlowTests/Server/Documents/ETL/Olap/FailoverTests.cs
  test/SlowTests/Server/Documents/ETL/Olap/S3Tests.cs
  test/SlowTests/Server/Documents/ETL/Raven/RDBS_85.cs
  test/SlowTests/Server/Documents/ETL/RavenDB_20757.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
  test/SlowTests/Server/Documents/PeriodicBackup/Restore/RestoreFromAzure.cs
  test/SlowTests/Server/Replication/PullReplicationTests.cs
  test/StressTests/Server/Documents/ETL/Olap/LocalTestsStress.cs
  test/Tests.Infrastructure/ClusterTestBase.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v6.0

#18320 RavenDB-21801 - dont fail test on failing delete temp file
  test/InterversionTests/SmugglerTests.cs
Labels: v6.0

#18319 RavenDB-22185 - fix failing test
  test/SlowTests/Server/Documents/Notifications/ChangesTests.cs
Labels: v5.4

#18315 RavenDB-22196 Expose referenced collections in index statistics.
  src/Raven.Client/Documents/Indexes/IndexStats.cs
  src/Raven.Server/Documents/Handlers/IndexHandler.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  test/SlowTests/Issues/RavenDB_22196.cs
Labels: v5.4

#18313 RavenDB-22207 Failed to get the debug package for a shareded database
  src/Raven.Server/Documents/Handlers/Debugging/ServerWideDebugInfoPackageHandler.cs
Labels: v6.0

#18327 5.4 to 6.0 merge
  src/Raven.Client/Documents/Indexes/IndexStats.cs
  src/Raven.Server/Documents/Handlers/Processors/Indexes/IndexHandlerProcessorForGetDatabaseIndexStatistics.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Rachis/RachisLogHistory.cs
  test/SlowTests/Issues/RavenDB_22196.cs
  test/SlowTests/Server/Documents/ETL/Queue/KafkaEtlTestBase.cs
  test/SlowTests/Server/Documents/ETL/Queue/RabbitMqEtlTestBase.cs
  test/SlowTests/Server/Documents/Notifications/ChangesTests.cs
  test/SlowTests/Server/Documents/QueueSink/RabbitMqQueueSinkTestBase.cs
  test/SlowTests/Server/Documents/QueueSink/RabbitMqSinkTests.cs
  test/StressTests/Databases.cs
  test/Tests.Infrastructure/ConnectionString/RabbitMqConnectionString.cs
  test/Tests.Infrastructure/RequiresRabbitMqRetryFactAttribute.cs
Labels: v6.0

#18326 RavenDB-21521: Restore PerCoreStatic for storage and key mapping pools.
  src/Sparrow/Json/PerCoreStatic.cs
  src/Voron/Data/CompactTrees/CompactKey.cs
Labels: Corax, v6.0

#18338 RavenDB-22158 Unwrap aggregated exception to check if socket was closed and ignore exception.
  src/Raven.Server/NotificationCenter/Handlers/ProxyWebSocketConnection.cs
Labels: v5.4

#18342 5.4 to 6.0 merge
  src/Raven.Client/Documents/Commands/DocumentSizeDetails.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Handlers/Processors/Documents/DocumentHandlerProcessorForGetDocSize.cs
  src/Raven.Server/NotificationCenter/Handlers/ProxyWebSocketConnection.cs
  src/Raven.Studio/typescript/viewmodels/database/documents/editDocument.ts
  src/Raven.Studio/wwwroot/App/views/database/documents/editDocument.html
  src/Voron/Data/Tables/Table.cs
  test/FastTests/Voron/Tables/Compression.cs
  test/SlowTests/Authentication/AuthenticationLetsEncryptTests.cs
  test/SlowTests/Issues/RavenDB_17231.cs
Labels: v6.0

#18345 RavenDB-21521 Revert "Restore PerCoreStatic for storage and key mapping pools."
  src/Sparrow/Json/PerCoreStatic.cs
  src/Voron/Data/CompactTrees/CompactKey.cs
Labels: v6.0

#18335 RavenDB-22183 / RavenDB-10493 Fixing translation of DateTime.MaxValue to JS date when building RQL with JS projection
  src/Raven.Client/Util/JavascriptConversionExtensions.cs
  test/SlowTests/Issues/RavenDB-10493.cs
Labels: v5.4

#18346 RavenDB-22064 Adjusting the assertion of allocated memory due to recent optimizatitions that could result in slightly different allocation patterns. Adding more strict assertion for the used memory
  test/SlowTests/Issues/RavenDB_13315.cs
Labels: v6.0

#18352 RavenDB-22232 Failed to delete Filtered replication Access
  src/Raven.Server/Documents/Handlers/Processors/Replication/AbstractPullReplicationHandlerProcessorForUnregisterHubAccess.cs
  test/SlowTests/Server/Replication/PullReplicationWithAuthenticationTest.cs
Labels: v6.0

#18343 RavenDB-22229 - fix legacy index replication
  src/Raven.Server/Documents/Handlers/Admin/Processors/Indexes/AbstractAdminIndexHandlerProcessorForJavaScriptPut.cs
  src/Raven.Server/Documents/Handlers/Admin/Processors/Indexes/AbstractAdminIndexHandlerProcessorForPut.cs
  src/Raven.Server/Documents/Handlers/Admin/Processors/Indexes/AbstractAdminIndexHandlerProcessorForStaticPut.cs
  src/Raven.Server/Documents/Handlers/Admin/Processors/Indexes/AdminIndexHandlerProcessorForJavaScriptPut.cs
  src/Raven.Server/Documents/Handlers/Admin/Processors/Indexes/AdminIndexHandlerProcessorForStaticPut.cs
  src/Raven.Server/Documents/Sharding/Handlers/Admin/Processors/Indexes/ShardedAdminIndexHandlerProcessorForJavaScriptPut.cs
  src/Raven.Server/Documents/Sharding/Handlers/Admin/Processors/Indexes/ShardedAdminIndexHandlerProcessorForStaticPut.cs
Labels: v6.0

#18355 RavenDB-22199 avoid the stress test ParallelClusterTransactions on 32 bits
  test/StressTests/Cluster/ClusterStressTests.cs
Labels: v5.4

#18340 RavenDB-22229 - Add authorization check for the legacy replication for indexes
  src/Raven.Server/Documents/Handlers/Admin/AdminIndexHandler.cs
Labels: v5.4

#18358 RavenDB-22233 - change the test batch count
  test/SlowTests/Issues/RavenDB-15754.cs
Labels: v6.0

#18359 RavenDB-22192: Updated tests when CurrentCulture is set to invariant.
  test/SlowTests/Issues/RavenDB-11795.cs
Labels: v6.0

#18357 RavenDB-22239 Add test for "GetCompareExchangeValuesOperation"
  test/SlowTests/Client/UniqueValues.cs
Labels: v5.4

#18362 5.4 to 6.0 merge
  src/Raven.Client/Util/JavascriptConversionExtensions.cs
  src/Raven.Server/Documents/CollectionRunner.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Handlers/IndexHandler.cs
  src/Raven.Server/Documents/Indexes/IndexMerging/IndexData.cs
  src/Raven.Server/Documents/Indexes/IndexMerging/IndexMergeResults.cs
  src/Raven.Server/Documents/Indexes/IndexMerging/IndexMerger.cs
  src/Raven.Server/Documents/Queries/CollectionQueryEnumerable.cs
  src/Raven.Server/Documents/Queries/Dynamic/CollectionQueryRunner.cs
  src/Raven.Studio/typescript/components/pages/database/indexes/cleanup/IndexCleanup.spec.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/cleanup/IndexCleanup.stories.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/cleanup/IndexCleanup.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/cleanup/carouselItems/MergeSuggestionsErrorsCarouselCard.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/cleanup/useIndexCleanup.tsx
  src/Raven.Studio/typescript/test/stubs/IndexesStubs.ts
  test/RachisTests/DatabaseCluster/ReplicationTests.cs
  test/SlowTests/Issues/RavenDB-10493.cs
  test/SlowTests/Issues/RavenDB-22178.cs
  test/SlowTests/Issues/RavenDB_22110.cs
  test/SlowTests/Server/Documents/Indexing/IndexMerging.cs
  test/StressTests/Cluster/ClusterStressTests.cs
Labels: v6.0

#18356 RavenDB-22151 Updating dotnet-dump related classes
  tools/Raven.Debug/CommandLineApp.cs
  tools/Raven.Debug/Dump/Dumper.Windows.cs
  tools/Raven.Debug/Dump/Dumper.cs
Labels: v5.4

#18369 5.4 to 6.0 merge
  src/Raven.Server/Raven.Server.csproj
  test/SlowTests/Client/UniqueValues.cs
  tools/Raven.Debug/CommandLineApp.cs
  tools/Raven.Debug/Dump/Dumper.Windows.cs
  tools/Raven.Debug/Dump/Dumper.cs
Labels: v6.0

#18366 RavenDB-20103: ARM support for the different variants of VectorizedAnd
  src/Corax/Querying/IndexSearcher.cs
  src/Corax/Querying/Matches/Meta/MergeHelper.cs
  src/Corax/Querying/Matches/TermMatch.cs
Labels: v6.0

#18371 RavenDB-22151 Added support for new types of memory dumps in /admin/debug/dump endpoint
  src/Raven.Server/Web/System/AdminDumpHandler.cs
  tools/Raven.Debug/CommandLineApp.cs
Labels: v5.4

#18333 RavenDB-22226 - Fix updating value in dynamic index
  src/Voron/Data/Tables/Table.cs
  test/FastTests/Voron/Tables/RavenDB_22226.cs
Labels: Sharding, v6.0

#18328 RavenDB-21996 Include documentation
  src/Raven.Client/DocumentationUrls.cs
  src/Raven.Client/Documents/Conventions/DocumentConventions.cs
  src/Raven.Client/Documents/LinqExtensions.cs
  src/Raven.Client/Documents/Session/AbstractDocumentQuery.Includes.cs
  src/Raven.Client/Documents/Session/AsyncDocumentSession.Includes.cs
  src/Raven.Client/Documents/Session/AsyncDocumentSession.Lazy.cs
  src/Raven.Client/Documents/Session/DocumentSession.Includes.cs
  src/Raven.Client/Documents/Session/DocumentSession.Lazy.cs
  src/Raven.Client/Documents/Session/IAbstractDocumentQuery.cs
  src/Raven.Client/Documents/Session/IAsyncDocumentSession.Load.cs
  src/Raven.Client/Documents/Session/IDocumentQueryBase.cs
  src/Raven.Client/Documents/Session/IDocumentSession.Include.cs
  src/Raven.Client/Documents/Session/Loaders/AsyncMultiLoaderWithInclude.cs
  src/Raven.Client/Documents/Session/Loaders/IAsyncLoaderWithInclude.cs
  src/Raven.Client/Documents/Session/Loaders/ILazyLoaderWithInclude.cs
  src/Raven.Client/Documents/Session/Loaders/ILoaderWithInclude.cs
  src/Raven.Client/Documents/Session/Loaders/IncludeBuilder.cs
  src/Raven.Client/Documents/Session/Loaders/LazyMultiLoaderWithInclude.cs
  src/Raven.Client/Documents/Session/Operations/Lazy/ILazySessionOperations.cs
Labels: v6.0

#18379 5.4 to 6.0 merge
  src/Raven.Server/Web/System/AdminDumpHandler.cs
  tools/Raven.Debug/CommandLineApp.cs
Labels: v6.0

#18373 RavenDB-13830 / RavenDB-10621 / RavenDB-21987 Unskipping the test which no longer fails (even on 32 bits)
  test/SlowTests/Issues/RavenDB_10621.cs
Labels: v5.4

#18380 5.4 to 6.0 merge
  src/Raven.Server/NotificationCenter/Handlers/DatabaseNotificationCenterHandler.cs
  test/SlowTests/Issues/RavenDB-17068.cs
  test/SlowTests/Issues/RavenDB_10621.cs
  test/SlowTests/Issues/RavenDB_22176.cs
Labels: v6.0

#18378 RavenDB-22242 Support `@AllResults` aggregations in Corax.
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxIndexFacetedReadOperation.cs
  test/SlowTests/Issues/RavenDB_14952.cs
  test/SlowTests/Tests/TestsInheritanceTests.cs
Labels: v6.0

#18382 RavenDB-22220 - fix Exception during tests discovery
  test/StressTests/Server/Documents/PeriodicBackup/RetentionStress.cs
  test/Tests.Infrastructure/AmazonS3RetryFactAttribute.cs
  test/Tests.Infrastructure/AmazonS3RetryTheoryAttribute.cs
  test/Tests.Infrastructure/AzureRetryFactAttribute.cs
  test/Tests.Infrastructure/AzureRetryTheoryAttribute.cs
  test/Tests.Infrastructure/CloudAttributeHelper.cs
  test/Tests.Infrastructure/MultiTheoryAttribute .cs
  test/Tests.Infrastructure/NightlyBuildTheoryAttribute.cs
  test/Tests.Infrastructure/RavenTheoryAttribute.cs
Labels: v6.0

#18381 RavenDB-7070 Updating Jint to 3.0.2
  src/Raven.Server/Raven.Server.csproj
Labels: v6.0

#18383 RavenDB-20446 Fixing occassionally failing. Let's wait explicitly for index to be non stale before issuing a query so we will be sure we won't wait for the replacement to complete the swap.
  test/SlowTests/Issues/RavenDB_12269.cs
Labels: v6.0

#18388 RDBCL-3407 : fix wrong folder name in server-wide sharded backups with script-generated settings
  src/Raven.Server/ServerWide/Commands/PutServerWideBackupConfigurationCommand.cs
  test/SlowTests/Sharding/Backup/ShardedBackupTests .cs
  test/SlowTests/Sharding/Backup/ShardedRestoreBackupTests.cs
Labels: v6.0

#18391 RavenDB-20446 Fixing occassionally failing. Let's wait explicitly for index to be non stale before issuing a query so we will be sure we won't wait for the replacement to complete the swap.
  test/SlowTests/Issues/RavenDB_12269.cs
Labels: v5.4

#18392 RavenDB-22280 Fix GetNotification endpoint tests in debug mode
  test/SlowTests/Issues/RavenDB_22176.cs
Labels: v5.4

#18384 RavenDB-22253 Hooking up NewTransactionCreated and AfterCommitWhenNewTransactionsPrevented events to transactions created on async commit
  src/Voron/Impl/LowLevelTransaction.cs
  src/Voron/StorageEnvironment.cs
  test/SlowTests/Issues/RavenDB_22253.cs
Labels: v5.4

#18394 5.4 to 6.0 merge
  src/Voron/Impl/LowLevelTransaction.cs
  src/Voron/StorageEnvironment.cs
  test/SlowTests/Issues/RavenDB_22176.cs
  test/SlowTests/Issues/RavenDB_22253.cs
Labels: v6.0

#18387 RavenDB-21983 - Update our Client API XML documentation [IAbstractTim…
  src/Raven.Client/DocumentationUrls.cs
  src/Raven.Client/Documents/Session/Loaders/IncludeBuilder.cs
Labels: v6.0

#18393 RavenDB-21877 Ace editor's full screen command doesn't work in read-only mode
  src/Raven.Studio/typescript/components/common/AceEditor.tsx
Labels: v6.0, Studio

#18398 RavenDB-17593 Clarify that reset index is done on the current node
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexes.ts
Labels: v5.4, Studio

#18397 RavenDB-17593 Clarify text for Reset index
  src/Raven.Studio/typescript/components/pages/database/indexes/list/ConfirmResetIndex.tsx
Labels: v6.0, Studio

#18401 RavenDB-22101 Better gui for tasks pinned node
  src/Raven.Studio/typescript/viewmodels/database/tasks/editElasticSearchEtlTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editExternalReplicationTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editKafkaEtlTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editOlapEtlTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editPeriodicBackupTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editRabbitMqEtlTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editRavenEtlTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editReplicationHubTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editReplicationSinkTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editSqlEtlTask.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editSubscriptionTask.ts
  src/Raven.Studio/typescript/viewmodels/manage/editServerWideBackup.ts
  src/Raven.Studio/typescript/viewmodels/manage/editServerWideExternalReplication.ts
  src/Raven.Studio/wwwroot/App/views/database/tasks/editElasticSearchEtlTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editExternalReplicationTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editKafkaEtlTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editOlapEtlTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editPeriodicBackupTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editRabbitMqEtlTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editRavenEtlTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editReplicationHubTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editReplicationSinkTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editSqlEtlTask.html
  src/Raven.Studio/wwwroot/App/views/database/tasks/editSubscriptionTask.html
  src/Raven.Studio/wwwroot/App/views/manage/editServerWideBackup.html
  src/Raven.Studio/wwwroot/App/views/manage/editServerWideExternalReplication.html
  src/Raven.Studio/wwwroot/App/views/partial/pinResponsibleNodeButtonsScript.html
  src/Raven.Studio/wwwroot/App/views/partial/taskResponsibleNodeSection.html
  src/Raven.Studio/wwwroot/App/views/partial/taskResponsibleNodeSection_ForBackup.html
Labels: v5.4, Studio

#18418 5.4 to 6.0 merge (after updating 5.4 to .NET 8)
  src/Sparrow.Server/LowMemory/CheckPageFileOnHdd.cs
Labels: v6.0

#18415 RavenDB-21926 Modify the state and the flags of a tree only if they aren't aleady set. Otherwise we force the write to journal of the pages where tree states are kept because we recognize that they were modified (even if the state did not change).
  src/Raven.Server/Documents/Indexes/MapReduce/MapReduceIndexBase.cs
  src/Voron/Data/BTrees/Tree.MultiTree.cs
  src/Voron/Data/BTrees/Tree.Stream.cs
  src/Voron/Data/BTrees/Tree.cs
  src/Voron/Data/CompactTrees/CompactTree.cs
  src/Voron/Data/Lookups/Lookup.cs
  test/SlowTests/Voron/RavenDB_21926.cs
Labels: v6.0

#18423 RavenDB-7070 Using different assertions so we'll see the actual exception
  test/SlowTests/Issues/RavenDB-12564.cs
Labels: v5.4

#18419 RavenDB-22190 - use the verifier from BouncyCastle
  src/Raven.Server/Commercial/LicenseValidator.cs
Labels: v5.4

#18426 RavenDB-22187 update LastCompletedClusterTransactionIndex before setting ClusterTransactionWaiter
  src/Raven.Server/Documents/DocumentDatabase.cs
Labels: v5.4

#18427 RavenDB-22289 Fixing test issue which assumed the order of paths returned by Directory.GetDirectories()
  test/SlowTests/Sharding/Backup/ShardedBackupTests .cs
Labels: v6.0

#18435 RavenDB-22309 notifying the database should propagate to the rachis notifier as well
  src/Raven.Server/Documents/DatabaseRaftIndexNotifications.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.cs
  src/Raven.Server/ServerWide/RachisLogIndexNotifications.cs
  test/SlowTests/Issues/RavenDB-22217.cs
Labels: v5.4

#18431 RavenDB-22241 Index cleanup - style improvement and refactoring
  src/Raven.Studio/typescript/components/pages/database/indexes/cleanup/IndexCleanup.spec.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/cleanup/IndexCleanup.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/cleanup/IndexCleanupAboutView.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/cleanup/carouselCards/MergeIndexesCard.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/cleanup/carouselCards/MergeSuggestionsErrorsCarouselCard.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/cleanup/carouselCards/RemoveSubindexesCard.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/cleanup/carouselCards/RemoveUnusedIndexesCard.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/cleanup/carouselCards/UnmergableIndexesCard.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/cleanup/navItems/MergeIndexesNavItem.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/cleanup/navItems/MergeSuggestionsErrorsNavItem.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/cleanup/navItems/RemoveSubindexesNavItem.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/cleanup/navItems/RemoveUnusedIndexesNavItem.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/cleanup/navItems/UnmergableIndexesNavItem.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/cleanup/useIndexCleanup.tsx
  src/Raven.Studio/wwwroot/Content/img/pages/indexCleanup/merge-suggestion-errors.svg
Labels: v6.0, Studio

#18432 RavenDB-22311 Alphanumerical sorter - index out of range exception fix
  src/Raven.Server/Documents/Queries/Sorting/AlphaNumeric/AlphaNumericFieldComparator.cs
  test/SlowTests/Issues/RavenDB-22311.cs
Labels: v6.0

#18374 RavenDB-22249 Change the link and names for the Cloud instances in the Licensing view
  src/Raven.Studio/typescript/components/common/FeatureAvailabilitySummary.spec.tsx
  src/Raven.Studio/typescript/components/common/FeatureAvailabilitySummary.stories.tsx
  src/Raven.Studio/typescript/components/common/FeatureAvailabilitySummary.tsx
Labels: v6.0, Studio

#18438 RavenDB-22309 separate cluster and database notifiers
  src/Raven.Server/Documents/DatabaseRaftIndexNotifications.cs
  src/Raven.Server/ServerWide/AbstractRaftIndexNotifications.cs
Labels: v5.4

#18442 RavenDB-22310 Edit replication sink broken in v5.4
  src/Raven.Studio/typescript/models/database/tasks/ongoingTaskReplicationSinkEditModel.ts
  src/Raven.Studio/typescript/models/database/tasks/ongoingTaskReplicationSinkListModel.ts
  src/Raven.Studio/wwwroot/App/views/database/tasks/ongoingTasks.html
Labels: v5.4, Studio

#18441 RavenDB-20225 Use moving avg to calculate the speed of the import
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/smugglerDatabaseDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/timeAwareEWMA.spec.ts
  src/Raven.Studio/typescript/viewmodels/common/timeAwareEWMA.ts
  src/Raven.Studio/wwwroot/App/views/common/notificationCenter/detailViewer/operations/smugglerDatabaseDetails.html
Labels: v6.0, Studio

#18457 RavenDB-22325 Delete time series: fix explanation of 'to' param
  src/Raven.Client/Documents/Session/ISessionDocumentTimeSeriesBase.cs
Labels: v6.0

#18458 RavenDB-22309 WaitForIndexNotification with CancellationToken should not use the notifiedListeners.WaitAsync task
  src/Raven.Server/ServerWide/AbstractRaftIndexNotifications.cs
Labels: v5.4

#18447 RavenDB-22318 Missing SliceComparer
  src/Raven.Server/Documents/Expiration/ExpiredDocumentsCleaner.cs
  src/Raven.Server/ServerWide/CompareExchangeExpirationStorage.cs
Labels: v5.4
