Repository ravendb/ravendb, pull requests merged in 2025-07, with the labels that each got.

#20879 7.0 to 7.1 merge
  src/Raven.Studio/typescript/components/services/DatabasesService.ts
Labels: Studio, v7.1

#20888 RavenDB-24478: Obsolete test fact attribute warnings
  test/SlowTests/Server/Documents/ETL/SQL/RavenDB_19518.cs
  test/SlowTests/Server/Documents/Migration/MongoDBMigrationTest.cs
  test/SlowTests/Server/Documents/Migration/NpgSQLSchemaTest.cs
  test/SlowTests/Server/Documents/Migration/OracleSQLSchemaTest.cs
  test/Tests.Infrastructure/LicenseRequiredTheoryAttribute.cs
  test/Tests.Infrastructure/RavenFactAttribute.cs
  test/Tests.Infrastructure/RavenMultiplatformFactAttribute.cs
  test/Tests.Infrastructure/RavenRetryFactAttribute.cs
  test/Tests.Infrastructure/RavenRetryTheoryAttribute.cs
  test/Tests.Infrastructure/RavenServiceRequirement.cs
  test/Tests.Infrastructure/RavenTheoryAttribute.cs
Labels: v6.2

#20893 RavenDB-24544 Copy ID is hidden
  src/Raven.Studio/wwwroot/App/views/database/documents/editDocument.html
Labels: v5.4, Studio

#20896 RavenDB-24556 DatabaseDistribution.tsx NRE
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/DatabaseDistribution.tsx
  src/Raven.Studio/typescript/components/utils/DatabaseUtils.ts
Labels: Studio, v6.2

#20897 5.4 to 6.2 merge
  src/Raven.Studio/wwwroot/App/views/database/documents/editDocument.html
Labels: Studio, v6.2

#20898 6.2 to 7.0 merge
  src/Raven.Server/Documents/Handlers/Debugging/PagingStatsHandler.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.5/TotalPagesRead.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.5/TotalPagesWritten.cs
  src/Raven.Server/Monitoring/Snmp/SnmpMibWriter.cs
  src/Raven.Server/Monitoring/Snmp/SnmpOids.cs
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
  src/Raven.Studio/typescript/components/common/clientConfiguration/ClientConfigurationUtils.ts
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/DatabaseDistribution.tsx
  src/Raven.Studio/typescript/components/utils/DatabaseUtils.ts
  src/Raven.Studio/wwwroot/App/views/database/documents/editDocument.html
  src/Raven.Studio/wwwroot/Content/css/basic-layout.less
  src/Raven.Studio/wwwroot/Content/css/pages/license.less
  src/Raven.Studio/wwwroot/Content/scss/_custom-properties.scss
  src/Voron/Impl/Journal/JournalFile.cs
  src/Voron/Impl/LowLevelTransaction.cs
  src/Voron/Impl/Paging/AbstractPager.cs
  src/Voron/Impl/Paging/PagingStatistics.cs
  test/SlowTests/Server/Documents/ETL/SQL/RavenDB_19518.cs
  test/SlowTests/Server/Documents/Migration/MongoDBMigrationTest.cs
  test/SlowTests/Server/Documents/Migration/NpgSQLSchemaTest.cs
  test/SlowTests/Server/Documents/Migration/OracleSQLSchemaTest.cs
  test/Tests.Infrastructure/LicenseRequiredTheoryAttribute.cs
  test/Tests.Infrastructure/RavenFactAttribute.cs
  test/Tests.Infrastructure/RavenMultiplatformFactAttribute.cs
  test/Tests.Infrastructure/RavenRetryFactAttribute.cs
  test/Tests.Infrastructure/RavenRetryTheoryAttribute.cs
  test/Tests.Infrastructure/RavenServiceRequirement.cs
  test/Tests.Infrastructure/RavenTheoryAttribute.cs
Labels: v7.0

#20899 7.0 to 7.1 merge
  src/Raven.Server/Documents/Handlers/Debugging/PagingStatsHandler.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.5/TotalPagesRead.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.5/TotalPagesWritten.cs
  src/Raven.Server/Monitoring/Snmp/SnmpMibWriter.cs
  src/Raven.Server/Monitoring/Snmp/SnmpOids.cs
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
  src/Raven.Studio/typescript/components/common/clientConfiguration/ClientConfigurationUtils.ts
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/DatabaseDistribution.tsx
  src/Raven.Studio/typescript/components/utils/DatabaseUtils.ts
  src/Raven.Studio/wwwroot/App/views/database/documents/editDocument.html
  src/Raven.Studio/wwwroot/Content/css/basic-layout.less
  src/Raven.Studio/wwwroot/Content/css/pages/license.less
  src/Raven.Studio/wwwroot/Content/scss/_custom-properties.scss
  src/Voron/Impl/Journal/JournalFile.cs
  src/Voron/Impl/LowLevelTransaction.cs
  src/Voron/Impl/Paging/AbstractPager.cs
  src/Voron/Impl/Paging/PagingStatistics.cs
  test/SlowTests/Server/Documents/ETL/SQL/RavenDB_19518.cs
  test/SlowTests/Server/Documents/Migration/MongoDBMigrationTest.cs
  test/SlowTests/Server/Documents/Migration/NpgSQLSchemaTest.cs
  test/SlowTests/Server/Documents/Migration/OracleSQLSchemaTest.cs
  test/Tests.Infrastructure/LicenseRequiredTheoryAttribute.cs
  test/Tests.Infrastructure/RavenFactAttribute.cs
  test/Tests.Infrastructure/RavenMultiplatformFactAttribute.cs
  test/Tests.Infrastructure/RavenRetryFactAttribute.cs
  test/Tests.Infrastructure/RavenRetryTheoryAttribute.cs
  test/Tests.Infrastructure/RavenServiceRequirement.cs
  test/Tests.Infrastructure/RavenTheoryAttribute.cs
Labels: v7.1

#20901 7.1 to 8.0 merge
  src/Raven.Server/Documents/AI/AbstractChatCompletionClient.cs
  src/Raven.Server/Documents/AI/AiExceptions.cs
  src/Raven.Server/Documents/Handlers/Debugging/PagingStatsHandler.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.5/TotalPagesRead.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.5/TotalPagesWritten.cs
  src/Raven.Server/Monitoring/Snmp/SnmpMibWriter.cs
  src/Raven.Server/Monitoring/Snmp/SnmpOids.cs
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
  src/Raven.Studio/typescript/components/common/clientConfiguration/ClientConfigurationUtils.ts
  src/Raven.Studio/typescript/components/pages/database/tasks/ongoingTasks/partials/OngoingTaskAddModal.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/DatabaseDistribution.tsx
  src/Raven.Studio/typescript/components/utils/DatabaseUtils.ts
  src/Raven.Studio/wwwroot/App/views/database/documents/editDocument.html
  src/Raven.Studio/wwwroot/Content/css/basic-layout.less
  src/Raven.Studio/wwwroot/Content/css/pages/license.less
  src/Raven.Studio/wwwroot/Content/scss/_custom-properties.scss
  src/Voron/Impl/LowLevelTransaction.cs
  src/Voron/Impl/Paging/PagingStatistics.cs
  test/SlowTests/Server/Documents/AI/GenAi/GenAiBasics.cs
  test/SlowTests/Server/Documents/ETL/SQL/RavenDB_19518.cs
  test/SlowTests/Server/Documents/Migration/MongoDBMigrationTest.cs
  test/SlowTests/Server/Documents/Migration/NpgSQLSchemaTest.cs
  test/SlowTests/Server/Documents/Migration/OracleSQLSchemaTest.cs
  test/Tests.Infrastructure/LicenseRequiredTheoryAttribute.cs
  test/Tests.Infrastructure/RavenFactAttribute.cs
  test/Tests.Infrastructure/RavenMultiplatformFactAttribute.cs
  test/Tests.Infrastructure/RavenRetryFactAttribute.cs
  test/Tests.Infrastructure/RavenRetryTheoryAttribute.cs
  test/Tests.Infrastructure/RavenServiceRequirement.cs
  test/Tests.Infrastructure/RavenTheoryAttribute.cs
Labels: v8.0

#20913 6.2 to 7.0 merge
  test/SlowTests/Tests/TestsInheritanceTests.cs
Labels: v7.0

#20870 RavenDB-24207 - Test for expected errors on failure
  test/SlowTests/Server/Documents/AI/AiAgent/AiAgentErrors.cs
Labels: ai-agent

#20933 RavenDB-24585 AI Agent: allow to resume the test
  src/Raven.Client/Documents/AI/Conversation.cs
  src/Raven.Client/Documents/Operations/AI/Agents/RunConversationOperation.cs
  src/Raven.Client/Json/Serialization/JsonDeserializationClient.cs
  src/Raven.Server/Documents/Handlers/AI/Agents/AbstractAiAgentProcessor.cs
  src/Raven.Server/Documents/Handlers/AI/Agents/AiAgentProcessorForTestConversation.cs
  src/Raven.Server/Documents/Handlers/AI/Agents/ConversationDocument.cs
  test/SlowTests/Server/Documents/AI/AiAgent/AiAgentBasics.cs
Labels: ai-agent

#20946 RavenDB-24120 Fix LimitedStreamTests
  test/FastTests/Utils/LimitedStreamTests.cs
Labels: v5.4

#20947 RavenDB-16927 adjusting the test
  test/RachisTests/AddNodeToClusterTests.cs
Labels: v5.4

#20949 RavenDB-24264 added more debugging information
  src/Raven.Server/ServerWide/ServerStore.cs
  test/FastTests/Server/Basic/IdleOperations.cs
Labels: v5.4

#20950 RavenDB-24557 added small tolerance
  test/SlowTests/Smuggler/SmugglerApiTests.cs
Labels: v6.2

#20953 RavenDB-24613 - Allowing a script to emit multiple embeddings.generat…
  src/Raven.Server/Documents/ETL/Providers/AI/Embeddings/EmbeddingsGenerationScriptTransformer.cs
  test/SlowTests/Issues/RavenDB_24613.cs
Labels: v7.1

#20954 RavenDB-24212 add concurrency control to ai conversations
  src/Raven.Client/Documents/AI/AiOperations.cs
  src/Raven.Client/Documents/AI/Conversation.cs
  src/Raven.Client/Documents/Operations/AI/Agents/RunConversationOperation.cs
  src/Raven.Server/Documents/Handlers/AI/Agents/AbstractAiAgentProcessor.cs
  src/Raven.Server/Documents/Handlers/AI/Agents/ConversationDocument.cs
  test/SlowTests/Server/Documents/AI/AiAgent/AiAgentClientApiBasics.cs
Labels: ai-agent

#20952 RavenDB-24625 Fix EnterpriseAi showing free license message
  src/Raven.Studio/typescript/components/pages/resources/about/partials/LicenseDetails.tsx
Labels: Studio, v7.1

#20958 RavenDB-23060
  src/Raven.Server/ServerWide/Maintenance/ClusterMaintenanceSupervisor.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterNodeStatusReport.cs
  src/Raven.Server/ServerWide/ServerStore.cs
Labels: v5.4

#20951 RavenDB-23060
  src/Raven.Server/ServerWide/Maintenance/ClusterMaintenanceSupervisor.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterNodeStatusReport.cs
  src/Raven.Server/ServerWide/ServerStore.cs
Labels: v6.2

#20971 RavenDB-24211 AI Agent: Fix build and minor bugs
  src/Raven.Studio/typescript/components/common/sampleObjectAndSchemaFields/SampleObjectAndSchemaFields.tsx
  src/Raven.Studio/typescript/components/pages/database/aiHub/aiAgents/edit/EditAiAgentMain.tsx
  src/Raven.Studio/typescript/components/pages/database/aiHub/aiAgents/edit/utils/editAiAgentUtils.ts
  src/Raven.Studio/typescript/components/pages/database/aiHub/aiAgents/edit/utils/editAiAgentValidation.ts
  src/Raven.Studio/typescript/components/pages/database/aiHub/aiAgents/partials/AiAgentMessages.tsx
Labels: Studio, ai-agent

#20970 7.0 to 7.1 merge
  src/Raven.Server/Documents/CollectionRunner.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterMaintenanceSupervisor.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterNodeStatusReport.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Studio/typescript/components/common/FeatureAvailabilitySummary.tsx
  src/Raven.Studio/typescript/components/pages/resources/about/AboutPage.spec.tsx
  src/Raven.Studio/typescript/components/pages/resources/about/partials/LicenseDetails.tsx
  src/Voron/Data/BTrees/Tree.Stream.cs
  test/FastTests/Server/Basic/IdleOperations.cs
  test/FastTests/Utils/LimitedStreamTests.cs
  test/RachisTests/AddNodeToClusterTests.cs
  test/SlowTests/Issues/RavenDB-24375.cs
  test/SlowTests/Issues/RavenDB_20202.cs
  test/SlowTests/Smuggler/SmugglerApiTests.cs
Labels: v7.1

#20965 RavenDB-24553 Exception when enabling CompressAllCollections
  src/Raven.Client/Documents/Operations/Backups/BackupSettings.cs
  test/SlowTests/Issues/RavenDB_24553.cs
Labels: v6.2

#20948 RavenDB-24594 fixed race condition in the DeferrableTimeout
  src/Raven.Server/ServerWide/DeferrableTimeout.cs
Labels: v5.4

#20978 RavenDB-24487 : Handle javascript index for retired attachments (Phase 1)
  src/Raven.Server/Documents/Indexes/Static/JavaScript/AttachmentNameObjectInstance.cs
  src/Raven.Server/Documents/Indexes/Static/JavaScript/AttachmentObjectInstance.cs
  test/SlowTests/Issues/RavenDB_24487.cs
Labels: remote-attachments

#20984 RavenDB-24635 - Fix AiAgentClientApiBasicTest test
  src/Raven.Server/Documents/AI/ChatCompletionClient.cs
  test/SlowTests/Server/Documents/AI/AiAgent/RavenDB-24635.cs
Labels: ai-agent

#20977 RavenDB-24157 : add tests that throw on sharded database for retire attachment endpoints
  src/Raven.Server/Documents/Sharding/Handlers/ShardedRetiredAttachmnentHandler.cs
  test/SlowTests/Issues/RavenDB_24157.cs
Labels: remote-attachments

#20987 RavenDB-24677 tests that create server-wide backups cannot use global server
  test/SlowTests/Issues/RavenDB_24553.cs
Labels: v6.2

#20981 RavenDB - 24505 : Need to block unsupported OpenAI models
  src/Raven.Client/Documents/Operations/AI/EmbeddingsGenerationConfiguration.cs
  src/Raven.Client/Documents/Operations/AI/GenAiConfiguration.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  test/SlowTests/Issues/RavenDB-24505.cs
  test/SlowTests/Server/Documents/AI/GenAi/GenAiTestScript.cs
Labels: v7.1

#20985 RavenDB-24191 Cannot register includes: Unclear error message
  src/Raven.Client/Documents/Session/InMemoryDocumentSessionOperations.cs
  test/SlowTests/Issues/RavenDB_21339.cs
Labels: v6.2

#20996 Merge v7.1 into feature/ai-agent
  src/Raven.Client/Documents/Operations/AI/EmbeddingsGenerationConfiguration.cs
  src/Raven.Client/Documents/Operations/AI/GenAiConfiguration.cs
  src/Raven.Client/Documents/Operations/Backups/BackupSettings.cs
  src/Raven.Client/Documents/Session/InMemoryDocumentSessionOperations.cs
  src/Raven.Server/Documents/CollectionRunner.cs
  src/Raven.Server/Documents/ETL/Providers/AI/Embeddings/EmbeddingsGenerationScriptTransformer.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.5/ProcessOpenFileDescriptors.cs
  src/Raven.Server/Monitoring/Snmp/SnmpOids.cs
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
  src/Raven.Server/ServerWide/DeferrableTimeout.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterMaintenanceSupervisor.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterNodeStatusReport.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Studio/typescript/components/common/FeatureAvailabilitySummary.tsx
  src/Raven.Studio/typescript/components/pages/resources/about/AboutPage.spec.tsx
  src/Raven.Studio/typescript/components/pages/resources/about/partials/LicenseDetails.tsx
  src/Voron/Data/BTrees/Tree.Stream.cs
  test/FastTests/Server/Basic/IdleOperations.cs
  test/FastTests/Utils/LimitedStreamTests.cs
  test/RachisTests/AddNodeToClusterTests.cs
  test/SlowTests/Issues/RavenDB-24375.cs
  test/SlowTests/Issues/RavenDB-24505.cs
  test/SlowTests/Issues/RavenDB_15430.cs
  test/SlowTests/Issues/RavenDB_20202.cs
  test/SlowTests/Issues/RavenDB_21339.cs
  test/SlowTests/Issues/RavenDB_24553.cs
  test/SlowTests/Issues/RavenDB_24613.cs
  test/SlowTests/Server/Documents/AI/GenAi/GenAiTestScript.cs
  test/SlowTests/Smuggler/SmugglerApiTests.cs
Labels: ai-agent

#20956 RavenDB-24250 Validate license configuration before restore
  src/Raven.Server/Documents/PeriodicBackup/Restore/AbstractRestoreBackupTask.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.License.cs
Labels: v6.2

#21007 RavenDB-24211 AI Agent: Fix ai agent delete
  src/Raven.Server/Documents/Handlers/AI/Agents/AiAgentProcessorForDeleteAiAgent.cs
  src/Raven.Studio/typescript/commands/database/aiAgents/deleteAiAgentCommand.ts
  src/Raven.Studio/typescript/components/pages/database/aiHub/aiAgents/AiAgents.tsx
  src/Raven.Studio/typescript/components/pages/database/aiHub/aiAgents/partials/AiAgentCard.tsx
Labels: ai-agent

#20986 RavenDB-24525 Add withNestedSubmit to AiConnectionString
  src/Raven.Studio/typescript/components/pages/database/settings/connectionStrings/editForms/AiConnectionString.tsx
  src/Raven.Studio/typescript/components/utils/common.ts
Labels: Studio, v7.0

#21009 RavenDB-24616 Use unmanaged allocation in Tree.Stream instead of LOH managed allocation
  src/Voron/Data/BTrees/Tree.Stream.cs
Labels: v5.4

#21013 RavenDB-24699 AI Agent: license restrictions
  src/Raven.Studio/typescript/components/pages/database/aiHub/aiAgents/AiAgents.tsx
  src/Raven.Studio/typescript/components/pages/database/aiHub/aiAgents/AiAgentsInfoHub.tsx
Labels: Studio, ai-agent

#21014 RavenDB-24689 AI Agent: Create new connection string for ai agent enhancements
  src/Raven.Studio/typescript/components/common/ClickableCard.tsx
  src/Raven.Studio/typescript/components/pages/database/aiHub/aiAgents/edit/EditAiAgent.tsx
  src/Raven.Studio/typescript/components/pages/database/aiHub/aiAgents/edit/partials/EditAiAgentBasicSection.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/connectionStrings/editForms/AiConnectionString.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/connectionStrings/editForms/aiFields/ModelTypeField.tsx
Labels: Studio, ai-agent

#21024 RavenDB-24690 Use npm ci instead of npm install in RavenDB repo
  .github/workflows/StudioTests.yml
  .github/workflows/compile.yml
  .github/workflows/studioConventions.yml
  debug.Dockerfile
  scripts/buildProjects.ps1
  src/Raven.Studio/Raven.Studio.csproj
  src/Raven.Studio/aceBuild/README.txt
Labels: v5.4

#21025 RavenDB-24700 AI Agent: disable identifier when editing ai agent
  src/Raven.Studio/typescript/components/pages/database/aiHub/aiAgents/edit/EditAiAgent.tsx
  src/Raven.Studio/typescript/components/pages/database/aiHub/aiAgents/edit/partials/EditAiAgentBasicSection.tsx
Labels: Studio, ai-agent

#21016 RavenDB-24633 - Studio UI – Embeddings Generation AI Task lacks “Test connection" button
  src/Raven.Studio/typescript/components/pages/database/settings/connectionStrings/editForms/aiConnectionStringUtils.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editEmbeddingsGenerationTask.ts
  src/Raven.Studio/typings/_studio/dto.d.ts
  src/Raven.Studio/wwwroot/App/views/database/tasks/editEmbeddingsGenerationTask.html
Labels: Studio, v7.0

#21005 RavenDB-23681 fix test ShouldRescheduleBackupTimerIfDocumentDatabaseF…
  src/Raven.Server/Documents/DatabasesLandlord.cs
  test/StressTests/Issues/RavenDB_18420.cs
Labels: v5.4

#21026 release/v6.2 to v6.2 merge
  src/CommonAssemblyInfo.cs
  src/Raven.Client/Properties/VersionInfo.cs
  src/Raven.Server/Documents/Handlers/Debugging/PagingStatsHandler.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.5/TotalPagesRead.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.5/TotalPagesWritten.cs
  src/Raven.Server/Monitoring/Snmp/SnmpMibWriter.cs
  src/Raven.Server/Monitoring/Snmp/SnmpOids.cs
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
  src/Raven.Studio/typescript/components/pages/database/tasks/ongoingTasks/partials/OngoingTasksReducer.ts
  src/Voron/Impl/Journal/JournalFile.cs
  src/Voron/Impl/LowLevelTransaction.cs
  src/Voron/Impl/Paging/AbstractPager.cs
  src/Voron/Impl/Paging/PagingStatistics.cs
Labels: v6.2

#21027 release/v7.0 to v7.0 merge
  src/CommonAssemblyInfo.cs
  src/Raven.Client/Properties/VersionInfo.cs
  src/Raven.Server/Documents/Handlers/Debugging/PagingStatsHandler.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.5/TotalPagesRead.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.5/TotalPagesWritten.cs
  src/Raven.Server/Monitoring/Snmp/SnmpMibWriter.cs
  src/Raven.Server/Monitoring/Snmp/SnmpOids.cs
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
  src/Raven.Studio/typescript/components/pages/database/tasks/ongoingTasks/partials/OngoingTasksReducer.ts
  src/Voron/Impl/Journal/JournalFile.cs
  src/Voron/Impl/LowLevelTransaction.cs
  src/Voron/Impl/Paging/AbstractPager.cs
  src/Voron/Impl/Paging/PagingStatistics.cs
Labels: v7.0

#21028 release/v7.1 to v7.1 merge
  src/CommonAssemblyInfo.cs
  src/Raven.Client/Properties/VersionInfo.cs
  src/Raven.Server/Documents/Handlers/Debugging/PagingStatsHandler.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.5/TotalPagesRead.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.5/TotalPagesWritten.cs
  src/Raven.Server/Monitoring/Snmp/SnmpMibWriter.cs
  src/Raven.Server/Monitoring/Snmp/SnmpOids.cs
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
  src/Raven.Studio/typescript/components/pages/database/tasks/ongoingTasks/partials/OngoingTasksReducer.ts
  src/Voron/Impl/Journal/JournalFile.cs
  src/Voron/Impl/LowLevelTransaction.cs
  src/Voron/Impl/Paging/AbstractPager.cs
  src/Voron/Impl/Paging/PagingStatistics.cs
Labels: v7.1

#21032 7.0 to 7.1 merge
  .github/workflows/StudioTests.yml
  .github/workflows/compile.yml
  .github/workflows/studioConventions.yml
  debug.Dockerfile
  scripts/buildProjects.ps1
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/AbstractRestoreBackupTask.cs
  src/Raven.Server/Monitoring/Snmp/SnmpOids.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.License.cs
  src/Raven.Studio/Raven.Studio.csproj
  src/Raven.Studio/aceBuild/README.txt
  src/Raven.Studio/typescript/components/models/indexes.ts
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexFilter.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexesPage.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/list/useIndexesPage.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/connectionStrings/editForms/AiConnectionString.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/connectionStrings/editForms/aiConnectionStringUtils.ts
  src/Raven.Studio/typescript/components/utils/common.ts
  src/Raven.Studio/typescript/models/database/index/indexDefinition.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editEmbeddingsGenerationTask.ts
  src/Raven.Studio/wwwroot/App/views/database/tasks/editEmbeddingsGenerationTask.html
  src/Voron/Data/BTrees/Tree.Stream.cs
  test/LicenseTests/Helpers/LicenseOptionTestHelper.cs
  test/LicenseTests/LicenseOptionsEmbeddedTests.cs
  test/LicenseTests/LicenseOptionsTestDriverTests.cs
  test/SlowTests/Server/Documents/ETL/SQL/SqlEtlTests.cs
  test/StressTests/Issues/RavenDB_18420.cs
  test/Tests.Infrastructure/RavenFactAttribute.cs
  test/Tests.Infrastructure/RavenServiceRequirement.cs
  test/Tests.Infrastructure/RavenTestHelper.cs
Labels: v7.1

#21034 7.1 to feature/ai-agent merge
  .github/workflows/StudioTests.yml
  .github/workflows/compile.yml
  .github/workflows/studioConventions.yml
  debug.Dockerfile
  scripts/buildProjects.ps1
  src/CommonAssemblyInfo.cs
  src/Raven.Client/Properties/VersionInfo.cs
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/Handlers/Debugging/PagingStatsHandler.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/AbstractRestoreBackupTask.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.5/TotalPagesRead.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.5/TotalPagesWritten.cs
  src/Raven.Server/Monitoring/Snmp/SnmpMibWriter.cs
  src/Raven.Server/Monitoring/Snmp/SnmpOids.cs
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.License.cs
  src/Raven.Studio/Raven.Studio.csproj
  src/Raven.Studio/aceBuild/README.txt
  src/Raven.Studio/package-lock.json
  src/Raven.Studio/typescript/components/models/indexes.ts
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexFilter.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexesPage.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/list/useIndexesPage.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/connectionStrings/ConnectionStrings.spec.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/connectionStrings/editForms/aiConnectionStringUtils.ts
  src/Raven.Studio/typescript/components/pages/database/tasks/ongoingTasks/editTasks/editGenAiTask/EditGenAiTask.stories.tsx
  src/Raven.Studio/typescript/components/pages/database/tasks/ongoingTasks/editTasks/editGenAiTask/partials/fields/EditGenAiTaskBasicFields.tsx
  src/Raven.Studio/typescript/components/pages/database/tasks/ongoingTasks/partials/OngoingTasksReducer.ts
  src/Raven.Studio/typescript/models/database/index/indexDefinition.ts
  src/Raven.Studio/typescript/test/stubs/DatabasesStubs.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editEmbeddingsGenerationTask.ts
  src/Raven.Studio/wwwroot/App/views/database/tasks/editEmbeddingsGenerationTask.html
  src/Raven.Studio/wwwroot/Content/css/root.less
  src/Voron/Data/BTrees/Tree.Stream.cs
  src/Voron/Impl/Journal/JournalFile.cs
  src/Voron/Impl/LowLevelTransaction.cs
  src/Voron/Impl/Paging/AbstractPager.cs
  src/Voron/Impl/Paging/PagingStatistics.cs
  test/LicenseTests/Helpers/LicenseOptionTestHelper.cs
  test/LicenseTests/LicenseOptionsEmbeddedTests.cs
  test/LicenseTests/LicenseOptionsTestDriverTests.cs
  test/SlowTests/Server/Documents/ETL/SQL/SqlEtlTests.cs
  test/StressTests/Issues/RavenDB_18420.cs
  test/Tests.Infrastructure/RavenFactAttribute.cs
  test/Tests.Infrastructure/RavenServiceRequirement.cs
  test/Tests.Infrastructure/RavenTestHelper.cs
Labels: ai-agent

#21033 7.1 to 8.0 merge
  .github/workflows/StudioTests.yml
  .github/workflows/compile.yml
  .github/workflows/studioConventions.yml
  debug.Dockerfile
  scripts/buildProjects.ps1
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/Handlers/Debugging/PagingStatsHandler.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/AbstractRestoreBackupTask.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.5/TotalPagesRead.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.5/TotalPagesWritten.cs
  src/Raven.Server/Monitoring/Snmp/SnmpMibWriter.cs
  src/Raven.Server/Monitoring/Snmp/SnmpOids.cs
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
  src/Raven.Server/ServerWide/ClusterStateMachine.License.cs
  src/Raven.Studio/Raven.Studio.csproj
  src/Raven.Studio/aceBuild/README.txt
  src/Raven.Studio/package-lock.json
  src/Raven.Studio/typescript/components/models/indexes.ts
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexFilter.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexesPage.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/list/useIndexesPage.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/connectionStrings/ConnectionStrings.spec.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/connectionStrings/editForms/AiConnectionString.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/connectionStrings/editForms/aiConnectionStringUtils.ts
  src/Raven.Studio/typescript/components/pages/database/tasks/ongoingTasks/editTasks/editGenAiTask/EditGenAiTask.stories.tsx
  src/Raven.Studio/typescript/components/pages/database/tasks/ongoingTasks/editTasks/editGenAiTask/partials/fields/EditGenAiTaskBasicFields.tsx
  src/Raven.Studio/typescript/components/pages/database/tasks/ongoingTasks/partials/OngoingTasksReducer.ts
  src/Raven.Studio/typescript/components/utils/common.ts
  src/Raven.Studio/typescript/models/database/index/indexDefinition.ts
  src/Raven.Studio/typescript/test/stubs/DatabasesStubs.ts
  src/Raven.Studio/typescript/viewmodels/database/tasks/editEmbeddingsGenerationTask.ts
  src/Raven.Studio/wwwroot/App/views/database/tasks/editEmbeddingsGenerationTask.html
  src/Raven.Studio/wwwroot/Content/css/root.less
  src/Voron/Data/BTrees/Tree.Stream.cs
  src/Voron/Impl/LowLevelTransaction.cs
  src/Voron/Impl/Paging/PagingStatistics.cs
  test/LicenseTests/Helpers/LicenseOptionTestHelper.cs
  test/LicenseTests/LicenseOptionsEmbeddedTests.cs
  test/LicenseTests/LicenseOptionsTestDriverTests.cs
  test/SlowTests/Server/Documents/ETL/SQL/SqlEtlTests.cs
  test/StressTests/Issues/RavenDB_18420.cs
  test/Tests.Infrastructure/RavenFactAttribute.cs
  test/Tests.Infrastructure/RavenServiceRequirement.cs
  test/Tests.Infrastructure/RavenTestHelper.cs
Labels: v8.0

#20908 [RavenDB-24587] Prevent unloading by idle on long running operations
  src/Raven.Server/Documents/ETL/Providers/AI/Embeddings/EmbeddingsGenerationTask.cs
  src/Raven.Server/Documents/ETL/Providers/AI/GenAi/GenAiTask.cs
Labels: v7.1

#21054 RavenDB-24759 tests are missing RavenServiceRequirement and failing with connectivity exception
  test/SlowTests/Issues/RavenDB-22426.cs
  test/SlowTests/Server/Documents/ETL/ConnectionStringTests.cs
Labels: v6.2

#21059 RavenDB-24717 AI Agent: different view for the tool call
  src/Raven.Studio/typescript/components/pages/database/aiHub/aiAgents/partials/AiAgentMessages.scss
  src/Raven.Studio/typescript/components/pages/database/aiHub/aiAgents/partials/AiAgentMessages.tsx
Labels: Studio, ai-agent

#21062 RavenDB-24718 AI Agent: submit to a tool action is free text
  src/Raven.Studio/typescript/components/common/ace/actions/AceEditorFormatAction.tsx
  src/Raven.Studio/typescript/components/pages/database/aiHub/aiAgents/partials/AiAgentMessages.tsx
Labels: Studio, ai-agent

#21072 RavenDB-24704 Fix AceEditor colors on various themes
  src/Raven.Studio/typescript/components/common/AceEditor.scss
Labels: Studio, v6.2

#21073 RavenDB-23699 Test changes
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
Labels: v6.2

#21080 RavenDB-24796 - Improve UI/UX (test query - parameters null instead of 'undefined')
  src/Raven.Studio/typescript/components/pages/database/aiHub/aiAgents/edit/partials/EditAiAgentToolsSection.tsx
  src/Raven.Studio/typescript/models/database/query/queryCriteria.ts
Labels: Studio, ai-agent

#21081 RavenDB-23966: Changes in macOS storage and memory calc
  build.ps1
  libs/librvnpal/librvnpal.linux.arm.32.so
  libs/librvnpal/librvnpal.linux.arm.64.so
  libs/librvnpal/librvnpal.linux.x64.so
  libs/librvnpal/librvnpal.mac.arm64.dylib
  libs/librvnpal/librvnpal.mac.x64.dylib
  libs/librvnpal/librvnpal.win.x64.dll
  libs/librvnpal/librvnpal.win.x86.dll
  libs/librvnpal/librvnpal.win7.x64.dll
  libs/librvnpal/librvnpal.win7.x86.dll
  src/Raven.Pal/README.txt
  src/Raven.Pal/inc/rvn.h
  src/Raven.Pal/pal.ver
  src/Raven.Pal/src/posix/getsysteminformation.c
  src/Raven.Pal/src/rvngetpalver.c
  src/Sparrow.Server/LowMemory/MemoryInformation.cs
  src/Sparrow.Server/Platform/Pal.cs
  src/Sparrow.Server/Platform/Posix/macOS/macSyscall.cs
  src/Sparrow.Server/Platform/Posix/macOS/vm_statistics64.cs
Labels: v6.2

#21086 5.4 to 6.2 merge
  test/SlowTests/Issues/RavenDB-19922.cs
Labels: v6.2
