Repository ravendb/ravendb, pull requests merged in 2025-02, with the labels that each got.

#20085 RavenDB-22220 - fix Exception during tests discovery
  test/StressTests/Server/Documents/PeriodicBackup/RetentionStress.cs
  test/Tests.Infrastructure/AmazonS3RetryFactAttribute.cs
  test/Tests.Infrastructure/AmazonS3RetryTheoryAttribute.cs
  test/Tests.Infrastructure/AzureRetryFactAttribute.cs
  test/Tests.Infrastructure/AzureRetryTheoryAttribute.cs
  test/Tests.Infrastructure/CloudAttributeHelper.cs
  test/Tests.Infrastructure/MultiTheoryAttribute .cs
  test/Tests.Infrastructure/NightlyBuildFactAttribute.cs
  test/Tests.Infrastructure/NightlyBuildTheoryAttribute.cs
  test/Tests.Infrastructure/RavenTheoryAttribute.cs
Labels: v5.4

#20083 6.0 to 6.2 merge
  src/Raven.Client/Http/NodeSelector.cs
  src/Raven.Client/Http/RequestExecutor.cs
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/Handlers/Processors/Queries/AbstractQueriesHandlerProcessorForGet.cs
  src/Raven.Server/Documents/PeriodicBackup/ConcurrentBackupsCounter.cs
  src/Raven.Server/Utils/BackupUtils.cs
  src/Raven.Studio/webpack.config.js
  src/Raven.Studio/wwwroot/App/views/resources/widgets/gcInfoWidget.html
  src/Raven.Studio/wwwroot/Content/css/pages/cluster-dashboard.less
  src/Sparrow.Server/ByteString.cs
  test/SlowTests/Client/ClientConfigurationTests.cs
  test/SlowTests/Issues/RavenDB-23668.cs
Labels: v6.2

#20087 RavenDB-23409 test should run on 64bit only
  test/SlowTests/Issues/RavenDB-23409.cs
Labels: v5.4

#20086 6.2 to 7.0 merge
  src/Raven.Client/Http/NodeSelector.cs
  src/Raven.Client/Http/RequestExecutor.cs
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/Handlers/Processors/Queries/AbstractQueriesHandlerProcessorForGet.cs
  src/Raven.Server/Documents/PeriodicBackup/ConcurrentBackupsCounter.cs
  src/Raven.Server/NotificationCenter/AbstractNotificationCenter.cs
  src/Raven.Server/NotificationCenter/NotificationsStorage.cs
  src/Raven.Server/Rachis/Commands/DeleteNotificationCommand.cs
  src/Raven.Server/Rachis/Commands/StoreNotificationCommand.cs
  src/Raven.Server/ServerWide/ServerStore.cs
  src/Raven.Server/Utils/BackupUtils.cs
  src/Raven.Studio/webpack.config.js
  src/Raven.Studio/wwwroot/App/views/resources/widgets/gcInfoWidget.html
  src/Raven.Studio/wwwroot/Content/css/pages/cluster-dashboard.less
  src/Sparrow.Server/ByteString.cs
  test/SlowTests/Client/ClientConfigurationTests.cs
  test/SlowTests/Issues/RavenDB-23668.cs
  test/SlowTests/Server/Documents/PeriodicBackup/RavenDB-11139.cs
  test/SlowTests/Utils/CompareExchangeTombstonCleanerTestHelper.cs
Labels: v7.0

#20084 RavenDB-23679 bumped Snowflake.Data to 4.3.0
  Directory.Packages.props
Labels: v7.0

#20091 RavenDB-23695 HNSW indexing: handle updates in PostingList
  src/Voron/Data/Graphs/Hnsw.cs
  src/Voron/Data/PostingLists/PostingList.cs
  src/Voron/Util/PFor/FastPForEncoder.cs
  test/FastTests/Corax/RavenDB_23695.cs
Labels: v7.0

#20097 release/v7.0 to 7.0 merge
  Directory.Packages.props
  src/CommonAssemblyInfo.cs
  src/Raven.Client/Documents/Queries/Vector/VectorFieldFactory.cs
  src/Raven.Client/Properties/VersionInfo.cs
  src/Raven.Server/Config/Categories/IndexingConfiguration.cs
  src/Raven.Studio/typescript/viewmodels/resources/widgets/ongoingTasksWidget.ts
  src/Voron/Data/Graphs/Hnsw.cs
  src/Voron/Data/PostingLists/PostingList.cs
  src/Voron/Util/PFor/FastPForEncoder.cs
  test/FastTests/Corax/RavenDB_23695.cs
Labels: v7.0

#20090 RavenDB-23597 move the ReadBalanceBehavior to be based on the conventions
  src/Raven.Client/Http/RequestExecutor.cs
Labels: v5.4

#20095 RavenDB-23697 All revisions view: Update the about text
  src/Raven.Studio/typescript/components/pages/database/documents/allRevisions/partials/AllRevisionsAboutView.tsx
Labels: Studio, v7.0

#20117 RavenDB-19152 - SlowTests.Server.Documents.Revisions.RevisionsReplication.IdenticalRevisionCountCluster(options: DatabaseMode = Single , SearchEngineMode = Lucene)
  src/Raven.Server/Documents/Replication/IncomingReplicationHandler.cs
  test/SlowTests/Issues/RavenDB-19152.cs
Labels: v5.4

#20047 RavenDB-23619 Failing storybook smoke test: StudioSearchWithDatabaseSwitcher
  src/Raven.Studio/typescript/components/shell/studioSearchWithDatabaseSelector/StudioSearchWithDatabaseSwitcher.stories.tsx
Labels: Studio, v6.2

#20114 RavenDB-23640 omnisearch: revisions should not come up on top
  .gitignore
  src/Raven.Studio/typescript/components/shell/studioSearchWithDatabaseSelector/studioSearch/bits/StudioSearchDatabaseResults.tsx
Labels: v7.0

#20118 5.4 to 6.0 merge
  src/Raven.Client/Http/RequestExecutor.cs
  src/Raven.Server/Documents/Replication/Incoming/IncomingReplicationHandler.cs
  src/Raven.Server/Utils/BackupUtils.cs
  test/SlowTests/Issues/RavenDB-19152.cs
  test/SlowTests/Issues/RavenDB-23409.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v6.0

#20119 6.0 to 6.2 merge
  src/Raven.Client/Http/RequestExecutor.cs
  src/Raven.Server/Documents/Replication/Incoming/IncomingReplicationHandler.cs
  src/Raven.Server/Utils/BackupUtils.cs
  src/Raven.Studio/.eslintrc.js
  src/Raven.Studio/package-lock.json
  src/Raven.Studio/package.json
  src/Raven.Studio/webpack.config.js
  test/SlowTests/Issues/RavenDB-19152.cs
  test/SlowTests/Issues/RavenDB-23409.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v6.2

#20121 6.2 to 7.0 merge
  src/Raven.Client/Http/RequestExecutor.cs
  src/Raven.Server/Documents/Replication/Incoming/IncomingReplicationHandler.cs
  src/Raven.Server/Rachis/Elector.cs
  src/Raven.Server/Rachis/RachisConsensus.cs
  src/Raven.Server/Utils/BackupUtils.cs
  src/Raven.Studio/.eslintrc.js
  src/Raven.Studio/.storybook/main.ts
  src/Raven.Studio/.storybook/preview.js
  src/Raven.Studio/.storybook/storeDecorator.tsx
  src/Raven.Studio/package-lock.json
  src/Raven.Studio/package.json
  src/Raven.Studio/typescript/common/constants/timeInSeconds.ts
  src/Raven.Studio/typescript/common/shell/menu/items/manageServer.ts
  src/Raven.Studio/typescript/common/shell/menu/items/settings.ts
  src/Raven.Studio/typescript/components/common/DurationPicker.tsx
  src/Raven.Studio/typescript/components/common/SizeGetter.tsx
  src/Raven.Studio/typescript/components/common/virtualTable/cells/CellValue.tsx
  src/Raven.Studio/typescript/components/common/virtualTable/cells/CellWithCopy.tsx
  src/Raven.Studio/typescript/components/common/virtualTable/cells/CellWithDescription.tsx
  src/Raven.Studio/typescript/components/pages/database/documents/identities/DocumentIdentities.stories.tsx
  src/Raven.Studio/typescript/components/pages/database/documents/identities/DocumentIdentities.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/revisionsBinCleaner/RevisionsBinCleaner.spec.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/revisionsBinCleaner/RevisionsBinCleaner.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/revisionsBinCleaner/RevisionsBinCleanerInfoHub.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/revisionsBinCleaner/RevisionsBinCleanerUtils.ts
  src/Raven.Studio/typescript/components/pages/database/settings/revisionsBinCleaner/RevisionsBinCleanerValidation.ts
  src/Raven.Studio/typescript/components/pages/database/settings/revisionsBinCleaner/useRevisionsBinCleanerFormSideEffects.tsx
  src/Raven.Studio/typescript/components/pages/resources/manageServer/serverSettings/ServerSettings.spec.tsx
  src/Raven.Studio/typescript/components/pages/resources/manageServer/serverSettings/ServerSettings.stories.tsx
  src/Raven.Studio/typescript/components/pages/resources/manageServer/serverSettings/ServerSettings.tsx
  src/Raven.Studio/typescript/components/pages/resources/manageServer/serverSettings/ServerSettingsInfoHub.tsx
  src/Raven.Studio/typescript/components/pages/resources/manageServer/serverSettings/ServerSettingsVirtualTable.tsx
  src/Raven.Studio/typescript/components/pages/resources/manageServer/serverSettings/useServerSettingsColumns.tsx
  src/Raven.Studio/typescript/components/services/ManageServerService.ts
  src/Raven.Studio/typescript/components/shell/studioSearchWithDatabaseSelector/StudioSearchWithDatabaseSwitcher.stories.tsx
  src/Raven.Studio/typescript/models/database/settings/databaseSettingsModels.ts
  src/Raven.Studio/typescript/test/mocks/services/MockManageServerService.ts
  src/Raven.Studio/typescript/test/stubs/ManageServerStubs.ts
  src/Raven.Studio/typescript/viewmodels/database/settings/databaseSettings.ts
  src/Raven.Studio/typescript/viewmodels/manage/serverSettings.ts
  src/Raven.Studio/webpack.config.js
  src/Raven.Studio/wwwroot/App/views/manage/serverSettings.html
  src/Raven.Studio/wwwroot/Content/css/_bs5.scss
  test/SlowTests/Issues/RavenDB-19152.cs
  test/SlowTests/Issues/RavenDB-22419.cs
  test/SlowTests/Issues/RavenDB-23409.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v7.0

#20115 RavenDB-23716 do expression compilation once in BlittableJsonReader
  src/Raven.Client/Json/Serialization/NewtonsoftJson/Internal/BlittableJsonReader.cs
Labels: v5.4

#20112 RavenDB-23322 - don't read from tree on deletion [v5.4]
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Storage/Schema/Updates/Documents/42017/From41016.cs
  src/Voron/Data/Tables/Table.cs
  src/Voron/Data/Tables/TableValueCompressor.cs
Labels: v5.4

#20126 RavenDB-23322 - don't read from tree on deletion [v6.0]
  src/Raven.Server/Storage/Schema/Updates/Documents/42017/From41016.cs
  src/Voron/Data/Tables/Table.cs
  src/Voron/Data/Tables/TableValueCompressor.cs
Labels: v6.0

#20124 RavenDB-23071 - Document id isn't copied corretly
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/performanceHint/hugeDocumentsDetails.ts
Labels: v5.4, Studio

#20123 RavenDB-22491 - Change the 'revisions/size' endpoint method to POST
  src/Raven.Server/Documents/Handlers/RevisionsHandler.cs
  test/SlowTests/Issues/RavenDB-22491.cs
Labels: v5.4

#20125 RavenDB-23083 - Database compact monitoring tail not working
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/compactDatabaseDetails.ts
Labels: v5.4, Studio

#20113 RavenDB-23707 Copy to clipboard doesn't work on Document view
  .gitignore
  src/Raven.Studio/typescript/viewmodels/common/showDataDialog.ts
  src/Raven.Studio/wwwroot/App/views/common/showDataDialog.html
Labels: v5.4

#20135 RavenDB-23618 In GitHub action use node version from .nvmrc instead o…
  .github/workflows/StudioTests.yml
  .github/workflows/compile.yml
Labels: v6.2

#20134 RavenDB-23660 Fix license info misdirections
  src/Raven.Studio/typescript/components/pages/resources/about/partials/LicenseDetails.tsx
Labels: Studio, v6.2

#20131 RavenDB-23686 move notificationCenter initialize after engine initialize
  src/Raven.Server/ServerWide/ServerStore.cs
Labels: v6.2

#20137 RavenDB-23671 - Add missing license property
  src/Raven.Server/Commercial/LicenseAttribute.cs
Labels: v5.4

#20139 5.4 to 6.0 merge
  .gitignore
  src/Raven.Client/Json/Serialization/NewtonsoftJson/Internal/BlittableJsonReader.cs
  src/Raven.Server/Documents/Handlers/Processors/Batches/BatchHandlerProcessorForBulkDocs.cs
  src/Raven.Server/Documents/Handlers/RevisionsHandler.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/customControlls/licenseAgpl.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/operations/compactDatabaseDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/notificationCenter/detailViewer/performanceHint/hugeDocumentsDetails.ts
  src/Raven.Studio/typescript/viewmodels/common/showDataDialog.ts
  src/Raven.Studio/typescript/viewmodels/shell/registration.ts
  src/Raven.Studio/wwwroot/App/views/common/notificationCenter/customControlls/licenseAgpl.html
  src/Raven.Studio/wwwroot/App/views/common/showDataDialog.html
  src/Raven.Studio/wwwroot/App/views/shell/registration.html
  src/Sparrow/Utils/NativeMemory.cs
  src/Voron/Impl/FileHeaders/HeaderAccessor.cs
  src/Voron/StorageEnvironmentOptions.cs
  test/FastTests/Server/Documents/Queries/WaitingForNonStaleResults.cs
  test/SlowTests/Issues/RavenDB-22491.cs
  test/SlowTests/Issues/RavenDB-23136.cs
Labels: v6.0

#20144 RavenDB-23671 Subscription expiration is showing the next day
  src/Raven.Studio/typescript/components/pages/resources/about/AboutPage.stories.tsx
  src/Raven.Studio/typescript/components/pages/resources/about/partials/LicenseSummary.tsx
  src/Raven.Studio/typescript/models/auth/licenseModel.ts
  src/Raven.Studio/typescript/viewmodels/shell/registration.ts
Labels: v6.0, Studio

#20136 RavenDB-23728 - Fix - 'Enforce Revisions Configuration' operation lasts forever (v6.0)
  src/Raven.Server/Documents/Handlers/Admin/Processors/Revisions/AbstractAdminRevisionsHandlerProcessorForEnforceRevisionsConfiguration.cs
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  src/Raven.Server/Documents/TransactionMerger/Commands/EnforceRevisionConfigurationCommand.cs
  test/SlowTests/Issues/RavenDB-23728.cs
  test/SlowTests/Issues/RavenDB-6886.cs
  test/SlowTests/Issues/RavenDB_21934.cs
Labels: v6.0

#20151 RavenDB-23737 Fix colors for menu items
  src/Raven.Studio/typescript/common/shell/menu/items/settings.ts
  src/Raven.Studio/typescript/components/pages/database/settings/tombstones/TombstonesState.tsx
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon/tombstones.svg
  src/Raven.Studio/wwwroot/Content/css/icons.less
Labels: Studio, v6.2

#20153 RavenDB-23604 - Vector field settings: Ensure Source and Destination selections are independent
  src/Raven.Studio/typescript/models/database/index/vectorOptions.ts
Labels: Studio, v7.0

#20152 RavenDB-23735 - Refactoring of the way we pass durandal props to react components
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexesPage.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/connectionStrings/ConnectionStrings.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/DatabasesPage.stories.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/DatabasesPage.tsx
  src/Raven.Studio/typescript/viewmodels/reactViewModelBase.ts
  src/Raven.Studio/typescript/viewmodels/shardedReactViewModelBase.ts
  src/Raven.Studio/typings/_studio/dto.d.ts
Labels: Studio, v6.2

#20157 6.0 to 6.2 merge
  src/Raven.Studio/package-lock.json
  src/Raven.Studio/package.json
  src/Raven.Studio/scripts/setup_jest.js
  src/Raven.Studio/typescript/components/common/SizeGetter.tsx
  src/Raven.Studio/typescript/components/pages/database/documents/identities/DocumentIdentities.spec.tsx
  src/Raven.Studio/typescript/components/pages/resources/manageServer/serverSettings/ServerSettings.spec.tsx
Labels: Studio, v6.2

#20063 RavenDB-23664 adjust GH actions branch patterns to cover release and feature branches as well
  .github/workflows/FastTests.yml
  .github/workflows/StudioTests.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/studioConventions.yml
Labels: v5.4

#20170 6.2 to 7.0 merge
  src/Raven.Server/NotificationCenter/NotificationsStorage.cs
  src/Raven.Server/NotificationCenter/ServerStoreNotificationStorage.cs
  src/Raven.Server/ServerWide/ServerStore.cs
Labels: v7.0

#20171 RavenDB-23062 - StressTests.Client.TimeSeries.Policies.TimeSeriesConf…
  test/StressTests/Client/TimeSeries/Policies/TimeSeriesConfigurationTestsStress.cs
Labels: v5.4

#20173 RavenDB-23735 - Refactoring of the way we pass durandal props to react components (type safety fix)
  src/Raven.Studio/typescript/components/pages/database/indexes/list/IndexesPage.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/connectionStrings/ConnectionStrings.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/DatabasesPage.tsx
  src/Raven.Studio/typescript/viewmodels/reactViewModelBase.ts
  src/Raven.Studio/typescript/viewmodels/shardedReactViewModelBase.ts
  src/Raven.Studio/typings/_studio/dto.d.ts
Labels: Studio, v6.2

#20167 RavenDB-23765 Frequency input should be disabled when Cleaner is disabled
  src/Raven.Studio/typescript/components/pages/database/settings/revisionsBinCleaner/RevisionsBinCleaner.tsx
Labels: Studio, v6.2

#20110 RavenDB-23603 MultiUnaryMatch - handle not existing
  src/Corax/Querying/Matches/MultiUnaryMatch.cs
  test/SlowTests/Corax/CoraxNotExistingTests.cs
  test/SlowTests/Issues/RavenDB-22703_LowLevel.cs
Labels: Corax, v6.0

#20174 RavenDB-23772 Fixing NRE when getting number of entries from a table that was supposed to be _forGlobalReadsOnly - all documents. We need to use an index to get the number of entries then.
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxDocumentTrainSourceEnumerator.cs
  test/SlowTests/Corax/RavenDB_23772.cs
Labels: Corax, v6.0

#20179 RavenDB-23675 - fixes to sizeGetter, moving package to devDependencies, adding classname to sizegetter.
  src/Raven.Studio/package-lock.json
  src/Raven.Studio/package.json
  src/Raven.Studio/typescript/components/common/SizeGetter.tsx
Labels: v6.0, Studio

#20184 RavenDB-23778 Improve pop-up msg when removing "Delete Revisions"
  src/Raven.Studio/typescript/viewmodels/database/documents/revisionsBin.ts
Labels: Studio, v7.0

#20189 RavenDB-23429 storybook build: fix console error
  src/Raven.Studio/.storybook/main.ts
Labels: Studio, v6.2

#20190 RavenDB-23783 Fix text in popup when setting 'purge revisions'
  src/Raven.Studio/typescript/components/pages/database/settings/documentRevisions/EditRevision.tsx
Labels: Studio, v7.0

#20197 RavenDB-21765 - fix not compiling studio
  src/Raven.Studio/typescript/components/pages/database/indexes/list/terms/IndexTerms.tsx
Labels: Studio, v6.2

#20182 RavenDB-23773 - Fix failing test SeekBackwardFrom_VoronOverloads_Random
  test/SlowTests/Issues/RavenDB-23167-Voron.cs
Labels: v5.4

#20199 RavenDB-23576 Run smoke tests on GHA
  .github/workflows/StudioTests.yml
  src/Raven.Studio/package-lock.json
  src/Raven.Studio/package.json
  src/Raven.Studio/webpack.config.js
Labels: v6.2

#20203 RavenDB-21764 - clean up tests
  src/Raven.Studio/typescript/components/pages/database/documents/identities/DocumentIdentities.spec.tsx
Labels: Studio, v6.2

#20195 RavenDB-23374 New README!
  docs/image.png
  docs/logoBlue.png
  readme.md
Labels: v7.0

#20213 RavenDB-23753 Better OpenTelemetry license alert
  src/Raven.Server/Commercial/LicenseManager.cs
Labels: v6.2

#20209 RavenDB-23733 - Fix ClusterTransactionTests
  test/SlowTests/Cluster/ClusterTransactionTests.cs
Labels: v6.0

#20212 RavenDB-23683 - Improve the logic for determining when a backup should run
  src/Raven.Server/Documents/PeriodicBackup/ConcurrentBackupsCounter.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
Labels: v5.4

#20211 RavenDB-23683 - Improve the logic for determining when a backup should run
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/PeriodicBackup/ConcurrentBackupsCounter.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
Labels: v6.0

#20217 RavenDB-23785 Skip pebble tests
  test/SlowTests/Authentication/AuthenticationLetsEncryptTests.cs
Labels: v5.4

#20225 6.0 to 6.2 merge
  src/Raven.Server/Documents/Handlers/RevisionsHandler.cs
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  src/Raven.Server/Json/JsonDeserializationServer.cs
  test/SlowTests/Authentication/AuthenticationLetsEncryptTests.cs
  test/SlowTests/Issues/RavenDB-22491.cs
Labels: v6.2

#20224 RavenDB-23615 allow to set custom values to SupportedFeatures
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
Labels: v5.4

#20221 RavenDB-23798 - Fix server settings story in storybook
  src/Raven.Studio/typescript/components/pages/resources/manageServer/serverSettings/ServerSettings.stories.tsx
  src/Raven.Studio/typescript/components/pages/resources/manageServer/serverSettings/ServerSettings.tsx
Labels: Studio, v6.2

#20105 RavenDB-23695: Optimization of the fix for modification lists.
  src/Voron/Data/PostingLists/PostingList.cs
Labels: v7.0

#20186 RavenDB-23782: Add TrafficWatch and EventListener configurations in TestBase
  test/Tests.Infrastructure/TestBase.cs
Labels: v7.0

#20228 RavenDB-23775 - High CPU on RavenDB TEST cluster after update
  src/Raven.Server/Documents/DatabasesLandlord.cs
Labels: v5.4

#20233 RavenDB-23807 - Long GC pauses due to low memory handler
  src/Raven.Server/Indexing/LuceneCleaner.cs
Labels: v5.4

#20236 5.4 to 6.0 merge
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/Handlers/Debugging/MemoryDebugHandler.cs
  src/Raven.Server/Documents/Handlers/Debugging/TransactionDebugHandler.cs
  src/Raven.Server/Indexing/LuceneCleaner.cs
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
  src/Sparrow.Server/ByteString.cs
  src/Sparrow/Utils/MemoryUtils.cs
  src/Voron/Impl/LowLevelTransaction.cs
  test/FastTests/Sparrow/ByteStringTests.cs
Labels: v6.0

#20237 6.0 to 6.2 merge
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/Handlers/Debugging/MemoryDebugHandler.cs
  src/Raven.Server/Documents/Handlers/Debugging/TransactionDebugHandler.cs
  src/Raven.Server/Indexing/LuceneCleaner.cs
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
  src/Sparrow.Server/ByteString.cs
  src/Sparrow/Utils/MemoryUtils.cs
  src/Voron/Impl/LowLevelTransaction.cs
  test/FastTests/Sparrow/ByteStringTests.cs
Labels: v6.2
