Repository ravendb/ravendb, pull requests merged in 2025-04, with the labels that each got.

#20391 RavenDB-23959 Fix label in AI connection strings
  src/Raven.Studio/typescript/components/pages/database/settings/connectionStrings/editForms/aiFields/EmbeddingsMaxConcurrentBatchesField.tsx
Labels: Studio, v7.0

#20384 RavenDB-23931 Studio Search doesn't properly support macOS keyboard shortcuts
  src/Raven.Studio/typescript/components/shell/studioSearchWithDatabaseSelector/studioSearch/StudioSearch.tsx
  src/Raven.Studio/typescript/components/shell/studioSearchWithDatabaseSelector/studioSearch/hooks/useStudioSearchKeyboardEvents.ts
Labels: Studio, v6.2

#20394 RavenDB-23995 Disable react compiler due to react-table issue
  src/Raven.Studio/webpack.config.js
Labels: Studio, v6.2

#20398 RavenDB-23893 Open index errors by default
  src/Raven.Studio/typescript/components/pages/database/indexes/errors/IndexErrorsPanel.tsx
Labels: Studio, v6.2

#20401 RavenDB-23897 Clean old an irrelevant files
  git_setup.cmd
  git_setup.sh
  testInLoop.sh
Labels: v5.4

#20406 5.4 to 6.2 merge
  .github/workflows/test-conventions.yml
  git_setup.cmd
  git_setup.sh
  src/Voron/StorageEnvironment.cs
  test/SlowTests/Tests/TestsInheritanceTests.cs
  test/SlowTests/Voron/Issues/RavenDB_22767.cs
  test/Tests.Infrastructure/RavenTestCategory.cs
  testInLoop.sh
Labels: v6.2

#20411 RavenDB-23999 proxy command will respect accept-encoding header
  src/Raven.Client/Http/RavenCommand.cs
  src/Raven.Client/Http/RequestExecutor.cs
  src/Raven.Server/Documents/Handlers/Processors/AbstractHandlerProxyReadProcessor.cs
  src/Raven.Server/Documents/Handlers/Processors/OngoingTasks/OngoingTasksHandlerProcessorForBackupDatabaseNow.cs
  src/Raven.Server/Documents/Handlers/Processors/OngoingTasks/OngoingTasksHandlerProcessorForGetRunningBackupOperationStatus.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Attachments/ShardedAttachmentHandlerProcessorForGetAttachment.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Attachments/ShardedAttachmentHandlerProcessorForGetAttachmentMetadataWithCounts.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Attachments/ShardedAttachmentHandlerProcessorForHeadAttachment.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Attachments/ShardedAttachmentHandlerProcessorForPutAttachment.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Documents/ShardedDocumentHandlerProcessorForDelete.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Documents/ShardedDocumentHandlerProcessorForGenerateClassFromDocument.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Documents/ShardedDocumentHandlerProcessorForGetDocSize.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Documents/ShardedDocumentHandlerProcessorForHead.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Documents/ShardedDocumentHandlerProcessorForPatch.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Documents/ShardedDocumentHandlerProcessorForPut.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/ETL/AbstractShardedEtlHandlerProcessorForTest.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/HiLo/ShardedHiLoHandlerProcessorForGetNextHiLo.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/HiLo/ShardedHiLoHandlerProcessorForReturnHiLo.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Queries/ShardedQueriesHandlerProcessorForGet.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Queries/ShardedQueriesHandlerProcessorForPatchTest.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Replication/ShardedReplicationHandlerProcessorForGetConflicts.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Streaming/ShardedStreamingHandlerProcessorForGetTimeSeries.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/TimeSeries/ShardedTimeSeriesHandlerProcessorForGetDebugSegmentsSummary.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/TimeSeries/ShardedTimeSeriesHandlerProcessorForGetTimeSeriesStats.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/TimeSeries/ShardedTimeSeriesHandlerProcessorForPostTimeSeries.cs
  src/Raven.Server/Web/Http/ProxyCommand.cs
  src/Raven.Server/Web/Studio/Sharding/Processors/ShardedStudioDatabaseTasksHandlerProcessorForGetSuggestConflictResolution.cs
  test/SlowTests/Issues/RavenDB_23999.cs
Labels: v6.2

#20408 RavenDB-24004 Select creatable - get custom options from value
  src/Raven.Studio/typescript/components/common/Form.tsx
Labels: Studio, v6.2

#20400 RavenDB-23932 Fix dropdown menu positioning
  src/Raven.Studio/typescript/components/common/RichPanel.scss
Labels: Studio, v6.2

#20416 RavenDB-23747 Rename What's new menu item to Release notes
  src/Raven.Studio/typescript/common/shell/menu/generateMenuItems.ts
  src/Raven.Studio/typescript/common/shell/menu/items/rootItems.ts
  src/Raven.Studio/typescript/components/shell/studioSearchWithDatabaseSelector/StudioSearchWithDatabaseSwitcher.stories.tsx
  src/Raven.Studio/typescript/viewmodels/shell.ts
Labels: Studio, v6.2

#20415 RavenDB-24008 OpenAI connection string: fix tooltips
  src/Raven.Studio/typescript/components/pages/database/settings/connectionStrings/editForms/aiFields/OpenAiSettings.tsx
Labels: Studio, v7.0

#20218 RavenDB-23661: Caller should decide prefetching or not.
  src/Voron/Data/Tables/Table.cs
  src/Voron/Impl/Compaction/StorageCompaction.cs
  src/Voron/Impl/Transaction.cs
Labels: v7.0

#20422 RavenDB-24011 dropped macOS x64 from GH actions
  .github/workflows/FastTests.yml
Labels: v5.4

#20417 RavenDB-23591 - add comments for patch Client Api
  src/Raven.Client/Documents/Session/IAdvancedSessionOperations.Patch.cs
  src/Raven.Client/Documents/Session/IAsyncAdvancedSessionOperations.Patch.cs
Labels: v6.2

#20418 RavenDB-23649 Create a func to support the creation of exact or search analyzers and allow changing analyzers for static fields as well.
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxIndexingHelpers.cs
  test/SlowTests/Corax/RavenDB-23649.cs
Labels: Corax, v6.2

#20403 RavenDB-23976 Do not use `outputCount` as an indicator of the capacity of `bigDeltaOffsets` as it will likely be smaller.
  src/Voron/Util/PFor/FastPForDecoder.cs
Labels: Corax, v6.2

#20419 RavenDB-23050 Corax Jint Converter will not persist the dynamic field in the field dictionary
  src/Raven.Server/Documents/Indexes/Persistence/Corax/JintCoraxDocumentConverter.cs
  test/SlowTests/Corax/RavenDB_23050.cs
Labels: Corax, v6.2

#20430 6.2 to 7.0 merge
  src/Raven.Client/Documents/Session/IAdvancedSessionOperations.Patch.cs
  src/Raven.Client/Documents/Session/IAsyncAdvancedSessionOperations.Patch.cs
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxIndexingHelpers.cs
  src/Raven.Server/Documents/Indexes/Persistence/Corax/JintCoraxDocumentConverter.cs
  src/Voron/Util/NativeList.cs
  src/Voron/Util/PFor/FastPForDecoder.cs
  test/SlowTests/Corax/RavenDB-23649.cs
  test/SlowTests/Corax/RavenDB_23050.cs
  test/StressTests/Utils/NextAllocationSizeTests.cs
Labels: v7.0

#20431 RavenDB-24010 Fixing ocassionally failing MustRemoveFailedTransactionFromActiveTransactions test
  test/SlowTests/Voron/Issues/RavenDB_22767.cs
Labels: v5.4

#20420 RavenDB-23838 Update PropSummary.tsx
  src/Raven.Studio/typescript/components/common/AboutView.tsx
  src/Raven.Studio/typescript/components/common/ConfirmDialog.tsx
  src/Raven.Studio/typescript/components/common/DatabaseGroup.tsx
  src/Raven.Studio/typescript/components/common/Dialog.tsx
  src/Raven.Studio/typescript/components/common/EmptySet.tsx
  src/Raven.Studio/typescript/components/common/Icon.tsx
  src/Raven.Studio/typescript/components/common/NodeSet.tsx
  src/Raven.Studio/typescript/components/common/PropSummary.tsx
  src/Raven.Studio/typescript/components/common/select/Select.tsx
  src/Raven.Studio/typescript/components/models/common.ts
  src/Raven.Studio/typescript/components/pages/database/tasks/shared/OngoingTaskOperationConfirm.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/DatabaseNodeSetItem.tsx
  src/Raven.Studio/typescript/components/shell/studioSearchWithDatabaseSelector/databaseSwitcher/bits/DatabaseIcon.tsx
Labels: Studio, v6.2

#20427 RavenDB-24016 added IsProcessInJob to check if process is running in any Job
  src/Sparrow.Server/LowMemory/MemoryInformation.cs
  src/Sparrow.Server/Platform/Win32/Win32MemoryQueryMethods.cs
Labels: v5.4

#20433 RavenDB-23097 : flaky test adjustments
  test/SlowTests/Server/Documents/OngoingTasks/PinOnGoingTaskToMentorNode.cs
Labels: v6.2

#20437 RavenDB-23722 Throw relevant exception for embeddings length mismatch
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxQueryBuilder.VectorSearch.cs
  test/SlowTests/Issues/RavenDB-23722.cs
Labels: v7.0

#20441 5.4 to 6.2 merge
  src/Raven.Server/Commercial/LetsEncrypt/LetsEncryptSimulationHelper.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.19/ServerLongestTransaction.cs
  src/Raven.Server/Monitoring/Snmp/SnmpOids.cs
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
  src/Raven.Server/RavenServer.cs
  src/Sparrow.Server/LowMemory/MemoryInformation.cs
  src/Sparrow.Server/Platform/Win32/Win32MemoryQueryMethods.cs
  src/Voron/Util/ActiveTransactions.cs
  test/SlowTests/Authentication/AuthenticationLetsEncryptTests.cs
  test/SlowTests/Tools/SetupUnsecuredClusterUsingRvn.cs
  test/SlowTests/Voron/Issues/RavenDB_22767.cs
  test/Tests.Infrastructure/RavenTestBase.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v6.2

#20442 6.2 to 7.0 merge
  src/Raven.Server/Commercial/LetsEncrypt/LetsEncryptSimulationHelper.cs
  src/Raven.Server/Commercial/LicenseHelper.cs
  src/Raven.Server/Commercial/LicenseManager.cs
  src/Raven.Server/Commercial/LicenseStatus.cs
  src/Raven.Server/Commercial/LicenseStorage.cs
  src/Raven.Server/Commercial/LicenseVersionInformation.cs
  src/Raven.Server/Commercial/UpgradeRequired.cs
  src/Raven.Server/Json/JsonDeserializationServer.cs
  src/Raven.Server/Monitoring/Snmp/Objects/Server/1.19/ServerLongestTransaction.cs
  src/Raven.Server/Monitoring/Snmp/SnmpOids.cs
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
  src/Raven.Server/RavenServer.cs
  src/Raven.Studio/typescript/components/common/AboutView.tsx
  src/Raven.Studio/typescript/components/common/ConfirmDialog.tsx
  src/Raven.Studio/typescript/components/common/DatabaseGroup.tsx
  src/Raven.Studio/typescript/components/common/Dialog.tsx
  src/Raven.Studio/typescript/components/common/EmptySet.tsx
  src/Raven.Studio/typescript/components/common/Icon.tsx
  src/Raven.Studio/typescript/components/common/Modal.tsx
  src/Raven.Studio/typescript/components/common/NodeSet.tsx
  src/Raven.Studio/typescript/components/common/PropSummary.tsx
  src/Raven.Studio/typescript/components/common/select/Select.tsx
  src/Raven.Studio/typescript/components/models/common.ts
  src/Raven.Studio/typescript/components/pages/database/tasks/shared/OngoingTaskOperationConfirm.tsx
  src/Raven.Studio/typescript/components/pages/resources/about/partials/LicenseDetails.tsx
  src/Raven.Studio/typescript/components/pages/resources/about/partials/LicenseSummary.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/DatabaseNodeSetItem.tsx
  src/Raven.Studio/typescript/components/shell/studioSearchWithDatabaseSelector/databaseSwitcher/bits/DatabaseIcon.tsx
  src/Raven.Studio/typescript/durandalPlugins/bootstrapModal.ts
  src/Raven.Studio/typescript/test/stubs/LicenseStubs.ts
  src/Raven.Studio/typescript/viewmodels/shell.ts
  src/Raven.Studio/typescript/viewmodels/shell/UpgradeModal.tsx
  src/Sparrow.Server/LowMemory/MemoryInformation.cs
  src/Sparrow.Server/Platform/Win32/Win32MemoryQueryMethods.cs
  src/Voron/Util/ActiveTransactions.cs
  test/SlowTests/Authentication/AuthenticationLetsEncryptTests.cs
  test/SlowTests/Server/Documents/OngoingTasks/PinOnGoingTaskToMentorNode.cs
  test/SlowTests/Tools/SetupUnsecuredClusterUsingRvn.cs
  test/SlowTests/Voron/Issues/RavenDB_22767.cs
  test/Tests.Infrastructure/RavenTestBase.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v7.0

#20448 RavenDB-23844 Add more colors to indexPerformance
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexPerformance.ts
  src/Raven.Studio/wwwroot/App/views/database/indexes/indexPerformance.html
  src/Raven.Studio/wwwroot/Content/css/pages/index-performance.less
Labels: Studio, v7.0

#20443 RavenDB-24041 switched to tx merger when incrementing engine boots in snmp
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
Labels: v6.2

#20458 RavenDB-24061 Load custom analyzers and sorters before initializing indexes, since indexes may start before they are loaded.
  src/Raven.Server/Documents/Indexes/IndexStore.cs
Labels: v5.4

#20460 RavenDB-24015 Remove exhaustiveStringTuple form Icon story
  src/Raven.Studio/typescript/components/common/Icon.stories.tsx
Labels: Studio, v7.0

#20461 RavenDB-24051 Error when trying to access a revision from the All Revisions view
  src/Raven.Studio/typescript/viewmodels/database/documents/editDocument.ts
Labels: Studio, v7.0

#20464 RavenDB-23292 TypeError: Cannot read properties of null (reading 'countOfDocuments')
  src/Raven.Studio/typescript/common/shell/footer.ts
Labels: Studio, v6.2

#20465 6.2 to 7.0 merge
  bench/Voron.Benchmark/Corax/Containers.cs
  src/Corax/Constants.cs
  src/Corax/Indexing/IndexWriter.cs
  src/Corax/Indexing/IndexedField.cs
  src/Corax/Querying/IndexSearcher.cs
  src/Corax/Utils/ICoraxStatsScope.cs
  src/Raven.Client/Documents/Indexes/IndexingPerformanceStats.cs
  src/Raven.Server/Config/Categories/IndexingConfiguration.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/IndexStore.cs
  src/Raven.Server/Documents/Indexes/IndexingStatsAggregator.cs
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxIndexWriteOperation.cs
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxIndexingStats.cs
  src/Raven.Server/Documents/Indexes/Persistence/IndexWriteOperationBase.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/LuceneIndexWriteOperation.cs
  src/Raven.Server/Documents/Indexes/Test/TestIndexWriteOperation.cs
  src/Raven.Server/Monitoring/Snmp/SnmpWatcher.cs
  src/Raven.Studio/typescript/common/shell/footer.ts
  src/Raven.Studio/typescript/models/database/index/configurationItem.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/indexPerformance.ts
  src/Voron/Data/Containers/Container.cs
  src/Voron/Data/Containers/ContainerPageHeader.cs
  test/FastTests/Issues/RavenDB_16590.cs
  test/SlowTests/Corax/RavenDB_23050.cs
  test/SlowTests/Voron/ContainerSpaceUsageCalculationTests.cs
Labels: v7.0

#20456 CSV-755 Update npm packages (v5.4)
  src/Raven.Studio/package-lock.json
  src/Raven.Studio/package.json
  src/Raven.Studio/webpack.config.js
Labels: v5.4, Studio

#20445 RavenDB-24011 dropped macos-x64 support
  CONTRIBUTING.md
  build.ps1
  libs/libzstd/libzstd.mac.x64.dylib
  scripts/target.ps1
  scripts/upload.ps1
  src/Directory.Build.props
  src/Raven.Client/Raven.Client.csproj
  src/Raven.Pal/build.ps1
  src/Raven.Server/Raven.Server.csproj
Labels: v7.1

#20457 CSV-755 Update npm packages (v6.2)
  src/Raven.Studio/package-lock.json
  src/Raven.Studio/package.json
Labels: Studio, v6.2

#20470 RavenDB-24053 Some details are hidden for sharded db
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/ValidDatabasePropertiesPanel.spec.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/ValidDatabasePropertiesPanel.tsx
Labels: Studio, v6.2

#20481 6.2 to 7.0 merge
  src/Raven.Client/Documents/Linq/LinqPathProvider.cs
  src/Raven.Client/Documents/Linq/RavenQueryProviderProcessor.cs
  src/Raven.Client/Util/JavascriptConversionExtensions.cs
  src/Raven.Server/Documents/Handlers/Processors/Batches/AbstractClusterTransactionRequestProcessor.cs
  src/Raven.Studio/.storybook/preview.js
  src/Raven.Studio/package-lock.json
  src/Raven.Studio/package.json
  src/Raven.Studio/typescript/commands/database/documents/deleteDocumentsCommand.ts
  src/Raven.Studio/typescript/commands/database/documents/saveDocumentCommand.ts
  src/Raven.Studio/typescript/common/notifications/protractedCommandsDetector.ts
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/ValidDatabasePropertiesPanel.spec.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/ValidDatabasePropertiesPanel.tsx
  src/Raven.Studio/typescript/components/shell/partials/ProtractedRequestMessage.scss
  src/Raven.Studio/typescript/components/shell/partials/ProtractedRequestMessage.tsx
  src/Raven.Studio/typescript/main.ts
  src/Raven.Studio/typescript/viewmodels/common/deleteDocuments.ts
  src/Raven.Studio/typescript/viewmodels/database/documents/editDocument.ts
  src/Raven.Studio/typescript/viewmodels/shell.ts
  src/Raven.Studio/wwwroot/App/views/database/documents/editDocument.html
  src/Raven.Studio/wwwroot/App/views/shell.html
  src/Raven.Studio/wwwroot/index.html
  test/SlowTests/Tests/Linq/Contains.cs
Labels: v7.0

#20489 RavenDB-22767 Adjusting the assertion in `MustRemoveFailedTransactionFromActiveTransactions` test since the calculation of oldest transaction is different in 7.1
  test/SlowTests/Voron/Issues/RavenDB_22767.cs
Labels: v7.1

#20488 RavenDB-22755 Fix delete via cluster tx
  src/Raven.Studio/typescript/viewmodels/database/documents/editDocument.ts
  src/Raven.Studio/wwwroot/App/views/database/documents/editDocument.html
Labels: Studio, v6.2

#20487 RavenDB-22755 Add Delete document via cluster wide transaction
  src/Raven.Studio/typescript/viewmodels/database/documents/editDocument.ts
  src/Raven.Studio/wwwroot/App/views/database/documents/editDocument.html
Labels: Studio, v7.0

#20490 RavenDB-22755 Fix delete via cluster tx
  src/Raven.Studio/typescript/viewmodels/database/documents/editDocument.ts
  src/Raven.Studio/wwwroot/App/views/database/documents/editDocument.html
Labels: v5.4, Studio

#20486 RavenDB-23848 detect TrueToken properly when adding default operator
  src/Raven.Client/Documents/Session/AbstractDocumentQuery.cs
  test/FastTests/Issues/RavenDB_23848.cs
Labels: v6.2

#20492 RavenDB-23747 Replace icon for Release notes
  src/Raven.Studio/typescript/common/shell/menu/items/rootItems.ts
  src/Raven.Studio/wwwroot/Content/css/icons.less
Labels: Studio, v6.2

#19610 RavenDB-23148: Write amplification issues
  src/Raven.Server/Config/Categories/StorageConfiguration.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
Labels: Docs, v7.1

#20484 RavenDB-24042 fixed log messages
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
Labels: v7.0

#20485 RavenDB-23905 fixed audit message
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
Labels: v6.2

#20449 RavenDB-24052 - fix OperationCanceledException on waiting subscriptions
  src/Raven.Server/Documents/TcpHandlers/SubscriptionConnection.cs
  test/SlowTests/Client/Subscriptions/SubscriptionsBasic.cs
Labels: v5.4

#20491 RavenDB-24054 Fix creating test index
  src/Raven.Studio/typescript/models/database/index/testIndex.ts
  src/Raven.Studio/typescript/viewmodels/database/indexes/editIndex.ts
Labels: Studio, v6.2

#20509 RavenDB-24060 Adjust license Type text for Cloud
  src/Raven.Studio/typescript/models/auth/licenseModel.ts
Labels: Studio, v6.2

#20508 RavenDB-24060 Adjust license Type text for Cloud
  src/Raven.Studio/typescript/models/auth/licenseModel.ts
Labels: v5.4, Studio

#20520 5.4 to 6.2 merge
  src/Raven.Server/Documents/Subscriptions/AbstractSubscriptionConnectionsState.cs
  test/SlowTests/Client/Subscriptions/SubscriptionsBasic.cs
Labels: v6.2

#20514 RavenDB-14251 Log while waiting for retention to ensure compression thread is awake
  test/SlowTests/SparrowTests/LoggingSourceTests.cs
Labels: v5.4

#20522 RavenDB-23989 - (v7.0) replace 'react-dnd' with '@dnd-kit/core'
  src/Raven.Studio/package-lock.json
  src/Raven.Studio/package.json
  src/Raven.Studio/scripts/setup_jest.js
  src/Raven.Studio/typescript/components/hooks/useDraggableItem.ts
Labels: Studio, v7.0

#20523 RavenDB-23989 - (v6.2) replace 'react-dnd' with '@dnd-kit/core'
  src/Raven.Studio/package-lock.json
  src/Raven.Studio/package.json
  src/Raven.Studio/scripts/setup_jest.js
  src/Raven.Studio/typescript/components/hooks/useDraggableItem.ts
Labels: Studio, v6.2

#20543 release/v6.2 to v6.2 merge
  src/CommonAssemblyInfo.cs
  src/Raven.Client/Properties/VersionInfo.cs
  src/Raven.Studio/typescript/components/pages/database/indexes/list/migration/import/ImportIndexes.tsx
Labels: v6.2

#20542 release/v5.4 to v5.4 merge
  src/CommonAssemblyInfo.cs
  src/Raven.Client/Properties/VersionInfo.cs
Labels: v5.4

#20537 RavenDB-23441 Vector Search - Autocomplete Enhancements
  src/Raven.Studio/languageService/grammar/BaseRqlLexer.g4
  src/Raven.Studio/languageService/grammar/BaseRqlParser.g4
  src/Raven.Studio/languageService/src/generated/BaseRqlLexer.interp
  src/Raven.Studio/languageService/src/generated/BaseRqlLexer.tokens
  src/Raven.Studio/languageService/src/generated/BaseRqlLexer.ts
  src/Raven.Studio/languageService/src/generated/BaseRqlParser.interp
  src/Raven.Studio/languageService/src/generated/BaseRqlParser.tokens
  src/Raven.Studio/languageService/src/generated/BaseRqlParser.ts
  src/Raven.Studio/languageService/src/generated/BaseRqlParserVisitor.ts
  src/Raven.Studio/languageService/src/providers/common.ts
  src/Raven.Studio/languageService/src/providers/keywords.ts
  src/Raven.Studio/languageService/test/autocomplete/where.spec.ts
  src/Raven.Studio/languageService/test/data/queries.json
Labels: Studio, v7.0

#20533 RavenDB-23972 Use `InlineDataWithRandomSeed` instead of `Random.Shared` to retrieve the seed when the test fails.
  test/FastTests/Sparrow/Memory.cs
  test/SlowTests/Voron/CompactTrees/FuzzyUpserts.cs
  test/StressTests/Client/MultiGet.cs
  test/StressTests/Corax/Bugs/PostingListTestsExtended.cs
Labels: v7.0

#20507 RavenDB-23339 Add audit logs for index/database configuration
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
Labels: v5.4

#20546 CSV-775 Update socks package
  src/Raven.Studio/package-lock.json
Labels: v5.4, Studio
