Repository ravendb/ravendb, pull requests merged in 2025-09, with the labels that each got.

#21290 5.4 to 6.2 merge
  .github/workflows/versionLabel.yml
  scripts/githubActions/set_github_label.ps1
Labels: v6.2

#21289 RavenDB-20854 - Fix for `SlowTests.Issues.RavenDB_20150.CompareExchangeTombstoneWillBeCleanedOnlyWhenAllNodesHaveBackedUpPreviousOnes`
  test/SlowTests/Issues/RavenDB_20150.cs
Labels: v5.4

#21288 RavenDB-21427 fix test Prevent_Put_Dynamic_Node_Distribution
  test/SlowTests/Issues/RavenDB-21427.cs
Labels: v6.2

#21287 RavenDB-22224: flaky test adjustments
  test/SlowTests/Server/Documents/ETL/Olap/RavenDB_18465.cs
Labels: v6.2

#21292 7.0 to 7.1 merge
  .github/copilot-instructions.md
  .github/workflows/versionLabel.yml
  scripts/githubActions/set_github_label.ps1
  src/Raven.Server/Documents/CountersRepairTask.cs
  src/Raven.Server/Documents/CountersStorage.cs
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/Handlers/CountersHandler.cs
  src/Raven.Server/Documents/Replication/Incoming/IncomingReplicationHandler.cs
  src/Raven.Server/Routing/RequestRouter.cs
  src/Raven.Server/Storage/Schema/Updates/Documents/50001/From42017.cs
  src/Raven.Server/Utils/BackupUtils.cs
  src/Raven.Studio/typescript/components/common/Form.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/DatabasesPage.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/DatabasesList.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/DatabasesSelectActions.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/store/databasesViewSlice.ts
  src/Raven.Studio/typescript/models/database/documents/documentMetadata.ts
  src/Raven.Studio/typescript/viewmodels/database/documents/editDocument.ts
  src/Raven.Studio/wwwroot/App/views/database/documents/editDocument.html
  src/Raven.Studio/wwwroot/App/views/resources/deleteDatabaseConfirm.html
  src/Raven.Studio/wwwroot/App/views/resources/disableDatabaseToggleConfirm.html
  src/Raven.Studio/wwwroot/Content/css/pages/documents-edit.less
  test/SlowTests/Client/Subscriptions/SubscriptionsBasic.cs
  test/SlowTests/Data/RavenDB_24797/24797_counters_test.ravendb-snapshot
  test/SlowTests/Issues/RavenDB-18442.cs
  test/SlowTests/Issues/RavenDB-24797.cs
  test/SlowTests/Issues/RavenDB_20084.cs
  test/SlowTests/Issues/RavenDB_20915.cs
  test/SlowTests/Server/Documents/QueueSink/Issues/RavenDB_22105.cs
  test/SlowTests/Server/Replication/PullReplicationTests.cs
  test/SlowTests/SlowTests.csproj
  test/StressTests/Issues/RavenDB-13987.cs
  test/StressTests/Issues/RavenDB_14292.cs
  test/StressTests/Issues/RavenDB_14744.cs
  test/StressTests/Issues/RavenDB_18420.cs
  test/StressTests/Server/Replication/ExternalReplicationStressTests.cs
Labels: v7.1

#21302 RavenDB-24929 : fixed failing test for AI Agent
  test/SlowTests/Server/Documents/AI/AiAgent/RavenDB-24611.cs
Labels: v7.1, ai-agent

#21303 RavenDB-24928 : fixed flaky test EventWillBeRaisedForUnexpectedActions
  test/SlowTests/Server/Documents/AI/AiAgent/RavenDB-24900.cs
Labels: v7.1, ai-agent

#21298 RavenDB-24621 GenAI support for images & documents
  src/Raven.Server/Documents/AI/AiExceptions.cs
  src/Raven.Server/Documents/AI/ChatCompletionClient.cs
  src/Raven.Server/Documents/AI/IChatCompletionClient.cs
  src/Raven.Server/Documents/ETL/EtlTransformer.cs
  src/Raven.Server/Documents/ETL/Providers/AI/AiAttachment.cs
  src/Raven.Server/Documents/ETL/Providers/AI/GenAi/GenAiBatchPatchCommand.cs
  src/Raven.Server/Documents/ETL/Providers/AI/GenAi/GenAiResultItem.cs
  src/Raven.Server/Documents/ETL/Providers/AI/GenAi/GenAiScriptResult.cs
  src/Raven.Server/Documents/ETL/Providers/AI/GenAi/GenAiScriptTransformer.cs
  src/Raven.Server/Documents/ETL/Providers/AI/GenAi/GenAiTask.cs
  src/Raven.Server/Documents/ETL/Providers/AI/GenAi/Test/GenAiTestScriptResult.cs
  src/Raven.Server/Documents/ETL/Providers/AI/GenAi/Test/TestGenAiScript.cs
  src/Raven.Server/Documents/ETL/Providers/AI/Handlers/Processors/AiEtlHandlerProcessorForTestAiConnectionBase.cs
  src/Raven.Server/Documents/ETL/Test/TestEtlScript.cs
  src/Raven.Studio/typescript/components/common/ace/AceEditor.tsx
  src/Raven.Studio/typescript/components/common/virtualTable/partials/VirtualTableBodyWrapper.tsx
  src/Raven.Studio/typescript/components/common/virtualTable/partials/VirtualTableColumnSettings.tsx
  src/Raven.Studio/typescript/components/common/virtualTable/partials/VirtualTableHead.tsx
  src/Raven.Studio/typescript/components/common/virtualTable/utils/virtualTableConstants.ts
  src/Raven.Studio/typescript/components/common/virtualTable/utils/virtualTableUtils.ts
  src/Raven.Studio/typescript/components/pages/database/tasks/ongoingTasks/editTasks/editGenAiTask/hooks/useEditGenAiTaskTests.ts
  src/Raven.Studio/typescript/components/pages/database/tasks/ongoingTasks/editTasks/editGenAiTask/partials/EditGenAiTaskAttachmentsButton.tsx
  src/Raven.Studio/typescript/components/pages/database/tasks/ongoingTasks/editTasks/editGenAiTask/partials/EditGenAiTaskFormVirtualList.tsx
  src/Raven.Studio/typescript/components/pages/database/tasks/ongoingTasks/editTasks/editGenAiTask/partials/EditGenAiTaskPlayground.tsx
  src/Raven.Studio/typescript/components/pages/database/tasks/ongoingTasks/editTasks/editGenAiTask/partials/EditGenAiTaskReadOnlyVirtualList.tsx
  src/Raven.Studio/typescript/components/pages/database/tasks/ongoingTasks/editTasks/editGenAiTask/partials/fields/EditGenAiTaskContextFields.tsx
  src/Raven.Studio/typescript/components/pages/database/tasks/ongoingTasks/editTasks/editGenAiTask/store/editGenAiTaskSlice.ts
  src/Raven.Studio/typescript/components/pages/database/tasks/ongoingTasks/editTasks/editGenAiTask/utils/editGenAiTaskValidation.ts
  src/Raven.Studio/typescript/test/stubs/TasksStubs.ts
  test/SlowTests/Data/RavenDB_24644/Hibernating.pdf
  test/SlowTests/Data/RavenDB_24644/Raven.pdf
  test/SlowTests/Data/RavenDB_24645/heart.gif
  test/SlowTests/Data/RavenDB_24645/heart.jpeg
  test/SlowTests/Data/RavenDB_24645/heart.png
  test/SlowTests/Data/RavenDB_24645/heart.webp
  test/SlowTests/Data/RavenDB_24648/banana.png
  test/SlowTests/Data/RavenDB_24648/heart.png
  test/SlowTests/Data/RavenDB_24648/star.png
  test/SlowTests/Server/Documents/AI/ChatCompletionClientTests.cs
  test/SlowTests/Server/Documents/AI/GenAi/GenAiTestScript.cs
  test/SlowTests/Server/Documents/AI/GenAi/Issues/RavenDB-24621.cs
  test/SlowTests/Server/Documents/AI/GenAi/Issues/RavenDB-24642.cs
  test/SlowTests/Server/Documents/AI/GenAi/Issues/RavenDB-24644.cs
  test/SlowTests/Server/Documents/AI/GenAi/Issues/RavenDB-24645.cs
  test/SlowTests/Server/Documents/AI/GenAi/Issues/RavenDB-24867.cs
  test/SlowTests/Server/Documents/AI/GenAi/RavenDB-24648.cs
  test/SlowTests/SlowTests.csproj
  test/StressTests/GenAi/ChatCompletionClientStressTests.cs
  test/Tests.Infrastructure/ConnectionString/AI/BaseAiConnectionStringForTesting.cs
  test/Tests.Infrastructure/RavenTestBase.cs
Labels: v7.1

#21267 RavenDB-24942 use Avx512F.VL if possible for the inner loop of XXhash
  src/Sparrow/Hashing.Streamed.cs
  src/Sparrow/Hashing.cs
Labels: v7.1

#21314 RavenDB-24912 - Remove 38 unused embedded resources from test projects
  test/FastTests/Corax/Bugs/Terms-2.txt.gz
  test/FastTests/FastTests.csproj
  test/SlowTests/Data/RavenDB_13512/Incremental/17.ravendb-full-backup
  test/SlowTests/Data/RavenDB_13512/Incremental/18-01.ravendb-incremental-backup
  test/SlowTests/Data/RavenDB_13512/Incremental/18.ravendb-incremental-backup
  test/SlowTests/Data/RavenDB_13512/counters.test.4.1.6.ravendb-full-backup
  test/SlowTests/Data/mssql.northwind.insert.sql
  test/SlowTests/Data/mysql.northwind.insert.sql
  test/SlowTests/SlowTests.csproj
Labels: v7.1

#21329 RavenDB-25012 Fixing the potential race that OldestTransaction returned non zero value while there was no active transaction
  src/Voron/Util/ActiveTransactions.cs
  test/SlowTests/Voron/Issues/RavenDB_25012.cs
Labels: v5.4

#21346 RavenDB-22440 : fix flaky test
  test/StressTests/Server/Documents/ETL/Olap/LocalTestsStress.cs
Labels: v5.4

#21347 RavenDB-25023 GenAI: attachments NRE
  src/Raven.Studio/typescript/components/pages/database/tasks/ongoingTasks/editTasks/editGenAiTask/hooks/useEditGenAiTaskTests.ts
  src/Raven.Studio/typescript/components/pages/database/tasks/ongoingTasks/editTasks/editGenAiTask/utils/editGenAiTaskValidation.ts
Labels: Studio, v7.1

#21348 RavenDB-25024 session.Advanced.HasChanges does not reflect metadata c…
  src/Raven.Client/Documents/Session/InMemoryDocumentSessionOperations.cs
  test/SlowTests/Issues/RavenDB-25024.cs
Labels: v5.4

#21350 RavenDB-24621 - Change AiAttachmentSource names
  src/Raven.Server/Documents/ETL/Providers/AI/AiAttachment.cs
  src/Raven.Server/Documents/ETL/Providers/AI/GenAi/GenAiScriptTransformer.cs
  src/Raven.Server/Documents/ETL/Providers/AI/GenAi/GenAiTask.cs
  src/Raven.Studio/typescript/test/stubs/TasksStubs.ts
  test/SlowTests/Server/Documents/AI/GenAi/RavenDB-24648.cs
Labels: v7.1

#21352 RavenDB-24981 - Fix failing test 'AiAgentBasics.CanRunTest'
  src/Raven.Server/Documents/Handlers/AI/Agents/AbstractAiAgentProcessor.cs
  src/Raven.Server/Documents/Handlers/AI/Agents/AiAgentProcessorForTestConversation.cs
  src/Raven.Server/Documents/Handlers/AI/Agents/ConversationDocument.cs
  src/Raven.Server/Documents/Handlers/AI/Agents/PutConversationCommand.cs
  test/SlowTests/Server/Documents/AI/AiAgent/AiAgentBasics.cs
Labels: v7.1

#21349 RavenDB-22732 Add periodic backup info to debug package
  src/Raven.Client/Documents/Operations/OngoingTasks/GetTaskInfoResult.cs
  src/Raven.Server/Web/System/OngoingTasksHandler.cs
Labels: v5.4

#21363 RavenDB-25020 Fixing potential race condition in the test
  test/SlowTests/Voron/Issues/RavenDB_25012.cs
Labels: v5.4

#21353 RavenDB-24863 Meet escape behavior of only-ascii Id with not-only-ascii Id and allow cleaning documents with corrupted Ids
  src/Raven.Server/Documents/AttachmentsStorage.cs
  src/Raven.Server/Documents/ConflictsStorage.cs
  src/Raven.Server/Documents/CountersRepairTask.cs
  src/Raven.Server/Documents/CountersStorage.cs
  src/Raven.Server/Documents/DocumentIdWorker.cs
  src/Raven.Server/Documents/DocumentsStorage.Debug.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Handlers/Batches/Commands/ClusterTransactionMergedCommand.cs
  src/Raven.Server/Documents/Handlers/Debugging/DocumentDebugHandler.cs
  src/Raven.Server/Documents/Indexes/Static/CurrentIndexingScope.cs
  src/Raven.Server/Documents/Indexes/Workers/Counters/HandleCompareExchangeCountersReferences.cs
  src/Raven.Server/Documents/Indexes/Workers/Counters/HandleCountersReferences.cs
  src/Raven.Server/Documents/Indexes/Workers/TimeSeries/HandleCompareExchangeTimeSeriesReferences.cs
  src/Raven.Server/Documents/Indexes/Workers/TimeSeries/HandleTimeSeriesReferences.cs
  src/Raven.Server/Documents/Patch/PatchDocumentCommand.cs
  src/Raven.Server/Documents/Replication/Incoming/IncomingReplicationHandler.cs
  src/Raven.Server/Documents/Revisions/DeleteRevisionsByChangeVectorMergedCommand.cs
  src/Raven.Server/Documents/Revisions/DeleteRevisionsByDocumentIdMergedCommand.cs
  src/Raven.Server/Documents/Revisions/RevisionsStorage.Debug.cs
  src/Raven.Server/Documents/Revisions/RevisionsStorage.RevisionsBinCleanMergedCommand.cs
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesSliceHolder.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesStats.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesStorage.cs
  src/Raven.Server/ServerWide/SecretProtection.cs
  src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
  src/Raven.Server/Smuggler/Documents/StreamDestination.cs
  src/Raven.Server/Storage/Schema/Updates/Documents/42017/From41016.cs
  src/Raven.Server/Storage/Schema/Updates/Documents/50001/From42017.cs
  src/Raven.Server/Utils/ShardHelper.cs
  test/FastTests/Server/Documents/DocumentIdWorkerTests.cs
  test/SlowTests/Client/Attachments/AttachmentsReplication.cs
  test/SlowTests/Issues/RavenDB-24797.cs
  test/SlowTests/Issues/RavenDB_15240.cs
  test/SlowTests/Issues/RavenDB_19529.cs
  test/SlowTests/Issues/RavenDB_20843.cs
  test/SlowTests/Issues/RavenDB_22835.cs
  test/SlowTests/Issues/RavenDB_23167.cs
  test/SlowTests/Server/Documents/DocumentIdWorkerTests.cs
Labels: v6.2

#21376 5.4 to 6.2 merge
  src/Raven.Client/Documents/Operations/Backups/RestoreBackupConfiguration.cs
  src/Raven.Client/Documents/Operations/OngoingTasks/GetTaskInfoResult.cs
  src/Raven.Client/Documents/Session/InMemoryDocumentSessionOperations.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/OngoingTasks/AbstractOngoingTasks.cs
  src/Raven.Studio/typescript/test/stubs/TasksStubs.ts
  src/Voron/Data/BTrees/Tree.Stream.cs
  src/Voron/Impl/StreamBufferAllocator.cs
  src/Voron/Impl/Transaction.cs
  test/SlowTests/Issues/RavenDB-25024.cs
  test/SlowTests/Voron/Issues/RavenDB_25012.cs
  test/StressTests/Issues/RavenDB-15145.cs
  test/StressTests/Server/Documents/ETL/Olap/LocalTestsStress.cs
Labels: v6.2

#21383 RavenDB-24698 fix Backups restore points listing
  src/Raven.Server/Documents/PeriodicBackup/Aws/RavenAwsS3Client.cs
Labels: v5.4

#21384 RavenDB-25058 Fix restoring Incremental timeseries with dead values
  src/Raven.Server/Documents/TimeSeries/TimeSeriesStorage.cs
  test/SlowTests/Server/Documents/PeriodicBackup/BackupAndRestoreForIncrementalTimeSeries.cs
Labels: v6.2

#21390 RavenDB-25064 - Add the total allocated to the allocations event listener event
  src/Raven.Server/EventListener/EventsListener.cs
Labels: v5.4

#21393 RavenDB-24821 Open license modal when feature is not available for GenAI and Ai Agents
  src/Raven.Studio/typescript/components/pages/database/aiHub/aiAgents/partials/AiAgentsInfoHub.tsx
  src/Raven.Studio/typescript/components/pages/database/tasks/ongoingTasks/editTasks/editGenAiTask/EditGenAiTaskInfoHub.tsx
Labels: Studio, v7.1

#21388 RavenDB-24543 - use local schema for retired attachments schema upgrade
  src/Raven.Server/Storage/Schema/Updates/Documents/72000/From62000.cs
Labels: remote-attachments

#21408 merge v7.0 to release/v7.0
  Directory.Packages.props
Labels: v7.0, release

#21416 HRINT-4274 Replace usages of npm install with npm ci
  .github/copilot-instructions.md
  scripts/buildProjects.ps1
Labels: v6.2

#21409 merge v7.1 to release/v7.1
  Directory.Packages.props
Labels: v7.1, release

#21413 RavenDB-25045 : Debug assert fail in ByteString
  src/Raven.Server/Documents/CountersRepairTask.cs
Labels: v6.2, release

#21415 RavenDB-25045 : Debug assert fail in ByteString
  src/Raven.Server/Documents/CountersRepairTask.cs
Labels: v7.1, release

#21411 RavenDB-25068 use new request handler for queries
  src/Raven.Server/Documents/Handlers/AI/Agents/AbstractAiAgentProcessor.cs
  src/Raven.Server/Documents/Handlers/Processors/MultiGet/AbstractMultiGetHandlerProcessorForPost.cs
  test/SlowTests/Server/Documents/AI/AiAgent/RavenDB-24913.cs
Labels: v7.1, release

#21422 merge release/v6.2 to v6.2
  src/Raven.Server/Documents/CountersRepairTask.cs
Labels: v6.2

#21424 merge release/v7.1 to v7.1
  src/Raven.Client/Documents/Operations/AI/AiConnectionString.cs
  src/Raven.Client/Documents/Operations/AI/AiConnectorType.cs
  src/Raven.Client/Documents/Operations/AI/VertexSettings.cs
  src/Raven.Server/Documents/CountersRepairTask.cs
  src/Raven.Server/Documents/ETL/Providers/AI/Extensions/AiExtensions.cs
  src/Raven.Server/Documents/ETL/Providers/AI/Extensions/VertexBearerTokenProvider.cs
  src/Raven.Server/Documents/ETL/Providers/AI/Handlers/Processors/AiEtlHandlerProcessorForTestAiConnectionBase.cs
  src/Raven.Server/Documents/Handlers/AI/Agents/AbstractAiAgentProcessor.cs
  src/Raven.Server/Documents/Handlers/Processors/MultiGet/AbstractMultiGetHandlerProcessorForPost.cs
  src/Raven.Server/Json/JsonDeserializationServer.cs
  src/Raven.Studio/typescript/components/pages/database/settings/connectionStrings/connectionStringsTypes.ts
  src/Raven.Studio/typescript/components/pages/database/settings/connectionStrings/editForms/AiConnectionString.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/connectionStrings/editForms/aiConnectionStringUtils.ts
  src/Raven.Studio/typescript/components/pages/database/settings/connectionStrings/editForms/aiFields/VertexSettings.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/connectionStrings/store/connectionStringsMapsFromDto.ts
  src/Raven.Studio/typescript/components/pages/database/settings/connectionStrings/store/connectionStringsMapsToDto.ts
  src/Raven.Studio/typescript/test/stubs/DatabasesStubs.ts
  src/Raven.Studio/typings/_studio/dto.d.ts
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon/vertex-ai.svg
  test/SlowTests/Server/Documents/AI/AiAgent/RavenDB-24913.cs
  test/SlowTests/Server/Documents/AI/AiConnectionStringsTests.cs
  test/Tests.Infrastructure/ConnectionString/AI/VertexConnectorForTesting.cs
  test/Tests.Infrastructure/RavenAiIntegrationAttribute.cs
Labels: v7.1

#21423 merge release/v7.0 to v7.0
  src/Raven.Server/Documents/CountersRepairTask.cs
Labels: v7.0

#21426 RavenDB-24953 Strengthen the expected exceptions check conditions
  test/SlowTests/Issues/RavenDB_22498.cs
Labels: v6.2

#21427 RavenDB-22489 Changing the test conditions a bit. Better assertion message.
  test/SlowTests/Server/Documents/ETL/Raven/RavenDB_12800.cs
Labels: v6.2

#21425 RavenDB-24757 / RavenDB-14548 Added missing handling of 7.x tasks in TasksInfoAnalyzer of Debug Package analyzer
  src/Raven.Server/Documents/Handlers/Debugging/DebugPackage/Analyzers/Database/TasksInfoAnalyzer.cs
Labels: v7.1

#21359 RavenDB-24150 - add check of the size of attachment when its already exists in the cloud
  src/Raven.Server/Documents/Attachments/AttachmentUploader.cs
  src/Raven.Server/Documents/PeriodicBackup/Aws/RavenAwsS3Client.cs
  src/Raven.Server/Documents/PeriodicBackup/Azure/RavenAzureClient.cs
  src/Raven.Server/Documents/PeriodicBackup/FileUploaderBase.cs
  src/Raven.Server/Documents/RetireAttachmentsSender.cs
  test/SlowTests/Server/Documents/Attachments/AzureRetiredAttachmentsSlowTests.cs
  test/SlowTests/Server/Documents/Attachments/RetiredAttachmentsAzureBase.cs
  test/SlowTests/Server/Documents/Attachments/RetiredAttachmentsHolder.cs
  test/SlowTests/Server/Documents/Attachments/RetiredAttachmentsS3Base.cs
  test/SlowTests/Server/Documents/Attachments/S3RetiredAttachmentsSlowTests.cs
Labels: remote-attachments

#21455 [Release-7.0] RavenDB-22767 Dispose a streaming result so it will dispose a read transaction explicitly (via QueryResultServerSide.ReadTransactionDispose)
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Queries/Dynamic/CollectionQueryRunner.cs
Labels: v7.0, release

#21456 [Release-7.1] RavenDB-22767 Dispose a streaming result so it will dispose a read transaction explicitly (via QueryResultServerSide.ReadTransactionDispose)
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Queries/Dynamic/CollectionQueryRunner.cs
Labels: v7.1, release

#21461 7.0 to 7.1 merge
  .github/copilot-instructions.md
  bench/Micro.Benchmark/Program.cs
  scripts/buildProjects.ps1
  src/Corax/Constants.cs
  src/Corax/EntryIdPaginationSupportStatus.cs
  src/Corax/Indexing/IndexWriter.cs
  src/Corax/Querying/IndexSearcher.cs
  src/Corax/Querying/Matches/AllEntriesMatch.cs
  src/Corax/Querying/Matches/AndNotMatch.Erasure.cs
  src/Corax/Querying/Matches/AndNotMatch.cs
  src/Corax/Querying/Matches/BinaryMatch.Erasure.cs
  src/Corax/Querying/Matches/BinaryMatch.cs
  src/Corax/Querying/Matches/BoostingMatch.cs
  src/Corax/Querying/Matches/DeduplicationMatch.cs
  src/Corax/Querying/Matches/IncludeNonExistingMatch.cs
  src/Corax/Querying/Matches/IncludeNullMatch.cs
  src/Corax/Querying/Matches/MemoizationMatch.Erasure.cs
  src/Corax/Querying/Matches/MemoizationMatch.Provider.cs
  src/Corax/Querying/Matches/MemoizationMatch.cs
  src/Corax/Querying/Matches/Meta/IQueryMatch.cs
  src/Corax/Querying/Matches/MultiTermMatch.Erasure.cs
  src/Corax/Querying/Matches/MultiTermMatch.cs
  src/Corax/Querying/Matches/MultiUnaryMatch.Erasure.cs
  src/Corax/Querying/Matches/MultiUnaryMatch.cs
  src/Corax/Querying/Matches/MultiVectorSearchMatch.cs
  src/Corax/Querying/Matches/PharseMatch.cs
  src/Corax/Querying/Matches/SortingMatches/SortingMatch.Erasure.cs
  src/Corax/Querying/Matches/SortingMatches/SortingMatch.cs
  src/Corax/Querying/Matches/SortingMatches/SortingMultiMatch.Comparers.cs
  src/Corax/Querying/Matches/SortingMatches/SortingMultiMatch.Erasure.cs
  src/Corax/Querying/Matches/SpatialMatch/SpatialMatch.cs
  src/Corax/Querying/Matches/TermMatch.cs
  src/Corax/Querying/Matches/VectorSearchMatch.cs
  src/Corax/Querying/TermsReader.cs
  src/Corax/SupportedFeatures.cs
  src/Corax/Utils/GrowableBitArray.cs
  src/Corax/Utils/GrowableHashSet.cs
  src/Raven.Server/Documents/Indexes/IndexDefinitionBaseServerSide.cs
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxIndexFacetedReadOperation.cs
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxIndexReadOperation.cs
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxIndexWriteOperation.cs
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxQueryBuilder.cs
  src/Raven.Server/Documents/Indexes/Persistence/Corax/QueryOptimizer/CoraxBooleanItem.cs
  src/Raven.Server/Documents/Indexes/Persistence/Corax/QueryOptimizer/CoraxBooleanQueryBase.cs
  src/Raven.Studio/typescript/components/common/FeatureAvailabilitySummary.spec.tsx
  src/Raven.Studio/typescript/viewmodels/database/cmpXchg/editCmpXchg.ts
  src/Voron/Data/Lookups/Lookup.cs
  test/FastTests/Corax/CompoundFieldsOnIndex.cs
  test/FastTests/Corax/StreamingOptimization_QueryBuilder.cs
  test/SlowTests/Corax/GrowableBitArrayTests.cs
  test/SlowTests/Corax/RavenDB-22469.cs
  test/SlowTests/Issues/RavenDB-19932.cs
  test/SlowTests/Issues/RavenDB-24794.cs
  test/SlowTests/Server/Documents/AI/Embeddings/LoadVectorQuantizationTests.cs
Labels: v7.1

#21365 RavenDB-25031 Optimize DocumentHandler processor method
  src/Raven.Server/Documents/Handlers/DocumentHandler.cs
  src/Raven.Server/Documents/Handlers/Processors/Documents/AbstractDocumentHandlerProcessorForGet.cs
  src/Raven.Server/Documents/Sharding/Handlers/ShardedDocumentHandler.cs
  src/Raven.Server/Utils/DisposableBorrow.cs
Labels: v6.2

#21468 [v6.2] RavenDB-25092 - Top developer license bar overlaps fullscreen document editor
  src/Raven.Studio/wwwroot/App/views/database/documents/editDocument.html
Labels: v6.2, release

#21469 [v7.1] RavenDB-25092 - Top developer license bar overlaps fullscreen document editor
  src/Raven.Studio/wwwroot/App/views/database/documents/editDocument.html
Labels: v7.1, release

#21467 RavenDB-25018 Test fix
  test/SlowTests/Issues/RavenDB-24649.cs
Labels: v6.2

#21373 RavenDB-24974 Unify code path for GenAI and AI Agent
  src/Raven.Client/Documents/Operations/AI/AiUsage.cs
  src/Raven.Server/Documents/AI/ChatCompletionClient.cs
  src/Raven.Server/Documents/AI/IChatCompletionClient.cs
  src/Raven.Server/Documents/ETL/Providers/AI/GenAi/GenAiTask.cs
  src/Raven.Server/Documents/ETL/Providers/AI/Handlers/Processors/AiEtlHandlerProcessorForTestAiConnectionBase.cs
  src/Raven.Server/Documents/Handlers/AI/Agents/AbstractAiAgentProcessor.cs
  src/Raven.Server/Documents/Handlers/AI/Agents/AiAgentProcessorForTestConversation.cs
  src/Raven.Server/Documents/Handlers/AI/Agents/ConversationHandler.cs
  src/Raven.Server/Documents/Handlers/AI/Agents/GenAiConversationHandler.cs
  src/Raven.Server/Documents/Handlers/AI/Agents/RequestBody.cs
  src/Raven.Server/Documents/Handlers/AI/Agents/Talker.cs
  test/SlowTests/Server/Documents/AI/AiAgent/AiAgentErrors.cs
  test/SlowTests/Server/Documents/AI/AiAgent/AiAgentMockLlmTests.cs
  test/SlowTests/Server/Documents/AI/AiAgent/RavenDB-24811.cs
  test/SlowTests/Server/Documents/AI/AiAgent/RavenDB-24900.cs
  test/SlowTests/Server/Documents/AI/ChatCompletionClientTests.cs
  test/SlowTests/Server/Documents/AI/GenAi/GenAiBasics.cs
  test/SlowTests/Server/Documents/AI/GenAi/GenAiErrorHandling.cs
  test/SlowTests/Server/Documents/AI/GenAi/GenAiStats.cs
  test/SlowTests/Server/Documents/AI/GenAi/GenAiTestScript.cs
  test/SlowTests/Server/Documents/AI/OllamaTemperatureParameterTests.cs
  test/SlowTests/Server/Documents/AI/OllamaThinkParameterTests.cs
  test/StressTests/GenAi/ChatCompletionClientStressTests.cs
  test/Tests.Infrastructure/ConnectionString/AI/BaseAiConnectionStringForTesting.cs
  tools/TypingsGenerator/Program.cs
Labels: v7.1

#21473 RavenDB-25101 fix rollup when segment edge align with the aggregation
  src/Raven.Server/Documents/TimeSeries/TimeSeriesRollups.cs
  test/SlowTests/Client/TimeSeries/Issues/RavenDB_25101.cs
Labels: v6.2

#21479 [Release-7.1] RavenDB-25103 Pull replication (hub) will work correctly if a sink uses `Use the server certificate` option and its certificate has only 'TLS Server Authentication' EKU
  src/Raven.Server/Web/System/TcpConnectionInfoHandler.cs
  test/StressTests/Server/Replication/PullReplicationStressTests.cs
Labels: v7.1, release

#21480 RavenDB-25098 Optimize webpack build and update packages
  src/Raven.Studio/.eslintrc.js
  src/Raven.Studio/.storybook/main.ts
  src/Raven.Studio/package-lock.json
  src/Raven.Studio/package.json
  src/Raven.Studio/tsconfig.json
  src/Raven.Studio/typescript/components/common/PopoverWithHover.tsx
  src/Raven.Studio/typescript/components/common/virtualTable/columnProviders/useDocumentColumnsProvider.tsx
  src/Raven.Studio/typescript/components/hooks/useAsyncDebounce.ts
  src/Raven.Studio/typescript/components/pages/resources/manageServer/certificates/partials/authEnabled/CertificatesCloneModal.tsx
  src/Raven.Studio/typescript/components/pages/resources/manageServer/certificates/partials/authEnabled/CertificatesGenerateModal.tsx
  src/Raven.Studio/typescript/test/storybookTestUtils.tsx
  src/Raven.Studio/webpack.config.js
Labels: Studio, v6.2

#21485 merge release/v7.0 to v7.0
  src/Raven.Server/Web/System/TcpConnectionInfoHandler.cs
  src/Raven.Studio/wwwroot/App/views/database/documents/editDocument.html
  test/StressTests/Server/Replication/PullReplicationStressTests.cs
Labels: v7.0

#21490 RavenDB-25113 Removes wrong assertions.
  src/Voron/Data/CompactTrees/CompactTree.cs
Labels: v7.0, release

#21492 RavenDB-25098 [v7.0] Optimize webpack build and update packages
  src/Raven.Studio/.eslintrc.js
  src/Raven.Studio/.storybook/main.ts
  src/Raven.Studio/package-lock.json
  src/Raven.Studio/package.json
  src/Raven.Studio/tsconfig.json
  src/Raven.Studio/typescript/components/common/PopoverWithHover.tsx
  src/Raven.Studio/typescript/components/common/virtualTable/columnProviders/useDocumentColumnsProvider.tsx
  src/Raven.Studio/typescript/components/hooks/useAsyncDebounce.ts
  src/Raven.Studio/typescript/components/pages/resources/manageServer/certificates/partials/authEnabled/CertificatesCloneModal.tsx
  src/Raven.Studio/typescript/components/pages/resources/manageServer/certificates/partials/authEnabled/CertificatesGenerateModal.tsx
  src/Raven.Studio/typescript/test/storybookTestUtils.tsx
  src/Raven.Studio/webpack.config.js
Labels: Studio, v7.0

#21500 7.0 to 7.1 merge
  bench/Voron.Benchmark/MultiTree/MultiTreeInsertion.cs
  bench/Voron.Benchmark/StorageBenchmark.cs
  src/Raven.Server/Commercial/LicenseManager.cs
  src/Raven.Server/Documents/Handlers/DocumentHandler.cs
  src/Raven.Server/Documents/Handlers/Processors/Documents/AbstractDocumentHandlerProcessorForGet.cs
  src/Raven.Server/Documents/Indexes/IndexStorage.cs
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxIndexReadOperation.cs
  src/Raven.Server/Documents/Indexes/ReferenceContainer.cs
  src/Raven.Server/Documents/Indexes/Static/CurrentIndexingScope.cs
  src/Raven.Server/Documents/Sharding/Handlers/ShardedDocumentHandler.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesRollups.cs
  src/Raven.Server/Monitoring/OpenTelemetry/MetricsManager.cs
  src/Raven.Server/RavenServer.cs
  src/Raven.Server/Utils/DisposableBorrow.cs
  src/Raven.Studio/.eslintrc.js
  src/Raven.Studio/.storybook/main.ts
  src/Raven.Studio/package-lock.json
  src/Raven.Studio/package.json
  src/Raven.Studio/tsconfig.json
  src/Raven.Studio/typescript/components/common/PopoverWithHover.tsx
  src/Raven.Studio/typescript/components/common/virtualTable/columnProviders/useDocumentColumnsProvider.tsx
  src/Raven.Studio/typescript/components/hooks/useAsyncDebounce.ts
  src/Raven.Studio/typescript/components/pages/resources/manageServer/certificates/partials/authEnabled/CertificatesCloneModal.tsx
  src/Raven.Studio/typescript/components/pages/resources/manageServer/certificates/partials/authEnabled/CertificatesGenerateModal.tsx
  src/Raven.Studio/typescript/test/storybookTestUtils.tsx
  src/Raven.Studio/webpack.config.js
  src/Voron/Data/BTrees/Tree.Extensions.cs
  src/Voron/Data/BTrees/Tree.MultiTree.cs
  src/Voron/Data/BTrees/Tree.cs
  test/FastTests/Voron/MultiValueTree.cs
  test/SlowTests.Issues/Data/RavenDB_25033/RavenDB_25033_RDBC_128.txt
  test/SlowTests.Issues/Issues/RavenDB-24649.cs
  test/SlowTests.Issues/Issues/RavenDB-25033.cs
  test/SlowTests.Issues/SlowTests.Issues.csproj
  test/SlowTests/Client/TimeSeries/Issues/RavenDB_25101.cs
  test/SlowTests/Server/Documents/AI/Embeddings/RavenDB_25000.cs
  test/SlowTests/Voron/Compaction/StorageCompactionTestsSlow.cs
Labels: v7.1

#21495 merge release/7.0 to v7.0
  src/CommonAssemblyInfo.cs
  src/Raven.Client/Properties/VersionInfo.cs
  src/Voron/Data/CompactTrees/CompactTree.cs
Labels: v7.0

#21496 merge release/v7.1 to v7.1
  src/CommonAssemblyInfo.cs
  src/Raven.Client/Properties/VersionInfo.cs
  src/Voron/Data/CompactTrees/CompactTree.cs
Labels: v7.1
