Repository ravendb/ravendb, pull requests merged in 2025-08, with the labels that each got.

#21091 Revert "RavenDB-23966: Changes in macOS storage and memory calc"
  build.ps1
  libs/librvnpal/librvnpal.linux.arm.32.so
  libs/librvnpal/librvnpal.linux.arm.64.so
  libs/librvnpal/librvnpal.linux.x64.so
  libs/librvnpal/librvnpal.mac.arm64.dylib
  libs/librvnpal/librvnpal.mac.x64.dylib
  libs/librvnpal/librvnpal.win.x64.dll
  libs/librvnpal/librvnpal.win.x86.dll
  libs/librvnpal/librvnpal.win7.x64.dll
  libs/librvnpal/librvnpal.win7.x86.dll
  src/Raven.Pal/README.txt
  src/Raven.Pal/inc/rvn.h
  src/Raven.Pal/pal.ver
  src/Raven.Pal/src/posix/getsysteminformation.c
  src/Raven.Pal/src/rvngetpalver.c
  src/Sparrow.Server/LowMemory/MemoryInformation.cs
  src/Sparrow.Server/Platform/Pal.cs
  src/Sparrow.Server/Platform/Posix/macOS/macSyscall.cs
  src/Sparrow.Server/Platform/Posix/macOS/vm_statistics64.cs
Labels: v6.2

#21083 RavenDB 24611 - added tests for AI Agent
  test/SlowTests/Issues/RavenDB-24611.cs
Labels: ai-agent

#21100 RavenDB-24809 Fixing logging for CertificateExecTimeout if an executable won't exit in a given timeout
  src/Raven.Server/ServerWide/SecretProtection.cs
Labels: v6.2

#21108 RavenDB-24586 Added timeout to MRE in RavenDB_23473.CanUpdateNoExplicitlyConfiguredVectorFieldViaSubscriptionWithLoadDocument test
  test/SlowTests/Issues/RavenDB-23473.cs
Labels: v7.0

#21113 7.0 to 7.1 merge
  src/Raven.Server/NotificationCenter/Handlers/DatabaseNotificationCenterHandler.cs
  src/Raven.Server/ServerWide/SecretProtection.cs
  test/SlowTests/Authentication/AuthenticationDebugPackageInfoTests.cs
  test/SlowTests/Issues/RavenDB-23473.cs
Labels: v7.1

#21118 RavenDB-24798 fix change vector logic
  src/Raven.Server/Documents/Handlers/AI/Agents/AbstractAiAgentProcessor.cs
  src/Raven.Server/Web/RequestHandler.cs
  src/Raven.Studio/typescript/commands/database/aiAgents/runAiAgentCommand.ts
  src/Raven.Studio/typescript/components/pages/database/aiHub/aiAgents/chat/store/chatAiAgentSlice.ts
Labels: ai-agent

#21120 merge 7.1 to feature/ai-agent
  src/Raven.Server/NotificationCenter/Handlers/DatabaseNotificationCenterHandler.cs
  src/Raven.Server/ServerWide/SecretProtection.cs
  src/Raven.Studio/typescript/components/common/sampleObjectAndSchemaFields/SampleObjectAndSchemaFields.scss
  src/Raven.Studio/typescript/components/pages/database/aiHub/aiAgents/edit/EditAiAgent.scss
  src/Raven.Studio/wwwroot/Content/scss/_bs5extend.scss
  test/SlowTests/Authentication/AuthenticationDebugPackageInfoTests.cs
  test/SlowTests/Issues/RavenDB-23473.cs
Labels: ai-agent

#21101 RavenDB-24791 - ai-agent parameters of primitive types
  test/SlowTests/Server/Documents/AI/AiAgent/RavenDB-24791.cs
Labels: v7.1, ai-agent

#21123 RavenDB-24085 fixed audit log entry
  src/Raven.Server/Documents/Handlers/Processors/Queries/AbstractDatabaseOperationQueriesHandlerProcessor.cs
Labels: v6.2

#21110 RavenDB-24365 Data Archival Settings view: Fix link to docs
  src/Raven.Studio/typescript/components/pages/database/settings/dataArchival/DataArchival.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/documentExpiration/DocumentExpiration.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/documentRefresh/DocumentRefresh.tsx
Labels: Studio, v6.2

#21133 RavenDB-23876 fixed warnings
  src/Sparrow/Json/BlittableWriter.cs
Labels: v8.0

#21143 RavenDB-24678 - Use retired config destinations, use identifier in retired attachment, handle update of retireat & identifier
  src/Raven.Client/Documents/Attachments/RetiredAttachmentsConfiguration.cs
  src/Raven.Client/Documents/Attachments/RetiredAttachmentsDestinationConfiguration.cs
  src/Raven.Server/Documents/Attachments/RetireAttachmentExtensions.cs
  src/Raven.Server/Documents/AttachmentsStorage.cs
  src/Raven.Server/Documents/ETL/Providers/Raven/RavenEtlDocumentTransformer.cs
  src/Raven.Server/Documents/Handlers/Processors/Attachments/AttachmentHandlerProcessorForBulkPostAttachment.cs
  src/Raven.Server/Documents/Handlers/Processors/Attachments/Strategies/AbstractBulkPostAttachmentStrategyProcessor.cs
  src/Raven.Server/Documents/Handlers/Processors/Attachments/Strategies/IBulkPostAttachmentStrategy.cs
  src/Raven.Server/Documents/Handlers/Processors/Attachments/Strategies/RegularBulkPostAttachmentStrategyProcessor.cs
  src/Raven.Server/Documents/Handlers/Processors/Attachments/Strategies/RetiredBulkPostAttachmentStrategyProcessor.cs
  src/Raven.Server/Documents/Handlers/Processors/Attachments/Strategies/RetiredGetAttachmentStrategyProcessor.cs
  src/Raven.Server/Documents/Replication/DocumentInfoHelper.cs
  src/Raven.Server/Documents/Replication/Senders/ReplicationDocumentSenderBase.cs
  src/Raven.Server/Documents/RetireAttachmentsSender.cs
  src/Raven.Server/Documents/RetiredAttachmentsStorage.cs
  src/Sparrow.Server/ByteString.cs
  test/SlowTests/Server/Documents/Attachments/AzureRetiredAttachmentsSlowTests.cs
  test/SlowTests/Server/Documents/Attachments/DocumentSessionRetiredAttachmentsAsyncTests.cs
  test/SlowTests/Server/Documents/Attachments/RetiredAttachmentsHolder.cs
  test/SlowTests/Server/Documents/Attachments/S3RetiredAttachmentsSlowTests.cs
  test/Tests.Infrastructure/AmazonS3RetryTheoryAttribute.cs
  test/Tests.Infrastructure/AzureRetryTheoryAttribute.cs
Labels: remote-attachments

#21148 6.2 to 7.0 merge
  build.ps1
  libs/librvnpal/librvnpal.arm.32.so
  libs/librvnpal/librvnpal.arm.64.so
  libs/librvnpal/librvnpal.linux.x64.so
  libs/librvnpal/librvnpal.mac.arm64.dylib
  libs/librvnpal/librvnpal.mac.x64.dylib
  libs/librvnpal/librvnpal.win.x64.dll
  libs/librvnpal/librvnpal.win.x86.dll
  libs/librvnpal/librvnpal.win7.x64.dll
  libs/librvnpal/librvnpal.win7.x86.dll
  src/Raven.Pal/README.txt
  src/Raven.Pal/inc/rvn.h
  src/Raven.Pal/pal.ver
  src/Raven.Pal/src/posix/getsysteminformation.c
  src/Raven.Pal/src/rvngetpalver.c
  src/Raven.Server/Documents/Handlers/DocumentHandler.cs
  src/Raven.Server/Documents/Handlers/Processors/Documents/AbstractDocumentHandlerProcessorForDelete.cs
  src/Raven.Server/Documents/Handlers/Processors/Documents/AbstractDocumentHandlerProcessorForGet.cs
  src/Raven.Server/Documents/Handlers/Processors/Documents/DocumentHandlerProcessorForGet.cs
  src/Raven.Server/Documents/Handlers/Processors/Queries/AbstractDatabaseOperationQueriesHandlerProcessor.cs
  src/Raven.Server/Documents/Handlers/Processors/TimeSeries/AbstractTimeSeriesHandlerProcessor.cs
  src/Raven.Server/Documents/Handlers/Processors/TimeSeries/AbstractTimeSeriesHandlerProcessorForGetTimeSeriesRanges.cs
  src/Raven.Server/Documents/Includes/IncludeCountersCommand.cs
  src/Raven.Server/Documents/Includes/IncludeRevisionsCommand.cs
  src/Raven.Server/Documents/Includes/IncludeTimeSeriesCommand.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Documents/ShardedDocumentHandlerProcessorForGet.cs
  src/Raven.Server/Documents/Sharding/Handlers/ShardedDocumentHandler.cs
  src/Raven.Server/Json/BlittableJsonTextWriterExtensions.cs
  src/Raven.Server/Web/AbstractQueryStringParameters.cs
  src/Raven.Studio/typescript/components/pages/database/settings/dataArchival/DataArchival.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/documentExpiration/DocumentExpiration.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/documentRefresh/DocumentRefresh.tsx
  src/Sparrow.Server/LowMemory/MemoryInformation.cs
  src/Sparrow.Server/Platform/Pal.cs
  src/Sparrow.Server/Platform/Posix/macOS/macSyscall.cs
  src/Sparrow.Server/Platform/Posix/macOS/vm_statistics64.cs
  src/Sparrow/Json/AsyncBlittableJsonTextWriter.cs
  src/Sparrow/Json/BlittableJsonTextWriterExtensions.cs
  src/Sparrow/Json/JsonOperationContext.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  test/SlowTests/Voron/Issues/RavenDB_24629.cs
Labels: v7.0

#21150 7.0 to 7.1 merge
  build.ps1
  libs/librvnpal/librvnpal.arm.32.so
  libs/librvnpal/librvnpal.arm.64.so
  libs/librvnpal/librvnpal.linux.x64.so
  libs/librvnpal/librvnpal.mac.arm64.dylib
  libs/librvnpal/librvnpal.mac.x64.dylib
  libs/librvnpal/librvnpal.win.x64.dll
  libs/librvnpal/librvnpal.win.x86.dll
  libs/librvnpal/librvnpal.win7.x64.dll
  libs/librvnpal/librvnpal.win7.x86.dll
  src/Raven.Pal/README.txt
  src/Raven.Pal/inc/rvn.h
  src/Raven.Pal/pal.ver
  src/Raven.Pal/src/posix/getsysteminformation.c
  src/Raven.Pal/src/rvngetpalver.c
  src/Raven.Server/Documents/Handlers/DocumentHandler.cs
  src/Raven.Server/Documents/Handlers/Processors/Documents/AbstractDocumentHandlerProcessorForDelete.cs
  src/Raven.Server/Documents/Handlers/Processors/Documents/AbstractDocumentHandlerProcessorForGet.cs
  src/Raven.Server/Documents/Handlers/Processors/Documents/DocumentHandlerProcessorForGet.cs
  src/Raven.Server/Documents/Handlers/Processors/Queries/AbstractDatabaseOperationQueriesHandlerProcessor.cs
  src/Raven.Server/Documents/Handlers/Processors/TimeSeries/AbstractTimeSeriesHandlerProcessor.cs
  src/Raven.Server/Documents/Handlers/Processors/TimeSeries/AbstractTimeSeriesHandlerProcessorForGetTimeSeriesRanges.cs
  src/Raven.Server/Documents/Includes/IncludeCountersCommand.cs
  src/Raven.Server/Documents/Includes/IncludeRevisionsCommand.cs
  src/Raven.Server/Documents/Includes/IncludeTimeSeriesCommand.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Documents/ShardedDocumentHandlerProcessorForGet.cs
  src/Raven.Server/Documents/Sharding/Handlers/ShardedDocumentHandler.cs
  src/Raven.Server/Json/BlittableJsonTextWriterExtensions.cs
  src/Raven.Server/Web/AbstractQueryStringParameters.cs
  src/Raven.Studio/typescript/components/pages/database/settings/dataArchival/DataArchival.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/documentExpiration/DocumentExpiration.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/documentRefresh/DocumentRefresh.tsx
  src/Sparrow.Server/LowMemory/MemoryInformation.cs
  src/Sparrow.Server/Platform/Pal.cs
  src/Sparrow.Server/Platform/Posix/macOS/macSyscall.cs
  src/Sparrow.Server/Platform/Posix/macOS/vm_statistics64.cs
  src/Sparrow/Json/AsyncBlittableJsonTextWriter.cs
  src/Sparrow/Json/BlittableJsonTextWriterExtensions.cs
  src/Sparrow/Json/JsonOperationContext.cs
  src/Voron/Impl/Journal/WriteAheadJournal.cs
  test/SlowTests/Voron/Issues/RavenDB_24629.cs
Labels: v7.1

#21156 RavenDB-24767 - Increase the MaxStatements in TryCompileScript for ValidateSmugglerOptions
  src/Raven.Server/Documents/Patch/ScriptRunner.cs
  test/FastTests/Issues/RavenDB_24767.cs
Labels: v7.0

#21158 CSV-5225 npm update form-data
  src/Raven.Studio/package-lock.json
Labels: Studio, v6.2

#21166 RavenDB-24620 Allow generating embeddings via embeddings generation task for vectors indexed via CreateVector.
  src/Raven.Client/Constants.cs
  src/Raven.Client/Documents/Queries/Vector/VectorFieldFactory.cs
  src/Raven.Client/Documents/Session/AbstractDocumentQuery.cs
  src/Raven.Client/Documents/Session/Tokens/VectorSearchToken.cs
  src/Raven.Server/Documents/Indexes/IndexField.cs
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxQueryBuilder.VectorSearch.cs
  test/SlowTests/Issues/RavenDB-22076.cs
  test/SlowTests/Server/Documents/AI/Embeddings/RavenDB-24620.cs
Labels: v7.1

#21193 RavenDB-23942 GenAiData tests with Ollama should check connection
  test/SlowTests/Server/Documents/AI/AiAgent/RavenDB-24611.cs
  test/SlowTests/Server/Documents/AI/GenAi/GenAiBasics.cs
  test/SlowTests/Server/Documents/AI/GenAi/GenAiErrorHandling.cs
  test/SlowTests/Server/Documents/AI/GenAi/GenAiStats.cs
  test/SlowTests/Server/Documents/AI/GenAi/GenAiTestScript.cs
  test/SlowTests/Server/Documents/AI/GenAi/Issues/RavenDB_24298.cs
  test/Tests.Infrastructure/ConnectionString/AI/BaseAiConnectionStringForTesting.cs
Labels: v7.1

#21196 RavenDB-24645 : Changing CheckCanConnect to true on issues 24644 and 24645
  test/SlowTests/Server/Documents/AI/GenAi/Issues/RavenDB-24644.cs
  test/SlowTests/Server/Documents/AI/GenAi/Issues/RavenDB-24645.cs
Labels: genai-attachments

#21197 RavenDB-24074 Replaced WaitAll with WhenAll in EmbeddingsGenerator.DoWork()
  src/Raven.Server/Documents/AI/Embeddings/EmbeddingsGenerator.cs
Labels: v7.0

#21208 HRINT-4187 adjust Ollama uri for embeddings
  test/Tests.Infrastructure/ConnectionString/AI/OllamaConnectorForTesting.cs
Labels: v7.0

#21213 release/v6.2 to 6.2 merge
  src/CommonAssemblyInfo.cs
  src/Raven.Client/Properties/VersionInfo.cs
  src/Raven.Studio/typescript/components/common/clientConfiguration/ClientConfigurationUtils.ts
  src/Raven.Studio/typescript/components/common/clientConfiguration/useClientConfigurationFormSideEffects.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/clientConfiguration/ClientDatabaseConfiguration.tsx
  src/Raven.Studio/typescript/components/pages/resources/manageServer/clientConfiguration/ClientGlobalConfiguration.tsx
  src/Raven.Studio/wwwroot/Content/css/pages/documents-edit.less
Labels: v6.2

#21214 release/v7.0 to 7.0 merge
  src/CommonAssemblyInfo.cs
  src/Raven.Client/Properties/VersionInfo.cs
  src/Raven.Studio/typescript/components/common/clientConfiguration/ClientConfigurationUtils.ts
  src/Raven.Studio/typescript/components/common/clientConfiguration/useClientConfigurationFormSideEffects.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/clientConfiguration/ClientDatabaseConfiguration.tsx
  src/Raven.Studio/typescript/components/pages/resources/manageServer/clientConfiguration/ClientGlobalConfiguration.tsx
  src/Raven.Studio/wwwroot/Content/css/pages/documents-edit.less
Labels: v7.0

#21215 release/v7.1 to 7.1 merge
  src/CommonAssemblyInfo.cs
  src/Raven.Client/Properties/VersionInfo.cs
  src/Raven.Studio/typescript/components/common/clientConfiguration/ClientConfigurationUtils.ts
  src/Raven.Studio/typescript/components/common/clientConfiguration/useClientConfigurationFormSideEffects.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/clientConfiguration/ClientDatabaseConfiguration.tsx
  src/Raven.Studio/typescript/components/pages/resources/manageServer/clientConfiguration/ClientGlobalConfiguration.tsx
  src/Raven.Studio/wwwroot/Content/css/pages/documents-edit.less
Labels: v7.1

#21217 6.2 to 7.0 merge
  src/Raven.Server/Config/Categories/ClusterConfiguration.cs
  src/Raven.Server/Documents/Handlers/SingleDatabaseAdminHandler.cs
  src/Raven.Server/Documents/Sharding/Handlers/ShardedSingleDatabaseAdminHandler.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterMaintenanceWorker.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterNodeStatusReport.cs
  src/Raven.Server/Web/Studio/Processors/AbstractDatabaseTasksHandlerProcessorForRestartDatabase.cs
  src/Raven.Server/Web/Studio/Processors/DatabaseTasksHandlerProcessorForRestartDatabase.cs
  src/Raven.Server/Web/Studio/Sharding/Processors/ShardedDatabaseTasksHandlerProcessorForRestartDatabase.cs
  src/Raven.Server/Web/Studio/Sharding/ShardedStudioDatabaseTasksHandler.cs
  src/Raven.Server/Web/Studio/StudioDatabaseTasksHandler.cs
  src/Raven.Studio/typescript/viewmodels/database/tasks/editPeriodicBackupTask.ts
  test/SlowTests/Server/Documents/PeriodicBackup/ClusterBackupTests.cs
Labels: v7.0

#21219 merge 7.1 to feature/genai-attachments
  Directory.Packages.props
  src/CommonAssemblyInfo.cs
  src/Raven.Client/Documents/AI/AiConversation.cs
  src/Raven.Client/Documents/AI/IAiConversationOperations.cs
  src/Raven.Client/Documents/Conventions/DocumentConventions.cs
  src/Raven.Client/Documents/Indexes/ExpressionStringBuilder.cs
  src/Raven.Client/Properties/VersionInfo.cs
  src/Raven.Server/Config/Categories/ClusterConfiguration.cs
  src/Raven.Server/Documents/AI/Embeddings/EmbeddingsGenerator.cs
  src/Raven.Server/Documents/Handlers/SingleDatabaseAdminHandler.cs
  src/Raven.Server/Documents/Sharding/Handlers/ShardedSingleDatabaseAdminHandler.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterMaintenanceWorker.cs
  src/Raven.Server/ServerWide/Maintenance/ClusterNodeStatusReport.cs
  src/Raven.Server/Web/Studio/Processors/AbstractDatabaseTasksHandlerProcessorForRestartDatabase.cs
  src/Raven.Server/Web/Studio/Processors/DatabaseTasksHandlerProcessorForRestartDatabase.cs
  src/Raven.Server/Web/Studio/Sharding/Processors/ShardedDatabaseTasksHandlerProcessorForRestartDatabase.cs
  src/Raven.Server/Web/Studio/Sharding/ShardedStudioDatabaseTasksHandler.cs
  src/Raven.Server/Web/Studio/StudioDatabaseTasksHandler.cs
  src/Raven.Studio/typescript/components/common/clientConfiguration/ClientConfigurationUtils.ts
  src/Raven.Studio/typescript/components/common/clientConfiguration/useClientConfigurationFormSideEffects.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/clientConfiguration/ClientDatabaseConfiguration.tsx
  src/Raven.Studio/typescript/components/pages/resources/manageServer/clientConfiguration/ClientGlobalConfiguration.tsx
  src/Raven.Studio/typescript/viewmodels/database/tasks/editPeriodicBackupTask.ts
  src/Raven.Studio/wwwroot/Content/css/pages/documents-edit.less
  test/SlowTests/Client/Indexing/Issues/RavenDB-24858.cs
  test/SlowTests/Server/Documents/AI/AiAgent/AiAgentClientApiHandleActionCalls.cs
  test/SlowTests/Server/Documents/AI/AiAgent/RavenDB-24611.cs
  test/SlowTests/Server/Documents/AI/AiAgent/RavenDB-24883.cs
  test/SlowTests/Server/Documents/AI/GenAi/GenAiBasics.cs
  test/SlowTests/Server/Documents/AI/GenAi/GenAiErrorHandling.cs
  test/SlowTests/Server/Documents/AI/GenAi/GenAiStats.cs
  test/SlowTests/Server/Documents/AI/GenAi/GenAiTestScript.cs
  test/SlowTests/Server/Documents/AI/GenAi/Issues/RavenDB_24298.cs
  test/SlowTests/Server/Documents/PeriodicBackup/ClusterBackupTests.cs
  test/Tests.Infrastructure/ConnectionString/AI/BaseAiConnectionStringForTesting.cs
  test/Tests.Infrastructure/ConnectionString/AI/OllamaConnectorForTesting.cs
Labels: genai-attachments

#21227 RavenDB-24790 AI Agent: Show only the chat model type when creating a connection string from inside the agent definition
  src/Raven.Studio/typescript/components/pages/database/aiHub/aiAgents/edit/hooks/useEditAiAgent.ts
  src/Raven.Studio/typescript/components/pages/database/settings/connectionStrings/editForms/aiFields/ModelTypeField.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/connectionStrings/store/connectionStringsSlice.ts
  src/Raven.Studio/typescript/components/pages/database/tasks/ongoingTasks/editTasks/editGenAiTask/EditGenAiTask.tsx
  src/Raven.Studio/typescript/viewmodels/database/tasks/editEmbeddingsGenerationTask.ts
Labels: Studio, v7.1

#21207 RavenDB-24898 Adjust Rider team-shared settings
  .editorconfig
Labels: v5.4

#21230 RavenDB-24781 AI Agent: Clear agent params when starting a new chat session
  src/Raven.Studio/typescript/components/pages/database/aiHub/aiAgents/chat/ChatAiAgent.tsx
Labels: Studio, v7.1

#21242 RavenDB-24803 Disable Corax's Voron tests.
  test/SlowTests/Voron/CompactTrees/CompactTreeSlowTests.cs
  test/SlowTests/Voron/CompactTrees/FuzzyUpserts.cs
Labels: v5.4

#21240 RavenDB-24835 - return Skip message in implementations of RetryTheoryAttribute
  test/Tests.Infrastructure/AmazonGlacierRetryTheoryAttribute.cs
  test/Tests.Infrastructure/AmazonS3RetryTheoryAttribute.cs
  test/Tests.Infrastructure/AzureRetryTheoryAttribute.cs
  test/Tests.Infrastructure/CloudAttributeHelper.cs
  test/Tests.Infrastructure/CustomS3RetryTheoryAttribute.cs
  test/Tests.Infrastructure/RequiresMsSqlRetryTheoryAttribute.cs
Labels: v5.4

#21245 6.2 to 7.0 merge
  .editorconfig
  src/Corax/Indexing/IndexWriter.Debug.cs
  src/Corax/Indexing/IndexWriter.EntriesToTermsTracker.cs
  src/Corax/Indexing/IndexWriter.Exceptions.cs
  src/Corax/Indexing/IndexWriter.FieldBuffers.cs
  src/Corax/Indexing/IndexWriter.NumericalFieldInserter.cs
  src/Corax/Indexing/IndexWriter.TextualFieldInserter.cs
  src/Corax/Indexing/IndexWriter.cs
  test/SlowTests/Voron/CompactTrees/FuzzyUpserts.cs
  test/Tests.Infrastructure/AmazonGlacierRetryTheoryAttribute.cs
  test/Tests.Infrastructure/AmazonS3RetryTheoryAttribute.cs
  test/Tests.Infrastructure/AzureRetryTheoryAttribute.cs
  test/Tests.Infrastructure/CloudAttributeHelper.cs
  test/Tests.Infrastructure/CustomS3RetryTheoryAttribute.cs
  test/Tests.Infrastructure/RequiresMsSqlRetryTheoryAttribute.cs
Labels: v7.0

#21246 7.0 to 7.1 merge
  .editorconfig
  src/Corax/Indexing/IndexWriter.Debug.cs
  src/Corax/Indexing/IndexWriter.EntriesToTermsTracker.cs
  src/Corax/Indexing/IndexWriter.Exceptions.cs
  src/Corax/Indexing/IndexWriter.FieldBuffers.cs
  src/Corax/Indexing/IndexWriter.NumericalFieldInserter.cs
  src/Corax/Indexing/IndexWriter.TextualFieldInserter.cs
  src/Corax/Indexing/IndexWriter.cs
  test/SlowTests/Voron/CompactTrees/FuzzyUpserts.cs
  test/Tests.Infrastructure/AmazonGlacierRetryTheoryAttribute.cs
  test/Tests.Infrastructure/AmazonS3RetryTheoryAttribute.cs
  test/Tests.Infrastructure/AzureRetryTheoryAttribute.cs
  test/Tests.Infrastructure/CloudAttributeHelper.cs
  test/Tests.Infrastructure/CustomS3RetryTheoryAttribute.cs
  test/Tests.Infrastructure/RequiresMsSqlRetryTheoryAttribute.cs
Labels: v7.1

#21226 RavenDB-14341 updated XML documentation for the Subscriptions related public API
  src/Raven.Client/Documents/Subscriptions/CreateSubscriptionResult.cs
  src/Raven.Client/Documents/Subscriptions/DocumentSubscriptions.cs
  src/Raven.Client/Documents/Subscriptions/GetSubscriptionsResult.cs
  src/Raven.Client/Documents/Subscriptions/SubscriptionBatch.cs
  src/Raven.Client/Documents/Subscriptions/SubscriptionBatchBase.cs
  src/Raven.Client/Documents/Subscriptions/SubscriptionCriteria.cs
  src/Raven.Client/Documents/Subscriptions/SubscriptionMode.cs
  src/Raven.Client/Documents/Subscriptions/SubscriptionOpeningStrategy.cs
  src/Raven.Client/Documents/Subscriptions/SubscriptionShardingState.cs
  src/Raven.Client/Documents/Subscriptions/SubscriptionState.cs
  src/Raven.Client/Documents/Subscriptions/SubscriptionWorker.cs
  src/Raven.Client/Documents/Subscriptions/SubscriptionWorkerOptions.cs
Labels: v7.1

#21260 RavenDB-24872 switched test from Ollama to OpenAI
  test/SlowTests/Server/Documents/AI/AiAgent/RavenDB-24611.cs
Labels: v7.1

#21270 RavenDB-24880, RavenDB-24881 - Handling the situation when the database goes idle and there are no backups for a specific backup Task ID yet
  src/Raven.Server/Utils/BackupUtils.cs
Labels: v6.2
