Repository ravendb/ravendb, pull requests merged in 2025-05, with the labels that each got.

#20553 RavenDB-24135 Auto-index view: Label should be "Index Fields"
  src/Raven.Studio/wwwroot/App/views/database/indexes/editIndex.html
Labels: Studio, v7.0

#20559 RavenDB-23710 Fix index fields display in fields studio view for auto indexes
  src/Raven.Server/Documents/Indexes/Auto/AutoMapIndex.cs
  test/SlowTests/Issues/RavenDB-23710.cs
Labels: v6.2

#20472 RavenDB-23260 Lookup optimizations
  src/Voron/Data/Lookups/Lookup.Iterator.cs
  src/Voron/Data/Lookups/Lookup.cs
  test/FastTests/Corax/CoraxProjections.cs
Labels: Corax, v6.2

#20562 5.4 to 6.2 merge
  src/Raven.Server/Documents/DocumentPutAction.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
  src/Voron/Data/Tables/NewPageAllocator.cs
  test/SlowTests/SparrowTests/LoggingSourceTests.cs
Labels: v6.2

#20560 RavenDB-21083 - Enable support for multi-part uploads up to 5TB
  src/Raven.Server/Documents/PeriodicBackup/Aws/RavenAwsS3Client.cs
Labels: v5.4

#20548 RavenDB-24131 fix `/databases/*/admin/debug/cluster/txinfo`
  src/Raven.Server/Documents/Handlers/Debugging/TransactionDebugHandler.cs
  src/Raven.Server/ServerWide/Commands/ClusterTransactionCommand.cs
  test/SlowTests/Cluster/ClusterTransactionTests.cs
Labels: v5.4

#20567 RavenDB-24106 - fix XML warnings on compilation
  src/Raven.Client/Documents/Operations/Attachments/GetAttachmentsOperation.cs
  src/Raven.Client/Documents/Operations/CompareExchange/DeleteCompareExchangeValueOperation.cs
  src/Raven.Client/Documents/Operations/CompareExchange/GetCompareExchangeValueOperation.cs
  src/Raven.Client/Documents/Operations/DeleteByQueryOperation.cs
  src/Raven.Client/Documents/Operations/Revisions/GetRevisionsOperation.cs
  src/Raven.Client/Documents/Operations/TimeSeries/GetTimeSeriesOperation.cs
Labels: v6.2

#20566 RavenDB-24133 Fix the attachment key data extraction
  src/Raven.Server/Documents/AttachmentsStorage.Sharding.cs
  src/Raven.Server/Documents/AttachmentsStorage.cs
  src/Raven.Server/Documents/ETL/Providers/Raven/Enumerators/AttachmentTombstonesToRavenEtlItems.cs
  src/Raven.Server/Documents/ETL/Providers/Raven/RavenEtlDocumentTransformer.cs
  src/Raven.Server/Documents/Replication/DocumentInfoHelper.cs
  src/Raven.Server/Documents/Replication/Incoming/IncomingReplicationHandler.cs
  src/Raven.Server/Documents/Replication/Senders/ReplicationDocumentSenderBase.cs
  src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
Labels: v6.2

#20565 RavenDB-23896: Update audit log message for one-time backup execution
  src/Raven.Server/Web/System/OngoingTasksHandler.cs
Labels: v5.4

#20561 RavenDB-22533 Added TCP open connection to audit log
  src/Raven.Server/RavenServer.cs
Labels: v5.4

#20569 5.4 to 6.2 merge
  src/Raven.Server/Documents/DocumentPutAction.cs
  src/Raven.Server/Documents/Handlers/Processors/OngoingTasks/AbstractOngoingTasksHandlerProcessorForBackupDatabaseOnce.cs
  src/Raven.Server/Documents/PeriodicBackup/Aws/RavenAwsS3Client.cs
  src/Raven.Server/RavenServer.cs
  src/Raven.Server/ServerWide/Commands/ClusterTransactionCommand.cs
  test/SlowTests/Cluster/ClusterTransactionTests.cs
  tools/Raven.Debug/CommandLineApp.cs
  tools/Raven.Debug/LogTrafficWatch/LogTrafficWatch.cs
Labels: v6.2

#20572 RavenDB-24134 Enhance the replication debug endpoint functionality
  src/Raven.Server/Documents/Handlers/ReplicationHandler.cs
  src/Raven.Server/Documents/Replication/ReplicationItems/DocumentReplicationItem.cs
Labels: v6.2

#20571 RavenDB-23811 - Revert how we calculate the AdditionalMemoryUsageSize
  src/Voron/Impl/LowLevelTransaction.cs
Labels: v5.4

#20578 RavenDB-23088 Added `WaitForNonStaleResults` for TimeSeries LINQ tests.
  test/SlowTests/Client/TimeSeries/Query/TimeSeriesLinqQuery.cs
Labels: v6.2

#20576 RavenDB-23260 Lookup optimizations - v7.0 port.
  src/Voron/Data/Lookups/Lookup.Iterator.cs
Labels: v7.0

#20579 RavenDB-24178 Vector search: Fix XML comments
  src/Raven.Client/Documents/LinqExtensions.cs
  src/Raven.Client/Documents/Queries/Vector/VectorFieldFactory.cs
Labels: v7.0

#20584 RavenDB-22270 Add Audit Logging for Memory Dump Endpoints
  src/Raven.Server/Web/System/AdminDumpHandler.cs
Labels: v5.4

#20582 RavenDB-22274 Audit log on license related operations
  src/Raven.Server/Web/Studio/LicenseHandler.cs
Labels: v5.4

#20586 5.4 to 6.2 merge
  scripts/linux/pkg/deb/build-deb.ps1
  scripts/linux/pkg/deb/build-deb.sh
  scripts/linux/pkg/deb/build-deb_ubuntu-noble_arm64.ps1
  scripts/linux/pkg/deb/set-raven-platform-arm64-native.ps1
  scripts/linux/pkg/deb/set-raven-platform-arm64-native.sh
  scripts/linux/pkg/deb/set-raven-platform-armhf-native.ps1
  scripts/linux/pkg/deb/set-raven-platform-armhf-native.sh
  scripts/linux/pkg/deb/set-ubuntu-noble.sh
  scripts/linux/pkg/deb/ubuntu_native.Dockerfile
  src/Raven.Server/Web/Studio/LicenseHandler.cs
  src/Raven.Server/Web/System/AdminDumpHandler.cs
  src/Voron/Impl/LowLevelTransaction.cs
Labels: v6.2

#20587 6.2 to 7.0 merge
  scripts/linux/pkg/deb/build-deb.ps1
  scripts/linux/pkg/deb/build-deb.sh
  scripts/linux/pkg/deb/build-deb_ubuntu-noble_arm64.ps1
  scripts/linux/pkg/deb/set-raven-platform-arm64-native.ps1
  scripts/linux/pkg/deb/set-raven-platform-arm64-native.sh
  scripts/linux/pkg/deb/set-raven-platform-armhf-native.ps1
  scripts/linux/pkg/deb/set-raven-platform-armhf-native.sh
  scripts/linux/pkg/deb/set-ubuntu-noble.sh
  scripts/linux/pkg/deb/ubuntu_native.Dockerfile
  src/Raven.Server/Web/Studio/LicenseHandler.cs
  src/Raven.Server/Web/System/AdminDumpHandler.cs
  src/Voron/Impl/LowLevelTransaction.cs
  test/SlowTests/Client/TimeSeries/Query/TimeSeriesLinqQuery.cs
Labels: v7.0

#20588 7.0 to 7.1 merge
  scripts/linux/pkg/deb/build-deb.ps1
  scripts/linux/pkg/deb/build-deb.sh
  scripts/linux/pkg/deb/build-deb_ubuntu-noble_arm64.ps1
  scripts/linux/pkg/deb/set-raven-platform-arm64-native.ps1
  scripts/linux/pkg/deb/set-raven-platform-arm64-native.sh
  scripts/linux/pkg/deb/set-raven-platform-armhf-native.ps1
  scripts/linux/pkg/deb/set-raven-platform-armhf-native.sh
  scripts/linux/pkg/deb/set-ubuntu-noble.sh
  scripts/linux/pkg/deb/ubuntu_native.Dockerfile
  scripts/nuget.ps1
  src/Corax/Querying/IndexSearcher.VectorSearch.cs
  src/Raven.Client/Constants.cs
  src/Raven.Client/Documents/LinqExtensions.cs
  src/Raven.Client/Documents/Queries/Vector/VectorFieldFactory.cs
  src/Raven.Client/Documents/Session/AbstractDocumentQuery.cs
  src/Raven.Client/Documents/Session/Tokens/VectorSearchToken.cs
  src/Raven.Client/README.md
  src/Raven.Client/Raven.Client.csproj
  src/Raven.Embedded/EmbeddedServer.cs
  src/Raven.Embedded/ProcessHelper.cs
  src/Raven.Embedded/README.md
  src/Raven.Embedded/Raven.Embedded.csproj
  src/Raven.Embedded/Raven.Embedded.nuspec.template
  src/Raven.Embedded/RuntimeFrameworkVersionMatcher.cs
  src/Raven.Server/Documents/AI/Embeddings/EmbeddingsGenerator.cs
  src/Raven.Server/Documents/AI/TextChunker.cs
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxQueryBuilder.VectorSearch.cs
  src/Raven.Server/Documents/Queries/AST/JavascriptCodeQueryVisitor.cs
  src/Raven.Server/Web/Studio/LicenseHandler.cs
  src/Raven.Server/Web/System/AdminDumpHandler.cs
  src/Raven.Studio/languageService/src/providers/keywords.ts
  src/Raven.Studio/languageService/test/autocomplete/where.spec.ts
  src/Raven.TestDriver/README.md
  src/Raven.TestDriver/Raven.TestDriver.csproj
  src/Sparrow/UnmanagedPointer.cs
  src/Voron/Data/Graphs/Hnsw.Constants.cs
  src/Voron/Data/Lookups/Lookup.Iterator.cs
  test/LicenseTests/LicenseOptionsEmbeddedTests.cs
  test/SlowTests/Client/TimeSeries/Query/TimeSeriesLinqQuery.cs
  test/SlowTests/Issues/RavenDB_23792.cs
Labels: v7.1

#20591 RavenDB-24086 - skip heavy endpoints in test, move Authentication tests to stress tests
  test/SlowTests/Authentication/AuthenticationBasicTests.cs
  test/SlowTests/Tests/TestsInheritanceTests.cs
  test/StressTests/Authentication/AuthenticationStressTests.cs
Labels: v5.4

#20594 RavenDB-23953 - add cts to tests
  test/SlowTests/Authentication/AuthenticationLetsEncryptTests.cs
Labels: v6.2

#20589 RavenDB-24073 - Properly get the debug output for HNSW graph entries
  src/Voron/Data/Graphs/Hnsw.Debug.cs
Labels: v7.0

#20598 6.2 to 7.0 merge
  src/Corax/Querying/IndexSearcher.Search.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/LuceneAnalyzerAdapterForQuerying.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/LuceneAnalyzerAdapterForWriter.cs
  test/SlowTests/Authentication/AuthenticationBasicTests.cs
  test/SlowTests/Authentication/AuthenticationLetsEncryptTests.cs
  test/SlowTests/Corax/RavenDB-23649.cs
  test/SlowTests/Issues/RavenDB-23784.cs
  test/SlowTests/Issues/RavenDB_22937.cs
  test/SlowTests/Tests/TestsInheritanceTests.cs
  test/StressTests/Authentication/AuthenticationStressTests.cs
Labels: v7.0

#20595 RavenDB 24174
  test/SlowTests/Issues/RavenDB_23103.cs
Labels: v6.2

#20599 7.0 to 7.1 merge
  src/Corax/Querying/IndexSearcher.Search.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/LuceneAnalyzerAdapterForQuerying.cs
  src/Raven.Server/Documents/Indexes/Persistence/Lucene/LuceneAnalyzerAdapterForWriter.cs
  src/Voron/Data/Graphs/Hnsw.Debug.cs
  test/SlowTests/Authentication/AuthenticationBasicTests.cs
  test/SlowTests/Authentication/AuthenticationLetsEncryptTests.cs
  test/SlowTests/Corax/RavenDB-23649.cs
  test/SlowTests/Issues/RavenDB-23784.cs
  test/SlowTests/Issues/RavenDB_22937.cs
  test/SlowTests/Tests/TestsInheritanceTests.cs
  test/StressTests/Authentication/AuthenticationStressTests.cs
Labels: v7.1

#20601 RavenDB-24164 generate documentation file during the build to check for additional warnings in GH actions
  .github/workflows/compile.yml
Labels: v6.2

#20605 RavenDB-24105: Disable performance impacting logging configuration.
  src/Raven.Server/RavenServer.cs
Labels: v7.0

#20602 RavenDB-24065 fix AVE on 32-bits when we try to unmap an already closed pager
  src/Voron/Impl/Paging/Pager.32.cs
  src/Voron/Impl/Paging/Pager.StateFor32Bits.cs
Labels: v7.1

#20614 6.2 to 7.0 merge
  .github/workflows/compile.yml
  Directory.Packages.props
  src/Raven.Server/Documents/ETL/Providers/Queue/QueueBrokerConnectionHelper.cs
  src/Raven.Server/Documents/ETL/Providers/Queue/RabbitMq/RabbitMqEtl.cs
  src/Raven.Server/Documents/QueueSink/RabbitMqQueueSink.cs
  src/Raven.Server/Documents/QueueSink/RabbitMqSinkConsumer.cs
  test/SlowTests/Issues/RavenDB_23103.cs
  test/SlowTests/Server/Documents/ETL/Queue/RabbitMqEtlTestBase.cs
  test/SlowTests/Server/Documents/ETL/Queue/RabbitMqEtlTests.cs
  test/SlowTests/Server/Documents/ETL/Queue/RavenDB_21659_RabbitMq.cs
  test/SlowTests/Server/Documents/QueueSink/Issues/RavenDB_22105.cs
  test/SlowTests/Server/Documents/QueueSink/RabbitMqQueueSinkTestBase.cs
  test/SlowTests/Server/Documents/QueueSink/RabbitMqSinkTests.cs
  test/Tests.Infrastructure/ConnectionString/RabbitMqConnectionString.cs
Labels: v7.0

#20622 RavenDB-24218 bumped the date
  src/CommonAssemblyInfo.cs
Labels: v5.4

#20621 RavenDB-24218 bumped version to 8.0
  SECURITY.md
  docker/common.ps1
  docker/compose/linux-cluster/docker-compose.yml
  docker/compose/win-cluster/docker-compose.yml
  docker/debug/build-ubuntu-debug.ps1
  docker/debug/ravendb-ubuntu-debug/Dockerfile
  docker/manifest/manifest.yml
  docker/readme.md
  docker/run-linux.ps1
  docker/run-nanoserver.ps1
  docs/readme.linux.txt
  docs/readme.windows.txt
  readme.md
  scripts/certificates/powershell/dev-create-authenticated-cluster-with-subdomains.ps1
  scripts/certificates/powershell/dev-create-authenticated-cluster.ps1
  scripts/linux/pkg/deb/set-raven-version-env.ps1
  scripts/raspberry-pi/setup.sh
  scripts/raspberry-pi/start.sh
  scripts/updateSourceWithBuildInfo.ps1
  scripts/version.ps1
  src/CommonAssemblyInfo.cs
  src/Raven.Client/DocumentationUrls.cs
  src/Raven.Client/Properties/VersionInfo.cs
  src/Raven.Embedded/Raven.Embedded.nuspec.template
  src/Raven.Server/Monitoring/Snmp/Templates/zabbix_ravendb_template.xml
  src/Raven.Server/Program.cs
  src/Raven.Server/RavenServer.cs
  src/Raven.Server/ServerWide/ServerVersion.cs
  src/Raven.Server/Smuggler/Documents/Processors/BuildVersion.cs
  src/Raven.Server/Smuggler/Documents/Processors/IndexProcessor.cs
  src/Raven.Server/Smuggler/Documents/SmugglerBase.cs
  src/Raven.Server/Smuggler/Migration/MajorVersion.cs
  src/Raven.Server/Smuggler/Migration/Migrator.cs
  src/Raven.Studio/typescript/commands/commandBase.ts
  src/Raven.Studio/wwwroot/version.txt
Labels: v8.0

#20619 RavenDB-24218 bumped version to 7.1
  SECURITY.md
  docker/common.ps1
  docker/compose/linux-cluster/docker-compose.yml
  docker/compose/win-cluster/docker-compose.yml
  docker/debug/ravendb-ubuntu-debug/Dockerfile
  docker/manifest/manifest.yml
  docker/readme.md
  docker/run-linux.ps1
  docker/run-nanoserver.ps1
  docs/readme.linux.txt
  docs/readme.windows.txt
  readme.md
  scripts/certificates/powershell/dev-create-authenticated-cluster-with-subdomains.ps1
  scripts/certificates/powershell/dev-create-authenticated-cluster.ps1
  scripts/raspberry-pi/setup.sh
  scripts/raspberry-pi/start.sh
  scripts/updateSourceWithBuildInfo.ps1
  scripts/version.ps1
  src/CommonAssemblyInfo.cs
  src/Raven.Client/DocumentationUrls.cs
  src/Raven.Client/Documents/Operations/Revisions/EnforceRevisionsConfigurationOperation.cs
  src/Raven.Client/Properties/VersionInfo.cs
  src/Raven.Client/README.md
  src/Raven.Embedded/README.md
  src/Raven.Embedded/Raven.Embedded.nuspec.template
  src/Raven.Server/Documents/DocumentIdWorker.cs
  src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxDocumentConverterBase.cs
  src/Raven.Server/Documents/Indexes/Static/IndexCompilationCache.cs
  src/Raven.Server/Monitoring/Snmp/Templates/zabbix_ravendb_template.xml
  src/Raven.Server/NotificationCenter/Indexing.cs
  src/Raven.Server/Program.cs
  src/Raven.Server/ServerWide/ServerVersion.cs
  src/Raven.Studio/typescript/commands/commandBase.ts
  src/Raven.Studio/wwwroot/version.txt
  src/Raven.TestDriver/README.md
  test/SlowTests/Issues/RavenDB-23464.cs
Labels: v7.1

#20620 RavenDB-24218 updated SECURITY.md - 6.0 is no longer supported
  SECURITY.md
  src/CommonAssemblyInfo.cs
  src/Raven.Server/Smuggler/Migration/MajorVersion.cs
  src/Raven.Server/Smuggler/Migration/Migrator.cs
Labels: v7.0

#20590 RavenDB-23034 - Implements rate limiting for backup/restore and import/export operations
  src/Raven.Client/Documents/Operations/Backups/BackupConfiguration.cs
  src/Raven.Client/Documents/Operations/Backups/RestoreBackupConfiguration.cs
  src/Raven.Client/Documents/Smuggler/DatabaseSmugglerOptions.cs
  src/Raven.Server/Config/Categories/BackupConfiguration.cs
  src/Raven.Server/Documents/CollectionRunner.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/ExecuteRateLimitedOperations.cs
  src/Raven.Server/Documents/PeriodicBackup/BackupTask.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/AbstractRestoreBackupTask.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreSnapshotTask.cs
  src/Raven.Server/Documents/Queries/AbstractDatabaseQueryRunner.cs
  src/Raven.Server/Smuggler/Documents/Data/DatabaseSmugglerOptionsServerSide.cs
  src/Raven.Server/Smuggler/Documents/DatabaseSmuggler.cs
  src/Raven.Server/Smuggler/Documents/ShardedDatabaseSmuggler.cs
  src/Raven.Server/Smuggler/Documents/SmugglerBase.cs
  src/Voron/Impl/Backup/FullBackup.cs
  src/Voron/Util/DataCopier.cs
  src/Voron/Util/RateLimiting/RateGate.cs
  test/SlowTests/Server/Documents/PeriodicBackup/MaxReadOpsPerSecOptionTests.cs
  test/SlowTests/Smuggler/SmugglerApiTests.cs
  test/Tests.Infrastructure/RavenTestBase.ShardedBackupTestBase.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v6.2

#20624 RavenDB-24224 - disable certificate reset in test
  test/StressTests/Authentication/AuthenticationStressTests.cs
Labels: v6.2

#20626 6.2 to 7.0 merge
  src/Raven.Client/Documents/Operations/Backups/BackupConfiguration.cs
  src/Raven.Client/Documents/Operations/Backups/BackupSettings.cs
  src/Raven.Client/Documents/Operations/Backups/RestoreBackupConfiguration.cs
  src/Raven.Client/Documents/Operations/Backups/S3StorageClass.cs
  src/Raven.Client/Documents/Smuggler/DatabaseSmugglerOptions.cs
  src/Raven.Server/Config/Categories/BackupConfiguration.cs
  src/Raven.Server/Documents/CollectionRunner.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/ExecuteRateLimitedOperations.cs
  src/Raven.Server/Documents/PeriodicBackup/Aws/RavenAwsS3Client.cs
  src/Raven.Server/Documents/PeriodicBackup/BackupExtensions.cs
  src/Raven.Server/Documents/PeriodicBackup/BackupTask.cs
  src/Raven.Server/Documents/PeriodicBackup/DirectUpload/AwsS3MultiPartUploader.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/AbstractRestoreBackupTask.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreSnapshotTask.cs
  src/Raven.Server/Documents/Queries/AbstractDatabaseQueryRunner.cs
  src/Raven.Server/Smuggler/Documents/Data/DatabaseSmugglerOptionsServerSide.cs
  src/Raven.Server/Smuggler/Documents/DatabaseSmuggler.cs
  src/Raven.Server/Smuggler/Documents/ShardedDatabaseSmuggler.cs
  src/Raven.Server/Smuggler/Documents/SmugglerBase.cs
  src/Voron/Impl/Backup/FullBackup.cs
  src/Voron/Util/DataCopier.cs
  src/Voron/Util/RateLimiting/RateGate.cs
  test/SlowTests/Authentication/AuthenticationBasicTests.cs
  test/SlowTests/Issues/RavenDB_23846.cs
  test/SlowTests/Server/Documents/ETL/Olap/S3Tests.cs
  test/SlowTests/Server/Documents/PeriodicBackup/MaxReadOpsPerSecOptionTests.cs
  test/SlowTests/Smuggler/SmugglerApiTests.cs
  test/StressTests/Authentication/AuthenticationStressTests.cs
  test/Tests.Infrastructure/RavenTestBase.ShardedBackupTestBase.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v7.0

#20627 7.0 to 7.1 merge
  src/Raven.Client/Documents/Operations/Backups/BackupConfiguration.cs
  src/Raven.Client/Documents/Operations/Backups/BackupSettings.cs
  src/Raven.Client/Documents/Operations/Backups/RestoreBackupConfiguration.cs
  src/Raven.Client/Documents/Operations/Backups/S3StorageClass.cs
  src/Raven.Client/Documents/Smuggler/DatabaseSmugglerOptions.cs
  src/Raven.Server/Config/Categories/BackupConfiguration.cs
  src/Raven.Server/Documents/CollectionRunner.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/ExecuteRateLimitedOperations.cs
  src/Raven.Server/Documents/PeriodicBackup/Aws/RavenAwsS3Client.cs
  src/Raven.Server/Documents/PeriodicBackup/BackupExtensions.cs
  src/Raven.Server/Documents/PeriodicBackup/BackupTask.cs
  src/Raven.Server/Documents/PeriodicBackup/DirectUpload/AwsS3MultiPartUploader.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/AbstractRestoreBackupTask.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreSnapshotTask.cs
  src/Raven.Server/Documents/Queries/AbstractDatabaseQueryRunner.cs
  src/Raven.Server/Smuggler/Documents/Data/DatabaseSmugglerOptionsServerSide.cs
  src/Raven.Server/Smuggler/Documents/DatabaseSmuggler.cs
  src/Raven.Server/Smuggler/Documents/ShardedDatabaseSmuggler.cs
  src/Raven.Server/Smuggler/Documents/SmugglerBase.cs
  src/Raven.Server/Smuggler/Migration/MajorVersion.cs
  src/Raven.Server/Smuggler/Migration/Migrator.cs
  src/Voron/Impl/Backup/FullBackup.cs
  src/Voron/Util/DataCopier.cs
  src/Voron/Util/RateLimiting/RateGate.cs
  test/SlowTests/Authentication/AuthenticationBasicTests.cs
  test/SlowTests/Issues/RavenDB_23846.cs
  test/SlowTests/Server/Documents/ETL/Olap/S3Tests.cs
  test/SlowTests/Server/Documents/PeriodicBackup/MaxReadOpsPerSecOptionTests.cs
  test/SlowTests/Smuggler/SmugglerApiTests.cs
  test/StressTests/Authentication/AuthenticationStressTests.cs
  test/Tests.Infrastructure/RavenTestBase.ShardedBackupTestBase.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v7.1

#20628 RavenDB-24219 AI views: Add links to docs in "About this view"
  src/Raven.Studio/typescript/components/pages/database/aiHub/aiConnectionStrings/AiConnectionStringsInfoHub.tsx
  src/Raven.Studio/typescript/viewmodels/database/tasks/EditEmbeddingsGenerationInfoHub.tsx
Labels: Studio, v7.0

#20630 RavenDB-24233 Fix XML comments
  src/Raven.Client/Documents/Queries/Vector/VectorFieldFactory.cs
Labels: v7.0

#20638 6.2 to 7.0 merge
  src/Corax/Indexing/IndexWriter.Testing.cs
  src/Corax/Indexing/IndexWriter.cs
  src/Voron/Util/NativeList.cs
  test/FastTests/Corax/Bugs/RavenDB_24217.cs
Labels: v7.0

#20640 RavenDB-24239 Lucene: return an empty query when an analyzer removed all terms in the search method.
  src/Raven.Server/Documents/Queries/LuceneQueryHelper.cs
  test/SlowTests/Issues/RavenDB_14939.cs
Labels: v6.2

#20642 6.2 to 7.0 merge
  src/Raven.Server/Documents/Queries/LuceneQueryHelper.cs
  test/SlowTests/Issues/RavenDB_14939.cs
Labels: v7.0

#20643 7.0 to 7.1 merge
  src/Corax/Indexing/IndexWriter.Testing.cs
  src/Corax/Indexing/IndexWriter.cs
  src/Raven.Client/Documents/Operations/ETL/Queue/AmazonSqsConnectionSettings.cs
  src/Raven.Client/Documents/Operations/ETL/Queue/QueueConnectionString.cs
  src/Raven.Client/Documents/Queries/Vector/VectorFieldFactory.cs
  src/Raven.Server/Documents/Queries/LuceneQueryHelper.cs
  src/Raven.Studio/typescript/components/pages/database/aiHub/aiConnectionStrings/AiConnectionStringsInfoHub.tsx
  src/Raven.Studio/typescript/viewmodels/database/tasks/EditEmbeddingsGenerationInfoHub.tsx
  src/Voron/Util/NativeList.cs
  test/FastTests/Corax/Bugs/RavenDB_24217.cs
  test/SlowTests/Issues/RavenDB_14939.cs
Labels: v7.1

#20644 7.1 to 8.0 merge
  src/Corax/Indexing/IndexWriter.Testing.cs
  src/Corax/Indexing/IndexWriter.cs
  src/Raven.Client/Documents/Operations/Backups/BackupConfiguration.cs
  src/Raven.Client/Documents/Operations/Backups/BackupSettings.cs
  src/Raven.Client/Documents/Operations/Backups/RestoreBackupConfiguration.cs
  src/Raven.Client/Documents/Operations/Backups/S3StorageClass.cs
  src/Raven.Client/Documents/Operations/ETL/Queue/AmazonSqsConnectionSettings.cs
  src/Raven.Client/Documents/Operations/ETL/Queue/QueueConnectionString.cs
  src/Raven.Client/Documents/Queries/Vector/VectorFieldFactory.cs
  src/Raven.Client/Documents/Smuggler/DatabaseSmugglerOptions.cs
  src/Raven.Server/Config/Categories/BackupConfiguration.cs
  src/Raven.Server/Documents/CollectionRunner.cs
  src/Raven.Server/Documents/DocumentDatabase.cs
  src/Raven.Server/Documents/ExecuteRateLimitedOperations.cs
  src/Raven.Server/Documents/PeriodicBackup/Aws/RavenAwsS3Client.cs
  src/Raven.Server/Documents/PeriodicBackup/BackupExtensions.cs
  src/Raven.Server/Documents/PeriodicBackup/BackupTask.cs
  src/Raven.Server/Documents/PeriodicBackup/DirectUpload/AwsS3MultiPartUploader.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/AbstractRestoreBackupTask.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreSnapshotTask.cs
  src/Raven.Server/Documents/Queries/AbstractDatabaseQueryRunner.cs
  src/Raven.Server/Documents/Queries/LuceneQueryHelper.cs
  src/Raven.Server/Smuggler/Documents/Data/DatabaseSmugglerOptionsServerSide.cs
  src/Raven.Server/Smuggler/Documents/DatabaseSmuggler.cs
  src/Raven.Server/Smuggler/Documents/ShardedDatabaseSmuggler.cs
  src/Raven.Server/Smuggler/Documents/SmugglerBase.cs
  src/Raven.Server/Smuggler/Migration/Migrator.cs
  src/Raven.Studio/typescript/components/pages/database/aiHub/aiConnectionStrings/AiConnectionStringsInfoHub.tsx
  src/Raven.Studio/typescript/viewmodels/database/tasks/EditEmbeddingsGenerationInfoHub.tsx
  src/Voron/Impl/Backup/FullBackup.cs
  src/Voron/Util/DataCopier.cs
  src/Voron/Util/NativeList.cs
  src/Voron/Util/RateLimiting/RateGate.cs
  test/FastTests/Corax/Bugs/RavenDB_24217.cs
  test/SlowTests/Authentication/AuthenticationBasicTests.cs
  test/SlowTests/Issues/RavenDB_14939.cs
  test/SlowTests/Issues/RavenDB_23846.cs
  test/SlowTests/Server/Documents/ETL/Olap/S3Tests.cs
  test/SlowTests/Server/Documents/PeriodicBackup/MaxReadOpsPerSecOptionTests.cs
  test/SlowTests/Smuggler/SmugglerApiTests.cs
  test/StressTests/Authentication/AuthenticationStressTests.cs
  test/Tests.Infrastructure/RavenTestBase.ShardedBackupTestBase.cs
  test/Tests.Infrastructure/TestBase.cs
Labels: v8.0

#20649 RavenDB-19994: Fix failing test with wrong assert
  test/SlowTests/Authentication/AuthenticationDebugPackageInfoTests.cs
  test/StressTests/Authentication/AuthenticationStressTests.cs
  test/Tests.Infrastructure/RavenTestHelper.cs
Labels: v5.4

#20652 RavenDB-24251 - Update the download link of the Microsoft Visual C++ 2019 Redistributable Package
  src/Sparrow.Server/Platform/Pal.cs
  src/Sparrow.Server/Sodium.tt
  src/Sparrow/Platform/PlatformDetails.cs
  src/Sparrow/Platform/Sodium.cs
Labels: v5.4

#20662 RavenDB-23089 Fixing the test. Making sure that we do the assertion on the actual value that satisfied the condition of WaitForValue()
  test/SlowTests/Issues/RavenDB-22369.cs
Labels: v6.2

#20666 RavenDB-24281 Backward compatibility for indexes that do not have `NonExisting` posting list
  src/Corax/Querying/IndexSearcher.cs
  test/SlowTests/Data/RavenDB_24281/RavenDB_24281.ravendb-snapshot
  test/SlowTests/Issues/RavenDB-24281.cs
  test/SlowTests/SlowTests.csproj
Labels: v6.2

#20668 RavenDB-24155-logs - Add logs & SNMP monitoring to Missing Attachments
  src/Raven.Server/Documents/Replication/IncomingReplicationHandler.cs
Labels: v5.4

#20670 5.4 to 6.2 merge
  src/Raven.Server/Documents/Handlers/Debugging/MemoryDebugHandler.cs
  src/Raven.Server/Documents/Replication/Incoming/IncomingReplicationHandler.cs
  src/Raven.Server/RavenServer.cs
  src/Sparrow.Server/LowMemory/MemoryInformation.cs
  src/Sparrow.Server/Platform/Pal.cs
  src/Sparrow.Server/Platform/Win32/Win32MemoryMethods.cs
  src/Sparrow.Server/Sodium.tt
  src/Sparrow/Platform/PlatformDetails.cs
  src/Sparrow/Platform/Sodium.cs
  test/SlowTests/Authentication/AuthenticationDebugPackageInfoTests.cs
  test/SlowTests/Issues/RavenDB-14323.cs
  test/StressTests/Authentication/AuthenticationStressTests.cs
  test/Tests.Infrastructure/RavenTestHelper.cs
Labels: v6.2

#20674 6.2 to 7.0 merge
  src/Raven.Client/Documents/Operations/CollectionStatistics.cs
  src/Raven.Server/Documents/CountersStorage.cs
  src/Raven.Server/Documents/DocumentsStorage.cs
  src/Raven.Server/Documents/Handlers/CollectionsHandler.cs
  src/Raven.Server/Documents/Handlers/Processors/Collections/CollectionsHandlerProcessorForGetCollectionStats.cs
  src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
  src/Raven.Server/Documents/Sharding/Handlers/Processors/Collections/ShardedCollectionsHandlerProcessorForGetCollectionStats.cs
  src/Raven.Server/Documents/TimeSeries/TimeSeriesStorage.cs
  test/SlowTests/Authentication/AuthenticationDebugPackageInfoTests.cs
  test/SlowTests/Issues/RavenDB_14881.cs
  test/SlowTests/Issues/RavenDB_23754.cs
  test/SlowTests/Sharding/Client/Operations/GetCollectionStatisticsOperationTests.cs
Labels: v7.0

#20680 RavenDB-22767 Replaced `ValueTask` with `Task` and removed unnecessary `ConfigureAwait`
  src/Raven.Server/Documents/Handlers/Processors/Documents/AbstractDocumentHandlerProcessorForGet.cs
  src/Raven.Server/Documents/Handlers/Processors/Queries/AbstractQueriesHandlerProcessorForGet.cs
  src/Raven.Server/Documents/Handlers/Processors/Queries/DatabaseQueriesHandlerProcessorForGet.cs
  src/Raven.Server/Documents/Queries/QueryRunner.cs
Labels: v6.2

#20688 RavenDB-24294 - workaround for connectivity testing to the model
  src/Raven.Client/Documents/Operations/AI/AiConnectionString.cs
  src/Raven.Server/Documents/AI/AbstractChatCompletionClient.cs
  src/Raven.Server/Documents/AI/Embeddings/EmbeddingsMismatchException.cs
  src/Raven.Server/Documents/AI/GenAi/ChatCompletionClients.cs
  src/Raven.Server/Documents/ETL/Providers/AI/Handlers/Processors/AiEtlHandlerProcessorForTestAiConnectionBase.cs
Labels: v7.1
