Repository ravendb/ravendb, pull requests merged in 2025-03, with the labels that each got.

#20244 HRINT-4004 Change order in multiarch.dockerfile for deb
  scripts/linux/pkg/deb/ubuntu_multiarch.Dockerfile
Labels: v5.4

#20255 RavenDB-14706 Uncomment the Snowflake license check
  src/Raven.Server/Commercial/LicenseManager.cs
Labels: v7.0

#20261 RavenDB-23360: fixed eslint errors (v6.2) for (ButtonGroup, Pagination, Alert, ListGroup,Accordion, Table, Card, Nav, Carousel, InputGroup, InputGroupText)
  src/Raven.Studio/typescript/components/pages/database/documents/identities/DocumentIdentitiesModal.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/list/terms/IndexTerms.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/revisionsBinCleaner/RevisionsBinCleaner.tsx
  src/Raven.Studio/typescript/components/pages/database/tasks/ongoingTasks/panels/InternalReplicationPanel.tsx
  src/Raven.Studio/typescript/components/pages/database/tasks/ongoingTasks/partials/ChangeVectorDetails.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/create/regular/steps/StepShardingPrefixes.tsx
  src/Raven.Studio/typescript/components/shell/studioSearchWithDatabaseSelector/StudioSearchWithDatabaseSwitcher.tsx
  src/Raven.Studio/typescript/components/shell/studioSearchWithDatabaseSelector/studioSearch/StudioSearch.scss
  src/Raven.Studio/typescript/components/shell/studioSearchWithDatabaseSelector/studioSearch/StudioSearch.tsx
  src/Raven.Studio/typescript/components/shell/studioSearchWithDatabaseSelector/studioSearch/hooks/useStudioSearchKeyboardEvents.ts
Labels: Studio, v6.2

#20246 RavenDB-23309 test fix
  test/SlowTests/Issues/RavenDB-22659.cs
Labels: v6.2

#20208 RavenDB-23768 CPU usage calculation fix
  src/Raven.Server/Utils/Cpu/CpuUsageCalculator.cs
Labels: v6.2

#20270 RavenDB-7070 Adding new option in Testing by Contributor section of PR template
  .github/pull_request_template.md
Labels: v7.0

#20279 RavenDB-23759 compilation fixes for VS 17.13
  src/Raven.Server/Documents/Indexes/Static/StaticIndexBase.cs
  src/Raven.Server/Integrations/PostgreSQL/Types/PgFloat4.cs
  src/Raven.Server/Integrations/PostgreSQL/Types/PgFloat8.cs
  src/Sparrow/Json/LazyStringValue.cs
  test/SlowTests/Client/QueriesWithCustomFunctions.cs
  test/SlowTests/Issues/RavenDB-11907.cs
Labels: v5.4

#20287 5.4 to 6.0 merge
  src/Raven.Server/Documents/Indexes/Static/StaticIndexBase.cs
  src/Raven.Server/Integrations/PostgreSQL/Types/PgFloat4.cs
  src/Raven.Server/Integrations/PostgreSQL/Types/PgFloat8.cs
  src/Raven.Server/Utils/AsyncBlittableJsonTextWriterForDebug.cs
  src/Raven.Studio/package-lock.json
  src/Raven.Studio/package.json
  src/Raven.Studio/tsconfig.json
  src/Raven.Studio/typescript/common/__mocks__/eventsCollector.ts
  src/Raven.Studio/typescript/common/eventsCollector.ts
  src/Raven.Studio/typescript/viewmodels/shell.ts
  src/Raven.Studio/webpack.config.js
  src/Raven.Studio/wwwroot/Content/custom_ga.js
  src/Sparrow/Json/IBlittableJsonTextWriter.cs
  src/Voron/PageLocator.cs
  test/FastTests/Corax/Bugs/RavenDB-21471.cs
  test/FastTests/Server/Documents/Queries/Parser/ScannerTests.cs
  test/SlowTests/Client/QueriesWithCustomFunctions.cs
  test/SlowTests/Issues/RavenDB-11907.cs
Labels: v6.0

#20298 RavenDB-23863
  src/Sparrow/RecyclableMemoryStreamFactory.cs
Labels: v6.2

#20299 RavenDB-23863
  src/Sparrow/RecyclableMemoryStreamFactory.cs
Labels: v6.2

#20300 RavenDB-23863
  src/Sparrow/RecyclableMemoryStreamFactory.cs
Labels: v7.0

#20242 RavenDB-23809 Leader.PutAsync Keep context valid in case of exceptions
  src/Raven.Server/Rachis/Leader.cs
Labels: v5.4

#20307 release/v7.0 to v7.0 merge
  src/Sparrow/RecyclableMemoryStreamFactory.cs
  src/Voron/Data/CompactTrees/CompactKey.cs
Labels: v7.0

#20310 RavenDB-23867: Exchange the Directory Property and updated all benchmarks.
  Directory.Packages.props
  bench/Micro.Benchmark/Benchmarks/BatchedIntegerEncoding.cs
  bench/Micro.Benchmark/Benchmarks/Dictionary.cs
  bench/Micro.Benchmark/Benchmarks/Hardware/Compare.cs
  bench/Micro.Benchmark/Benchmarks/Hardware/Diff.cs
  bench/Micro.Benchmark/Benchmarks/Hardware/Prefetch.cs
  bench/Micro.Benchmark/Benchmarks/Hardware/Prefetch2.cs
  bench/Micro.Benchmark/Benchmarks/Hardware/Search.cs
  bench/Micro.Benchmark/Benchmarks/Hashing.XXHash32.cs
  bench/Micro.Benchmark/Benchmarks/Hashing.XXHash64.cs
  bench/Micro.Benchmark/Benchmarks/HopeEncoder.cs
  bench/Micro.Benchmark/Benchmarks/IntegerEncoding.cs
  bench/Micro.Benchmark/Benchmarks/LZ4/LZ4Benchmark.cs
  bench/Micro.Benchmark/Benchmarks/PageLocator/PlRandomRead.cs
  bench/Micro.Benchmark/Benchmarks/PageLocator/PlRandomWrite.cs
  bench/Micro.Benchmark/Benchmarks/Parsing/DateTimeParsing.cs
  bench/Micro.Benchmark/Benchmarks/PointerBenchmarks.cs
  bench/Micro.Benchmark/Benchmarks/Sorting/Sorting.cs
  bench/Micro.Benchmark/Benchmarks/TypeCache.cs
  bench/Micro.Benchmark/Benchmarks/Zstd/ZstdBenchmark.cs
  bench/Micro.Benchmark/Benchmarks/Zstd/ZstdPageBenchmark.cs
  bench/Micro.Benchmark/Program.cs
  bench/ServerStoreTxMerger.Benchmark/ServerStoreTxMerger.Benchmark.csproj
  tools/Raven.Debug/Raven.Debug.csproj
Labels: v6.2

#20275 RavenDB-23620 In tests, wait on the backup operation before starting a new one
  test/RachisTests/DatabaseCluster/AtomicClusterReadWriteTests.cs
  test/SlowTests/Issues/RavenDB-21050.cs
  test/SlowTests/Sharding/Backup/ShardedBackupTests .cs
  test/SlowTests/Sharding/Backup/ShardedRestoreBackupTests.cs
  test/SlowTests/Sharding/Cluster/ReshardingTests.cs
  test/SlowTests/Sharding/Cluster/ShardedClusterObserverTests.cs
  test/Tests.Infrastructure/RavenTestBase.Backup.cs
  test/Tests.Infrastructure/RavenTestBase.ShardedBackupTestBase.cs
Labels: v6.0

#20293 RavenDB-23221 Expose Community on About
  src/Raven.Studio/typescript/components/common/AboutView.tsx
  src/Raven.Studio/typescript/components/pages/resources/about/partials/LicenseSummary.tsx
  src/Raven.Studio/typescript/components/pages/resources/about/partials/SupportDetails.tsx
  src/Raven.Studio/typescript/components/pages/resources/about/partials/SupportSummary.tsx
  src/Raven.Studio/typescript/components/pages/resources/about/partials/VersionsSummary.tsx
  src/Raven.Studio/typescript/components/pages/resources/about/partials/common.tsx
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon/discord.svg
  src/Raven.Studio/wwwroot/Content/css/fonts/icomoon/support.svg
  src/Raven.Studio/wwwroot/Content/img/pages/about/support.svg
Labels: Studio, v6.2

#20291 RavenDB-23360 Fix textarea
  src/Raven.Studio/typescript/components/common/formDestinations/GoogleCloud.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/connectionStrings/editForms/AzureQueueStorageConnectionString.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/connectionStrings/editForms/RabbitMqConnectionString.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/connectionStrings/editForms/SqlConnectionString.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/create/formBackup/steps/source/BackupSourceGoogleCloud.tsx
Labels: Studio, v6.2

#20302 RavenDB-23789 - SlowTests.Server.Documents.OngoingTasks.ReplicationOngoingTaskProgressTests.GetPullReplicationAsHubTaskProgressShouldWork
  test/SlowTests/Server/Documents/OngoingTasks/ReplicationOngoingTaskProgressTests.cs
Labels: v6.2

#20301 RavenDB-23774 - SlowTests.Server.Documents.OngoingTasks.ReplicationOn…
  test/SlowTests/Server/Documents/OngoingTasks/ReplicationOngoingTaskProgressTests.cs
Labels: v6.2

#20316 RavenDB-23888 fixed polarity
  src/Raven.Server/Web/Authentication/AdminCertificatesHandler.cs
Labels: v5.4

#20320 RavenDB-23104 - skip unnecessary check in pull replication idle datab…
  test/SlowTests/Server/Replication/PullReplicationTests.cs
Labels: v5.4

#20317 RavenDB-7070 - move tests to FastTests
  test/FastTests/TestsInheritanceFastTests.cs
  test/SlowTests/Tests/TestsInheritanceTests.cs
Labels: v5.4

#20319 5.4 to 6.0 merge
  src/Raven.Server/Commercial/LicenseHelper.cs
  src/Raven.Server/Documents/CountersStorage.cs
  src/Raven.Server/Documents/ETL/EtlLoader.cs
  src/Raven.Server/Documents/Handlers/Admin/Processors/Tombstones/AdminTombstoneHandlerProcessorForState.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/MapReduce/Static/MapReduceIndex.cs
  src/Raven.Server/Documents/Indexes/Static/Counters/MapCountersIndex.cs
  src/Raven.Server/Documents/Indexes/Static/Counters/MapReduceCountersIndex.cs
  src/Raven.Server/Documents/Indexes/Static/MapIndex.cs
  src/Raven.Server/Documents/Indexes/Static/TimeSeries/MapReduceTimeSeriesIndex.cs
  src/Raven.Server/Documents/Indexes/Static/TimeSeries/MapTimeSeriesIndex.cs
  src/Raven.Server/Documents/Indexes/StaticIndexHelper.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
  src/Raven.Server/Documents/Replication/ConflictManager.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/Documents/TombstoneCleaner.cs
  src/Raven.Server/Web/Authentication/AdminCertificatesHandler.cs
  src/Raven.Studio/typescript/commands/database/documents/getDocumentRevisionPhysicalSizeCommand.ts
  src/Raven.Studio/typescript/components/pages/database/settings/tombstones/TombstonesState.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/tombstones/useTombstonesStateColumns.tsx
  src/Raven.Studio/typescript/test/stubs/DatabasesStubs.ts
  src/Raven.Studio/typescript/viewmodels/database/documents/editDocument.ts
  src/Raven.Studio/typings/_studio/dto.d.ts
  src/Sparrow.Server/ByteString.cs
  src/Sparrow/Collections/ConcurrentSet.cs
  test/FastTests/Sparrow/ByteStringTests.cs
  test/FastTests/Sparrow/ConcurrentSetTests.cs
  test/LicenseTests/LicenseOptionsTests.cs
  test/RachisTests/SubscriptionFailoverWIthWaitingChains.cs
  test/RachisTests/SubscriptionsFailover.cs
  test/SlowTests/Authentication/AuthenticationLetsEncryptTests.cs
  test/SlowTests/Client/Subscriptions/ConcurrentSubscriptionsTests.cs
  test/SlowTests/Client/Subscriptions/RevisionsSubscriptions.cs
  test/SlowTests/Issues/RavenDB-23579.cs
  test/SlowTests/Issues/RavenDB_10656.cs
  test/SlowTests/Issues/RavenDB_20608.cs
  test/SlowTests/Server/Documents/Indexing/MapReduce/OutputReduceToCollectionReplicationTests.cs
  test/SlowTests/Server/Documents/Revisions/RevisionsReplication.cs
Labels: v6.0

#20322 5.4 & release/6.0 to 6.0 merge
  src/CommonAssemblyInfo.cs
  src/Raven.Client/Properties/VersionInfo.cs
  test/FastTests/TestsInheritanceFastTests.cs
  test/SlowTests/Server/Replication/PullReplicationTests.cs
  test/SlowTests/Tests/TestsInheritanceTests.cs
Labels: v6.0

#20323 6.0 & release/6.2 to 6.2 merge
  src/CommonAssemblyInfo.cs
  src/Raven.Client/Properties/VersionInfo.cs
  src/Raven.Server/Commercial/LicenseHelper.cs
  src/Raven.Server/Documents/CountersStorage.cs
  src/Raven.Server/Documents/ETL/EtlLoader.cs
  src/Raven.Server/Documents/Handlers/Admin/Processors/Tombstones/AdminTombstoneHandlerProcessorForState.cs
  src/Raven.Server/Documents/Indexes/Index.cs
  src/Raven.Server/Documents/Indexes/MapReduce/Static/MapReduceIndex.cs
  src/Raven.Server/Documents/Indexes/Static/Counters/MapCountersIndex.cs
  src/Raven.Server/Documents/Indexes/Static/Counters/MapReduceCountersIndex.cs
  src/Raven.Server/Documents/Indexes/Static/MapIndex.cs
  src/Raven.Server/Documents/Indexes/Static/TimeSeries/MapReduceTimeSeriesIndex.cs
  src/Raven.Server/Documents/Indexes/Static/TimeSeries/MapTimeSeriesIndex.cs
  src/Raven.Server/Documents/Indexes/StaticIndexHelper.cs
  src/Raven.Server/Documents/Operations/AbstractOperations.cs
  src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
  src/Raven.Server/Documents/Replication/ConflictManager.cs
  src/Raven.Server/Documents/Replication/ReplicationLoader.cs
  src/Raven.Server/Documents/TombstoneCleaner.cs
  src/Raven.Server/Web/Authentication/AdminCertificatesHandler.cs
  src/Raven.Studio/typescript/commands/database/documents/getDocumentRevisionPhysicalSizeCommand.ts
  src/Raven.Studio/typescript/components/pages/database/settings/tombstones/TombstonesState.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/tombstones/useTombstonesStateColumns.tsx
  src/Raven.Studio/typescript/test/stubs/DatabasesStubs.ts
  src/Raven.Studio/typescript/viewmodels/database/documents/editDocument.ts
  src/Raven.Studio/typings/_studio/dto.d.ts
  src/Sparrow.Server/ByteString.cs
  src/Sparrow/Collections/ConcurrentSet.cs
  test/FastTests/Sparrow/ByteStringTests.cs
  test/FastTests/Sparrow/ConcurrentSetTests.cs
  test/FastTests/TestsInheritanceFastTests.cs
  test/LicenseTests/LicenseOptionsTests.cs
  test/RachisTests/DatabaseCluster/AtomicClusterReadWriteTests.cs
  test/RachisTests/SubscriptionFailoverWIthWaitingChains.cs
  test/RachisTests/SubscriptionsFailover.cs
  test/SlowTests/Authentication/AuthenticationLetsEncryptTests.cs
  test/SlowTests/Client/Subscriptions/ConcurrentSubscriptionsTests.cs
  test/SlowTests/Client/Subscriptions/RevisionsSubscriptions.cs
  test/SlowTests/Issues/RavenDB-21050.cs
  test/SlowTests/Issues/RavenDB-23579.cs
  test/SlowTests/Issues/RavenDB_10656.cs
  test/SlowTests/Issues/RavenDB_20608.cs
  test/SlowTests/Server/Documents/Indexing/MapReduce/OutputReduceToCollectionReplicationTests.cs
  test/SlowTests/Server/Documents/Revisions/RevisionsReplication.cs
  test/SlowTests/Server/Replication/PullReplicationTests.cs
  test/SlowTests/Sharding/Backup/ShardedBackupTests .cs
  test/SlowTests/Sharding/Backup/ShardedRestoreBackupTests.cs
  test/SlowTests/Sharding/Cluster/ReshardingTests.cs
  test/SlowTests/Sharding/Cluster/ShardedClusterObserverTests.cs
  test/SlowTests/Sharding/PrefixedSharding.cs
  test/SlowTests/Tests/TestsInheritanceTests.cs
  test/Tests.Infrastructure/RavenTestBase.Backup.cs
  test/Tests.Infrastructure/RavenTestBase.ShardedBackupTestBase.cs
Labels: v6.2

#20284 RavenDB-23775 - Avoid disposing idle database activity timer
  src/Raven.Server/Documents/DatabasesLandlord.cs
Labels: v5.4

#20169 RavenDB-22903 and RavenDB-23060: Enhance diagnostic logging for compare exchange tombstone cleanup
  src/Raven.Server/ServerWide/Maintenance/ClusterObserver.cs
  test/SlowTests/Server/Documents/PeriodicBackup/RavenDB-11139.cs
Labels: v6.2

#20318 RavenDB-23894 - Index Errors: Disable dropdown and display disclaimer instead of empty dropdown
  src/Raven.Studio/typescript/components/pages/database/indexes/errors/SelectIndexErrorsDropdown.tsx
Labels: Studio, v6.2

#20337 RavenDB-23914 In NLog.template.config explain how to enable audit log writing to file
  src/Raven.Server/NLog.template.config
Labels: v7.0

#20335 RavenDB-22246: Fix tests for Embedded Server for ThrowOnInvalidOrMissingLicense default value
  test/LicenseTests/LicenseOptionsTests.cs
Labels: v6.2

#20334 RavenDB-23908 - Restore the subscription name when restoring a database from a snapshot
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreBackupTaskBase.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
Labels: v5.4

#20333 RavenDB-20322 - Append changes to AttachmentsReplication.cs
  test/SlowTests/Client/Attachments/AttachmentsReplication.cs
Labels: v6.2

#20340 Revert "RavenDB-7070 - move tests to FastTests" v5.4
  test/FastTests/TestsInheritanceFastTests.cs
  test/SlowTests/Tests/TestsInheritanceTests.cs
Labels: v5.4

#20339 Revert "RavenDB-7070 - move tests to FastTests" v6.0
  test/FastTests/TestsInheritanceFastTests.cs
  test/SlowTests/Tests/TestsInheritanceTests.cs
Labels: v6.0

#19524 RavenDB-23077 - PerCoreContainer performance improvements
  src/Sparrow/Json/PerCoreContainer.cs
Labels: v6.2

#20314 RavenDB-23371 Corax: RangeQuery optimizations for big datasets.
  src/Corax/Querying/Matches/MultiTermMatch.cs
  src/Sparrow/Compression/VariableSizeEncoding.cs
  src/Voron/Util/NativeList.cs
  src/Voron/Util/PFor/FastPForDecoder.cs
Labels: Corax, v6.2

#20346 RavenDB-23776 - Error Toasts Triggered by Whitespace Input in "Create New Database" Modal
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/create/formBackup/CreateDatabaseFromBackup.tsx
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/create/regular/CreateDatabaseRegular.tsx
Labels: Studio, v6.2

#20343 RavenDB-23820 - Do not show "Pause indexing untill restart" option for a disabled database
  src/Raven.Studio/typescript/components/pages/resources/databases/partials/DatabasePanel.tsx
Labels: Studio, v6.2

#20342 RavenDB-23904 - View freezes on refresh in tombstones view
  src/Raven.Studio/typescript/components/pages/database/settings/tombstones/TombstonesState.tsx
Labels: Studio, v6.2

#20350 5.4 to 6.2 merge
  src/Raven.Server/Documents/DatabasesLandlord.cs
  src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreSnapshotTask.cs
  test/FastTests/TestsInheritanceFastTests.cs
  test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
  test/SlowTests/Tests/TestsInheritanceTests.cs
Labels: v6.2

#20349 RavenDB-23842 More massive ETL logs to Debug
  src/Raven.Server/Documents/ETL/Providers/RelationalDatabase/Common/RelationalDatabaseEtlBase.cs
  src/Raven.Server/Documents/ETL/Providers/RelationalDatabase/Common/RelationalWriters/RelationalDatabaseWriterBase.cs
Labels: v7.0

#20344 RavenDB-23929 VectorSearch - set default minimum similarity to 0.
  src/Raven.Server/Config/Categories/IndexingConfiguration.cs
  test/SlowTests/Issues/RavenDB-23509.cs
  test/SlowTests/Issues/RavenDB-23524.cs
  test/SlowTests/Issues/RavenDB-23658.cs
Labels: v7.0

#20353 RavenDB-23556 Update Azure models
  src/Raven.Studio/typescript/components/pages/database/settings/connectionStrings/editForms/aiConnectionStringUtils.ts
  src/Raven.Studio/typescript/components/pages/database/settings/connectionStrings/editForms/aiFields/AzureOpenAiSettings.tsx
  src/Raven.Studio/typescript/components/pages/database/settings/connectionStrings/editForms/aiFields/OpenAiSettings.tsx
Labels: v7.0

#20347 RavenDB-23934 - Clicking on the Run script button doesn't work in Admin JS Console.
  src/Raven.Studio/typescript/components/common/RunScriptButton.tsx
Labels: Studio, v6.2

#20351 RavenDB-23938 IndexErrors tests took too long
  src/Raven.Studio/typescript/components/pages/database/indexes/errors/IndexErrors.spec.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/errors/IndexErrors.stories.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/errors/IndexErrorsPanel.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/errors/IndexErrorsPanelTable.tsx
Labels: Studio, v6.2

#20362 RavenDB-23556 Add info icon and adjust text
  src/Raven.Studio/wwwroot/App/views/database/tasks/editEmbeddingsGenerationTask.html
Labels: v7.0

#20363 RavenDB-23556 Renaming collection name and changing the format of ID for embedding docs
  src/Raven.Server/Documents/AI/Embeddings/EmbeddingsHelper.cs
Labels: v7.0

#20356 RavenDB-23556: Cleaning up unused embeddings generation workers on DatabaseRecordChange
  src/Raven.Server/Documents/AI/Embeddings/EmbeddingsGenerator.cs
Labels: v7.0

#20365 RavenDB-23556 Fixing references of embeddings docs collection in auto indexes
  src/Raven.Server/Documents/Indexes/Auto/AutoMapIndex.cs
  test/SlowTests/Server/Documents/AI/Embeddings/QueryingTests.cs
Labels: v7.0

#20370 RavenDB-7070 Making the RabbitMQ connection infrastructure used in the test consistent with others so it won't throw InvalidOperationException when debugging if there is no relevant env variable is defined
  test/SlowTests/Server/Documents/ETL/Queue/RabbitMqEtlTestBase.cs
  test/Tests.Infrastructure/ConnectionString/RabbitMqConnectionString.cs
Labels: v5.4

#20375 RavenDB-23965 moved bge-micro-v2 to our S3
  src/DownloadEmbeddings.targets
Labels: v7.0

#20377 5.4 to 6.2 merge
  .github/workflows/FastTests.yml
  .github/workflows/FastTestsARM.yml
  src/Raven.Server/Platform/Posix/MemInfoReader.cs
  test/SlowTests/Authentication/AuthenticationBasicTests.cs
  test/SlowTests/Server/Documents/ETL/Queue/RabbitMqEtlTestBase.cs
  test/SlowTests/Server/Documents/QueueSink/RabbitMqQueueSinkTestBase.cs
  test/SlowTests/Server/Documents/QueueSink/RabbitMqSinkTests.cs
  test/Tests.Infrastructure/ConnectionString/RabbitMqConnectionString.cs
Labels: v6.2

#20378 6.2 to 7.0 merge
  .github/workflows/FastTests.yml
  .github/workflows/FastTestsARM.yml
  src/Raven.Server/Platform/Posix/MemInfoReader.cs
  src/Raven.Studio/typescript/components/pages/database/indexes/errors/IndexErrors.spec.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/errors/IndexErrors.stories.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/errors/IndexErrorsPanel.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/errors/IndexErrorsPanelTable.tsx
  test/SlowTests/Authentication/AuthenticationBasicTests.cs
  test/SlowTests/Server/Documents/ETL/Queue/RabbitMqEtlTestBase.cs
  test/SlowTests/Server/Documents/QueueSink/RabbitMqQueueSinkTestBase.cs
  test/SlowTests/Server/Documents/QueueSink/RabbitMqSinkTests.cs
  test/Tests.Infrastructure/ConnectionString/RabbitMqConnectionString.cs
Labels: v7.0

#20379 7.0 to 7.1 merge
  .github/workflows/FastTests.yml
  .github/workflows/FastTestsARM.yml
  src/Raven.Client/Raven.Client.csproj
  src/Raven.Server/Platform/Posix/MemInfoReader.cs
  src/Raven.Studio/typescript/components/pages/database/indexes/errors/IndexErrors.spec.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/errors/IndexErrors.stories.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/errors/IndexErrorsPanel.tsx
  src/Raven.Studio/typescript/components/pages/database/indexes/errors/IndexErrorsPanelTable.tsx
  src/Sparrow/Sparrow.csproj
  test/SlowTests/Authentication/AuthenticationBasicTests.cs
  test/SlowTests/Server/Documents/ETL/Queue/RabbitMqEtlTestBase.cs
  test/SlowTests/Server/Documents/QueueSink/RabbitMqQueueSinkTestBase.cs
  test/SlowTests/Server/Documents/QueueSink/RabbitMqSinkTests.cs
  test/SlowTests/SlowTests.csproj
  test/SlowTests/Tests/TestsInheritanceTests.cs
  test/SlowTests/Tests/fact-tests.txt
  test/Tests.Infrastructure/ConnectionString/RabbitMqConnectionString.cs
Labels: v7.1

#20368 RavenDB-23941 - Allow the backup task to complete before concluding the test
  test/RachisTests/DatabaseCluster/AtomicClusterReadWriteTests.cs
Labels: v6.2

#20380 RavenDB-23804 disable license configuration for all tests in AuthenticationBasicTests
  test/SlowTests/Authentication/AuthenticationBasicTests.cs
Labels: v5.4

#20381 RavenDB-23967 embedding cache documents from queries are written in a background
  test/SlowTests/Server/Documents/AI/Embeddings/QueryingTests.cs
Labels: v7.0

#20345 RavenDB-23777 - Remove the Delete button from the revisions comparison view
  src/Raven.Studio/wwwroot/App/views/database/documents/editDocument.html
Labels: Studio, v7.0

#20359 RavenDB-23917 set appropriate resource and component for audit loggers
  src/Raven.Server/Documents/AbstractDatabaseRequestHandler.cs
  src/Raven.Server/Documents/DatabaseRequestHandler.cs
  src/Raven.Server/Documents/Handlers/Admin/Processors/Configuration/AbstractAdminConfigurationHandlerProcessorForPutSettings.cs
  src/Raven.Server/Documents/Handlers/Admin/Processors/Indexes/AbstractAdminIndexHandlerProcessorForPut.cs
  src/Raven.Server/Documents/Handlers/Admin/Processors/Indexes/AdminIndexHandlerProcessorForJavaScriptPut.cs
  src/Raven.Server/Documents/Handlers/Admin/Processors/Revisions/AbstractAdminRevisionsHandlerProcessorForDeleteRevisions.cs
  src/Raven.Server/Documents/Handlers/Admin/Processors/Sorters/AbstractAdminSortersHandlerProcessorForDelete.cs
  src/Raven.Server/Documents/Handlers/Admin/Processors/Sorters/AbstractAdminSortersHandlerProcessorForPut.cs
  src/Raven.Server/Documents/Handlers/Admin/RachisAdminHandler.cs
  src/Raven.Server/Documents/Handlers/LegacyReplicationHandler.cs
  src/Raven.Server/Documents/Handlers/Processors/Analyzers/AbstractAdminAnalyzersHandlerProcessorForDelete.cs
  src/Raven.Server/Documents/Handlers/Processors/Analyzers/AbstractAdminAnalyzersHandlerProcessorForPut.cs
  src/Raven.Server/Documents/Handlers/Processors/Indexes/AbstractIndexHandlerProcessorForDelete.cs
  src/Raven.Server/Documents/Handlers/Processors/Indexes/IndexHandlerProcessorForReset.cs
  src/Raven.Server/Documents/Handlers/Processors/OngoingTasks/AbstractOngoingTasksHandlerProcessorForPutConnectionString.cs
  src/Raven.Server/Documents/Handlers/Processors/OngoingTasks/AbstractOngoingTasksHandlerProcessorForRemoveConnectionString.cs
  src/Raven.Server/Documents/Handlers/Processors/Queries/AbstractDatabaseOperationQueriesHandlerProcessor.cs
  src/Raven.Server/Documents/Handlers/Processors/SampleData/AbstractSampleDataHandlerProcessorForPostSampleData.cs
  src/Raven.Server/Documents/Handlers/Processors/Smuggler/AbstractSmugglerHandlerProcessorForImportDir.cs
  src/Raven.Server/Documents/Handlers/Processors/Streaming/AbstractStreamingHandlerProcessorForGetStreamQuery.cs
  src/Raven.Server/Integrations/PostgreSQL/Handlers/Processors/AbstractPostgreSqlIntegrationHandlerProcessorForAddUser.cs
  src/Raven.Server/Integrations/PostgreSQL/Handlers/Processors/AbstractPostgreSqlIntegrationHandlerProcessorForDeleteUser.cs
  src/Raven.Server/Logging/RavenLogManagerServerExtensions.cs
  src/Raven.Server/Smuggler/Documents/Handlers/SmugglerHandler.cs
  src/Raven.Server/Web/Authentication/AdminCertificatesHandler.cs
  src/Raven.Server/Web/Authentication/TwoFactorAuthenticationHandler.cs
  src/Raven.Server/Web/RequestHandler.Audit.cs
  src/Raven.Server/Web/System/AdminDatabasesHandler.cs
  src/Raven.Server/Web/System/Analyzers/AdminAnalyzersHandler.cs
  src/Raven.Server/Web/System/DatabasesHandler.cs
  src/Raven.Server/Web/System/Sorters/AdminSortersHandler.cs
Labels: v7.0

#20383 [7.1] RavenDB-22986 - Free space searching improvements
  src/Voron/Impl/FreeSpace/FreeSpaceHandling.cs
  src/Voron/Impl/FreeSpace/IFreeSpaceHandling.cs
  src/Voron/Impl/FreeSpace/StreamBitArray.cs
  src/Voron/Impl/LowLevelTransaction.cs
  test/FastTests/Voron/StreamBitArrayTests.cs
  test/FastTests/Voron/Trees/FreeSpaceTest.cs
Labels: v7.1

#20387 RavenDB-22767 Making sure that a transaction is removed from ActiveTransactions if an exception is thrown after already adding it there
  src/Voron/StorageEnvironment.cs
  test/SlowTests/Voron/Issues/RavenDB_22767.cs
Labels: v5.4

#20390 RavenDB-23988 Logs configuration: Fix some descriptions
  src/Raven.Server/Config/Categories/LogsConfiguration.cs
Labels: v7.0
