Repository ravendb/ravendb, pull requests merged in 2025-10, with the labels that each got.

#21493 RavenDB-14548 Fixing deserialization problem with AlertRaised
  src/Raven.Server/NotificationCenter/Notifications/AlertRaised.cs
  src/Raven.Server/NotificationCenter/Notifications/Notification.cs
Labels: v6.2

#21503 RavenDB-19961 Reapplying PR #17962: Retrying a test which is ocassionally failing
  test/SlowTests/Issues/RavenDB_15930.cs
Labels: v6.2

#21481 RavenDB-25112 Fix checking Accept-Encoding and compressing files from directory in Studio
  src/Raven.Server/Web/RequestHandler.cs
  src/Raven.Server/Web/System/StudioHandler.cs
Labels: v6.2

#21508 7.0 to 7.1 merge
  src/Raven.Server/NotificationCenter/Notifications/AlertRaised.cs
  src/Raven.Server/NotificationCenter/Notifications/Notification.cs
  src/Raven.Server/Web/RequestHandler.cs
  src/Raven.Server/Web/System/StudioHandler.cs
  test/SlowTests.Issues/Issues/RavenDB_15930.cs
Labels: v7.1

#21509 RavenDB-25085 Test agent - wrong z-index
  src/Raven.Studio/typescript/components/pages/database/aiHub/aiAgents/edit/EditAiAgent.tsx
Labels: Studio, v7.1

#21519 RavenDB-25105 always include latest log if the name is static
  src/Raven.Server/Documents/Handlers/Admin/AdminLogsHandler.cs
  src/Raven.Server/Logging/RavenLogManagerServerExtensions.cs
Labels: v7.0

#21524 RavenDB-21091 Handle VoronConcurrencyErrorException during `put` executed from a patch when using "/" at the end of ID and a document with same ID already exists
  src/Raven.Server/Documents/Patch/ScriptRunner.cs
  test/SlowTests/Issues/RavenDB_21091.cs
Labels: v6.2

#21528 RavenDB-25125 Detection of Posix's ENOTSUP error code and throwing NotSupportedException then (same as on Windows). Better exception messages for OS native errors.
  src/Raven.Server/Utils/ExceptionHelper.cs
  src/Sparrow.Server/Platform/Pal.cs
  src/Sparrow.Server/Platform/PalHelper.cs
Labels: v8.0

#21536 RavenDB-25086 Allow to get tags with version only for docker images
  docker/build-nanoserver.ps1
  docker/build-ubuntu.ps1
  docker/common.ps1
  docker/publish-nanoserver.ps1
  docker/publish-ubuntu.ps1
Labels: v5.4

#21540 Merge 6.2 to 7.0
  docker/build-nanoserver.ps1
  docker/build-ubuntu.ps1
  docker/common.ps1
  docker/publish-nanoserver.ps1
  docker/publish-ubuntu.ps1
  src/Raven.Server/Documents/DocumentPutAction.cs
  src/Raven.Server/Documents/Handlers/Batches/Commands/MergedBatchCommand.cs
  src/Raven.Server/Documents/Handlers/DocumentHandler.cs
  src/Raven.Server/Documents/Handlers/Processors/BulkInsert/MergedInsertBulkCommand.cs
  src/Raven.Server/Documents/Patch/ScriptRunner.cs
  test/SlowTests/Issues/RavenDB_21091.cs
Labels: v7.0

#21547 RavenDB-25066 [6.2] Adjust menu for smaller resolutions
  src/Raven.Studio/wwwroot/Content/css/basic-layout.less
  src/Raven.Studio/wwwroot/Content/css/bootstrap/variables-body.less
  src/Raven.Studio/wwwroot/Content/css/root.less
  src/Raven.Studio/wwwroot/Content/scss/_main-menu.scss
  src/Raven.Studio/wwwroot/Content/scss/_variables.scss
Labels: v6.2, release
